wiNpoS: wiNpoS-Hook/HooksImpl.cpp File Reference
HooksImpl.cpp File Reference
#include "pch.h"
#include "DebugNew.h"
#include "HooksImpl.h"
#include "HooksMgr.h"
#include "HooksCfg.h"
#include "Utils.h"
#include "TaskToolbar.h"
#include <Shlwapi.h>
#include <windowsx.h>
#include <resource.h>
#include <assert.h>
#include <future>
Namespaces
namespace anonymous_namespace{HooksImpl.cpp}
‍the hooks config
Functions
LRESULT CALLBACK ShellHookProc (int nCode, WPARAM wParam, LPARAM lParam)
the exported hook for the shell procedure
LRESULT CALLBACK CallWndProc (_In_ int nCode, _In_ WPARAM wParam, _In_ LPARAM lParam)
the exported hook for the main window procedure
LRESULT CALLBACK GetMsgProc (_In_ int nCode, _In_ WPARAM wParam, _In_ LPARAM lParam)
the exported hook for the windows-message procedure
Variables
HINSTANCE hInstance
thread_local HRESULT coInit
thread_local TaskToolbar _thumbnailToolbar
thread_local HooksImpl _hooks
thread_local HooksCfgPtr _hooksCfg = std::make_unique<HooksCfg>()
const UINT anonymous_namespace{HooksImpl.cpp}::TI_LBUTTONUP = 0x40
ID from close timer.
const UINT anonymous_namespace{HooksImpl.cpp}::TI_NCLBUTTONUP = 0x50
Function Documentation
CallWndProc()
LRESULT CALLBACK CallWndProc (_In_ int nCode, _In_ WPARAM wParam, _In_ LPARAM lParam)
the exported hook for the main window procedure
Parameters
nCode
wParam
lParam
Returns
Definition at line 51 of file HooksImpl.cpp.
{
    if (_hooksCfg->isDisabled())
        return CallNextHookEx(NULL, nCode, wParam, lParam);
    return HooksImpl::callWndProc(nCode, wParam, lParam);
}
References _hooksCfg, HooksImpl::callWndProc(), and HooksCfg::isDisabled().
GetMsgProc()
LRESULT CALLBACK GetMsgProc (_In_ int nCode, _In_ WPARAM wParam, _In_ LPARAM lParam)
the exported hook for the windows-message procedure
Parameters
nCode
wParam
lParam
Returns
Definition at line 64 of file HooksImpl.cpp.
{
    if (_hooksCfg->isDisabled())
        return CallNextHookEx(NULL, nCode, wParam, lParam);
    return HooksImpl::getMsgProc(nCode, wParam, lParam);
}
References _hooksCfg, HooksImpl::getMsgProc(), and HooksCfg::isDisabled().
ShellHookProc()
LRESULT CALLBACK ShellHookProc (int nCode, WPARAM wParam, LPARAM lParam)
the exported hook for the shell procedure
Parameters
nCode
wParam
lParam
Returns
Definition at line 38 of file HooksImpl.cpp.
{
    if (_hooksCfg->isDisabled())
        return CallNextHookEx(NULL, nCode, wParam, lParam);
    return HooksImpl::shellHookProc(nCode, wParam, lParam);
}
References _hooksCfg, HooksCfg::isDisabled(), and HooksImpl::shellHookProc().
Variable Documentation
_hooks
thread_local HooksImpl _hooks
Definition at line 18 of file HooksImpl.cpp.
_hooksCfg
thread_local HooksCfgPtr _hooksCfg = std::make_unique<HooksCfg>()
Definition at line 19 of file HooksImpl.cpp.
_thumbnailToolbar
thread_local TaskToolbar _thumbnailToolbar
Definition at line 17 of file HooksImpl.cpp.
coInit
thread_local HRESULT coInit
Definition at line 15 of file HooksImpl.cpp.
hInstance
HINSTANCE hInstance extern
Definition at line 23 of file wiNpoS-App.cpp.