wiNpoS: testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator Class Reference
testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator Class Reference
Public Member Functions
Iterator (const ParamGeneratorInterface< T > *base, typename ContainerType::const_iterator iterator)
virtual ~Iterator ()
virtual const ParamGeneratorInterface< T > * BaseGenerator () const
virtual void Advance ()
virtual ParamIteratorInterface< T > * Clone () const
virtual const T * Current () const
virtual bool Equals (const ParamIteratorInterface< T > &other) const
Public Member Functions inherited from testing::internal::ParamIteratorInterface< T >
virtual ~ParamIteratorInterface ()
Private Member Functions
Iterator (const Iterator &other)
Private Attributes
const ParamGeneratorInterface< T > *const base_
ContainerType::const_iterator iterator_
scoped_ptr< const T > value_
Detailed Description
template<typename T>
class testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator
Definition at line 304 of file gtest-param-util.h.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename T > testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Iterator (const ParamGeneratorInterface< T > * base, typename ContainerType::const_iterator iterator) inline
Definition at line 306 of file gtest-param-util.h.
        : base_(base), iterator_(iterator) {}
~Iterator()
template<typename T > virtual testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::~Iterator () inline virtual
Definition at line 309 of file gtest-param-util.h.
{}
Iterator() [2/2]
template<typename T > testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Iterator (const Iterator & other) inline private
Definition at line 344 of file gtest-param-util.h.
        : ParamIteratorInterface<T>(),
          base_(other.base_),
          iterator_(other.iterator_) {}
Member Function Documentation
Advance()
template<typename T > virtual void testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Advance () inline virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 314 of file gtest-param-util.h.
{
      ++iterator_;
      value_.reset();
    }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_, testing::internal::scoped_ptr< T >::reset(), and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::value_.
BaseGenerator()
template<typename T > virtual const ParamGeneratorInterface< T > * testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::BaseGenerator () const inline virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 311 of file gtest-param-util.h.
{
      return base_;
    }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::base_.
Clone()
template<typename T > virtual ParamIteratorInterface< T > * testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Clone () const inline virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 318 of file gtest-param-util.h.
{
      return new Iterator(*this);
    }
Current()
template<typename T > virtual const T * testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Current () const inline virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 328 of file gtest-param-util.h.
{
      if (value_.get() == NULL)
        value_.reset(new T(*iterator_));
      return value_.get();
    }
References testing::internal::scoped_ptr< T >::get(), testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_, testing::internal::scoped_ptr< T >::reset(), T, and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::value_.
Equals()
template<typename T > virtual bool testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Equals (const ParamIteratorInterface< T > & other) const inline virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 333 of file gtest-param-util.h.
{
      // Having the same base generator guarantees that the other
      // iterator is of the same type and we can downcast.
      GTEST_CHECK_(BaseGenerator() == other.BaseGenerator())
          << "The program attempted to compare iterators "
          << "from different generators." << std::endl;
      return iterator_ ==
          CheckedDowncastToActualType<const Iterator>(&other)->iterator_;
    }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::BaseGenerator(), testing::internal::ParamIteratorInterface< T >::BaseGenerator(), GTEST_CHECK_, and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_.
Member Data Documentation
base_
template<typename T > const ParamGeneratorInterface<T>* const testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::base_ private
Definition at line 351 of file gtest-param-util.h.
iterator_
template<typename T > ContainerType::const_iterator testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_ private
Definition at line 352 of file gtest-param-util.h.
value_
template<typename T > scoped_ptr<const T> testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::value_ mutable private
Definition at line 358 of file gtest-param-util.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/include/gtest/internal/gtest-param-util.h