wiNpoS: testing::internal::XmlUnitTestResultPrinter Class Reference
testing::internal::XmlUnitTestResultPrinter Class Reference
Public Member Functions
XmlUnitTestResultPrinter (const char *output_file)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
Public Member Functions inherited from testing::EmptyTestEventListener
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter)
Static Private Member Functions
static bool IsNormalizableWhitespace (char c)
static bool IsValidXmlCharacter (char c)
static std::string EscapeXml (const std::string &str, bool is_attribute)
static std::string RemoveInvalidXmlCharacters (const std::string &str)
static std::string EscapeXmlAttribute (const std::string &str)
static std::string EscapeXmlText (const char *str)
static void OutputXmlAttribute (std::ostream *stream, const std::string &element_name, const std::string &name, const std::string &value)
static void OutputXmlCDataSection (::std::ostream *stream, const char *data)
static void OutputXmlTestInfo (::std::ostream *stream, const char *test_case_name, const TestInfo &test_info)
static void PrintXmlTestCase (::std::ostream *stream, const TestCase &test_case)
static void PrintXmlUnitTest (::std::ostream *stream, const UnitTest &unit_test)
static std::string TestPropertiesAsXmlAttributes (const TestResult &result)
static void OutputXmlTestProperties (std::ostream *stream, const TestResult &result)
Private Attributes
const std::string output_file_
Detailed Description
Definition at line 3392 of file gtest.cc.
Constructor & Destructor Documentation
XmlUnitTestResultPrinter()
testing::internal::XmlUnitTestResultPrinter::XmlUnitTestResultPrinter (const char * output_file) explicit
Definition at line 3470 of file gtest.cc.
    : output_file_(output_file) {
  if (output_file_.c_str() == NULL || output_file_.empty()) {
    GTEST_LOG_(FATAL) << "XML output file may not be null";
  }
}
References GTEST_LOG_, and output_file_.
Member Function Documentation
EscapeXml()
std::string testing::internal::XmlUnitTestResultPrinter::EscapeXml (const std::string & str, bool is_attribute) static private
Definition at line 3519 of file gtest.cc.
{
  Message m;
  for (size_t i = 0; i < str.size(); ++i) {
    const char ch = str[i];
    switch (ch) {
      case '<':
        m << "&lt;";
        break;
      case '>':
        m << "&gt;";
        break;
      case '&':
        m << "&amp;";
        break;
      case '\'':
        if (is_attribute)
          m << "&apos;";
        else
          m << '\'';
        break;
      case '"':
        if (is_attribute)
          m << "&quot;";
        else
          m << '"';
        break;
      default:
        if (IsValidXmlCharacter(ch)) {
          if (is_attribute && IsNormalizableWhitespace(ch))
            m << "&#x" << String::FormatByte(static_cast<unsigned char>(ch))
              << ";";
          else
            m << ch;
        }
        break;
    }
  }
  return m.GetString();
}
References testing::internal::String::FormatByte(), testing::Message::GetString(), IsNormalizableWhitespace(), and IsValidXmlCharacter().
EscapeXmlAttribute()
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlAttribute (const std::string & str) inline static private
Definition at line 3420 of file gtest.cc.
{
    return EscapeXml(str, true);
  }
References EscapeXml().
EscapeXmlText()
static std::string testing::internal::XmlUnitTestResultPrinter::EscapeXmlText (const char * str) inline static private
Definition at line 3425 of file gtest.cc.
{
    return EscapeXml(str, false);
  }
References EscapeXml().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::internal::XmlUnitTestResultPrinter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (XmlUnitTestResultPrinter) private
IsNormalizableWhitespace()
static bool testing::internal::XmlUnitTestResultPrinter::IsNormalizableWhitespace (char c) inline static private
Definition at line 3401 of file gtest.cc.
{
    return c == 0x9 || c == 0xA || c == 0xD;
  }
IsValidXmlCharacter()
static bool testing::internal::XmlUnitTestResultPrinter::IsValidXmlCharacter (char c) inline static private
Definition at line 3406 of file gtest.cc.
{
    return IsNormalizableWhitespace(c) || c >= 0x20;
  }
References IsNormalizableWhitespace().
OnTestIterationEnd()
void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 3478 of file gtest.cc.
{
  FILE* xmlout = NULL;
  FilePath output_file(output_file_);
  FilePath output_dir(output_file.RemoveFileName());
  if (output_dir.CreateDirectoriesRecursively()) {
    xmlout = posix::FOpen(output_file_.c_str(), "w");
  }
  if (xmlout == NULL) {
    // TODO(wan): report the reason of the failure.
    //
    // We don't do it for now as:
    //
    //   1. There is no urgent need for it.
    //   2. It's a bit involved to make the errno variable thread-safe on
    //      all three operating systems (Linux, Windows, and Mac OS).
    //   3. To interpret the meaning of errno in a thread-safe way,
    //      we need the strerror_r() function, which is not available on
    //      Windows.
    GTEST_LOG_(FATAL) << "Unable to open file \"" << output_file_ << "\"";
  }
  std::stringstream stream;
  PrintXmlUnitTest(&stream, unit_test);
  fprintf(xmlout, "%s", StringStreamToString(&stream).c_str());
  fclose(xmlout);
}
References testing::internal::posix::FOpen(), GTEST_LOG_, output_file_, PrintXmlUnitTest(), testing::internal::FilePath::RemoveFileName(), and testing::internal::StringStreamToString().
OutputXmlAttribute()
void testing::internal::XmlUnitTestResultPrinter::OutputXmlAttribute (std::ostream * stream, const std::string & element_name, const std::string & name, const std::string & value) static private
Definition at line 3650 of file gtest.cc.
{
  const std::vector<std::string>& allowed_names =
      GetReservedAttributesForElement(element_name);
  GTEST_CHECK_(std::find(allowed_names.begin(), allowed_names.end(), name) !=
                   allowed_names.end())
      << "Attribute " << name << " is not allowed for element <" << element_name
      << ">.";
  *stream << " " << name << "=\"" << EscapeXmlAttribute(value) << "\"";
}
References EscapeXmlAttribute(), testing::GetReservedAttributesForElement(), and GTEST_CHECK_.
OutputXmlCDataSection()
void testing::internal::XmlUnitTestResultPrinter::OutputXmlCDataSection (::std::ostream * stream, const char * data) static private
Definition at line 3631 of file gtest.cc.
{
  const char* segment = data;
  *stream << "<![CDATA[";
  for (;;) {
    const char* const next_segment = strstr(segment, "]]>");
    if (next_segment != NULL) {
      stream->write(
          segment, static_cast<std::streamsize>(next_segment - segment));
      *stream << "]]>]]&gt;<![CDATA[";
      segment = next_segment + strlen("]]>");
    } else {
      *stream << segment;
      break;
    }
  }
  *stream << "]]>";
}
OutputXmlTestInfo()
void testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo (::std::ostream * stream, const char * test_case_name, const TestInfo & test_info) static private
Definition at line 3668 of file gtest.cc.
{
  const TestResult& result = *test_info.result();
  const std::string kTestcase = "testcase";
  if (test_info.is_in_another_shard()) {
    return;
  }
  *stream << "    <testcase";
  OutputXmlAttribute(stream, kTestcase, "name", test_info.name());
  if (test_info.value_param() != NULL) {
    OutputXmlAttribute(stream, kTestcase, "value_param",
                       test_info.value_param());
  }
  if (test_info.type_param() != NULL) {
    OutputXmlAttribute(stream, kTestcase, "type_param", test_info.type_param());
  }
  OutputXmlAttribute(stream, kTestcase, "status",
                     test_info.should_run() ? "run" : "notrun");
  OutputXmlAttribute(stream, kTestcase, "time",
                     FormatTimeInMillisAsSeconds(result.elapsed_time()));
  OutputXmlAttribute(stream, kTestcase, "classname", test_case_name);
  int failures = 0;
  for (int i = 0; i < result.total_part_count(); ++i) {
    const TestPartResult& part = result.GetTestPartResult(i);
    if (part.failed()) {
      if (++failures == 1) {
        *stream << ">\n";
      }
      const std::string location =
          internal::FormatCompilerIndependentFileLocation(part.file_name(),
                                                          part.line_number());
      const std::string summary = location + "\n" + part.summary();
      *stream << "      <failure message=\""
              << EscapeXmlAttribute(summary.c_str())
              << "\" type=\"\">";
      const std::string detail = location + "\n" + part.message();
      OutputXmlCDataSection(stream, RemoveInvalidXmlCharacters(detail).c_str());
      *stream << "</failure>\n";
    }
  }
  if (failures == 0 && result.test_property_count() == 0) {
    *stream << " />\n";
  } else {
    if (failures == 0) {
      *stream << ">\n";
    }
    OutputXmlTestProperties(stream, result);
    *stream << "    </testcase>\n";
  }
}
References testing::TestResult::elapsed_time(), EscapeXmlAttribute(), testing::TestPartResult::failed(), testing::TestPartResult::file_name(), testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatTimeInMillisAsSeconds(), testing::TestResult::GetTestPartResult(), testing::TestInfo::is_in_another_shard(), testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), OutputXmlAttribute(), OutputXmlCDataSection(), OutputXmlTestProperties(), RemoveInvalidXmlCharacters(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestPartResult::summary(), testing::TestResult::test_property_count(), testing::TestResult::total_part_count(), testing::TestInfo::type_param(), and testing::TestInfo::value_param().
OutputXmlTestProperties()
void testing::internal::XmlUnitTestResultPrinter::OutputXmlTestProperties (std::ostream * stream, const TestResult & result) static private
Definition at line 3803 of file gtest.cc.
{
  const std::string kProperties = "properties";
  const std::string kProperty = "property";
  if (result.test_property_count() <= 0) {
    return;
  }
  *stream << "<" << kProperties << ">\n";
  for (int i = 0; i < result.test_property_count(); ++i) {
    const TestProperty& property = result.GetTestProperty(i);
    *stream << "<" << kProperty;
    *stream << " name=\"" << EscapeXmlAttribute(property.key()) << "\"";
    *stream << " value=\"" << EscapeXmlAttribute(property.value()) << "\"";
    *stream << "/>\n";
  }
  *stream << "</" << kProperties << ">\n";
}
References EscapeXmlAttribute(), testing::TestResult::GetTestProperty(), and testing::TestResult::test_property_count().
PrintXmlTestCase()
void testing::internal::XmlUnitTestResultPrinter::PrintXmlTestCase (::std::ostream * stream, const TestCase & test_case) static private
Definition at line 3727 of file gtest.cc.
{
  const std::string kTestsuite = "testsuite";
  *stream << "  <" << kTestsuite;
  OutputXmlAttribute(stream, kTestsuite, "name", test_case.name());
  OutputXmlAttribute(stream, kTestsuite, "tests",
                     StreamableToString(test_case.reportable_test_count()));
  OutputXmlAttribute(stream, kTestsuite, "failures",
                     StreamableToString(test_case.failed_test_count()));
  OutputXmlAttribute(
      stream, kTestsuite, "disabled",
      StreamableToString(test_case.reportable_disabled_test_count()));
  OutputXmlAttribute(stream, kTestsuite, "errors", "0");
  OutputXmlAttribute(stream, kTestsuite, "time",
                     FormatTimeInMillisAsSeconds(test_case.elapsed_time()));
  *stream << TestPropertiesAsXmlAttributes(test_case.ad_hoc_test_result())
          << ">\n";
  for (int i = 0; i < test_case.total_test_count(); ++i) {
    if (test_case.GetTestInfo(i)->is_reportable())
      OutputXmlTestInfo(stream, test_case.name(), *test_case.GetTestInfo(i));
  }
  *stream << "  </" << kTestsuite << ">\n";
}
References testing::TestCase::ad_hoc_test_result(), testing::TestCase::elapsed_time(), testing::TestCase::failed_test_count(), testing::internal::FormatTimeInMillisAsSeconds(), testing::TestCase::GetTestInfo(), testing::TestInfo::is_reportable(), testing::TestCase::name(), OutputXmlAttribute(), OutputXmlTestInfo(), testing::TestCase::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), testing::internal::StreamableToString(), TestPropertiesAsXmlAttributes(), and testing::TestCase::total_test_count().
PrintXmlUnitTest()
void testing::internal::XmlUnitTestResultPrinter::PrintXmlUnitTest (::std::ostream * stream, const UnitTest & unit_test) static private
Definition at line 3753 of file gtest.cc.
{
  const std::string kTestsuites = "testsuites";
  *stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
  *stream << "<" << kTestsuites;
  OutputXmlAttribute(stream, kTestsuites, "tests",
                     StreamableToString(unit_test.reportable_test_count()));
  OutputXmlAttribute(stream, kTestsuites, "failures",
                     StreamableToString(unit_test.failed_test_count()));
  OutputXmlAttribute(
      stream, kTestsuites, "disabled",
      StreamableToString(unit_test.reportable_disabled_test_count()));
  OutputXmlAttribute(stream, kTestsuites, "errors", "0");
  OutputXmlAttribute(
      stream, kTestsuites, "timestamp",
      FormatEpochTimeInMillisAsIso8601(unit_test.start_timestamp()));
  OutputXmlAttribute(stream, kTestsuites, "time",
                     FormatTimeInMillisAsSeconds(unit_test.elapsed_time()));
  if (GTEST_FLAG(shuffle)) {
    OutputXmlAttribute(stream, kTestsuites, "random_seed",
                       StreamableToString(unit_test.random_seed()));
  }
  *stream << TestPropertiesAsXmlAttributes(unit_test.ad_hoc_test_result());
  OutputXmlAttribute(stream, kTestsuites, "name", "AllTests");
  *stream << ">\n";
  for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
    if (unit_test.GetTestCase(i)->reportable_test_count() > 0)
      PrintXmlTestCase(stream, *unit_test.GetTestCase(i));
  }
  *stream << "</" << kTestsuites << ">\n";
}
References testing::UnitTest::ad_hoc_test_result(), testing::UnitTest::elapsed_time(), testing::UnitTest::failed_test_count(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::FormatTimeInMillisAsSeconds(), testing::UnitTest::GetTestCase(), GTEST_FLAG, OutputXmlAttribute(), PrintXmlTestCase(), testing::UnitTest::random_seed(), testing::UnitTest::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), testing::UnitTest::reportable_test_count(), testing::UnitTest::start_timestamp(), testing::internal::StreamableToString(), TestPropertiesAsXmlAttributes(), and testing::UnitTest::total_test_case_count().
RemoveInvalidXmlCharacters()
std::string testing::internal::XmlUnitTestResultPrinter::RemoveInvalidXmlCharacters (const std::string & str) static private
Definition at line 3565 of file gtest.cc.
{
  std::string output;
  output.reserve(str.size());
  for (std::string::const_iterator it = str.begin(); it != str.end(); ++it)
    if (IsValidXmlCharacter(*it))
      output.push_back(*it);
  return output;
}
References IsValidXmlCharacter().
TestPropertiesAsXmlAttributes()
std::string testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes (const TestResult & result) static private
Definition at line 3792 of file gtest.cc.
{
  Message attributes;
  for (int i = 0; i < result.test_property_count(); ++i) {
    const TestProperty& property = result.GetTestProperty(i);
    attributes << " " << property.key() << "="
        << "\"" << EscapeXmlAttribute(property.value()) << "\"";
  }
  return attributes.GetString();
}
References EscapeXmlAttribute(), testing::Message::GetString(), testing::TestResult::GetTestProperty(), and testing::TestResult::test_property_count().
Member Data Documentation
output_file_
const std::string testing::internal::XmlUnitTestResultPrinter::output_file_ private
Definition at line 3464 of file gtest.cc.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/src/gtest.cc