wiNpoS: testing::ScopedTrace Class Reference
testing::ScopedTrace Class Reference
Public Member Functions
template<typename T >
ScopedTrace (const char *file, int line, const T &message)
ScopedTrace (const char *file, int line, const char *message)
ScopedTrace (const char *file, int line, const std::string &message)
~ScopedTrace ()
Private Member Functions
void PushTrace (const char *file, int line, std::string message)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace)
Detailed Description
Definition at line 2146 of file gtest.h.
Constructor & Destructor Documentation
ScopedTrace() [1/3]
template<typename T > testing::ScopedTrace::ScopedTrace (const char * file, int line, const T & message) inline
Definition at line 2154 of file gtest.h.
{
    PushTrace(file, line, (Message() << message).GetString());
  }
References GetString().
ScopedTrace() [2/3]
testing::ScopedTrace::ScopedTrace (const char * file, int line, const char * message) inline
Definition at line 2159 of file gtest.h.
{
    PushTrace(file, line, message ? message : "(null)");
  }
ScopedTrace() [3/3]
testing::ScopedTrace::ScopedTrace (const char * file, int line, const std::string & message) inline
Definition at line 2169 of file gtest.h.
{
    PushTrace(file, line, message);
  }
~ScopedTrace()
testing::ScopedTrace::~ScopedTrace ()
Definition at line 5841 of file gtest.cc.
{
  UnitTest::GetInstance()->PopGTestTrace();
}
References testing::UnitTest::GetInstance(), and testing::UnitTest::PopGTestTrace().
Member Function Documentation
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::ScopedTrace::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedTrace) private
PushTrace()
void testing::ScopedTrace::PushTrace (const char * file, int line, std::string message) private
Definition at line 5831 of file gtest.cc.
{
  internal::TraceInfo trace;
  trace.file = file;
  trace.line = line;
  trace.message.swap(message);
  UnitTest::GetInstance()->PushGTestTrace(trace);
}
References testing::internal::TraceInfo::file, testing::UnitTest::GetInstance(), testing::internal::TraceInfo::line, testing::internal::TraceInfo::message, and testing::UnitTest::PushGTestTrace().
The documentation for this class was generated from the following files:
rapidjson/thirdparty/gtest/googletest/include/gtest/gtest.h
rapidjson/thirdparty/gtest/googletest/src/gtest.cc