wiNpoS: anonymous_namespace{gtest_unittest.cc}::UnitTestRecordPropertyTest Class Reference
anonymous_namespace{gtest_unittest.cc}::UnitTestRecordPropertyTest Class Reference
Static Public Member Functions
static void SetUpTestCase ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
Protected Member Functions inherited from testing::internal::UnitTestRecordPropertyTestHelper
UnitTestRecordPropertyTestHelper ()
void UnitTestRecordProperty (const char *key, const std::string &value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes inherited from testing::internal::UnitTestRecordPropertyTestHelper
UnitTest unit_test_
Detailed Description
Definition at line 1998 of file gtest_unittest.cc.
Member Function Documentation
SetUpTestCase()
static void anonymous_namespace{gtest_unittest.cc}::UnitTestRecordPropertyTest::SetUpTestCase () inline static
Definition at line 2001 of file gtest_unittest.cc.
{
    ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(
        "disabled");
    ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(
        "errors");
    ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(
        "failures");
    ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(
        "name");
    ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(
        "tests");
    ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(
        "time");
    Test::RecordProperty("test_case_key_1", "1");
    const TestCase* test_case = UnitTest::GetInstance()->current_test_case();
    ASSERT_TRUE(test_case != NULL);
    ASSERT_EQ(1, test_case->ad_hoc_test_result().test_property_count());
    EXPECT_STREQ("test_case_key_1",
                 test_case->ad_hoc_test_result().GetTestProperty(0).key());
    EXPECT_STREQ("1",
                 test_case->ad_hoc_test_result().GetTestProperty(0).value());
  }
References testing::TestCase::ad_hoc_test_result(), ASSERT_EQ, ASSERT_TRUE, EXPECT_STREQ, anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(), testing::TestResult::GetTestProperty(), testing::TestProperty::key(), testing::TestResult::test_property_count(), and testing::TestProperty::value().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest_unittest.cc