wiNpoS: HooksMgr Class Reference
HooksMgr Class Reference
Manage the Hooks install / uninstall.
#include <HooksMgr.h>
Public Member Functions
HooksMgr ()=default
~HooksMgr ()=default
void loadHook ()
void unloadHook ()
void attach ()
void setHooks (HMODULE hModule)
void detach ()
void unhookHooks ()
void install ()
void uninstall ()
void startOtherBitInstance ()
void stopOtherBitInstance ()
Static Public Member Functions
static HMODULE load ()
static void unloadHook (HMODULE hModule)
Private Attributes
HMODULE _hModule = NULL
HHOOK _hhkShellHookProc = NULL
HHOOK _hhkCallWndProc = NULL
HHOOK _hhkGetMessage = NULL
PROCESS_INFORMATION _childProcessInfo = { 0 }
Detailed Description
Manage the Hooks install / uninstall.
Definition at line 16 of file HooksMgr.h.
Constructor & Destructor Documentation
HooksMgr()
HooksMgr::HooksMgr () default
~HooksMgr()
HooksMgr::~HooksMgr () default
Member Function Documentation
attach()
void HooksMgr::attach ()
Definition at line 52 of file HooksMgr.cpp.
{
    _hModule = load();
    setHooks(_hModule);
}
References _hModule, load(), and setHooks().
detach()
void HooksMgr::detach ()
Definition at line 80 of file HooksMgr.cpp.
{
    unhookHooks();
    unloadHook(_hModule);
}
References _hModule, unhookHooks(), and unloadHook().
install()
void HooksMgr::install ()
Definition at line 108 of file HooksMgr.cpp.
{
    _hModule = load();
    //HOOKPROC hkShellHookProc = (HOOKPROC)GetProcAddress(_hModule, STRINGIZE(ShellHookProc));
    //assert(hkShellHookProc);
    HOOKPROC hkCallWndProc = (HOOKPROC)GetProcAddress(_hModule, STRINGIZE(CallWndProc));
    AssertTrue(hkCallWndProc, "Procedure adress should not be NULL");
    HOOKPROC hkGetMsgProc = (HOOKPROC)GetProcAddress(_hModule, STRINGIZE(GetMsgProc));
    AssertTrue(hkGetMsgProc, "Procedure adress should not be NULL");
    //_hhkShellHookProc = SetWindowsHookEx(WH_SHELL, hkShellHookProc, _hModule, NULL);
    //assert(_hhkShellHookProc);
    _hhkCallWndProc = SetWindowsHookEx(WH_CALLWNDPROC, hkCallWndProc, _hModule, NULL);
    AssertTrue(_hhkCallWndProc, "Hook handle should not be NULL");
    _hhkGetMessage = SetWindowsHookEx(WH_GETMESSAGE, hkGetMsgProc, _hModule, NULL);
    AssertTrue(_hhkGetMessage, "Hook handle should not be NULL");
}
References _hhkCallWndProc, _hhkGetMessage, _hModule, AssertTrue, CallWndProc(), GetMsgProc(), load(), and STRINGIZE.
load()
HMODULE HooksMgr::load () static
Returns
Definition at line 12 of file HooksMgr.cpp.
{
    HMODULE hModule = NULL;
#ifdef _WIN64
    hModule = LoadLibrary(L"wiNpoS-Hook64.dll");
#else
    hModule = LoadLibrary(L"wiNpoS-Hook32.dll");
#endif // _WIN64
    return hModule;
}
loadHook()
void HooksMgr::loadHook ()
Definition at line 36 of file HooksMgr.cpp.
{
    _hModule = load();
}
References _hModule, and load().
setHooks()
void HooksMgr::setHooks (HMODULE hModule)
Parameters
hModule
Definition at line 62 of file HooksMgr.cpp.
{
    HOOKPROC hkCallWndProc = (HOOKPROC)GetProcAddress(hModule, STRINGIZE(CallWndProc));
    AssertTrue(hkCallWndProc, "Procedure adress should not be NULL");
    HOOKPROC hkGetMsgProc = (HOOKPROC)GetProcAddress(hModule, STRINGIZE(GetMsgProc));
    AssertTrue(hkGetMsgProc, "Procedure adress should not be NULL");
    _hhkCallWndProc = SetWindowsHookEx(WH_CALLWNDPROC, hkCallWndProc, NULL, GetCurrentThreadId());
    AssertTrue(_hhkCallWndProc, "Hook handle should not be NULL");
    _hhkGetMessage = SetWindowsHookEx(WH_GETMESSAGE, hkGetMsgProc, NULL, GetCurrentThreadId());
    AssertTrue(_hhkGetMessage, "Hook handle should not be NULL");
}
References _hhkCallWndProc, _hhkGetMessage, AssertTrue, CallWndProc(), GetMsgProc(), and STRINGIZE.
startOtherBitInstance()
void HooksMgr::startOtherBitInstance ()
Definition at line 161 of file HooksMgr.cpp.
{
    using std::regex;
    using std::regex_replace;
#ifdef _WIN64
    string exeName = regex_replace(Utils::ExeName, regex("64"), "32");
#else
    string exeName = regex_replace(Utils::ExeName, regex("32"), "64");
#endif // _WIN64
    char exePath[MAX_PATH] = { 0 };
    strcpy_s(exePath, Utils::BinDir.c_str());
    PathAppendA(exePath, exeName.c_str());
    DWORD fileAttributes = GetFileAttributesA(exePath);
    if (fileAttributes != INVALID_FILE_ATTRIBUTES && !(fileAttributes & FILE_ATTRIBUTE_DIRECTORY))
    {
        stopOtherBitInstance();
        STARTUPINFOA si = { sizeof(STARTUPINFO), 0 };
        char arguments[MAX_PATH] = "-no-tray";
        // Create the child process
        BOOL succeed = CreateProcessA(
            exePath,                         // Replace with the actual child process name or path
            arguments,                   // Command line (optional)
            NULL,                            // Process handle not inheritable
            NULL,                            // Thread handle not inheritable
            FALSE,                       // Set handle inheritance to FALSE
            0,                               // No creation flags
            NULL,                            // Use parent's environment block
            NULL,                            // Use parent's starting directory
            &si,                             // Pointer to STARTUPINFO structure
            &_childProcessInfo       // Pointer to PROCESS_INFORMATION structure
        );
    }
}
References _childProcessInfo, Utils::BinDir, Utils::ExeName, and stopOtherBitInstance().
stopOtherBitInstance()
void HooksMgr::stopOtherBitInstance ()
Definition at line 197 of file HooksMgr.cpp.
{
    if (_childProcessInfo.hThread)
    {
        BOOL succeed = PostThreadMessageA(GetThreadId(_childProcessInfo.hThread), WM_QUIT, 0, 0);
        CloseHandle(_childProcessInfo.hProcess);
        CloseHandle(_childProcessInfo.hThread);
        _childProcessInfo = { 0 };
    }
}
References _childProcessInfo.
unhookHooks()
void HooksMgr::unhookHooks ()
Definition at line 90 of file HooksMgr.cpp.
{
    if (_hhkGetMessage && UnhookWindowsHookEx(_hhkGetMessage))
        _hhkGetMessage = NULL;
    AssertTrue(_hhkGetMessage == NULL, "Hook handle should be NULL");
    if (_hhkCallWndProc && UnhookWindowsHookEx(_hhkCallWndProc))
        _hhkCallWndProc = NULL;
    AssertTrue(_hhkCallWndProc == NULL, "Hook handle should be NULL");
    //if (_hhkShellHookProc && UnhookWindowsHookEx(_hhkShellHookProc))
    //  _hhkShellHookProc = NULL;
    //assert(_hhkShellHookProc == NULL);
}
References _hhkCallWndProc, _hhkGetMessage, and AssertTrue.
uninstall()
void HooksMgr::uninstall ()
Definition at line 134 of file HooksMgr.cpp.
{
    unhookHooks();
    //PostMessage(HWND_BROADCAST, MT_HOOK_MSG_UNLOAD, NULL, NULL);
    //detach();
}
References unhookHooks().
unloadHook() [1/2]
void HooksMgr::unloadHook ()
Definition at line 44 of file HooksMgr.cpp.
{
    unloadHook(_hModule);
}
References _hModule, and unloadHook().
unloadHook() [2/2]
void HooksMgr::unloadHook (HMODULE hModule) static
Parameters
hModule
Definition at line 27 of file HooksMgr.cpp.
{
    BOOL libraryFreed = FreeLibrary(hModule);
    AssertTrue(libraryFreed, "Library not freed");
}
References AssertTrue.
Member Data Documentation
_childProcessInfo
PROCESS_INFORMATION HooksMgr::_childProcessInfo = { 0 } private
Definition at line 27 of file HooksMgr.h.
{ 0 };
_hhkCallWndProc
HHOOK HooksMgr::_hhkCallWndProc = NULL private
Definition at line 25 of file HooksMgr.h.
_hhkGetMessage
HHOOK HooksMgr::_hhkGetMessage = NULL private
Definition at line 26 of file HooksMgr.h.
_hhkShellHookProc
HHOOK HooksMgr::_hhkShellHookProc = NULL private
Definition at line 24 of file HooksMgr.h.
_hModule
HMODULE HooksMgr::_hModule = NULL private
Definition at line 23 of file HooksMgr.h.
The documentation for this class was generated from the following files:
wiNpoS-Shared/HooksMgr.h
wiNpoS-Shared/HooksMgr.cpp