wiNpoS: testing::internal::FunctionMockerBase< F > Class Template Reference
testing::internal::FunctionMockerBase< F > Class Template Reference
Public Types
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
Public Member Functions
FunctionMockerBase ()
virtual ~FunctionMockerBase () GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const OnCallSpec< F > * FindOnCallSpec (const ArgumentTuple &args) const
Result PerformDefaultAction (typename RvalueRef< typename Function< F >::ArgumentTuple >::type args, const std::string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (void *untyped_args, const std::string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, void *untyped_args) const
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
Public Member Functions inherited from testing::internal::UntypedFunctionMockerBase
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedActionResultHolderBase * UntypedInvokeWith (void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Protected Types
typedef ActionResultHolder< Result > ResultHolder
Protected Types inherited from testing::internal::UntypedFunctionMockerBase
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
Protected Member Functions
Result InvokeWith (typename RvalueRef< typename Function< F >::ArgumentTuple >::type args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
OnCallSpec< F > & AddNewOnCallSpec (const char *file, int line, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
TypedExpectation< F > & AddNewExpectation (const char *file, int line, const std::string &source_text, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Protected Member Functions inherited from testing::internal::UntypedFunctionMockerBase
Expectation GetHandleOf (ExpectationBase *exp)
Private Member Functions
void DescribeDefaultActionTo (const ArgumentTuple &args, ::std::ostream *os) const
virtual void UntypedDescribeUninterestingCall (const void *untyped_args, ::std::ostream *os) const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
virtual const ExpectationBase * UntypedFindMatchingExpectation (const void *untyped_args, const void **untyped_action, bool *is_excessive, ::std::ostream *what, ::std::ostream *why) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
virtual void UntypedPrintArgs (const void *untyped_args, ::std::ostream *os) const
TypedExpectation< F > * FindMatchingExpectationLocked (const ArgumentTuple &args) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FormatUnexpectedCallMessageLocked (const ArgumentTuple &args, ::std::ostream *os, ::std::ostream *why) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void PrintTriedExpectationsLocked (const ArgumentTuple &args, ::std::ostream *why) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
GTEST_DISALLOW_COPY_AND_ASSIGN_ (FunctionMockerBase)
Friends
template<typename Function >
class MockSpec
template<typename Func >
class TypedExpectation
Additional Inherited Members
Protected Attributes inherited from testing::internal::UntypedFunctionMockerBase
const void * mock_obj_
const char * name_
UntypedOnCallSpecs untyped_on_call_specs_
UntypedExpectations untyped_expectations_
Detailed Description
template<typename F>
class testing::internal::FunctionMockerBase< F >
Definition at line 1469 of file gmock-spec-builders.h.
Member Typedef Documentation
ArgumentMatcherTuple
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::FunctionMockerBase< F >::ArgumentMatcherTuple
Definition at line 1473 of file gmock-spec-builders.h.
ArgumentTuple
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::FunctionMockerBase< F >::ArgumentTuple
Definition at line 1472 of file gmock-spec-builders.h.
Result
template<typename F > typedef Function<F>::Result testing::internal::FunctionMockerBase< F >::Result
Definition at line 1471 of file gmock-spec-builders.h.
ResultHolder
template<typename F > typedef ActionResultHolder<Result> testing::internal::FunctionMockerBase< F >::ResultHolder protected
Definition at line 1591 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
FunctionMockerBase()
template<typename F > testing::internal::FunctionMockerBase< F >::FunctionMockerBase () inline
Definition at line 1475 of file gmock-spec-builders.h.
{}
~FunctionMockerBase()
template<typename F > virtual testing::internal::FunctionMockerBase< F >::~FunctionMockerBase () inline virtual
Definition at line 1480 of file gmock-spec-builders.h.
{
    MutexLock l(&g_gmock_mutex);
    VerifyAndClearExpectationsLocked();
    Mock::UnregisterLocked(this);
    ClearDefaultActionsLocked();
  }
Member Function Documentation
AddNewExpectation()
template<typename F > TypedExpectation< F > & testing::internal::FunctionMockerBase< F >::AddNewExpectation (const char * file, int line, const std::string & source_text, const ArgumentMatcherTuple & m) inline protected
Definition at line 1619 of file gmock-spec-builders.h.
{
    Mock::RegisterUseByOnCallOrExpectCall(MockObject(), file, line);
    TypedExpectation<F>* const expectation =
        new TypedExpectation<F>(this, file, line, source_text, m);
    const linked_ptr<ExpectationBase> untyped_expectation(expectation);
    // See the definition of untyped_expectations_ for why access to
    // it is unprotected here.
    untyped_expectations_.push_back(untyped_expectation);
    // Adds this expectation into the implicit sequence if there is one.
    Sequence* const implicit_sequence = g_gmock_implicit_sequence.get();
    if (implicit_sequence != NULL) {
      implicit_sequence->AddExpectation(Expectation(untyped_expectation));
    }
    return *expectation;
  }
References testing::Sequence::AddExpectation(), and testing::internal::g_gmock_implicit_sequence.
AddNewOnCallSpec()
template<typename F > OnCallSpec< F > & testing::internal::FunctionMockerBase< F >::AddNewOnCallSpec (const char * file, int line, const ArgumentMatcherTuple & m) inline protected
Definition at line 1608 of file gmock-spec-builders.h.
{
    Mock::RegisterUseByOnCallOrExpectCall(MockObject(), file, line);
    OnCallSpec<F>* const on_call_spec = new OnCallSpec<F>(file, line, m);
    untyped_on_call_specs_.push_back(on_call_spec);
    return *on_call_spec;
  }
ClearDefaultActionsLocked()
template<typename F > virtual void testing::internal::FunctionMockerBase< F >::ClearDefaultActionsLocked () inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
Definition at line 1561 of file gmock-spec-builders.h.
{
    g_gmock_mutex.AssertHeld();
    // Deleting our default actions may trigger other mock objects to be
    // deleted, for example if an action contains a reference counted smart
    // pointer to that mock object, and that is the last reference. So if we
    // delete our actions within the context of the global mutex we may deadlock
    // when this method is called again. Instead, make a copy of the set of
    // actions to delete, clear our set within the mutex, and then delete the
    // actions outside of the mutex.
    UntypedOnCallSpecs specs_to_delete;
    untyped_on_call_specs_.swap(specs_to_delete);
    g_gmock_mutex.Unlock();
    for (UntypedOnCallSpecs::const_iterator it =
             specs_to_delete.begin();
         it != specs_to_delete.end(); ++it) {
      delete static_cast<const OnCallSpec<F>*>(*it);
    }
    // Lock the mutex again, since the caller expects it to be locked when we
    // return.
    g_gmock_mutex.Lock();
  }
DescribeDefaultActionTo()
template<typename F > void testing::internal::FunctionMockerBase< F >::DescribeDefaultActionTo (const ArgumentTuple & args, ::std::ostream * os) const inline private
Definition at line 1648 of file gmock-spec-builders.h.
{
    const OnCallSpec<F>* const spec = FindOnCallSpec(args);
    if (spec == NULL) {
      *os << (internal::type_equals<Result, void>::value ?
              "returning directly.\n" :
              "returning default value.\n");
    } else {
      *os << "taking default action specified at:\n"
          << FormatFileLocation(spec->file(), spec->line()) << "\n";
    }
  }
References testing::internal::UntypedOnCallSpecBase::file(), testing::internal::FormatFileLocation(), and testing::internal::UntypedOnCallSpecBase::line().
FindMatchingExpectationLocked()
template<typename F > TypedExpectation< F > * testing::internal::FunctionMockerBase< F >::FindMatchingExpectationLocked (const ArgumentTuple & args) const inline private
Definition at line 1728 of file gmock-spec-builders.h.
{
    g_gmock_mutex.AssertHeld();
    // See the definition of untyped_expectations_ for why access to
    // it is unprotected here.
    for (typename UntypedExpectations::const_reverse_iterator it =
             untyped_expectations_.rbegin();
         it != untyped_expectations_.rend(); ++it) {
      TypedExpectation<F>* const exp =
          static_cast<TypedExpectation<F>*>(it->get());
      if (exp->ShouldHandleArguments(args)) {
        return exp;
      }
    }
    return NULL;
  }
References testing::internal::TypedExpectation< F >::ShouldHandleArguments().
FindOnCallSpec()
template<typename F > const OnCallSpec< F > * testing::internal::FunctionMockerBase< F >::FindOnCallSpec (const ArgumentTuple & args) const inline
Definition at line 1491 of file gmock-spec-builders.h.
{
    for (UntypedOnCallSpecs::const_reverse_iterator it
             = untyped_on_call_specs_.rbegin();
         it != untyped_on_call_specs_.rend(); ++it) {
      const OnCallSpec<F>* spec = static_cast<const OnCallSpec<F>*>(*it);
      if (spec->Matches(args))
        return spec;
    }
    return NULL;
  }
References testing::internal::OnCallSpec< F >::Matches().
FormatUnexpectedCallMessageLocked()
template<typename F > void testing::internal::FunctionMockerBase< F >::FormatUnexpectedCallMessageLocked (const ArgumentTuple & args, ::std::ostream * os, ::std::ostream * why) const inline private
Definition at line 1747 of file gmock-spec-builders.h.
{
    g_gmock_mutex.AssertHeld();
    *os << "\nUnexpected mock function call - ";
    DescribeDefaultActionTo(args, os);
    PrintTriedExpectationsLocked(args, why);
  }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
template<typename F > testing::internal::FunctionMockerBase< F >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (FunctionMockerBase< F >) private
InvokeWith()
template<typename F > Result testing::internal::FunctionMockerBase< F >::InvokeWith (typename RvalueRef< typename Function< F >::ArgumentTuple >::type args) inline protected
Definition at line 1596 of file gmock-spec-builders.h.
{
    // const_cast is required since in C++98 we still pass ArgumentTuple around
    // by const& instead of rvalue reference.
    void* untyped_args = const_cast<void*>(static_cast<const void*>(&args));
    scoped_ptr<ResultHolder> holder(
        DownCast_<ResultHolder*>(this->UntypedInvokeWith(untyped_args)));
    return holder->Unwrap();
  }
PerformDefaultAction()
template<typename F > Result testing::internal::FunctionMockerBase< F >::PerformDefaultAction (typename RvalueRef< typename Function< F >::ArgumentTuple >::type args, const std::string & call_description) const inline
Definition at line 1511 of file gmock-spec-builders.h.
{
    const OnCallSpec<F>* const spec =
        this->FindOnCallSpec(args);
    if (spec != NULL) {
      return spec->GetAction().Perform(internal::move(args));
    }
    const std::string message =
        call_description +
        "\n    The mock function has no default action "
        "set, and its return type has no default value set.";
#if GTEST_HAS_EXCEPTIONS
    if (!DefaultValue<Result>::Exists()) {
      throw std::runtime_error(message);
    }
#else
    Assert(DefaultValue<Result>::Exists(), "", -1, message);
#endif
    return DefaultValue<Result>::Get();
  }
References testing::internal::Assert(), and testing::internal::OnCallSpec< F >::GetAction().
PrintTriedExpectationsLocked()
template<typename F > void testing::internal::FunctionMockerBase< F >::PrintTriedExpectationsLocked (const ArgumentTuple & args, ::std::ostream * why) const inline private
Definition at line 1760 of file gmock-spec-builders.h.
{
    g_gmock_mutex.AssertHeld();
    const int count = static_cast<int>(untyped_expectations_.size());
    *why << "Google Mock tried the following " << count << " "
         << (count == 1 ? "expectation, but it didn't match" :
             "expectations, but none matched")
         << ":\n";
    for (int i = 0; i < count; i++) {
      TypedExpectation<F>* const expectation =
          static_cast<TypedExpectation<F>*>(untyped_expectations_[i].get());
      *why << "\n";
      expectation->DescribeLocationTo(why);
      if (count > 1) {
        *why << "tried expectation #" << i << ": ";
      }
      *why << expectation->source_text() << "...\n";
      expectation->ExplainMatchResultTo(args, why);
      expectation->DescribeCallCountTo(why);
    }
  }
References testing::internal::ExpectationBase::DescribeCallCountTo(), testing::internal::ExpectationBase::DescribeLocationTo(), testing::internal::TypedExpectation< F >::ExplainMatchResultTo(), and testing::internal::ExpectationBase::source_text().
UntypedDescribeUninterestingCall()
template<typename F > virtual void testing::internal::FunctionMockerBase< F >::UntypedDescribeUninterestingCall (const void * untyped_args, ::std::ostream * os) const inline private virtual
Implements testing::internal::UntypedFunctionMockerBase.
Definition at line 1665 of file gmock-spec-builders.h.
{
    const ArgumentTuple& args =
        *static_cast<const ArgumentTuple*>(untyped_args);
    *os << "Uninteresting mock function call - ";
    DescribeDefaultActionTo(args, os);
    *os << "    Function call: " << Name();
    UniversalPrint(args, os);
  }
References testing::internal::UniversalPrint().
UntypedFindMatchingExpectation()
template<typename F > virtual const ExpectationBase * testing::internal::FunctionMockerBase< F >::UntypedFindMatchingExpectation (const void * untyped_args, const void ** untyped_action, bool * is_excessive, ::std::ostream * what, ::std::ostream * why) inline private virtual
Implements testing::internal::UntypedFunctionMockerBase.
Definition at line 1693 of file gmock-spec-builders.h.
{
    const ArgumentTuple& args =
        *static_cast<const ArgumentTuple*>(untyped_args);
    MutexLock l(&g_gmock_mutex);
    TypedExpectation<F>* exp = this->FindMatchingExpectationLocked(args);
    if (exp == NULL) {  // A match wasn't found.
      this->FormatUnexpectedCallMessageLocked(args, what, why);
      return NULL;
    }
    // This line must be done before calling GetActionForArguments(),
    // which will increment the call count for *exp and thus affect
    // its saturation status.
    *is_excessive = exp->IsSaturated();
    const Action<F>* action = exp->GetActionForArguments(this, args, what, why);
    if (action != NULL && action->IsDoDefault())
      action = NULL;  // Normalize "do default" to NULL.
    *untyped_action = action;
    return exp;
  }
References testing::internal::TypedExpectation< F >::GetActionForArguments(), and testing::internal::ExpectationBase::IsSaturated().
UntypedPerformAction()
template<typename F > virtual UntypedActionResultHolderBase * testing::internal::FunctionMockerBase< F >::UntypedPerformAction (const void * untyped_action, void * untyped_args) const inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
Definition at line 1550 of file gmock-spec-builders.h.
{
    // Make a copy of the action before performing it, in case the
    // action deletes the mock object (and thus deletes itself).
    const Action<F> action = *static_cast<const Action<F>*>(untyped_action);
    ArgumentTuple* args = static_cast<ArgumentTuple*>(untyped_args);
    return ResultHolder::PerformAction(action, internal::move(*args));
  }
UntypedPerformDefaultAction()
template<typename F > virtual UntypedActionResultHolderBase * testing::internal::FunctionMockerBase< F >::UntypedPerformDefaultAction (void * untyped_args, const std::string & call_description) const inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
Definition at line 1538 of file gmock-spec-builders.h.
{
    ArgumentTuple* args = static_cast<ArgumentTuple*>(untyped_args);
    return ResultHolder::PerformDefaultAction(this, internal::move(*args),
                                              call_description);
  }
UntypedPrintArgs()
template<typename F > virtual void testing::internal::FunctionMockerBase< F >::UntypedPrintArgs (const void * untyped_args, ::std::ostream * os) const inline private virtual
Implements testing::internal::UntypedFunctionMockerBase.
Definition at line 1719 of file gmock-spec-builders.h.
{
    const ArgumentTuple& args =
        *static_cast<const ArgumentTuple*>(untyped_args);
    UniversalPrint(args, os);
  }
References testing::internal::UniversalPrint().
Friends And Related Symbol Documentation
MockSpec
template<typename F > template<typename Function > friend class MockSpec friend
Definition at line 1589 of file gmock-spec-builders.h.
TypedExpectation
template<typename F > template<typename Func > friend class TypedExpectation friend
Definition at line 1641 of file gmock-spec-builders.h.
The documentation for this class was generated from the following files:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-generated-function-mockers.h
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-spec-builders.h