wiNpoS: rapidjson::GenericObject< Const, ValueT > Class Template Reference
rapidjson::GenericObject< Const, ValueT > Class Template Reference
Helper class for accessing Value of object type.
#include <document.h>
Public Types
typedef GenericObject< true, ValueT > ConstObject
typedef GenericObject< false, ValueT > Object
typedef ValueT PlainType
typedef internal::MaybeAddConst< Const, PlainType >::Type ValueType
typedef GenericMemberIterator< Const, typename ValueT::EncodingType, typename ValueT::AllocatorType > MemberIterator
typedef GenericMemberIterator< true, typename ValueT::EncodingType, typename ValueT::AllocatorType > ConstMemberIterator
typedef ValueType::AllocatorType AllocatorType
typedef ValueType::StringRefType StringRefType
typedef ValueType::EncodingType EncodingType
typedef ValueType::Ch Ch
Public Member Functions
GenericObject (const GenericObject &rhs)
GenericObject & operator= (const GenericObject &rhs)
~GenericObject ()
operator ValueType & () const
SizeType MemberCount () const
SizeType MemberCapacity () const
bool ObjectEmpty () const
template<typename T >
ValueType & operator[] (T *name) const
template<typename SourceAllocator >
ValueType & operator[] (const GenericValue< EncodingType, SourceAllocator > &name) const
MemberIterator MemberBegin () const
MemberIterator MemberEnd () const
GenericObject MemberReserve (SizeType newCapacity, AllocatorType &allocator) const
bool HasMember (const Ch *name) const
template<typename SourceAllocator >
bool HasMember (const GenericValue< EncodingType, SourceAllocator > &name) const
MemberIterator FindMember (const Ch *name) const
template<typename SourceAllocator >
MemberIterator FindMember (const GenericValue< EncodingType, SourceAllocator > &name) const
GenericObject AddMember (ValueType &name, ValueType &value, AllocatorType &allocator) const
GenericObject AddMember (ValueType &name, StringRefType value, AllocatorType &allocator) const
template<typename T >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T >, internal::IsGenericValue< T > >),(ValueType &)) AddMember(ValueType &name
GenericObject AddMember (StringRefType name, ValueType &value, AllocatorType &allocator) const
GenericObject AddMember (StringRefType name, StringRefType value, AllocatorType &allocator) const
template<typename T >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T >, internal::IsGenericValue< T > >),(GenericObject)) AddMember(StringRefType name
void RemoveAllMembers ()
bool RemoveMember (const Ch *name) const
template<typename SourceAllocator >
bool RemoveMember (const GenericValue< EncodingType, SourceAllocator > &name) const
MemberIterator RemoveMember (MemberIterator m) const
MemberIterator EraseMember (ConstMemberIterator pos) const
MemberIterator EraseMember (ConstMemberIterator first, ConstMemberIterator last) const
bool EraseMember (const Ch *name) const
template<typename SourceAllocator >
bool EraseMember (const GenericValue< EncodingType, SourceAllocator > &name) const
Public Attributes
T value
T AllocatorType &allocator const { value_.AddMember(name, value, allocator)
return * this
Private Member Functions
GenericObject ()
GenericObject (ValueType &value)
Private Attributes
ValueType & value_
Friends
template<typename , typename >
class GenericValue
Detailed Description
template<bool Const, typename ValueT>
class rapidjson::GenericObject< Const, ValueT >
Helper class for accessing Value of object type.
Instance of this helper class is obtained by GenericValue::GetObject(). In addition to all APIs for array type, it provides range-based for loop if RAPIDJSON_HAS_CXX11_RANGE_FOR=1.
Definition at line 2952 of file document.h.
Member Typedef Documentation
AllocatorType
template<bool Const, typename ValueT > typedef ValueType::AllocatorType rapidjson::GenericObject< Const, ValueT >::AllocatorType
Definition at line 2960 of file document.h.
Ch
template<bool Const, typename ValueT > typedef ValueType::Ch rapidjson::GenericObject< Const, ValueT >::Ch
Definition at line 2963 of file document.h.
ConstMemberIterator
template<bool Const, typename ValueT > typedef GenericMemberIterator<true, typename ValueT::EncodingType, typename ValueT::AllocatorType> rapidjson::GenericObject< Const, ValueT >::ConstMemberIterator
Definition at line 2959 of file document.h.
ConstObject
template<bool Const, typename ValueT > typedef GenericObject<true, ValueT> rapidjson::GenericObject< Const, ValueT >::ConstObject
Definition at line 2954 of file document.h.
EncodingType
template<bool Const, typename ValueT > typedef ValueType::EncodingType rapidjson::GenericObject< Const, ValueT >::EncodingType
Definition at line 2962 of file document.h.
MemberIterator
template<bool Const, typename ValueT > typedef GenericMemberIterator<Const, typename ValueT::EncodingType, typename ValueT::AllocatorType> rapidjson::GenericObject< Const, ValueT >::MemberIterator
Definition at line 2958 of file document.h.
Object
template<bool Const, typename ValueT > typedef GenericObject<false, ValueT> rapidjson::GenericObject< Const, ValueT >::Object
Definition at line 2955 of file document.h.
PlainType
template<bool Const, typename ValueT > typedef ValueT rapidjson::GenericObject< Const, ValueT >::PlainType
Definition at line 2956 of file document.h.
StringRefType
template<bool Const, typename ValueT > typedef ValueType::StringRefType rapidjson::GenericObject< Const, ValueT >::StringRefType
Definition at line 2961 of file document.h.
ValueType
template<bool Const, typename ValueT > typedef internal::MaybeAddConst<Const,PlainType>::Type rapidjson::GenericObject< Const, ValueT >::ValueType
Definition at line 2957 of file document.h.
Constructor & Destructor Documentation
GenericObject() [1/3]
template<bool Const, typename ValueT > rapidjson::GenericObject< Const, ValueT >::GenericObject (const GenericObject< Const, ValueT > & rhs) inline
Definition at line 2968 of file document.h.
: value_(rhs.value_) {}
~GenericObject()
template<bool Const, typename ValueT > rapidjson::GenericObject< Const, ValueT >::~GenericObject () inline
Definition at line 2970 of file document.h.
{}
GenericObject() [2/3]
template<bool Const, typename ValueT > rapidjson::GenericObject< Const, ValueT >::GenericObject () private
GenericObject() [3/3]
template<bool Const, typename ValueT > rapidjson::GenericObject< Const, ValueT >::GenericObject (ValueType & value) inline private
Definition at line 3031 of file document.h.
: value_(value) {}
References rapidjson::value.
Member Function Documentation
AddMember() [1/4]
template<bool Const, typename ValueT > GenericObject rapidjson::GenericObject< Const, ValueT >::AddMember (StringRefType name, StringRefType value, AllocatorType & allocator) const inline
Definition at line 3007 of file document.h.
{ value_.AddMember(name, value, allocator); return *this; }
References rapidjson::GenericObject< Const, ValueT >::AddMember(), and rapidjson::value.
AddMember() [2/4]
template<bool Const, typename ValueT > GenericObject rapidjson::GenericObject< Const, ValueT >::AddMember (StringRefType name, ValueType & value, AllocatorType & allocator) const inline
Definition at line 3006 of file document.h.
{ value_.AddMember(name, value, allocator); return *this; }
References rapidjson::GenericObject< Const, ValueT >::AddMember(), and rapidjson::value.
AddMember() [3/4]
template<bool Const, typename ValueT > GenericObject rapidjson::GenericObject< Const, ValueT >::AddMember (ValueType & name, StringRefType value, AllocatorType & allocator) const inline
Definition at line 2995 of file document.h.
{ value_.AddMember(name, value, allocator); return *this; }
References rapidjson::GenericObject< Const, ValueT >::AddMember(), and rapidjson::value.
AddMember() [4/4]
template<bool Const, typename ValueT > GenericObject rapidjson::GenericObject< Const, ValueT >::AddMember (ValueType & name, ValueType & value, AllocatorType & allocator) const inline
Definition at line 2994 of file document.h.
{ value_.AddMember(name, value, allocator); return *this; }
References rapidjson::GenericObject< Const, ValueT >::AddMember(), and rapidjson::value.
EraseMember() [1/4]
template<bool Const, typename ValueT > bool rapidjson::GenericObject< Const, ValueT >::EraseMember (const Ch * name) const inline
Definition at line 3018 of file document.h.
{ return value_.EraseMember(name); }
EraseMember() [2/4]
template<bool Const, typename ValueT > template<typename SourceAllocator > bool rapidjson::GenericObject< Const, ValueT >::EraseMember (const GenericValue< EncodingType, SourceAllocator > & name) const inline
Definition at line 3022 of file document.h.
{ return value_.EraseMember(name); }
EraseMember() [3/4]
template<bool Const, typename ValueT > MemberIterator rapidjson::GenericObject< Const, ValueT >::EraseMember (ConstMemberIterator first, ConstMemberIterator last) const inline
Definition at line 3017 of file document.h.
{ return value_.EraseMember(first, last); }
EraseMember() [4/4]
template<bool Const, typename ValueT > MemberIterator rapidjson::GenericObject< Const, ValueT >::EraseMember (ConstMemberIterator pos) const inline
Definition at line 3016 of file document.h.
{ return value_.EraseMember(pos); }
FindMember() [1/2]
template<bool Const, typename ValueT > MemberIterator rapidjson::GenericObject< Const, ValueT >::FindMember (const Ch * name) const inline
Definition at line 2989 of file document.h.
{ return value_.FindMember(name); }
FindMember() [2/2]
template<bool Const, typename ValueT > template<typename SourceAllocator > MemberIterator rapidjson::GenericObject< Const, ValueT >::FindMember (const GenericValue< EncodingType, SourceAllocator > & name) const inline
Definition at line 2990 of file document.h.
{ return value_.FindMember(name); }
HasMember() [1/2]
template<bool Const, typename ValueT > bool rapidjson::GenericObject< Const, ValueT >::HasMember (const Ch * name) const inline
Definition at line 2984 of file document.h.
{ return value_.HasMember(name); }
HasMember() [2/2]
template<bool Const, typename ValueT > template<typename SourceAllocator > bool rapidjson::GenericObject< Const, ValueT >::HasMember (const GenericValue< EncodingType, SourceAllocator > & name) const inline
Definition at line 2988 of file document.h.
{ return value_.HasMember(name); }
MemberBegin()
template<bool Const, typename ValueT > MemberIterator rapidjson::GenericObject< Const, ValueT >::MemberBegin () const inline
Definition at line 2981 of file document.h.
{ return value_.MemberBegin(); }
MemberCapacity()
template<bool Const, typename ValueT > SizeType rapidjson::GenericObject< Const, ValueT >::MemberCapacity () const inline
Definition at line 2974 of file document.h.
{ return value_.MemberCapacity(); }
MemberCount()
template<bool Const, typename ValueT > SizeType rapidjson::GenericObject< Const, ValueT >::MemberCount () const inline
Definition at line 2973 of file document.h.
{ return value_.MemberCount(); }
MemberEnd()
template<bool Const, typename ValueT > MemberIterator rapidjson::GenericObject< Const, ValueT >::MemberEnd () const inline
Definition at line 2982 of file document.h.
{ return value_.MemberEnd(); }
MemberReserve()
template<bool Const, typename ValueT > GenericObject rapidjson::GenericObject< Const, ValueT >::MemberReserve (SizeType newCapacity, AllocatorType & allocator) const inline
Definition at line 2983 of file document.h.
{ value_.MemberReserve(newCapacity, allocator); return *this; }
References rapidjson::GenericObject< Const, ValueT >::MemberReserve().
ObjectEmpty()
template<bool Const, typename ValueT > bool rapidjson::GenericObject< Const, ValueT >::ObjectEmpty () const inline
Definition at line 2975 of file document.h.
{ return value_.ObjectEmpty(); }
operator ValueType &()
template<bool Const, typename ValueT > rapidjson::GenericObject< Const, ValueT >::operator ValueType & () const inline
Definition at line 2972 of file document.h.
{ return value_; }
operator=()
template<bool Const, typename ValueT > GenericObject & rapidjson::GenericObject< Const, ValueT >::operator= (const GenericObject< Const, ValueT > & rhs) inline
Definition at line 2969 of file document.h.
{ value_ = rhs.value_; return *this; }
References rapidjson::GenericObject< Const, ValueT >::value_.
operator[]() [1/2]
template<bool Const, typename ValueT > template<typename SourceAllocator > ValueType & rapidjson::GenericObject< Const, ValueT >::operator[] (const GenericValue< EncodingType, SourceAllocator > & name) const inline
Definition at line 2977 of file document.h.
{ return value_[name]; }
operator[]() [2/2]
template<bool Const, typename ValueT > template<typename T > ValueType & rapidjson::GenericObject< Const, ValueT >::operator[] (T * name) const inline
Definition at line 2976 of file document.h.
{ return value_[name]; }
RAPIDJSON_DISABLEIF_RETURN() [1/2]
template<bool Const, typename ValueT > template<typename T > rapidjson::GenericObject< Const, ValueT >::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T >, internal::IsGenericValue< T > >) , (GenericObject< Const, ValueT >))
References rapidjson::value.
RAPIDJSON_DISABLEIF_RETURN() [2/2]
template<bool Const, typename ValueT > template<typename T > rapidjson::GenericObject< Const, ValueT >::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T >, internal::IsGenericValue< T > >) , (ValueType &)) &
RemoveAllMembers()
template<bool Const, typename ValueT > void rapidjson::GenericObject< Const, ValueT >::RemoveAllMembers () inline
Definition at line 3009 of file document.h.
{ value_.RemoveAllMembers(); }
RemoveMember() [1/3]
template<bool Const, typename ValueT > bool rapidjson::GenericObject< Const, ValueT >::RemoveMember (const Ch * name) const inline
Definition at line 3010 of file document.h.
{ return value_.RemoveMember(name); }
RemoveMember() [2/3]
template<bool Const, typename ValueT > template<typename SourceAllocator > bool rapidjson::GenericObject< Const, ValueT >::RemoveMember (const GenericValue< EncodingType, SourceAllocator > & name) const inline
Definition at line 3014 of file document.h.
{ return value_.RemoveMember(name); }
RemoveMember() [3/3]
template<bool Const, typename ValueT > MemberIterator rapidjson::GenericObject< Const, ValueT >::RemoveMember (MemberIterator m) const inline
Definition at line 3015 of file document.h.
{ return value_.RemoveMember(m); }
Friends And Related Symbol Documentation
GenericValue
template<bool Const, typename ValueT > template<typename , typename > friend class GenericValue friend
Definition at line 2966 of file document.h.
Member Data Documentation
const
template<bool Const, typename ValueT > T AllocatorType &allocator rapidjson::GenericObject< Const, ValueT >::const { value_.AddMember(name, value, allocator)
Definition at line 2999 of file document.h.
this
template<bool Const, typename ValueT > return * rapidjson::GenericObject< Const, ValueT >::this
Definition at line 2999 of file document.h.
value
template<bool Const, typename ValueT > T rapidjson::GenericObject< Const, ValueT >::value
Definition at line 2999 of file document.h.
value_
template<bool Const, typename ValueT > ValueType& rapidjson::GenericObject< Const, ValueT >::value_ private
Definition at line 3032 of file document.h.
The documentation for this class was generated from the following file:
rapidjson/include/rapidjson/document.h