wiNpoS: testing::internal::JsonUnitTestResultPrinter Class Reference
testing::internal::JsonUnitTestResultPrinter Class Reference
Public Member Functions
JsonUnitTestResultPrinter (const char *output_file)
virtual void OnTestIterationEnd (const UnitTest &unit_test, int iteration)
Public Member Functions inherited from testing::EmptyTestEventListener
virtual void OnTestProgramStart (const UnitTest &)
virtual void OnTestIterationStart (const UnitTest &, int)
virtual void OnEnvironmentsSetUpStart (const UnitTest &)
virtual void OnEnvironmentsSetUpEnd (const UnitTest &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestStart (const TestInfo &)
virtual void OnTestPartResult (const TestPartResult &)
virtual void OnTestEnd (const TestInfo &)
virtual void OnTestCaseEnd (const TestCase &)
virtual void OnEnvironmentsTearDownStart (const UnitTest &)
virtual void OnEnvironmentsTearDownEnd (const UnitTest &)
virtual void OnTestProgramEnd (const UnitTest &)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (JsonUnitTestResultPrinter)
Static Private Member Functions
static std::string EscapeJson (const std::string &str)
static void OutputJsonKey (std::ostream *stream, const std::string &element_name, const std::string &name, const std::string &value, const std::string &indent, bool comma=true)
static void OutputJsonKey (std::ostream *stream, const std::string &element_name, const std::string &name, int value, const std::string &indent, bool comma=true)
static void OutputJsonTestInfo (::std::ostream *stream, const char *test_case_name, const TestInfo &test_info)
static void PrintJsonTestCase (::std::ostream *stream, const TestCase &test_case)
static void PrintJsonUnitTest (::std::ostream *stream, const UnitTest &unit_test)
static std::string TestPropertiesAsJson (const TestResult &result, const std::string &indent)
Private Attributes
const std::string output_file_
Detailed Description
Definition at line 3827 of file gtest.cc.
Constructor & Destructor Documentation
JsonUnitTestResultPrinter()
testing::internal::JsonUnitTestResultPrinter::JsonUnitTestResultPrinter (const char * output_file) explicit
Definition at line 3877 of file gtest.cc.
    : output_file_(output_file) {
  if (output_file_.empty()) {
    GTEST_LOG_(FATAL) << "JSON output file may not be null";
  }
}
References GTEST_LOG_, and output_file_.
Member Function Documentation
EscapeJson()
std::string testing::internal::JsonUnitTestResultPrinter::EscapeJson (const std::string & str) static private
Definition at line 3914 of file gtest.cc.
{
  Message m;
  for (size_t i = 0; i < str.size(); ++i) {
    const char ch = str[i];
    switch (ch) {
      case '\\':
      case '"':
      case '/':
        m << '\\' << ch;
        break;
      case '\b':
        m << "\\b";
        break;
      case '\t':
        m << "\\t";
        break;
      case '\n':
        m << "\\n";
        break;
      case '\f':
        m << "\\f";
        break;
      case '\r':
        m << "\\r";
        break;
      default:
        if (ch < ' ') {
          m << "\\u00" << String::FormatByte(static_cast<unsigned char>(ch));
        } else {
          m << ch;
        }
        break;
    }
  }
  return m.GetString();
}
References testing::internal::String::FormatByte(), and testing::Message::GetString().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::internal::JsonUnitTestResultPrinter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (JsonUnitTestResultPrinter) private
OnTestIterationEnd()
void testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 3884 of file gtest.cc.
{
  FILE* jsonout = NULL;
  FilePath output_file(output_file_);
  FilePath output_dir(output_file.RemoveFileName());
  if (output_dir.CreateDirectoriesRecursively()) {
    jsonout = posix::FOpen(output_file_.c_str(), "w");
  }
  if (jsonout == NULL) {
    // TODO(phosek): report the reason of the failure.
    //
    // We don't do it for now as:
    //
    //   1. There is no urgent need for it.
    //   2. It's a bit involved to make the errno variable thread-safe on
    //      all three operating systems (Linux, Windows, and Mac OS).
    //   3. To interpret the meaning of errno in a thread-safe way,
    //      we need the strerror_r() function, which is not available on
    //      Windows.
    GTEST_LOG_(FATAL) << "Unable to open file \""
                      << output_file_ << "\"";
  }
  std::stringstream stream;
  PrintJsonUnitTest(&stream, unit_test);
  fprintf(jsonout, "%s", StringStreamToString(&stream).c_str());
  fclose(jsonout);
}
References testing::internal::posix::FOpen(), GTEST_LOG_, output_file_, PrintJsonUnitTest(), testing::internal::FilePath::RemoveFileName(), and testing::internal::StringStreamToString().
OutputJsonKey() [1/2]
void testing::internal::JsonUnitTestResultPrinter::OutputJsonKey (std::ostream * stream, const std::string & element_name, const std::string & name, const std::string & value, const std::string & indent, bool comma = true) static private
Definition at line 3982 of file gtest.cc.
                {
  const std::vector<std::string>& allowed_names =
      GetReservedAttributesForElement(element_name);
  GTEST_CHECK_(std::find(allowed_names.begin(), allowed_names.end(), name) !=
                   allowed_names.end())
      << "Key \"" << name << "\" is not allowed for value \"" << element_name
      << "\".";
  *stream << indent << "\"" << name << "\": \"" << EscapeJson(value) << "\"";
  if (comma)
    *stream << ",\n";
}
References EscapeJson(), testing::GetReservedAttributesForElement(), and GTEST_CHECK_.
OutputJsonKey() [2/2]
void testing::internal::JsonUnitTestResultPrinter::OutputJsonKey (std::ostream * stream, const std::string & element_name, const std::string & name, int value, const std::string & indent, bool comma = true) static private
Definition at line 4002 of file gtest.cc.
                {
  const std::vector<std::string>& allowed_names =
      GetReservedAttributesForElement(element_name);
  GTEST_CHECK_(std::find(allowed_names.begin(), allowed_names.end(), name) !=
                   allowed_names.end())
      << "Key \"" << name << "\" is not allowed for value \"" << element_name
      << "\".";
  *stream << indent << "\"" << name << "\": " << StreamableToString(value);
  if (comma)
    *stream << ",\n";
}
References testing::GetReservedAttributesForElement(), GTEST_CHECK_, and testing::internal::StreamableToString().
OutputJsonTestInfo()
void testing::internal::JsonUnitTestResultPrinter::OutputJsonTestInfo (::std::ostream * stream, const char * test_case_name, const TestInfo & test_info) static private
Definition at line 4023 of file gtest.cc.
{
  const TestResult& result = *test_info.result();
  const std::string kTestcase = "testcase";
  const std::string kIndent = Indent(10);
  *stream << Indent(8) << "{\n";
  OutputJsonKey(stream, kTestcase, "name", test_info.name(), kIndent);
  if (test_info.value_param() != NULL) {
    OutputJsonKey(stream, kTestcase, "value_param",
                  test_info.value_param(), kIndent);
  }
  if (test_info.type_param() != NULL) {
    OutputJsonKey(stream, kTestcase, "type_param", test_info.type_param(),
                  kIndent);
  }
  OutputJsonKey(stream, kTestcase, "status",
                test_info.should_run() ? "RUN" : "NOTRUN", kIndent);
  OutputJsonKey(stream, kTestcase, "time",
                FormatTimeInMillisAsDuration(result.elapsed_time()), kIndent);
  OutputJsonKey(stream, kTestcase, "classname", test_case_name, kIndent, false);
  *stream << TestPropertiesAsJson(result, kIndent);
  int failures = 0;
  for (int i = 0; i < result.total_part_count(); ++i) {
    const TestPartResult& part = result.GetTestPartResult(i);
    if (part.failed()) {
      *stream << ",\n";
      if (++failures == 1) {
        *stream << kIndent << "\"" << "failures" << "\": [\n";
      }
      const std::string location =
          internal::FormatCompilerIndependentFileLocation(part.file_name(),
                                                          part.line_number());
      const std::string message = EscapeJson(location + "\n" + part.message());
      *stream << kIndent << "  {\n"
              << kIndent << "    \"failure\": \"" << message << "\",\n"
              << kIndent << "    \"type\": \"\"\n"
              << kIndent << "  }";
    }
  }
  if (failures > 0)
    *stream << "\n" << kIndent << "]";
  *stream << "\n" << Indent(8) << "}";
}
References testing::TestResult::elapsed_time(), EscapeJson(), testing::TestPartResult::failed(), testing::TestPartResult::file_name(), testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatTimeInMillisAsDuration(), testing::TestResult::GetTestPartResult(), testing::internal::Indent(), testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), OutputJsonKey(), testing::TestInfo::result(), testing::TestInfo::should_run(), TestPropertiesAsJson(), testing::TestResult::total_part_count(), testing::TestInfo::type_param(), and testing::TestInfo::value_param().
PrintJsonTestCase()
void testing::internal::JsonUnitTestResultPrinter::PrintJsonTestCase (::std::ostream * stream, const TestCase & test_case) static private
Definition at line 4074 of file gtest.cc.
{
  const std::string kTestsuite = "testsuite";
  const std::string kIndent = Indent(6);
  *stream << Indent(4) << "{\n";
  OutputJsonKey(stream, kTestsuite, "name", test_case.name(), kIndent);
  OutputJsonKey(stream, kTestsuite, "tests", test_case.reportable_test_count(),
                kIndent);
  OutputJsonKey(stream, kTestsuite, "failures", test_case.failed_test_count(),
                kIndent);
  OutputJsonKey(stream, kTestsuite, "disabled",
                test_case.reportable_disabled_test_count(), kIndent);
  OutputJsonKey(stream, kTestsuite, "errors", 0, kIndent);
  OutputJsonKey(stream, kTestsuite, "time",
                FormatTimeInMillisAsDuration(test_case.elapsed_time()), kIndent,
                false);
  *stream << TestPropertiesAsJson(test_case.ad_hoc_test_result(), kIndent)
          << ",\n";
  *stream << kIndent << "\"" << kTestsuite << "\": [\n";
  bool comma = false;
  for (int i = 0; i < test_case.total_test_count(); ++i) {
    if (test_case.GetTestInfo(i)->is_reportable()) {
      if (comma) {
        *stream << ",\n";
      } else {
        comma = true;
      }
      OutputJsonTestInfo(stream, test_case.name(), *test_case.GetTestInfo(i));
    }
  }
  *stream << "\n" << kIndent << "]\n" << Indent(4) << "}";
}
References testing::TestCase::ad_hoc_test_result(), testing::TestCase::elapsed_time(), testing::TestCase::failed_test_count(), testing::internal::FormatTimeInMillisAsDuration(), testing::TestCase::GetTestInfo(), testing::internal::Indent(), testing::TestInfo::is_reportable(), testing::TestCase::name(), OutputJsonKey(), OutputJsonTestInfo(), testing::TestCase::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), TestPropertiesAsJson(), and testing::TestCase::total_test_count().
PrintJsonUnitTest()
void testing::internal::JsonUnitTestResultPrinter::PrintJsonUnitTest (::std::ostream * stream, const UnitTest & unit_test) static private
Definition at line 4111 of file gtest.cc.
{
  const std::string kTestsuites = "testsuites";
  const std::string kIndent = Indent(2);
  *stream << "{\n";
  OutputJsonKey(stream, kTestsuites, "tests", unit_test.reportable_test_count(),
                kIndent);
  OutputJsonKey(stream, kTestsuites, "failures", unit_test.failed_test_count(),
                kIndent);
  OutputJsonKey(stream, kTestsuites, "disabled",
                unit_test.reportable_disabled_test_count(), kIndent);
  OutputJsonKey(stream, kTestsuites, "errors", 0, kIndent);
  if (GTEST_FLAG(shuffle)) {
    OutputJsonKey(stream, kTestsuites, "random_seed", unit_test.random_seed(),
                  kIndent);
  }
  OutputJsonKey(stream, kTestsuites, "timestamp",
                FormatEpochTimeInMillisAsRFC3339(unit_test.start_timestamp()),
                kIndent);
  OutputJsonKey(stream, kTestsuites, "time",
                FormatTimeInMillisAsDuration(unit_test.elapsed_time()), kIndent,
                false);
  *stream << TestPropertiesAsJson(unit_test.ad_hoc_test_result(), kIndent)
          << ",\n";
  OutputJsonKey(stream, kTestsuites, "name", "AllTests", kIndent);
  *stream << kIndent << "\"" << kTestsuites << "\": [\n";
  bool comma = false;
  for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
    if (unit_test.GetTestCase(i)->reportable_test_count() > 0) {
      if (comma) {
        *stream << ",\n";
      } else {
        comma = true;
      }
      PrintJsonTestCase(stream, *unit_test.GetTestCase(i));
    }
  }
  *stream << "\n" << kIndent << "]\n" << "}\n";
}
References testing::UnitTest::ad_hoc_test_result(), testing::UnitTest::elapsed_time(), testing::UnitTest::failed_test_count(), testing::internal::FormatEpochTimeInMillisAsRFC3339(), testing::internal::FormatTimeInMillisAsDuration(), testing::UnitTest::GetTestCase(), GTEST_FLAG, testing::internal::Indent(), OutputJsonKey(), PrintJsonTestCase(), testing::UnitTest::random_seed(), testing::UnitTest::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), testing::UnitTest::reportable_test_count(), testing::UnitTest::start_timestamp(), TestPropertiesAsJson(), and testing::UnitTest::total_test_case_count().
TestPropertiesAsJson()
std::string testing::internal::JsonUnitTestResultPrinter::TestPropertiesAsJson (const TestResult & result, const std::string & indent) static private
Definition at line 4158 of file gtest.cc.
{
  Message attributes;
  for (int i = 0; i < result.test_property_count(); ++i) {
    const TestProperty& property = result.GetTestProperty(i);
    attributes << ",\n" << indent << "\"" << property.key() << "\": "
               << "\"" << EscapeJson(property.value()) << "\"";
  }
  return attributes.GetString();
}
References EscapeJson(), testing::Message::GetString(), testing::TestResult::GetTestProperty(), and testing::TestResult::test_property_count().
Member Data Documentation
output_file_
const std::string testing::internal::JsonUnitTestResultPrinter::output_file_ private
Definition at line 3871 of file gtest.cc.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/src/gtest.cc