wiNpoS: testing::internal::StartsWithMatcher< StringType > Class Template Reference
testing::internal::StartsWithMatcher< StringType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
StartsWithMatcher (const StringType &prefix)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (StartsWithMatcher)
Private Attributes
const StringType prefix_
Detailed Description
template<typename StringType>
class testing::internal::StartsWithMatcher< StringType >
Definition at line 1429 of file gmock-matchers.h.
Constructor & Destructor Documentation
StartsWithMatcher()
template<typename StringType > testing::internal::StartsWithMatcher< StringType >::StartsWithMatcher (const StringType & prefix) inline explicit
Definition at line 1431 of file gmock-matchers.h.
                                                       : prefix_(prefix) {
  }
Member Function Documentation
DescribeNegationTo()
template<typename StringType > void testing::internal::StartsWithMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1474 of file gmock-matchers.h.
{
    *os << "doesn't start with ";
    UniversalPrint(prefix_, os);
  }
References testing::internal::StartsWithMatcher< StringType >::prefix_, and testing::internal::UniversalPrint().
DescribeTo()
template<typename StringType > void testing::internal::StartsWithMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1469 of file gmock-matchers.h.
{
    *os << "starts with ";
    UniversalPrint(prefix_, os);
  }
References testing::internal::StartsWithMatcher< StringType >::prefix_, and testing::internal::UniversalPrint().
GTEST_DISALLOW_ASSIGN_()
template<typename StringType > testing::internal::StartsWithMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (StartsWithMatcher< StringType >) private
MatchAndExplain() [1/2]
template<typename StringType > template<typename CharType > bool testing::internal::StartsWithMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1453 of file gmock-matchers.h.
{
    return s != NULL && MatchAndExplain(StringType(s), listener);
  }
References testing::internal::StartsWithMatcher< StringType >::MatchAndExplain().
MatchAndExplain() [2/2]
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StartsWithMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1462 of file gmock-matchers.h.
{
    const StringType& s2(s);
    return s2.length() >= prefix_.length() &&
        s2.substr(0, prefix_.length()) == prefix_;
  }
References testing::internal::StartsWithMatcher< StringType >::prefix_.
Member Data Documentation
prefix_
template<typename StringType > const StringType testing::internal::StartsWithMatcher< StringType >::prefix_ private
Definition at line 1480 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h