wiNpoS: testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer > Class Template Reference
testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer > Class Template Reference
Public Types
typedef PointeeOf< GTEST_REMOVE_CONST_(GTEST_REMOVE_REFERENCE_(Pointer))>::type Pointee
Public Member Functions
Impl (const InnerMatcher &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Pointer pointer, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< const Pointee & > matcher_
Detailed Description
template<typename InnerMatcher>
template<typename Pointer>
class testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >
Definition at line 2336 of file gmock-matchers.h.
Member Typedef Documentation
Pointee
template<typename InnerMatcher > template<typename Pointer > typedef PointeeOf<GTEST_REMOVE_CONST_(GTEST_REMOVE_REFERENCE_(Pointer))>::type testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::Pointee
Definition at line 2339 of file gmock-matchers.h.
Constructor & Destructor Documentation
Impl()
template<typename InnerMatcher > template<typename Pointer > testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::Impl (const InnerMatcher & matcher) inline explicit
Definition at line 2341 of file gmock-matchers.h.
        : matcher_(MatcherCast<const Pointee&>(matcher)) {}
References testing::MatcherCast().
Member Function Documentation
DescribeNegationTo()
template<typename InnerMatcher > template<typename Pointer > virtual void testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2349 of file gmock-matchers.h.
{
      *os << "does not point to a value that ";
      matcher_.DescribeTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::matcher_.
DescribeTo()
template<typename InnerMatcher > template<typename Pointer > virtual void testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2344 of file gmock-matchers.h.
{
      *os << "points to a value that ";
      matcher_.DescribeTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::matcher_.
GTEST_DISALLOW_ASSIGN_()
template<typename InnerMatcher > template<typename Pointer > testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::GTEST_DISALLOW_ASSIGN_ (Impl< Pointer >) private
MatchAndExplain()
template<typename InnerMatcher > template<typename Pointer > virtual bool testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::MatchAndExplain (Pointer pointer, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Pointer >.
Definition at line 2354 of file gmock-matchers.h.
{
      if (GetRawPointer(pointer) == NULL)
        return false;
      *listener << "which points to ";
      return MatchPrintAndExplain(*pointer, matcher_, listener);
    }
References testing::internal::GetRawPointer(), testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::matcher_, and testing::internal::MatchPrintAndExplain().
Member Data Documentation
matcher_
template<typename InnerMatcher > template<typename Pointer > const Matcher<const Pointee&> testing::internal::PointeeMatcher< InnerMatcher >::Impl< Pointer >::matcher_ private
Definition at line 2364 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h