wiNpoS: testing::internal::TestEventListenersAccessor Class Reference
testing::internal::TestEventListenersAccessor Class Reference
Static Public Member Functions
static TestEventListener * GetRepeater (TestEventListeners *listeners)
static void SetDefaultResultPrinter (TestEventListeners *listeners, TestEventListener *listener)
static void SetDefaultXmlGenerator (TestEventListeners *listeners, TestEventListener *listener)
static bool EventForwardingEnabled (const TestEventListeners &listeners)
static void SuppressEventForwarding (TestEventListeners *listeners)
Detailed Description
Definition at line 155 of file gtest_unittest.cc.
Member Function Documentation
EventForwardingEnabled()
static bool testing::internal::TestEventListenersAccessor::EventForwardingEnabled (const TestEventListeners & listeners) inline static
Definition at line 170 of file gtest_unittest.cc.
{
    return listeners.EventForwardingEnabled();
  }
References testing::TestEventListeners::EventForwardingEnabled().
GetRepeater()
static TestEventListener * testing::internal::TestEventListenersAccessor::GetRepeater (TestEventListeners * listeners) inline static
Definition at line 157 of file gtest_unittest.cc.
{
    return listeners->repeater();
  }
References testing::TestEventListeners::repeater().
SetDefaultResultPrinter()
static void testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 161 of file gtest_unittest.cc.
{
    listeners->SetDefaultResultPrinter(listener);
  }
References testing::TestEventListeners::SetDefaultResultPrinter().
SetDefaultXmlGenerator()
static void testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator (TestEventListeners * listeners, TestEventListener * listener) inline static
Definition at line 165 of file gtest_unittest.cc.
{
    listeners->SetDefaultXmlGenerator(listener);
  }
References testing::TestEventListeners::SetDefaultXmlGenerator().
SuppressEventForwarding()
static void testing::internal::TestEventListenersAccessor::SuppressEventForwarding (TestEventListeners * listeners) inline static
Definition at line 174 of file gtest_unittest.cc.
{
    listeners->SuppressEventForwarding();
  }
References testing::TestEventListeners::SuppressEventForwarding().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest_unittest.cc