wiNpoS: RemoteSchemaDocumentProvider< SchemaDocumentType > Class Template Reference
RemoteSchemaDocumentProvider< SchemaDocumentType > Class Template Reference
Public Member Functions
RemoteSchemaDocumentProvider ()
~RemoteSchemaDocumentProvider ()
virtual const SchemaDocumentType * GetRemoteDocument (const char *uri, SizeType length)
Public Member Functions inherited from rapidjson::IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >
virtual ~IGenericRemoteSchemaDocumentProvider ()
virtual const SchemaDocumentType * GetRemoteDocument (const Ch *uri, SizeType length)=0
virtual const SchemaDocumentType * GetRemoteDocument (const GenericUri< ValueType, AllocatorType > uri, Specification &spec)
Private Types
typedef GenericDocument< typename SchemaDocumentType::EncodingType, MemoryPoolAllocator<>, MemoryPoolAllocator<> > DocumentType
Private Member Functions
RemoteSchemaDocumentProvider (const RemoteSchemaDocumentProvider &)
RemoteSchemaDocumentProvider & operator= (const RemoteSchemaDocumentProvider &)
Private Attributes
SchemaDocumentType * sd_ [kCount]
DocumentType::AllocatorType documentAllocator_
SchemaDocumentType::AllocatorType schemaAllocator_
char documentBuffer_ [16384]
char schemaBuffer_ [128u *1024]
Static Private Attributes
static const size_t kCount = 5
Additional Inherited Members
Public Types inherited from rapidjson::IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >
typedef SchemaDocumentType::Ch Ch
typedef SchemaDocumentType::ValueType ValueType
typedef SchemaDocumentType::AllocatorType AllocatorType
Detailed Description
template<typename SchemaDocumentType = SchemaDocument>
class RemoteSchemaDocumentProvider< SchemaDocumentType >
Definition at line 2108 of file schematest.cpp.
Member Typedef Documentation
DocumentType
template<typename SchemaDocumentType = SchemaDocument> typedef GenericDocument<typename SchemaDocumentType::EncodingType, MemoryPoolAllocator<>, MemoryPoolAllocator<> > RemoteSchemaDocumentProvider< SchemaDocumentType >::DocumentType private
Definition at line 2167 of file schematest.cpp.
Constructor & Destructor Documentation
RemoteSchemaDocumentProvider() [1/2]
template<typename SchemaDocumentType = SchemaDocument> RemoteSchemaDocumentProvider< SchemaDocumentType >::RemoteSchemaDocumentProvider () inline
Definition at line 2110 of file schematest.cpp.
                                   :
        documentAllocator_(documentBuffer_, sizeof(documentBuffer_)),
        schemaAllocator_(schemaBuffer_, sizeof(schemaBuffer_))
    {
        const char* filenames[kCount] = {
            "jsonschema/remotes/integer.json",
            "jsonschema/remotes/subSchemas.json",
            "jsonschema/remotes/folder/folderInteger.json",
            "draft-04/schema",
            "unittestschema/address.json"
        };
        const char* uris[kCount] = {
            "http://localhost:1234/integer.json",
            "http://localhost:1234/subSchemas.json",
            "http://localhost:1234/folder/folderInteger.json",
            "http://json-schema.org/draft-04/schema",
            "http://localhost:1234/address.json"
        };
        for (size_t i = 0; i < kCount; i++) {
            sd_[i] = 0;
            char jsonBuffer[8192];
            MemoryPoolAllocator<> jsonAllocator(jsonBuffer, sizeof(jsonBuffer));
            char* json = ReadFile(filenames[i], jsonAllocator);
            if (!json) {
                printf("json remote file %s not found", filenames[i]);
                ADD_FAILURE();
            }
            else {
                char stackBuffer[4096];
                MemoryPoolAllocator<> stackAllocator(stackBuffer, sizeof(stackBuffer));
                DocumentType d(&documentAllocator_, 1024, &stackAllocator);
                d.Parse(json);
                sd_[i] = new SchemaDocumentType(d, uris[i], static_cast<SizeType>(strlen(uris[i])), 0, &schemaAllocator_);
                MemoryPoolAllocator<>::Free(json);
            }
        };
    }
References ADD_FAILURE, RemoteSchemaDocumentProvider< SchemaDocumentType >::documentAllocator_, rapidjson::MemoryPoolAllocator< BaseAllocator >::Free(), RemoteSchemaDocumentProvider< SchemaDocumentType >::kCount, rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse(), ReadFile(), RemoteSchemaDocumentProvider< SchemaDocumentType >::schemaAllocator_, and RemoteSchemaDocumentProvider< SchemaDocumentType >::sd_.
~RemoteSchemaDocumentProvider()
template<typename SchemaDocumentType = SchemaDocument> RemoteSchemaDocumentProvider< SchemaDocumentType >::~RemoteSchemaDocumentProvider () inline
Definition at line 2150 of file schematest.cpp.
{
        for (size_t i = 0; i < kCount; i++)
            delete sd_[i];
    }
References RemoteSchemaDocumentProvider< SchemaDocumentType >::kCount, and RemoteSchemaDocumentProvider< SchemaDocumentType >::sd_.
RemoteSchemaDocumentProvider() [2/2]
template<typename SchemaDocumentType = SchemaDocument> RemoteSchemaDocumentProvider< SchemaDocumentType >::RemoteSchemaDocumentProvider (const RemoteSchemaDocumentProvider< SchemaDocumentType > &) private
Member Function Documentation
GetRemoteDocument()
template<typename SchemaDocumentType = SchemaDocument> virtual const SchemaDocumentType * RemoteSchemaDocumentProvider< SchemaDocumentType >::GetRemoteDocument (const char * uri, SizeType length) inline virtual
Definition at line 2155 of file schematest.cpp.
{
        //printf("GetRemoteDocument : %s\n", uri);
        for (size_t i = 0; i < kCount; i++)
            if (typename SchemaDocumentType::GValue(uri, length) == sd_[i]->GetURI()) {
                //printf("Matched document");
                return sd_[i];
            }
        //printf("No matched document");
        return 0;
    }
References RemoteSchemaDocumentProvider< SchemaDocumentType >::kCount, and RemoteSchemaDocumentProvider< SchemaDocumentType >::sd_.
operator=()
template<typename SchemaDocumentType = SchemaDocument> RemoteSchemaDocumentProvider & RemoteSchemaDocumentProvider< SchemaDocumentType >::operator= (const RemoteSchemaDocumentProvider< SchemaDocumentType > &) private
Member Data Documentation
documentAllocator_
template<typename SchemaDocumentType = SchemaDocument> DocumentType::AllocatorType RemoteSchemaDocumentProvider< SchemaDocumentType >::documentAllocator_ private
Definition at line 2174 of file schematest.cpp.
documentBuffer_
template<typename SchemaDocumentType = SchemaDocument> char RemoteSchemaDocumentProvider< SchemaDocumentType >::documentBuffer_[16384] private
Definition at line 2176 of file schematest.cpp.
kCount
template<typename SchemaDocumentType = SchemaDocument> const size_t RemoteSchemaDocumentProvider< SchemaDocumentType >::kCount = 5 static private
Definition at line 2172 of file schematest.cpp.
schemaAllocator_
template<typename SchemaDocumentType = SchemaDocument> SchemaDocumentType::AllocatorType RemoteSchemaDocumentProvider< SchemaDocumentType >::schemaAllocator_ private
Definition at line 2175 of file schematest.cpp.
schemaBuffer_
template<typename SchemaDocumentType = SchemaDocument> char RemoteSchemaDocumentProvider< SchemaDocumentType >::schemaBuffer_[128u *1024] private
Definition at line 2177 of file schematest.cpp.
sd_
template<typename SchemaDocumentType = SchemaDocument> SchemaDocumentType* RemoteSchemaDocumentProvider< SchemaDocumentType >::sd_[kCount] private
Definition at line 2173 of file schematest.cpp.
The documentation for this class was generated from the following file:
rapidjson/test/unittest/schematest.cpp