wiNpoS: rapidjson::internal::Schema< SchemaDocumentType > Class Template Reference
rapidjson::internal::Schema< SchemaDocumentType > Class Template Reference
#include <schema.h>
Classes
struct PatternProperty
struct Property
struct SchemaArray
Public Types
typedef SchemaDocumentType::ValueType ValueType
typedef SchemaDocumentType::AllocatorType AllocatorType
typedef SchemaDocumentType::PointerType PointerType
typedef ValueType::EncodingType EncodingType
typedef EncodingType::Ch Ch
typedef SchemaValidationContext< SchemaDocumentType > Context
typedef Schema< SchemaDocumentType > SchemaType
typedef GenericValue< EncodingType, AllocatorType > SValue
typedef IValidationErrorHandler< Schema > ErrorHandler
typedef GenericUri< ValueType, AllocatorType > UriType
Public Member Functions
Schema (SchemaDocumentType *schemaDocument, const PointerType &p, const ValueType &value, const ValueType &document, AllocatorType *allocator, const UriType &id=UriType())
~Schema ()
const SValue & GetURI () const
const UriType & GetId () const
const Specification & GetSpecification () const
const PointerType & GetPointer () const
bool BeginValue (Context &context) const
RAPIDJSON_FORCEINLINE bool EndValue (Context &context) const
bool Null (Context &context) const
bool Bool (Context &context, bool b) const
bool Int (Context &context, int i) const
bool Uint (Context &context, unsigned u) const
bool Int64 (Context &context, int64_t i) const
bool Uint64 (Context &context, uint64_t u) const
bool Double (Context &context, double d) const
bool String (Context &context, const Ch *str, SizeType length, bool) const
bool StartObject (Context &context) const
bool Key (Context &context, const Ch *str, SizeType len, bool) const
bool EndObject (Context &context, SizeType memberCount) const
bool StartArray (Context &context) const
bool EndArray (Context &context, SizeType elementCount) const
Static Public Member Functions
static const ValueType & GetValidateErrorKeyword (ValidateErrorCode validateErrorCode)
static const ValueType & GetNullString ()
static const ValueType & GetBooleanString ()
static const ValueType & GetObjectString ()
static const ValueType & GetArrayString ()
static const ValueType & GetStringString ()
static const ValueType & GetNumberString ()
static const ValueType & GetIntegerString ()
static const ValueType & GetTypeString ()
static const ValueType & GetEnumString ()
static const ValueType & GetAllOfString ()
static const ValueType & GetAnyOfString ()
static const ValueType & GetOneOfString ()
static const ValueType & GetNotString ()
static const ValueType & GetPropertiesString ()
static const ValueType & GetRequiredString ()
static const ValueType & GetDependenciesString ()
static const ValueType & GetPatternPropertiesString ()
static const ValueType & GetAdditionalPropertiesString ()
static const ValueType & GetMinPropertiesString ()
static const ValueType & GetMaxPropertiesString ()
static const ValueType & GetItemsString ()
static const ValueType & GetMinItemsString ()
static const ValueType & GetMaxItemsString ()
static const ValueType & GetAdditionalItemsString ()
static const ValueType & GetUniqueItemsString ()
static const ValueType & GetMinLengthString ()
static const ValueType & GetMaxLengthString ()
static const ValueType & GetPatternString ()
static const ValueType & GetMinimumString ()
static const ValueType & GetMaximumString ()
static const ValueType & GetExclusiveMinimumString ()
static const ValueType & GetExclusiveMaximumString ()
static const ValueType & GetMultipleOfString ()
static const ValueType & GetDefaultValueString ()
static const ValueType & GetSchemaString ()
static const ValueType & GetRefString ()
static const ValueType & GetIdString ()
static const ValueType & GetSwaggerString ()
static const ValueType & GetOpenApiString ()
static const ValueType & GetReadOnlyString ()
static const ValueType & GetWriteOnlyString ()
static const ValueType & GetNullableString ()
Private Types
enum SchemaValueType {
kNullSchemaType , kBooleanSchemaType , kObjectSchemaType , kArraySchemaType ,
kStringSchemaType , kNumberSchemaType , kIntegerSchemaType , kTotalSchemaType
}
typedef internal::GenericRegex< EncodingType, AllocatorType > RegexType
Private Member Functions
template<typename V1 , typename V2 >
void AddUniqueElement (V1 &a, const V2 &v)
void AssignIfExist (SchemaArray &out, SchemaDocumentType &schemaDocument, const PointerType &p, const ValueType &value, const ValueType &name, const ValueType &document)
template<typename ValueType >
RegexType * CreatePattern (const ValueType &value, SchemaDocumentType *sd, const PointerType &p)
void AddType (const ValueType &type)
bool CreateParallelValidator (Context &context) const
void CreateSchemaValidators (Context &context, const SchemaArray &schemas, const bool inheritContinueOnErrors) const
bool FindPropertyIndex (const ValueType &name, SizeType *outIndex) const
bool CheckBool (Context &context, bool) const
bool CheckInt (Context &context, int64_t i) const
bool CheckUint (Context &context, uint64_t i) const
bool CheckDoubleMinimum (Context &context, double d) const
bool CheckDoubleMaximum (Context &context, double d) const
bool CheckDoubleMultipleOf (Context &context, double d) const
void DisallowedType (Context &context, const ValueType &actualType) const
Static Private Member Functions
static const ValueType * GetMember (const ValueType &value, const ValueType &name)
static void AssignIfExist (bool &out, const ValueType &value, const ValueType &name)
static void AssignIfExist (SizeType &out, const ValueType &value, const ValueType &name)
static bool IsPatternMatch (const RegexType *pattern, const Ch *str, SizeType)
Private Attributes
AllocatorType * allocator_
SValue uri_
UriType id_
Specification spec_
PointerType pointer_
const SchemaType * typeless_
uint64_t * enum_
SizeType enumCount_
SchemaArray allOf_
SchemaArray anyOf_
SchemaArray oneOf_
const SchemaType * not_
unsigned type_
SizeType validatorCount_
SizeType notValidatorIndex_
Property * properties_
const SchemaType * additionalPropertiesSchema_
PatternProperty * patternProperties_
SizeType patternPropertyCount_
SizeType propertyCount_
SizeType minProperties_
SizeType maxProperties_
bool additionalProperties_
bool hasDependencies_
bool hasRequired_
bool hasSchemaDependencies_
const SchemaType * additionalItemsSchema_
const SchemaType * itemsList_
const SchemaType ** itemsTuple_
SizeType itemsTupleCount_
SizeType minItems_
SizeType maxItems_
bool additionalItems_
bool uniqueItems_
RegexType * pattern_
SizeType minLength_
SizeType maxLength_
SValue minimum_
SValue maximum_
SValue multipleOf_
bool exclusiveMinimum_
bool exclusiveMaximum_
SizeType defaultValueLength_
bool readOnly_
bool writeOnly_
bool nullable_
Friends
class GenericSchemaDocument< ValueType, AllocatorType >
Detailed Description
template<typename SchemaDocumentType>
class rapidjson::internal::Schema< SchemaDocumentType >
Definition at line 520 of file schema.h.
Member Typedef Documentation
AllocatorType
template<typename SchemaDocumentType > typedef SchemaDocumentType::AllocatorType rapidjson::internal::Schema< SchemaDocumentType >::AllocatorType
Definition at line 523 of file schema.h.
Ch
template<typename SchemaDocumentType > typedef EncodingType::Ch rapidjson::internal::Schema< SchemaDocumentType >::Ch
Definition at line 526 of file schema.h.
Context
template<typename SchemaDocumentType > typedef SchemaValidationContext<SchemaDocumentType> rapidjson::internal::Schema< SchemaDocumentType >::Context
Definition at line 527 of file schema.h.
EncodingType
template<typename SchemaDocumentType > typedef ValueType::EncodingType rapidjson::internal::Schema< SchemaDocumentType >::EncodingType
Definition at line 525 of file schema.h.
ErrorHandler
template<typename SchemaDocumentType > typedef IValidationErrorHandler<Schema> rapidjson::internal::Schema< SchemaDocumentType >::ErrorHandler
Definition at line 530 of file schema.h.
PointerType
template<typename SchemaDocumentType > typedef SchemaDocumentType::PointerType rapidjson::internal::Schema< SchemaDocumentType >::PointerType
Definition at line 524 of file schema.h.
RegexType
template<typename SchemaDocumentType > typedef internal::GenericRegex<EncodingType, AllocatorType> rapidjson::internal::Schema< SchemaDocumentType >::RegexType private
Definition at line 1344 of file schema.h.
SchemaType
template<typename SchemaDocumentType > typedef Schema<SchemaDocumentType> rapidjson::internal::Schema< SchemaDocumentType >::SchemaType
Definition at line 528 of file schema.h.
SValue
template<typename SchemaDocumentType > typedef GenericValue<EncodingType, AllocatorType> rapidjson::internal::Schema< SchemaDocumentType >::SValue
Definition at line 529 of file schema.h.
UriType
template<typename SchemaDocumentType > typedef GenericUri<ValueType, AllocatorType> rapidjson::internal::Schema< SchemaDocumentType >::UriType
Definition at line 531 of file schema.h.
ValueType
template<typename SchemaDocumentType > typedef SchemaDocumentType::ValueType rapidjson::internal::Schema< SchemaDocumentType >::ValueType
Definition at line 522 of file schema.h.
Member Enumeration Documentation
SchemaValueType
template<typename SchemaDocumentType > enum rapidjson::internal::Schema::SchemaValueType private
Enumerator
kNullSchemaType
kBooleanSchemaType
kObjectSchemaType
kArraySchemaType
kStringSchemaType
kNumberSchemaType
kIntegerSchemaType
kTotalSchemaType
Definition at line 1332 of file schema.h.
{
        kNullSchemaType,
        kBooleanSchemaType,
        kObjectSchemaType,
        kArraySchemaType,
        kStringSchemaType,
        kNumberSchemaType,
        kIntegerSchemaType,
        kTotalSchemaType
    };
Constructor & Destructor Documentation
Schema()
template<typename SchemaDocumentType > rapidjson::internal::Schema< SchemaDocumentType >::Schema (SchemaDocumentType * schemaDocument, const PointerType & p, const ValueType & value, const ValueType & document, AllocatorType * allocator, const UriType & id = UriType()) inline
Definition at line 534 of file schema.h.
                                                                                                                                                                                 :
        allocator_(allocator),
        uri_(schemaDocument->GetURI(), *allocator),
        id_(id, allocator),
        spec_(schemaDocument->GetSpecification()),
        pointer_(p, allocator),
        typeless_(schemaDocument->GetTypeless()),
        enum_(),
        enumCount_(),
        not_(),
        type_((1 << kTotalSchemaType) - 1), // typeless
        validatorCount_(),
        notValidatorIndex_(),
        properties_(),
        additionalPropertiesSchema_(),
        patternProperties_(),
        patternPropertyCount_(),
        propertyCount_(),
        minProperties_(),
        maxProperties_(SizeType(~0)),
        additionalProperties_(true),
        hasDependencies_(),
        hasRequired_(),
        hasSchemaDependencies_(),
        additionalItemsSchema_(),
        itemsList_(),
        itemsTuple_(),
        itemsTupleCount_(),
        minItems_(),
        maxItems_(SizeType(~0)),
        additionalItems_(true),
        uniqueItems_(false),
        pattern_(),
        minLength_(0),
        maxLength_(~SizeType(0)),
        exclusiveMinimum_(false),
        exclusiveMaximum_(false),
        defaultValueLength_(0),
        readOnly_(false),
        writeOnly_(false),
        nullable_(false)
    {
        GenericStringBuffer<EncodingType> sb;
        p.StringifyUriFragment(sb);
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Schema", sb.GetString(), id.GetString());
        typedef typename ValueType::ConstValueIterator ConstValueIterator;
        typedef typename ValueType::ConstMemberIterator ConstMemberIterator;
        // PR #1393
        // Early add this Schema and its $ref(s) in schemaDocument's map to avoid infinite
        // recursion (with recursive schemas), since schemaDocument->getSchema() is always
        // checked before creating a new one. Don't cache typeless_, though.
        if (this != typeless_) {
          typedef typename SchemaDocumentType::SchemaEntry SchemaEntry;
          SchemaEntry *entry = schemaDocument->schemaMap_.template Push<SchemaEntry>();
          new (entry) SchemaEntry(pointer_, this, true, allocator_);
          schemaDocument->AddSchemaRefs(this);
        }
        if (!value.IsObject())
            return;
        // If we have an id property, resolve it with the in-scope id
        // Not supported for open api 2.0 or 3.0
        if (spec_.oapi != kVersion20 && spec_.oapi != kVersion30)
        if (const ValueType* v = GetMember(value, GetIdString())) {
            if (v->IsString()) {
                UriType local(*v, allocator);
                id_ = local.Resolve(id_, allocator);
                    RAPIDJSON_SCHEMA_PRINT(SchemaIds, id.GetString(), v->GetString(), id_.GetString());
            }
        }
        if (const ValueType* v = GetMember(value, GetTypeString())) {
            type_ = 0;
            if (v->IsString())
                AddType(*v);
            else if (v->IsArray())
                for (ConstValueIterator itr = v->Begin(); itr != v->End(); ++itr)
                    AddType(*itr);
        }
        if (const ValueType* v = GetMember(value, GetEnumString())) {
            if (v->IsArray() && v->Size() > 0) {
                enum_ = static_cast<uint64_t*>(allocator_->Malloc(sizeof(uint64_t) * v->Size()));
                for (ConstValueIterator itr = v->Begin(); itr != v->End(); ++itr) {
                    typedef Hasher<EncodingType, MemoryPoolAllocator<AllocatorType> > EnumHasherType;
                    char buffer[256u + 24];
                    MemoryPoolAllocator<AllocatorType> hasherAllocator(buffer, sizeof(buffer));
                    EnumHasherType h(&hasherAllocator, 256);
                    itr->Accept(h);
                    enum_[enumCount_++] = h.GetHashCode();
                }
            }
        }
        if (schemaDocument)
            AssignIfExist(allOf_, *schemaDocument, p, value, GetAllOfString(), document);
        // AnyOf, OneOf, Not not supported for open api 2.0
        if (schemaDocument && spec_.oapi != kVersion20) {
            AssignIfExist(anyOf_, *schemaDocument, p, value, GetAnyOfString(), document);
            AssignIfExist(oneOf_, *schemaDocument, p, value, GetOneOfString(), document);
            if (const ValueType* v = GetMember(value, GetNotString())) {
                schemaDocument->CreateSchema(&not_, p.Append(GetNotString(), allocator_), *v, document, id_);
                notValidatorIndex_ = validatorCount_;
                validatorCount_++;
            }
        }
        // Object
        const ValueType* properties = GetMember(value, GetPropertiesString());
        const ValueType* required = GetMember(value, GetRequiredString());
        const ValueType* dependencies = GetMember(value, GetDependenciesString());
        {
            // Gather properties from properties/required/dependencies
            SValue allProperties(kArrayType);
            if (properties && properties->IsObject())
                for (ConstMemberIterator itr = properties->MemberBegin(); itr != properties->MemberEnd(); ++itr)
                    AddUniqueElement(allProperties, itr->name);
            if (required && required->IsArray())
                for (ConstValueIterator itr = required->Begin(); itr != required->End(); ++itr)
                    if (itr->IsString())
                        AddUniqueElement(allProperties, *itr);
            // Dependencies not supported for open api 2.0 and 3.0
            if (spec_.oapi != kVersion20 && spec_.oapi != kVersion30)
            if (dependencies && dependencies->IsObject())
                for (ConstMemberIterator itr = dependencies->MemberBegin(); itr != dependencies->MemberEnd(); ++itr) {
                    AddUniqueElement(allProperties, itr->name);
                    if (itr->value.IsArray())
                        for (ConstValueIterator i = itr->value.Begin(); i != itr->value.End(); ++i)
                            if (i->IsString())
                                AddUniqueElement(allProperties, *i);
                }
            if (allProperties.Size() > 0) {
                propertyCount_ = allProperties.Size();
                properties_ = static_cast<Property*>(allocator_->Malloc(sizeof(Property) * propertyCount_));
                for (SizeType i = 0; i < propertyCount_; i++) {
                    new (&properties_[i]) Property();
                    properties_[i].name = allProperties[i];
                    properties_[i].schema = typeless_;
                }
            }
        }
        if (properties && properties->IsObject()) {
            PointerType q = p.Append(GetPropertiesString(), allocator_);
            for (ConstMemberIterator itr = properties->MemberBegin(); itr != properties->MemberEnd(); ++itr) {
                SizeType index;
                if (FindPropertyIndex(itr->name, &index))
                    schemaDocument->CreateSchema(&properties_[index].schema, q.Append(itr->name, allocator_), itr->value, document, id_);
            }
        }
        // PatternProperties not supported for open api 2.0 and 3.0
        if (spec_.oapi != kVersion20 && spec_.oapi != kVersion30)
        if (const ValueType* v = GetMember(value, GetPatternPropertiesString())) {
            PointerType q = p.Append(GetPatternPropertiesString(), allocator_);
            patternProperties_ = static_cast<PatternProperty*>(allocator_->Malloc(sizeof(PatternProperty) * v->MemberCount()));
            patternPropertyCount_ = 0;
            for (ConstMemberIterator itr = v->MemberBegin(); itr != v->MemberEnd(); ++itr) {
                new (&patternProperties_[patternPropertyCount_]) PatternProperty();
                PointerType r = q.Append(itr->name, allocator_);
                patternProperties_[patternPropertyCount_].pattern = CreatePattern(itr->name, schemaDocument, r);
                schemaDocument->CreateSchema(&patternProperties_[patternPropertyCount_].schema, r, itr->value, document, id_);
                patternPropertyCount_++;
            }
        }
        if (required && required->IsArray())
            for (ConstValueIterator itr = required->Begin(); itr != required->End(); ++itr)
                if (itr->IsString()) {
                    SizeType index;
                    if (FindPropertyIndex(*itr, &index)) {
                        properties_[index].required = true;
                        hasRequired_ = true;
                    }
                }
        // Dependencies not supported for open api 2.0 and 3.0
        if (spec_.oapi != kVersion20 && spec_.oapi != kVersion30)
        if (dependencies && dependencies->IsObject()) {
            PointerType q = p.Append(GetDependenciesString(), allocator_);
            hasDependencies_ = true;
            for (ConstMemberIterator itr = dependencies->MemberBegin(); itr != dependencies->MemberEnd(); ++itr) {
                SizeType sourceIndex;
                if (FindPropertyIndex(itr->name, &sourceIndex)) {
                    if (itr->value.IsArray()) {
                        properties_[sourceIndex].dependencies = static_cast<bool*>(allocator_->Malloc(sizeof(bool) * propertyCount_));
                        std::memset(properties_[sourceIndex].dependencies, 0, sizeof(bool)* propertyCount_);
                        for (ConstValueIterator targetItr = itr->value.Begin(); targetItr != itr->value.End(); ++targetItr) {
                            SizeType targetIndex;
                            if (FindPropertyIndex(*targetItr, &targetIndex))
                                properties_[sourceIndex].dependencies[targetIndex] = true;
                        }
                    }
                    else if (itr->value.IsObject()) {
                        hasSchemaDependencies_ = true;
                        schemaDocument->CreateSchema(&properties_[sourceIndex].dependenciesSchema, q.Append(itr->name, allocator_), itr->value, document, id_);
                        properties_[sourceIndex].dependenciesValidatorIndex = validatorCount_;
                        validatorCount_++;
                    }
                }
            }
        }
        if (const ValueType* v = GetMember(value, GetAdditionalPropertiesString())) {
            if (v->IsBool())
                additionalProperties_ = v->GetBool();
            else if (v->IsObject())
                schemaDocument->CreateSchema(&additionalPropertiesSchema_, p.Append(GetAdditionalPropertiesString(), allocator_), *v, document, id_);
        }
        AssignIfExist(minProperties_, value, GetMinPropertiesString());
        AssignIfExist(maxProperties_, value, GetMaxPropertiesString());
        // Array
        if (const ValueType* v = GetMember(value, GetItemsString())) {
            PointerType q = p.Append(GetItemsString(), allocator_);
            if (v->IsObject()) // List validation
                schemaDocument->CreateSchema(&itemsList_, q, *v, document, id_);
            else if (v->IsArray()) { // Tuple validation
                itemsTuple_ = static_cast<const Schema**>(allocator_->Malloc(sizeof(const Schema*) * v->Size()));
                SizeType index = 0;
                for (ConstValueIterator itr = v->Begin(); itr != v->End(); ++itr, index++)
                    schemaDocument->CreateSchema(&itemsTuple_[itemsTupleCount_++], q.Append(index, allocator_), *itr, document, id_);
            }
        }
        AssignIfExist(minItems_, value, GetMinItemsString());
        AssignIfExist(maxItems_, value, GetMaxItemsString());
        // AdditionalItems not supported for openapi 2.0 and 3.0
        if (spec_.oapi != kVersion20 && spec_.oapi != kVersion30)
        if (const ValueType* v = GetMember(value, GetAdditionalItemsString())) {
            if (v->IsBool())
                additionalItems_ = v->GetBool();
            else if (v->IsObject())
                schemaDocument->CreateSchema(&additionalItemsSchema_, p.Append(GetAdditionalItemsString(), allocator_), *v, document, id_);
        }
        AssignIfExist(uniqueItems_, value, GetUniqueItemsString());
        // String
        AssignIfExist(minLength_, value, GetMinLengthString());
        AssignIfExist(maxLength_, value, GetMaxLengthString());
        if (const ValueType* v = GetMember(value, GetPatternString()))
            pattern_ = CreatePattern(*v, schemaDocument, p.Append(GetPatternString(), allocator_));
        // Number
        if (const ValueType* v = GetMember(value, GetMinimumString()))
            if (v->IsNumber())
                minimum_.CopyFrom(*v, *allocator_);
        if (const ValueType* v = GetMember(value, GetMaximumString()))
            if (v->IsNumber())
                maximum_.CopyFrom(*v, *allocator_);
        AssignIfExist(exclusiveMinimum_, value, GetExclusiveMinimumString());
        AssignIfExist(exclusiveMaximum_, value, GetExclusiveMaximumString());
        if (const ValueType* v = GetMember(value, GetMultipleOfString()))
            if (v->IsNumber() && v->GetDouble() > 0.0)
                multipleOf_.CopyFrom(*v, *allocator_);
        // Default
        if (const ValueType* v = GetMember(value, GetDefaultValueString()))
            if (v->IsString())
                defaultValueLength_ = v->GetStringLength();
        // ReadOnly - open api only (until draft 7 supported)
        // WriteOnly - open api 3 only (until draft 7 supported)
        // Both can't be true
        if (spec_.oapi != kVersionNone)
            AssignIfExist(readOnly_, value, GetReadOnlyString());
        if (spec_.oapi >= kVersion30)
            AssignIfExist(writeOnly_, value, GetWriteOnlyString());
        if (readOnly_ && writeOnly_)
            schemaDocument->SchemaError(kSchemaErrorReadOnlyAndWriteOnly, p);
        // Nullable - open api 3 only
        // If true add 'null' as allowable type
        if (spec_.oapi >= kVersion30) {
            AssignIfExist(nullable_, value, GetNullableString());
            if (nullable_)
                AddType(GetNullString());
        }
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), GetString(), rapidjson::kArrayType, rapidjson::kSchemaErrorReadOnlyAndWriteOnly, rapidjson::kVersion20, rapidjson::kVersion30, rapidjson::kVersionNone, Method, rapidjson::internal::Schema< SchemaDocumentType >::Property::name, rapidjson::internal::Schema< SchemaDocumentType >::PatternProperty::pattern, RAPIDJSON_SCHEMA_PRINT, rapidjson::GenericUri< ValueType, Allocator >::Resolve(), and rapidjson::value.
~Schema()
template<typename SchemaDocumentType > rapidjson::internal::Schema< SchemaDocumentType >::~Schema () inline
Definition at line 832 of file schema.h.
              {
        AllocatorType::Free(enum_);
        if (properties_) {
            for (SizeType i = 0; i < propertyCount_; i++)
                properties_[i].~Property();
            AllocatorType::Free(properties_);
        }
        if (patternProperties_) {
            for (SizeType i = 0; i < patternPropertyCount_; i++)
                patternProperties_[i].~PatternProperty();
            AllocatorType::Free(patternProperties_);
        }
        AllocatorType::Free(itemsTuple_);
#if RAPIDJSON_SCHEMA_HAS_REGEX
        if (pattern_) {
            pattern_->~RegexType();
            AllocatorType::Free(pattern_);
        }
#endif
    }
Member Function Documentation
AddType()
template<typename SchemaDocumentType > void rapidjson::internal::Schema< SchemaDocumentType >::AddType (const ValueType & type) inline private
Definition at line 1449 of file schema.h.
{
        if      (type == GetNullString()   ) type_ |= 1 << kNullSchemaType;
        else if (type == GetBooleanString()) type_ |= 1 << kBooleanSchemaType;
        else if (type == GetObjectString() ) type_ |= 1 << kObjectSchemaType;
        else if (type == GetArrayString()  ) type_ |= 1 << kArraySchemaType;
        else if (type == GetStringString() ) type_ |= 1 << kStringSchemaType;
        else if (type == GetIntegerString()) type_ |= 1 << kIntegerSchemaType;
        else if (type == GetNumberString() ) type_ |= (1 << kNumberSchemaType) | (1 << kIntegerSchemaType);
    }
AddUniqueElement()
template<typename SchemaDocumentType > template<typename V1 , typename V2 > void rapidjson::internal::Schema< SchemaDocumentType >::AddUniqueElement (V1 & a, const V2 & v) inline private
Definition at line 1360 of file schema.h.
{
        for (typename V1::ConstValueIterator itr = a.Begin(); itr != a.End(); ++itr)
            if (*itr == v)
                return;
        V1 c(v, *allocator_);
        a.PushBack(c, *allocator_);
    }
References rapidjson::a.
AssignIfExist() [1/3]
template<typename SchemaDocumentType > static void rapidjson::internal::Schema< SchemaDocumentType >::AssignIfExist (bool & out, const ValueType & value, const ValueType & name) inline static private
Definition at line 1373 of file schema.h.
{
        if (const ValueType* v = GetMember(value, name))
            if (v->IsBool())
                out = v->GetBool();
    }
References rapidjson::value.
AssignIfExist() [2/3]
template<typename SchemaDocumentType > void rapidjson::internal::Schema< SchemaDocumentType >::AssignIfExist (SchemaArray & out, SchemaDocumentType & schemaDocument, const PointerType & p, const ValueType & value, const ValueType & name, const ValueType & document) inline private
Definition at line 1385 of file schema.h.
{
        if (const ValueType* v = GetMember(value, name)) {
            if (v->IsArray() && v->Size() > 0) {
                PointerType q = p.Append(name, allocator_);
                out.count = v->Size();
                out.schemas = static_cast<const Schema**>(allocator_->Malloc(out.count * sizeof(const Schema*)));
                memset(out.schemas, 0, sizeof(Schema*)* out.count);
                for (SizeType i = 0; i < out.count; i++)
                    schemaDocument.CreateSchema(&out.schemas[i], q.Append(i, allocator_), (*v)[i], document, id_);
                out.begin = validatorCount_;
                validatorCount_ += out.count;
            }
        }
    }
References rapidjson::internal::Schema< SchemaDocumentType >::SchemaArray::begin, rapidjson::internal::Schema< SchemaDocumentType >::SchemaArray::count, rapidjson::internal::Schema< SchemaDocumentType >::SchemaArray::schemas, and rapidjson::value.
AssignIfExist() [3/3]
template<typename SchemaDocumentType > static void rapidjson::internal::Schema< SchemaDocumentType >::AssignIfExist (SizeType & out, const ValueType & value, const ValueType & name) inline static private
Definition at line 1379 of file schema.h.
{
        if (const ValueType* v = GetMember(value, name))
            if (v->IsUint64() && v->GetUint64() <= SizeType(~0))
                out = static_cast<SizeType>(v->GetUint64());
    }
References rapidjson::value.
BeginValue()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::BeginValue (Context & context) const inline
Definition at line 869 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::BeginValue");
        if (context.inArray) {
            if (uniqueItems_)
                context.valueUniqueness = true;
            if (itemsList_)
                context.valueSchema = itemsList_;
            else if (itemsTuple_) {
                if (context.arrayElementIndex < itemsTupleCount_)
                    context.valueSchema = itemsTuple_[context.arrayElementIndex];
                else if (additionalItemsSchema_)
                    context.valueSchema = additionalItemsSchema_;
                else if (additionalItems_)
                    context.valueSchema = typeless_;
                else {
                    context.error_handler.DisallowedItem(context.arrayElementIndex);
                    // Must set valueSchema for when kValidateContinueOnErrorFlag is set, else reports spurious type error
                    context.valueSchema = typeless_;
                    // Must bump arrayElementIndex for when kValidateContinueOnErrorFlag is set
                    context.arrayElementIndex++;
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorAdditionalItems);
                }
            }
            else
                context.valueSchema = typeless_;
            context.arrayElementIndex++;
        }
        return true;
    }
References rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::arrayElementIndex, rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedItem(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::inArray, rapidjson::kValidateErrorAdditionalItems, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, RAPIDJSON_SCHEMA_PRINT, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::valueSchema, and rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::valueUniqueness.
Bool()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Bool (Context & context, bool b) const inline
Definition at line 1001 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Bool", b);
        if (!CheckBool(context, b))
            return false;
        return CreateParallelValidator(context);
    }
References Method, and RAPIDJSON_SCHEMA_PRINT.
CheckBool()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CheckBool (Context & context, bool) const inline private
Definition at line 1524 of file schema.h.
{
        if (!(type_ & (1 << kBooleanSchemaType))) {
            DisallowedType(context, GetBooleanString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        return true;
    }
References rapidjson::kValidateErrorType, and RAPIDJSON_INVALID_KEYWORD_RETURN.
CheckDoubleMaximum()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMaximum (Context & context, double d) const inline private
Definition at line 1636 of file schema.h.
{
        if (exclusiveMaximum_ ? d >= maximum_.GetDouble() : d > maximum_.GetDouble()) {
            context.error_handler.AboveMaximum(d, maximum_, exclusiveMaximum_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMaximum_ ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum);
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::AboveMaximum(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorExclusiveMaximum, rapidjson::kValidateErrorMaximum, and RAPIDJSON_INVALID_KEYWORD_RETURN.
CheckDoubleMinimum()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMinimum (Context & context, double d) const inline private
Definition at line 1628 of file schema.h.
{
        if (exclusiveMinimum_ ? d <= minimum_.GetDouble() : d < minimum_.GetDouble()) {
            context.error_handler.BelowMinimum(d, minimum_, exclusiveMinimum_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMinimum_ ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum);
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::BelowMinimum(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorExclusiveMinimum, rapidjson::kValidateErrorMinimum, and RAPIDJSON_INVALID_KEYWORD_RETURN.
CheckDoubleMultipleOf()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf (Context & context, double d) const inline private
Definition at line 1644 of file schema.h.
{
        double a = std::abs(d), b = std::abs(multipleOf_.GetDouble());
        double q = std::floor(a / b);
        double r = a - q * b;
        if (r > 0.0) {
            context.error_handler.NotMultipleOf(d, multipleOf_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMultipleOf);
        }
        return true;
    }
References rapidjson::a, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorMultipleOf, rapidjson::internal::IValidationErrorHandler< SchemaType >::NotMultipleOf(), and RAPIDJSON_INVALID_KEYWORD_RETURN.
CheckInt()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CheckInt (Context & context, int64_t i) const inline private
Definition at line 1532 of file schema.h.
{
        if (!(type_ & ((1 << kIntegerSchemaType) | (1 << kNumberSchemaType)))) {
            DisallowedType(context, GetIntegerString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        if (!minimum_.IsNull()) {
            if (minimum_.IsInt64()) {
                if (exclusiveMinimum_ ? i <= minimum_.GetInt64() : i < minimum_.GetInt64()) {
                    context.error_handler.BelowMinimum(i, minimum_, exclusiveMinimum_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMinimum_ ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum);
                }
            }
            else if (minimum_.IsUint64()) {
                context.error_handler.BelowMinimum(i, minimum_, exclusiveMinimum_);
                RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMinimum_ ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum); // i <= max(int64_t) < minimum.GetUint64()
            }
            else if (!CheckDoubleMinimum(context, static_cast<double>(i)))
                return false;
        }
        if (!maximum_.IsNull()) {
            if (maximum_.IsInt64()) {
                if (exclusiveMaximum_ ? i >= maximum_.GetInt64() : i > maximum_.GetInt64()) {
                    context.error_handler.AboveMaximum(i, maximum_, exclusiveMaximum_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMaximum_ ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum);
                }
            }
            else if (maximum_.IsUint64()) { }
                /* do nothing */ // i <= max(int64_t) < maximum_.GetUint64()
            else if (!CheckDoubleMaximum(context, static_cast<double>(i)))
                return false;
        }
        if (!multipleOf_.IsNull()) {
            if (multipleOf_.IsUint64()) {
                if (static_cast<uint64_t>(i >= 0 ? i : -i) % multipleOf_.GetUint64() != 0) {
                    context.error_handler.NotMultipleOf(i, multipleOf_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMultipleOf);
                }
            }
            else if (!CheckDoubleMultipleOf(context, static_cast<double>(i)))
                return false;
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::AboveMaximum(), rapidjson::internal::IValidationErrorHandler< SchemaType >::BelowMinimum(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorExclusiveMaximum, rapidjson::kValidateErrorExclusiveMinimum, rapidjson::kValidateErrorMaximum, rapidjson::kValidateErrorMinimum, rapidjson::kValidateErrorMultipleOf, rapidjson::kValidateErrorType, rapidjson::internal::IValidationErrorHandler< SchemaType >::NotMultipleOf(), and RAPIDJSON_INVALID_KEYWORD_RETURN.
CheckUint()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CheckUint (Context & context, uint64_t i) const inline private
Definition at line 1580 of file schema.h.
{
        if (!(type_ & ((1 << kIntegerSchemaType) | (1 << kNumberSchemaType)))) {
            DisallowedType(context, GetIntegerString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        if (!minimum_.IsNull()) {
            if (minimum_.IsUint64()) {
                if (exclusiveMinimum_ ? i <= minimum_.GetUint64() : i < minimum_.GetUint64()) {
                    context.error_handler.BelowMinimum(i, minimum_, exclusiveMinimum_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMinimum_ ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum);
                }
            }
            else if (minimum_.IsInt64())
                /* do nothing */; // i >= 0 > minimum.Getint64()
            else if (!CheckDoubleMinimum(context, static_cast<double>(i)))
                return false;
        }
        if (!maximum_.IsNull()) {
            if (maximum_.IsUint64()) {
                if (exclusiveMaximum_ ? i >= maximum_.GetUint64() : i > maximum_.GetUint64()) {
                    context.error_handler.AboveMaximum(i, maximum_, exclusiveMaximum_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMaximum_ ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum);
                }
            }
            else if (maximum_.IsInt64()) {
                context.error_handler.AboveMaximum(i, maximum_, exclusiveMaximum_);
                RAPIDJSON_INVALID_KEYWORD_RETURN(exclusiveMaximum_ ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum); // i >= 0 > maximum_
            }
            else if (!CheckDoubleMaximum(context, static_cast<double>(i)))
                return false;
        }
        if (!multipleOf_.IsNull()) {
            if (multipleOf_.IsUint64()) {
                if (i % multipleOf_.GetUint64() != 0) {
                    context.error_handler.NotMultipleOf(i, multipleOf_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMultipleOf);
                }
            }
            else if (!CheckDoubleMultipleOf(context, static_cast<double>(i)))
                return false;
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::AboveMaximum(), rapidjson::internal::IValidationErrorHandler< SchemaType >::BelowMinimum(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorExclusiveMaximum, rapidjson::kValidateErrorExclusiveMinimum, rapidjson::kValidateErrorMaximum, rapidjson::kValidateErrorMinimum, rapidjson::kValidateErrorMultipleOf, rapidjson::kValidateErrorType, rapidjson::internal::IValidationErrorHandler< SchemaType >::NotMultipleOf(), and RAPIDJSON_INVALID_KEYWORD_RETURN.
CreateParallelValidator()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::CreateParallelValidator (Context & context) const inline private
Definition at line 1462 of file schema.h.
{
        if (enum_ || context.arrayUniqueness)
            context.hasher = context.factory.CreateHasher();
        if (validatorCount_) {
            RAPIDJSON_ASSERT(context.validators == 0);
            context.validators = static_cast<ISchemaValidator**>(context.factory.MallocState(sizeof(ISchemaValidator*) * validatorCount_));
            std::memset(context.validators, 0, sizeof(ISchemaValidator*) * validatorCount_);
            context.validatorCount = validatorCount_;
            // Always return after first failure for these sub-validators
            if (allOf_.schemas)
                CreateSchemaValidators(context, allOf_, false);
            if (anyOf_.schemas)
                CreateSchemaValidators(context, anyOf_, false);
            if (oneOf_.schemas)
                CreateSchemaValidators(context, oneOf_, false);
            if (not_)
                context.validators[notValidatorIndex_] = context.factory.CreateSchemaValidator(*not_, false);
            if (hasSchemaDependencies_) {
                for (SizeType i = 0; i < propertyCount_; i++)
                    if (properties_[i].dependenciesSchema)
                        context.validators[properties_[i].dependenciesValidatorIndex] = context.factory.CreateSchemaValidator(*properties_[i].dependenciesSchema, false);
            }
        }
        // Add any other type-independent checks here
        if (readOnly_ && (context.flags & kValidateWriteFlag)) {
            context.error_handler.DisallowedWhenWriting();
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorReadOnly);
        }
        if (writeOnly_ && (context.flags & kValidateReadFlag)) {
            context.error_handler.DisallowedWhenReading();
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorWriteOnly);
        }
        return true;
    }
References rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::arrayUniqueness, rapidjson::internal::ISchemaStateFactory< SchemaType >::CreateHasher(), rapidjson::internal::ISchemaStateFactory< SchemaType >::CreateSchemaValidator(), rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedWhenReading(), rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedWhenWriting(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::factory, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::flags, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::hasher, rapidjson::kValidateErrorReadOnly, rapidjson::kValidateErrorWriteOnly, rapidjson::kValidateReadFlag, rapidjson::kValidateWriteFlag, rapidjson::internal::ISchemaStateFactory< SchemaType >::MallocState(), RAPIDJSON_ASSERT, RAPIDJSON_INVALID_KEYWORD_RETURN, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::validatorCount, and rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::validators.
CreatePattern()
template<typename SchemaDocumentType > template<typename ValueType > RegexType * rapidjson::internal::Schema< SchemaDocumentType >::CreatePattern (const ValueType & value, SchemaDocumentType * sd, const PointerType & p) inline private
Definition at line 1402 of file schema.h.
{
        if (value.IsString()) {
            RegexType* r = new (allocator_->Malloc(sizeof(RegexType))) RegexType(value.GetString(), allocator_);
            if (!r->IsValid()) {
                sd->SchemaErrorValue(kSchemaErrorRegexInvalid, p, value.GetString(), value.GetStringLength());
                r->~RegexType();
                AllocatorType::Free(r);
                r = 0;
            }
            return r;
        }
        return 0;
    }
References rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), rapidjson::kSchemaErrorRegexInvalid, and rapidjson::value.
CreateSchemaValidators()
template<typename SchemaDocumentType > void rapidjson::internal::Schema< SchemaDocumentType >::CreateSchemaValidators (Context & context, const SchemaArray & schemas, const bool inheritContinueOnErrors) const inline private
Definition at line 1505 of file schema.h.
{
        for (SizeType i = 0; i < schemas.count; i++)
            context.validators[schemas.begin + i] = context.factory.CreateSchemaValidator(*schemas.schemas[i], inheritContinueOnErrors);
    }
References rapidjson::internal::Schema< SchemaDocumentType >::SchemaArray::begin, rapidjson::internal::Schema< SchemaDocumentType >::SchemaArray::count, rapidjson::internal::ISchemaStateFactory< SchemaType >::CreateSchemaValidator(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::factory, rapidjson::internal::Schema< SchemaDocumentType >::SchemaArray::schemas, and rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::validators.
DisallowedType()
template<typename SchemaDocumentType > void rapidjson::internal::Schema< SchemaDocumentType >::DisallowedType (Context & context, const ValueType & actualType) const inline private
Definition at line 1655 of file schema.h.
{
        ErrorHandler& eh = context.error_handler;
        eh.StartDisallowedType();
        if (type_ & (1 << kNullSchemaType)) eh.AddExpectedType(GetNullString());
        if (type_ & (1 << kBooleanSchemaType)) eh.AddExpectedType(GetBooleanString());
        if (type_ & (1 << kObjectSchemaType)) eh.AddExpectedType(GetObjectString());
        if (type_ & (1 << kArraySchemaType)) eh.AddExpectedType(GetArrayString());
        if (type_ & (1 << kStringSchemaType)) eh.AddExpectedType(GetStringString());
        if (type_ & (1 << kNumberSchemaType)) eh.AddExpectedType(GetNumberString());
        else if (type_ & (1 << kIntegerSchemaType)) eh.AddExpectedType(GetIntegerString());
        eh.EndDisallowedType(actualType);
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::AddExpectedType(), rapidjson::internal::IValidationErrorHandler< SchemaType >::EndDisallowedType(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, and rapidjson::internal::IValidationErrorHandler< SchemaType >::StartDisallowedType().
Double()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Double (Context & context, double d) const inline
Definition at line 1036 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Double", d);
        if (!(type_ & (1 << kNumberSchemaType))) {
            DisallowedType(context, GetNumberString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        if (!minimum_.IsNull() && !CheckDoubleMinimum(context, d))
            return false;
        if (!maximum_.IsNull() && !CheckDoubleMaximum(context, d))
            return false;
        if (!multipleOf_.IsNull() && !CheckDoubleMultipleOf(context, d))
            return false;
        return CreateParallelValidator(context);
    }
References rapidjson::kValidateErrorType, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, and RAPIDJSON_SCHEMA_PRINT.
EndArray()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::EndArray (Context & context, SizeType elementCount) const inline
Definition at line 1220 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::EndArray");
        context.inArray = false;
        if (elementCount < minItems_) {
            context.error_handler.TooFewItems(elementCount, minItems_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMinItems);
        }
        if (elementCount > maxItems_) {
            context.error_handler.TooManyItems(elementCount, maxItems_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMaxItems);
        }
        return true;
    }
References rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::inArray, rapidjson::kValidateErrorMaxItems, rapidjson::kValidateErrorMinItems, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, RAPIDJSON_SCHEMA_PRINT, rapidjson::internal::IValidationErrorHandler< SchemaType >::TooFewItems(), and rapidjson::internal::IValidationErrorHandler< SchemaType >::TooManyItems().
EndObject()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::EndObject (Context & context, SizeType memberCount) const inline
Definition at line 1159 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::EndObject");
        if (hasRequired_) {
            context.error_handler.StartMissingProperties();
            for (SizeType index = 0; index < propertyCount_; index++)
                if (properties_[index].required && !context.propertyExist[index])
                    if (properties_[index].schema->defaultValueLength_ == 0 )
                        context.error_handler.AddMissingProperty(properties_[index].name);
            if (context.error_handler.EndMissingProperties())
                RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorRequired);
        }
        if (memberCount < minProperties_) {
            context.error_handler.TooFewProperties(memberCount, minProperties_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMinProperties);
        }
        if (memberCount > maxProperties_) {
            context.error_handler.TooManyProperties(memberCount, maxProperties_);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMaxProperties);
        }
        if (hasDependencies_) {
            context.error_handler.StartDependencyErrors();
            for (SizeType sourceIndex = 0; sourceIndex < propertyCount_; sourceIndex++) {
                const Property& source = properties_[sourceIndex];
                if (context.propertyExist[sourceIndex]) {
                    if (source.dependencies) {
                        context.error_handler.StartMissingDependentProperties();
                        for (SizeType targetIndex = 0; targetIndex < propertyCount_; targetIndex++)
                            if (source.dependencies[targetIndex] && !context.propertyExist[targetIndex])
                                context.error_handler.AddMissingDependentProperty(properties_[targetIndex].name);
                        context.error_handler.EndMissingDependentProperties(source.name);
                    }
                    else if (source.dependenciesSchema) {
                        ISchemaValidator* dependenciesValidator = context.validators[source.dependenciesValidatorIndex];
                        if (!dependenciesValidator->IsValid())
                            context.error_handler.AddDependencySchemaError(source.name, dependenciesValidator);
                    }
                }
            }
            if (context.error_handler.EndDependencyErrors())
                RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorDependencies);
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::AddDependencySchemaError(), rapidjson::internal::IValidationErrorHandler< SchemaType >::AddMissingDependentProperty(), rapidjson::internal::IValidationErrorHandler< SchemaType >::AddMissingProperty(), rapidjson::internal::IValidationErrorHandler< SchemaType >::EndDependencyErrors(), rapidjson::internal::IValidationErrorHandler< SchemaType >::EndMissingDependentProperties(), rapidjson::internal::IValidationErrorHandler< SchemaType >::EndMissingProperties(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::internal::ISchemaValidator::IsValid(), rapidjson::kValidateErrorDependencies, rapidjson::kValidateErrorMaxProperties, rapidjson::kValidateErrorMinProperties, rapidjson::kValidateErrorRequired, Method, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::propertyExist, RAPIDJSON_INVALID_KEYWORD_RETURN, RAPIDJSON_SCHEMA_PRINT, rapidjson::source, rapidjson::internal::IValidationErrorHandler< SchemaType >::StartDependencyErrors(), rapidjson::internal::IValidationErrorHandler< SchemaType >::StartMissingDependentProperties(), rapidjson::internal::IValidationErrorHandler< SchemaType >::StartMissingProperties(), rapidjson::internal::IValidationErrorHandler< SchemaType >::TooFewProperties(), rapidjson::internal::IValidationErrorHandler< SchemaType >::TooManyProperties(), and rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::validators.
EndValue()
template<typename SchemaDocumentType > RAPIDJSON_FORCEINLINE bool rapidjson::internal::Schema< SchemaDocumentType >::EndValue (Context & context) const inline
Definition at line 901 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::EndValue");
        // Only check pattern properties if we have validators
        if (context.patternPropertiesValidatorCount > 0) {
            bool otherValid = false;
            SizeType count = context.patternPropertiesValidatorCount;
            if (context.objectPatternValidatorType != Context::kPatternValidatorOnly)
                otherValid = context.patternPropertiesValidators[--count]->IsValid();
            bool patternValid = true;
            for (SizeType i = 0; i < count; i++)
                if (!context.patternPropertiesValidators[i]->IsValid()) {
                    patternValid = false;
                    break;
                }
            if (context.objectPatternValidatorType == Context::kPatternValidatorOnly) {
                if (!patternValid) {
                    context.error_handler.PropertyViolations(context.patternPropertiesValidators, count);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorPatternProperties);
                }
            }
            else if (context.objectPatternValidatorType == Context::kPatternValidatorWithProperty) {
                if (!patternValid || !otherValid) {
                    context.error_handler.PropertyViolations(context.patternPropertiesValidators, count + 1);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorPatternProperties);
                }
            }
            else if (!patternValid && !otherValid) { // kPatternValidatorWithAdditionalProperty)
                context.error_handler.PropertyViolations(context.patternPropertiesValidators, count + 1);
                RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorPatternProperties);
            }
        }
        // For enums only check if we have a hasher
        if (enum_ && context.hasher) {
            const uint64_t h = context.factory.GetHashCode(context.hasher);
            for (SizeType i = 0; i < enumCount_; i++)
                if (enum_[i] == h)
                    goto foundEnum;
            context.error_handler.DisallowedValue(kValidateErrorEnum);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorEnum);
            foundEnum:;
        }
        // Only check allOf etc if we have validators
        if (context.validatorCount > 0) {
            if (allOf_.schemas)
                for (SizeType i = allOf_.begin; i < allOf_.begin + allOf_.count; i++)
                    if (!context.validators[i]->IsValid()) {
                        context.error_handler.NotAllOf(&context.validators[allOf_.begin], allOf_.count);
                        RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorAllOf);
                    }
            if (anyOf_.schemas) {
                for (SizeType i = anyOf_.begin; i < anyOf_.begin + anyOf_.count; i++)
                    if (context.validators[i]->IsValid())
                        goto foundAny;
                context.error_handler.NoneOf(&context.validators[anyOf_.begin], anyOf_.count);
                RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorAnyOf);
                foundAny:;
            }
            if (oneOf_.schemas) {
                bool oneValid = false;
                SizeType firstMatch = 0;
                for (SizeType i = oneOf_.begin; i < oneOf_.begin + oneOf_.count; i++)
                    if (context.validators[i]->IsValid()) {
                        if (oneValid) {
                            context.error_handler.MultipleOneOf(firstMatch, i - oneOf_.begin);
                            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorOneOfMatch);
                        } else {
                            oneValid = true;
                            firstMatch = i - oneOf_.begin;
                        }
                    }
                if (!oneValid) {
                    context.error_handler.NotOneOf(&context.validators[oneOf_.begin], oneOf_.count);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorOneOf);
                }
            }
            if (not_ && context.validators[notValidatorIndex_]->IsValid()) {
                context.error_handler.Disallowed();
                RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorNot);
            }
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::Disallowed(), rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedValue(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::factory, rapidjson::internal::ISchemaStateFactory< SchemaType >::GetHashCode(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::hasher, rapidjson::internal::ISchemaValidator::IsValid(), rapidjson::kValidateErrorAllOf, rapidjson::kValidateErrorAnyOf, rapidjson::kValidateErrorEnum, rapidjson::kValidateErrorNot, rapidjson::kValidateErrorOneOf, rapidjson::kValidateErrorOneOfMatch, rapidjson::kValidateErrorPatternProperties, Method, rapidjson::internal::IValidationErrorHandler< SchemaType >::MultipleOneOf(), rapidjson::internal::IValidationErrorHandler< SchemaType >::NoneOf(), rapidjson::internal::IValidationErrorHandler< SchemaType >::NotAllOf(), rapidjson::internal::IValidationErrorHandler< SchemaType >::NotOneOf(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::objectPatternValidatorType, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesValidatorCount, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesValidators, rapidjson::internal::IValidationErrorHandler< SchemaType >::PropertyViolations(), RAPIDJSON_INVALID_KEYWORD_RETURN, RAPIDJSON_SCHEMA_PRINT, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::validatorCount, and rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::validators.
FindPropertyIndex()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::FindPropertyIndex (const ValueType & name, SizeType * outIndex) const inline private
Definition at line 1511 of file schema.h.
{
        SizeType len = name.GetStringLength();
        const Ch* str = name.GetString();
        for (SizeType index = 0; index < propertyCount_; index++)
            if (properties_[index].name.GetStringLength() == len &&
                (std::memcmp(properties_[index].name.GetString(), str, sizeof(Ch) * len) == 0))
            {
                *outIndex = index;
                return true;
            }
        return false;
    }
GetAdditionalItemsString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetAdditionalItemsString () inline static
Definition at line 1309 of file schema.h.
GetAdditionalPropertiesString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetAdditionalPropertiesString () inline static
Definition at line 1303 of file schema.h.
GetAllOfString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetAllOfString () inline static
Definition at line 1295 of file schema.h.
GetAnyOfString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetAnyOfString () inline static
Definition at line 1296 of file schema.h.
GetArrayString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetArrayString () inline static
Definition at line 1289 of file schema.h.
GetBooleanString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetBooleanString () inline static
Definition at line 1287 of file schema.h.
GetDefaultValueString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetDefaultValueString () inline static
Definition at line 1319 of file schema.h.
GetDependenciesString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetDependenciesString () inline static
Definition at line 1301 of file schema.h.
GetEnumString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetEnumString () inline static
Definition at line 1294 of file schema.h.
GetExclusiveMaximumString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetExclusiveMaximumString () inline static
Definition at line 1317 of file schema.h.
GetExclusiveMinimumString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetExclusiveMinimumString () inline static
Definition at line 1316 of file schema.h.
GetId()
template<typename SchemaDocumentType > const UriType & rapidjson::internal::Schema< SchemaDocumentType >::GetId () const inline
Definition at line 857 of file schema.h.
{
        return id_;
    }
GetIdString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetIdString () inline static
Definition at line 1322 of file schema.h.
GetIntegerString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetIntegerString () inline static
Definition at line 1292 of file schema.h.
GetItemsString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetItemsString () inline static
Definition at line 1306 of file schema.h.
GetMaximumString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMaximumString () inline static
Definition at line 1315 of file schema.h.
GetMaxItemsString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMaxItemsString () inline static
Definition at line 1308 of file schema.h.
GetMaxLengthString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMaxLengthString () inline static
Definition at line 1312 of file schema.h.
GetMaxPropertiesString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMaxPropertiesString () inline static
Definition at line 1305 of file schema.h.
GetMember()
template<typename SchemaDocumentType > static const ValueType * rapidjson::internal::Schema< SchemaDocumentType >::GetMember (const ValueType & value, const ValueType & name) inline static private
Definition at line 1368 of file schema.h.
{
        typename ValueType::ConstMemberIterator itr = value.FindMember(name);
        return itr != value.MemberEnd() ? &(itr->value) : 0;
    }
References rapidjson::value.
GetMinimumString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMinimumString () inline static
Definition at line 1314 of file schema.h.
GetMinItemsString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMinItemsString () inline static
Definition at line 1307 of file schema.h.
GetMinLengthString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMinLengthString () inline static
Definition at line 1311 of file schema.h.
GetMinPropertiesString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMinPropertiesString () inline static
Definition at line 1304 of file schema.h.
GetMultipleOfString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetMultipleOfString () inline static
Definition at line 1318 of file schema.h.
GetNotString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetNotString () inline static
Definition at line 1298 of file schema.h.
GetNullableString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetNullableString () inline static
Definition at line 1327 of file schema.h.
GetNullString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetNullString () inline static
Definition at line 1286 of file schema.h.
GetNumberString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetNumberString () inline static
Definition at line 1291 of file schema.h.
GetObjectString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetObjectString () inline static
Definition at line 1288 of file schema.h.
GetOneOfString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetOneOfString () inline static
Definition at line 1297 of file schema.h.
GetOpenApiString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetOpenApiString () inline static
Definition at line 1324 of file schema.h.
GetPatternPropertiesString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetPatternPropertiesString () inline static
Definition at line 1302 of file schema.h.
GetPatternString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetPatternString () inline static
Definition at line 1313 of file schema.h.
GetPointer()
template<typename SchemaDocumentType > const PointerType & rapidjson::internal::Schema< SchemaDocumentType >::GetPointer () const inline
Definition at line 865 of file schema.h.
{
        return pointer_;
    }
GetPropertiesString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetPropertiesString () inline static
Definition at line 1299 of file schema.h.
GetReadOnlyString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetReadOnlyString () inline static
Definition at line 1325 of file schema.h.
GetRefString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetRefString () inline static
Definition at line 1321 of file schema.h.
GetRequiredString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetRequiredString () inline static
Definition at line 1300 of file schema.h.
GetSchemaString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetSchemaString () inline static
Definition at line 1320 of file schema.h.
GetSpecification()
template<typename SchemaDocumentType > const Specification & rapidjson::internal::Schema< SchemaDocumentType >::GetSpecification () const inline
Definition at line 861 of file schema.h.
{
        return spec_;
    }
GetStringString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetStringString () inline static
Definition at line 1290 of file schema.h.
GetSwaggerString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetSwaggerString () inline static
Definition at line 1323 of file schema.h.
GetTypeString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetTypeString () inline static
Definition at line 1293 of file schema.h.
GetUniqueItemsString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetUniqueItemsString () inline static
Definition at line 1310 of file schema.h.
GetURI()
template<typename SchemaDocumentType > const SValue & rapidjson::internal::Schema< SchemaDocumentType >::GetURI () const inline
Definition at line 853 of file schema.h.
{
        return uri_;
    }
GetValidateErrorKeyword()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetValidateErrorKeyword (ValidateErrorCode validateErrorCode) inline static
Definition at line 1237 of file schema.h.
{
        switch (validateErrorCode) {
            case kValidateErrorMultipleOf:              return GetMultipleOfString();
            case kValidateErrorMaximum:                 return GetMaximumString();
            case kValidateErrorExclusiveMaximum:        return GetMaximumString(); // Same
            case kValidateErrorMinimum:                 return GetMinimumString();
            case kValidateErrorExclusiveMinimum:        return GetMinimumString(); // Same
            case kValidateErrorMaxLength:               return GetMaxLengthString();
            case kValidateErrorMinLength:               return GetMinLengthString();
            case kValidateErrorPattern:                 return GetPatternString();
            case kValidateErrorMaxItems:                return GetMaxItemsString();
            case kValidateErrorMinItems:                return GetMinItemsString();
            case kValidateErrorUniqueItems:             return GetUniqueItemsString();
            case kValidateErrorAdditionalItems:         return GetAdditionalItemsString();
            case kValidateErrorMaxProperties:           return GetMaxPropertiesString();
            case kValidateErrorMinProperties:           return GetMinPropertiesString();
            case kValidateErrorRequired:                return GetRequiredString();
            case kValidateErrorAdditionalProperties:    return GetAdditionalPropertiesString();
            case kValidateErrorPatternProperties:       return GetPatternPropertiesString();
            case kValidateErrorDependencies:            return GetDependenciesString();
            case kValidateErrorEnum:                    return GetEnumString();
            case kValidateErrorType:                    return GetTypeString();
            case kValidateErrorOneOf:                   return GetOneOfString();
            case kValidateErrorOneOfMatch:              return GetOneOfString(); // Same
            case kValidateErrorAllOf:                   return GetAllOfString();
            case kValidateErrorAnyOf:                   return GetAnyOfString();
            case kValidateErrorNot:                     return GetNotString();
            case kValidateErrorReadOnly:                return GetReadOnlyString();
            case kValidateErrorWriteOnly:               return GetWriteOnlyString();
            default:                                    return GetNullString();
        }
    }
References rapidjson::kValidateErrorAdditionalItems, rapidjson::kValidateErrorAdditionalProperties, rapidjson::kValidateErrorAllOf, rapidjson::kValidateErrorAnyOf, rapidjson::kValidateErrorDependencies, rapidjson::kValidateErrorEnum, rapidjson::kValidateErrorExclusiveMaximum, rapidjson::kValidateErrorExclusiveMinimum, rapidjson::kValidateErrorMaximum, rapidjson::kValidateErrorMaxItems, rapidjson::kValidateErrorMaxLength, rapidjson::kValidateErrorMaxProperties, rapidjson::kValidateErrorMinimum, rapidjson::kValidateErrorMinItems, rapidjson::kValidateErrorMinLength, rapidjson::kValidateErrorMinProperties, rapidjson::kValidateErrorMultipleOf, rapidjson::kValidateErrorNot, rapidjson::kValidateErrorOneOf, rapidjson::kValidateErrorOneOfMatch, rapidjson::kValidateErrorPattern, rapidjson::kValidateErrorPatternProperties, rapidjson::kValidateErrorReadOnly, rapidjson::kValidateErrorRequired, rapidjson::kValidateErrorType, rapidjson::kValidateErrorUniqueItems, and rapidjson::kValidateErrorWriteOnly.
GetWriteOnlyString()
template<typename SchemaDocumentType > static const ValueType & rapidjson::internal::Schema< SchemaDocumentType >::GetWriteOnlyString () inline static
Definition at line 1326 of file schema.h.
Int()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Int (Context & context, int i) const inline
Definition at line 1008 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Int", (int64_t)i);
        if (!CheckInt(context, i))
            return false;
        return CreateParallelValidator(context);
    }
References Method, and RAPIDJSON_SCHEMA_PRINT.
Int64()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Int64 (Context & context, int64_t i) const inline
Definition at line 1022 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Int64", i);
        if (!CheckInt(context, i))
            return false;
        return CreateParallelValidator(context);
    }
References Method, and RAPIDJSON_SCHEMA_PRINT.
IsPatternMatch()
template<typename SchemaDocumentType > static bool rapidjson::internal::Schema< SchemaDocumentType >::IsPatternMatch (const RegexType * pattern, const Ch * str, SizeType) inline static private
Definition at line 1416 of file schema.h.
{
        GenericRegexSearch<RegexType> rs(*pattern);
        return rs.Search(str);
    }
References rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search().
Key()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Key (Context & context, const Ch * str, SizeType len, bool) const inline
Definition at line 1106 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Key", str);
        if (patternProperties_) {
            context.patternPropertiesSchemaCount = 0;
            for (SizeType i = 0; i < patternPropertyCount_; i++)
                if (patternProperties_[i].pattern && IsPatternMatch(patternProperties_[i].pattern, str, len)) {
                    context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = patternProperties_[i].schema;
                    context.valueSchema = typeless_;
                }
        }
        SizeType index  = 0;
        if (FindPropertyIndex(ValueType(str, len).Move(), &index)) {
            if (context.patternPropertiesSchemaCount > 0) {
                context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = properties_[index].schema;
                context.valueSchema = typeless_;
                context.valuePatternValidatorType = Context::kPatternValidatorWithProperty;
            }
            else
                context.valueSchema = properties_[index].schema;
            if (context.propertyExist)
                context.propertyExist[index] = true;
            return true;
        }
        if (additionalPropertiesSchema_) {
            if (context.patternPropertiesSchemaCount > 0) {
                context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = additionalPropertiesSchema_;
                context.valueSchema = typeless_;
                context.valuePatternValidatorType = Context::kPatternValidatorWithAdditionalProperty;
            }
            else
                context.valueSchema = additionalPropertiesSchema_;
            return true;
        }
        else if (additionalProperties_) {
            context.valueSchema = typeless_;
            return true;
        }
        if (context.patternPropertiesSchemaCount == 0) { // patternProperties are not additional properties
            // Must set valueSchema for when kValidateContinueOnErrorFlag is set, else reports spurious type error
            context.valueSchema = typeless_;
            context.error_handler.DisallowedProperty(str, len);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorAdditionalProperties);
        }
        return true;
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedProperty(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorAdditionalProperties, Method, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemaCount, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemas, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::propertyExist, RAPIDJSON_INVALID_KEYWORD_RETURN, RAPIDJSON_SCHEMA_PRINT, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::valuePatternValidatorType, and rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::valueSchema.
Null()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Null (Context & context) const inline
Definition at line 992 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Null");
        if (!(type_ & (1 << kNullSchemaType))) {
            DisallowedType(context, GetNullString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        return CreateParallelValidator(context);
    }
References rapidjson::kValidateErrorType, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, and RAPIDJSON_SCHEMA_PRINT.
StartArray()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::StartArray (Context & context) const inline
Definition at line 1207 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::StartArray");
        context.arrayElementIndex = 0;
        context.inArray = true;  // Ensure we note that we are in an array
        if (!(type_ & (1 << kArraySchemaType))) {
            DisallowedType(context, GetArrayString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        return CreateParallelValidator(context);
    }
References rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::arrayElementIndex, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::inArray, rapidjson::kValidateErrorType, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, and RAPIDJSON_SCHEMA_PRINT.
StartObject()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::StartObject (Context & context) const inline
Definition at line 1084 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::StartObject");
        if (!(type_ & (1 << kObjectSchemaType))) {
            DisallowedType(context, GetObjectString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        if (hasDependencies_ || hasRequired_) {
            context.propertyExist = static_cast<bool*>(context.factory.MallocState(sizeof(bool) * propertyCount_));
            std::memset(context.propertyExist, 0, sizeof(bool) * propertyCount_);
        }
        if (patternProperties_) { // pre-allocate schema array
            SizeType count = patternPropertyCount_ + 1; // extra for valuePatternValidatorType
            context.patternPropertiesSchemas = static_cast<const SchemaType**>(context.factory.MallocState(sizeof(const SchemaType*) * count));
            context.patternPropertiesSchemaCount = 0;
            std::memset(context.patternPropertiesSchemas, 0, sizeof(SchemaType*) * count);
        }
        return CreateParallelValidator(context);
    }
References rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::factory, rapidjson::kValidateErrorType, rapidjson::internal::ISchemaStateFactory< SchemaType >::MallocState(), Method, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemaCount, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemas, rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::propertyExist, RAPIDJSON_INVALID_KEYWORD_RETURN, and RAPIDJSON_SCHEMA_PRINT.
String()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::String (Context & context, const Ch * str, SizeType length, bool) const inline
Definition at line 1055 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::String", str);
        if (!(type_ & (1 << kStringSchemaType))) {
            DisallowedType(context, GetStringString());
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorType);
        }
        if (minLength_ != 0 || maxLength_ != SizeType(~0)) {
            SizeType count;
            if (internal::CountStringCodePoint<EncodingType>(str, length, &count)) {
                if (count < minLength_) {
                    context.error_handler.TooShort(str, length, minLength_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMinLength);
                }
                if (count > maxLength_) {
                    context.error_handler.TooLong(str, length, maxLength_);
                    RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorMaxLength);
                }
            }
        }
        if (pattern_ && !IsPatternMatch(pattern_, str, length)) {
            context.error_handler.DoesNotMatch(str, length);
            RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorPattern);
        }
        return CreateParallelValidator(context);
    }
References rapidjson::internal::IValidationErrorHandler< SchemaType >::DoesNotMatch(), rapidjson::internal::SchemaValidationContext< SchemaDocumentType >::error_handler, rapidjson::kValidateErrorMaxLength, rapidjson::kValidateErrorMinLength, rapidjson::kValidateErrorPattern, rapidjson::kValidateErrorType, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, RAPIDJSON_SCHEMA_PRINT, rapidjson::internal::IValidationErrorHandler< SchemaType >::TooLong(), and rapidjson::internal::IValidationErrorHandler< SchemaType >::TooShort().
Uint()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Uint (Context & context, unsigned u) const inline
Definition at line 1015 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Uint", (uint64_t)u);
        if (!CheckUint(context, u))
            return false;
        return CreateParallelValidator(context);
    }
References Method, and RAPIDJSON_SCHEMA_PRINT.
Uint64()
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::Uint64 (Context & context, uint64_t u) const inline
Definition at line 1029 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "Schema::Uint64", u);
        if (!CheckUint(context, u))
            return false;
        return CreateParallelValidator(context);
    }
References Method, and RAPIDJSON_SCHEMA_PRINT.
Friends And Related Symbol Documentation
GenericSchemaDocument< ValueType, AllocatorType >
template<typename SchemaDocumentType > friend class GenericSchemaDocument< ValueType, AllocatorType > friend
Definition at line 531 of file schema.h.
Member Data Documentation
additionalItems_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::additionalItems_ private
Definition at line 1728 of file schema.h.
additionalItemsSchema_
template<typename SchemaDocumentType > const SchemaType* rapidjson::internal::Schema< SchemaDocumentType >::additionalItemsSchema_ private
Definition at line 1722 of file schema.h.
additionalProperties_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::additionalProperties_ private
Definition at line 1717 of file schema.h.
additionalPropertiesSchema_
template<typename SchemaDocumentType > const SchemaType* rapidjson::internal::Schema< SchemaDocumentType >::additionalPropertiesSchema_ private
Definition at line 1711 of file schema.h.
allocator_
template<typename SchemaDocumentType > AllocatorType* rapidjson::internal::Schema< SchemaDocumentType >::allocator_ private
Definition at line 1694 of file schema.h.
allOf_
template<typename SchemaDocumentType > SchemaArray rapidjson::internal::Schema< SchemaDocumentType >::allOf_ private
Definition at line 1702 of file schema.h.
anyOf_
template<typename SchemaDocumentType > SchemaArray rapidjson::internal::Schema< SchemaDocumentType >::anyOf_ private
Definition at line 1703 of file schema.h.
defaultValueLength_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::defaultValueLength_ private
Definition at line 1741 of file schema.h.
enum_
template<typename SchemaDocumentType > uint64_t* rapidjson::internal::Schema< SchemaDocumentType >::enum_ private
Definition at line 1700 of file schema.h.
enumCount_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::enumCount_ private
Definition at line 1701 of file schema.h.
exclusiveMaximum_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::exclusiveMaximum_ private
Definition at line 1739 of file schema.h.
exclusiveMinimum_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::exclusiveMinimum_ private
Definition at line 1738 of file schema.h.
hasDependencies_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::hasDependencies_ private
Definition at line 1718 of file schema.h.
hasRequired_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::hasRequired_ private
Definition at line 1719 of file schema.h.
hasSchemaDependencies_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::hasSchemaDependencies_ private
Definition at line 1720 of file schema.h.
id_
template<typename SchemaDocumentType > UriType rapidjson::internal::Schema< SchemaDocumentType >::id_ private
Definition at line 1696 of file schema.h.
itemsList_
template<typename SchemaDocumentType > const SchemaType* rapidjson::internal::Schema< SchemaDocumentType >::itemsList_ private
Definition at line 1723 of file schema.h.
itemsTuple_
template<typename SchemaDocumentType > const SchemaType** rapidjson::internal::Schema< SchemaDocumentType >::itemsTuple_ private
Definition at line 1724 of file schema.h.
itemsTupleCount_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::itemsTupleCount_ private
Definition at line 1725 of file schema.h.
maximum_
template<typename SchemaDocumentType > SValue rapidjson::internal::Schema< SchemaDocumentType >::maximum_ private
Definition at line 1736 of file schema.h.
maxItems_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::maxItems_ private
Definition at line 1727 of file schema.h.
maxLength_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::maxLength_ private
Definition at line 1733 of file schema.h.
maxProperties_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::maxProperties_ private
Definition at line 1716 of file schema.h.
minimum_
template<typename SchemaDocumentType > SValue rapidjson::internal::Schema< SchemaDocumentType >::minimum_ private
Definition at line 1735 of file schema.h.
minItems_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::minItems_ private
Definition at line 1726 of file schema.h.
minLength_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::minLength_ private
Definition at line 1732 of file schema.h.
minProperties_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::minProperties_ private
Definition at line 1715 of file schema.h.
multipleOf_
template<typename SchemaDocumentType > SValue rapidjson::internal::Schema< SchemaDocumentType >::multipleOf_ private
Definition at line 1737 of file schema.h.
not_
template<typename SchemaDocumentType > const SchemaType* rapidjson::internal::Schema< SchemaDocumentType >::not_ private
Definition at line 1705 of file schema.h.
notValidatorIndex_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::notValidatorIndex_ private
Definition at line 1708 of file schema.h.
nullable_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::nullable_ private
Definition at line 1745 of file schema.h.
oneOf_
template<typename SchemaDocumentType > SchemaArray rapidjson::internal::Schema< SchemaDocumentType >::oneOf_ private
Definition at line 1704 of file schema.h.
pattern_
template<typename SchemaDocumentType > RegexType* rapidjson::internal::Schema< SchemaDocumentType >::pattern_ private
Definition at line 1731 of file schema.h.
patternProperties_
template<typename SchemaDocumentType > PatternProperty* rapidjson::internal::Schema< SchemaDocumentType >::patternProperties_ private
Definition at line 1712 of file schema.h.
patternPropertyCount_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::patternPropertyCount_ private
Definition at line 1713 of file schema.h.
pointer_
template<typename SchemaDocumentType > PointerType rapidjson::internal::Schema< SchemaDocumentType >::pointer_ private
Definition at line 1698 of file schema.h.
properties_
template<typename SchemaDocumentType > Property* rapidjson::internal::Schema< SchemaDocumentType >::properties_ private
Definition at line 1710 of file schema.h.
propertyCount_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::propertyCount_ private
Definition at line 1714 of file schema.h.
readOnly_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::readOnly_ private
Definition at line 1743 of file schema.h.
spec_
template<typename SchemaDocumentType > Specification rapidjson::internal::Schema< SchemaDocumentType >::spec_ private
Definition at line 1697 of file schema.h.
type_
template<typename SchemaDocumentType > unsigned rapidjson::internal::Schema< SchemaDocumentType >::type_ private
Definition at line 1706 of file schema.h.
typeless_
template<typename SchemaDocumentType > const SchemaType* rapidjson::internal::Schema< SchemaDocumentType >::typeless_ private
Definition at line 1699 of file schema.h.
uniqueItems_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::uniqueItems_ private
Definition at line 1729 of file schema.h.
uri_
template<typename SchemaDocumentType > SValue rapidjson::internal::Schema< SchemaDocumentType >::uri_ private
Definition at line 1695 of file schema.h.
validatorCount_
template<typename SchemaDocumentType > SizeType rapidjson::internal::Schema< SchemaDocumentType >::validatorCount_ private
Definition at line 1707 of file schema.h.
writeOnly_
template<typename SchemaDocumentType > bool rapidjson::internal::Schema< SchemaDocumentType >::writeOnly_ private
Definition at line 1744 of file schema.h.
The documentation for this class was generated from the following file:
rapidjson/include/rapidjson/schema.h