wiNpoS: WinPosWnd Class Reference
WinPosWnd Class Reference
#include <WinPosWnd.h>
Classes
struct MonitorPreview
struct WinPosPreview
Public Member Functions
void create (POINT pt, HWND hParentWnd)
create the required windows for monitor preview and all configured positions
void destroy ()
destroys every windows
FLOAT getScale ()
HWND getWndHandle ()
Static Public Member Functions
static WinPosWnd * getWinPosWnd (HWND hWnd)
get the instance of WinPosWnd to a window handle
Private Types
using PosPreviewCfgs = WinPosWndCfg::PosPreviewCfgs
using MonitorPreviewPtr = std::shared_ptr< MonitorPreview >
using WinPosPreviewPtr = std::shared_ptr< WinPosPreview >
using WinPosPreviews = std::vector< WinPosPreviewPtr >
using MonitorPreviews = std::vector< std::shared_ptr< MonitorPreview > >
using RectVector = std::vector< RECT >
Private Member Functions
RECT getTotalPreviewRect (POINT pt, const RectVector &monitorRects)
void correctEdgecases (POINT pt, const RECT &totalRect)
if the window looks beyond the edge of the monitor, it is moved so that it is displayed as a whole on this monitor
LRESULT WndProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
the main WNDPROC for the WinPosWnd instances
Static Private Member Functions
static WNDCLASS * initWndClass ()
initialize the WNDCLASS structure
static LRESULT CALLBACK WndProcStatic (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
static WNDPROC. Forwards to the WinPosWnd instances.
Private Attributes
std::vector< HWND > _hWnds
MonitorPreviews _previews
RECT _totalRect = { 0 }
UINT _closeTimeout = 3500
FLOAT _scale = 0.12f
Static Private Attributes
static const WNDCLASS * wndClass = nullptr
pointer to WNDCLASS structure from WinPosWnd
static std::map< HWND, WinPosWnd * > hWndToWinPosMap
map, contains all window handles for every instance of WinPosWnd
Detailed Description
Definition at line 11 of file WinPosWnd.h.
Member Typedef Documentation
MonitorPreviewPtr
using WinPosWnd::MonitorPreviewPtr = std::shared_ptr<MonitorPreview> private
Definition at line 25 of file WinPosWnd.h.
MonitorPreviews
using WinPosWnd::MonitorPreviews = std::vector<std::shared_ptr<MonitorPreview> > private
Definition at line 59 of file WinPosWnd.h.
PosPreviewCfgs
using WinPosWnd::PosPreviewCfgs = WinPosWndCfg::PosPreviewCfgs private
Definition at line 23 of file WinPosWnd.h.
RectVector
using WinPosWnd::RectVector = std::vector<RECT> private
Definition at line 73 of file WinPosWnd.h.
WinPosPreviewPtr
using WinPosWnd::WinPosPreviewPtr = std::shared_ptr<WinPosPreview> private
Definition at line 37 of file WinPosWnd.h.
WinPosPreviews
using WinPosWnd::WinPosPreviews = std::vector<WinPosPreviewPtr> private
Definition at line 38 of file WinPosWnd.h.
Member Function Documentation
correctEdgecases()
void WinPosWnd::correctEdgecases (POINT pt, const RECT & totalRect) private
if the window looks beyond the edge of the monitor, it is moved so that it is displayed as a whole on this monitor
Parameters
pt
totalRect
Definition at line 171 of file WinPosWnd.cpp.
{
    HMONITOR hMonitor = MonitorFromPoint(pt, MONITOR_DEFAULTTONEAREST);
    if (hMonitor)
    {
        MONITORINFOEX mi = { sizeof(MONITORINFOEX) };
        GetMonitorInfo(hMonitor, &mi);
        const RECT& mr = mi.rcWork;
        using std::make_tuple;
        using std::get;
        enum { X, Y };
        auto offset = make_tuple(0, 0);
        if (totalRect.left < mr.left)
            offset = make_tuple(mr.left - totalRect.left, get<Y>(offset));
        if (totalRect.right > mr.right)
            offset = make_tuple(-(totalRect.right - mr.right), get<Y>(offset));
        if (totalRect.top < mr.top)
            offset = make_tuple(get<X>(offset), mr.top - totalRect.top);
        if (totalRect.bottom > mr.bottom)
            offset = make_tuple(get<X>(offset), -(totalRect.bottom - mr.bottom));
        if (offset != std::make_tuple(0, 0))
        {
            for (auto& mp : _previews)
                OffsetRect(&mp->prvRect, get<X>(offset), get<Y>(offset));
        }
    }
}
References _previews.
create()
void WinPosWnd::create (POINT pt, HWND hParentWnd)
create the required windows for monitor preview and all configured positions
Parameters
pt point where the window should displayed
hParentWnd the main window handle
Definition at line 223 of file WinPosWnd.cpp.
{
    using std::views::transform;
    using std::ranges::to;
    using MonitorConfig = WinPosWndCfg::MonitorConfig;
    if (wndClass == nullptr)
        wndClass = initWndClass();
    destroy();
    WinPosWndCfg config;
    config.readConfig();
    _closeTimeout = config.getCloseTimeout();
    _scale = config.getScale();
    auto monitorConfigs = config.getMonitors();
    RectVector monitorRects = monitorConfigs | transform([](const MonitorConfig& mc) { return mc.monitorRect; }) | to<RectVector>();
    RECT totalRect = getTotalPreviewRect(pt, monitorRects);
    _previews = monitorConfigs | transform([pt, totalRect, this](const MonitorConfig& mc)
        {
            MonitorPreview mp = { *this, 0, mc.monitorRect, mc.previewRect, mc.name, mc.device };
            mp.offsetToPt(pt, totalRect);
            auto res = std::make_shared<MonitorPreview>(mp);
            res->createWinPosPreviews(mc.previews, res);
            return res;
        }) | to<MonitorPreviews>();
    correctEdgecases(pt, totalRect);
    _totalRect = totalRect;
    for (auto& mp : _previews)
    {
        HWND hWnd = mp->create(hParentWnd);
        _hWnds.push_back(hWnd);
        WinPosWnd::hWndToWinPosMap[hWnd] = this;
    }
    if(!_hWnds.empty())
    {
        //SetCapture(_hWnds.front());
        SetTimer(_hWnds.front(), CLOSE_TIMER, _closeTimeout, (TIMERPROC)nullptr);
    }
}
References _closeTimeout, _hWnds, _previews, _scale, _totalRect, correctEdgecases(), destroy(), WinPosWndCfg::getCloseTimeout(), WinPosWndCfg::getMonitors(), WinPosWndCfg::getScale(), getTotalPreviewRect(), hWndToWinPosMap, initWndClass(), WinPosWnd::MonitorPreview::monitorRect, WinPosWnd::MonitorPreview::offsetToPt(), WinPosWndCfg::readConfig(), and wndClass.
destroy()
void WinPosWnd::destroy ()
destroys every windows
Definition at line 275 of file WinPosWnd.cpp.
{
    for (HWND hWnd : _hWnds)
        DestroyWindow(hWnd);
    _hWnds.clear();
}
References _hWnds.
getScale()
FLOAT WinPosWnd::getScale () inline
Definition at line 17 of file WinPosWnd.h.
{ return _scale; }
References _scale.
getTotalPreviewRect()
RECT WinPosWnd::getTotalPreviewRect (POINT pt, const RectVector & monitorRects) private
Parameters
monitorRects
pt
Returns
Definition at line 139 of file WinPosWnd.cpp.
{
    RECT tpr = { 0 };
    for (const RECT& r : monitorRects)
    {
        //RECT pr = tpr;
        tpr.right += r.right - r.left;
        tpr.top = std::min(tpr.top, r.top);
        tpr.bottom = std::max(tpr.bottom, r.bottom);
        //UnionRect(&tpr, &pr, &r);
    }
    tpr = ScaleRect(tpr, _scale);
    OffsetRect(&tpr, pt.x - ((tpr.right - tpr.left) / 2), pt.y);
    return tpr;
}
References _scale.
getWinPosWnd()
WinPosWnd * WinPosWnd::getWinPosWnd (HWND hWnd) static
get the instance of WinPosWnd to a window handle
Parameters
hWnd
Definition at line 210 of file WinPosWnd.cpp.
{
    auto it = WinPosWnd::hWndToWinPosMap.find(hWnd);
    if (it != WinPosWnd::hWndToWinPosMap.end())
        return it->second;
    return nullptr;
}
References hWndToWinPosMap.
getWndHandle()
HWND WinPosWnd::getWndHandle ()
Returns
the first window handle in the list. NULL if if none is available
Definition at line 158 of file WinPosWnd.cpp.
{
    if (_hWnds.empty())
        return NULL;
    return _hWnds.front();
}
References _hWnds.
initWndClass()
WNDCLASS * WinPosWnd::initWndClass () static private
initialize the WNDCLASS structure
Returns
pointer to global WNDCLASS structure
Definition at line 37 of file WinPosWnd.cpp.
{
    static const std::wstring className = L"wiNpoSWnd";
    static WNDCLASS wcl = { 0 };
    wcl.hbrBackground = (HBRUSH)COLOR_WINDOW;
    wcl.hCursor = LoadCursor(NULL, IDC_ARROW);
    wcl.hInstance = hInstance;
    wcl.lpszClassName = className.c_str();
    wcl.lpfnWndProc = WinPosWnd::WndProcStatic;
    WORD res = RegisterClass(&wcl);
    return &wcl;
}
References hInstance, and WndProcStatic().
WndProc()
LRESULT WinPosWnd::WndProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) private
the main WNDPROC for the WinPosWnd instances
Definition at line 64 of file WinPosWnd.cpp.
{
    using std::ranges::find_if;
    switch (message)
    {
        case WM_TIMER:
            if (wParam == CLOSE_TIMER)
            {
                destroy();
            }
            break;
        case WM_DESTROY:
        {
            WinPosWnd::hWndToWinPosMap.erase(hWnd);
            break;
        }
        case WM_KEYDOWN:
        {
            WRITE_DEBUG_LOG_DETAIL("WM_KEYDOWN", format("Hwnd: {:#010x}, wParam: {}", (uint64_t)hWnd, wParam));
            if (wParam == VK_ESCAPE)
            {
                destroy();
                return  DefWindowProc(hWnd, message, wParam, lParam);
            }
            break;
        }
        case WM_LBUTTONUP:
        {
            POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };
            auto it = find_if(_previews, [hWnd](auto& mp) { return mp->hWnd == hWnd; });
            if (it != _previews.end())
                (*it)->onLButtonDown(pt);
            destroy();
            break;
        }
        case WM_MOUSEMOVE:
        {
            if (!_hWnds.empty())
                SetTimer(_hWnds.front(), CLOSE_TIMER, _closeTimeout, (TIMERPROC)nullptr);
            POINT pt = { 0 };
            GetCursorPos(&pt);
            for (auto& mp : _previews)
                mp->onMouseMove(pt);
            //WRITE_DEBUG_LOG_DETAIL("WM_MOUSEMOVE", format("Hwnd: {:#010x}, x:{}, y: {}", (uint64_t)hWnd, pt.x, pt.y));
            break;
        }
        case WM_PAINT:
        {
            PAINTSTRUCT ps;
            HDC hDc = BeginPaint(hWnd, &ps);
            auto it = find_if(_previews, [hWnd](auto mp) { return mp->hWnd == hWnd; });
            if (it != _previews.end())
                (*it)->paint(ps, hDc);
            EndPaint(hWnd, &ps);
            break;
        }
        default:
            break;
    }
    return DefWindowProc(hWnd, message, wParam, lParam);
}
References _closeTimeout, _hWnds, _previews, destroy(), hWndToWinPosMap, and WRITE_DEBUG_LOG_DETAIL.
WndProcStatic()
LRESULT CALLBACK WinPosWnd::WndProcStatic (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) static private
static WNDPROC. Forwards to the WinPosWnd instances.
Definition at line 54 of file WinPosWnd.cpp.
{
    if (WinPosWnd* winPosWnd = getWinPosWnd(hWnd))
        return winPosWnd->WndProc(hWnd, message, wParam, lParam);
    return DefWindowProc(hWnd, message, wParam, lParam);
}
References getWinPosWnd().
Member Data Documentation
_closeTimeout
UINT WinPosWnd::_closeTimeout = 3500 private
Definition at line 69 of file WinPosWnd.h.
_hWnds
std::vector<HWND> WinPosWnd::_hWnds private
Definition at line 64 of file WinPosWnd.h.
_previews
MonitorPreviews WinPosWnd::_previews private
Definition at line 66 of file WinPosWnd.h.
_scale
FLOAT WinPosWnd::_scale = 0.12f private
Definition at line 70 of file WinPosWnd.h.
_totalRect
RECT WinPosWnd::_totalRect = { 0 } private
Definition at line 68 of file WinPosWnd.h.
{ 0 };
hWndToWinPosMap
std::map< HWND, WinPosWnd * > WinPosWnd::hWndToWinPosMap static private
map, contains all window handles for every instance of WinPosWnd
Definition at line 63 of file WinPosWnd.h.
wndClass
const WNDCLASS * WinPosWnd::wndClass = nullptr static private
pointer to WNDCLASS structure from WinPosWnd
Definition at line 62 of file WinPosWnd.h.
The documentation for this class was generated from the following files:
wiNpoS-Hook/WinPosWnd.h
wiNpoS-Hook/WinPosWnd.cpp