wiNpoS: testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer > Class Template Reference
testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> LhsView
typedef LhsView::type LhsStlContainer
typedef LhsView::const_reference LhsStlContainerReference
typedef LhsStlContainer::value_type LhsValue
typedef ::testing::tuple< const LhsValue &, const RhsValue & > InnerMatcherArg
Public Member Functions
Impl (const TupleMatcher &tuple_matcher, const RhsStlContainer &rhs)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (LhsContainer lhs, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< InnerMatcherArg > mono_tuple_matcher_
const RhsStlContainer rhs_
Detailed Description
template<typename TupleMatcher, typename RhsContainer>
template<typename LhsContainer>
class testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >
Definition at line 3018 of file gmock-matchers.h.
Member Typedef Documentation
InnerMatcherArg
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > typedef ::testing::tuple<const LhsValue&, const RhsValue&> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::InnerMatcherArg
Definition at line 3029 of file gmock-matchers.h.
LhsStlContainer
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > typedef LhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainer
Definition at line 3022 of file gmock-matchers.h.
LhsStlContainerReference
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > typedef LhsView::const_reference testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsStlContainerReference
Definition at line 3023 of file gmock-matchers.h.
LhsValue
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > typedef LhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsValue
Definition at line 3024 of file gmock-matchers.h.
LhsView
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(LhsContainer)> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::LhsView
Definition at line 3021 of file gmock-matchers.h.
Constructor & Destructor Documentation
Impl()
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::Impl (const TupleMatcher & tuple_matcher, const RhsStlContainer & rhs) inline
Definition at line 3031 of file gmock-matchers.h.
        : mono_tuple_matcher_(SafeMatcherCast<InnerMatcherArg>(tuple_matcher)),
          rhs_(rhs) {}
Member Function Documentation
DescribeNegationTo()
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3043 of file gmock-matchers.h.
{
      *os << "doesn't contain exactly " << rhs_.size()
          << " values, or contains a value x at some index i"
          << " where x and the i-th value of ";
      UniversalPrint(rhs_, os);
      *os << " ";
      mono_tuple_matcher_.DescribeNegationTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::mono_tuple_matcher_, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::rhs_, and testing::internal::UniversalPrint().
DescribeTo()
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > virtual void testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3036 of file gmock-matchers.h.
{
      *os << "contains " << rhs_.size()
          << " values, where each value and its corresponding value in ";
      UniversalPrinter<RhsStlContainer>::Print(rhs_, os);
      *os << " ";
      mono_tuple_matcher_.DescribeTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeTo(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::mono_tuple_matcher_, testing::internal::UniversalPrinter< T >::Print(), and testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::rhs_.
GTEST_DISALLOW_ASSIGN_()
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::GTEST_DISALLOW_ASSIGN_ (Impl< LhsContainer >) private
MatchAndExplain()
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > virtual bool testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 3052 of file gmock-matchers.h.
{
      LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
      const size_t actual_size = lhs_stl_container.size();
      if (actual_size != rhs_.size()) {
        *listener << "which contains " << actual_size << " values";
        return false;
      }
      typename LhsStlContainer::const_iterator left = lhs_stl_container.begin();
      typename RhsStlContainer::const_iterator right = rhs_.begin();
      for (size_t i = 0; i != actual_size; ++i, ++left, ++right) {
        if (listener->IsInterested()) {
          StringMatchResultListener inner_listener;
          // Create InnerMatcherArg as a temporarily object to avoid it outlives
          // *left and *right. Dereference or the conversion to `const T&` may
          // return temp objects, e.g for vector<bool>.
          if (!mono_tuple_matcher_.MatchAndExplain(
                  InnerMatcherArg(ImplicitCast_<const LhsValue&>(*left),
                                  ImplicitCast_<const RhsValue&>(*right)),
                  &inner_listener)) {
            *listener << "where the value pair (";
            UniversalPrint(*left, listener->stream());
            *listener << ", ";
            UniversalPrint(*right, listener->stream());
            *listener << ") at index #" << i << " don't match";
            PrintIfNotEmpty(inner_listener.str(), listener->stream());
            return false;
          }
        } else {
          if (!mono_tuple_matcher_.Matches(
                  InnerMatcherArg(ImplicitCast_<const LhsValue&>(*left),
                                  ImplicitCast_<const RhsValue&>(*right))))
            return false;
        }
      }
      return true;
    }
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::MatchResultListener::IsInterested(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::mono_tuple_matcher_, testing::internal::PrintIfNotEmpty(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::rhs_, testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and testing::internal::UniversalPrint().
Member Data Documentation
mono_tuple_matcher_
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > const Matcher<InnerMatcherArg> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::mono_tuple_matcher_ private
Definition at line 3093 of file gmock-matchers.h.
rhs_
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > const RhsStlContainer testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::rhs_ private
Definition at line 3094 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h