wiNpoS: testing::Test Class Reference
testing::Test Class Reference abstract
Inherited by testing::TestWithParam< int >, testing::TestWithParam< std::string >, testing::TestWithParam< MyType >, testing::TestWithParam< std::pair< size_t, size_t > >, testing::TestWithParam< std::pair< int, int > >, AdHocTestResultTest, CommonTest< T >, EncodedStreamTest, ExpectFailureTest, FatalFailureInFixtureConstructorTest, FatalFailureInSetUpTest, FileStreamTest, FooTest, GMockOutputTest, MacroNamingTestNonParametrized, NonFatalFailureInFixtureConstructorTest, NonFatalFailureInSetUpTest, NonParameterizedBaseTest, Predicate1Test, Predicate2Test, Predicate3Test, Predicate4Test, Predicate5Test, PropertyOne, PropertyTwo, ProtectedFixtureMethodsTest, TEST_F_before_TEST_in_same_test_case, TEST_before_TEST_F_in_same_test_case, TypeParamTest< T >, TypedTest< T >, anonymous_namespace{gmock-actions_test.cc}::SetErrnoAndReturnTest, anonymous_namespace{gmock-spec-builders_test.cc}::PartialOrderTest, anonymous_namespace{gmock-spec-builders_test.cc}::VerboseFlagPreservingFixture, anonymous_namespace{gtest-linked_ptr_test.cc}::LinkedPtrTest, anonymous_namespace{gtest-test-part_test.cc}::TestPartResultArrayTest, anonymous_namespace{gtest-test-part_test.cc}::TestPartResultTest, anonymous_namespace{gtest-tuple_test.cc}::BigTupleTest, anonymous_namespace{gtest_filter_unittest_.cc}::FooTest, anonymous_namespace{gtest_unittest.cc}::AnotherSubClassOfTest, anonymous_namespace{gtest_unittest.cc}::DisabledTestsTest, anonymous_namespace{gtest_unittest.cc}::FRIEND_TEST_Test2, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >, anonymous_namespace{gtest_unittest.cc}::FormatEpochTimeInMillisAsIso8601Test, anonymous_namespace{gtest_unittest.cc}::GTestFlagSaverTest, anonymous_namespace{gtest_unittest.cc}::NoFatalFailureTest, anonymous_namespace{gtest_unittest.cc}::ScopedFakeTestPartResultReporterTest, anonymous_namespace{gtest_unittest.cc}::ShouldShardTest, anonymous_namespace{gtest_unittest.cc}::SingleEvaluationTest, anonymous_namespace{gtest_unittest.cc}::SubClassOfTest, anonymous_namespace{gtest_unittest.cc}::TestLifeCycleTest, anonymous_namespace{gtest_unittest.cc}::TestResultTest, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest, anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3, anonymous_namespace{sample5_unittest.cc}::QuickTest, anonymous_namespace{sample6_unittest.cc}::PrimeTableTest< T >, bar::MixedUpTestCaseTest, bar::MixedUpTestCaseWithSameTestNameTest, foo::MixedUpTestCaseTest, foo::MixedUpTestCaseWithSameTestNameTest, testing::CodeLocationForTESTF, testing::CodeLocationForTYPEDTEST< T >, testing::CodeLocationForTYPEDTESTP< T >, testing::CurrentTestInfoTest, testing::ParseFlagsTest, testing::SetUpTestCaseTest, testing::TestInfoTest, testing::TestWithParam< T >, testing::gmock_generated_function_mockers_test::FunctionMockerTest, testing::gmock_matchers_test::BacktrackingBPMTest, testing::gmock_matchers_test::FloatingPointTest< RawType >, testing::gmock_matchers_test::UnorderedElementsAreTest, testing::internal::ListenerTest, testing::internal::UnitTestRecordPropertyTestHelper, testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::LogIsVisibleTest, testing::internal::anonymous_namespace{gtest-filepath_test.cc}::DirectoryCreationTest, and testing::internal::anonymous_namespace{gtest-options_test.cc}::XmlOutputChangeDirTest.
Classes
struct Setup_should_be_spelled_SetUp
Public Types
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions
virtual ~Test ()
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions
Test ()
virtual void SetUp ()
virtual void TearDown ()
Private Member Functions
virtual void TestBody ()=0
void Run ()
void DeleteSelf_ ()
virtual Setup_should_be_spelled_SetUp * Setup ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test)
Static Private Member Functions
static bool HasSameFixtureClass ()
Private Attributes
const internal::scoped_ptr< GTEST_FLAG_SAVER_ > gtest_flag_saver_
Friends
class TestInfo
Detailed Description
Definition at line 397 of file gtest.h.
Member Typedef Documentation
SetUpTestCaseFunc
typedef internal::SetUpTestCaseFunc testing::Test::SetUpTestCaseFunc
Definition at line 403 of file gtest.h.
TearDownTestCaseFunc
typedef internal::TearDownTestCaseFunc testing::Test::TearDownTestCaseFunc
Definition at line 404 of file gtest.h.
Constructor & Destructor Documentation
~Test()
Test::~Test () virtual
Definition at line 2237 of file gtest.cc.
            {
}
Test()
Test::Test () protected
Definition at line 2230 of file gtest.cc.
    : gtest_flag_saver_(new GTEST_FLAG_SAVER_) {
}
Member Function Documentation
DeleteSelf_()
void testing::Test::DeleteSelf_ () inline private
Definition at line 479 of file gtest.h.
{ delete this; }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::Test::GTEST_DISALLOW_COPY_AND_ASSIGN_ (Test) private
HasFailure()
static bool testing::Test::HasFailure () inline static
Definition at line 433 of file gtest.h.
{ return HasFatalFailure() || HasNonfatalFailure(); }
HasFatalFailure()
bool Test::HasFatalFailure () static
Definition at line 2505 of file gtest.cc.
{
  return internal::GetUnitTestImpl()->current_test_result()->HasFatalFailure();
}
HasNonfatalFailure()
bool Test::HasNonfatalFailure () static
Definition at line 2510 of file gtest.cc.
{
  return internal::GetUnitTestImpl()->current_test_result()->
      HasNonfatalFailure();
}
HasSameFixtureClass()
bool Test::HasSameFixtureClass () static private
Definition at line 2285 of file gtest.cc.
{
  internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
  const TestCase* const test_case = impl->current_test_case();
  // Info about the first test in the current test case.
  const TestInfo* const first_test_info = test_case->test_info_list()[0];
  const internal::TypeId first_fixture_id = first_test_info->fixture_class_id_;
  const char* const first_test_name = first_test_info->name();
  // Info about the current test.
  const TestInfo* const this_test_info = impl->current_test_info();
  const internal::TypeId this_fixture_id = this_test_info->fixture_class_id_;
  const char* const this_test_name = this_test_info->name();
  if (this_fixture_id != first_fixture_id) {
    // Is the first test defined using TEST?
    const bool first_is_TEST = first_fixture_id == internal::GetTestTypeId();
    // Is this test defined using TEST?
    const bool this_is_TEST = this_fixture_id == internal::GetTestTypeId();
    if (first_is_TEST || this_is_TEST) {
      // Both TEST and TEST_F appear in same test case, which is incorrect.
      // Tell the user how to fix this.
      // Gets the name of the TEST and the name of the TEST_F.  Note
      // that first_is_TEST and this_is_TEST cannot both be true, as
      // the fixture IDs are different for the two tests.
      const char* const TEST_name =
          first_is_TEST ? first_test_name : this_test_name;
      const char* const TEST_F_name =
          first_is_TEST ? this_test_name : first_test_name;
      ADD_FAILURE()
          << "All tests in the same test case must use the same test fixture\n"
          << "class, so mixing TEST_F and TEST in the same test case is\n"
          << "illegal.  In test case " << this_test_info->test_case_name()
          << ",\n"
          << "test " << TEST_F_name << " is defined using TEST_F but\n"
          << "test " << TEST_name << " is defined using TEST.  You probably\n"
          << "want to change the TEST to TEST_F or move it to another test\n"
          << "case.";
    } else {
      // Two fixture classes with the same name appear in two different
      // namespaces, which is not allowed. Tell the user how to fix this.
      ADD_FAILURE()
          << "All tests in the same test case must use the same test fixture\n"
          << "class.  However, in test case "
          << this_test_info->test_case_name() << ",\n"
          << "you defined test " << first_test_name
          << " and test " << this_test_name << "\n"
          << "using two different test fixture classes.  This can happen if\n"
          << "the two classes are from different namespaces or translation\n"
          << "units and have the same name.  You should probably rename one\n"
          << "of the classes to put the tests into different test cases.";
    }
    return false;
  }
  return true;
}
References ADD_FAILURE, testing::internal::UnitTestImpl::current_test_case(), testing::internal::UnitTestImpl::current_test_info(), testing::TestInfo::fixture_class_id_, testing::internal::GetTestTypeId(), testing::internal::GetUnitTestImpl(), testing::TestInfo::name(), testing::TestInfo::test_case_name(), and testing::TestCase::test_info_list().
RecordProperty() [1/2]
void Test::RecordProperty (const std::string & key, const std::string & value) static
Definition at line 2253 of file gtest.cc.
{
  UnitTest::GetInstance()->RecordProperty(key, value);
}
References testing::UnitTest::GetInstance(), and testing::UnitTest::RecordProperty().
RecordProperty() [2/2]
void Test::RecordProperty (const std::string & key, int value) static
Definition at line 2258 of file gtest.cc.
{
  Message value_message;
  value_message << value;
  RecordProperty(key, value_message.GetString().c_str());
}
References testing::Message::GetString(), and RecordProperty().
Run()
void Test::Run () private
Definition at line 2483 of file gtest.cc.
               {
  if (!HasSameFixtureClass()) return;
  internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
  impl->os_stack_trace_getter()->UponLeavingGTest();
  internal::HandleExceptionsInMethodIfSupported(this, &Test::SetUp, "SetUp()");
  // We will run the test only if SetUp() was successful.
  if (!HasFatalFailure()) {
    impl->os_stack_trace_getter()->UponLeavingGTest();
    internal::HandleExceptionsInMethodIfSupported(
        this, &Test::TestBody, "the test body");
  }
  // However, we want to clean up as much as possible.  Hence we will
  // always call TearDown(), even if SetUp() or the test body has
  // failed.
  impl->os_stack_trace_getter()->UponLeavingGTest();
  internal::HandleExceptionsInMethodIfSupported(
      this, &Test::TearDown, "TearDown()");
}
References testing::internal::UnitTestImpl::os_stack_trace_getter(), and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
SetUp()
void Test::SetUp () protected virtual
Reimplemented in EncodedStreamTest, FileStreamTest, anonymous_namespace{gmock-actions_test.cc}::SetErrnoAndReturnTest, testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::LogIsVisibleTest, anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3, anonymous_namespace{sample5_unittest.cc}::QuickTest, anonymous_namespace{sample5_unittest.cc}::QueueTest, testing::internal::anonymous_namespace{gtest-filepath_test.cc}::DirectoryCreationTest, testing::internal::ListenerTest, testing::internal::anonymous_namespace{gtest-options_test.cc}::XmlOutputChangeDirTest, TestGenerationTest, CommonTest< T >, NonFatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInSetUpTest, FatalFailureInSetUpTest, Predicate1Test, Predicate2Test, Predicate3Test, Predicate4Test, Predicate5Test, anonymous_namespace{gtest_unittest.cc}::FormatEpochTimeInMillisAsIso8601Test, anonymous_namespace{gtest_unittest.cc}::TestResultTest, anonymous_namespace{gtest_unittest.cc}::ShouldShardTest, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >, testing::SetUpTestCaseTest, testing::ParseFlagsTest, ProtectedFixtureMethodsTest, PropertyOne, and PropertyTwo.
Definition at line 2243 of file gtest.cc.
                 {
}
Setup()
virtual Setup_should_be_spelled_SetUp * testing::Test::Setup () inline private virtual
Definition at line 500 of file gtest.h.
{ return NULL; }
SetUpTestCase()
static void testing::Test::SetUpTestCase () inline static
Definition at line 415 of file gtest.h.
{}
TearDown()
void Test::TearDown () protected virtual
Reimplemented in EncodedStreamTest, FileStreamTest, anonymous_namespace{gmock-actions_test.cc}::SetErrnoAndReturnTest, testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::LogIsVisibleTest, anonymous_namespace{sample5_unittest.cc}::QuickTest, testing::internal::anonymous_namespace{gtest-filepath_test.cc}::DirectoryCreationTest, testing::internal::ListenerTest, testing::internal::anonymous_namespace{gtest-options_test.cc}::XmlOutputChangeDirTest, TestGenerationTest, CommonTest< T >, NonFatalFailureInFixtureConstructorTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInSetUpTest, FatalFailureInSetUpTest, Predicate1Test, Predicate2Test, Predicate3Test, Predicate4Test, Predicate5Test, anonymous_namespace{gtest_unittest.cc}::FormatEpochTimeInMillisAsIso8601Test, anonymous_namespace{gtest_unittest.cc}::TestResultTest, anonymous_namespace{gtest_unittest.cc}::ShouldShardTest, ProtectedFixtureMethodsTest, PropertyOne, and PropertyTwo.
Definition at line 2249 of file gtest.cc.
                    {
}
TearDownTestCase()
static void testing::Test::TearDownTestCase () inline static
Definition at line 423 of file gtest.h.
{}
TestBody()
virtual void testing::Test::TestBody () private pure virtual
Friends And Related Symbol Documentation
TestInfo
friend class TestInfo friend
Definition at line 399 of file gtest.h.
Member Data Documentation
gtest_flag_saver_
const internal::scoped_ptr< GTEST_FLAG_SAVER_ > testing::Test::gtest_flag_saver_ private
Definition at line 481 of file gtest.h.
The documentation for this class was generated from the following files:
rapidjson/thirdparty/gtest/googletest/include/gtest/gtest.h
rapidjson/thirdparty/gtest/googletest/src/gtest.cc