wiNpoS: testing::internal::ParameterizedTestCaseInfo< TestCase > Class Template Reference
testing::internal::ParameterizedTestCaseInfo< TestCase > Class Template Reference
#include <gtest-param-util.h>
Classes
struct InstantiationInfo
struct TestInfo
Public Types
typedef TestCase::ParamType ParamType
typedef ParamNameGenFunc< ParamType >::Type ParamNameGeneratorFunc
Public Member Functions
typedef ParamGenerator (GeneratorCreationFunc)()
ParameterizedTestCaseInfo (const char *name, CodeLocation code_location)
virtual const std::string & GetTestCaseName () const
virtual TypeId GetTestCaseTypeId () const
void AddTestPattern (const char *test_case_name, const char *test_base_name, TestMetaFactoryBase< ParamType > *meta_factory)
int AddTestCaseInstantiation (const std::string &instantiation_name, GeneratorCreationFunc *func, ParamNameGeneratorFunc *name_func, const char *file, int line)
virtual void RegisterTests ()
Public Member Functions inherited from testing::internal::ParameterizedTestCaseInfoBase
virtual ~ParameterizedTestCaseInfoBase ()
Private Types
typedef ::std::vector< linked_ptr< TestInfo > > TestInfoContainer
typedef ::std::vector< InstantiationInfo > InstantiationContainer
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestCaseInfo)
Static Private Member Functions
static bool IsValidParamName (const std::string &name)
Private Attributes
const std::string test_case_name_
CodeLocation code_location_
TestInfoContainer tests_
InstantiationContainer instantiations_
Additional Inherited Members
Protected Member Functions inherited from testing::internal::ParameterizedTestCaseInfoBase
ParameterizedTestCaseInfoBase ()
Detailed Description
template<class TestCase>
class testing::internal::ParameterizedTestCaseInfo< TestCase >
Definition at line 494 of file gtest-param-util.h.
Member Typedef Documentation
InstantiationContainer
template<class TestCase > typedef ::std::vector<InstantiationInfo> testing::internal::ParameterizedTestCaseInfo< TestCase >::InstantiationContainer private
Definition at line 632 of file gtest-param-util.h.
ParamNameGeneratorFunc
template<class TestCase > typedef ParamNameGenFunc<ParamType>::Type testing::internal::ParameterizedTestCaseInfo< TestCase >::ParamNameGeneratorFunc
Definition at line 502 of file gtest-param-util.h.
ParamType
template<class TestCase > typedef TestCase::ParamType testing::internal::ParameterizedTestCaseInfo< TestCase >::ParamType
Definition at line 499 of file gtest-param-util.h.
TestInfoContainer
template<class TestCase > typedef ::std::vector<linked_ptr<TestInfo> > testing::internal::ParameterizedTestCaseInfo< TestCase >::TestInfoContainer private
Definition at line 610 of file gtest-param-util.h.
Constructor & Destructor Documentation
ParameterizedTestCaseInfo()
template<class TestCase > testing::internal::ParameterizedTestCaseInfo< TestCase >::ParameterizedTestCaseInfo (const char * name, CodeLocation code_location) inline explicit
Definition at line 504 of file gtest-param-util.h.
      : test_case_name_(name), code_location_(code_location) {}
Member Function Documentation
AddTestCaseInstantiation()
template<class TestCase > int testing::internal::ParameterizedTestCaseInfo< TestCase >::AddTestCaseInstantiation (const std::string & instantiation_name, GeneratorCreationFunc * func, ParamNameGeneratorFunc * name_func, const char * file, int line) inline
Definition at line 527 of file gtest-param-util.h.
{
    instantiations_.push_back(
        InstantiationInfo(instantiation_name, func, name_func, file, line));
    return 0;  // Return value used only to run this method in namespace scope.
  }
References testing::internal::ParameterizedTestCaseInfo< TestCase >::instantiations_.
AddTestPattern()
template<class TestCase > void testing::internal::ParameterizedTestCaseInfo< TestCase >::AddTestPattern (const char * test_case_name, const char * test_base_name, TestMetaFactoryBase< ParamType > * meta_factory) inline
Definition at line 518 of file gtest-param-util.h.
{
    tests_.push_back(linked_ptr<TestInfo>(new TestInfo(test_case_name,
                                                       test_base_name,
                                                       meta_factory)));
  }
References testing::internal::ParameterizedTestCaseInfo< TestCase >::tests_.
GetTestCaseName()
template<class TestCase > virtual const std::string & testing::internal::ParameterizedTestCaseInfo< TestCase >::GetTestCaseName () const inline virtual
Implements testing::internal::ParameterizedTestCaseInfoBase.
Definition at line 509 of file gtest-param-util.h.
{ return test_case_name_; }
References testing::internal::ParameterizedTestCaseInfo< TestCase >::test_case_name_.
GetTestCaseTypeId()
template<class TestCase > virtual TypeId testing::internal::ParameterizedTestCaseInfo< TestCase >::GetTestCaseTypeId () const inline virtual
Implements testing::internal::ParameterizedTestCaseInfoBase.
Definition at line 511 of file gtest-param-util.h.
{ return GetTypeId<TestCase>(); }
GTEST_DISALLOW_COPY_AND_ASSIGN_()
template<class TestCase > testing::internal::ParameterizedTestCaseInfo< TestCase >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestCaseInfo< TestCase >) private
IsValidParamName()
template<class TestCase > static bool testing::internal::ParameterizedTestCaseInfo< TestCase >::IsValidParamName (const std::string & name) inline static private
Definition at line 634 of file gtest-param-util.h.
{
    // Check for empty string
    if (name.empty())
      return false;
    // Check for invalid characters
    for (std::string::size_type index = 0; index < name.size(); ++index) {
      if (!isalnum(name[index]) && name[index] != '_')
        return false;
    }
    return true;
  }
ParamGenerator()
template<class TestCase > typedef testing::internal::ParameterizedTestCaseInfo< TestCase >::ParamGenerator (GeneratorCreationFunc)
RegisterTests()
template<class TestCase > virtual void testing::internal::ParameterizedTestCaseInfo< TestCase >::RegisterTests () inline virtual
Implements testing::internal::ParameterizedTestCaseInfoBase.
Definition at line 540 of file gtest-param-util.h.
{
    for (typename TestInfoContainer::iterator test_it = tests_.begin();
         test_it != tests_.end(); ++test_it) {
      linked_ptr<TestInfo> test_info = *test_it;
      for (typename InstantiationContainer::iterator gen_it =
               instantiations_.begin(); gen_it != instantiations_.end();
               ++gen_it) {
        const std::string& instantiation_name = gen_it->name;
        ParamGenerator<ParamType> generator((*gen_it->generator)());
        ParamNameGeneratorFunc* name_func = gen_it->name_func;
        const char* file = gen_it->file;
        int line = gen_it->line;
        std::string test_case_name;
        if ( !instantiation_name.empty() )
          test_case_name = instantiation_name + "/";
        test_case_name += test_info->test_case_base_name;
        size_t i = 0;
        std::set<std::string> test_param_names;
        for (typename ParamGenerator<ParamType>::iterator param_it =
                 generator.begin();
             param_it != generator.end(); ++param_it, ++i) {
          Message test_name_stream;
          std::string param_name = name_func(
              TestParamInfo<ParamType>(*param_it, i));
          GTEST_CHECK_(IsValidParamName(param_name))
              << "Parameterized test name '" << param_name
              << "' is invalid, in " << file
              << " line " << line << std::endl;
          GTEST_CHECK_(test_param_names.count(param_name) == 0)
              << "Duplicate parameterized test name '" << param_name
              << "', in " << file << " line " << line << std::endl;
          test_param_names.insert(param_name);
          test_name_stream << test_info->test_base_name << "/" << param_name;
          MakeAndRegisterTestInfo(
              test_case_name.c_str(),
              test_name_stream.GetString().c_str(),
              NULL,  // No type parameter.
              PrintToString(*param_it).c_str(),
              code_location_,
              GetTestCaseTypeId(),
              TestCase::SetUpTestCase,
              TestCase::TearDownTestCase,
              test_info->test_meta_factory->CreateTestFactory(*param_it));
        }  // for param_it
      }  // for gen_it
    }  // for test_it
  }  // RegisterTests
References testing::internal::ParamGenerator< T >::begin(), testing::internal::ParameterizedTestCaseInfo< TestCase >::code_location_, testing::internal::ParamGenerator< T >::end(), testing::Message::GetString(), testing::internal::ParameterizedTestCaseInfo< TestCase >::GetTestCaseTypeId(), GTEST_CHECK_, testing::internal::ParameterizedTestCaseInfo< TestCase >::instantiations_, testing::internal::ParameterizedTestCaseInfo< TestCase >::IsValidParamName(), testing::internal::MakeAndRegisterTestInfo(), testing::PrintToString(), and testing::internal::ParameterizedTestCaseInfo< TestCase >::tests_.
Member Data Documentation
code_location_
template<class TestCase > CodeLocation testing::internal::ParameterizedTestCaseInfo< TestCase >::code_location_ private
Definition at line 649 of file gtest-param-util.h.
instantiations_
template<class TestCase > InstantiationContainer testing::internal::ParameterizedTestCaseInfo< TestCase >::instantiations_ private
Definition at line 651 of file gtest-param-util.h.
test_case_name_
template<class TestCase > const std::string testing::internal::ParameterizedTestCaseInfo< TestCase >::test_case_name_ private
Definition at line 648 of file gtest-param-util.h.
tests_
template<class TestCase > TestInfoContainer testing::internal::ParameterizedTestCaseInfo< TestCase >::tests_ private
Definition at line 650 of file gtest-param-util.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/include/gtest/internal/gtest-param-util.h