wiNpoS: FilterKeyHandler< OutputHandler > Class Template Reference
FilterKeyHandler< OutputHandler > Class Template Reference
Public Types
typedef char Ch
typedef char Ch
Public Member Functions
FilterKeyHandler (OutputHandler &outputHandler, const Ch *keyString, SizeType keyLength)
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType len, bool copy)
bool String (const Ch *str, SizeType len, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType len, bool copy)
bool EndObject (SizeType)
bool StartArray ()
bool EndArray (SizeType elementCount)
FilterKeyHandler (OutputHandler &outputHandler, const Ch *keyString, SizeType keyLength)
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType len, bool copy)
bool String (const Ch *str, SizeType len, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType len, bool copy)
bool EndObject (SizeType)
bool StartArray ()
bool EndArray (SizeType elementCount)
Private Member Functions
FilterKeyHandler (const FilterKeyHandler &)
FilterKeyHandler & operator= (const FilterKeyHandler &)
bool EndValue ()
FilterKeyHandler (const FilterKeyHandler &)
FilterKeyHandler & operator= (const FilterKeyHandler &)
bool EndValue ()
Private Attributes
OutputHandler & outputHandler_
const char * keyString_
const SizeType keyLength_
unsigned filterValueDepth_
std::stack< SizeType > filteredKeyCount_
Detailed Description
template<typename OutputHandler>
class FilterKeyHandler< OutputHandler >
Definition at line 18 of file filterkey.cpp.
Member Typedef Documentation
Ch [1/2]
template<typename OutputHandler > typedef char FilterKeyHandler< OutputHandler >::Ch
Definition at line 20 of file filterkey.cpp.
Ch [2/2]
template<typename OutputHandler > typedef char FilterKeyHandler< OutputHandler >::Ch
Definition at line 21 of file filterkeydom.cpp.
Constructor & Destructor Documentation
FilterKeyHandler() [1/4]
template<typename OutputHandler > FilterKeyHandler< OutputHandler >::FilterKeyHandler (OutputHandler & outputHandler, const Ch * keyString, SizeType keyLength) inline
Definition at line 22 of file filterkey.cpp.
                                                                                            :
        outputHandler_(outputHandler), keyString_(keyString), keyLength_(keyLength), filterValueDepth_(), filteredKeyCount_()
    {}
FilterKeyHandler() [2/4]
template<typename OutputHandler > FilterKeyHandler< OutputHandler >::FilterKeyHandler (const FilterKeyHandler< OutputHandler > &) private
FilterKeyHandler() [3/4]
template<typename OutputHandler > FilterKeyHandler< OutputHandler >::FilterKeyHandler (OutputHandler & outputHandler, const Ch * keyString, SizeType keyLength) inline
Definition at line 23 of file filterkeydom.cpp.
                                                                                            :
        outputHandler_(outputHandler), keyString_(keyString), keyLength_(keyLength), filterValueDepth_(), filteredKeyCount_()
    {}
FilterKeyHandler() [4/4]
template<typename OutputHandler > FilterKeyHandler< OutputHandler >::FilterKeyHandler (const FilterKeyHandler< OutputHandler > &) private
Member Function Documentation
Bool() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Bool (bool b) inline
Definition at line 27 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Bool(b)   && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Bool() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Bool (bool b) inline
Definition at line 28 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Bool(b)   && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Double() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Double (double d) inline
Definition at line 32 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Double(d) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Double() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Double (double d) inline
Definition at line 33 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Double(d) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
EndArray() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::EndArray (SizeType elementCount) inline
Definition at line 82 of file filterkey.cpp.
{
        if (filterValueDepth_ > 0) {
            filterValueDepth_--;
            return EndValue();
        }
        else
            return outputHandler_.EndArray(elementCount) && EndValue();
    }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
EndArray() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::EndArray (SizeType elementCount) inline
Definition at line 83 of file filterkeydom.cpp.
{
        if (filterValueDepth_ > 0) {
            filterValueDepth_--;
            return EndValue();
        }
        else
            return outputHandler_.EndArray(elementCount) && EndValue();
    }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
EndObject() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::EndObject (SizeType) inline
Definition at line 60 of file filterkey.cpp.
{
        if (filterValueDepth_ > 0) {
            filterValueDepth_--;
            return EndValue();
        }
        else {
            // Use our own filtered memberCount
            SizeType memberCount = filteredKeyCount_.top();
            filteredKeyCount_.pop();
            return outputHandler_.EndObject(memberCount) && EndValue();
        }
    }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filteredKeyCount_, FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
EndObject() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::EndObject (SizeType) inline
Definition at line 61 of file filterkeydom.cpp.
{
        if (filterValueDepth_ > 0) {
            filterValueDepth_--;
            return EndValue();
        }
        else {
            // Use our own filtered memberCount
            SizeType memberCount = filteredKeyCount_.top();
            filteredKeyCount_.pop();
            return outputHandler_.EndObject(memberCount) && EndValue();
        }
    }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filteredKeyCount_, FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
EndValue() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::EndValue () inline private
Definition at line 95 of file filterkey.cpp.
                    {
        if (filterValueDepth_ == 1) // Just at the end of value after filtered key
            filterValueDepth_ = 0;
        return true;
    }
References FilterKeyHandler< OutputHandler >::filterValueDepth_.
EndValue() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::EndValue () inline private
Definition at line 96 of file filterkeydom.cpp.
                    {
        if (filterValueDepth_ == 1) // Just at the end of value after filtered key
            filterValueDepth_ = 0;
        return true;
    }
References FilterKeyHandler< OutputHandler >::filterValueDepth_.
Int() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Int (int i) inline
Definition at line 28 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Int(i)    && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Int() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Int (int i) inline
Definition at line 29 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Int(i)    && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Int64() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Int64 (int64_t i) inline
Definition at line 30 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Int64(i)  && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Int64() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Int64 (int64_t i) inline
Definition at line 31 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Int64(i)  && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Key() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Key (const Ch * str, SizeType len, bool copy) inline
Definition at line 47 of file filterkey.cpp.
{
        if (filterValueDepth_ > 0)
            return true;
        else if (len == keyLength_ && std::memcmp(str, keyString_, len) == 0) {
            filterValueDepth_ = 1;
            return true;
        }
        else {
            ++filteredKeyCount_.top();
            return outputHandler_.Key(str, len, copy);
        }
    }
References FilterKeyHandler< OutputHandler >::filteredKeyCount_, FilterKeyHandler< OutputHandler >::filterValueDepth_, FilterKeyHandler< OutputHandler >::keyLength_, FilterKeyHandler< OutputHandler >::keyString_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Key() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Key (const Ch * str, SizeType len, bool copy) inline
Definition at line 48 of file filterkeydom.cpp.
{
        if (filterValueDepth_ > 0)
            return true;
        else if (len == keyLength_ && std::memcmp(str, keyString_, len) == 0) {
            filterValueDepth_ = 1;
            return true;
        }
        else {
            ++filteredKeyCount_.top();
            return outputHandler_.Key(str, len, copy);
        }
    }
References FilterKeyHandler< OutputHandler >::filteredKeyCount_, FilterKeyHandler< OutputHandler >::filterValueDepth_, FilterKeyHandler< OutputHandler >::keyLength_, FilterKeyHandler< OutputHandler >::keyString_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Null() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Null () inline
Definition at line 26 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Null()    && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Null() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Null () inline
Definition at line 27 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Null()    && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
operator=() [1/2]
template<typename OutputHandler > FilterKeyHandler & FilterKeyHandler< OutputHandler >::operator= (const FilterKeyHandler< OutputHandler > &) private
operator=() [2/2]
template<typename OutputHandler > FilterKeyHandler & FilterKeyHandler< OutputHandler >::operator= (const FilterKeyHandler< OutputHandler > &) private
RawNumber() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::RawNumber (const Ch * str, SizeType len, bool copy) inline
Definition at line 33 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.RawNumber(str, len, copy) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
RawNumber() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::RawNumber (const Ch * str, SizeType len, bool copy) inline
Definition at line 34 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.RawNumber(str, len, copy) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
StartArray() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::StartArray () inline
Definition at line 73 of file filterkey.cpp.
                      {
        if (filterValueDepth_ > 0) {
            filterValueDepth_++;
            return true;
        }
        else
            return outputHandler_.StartArray();
    }
References FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
StartArray() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::StartArray () inline
Definition at line 74 of file filterkeydom.cpp.
                      {
        if (filterValueDepth_ > 0) {
            filterValueDepth_++;
            return true;
        }
        else
            return outputHandler_.StartArray();
    }
References FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
StartObject() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::StartObject () inline
Definition at line 36 of file filterkey.cpp.
                       {
        if (filterValueDepth_ > 0) {
            filterValueDepth_++;
            return true;
        }
        else {
            filteredKeyCount_.push(0);
            return outputHandler_.StartObject();
        }
    }
References FilterKeyHandler< OutputHandler >::filteredKeyCount_, FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
StartObject() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::StartObject () inline
Definition at line 37 of file filterkeydom.cpp.
                       {
        if (filterValueDepth_ > 0) {
            filterValueDepth_++;
            return true;
        }
        else {
            filteredKeyCount_.push(0);
            return outputHandler_.StartObject();
        }
    }
References FilterKeyHandler< OutputHandler >::filteredKeyCount_, FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
String() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::String (const Ch * str, SizeType len, bool copy) inline
Definition at line 34 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.String   (str, len, copy) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
String() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::String (const Ch * str, SizeType len, bool copy) inline
Definition at line 35 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.String   (str, len, copy) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Uint() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Uint (unsigned u) inline
Definition at line 29 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Uint(u)   && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Uint() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Uint (unsigned u) inline
Definition at line 30 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Uint(u)   && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Uint64() [1/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Uint64 (uint64_t u) inline
Definition at line 31 of file filterkey.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Uint64(u) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Uint64() [2/2]
template<typename OutputHandler > bool FilterKeyHandler< OutputHandler >::Uint64 (uint64_t u) inline
Definition at line 32 of file filterkeydom.cpp.
{ return filterValueDepth_ > 0 ? EndValue() : outputHandler_.Uint64(u) && EndValue(); }
References FilterKeyHandler< OutputHandler >::EndValue(), FilterKeyHandler< OutputHandler >::filterValueDepth_, and FilterKeyHandler< OutputHandler >::outputHandler_.
Member Data Documentation
filteredKeyCount_
template<typename OutputHandler > std::stack< SizeType > FilterKeyHandler< OutputHandler >::filteredKeyCount_ private
Definition at line 105 of file filterkey.cpp.
filterValueDepth_
template<typename OutputHandler > unsigned FilterKeyHandler< OutputHandler >::filterValueDepth_ private
Definition at line 104 of file filterkey.cpp.
keyLength_
template<typename OutputHandler > const SizeType FilterKeyHandler< OutputHandler >::keyLength_ private
Definition at line 103 of file filterkey.cpp.
keyString_
template<typename OutputHandler > const char * FilterKeyHandler< OutputHandler >::keyString_ private
Definition at line 102 of file filterkey.cpp.
outputHandler_
template<typename OutputHandler > OutputHandler & FilterKeyHandler< OutputHandler >::outputHandler_ private
Definition at line 101 of file filterkey.cpp.
The documentation for this class was generated from the following files:
rapidjson/example/filterkey/filterkey.cpp
rapidjson/example/filterkeydom/filterkeydom.cpp