wiNpoS: rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference
rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference
JSON Schema Validator.
#include <schema.h>
Public Types
typedef SchemaDocumentType::SchemaType SchemaType
typedef SchemaDocumentType::PointerType PointerType
typedef SchemaType::EncodingType EncodingType
typedef SchemaType::SValue SValue
typedef EncodingType::Ch Ch
typedef GenericStringRef< Ch > StringRefType
typedef GenericValue< EncodingType, StateAllocator > ValueType
Public Types inherited from rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >
typedef SchemaType::Ch Ch
typedef SchemaType::SValue SValue
Public Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor without output handler.
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, OutputHandler &outputHandler, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor with output handler.
~GenericSchemaValidator ()
Destructor.
void Reset ()
Reset the internal states.
void ResetError ()
Reset the error state.
void SetValidateFlags (unsigned flags)
Implementation of ISchemaValidator.
virtual unsigned GetValidateFlags () const
virtual bool IsValid () const
ValueType & GetError ()
End of Implementation of ISchemaValidator.
const ValueType & GetError () const
PointerType GetInvalidSchemaPointer () const
Gets the JSON pointer pointed to the invalid schema.
const Ch * GetInvalidSchemaKeyword () const
Gets the keyword of invalid schema.
ValidateErrorCode GetInvalidSchemaCode () const
Gets the error code of invalid schema.
PointerType GetInvalidDocumentPointer () const
Gets the JSON pointer pointed to the invalid value.
void NotMultipleOf (int64_t actual, const SValue &expected)
void NotMultipleOf (uint64_t actual, const SValue &expected)
void NotMultipleOf (double actual, const SValue &expected)
void AboveMaximum (int64_t actual, const SValue &expected, bool exclusive)
void AboveMaximum (uint64_t actual, const SValue &expected, bool exclusive)
void AboveMaximum (double actual, const SValue &expected, bool exclusive)
void BelowMinimum (int64_t actual, const SValue &expected, bool exclusive)
void BelowMinimum (uint64_t actual, const SValue &expected, bool exclusive)
void BelowMinimum (double actual, const SValue &expected, bool exclusive)
void TooLong (const Ch *str, SizeType length, SizeType expected)
void TooShort (const Ch *str, SizeType length, SizeType expected)
void DoesNotMatch (const Ch *str, SizeType length)
void DisallowedItem (SizeType index)
void TooFewItems (SizeType actualCount, SizeType expectedCount)
void TooManyItems (SizeType actualCount, SizeType expectedCount)
void DuplicateItems (SizeType index1, SizeType index2)
void TooManyProperties (SizeType actualCount, SizeType expectedCount)
void TooFewProperties (SizeType actualCount, SizeType expectedCount)
void StartMissingProperties ()
void AddMissingProperty (const SValue &name)
bool EndMissingProperties ()
void PropertyViolations (ISchemaValidator **subvalidators, SizeType count)
void DisallowedProperty (const Ch *name, SizeType length)
void StartDependencyErrors ()
void StartMissingDependentProperties ()
void AddMissingDependentProperty (const SValue &targetName)
void EndMissingDependentProperties (const SValue &sourceName)
void AddDependencySchemaError (const SValue &sourceName, ISchemaValidator *subvalidator)
bool EndDependencyErrors ()
void DisallowedValue (const ValidateErrorCode code=kValidateErrorEnum)
void StartDisallowedType ()
void AddExpectedType (const typename SchemaType::ValueType &expectedType)
void EndDisallowedType (const typename SchemaType::ValueType &actualType)
void NotAllOf (ISchemaValidator **subvalidators, SizeType count)
void NoneOf (ISchemaValidator **subvalidators, SizeType count)
void NotOneOf (ISchemaValidator **subvalidators, SizeType count)
void MultipleOneOf (SizeType index1, SizeType index2)
void Disallowed ()
void DisallowedWhenWriting ()
void DisallowedWhenReading ()
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType length, bool copy)
bool String (const Ch *str, SizeType length, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType len, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
virtual ISchemaValidator * CreateSchemaValidator (const SchemaType &root, const bool inheritContinueOnErrors)
virtual void DestroySchemaValidator (ISchemaValidator *validator)
virtual void * CreateHasher ()
virtual uint64_t GetHashCode (void *hasher)
virtual void DestroryHasher (void *hasher)
virtual void * MallocState (size_t size)
virtual void FreeState (void *p)
Public Member Functions inherited from rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >
virtual ~ISchemaStateFactory ()
virtual void DestroySchemaValidator (ISchemaValidator *validator)=0
Public Member Functions inherited from rapidjson::internal::ISchemaValidator
virtual ~ISchemaValidator ()
Public Member Functions inherited from rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >
virtual ~IValidationErrorHandler ()
virtual void TooLong (const Ch *str, SizeType length, SizeType expected)=0
virtual void TooShort (const Ch *str, SizeType length, SizeType expected)=0
virtual void DoesNotMatch (const Ch *str, SizeType length)=0
virtual void PropertyViolations (ISchemaValidator **subvalidators, SizeType count)=0
virtual void DisallowedProperty (const Ch *name, SizeType length)=0
virtual void AddDependencySchemaError (const SValue &souceName, ISchemaValidator *subvalidator)=0
virtual void NotAllOf (ISchemaValidator **subvalidators, SizeType count)=0
virtual void NoneOf (ISchemaValidator **subvalidators, SizeType count)=0
virtual void NotOneOf (ISchemaValidator **subvalidators, SizeType count)=0
Static Public Member Functions
static const StringRefType & GetInstanceRefString ()
static const StringRefType & GetSchemaRefString ()
static const StringRefType & GetExpectedString ()
static const StringRefType & GetActualString ()
static const StringRefType & GetDisallowedString ()
static const StringRefType & GetMissingString ()
static const StringRefType & GetErrorsString ()
static const StringRefType & GetErrorCodeString ()
static const StringRefType & GetErrorMessageString ()
static const StringRefType & GetDuplicatesString ()
static const StringRefType & GetMatchesString ()
Private Types
typedef SchemaType::Context Context
typedef GenericValue< UTF8<>, StateAllocator > HashCodeArray
typedef internal::Hasher< EncodingType, StateAllocator > HasherType
Private Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, const SchemaType &root, const char *basePath, size_t basePathSize, unsigned depth, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
StateAllocator & GetStateAllocator ()
bool GetContinueOnErrors () const
bool BeginValue ()
bool EndValue ()
void AppendToken (const Ch *str, SizeType len)
RAPIDJSON_FORCEINLINE void PushSchema (const SchemaType &schema)
RAPIDJSON_FORCEINLINE void PopSchema ()
void AddErrorInstanceLocation (ValueType &result, bool parent)
void AddErrorSchemaLocation (ValueType &result, PointerType schema=PointerType())
void AddErrorCode (ValueType &result, const ValidateErrorCode code)
void AddError (ValueType &keyword, ValueType &error)
void AddCurrentError (const ValidateErrorCode code, bool parent=false)
void MergeError (ValueType &other)
void AddNumberError (const ValidateErrorCode code, ValueType &actual, const SValue &expected, const typename SchemaType::ValueType &(*exclusive)()=0)
void AddErrorArray (const ValidateErrorCode code, ISchemaValidator **subvalidators, SizeType count)
const SchemaType & CurrentSchema () const
Context & CurrentContext ()
const Context & CurrentContext () const
Private Attributes
const SchemaDocumentType * schemaDocument_
const SchemaType & root_
StateAllocator * stateAllocator_
StateAllocator * ownStateAllocator_
internal::Stack< StateAllocator > schemaStack_
stack to store the current path of schema (BaseSchemaType *)
internal::Stack< StateAllocator > documentStack_
stack to store the current path of validating document (Ch)
OutputHandler * outputHandler_
ValueType error_
ValueType currentError_
ValueType missingDependents_
bool valid_
unsigned flags_
unsigned depth_
Static Private Attributes
static const size_t kDefaultSchemaStackCapacity = 1024
static const size_t kDefaultDocumentStackCapacity = 256
Detailed Description
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
class rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >
JSON Schema Validator.
A SAX style JSON schema validator. It uses a GenericSchemaDocument to validate SAX events. It delegates the incoming SAX events to an output handler. The default output handler does nothing. It can be reused multiple times by calling Reset().
Template Parameters
SchemaDocumentType Type of schema document.
OutputHandler Type of output handler. Default handler does nothing.
StateAllocator Allocator for storing the internal validation states.
Definition at line 2436 of file schema.h.
Member Typedef Documentation
Ch
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef EncodingType::Ch rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Ch
Definition at line 2445 of file schema.h.
Context
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::Context rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Context private
Definition at line 2937 of file schema.h.
EncodingType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::EncodingType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EncodingType
Definition at line 2443 of file schema.h.
HashCodeArray
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef GenericValue<UTF8<>, StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::HashCodeArray private
Definition at line 2938 of file schema.h.
HasherType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef internal::Hasher<EncodingType, StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::HasherType private
Definition at line 2939 of file schema.h.
PointerType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaDocumentType::PointerType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PointerType
Definition at line 2442 of file schema.h.
SchemaType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaDocumentType::SchemaType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SchemaType
Definition at line 2441 of file schema.h.
StringRefType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef GenericStringRef<Ch> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StringRefType
Definition at line 2446 of file schema.h.
SValue
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::SValue rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SValue
Definition at line 2444 of file schema.h.
ValueType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef GenericValue<EncodingType, StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ValueType
Definition at line 2447 of file schema.h.
Constructor & Destructor Documentation
GenericSchemaValidator() [1/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline
Constructor without output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Definition at line 2456 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(schemaDocument.GetRoot()),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(0),
        error_(kObjectType),
        currentError_(),
        missingDependents_(),
        valid_(true),
        flags_(kValidateDefaultFlags),
        depth_(0)
    {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::GenericSchemaValidator");
    }
References rapidjson::kObjectType, rapidjson::kValidateDefaultFlags, Method, and RAPIDJSON_SCHEMA_PRINT.
GenericSchemaValidator() [2/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, OutputHandler & outputHandler, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline
Constructor with output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Definition at line 2486 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(schemaDocument.GetRoot()),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(&outputHandler),
        error_(kObjectType),
        currentError_(),
        missingDependents_(),
        valid_(true),
        flags_(kValidateDefaultFlags),
        depth_(0)
    {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::GenericSchemaValidator (output handler)");
    }
References rapidjson::kObjectType, rapidjson::kValidateDefaultFlags, Method, and RAPIDJSON_SCHEMA_PRINT.
~GenericSchemaValidator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator () inline
Destructor.
Definition at line 2511 of file schema.h.
{
        Reset();
        RAPIDJSON_DELETE(ownStateAllocator_);
    }
References RAPIDJSON_DELETE.
GenericSchemaValidator() [3/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, const SchemaType & root, const char * basePath, size_t basePathSize, unsigned depth, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline private
Definition at line 2941 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(root),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(0),
        error_(kObjectType),
        currentError_(),
        missingDependents_(),
        valid_(true),
        flags_(kValidateDefaultFlags),
        depth_(depth)
    {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::GenericSchemaValidator (internal)", basePath && basePathSize ? basePath : "");
        if (basePath && basePathSize)
            memcpy(documentStack_.template Push<char>(basePathSize), basePath, basePathSize);
    }
References rapidjson::kObjectType, rapidjson::kValidateDefaultFlags, Method, and RAPIDJSON_SCHEMA_PRINT.
Member Function Documentation
AboveMaximum() [1/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (double actual, const SValue & expected, bool exclusive) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2601 of file schema.h.
{
        AddNumberError(exclusive ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum, ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMaximumString : 0);
    }
References rapidjson::kValidateErrorExclusiveMaximum, and rapidjson::kValidateErrorMaximum.
AboveMaximum() [2/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (int64_t actual, const SValue & expected, bool exclusive) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2593 of file schema.h.
{
        AddNumberError(exclusive ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum, ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMaximumString : 0);
    }
References rapidjson::kValidateErrorExclusiveMaximum, and rapidjson::kValidateErrorMaximum.
AboveMaximum() [3/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (uint64_t actual, const SValue & expected, bool exclusive) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2597 of file schema.h.
{
        AddNumberError(exclusive ? kValidateErrorExclusiveMaximum : kValidateErrorMaximum, ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMaximumString : 0);
    }
References rapidjson::kValidateErrorExclusiveMaximum, and rapidjson::kValidateErrorMaximum.
AddCurrentError()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddCurrentError (const ValidateErrorCode code, bool parent = false) inline private
Definition at line 3123 of file schema.h.
{
        AddErrorCode(currentError_, code);
        AddErrorInstanceLocation(currentError_, parent);
        AddErrorSchemaLocation(currentError_);
        AddError(ValueType(SchemaType::GetValidateErrorKeyword(code), GetStateAllocator(), false).Move(), currentError_);
    }
AddDependencySchemaError()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddDependencySchemaError (const SValue & sourceName, ISchemaValidator * subvalidator) inline
Definition at line 2712 of file schema.h.
{
        currentError_.AddMember(ValueType(sourceName, GetStateAllocator()).Move(),
            static_cast<GenericSchemaValidator*>(subvalidator)->GetError(), GetStateAllocator());
    }
AddError()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddError (ValueType & keyword, ValueType & error) inline private
Definition at line 3109 of file schema.h.
{
        typename ValueType::MemberIterator member = error_.FindMember(keyword);
        if (member == error_.MemberEnd())
            error_.AddMember(keyword, error, GetStateAllocator());
        else {
            if (member->value.IsObject()) {
                ValueType errors(kArrayType);
                errors.PushBack(member->value, GetStateAllocator());
                member->value = errors;
            }
            member->value.PushBack(error, GetStateAllocator());
        }
    }
References rapidjson::kArrayType.
AddErrorArray()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorArray (const ValidateErrorCode code, ISchemaValidator ** subvalidators, SizeType count) inline private
Definition at line 3146 of file schema.h.
{
        ValueType errors(kArrayType);
        for (SizeType i = 0; i < count; ++i)
            errors.PushBack(static_cast<GenericSchemaValidator*>(subvalidators[i])->GetError(), GetStateAllocator());
        currentError_.SetObject();
        currentError_.AddMember(GetErrorsString(), errors, GetStateAllocator());
        AddCurrentError(code);
    }
References rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError(), and rapidjson::kArrayType.
AddErrorCode()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorCode (ValueType & result, const ValidateErrorCode code) inline private
Definition at line 3105 of file schema.h.
{
        result.AddMember(GetErrorCodeString(), code, GetStateAllocator());
    }
AddErrorInstanceLocation()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorInstanceLocation (ValueType & result, bool parent) inline private
Definition at line 3083 of file schema.h.
{
        GenericStringBuffer<EncodingType> sb;
        PointerType instancePointer = GetInvalidDocumentPointer();
        ((parent && instancePointer.GetTokenCount() > 0)
         ? PointerType(instancePointer.GetTokens(), instancePointer.GetTokenCount() - 1)
         : instancePointer).StringifyUriFragment(sb);
        ValueType instanceRef(sb.GetString(), static_cast<SizeType>(sb.GetSize() / sizeof(Ch)),
                              GetStateAllocator());
        result.AddMember(GetInstanceRefString(), instanceRef, GetStateAllocator());
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString().
AddErrorSchemaLocation()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorSchemaLocation (ValueType & result, PointerType schema = PointerType()) inline private
Definition at line 3094 of file schema.h.
{
        GenericStringBuffer<EncodingType> sb;
        SizeType len = CurrentSchema().GetURI().GetStringLength();
        if (len) memcpy(sb.Push(len), CurrentSchema().GetURI().GetString(), len * sizeof(Ch));
        if (schema.GetTokenCount()) schema.StringifyUriFragment(sb);
        else GetInvalidSchemaPointer().StringifyUriFragment(sb);
        ValueType schemaRef(sb.GetString(), static_cast<SizeType>(sb.GetSize() / sizeof(Ch)),
            GetStateAllocator());
        result.AddMember(GetSchemaRefString(), schemaRef, GetStateAllocator());
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), GetString(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Push().
AddExpectedType()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddExpectedType (const typename SchemaType::ValueType & expectedType) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2733 of file schema.h.
{
        currentError_.PushBack(ValueType(expectedType, GetStateAllocator()).Move(), GetStateAllocator());
    }
AddMissingDependentProperty()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddMissingDependentProperty (const SValue & targetName) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2693 of file schema.h.
{
        missingDependents_.PushBack(ValueType(targetName, GetStateAllocator()).Move(), GetStateAllocator());
    }
AddMissingProperty()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddMissingProperty (const SValue & name) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2665 of file schema.h.
{
        currentError_.PushBack(ValueType(name, GetStateAllocator()).Move(), GetStateAllocator());
    }
AddNumberError()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddNumberError (const ValidateErrorCode code, ValueType & actual, const SValue & expected, const typename SchemaType::ValueType &(*)() exclusive = 0) inline private
Definition at line 3136 of file schema.h.
{
        currentError_.SetObject();
        currentError_.AddMember(GetActualString(), actual, GetStateAllocator());
        currentError_.AddMember(GetExpectedString(), ValueType(expected, GetStateAllocator()).Move(), GetStateAllocator());
        if (exclusive)
            currentError_.AddMember(ValueType(exclusive(), GetStateAllocator()).Move(), true, GetStateAllocator());
        AddCurrentError(code);
    }
AppendToken()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AppendToken (const Ch * str, SizeType len) inline private
Definition at line 3055 of file schema.h.
{
        documentStack_.template Reserve<Ch>(1 + len * 2); // worst case all characters are escaped as two characters
        *documentStack_.template PushUnsafe<Ch>() = '/';
        for (SizeType i = 0; i < len; i++) {
            if (str[i] == '~') {
                *documentStack_.template PushUnsafe<Ch>() = '~';
                *documentStack_.template PushUnsafe<Ch>() = '0';
            }
            else if (str[i] == '/') {
                *documentStack_.template PushUnsafe<Ch>() = '~';
                *documentStack_.template PushUnsafe<Ch>() = '1';
            }
            else
                *documentStack_.template PushUnsafe<Ch>() = str[i];
        }
    }
BeginValue()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue () inline private
Definition at line 2979 of file schema.h.
                      {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::BeginValue");
        if (schemaStack_.Empty())
            PushSchema(root_);
        else {
            if (CurrentContext().inArray)
                internal::TokenHelper<internal::Stack<StateAllocator>, Ch>::AppendIndexToken(documentStack_, CurrentContext().arrayElementIndex);
            if (!CurrentSchema().BeginValue(CurrentContext()) && !GetContinueOnErrors())
                return false;
            SizeType count = CurrentContext().patternPropertiesSchemaCount;
            const SchemaType** sa = CurrentContext().patternPropertiesSchemas;
            typename Context::PatternValidatorType patternValidatorType = CurrentContext().valuePatternValidatorType;
            bool valueUniqueness = CurrentContext().valueUniqueness;
            RAPIDJSON_ASSERT(CurrentContext().valueSchema);
            PushSchema(*CurrentContext().valueSchema);
            if (count > 0) {
                CurrentContext().objectPatternValidatorType = patternValidatorType;
                ISchemaValidator**& va = CurrentContext().patternPropertiesValidators;
                SizeType& validatorCount = CurrentContext().patternPropertiesValidatorCount;
                va = static_cast<ISchemaValidator**>(MallocState(sizeof(ISchemaValidator*) * count));
                std::memset(va, 0, sizeof(ISchemaValidator*) * count);
                for (SizeType i = 0; i < count; i++)
                    va[validatorCount++] = CreateSchemaValidator(*sa[i], true);  // Inherit continueOnError
            }
            CurrentContext().arrayUniqueness = valueUniqueness;
        }
        return true;
    }
References Method, RAPIDJSON_ASSERT, and RAPIDJSON_SCHEMA_PRINT.
BelowMinimum() [1/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (double actual, const SValue & expected, bool exclusive) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2613 of file schema.h.
{
        AddNumberError(exclusive ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum, ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMinimumString : 0);
    }
References rapidjson::kValidateErrorExclusiveMinimum, and rapidjson::kValidateErrorMinimum.
BelowMinimum() [2/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (int64_t actual, const SValue & expected, bool exclusive) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2605 of file schema.h.
{
        AddNumberError(exclusive ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum, ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMinimumString : 0);
    }
References rapidjson::kValidateErrorExclusiveMinimum, and rapidjson::kValidateErrorMinimum.
BelowMinimum() [3/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (uint64_t actual, const SValue & expected, bool exclusive) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2609 of file schema.h.
{
        AddNumberError(exclusive ? kValidateErrorExclusiveMinimum : kValidateErrorMinimum, ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMinimumString : 0);
    }
References rapidjson::kValidateErrorExclusiveMinimum, and rapidjson::kValidateErrorMinimum.
Bool()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool (bool b) inline
Definition at line 2830 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Bool,   (CurrentContext(), b), (b)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
CreateHasher()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void * rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateHasher () inline virtual
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2913 of file schema.h.
{
        return new (GetStateAllocator().Malloc(sizeof(HasherType))) HasherType(&GetStateAllocator());
    }
CreateSchemaValidator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual ISchemaValidator * rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator (const SchemaType & root, const bool inheritContinueOnErrors) inline virtual
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2897 of file schema.h.
{
        *documentStack_.template Push<Ch>() = '\0';
        documentStack_.template Pop<Ch>(1);
        ISchemaValidator* sv = new (GetStateAllocator().Malloc(sizeof(GenericSchemaValidator))) GenericSchemaValidator(*schemaDocument_, root, documentStack_.template Bottom<char>(), documentStack_.GetSize(),
        depth_ + 1,
        &GetStateAllocator());
        sv->SetValidateFlags(inheritContinueOnErrors ? GetValidateFlags() : GetValidateFlags() & ~static_cast<unsigned>(kValidateContinueOnErrorFlag));
        return sv;
    }
References rapidjson::kValidateContinueOnErrorFlag, and rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SetValidateFlags().
CurrentContext() [1/2]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> Context & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext () inline private
Definition at line 3157 of file schema.h.
{ return *schemaStack_.template Top<Context>(); }
CurrentContext() [2/2]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const Context & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext () const inline private
Definition at line 3158 of file schema.h.
{ return *schemaStack_.template Top<Context>(); }
CurrentSchema()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const SchemaType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema () const inline private
Definition at line 3156 of file schema.h.
{ return *schemaStack_.template Top<Context>()->schema; }
DestroryHasher()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroryHasher (void * hasher) inline virtual
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2921 of file schema.h.
{
        HasherType* h = static_cast<HasherType*>(hasher);
        h->~HasherType();
        StateAllocator::Free(h);
    }
DestroySchemaValidator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator (ISchemaValidator * validator) inline virtual
Definition at line 2907 of file schema.h.
{
        GenericSchemaValidator* v = static_cast<GenericSchemaValidator*>(validator);
        v->~GenericSchemaValidator();
        StateAllocator::Free(v);
    }
References rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator().
Disallowed()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Disallowed () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2764 of file schema.h.
                      {
        currentError_.SetObject();
        AddCurrentError(kValidateErrorNot);
    }
References rapidjson::kValidateErrorNot.
DisallowedItem()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedItem (SizeType index) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2632 of file schema.h.
{
        currentError_.SetObject();
        currentError_.AddMember(GetDisallowedString(), ValueType(index).Move(), GetStateAllocator());
        AddCurrentError(kValidateErrorAdditionalItems, true);
    }
References rapidjson::kValidateErrorAdditionalItems.
DisallowedProperty()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedProperty (const Ch * name, SizeType length) inline
Definition at line 2681 of file schema.h.
{
        currentError_.SetObject();
        currentError_.AddMember(GetDisallowedString(), ValueType(name, length, GetStateAllocator()).Move(), GetStateAllocator());
        AddCurrentError(kValidateErrorAdditionalProperties, true);
    }
References rapidjson::kValidateErrorAdditionalProperties.
DisallowedValue()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedValue (const ValidateErrorCode code = kValidateErrorEnum) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2726 of file schema.h.
{
        currentError_.SetObject();
        AddCurrentError(code);
    }
DisallowedWhenReading()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedWhenReading () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2772 of file schema.h.
{
        currentError_.SetObject();
        AddCurrentError(kValidateErrorWriteOnly);
    }
References rapidjson::kValidateErrorWriteOnly.
DisallowedWhenWriting()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedWhenWriting () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2768 of file schema.h.
{
        currentError_.SetObject();
        AddCurrentError(kValidateErrorReadOnly);
    }
References rapidjson::kValidateErrorReadOnly.
DoesNotMatch()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DoesNotMatch (const Ch * str, SizeType length) inline
Definition at line 2626 of file schema.h.
{
        currentError_.SetObject();
        currentError_.AddMember(GetActualString(), ValueType(str, length, GetStateAllocator()).Move(), GetStateAllocator());
        AddCurrentError(kValidateErrorPattern);
    }
References rapidjson::kValidateErrorPattern.
Double()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double (double d) inline
Definition at line 2835 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Double, (CurrentContext(), d), (d)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
DuplicateItems()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DuplicateItems (SizeType index1, SizeType index2) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2645 of file schema.h.
{
        ValueType duplicates(kArrayType);
        duplicates.PushBack(index1, GetStateAllocator());
        duplicates.PushBack(index2, GetStateAllocator());
        currentError_.SetObject();
        currentError_.AddMember(GetDuplicatesString(), duplicates, GetStateAllocator());
        AddCurrentError(kValidateErrorUniqueItems, true);
    }
References rapidjson::kArrayType, and rapidjson::kValidateErrorUniqueItems.
EndArray()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray (SizeType elementCount) inline
Definition at line 2881 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::EndArray");
        if (!valid_) return false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndArray, (elementCount));
        if (!CurrentSchema().EndArray(CurrentContext(), elementCount) && !GetContinueOnErrors()) {
            valid_ = false;
            return valid_;
        }
        RAPIDJSON_SCHEMA_HANDLE_END_(EndArray, (elementCount));
    }
References Method, RAPIDJSON_SCHEMA_HANDLE_END_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and RAPIDJSON_SCHEMA_PRINT.
EndDependencyErrors()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndDependencyErrors () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2716 of file schema.h.
{
        if (currentError_.ObjectEmpty())
            return false;
        ValueType error(kObjectType);
        error.AddMember(GetErrorsString(), currentError_, GetStateAllocator());
        currentError_ = error;
        AddCurrentError(kValidateErrorDependencies);
        return true;
    }
References rapidjson::kObjectType, and rapidjson::kValidateErrorDependencies.
EndDisallowedType()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndDisallowedType (const typename SchemaType::ValueType & actualType) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2736 of file schema.h.
{
        ValueType error(kObjectType);
        error.AddMember(GetExpectedString(), currentError_, GetStateAllocator());
        error.AddMember(GetActualString(), ValueType(actualType, GetStateAllocator()).Move(), GetStateAllocator());
        currentError_ = error;
        AddCurrentError(kValidateErrorType);
    }
References rapidjson::kObjectType, and rapidjson::kValidateErrorType.
EndMissingDependentProperties()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndMissingDependentProperties (const SValue & sourceName) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2696 of file schema.h.
{
        if (!missingDependents_.Empty()) {
            // Create equivalent 'required' error
            ValueType error(kObjectType);
            ValidateErrorCode code = kValidateErrorRequired;
            error.AddMember(GetMissingString(), missingDependents_.Move(), GetStateAllocator());
            AddErrorCode(error, code);
            AddErrorInstanceLocation(error, false);
            // When appending to a pointer ensure its allocator is used
            PointerType schemaRef = GetInvalidSchemaPointer().Append(SchemaType::GetValidateErrorKeyword(kValidateErrorDependencies), &GetInvalidSchemaPointer().GetAllocator());
            AddErrorSchemaLocation(error, schemaRef.Append(sourceName.GetString(), sourceName.GetStringLength(), &GetInvalidSchemaPointer().GetAllocator()));
            ValueType wrapper(kObjectType);
            wrapper.AddMember(ValueType(SchemaType::GetValidateErrorKeyword(code), GetStateAllocator()).Move(), error, GetStateAllocator());
            currentError_.AddMember(ValueType(sourceName, GetStateAllocator()).Move(), wrapper, GetStateAllocator());
        }
    }
References rapidjson::kObjectType, rapidjson::kValidateErrorDependencies, and rapidjson::kValidateErrorRequired.
EndMissingProperties()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndMissingProperties () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2668 of file schema.h.
{
        if (currentError_.Empty())
            return false;
        ValueType error(kObjectType);
        error.AddMember(GetMissingString(), currentError_, GetStateAllocator());
        currentError_ = error;
        AddCurrentError(kValidateErrorRequired);
        return true;
    }
References rapidjson::kObjectType, and rapidjson::kValidateErrorRequired.
EndObject()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject (SizeType memberCount) inline
Definition at line 2862 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::EndObject");
        if (!valid_) return false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndObject, (memberCount));
        if (!CurrentSchema().EndObject(CurrentContext(), memberCount) && !GetContinueOnErrors()) {
            valid_ = false;
            return valid_;
        }
        RAPIDJSON_SCHEMA_HANDLE_END_(EndObject, (memberCount));
    }
References Method, RAPIDJSON_SCHEMA_HANDLE_END_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and RAPIDJSON_SCHEMA_PRINT.
EndValue()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue () inline private
Definition at line 3012 of file schema.h.
                    {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::EndValue");
        if (!CurrentSchema().EndValue(CurrentContext()) && !GetContinueOnErrors())
            return false;
        GenericStringBuffer<EncodingType> sb;
        schemaDocument_->GetPointer(&CurrentSchema()).StringifyUriFragment(sb);
        *documentStack_.template Push<Ch>() = '\0';
        documentStack_.template Pop<Ch>(1);
        RAPIDJSON_SCHEMA_PRINT(ValidatorPointers, sb.GetString(), documentStack_.template Bottom<Ch>(), depth_);
        void* hasher = CurrentContext().hasher;
        uint64_t h = hasher && CurrentContext().arrayUniqueness ? static_cast<HasherType*>(hasher)->GetHashCode() : 0;
        PopSchema();
        if (!schemaStack_.Empty()) {
            Context& context = CurrentContext();
            // Only check uniqueness if there is a hasher
            if (hasher && context.valueUniqueness) {
                HashCodeArray* a = static_cast<HashCodeArray*>(context.arrayElementHashCodes);
                if (!a)
                    CurrentContext().arrayElementHashCodes = a = new (GetStateAllocator().Malloc(sizeof(HashCodeArray))) HashCodeArray(kArrayType);
                for (typename HashCodeArray::ConstValueIterator itr = a->Begin(); itr != a->End(); ++itr)
                    if (itr->GetUint64() == h) {
                        DuplicateItems(static_cast<SizeType>(itr - a->Begin()), a->Size());
                        // Cleanup before returning if continuing
                        if (GetContinueOnErrors()) {
                            a->PushBack(h, GetStateAllocator());
                            while (!documentStack_.Empty() && *documentStack_.template Pop<Ch>(1) != '/');
                        }
                        RAPIDJSON_INVALID_KEYWORD_RETURN(kValidateErrorUniqueItems);
                    }
                a->PushBack(h, GetStateAllocator());
            }
        }
        // Remove the last token of document pointer
        while (!documentStack_.Empty() && *documentStack_.template Pop<Ch>(1) != '/')
            ;
        return true;
    }
References rapidjson::a, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::kArrayType, rapidjson::kValidateErrorUniqueItems, Method, RAPIDJSON_INVALID_KEYWORD_RETURN, and RAPIDJSON_SCHEMA_PRINT.
FreeState()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::FreeState (void * p) inline virtual
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2931 of file schema.h.
{
        StateAllocator::Free(p);
    }
GetActualString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetActualString () inline static
Definition at line 2787 of file schema.h.
GetContinueOnErrors()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetContinueOnErrors () const inline private
Definition at line 2975 of file schema.h.
{
        return flags_ & kValidateContinueOnErrorFlag;
    }
References rapidjson::kValidateContinueOnErrorFlag.
GetDisallowedString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetDisallowedString () inline static
Definition at line 2788 of file schema.h.
GetDuplicatesString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetDuplicatesString () inline static
Definition at line 2793 of file schema.h.
GetError() [1/2]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> ValueType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError () inline
End of Implementation of ISchemaValidator.
Gets the error object.
Definition at line 2548 of file schema.h.
{ return error_; }
GetError() [2/2]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const ValueType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError () const inline
Definition at line 2549 of file schema.h.
{ return error_; }
GetErrorCodeString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetErrorCodeString () inline static
Definition at line 2791 of file schema.h.
GetErrorMessageString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetErrorMessageString () inline static
Definition at line 2792 of file schema.h.
GetErrorsString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetErrorsString () inline static
Definition at line 2790 of file schema.h.
GetExpectedString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetExpectedString () inline static
Definition at line 2786 of file schema.h.
GetHashCode()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual uint64_t rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode (void * hasher) inline virtual
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2917 of file schema.h.
{
        return static_cast<HasherType*>(hasher)->GetHashCode();
    }
GetInstanceRefString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInstanceRefString () inline static
Definition at line 2784 of file schema.h.
GetInvalidDocumentPointer()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> PointerType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer () const inline
Gets the JSON pointer pointed to the invalid value.
Definition at line 2575 of file schema.h.
{
        if (documentStack_.Empty()) {
            return PointerType();
        }
        else {
            return PointerType(documentStack_.template Bottom<Ch>(), documentStack_.GetSize() / sizeof(Ch));
        }
    }
GetInvalidSchemaCode()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> ValidateErrorCode rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaCode () const inline
Gets the error code of invalid schema.
Definition at line 2567 of file schema.h.
{
        if (!schemaStack_.Empty()) return CurrentContext().invalidCode;
        if (GetContinueOnErrors() && !error_.ObjectEmpty()) return kValidateErrors;
        return kValidateErrorNone;
    }
References rapidjson::kValidateErrorNone, and rapidjson::kValidateErrors.
GetInvalidSchemaKeyword()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const Ch * rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword () const inline
Gets the keyword of invalid schema.
Definition at line 2559 of file schema.h.
{
        if (!schemaStack_.Empty()) return CurrentContext().invalidKeyword;
        if (GetContinueOnErrors() && !error_.ObjectEmpty()) return static_cast<const Ch*>(GetErrorsString());
        return 0;
    }
GetInvalidSchemaPointer()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> PointerType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer () const inline
Gets the JSON pointer pointed to the invalid schema.
Definition at line 2553 of file schema.h.
{
        return schemaStack_.Empty() ? PointerType() : CurrentSchema().GetPointer();
    }
GetMatchesString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetMatchesString () inline static
Definition at line 2794 of file schema.h.
GetMissingString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetMissingString () inline static
Definition at line 2789 of file schema.h.
GetSchemaRefString()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetSchemaRefString () inline static
Definition at line 2785 of file schema.h.
GetStateAllocator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> StateAllocator & rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator () inline private
Definition at line 2969 of file schema.h.
{
        if (!stateAllocator_)
            stateAllocator_ = ownStateAllocator_ = RAPIDJSON_NEW(StateAllocator)();
        return *stateAllocator_;
    }
References RAPIDJSON_NEW.
GetValidateFlags()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual unsigned rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetValidateFlags () const inline virtual
Implements rapidjson::internal::ISchemaValidator.
Definition at line 2536 of file schema.h.
{
        return flags_;
    }
Int()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int (int i) inline
Definition at line 2831 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Int,    (CurrentContext(), i), (i)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Int64()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64 (int64_t i) inline
Definition at line 2833 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Int64,  (CurrentContext(), i), (i)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
IsValid()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid () const inline virtual
Implements rapidjson::internal::ISchemaValidator.
Definition at line 2540 of file schema.h.
{
        if (!valid_) return false;
        if (GetContinueOnErrors() && !error_.ObjectEmpty()) return false;
        return true;
    }
Key()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key (const Ch * str, SizeType len, bool copy) inline
Definition at line 2849 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::Key", str);
        if (!valid_) return false;
        AppendToken(str, len);
        if (!CurrentSchema().Key(CurrentContext(), str, len, copy) && !GetContinueOnErrors()) {
            valid_ = false;
            return valid_;
        }
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(Key, (str, len, copy));
        valid_ = !outputHandler_ || outputHandler_->Key(str, len, copy);
        return valid_;
    }
References Method, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and RAPIDJSON_SCHEMA_PRINT.
MallocState()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void * rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MallocState (size_t size) inline virtual
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2927 of file schema.h.
{
        return GetStateAllocator().Malloc(size);
    }
MergeError()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MergeError (ValueType & other) inline private
Definition at line 3130 of file schema.h.
{
        for (typename ValueType::MemberIterator it = other.MemberBegin(), end = other.MemberEnd(); it != end; ++it) {
            AddError(it->name, it->value);
        }
    }
MultipleOneOf()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MultipleOneOf (SizeType index1, SizeType index2) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2756 of file schema.h.
{
        ValueType matches(kArrayType);
        matches.PushBack(index1, GetStateAllocator());
        matches.PushBack(index2, GetStateAllocator());
        currentError_.SetObject();
        currentError_.AddMember(GetMatchesString(), matches, GetStateAllocator());
        AddCurrentError(kValidateErrorOneOfMatch);
    }
References rapidjson::kArrayType, and rapidjson::kValidateErrorOneOfMatch.
NoneOf()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NoneOf (ISchemaValidator ** subvalidators, SizeType count) inline
Definition at line 2750 of file schema.h.
{
        AddErrorArray(kValidateErrorAnyOf, subvalidators, count);
    }
References rapidjson::kValidateErrorAnyOf.
NotAllOf()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotAllOf (ISchemaValidator ** subvalidators, SizeType count) inline
Definition at line 2743 of file schema.h.
{
        // Treat allOf like oneOf and anyOf to match https://rapidjson.org/md_doc_schema.html#allOf-anyOf-oneOf
        AddErrorArray(kValidateErrorAllOf, subvalidators, count);
        //for (SizeType i = 0; i < count; ++i) {
        //    MergeError(static_cast<GenericSchemaValidator*>(subvalidators[i])->GetError());
        //}
    }
References rapidjson::kValidateErrorAllOf.
NotMultipleOf() [1/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (double actual, const SValue & expected) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2590 of file schema.h.
{
        AddNumberError(kValidateErrorMultipleOf, ValueType(actual).Move(), expected);
    }
References rapidjson::kValidateErrorMultipleOf.
NotMultipleOf() [2/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (int64_t actual, const SValue & expected) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2584 of file schema.h.
{
        AddNumberError(kValidateErrorMultipleOf, ValueType(actual).Move(), expected);
    }
References rapidjson::kValidateErrorMultipleOf.
NotMultipleOf() [3/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (uint64_t actual, const SValue & expected) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2587 of file schema.h.
{
        AddNumberError(kValidateErrorMultipleOf, ValueType(actual).Move(), expected);
    }
References rapidjson::kValidateErrorMultipleOf.
NotOneOf()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotOneOf (ISchemaValidator ** subvalidators, SizeType count) inline
Definition at line 2753 of file schema.h.
{
        AddErrorArray(kValidateErrorOneOf, subvalidators, count);
    }
References rapidjson::kValidateErrorOneOf.
Null()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null () inline
Definition at line 2829 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Null,   (CurrentContext()), ()); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
PopSchema()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema () inline private
Definition at line 3074 of file schema.h.
{
        Context* c = schemaStack_.template Pop<Context>(1);
        if (HashCodeArray* a = static_cast<HashCodeArray*>(c->arrayElementHashCodes)) {
            a->~HashCodeArray();
            StateAllocator::Free(a);
        }
        c->~Context();
    }
References rapidjson::a.
PropertyViolations()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PropertyViolations (ISchemaValidator ** subvalidators, SizeType count) inline
Definition at line 2677 of file schema.h.
{
        for (SizeType i = 0; i < count; ++i)
            MergeError(static_cast<GenericSchemaValidator*>(subvalidators[i])->GetError());
    }
PushSchema()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PushSchema (const SchemaType & schema) inline private
Definition at line 3072 of file schema.h.
{ new (schemaStack_.template Push<Context>()) Context(*this, *this, &schema, flags_); }
RawNumber()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber (const Ch * str, SizeType length, bool copy) inline
Definition at line 2836 of file schema.h.
                                    { RAPIDJSON_SCHEMA_HANDLE_VALUE_(String, (CurrentContext(), str, length, copy), (str, length, copy)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Reset()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset () inline
Reset the internal states.
Definition at line 2517 of file schema.h.
                 {
        while (!schemaStack_.Empty())
            PopSchema();
        documentStack_.Clear();
        ResetError();
    }
ResetError()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ResetError () inline
Reset the error state.
Definition at line 2525 of file schema.h.
                      {
        error_.SetObject();
        currentError_.SetNull();
        missingDependents_.SetNull();
        valid_ = true;
    }
SetValidateFlags()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SetValidateFlags (unsigned flags) inline virtual
Implementation of ISchemaValidator.
Implements rapidjson::internal::ISchemaValidator.
Definition at line 2533 of file schema.h.
{
        flags_ = flags;
    }
StartArray()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray () inline
Definition at line 2873 of file schema.h.
                      {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::StartArray");
        RAPIDJSON_SCHEMA_HANDLE_BEGIN_(StartArray, (CurrentContext()));
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(StartArray, ());
        valid_ = !outputHandler_ || outputHandler_->StartArray();
        return valid_;
    }
References Method, RAPIDJSON_SCHEMA_HANDLE_BEGIN_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and RAPIDJSON_SCHEMA_PRINT.
StartDependencyErrors()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartDependencyErrors () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2687 of file schema.h.
{
        currentError_.SetObject();
    }
StartDisallowedType()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartDisallowedType () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2730 of file schema.h.
{
        currentError_.SetArray();
    }
StartMissingDependentProperties()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartMissingDependentProperties () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2690 of file schema.h.
{
        missingDependents_.SetArray();
    }
StartMissingProperties()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartMissingProperties () inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2662 of file schema.h.
{
        currentError_.SetArray();
    }
StartObject()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject () inline
Definition at line 2841 of file schema.h.
                       {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaValidator::StartObject");
        RAPIDJSON_SCHEMA_HANDLE_BEGIN_(StartObject, (CurrentContext()));
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(StartObject, ());
        valid_ = !outputHandler_ || outputHandler_->StartObject();
        return valid_;
    }
References Method, RAPIDJSON_SCHEMA_HANDLE_BEGIN_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and RAPIDJSON_SCHEMA_PRINT.
String()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String (const Ch * str, SizeType length, bool copy) inline
Definition at line 2838 of file schema.h.
                                    { RAPIDJSON_SCHEMA_HANDLE_VALUE_(String, (CurrentContext(), str, length, copy), (str, length, copy)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
TooFewItems()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooFewItems (SizeType actualCount, SizeType expectedCount) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2637 of file schema.h.
{
        AddNumberError(kValidateErrorMinItems,
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
References rapidjson::kValidateErrorMinItems.
TooFewProperties()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooFewProperties (SizeType actualCount, SizeType expectedCount) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2658 of file schema.h.
{
        AddNumberError(kValidateErrorMinProperties,
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
References rapidjson::kValidateErrorMinProperties.
TooLong()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooLong (const Ch * str, SizeType length, SizeType expected) inline
Definition at line 2618 of file schema.h.
{
        AddNumberError(kValidateErrorMaxLength,
            ValueType(str, length, GetStateAllocator()).Move(), SValue(expected).Move());
    }
References rapidjson::kValidateErrorMaxLength.
TooManyItems()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooManyItems (SizeType actualCount, SizeType expectedCount) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2641 of file schema.h.
{
        AddNumberError(kValidateErrorMaxItems,
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
References rapidjson::kValidateErrorMaxItems.
TooManyProperties()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooManyProperties (SizeType actualCount, SizeType expectedCount) inline virtual
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2654 of file schema.h.
{
        AddNumberError(kValidateErrorMaxProperties,
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
References rapidjson::kValidateErrorMaxProperties.
TooShort()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooShort (const Ch * str, SizeType length, SizeType expected) inline
Definition at line 2622 of file schema.h.
{
        AddNumberError(kValidateErrorMinLength,
            ValueType(str, length, GetStateAllocator()).Move(), SValue(expected).Move());
    }
References rapidjson::kValidateErrorMinLength.
Uint()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint (unsigned u) inline
Definition at line 2832 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Uint,   (CurrentContext(), u), (u)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Uint64()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64 (uint64_t u) inline
Definition at line 2834 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Uint64, (CurrentContext(), u), (u)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Member Data Documentation
currentError_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> ValueType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::currentError_ private
Definition at line 3170 of file schema.h.
depth_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> unsigned rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::depth_ private
Definition at line 3174 of file schema.h.
documentStack_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> internal::Stack<StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_ private
stack to store the current path of validating document (Ch)
Definition at line 3167 of file schema.h.
error_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> ValueType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::error_ private
Definition at line 3169 of file schema.h.
flags_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> unsigned rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::flags_ private
Definition at line 3173 of file schema.h.
kDefaultDocumentStackCapacity
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const size_t rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::kDefaultDocumentStackCapacity = 256 static private
Definition at line 3161 of file schema.h.
kDefaultSchemaStackCapacity
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const size_t rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::kDefaultSchemaStackCapacity = 1024 static private
Definition at line 3160 of file schema.h.
missingDependents_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> ValueType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::missingDependents_ private
Definition at line 3171 of file schema.h.
outputHandler_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> OutputHandler* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::outputHandler_ private
Definition at line 3168 of file schema.h.
ownStateAllocator_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> StateAllocator* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ownStateAllocator_ private
Definition at line 3165 of file schema.h.
root_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const SchemaType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::root_ private
Definition at line 3163 of file schema.h.
schemaDocument_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const SchemaDocumentType* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaDocument_ private
Definition at line 3162 of file schema.h.
schemaStack_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> internal::Stack<StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_ private
stack to store the current path of schema (BaseSchemaType *)
Definition at line 3166 of file schema.h.
stateAllocator_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> StateAllocator* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::stateAllocator_ private
Definition at line 3164 of file schema.h.
valid_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_ private
Definition at line 3172 of file schema.h.
The documentation for this class was generated from the following files:
rapidjson/include/rapidjson/fwd.h
rapidjson/include/rapidjson/schema.h