wiNpoS: testing::internal::StrEqualityMatcher< StringType > Class Template Reference
testing::internal::StrEqualityMatcher< StringType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
StrEqualityMatcher (const StringType &str, bool expect_eq, bool case_sensitive)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
void DescribeToHelper (bool expect_eq, ::std::ostream *os) const
GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher)
Private Attributes
const StringType string_
const bool expect_eq_
const bool case_sensitive_
Detailed Description
template<typename StringType>
class testing::internal::StrEqualityMatcher< StringType >
Definition at line 1295 of file gmock-matchers.h.
Constructor & Destructor Documentation
StrEqualityMatcher()
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::StrEqualityMatcher (const StringType & str, bool expect_eq, bool case_sensitive) inline
Definition at line 1297 of file gmock-matchers.h.
      : string_(str), expect_eq_(expect_eq), case_sensitive_(case_sensitive) {}
Member Function Documentation
DescribeNegationTo()
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1344 of file gmock-matchers.h.
{
    DescribeToHelper(!expect_eq_, os);
  }
References testing::internal::StrEqualityMatcher< StringType >::DescribeToHelper(), and testing::internal::StrEqualityMatcher< StringType >::expect_eq_.
DescribeTo()
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
Definition at line 1340 of file gmock-matchers.h.
{
    DescribeToHelper(expect_eq_, os);
  }
References testing::internal::StrEqualityMatcher< StringType >::DescribeToHelper(), and testing::internal::StrEqualityMatcher< StringType >::expect_eq_.
DescribeToHelper()
template<typename StringType > void testing::internal::StrEqualityMatcher< StringType >::DescribeToHelper (bool expect_eq, ::std::ostream * os) const inline private
Definition at line 1349 of file gmock-matchers.h.
{
    *os << (expect_eq ? "is " : "isn't ");
    *os << "equal to ";
    if (!case_sensitive_) {
      *os << "(ignoring case) ";
    }
    UniversalPrint(string_, os);
  }
References testing::internal::StrEqualityMatcher< StringType >::case_sensitive_, testing::internal::StrEqualityMatcher< StringType >::string_, and testing::internal::UniversalPrint().
GTEST_DISALLOW_ASSIGN_()
template<typename StringType > testing::internal::StrEqualityMatcher< StringType >::GTEST_DISALLOW_ASSIGN_ (StrEqualityMatcher< StringType >) private
MatchAndExplain() [1/2]
template<typename StringType > template<typename CharType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1320 of file gmock-matchers.h.
{
    if (s == NULL) {
      return !expect_eq_;
    }
    return MatchAndExplain(StringType(s), listener);
  }
References testing::internal::StrEqualityMatcher< StringType >::expect_eq_, and testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain().
MatchAndExplain() [2/2]
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1332 of file gmock-matchers.h.
{
    const StringType& s2(s);
    const bool eq = case_sensitive_ ? s2 == string_ :
        CaseInsensitiveStringEquals(s2, string_);
    return expect_eq_ == eq;
  }
References testing::internal::StrEqualityMatcher< StringType >::case_sensitive_, testing::internal::CaseInsensitiveStringEquals(), testing::internal::StrEqualityMatcher< StringType >::expect_eq_, and testing::internal::StrEqualityMatcher< StringType >::string_.
Member Data Documentation
case_sensitive_
template<typename StringType > const bool testing::internal::StrEqualityMatcher< StringType >::case_sensitive_ private
Definition at line 1360 of file gmock-matchers.h.
expect_eq_
template<typename StringType > const bool testing::internal::StrEqualityMatcher< StringType >::expect_eq_ private
Definition at line 1359 of file gmock-matchers.h.
string_
template<typename StringType > const StringType testing::internal::StrEqualityMatcher< StringType >::string_ private
Definition at line 1358 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h