wiNpoS: testing::internal::DefaultGlobalTestPartResultReporter Class Reference
testing::internal::DefaultGlobalTestPartResultReporter Class Reference
#include <gtest-internal-inl.h>
Public Member Functions
DefaultGlobalTestPartResultReporter (UnitTestImpl *unit_test)
virtual void ReportTestPartResult (const TestPartResult &result)
Public Member Functions inherited from testing::TestPartResultReporterInterface
virtual ~TestPartResultReporterInterface ()
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter)
Private Attributes
UnitTestImpl *const unit_test_
Detailed Description
Definition at line 461 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
DefaultGlobalTestPartResultReporter()
testing::internal::DefaultGlobalTestPartResultReporter::DefaultGlobalTestPartResultReporter (UnitTestImpl * unit_test) explicit
Definition at line 700 of file gtest.cc.
                             : unit_test_(unit_test) {}
Member Function Documentation
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::internal::DefaultGlobalTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (DefaultGlobalTestPartResultReporter) private
ReportTestPartResult()
void testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) virtual
Implements testing::TestPartResultReporterInterface.
Definition at line 703 of file gtest.cc.
{
  unit_test_->current_test_result()->AddTestPartResult(result);
  unit_test_->listeners()->repeater()->OnTestPartResult(result);
}
References testing::TestResult::AddTestPartResult(), testing::internal::UnitTestImpl::current_test_result(), testing::internal::UnitTestImpl::listeners(), testing::TestEventListener::OnTestPartResult(), testing::TestEventListeners::repeater(), and unit_test_.
Member Data Documentation
unit_test_
UnitTestImpl* const testing::internal::DefaultGlobalTestPartResultReporter::unit_test_ private
Definition at line 470 of file gtest-internal-inl.h.
The documentation for this class was generated from the following files:
rapidjson/thirdparty/gtest/googletest/src/gtest-internal-inl.h
rapidjson/thirdparty/gtest/googletest/src/gtest.cc