wiNpoS: rapidjson::GenericSchemaDocument< ValueT, Allocator > Class Template Reference
rapidjson::GenericSchemaDocument< ValueT, Allocator > Class Template Reference
JSON schema document.
#include <schema.h>
Classes
struct SchemaEntry
Public Types
typedef ValueT ValueType
typedef IGenericRemoteSchemaDocumentProvider< GenericSchemaDocument > IRemoteSchemaDocumentProviderType
typedef Allocator AllocatorType
typedef ValueType::EncodingType EncodingType
typedef EncodingType::Ch Ch
typedef internal::Schema< GenericSchemaDocument > SchemaType
typedef GenericPointer< ValueType, Allocator > PointerType
typedef GenericValue< EncodingType, AllocatorType > GValue
typedef GenericUri< ValueType, Allocator > UriType
typedef GenericStringRef< Ch > StringRefType
Public Member Functions
GenericSchemaDocument (const ValueType &document, const Ch *uri=0, SizeType uriLength=0, IRemoteSchemaDocumentProviderType *remoteProvider=0, Allocator *allocator=0, const PointerType &pointer=PointerType(), const Specification &spec=Specification(kDraft04))
Constructor.
~GenericSchemaDocument ()
Destructor.
const GValue & GetURI () const
const Specification & GetSpecification () const
bool IsSupportedSpecification () const
const SchemaType & GetRoot () const
Get the root schema.
GValue & GetError ()
Gets the error object.
const GValue & GetError () const
void SchemaError (const SchemaErrorCode code, const PointerType &location)
Default error method.
void SchemaErrorValue (const SchemaErrorCode code, const PointerType &location, const Ch *value, SizeType length)
Method for error with single string value insert.
void SchemaErrorPointer (const SchemaErrorCode code, const PointerType &location, const Ch *value, SizeType length, const PointerType &pointer)
Method for error with invalid pointer.
Static Public Member Functions
static const Specification GetSpecification (const ValueType &document)
Static method to get the specification of any schema document.
static const StringRefType & GetSchemaErrorKeyword (SchemaErrorCode schemaErrorCode)
Private Types
typedef const PointerType * SchemaRefPtr
Private Member Functions
GenericSchemaDocument (const GenericSchemaDocument &)
Prohibit copying.
GenericSchemaDocument & operator= (const GenericSchemaDocument &)
Prohibit assignment.
void AddErrorInstanceLocation (GValue &result, const PointerType &location)
void AddError (GValue &keyword, GValue &error)
void AddCurrentError (const SchemaErrorCode code, const PointerType &location)
void SetSchemaSpecification (const ValueType &document)
void CreateSchemaRecursive (const SchemaType **schema, const PointerType &pointer, const ValueType &v, const ValueType &document, const UriType &id)
const UriType & CreateSchema (const SchemaType **schema, const PointerType &pointer, const ValueType &v, const ValueType &document, const UriType &id)
bool HandleRefSchema (const PointerType &source, const SchemaType **schema, const ValueType &v, const ValueType &document, const UriType &id)
ValueType * FindId (const ValueType &doc, const UriType &finduri, PointerType &resptr, const UriType &baseuri, bool full, const PointerType &here=PointerType()) const
Find the first subschema with a resolved 'id' that matches the specified URI.
void AddSchemaRefs (SchemaType *schema)
bool IsCyclicRef (const PointerType &pointer) const
const SchemaType * GetSchema (const PointerType &pointer) const
PointerType GetPointer (const SchemaType *schema) const
const SchemaType * GetTypeless () const
Static Private Member Functions
static const StringRefType & GetInstanceRefString ()
static const StringRefType & GetErrorCodeString ()
static const StringRefType & GetValueString ()
static const StringRefType & GetOffsetString ()
static const StringRefType & GetNullString ()
static const StringRefType & GetSpecUnknownString ()
static const StringRefType & GetSpecUnsupportedString ()
static const StringRefType & GetSpecIllegalString ()
static const StringRefType & GetStartUnknownString ()
static const StringRefType & GetRefPlainNameString ()
static const StringRefType & GetRefInvalidString ()
static const StringRefType & GetRefPointerInvalidString ()
static const StringRefType & GetRefUnknownString ()
static const StringRefType & GetRefCyclicalString ()
static const StringRefType & GetRefNoRemoteProviderString ()
static const StringRefType & GetRefNoRemoteSchemaString ()
static const StringRefType & GetReadOnlyAndWriteOnlyString ()
static const StringRefType & GetRegexInvalidString ()
static SchemaDraft GetSchemaDraft (const ValueType &document)
static OpenApiVersion GetOpenApiVersion (const ValueType &document)
Private Attributes
IRemoteSchemaDocumentProviderType * remoteProvider_
Allocator * allocator_
Allocator * ownAllocator_
const SchemaType * root_
Root schema.
SchemaType * typeless_
internal::Stack< Allocator > schemaMap_
internal::Stack< Allocator > schemaRef_
GValue uri_
UriType docId_
Specification spec_
GValue error_
GValue currentError_
Static Private Attributes
static const size_t kInitialSchemaMapSize = 64
static const size_t kInitialSchemaRefSize = 64
Friends
class internal::Schema< GenericSchemaDocument >
template<typename , typename , typename >
class GenericSchemaValidator
Detailed Description
template<typename ValueT, typename Allocator = CrtAllocator>
class rapidjson::GenericSchemaDocument< ValueT, Allocator >
JSON schema document.
A JSON schema document is a compiled version of a JSON schema. It is basically a tree of internal::Schema.
Note
This is an immutable class (i.e. its instance cannot be modified after construction).
Template Parameters
ValueT Type of JSON value (e.g. Value), which also determine the encoding.
Allocator Allocator type for allocating memory of this document.
Definition at line 1814 of file schema.h.
Member Typedef Documentation
AllocatorType
template<typename ValueT , typename Allocator = CrtAllocator> typedef Allocator rapidjson::GenericSchemaDocument< ValueT, Allocator >::AllocatorType
Definition at line 1818 of file schema.h.
Ch
template<typename ValueT , typename Allocator = CrtAllocator> typedef EncodingType::Ch rapidjson::GenericSchemaDocument< ValueT, Allocator >::Ch
Definition at line 1820 of file schema.h.
EncodingType
template<typename ValueT , typename Allocator = CrtAllocator> typedef ValueType::EncodingType rapidjson::GenericSchemaDocument< ValueT, Allocator >::EncodingType
Definition at line 1819 of file schema.h.
GValue
template<typename ValueT , typename Allocator = CrtAllocator> typedef GenericValue<EncodingType, AllocatorType> rapidjson::GenericSchemaDocument< ValueT, Allocator >::GValue
Definition at line 1823 of file schema.h.
IRemoteSchemaDocumentProviderType
template<typename ValueT , typename Allocator = CrtAllocator> typedef IGenericRemoteSchemaDocumentProvider<GenericSchemaDocument> rapidjson::GenericSchemaDocument< ValueT, Allocator >::IRemoteSchemaDocumentProviderType
Definition at line 1817 of file schema.h.
PointerType
template<typename ValueT , typename Allocator = CrtAllocator> typedef GenericPointer<ValueType, Allocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::PointerType
Definition at line 1822 of file schema.h.
SchemaRefPtr
template<typename ValueT , typename Allocator = CrtAllocator> typedef const PointerType* rapidjson::GenericSchemaDocument< ValueT, Allocator >::SchemaRefPtr private
Definition at line 2006 of file schema.h.
SchemaType
template<typename ValueT , typename Allocator = CrtAllocator> typedef internal::Schema<GenericSchemaDocument> rapidjson::GenericSchemaDocument< ValueT, Allocator >::SchemaType
Definition at line 1821 of file schema.h.
StringRefType
template<typename ValueT , typename Allocator = CrtAllocator> typedef GenericStringRef<Ch> rapidjson::GenericSchemaDocument< ValueT, Allocator >::StringRefType
Definition at line 1825 of file schema.h.
UriType
template<typename ValueT , typename Allocator = CrtAllocator> typedef GenericUri<ValueType, Allocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::UriType
Definition at line 1824 of file schema.h.
ValueType
template<typename ValueT , typename Allocator = CrtAllocator> typedef ValueT rapidjson::GenericSchemaDocument< ValueT, Allocator >::ValueType
Definition at line 1816 of file schema.h.
Constructor & Destructor Documentation
GenericSchemaDocument() [1/2]
template<typename ValueT , typename Allocator = CrtAllocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument (const ValueType & document, const Ch * uri = 0, SizeType uriLength = 0, IRemoteSchemaDocumentProviderType * remoteProvider = 0, Allocator * allocator = 0, const PointerType & pointer = PointerType(), const Specification & spec = Specification(kDraft04)) inline explicit
Constructor.
Compile a JSON document into schema document.
Parameters
document A JSON document as source.
uri The base URI of this schema document for purposes of violation reporting.
uriLength Length of name, in code points.
remoteProvider An optional remote schema document provider for resolving remote reference. Can be null.
allocator An optional allocator instance for allocating memory. Can be null.
pointer An optional JSON pointer to the start of the schema document
spec Optional schema draft or OpenAPI version. Used if no specification in document. Defaults to draft-04.
Definition at line 1842 of file schema.h.
                                                             :
        remoteProvider_(remoteProvider),
        allocator_(allocator),
        ownAllocator_(),
        root_(),
        typeless_(),
        schemaMap_(allocator, kInitialSchemaMapSize),
        schemaRef_(allocator, kInitialSchemaRefSize),
        spec_(spec),
        error_(kObjectType),
        currentError_()
    {
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaDocument::GenericSchemaDocument");
        if (!allocator_)
            ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
        Ch noUri[1] = {0};
        uri_.SetString(uri ? uri : noUri, uriLength, *allocator_);
        docId_ = UriType(uri_, allocator_);
        typeless_ = static_cast<SchemaType*>(allocator_->Malloc(sizeof(SchemaType)));
        new (typeless_) SchemaType(this, PointerType(), ValueType(kObjectType).Move(), ValueType(kObjectType).Move(), allocator_, docId_);
        // Establish the schema draft or open api version.
        // We only ever look for '$schema' or 'swagger' or 'openapi' at the root of the document.
        SetSchemaSpecification(document);
        // Generate root schema, it will call CreateSchema() to create sub-schemas,
        // And call HandleRefSchema() if there are $ref.
        // PR #1393 use input pointer if supplied
        root_ = typeless_;
        if (pointer.GetTokenCount() == 0) {
            CreateSchemaRecursive(&root_, pointer, document, document, docId_);
        }
        else if (const ValueType* v = pointer.Get(document)) {
            CreateSchema(&root_, pointer, *v, document, docId_);
        }
        else {
            GenericStringBuffer<EncodingType> sb;
            pointer.StringifyUriFragment(sb);
            SchemaErrorValue(kSchemaErrorStartUnknown, PointerType(), sb.GetString(), static_cast<SizeType>(sb.GetSize() / sizeof(Ch)));
        }
        RAPIDJSON_ASSERT(root_ != 0);
        schemaRef_.ShrinkToFit(); // Deallocate all memory for ref
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::kObjectType, rapidjson::kSchemaErrorStartUnknown, Method, rapidjson::pointer, RAPIDJSON_ASSERT, RAPIDJSON_NEW, and RAPIDJSON_SCHEMA_PRINT.
~GenericSchemaDocument()
template<typename ValueT , typename Allocator = CrtAllocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::~GenericSchemaDocument () inline
Destructor.
Definition at line 1917 of file schema.h.
{
        while (!schemaMap_.Empty())
            schemaMap_.template Pop<SchemaEntry>(1)->~SchemaEntry();
        if (typeless_) {
            typeless_->~SchemaType();
            Allocator::Free(typeless_);
        }
        // these may contain some allocator data so clear before deleting ownAllocator_
        uri_.SetNull();
        error_.SetNull();
        currentError_.SetNull();
        RAPIDJSON_DELETE(ownAllocator_);
    }
References RAPIDJSON_DELETE.
GenericSchemaDocument() [2/2]
template<typename ValueT , typename Allocator = CrtAllocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument (const GenericSchemaDocument< ValueT, Allocator > &) private
Prohibit copying.
Member Function Documentation
AddCurrentError()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::AddCurrentError (const SchemaErrorCode code, const PointerType & location) inline private
Definition at line 2042 of file schema.h.
{
      RAPIDJSON_SCHEMA_PRINT(InvalidKeyword, GetSchemaErrorKeyword(code));
      currentError_.AddMember(GetErrorCodeString(), code, *allocator_);
      AddErrorInstanceLocation(currentError_, location);
      AddError(GValue(GetSchemaErrorKeyword(code)).Move(), currentError_);
    }
References RAPIDJSON_SCHEMA_PRINT.
AddError()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::AddError (GValue & keyword, GValue & error) inline private
Definition at line 2028 of file schema.h.
{
      typename GValue::MemberIterator member = error_.FindMember(keyword);
      if (member == error_.MemberEnd())
        error_.AddMember(keyword, error, *allocator_);
      else {
        if (member->value.IsObject()) {
          GValue errors(kArrayType);
          errors.PushBack(member->value, *allocator_);
          member->value = errors;
        }
        member->value.PushBack(error, *allocator_);
      }
    }
References rapidjson::kArrayType.
AddErrorInstanceLocation()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::AddErrorInstanceLocation (GValue & result, const PointerType & location) inline private
Definition at line 2021 of file schema.h.
{
      GenericStringBuffer<EncodingType> sb;
      location.StringifyUriFragment(sb);
      GValue instanceRef(sb.GetString(), static_cast<SizeType>(sb.GetSize() / sizeof(Ch)), *allocator_);
      result.AddMember(GetInstanceRefString(), instanceRef, *allocator_);
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString().
AddSchemaRefs()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::AddSchemaRefs (SchemaType * schema) inline private
Definition at line 2362 of file schema.h.
{
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaDocument::AddSchemaRefs");
        while (!schemaRef_.Empty()) {
            SchemaRefPtr *ref = schemaRef_.template Pop<SchemaRefPtr>(1);
            SchemaEntry *entry = schemaMap_.template Push<SchemaEntry>();
            new (entry) SchemaEntry(**ref, schema, false, allocator_);
        }
    }
References Method, and RAPIDJSON_SCHEMA_PRINT.
CreateSchema()
template<typename ValueT , typename Allocator = CrtAllocator> const UriType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::CreateSchema (const SchemaType ** schema, const PointerType & pointer, const ValueType & v, const ValueType & document, const UriType & id) inline private
Definition at line 2175 of file schema.h.
{
        RAPIDJSON_ASSERT(pointer.IsValid());
        GenericStringBuffer<EncodingType> sb;
        pointer.StringifyUriFragment(sb);
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaDocument::CreateSchema", sb.GetString(), id.GetString());
        if (v.IsObject()) {
            if (const SchemaType* sc = GetSchema(pointer)) {
                if (schema)
                    *schema = sc;
                AddSchemaRefs(const_cast<SchemaType*>(sc));
            }
            else if (!HandleRefSchema(pointer, schema, v, document, id)) {
                // The new schema constructor adds itself and its $ref(s) to schemaMap_
                SchemaType* s = new (allocator_->Malloc(sizeof(SchemaType))) SchemaType(this, pointer, v, document, allocator_, id);
                if (schema)
                    *schema = s;
                return s->GetId();
            }
        }
        else {
            if (schema)
                *schema = typeless_;
            AddSchemaRefs(typeless_);
        }
        return id;
    }
References rapidjson::internal::Schema< SchemaDocumentType >::GetId(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), Method, rapidjson::pointer, RAPIDJSON_ASSERT, and RAPIDJSON_SCHEMA_PRINT.
CreateSchemaRecursive()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive (const SchemaType ** schema, const PointerType & pointer, const ValueType & v, const ValueType & document, const UriType & id) inline private
Definition at line 2162 of file schema.h.
{
        if (v.GetType() == kObjectType) {
            UriType newid = UriType(CreateSchema(schema, pointer, v, document, id), allocator_);
            for (typename ValueType::ConstMemberIterator itr = v.MemberBegin(); itr != v.MemberEnd(); ++itr)
                CreateSchemaRecursive(0, pointer.Append(itr->name, allocator_), itr->value, document, newid);
        }
        else if (v.GetType() == kArrayType)
            for (SizeType i = 0; i < v.Size(); i++)
                CreateSchemaRecursive(0, pointer.Append(i, allocator_), v[i], document, id);
    }
References rapidjson::kArrayType, rapidjson::kObjectType, and rapidjson::pointer.
FindId()
template<typename ValueT , typename Allocator = CrtAllocator> ValueType * rapidjson::GenericSchemaDocument< ValueT, Allocator >::FindId (const ValueType & doc, const UriType & finduri, PointerType & resptr, const UriType & baseuri, bool full, const PointerType & here = PointerType()) const inline private
Find the first subschema with a resolved 'id' that matches the specified URI.
Definition at line 2323 of file schema.h.
{
        SizeType i = 0;
        ValueType* resval = 0;
        UriType tempuri = UriType(finduri, allocator_);
        UriType localuri = UriType(baseuri, allocator_);
        if (doc.GetType() == kObjectType) {
            // Establish the base URI of this object
            typename ValueType::ConstMemberIterator m = doc.FindMember(SchemaType::GetIdString());
            if (m != doc.MemberEnd() && m->value.GetType() == kStringType) {
                localuri = UriType(m->value, allocator_).Resolve(baseuri, allocator_);
            }
            // See if it matches
            if (localuri.Match(finduri, full)) {
                RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaDocument::FindId (match)", full ? localuri.GetString() : localuri.GetBaseString());
                resval = const_cast<ValueType *>(&doc);
                resptr = here;
                return resval;
            }
            // No match, continue looking
            for (m = doc.MemberBegin(); m != doc.MemberEnd(); ++m) {
                if (m->value.GetType() == kObjectType || m->value.GetType() == kArrayType) {
                    resval = FindId(m->value, finduri, resptr, localuri, full, here.Append(m->name.GetString(), m->name.GetStringLength(), allocator_));
                }
                if (resval) break;
            }
        } else if (doc.GetType() == kArrayType) {
            // Continue looking
            for (typename ValueType::ConstValueIterator v = doc.Begin(); v != doc.End(); ++v) {
                if (v->GetType() == kObjectType || v->GetType() == kArrayType) {
                    resval = FindId(*v, finduri, resptr, localuri, full, here.Append(i, allocator_));
                }
                if (resval) break;
                i++;
            }
        }
        return resval;
    }
References rapidjson::GenericUri< ValueType, Allocator >::GetBaseString(), rapidjson::GenericUri< ValueType, Allocator >::GetString(), rapidjson::kArrayType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::GenericUri< ValueType, Allocator >::Match(), Method, RAPIDJSON_SCHEMA_PRINT, and rapidjson::GenericUri< ValueType, Allocator >::Resolve().
GetError() [1/2]
template<typename ValueT , typename Allocator = CrtAllocator> GValue & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetError () inline
Gets the error object.
Definition at line 1957 of file schema.h.
{ return error_; }
GetError() [2/2]
template<typename ValueT , typename Allocator = CrtAllocator> const GValue & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetError () const inline
Definition at line 1958 of file schema.h.
{ return error_; }
GetErrorCodeString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetErrorCodeString () inline static private
Definition at line 2057 of file schema.h.
GetInstanceRefString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetInstanceRefString () inline static private
Definition at line 2056 of file schema.h.
GetNullString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetNullString () inline static private
Definition at line 2061 of file schema.h.
GetOffsetString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetOffsetString () inline static private
Definition at line 2059 of file schema.h.
GetOpenApiVersion()
template<typename ValueT , typename Allocator = CrtAllocator> static OpenApiVersion rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetOpenApiVersion (const ValueType & document) inline static private
Definition at line 2113 of file schema.h.
{
        static const Ch kVersion20String[] = { '2', '.', '0', '\0' };
        static const Ch kVersion30String[] = { '3', '.', '0', '.', '\0' }; // ignore patch level
        static const Ch kVersion31String[] = { '3', '.', '1', '.', '\0' }; // ignore patch level
        static SizeType len = internal::StrLen<Ch>(kVersion30String);
        if (!document.IsObject()) {
            return kVersionNone;
        }
        // Get the open api version from the swagger / openapi keyword at the supplied location
        typename ValueType::ConstMemberIterator itr = document.FindMember(SchemaType::GetSwaggerString());
        if (itr == document.MemberEnd()) itr = document.FindMember(SchemaType::GetOpenApiString());
        if (itr != document.MemberEnd()) {
            if (!itr->value.IsString()) return kVersionUnknown;
            const ValueType kVersion20Value(kVersion20String);
            if (kVersion20Value == itr->value) return kVersion20; // must match 2.0 exactly
            const ValueType kVersion30Value(kVersion30String);
            if (itr->value.GetStringLength() > len && kVersion30Value == ValueType(itr->value.GetString(), len)) return kVersion30; // must match 3.0.x
            const ValueType kVersion31Value(kVersion31String);
            if (itr->value.GetStringLength() > len && kVersion31Value == ValueType(itr->value.GetString(), len)) return kVersion31; // must match 3.1.x
            return kVersionUnknown;
        }
        // swagger or openapi not found
        return kVersionNone;
    }
References rapidjson::kVersion20, rapidjson::kVersion30, rapidjson::kVersion31, rapidjson::kVersionNone, and rapidjson::kVersionUnknown.
GetPointer()
template<typename ValueT , typename Allocator = CrtAllocator> PointerType rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetPointer (const SchemaType * schema) const inline private
Definition at line 2386 of file schema.h.
{
        for (const SchemaEntry* target = schemaMap_.template Bottom<SchemaEntry>(); target != schemaMap_.template End<SchemaEntry>(); ++target)
            if (schema == target->schema)
                return target->pointer;
        return PointerType();
    }
GetReadOnlyAndWriteOnlyString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetReadOnlyAndWriteOnlyString () inline static private
Definition at line 2073 of file schema.h.
GetRefCyclicalString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefCyclicalString () inline static private
Definition at line 2070 of file schema.h.
GetRefInvalidString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefInvalidString () inline static private
Definition at line 2067 of file schema.h.
GetRefNoRemoteProviderString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefNoRemoteProviderString () inline static private
Definition at line 2071 of file schema.h.
GetRefNoRemoteSchemaString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefNoRemoteSchemaString () inline static private
Definition at line 2072 of file schema.h.
GetRefPlainNameString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefPlainNameString () inline static private
Definition at line 2066 of file schema.h.
GetRefPointerInvalidString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefPointerInvalidString () inline static private
Definition at line 2068 of file schema.h.
GetRefUnknownString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRefUnknownString () inline static private
Definition at line 2069 of file schema.h.
GetRegexInvalidString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRegexInvalidString () inline static private
Definition at line 2074 of file schema.h.
GetRoot()
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetRoot () const inline
Get the root schema.
Definition at line 1954 of file schema.h.
{ return *root_; }
GetSchema()
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType * rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSchema (const PointerType & pointer) const inline private
Definition at line 2379 of file schema.h.
{
        for (const SchemaEntry* target = schemaMap_.template Bottom<SchemaEntry>(); target != schemaMap_.template End<SchemaEntry>(); ++target)
            if (pointer == target->pointer)
                return target->schema;
        return 0;
    }
References rapidjson::pointer.
GetSchemaDraft()
template<typename ValueT , typename Allocator = CrtAllocator> static SchemaDraft rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSchemaDraft (const ValueType & document) inline static private
Definition at line 2079 of file schema.h.
{
        static const Ch kDraft03String[] = { 'h', 't', 't', 'p', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '-', '0', '3', '/', 's', 'c', 'h', 'e', 'm', 'a', '#', '\0' };
        static const Ch kDraft04String[] = { 'h', 't', 't', 'p', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '-', '0', '4', '/', 's', 'c', 'h', 'e', 'm', 'a', '#', '\0' };
        static const Ch kDraft05String[] = { 'h', 't', 't', 'p', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '-', '0', '5', '/', 's', 'c', 'h', 'e', 'm', 'a', '#', '\0' };
        static const Ch kDraft06String[] = { 'h', 't', 't', 'p', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '-', '0', '6', '/', 's', 'c', 'h', 'e', 'm', 'a', '#', '\0' };
        static const Ch kDraft07String[] = { 'h', 't', 't', 'p', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '-', '0', '7', '/', 's', 'c', 'h', 'e', 'm', 'a', '#', '\0' };
        static const Ch kDraft2019_09String[] = { 'h', 't', 't', 'p', 's', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '/', '2', '0', '1', '9', '-', '0', '9', '/', 's', 'c', 'h', 'e', 'm', 'a', '\0' };
        static const Ch kDraft2020_12String[] = { 'h', 't', 't', 'p', 's', ':', '/', '/', 'j', 's', 'o', 'n', '-', 's', 'c', 'h', 'e', 'm', 'a', '.', 'o', 'r', 'g', '/', 'd', 'r', 'a', 'f', 't', '/', '2', '0', '2', '0', '-', '1', '2', '/', 's', 'c', 'h', 'e', 'm', 'a', '\0' };
        if (!document.IsObject()) {
            return kDraftNone;
        }
        // Get the schema draft from the $schema keyword at the supplied location
        typename ValueType::ConstMemberIterator itr = document.FindMember(SchemaType::GetSchemaString());
        if (itr != document.MemberEnd()) {
            if (!itr->value.IsString()) return kDraftUnknown;
            const UriType draftUri(itr->value);
            // Check base uri for match
            if (draftUri.Match(UriType(kDraft04String), false)) return kDraft04;
            if (draftUri.Match(UriType(kDraft05String), false)) return kDraft05;
            if (draftUri.Match(UriType(kDraft06String), false)) return kDraft06;
            if (draftUri.Match(UriType(kDraft07String), false)) return kDraft07;
            if (draftUri.Match(UriType(kDraft03String), false)) return kDraft03;
            if (draftUri.Match(UriType(kDraft2019_09String), false)) return kDraft2019_09;
            if (draftUri.Match(UriType(kDraft2020_12String), false)) return kDraft2020_12;
            return kDraftUnknown;
        }
        // $schema not found
        return kDraftNone;
    }
References rapidjson::kDraft03, rapidjson::kDraft04, rapidjson::kDraft05, rapidjson::kDraft06, rapidjson::kDraft07, rapidjson::kDraft2019_09, rapidjson::kDraft2020_12, rapidjson::kDraftNone, rapidjson::kDraftUnknown, and rapidjson::GenericUri< ValueType, Allocator >::Match().
GetSchemaErrorKeyword()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSchemaErrorKeyword (SchemaErrorCode schemaErrorCode) inline static
Definition at line 1960 of file schema.h.
{
        switch (schemaErrorCode) {
            case kSchemaErrorStartUnknown:             return GetStartUnknownString();
            case kSchemaErrorRefPlainName:             return GetRefPlainNameString();
            case kSchemaErrorRefInvalid:               return GetRefInvalidString();
            case kSchemaErrorRefPointerInvalid:        return GetRefPointerInvalidString();
            case kSchemaErrorRefUnknown:               return GetRefUnknownString();
            case kSchemaErrorRefCyclical:              return GetRefCyclicalString();
            case kSchemaErrorRefNoRemoteProvider:      return GetRefNoRemoteProviderString();
            case kSchemaErrorRefNoRemoteSchema:        return GetRefNoRemoteSchemaString();
            case kSchemaErrorRegexInvalid:             return GetRegexInvalidString();
            case kSchemaErrorSpecUnknown:              return GetSpecUnknownString();
            case kSchemaErrorSpecUnsupported:          return GetSpecUnsupportedString();
            case kSchemaErrorSpecIllegal:              return GetSpecIllegalString();
            case kSchemaErrorReadOnlyAndWriteOnly:     return GetReadOnlyAndWriteOnlyString();
            default:                                   return GetNullString();
        }
    }
References rapidjson::kSchemaErrorReadOnlyAndWriteOnly, rapidjson::kSchemaErrorRefCyclical, rapidjson::kSchemaErrorRefInvalid, rapidjson::kSchemaErrorRefNoRemoteProvider, rapidjson::kSchemaErrorRefNoRemoteSchema, rapidjson::kSchemaErrorRefPlainName, rapidjson::kSchemaErrorRefPointerInvalid, rapidjson::kSchemaErrorRefUnknown, rapidjson::kSchemaErrorRegexInvalid, rapidjson::kSchemaErrorSpecIllegal, rapidjson::kSchemaErrorSpecUnknown, rapidjson::kSchemaErrorSpecUnsupported, and rapidjson::kSchemaErrorStartUnknown.
GetSpecification() [1/2]
template<typename ValueT , typename Allocator = CrtAllocator> const Specification & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSpecification () const inline
Definition at line 1936 of file schema.h.
{ return spec_; }
GetSpecification() [2/2]
template<typename ValueT , typename Allocator = CrtAllocator> static const Specification rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSpecification (const ValueType & document) inline static
Static method to get the specification of any schema document.
Definition at line 1941 of file schema.h.
{
      SchemaDraft draft = GetSchemaDraft(document);
      if (draft != kDraftNone)
        return Specification(draft);
      else {
        OpenApiVersion oapi = GetOpenApiVersion(document);
        if (oapi != kVersionNone)
          return Specification(oapi);
      }
      return Specification(kDraftNone);
    }
References rapidjson::kDraftNone, and rapidjson::kVersionNone.
GetSpecIllegalString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSpecIllegalString () inline static private
Definition at line 2064 of file schema.h.
GetSpecUnknownString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSpecUnknownString () inline static private
Definition at line 2062 of file schema.h.
GetSpecUnsupportedString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSpecUnsupportedString () inline static private
Definition at line 2063 of file schema.h.
GetStartUnknownString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetStartUnknownString () inline static private
Definition at line 2065 of file schema.h.
GetTypeless()
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType * rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetTypeless () const inline private
Definition at line 2393 of file schema.h.
{ return typeless_; }
GetURI()
template<typename ValueT , typename Allocator = CrtAllocator> const GValue & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetURI () const inline
Definition at line 1934 of file schema.h.
{ return uri_; }
GetValueString()
template<typename ValueT , typename Allocator = CrtAllocator> static const StringRefType & rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetValueString () inline static private
Definition at line 2058 of file schema.h.
HandleRefSchema()
template<typename ValueT , typename Allocator = CrtAllocator> bool rapidjson::GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema (const PointerType & source, const SchemaType ** schema, const ValueType & v, const ValueType & document, const UriType & id) inline private
Definition at line 2204 of file schema.h.
{
        typename ValueType::ConstMemberIterator itr = v.FindMember(SchemaType::GetRefString());
        if (itr == v.MemberEnd())
            return false;
        GenericStringBuffer<EncodingType> sb;
        source.StringifyUriFragment(sb);
        RAPIDJSON_SCHEMA_PRINT(Method, "GenericSchemaDocument::HandleRefSchema", sb.GetString(), id.GetString());
        // Resolve the source pointer to the $ref'ed schema (finally)
        new (schemaRef_.template Push<SchemaRefPtr>()) SchemaRefPtr(&source);
        if (itr->value.IsString()) {
            SizeType len = itr->value.GetStringLength();
            if (len == 0)
                SchemaError(kSchemaErrorRefInvalid, source);
            else {
                // First resolve $ref against the in-scope id
                UriType scopeId = UriType(id, allocator_);
                UriType ref = UriType(itr->value, allocator_).Resolve(scopeId, allocator_);
                RAPIDJSON_SCHEMA_PRINT(SchemaIds, id.GetString(), itr->value.GetString(), ref.GetString());
                // See if the resolved $ref minus the fragment matches a resolved id in this document
                // Search from the root. Returns the subschema in the document and its absolute JSON pointer.
                PointerType basePointer = PointerType();
                const ValueType *base = FindId(document, ref, basePointer, docId_, false);
                if (!base) {
                    // Remote reference - call the remote document provider
                    if (!remoteProvider_)
                        SchemaError(kSchemaErrorRefNoRemoteProvider, source);
                    else {
                        if (const GenericSchemaDocument* remoteDocument = remoteProvider_->GetRemoteDocument(ref, spec_)) {
                            const Ch* s = ref.GetFragString();
                            len = ref.GetFragStringLength();
                            if (len <= 1 || s[1] == '/') {
                                // JSON pointer fragment, absolute in the remote schema
                                const PointerType pointer(s, len, allocator_);
                                if (!pointer.IsValid())
                                    SchemaErrorPointer(kSchemaErrorRefPointerInvalid, source, s, len, pointer);
                                else {
                                    // Get the subschema
                                    if (const SchemaType *sc = remoteDocument->GetSchema(pointer)) {
                                        if (schema)
                                            *schema = sc;
                                        AddSchemaRefs(const_cast<SchemaType *>(sc));
                                        return true;
                                    } else
                                        SchemaErrorValue(kSchemaErrorRefUnknown, source, ref.GetString(), ref.GetStringLength());
                                }
                            } else
                                // Plain name fragment, not allowed in remote schema
                                SchemaErrorValue(kSchemaErrorRefPlainName, source, s, len);
                        } else
                          SchemaErrorValue(kSchemaErrorRefNoRemoteSchema, source, ref.GetString(), ref.GetStringLength());
                    }
                }
                else { // Local reference
                    const Ch* s = ref.GetFragString();
                    len = ref.GetFragStringLength();
                    if (len <= 1 || s[1] == '/') {
                        // JSON pointer fragment, relative to the resolved URI
                        const PointerType relPointer(s, len, allocator_);
                        if (!relPointer.IsValid())
                            SchemaErrorPointer(kSchemaErrorRefPointerInvalid, source, s, len, relPointer);
                        else {
                            // Get the subschema
                            if (const ValueType *pv = relPointer.Get(*base)) {
                                // Now get the absolute JSON pointer by adding relative to base
                                PointerType pointer(basePointer, allocator_);
                                for (SizeType i = 0; i < relPointer.GetTokenCount(); i++)
                                    pointer = pointer.Append(relPointer.GetTokens()[i], allocator_);
                                if (IsCyclicRef(pointer))
                                    SchemaErrorValue(kSchemaErrorRefCyclical, source, ref.GetString(), ref.GetStringLength());
                                else {
                                    // Call CreateSchema recursively, but first compute the in-scope id for the $ref target as we have jumped there
                                    // TODO: cache pointer <-> id mapping
                                    size_t unresolvedTokenIndex;
                                    scopeId = pointer.GetUri(document, docId_, &unresolvedTokenIndex, allocator_);
                                    CreateSchema(schema, pointer, *pv, document, scopeId);
                                    return true;
                                }
                            } else
                                SchemaErrorValue(kSchemaErrorRefUnknown, source, ref.GetString(), ref.GetStringLength());
                        }
                    } else {
                        // Plain name fragment, relative to the resolved URI
                        // Not supported in open api 2.0 and 3.0
                        PointerType pointer(allocator_);
                        if (spec_.oapi == kVersion20 || spec_.oapi == kVersion30)
                            SchemaErrorValue(kSchemaErrorRefPlainName, source, s, len);
                        // See if the fragment matches an id in this document.
                        // Search from the base we just established. Returns the subschema in the document and its absolute JSON pointer.
                        else if (const ValueType *pv = FindId(*base, ref, pointer, UriType(ref.GetBaseString(), ref.GetBaseStringLength(), allocator_), true, basePointer)) {
                            if (IsCyclicRef(pointer))
                                SchemaErrorValue(kSchemaErrorRefCyclical, source, ref.GetString(), ref.GetStringLength());
                            else {
                                // Call CreateSchema recursively, but first compute the in-scope id for the $ref target as we have jumped there
                                // TODO: cache pointer <-> id mapping
                                size_t unresolvedTokenIndex;
                                scopeId = pointer.GetUri(document, docId_, &unresolvedTokenIndex, allocator_);
                                CreateSchema(schema, pointer, *pv, document, scopeId);
                                return true;
                            }
                        } else
                            SchemaErrorValue(kSchemaErrorRefUnknown, source, ref.GetString(), ref.GetStringLength());
                    }
                }
            }
        }
        // Invalid/Unknown $ref
        if (schema)
            *schema = typeless_;
        AddSchemaRefs(typeless_);
        return true;
    }
References rapidjson::GenericUri< ValueType, Allocator >::GetBaseString(), rapidjson::GenericUri< ValueType, Allocator >::GetBaseStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetFragString(), rapidjson::GenericUri< ValueType, Allocator >::GetFragStringLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::GenericUri< ValueType, Allocator >::GetString(), GetString(), rapidjson::GenericUri< ValueType, Allocator >::GetStringLength(), rapidjson::kSchemaErrorRefCyclical, rapidjson::kSchemaErrorRefInvalid, rapidjson::kSchemaErrorRefNoRemoteProvider, rapidjson::kSchemaErrorRefNoRemoteSchema, rapidjson::kSchemaErrorRefPlainName, rapidjson::kSchemaErrorRefPointerInvalid, rapidjson::kSchemaErrorRefUnknown, rapidjson::kVersion20, rapidjson::kVersion30, Method, rapidjson::pointer, RAPIDJSON_SCHEMA_PRINT, rapidjson::GenericUri< ValueType, Allocator >::Resolve(), and rapidjson::source.
IsCyclicRef()
template<typename ValueT , typename Allocator = CrtAllocator> bool rapidjson::GenericSchemaDocument< ValueT, Allocator >::IsCyclicRef (const PointerType & pointer) const inline private
Definition at line 2372 of file schema.h.
{
        for (const SchemaRefPtr* ref = schemaRef_.template Bottom<SchemaRefPtr>(); ref != schemaRef_.template End<SchemaRefPtr>(); ++ref)
            if (pointer == **ref)
                return true;
        return false;
    }
References rapidjson::pointer.
IsSupportedSpecification()
template<typename ValueT , typename Allocator = CrtAllocator> bool rapidjson::GenericSchemaDocument< ValueT, Allocator >::IsSupportedSpecification () const inline
Definition at line 1937 of file schema.h.
{ return spec_.IsSupported(); }
operator=()
template<typename ValueT , typename Allocator = CrtAllocator> GenericSchemaDocument & rapidjson::GenericSchemaDocument< ValueT, Allocator >::operator= (const GenericSchemaDocument< ValueT, Allocator > &) private
Prohibit assignment.
SchemaError()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::SchemaError (const SchemaErrorCode code, const PointerType & location) inline
Default error method.
Definition at line 1980 of file schema.h.
{
      currentError_ = GValue(kObjectType);
      AddCurrentError(code, location);
    }
References rapidjson::kObjectType.
SchemaErrorPointer()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::SchemaErrorPointer (const SchemaErrorCode code, const PointerType & location, const Ch * value, SizeType length, const PointerType & pointer) inline
Method for error with invalid pointer.
Definition at line 1993 of file schema.h.
{
      currentError_ = GValue(kObjectType);
      currentError_.AddMember(GetValueString(), GValue(value, length, *allocator_).Move(), *allocator_);
      currentError_.AddMember(GetOffsetString(), static_cast<SizeType>(pointer.GetParseErrorOffset() / sizeof(Ch)), *allocator_);
      AddCurrentError(code, location);
    }
References rapidjson::kObjectType, rapidjson::pointer, and rapidjson::value.
SchemaErrorValue()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::SchemaErrorValue (const SchemaErrorCode code, const PointerType & location, const Ch * value, SizeType length) inline
Method for error with single string value insert.
Definition at line 1986 of file schema.h.
{
      currentError_ = GValue(kObjectType);
      currentError_.AddMember(GetValueString(), GValue(value, length, *allocator_).Move(), *allocator_);
      AddCurrentError(code, location);
    }
References rapidjson::kObjectType, and rapidjson::value.
SetSchemaSpecification()
template<typename ValueT , typename Allocator = CrtAllocator> void rapidjson::GenericSchemaDocument< ValueT, Allocator >::SetSchemaSpecification (const ValueType & document) inline private
Definition at line 2142 of file schema.h.
{
        // Look for '$schema', 'swagger' or 'openapi' keyword at document root
        SchemaDraft docDraft = GetSchemaDraft(document);
        OpenApiVersion docOapi = GetOpenApiVersion(document);
        // Error if both in document
        if (docDraft != kDraftNone && docOapi != kVersionNone)
          SchemaError(kSchemaErrorSpecIllegal, PointerType());
        // Use document draft or open api version if present or use spec from constructor
        if (docDraft != kDraftNone)
            spec_ = Specification(docDraft);
        else if (docOapi != kVersionNone)
            spec_ = Specification(docOapi);
        // Error if draft or version unknown
        if (spec_.draft == kDraftUnknown || spec_.oapi == kVersionUnknown)
          SchemaError(kSchemaErrorSpecUnknown, PointerType());
        else if (!spec_.IsSupported())
            SchemaError(kSchemaErrorSpecUnsupported, PointerType());
    }
References rapidjson::kDraftNone, rapidjson::kDraftUnknown, rapidjson::kSchemaErrorSpecIllegal, rapidjson::kSchemaErrorSpecUnknown, rapidjson::kSchemaErrorSpecUnsupported, rapidjson::kVersionNone, and rapidjson::kVersionUnknown.
Friends And Related Symbol Documentation
GenericSchemaValidator
template<typename ValueT , typename Allocator = CrtAllocator> template<typename , typename , typename > friend class GenericSchemaValidator friend
Definition at line 1828 of file schema.h.
internal::Schema< GenericSchemaDocument >
template<typename ValueT , typename Allocator = CrtAllocator> friend class internal::Schema< GenericSchemaDocument > friend
Definition at line 1825 of file schema.h.
Member Data Documentation
allocator_
template<typename ValueT , typename Allocator = CrtAllocator> Allocator* rapidjson::GenericSchemaDocument< ValueT, Allocator >::allocator_ private
Definition at line 2399 of file schema.h.
currentError_
template<typename ValueT , typename Allocator = CrtAllocator> GValue rapidjson::GenericSchemaDocument< ValueT, Allocator >::currentError_ private
Definition at line 2409 of file schema.h.
docId_
template<typename ValueT , typename Allocator = CrtAllocator> UriType rapidjson::GenericSchemaDocument< ValueT, Allocator >::docId_ private
Definition at line 2406 of file schema.h.
error_
template<typename ValueT , typename Allocator = CrtAllocator> GValue rapidjson::GenericSchemaDocument< ValueT, Allocator >::error_ private
Definition at line 2408 of file schema.h.
kInitialSchemaMapSize
template<typename ValueT , typename Allocator = CrtAllocator> const size_t rapidjson::GenericSchemaDocument< ValueT, Allocator >::kInitialSchemaMapSize = 64 static private
Definition at line 2395 of file schema.h.
kInitialSchemaRefSize
template<typename ValueT , typename Allocator = CrtAllocator> const size_t rapidjson::GenericSchemaDocument< ValueT, Allocator >::kInitialSchemaRefSize = 64 static private
Definition at line 2396 of file schema.h.
ownAllocator_
template<typename ValueT , typename Allocator = CrtAllocator> Allocator* rapidjson::GenericSchemaDocument< ValueT, Allocator >::ownAllocator_ private
Definition at line 2400 of file schema.h.
remoteProvider_
template<typename ValueT , typename Allocator = CrtAllocator> IRemoteSchemaDocumentProviderType* rapidjson::GenericSchemaDocument< ValueT, Allocator >::remoteProvider_ private
Definition at line 2398 of file schema.h.
root_
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType* rapidjson::GenericSchemaDocument< ValueT, Allocator >::root_ private
Root schema.
Definition at line 2401 of file schema.h.
schemaMap_
template<typename ValueT , typename Allocator = CrtAllocator> internal::Stack<Allocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::schemaMap_ private
Definition at line 2403 of file schema.h.
schemaRef_
template<typename ValueT , typename Allocator = CrtAllocator> internal::Stack<Allocator> rapidjson::GenericSchemaDocument< ValueT, Allocator >::schemaRef_ private
Definition at line 2404 of file schema.h.
spec_
template<typename ValueT , typename Allocator = CrtAllocator> Specification rapidjson::GenericSchemaDocument< ValueT, Allocator >::spec_ private
Definition at line 2407 of file schema.h.
typeless_
template<typename ValueT , typename Allocator = CrtAllocator> SchemaType* rapidjson::GenericSchemaDocument< ValueT, Allocator >::typeless_ private
Definition at line 2402 of file schema.h.
uri_
template<typename ValueT , typename Allocator = CrtAllocator> GValue rapidjson::GenericSchemaDocument< ValueT, Allocator >::uri_ private
Definition at line 2405 of file schema.h.
The documentation for this class was generated from the following files:
rapidjson/include/rapidjson/fwd.h
rapidjson/include/rapidjson/schema.h