wiNpoS: gtest_json_output_unittest.GTestJsonOutputUnitTest Class Reference
gtest_json_output_unittest.GTestJsonOutputUnitTest Class Reference
Public Member Functions
testNonEmptyJsonOutput (self)
testEmptyJsonOutput (self)
testTimestampValue (self)
testDefaultOutputFile (self)
testSuppressedJsonOutput (self)
testFilteredTestJsonOutput (self)
Protected Member Functions
_GetJsonOutput (self, gtest_prog_name, extra_args, expected_exit_code)
_TestJsonOutput (self, gtest_prog_name, expected, expected_exit_code, extra_args=None)
Detailed Description
Unit test for Google Test's JSON output functionality.
Definition at line 443 of file gtest_json_output_unittest.py.
Member Function Documentation
_GetJsonOutput()
gtest_json_output_unittest.GTestJsonOutputUnitTest._GetJsonOutput (self, gtest_prog_name, extra_args, expected_exit_code) protected
Returns the JSON output generated by running the program gtest_prog_name.
Furthermore, the program's exit code must be expected_exit_code.
Args:
  gtest_prog_name: Google Test binary name.
  extra_args: extra arguments to binary invocation.
  expected_exit_code: program's exit code.
Definition at line 556 of file gtest_json_output_unittest.py.
  def _GetJsonOutput(self, gtest_prog_name, extra_args, expected_exit_code):
    """Returns the JSON output generated by running the program gtest_prog_name.
    Furthermore, the program's exit code must be expected_exit_code.
    Args:
      gtest_prog_name: Google Test binary name.
      extra_args: extra arguments to binary invocation.
      expected_exit_code: program's exit code.
    """
    json_path = os.path.join(gtest_test_utils.GetTempDir(),
                             gtest_prog_name + 'out.json')
    gtest_prog_path = gtest_test_utils.GetTestExecutablePath(gtest_prog_name)
    command = (
        [gtest_prog_path, '%s=json:%s' % (GTEST_OUTPUT_FLAG, json_path)] +
        extra_args
    )
    p = gtest_test_utils.Subprocess(command)
    if p.terminated_by_signal:
      self.assert_(False,
                   '%s was killed by signal %d' % (gtest_prog_name, p.signal))
    else:
      self.assert_(p.exited)
      self.assertEquals(expected_exit_code, p.exit_code,
                        "'%s' exited with code %s, which doesn't match "
                        'the expected exit code %s.'
                        % (command, p.exit_code, expected_exit_code))
    with open(json_path) as f:
      actual = json.load(f)
    return actual
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
_TestJsonOutput()
gtest_json_output_unittest.GTestJsonOutputUnitTest._TestJsonOutput (self, gtest_prog_name, expected, expected_exit_code, extra_args = None) protected
Checks the JSON output generated by the Google Test binary.
Asserts that the JSON document generated by running the program
gtest_prog_name matches expected_json, a string containing another
JSON document.  Furthermore, the program's exit code must be
expected_exit_code.
Args:
  gtest_prog_name: Google Test binary name.
  expected: expected output.
  expected_exit_code: program's exit code.
  extra_args: extra arguments to binary invocation.
Definition at line 588 of file gtest_json_output_unittest.py.
                      expected_exit_code, extra_args=None):
    """Checks the JSON output generated by the Google Test binary.
    Asserts that the JSON document generated by running the program
    gtest_prog_name matches expected_json, a string containing another
    JSON document.  Furthermore, the program's exit code must be
    expected_exit_code.
    Args:
      gtest_prog_name: Google Test binary name.
      expected: expected output.
      expected_exit_code: program's exit code.
      extra_args: extra arguments to binary invocation.
    """
    actual = self._GetJsonOutput(gtest_prog_name, extra_args or [],
                                 expected_exit_code)
    self.assertEqual(expected, gtest_json_test_utils.normalize(actual))
References gtest_json_output_unittest.GTestJsonOutputUnitTest._GetJsonOutput(), gtest_test_utils.Main(), and gtest_json_test_utils.normalize().
testDefaultOutputFile()
gtest_json_output_unittest.GTestJsonOutputUnitTest.testDefaultOutputFile (self)
Verifies the default output file name.
Confirms that Google Test produces an JSON output file with the expected
default name if no name is explicitly specified.
Definition at line 492 of file gtest_json_output_unittest.py.
  def testDefaultOutputFile(self):
    """Verifies the default output file name.
    Confirms that Google Test produces an JSON output file with the expected
    default name if no name is explicitly specified.
    """
    output_file = os.path.join(gtest_test_utils.GetTempDir(),
                               GTEST_DEFAULT_OUTPUT_FILE)
    gtest_prog_path = gtest_test_utils.GetTestExecutablePath(
        'gtest_no_test_unittest')
    try:
      os.remove(output_file)
    except OSError:
      e = sys.exc_info()[1]
      if e.errno != errno.ENOENT:
        raise
    p = gtest_test_utils.Subprocess(
        [gtest_prog_path, '%s=json' % GTEST_OUTPUT_FLAG],
        working_dir=gtest_test_utils.GetTempDir())
    self.assert_(p.exited)
    self.assertEquals(0, p.exit_code)
    self.assert_(os.path.isfile(output_file))
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
testEmptyJsonOutput()
gtest_json_output_unittest.GTestJsonOutputUnitTest.testEmptyJsonOutput (self)
Verifies JSON output for a Google Test binary without actual tests.
Runs a test program that generates an empty JSON output, and
tests that the JSON output is expected.
Definition at line 459 of file gtest_json_output_unittest.py.
  def testEmptyJsonOutput(self):
    """Verifies JSON output for a Google Test binary without actual tests.
    Runs a test program that generates an empty JSON output, and
    tests that the JSON output is expected.
    """
    self._TestJsonOutput('gtest_no_test_unittest', EXPECTED_EMPTY, 0)
References gtest_json_output_unittest.GTestJsonOutputUnitTest._TestJsonOutput().
testFilteredTestJsonOutput()
gtest_json_output_unittest.GTestJsonOutputUnitTest.testFilteredTestJsonOutput (self)
Verifies JSON output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the JSON output.
Definition at line 546 of file gtest_json_output_unittest.py.
  def testFilteredTestJsonOutput(self):
    """Verifies JSON output when a filter is applied.
    Runs a test program that executes only some tests and verifies that
    non-selected tests do not show up in the JSON output.
    """
    self._TestJsonOutput(GTEST_PROGRAM_NAME, EXPECTED_FILTERED, 0,
                         extra_args=['%s=SuccessfulTest.*' % GTEST_FILTER_FLAG])
References gtest_json_output_unittest.GTestJsonOutputUnitTest._TestJsonOutput().
testNonEmptyJsonOutput()
gtest_json_output_unittest.GTestJsonOutputUnitTest.testNonEmptyJsonOutput (self)
Verifies JSON output for a Google Test binary with non-empty output.
Runs a test program that generates a non-empty JSON output, and
tests that the JSON output is expected.
Definition at line 451 of file gtest_json_output_unittest.py.
    def testNonEmptyJsonOutput(self):
      """Verifies JSON output for a Google Test binary with non-empty output.
      Runs a test program that generates a non-empty JSON output, and
      tests that the JSON output is expected.
      """
      self._TestJsonOutput(GTEST_PROGRAM_NAME, EXPECTED_NON_EMPTY, 1)
References gtest_json_output_unittest.GTestJsonOutputUnitTest._TestJsonOutput().
testSuppressedJsonOutput()
gtest_json_output_unittest.GTestJsonOutputUnitTest.testSuppressedJsonOutput (self)
Verifies that no JSON output is generated.
Tests that no JSON file is generated if the default JSON listener is
shut down before RUN_ALL_TESTS is invoked.
Definition at line 516 of file gtest_json_output_unittest.py.
  def testSuppressedJsonOutput(self):
    """Verifies that no JSON output is generated.
    Tests that no JSON file is generated if the default JSON listener is
    shut down before RUN_ALL_TESTS is invoked.
    """
    json_path = os.path.join(gtest_test_utils.GetTempDir(),
                             GTEST_PROGRAM_NAME + 'out.json')
    if os.path.isfile(json_path):
      os.remove(json_path)
    command = [GTEST_PROGRAM_PATH,
               '%s=json:%s' % (GTEST_OUTPUT_FLAG, json_path),
               '--shut_down_xml']
    p = gtest_test_utils.Subprocess(command)
    if p.terminated_by_signal:
      # p.signal is available only if p.terminated_by_signal is True.
      self.assertFalse(
          p.terminated_by_signal,
          '%s was killed by signal %d' % (GTEST_PROGRAM_NAME, p.signal))
    else:
      self.assert_(p.exited)
      self.assertEquals(1, p.exit_code,
                        "'%s' exited with code %s, which doesn't match "
                        'the expected exit code %s.'
                        % (command, p.exit_code, 1))
    self.assert_(not os.path.isfile(json_path))
References gtest_test_utils.GetTempDir().
testTimestampValue()
gtest_json_output_unittest.GTestJsonOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the JSON output is valid.
Runs a test program that generates an empty JSON output, and checks if
the timestamp attribute in the testsuites tag is valid.
Definition at line 468 of file gtest_json_output_unittest.py.
  def testTimestampValue(self):
    """Checks whether the timestamp attribute in the JSON output is valid.
    Runs a test program that generates an empty JSON output, and checks if
    the timestamp attribute in the testsuites tag is valid.
    """
    actual = self._GetJsonOutput('gtest_no_test_unittest', [], 0)
    date_time_str = actual['timestamp']
    # datetime.strptime() is only available in Python 2.5+ so we have to
    # parse the expected datetime manually.
    match = re.match(r'(\d+)-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)', date_time_str)
    self.assertTrue(
        re.match,
        'JSON datettime string %s has incorrect format' % date_time_str)
    date_time_from_json = datetime.datetime(
        year=int(match.group(1)), month=int(match.group(2)),
        day=int(match.group(3)), hour=int(match.group(4)),
        minute=int(match.group(5)), second=int(match.group(6)))
    time_delta = abs(datetime.datetime.now() - date_time_from_json)
    # timestamp value should be near the current local time
    self.assertTrue(time_delta < datetime.timedelta(seconds=600),
                    'time_delta is %s' % time_delta)
References gtest_json_output_unittest.GTestJsonOutputUnitTest._GetJsonOutput().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest_json_output_unittest.py