wiNpoS: rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator > Class Template Reference
rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator > Class Template Reference
A helper class for parsing with validation.
#include <schema.h>
Public Types
typedef SchemaDocumentType::PointerType PointerType
typedef InputStream::Ch Ch
typedef GenericValue< SourceEncoding, StackAllocator > ValueType
Public Member Functions
SchemaValidatingReader (InputStream &is, const SchemaDocumentType &sd)
Constructor.
template<typename Handler >
bool operator() (Handler &handler)
const ParseResult & GetParseResult () const
bool IsValid () const
const PointerType & GetInvalidSchemaPointer () const
const Ch * GetInvalidSchemaKeyword () const
const PointerType & GetInvalidDocumentPointer () const
const ValueType & GetError () const
ValidateErrorCode GetInvalidSchemaCode () const
Private Attributes
InputStream & is_
const SchemaDocumentType & sd_
ParseResult parseResult_
PointerType invalidSchemaPointer_
const Ch * invalidSchemaKeyword_
PointerType invalidDocumentPointer_
ValidateErrorCode invalidSchemaCode_
StackAllocator allocator_
ValueType error_
bool isValid_
Detailed Description
template<unsigned parseFlags, typename InputStream, typename SourceEncoding, typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
class rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >
A helper class for parsing with validation.
This helper class is a functor, designed as a parameter of GenericDocument::Populate().
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept.
SourceEncoding Encoding of the input stream.
SchemaDocumentType Type of schema document.
StackAllocator Allocator type for stack.
Definition at line 3198 of file schema.h.
Member Typedef Documentation
Ch
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> typedef InputStream::Ch rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::Ch
Definition at line 3201 of file schema.h.
PointerType
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> typedef SchemaDocumentType::PointerType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::PointerType
Definition at line 3200 of file schema.h.
ValueType
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> typedef GenericValue<SourceEncoding, StackAllocator> rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::ValueType
Definition at line 3202 of file schema.h.
Constructor & Destructor Documentation
SchemaValidatingReader()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::SchemaValidatingReader (InputStream & is, const SchemaDocumentType & sd) inline
Constructor.
Parameters
is Input stream.
sd Schema document.
Definition at line 3209 of file schema.h.
: is_(is), sd_(sd), invalidSchemaKeyword_(), invalidSchemaCode_(kValidateErrorNone), error_(kObjectType), isValid_(true) {}
References rapidjson::kObjectType, and rapidjson::kValidateErrorNone.
Member Function Documentation
GetError()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const ValueType & rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetError () const inline
Definition at line 3240 of file schema.h.
{ return error_; }
GetInvalidDocumentPointer()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const PointerType & rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidDocumentPointer () const inline
Definition at line 3239 of file schema.h.
{ return invalidDocumentPointer_; }
GetInvalidSchemaCode()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> ValidateErrorCode rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaCode () const inline
Definition at line 3241 of file schema.h.
{ return invalidSchemaCode_; }
GetInvalidSchemaKeyword()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const Ch * rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaKeyword () const inline
Definition at line 3238 of file schema.h.
{ return invalidSchemaKeyword_; }
GetInvalidSchemaPointer()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const PointerType & rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaPointer () const inline
Definition at line 3237 of file schema.h.
{ return invalidSchemaPointer_; }
GetParseResult()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const ParseResult & rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetParseResult () const inline
Definition at line 3235 of file schema.h.
{ return parseResult_; }
IsValid()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> bool rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::IsValid () const inline
Definition at line 3236 of file schema.h.
{ return isValid_; }
operator()()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> template<typename Handler > bool rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator() (Handler & handler) inline
Definition at line 3212 of file schema.h.
{
        GenericReader<SourceEncoding, typename SchemaDocumentType::EncodingType, StackAllocator> reader;
        GenericSchemaValidator<SchemaDocumentType, Handler> validator(sd_, handler);
        parseResult_ = reader.template Parse<parseFlags>(is_, validator);
        isValid_ = validator.IsValid();
        if (isValid_) {
            invalidSchemaPointer_ = PointerType();
            invalidSchemaKeyword_ = 0;
            invalidDocumentPointer_ = PointerType();
            error_.SetObject();
        }
        else {
            invalidSchemaPointer_ = validator.GetInvalidSchemaPointer();
            invalidSchemaKeyword_ = validator.GetInvalidSchemaKeyword();
            invalidSchemaCode_ = validator.GetInvalidSchemaCode();
            invalidDocumentPointer_ = validator.GetInvalidDocumentPointer();
            error_.CopyFrom(validator.GetError(), allocator_);
        }
        return parseResult_;
    }
References rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaCode(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer(), and rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid().
Member Data Documentation
allocator_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> StackAllocator rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::allocator_ private
Definition at line 3252 of file schema.h.
error_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> ValueType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::error_ private
Definition at line 3253 of file schema.h.
invalidDocumentPointer_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> PointerType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidDocumentPointer_ private
Definition at line 3250 of file schema.h.
invalidSchemaCode_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> ValidateErrorCode rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidSchemaCode_ private
Definition at line 3251 of file schema.h.
invalidSchemaKeyword_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const Ch* rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidSchemaKeyword_ private
Definition at line 3249 of file schema.h.
invalidSchemaPointer_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> PointerType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidSchemaPointer_ private
Definition at line 3248 of file schema.h.
is_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> InputStream& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::is_ private
Definition at line 3244 of file schema.h.
isValid_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> bool rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::isValid_ private
Definition at line 3254 of file schema.h.
parseResult_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> ParseResult rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::parseResult_ private
Definition at line 3247 of file schema.h.
sd_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const SchemaDocumentType& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::sd_ private
Definition at line 3245 of file schema.h.
The documentation for this class was generated from the following file:
rapidjson/include/rapidjson/schema.h