wiNpoS: testing::internal::UnorderedElementsAreMatcherImpl< Container > Class Template Reference
testing::internal::UnorderedElementsAreMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::const_iterator StlContainerConstIterator
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InputIter >
UnorderedElementsAreMatcherImpl (UnorderedMatcherRequire::Flags matcher_flags, InputIter first, InputIter last)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
template<typename ElementIter >
MatchMatrix AnalyzeElements (ElementIter elem_first, ElementIter elem_last, ::std::vector< std::string > *element_printouts, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImpl)
Private Attributes
::std::vector< Matcher< const Element & > > matchers_
Additional Inherited Members
Protected Types inherited from testing::internal::UnorderedElementsAreMatcherImplBase
typedef ::std::vector< const MatcherDescriberInterface * > MatcherDescriberVec
Protected Member Functions inherited from testing::internal::UnorderedElementsAreMatcherImplBase
UnorderedElementsAreMatcherImplBase (UnorderedMatcherRequire::Flags matcher_flags)
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyMatchMatrix (const ::std::vector< std::string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
bool FindPairing (const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
UnorderedMatcherRequire::Flags match_flags () const
Static Protected Member Functions inherited from testing::internal::UnorderedElementsAreMatcherImplBase
static Message Elements (size_t n)
Detailed Description
template<typename Container>
class testing::internal::UnorderedElementsAreMatcherImpl< Container >
Definition at line 3712 of file gmock-matchers.h.
Member Typedef Documentation
Element
template<typename Container > typedef StlContainer::value_type testing::internal::UnorderedElementsAreMatcherImpl< Container >::Element
Definition at line 3721 of file gmock-matchers.h.
StlContainer
template<typename Container > typedef View::type testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainer
Definition at line 3718 of file gmock-matchers.h.
StlContainerConstIterator
template<typename Container > typedef StlContainer::const_iterator testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerConstIterator
Definition at line 3720 of file gmock-matchers.h.
StlContainerReference
template<typename Container > typedef View::const_reference testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerReference
Definition at line 3719 of file gmock-matchers.h.
View
template<typename Container > typedef internal::StlContainerView<RawContainer> testing::internal::UnorderedElementsAreMatcherImpl< Container >::View
Definition at line 3717 of file gmock-matchers.h.
Constructor & Destructor Documentation
UnorderedElementsAreMatcherImpl()
template<typename Container > template<typename InputIter > testing::internal::UnorderedElementsAreMatcherImpl< Container >::UnorderedElementsAreMatcherImpl (UnorderedMatcherRequire::Flags matcher_flags, InputIter first, InputIter last) inline
Definition at line 3724 of file gmock-matchers.h.
      : UnorderedElementsAreMatcherImplBase(matcher_flags) {
    for (; first != last; ++first) {
      matchers_.push_back(MatcherCast<const Element&>(*first));
      matcher_describers().push_back(matchers_.back().GetDescriber());
    }
  }
References testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers(), and testing::internal::UnorderedElementsAreMatcherImpl< Container >::matchers_.
Member Function Documentation
AnalyzeElements()
template<typename Container > template<typename ElementIter > MatchMatrix testing::internal::UnorderedElementsAreMatcherImpl< Container >::AnalyzeElements (ElementIter elem_first, ElementIter elem_last, ::std::vector< std::string > * element_printouts, MatchResultListener * listener) const inline private
Definition at line 3774 of file gmock-matchers.h.
{
    element_printouts->clear();
    ::std::vector<char> did_match;
    size_t num_elements = 0;
    for (; elem_first != elem_last; ++num_elements, ++elem_first) {
      if (listener->IsInterested()) {
        element_printouts->push_back(PrintToString(*elem_first));
      }
      for (size_t irhs = 0; irhs != matchers_.size(); ++irhs) {
        did_match.push_back(Matches(matchers_[irhs])(*elem_first));
      }
    }
    MatchMatrix matrix(num_elements, matchers_.size());
    ::std::vector<char>::const_iterator did_match_iter = did_match.begin();
    for (size_t ilhs = 0; ilhs != num_elements; ++ilhs) {
      for (size_t irhs = 0; irhs != matchers_.size(); ++irhs) {
        matrix.SetEdge(ilhs, irhs, *did_match_iter++ != 0);
      }
    }
    return matrix;
  }
References testing::MatchResultListener::IsInterested(), testing::internal::UnorderedElementsAreMatcherImpl< Container >::matchers_, testing::Matches(), testing::PrintToString(), and testing::internal::MatchMatrix::SetEdge().
DescribeNegationTo()
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3739 of file gmock-matchers.h.
{
    return UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl(os);
  }
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl().
DescribeTo()
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3734 of file gmock-matchers.h.
{
    return UnorderedElementsAreMatcherImplBase::DescribeToImpl(os);
  }
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl().
GTEST_DISALLOW_ASSIGN_()
template<typename Container > testing::internal::UnorderedElementsAreMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (UnorderedElementsAreMatcherImpl< Container >) private
GTEST_REMOVE_REFERENCE_AND_CONST_()
template<typename Container > typedef testing::internal::UnorderedElementsAreMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
MatchAndExplain()
template<typename Container > virtual bool testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 3743 of file gmock-matchers.h.
{
    StlContainerReference stl_container = View::ConstReference(container);
    ::std::vector<std::string> element_printouts;
    MatchMatrix matrix =
        AnalyzeElements(stl_container.begin(), stl_container.end(),
                        &element_printouts, listener);
    if (matrix.LhsSize() == 0 && matrix.RhsSize() == 0) {
      return true;
    }
    if (match_flags() == UnorderedMatcherRequire::ExactMatch) {
      if (matrix.LhsSize() != matrix.RhsSize()) {
        // The element count doesn't match.  If the container is empty,
        // there's no need to explain anything as Google Mock already
        // prints the empty container. Otherwise we just need to show
        // how many elements there actually are.
        if (matrix.LhsSize() != 0 && listener->IsInterested()) {
          *listener << "which has " << Elements(matrix.LhsSize());
        }
        return false;
      }
    }
    return VerifyMatchMatrix(element_printouts, matrix, listener) &&
           FindPairing(matrix, listener);
  }
References testing::internal::UnorderedElementsAreMatcherImpl< Container >::AnalyzeElements(), testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::UnorderedElementsAreMatcherImplBase::Elements(), testing::internal::UnorderedMatcherRequire::ExactMatch, testing::internal::UnorderedElementsAreMatcherImplBase::FindPairing(), testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::LhsSize(), testing::internal::UnorderedElementsAreMatcherImplBase::match_flags(), testing::internal::MatchMatrix::RhsSize(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyMatchMatrix().
Member Data Documentation
matchers_
template<typename Container > ::std::vector<Matcher<const Element&> > testing::internal::UnorderedElementsAreMatcherImpl< Container >::matchers_ private
Definition at line 3799 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h