wiNpoS: testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional > Class Template Reference
testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef OptionalView::value_type ValueType
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Optional) OptionalView
Impl (const ValueMatcher &value_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Optional optional, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< ValueType > value_matcher_
Detailed Description
template<typename ValueMatcher>
template<typename Optional>
class testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >
Definition at line 4012 of file gmock-matchers.h.
Member Typedef Documentation
ValueType
template<typename ValueMatcher > template<typename Optional > typedef OptionalView::value_type testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::ValueType
Definition at line 4015 of file gmock-matchers.h.
Constructor & Destructor Documentation
Impl()
template<typename ValueMatcher > template<typename Optional > testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::Impl (const ValueMatcher & value_matcher) inline explicit
Definition at line 4016 of file gmock-matchers.h.
        : value_matcher_(MatcherCast<ValueType>(value_matcher)) {}
References testing::MatcherCast().
Member Function Documentation
DescribeNegationTo()
template<typename ValueMatcher > template<typename Optional > virtual void testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 4024 of file gmock-matchers.h.
{
      *os << "value ";
      value_matcher_.DescribeNegationTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), and testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::value_matcher_.
DescribeTo()
template<typename ValueMatcher > template<typename Optional > virtual void testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 4019 of file gmock-matchers.h.
{
      *os << "value ";
      value_matcher_.DescribeTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::value_matcher_.
GTEST_DISALLOW_ASSIGN_()
template<typename ValueMatcher > template<typename Optional > testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::GTEST_DISALLOW_ASSIGN_ (Impl< Optional >) private
GTEST_REMOVE_REFERENCE_AND_CONST_()
template<typename ValueMatcher > template<typename Optional > typedef testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Optional)
MatchAndExplain()
template<typename ValueMatcher > template<typename Optional > virtual bool testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::MatchAndExplain (Optional optional, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Optional >.
Definition at line 4029 of file gmock-matchers.h.
{
      if (!optional) {
        *listener << "which is not engaged";
        return false;
      }
      const ValueType& value = *optional;
      StringMatchResultListener value_listener;
      const bool match = value_matcher_.MatchAndExplain(value, &value_listener);
      *listener << "whose value " << PrintToString(value)
                << (match ? " matches" : " doesn't match");
      PrintIfNotEmpty(value_listener.str(), listener->stream());
      return match;
    }
References testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::value_matcher_.
Member Data Documentation
value_matcher_
template<typename ValueMatcher > template<typename Optional > const Matcher<ValueType> testing::internal::OptionalMatcher< ValueMatcher >::Impl< Optional >::value_matcher_ private
Definition at line 4045 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h