wiNpoS: testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple > Class Template Reference
testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple > Class Template Reference
Public Member Functions
Impl (FloatType max_abs_error, bool nan_eq_nan)
virtual bool MatchAndExplain (Tuple args, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Attributes
FloatType max_abs_error_
const bool nan_eq_nan_
Detailed Description
template<typename FloatType>
template<typename Tuple>
class testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >
Definition at line 2273 of file gmock-matchers.h.
Constructor & Destructor Documentation
Impl()
template<typename FloatType > template<typename Tuple > testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::Impl (FloatType max_abs_error, bool nan_eq_nan) inline
Definition at line 2275 of file gmock-matchers.h.
                                                   :
        max_abs_error_(max_abs_error),
        nan_eq_nan_(nan_eq_nan) {}
Member Function Documentation
DescribeNegationTo()
template<typename FloatType > template<typename Tuple > virtual void testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2295 of file gmock-matchers.h.
{
      *os << "aren't " << GetDesc;
    }
References testing::internal::FloatingEq2Matcher< FloatType >::GetDesc().
DescribeTo()
template<typename FloatType > template<typename Tuple > virtual void testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2292 of file gmock-matchers.h.
{
      *os << "are " << GetDesc;
    }
References testing::internal::FloatingEq2Matcher< FloatType >::GetDesc().
MatchAndExplain()
template<typename FloatType > template<typename Tuple > virtual bool testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::MatchAndExplain (Tuple args, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Tuple >.
Definition at line 2279 of file gmock-matchers.h.
{
      if (max_abs_error_ == -1) {
        FloatingEqMatcher<FloatType> fm(::testing::get<0>(args), nan_eq_nan_);
        return static_cast<Matcher<FloatType> >(fm).MatchAndExplain(
            ::testing::get<1>(args), listener);
      } else {
        FloatingEqMatcher<FloatType> fm(::testing::get<0>(args), nan_eq_nan_,
                                        max_abs_error_);
        return static_cast<Matcher<FloatType> >(fm).MatchAndExplain(
            ::testing::get<1>(args), listener);
      }
    }
References testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::MatchAndExplain(), testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::max_abs_error_, and testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::nan_eq_nan_.
Member Data Documentation
max_abs_error_
template<typename FloatType > template<typename Tuple > FloatType testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::max_abs_error_ private
Definition at line 2300 of file gmock-matchers.h.
nan_eq_nan_
template<typename FloatType > template<typename Tuple > const bool testing::internal::FloatingEq2Matcher< FloatType >::Impl< Tuple >::nan_eq_nan_ private
Definition at line 2301 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h