wiNpoS: rapidjson::GenericUri< ValueType, Allocator > Class Template Reference
rapidjson::GenericUri< ValueType, Allocator > Class Template Reference
#include <uri.h>
Public Types
typedef ValueType::Ch Ch
Public Member Functions
GenericUri (Allocator *allocator=0)
Constructors.
GenericUri (const Ch *uri, SizeType len, Allocator *allocator=0)
GenericUri (const Ch *uri, Allocator *allocator=0)
template<typename T >
GenericUri (const T &uri, Allocator *allocator=0)
GenericUri (const GenericUri &rhs)
Copy constructor.
GenericUri (const GenericUri &rhs, Allocator *allocator)
Copy constructor.
~GenericUri ()
Destructor.
GenericUri & operator= (const GenericUri &rhs)
Assignment operator.
template<typename T >
void Get (T &uri, Allocator &allocator)
Getters.
const Ch * GetString () const
SizeType GetStringLength () const
const Ch * GetBaseString () const
SizeType GetBaseStringLength () const
const Ch * GetSchemeString () const
SizeType GetSchemeStringLength () const
const Ch * GetAuthString () const
SizeType GetAuthStringLength () const
const Ch * GetPathString () const
SizeType GetPathStringLength () const
const Ch * GetQueryString () const
SizeType GetQueryStringLength () const
const Ch * GetFragString () const
SizeType GetFragStringLength () const
bool operator== (const GenericUri &rhs) const
Equality operators.
bool operator!= (const GenericUri &rhs) const
bool Match (const GenericUri &uri, bool full=true) const
GenericUri Resolve (const GenericUri &baseuri, Allocator *allocator=0)
Resolve this URI against another (base) URI in accordance with URI resolution rules.
Allocator & GetAllocator ()
Get the allocator of this GenericUri.
Private Member Functions
std::size_t Allocate (std::size_t len)
void Free ()
void Parse (const Ch *uri, std::size_t len)
void SetBase ()
void SetUri ()
Ch * CopyPart (Ch *to, Ch *from, std::size_t len)
void RemoveDotSegments ()
Private Attributes
Ch * uri_
Ch * base_
Ch * scheme_
Ch * auth_
Ch * path_
Ch * query_
Ch * frag_
Allocator * allocator_
The current allocator. It is either user-supplied or equal to ownAllocator_.
Allocator * ownAllocator_
Allocator owned by this Uri.
Detailed Description
template<typename ValueType, typename Allocator = CrtAllocator>
class rapidjson::GenericUri< ValueType, Allocator >
Definition at line 33 of file uri.h.
Member Typedef Documentation
Ch
template<typename ValueType , typename Allocator = CrtAllocator> typedef ValueType::Ch rapidjson::GenericUri< ValueType, Allocator >::Ch
Definition at line 35 of file uri.h.
Constructor & Destructor Documentation
GenericUri() [1/6]
template<typename ValueType , typename Allocator = CrtAllocator> rapidjson::GenericUri< ValueType, Allocator >::GenericUri (Allocator * allocator = 0) inline
Constructors.
Definition at line 41 of file uri.h.
                                         : uri_(), base_(), scheme_(), auth_(), path_(), query_(), frag_(), allocator_(allocator), ownAllocator_() {
    }
GenericUri() [2/6]
template<typename ValueType , typename Allocator = CrtAllocator> rapidjson::GenericUri< ValueType, Allocator >::GenericUri (const Ch * uri, SizeType len, Allocator * allocator = 0) inline
Definition at line 44 of file uri.h.
                                                                      : uri_(), base_(), scheme_(), auth_(), path_(), query_(), frag_(), allocator_(allocator), ownAllocator_() {
        Parse(uri, len);
    }
GenericUri() [3/6]
template<typename ValueType , typename Allocator = CrtAllocator> rapidjson::GenericUri< ValueType, Allocator >::GenericUri (const Ch * uri, Allocator * allocator = 0) inline
Definition at line 48 of file uri.h.
                                                        : uri_(), base_(), scheme_(), auth_(), path_(), query_(), frag_(), allocator_(allocator), ownAllocator_() {
        Parse(uri, internal::StrLen<Ch>(uri));
    }
GenericUri() [4/6]
template<typename ValueType , typename Allocator = CrtAllocator> template<typename T > rapidjson::GenericUri< ValueType, Allocator >::GenericUri (const T & uri, Allocator * allocator = 0) inline
Definition at line 53 of file uri.h.
                                                                            : uri_(), base_(), scheme_(), auth_(), path_(), query_(), frag_(), allocator_(allocator), ownAllocator_() {
        const Ch* u = uri.template Get<const Ch*>(); // TypeHelper from document.h
        Parse(u, internal::StrLen<Ch>(u));
    }
GenericUri() [5/6]
template<typename ValueType , typename Allocator = CrtAllocator> rapidjson::GenericUri< ValueType, Allocator >::GenericUri (const GenericUri< ValueType, Allocator > & rhs) inline
Copy constructor.
Definition at line 65 of file uri.h.
                                      : uri_(), base_(), scheme_(), auth_(), path_(), query_(), frag_(), allocator_(), ownAllocator_() {
        *this = rhs;
    }
GenericUri() [6/6]
template<typename ValueType , typename Allocator = CrtAllocator> rapidjson::GenericUri< ValueType, Allocator >::GenericUri (const GenericUri< ValueType, Allocator > & rhs, Allocator * allocator) inline
Copy constructor.
Definition at line 70 of file uri.h.
                                                            : uri_(), base_(), scheme_(), auth_(), path_(), query_(), frag_(), allocator_(allocator), ownAllocator_() {
        *this = rhs;
    }
~GenericUri()
template<typename ValueType , typename Allocator = CrtAllocator> rapidjson::GenericUri< ValueType, Allocator >::~GenericUri () inline
Destructor.
Definition at line 75 of file uri.h.
                  {
        Free();
        RAPIDJSON_DELETE(ownAllocator_);
    }
References rapidjson::Free(), and RAPIDJSON_DELETE.
Member Function Documentation
Allocate()
template<typename ValueType , typename Allocator = CrtAllocator> std::size_t rapidjson::GenericUri< ValueType, Allocator >::Allocate (std::size_t len) inline private
Definition at line 234 of file uri.h.
{
        // Create own allocator if user did not supply.
        if (!allocator_)
            ownAllocator_ =  allocator_ = RAPIDJSON_NEW(Allocator)();
        // Allocate one block containing each part of the URI (5) plus base plus full URI, all null terminated.
        // Order: scheme, auth, path, query, frag, base, uri
        // Note need to set, increment, assign in 3 stages to avoid compiler warning bug.
        size_t total = (3 * len + 7) * sizeof(Ch);
        scheme_ = static_cast<Ch*>(allocator_->Malloc(total));
        *scheme_ = '\0';
        auth_ = scheme_;
        auth_++;
        *auth_ = '\0';
        path_ = auth_;
        path_++;
        *path_ = '\0';
        query_ = path_;
        query_++;
        *query_ = '\0';
        frag_ = query_;
        frag_++;
        *frag_ = '\0';
        base_ = frag_;
        base_++;
        *base_ = '\0';
        uri_ = base_;
        uri_++;
        *uri_ = '\0';
        return total;
    }
References RAPIDJSON_NEW.
CopyPart()
template<typename ValueType , typename Allocator = CrtAllocator> Ch * rapidjson::GenericUri< ValueType, Allocator >::CopyPart (Ch * to, Ch * from, std::size_t len) inline private
Definition at line 399 of file uri.h.
{
        RAPIDJSON_ASSERT(to != 0);
        RAPIDJSON_ASSERT(from != 0);
        std::memcpy(to, from, len * sizeof(Ch));
        to[len] = '\0';
        Ch* next = to + len + 1;
        return next;
    }
References RAPIDJSON_ASSERT.
Free()
template<typename ValueType , typename Allocator = CrtAllocator> void rapidjson::GenericUri< ValueType, Allocator >::Free () inline private
Definition at line 267 of file uri.h.
                {
        if (scheme_) {
            Allocator::Free(scheme_);
            scheme_ = 0;
        }
    }
Get()
template<typename ValueType , typename Allocator = CrtAllocator> template<typename T > void rapidjson::GenericUri< ValueType, Allocator >::Get (T & uri, Allocator & allocator) inline
Getters.
Definition at line 99 of file uri.h.
{
        uri.template Set<const Ch*>(this->GetString(), allocator); // TypeHelper from document.h
    }
References GetString().
GetAllocator()
template<typename ValueType , typename Allocator = CrtAllocator> Allocator & rapidjson::GenericUri< ValueType, Allocator >::GetAllocator () inline
Get the allocator of this GenericUri.
Definition at line 229 of file uri.h.
{ return *allocator_; }
GetAuthString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetAuthString () const inline
Definition at line 109 of file uri.h.
{ return auth_; }
GetAuthStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetAuthStringLength () const inline
Definition at line 110 of file uri.h.
{ return auth_ == 0 ? 0 : internal::StrLen<Ch>(auth_); }
GetBaseString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetBaseString () const inline
Definition at line 105 of file uri.h.
{ return base_; }
GetBaseStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetBaseStringLength () const inline
Definition at line 106 of file uri.h.
{ return base_ == 0 ? 0 : internal::StrLen<Ch>(base_); }
GetFragString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetFragString () const inline
Definition at line 115 of file uri.h.
{ return frag_; }
GetFragStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetFragStringLength () const inline
Definition at line 116 of file uri.h.
{ return frag_ == 0 ? 0 : internal::StrLen<Ch>(frag_); }
GetPathString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetPathString () const inline
Definition at line 111 of file uri.h.
{ return path_; }
GetPathStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetPathStringLength () const inline
Definition at line 112 of file uri.h.
{ return path_ == 0 ? 0 : internal::StrLen<Ch>(path_); }
GetQueryString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetQueryString () const inline
Definition at line 113 of file uri.h.
{ return query_; }
GetQueryStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetQueryStringLength () const inline
Definition at line 114 of file uri.h.
{ return query_ == 0 ? 0 : internal::StrLen<Ch>(query_); }
GetSchemeString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetSchemeString () const inline
Definition at line 107 of file uri.h.
{ return scheme_; }
GetSchemeStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetSchemeStringLength () const inline
Definition at line 108 of file uri.h.
{ return scheme_ == 0 ? 0 : internal::StrLen<Ch>(scheme_); }
GetString()
template<typename ValueType , typename Allocator = CrtAllocator> const Ch * rapidjson::GenericUri< ValueType, Allocator >::GetString () const inline
Definition at line 103 of file uri.h.
{ return uri_; }
GetStringLength()
template<typename ValueType , typename Allocator = CrtAllocator> SizeType rapidjson::GenericUri< ValueType, Allocator >::GetStringLength () const inline
Definition at line 104 of file uri.h.
{ return uri_ == 0 ? 0 : internal::StrLen<Ch>(uri_); }
Match()
template<typename ValueType , typename Allocator = CrtAllocator> bool rapidjson::GenericUri< ValueType, Allocator >::Match (const GenericUri< ValueType, Allocator > & uri, bool full = true) const inline
Definition at line 137 of file uri.h.
{
        Ch* s1;
        Ch* s2;
        if (full) {
            s1 = uri_;
            s2 = uri.uri_;
        } else {
            s1 = base_;
            s2 = uri.base_;
        }
        if (s1 == s2) return true;
        if (s1 == 0 || s2 == 0) return false;
        return internal::StrCmp<Ch>(s1, s2) == 0;
    }
References rapidjson::GenericUri< ValueType, Allocator >::base_, and rapidjson::GenericUri< ValueType, Allocator >::uri_.
operator!=()
template<typename ValueType , typename Allocator = CrtAllocator> bool rapidjson::GenericUri< ValueType, Allocator >::operator!= (const GenericUri< ValueType, Allocator > & rhs) const inline
Definition at line 133 of file uri.h.
{
        return !Match(rhs, true);
    }
operator=()
template<typename ValueType , typename Allocator = CrtAllocator> GenericUri & rapidjson::GenericUri< ValueType, Allocator >::operator= (const GenericUri< ValueType, Allocator > & rhs) inline
Assignment operator.
Definition at line 81 of file uri.h.
{
        if (this != &rhs) {
            // Do not delete ownAllocator
            Free();
            Allocate(rhs.GetStringLength());
            auth_ = CopyPart(scheme_, rhs.scheme_, rhs.GetSchemeStringLength());
            path_ = CopyPart(auth_, rhs.auth_, rhs.GetAuthStringLength());
            query_ = CopyPart(path_, rhs.path_, rhs.GetPathStringLength());
            frag_ = CopyPart(query_, rhs.query_, rhs.GetQueryStringLength());
            base_ = CopyPart(frag_, rhs.frag_, rhs.GetFragStringLength());
            uri_ = CopyPart(base_, rhs.base_, rhs.GetBaseStringLength());
            CopyPart(uri_, rhs.uri_, rhs.GetStringLength());
        }
        return *this;
    }
References rapidjson::GenericUri< ValueType, Allocator >::auth_, rapidjson::GenericUri< ValueType, Allocator >::base_, rapidjson::GenericUri< ValueType, Allocator >::frag_, rapidjson::Free(), rapidjson::GenericUri< ValueType, Allocator >::GetAuthStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetBaseStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetFragStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetPathStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetQueryStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetSchemeStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetStringLength(), rapidjson::GenericUri< ValueType, Allocator >::path_, rapidjson::GenericUri< ValueType, Allocator >::query_, rapidjson::GenericUri< ValueType, Allocator >::scheme_, and rapidjson::GenericUri< ValueType, Allocator >::uri_.
operator==()
template<typename ValueType , typename Allocator = CrtAllocator> bool rapidjson::GenericUri< ValueType, Allocator >::operator== (const GenericUri< ValueType, Allocator > & rhs) const inline
Equality operators.
Definition at line 129 of file uri.h.
{
        return Match(rhs, true);
    }
Parse()
template<typename ValueType , typename Allocator = CrtAllocator> void rapidjson::GenericUri< ValueType, Allocator >::Parse (const Ch * uri, std::size_t len) inline private
Definition at line 277 of file uri.h.
{
        std::size_t start = 0, pos1 = 0, pos2 = 0;
        Allocate(len);
        // Look for scheme ([^:/?#]+):)?
        if (start < len) {
            while (pos1 < len) {
                if (uri[pos1] == ':') break;
                pos1++;
            }
            if (pos1 != len) {
                while (pos2 < len) {
                    if (uri[pos2] == '/') break;
                    if (uri[pos2] == '?') break;
                    if (uri[pos2] == '#') break;
                    pos2++;
                }
                if (pos1 < pos2) {
                    pos1++;
                    std::memcpy(scheme_, &uri[start], pos1 * sizeof(Ch));
                    scheme_[pos1] = '\0';
                    start = pos1;
                }
            }
        }
        // Look for auth (//([^/?#]*))?
        // Note need to set, increment, assign in 3 stages to avoid compiler warning bug.
        auth_ = scheme_ + GetSchemeStringLength();
        auth_++;
        *auth_ = '\0';
        if (start < len - 1 && uri[start] == '/' && uri[start + 1] == '/') {
            pos2 = start + 2;
            while (pos2 < len) {
                if (uri[pos2] == '/') break;
                if (uri[pos2] == '?') break;
                if (uri[pos2] == '#') break;
                pos2++;
            }
            std::memcpy(auth_, &uri[start], (pos2 - start) * sizeof(Ch));
            auth_[pos2 - start] = '\0';
            start = pos2;
        }
        // Look for path ([^?#]*)
        // Note need to set, increment, assign in 3 stages to avoid compiler warning bug.
        path_ = auth_ + GetAuthStringLength();
        path_++;
        *path_ = '\0';
        if (start < len) {
            pos2 = start;
            while (pos2 < len) {
                if (uri[pos2] == '?') break;
                if (uri[pos2] == '#') break;
                pos2++;
            }
            if (start != pos2) {
                std::memcpy(path_, &uri[start], (pos2 - start) * sizeof(Ch));
                path_[pos2 - start] = '\0';
                if (path_[0] == '/')
                    RemoveDotSegments();   // absolute path - normalize
                start = pos2;
            }
        }
        // Look for query (\?([^#]*))?
        // Note need to set, increment, assign in 3 stages to avoid compiler warning bug.
        query_ = path_ + GetPathStringLength();
        query_++;
        *query_ = '\0';
        if (start < len && uri[start] == '?') {
            pos2 = start + 1;
            while (pos2 < len) {
                if (uri[pos2] == '#') break;
                pos2++;
            }
            if (start != pos2) {
                std::memcpy(query_, &uri[start], (pos2 - start) * sizeof(Ch));
                query_[pos2 - start] = '\0';
                start = pos2;
            }
        }
        // Look for fragment (#(.*))?
        // Note need to set, increment, assign in 3 stages to avoid compiler warning bug.
        frag_ = query_ + GetQueryStringLength();
        frag_++;
        *frag_ = '\0';
        if (start < len && uri[start] == '#') {
            std::memcpy(frag_, &uri[start], (len - start) * sizeof(Ch));
            frag_[len - start] = '\0';
        }
        // Re-constitute base_ and uri_
        base_ = frag_ + GetFragStringLength() + 1;
        SetBase();
        uri_ = base_ + GetBaseStringLength() + 1;
        SetUri();
    }
RemoveDotSegments()
template<typename ValueType , typename Allocator = CrtAllocator> void rapidjson::GenericUri< ValueType, Allocator >::RemoveDotSegments () inline private
Definition at line 411 of file uri.h.
{
        std::size_t pathlen = GetPathStringLength();
        std::size_t pathpos = 0;  // Position in path_
        std::size_t newpos = 0;   // Position in new path_
        // Loop through each segment in original path_
        while (pathpos < pathlen) {
            // Get next segment, bounded by '/' or end
            size_t slashpos = 0;
            while ((pathpos + slashpos) < pathlen) {
                if (path_[pathpos + slashpos] == '/') break;
                slashpos++;
            }
            // Check for .. and . segments
            if (slashpos == 2 && path_[pathpos] == '.' && path_[pathpos + 1] == '.') {
                // Backup a .. segment in the new path_
                // We expect to find a previously added slash at the end or nothing
                RAPIDJSON_ASSERT(newpos == 0 || path_[newpos - 1] == '/');
                size_t lastslashpos = newpos;
                // Make sure we don't go beyond the start segment
                if (lastslashpos > 1) {
                    // Find the next to last slash and back up to it
                    lastslashpos--;
                    while (lastslashpos > 0) {
                        if (path_[lastslashpos - 1] == '/') break;
                        lastslashpos--;
                    }
                    // Set the new path_ position
                    newpos = lastslashpos;
                }
            } else if (slashpos == 1 && path_[pathpos] == '.') {
                // Discard . segment, leaves new path_ unchanged
            } else {
                // Move any other kind of segment to the new path_
                RAPIDJSON_ASSERT(newpos <= pathpos);
                std::memmove(&path_[newpos], &path_[pathpos], slashpos * sizeof(Ch));
                newpos += slashpos;
                // Add slash if not at end
                if ((pathpos + slashpos) < pathlen) {
                    path_[newpos] = '/';
                    newpos++;
                }
            }
            // Move to next segment
            pathpos += slashpos + 1;
        }
        path_[newpos] = '\0';
    }
References RAPIDJSON_ASSERT.
Resolve()
template<typename ValueType , typename Allocator = CrtAllocator> GenericUri rapidjson::GenericUri< ValueType, Allocator >::Resolve (const GenericUri< ValueType, Allocator > & baseuri, Allocator * allocator = 0) inline
Resolve this URI against another (base) URI in accordance with URI resolution rules.
Definition at line 156 of file uri.h.
{
        GenericUri resuri;
        resuri.allocator_ = allocator;
        // Ensure enough space for combining paths
        resuri.Allocate(GetStringLength() + baseuri.GetStringLength() + 1); // + 1 for joining slash
        if (!(GetSchemeStringLength() == 0)) {
            // Use all of this URI
            resuri.auth_ = CopyPart(resuri.scheme_, scheme_, GetSchemeStringLength());
            resuri.path_ = CopyPart(resuri.auth_, auth_, GetAuthStringLength());
            resuri.query_ = CopyPart(resuri.path_, path_, GetPathStringLength());
            resuri.frag_ = CopyPart(resuri.query_, query_, GetQueryStringLength());
            resuri.RemoveDotSegments();
        } else {
            // Use the base scheme
            resuri.auth_ = CopyPart(resuri.scheme_, baseuri.scheme_, baseuri.GetSchemeStringLength());
            if (!(GetAuthStringLength() == 0)) {
                // Use this auth, path, query
                resuri.path_ = CopyPart(resuri.auth_, auth_, GetAuthStringLength());
                resuri.query_ = CopyPart(resuri.path_, path_, GetPathStringLength());
                resuri.frag_ = CopyPart(resuri.query_, query_, GetQueryStringLength());
                resuri.RemoveDotSegments();
            } else {
                // Use the base auth
                resuri.path_ = CopyPart(resuri.auth_, baseuri.auth_, baseuri.GetAuthStringLength());
                if (GetPathStringLength() == 0) {
                    // Use the base path
                    resuri.query_ = CopyPart(resuri.path_, baseuri.path_, baseuri.GetPathStringLength());
                    if (GetQueryStringLength() == 0) {
                        // Use the base query
                        resuri.frag_ = CopyPart(resuri.query_, baseuri.query_, baseuri.GetQueryStringLength());
                    } else {
                        // Use this query
                        resuri.frag_ = CopyPart(resuri.query_, query_, GetQueryStringLength());
                    }
                } else {
                    if (path_[0] == '/') {
                        // Absolute path - use all of this path
                        resuri.query_ = CopyPart(resuri.path_, path_, GetPathStringLength());
                        resuri.RemoveDotSegments();
                    } else {
                        // Relative path - append this path to base path after base path's last slash
                        size_t pos = 0;
                        if (!(baseuri.GetAuthStringLength() == 0) && baseuri.GetPathStringLength() == 0) {
                            resuri.path_[pos] = '/';
                            pos++;
                        }
                        size_t lastslashpos = baseuri.GetPathStringLength();
                        while (lastslashpos > 0) {
                            if (baseuri.path_[lastslashpos - 1] == '/') break;
                            lastslashpos--;
                        }
                        std::memcpy(&resuri.path_[pos], baseuri.path_, lastslashpos * sizeof(Ch));
                        pos += lastslashpos;
                        resuri.query_ = CopyPart(&resuri.path_[pos], path_, GetPathStringLength());
                        resuri.RemoveDotSegments();
                    }
                    // Use this query
                    resuri.frag_ = CopyPart(resuri.query_, query_, GetQueryStringLength());
                }
            }
        }
        // Always use this frag
        resuri.base_ = CopyPart(resuri.frag_, frag_, GetFragStringLength());
        // Re-constitute base_ and uri_
        resuri.SetBase();
        resuri.uri_ = resuri.base_ + resuri.GetBaseStringLength() + 1;
        resuri.SetUri();
        return resuri;
    }
References rapidjson::GenericUri< ValueType, Allocator >::Allocate(), rapidjson::GenericUri< ValueType, Allocator >::allocator_, rapidjson::GenericUri< ValueType, Allocator >::auth_, rapidjson::GenericUri< ValueType, Allocator >::base_, rapidjson::GenericUri< ValueType, Allocator >::frag_, rapidjson::GenericUri< ValueType, Allocator >::GetAuthStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetBaseStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetPathStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetQueryStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetSchemeStringLength(), rapidjson::GenericUri< ValueType, Allocator >::GetStringLength(), rapidjson::GenericUri< ValueType, Allocator >::path_, rapidjson::GenericUri< ValueType, Allocator >::query_, rapidjson::GenericUri< ValueType, Allocator >::RemoveDotSegments(), rapidjson::GenericUri< ValueType, Allocator >::scheme_, rapidjson::GenericUri< ValueType, Allocator >::SetBase(), rapidjson::GenericUri< ValueType, Allocator >::SetUri(), and rapidjson::GenericUri< ValueType, Allocator >::uri_.
SetBase()
template<typename ValueType , typename Allocator = CrtAllocator> void rapidjson::GenericUri< ValueType, Allocator >::SetBase () inline private
Definition at line 374 of file uri.h.
                   {
        Ch* next = base_;
        std::memcpy(next, scheme_, GetSchemeStringLength() * sizeof(Ch));
        next+= GetSchemeStringLength();
        std::memcpy(next, auth_, GetAuthStringLength() * sizeof(Ch));
        next+= GetAuthStringLength();
        std::memcpy(next, path_, GetPathStringLength() * sizeof(Ch));
        next+= GetPathStringLength();
        std::memcpy(next, query_, GetQueryStringLength() * sizeof(Ch));
        next+= GetQueryStringLength();
        *next = '\0';
    }
SetUri()
template<typename ValueType , typename Allocator = CrtAllocator> void rapidjson::GenericUri< ValueType, Allocator >::SetUri () inline private
Definition at line 388 of file uri.h.
                  {
        Ch* next = uri_;
        std::memcpy(next, base_, GetBaseStringLength() * sizeof(Ch));
        next+= GetBaseStringLength();
        std::memcpy(next, frag_, GetFragStringLength() * sizeof(Ch));
        next+= GetFragStringLength();
        *next = '\0';
    }
Member Data Documentation
allocator_
template<typename ValueType , typename Allocator = CrtAllocator> Allocator* rapidjson::GenericUri< ValueType, Allocator >::allocator_ private
The current allocator. It is either user-supplied or equal to ownAllocator_.
Definition at line 468 of file uri.h.
auth_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::auth_ private
Definition at line 463 of file uri.h.
base_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::base_ private
Definition at line 461 of file uri.h.
frag_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::frag_ private
Definition at line 466 of file uri.h.
ownAllocator_
template<typename ValueType , typename Allocator = CrtAllocator> Allocator* rapidjson::GenericUri< ValueType, Allocator >::ownAllocator_ private
Allocator owned by this Uri.
Definition at line 469 of file uri.h.
path_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::path_ private
Definition at line 464 of file uri.h.
query_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::query_ private
Definition at line 465 of file uri.h.
scheme_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::scheme_ private
Definition at line 462 of file uri.h.
uri_
template<typename ValueType , typename Allocator = CrtAllocator> Ch* rapidjson::GenericUri< ValueType, Allocator >::uri_ private
Definition at line 460 of file uri.h.
The documentation for this class was generated from the following file:
rapidjson/include/rapidjson/uri.h