wiNpoS: rapidjson::GenericArray< Const, ValueT > Class Template Reference
rapidjson::GenericArray< Const, ValueT > Class Template Reference
Helper class for accessing Value of array type.
#include <document.h>
Public Types
typedef GenericArray< true, ValueT > ConstArray
typedef GenericArray< false, ValueT > Array
typedef ValueT PlainType
typedef internal::MaybeAddConst< Const, PlainType >::Type ValueType
typedef ValueType * ValueIterator
typedef const ValueT * ConstValueIterator
typedef ValueType::AllocatorType AllocatorType
typedef ValueType::StringRefType StringRefType
Public Member Functions
GenericArray (const GenericArray &rhs)
GenericArray & operator= (const GenericArray &rhs)
~GenericArray ()
operator ValueType & () const
SizeType Size () const
SizeType Capacity () const
bool Empty () const
void Clear () const
ValueType & operator[] (SizeType index) const
ValueIterator Begin () const
ValueIterator End () const
GenericArray Reserve (SizeType newCapacity, AllocatorType &allocator) const
GenericArray PushBack (ValueType &value, AllocatorType &allocator) const
GenericArray PushBack (StringRefType value, AllocatorType &allocator) const
template<typename T >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T >, internal::IsGenericValue< T > >),(const GenericArray &)) PushBack(T value
GenericArray PopBack () const
ValueIterator Erase (ConstValueIterator pos) const
ValueIterator Erase (ConstValueIterator first, ConstValueIterator last) const
Public Attributes
AllocatorType &allocator const { value_.PushBack(value, allocator)
return * this
Private Member Functions
GenericArray ()
GenericArray (ValueType &value)
Private Attributes
ValueType & value_
Friends
template<typename , typename >
class GenericValue
Detailed Description
template<bool Const, typename ValueT>
class rapidjson::GenericArray< Const, ValueT >
Helper class for accessing Value of array type.
Instance of this helper class is obtained by GenericValue::GetArray(). In addition to all APIs for array type, it provides range-based for loop if RAPIDJSON_HAS_CXX11_RANGE_FOR=1.
Definition at line 2898 of file document.h.
Member Typedef Documentation
AllocatorType
template<bool Const, typename ValueT > typedef ValueType::AllocatorType rapidjson::GenericArray< Const, ValueT >::AllocatorType
Definition at line 2906 of file document.h.
Array
template<bool Const, typename ValueT > typedef GenericArray<false, ValueT> rapidjson::GenericArray< Const, ValueT >::Array
Definition at line 2901 of file document.h.
ConstArray
template<bool Const, typename ValueT > typedef GenericArray<true, ValueT> rapidjson::GenericArray< Const, ValueT >::ConstArray
Definition at line 2900 of file document.h.
ConstValueIterator
template<bool Const, typename ValueT > typedef const ValueT* rapidjson::GenericArray< Const, ValueT >::ConstValueIterator
Definition at line 2905 of file document.h.
PlainType
template<bool Const, typename ValueT > typedef ValueT rapidjson::GenericArray< Const, ValueT >::PlainType
Definition at line 2902 of file document.h.
StringRefType
template<bool Const, typename ValueT > typedef ValueType::StringRefType rapidjson::GenericArray< Const, ValueT >::StringRefType
Definition at line 2907 of file document.h.
ValueIterator
template<bool Const, typename ValueT > typedef ValueType* rapidjson::GenericArray< Const, ValueT >::ValueIterator
Definition at line 2904 of file document.h.
ValueType
template<bool Const, typename ValueT > typedef internal::MaybeAddConst<Const,PlainType>::Type rapidjson::GenericArray< Const, ValueT >::ValueType
Definition at line 2903 of file document.h.
Constructor & Destructor Documentation
GenericArray() [1/3]
template<bool Const, typename ValueT > rapidjson::GenericArray< Const, ValueT >::GenericArray (const GenericArray< Const, ValueT > & rhs) inline
Definition at line 2912 of file document.h.
: value_(rhs.value_) {}
~GenericArray()
template<bool Const, typename ValueT > rapidjson::GenericArray< Const, ValueT >::~GenericArray () inline
Definition at line 2914 of file document.h.
{}
GenericArray() [2/3]
template<bool Const, typename ValueT > rapidjson::GenericArray< Const, ValueT >::GenericArray () private
GenericArray() [3/3]
template<bool Const, typename ValueT > rapidjson::GenericArray< Const, ValueT >::GenericArray (ValueType & value) inline private
Definition at line 2942 of file document.h.
: value_(value) {}
References rapidjson::value.
Member Function Documentation
Begin()
template<bool Const, typename ValueT > ValueIterator rapidjson::GenericArray< Const, ValueT >::Begin () const inline
Definition at line 2922 of file document.h.
{ return value_.Begin(); }
Capacity()
template<bool Const, typename ValueT > SizeType rapidjson::GenericArray< Const, ValueT >::Capacity () const inline
Definition at line 2918 of file document.h.
{ return value_.Capacity(); }
Clear()
template<bool Const, typename ValueT > void rapidjson::GenericArray< Const, ValueT >::Clear () const inline
Definition at line 2920 of file document.h.
{ value_.Clear(); }
Empty()
template<bool Const, typename ValueT > bool rapidjson::GenericArray< Const, ValueT >::Empty () const inline
Definition at line 2919 of file document.h.
{ return value_.Empty(); }
End()
template<bool Const, typename ValueT > ValueIterator rapidjson::GenericArray< Const, ValueT >::End () const inline
Definition at line 2923 of file document.h.
{ return value_.End(); }
Erase() [1/2]
template<bool Const, typename ValueT > ValueIterator rapidjson::GenericArray< Const, ValueT >::Erase (ConstValueIterator first, ConstValueIterator last) const inline
Definition at line 2933 of file document.h.
{ return value_.Erase(first, last); }
Erase() [2/2]
template<bool Const, typename ValueT > ValueIterator rapidjson::GenericArray< Const, ValueT >::Erase (ConstValueIterator pos) const inline
Definition at line 2932 of file document.h.
{ return value_.Erase(pos); }
operator ValueType &()
template<bool Const, typename ValueT > rapidjson::GenericArray< Const, ValueT >::operator ValueType & () const inline
Definition at line 2916 of file document.h.
{ return value_; }
operator=()
template<bool Const, typename ValueT > GenericArray & rapidjson::GenericArray< Const, ValueT >::operator= (const GenericArray< Const, ValueT > & rhs) inline
Definition at line 2913 of file document.h.
{ value_ = rhs.value_; return *this; }
References rapidjson::GenericArray< Const, ValueT >::value_.
operator[]()
template<bool Const, typename ValueT > ValueType & rapidjson::GenericArray< Const, ValueT >::operator[] (SizeType index) const inline
Definition at line 2921 of file document.h.
{  return value_[index]; }
PopBack()
template<bool Const, typename ValueT > GenericArray rapidjson::GenericArray< Const, ValueT >::PopBack () const inline
Definition at line 2931 of file document.h.
{ value_.PopBack(); return *this; }
References rapidjson::GenericArray< Const, ValueT >::PopBack().
PushBack() [1/2]
template<bool Const, typename ValueT > GenericArray rapidjson::GenericArray< Const, ValueT >::PushBack (StringRefType value, AllocatorType & allocator) const inline
Definition at line 2929 of file document.h.
{ value_.PushBack(value, allocator); return *this; }
References rapidjson::GenericArray< Const, ValueT >::PushBack(), and rapidjson::value.
PushBack() [2/2]
template<bool Const, typename ValueT > GenericArray rapidjson::GenericArray< Const, ValueT >::PushBack (ValueType & value, AllocatorType & allocator) const inline
Definition at line 2925 of file document.h.
{ value_.PushBack(value, allocator); return *this; }
References rapidjson::GenericArray< Const, ValueT >::PushBack(), and rapidjson::value.
RAPIDJSON_DISABLEIF_RETURN()
template<bool Const, typename ValueT > template<typename T > rapidjson::GenericArray< Const, ValueT >::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T >, internal::IsGenericValue< T > >) , (const GenericArray< Const, ValueT > &))
Reserve()
template<bool Const, typename ValueT > GenericArray rapidjson::GenericArray< Const, ValueT >::Reserve (SizeType newCapacity, AllocatorType & allocator) const inline
Definition at line 2924 of file document.h.
{ value_.Reserve(newCapacity, allocator); return *this; }
References rapidjson::GenericArray< Const, ValueT >::Reserve().
Size()
template<bool Const, typename ValueT > SizeType rapidjson::GenericArray< Const, ValueT >::Size () const inline
Definition at line 2917 of file document.h.
{ return value_.Size(); }
Friends And Related Symbol Documentation
GenericValue
template<bool Const, typename ValueT > template<typename , typename > friend class GenericValue friend
Definition at line 2910 of file document.h.
Member Data Documentation
const
template<bool Const, typename ValueT > AllocatorType& allocator rapidjson::GenericArray< Const, ValueT >::const { value_.PushBack(value, allocator)
Definition at line 2930 of file document.h.
this
template<bool Const, typename ValueT > return* rapidjson::GenericArray< Const, ValueT >::this
Definition at line 2930 of file document.h.
value_
template<bool Const, typename ValueT > ValueType& rapidjson::GenericArray< Const, ValueT >::value_ private
Definition at line 2943 of file document.h.
The documentation for this class was generated from the following file:
rapidjson/include/rapidjson/document.h