wiNpoS: testing::internal::ContainerEqMatcher< Container > Class Template Reference
testing::internal::ContainerEqMatcher< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< Container > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
Public Member Functions
ContainerEqMatcher (const Container &expected)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename LhsContainer >
bool MatchAndExplain (const LhsContainer &lhs, MatchResultListener *listener) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher)
Private Attributes
const StlContainer expected_
Detailed Description
template<typename Container>
class testing::internal::ContainerEqMatcher< Container >
Definition at line 2816 of file gmock-matchers.h.
Member Typedef Documentation
StlContainer
template<typename Container > typedef View::type testing::internal::ContainerEqMatcher< Container >::StlContainer
Definition at line 2819 of file gmock-matchers.h.
StlContainerReference
template<typename Container > typedef View::const_reference testing::internal::ContainerEqMatcher< Container >::StlContainerReference
Definition at line 2820 of file gmock-matchers.h.
View
template<typename Container > typedef internal::StlContainerView<Container> testing::internal::ContainerEqMatcher< Container >::View
Definition at line 2818 of file gmock-matchers.h.
Constructor & Destructor Documentation
ContainerEqMatcher()
template<typename Container > testing::internal::ContainerEqMatcher< Container >::ContainerEqMatcher (const Container & expected) inline explicit
Definition at line 2824 of file gmock-matchers.h.
      : expected_(View::Copy(expected)) {
    // Makes sure the user doesn't instantiate this class template
    // with a const or reference type.
    (void)testing::StaticAssertTypeEq<Container,
        GTEST_REMOVE_REFERENCE_AND_CONST_(Container)>();
  }
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
Member Function Documentation
DescribeNegationTo()
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2836 of file gmock-matchers.h.
{
    *os << "does not equal ";
    UniversalPrint(expected_, os);
  }
References testing::internal::ContainerEqMatcher< Container >::expected_, and testing::internal::UniversalPrint().
DescribeTo()
template<typename Container > void testing::internal::ContainerEqMatcher< Container >::DescribeTo (::std::ostream * os) const inline
Definition at line 2832 of file gmock-matchers.h.
{
    *os << "equals ";
    UniversalPrint(expected_, os);
  }
References testing::internal::ContainerEqMatcher< Container >::expected_, and testing::internal::UniversalPrint().
GTEST_DISALLOW_ASSIGN_()
template<typename Container > testing::internal::ContainerEqMatcher< Container >::GTEST_DISALLOW_ASSIGN_ (ContainerEqMatcher< Container >) private
MatchAndExplain()
template<typename Container > template<typename LhsContainer > bool testing::internal::ContainerEqMatcher< Container >::MatchAndExplain (const LhsContainer & lhs, MatchResultListener * listener) const inline
Definition at line 2842 of file gmock-matchers.h.
{
    // GTEST_REMOVE_CONST_() is needed to work around an MSVC 8.0 bug
    // that causes LhsContainer to be a const type sometimes.
    typedef internal::StlContainerView<GTEST_REMOVE_CONST_(LhsContainer)>
        LhsView;
    typedef typename LhsView::type LhsStlContainer;
    StlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
    if (lhs_stl_container == expected_)
      return true;
    ::std::ostream* const os = listener->stream();
    if (os != NULL) {
      // Something is different. Check for extra values first.
      bool printed_header = false;
      for (typename LhsStlContainer::const_iterator it =
               lhs_stl_container.begin();
           it != lhs_stl_container.end(); ++it) {
        if (internal::ArrayAwareFind(expected_.begin(), expected_.end(), *it) ==
            expected_.end()) {
          if (printed_header) {
            *os << ", ";
          } else {
            *os << "which has these unexpected elements: ";
            printed_header = true;
          }
          UniversalPrint(*it, os);
        }
      }
      // Now check for missing values.
      bool printed_header2 = false;
      for (typename StlContainer::const_iterator it = expected_.begin();
           it != expected_.end(); ++it) {
        if (internal::ArrayAwareFind(
                lhs_stl_container.begin(), lhs_stl_container.end(), *it) ==
            lhs_stl_container.end()) {
          if (printed_header2) {
            *os << ", ";
          } else {
            *os << (printed_header ? ",\nand" : "which")
                << " doesn't have these expected elements: ";
            printed_header2 = true;
          }
          UniversalPrint(*it, os);
        }
      }
    }
    return false;
  }
References testing::internal::ArrayAwareFind(), testing::internal::ContainerEqMatcher< Container >::expected_, GTEST_REMOVE_CONST_, testing::MatchResultListener::stream(), and testing::internal::UniversalPrint().
Member Data Documentation
expected_
template<typename Container > const StlContainer testing::internal::ContainerEqMatcher< Container >::expected_ private
Definition at line 2895 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h