wiNpoS: testing::internal::any_cast_matcher::AnyCastMatcher< T > Class Template Reference
testing::internal::any_cast_matcher::AnyCastMatcher< T > Class Template Reference
Public Member Functions
AnyCastMatcher (const ::testing::Matcher< const T & > &matcher)
template<typename AnyType >
bool MatchAndExplain (const AnyType &value, ::testing::MatchResultListener *listener) const
void DescribeTo (std::ostream *os) const
void DescribeNegationTo (std::ostream *os) const
Static Private Member Functions
static std::string GetTypeName ()
Private Attributes
const ::testing::Matcher< const T & > matcher_
Detailed Description
template<typename T>
class testing::internal::any_cast_matcher::AnyCastMatcher< T >
Definition at line 4123 of file gmock-matchers.h.
Constructor & Destructor Documentation
AnyCastMatcher()
template<typename T > testing::internal::any_cast_matcher::AnyCastMatcher< T >::AnyCastMatcher (const ::testing::Matcher< const T & > & matcher) inline explicit
Definition at line 4125 of file gmock-matchers.h.
      : matcher_(matcher) {}
Member Function Documentation
DescribeNegationTo()
template<typename T > void testing::internal::any_cast_matcher::AnyCastMatcher< T >::DescribeNegationTo (std::ostream * os) const inline
Definition at line 4156 of file gmock-matchers.h.
{
    *os << "is an 'any' type with value of type other than '" << GetTypeName()
        << "' or the value ";
    matcher_.DescribeNegationTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), testing::internal::any_cast_matcher::AnyCastMatcher< T >::GetTypeName(), and testing::internal::any_cast_matcher::AnyCastMatcher< T >::matcher_.
DescribeTo()
template<typename T > void testing::internal::any_cast_matcher::AnyCastMatcher< T >::DescribeTo (std::ostream * os) const inline
Definition at line 4150 of file gmock-matchers.h.
{
    *os << "is an 'any' type with value of type '" << GetTypeName()
        << "' and the value ";
    matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), testing::internal::any_cast_matcher::AnyCastMatcher< T >::GetTypeName(), and testing::internal::any_cast_matcher::AnyCastMatcher< T >::matcher_.
GetTypeName()
template<typename T > static std::string testing::internal::any_cast_matcher::AnyCastMatcher< T >::GetTypeName () inline static private
Definition at line 4163 of file gmock-matchers.h.
{
#if GTEST_HAS_RTTI
    GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(
        return internal::GetTypeName<T>());
#endif
    return "the element type";
  }
References GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_.
MatchAndExplain()
template<typename T > template<typename AnyType > bool testing::internal::any_cast_matcher::AnyCastMatcher< T >::MatchAndExplain (const AnyType & value, ::testing::MatchResultListener * listener) const inline
Definition at line 4129 of file gmock-matchers.h.
{
    if (!listener->IsInterested()) {
      const T* ptr = any_cast<T>(&value);
      return ptr != NULL && matcher_.Matches(*ptr);
    }
    const T* elem = any_cast<T>(&value);
    if (elem == NULL) {
      *listener << "whose value is not of type '" << GetTypeName() << "'";
      return false;
    }
    StringMatchResultListener elem_listener;
    const bool match = matcher_.MatchAndExplain(*elem, &elem_listener);
    *listener << "whose value " << PrintToString(*elem)
              << (match ? " matches" : " doesn't match");
    PrintIfNotEmpty(elem_listener.str(), listener->stream());
    return match;
  }
References testing::internal::any_cast_matcher::AnyCastMatcher< T >::GetTypeName(), testing::MatchResultListener::IsInterested(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::any_cast_matcher::AnyCastMatcher< T >::matcher_, testing::internal::MatcherBase< T >::Matches(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and T.
Member Data Documentation
matcher_
template<typename T > const ::testing::Matcher<const T&> testing::internal::any_cast_matcher::AnyCastMatcher< T >::matcher_ private
Definition at line 4171 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h