wiNpoS: rapidjson::GenericValue< Encoding, Allocator > Class Template Reference
rapidjson::GenericValue< Encoding, Allocator > Class Template Reference
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
#include <document.h>
Classes
struct ArrayData
union Data
struct Flag
union Number
struct ObjectData
struct ShortString
struct String
Public Types
typedef GenericMember< Encoding, Allocator > Member
Name-value pair in an object.
typedef Encoding EncodingType
Encoding type from template parameter.
typedef Allocator AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericStringRef< Ch > StringRefType
Reference to a constant string.
typedef GenericMemberIterator< false, Encoding, Allocator >::Iterator MemberIterator
Member iterator for iterating in object.
typedef GenericMemberIterator< true, Encoding, Allocator >::Iterator ConstMemberIterator
Constant member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
typedef GenericValue< Encoding, Allocator > ValueType
Value type of itself.
typedef GenericArray< false, ValueType > Array
typedef GenericArray< true, ValueType > ConstArray
typedef GenericObject< false, ValueType > Object
typedef GenericObject< true, ValueType > ConstObject
Assignment operators
enum {
kBoolFlag = 0x0008 , kNumberFlag = 0x0010 , kIntFlag = 0x0020 , kUintFlag = 0x0040 ,
kInt64Flag = 0x0080 , kUint64Flag = 0x0100 , kDoubleFlag = 0x0200 , kStringFlag = 0x0400 ,
kCopyFlag = 0x0800 , kInlineStrFlag = 0x1000 , kNullFlag = kNullType , kTrueFlag = static_cast<int>(kTrueType) | static_cast<int>(kBoolFlag) ,
kFalseFlag = static_cast<int>(kFalseType) | static_cast<int>(kBoolFlag) , kNumberIntFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kIntFlag | kInt64Flag) , kNumberUintFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kUintFlag | kUint64Flag | kInt64Flag) , kNumberInt64Flag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kInt64Flag) ,
kNumberUint64Flag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kUint64Flag) , kNumberDoubleFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kDoubleFlag) , kNumberAnyFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kIntFlag | kInt64Flag | kUintFlag | kUint64Flag | kDoubleFlag) , kConstStringFlag = static_cast<int>(kStringType) | static_cast<int>(kStringFlag) ,
kCopyStringFlag = static_cast<int>(kStringType) | static_cast<int>(kStringFlag | kCopyFlag) , kShortStringFlag = static_cast<int>(kStringType) | static_cast<int>(kStringFlag | kCopyFlag | kInlineStrFlag) , kObjectFlag = kObjectType , kArrayFlag = kArrayType ,
kTypeMask = 0x07
}
template<typename , typename , typename >
class GenericDocument
static const SizeType kDefaultArrayCapacity = 16
static const SizeType kDefaultObjectCapacity = 16
Data data_
GenericValue & operator= (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment with move semantics.
GenericValue & operator= (StringRefType str) RAPIDJSON_NOEXCEPT
Assignment of constant string reference (no copy)
template<typename T >
RAPIDJSON_DISABLEIF_RETURN ((internal::IsPointer< T >),(GenericValue &)) operator
Assignment with primitive types.
RAPIDJSON_FORCEINLINE const Ch * GetStringPointer () const
RAPIDJSON_FORCEINLINE const Ch * SetStringPointer (const Ch *str)
RAPIDJSON_FORCEINLINE GenericValue * GetElementsPointer () const
RAPIDJSON_FORCEINLINE GenericValue * SetElementsPointer (GenericValue *elements)
RAPIDJSON_FORCEINLINE Member * GetMembersPointer () const
RAPIDJSON_FORCEINLINE Member * SetMembersPointer (Member *members)
RAPIDJSON_FORCEINLINE Member * DoAllocMembers (SizeType capacity, Allocator &allocator)
void DoReserveMembers (SizeType newCapacity, Allocator &allocator)
template<typename SourceAllocator >
MemberIterator DoFindMember (const GenericValue< Encoding, SourceAllocator > &name)
void DoClearMembers ()
void DoFreeMembers ()
void DoAddMember (GenericValue &name, GenericValue &value, Allocator &allocator)
MemberIterator DoRemoveMember (MemberIterator m)
MemberIterator DoEraseMembers (ConstMemberIterator first, ConstMemberIterator last)
template<typename SourceAllocator >
void DoCopyMembers (const GenericValue< Encoding, SourceAllocator > &rhs, Allocator &allocator, bool copyConstStrings)
void SetArrayRaw (GenericValue *values, SizeType count, Allocator &allocator)
void SetObjectRaw (Member *members, SizeType count, Allocator &allocator)
Initialize this value as object with initial data, without calling destructor.
void SetStringRaw (StringRefType s) RAPIDJSON_NOEXCEPT
Initialize this value as constant string, without calling destructor.
void SetStringRaw (StringRefType s, Allocator &allocator)
Initialize this value as copy string with initial data, without calling destructor.
void RawAssign (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment without calling destructor.
template<typename SourceAllocator >
bool StringEqual (const GenericValue< Encoding, SourceAllocator > &rhs) const
static RAPIDJSON_FORCEINLINE const Ch * DataString (const Data &data)
static RAPIDJSON_FORCEINLINE SizeType DataStringLength (const Data &data)
Constructors and destructor.
GenericValue () RAPIDJSON_NOEXCEPT
Default constructor creates a null value.
GenericValue (Type type) RAPIDJSON_NOEXCEPT
Constructor with JSON value type.
template<typename SourceAllocator >
GenericValue (const GenericValue< Encoding, SourceAllocator > &rhs, Allocator &allocator, bool copyConstStrings=false)
Explicit copy constructor (with allocator)
template<typename T >
GenericValue (T b, RAPIDJSON_ENABLEIF((internal::IsSame< bool, T >))) RAPIDJSON_NOEXCEPT
Constructor for boolean value.
GenericValue (int i) RAPIDJSON_NOEXCEPT
Constructor for int value.
GenericValue (unsigned u) RAPIDJSON_NOEXCEPT
Constructor for unsigned value.
GenericValue (int64_t i64) RAPIDJSON_NOEXCEPT
Constructor for int64_t value.
GenericValue (uint64_t u64) RAPIDJSON_NOEXCEPT
Constructor for uint64_t value.
GenericValue (double d) RAPIDJSON_NOEXCEPT
Constructor for double value.
GenericValue (float f) RAPIDJSON_NOEXCEPT
Constructor for float value.
GenericValue (const Ch *s, SizeType length) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (StringRefType s) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (Array a) RAPIDJSON_NOEXCEPT
Constructor for Array.
GenericValue (Object o) RAPIDJSON_NOEXCEPT
Constructor for Object.
~GenericValue ()
Destructor.
GenericValue (const GenericValue &rhs)
Copy constructor is not permitted.
Detailed Description
template<typename Encoding, typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>>
class rapidjson::GenericValue< Encoding, Allocator >
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
A JSON value can be one of 7 types. This class is a variant type supporting these types.
Use the Value if UTF8 and default allocator
Template Parameters
Encoding Encoding of the value. (Even non-string values need to have the same encoding in a document)
Allocator Allocator type for allocating memory of object, array and string.
Definition at line 668 of file document.h.
Member Typedef Documentation
AllocatorType
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef Allocator rapidjson::GenericValue< Encoding, Allocator >::AllocatorType
Allocator type from template parameter.
Definition at line 673 of file document.h.
Array
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericArray<false, ValueType> rapidjson::GenericValue< Encoding, Allocator >::Array
Definition at line 681 of file document.h.
Ch
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef Encoding::Ch rapidjson::GenericValue< Encoding, Allocator >::Ch
Character type derived from Encoding.
Definition at line 674 of file document.h.
ConstArray
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericArray<true, ValueType> rapidjson::GenericValue< Encoding, Allocator >::ConstArray
Definition at line 682 of file document.h.
ConstMemberIterator
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericMemberIterator<true,Encoding,Allocator>::Iterator rapidjson::GenericValue< Encoding, Allocator >::ConstMemberIterator
Constant member iterator for iterating in object.
Definition at line 677 of file document.h.
ConstObject
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericObject<true, ValueType> rapidjson::GenericValue< Encoding, Allocator >::ConstObject
Definition at line 684 of file document.h.
ConstValueIterator
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef const GenericValue* rapidjson::GenericValue< Encoding, Allocator >::ConstValueIterator
Constant value iterator for iterating in array.
Definition at line 679 of file document.h.
EncodingType
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef Encoding rapidjson::GenericValue< Encoding, Allocator >::EncodingType
Encoding type from template parameter.
Definition at line 672 of file document.h.
Member
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericMember<Encoding, Allocator> rapidjson::GenericValue< Encoding, Allocator >::Member
Name-value pair in an object.
Definition at line 671 of file document.h.
MemberIterator
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericMemberIterator<false,Encoding,Allocator>::Iterator rapidjson::GenericValue< Encoding, Allocator >::MemberIterator
Member iterator for iterating in object.
Definition at line 676 of file document.h.
Object
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericObject<false, ValueType> rapidjson::GenericValue< Encoding, Allocator >::Object
Definition at line 683 of file document.h.
StringRefType
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericStringRef<Ch> rapidjson::GenericValue< Encoding, Allocator >::StringRefType
Reference to a constant string.
Definition at line 675 of file document.h.
ValueIterator
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericValue* rapidjson::GenericValue< Encoding, Allocator >::ValueIterator
Value iterator for iterating in array.
Definition at line 678 of file document.h.
ValueType
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> typedef GenericValue<Encoding, Allocator> rapidjson::GenericValue< Encoding, Allocator >::ValueType
Value type of itself.
Definition at line 680 of file document.h.
Member Enumeration Documentation
anonymous enum
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> anonymous enum
Enumerator
kBoolFlag
kNumberFlag
kIntFlag
kUintFlag
kInt64Flag
kUint64Flag
kDoubleFlag
kStringFlag
kCopyFlag
kInlineStrFlag
kNullFlag
kTrueFlag
kFalseFlag
kNumberIntFlag
kNumberUintFlag
kNumberInt64Flag
kNumberUint64Flag
kNumberDoubleFlag
kNumberAnyFlag
kConstStringFlag
kCopyStringFlag
kShortStringFlag
kObjectFlag
kArrayFlag
kTypeMask
Definition at line 1991 of file document.h.
         {
        kBoolFlag       = 0x0008,
        kNumberFlag     = 0x0010,
        kIntFlag        = 0x0020,
        kUintFlag       = 0x0040,
        kInt64Flag      = 0x0080,
        kUint64Flag     = 0x0100,
        kDoubleFlag     = 0x0200,
        kStringFlag     = 0x0400,
        kCopyFlag       = 0x0800,
        kInlineStrFlag  = 0x1000,
        // Initial flags of different types.
        kNullFlag = kNullType,
        // These casts are added to suppress the warning on MSVC about bitwise operations between enums of different types.
        kTrueFlag = static_cast<int>(kTrueType) | static_cast<int>(kBoolFlag),
        kFalseFlag = static_cast<int>(kFalseType) | static_cast<int>(kBoolFlag),
        kNumberIntFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kIntFlag | kInt64Flag),
        kNumberUintFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kUintFlag | kUint64Flag | kInt64Flag),
        kNumberInt64Flag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kInt64Flag),
        kNumberUint64Flag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kUint64Flag),
        kNumberDoubleFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kDoubleFlag),
        kNumberAnyFlag = static_cast<int>(kNumberType) | static_cast<int>(kNumberFlag | kIntFlag | kInt64Flag | kUintFlag | kUint64Flag | kDoubleFlag),
        kConstStringFlag = static_cast<int>(kStringType) | static_cast<int>(kStringFlag),
        kCopyStringFlag = static_cast<int>(kStringType) | static_cast<int>(kStringFlag | kCopyFlag),
        kShortStringFlag = static_cast<int>(kStringType) | static_cast<int>(kStringFlag | kCopyFlag | kInlineStrFlag),
        kObjectFlag = kObjectType,
        kArrayFlag = kArrayType,
        kTypeMask = 0x07
    };
Constructor & Destructor Documentation
GenericValue() [1/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue () inline
Default constructor creates a null value.
Definition at line 690 of file document.h.
: data_() { data_.f.flags = kNullFlag; }
GenericValue() [2/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const GenericValue< Encoding, Allocator > & rhs) private
Copy constructor is not permitted.
GenericValue() [3/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (Type type) inline explicit
Constructor with JSON value type.
This creates a Value of specified type with default content.
Parameters
type Type of the value.
Note
Default content for number is zero.
Definition at line 720 of file document.h.
                                                        : data_() {
        static const uint16_t defaultFlags[] = {
            kNullFlag, kFalseFlag, kTrueFlag, kObjectFlag, kArrayFlag, kShortStringFlag,
            kNumberAnyFlag
        };
        RAPIDJSON_NOEXCEPT_ASSERT(type >= kNullType && type <= kNumberType);
        data_.f.flags = defaultFlags[type];
        // Use ShortString to store empty string.
        if (type == kStringType)
            data_.ss.SetLength(0);
    }
References rapidjson::kNullType, rapidjson::kNumberType, rapidjson::kStringType, and RAPIDJSON_NOEXCEPT_ASSERT.
GenericValue() [4/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename SourceAllocator > rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const GenericValue< Encoding, SourceAllocator > & rhs, Allocator & allocator, bool copyConstStrings = false) inline
Explicit copy constructor (with allocator)
Creates a copy of a Value by using the given Allocator
Template Parameters
SourceAllocator allocator of rhs
Parameters
rhs Value to copy from (read-only)
allocator Allocator for allocating copied elements and buffers. Commonly use GenericDocument::GetAllocator().
copyConstStrings Force copying of constant strings (e.g. referencing an in-situ buffer)
See also
CopyFrom()
Definition at line 742 of file document.h.
{
        switch (rhs.GetType()) {
        case kObjectType:
            DoCopyMembers(rhs, allocator, copyConstStrings);
            break;
        case kArrayType: {
                SizeType count = rhs.data_.a.size;
                GenericValue* le = reinterpret_cast<GenericValue*>(allocator.Malloc(count * sizeof(GenericValue)));
                const GenericValue<Encoding,SourceAllocator>* re = rhs.GetElementsPointer();
                for (SizeType i = 0; i < count; i++)
                    new (&le[i]) GenericValue(re[i], allocator, copyConstStrings);
                data_.f.flags = kArrayFlag;
                data_.a.size = data_.a.capacity = count;
                SetElementsPointer(le);
            }
            break;
        case kStringType:
            if (rhs.data_.f.flags == kConstStringFlag && !copyConstStrings) {
                data_.f.flags = rhs.data_.f.flags;
                data_  = *reinterpret_cast<const Data*>(&rhs.data_);
            }
            else
                SetStringRaw(StringRef(rhs.GetString(), rhs.GetStringLength()), allocator);
            break;
        default:
            data_.f.flags = rhs.data_.f.flags;
            data_  = *reinterpret_cast<const Data*>(&rhs.data_);
            break;
        }
    }
References rapidjson::GenericValue< Encoding, Allocator >::Data::a, rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::Data::f, rapidjson::GenericValue< Encoding, Allocator >::Flag::flags, rapidjson::GenericValue< Encoding, Allocator >::GetElementsPointer(), rapidjson::kArrayType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::GenericValue< Encoding, Allocator >::ArrayData::size, and rapidjson::StringRef().
GenericValue() [5/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename T > rapidjson::GenericValue< Encoding, Allocator >::GenericValue (T b, RAPIDJSON_ENABLEIF((internal::IsSame< bool, T >))) inline explicit
Constructor for boolean value.
Parameters
b Boolean value
Note
This constructor is limited to real boolean values and rejects implicitly converted types like arbitrary pointers. Use an explicit cast to bool, if you want to construct a boolean JSON value in such cases.
Definition at line 781 of file document.h.
        : data_() {
            // safe-guard against failing SFINAE
            RAPIDJSON_STATIC_ASSERT((internal::IsSame<bool,T>::Value));
            data_.f.flags = b ? kTrueFlag : kFalseFlag;
    }
References RAPIDJSON_STATIC_ASSERT.
GenericValue() [6/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (int i) inline explicit
Constructor for int value.
Definition at line 792 of file document.h.
                                                    : data_() {
        data_.n.i64 = i;
        data_.f.flags = (i >= 0) ? (kNumberIntFlag | kUintFlag | kUint64Flag) : kNumberIntFlag;
    }
GenericValue() [7/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (unsigned u) inline explicit
Constructor for unsigned value.
Definition at line 798 of file document.h.
                                                         : data_() {
        data_.n.u64 = u;
        data_.f.flags = (u & 0x80000000) ? kNumberUintFlag : (kNumberUintFlag | kIntFlag | kInt64Flag);
    }
GenericValue() [8/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (int64_t i64) inline explicit
Constructor for int64_t value.
Definition at line 804 of file document.h.
                                                          : data_() {
        data_.n.i64 = i64;
        data_.f.flags = kNumberInt64Flag;
        if (i64 >= 0) {
            data_.f.flags |= kNumberUint64Flag;
            if (!(static_cast<uint64_t>(i64) & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x00000000)))
                data_.f.flags |= kUintFlag;
            if (!(static_cast<uint64_t>(i64) & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
                data_.f.flags |= kIntFlag;
        }
        else if (i64 >= static_cast<int64_t>(RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
            data_.f.flags |= kIntFlag;
    }
References RAPIDJSON_UINT64_C2.
GenericValue() [9/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (uint64_t u64) inline explicit
Constructor for uint64_t value.
Definition at line 819 of file document.h.
                                                           : data_() {
        data_.n.u64 = u64;
        data_.f.flags = kNumberUint64Flag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0x80000000, 0x00000000)))
            data_.f.flags |= kInt64Flag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x00000000)))
            data_.f.flags |= kUintFlag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
            data_.f.flags |= kIntFlag;
    }
References RAPIDJSON_UINT64_C2.
GenericValue() [10/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (double d) inline explicit
Constructor for double value.
Definition at line 831 of file document.h.
: data_() { data_.n.d = d; data_.f.flags = kNumberDoubleFlag; }
GenericValue() [11/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (float f) inline explicit
Constructor for float value.
Definition at line 834 of file document.h.
: data_() { data_.n.d = static_cast<double>(f); data_.f.flags = kNumberDoubleFlag; }
GenericValue() [12/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length) inline
Constructor for constant string (i.e. do not make a copy of string)
Definition at line 837 of file document.h.
: data_() { SetStringRaw(StringRef(s, length)); }
References rapidjson::StringRef().
GenericValue() [13/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (StringRefType s) inline explicit
Constructor for constant string (i.e. do not make a copy of string)
Definition at line 840 of file document.h.
: data_() { SetStringRaw(s); }
GenericValue() [14/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
Definition at line 843 of file document.h.
: data_() { SetStringRaw(StringRef(s, length), allocator); }
References rapidjson::StringRef().
GenericValue() [15/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
Definition at line 846 of file document.h.
: data_() { SetStringRaw(StringRef(s), allocator); }
References rapidjson::StringRef().
GenericValue() [16/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (Array a) inline
Constructor for Array.
Parameters
a An array obtained by GetArray().
Note
Array is always pass-by-value.
the source array is moved into this value and the sourec array becomes empty.
Definition at line 861 of file document.h.
                                             : data_(a.value_.data_) {
        a.value_.data_ = Data();
        a.value_.data_.f.flags = kArrayFlag;
    }
References rapidjson::a.
GenericValue() [17/17]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::GenericValue (Object o) inline
Constructor for Object.
Parameters
o An object obtained by GetObject().
Note
Object is always pass-by-value.
the source object is moved into this value and the sourec object becomes empty.
Definition at line 872 of file document.h.
                                              : data_(o.value_.data_) {
        o.value_.data_ = Data();
        o.value_.data_.f.flags = kObjectFlag;
    }
~GenericValue()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> rapidjson::GenericValue< Encoding, Allocator >::~GenericValue () inline
Destructor.
Need to destruct elements of array, members of object, or copy-string.
Definition at line 880 of file document.h.
                    {
        // With RAPIDJSON_USE_MEMBERSMAP, the maps need to be destroyed to release
        // their Allocator if it's refcounted (e.g. MemoryPoolAllocator).
        if (Allocator::kNeedFree || (RAPIDJSON_USE_MEMBERSMAP+0 &&
                                     internal::IsRefCounted<Allocator>::Value)) {
            switch(data_.f.flags) {
            case kArrayFlag:
                {
                    GenericValue* e = GetElementsPointer();
                    for (GenericValue* v = e; v != e + data_.a.size; ++v)
                        v->~GenericValue();
                    if (Allocator::kNeedFree) { // Shortcut by Allocator's trait
                        Allocator::Free(e);
                    }
                }
                break;
            case kObjectFlag:
                DoFreeMembers();
                break;
            case kCopyStringFlag:
                if (Allocator::kNeedFree) { // Shortcut by Allocator's trait
                    Allocator::Free(const_cast<Ch*>(GetStringPointer()));
                }
                break;
            default:
                break;  // Do nothing for other types.
            }
        }
    }
References RAPIDJSON_USE_MEMBERSMAP, and rapidjson::GenericValue< Encoding, Allocator >::~GenericValue().
Member Function Documentation
DataString()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> static RAPIDJSON_FORCEINLINE const Ch * rapidjson::GenericValue< Encoding, Allocator >::DataString (const Data & data) inline static
Definition at line 2107 of file document.h.
{
        return (data.f.flags & kInlineStrFlag) ? data.ss.str : RAPIDJSON_GETPOINTER(Ch, data.s.str);
    }
References rapidjson::GenericValue< Encoding, Allocator >::Data::f, rapidjson::GenericValue< Encoding, Allocator >::Flag::flags, RAPIDJSON_GETPOINTER, rapidjson::GenericValue< Encoding, Allocator >::Data::s, rapidjson::GenericValue< Encoding, Allocator >::Data::ss, rapidjson::GenericValue< Encoding, Allocator >::String::str, and rapidjson::GenericValue< Encoding, Allocator >::ShortString::str.
DataStringLength()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> static RAPIDJSON_FORCEINLINE SizeType rapidjson::GenericValue< Encoding, Allocator >::DataStringLength (const Data & data) inline static
Definition at line 2110 of file document.h.
{
        return (data.f.flags & kInlineStrFlag) ? data.ss.GetLength() : data.s.length;
    }
References rapidjson::GenericValue< Encoding, Allocator >::Data::f, rapidjson::GenericValue< Encoding, Allocator >::Flag::flags, rapidjson::GenericValue< Encoding, Allocator >::ShortString::GetLength(), rapidjson::GenericValue< Encoding, Allocator >::String::length, rapidjson::GenericValue< Encoding, Allocator >::Data::s, and rapidjson::GenericValue< Encoding, Allocator >::Data::ss.
DoAddMember()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::DoAddMember (GenericValue< Encoding, Allocator > & name, GenericValue< Encoding, Allocator > & value, Allocator & allocator) inline
Definition at line 2304 of file document.h.
{
        ObjectData& o = data_.o;
        if (o.size >= o.capacity)
            DoReserveMembers(o.capacity ? (o.capacity + (o.capacity + 1) / 2) : kDefaultObjectCapacity, allocator);
        Member* members = GetMembersPointer();
        Member* m = members + o.size;
        m->name.RawAssign(name);
        m->value.RawAssign(value);
#if RAPIDJSON_USE_MEMBERSMAP
        Map* &map = GetMap(members);
        MapIterator* mit = GetMapIterators(map);
        new (&mit[o.size]) MapIterator(map->insert(MapPair(m->name.data_, o.size)));
#endif
        ++o.size;
    }
References rapidjson::GenericValue< Encoding, Allocator >::ObjectData::capacity, rapidjson::GenericValue< Encoding, Allocator >::ObjectData::size, and rapidjson::value.
DoAllocMembers()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE Member * rapidjson::GenericValue< Encoding, Allocator >::DoAllocMembers (SizeType capacity, Allocator & allocator) inline
Definition at line 2268 of file document.h.
{
        return Malloc<Member>(allocator, capacity);
    }
DoClearMembers()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::DoClearMembers () inline
Definition at line 2290 of file document.h.
{
        for (MemberIterator m = MemberBegin(); m != MemberEnd(); ++m)
            m->~Member();
        data_.o.size = 0;
    }
DoCopyMembers()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename SourceAllocator > void rapidjson::GenericValue< Encoding, Allocator >::DoCopyMembers (const GenericValue< Encoding, SourceAllocator > & rhs, Allocator & allocator, bool copyConstStrings) inline
Definition at line 2379 of file document.h.
{
        RAPIDJSON_ASSERT(rhs.GetType() == kObjectType);
        data_.f.flags = kObjectFlag;
        SizeType count = rhs.data_.o.size;
        Member* lm = DoAllocMembers(count, allocator);
        const typename GenericValue<Encoding,SourceAllocator>::Member* rm = rhs.GetMembersPointer();
#if RAPIDJSON_USE_MEMBERSMAP
        Map* &map = GetMap(lm);
        MapIterator* mit = GetMapIterators(map);
#endif
        for (SizeType i = 0; i < count; i++) {
            new (&lm[i].name) GenericValue(rm[i].name, allocator, copyConstStrings);
            new (&lm[i].value) GenericValue(rm[i].value, allocator, copyConstStrings);
#if RAPIDJSON_USE_MEMBERSMAP
            new (&mit[i]) MapIterator(map->insert(MapPair(lm[i].name.data_, i)));
#endif
        }
        data_.o.size = data_.o.capacity = count;
        SetMembersPointer(lm);
    }
References rapidjson::GenericValue< Encoding, Allocator >::data_, rapidjson::GenericValue< Encoding, Allocator >::GetMembersPointer(), rapidjson::kObjectType, rapidjson::GenericValue< Encoding, Allocator >::Data::o, RAPIDJSON_ASSERT, rapidjson::GenericValue< Encoding, Allocator >::ObjectData::size, and rapidjson::value.
DoEraseMembers()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> MemberIterator rapidjson::GenericValue< Encoding, Allocator >::DoEraseMembers (ConstMemberIterator first, ConstMemberIterator last) inline
Definition at line 2344 of file document.h.
{
        ObjectData& o = data_.o;
        MemberIterator beg = MemberBegin(),
                       pos = beg + (first - beg),
                       end = MemberEnd();
#if RAPIDJSON_USE_MEMBERSMAP
        Map* &map = GetMap(GetMembersPointer());
        MapIterator* mit = GetMapIterators(map);
#endif
        for (MemberIterator itr = pos; itr != last; ++itr) {
#if RAPIDJSON_USE_MEMBERSMAP
            map->erase(DropMapIterator(mit[itr - beg]));
#endif
            itr->~Member();
        }
#if RAPIDJSON_USE_MEMBERSMAP
        if (first != last) {
            // Move remaining members/iterators
            MemberIterator next = pos + (last - first);
            for (MemberIterator itr = pos; next != end; ++itr, ++next) {
                std::memcpy(static_cast<void*>(&*itr), &*next, sizeof(Member));
                SizeType mpos = static_cast<SizeType>(itr - beg);
                new (&mit[mpos]) MapIterator(DropMapIterator(mit[next - beg]));
                mit[mpos]->second = mpos;
            }
        }
#else
        std::memmove(static_cast<void*>(&*pos), &*last,
                     static_cast<size_t>(end - last) * sizeof(Member));
#endif
        o.size -= static_cast<SizeType>(last - first);
        return pos;
    }
References rapidjson::GenericValue< Encoding, Allocator >::ObjectData::size.
DoFindMember()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename SourceAllocator > MemberIterator rapidjson::GenericValue< Encoding, Allocator >::DoFindMember (const GenericValue< Encoding, SourceAllocator > & name) inline
Definition at line 2282 of file document.h.
{
        MemberIterator member = MemberBegin();
        for ( ; member != MemberEnd(); ++member)
            if (name.StringEqual(member->name))
                break;
        return member;
    }
References rapidjson::GenericValue< Encoding, Allocator >::StringEqual().
DoFreeMembers()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::DoFreeMembers () inline
Definition at line 2296 of file document.h.
{
        for (MemberIterator m = MemberBegin(); m != MemberEnd(); ++m)
            m->~Member();
        Allocator::Free(GetMembersPointer());
    }
DoRemoveMember()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> MemberIterator rapidjson::GenericValue< Encoding, Allocator >::DoRemoveMember (MemberIterator m) inline
Definition at line 2320 of file document.h.
{
        ObjectData& o = data_.o;
        Member* members = GetMembersPointer();
#if RAPIDJSON_USE_MEMBERSMAP
        Map* &map = GetMap(members);
        MapIterator* mit = GetMapIterators(map);
        SizeType mpos = static_cast<SizeType>(&*m - members);
        map->erase(DropMapIterator(mit[mpos]));
#endif
        MemberIterator last(members + (o.size - 1));
        if (o.size > 1 && m != last) {
#if RAPIDJSON_USE_MEMBERSMAP
            new (&mit[mpos]) MapIterator(DropMapIterator(mit[&*last - members]));
            mit[mpos]->second = mpos;
#endif
            *m = *last; // Move the last one to this place
        }
        else {
            m->~Member(); // Only one left, just destroy
        }
        --o.size;
        return m;
    }
References rapidjson::GenericValue< Encoding, Allocator >::ObjectData::size.
DoReserveMembers()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::DoReserveMembers (SizeType newCapacity, Allocator & allocator) inline
Definition at line 2272 of file document.h.
{
        ObjectData& o = data_.o;
        if (newCapacity > o.capacity) {
            Member* newMembers = Realloc<Member>(allocator, GetMembersPointer(), o.capacity, newCapacity);
            RAPIDJSON_SETPOINTER(Member, o.members, newMembers);
            o.capacity = newCapacity;
        }
    }
References rapidjson::GenericValue< Encoding, Allocator >::ObjectData::capacity, rapidjson::GenericValue< Encoding, Allocator >::ObjectData::members, and RAPIDJSON_SETPOINTER.
GetElementsPointer()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE GenericValue * rapidjson::GenericValue< Encoding, Allocator >::GetElementsPointer () const inline
Definition at line 2116 of file document.h.
{ return RAPIDJSON_GETPOINTER(GenericValue, data_.a.elements); }
References RAPIDJSON_GETPOINTER.
GetMembersPointer()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE Member * rapidjson::GenericValue< Encoding, Allocator >::GetMembersPointer () const inline
Definition at line 2118 of file document.h.
{ return RAPIDJSON_GETPOINTER(Member, data_.o.members); }
References RAPIDJSON_GETPOINTER.
GetStringPointer()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE const Ch * rapidjson::GenericValue< Encoding, Allocator >::GetStringPointer () const inline
Definition at line 2114 of file document.h.
{ return RAPIDJSON_GETPOINTER(Ch, data_.s.str); }
References RAPIDJSON_GETPOINTER.
operator=() [1/2]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> GenericValue & rapidjson::GenericValue< Encoding, Allocator >::operator= (GenericValue< Encoding, Allocator > & rhs) inline
Assignment with move semantics.
Parameters
rhs Source of the assignment. It will become a null value after assignment.
Definition at line 921 of file document.h.
{
        if (RAPIDJSON_LIKELY(this != &rhs)) {
            // Can't destroy "this" before assigning "rhs", otherwise "rhs"
            // could be used after free if it's an sub-Value of "this",
            // hence the temporary danse.
            GenericValue temp;
            temp.RawAssign(rhs);
            this->~GenericValue();
            RawAssign(temp);
        }
        return *this;
    }
References RAPIDJSON_LIKELY, and rapidjson::GenericValue< Encoding, Allocator >::RawAssign().
operator=() [2/2]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> GenericValue & rapidjson::GenericValue< Encoding, Allocator >::operator= (StringRefType str) inline
Assignment of constant string reference (no copy)
Parameters
str Constant string reference to be assigned
Note
This overload is needed to avoid clashes with the generic primitive type assignment overload below.
See also
GenericStringRef, operator=(T)
Definition at line 946 of file document.h.
{
        GenericValue s(str);
        return *this = s;
    }
RAPIDJSON_DISABLEIF_RETURN()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename T > rapidjson::GenericValue< Encoding, Allocator >::RAPIDJSON_DISABLEIF_RETURN ((internal::IsPointer< T >) , (GenericValue< Encoding, Allocator > &))
Assignment with primitive types.
Template Parameters
T Either Type, int, unsigned, int64_t, uint64_t
Parameters
value The value to be assigned.
Note
The source type T explicitly disallows all pointer types, especially (const) Ch*. This helps avoiding implicitly referencing character strings with insufficient lifetime, use SetString(const Ch*, Allocator&) (for copying) or StringRef() (to explicitly mark the pointer as constant) instead. All other pointer types would implicitly convert to bool, use SetBool() instead. Set boolean value
References rapidjson::value.
RawAssign()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::RawAssign (GenericValue< Encoding, Allocator > & rhs) inline
Assignment without calling destructor.
Definition at line 2459 of file document.h.
{
        data_ = rhs.data_;
        // data_.f.flags = rhs.data_.f.flags;
        rhs.data_.f.flags = kNullFlag;
    }
SetArrayRaw()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::SetArrayRaw (GenericValue< Encoding, Allocator > * values, SizeType count, Allocator & allocator) inline
Definition at line 2402 of file document.h.
{
        data_.f.flags = kArrayFlag;
        if (count) {
            GenericValue* e = static_cast<GenericValue*>(allocator.Malloc(count * sizeof(GenericValue)));
            SetElementsPointer(e);
            std::memcpy(static_cast<void*>(e), values, count * sizeof(GenericValue));
        }
        else
            SetElementsPointer(0);
        data_.a.size = data_.a.capacity = count;
    }
SetElementsPointer()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE GenericValue * rapidjson::GenericValue< Encoding, Allocator >::SetElementsPointer (GenericValue< Encoding, Allocator > * elements) inline
Definition at line 2117 of file document.h.
{ return RAPIDJSON_SETPOINTER(GenericValue, data_.a.elements, elements); }
References RAPIDJSON_SETPOINTER.
SetMembersPointer()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE Member * rapidjson::GenericValue< Encoding, Allocator >::SetMembersPointer (Member * members) inline
Definition at line 2119 of file document.h.
{ return RAPIDJSON_SETPOINTER(Member, data_.o.members, members); }
References RAPIDJSON_SETPOINTER.
SetObjectRaw()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::SetObjectRaw (Member * members, SizeType count, Allocator & allocator) inline
Initialize this value as object with initial data, without calling destructor.
Definition at line 2415 of file document.h.
{
        data_.f.flags = kObjectFlag;
        if (count) {
            Member* m = DoAllocMembers(count, allocator);
            SetMembersPointer(m);
            std::memcpy(static_cast<void*>(m), members, count * sizeof(Member));
#if RAPIDJSON_USE_MEMBERSMAP
            Map* &map = GetMap(m);
            MapIterator* mit = GetMapIterators(map);
            for (SizeType i = 0; i < count; i++) {
                new (&mit[i]) MapIterator(map->insert(MapPair(m[i].name.data_, i)));
            }
#endif
        }
        else
            SetMembersPointer(0);
        data_.o.size = data_.o.capacity = count;
    }
SetStringPointer()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> RAPIDJSON_FORCEINLINE const Ch * rapidjson::GenericValue< Encoding, Allocator >::SetStringPointer (const Ch * str) inline
Definition at line 2115 of file document.h.
{ return RAPIDJSON_SETPOINTER(Ch, data_.s.str, str); }
References RAPIDJSON_SETPOINTER.
SetStringRaw() [1/2]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw (StringRefType s) inline
Initialize this value as constant string, without calling destructor.
Definition at line 2435 of file document.h.
{
        data_.f.flags = kConstStringFlag;
        SetStringPointer(s);
        data_.s.length = s.length;
    }
SetStringRaw() [2/2]
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> void rapidjson::GenericValue< Encoding, Allocator >::SetStringRaw (StringRefType s, Allocator & allocator) inline
Initialize this value as copy string with initial data, without calling destructor.
Definition at line 2442 of file document.h.
{
        Ch* str = 0;
        if (ShortString::Usable(s.length)) {
            data_.f.flags = kShortStringFlag;
            data_.ss.SetLength(s.length);
            str = data_.ss.str;
        } else {
            data_.f.flags = kCopyStringFlag;
            data_.s.length = s.length;
            str = static_cast<Ch *>(allocator.Malloc((s.length + 1) * sizeof(Ch)));
            SetStringPointer(str);
        }
        std::memcpy(str, s, s.length * sizeof(Ch));
        str[s.length] = '\0';
    }
References rapidjson::GenericStringRef< CharType >::length.
StringEqual()
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename SourceAllocator > bool rapidjson::GenericValue< Encoding, Allocator >::StringEqual (const GenericValue< Encoding, SourceAllocator > & rhs) const inline
Definition at line 2466 of file document.h.
{
        RAPIDJSON_ASSERT(IsString());
        RAPIDJSON_ASSERT(rhs.IsString());
        const SizeType len1 = GetStringLength();
        const SizeType len2 = rhs.GetStringLength();
        if(len1 != len2) { return false; }
        const Ch* const str1 = GetString();
        const Ch* const str2 = rhs.GetString();
        if(str1 == str2) { return true; } // fast path for constant string
        return (std::memcmp(str1, str2, sizeof(Ch) * len1) == 0);
    }
References GetString(), and RAPIDJSON_ASSERT.
Friends And Related Symbol Documentation
GenericDocument
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> template<typename , typename , typename > friend class GenericDocument friend
Definition at line 1989 of file document.h.
Member Data Documentation
data_
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> Data rapidjson::GenericValue< Encoding, Allocator >::data_
Definition at line 2481 of file document.h.
kDefaultArrayCapacity
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> const SizeType rapidjson::GenericValue< Encoding, Allocator >::kDefaultArrayCapacity = 16 static
Definition at line 2023 of file document.h.
kDefaultObjectCapacity
template<typename Encoding , typename Allocator = :: rapidjson ::MemoryPoolAllocator<:: rapidjson ::CrtAllocator>> const SizeType rapidjson::GenericValue< Encoding, Allocator >::kDefaultObjectCapacity = 16 static
Definition at line 2024 of file document.h.
The documentation for this class was generated from the following file:
rapidjson/include/rapidjson/document.h