wiNpoS: TestGenerationTest Class Reference
TestGenerationTest Class Reference
Public Types
enum { PARAMETER_COUNT }
typedef TestGenerationEnvironment< PARAMETER_COUNT > Environment
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Types inherited from testing::WithParamInterface< T >
typedef T ParamType
Public Member Functions
TestGenerationTest ()
virtual void SetUp ()
virtual void TearDown ()
Public Member Functions inherited from testing::Test
virtual ~Test ()
Public Member Functions inherited from testing::WithParamInterface< T >
virtual ~WithParamInterface ()
const ParamType & GetParam () const
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Attributes
int current_parameter_
Static Protected Attributes
static vector< int > collected_parameters_
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestGenerationTest)
Additional Inherited Members
Protected Member Functions inherited from testing::Test
Test ()
Detailed Description
Definition at line 663 of file gtest-param-test_test.cc.
Member Typedef Documentation
Environment
typedef TestGenerationEnvironment<PARAMETER_COUNT> TestGenerationTest::Environment
Definition at line 670 of file gtest-param-test_test.cc.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PARAMETER_COUNT
Definition at line 665 of file gtest-param-test_test.cc.
       {
    PARAMETER_COUNT =
        sizeof(test_generation_params)/sizeof(test_generation_params[0])
  };
Constructor & Destructor Documentation
TestGenerationTest()
TestGenerationTest::TestGenerationTest () inline
Definition at line 672 of file gtest-param-test_test.cc.
                       {
    Environment::Instance()->FixtureConstructorExecuted();
    current_parameter_ = GetParam();
  }
References current_parameter_, TestGenerationEnvironment< kExpectedCalls >::FixtureConstructorExecuted(), testing::WithParamInterface< T >::GetParam(), and TestGenerationEnvironment< kExpectedCalls >::Instance().
Member Function Documentation
GTEST_DISALLOW_COPY_AND_ASSIGN_()
TestGenerationTest::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestGenerationTest) private
SetUp()
virtual void TestGenerationTest::SetUp () inline virtual
Reimplemented from testing::Test.
Definition at line 676 of file gtest-param-test_test.cc.
                       {
    Environment::Instance()->SetUpExecuted();
    EXPECT_EQ(current_parameter_, GetParam());
  }
References current_parameter_, EXPECT_EQ, testing::WithParamInterface< T >::GetParam(), TestGenerationEnvironment< kExpectedCalls >::Instance(), and TestGenerationEnvironment< kExpectedCalls >::SetUpExecuted().
SetUpTestCase()
static void TestGenerationTest::SetUpTestCase () inline static
Definition at line 685 of file gtest-param-test_test.cc.
{
    bool all_tests_in_test_case_selected = true;
    for (int i = 0; i < PARAMETER_COUNT; ++i) {
      Message test_name;
      test_name << "TestsExpandedAndRun/" << i;
      if ( !UnitTestOptions::FilterMatchesTest(
                "TestExpansionModule/MultipleTestGenerationTest",
                test_name.GetString())) {
        all_tests_in_test_case_selected = false;
      }
    }
    EXPECT_TRUE(all_tests_in_test_case_selected)
        << "When running the TestGenerationTest test case all of its tests\n"
        << "must be selected by the filter flag for the test case to pass.\n"
        << "If not all of them are enabled, we can't reliably conclude\n"
        << "that the correct number of tests have been generated.";
    collected_parameters_.clear();
  }
References collected_parameters_, EXPECT_TRUE, and PARAMETER_COUNT.
TearDown()
virtual void TestGenerationTest::TearDown () inline virtual
Reimplemented from testing::Test.
Definition at line 680 of file gtest-param-test_test.cc.
{
    Environment::Instance()->TearDownExecuted();
    EXPECT_EQ(current_parameter_, GetParam());
  }
References current_parameter_, EXPECT_EQ, testing::WithParamInterface< T >::GetParam(), TestGenerationEnvironment< kExpectedCalls >::Instance(), and TestGenerationEnvironment< kExpectedCalls >::TearDownExecuted().
TearDownTestCase()
static void TestGenerationTest::TearDownTestCase () inline static
Definition at line 706 of file gtest-param-test_test.cc.
{
    vector<int> expected_values(test_generation_params,
                                test_generation_params + PARAMETER_COUNT);
    // Test execution order is not guaranteed by Google Test,
    // so the order of values in collected_parameters_ can be
    // different and we have to sort to compare.
    sort(expected_values.begin(), expected_values.end());
    sort(collected_parameters_.begin(), collected_parameters_.end());
    EXPECT_TRUE(collected_parameters_ == expected_values);
  }
References collected_parameters_, EXPECT_TRUE, PARAMETER_COUNT, and test_generation_params.
Member Data Documentation
collected_parameters_
vector< int > TestGenerationTest::collected_parameters_ static protected
Definition at line 720 of file gtest-param-test_test.cc.
current_parameter_
int TestGenerationTest::current_parameter_ protected
Definition at line 719 of file gtest-param-test_test.cc.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest-param-test_test.cc