wiNpoS: testing::internal::PairMatcherImpl< PairType > Class Template Reference
testing::internal::PairMatcherImpl< PairType > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef RawPairType::first_type FirstType
typedef RawPairType::second_type SecondType
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename FirstMatcher , typename SecondMatcher >
PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (PairType a_pair, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
void ExplainSuccess (const std::string &first_explanation, const std::string &second_explanation, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl)
Private Attributes
const Matcher< const FirstType & > first_matcher_
const Matcher< const SecondType & > second_matcher_
Detailed Description
template<typename PairType>
class testing::internal::PairMatcherImpl< PairType >
Definition at line 3353 of file gmock-matchers.h.
Member Typedef Documentation
FirstType
template<typename PairType > typedef RawPairType::first_type testing::internal::PairMatcherImpl< PairType >::FirstType
Definition at line 3356 of file gmock-matchers.h.
SecondType
template<typename PairType > typedef RawPairType::second_type testing::internal::PairMatcherImpl< PairType >::SecondType
Definition at line 3357 of file gmock-matchers.h.
Constructor & Destructor Documentation
PairMatcherImpl()
template<typename PairType > template<typename FirstMatcher , typename SecondMatcher > testing::internal::PairMatcherImpl< PairType >::PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3360 of file gmock-matchers.h.
      : first_matcher_(
            testing::SafeMatcherCast<const FirstType&>(first_matcher)),
        second_matcher_(
            testing::SafeMatcherCast<const SecondType&>(second_matcher)) {
  }
Member Function Documentation
DescribeNegationTo()
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3376 of file gmock-matchers.h.
{
    *os << "has a first field that ";
    first_matcher_.DescribeNegationTo(os);
    *os << ", or has a second field that ";
    second_matcher_.DescribeNegationTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), testing::internal::PairMatcherImpl< PairType >::first_matcher_, and testing::internal::PairMatcherImpl< PairType >::second_matcher_.
DescribeTo()
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3368 of file gmock-matchers.h.
{
    *os << "has a first field that ";
    first_matcher_.DescribeTo(os);
    *os << ", and has a second field that ";
    second_matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), testing::internal::PairMatcherImpl< PairType >::first_matcher_, and testing::internal::PairMatcherImpl< PairType >::second_matcher_.
ExplainSuccess()
template<typename PairType > void testing::internal::PairMatcherImpl< PairType >::ExplainSuccess (const std::string & first_explanation, const std::string & second_explanation, MatchResultListener * listener) const inline private
Definition at line 3413 of file gmock-matchers.h.
{
    *listener << "whose both fields match";
    if (first_explanation != "") {
      *listener << ", where the first field is a value " << first_explanation;
    }
    if (second_explanation != "") {
      *listener << ", ";
      if (first_explanation != "") {
        *listener << "and ";
      } else {
        *listener << "where ";
      }
      *listener << "the second field is a value " << second_explanation;
    }
  }
GTEST_DISALLOW_ASSIGN_()
template<typename PairType > testing::internal::PairMatcherImpl< PairType >::GTEST_DISALLOW_ASSIGN_ (PairMatcherImpl< PairType >) private
GTEST_REMOVE_REFERENCE_AND_CONST_()
template<typename PairType > typedef testing::internal::PairMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
MatchAndExplain()
template<typename PairType > virtual bool testing::internal::PairMatcherImpl< PairType >::MatchAndExplain (PairType a_pair, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 3385 of file gmock-matchers.h.
{
    if (!listener->IsInterested()) {
      // If the listener is not interested, we don't need to construct the
      // explanation.
      return first_matcher_.Matches(pair_getters::First(a_pair, Rank0())) &&
             second_matcher_.Matches(pair_getters::Second(a_pair, Rank0()));
    }
    StringMatchResultListener first_inner_listener;
    if (!first_matcher_.MatchAndExplain(pair_getters::First(a_pair, Rank0()),
                                        &first_inner_listener)) {
      *listener << "whose first field does not match";
      PrintIfNotEmpty(first_inner_listener.str(), listener->stream());
      return false;
    }
    StringMatchResultListener second_inner_listener;
    if (!second_matcher_.MatchAndExplain(pair_getters::Second(a_pair, Rank0()),
                                         &second_inner_listener)) {
      *listener << "whose second field does not match";
      PrintIfNotEmpty(second_inner_listener.str(), listener->stream());
      return false;
    }
    ExplainSuccess(first_inner_listener.str(), second_inner_listener.str(),
                   listener);
    return true;
  }
References testing::internal::PairMatcherImpl< PairType >::ExplainSuccess(), testing::internal::pair_getters::First(), testing::internal::PairMatcherImpl< PairType >::first_matcher_, testing::MatchResultListener::IsInterested(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), testing::internal::PrintIfNotEmpty(), testing::internal::pair_getters::Second(), testing::internal::PairMatcherImpl< PairType >::second_matcher_, testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
Member Data Documentation
first_matcher_
template<typename PairType > const Matcher<const FirstType&> testing::internal::PairMatcherImpl< PairType >::first_matcher_ private
Definition at line 3431 of file gmock-matchers.h.
second_matcher_
template<typename PairType > const Matcher<const SecondType&> testing::internal::PairMatcherImpl< PairType >::second_matcher_ private
Definition at line 3432 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h