wiNpoS: testing::internal::MatchesRegexMatcher Class Reference
testing::internal::MatchesRegexMatcher Class Reference
#include <gmock-matchers.h>
Public Member Functions
MatchesRegexMatcher (const RE *regex, bool full_match)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<class MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher)
Private Attributes
const internal::linked_ptr< const RE > regex_
const bool full_match_
Detailed Description
Definition at line 1547 of file gmock-matchers.h.
Constructor & Destructor Documentation
MatchesRegexMatcher()
testing::internal::MatchesRegexMatcher::MatchesRegexMatcher (const RE * regex, bool full_match) inline
Definition at line 1549 of file gmock-matchers.h.
      : regex_(regex), full_match_(full_match) {}
Member Function Documentation
DescribeNegationTo()
void testing::internal::MatchesRegexMatcher::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 1587 of file gmock-matchers.h.
{
    *os << "doesn't " << (full_match_ ? "match" : "contain")
        << " regular expression ";
    UniversalPrinter<std::string>::Print(regex_->pattern(), os);
  }
References full_match_, testing::internal::UniversalPrinter< T >::Print(), and regex_.
DescribeTo()
void testing::internal::MatchesRegexMatcher::DescribeTo (::std::ostream * os) const inline
Definition at line 1581 of file gmock-matchers.h.
{
    *os << (full_match_ ? "matches" : "contains")
        << " regular expression ";
    UniversalPrinter<std::string>::Print(regex_->pattern(), os);
  }
References full_match_, testing::internal::UniversalPrinter< T >::Print(), and regex_.
GTEST_DISALLOW_ASSIGN_()
testing::internal::MatchesRegexMatcher::GTEST_DISALLOW_ASSIGN_ (MatchesRegexMatcher) private
MatchAndExplain() [1/2]
template<typename CharType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
Definition at line 1565 of file gmock-matchers.h.
{
    return s != NULL && MatchAndExplain(std::string(s), listener);
  }
References MatchAndExplain().
MatchAndExplain() [2/2]
template<class MatcheeStringType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
Definition at line 1574 of file gmock-matchers.h.
{
    const std::string& s2(s);
    return full_match_ ? RE::FullMatch(s2, *regex_) :
        RE::PartialMatch(s2, *regex_);
  }
References full_match_, testing::internal::RE::FullMatch(), testing::internal::RE::PartialMatch(), and regex_.
Member Data Documentation
full_match_
const bool testing::internal::MatchesRegexMatcher::full_match_ private
Definition at line 1595 of file gmock-matchers.h.
regex_
const internal::linked_ptr<const RE> testing::internal::MatchesRegexMatcher::regex_ private
Definition at line 1594 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h