wiNpoS: testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container > Class Template Reference
testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef ContainerView::type::size_type SizeType
Public Member Functions
Impl (const SizeMatcher &size_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
const Matcher< SizeType > size_matcher_
Detailed Description
template<typename SizeMatcher>
template<typename Container>
class testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >
Definition at line 2706 of file gmock-matchers.h.
Member Typedef Documentation
ContainerView
template<typename SizeMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::ContainerView
Definition at line 2709 of file gmock-matchers.h.
SizeType
template<typename SizeMatcher > template<typename Container > typedef ContainerView::type::size_type testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::SizeType
Definition at line 2710 of file gmock-matchers.h.
Constructor & Destructor Documentation
Impl()
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::Impl (const SizeMatcher & size_matcher) inline explicit
Definition at line 2711 of file gmock-matchers.h.
        : size_matcher_(MatcherCast<SizeType>(size_matcher)) {}
References testing::MatcherCast().
Member Function Documentation
DescribeNegationTo()
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2718 of file gmock-matchers.h.
{
      *os << "size ";
      size_matcher_.DescribeNegationTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), and testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::size_matcher_.
DescribeTo()
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2714 of file gmock-matchers.h.
{
      *os << "size ";
      size_matcher_.DescribeTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::size_matcher_.
GTEST_DISALLOW_ASSIGN_()
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::GTEST_DISALLOW_ASSIGN_ (Impl< Container >) private
MatchAndExplain()
template<typename SizeMatcher > template<typename Container > virtual bool testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 2723 of file gmock-matchers.h.
{
      SizeType size = container.size();
      StringMatchResultListener size_listener;
      const bool result = size_matcher_.MatchAndExplain(size, &size_listener);
      *listener
          << "whose size " << size << (result ? " matches" : " doesn't match");
      PrintIfNotEmpty(size_listener.str(), listener->stream());
      return result;
    }
References testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::PrintIfNotEmpty(), testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::size_matcher_, testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
Member Data Documentation
size_matcher_
template<typename SizeMatcher > template<typename Container > const Matcher<SizeType> testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::size_matcher_ private
Definition at line 2735 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h