wiNpoS: anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3 Class Reference
anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3 Class Reference
Protected Member Functions
virtual void SetUp ()
void MapTester (const Queue< int > *q)
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Static Protected Member Functions
static int Double (int n)
Protected Attributes
Queue< int > q0_
Queue< int > q1_
Queue< int > q2_
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 70 of file sample3_unittest.cc.
Member Function Documentation
Double()
static int anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3::Double (int n) inline static protected
Definition at line 91 of file sample3_unittest.cc.
{
    return 2*n;
  }
MapTester()
void anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3::MapTester (const Queue< int > * q) inline protected
Definition at line 96 of file sample3_unittest.cc.
{
    // Creates a new queue, where each element is twice as big as the
    // corresponding one in q.
    const Queue<int> * const new_q = q->Map(Double);
    // Verifies that the new queue has the same size as q.
    ASSERT_EQ(q->Size(), new_q->Size());
    // Verifies the relationship between the elements of the two queues.
    for ( const QueueNode<int> * n1 = q->Head(), * n2 = new_q->Head();
          n1 != NULL; n1 = n1->next(), n2 = n2->next() ) {
      EXPECT_EQ(2 * n1->element(), n2->element());
    }
    delete new_q;
  }
References ASSERT_EQ, EXPECT_EQ, Queue< E >::Head(), Queue< E >::Map(), and Queue< E >::Size().
SetUp()
virtual void anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 77 of file sample3_unittest.cc.
                       {
    q1_.Enqueue(1);
    q2_.Enqueue(2);
    q2_.Enqueue(3);
  }
Member Data Documentation
q0_
Queue<int> anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3::q0_ protected
Definition at line 114 of file sample3_unittest.cc.
q1_
Queue<int> anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3::q1_ protected
Definition at line 115 of file sample3_unittest.cc.
q2_
Queue<int> anonymous_namespace{sample3_unittest.cc}::QueueTestSmpl3::q2_ protected
Definition at line 116 of file sample3_unittest.cc.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/samples/sample3_unittest.cc