wiNpoS: testing::internal::variant_matcher::VariantMatcher< T > Class Template Reference
testing::internal::variant_matcher::VariantMatcher< T > Class Template Reference
Public Member Functions
VariantMatcher (::testing::Matcher< const T & > matcher)
template<typename Variant >
bool MatchAndExplain (const Variant &value, ::testing::MatchResultListener *listener) const
void DescribeTo (std::ostream *os) const
void DescribeNegationTo (std::ostream *os) const
Static Private Member Functions
static std::string GetTypeName ()
Private Attributes
const ::testing::Matcher< const T & > matcher_
Detailed Description
template<typename T>
class testing::internal::variant_matcher::VariantMatcher< T >
Definition at line 4063 of file gmock-matchers.h.
Constructor & Destructor Documentation
VariantMatcher()
template<typename T > testing::internal::variant_matcher::VariantMatcher< T >::VariantMatcher (::testing::Matcher< const T & > matcher) inline explicit
Definition at line 4065 of file gmock-matchers.h.
      : matcher_(internal::move(matcher)) {}
Member Function Documentation
DescribeNegationTo()
template<typename T > void testing::internal::variant_matcher::VariantMatcher< T >::DescribeNegationTo (std::ostream * os) const inline
Definition at line 4095 of file gmock-matchers.h.
{
    *os << "is a variant<> with value of type other than '" << GetTypeName()
        << "' or the value ";
    matcher_.DescribeNegationTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), testing::internal::variant_matcher::VariantMatcher< T >::GetTypeName(), and testing::internal::variant_matcher::VariantMatcher< T >::matcher_.
DescribeTo()
template<typename T > void testing::internal::variant_matcher::VariantMatcher< T >::DescribeTo (std::ostream * os) const inline
Definition at line 4089 of file gmock-matchers.h.
{
    *os << "is a variant<> with value of type '" << GetTypeName()
        << "' and the value ";
    matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), testing::internal::variant_matcher::VariantMatcher< T >::GetTypeName(), and testing::internal::variant_matcher::VariantMatcher< T >::matcher_.
GetTypeName()
template<typename T > static std::string testing::internal::variant_matcher::VariantMatcher< T >::GetTypeName () inline static private
Definition at line 4102 of file gmock-matchers.h.
{
#if GTEST_HAS_RTTI
    GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(
        return internal::GetTypeName<T>());
#endif
    return "the element type";
  }
References GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_.
MatchAndExplain()
template<typename T > template<typename Variant > bool testing::internal::variant_matcher::VariantMatcher< T >::MatchAndExplain (const Variant & value, ::testing::MatchResultListener * listener) const inline
Definition at line 4069 of file gmock-matchers.h.
{
    if (!listener->IsInterested()) {
      return holds_alternative<T>(value) && matcher_.Matches(get<T>(value));
    }
    if (!holds_alternative<T>(value)) {
      *listener << "whose value is not of type '" << GetTypeName() << "'";
      return false;
    }
    const T& elem = get<T>(value);
    StringMatchResultListener elem_listener;
    const bool match = matcher_.MatchAndExplain(elem, &elem_listener);
    *listener << "whose value " << PrintToString(elem)
              << (match ? " matches" : " doesn't match");
    PrintIfNotEmpty(elem_listener.str(), listener->stream());
    return match;
  }
References testing::internal::variant_matcher::VariantMatcher< T >::GetTypeName(), testing::MatchResultListener::IsInterested(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::variant_matcher::VariantMatcher< T >::matcher_, testing::internal::MatcherBase< T >::Matches(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and T.
Member Data Documentation
matcher_
template<typename T > const ::testing::Matcher<const T&> testing::internal::variant_matcher::VariantMatcher< T >::matcher_ private
Definition at line 4110 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h