wiNpoS: testing::internal::UnitTestHelper Class Reference
testing::internal::UnitTestHelper Class Reference
Static Public Member Functions
static TestCase const ** GetSortedTestCases ()
static const TestCase * FindTestCase (const char *name)
static TestInfo const ** GetSortedTests (const TestCase *test_case)
Detailed Description
Definition at line 53 of file gtest-unittest-api_test.cc.
Member Function Documentation
FindTestCase()
static const TestCase * testing::internal::UnitTestHelper::FindTestCase (const char * name) inline static
Definition at line 73 of file gtest-unittest-api_test.cc.
{
    UnitTest& unit_test = *UnitTest::GetInstance();
    for (int i = 0; i < unit_test.total_test_case_count(); ++i) {
      const TestCase* test_case = unit_test.GetTestCase(i);
      if (0 == strcmp(test_case->name(), name))
        return test_case;
    }
    return NULL;
  }
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), testing::TestCase::name(), and testing::UnitTest::total_test_case_count().
GetSortedTestCases()
static TestCase const ** testing::internal::UnitTestHelper::GetSortedTestCases () inline static
Definition at line 57 of file gtest-unittest-api_test.cc.
{
    UnitTest& unit_test = *UnitTest::GetInstance();
    TestCase const** const test_cases =
        new const TestCase*[unit_test.total_test_case_count()];
    for (int i = 0; i < unit_test.total_test_case_count(); ++i)
      test_cases[i] = unit_test.GetTestCase(i);
    std::sort(test_cases,
              test_cases + unit_test.total_test_case_count(),
              LessByName<TestCase>());
    return test_cases;
  }
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), and testing::UnitTest::total_test_case_count().
GetSortedTests()
static TestInfo const ** testing::internal::UnitTestHelper::GetSortedTests (const TestCase * test_case) inline static
Definition at line 86 of file gtest-unittest-api_test.cc.
{
    TestInfo const** const tests =
        new const TestInfo*[test_case->total_test_count()];
    for (int i = 0; i < test_case->total_test_count(); ++i)
      tests[i] = test_case->GetTestInfo(i);
    std::sort(tests, tests + test_case->total_test_count(),
              LessByName<TestInfo>());
    return tests;
  }
References testing::TestCase::GetTestInfo(), and testing::TestCase::total_test_count().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest-unittest-api_test.cc