wiNpoS: testing::internal::ContainsMatcherImpl< Container > Class Template Reference
testing::internal::ContainsMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
template<typename InnerMatcher >
ContainsMatcherImpl (InnerMatcher inner_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::internal::QuantifierMatcherImpl< Container >
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (ContainsMatcherImpl)
Additional Inherited Members
Public Types inherited from testing::internal::QuantifierMatcherImpl< Container >
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
Protected Member Functions inherited from testing::internal::QuantifierMatcherImpl< Container >
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
Protected Attributes inherited from testing::internal::QuantifierMatcherImpl< Container >
const Matcher< const Element & > inner_matcher_
Detailed Description
template<typename Container>
class testing::internal::ContainsMatcherImpl< Container >
Definition at line 3153 of file gmock-matchers.h.
Constructor & Destructor Documentation
ContainsMatcherImpl()
template<typename Container > template<typename InnerMatcher > testing::internal::ContainsMatcherImpl< Container >::ContainsMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 3156 of file gmock-matchers.h.
      : QuantifierMatcherImpl<Container>(inner_matcher) {}
Member Function Documentation
DescribeNegationTo()
template<typename Container > virtual void testing::internal::ContainsMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3165 of file gmock-matchers.h.
{
    *os << "doesn't contain any element that ";
    this->inner_matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_.
DescribeTo()
template<typename Container > virtual void testing::internal::ContainsMatcherImpl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3160 of file gmock-matchers.h.
{
    *os << "contains at least one element that ";
    this->inner_matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_.
GTEST_DISALLOW_ASSIGN_()
template<typename Container > testing::internal::ContainsMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (ContainsMatcherImpl< Container >) private
MatchAndExplain()
template<typename Container > virtual bool testing::internal::ContainsMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 3170 of file gmock-matchers.h.
{
    return this->MatchAndExplainImpl(false, container, listener);
  }
References testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h