wiNpoS: HooksCfg Class Reference
HooksCfg Class Reference
#include <HooksCfg.h>
Public Member Functions
void readAppConfig ()
read the config for this app
void readConfig ()
read the global config for all apps
void writeAppConfig ()
save the config for this app
void writeConfig ()
save global config for all apps
void openFolder ()
open the config folder
void openWinPosConfig ()
open the wiNpoS config in editor
void disable ()
stores disabled in config
void enable ()
remove disabled from config
bool isDisabled ()
check if someone has disabled stored in config
Public Attributes
RECT Rect = { 0 }
bool _disabled = false
Private Member Functions
DocumentPtr readConfigDocument (const string &configPath)
read a JSON config from given path
void writeConfigDocument (rapidjson::Document &d, const string &configPath)
save the JSON document to the given path
string getAppConfigPath ()
the path to the config file for this app
string getConfigPath ()
the path to the global config, for all apps
string getConfigDir ()
the directory, where store the configs and logs
Detailed Description
Definition at line 24 of file HooksCfg.h.
Member Function Documentation
disable()
void HooksCfg::disable ()
stores disabled in config
Definition at line 186 of file HooksCfg.cpp.
{
    _disabled = true;
    writeConfig();
}
References _disabled, and writeConfig().
enable()
void HooksCfg::enable ()
remove disabled from config
Definition at line 194 of file HooksCfg.cpp.
{
    _disabled = false;
    writeConfig();
}
References _disabled, and writeConfig().
getAppConfigPath()
string HooksCfg::getAppConfigPath () private
the path to the config file for this app
Returns
Definition at line 212 of file HooksCfg.cpp.
{
    using std::format;
    char filePath[MAX_PATH];
    GetModuleFileNameA(NULL, filePath, MAX_PATH);
    string exeName = PathFindFileNameA(filePath);
    return format(R"({}\{}.jsonl)", getConfigDir(), exeName);
}
References getConfigDir().
getConfigDir()
string HooksCfg::getConfigDir () private
the directory, where store the configs and logs
Returns
Definition at line 234 of file HooksCfg.cpp.
{
    char configDir[MAX_PATH];
    ExpandEnvironmentStringsA(R"(%APPDATA%\wiNpoS)", configDir, MAX_PATH);
    return configDir;
}
getConfigPath()
string HooksCfg::getConfigPath () private
the path to the global config, for all apps
Returns
Definition at line 224 of file HooksCfg.cpp.
{
    using std::format;
    return format(R"({}\wiNpoS.jsonl)", getConfigDir());
}
References getConfigDir().
isDisabled()
bool HooksCfg::isDisabled ()
check if someone has disabled stored in config
Returns
Definition at line 203 of file HooksCfg.cpp.
{
    readConfig();
    return _disabled;
}
References _disabled, and readConfig().
openFolder()
void HooksCfg::openFolder ()
open the config folder
Definition at line 150 of file HooksCfg.cpp.
{
    wchar_t dir[MAX_PATH];
    ExpandEnvironmentStrings(LR"(%APPDATA%\wiNpoS)", dir, MAX_PATH);
    HINSTANCE hFolder = ShellExecute(
        NULL,
        L"open",
        dir,
        NULL,
        dir,
        SW_SHOW
    );
}
openWinPosConfig()
void HooksCfg::openWinPosConfig ()
open the wiNpoS config in editor
Definition at line 168 of file HooksCfg.cpp.
{
    string configPath = WinPosWndCfg::getConfigPath();
    char configDir[MAX_PATH];
    ExpandEnvironmentStringsA(R"(%APPDATA%\wiNpoS)", configDir, MAX_PATH);
    HINSTANCE hConfig = ShellExecuteA(
        NULL,
        "open",
        configPath.c_str(),
        NULL,
        configDir,
        SW_SHOW
    );
}
References WinPosWndCfg::getConfigPath().
readAppConfig()
void HooksCfg::readAppConfig ()
read the config for this app
Definition at line 76 of file HooksCfg.cpp.
{
    { // default rect
        RECT wa = { 0 };
        SystemParametersInfo(SPI_GETWORKAREA, 0, &wa, 0);
        int waw = wa.right - wa.left, wah = wa.bottom - wa.top;
        int w = 600, h = 400;
        Rect.left = (waw - w) / 2;
        Rect.top = (wah - h) / 2;
        Rect.right = Rect.left + w;
        Rect.bottom = Rect.top + h;
    }
    if(auto d_ptr = readConfigDocument(getAppConfigPath()))
    {
        Document& d = *d_ptr;
        if (d.HasMember("left"))
            Rect.left = d["left"].GetInt();
        if (d.HasMember("top"))
            Rect.top = d["top"].GetInt();
        if (d.HasMember("right"))
            Rect.right = d["right"].GetInt();
        if (d.HasMember("bottom"))
            Rect.bottom = d["bottom"].GetInt();
    }
}
References getAppConfigPath(), readConfigDocument(), and Rect.
readConfig()
void HooksCfg::readConfig ()
read the global config for all apps
Definition at line 106 of file HooksCfg.cpp.
{
    if(auto d_ptr = readConfigDocument(getConfigPath()))
    {
        Document& d = *d_ptr;
        _disabled = d.HasMember("disabled") ? d["disabled"].GetBool() : false;
    }
}
References _disabled, getConfigPath(), and readConfigDocument().
readConfigDocument()
DocumentPtr HooksCfg::readConfigDocument (const string & configPath) private
read a JSON config from given path
Parameters
configPath
Returns
Definition at line 32 of file HooksCfg.cpp.
{
    FILE* fp = nullptr;
    errno_t res = fopen_s(&fp, configPath.c_str(), "rb"); // non-Windows use "r"
    if (fp)
    {
        static const size_t BUFFER_SIZE = 4096 * 8;
        std::unique_ptr<char[]> buffer = std::make_unique<char[]>(BUFFER_SIZE);
        FileReadStream is(fp, buffer.get(), BUFFER_SIZE);
        fclose(fp);
        auto d_ptr = std::shared_ptr<Document>(new Document);
        d_ptr->ParseStream<kParseCommentsFlag | kParseTrailingCommasFlag>(is);
        return d_ptr;
    }
    return DocumentPtr();
}
writeAppConfig()
void HooksCfg::writeAppConfig ()
save the config for this app
Definition at line 117 of file HooksCfg.cpp.
{
    string configDir = getConfigDir();
    CreateDirectoryA(configDir.c_str(), NULL);
    Document d;
    d.SetObject();
    auto& a = d.GetAllocator();
    d.AddMember("left", (int)Rect.left, a);
    d.AddMember("top", (int)Rect.top, a);
    d.AddMember("right", (int)Rect.right, a);
    d.AddMember("bottom", (int)Rect.bottom, a);
    string configPath = getAppConfigPath();
    writeConfigDocument(d, configPath);
}
References getAppConfigPath(), getConfigDir(), Rect, and writeConfigDocument().
writeConfig()
void HooksCfg::writeConfig ()
save global config for all apps
Definition at line 137 of file HooksCfg.cpp.
{
    Document d;
    d.SetObject();
    auto& a = d.GetAllocator();
    d.AddMember("disabled", _disabled, a);
    string configPath = getConfigPath();
    writeConfigDocument(d, configPath);
}
References _disabled, getConfigPath(), and writeConfigDocument().
writeConfigDocument()
void HooksCfg::writeConfigDocument (rapidjson::Document & d, const string & configPath) private
save the JSON document to the given path
Parameters
configPath
d
Definition at line 56 of file HooksCfg.cpp.
{
    FILE* fp = nullptr;
    errno_t res = fopen_s(&fp, configPath.c_str(), "wb"); // non-Windows use "w"
    AssertTrue(fp, dformat("File {} should be open here", configPath));
    static const size_t BUFFER_SIZE = 4096 * 8;
    std::unique_ptr<char[]> buffer = std::make_unique<char[]>(BUFFER_SIZE);
    FileWriteStream os(fp, buffer.get(), BUFFER_SIZE);
    PrettyWriter<FileWriteStream> writer(os);
    d.Accept(writer);
    fclose(fp);
    WRITE_DEBUG_LOG(format("Write config to {}", configPath));
}
References AssertTrue, and WRITE_DEBUG_LOG.
Member Data Documentation
_disabled
bool HooksCfg::_disabled = false
Definition at line 28 of file HooksCfg.h.
Rect
RECT HooksCfg::Rect = { 0 }
Definition at line 27 of file HooksCfg.h.
{ 0 };
The documentation for this class was generated from the following files:
wiNpoS-Shared/HooksCfg.h
wiNpoS-Shared/HooksCfg.cpp