wiNpoS: JsonxWriter< OutputStream > Class Template Reference
JsonxWriter< OutputStream > Class Template Reference
Public Member Functions
JsonxWriter (OutputStream &os)
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned i)
bool Int64 (int64_t i)
bool Uint64 (uint64_t i)
bool Double (double d)
bool RawNumber (const char *str, SizeType length, bool)
bool String (const char *str, SizeType length, bool)
bool StartObject ()
bool Key (const char *str, SizeType length, bool)
bool EndObject (SizeType)
bool StartArray ()
bool EndArray (SizeType)
Private Member Functions
bool WriteString (const char *s)
bool WriteEscapedAttributeValue (const char *s, size_t length)
bool WriteEscapedText (const char *s, size_t length)
bool WriteStartElement (const char *type, bool emptyElement=false)
bool WriteEndElement (const char *type)
bool WriteNumberElement (const char *buffer, int length)
Private Attributes
OutputStream & os_
StringBuffer name_
unsigned level_
bool hasName_
Detailed Description
template<typename OutputStream>
class JsonxWriter< OutputStream >
Definition at line 19 of file jsonx.cpp.
Constructor & Destructor Documentation
JsonxWriter()
template<typename OutputStream > JsonxWriter< OutputStream >::JsonxWriter (OutputStream & os) inline
Definition at line 21 of file jsonx.cpp.
                                  : os_(os), name_(), level_(0), hasName_(false) {
    }
Member Function Documentation
Bool()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Bool (bool b) inline
Definition at line 28 of file jsonx.cpp.
                      {
        return
            WriteStartElement("boolean") &&
            WriteString(b ? "true" : "false") &&
            WriteEndElement("boolean");
    }
References JsonxWriter< OutputStream >::WriteEndElement(), JsonxWriter< OutputStream >::WriteStartElement(), and JsonxWriter< OutputStream >::WriteString().
Double()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Double (double d) inline
Definition at line 55 of file jsonx.cpp.
{
        char buffer[30];
        return WriteNumberElement(buffer, sprintf(buffer, "%.17g", d));
    }
References JsonxWriter< OutputStream >::WriteNumberElement().
EndArray()
template<typename OutputStream > bool JsonxWriter< OutputStream >::EndArray (SizeType) inline
Definition at line 95 of file jsonx.cpp.
{
        return WriteEndElement("array");
    }
References JsonxWriter< OutputStream >::WriteEndElement().
EndObject()
template<typename OutputStream > bool JsonxWriter< OutputStream >::EndObject (SizeType) inline
Definition at line 87 of file jsonx.cpp.
{
        return WriteEndElement("object");
    }
References JsonxWriter< OutputStream >::WriteEndElement().
Int()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Int (int i) inline
Definition at line 35 of file jsonx.cpp.
                    {
        char buffer[12];
        return WriteNumberElement(buffer, sprintf(buffer, "%d", i));
    }
References JsonxWriter< OutputStream >::WriteNumberElement().
Int64()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Int64 (int64_t i) inline
Definition at line 45 of file jsonx.cpp.
{
        char buffer[21];
        return WriteNumberElement(buffer, sprintf(buffer, "%" PRId64, i));
    }
References PRId64, and JsonxWriter< OutputStream >::WriteNumberElement().
Key()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Key (const char * str, SizeType length, bool) inline
Definition at line 78 of file jsonx.cpp.
{
        // backup key to name_
        name_.Clear();
        for (SizeType i = 0; i < length; i++)
            name_.Put(str[i]);
        hasName_ = true;
        return true;
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::Clear(), JsonxWriter< OutputStream >::hasName_, JsonxWriter< OutputStream >::name_, and rapidjson::GenericStringBuffer< Encoding, Allocator >::Put().
Null()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Null () inline
Definition at line 24 of file jsonx.cpp.
                {
        return WriteStartElement("null", true);
    }
References JsonxWriter< OutputStream >::WriteStartElement().
RawNumber()
template<typename OutputStream > bool JsonxWriter< OutputStream >::RawNumber (const char * str, SizeType length, bool) inline
Definition at line 60 of file jsonx.cpp.
{
        return
            WriteStartElement("number") &&
            WriteEscapedText(str, length) &&
            WriteEndElement("number");
    }
References JsonxWriter< OutputStream >::WriteEndElement(), JsonxWriter< OutputStream >::WriteEscapedText(), and JsonxWriter< OutputStream >::WriteStartElement().
StartArray()
template<typename OutputStream > bool JsonxWriter< OutputStream >::StartArray () inline
Definition at line 91 of file jsonx.cpp.
                      {
        return WriteStartElement("array");
    }
References JsonxWriter< OutputStream >::WriteStartElement().
StartObject()
template<typename OutputStream > bool JsonxWriter< OutputStream >::StartObject () inline
Definition at line 74 of file jsonx.cpp.
                       {
        return WriteStartElement("object");
    }
References JsonxWriter< OutputStream >::WriteStartElement().
String()
template<typename OutputStream > bool JsonxWriter< OutputStream >::String (const char * str, SizeType length, bool) inline
Definition at line 67 of file jsonx.cpp.
{
        return
            WriteStartElement("string") &&
            WriteEscapedText(str, length) &&
            WriteEndElement("string");
    }
References JsonxWriter< OutputStream >::WriteEndElement(), JsonxWriter< OutputStream >::WriteEscapedText(), and JsonxWriter< OutputStream >::WriteStartElement().
Uint()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Uint (unsigned i) inline
Definition at line 40 of file jsonx.cpp.
{
        char buffer[11];
        return WriteNumberElement(buffer, sprintf(buffer, "%u", i));
    }
References JsonxWriter< OutputStream >::WriteNumberElement().
Uint64()
template<typename OutputStream > bool JsonxWriter< OutputStream >::Uint64 (uint64_t i) inline
Definition at line 50 of file jsonx.cpp.
{
        char buffer[21];
        return WriteNumberElement(buffer, sprintf(buffer, "%" PRIu64, i));
    }
References PRIu64, and JsonxWriter< OutputStream >::WriteNumberElement().
WriteEndElement()
template<typename OutputStream > bool JsonxWriter< OutputStream >::WriteEndElement (const char * type) inline private
Definition at line 162 of file jsonx.cpp.
{
        if (!WriteString("</json:") ||
            !WriteString(type) ||
            !WriteString(">"))
            return false;
        // For the last end tag, flush the output stream.
        if (--level_ == 0)
            os_.Flush();
        return true;
    }
References JsonxWriter< OutputStream >::level_, JsonxWriter< OutputStream >::os_, and JsonxWriter< OutputStream >::WriteString().
WriteEscapedAttributeValue()
template<typename OutputStream > bool JsonxWriter< OutputStream >::WriteEscapedAttributeValue (const char * s, size_t length) inline private
Definition at line 106 of file jsonx.cpp.
{
        for (size_t i = 0; i < length; i++) {
            switch (s[i]) {
                case '&': WriteString("&amp;"); break;
                case '<': WriteString("&lt;"); break;
                case '"': WriteString("&quot;"); break;
                default: os_.Put(s[i]); break;
            }
        }
        return true;
    }
References JsonxWriter< OutputStream >::os_, and JsonxWriter< OutputStream >::WriteString().
WriteEscapedText()
template<typename OutputStream > bool JsonxWriter< OutputStream >::WriteEscapedText (const char * s, size_t length) inline private
Definition at line 118 of file jsonx.cpp.
{
        for (size_t i = 0; i < length; i++) {
            switch (s[i]) {
                case '&': WriteString("&amp;"); break;
                case '<': WriteString("&lt;"); break;
                default: os_.Put(s[i]); break;
            }
        }
        return true;
    }
References JsonxWriter< OutputStream >::os_, and JsonxWriter< OutputStream >::WriteString().
WriteNumberElement()
template<typename OutputStream > bool JsonxWriter< OutputStream >::WriteNumberElement (const char * buffer, int length) inline private
Definition at line 175 of file jsonx.cpp.
{
        if (!WriteStartElement("number"))
            return false;
        for (int j = 0; j < length; j++)
            os_.Put(buffer[j]);
        return WriteEndElement("number");
    }
References JsonxWriter< OutputStream >::os_, JsonxWriter< OutputStream >::WriteEndElement(), and JsonxWriter< OutputStream >::WriteStartElement().
WriteStartElement()
template<typename OutputStream > bool JsonxWriter< OutputStream >::WriteStartElement (const char * type, bool emptyElement = false) inline private
Definition at line 129 of file jsonx.cpp.
{
        if (level_ == 0)
            if (!WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"))
                return false;
        if (!WriteString("<json:") || !WriteString(type))
            return false;
        // For root element, need to add declarations
        if (level_ == 0) {
            if (!WriteString(
                " xsi:schemaLocation=\"http://www.datapower.com/schemas/json jsonx.xsd\""
                " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                " xmlns:json=\"http://www.ibm.com/xmlns/prod/2009/jsonx\""))
                return false;
        }
        if (hasName_) {
            hasName_ = false;
            if (!WriteString(" name=\"") ||
                !WriteEscapedAttributeValue(name_.GetString(), name_.GetSize()) ||
                !WriteString("\""))
                return false;
        }
        if (emptyElement)
            return WriteString("/>");
        else {
            level_++;
            return WriteString(">");
        }
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), JsonxWriter< OutputStream >::hasName_, JsonxWriter< OutputStream >::level_, JsonxWriter< OutputStream >::name_, JsonxWriter< OutputStream >::WriteEscapedAttributeValue(), and JsonxWriter< OutputStream >::WriteString().
WriteString()
template<typename OutputStream > bool JsonxWriter< OutputStream >::WriteString (const char * s) inline private
Definition at line 100 of file jsonx.cpp.
{
        while (*s)
            os_.Put(*s++);
        return true;
    }
References JsonxWriter< OutputStream >::os_.
Member Data Documentation
hasName_
template<typename OutputStream > bool JsonxWriter< OutputStream >::hasName_ private
Definition at line 186 of file jsonx.cpp.
level_
template<typename OutputStream > unsigned JsonxWriter< OutputStream >::level_ private
Definition at line 185 of file jsonx.cpp.
name_
template<typename OutputStream > StringBuffer JsonxWriter< OutputStream >::name_ private
Definition at line 184 of file jsonx.cpp.
os_
template<typename OutputStream > OutputStream& JsonxWriter< OutputStream >::os_ private
Definition at line 183 of file jsonx.cpp.
The documentation for this class was generated from the following file:
rapidjson/example/jsonx/jsonx.cpp