wiNpoS: testing::internal::ResultOfMatcher< Callable >::Impl< T > Class Template Reference
testing::internal::ResultOfMatcher< Callable >::Impl< T > Class Template Reference
Public Member Functions
Impl (CallableStorageType callable, const Matcher< ResultType > &matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (T obj, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
Private Member Functions
GTEST_DISALLOW_ASSIGN_ (Impl)
Private Attributes
CallableStorageType callable_
const Matcher< ResultType > matcher_
Detailed Description
template<typename Callable>
template<typename T>
class testing::internal::ResultOfMatcher< Callable >::Impl< T >
Definition at line 2650 of file gmock-matchers.h.
Constructor & Destructor Documentation
Impl()
template<typename Callable > template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::Impl (CallableStorageType callable, const Matcher< ResultType > & matcher) inline
Definition at line 2652 of file gmock-matchers.h.
        : callable_(callable), matcher_(matcher) {}
Member Function Documentation
DescribeNegationTo()
template<typename Callable > template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 2660 of file gmock-matchers.h.
{
      *os << "is mapped by the given callable to a value that ";
      matcher_.DescribeNegationTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), and testing::internal::ResultOfMatcher< Callable >::Impl< T >::matcher_.
DescribeTo()
template<typename Callable > template<typename T > virtual void testing::internal::ResultOfMatcher< Callable >::Impl< T >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 2655 of file gmock-matchers.h.
{
      *os << "is mapped by the given callable to a value that ";
      matcher_.DescribeTo(os);
    }
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::ResultOfMatcher< Callable >::Impl< T >::matcher_.
GTEST_DISALLOW_ASSIGN_()
template<typename Callable > template<typename T > testing::internal::ResultOfMatcher< Callable >::Impl< T >::GTEST_DISALLOW_ASSIGN_ (Impl< T >) private
MatchAndExplain()
template<typename Callable > template<typename T > virtual bool testing::internal::ResultOfMatcher< Callable >::Impl< T >::MatchAndExplain (T obj, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< T >.
Definition at line 2665 of file gmock-matchers.h.
{
      *listener << "which is mapped by the given callable to ";
      // Cannot pass the return value (for example, int) to
      // MatchPrintAndExplain, which takes a non-const reference as argument.
      ResultType result =
          CallableTraits<Callable>::template Invoke<T>(callable_, obj);
      return MatchPrintAndExplain(result, matcher_, listener);
    }
References testing::internal::ResultOfMatcher< Callable >::Impl< T >::callable_, testing::internal::ResultOfMatcher< Callable >::Impl< T >::matcher_, and testing::internal::MatchPrintAndExplain().
Member Data Documentation
callable_
template<typename Callable > template<typename T > CallableStorageType testing::internal::ResultOfMatcher< Callable >::Impl< T >::callable_ mutable private
Definition at line 2680 of file gmock-matchers.h.
matcher_
template<typename Callable > template<typename T > const Matcher<ResultType> testing::internal::ResultOfMatcher< Callable >::Impl< T >::matcher_ private
Definition at line 2681 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h