wiNpoS: testing::internal::QuantifierMatcherImpl< Container > Class Template Reference
testing::internal::QuantifierMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherInterface< Container >
virtual bool MatchAndExplain (Container x, MatchResultListener *listener) const=0
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
Protected Member Functions
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
Protected Attributes
const Matcher< const Element & > inner_matcher_
Detailed Description
template<typename Container>
class testing::internal::QuantifierMatcherImpl< Container >
Definition at line 3108 of file gmock-matchers.h.
Member Typedef Documentation
Element
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element
Definition at line 3114 of file gmock-matchers.h.
StlContainer
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer
Definition at line 3112 of file gmock-matchers.h.
StlContainerReference
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference
Definition at line 3113 of file gmock-matchers.h.
View
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View
Definition at line 3111 of file gmock-matchers.h.
Constructor & Destructor Documentation
QuantifierMatcherImpl()
template<typename Container > template<typename InnerMatcher > testing::internal::QuantifierMatcherImpl< Container >::QuantifierMatcherImpl (InnerMatcher inner_matcher) inline explicit
Definition at line 3117 of file gmock-matchers.h.
      : inner_matcher_(
           testing::SafeMatcherCast<const Element&>(inner_matcher)) {}
Member Function Documentation
GTEST_DISALLOW_ASSIGN_()
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) protected
GTEST_REMOVE_REFERENCE_AND_CONST_()
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
MatchAndExplainImpl()
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
Definition at line 3124 of file gmock-matchers.h.
{
    StlContainerReference stl_container = View::ConstReference(container);
    size_t i = 0;
    for (typename StlContainer::const_iterator it = stl_container.begin();
         it != stl_container.end(); ++it, ++i) {
      StringMatchResultListener inner_listener;
      const bool matches = inner_matcher_.MatchAndExplain(*it, &inner_listener);
      if (matches != all_elements_should_match) {
        *listener << "whose element #" << i
                  << (matches ? " matches" : " doesn't match");
        PrintIfNotEmpty(inner_listener.str(), listener->stream());
        return !all_elements_should_match;
      }
    }
    return all_elements_should_match;
  }
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_, testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
Member Data Documentation
inner_matcher_
template<typename Container > const Matcher<const Element&> testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_ protected
Definition at line 3145 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h