wiNpoS: testing::internal::PropertyMatcher< Class, PropertyType, Property > Class Template Reference
testing::internal::PropertyMatcher< Class, PropertyType, Property > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
typedef GTEST_REFERENCE_TO_CONST_ (PropertyType) RefToConstProperty
PropertyMatcher (Property property, const Matcher< RefToConstProperty > &matcher)
PropertyMatcher (const std::string &property_name, Property property, const Matcher< RefToConstProperty > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
Private Member Functions
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (PropertyMatcher)
Private Attributes
Property property_
const Matcher< RefToConstProperty > matcher_
const std::string whose_property_
Detailed Description
template<typename Class, typename PropertyType, typename Property>
class testing::internal::PropertyMatcher< Class, PropertyType, Property >
Definition at line 2520 of file gmock-matchers.h.
Constructor & Destructor Documentation
PropertyMatcher() [1/2]
template<typename Class , typename PropertyType , typename Property > testing::internal::PropertyMatcher< Class, PropertyType, Property >::PropertyMatcher (Property property, const Matcher< RefToConstProperty > & matcher) inline
Definition at line 2528 of file gmock-matchers.h.
      : property_(property),
        matcher_(matcher),
        whose_property_("whose given property ") {}
PropertyMatcher() [2/2]
template<typename Class , typename PropertyType , typename Property > testing::internal::PropertyMatcher< Class, PropertyType, Property >::PropertyMatcher (const std::string & property_name, Property property, const Matcher< RefToConstProperty > & matcher) inline
Definition at line 2533 of file gmock-matchers.h.
      : property_(property),
        matcher_(matcher),
        whose_property_("whose property `" + property_name + "` ") {}
Member Function Documentation
DescribeNegationTo()
template<typename Class , typename PropertyType , typename Property > void testing::internal::PropertyMatcher< Class, PropertyType, Property >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2544 of file gmock-matchers.h.
{
    *os << "is an object " << whose_property_;
    matcher_.DescribeNegationTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), testing::internal::PropertyMatcher< Class, PropertyType, Property >::matcher_, and testing::internal::PropertyMatcher< Class, PropertyType, Property >::whose_property_.
DescribeTo()
template<typename Class , typename PropertyType , typename Property > void testing::internal::PropertyMatcher< Class, PropertyType, Property >::DescribeTo (::std::ostream * os) const inline
Definition at line 2539 of file gmock-matchers.h.
{
    *os << "is an object " << whose_property_;
    matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), testing::internal::PropertyMatcher< Class, PropertyType, Property >::matcher_, and testing::internal::PropertyMatcher< Class, PropertyType, Property >::whose_property_.
GTEST_DISALLOW_ASSIGN_()
template<typename Class , typename PropertyType , typename Property > testing::internal::PropertyMatcher< Class, PropertyType, Property >::GTEST_DISALLOW_ASSIGN_ (PropertyMatcher< Class, PropertyType, Property >) private
GTEST_REFERENCE_TO_CONST_()
template<typename Class , typename PropertyType , typename Property > typedef testing::internal::PropertyMatcher< Class, PropertyType, Property >::GTEST_REFERENCE_TO_CONST_ (PropertyType)
MatchAndExplain()
template<typename Class , typename PropertyType , typename Property > template<typename T > bool testing::internal::PropertyMatcher< Class, PropertyType, Property >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2550 of file gmock-matchers.h.
{
    return MatchAndExplainImpl(
        typename ::testing::internal::
            is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
        value, listener);
  }
References GTEST_REMOVE_CONST_, testing::internal::PropertyMatcher< Class, PropertyType, Property >::MatchAndExplainImpl(), and T.
MatchAndExplainImpl() [1/2]
template<typename Class , typename PropertyType , typename Property > bool testing::internal::PropertyMatcher< Class, PropertyType, Property >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2561 of file gmock-matchers.h.
{
    *listener << whose_property_ << "is ";
    // Cannot pass the return value (for example, int) to MatchPrintAndExplain,
    // which takes a non-const reference as argument.
#if defined(_PREFAST_) && _MSC_VER == 1800
    // Workaround bug in VC++ 2013's /analyze parser.
    // https://connect.microsoft.com/VisualStudio/feedback/details/1106363/internal-compiler-error-with-analyze-due-to-failure-to-infer-move
    posix::Abort();  // To make sure it is never run.
    return false;
#else
    RefToConstProperty result = (obj.*property_)();
    return MatchPrintAndExplain(result, matcher_, listener);
#endif
  }
References testing::internal::posix::Abort(), testing::internal::PropertyMatcher< Class, PropertyType, Property >::matcher_, testing::internal::MatchPrintAndExplain(), testing::internal::PropertyMatcher< Class, PropertyType, Property >::property_, and testing::internal::PropertyMatcher< Class, PropertyType, Property >::whose_property_.
MatchAndExplainImpl() [2/2]
template<typename Class , typename PropertyType , typename Property > bool testing::internal::PropertyMatcher< Class, PropertyType, Property >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2577 of file gmock-matchers.h.
{
    if (p == NULL)
      return false;
    *listener << "which points to an object ";
    // Since *p has a property method, it must be a class/struct/union
    // type and thus cannot be a pointer.  Therefore we pass
    // false_type() as the first argument.
    return MatchAndExplainImpl(false_type(), *p, listener);
  }
References testing::internal::PropertyMatcher< Class, PropertyType, Property >::MatchAndExplainImpl().
Member Data Documentation
matcher_
template<typename Class , typename PropertyType , typename Property > const Matcher<RefToConstProperty> testing::internal::PropertyMatcher< Class, PropertyType, Property >::matcher_ private
Definition at line 2590 of file gmock-matchers.h.
property_
template<typename Class , typename PropertyType , typename Property > Property testing::internal::PropertyMatcher< Class, PropertyType, Property >::property_ private
Definition at line 2589 of file gmock-matchers.h.
whose_property_
template<typename Class , typename PropertyType , typename Property > const std::string testing::internal::PropertyMatcher< Class, PropertyType, Property >::whose_property_ private
Definition at line 2594 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h