wiNpoS: testing::internal::FieldMatcher< Class, FieldType > Class Template Reference
testing::internal::FieldMatcher< Class, FieldType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
FieldMatcher (FieldType Class::*field, const Matcher< const FieldType & > &matcher)
FieldMatcher (const std::string &field_name, FieldType Class::*field, const Matcher< const FieldType & > &matcher)
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
template<typename T >
bool MatchAndExplain (const T &value, MatchResultListener *listener) const
Private Member Functions
bool MatchAndExplainImpl (false_type, const Class &obj, MatchResultListener *listener) const
bool MatchAndExplainImpl (true_type, const Class *p, MatchResultListener *listener) const
GTEST_DISALLOW_ASSIGN_ (FieldMatcher)
Private Attributes
const FieldType Class::* field_
const Matcher< const FieldType & > matcher_
const std::string whose_field_
Detailed Description
template<typename Class, typename FieldType>
class testing::internal::FieldMatcher< Class, FieldType >
Definition at line 2452 of file gmock-matchers.h.
Constructor & Destructor Documentation
FieldMatcher() [1/2]
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::FieldMatcher (FieldType Class::* field, const Matcher< const FieldType & > & matcher) inline
Definition at line 2454 of file gmock-matchers.h.
      : field_(field), matcher_(matcher), whose_field_("whose given field ") {}
FieldMatcher() [2/2]
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::FieldMatcher (const std::string & field_name, FieldType Class::* field, const Matcher< const FieldType & > & matcher) inline
Definition at line 2458 of file gmock-matchers.h.
      : field_(field),
        matcher_(matcher),
        whose_field_("whose field `" + field_name + "` ") {}
Member Function Documentation
DescribeNegationTo()
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeNegationTo (::std::ostream * os) const inline
Definition at line 2469 of file gmock-matchers.h.
{
    *os << "is an object " << whose_field_;
    matcher_.DescribeNegationTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeNegationTo(), testing::internal::FieldMatcher< Class, FieldType >::matcher_, and testing::internal::FieldMatcher< Class, FieldType >::whose_field_.
DescribeTo()
template<typename Class , typename FieldType > void testing::internal::FieldMatcher< Class, FieldType >::DescribeTo (::std::ostream * os) const inline
Definition at line 2464 of file gmock-matchers.h.
{
    *os << "is an object " << whose_field_;
    matcher_.DescribeTo(os);
  }
References testing::internal::MatcherBase< T >::DescribeTo(), testing::internal::FieldMatcher< Class, FieldType >::matcher_, and testing::internal::FieldMatcher< Class, FieldType >::whose_field_.
GTEST_DISALLOW_ASSIGN_()
template<typename Class , typename FieldType > testing::internal::FieldMatcher< Class, FieldType >::GTEST_DISALLOW_ASSIGN_ (FieldMatcher< Class, FieldType >) private
MatchAndExplain()
template<typename Class , typename FieldType > template<typename T > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplain (const T & value, MatchResultListener * listener) const inline
Definition at line 2475 of file gmock-matchers.h.
{
    return MatchAndExplainImpl(
        typename ::testing::internal::
            is_pointer<GTEST_REMOVE_CONST_(T)>::type(),
        value, listener);
  }
References GTEST_REMOVE_CONST_, testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl(), and T.
MatchAndExplainImpl() [1/2]
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (false_type , const Class & obj, MatchResultListener * listener) const inline private
Definition at line 2486 of file gmock-matchers.h.
{
    *listener << whose_field_ << "is ";
    return MatchPrintAndExplain(obj.*field_, matcher_, listener);
  }
References testing::internal::FieldMatcher< Class, FieldType >::field_, testing::internal::FieldMatcher< Class, FieldType >::matcher_, testing::internal::MatchPrintAndExplain(), and testing::internal::FieldMatcher< Class, FieldType >::whose_field_.
MatchAndExplainImpl() [2/2]
template<typename Class , typename FieldType > bool testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl (true_type , const Class * p, MatchResultListener * listener) const inline private
Definition at line 2492 of file gmock-matchers.h.
{
    if (p == NULL)
      return false;
    *listener << "which points to an object ";
    // Since *p has a field, it must be a class/struct/union type and
    // thus cannot be a pointer.  Therefore we pass false_type() as
    // the first argument.
    return MatchAndExplainImpl(false_type(), *p, listener);
  }
References testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplainImpl().
Member Data Documentation
field_
template<typename Class , typename FieldType > const FieldType Class::* testing::internal::FieldMatcher< Class, FieldType >::field_ private
Definition at line 2504 of file gmock-matchers.h.
matcher_
template<typename Class , typename FieldType > const Matcher<const FieldType&> testing::internal::FieldMatcher< Class, FieldType >::matcher_ private
Definition at line 2505 of file gmock-matchers.h.
whose_field_
template<typename Class , typename FieldType > const std::string testing::internal::FieldMatcher< Class, FieldType >::whose_field_ private
Definition at line 2509 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h