wiNpoS: testing::internal::FloatingEq2Matcher< FloatType > Class Template Reference
testing::internal::FloatingEq2Matcher< FloatType > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
FloatingEq2Matcher ()
FloatingEq2Matcher (bool nan_eq_nan)
FloatingEq2Matcher (FloatType max_abs_error)
FloatingEq2Matcher (FloatType max_abs_error, bool nan_eq_nan)
template<typename T1 , typename T2 >
operator Matcher< ::testing::tuple< T1, T2 > > () const
template<typename T1 , typename T2 >
operator Matcher< const ::testing::tuple< T1, T2 > & > () const
Private Member Functions
void Init (FloatType max_abs_error_val, bool nan_eq_nan_val)
Static Private Member Functions
::std::ostream & GetDesc (::std::ostream &os)
Private Attributes
FloatType max_abs_error_
bool nan_eq_nan_
Detailed Description
template<typename FloatType>
class testing::internal::FloatingEq2Matcher< FloatType >
Definition at line 2242 of file gmock-matchers.h.
Constructor & Destructor Documentation
FloatingEq2Matcher() [1/4]
template<typename FloatType > testing::internal::FloatingEq2Matcher< FloatType >::FloatingEq2Matcher () inline
Definition at line 2244 of file gmock-matchers.h.
{ Init(-1, false); }
References testing::internal::FloatingEq2Matcher< FloatType >::Init().
FloatingEq2Matcher() [2/4]
template<typename FloatType > testing::internal::FloatingEq2Matcher< FloatType >::FloatingEq2Matcher (bool nan_eq_nan) inline explicit
Definition at line 2246 of file gmock-matchers.h.
{ Init(-1, nan_eq_nan); }
References testing::internal::FloatingEq2Matcher< FloatType >::Init().
FloatingEq2Matcher() [3/4]
template<typename FloatType > testing::internal::FloatingEq2Matcher< FloatType >::FloatingEq2Matcher (FloatType max_abs_error) inline explicit
Definition at line 2248 of file gmock-matchers.h.
{
    Init(max_abs_error, false);
  }
References testing::internal::FloatingEq2Matcher< FloatType >::Init().
FloatingEq2Matcher() [4/4]
template<typename FloatType > testing::internal::FloatingEq2Matcher< FloatType >::FloatingEq2Matcher (FloatType max_abs_error, bool nan_eq_nan) inline
Definition at line 2252 of file gmock-matchers.h.
{
    Init(max_abs_error, nan_eq_nan);
  }
References testing::internal::FloatingEq2Matcher< FloatType >::Init().
Member Function Documentation
GetDesc()
template<typename FloatType > ::std::ostream & testing::internal::FloatingEq2Matcher< FloatType >::GetDesc (::std::ostream & os) inline static private
Definition at line 2268 of file gmock-matchers.h.
                                             {  // NOLINT
    return os << "an almost-equal pair";
  }
Init()
template<typename FloatType > void testing::internal::FloatingEq2Matcher< FloatType >::Init (FloatType max_abs_error_val, bool nan_eq_nan_val) inline private
Definition at line 2304 of file gmock-matchers.h.
{
    max_abs_error_ = max_abs_error_val;
    nan_eq_nan_ = nan_eq_nan_val;
  }
References testing::internal::FloatingEq2Matcher< FloatType >::max_abs_error_, and testing::internal::FloatingEq2Matcher< FloatType >::nan_eq_nan_.
operator Matcher< ::testing::tuple< T1, T2 > >()
template<typename FloatType > template<typename T1 , typename T2 > testing::internal::FloatingEq2Matcher< FloatType >::operator Matcher< ::testing::tuple< T1, T2 > > () const inline
Definition at line 2257 of file gmock-matchers.h.
{
    return MakeMatcher(
        new Impl< ::testing::tuple<T1, T2> >(max_abs_error_, nan_eq_nan_));
  }
References testing::MakeMatcher(), testing::internal::FloatingEq2Matcher< FloatType >::max_abs_error_, and testing::internal::FloatingEq2Matcher< FloatType >::nan_eq_nan_.
operator Matcher< const ::testing::tuple< T1, T2 > & >()
template<typename FloatType > template<typename T1 , typename T2 > testing::internal::FloatingEq2Matcher< FloatType >::operator Matcher< const ::testing::tuple< T1, T2 > & > () const inline
Definition at line 2262 of file gmock-matchers.h.
{
    return MakeMatcher(
        new Impl<const ::testing::tuple<T1, T2>&>(max_abs_error_, nan_eq_nan_));
  }
References testing::MakeMatcher(), testing::internal::FloatingEq2Matcher< FloatType >::max_abs_error_, and testing::internal::FloatingEq2Matcher< FloatType >::nan_eq_nan_.
Member Data Documentation
max_abs_error_
template<typename FloatType > FloatType testing::internal::FloatingEq2Matcher< FloatType >::max_abs_error_ private
Definition at line 2308 of file gmock-matchers.h.
nan_eq_nan_
template<typename FloatType > bool testing::internal::FloatingEq2Matcher< FloatType >::nan_eq_nan_ private
Definition at line 2309 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googlemock/include/gmock/gmock-matchers.h