wiNpoS: gtest_env_var_test.GTestEnvVarTest Class Reference
gtest_env_var_test.GTestEnvVarTest Class Reference
Public Member Functions
testEnvVarAffectsFlag (self)
testXmlOutputFile (self)
testXmlOutputFileOverride (self)
Detailed Description
Definition at line 83 of file gtest_env_var_test.py.
Member Function Documentation
testEnvVarAffectsFlag()
gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag (self)
Tests that environment variable should affect the corresponding flag.
Definition at line 85 of file gtest_env_var_test.py.
  def testEnvVarAffectsFlag(self):
    """Tests that environment variable should affect the corresponding flag."""
    TestFlag('break_on_failure', '1', '0')
    TestFlag('color', 'yes', 'auto')
    TestFlag('filter', 'FooTest.Bar', '*')
    SetEnvVar('XML_OUTPUT_FILE', None)  # For 'output' test
    TestFlag('output', 'xml:tmp/foo.xml', '')
    TestFlag('print_time', '0', '1')
    TestFlag('repeat', '999', '1')
    TestFlag('throw_on_failure', '1', '0')
    TestFlag('death_test_style', 'threadsafe', 'fast')
    TestFlag('catch_exceptions', '0', '1')
    if IS_LINUX:
      TestFlag('death_test_use_fork', '1', '0')
      TestFlag('stack_trace_depth', '0', '100')
References gtest_env_var_test.SetEnvVar(), and gtest_env_var_test.TestFlag().
testXmlOutputFile()
gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile (self)
Tests that $XML_OUTPUT_FILE affects the output flag.
Definition at line 104 of file gtest_env_var_test.py.
  def testXmlOutputFile(self):
    """Tests that $XML_OUTPUT_FILE affects the output flag."""
    SetEnvVar('GTEST_OUTPUT', None)
    SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
    AssertEq('xml:tmp/bar.xml', GetFlag('output'))
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), and gtest_env_var_test.SetEnvVar().
testXmlOutputFileOverride()
gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride (self)
Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT.
Definition at line 111 of file gtest_env_var_test.py.
  def testXmlOutputFileOverride(self):
    """Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT."""
    SetEnvVar('GTEST_OUTPUT', 'xml:tmp/foo.xml')
    SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
    AssertEq('xml:tmp/foo.xml', GetFlag('output'))
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_test_utils.Main(), and gtest_env_var_test.SetEnvVar().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest_env_var_test.py