wiNpoS: anonymous_namespace{gtest_unittest.cc}::TestResultTest Class Reference
anonymous_namespace{gtest_unittest.cc}::TestResultTest Class Reference
Protected Types
typedef std::vector< TestPartResult > TPRVector
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
Protected Member Functions inherited from testing::Test
Test ()
Static Protected Member Functions
static void CompareTestPartResult (const TestPartResult &expected, const TestPartResult &actual)
Protected Attributes
TestPartResult * pr1
TestPartResult * pr2
TestResult * r0
TestResult * r1
TestResult * r2
Additional Inherited Members
Public Types inherited from testing::Test
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions inherited from testing::Test
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Detailed Description
Definition at line 1357 of file gtest_unittest.cc.
Member Typedef Documentation
TPRVector
typedef std::vector<TestPartResult> anonymous_namespace{gtest_unittest.cc}::TestResultTest::TPRVector protected
Definition at line 1359 of file gtest_unittest.cc.
Member Function Documentation
CompareTestPartResult()
static void anonymous_namespace{gtest_unittest.cc}::TestResultTest::CompareTestPartResult (const TestPartResult & expected, const TestPartResult & actual) inline static protected
Definition at line 1415 of file gtest_unittest.cc.
{
    EXPECT_EQ(expected.type(), actual.type());
    EXPECT_STREQ(expected.file_name(), actual.file_name());
    EXPECT_EQ(expected.line_number(), actual.line_number());
    EXPECT_STREQ(expected.summary(), actual.summary());
    EXPECT_STREQ(expected.message(), actual.message());
    EXPECT_EQ(expected.passed(), actual.passed());
    EXPECT_EQ(expected.failed(), actual.failed());
    EXPECT_EQ(expected.nonfatally_failed(), actual.nonfatally_failed());
    EXPECT_EQ(expected.fatally_failed(), actual.fatally_failed());
  }
References EXPECT_EQ, EXPECT_STREQ, testing::TestPartResult::failed(), testing::TestPartResult::fatally_failed(), testing::TestPartResult::file_name(), testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestPartResult::nonfatally_failed(), testing::TestPartResult::passed(), testing::TestPartResult::summary(), and testing::TestPartResult::type().
SetUp()
virtual void anonymous_namespace{gtest_unittest.cc}::TestResultTest::SetUp () inline protected virtual
Reimplemented from testing::Test.
Definition at line 1367 of file gtest_unittest.cc.
                       {
    // pr1 is for success.
    pr1 = new TestPartResult(TestPartResult::kSuccess,
                             "foo/bar.cc",
                             10,
                             "Success!");
    // pr2 is for fatal failure.
    pr2 = new TestPartResult(TestPartResult::kFatalFailure,
                             "foo/bar.cc",
                             -1,  // This line number means "unknown"
                             "Failure!");
    // Creates the TestResult objects.
    r0 = new TestResult();
    r1 = new TestResult();
    r2 = new TestResult();
    // In order to test TestResult, we need to modify its internal
    // state, in particular the TestPartResult vector it holds.
    // test_part_results() returns a const reference to this vector.
    // We cast it to a non-const object s.t. it can be modified (yes,
    // this is a hack).
    TPRVector* results1 = const_cast<TPRVector*>(
        &TestResultAccessor::test_part_results(*r1));
    TPRVector* results2 = const_cast<TPRVector*>(
        &TestResultAccessor::test_part_results(*r2));
    // r0 is an empty TestResult.
    // r1 contains a single SUCCESS TestPartResult.
    results1->push_back(*pr1);
    // r2 contains a SUCCESS, and a FAILURE.
    results2->push_back(*pr1);
    results2->push_back(*pr2);
  }
TearDown()
virtual void anonymous_namespace{gtest_unittest.cc}::TestResultTest::TearDown () inline protected virtual
Reimplemented from testing::Test.
Definition at line 1405 of file gtest_unittest.cc.
{
    delete pr1;
    delete pr2;
    delete r0;
    delete r1;
    delete r2;
  }
Member Data Documentation
pr1
TestPartResult* anonymous_namespace{gtest_unittest.cc}::TestResultTest::pr1 protected
Definition at line 1362 of file gtest_unittest.cc.
pr2
TestPartResult * anonymous_namespace{gtest_unittest.cc}::TestResultTest::pr2 protected
Definition at line 1362 of file gtest_unittest.cc.
r0
TestResult* anonymous_namespace{gtest_unittest.cc}::TestResultTest::r0 protected
Definition at line 1365 of file gtest_unittest.cc.
r1
TestResult * anonymous_namespace{gtest_unittest.cc}::TestResultTest::r1 protected
Definition at line 1365 of file gtest_unittest.cc.
r2
TestResult * anonymous_namespace{gtest_unittest.cc}::TestResultTest::r2 protected
Definition at line 1365 of file gtest_unittest.cc.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest_unittest.cc