wiNpoS: gtest_xml_output_unittest.GTestXMLOutputUnitTest Class Reference
gtest_xml_output_unittest.GTestXMLOutputUnitTest Class Reference
Public Member Functions
testNonEmptyXmlOutput (self)
testEmptyXmlOutput (self)
testTimestampValue (self)
testDefaultOutputFile (self)
testSuppressedXmlOutput (self)
testFilteredTestXmlOutput (self)
testShardedTestXmlOutput (self)
Public Member Functions inherited from gtest_xml_test_utils.GTestXMLTestCase
AssertEquivalentNodes (self, expected_node, actual_node)
NormalizeXml (self, element)
Protected Member Functions
_GetXmlOutput (self, gtest_prog_name, extra_args, extra_env, expected_exit_code)
_TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args=None, extra_env=None)
Protected Member Functions inherited from gtest_xml_test_utils.GTestXMLTestCase
_GetChildren (self, element)
Additional Inherited Members
Public Attributes inherited from gtest_xml_test_utils.GTestXMLTestCase
identifying_attribute
Static Public Attributes inherited from gtest_xml_test_utils.GTestXMLTestCase
dict identifying_attribute
Detailed Description
Unit test for Google Test's XML output functionality.
Definition at line 204 of file gtest_xml_output_unittest.py.
Member Function Documentation
_GetXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput (self, gtest_prog_name, extra_args, extra_env, expected_exit_code) protected
Returns the xml output generated by running the program gtest_prog_name.
Furthermore, the program's exit code must be expected_exit_code.
Definition at line 328 of file gtest_xml_output_unittest.py.
                    expected_exit_code):
    """
    Returns the xml output generated by running the program gtest_prog_name.
    Furthermore, the program's exit code must be expected_exit_code.
    """
    xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                            gtest_prog_name + 'out.xml')
    gtest_prog_path = gtest_test_utils.GetTestExecutablePath(gtest_prog_name)
    command = ([gtest_prog_path, '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path)] +
               extra_args)
    environ_copy = os.environ.copy()
    if extra_env:
      environ_copy.update(extra_env)
    p = gtest_test_utils.Subprocess(command, env=environ_copy)
    if p.terminated_by_signal:
      self.assert_(False,
                   '%s was killed by signal %d' % (gtest_prog_name, p.signal))
    else:
      self.assert_(p.exited)
      self.assertEquals(expected_exit_code, p.exit_code,
                        "'%s' exited with code %s, which doesn't match "
                        'the expected exit code %s.'
                        % (command, p.exit_code, expected_exit_code))
    actual = minidom.parse(xml_path)
    return actual
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
_TestXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput (self, gtest_prog_name, expected_xml, expected_exit_code, extra_args = None, extra_env = None) protected
Asserts that the XML document generated by running the program
gtest_prog_name matches expected_xml, a string containing another
XML document.  Furthermore, the program's exit code must be
expected_exit_code.
Definition at line 357 of file gtest_xml_output_unittest.py.
                     expected_exit_code, extra_args=None, extra_env=None):
    """
    Asserts that the XML document generated by running the program
    gtest_prog_name matches expected_xml, a string containing another
    XML document.  Furthermore, the program's exit code must be
    expected_exit_code.
    """
    actual = self._GetXmlOutput(gtest_prog_name, extra_args or [],
                                extra_env or {}, expected_exit_code)
    expected = minidom.parseString(expected_xml)
    self.NormalizeXml(actual.documentElement)
    self.AssertEquivalentNodes(expected.documentElement,
                               actual.documentElement)
    expected.unlink()
    actual.unlink()
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.Main(), and gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
testDefaultOutputFile()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile (self)
Confirms that Google Test produces an XML output file with the expected
default name if no name is explicitly specified.
Definition at line 253 of file gtest_xml_output_unittest.py.
  def testDefaultOutputFile(self):
    """
    Confirms that Google Test produces an XML output file with the expected
    default name if no name is explicitly specified.
    """
    output_file = os.path.join(gtest_test_utils.GetTempDir(),
                               GTEST_DEFAULT_OUTPUT_FILE)
    gtest_prog_path = gtest_test_utils.GetTestExecutablePath(
        'gtest_no_test_unittest')
    try:
      os.remove(output_file)
    except OSError, e:
      if e.errno != errno.ENOENT:
        raise
    p = gtest_test_utils.Subprocess(
        [gtest_prog_path, '%s=xml' % GTEST_OUTPUT_FLAG],
        working_dir=gtest_test_utils.GetTempDir())
    self.assert_(p.exited)
    self.assertEquals(0, p.exit_code)
    self.assert_(os.path.isfile(output_file))
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
testEmptyXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testEmptyXmlOutput (self)
Verifies XML output for a Google Test binary without actual tests.
Runs a test program that generates an empty XML output, and
tests that the XML output is expected.
Definition at line 219 of file gtest_xml_output_unittest.py.
  def testEmptyXmlOutput(self):
    """Verifies XML output for a Google Test binary without actual tests.
    Runs a test program that generates an empty XML output, and
    tests that the XML output is expected.
    """
    self._TestXmlOutput('gtest_no_test_unittest', EXPECTED_EMPTY_XML, 0)
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
testFilteredTestXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput (self)
Verifies XML output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the XML output.
Definition at line 304 of file gtest_xml_output_unittest.py.
  def testFilteredTestXmlOutput(self):
    """Verifies XML output when a filter is applied.
    Runs a test program that executes only some tests and verifies that
    non-selected tests do not show up in the XML output.
    """
    self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_FILTERED_TEST_XML, 0,
                        extra_args=['%s=SuccessfulTest.*' % GTEST_FILTER_FLAG])
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
testNonEmptyXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testNonEmptyXmlOutput (self)
Runs a test program that generates a non-empty XML output, and
tests that the XML output is expected.
Definition at line 212 of file gtest_xml_output_unittest.py.
    def testNonEmptyXmlOutput(self):
      """
      Runs a test program that generates a non-empty XML output, and
      tests that the XML output is expected.
      """
      self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_NON_EMPTY_XML, 1)
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
testShardedTestXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testShardedTestXmlOutput (self)
Verifies XML output when run using multiple shards.
Runs a test program that executes only one shard and verifies that tests
from other shards do not show up in the XML output.
Definition at line 314 of file gtest_xml_output_unittest.py.
  def testShardedTestXmlOutput(self):
    """Verifies XML output when run using multiple shards.
    Runs a test program that executes only one shard and verifies that tests
    from other shards do not show up in the XML output.
    """
    self._TestXmlOutput(
        GTEST_PROGRAM_NAME,
        EXPECTED_SHARDED_TEST_XML,
        0,
        extra_env={SHARD_INDEX_ENV_VAR: '0',
                   TOTAL_SHARDS_ENV_VAR: '10'})
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput().
testSuppressedXmlOutput()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testSuppressedXmlOutput (self)
Tests that no XML file is generated if the default XML listener is
shut down before RUN_ALL_TESTS is invoked.
Definition at line 275 of file gtest_xml_output_unittest.py.
  def testSuppressedXmlOutput(self):
    """
    Tests that no XML file is generated if the default XML listener is
    shut down before RUN_ALL_TESTS is invoked.
    """
    xml_path = os.path.join(gtest_test_utils.GetTempDir(),
                            GTEST_PROGRAM_NAME + 'out.xml')
    if os.path.isfile(xml_path):
      os.remove(xml_path)
    command = [GTEST_PROGRAM_PATH,
               '%s=xml:%s' % (GTEST_OUTPUT_FLAG, xml_path),
               '--shut_down_xml']
    p = gtest_test_utils.Subprocess(command)
    if p.terminated_by_signal:
      # p.signal is available only if p.terminated_by_signal is True.
      self.assertFalse(
          p.terminated_by_signal,
          '%s was killed by signal %d' % (GTEST_PROGRAM_NAME, p.signal))
    else:
      self.assert_(p.exited)
      self.assertEquals(1, p.exit_code,
                        "'%s' exited with code %s, which doesn't match "
                        'the expected exit code %s.'
                        % (command, p.exit_code, 1))
    self.assert_(not os.path.isfile(xml_path))
References gtest_test_utils.GetTempDir().
testTimestampValue()
gtest_xml_output_unittest.GTestXMLOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the XML output is valid.
Runs a test program that generates an empty XML output, and checks if
the timestamp attribute in the testsuites tag is valid.
Definition at line 228 of file gtest_xml_output_unittest.py.
  def testTimestampValue(self):
    """Checks whether the timestamp attribute in the XML output is valid.
    Runs a test program that generates an empty XML output, and checks if
    the timestamp attribute in the testsuites tag is valid.
    """
    actual = self._GetXmlOutput('gtest_no_test_unittest', [], {}, 0)
    date_time_str = actual.documentElement.getAttributeNode('timestamp').value
    # datetime.strptime() is only available in Python 2.5+ so we have to
    # parse the expected datetime manually.
    match = re.match(r'(\d+)-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)', date_time_str)
    self.assertTrue(
        re.match,
        'XML datettime string %s has incorrect format' % date_time_str)
    date_time_from_xml = datetime.datetime(
        year=int(match.group(1)), month=int(match.group(2)),
        day=int(match.group(3)), hour=int(match.group(4)),
        minute=int(match.group(5)), second=int(match.group(6)))
    time_delta = abs(datetime.datetime.now() - date_time_from_xml)
    # timestamp value should be near the current local time
    self.assertTrue(time_delta < datetime.timedelta(seconds=600),
                    'time_delta is %s' % time_delta)
    actual.unlink()
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput().
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/test/gtest_xml_output_unittest.py