wiNpoS: JsonWriter Class Reference
JsonWriter Class Reference
#include <archiver.h>
Public Member Functions
JsonWriter ()
Constructor.
~JsonWriter ()
Destructor.
const char * GetString () const
Obtains the serialized JSON string.
operator bool () const
JsonWriter & StartObject ()
JsonWriter & Member (const char *name)
bool HasMember (const char *name) const
JsonWriter & EndObject ()
JsonWriter & StartArray (size_t *size=0)
JsonWriter & EndArray ()
JsonWriter & operator& (bool &b)
JsonWriter & operator& (unsigned &u)
JsonWriter & operator& (int &i)
JsonWriter & operator& (double &d)
JsonWriter & operator& (std::string &s)
JsonWriter & SetNull ()
Static Public Attributes
static const bool IsReader = false
static const bool IsWriter = !IsReader
Private Member Functions
JsonWriter (const JsonWriter &)
JsonWriter & operator= (const JsonWriter &)
Private Attributes
void * mWriter
JSON writer.
void * mStream
Stream buffer.
Detailed Description
Definition at line 103 of file archiver.h.
Constructor & Destructor Documentation
JsonWriter() [1/2]
JsonWriter::JsonWriter ()
Constructor.
Definition at line 216 of file archiver.cpp.
                       : mWriter(), mStream() {
    mStream = new StringBuffer;
    mWriter = new PrettyWriter<StringBuffer>(*STREAM);
}
References mStream, mWriter, and STREAM.
~JsonWriter()
JsonWriter::~JsonWriter ()
Destructor.
Definition at line 221 of file archiver.cpp.
{
    delete WRITER;
    delete STREAM;
}
References STREAM, and WRITER.
JsonWriter() [2/2]
JsonWriter::JsonWriter (const JsonWriter &) private
Member Function Documentation
EndArray()
JsonWriter & JsonWriter::EndArray ()
Definition at line 256 of file archiver.cpp.
{
    WRITER->EndArray();
    return *this;
}
References EndArray(), and WRITER.
EndObject()
JsonWriter & JsonWriter::EndObject ()
Definition at line 235 of file archiver.cpp.
{
    WRITER->EndObject();
    return *this;
}
References EndObject(), and WRITER.
GetString()
const char * JsonWriter::GetString () const
Obtains the serialized JSON string.
Definition at line 226 of file archiver.cpp.
{
    return STREAM->GetString();
}
References STREAM.
HasMember()
bool JsonWriter::HasMember (const char * name) const
Definition at line 245 of file archiver.cpp.
{
    // This function is for JsonReader only.
    assert(false);
    return false;
}
Member()
JsonWriter & JsonWriter::Member (const char * name)
Definition at line 240 of file archiver.cpp.
{
    WRITER->String(name, static_cast<SizeType>(strlen(name)));
    return *this;
}
References WRITER.
operator bool()
JsonWriter::operator bool () const inline
Definition at line 116 of file archiver.h.
{ return true; }
operator&() [1/5]
JsonWriter & JsonWriter::operator& (bool & b)
Definition at line 261 of file archiver.cpp.
{
    WRITER->Bool(b);
    return *this;
}
References WRITER.
operator&() [2/5]
JsonWriter & JsonWriter::operator& (double & d)
Definition at line 276 of file archiver.cpp.
{
    WRITER->Double(d);
    return *this;
}
References WRITER.
operator&() [3/5]
JsonWriter & JsonWriter::operator& (int & i)
Definition at line 271 of file archiver.cpp.
{
    WRITER->Int(i);
    return *this;
}
References WRITER.
operator&() [4/5]
JsonWriter & JsonWriter::operator& (std::string & s)
Definition at line 281 of file archiver.cpp.
{
    WRITER->String(s.c_str(), static_cast<SizeType>(s.size()));
    return *this;
}
References WRITER.
operator&() [5/5]
JsonWriter & JsonWriter::operator& (unsigned & u)
Definition at line 266 of file archiver.cpp.
{
    WRITER->Uint(u);
    return *this;
}
References WRITER.
operator=()
JsonWriter & JsonWriter::operator= (const JsonWriter &) private
SetNull()
JsonWriter & JsonWriter::SetNull ()
Definition at line 286 of file archiver.cpp.
{
    WRITER->Null();
    return *this;
}
References WRITER.
StartArray()
JsonWriter & JsonWriter::StartArray (size_t * size = 0)
Definition at line 251 of file archiver.cpp.
{
    WRITER->StartArray();
    return *this;
}
References StartArray(), and WRITER.
StartObject()
JsonWriter & JsonWriter::StartObject ()
Definition at line 230 of file archiver.cpp.
{
    WRITER->StartObject();
    return *this;
}
References StartObject(), and WRITER.
Member Data Documentation
IsReader
const bool JsonWriter::IsReader = false static
Definition at line 133 of file archiver.h.
IsWriter
const bool JsonWriter::IsWriter = !IsReader static
Definition at line 134 of file archiver.h.
mStream
void* JsonWriter::mStream private
Stream buffer.
Definition at line 142 of file archiver.h.
mWriter
void* JsonWriter::mWriter private
JSON writer.
Definition at line 141 of file archiver.h.
The documentation for this class was generated from the following files:
rapidjson/example/archiver/archiver.h
rapidjson/example/archiver/archiver.cpp