wiNpoS: testing::internal::ParameterizedTestCaseRegistry Class Reference
testing::internal::ParameterizedTestCaseRegistry Class Reference
#include <gtest-param-util.h>
Public Member Functions
ParameterizedTestCaseRegistry ()
~ParameterizedTestCaseRegistry ()
template<class TestCase >
ParameterizedTestCaseInfo< TestCase > * GetTestCasePatternHolder (const char *test_case_name, CodeLocation code_location)
void RegisterTests ()
Private Types
typedef ::std::vector< ParameterizedTestCaseInfoBase * > TestCaseInfoContainer
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestCaseRegistry)
Private Attributes
TestCaseInfoContainer test_case_infos_
Detailed Description
Definition at line 662 of file gtest-param-util.h.
Member Typedef Documentation
TestCaseInfoContainer
typedef ::std::vector<ParameterizedTestCaseInfoBase*> testing::internal::ParameterizedTestCaseRegistry::TestCaseInfoContainer private
Definition at line 713 of file gtest-param-util.h.
Constructor & Destructor Documentation
ParameterizedTestCaseRegistry()
testing::internal::ParameterizedTestCaseRegistry::ParameterizedTestCaseRegistry () inline
Definition at line 664 of file gtest-param-util.h.
{}
~ParameterizedTestCaseRegistry()
testing::internal::ParameterizedTestCaseRegistry::~ParameterizedTestCaseRegistry () inline
Definition at line 665 of file gtest-param-util.h.
{
    for (TestCaseInfoContainer::iterator it = test_case_infos_.begin();
         it != test_case_infos_.end(); ++it) {
      delete *it;
    }
  }
References test_case_infos_.
Member Function Documentation
GetTestCasePatternHolder()
template<class TestCase > ParameterizedTestCaseInfo< TestCase > * testing::internal::ParameterizedTestCaseRegistry::GetTestCasePatternHolder (const char * test_case_name, CodeLocation code_location) inline
Definition at line 675 of file gtest-param-util.h.
{
    ParameterizedTestCaseInfo<TestCase>* typed_test_info = NULL;
    for (TestCaseInfoContainer::iterator it = test_case_infos_.begin();
         it != test_case_infos_.end(); ++it) {
      if ((*it)->GetTestCaseName() == test_case_name) {
        if ((*it)->GetTestCaseTypeId() != GetTypeId<TestCase>()) {
          // Complain about incorrect usage of Google Test facilities
          // and terminate the program since we cannot guaranty correct
          // test case setup and tear-down in this case.
          ReportInvalidTestCaseType(test_case_name, code_location);
          posix::Abort();
        } else {
          // At this point we are sure that the object we found is of the same
          // type we are looking for, so we downcast it to that type
          // without further checks.
          typed_test_info = CheckedDowncastToActualType<
              ParameterizedTestCaseInfo<TestCase> >(*it);
        }
        break;
      }
    }
    if (typed_test_info == NULL) {
      typed_test_info = new ParameterizedTestCaseInfo<TestCase>(
          test_case_name, code_location);
      test_case_infos_.push_back(typed_test_info);
    }
    return typed_test_info;
  }
References testing::internal::posix::Abort(), testing::internal::CheckedDowncastToActualType(), testing::internal::ReportInvalidTestCaseType(), and test_case_infos_.
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::internal::ParameterizedTestCaseRegistry::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestCaseRegistry) private
RegisterTests()
void testing::internal::ParameterizedTestCaseRegistry::RegisterTests () inline
Definition at line 705 of file gtest-param-util.h.
                       {
    for (TestCaseInfoContainer::iterator it = test_case_infos_.begin();
         it != test_case_infos_.end(); ++it) {
      (*it)->RegisterTests();
    }
  }
References test_case_infos_.
Member Data Documentation
test_case_infos_
TestCaseInfoContainer testing::internal::ParameterizedTestCaseRegistry::test_case_infos_ private
Definition at line 715 of file gtest-param-util.h.
The documentation for this class was generated from the following file:
rapidjson/thirdparty/gtest/googletest/include/gtest/internal/gtest-param-util.h