wiNpoS: rapidjson/test/unittest/cursorstreamwrappertest.cpp File Reference
cursorstreamwrappertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/document.h"
#include "rapidjson/cursorstreamwrapper.h"
Functions
static bool testJson (const char *json, size_t &line, size_t &col)
TEST (CursorStreamWrapper, MissingFirstBracket)
TEST (CursorStreamWrapper, MissingQuotes)
TEST (CursorStreamWrapper, MissingColon)
TEST (CursorStreamWrapper, MissingSecondQuotes)
TEST (CursorStreamWrapper, MissingComma)
TEST (CursorStreamWrapper, MissingArrayBracket)
TEST (CursorStreamWrapper, MissingArrayComma)
TEST (CursorStreamWrapper, MissingLastArrayBracket)
TEST (CursorStreamWrapper, MissingLastBracket)
Function Documentation
TEST() [1/9]
TEST (CursorStreamWrapper , MissingArrayBracket)
Definition at line 81 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "{\"string\"\n\n:\"my string\",\"array\"\n:\"1\", \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 4u);
    EXPECT_EQ(col, 9u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [2/9]
TEST (CursorStreamWrapper , MissingArrayComma)
Definition at line 90 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "{\"string\"\n\n:\"my string\",\"array\"\n:[\"1\" \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 4u);
    EXPECT_EQ(col, 6u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [3/9]
TEST (CursorStreamWrapper , MissingColon)
Definition at line 54 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "{\"string\"\n\n\"my string\",\"array\"\n:[\"1\", \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 3u);
    EXPECT_EQ(col, 0u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [4/9]
TEST (CursorStreamWrapper , MissingComma)
Definition at line 72 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "{\"string\"\n\n:\"my string\"\"array\"\n:[\"1\", \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 3u);
    EXPECT_EQ(col, 12u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [5/9]
TEST (CursorStreamWrapper , MissingFirstBracket)
Definition at line 36 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "\"string\"\n\n:\"my string\",\"array\"\n:[\"1\", \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 3u);
    EXPECT_EQ(col, 0u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [6/9]
TEST (CursorStreamWrapper , MissingLastArrayBracket)
Definition at line 99 of file cursorstreamwrappertest.cpp.
{
    const char json8[] = "{\"string\"\n\n:\"my string\",\"array\"\n:[\"1\", \"2\", \"3\"}";
    size_t col, line;
    bool ret = testJson(json8, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 4u);
    EXPECT_EQ(col, 15u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [7/9]
TEST (CursorStreamWrapper , MissingLastBracket)
Definition at line 108 of file cursorstreamwrappertest.cpp.
{
    const char json9[] = "{\"string\"\n\n:\"my string\",\"array\"\n:[\"1\", \"2\", \"3\"]";
    size_t col, line;
    bool ret = testJson(json9, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 4u);
    EXPECT_EQ(col, 16u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [8/9]
TEST (CursorStreamWrapper , MissingQuotes)
Definition at line 45 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "{\"string\n\n:\"my string\",\"array\"\n:[\"1\", \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 1u);
    EXPECT_EQ(col, 8u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
TEST() [9/9]
TEST (CursorStreamWrapper , MissingSecondQuotes)
Definition at line 63 of file cursorstreamwrappertest.cpp.
{
    const char json[] = "{\"string\"\n\n:my string\",\"array\"\n:[\"1\", \"2\", \"3\"]}";
    size_t col, line;
    bool ret = testJson(json, line, col);
    EXPECT_TRUE(ret);
    EXPECT_EQ(line, 3u);
    EXPECT_EQ(col, 1u);
}
References EXPECT_EQ, EXPECT_TRUE, and testJson().
testJson()
static bool testJson (const char * json, size_t & line, size_t & col) static
Definition at line 23 of file cursorstreamwrappertest.cpp.
{
    StringStream ss(json);
    CursorStreamWrapper<StringStream> csw(ss);
    Document document;
    document.ParseStream(csw);
    bool ret = document.HasParseError();
    if (ret) {
        col = csw.GetColumn();
        line = csw.GetLine();
    }
    return ret;
}
References rapidjson::CursorStreamWrapper< InputStream, Encoding >::GetColumn(), rapidjson::CursorStreamWrapper< InputStream, Encoding >::GetLine(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().