wiNpoS: wiNpoS-Hook/dllmain.cpp File Reference
dllmain.cpp File Reference
#include "pch.h"
#include <vector>
#include <Utils.h>
#include "HooksMgr.h"
#include <Shlwapi.h>
#include <assert.h>
#include "ThumbnailToolbar.h"
Classes
struct GetMainWndRes
Namespaces
namespace anonymous_namespace{dllmain.cpp}
Typedefs
using WndVector = std::vector< HWND >
Functions
GetMainWndRes GetMainWnd (DWORD currentThreadId=0)
LRESULT CALLBACK GetMessageHookProc (int nCode, WPARAM wParam, LPARAM lParam)
LRESULT CALLBACK ShellHookProc (int nCode, WPARAM wParam, LPARAM lParam)
BOOL APIENTRY DllMain (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
WndVector GetDesktopWnds ()
BOOL CALLBACK anonymous_namespace{dllmain.cpp}::EnumWindowsProc (HWND hWnd, LPARAM lParam)
Variables
HINSTANCE hInstance = NULL
ThumbnailToolbar thumbnailToolbar
thread_local HooksMgr hooks
thread_local HHOOK hhGetMessageHookProc = NULL
thread_local HHOOK hhShellHookProc = NULL
thread_local HRESULT coInit = S_FALSE
Typedef Documentation
WndVector
using WndVector = std::vector<HWND>
Definition at line 26 of file dllmain.cpp.
Function Documentation
DllMain()
BOOL APIENTRY DllMain (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
Definition at line 32 of file dllmain.cpp.
{
    switch ((int)ul_reason_for_call)
    {
        case DLL_PROCESS_ATTACH:
        {
            //while (true) {
            //  Sleep(500);
            //}
            hInstance = hModule;
            GetMainWndRes mw = GetMainWnd(0);
            if (mw) // only apps with main window
            {
                if (mw.wndThreadId == GetCurrentThreadId()) // its a regular attach from global hook
                {
                    hhGetMessageHookProc =
                        SetWindowsHookEx(WH_GETMESSAGE, GetMessageHookProc, NULL, mw.wndThreadId);
                    PostMessage(mw.hMainWnd, MT_HOOK_MSG_CREATE_TASK_TOOLBAR, (WPARAM)GetCurrentThreadId(), (LPARAM)GetCurrentThread());
                }
                else    // otherweise its a attach by infiltrated thread
                {       // here we must start a new thread, to release the calling process
                    std::thread t([mw]()
                        {   // this hook allows the continuation in the main thread of the application
                            hhGetMessageHookProc =
                                SetWindowsHookEx(WH_GETMESSAGE, GetMessageHookProc, NULL, mw.wndThreadId);
                            PostMessage(mw.hMainWnd, MT_HOOK_MSG_REGISTER_THREAD_HOOK, (WPARAM)GetCurrentProcessId(), (LPARAM)GetCurrentThreadId());
                            PostMessage(mw.hMainWnd, MT_HOOK_MSG_CREATE_TASK_TOOLBAR, (WPARAM)GetCurrentThreadId(), (LPARAM)GetCurrentThread());
                            MSG msg;
                            while (GetMessage(&msg, NULL, 0, 0))
{
                                TranslateMessage(&msg);
                                DispatchMessage(&msg);
                            }
                        });
                    t.detach(); // because the end of control is reached here
                }
                WRITE_DEBUG_LOG(format("Attach {} to {}", Utils::DllName, Utils::ExeName));
            }
            break;
        }
        case DLL_THREAD_ATTACH:
            hhShellHookProc =
                SetWindowsHookEx(WH_SHELL, ShellHookProc, NULL, GetCurrentThreadId());
            break;
        case DLL_THREAD_DETACH:
            if (UnhookWindowsHookEx(hhShellHookProc))
                hhShellHookProc = NULL;
            assert(hhShellHookProc == NULL);
            hooks.unhookHooks();
            if(coInit == S_OK)
                CoUninitialize();
            break;
        case DLL_PROCESS_DETACH:
        {
            if (UnhookWindowsHookEx(hhGetMessageHookProc))
                hhGetMessageHookProc = NULL;
            assert(hhGetMessageHookProc == NULL);
            WRITE_DEBUG_LOG(format("Detach {} from {}", Utils::DllName, Utils::ExeName));
            break;
        }
    }
    return TRUE;
}
References coInit, Utils::ExeName, GetMainWnd(), GetMessageHookProc(), hhGetMessageHookProc, hhShellHookProc, hInstance, GetMainWndRes::hMainWnd, hooks, MT_HOOK_MSG_CREATE_TASK_TOOLBAR, MT_HOOK_MSG_REGISTER_THREAD_HOOK, ShellHookProc(), HooksMgr::unhookHooks(), GetMainWndRes::wndThreadId, and WRITE_DEBUG_LOG.
GetDesktopWnds()
WndVector GetDesktopWnds ()
Definition at line 204 of file dllmain.cpp.
{
    WndVector hWnds;
    auto threadId = GetCurrentThreadId();
    auto hDesktop = GetThreadDesktop(threadId);
    auto res = EnumDesktopWindows(hDesktop, EnumWindowsProc, (LPARAM)&hWnds);
    return hWnds;   //EnumDesktopWindows()
}
References anonymous_namespace{dllmain.cpp}::EnumWindowsProc().
GetMainWnd()
GetMainWndRes GetMainWnd (DWORD currentThreadId = 0)
Definition at line 172 of file dllmain.cpp.
{
    auto wnds = GetDesktopWnds();
    auto currentProcessId = GetCurrentProcessId();
    for (HWND hWnd : wnds)
    {
        DWORD wndProcessId = NULL;
        auto wndThreadId = GetWindowThreadProcessId(hWnd, &wndProcessId);
        if (currentProcessId == wndProcessId && (currentThreadId == 0 || wndThreadId == currentThreadId))
        {
            HWND hMainWnd = GetAncestor(hWnd, GA_ROOT);
            GetMainWndRes res = { hMainWnd, wndThreadId };
            return res;
        }
    }
    GetMainWndRes res = { 0 };
    return res;
}
References GetDesktopWnds().
GetMessageHookProc()
LRESULT CALLBACK GetMessageHookProc (int nCode, WPARAM wParam, LPARAM lParam)
Definition at line 114 of file dllmain.cpp.
{
    switch (nCode)
    {
        case HC_ACTION:
        {
            if (wParam == PM_REMOVE)
            {
                MSG* pMsg = (MSG*)lParam;
                //WRITE_DEBUG_LOG(format("Msg: {}", pMsg->message));
                if (pMsg->message == MT_HOOK_MSG_REGISTER_THREAD_HOOK)
                {
                    hooks.setHooks(hInstance);
                }
                else if (pMsg->message == MT_HOOK_MSG_CREATE_TASK_TOOLBAR)
                {
                    HRESULT hr = thumbnailToolbar.initialize(hInstance, pMsg->hwnd);
                    if (hr == 0x800401f0)//0x800401f0 : CoInitialize has not been called.
                    {
                        coInit = CoInitialize(NULL);
                        hr = thumbnailToolbar.initialize(hInstance, pMsg->hwnd);
                    }
                    if (FAILED(hr))
                        WRITE_DEBUG_LOG(format("Initialize of task toolbar failed with {:#010x} for {}", hr, Utils::ExeName));
                    else
                        WRITE_DEBUG_LOG(format("Initialize of task toolbar succede with {:#010x} for {}", hr, Utils::ExeName));
                    uint32_t sourceThreadId = (uint32_t)pMsg->wParam;
                    if(sourceThreadId != GetCurrentThreadId())
                        PostThreadMessage(sourceThreadId, WM_QUIT, 0, 0);
                }
                else if (pMsg->message == MT_HOOK_MSG_UNLOAD)
                {
                    WRITE_DEBUG_LOG(format("Msg: {}(MT_HOOK_MSG_UNLOAD) in {}", pMsg->message, Utils::ExeName));
                    if(pMsg->wParam != GetCurrentProcessId())
                    {
                        std::thread t([]() {
                            WRITE_DEBUG_LOG(format("Unload {} from {}", Utils::DllName, Utils::ExeName));
                            FreeLibrary(hInstance);
                            });
                        t.detach(); // because the end of control is reached here
                    }
                }
            }
        }
    }
    return CallNextHookEx(NULL, nCode, wParam, lParam);
}
References coInit, Utils::ExeName, hInstance, hooks, ThumbnailToolbar::initialize(), MT_HOOK_MSG_CREATE_TASK_TOOLBAR, MT_HOOK_MSG_REGISTER_THREAD_HOOK, MT_HOOK_MSG_UNLOAD, HooksMgr::setHooks(), thumbnailToolbar, and WRITE_DEBUG_LOG.
ShellHookProc()
LRESULT CALLBACK ShellHookProc (int nCode, WPARAM wParam, LPARAM lParam)
Definition at line 215 of file dllmain.cpp.
{
    DWORD currentThreadId = GetCurrentThreadId();
    if (nCode == HSHELL_WINDOWCREATED)
    {
        HWND hNewWindow = (HWND)wParam;
        hhGetMessageHookProc =
            SetWindowsHookEx(WH_GETMESSAGE, GetMessageHookProc, NULL, GetCurrentThreadId());
        PostMessage(hNewWindow, MT_HOOK_MSG_CREATE_TASK_TOOLBAR, (WPARAM)GetCurrentThreadId(), (LPARAM)GetCurrentThread());
    }
    return CallNextHookEx(NULL, nCode, wParam, lParam);
}
References GetMessageHookProc(), hhGetMessageHookProc, and MT_HOOK_MSG_CREATE_TASK_TOOLBAR.
Variable Documentation
coInit
thread_local HRESULT coInit = S_FALSE
Definition at line 16 of file dllmain.cpp.
hhGetMessageHookProc
thread_local HHOOK hhGetMessageHookProc = NULL
Definition at line 14 of file dllmain.cpp.
hhShellHookProc
thread_local HHOOK hhShellHookProc = NULL
Definition at line 15 of file dllmain.cpp.
hInstance
HINSTANCE hInstance = NULL
Definition at line 11 of file dllmain.cpp.
hooks
thread_local HooksMgr hooks
Definition at line 13 of file dllmain.cpp.
thumbnailToolbar
ThumbnailToolbar thumbnailToolbar
Definition at line 12 of file dllmain.cpp.