wiNpoS: rapidjson/test/unittest/documenttest.cpp File Reference
documenttest.cpp File Reference
#include "unittest.h"
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/encodedstream.h"
#include "rapidjson/stringbuffer.h"
#include <sstream>
#include <algorithm>
Classes
struct OutputStringStream
Functions
template<typename DocumentType >
void ParseCheck (DocumentType &doc)
template<typename Allocator , typename StackAllocator >
void ParseTest ()
TEST (Document, Parse)
TEST (Document, UnchangedOnParseError)
static FILE * OpenEncodedFile (const char *filename)
TEST (Document, Parse_Encoding)
TEST (Document, ParseStream_EncodedInputStream)
TEST (Document, ParseStream_AutoUTFInputStream)
TEST (Document, Swap)
TEST (Document, AcceptWriter)
TEST (Document, UserBuffer)
TEST (Document, AssertAcceptInvalidNameType)
TEST (Document, UTF16_Document)
Function Documentation
OpenEncodedFile()
static FILE * OpenEncodedFile (const char * filename) static
Definition at line 156 of file documenttest.cpp.
{
    const char *paths[] = {
        "encodings",
        "bin/encodings",
        "../bin/encodings",
        "../../bin/encodings",
        "../../../bin/encodings"
    };
    char buffer[1024];
    for (size_t i = 0; i < sizeof(paths) / sizeof(paths[0]); i++) {
        sprintf(buffer, "%s/%s", paths[i], filename);
        FILE *fp = fopen(buffer, "rb");
        if (fp)
            return fp;
    }
    return 0;
}
ParseCheck()
template<typename DocumentType > void ParseCheck (DocumentType & doc)
Definition at line 33 of file documenttest.cpp.
{
    typedef typename DocumentType::ValueType ValueType;
    EXPECT_FALSE(doc.HasParseError());
    if (doc.HasParseError())
        printf("Error: %d at %zu\n", static_cast<int>(doc.GetParseError()), doc.GetErrorOffset());
    EXPECT_TRUE(static_cast<ParseResult>(doc));
    EXPECT_TRUE(doc.IsObject());
    EXPECT_TRUE(doc.HasMember("hello"));
    const ValueType& hello = doc["hello"];
    EXPECT_TRUE(hello.IsString());
    EXPECT_STREQ("world", hello.GetString());
    EXPECT_TRUE(doc.HasMember("t"));
    const ValueType& t = doc["t"];
    EXPECT_TRUE(t.IsTrue());
    EXPECT_TRUE(doc.HasMember("f"));
    const ValueType& f = doc["f"];
    EXPECT_TRUE(f.IsFalse());
    EXPECT_TRUE(doc.HasMember("n"));
    const ValueType& n = doc["n"];
    EXPECT_TRUE(n.IsNull());
    EXPECT_TRUE(doc.HasMember("i"));
    const ValueType& i = doc["i"];
    EXPECT_TRUE(i.IsNumber());
    EXPECT_EQ(123, i.GetInt());
    EXPECT_TRUE(doc.HasMember("pi"));
    const ValueType& pi = doc["pi"];
    EXPECT_TRUE(pi.IsNumber());
    EXPECT_DOUBLE_EQ(3.1416, pi.GetDouble());
    EXPECT_TRUE(doc.HasMember("a"));
    const ValueType& a = doc["a"];
    EXPECT_TRUE(a.IsArray());
    EXPECT_EQ(4u, a.Size());
    for (SizeType j = 0; j < 4; j++)
        EXPECT_EQ(j + 1, a[j].GetUint());
}
References rapidjson::a, EXPECT_DOUBLE_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, and EXPECT_TRUE.
ParseTest()
template<typename Allocator , typename StackAllocator > void ParseTest ()
Definition at line 79 of file documenttest.cpp.
                 {
    typedef GenericDocument<UTF8<>, Allocator, StackAllocator> DocumentType;
    DocumentType doc;
    const char* json = " { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] } ";
    doc.Parse(json);
    ParseCheck(doc);
    doc.SetNull();
    StringStream s(json);
    doc.template ParseStream<0>(s);
    ParseCheck(doc);
    doc.SetNull();
    char *buffer = strdup(json);
    doc.ParseInsitu(buffer);
    ParseCheck(doc);
    free(buffer);
    // Parse(const Ch*, size_t)
    size_t length = strlen(json);
    buffer = reinterpret_cast<char*>(malloc(length * 2));
    memcpy(buffer, json, length);
    memset(buffer + length, 'X', length);
#if RAPIDJSON_HAS_STDSTRING
    std::string s2(buffer, length); // backup buffer
#endif
    doc.SetNull();
    doc.Parse(buffer, length);
    free(buffer);
    ParseCheck(doc);
#if RAPIDJSON_HAS_STDSTRING
    // Parse(std::string)
    doc.SetNull();
    doc.Parse(s2);
    ParseCheck(doc);
#endif
}
References ParseCheck().
TEST() [1/10]
TEST (Document , AcceptWriter)
Definition at line 361 of file documenttest.cpp.
{
    Document doc;
    doc.Parse(" { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] } ");
    OutputStringStream os;
    Writer<OutputStringStream> writer(os);
    doc.Accept(writer);
    EXPECT_EQ("{\"hello\":\"world\",\"t\":true,\"f\":false,\"n\":null,\"i\":123,\"pi\":3.1416,\"a\":[1,2,3,4]}", os.str());
}
References EXPECT_EQ, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST() [2/10]
TEST (Document , AssertAcceptInvalidNameType)
Definition at line 390 of file documenttest.cpp.
{
    Document doc;
    doc.SetObject();
    doc.AddMember("a", 0, doc.GetAllocator());
    doc.FindMember("a")->name.SetNull(); // Change name to non-string type.
    OutputStringStream os;
    Writer<OutputStringStream> writer(os);
    ASSERT_THROW(doc.Accept(writer), AssertException);
}
References ASSERT_THROW, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator().
TEST() [3/10]
TEST (Document , Parse)
Definition at line 120 of file documenttest.cpp.
                      {
    ParseTest<MemoryPoolAllocator<>, CrtAllocator>();
    ParseTest<MemoryPoolAllocator<>, MemoryPoolAllocator<> >();
    ParseTest<CrtAllocator, MemoryPoolAllocator<> >();
    ParseTest<CrtAllocator, CrtAllocator>();
}
TEST() [4/10]
TEST (Document , Parse_Encoding)
Definition at line 174 of file documenttest.cpp.
{
    const char* json = " { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] } ";
    typedef GenericDocument<UTF16<> > DocumentType;
    DocumentType doc;
    // Parse<unsigned, SourceEncoding>(const SourceEncoding::Ch*)
    // doc.Parse<kParseDefaultFlags, UTF8<> >(json);
    // EXPECT_FALSE(doc.HasParseError());
    // EXPECT_EQ(0, StrCmp(doc[L"hello"].GetString(), L"world"));
    // Parse<unsigned, SourceEncoding>(const SourceEncoding::Ch*, size_t)
    size_t length = strlen(json);
    char* buffer = reinterpret_cast<char*>(malloc(length * 2));
    memcpy(buffer, json, length);
    memset(buffer + length, 'X', length);
#if RAPIDJSON_HAS_STDSTRING
    std::string s2(buffer, length); // backup buffer
#endif
    doc.SetNull();
    doc.Parse<kParseDefaultFlags, UTF8<> >(buffer, length);
    free(buffer);
    EXPECT_FALSE(doc.HasParseError());
    if (doc.HasParseError())
        printf("Error: %d at %zu\n", static_cast<int>(doc.GetParseError()), doc.GetErrorOffset());
    EXPECT_EQ(0, StrCmp(doc[L"hello"].GetString(), L"world"));
#if RAPIDJSON_HAS_STDSTRING
    // Parse<unsigned, SourceEncoding>(std::string)
    doc.SetNull();
#if defined(_MSC_VER) && _MSC_VER < 1800
    doc.Parse<kParseDefaultFlags, UTF8<> >(s2.c_str()); // VS2010 or below cannot handle templated function overloading. Use const char* instead.
#else
    doc.Parse<kParseDefaultFlags, UTF8<> >(s2);
#endif
    EXPECT_FALSE(doc.HasParseError());
    EXPECT_EQ(0, StrCmp(doc[L"hello"].GetString(), L"world"));
#endif
}
References EXPECT_EQ, EXPECT_FALSE, GetString(), rapidjson::kParseDefaultFlags, and StrCmp().
TEST() [5/10]
TEST (Document , ParseStream_AutoUTFInputStream)
Definition at line 256 of file documenttest.cpp.
{
    // Any -> UTF8
    FILE* fp = OpenEncodedFile("utf32be.json");
    char buffer[256];
    FileReadStream bis(fp, buffer, sizeof(buffer));
    AutoUTFInputStream<unsigned, FileReadStream> eis(bis);
    Document d;
    d.ParseStream<0, AutoUTF<unsigned> >(eis);
    EXPECT_FALSE(d.HasParseError());
    fclose(fp);
    char expected[] = "I can eat glass and it doesn't hurt me.";
    Value& v = d["en"];
    EXPECT_TRUE(v.IsString());
    EXPECT_EQ(sizeof(expected) - 1, v.GetStringLength());
    EXPECT_EQ(0, StrCmp(expected, v.GetString()));
    // UTF8 -> UTF8 in memory
    StringBuffer bos;
    Writer<StringBuffer> writer(bos);
    d.Accept(writer);
    // Condense the original file and compare.
    fp = OpenEncodedFile("utf8.json");
    FileReadStream is(fp, buffer, sizeof(buffer));
    Reader reader;
    StringBuffer bos2;
    Writer<StringBuffer> writer2(bos2);
    reader.Parse(is, writer2);
    fclose(fp);
    EXPECT_EQ(bos.GetSize(), bos2.GetSize());
    EXPECT_EQ(0, memcmp(bos.GetString(), bos2.GetString(), bos2.GetSize()));
}
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), OpenEncodedFile(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), and StrCmp().
TEST() [6/10]
TEST (Document , ParseStream_EncodedInputStream)
Definition at line 215 of file documenttest.cpp.
{
    // UTF8 -> UTF16
    FILE* fp = OpenEncodedFile("utf8.json");
    char buffer[256];
    FileReadStream bis(fp, buffer, sizeof(buffer));
    EncodedInputStream<UTF8<>, FileReadStream> eis(bis);
    GenericDocument<UTF16<> > d;
    d.ParseStream<0, UTF8<> >(eis);
    EXPECT_FALSE(d.HasParseError());
    fclose(fp);
    wchar_t expected[] = L"I can eat glass and it doesn't hurt me.";
    GenericValue<UTF16<> >& v = d[L"en"];
    EXPECT_TRUE(v.IsString());
    EXPECT_EQ(sizeof(expected) / sizeof(wchar_t) - 1, v.GetStringLength());
    EXPECT_EQ(0, StrCmp(expected, v.GetString()));
    // UTF16 -> UTF8 in memory
    StringBuffer bos;
    typedef EncodedOutputStream<UTF8<>, StringBuffer> OutputStream;
    OutputStream eos(bos, false);   // Not writing BOM
    {
        Writer<OutputStream, UTF16<>, UTF8<> > writer(eos);
        d.Accept(writer);
    }
    // Condense the original file and compare.
    fp = OpenEncodedFile("utf8.json");
    FileReadStream is(fp, buffer, sizeof(buffer));
    Reader reader;
    StringBuffer bos2;
    Writer<StringBuffer> writer2(bos2);
    reader.Parse(is, writer2);
    fclose(fp);
    EXPECT_EQ(bos.GetSize(), bos2.GetSize());
    EXPECT_EQ(0, memcmp(bos.GetString(), bos2.GetString(), bos2.GetSize()));
}
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), OpenEncodedFile(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), and StrCmp().
TEST() [7/10]
TEST (Document , Swap)
Definition at line 293 of file documenttest.cpp.
                     {
    Document d1;
    Document::AllocatorType& a = d1.GetAllocator();
    d1.SetArray().PushBack(1, a).PushBack(2, a);
    Value o;
    o.SetObject().AddMember("a", 1, a);
    // Swap between Document and Value
    d1.Swap(o);
    EXPECT_TRUE(d1.IsObject());
    EXPECT_TRUE(o.IsArray());
    d1.Swap(o);
    EXPECT_TRUE(d1.IsArray());
    EXPECT_TRUE(o.IsObject());
    o.Swap(d1);
    EXPECT_TRUE(d1.IsObject());
    EXPECT_TRUE(o.IsArray());
    // Swap between Document and Document
    Document d2;
    d2.SetArray().PushBack(3, a);
    d1.Swap(d2);
    EXPECT_TRUE(d1.IsArray());
    EXPECT_TRUE(d2.IsObject());
    EXPECT_EQ(&d2.GetAllocator(), &a);
    // reset value
    Value().Swap(d1);
    EXPECT_TRUE(d1.IsNull());
    // reset document, including allocator
    // so clear o before so that it doesnt contain dangling elements
    o.Clear();
    Document().Swap(d2);
    EXPECT_TRUE(d2.IsNull());
    EXPECT_NE(&d2.GetAllocator(), &a);
    // testing std::swap compatibility
    d1.SetBool(true);
    using std::swap;
    swap(d1, d2);
    EXPECT_TRUE(d1.IsNull());
    EXPECT_TRUE(d2.IsTrue());
    swap(o, d2);
    EXPECT_TRUE(o.IsTrue());
    EXPECT_TRUE(d2.IsArray());
}
References rapidjson::a, EXPECT_EQ, EXPECT_NE, EXPECT_TRUE, rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Swap().
TEST() [8/10]
TEST (Document , UnchangedOnParseError)
Definition at line 127 of file documenttest.cpp.
{
    Document doc;
    doc.SetArray().PushBack(0, doc.GetAllocator());
    ParseResult noError;
    EXPECT_TRUE(noError);
    ParseResult err = doc.Parse("{]");
    EXPECT_TRUE(doc.HasParseError());
    EXPECT_NE(err, noError);
    EXPECT_NE(err.Code(), noError);
    EXPECT_NE(noError, doc.GetParseError());
    EXPECT_EQ(err.Code(), doc.GetParseError());
    EXPECT_EQ(err.Offset(), doc.GetErrorOffset());
    EXPECT_TRUE(doc.IsArray());
    EXPECT_EQ(doc.Size(), 1u);
    err = doc.Parse("{}");
    EXPECT_FALSE(doc.HasParseError());
    EXPECT_FALSE(err.IsError());
    EXPECT_TRUE(err);
    EXPECT_EQ(err, noError);
    EXPECT_EQ(err.Code(), noError);
    EXPECT_EQ(err.Code(), doc.GetParseError());
    EXPECT_EQ(err.Offset(), doc.GetErrorOffset());
    EXPECT_TRUE(doc.IsObject());
    EXPECT_EQ(doc.MemberCount(), 0u);
}
References rapidjson::ParseResult::Code(), EXPECT_EQ, EXPECT_FALSE, EXPECT_NE, EXPECT_TRUE, rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetErrorOffset(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetParseError(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), rapidjson::ParseResult::IsError(), rapidjson::ParseResult::Offset(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST() [9/10]
TEST (Document , UserBuffer)
Definition at line 372 of file documenttest.cpp.
{
    typedef GenericDocument<UTF8<>, MemoryPoolAllocator<>, MemoryPoolAllocator<> > DocumentType;
    char valueBuffer[4096];
    char parseBuffer[1024];
    MemoryPoolAllocator<> valueAllocator(valueBuffer, sizeof(valueBuffer));
    MemoryPoolAllocator<> parseAllocator(parseBuffer, sizeof(parseBuffer));
    DocumentType doc(&valueAllocator, sizeof(parseBuffer) / 2, &parseAllocator);
    doc.Parse(" { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] } ");
    EXPECT_FALSE(doc.HasParseError());
    EXPECT_LE(valueAllocator.Size(), sizeof(valueBuffer));
    EXPECT_LE(parseAllocator.Size(), sizeof(parseBuffer));
    // Cover MemoryPoolAllocator::Capacity()
    EXPECT_LE(valueAllocator.Size(), valueAllocator.Capacity());
    EXPECT_LE(parseAllocator.Size(), parseAllocator.Capacity());
}
References rapidjson::MemoryPoolAllocator< BaseAllocator >::Capacity(), EXPECT_FALSE, EXPECT_LE, and rapidjson::MemoryPoolAllocator< BaseAllocator >::Size().
TEST() [10/10]
TEST (Document , UTF16_Document)
Definition at line 402 of file documenttest.cpp.
{
    GenericDocument< UTF16<> > json;
    json.Parse<kParseValidateEncodingFlag>(L"[{\"created_at\":\"Wed Oct 30 17:13:20 +0000 2012\"}]");
    ASSERT_TRUE(json.IsArray());
    GenericValue< UTF16<> >& v = json[0];
    ASSERT_TRUE(v.IsObject());
    GenericValue< UTF16<> >& s = v[L"created_at"];
    ASSERT_TRUE(s.IsString());
    EXPECT_EQ(0, memcmp(L"Wed Oct 30 17:13:20 +0000 2012", s.GetString(), (s.GetStringLength() + 1) * sizeof(wchar_t)));
}
References ASSERT_TRUE, EXPECT_EQ, rapidjson::kParseValidateEncodingFlag, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().