wiNpoS: rapidjson/thirdparty/gtest/googlemock/test/gmock_test.cc File Reference
gmock_test.cc File Reference
#include "gmock/gmock.h"
#include <string>
#include "gtest/gtest.h"
#include "gtest/internal/custom/gtest.h"
Functions
template<typename Char , int M, int N>
void TestInitGoogleMock (const Char *(&argv)[M], const Char *(&new_argv)[N], const ::std::string &expected_gmock_verbose)
TEST (InitGoogleMockTest, ParsesInvalidCommandLine)
TEST (InitGoogleMockTest, ParsesEmptyCommandLine)
TEST (InitGoogleMockTest, ParsesSingleFlag)
TEST (InitGoogleMockTest, ParsesMultipleFlags)
TEST (InitGoogleMockTest, ParsesUnrecognizedFlag)
TEST (InitGoogleMockTest, ParsesGoogleMockFlagAndUnrecognizedFlag)
TEST (WideInitGoogleMockTest, ParsesInvalidCommandLine)
TEST (WideInitGoogleMockTest, ParsesEmptyCommandLine)
TEST (WideInitGoogleMockTest, ParsesSingleFlag)
TEST (WideInitGoogleMockTest, ParsesMultipleFlags)
TEST (WideInitGoogleMockTest, ParsesUnrecognizedFlag)
TEST (WideInitGoogleMockTest, ParsesGoogleMockFlagAndUnrecognizedFlag)
TEST (FlagTest, IsAccessibleInCode)
Function Documentation
TEST() [1/13]
TEST (FlagTest , IsAccessibleInCode)
Definition at line 258 of file gmock_test.cc.
{
  bool dummy = testing::GMOCK_FLAG(catch_leaked_mocks) &&
      testing::GMOCK_FLAG(verbose) == "";
  (void)dummy;  // Avoids the "unused local variable" warning.
}
TEST() [2/13]
TEST (InitGoogleMockTest , ParsesEmptyCommandLine)
Definition at line 79 of file gmock_test.cc.
{
  const char* argv[] = {
    "foo.exe",
    NULL
  };
  const char* new_argv[] = {
    "foo.exe",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
}
References GMOCK_FLAG, and TestInitGoogleMock().
TEST() [3/13]
TEST (InitGoogleMockTest , ParsesGoogleMockFlagAndUnrecognizedFlag)
Definition at line 144 of file gmock_test.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--non_gmock_flag=blah",
    "--gmock_verbose=error",
    NULL
  };
  const char* new_argv[] = {
    "foo.exe",
    "--non_gmock_flag=blah",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, "error");
}
References TestInitGoogleMock().
TEST() [4/13]
TEST (InitGoogleMockTest , ParsesInvalidCommandLine)
Definition at line 67 of file gmock_test.cc.
{
  const char* argv[] = {
    NULL
  };
  const char* new_argv[] = {
    NULL
  };
  TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
}
References GMOCK_FLAG, and TestInitGoogleMock().
TEST() [5/13]
TEST (InitGoogleMockTest , ParsesMultipleFlags)
Definition at line 108 of file gmock_test.cc.
{
  int old_default_behavior = GMOCK_FLAG(default_mock_behavior);
  const wchar_t* argv[] = {
    L"foo.exe",
    L"--gmock_verbose=info",
    L"--gmock_default_mock_behavior=2",
    NULL
  };
  const wchar_t* new_argv[] = {
    L"foo.exe",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, "info");
  EXPECT_EQ(2, GMOCK_FLAG(default_mock_behavior));
  EXPECT_NE(2, old_default_behavior);
  GMOCK_FLAG(default_mock_behavior) = old_default_behavior;
}
References EXPECT_EQ, EXPECT_NE, GMOCK_FLAG, and TestInitGoogleMock().
TEST() [6/13]
TEST (InitGoogleMockTest , ParsesSingleFlag)
Definition at line 93 of file gmock_test.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gmock_verbose=info",
    NULL
  };
  const char* new_argv[] = {
    "foo.exe",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, "info");
}
References TestInitGoogleMock().
TEST() [7/13]
TEST (InitGoogleMockTest , ParsesUnrecognizedFlag)
Definition at line 128 of file gmock_test.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--non_gmock_flag=blah",
    NULL
  };
  const char* new_argv[] = {
    "foo.exe",
    "--non_gmock_flag=blah",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
}
References GMOCK_FLAG, and TestInitGoogleMock().
TEST() [8/13]
TEST (WideInitGoogleMockTest , ParsesEmptyCommandLine)
Definition at line 173 of file gmock_test.cc.
{
  const wchar_t* argv[] = {
    L"foo.exe",
    NULL
  };
  const wchar_t* new_argv[] = {
    L"foo.exe",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
}
References GMOCK_FLAG, and TestInitGoogleMock().
TEST() [9/13]
TEST (WideInitGoogleMockTest , ParsesGoogleMockFlagAndUnrecognizedFlag)
Definition at line 238 of file gmock_test.cc.
{
  const wchar_t* argv[] = {
    L"foo.exe",
    L"--non_gmock_flag=blah",
    L"--gmock_verbose=error",
    NULL
  };
  const wchar_t* new_argv[] = {
    L"foo.exe",
    L"--non_gmock_flag=blah",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, "error");
}
References TestInitGoogleMock().
TEST() [10/13]
TEST (WideInitGoogleMockTest , ParsesInvalidCommandLine)
Definition at line 161 of file gmock_test.cc.
{
  const wchar_t* argv[] = {
    NULL
  };
  const wchar_t* new_argv[] = {
    NULL
  };
  TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
}
References GMOCK_FLAG, and TestInitGoogleMock().
TEST() [11/13]
TEST (WideInitGoogleMockTest , ParsesMultipleFlags)
Definition at line 202 of file gmock_test.cc.
{
  int old_default_behavior = GMOCK_FLAG(default_mock_behavior);
  const wchar_t* argv[] = {
    L"foo.exe",
    L"--gmock_verbose=info",
    L"--gmock_default_mock_behavior=2",
    NULL
  };
  const wchar_t* new_argv[] = {
    L"foo.exe",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, "info");
  EXPECT_EQ(2, GMOCK_FLAG(default_mock_behavior));
  EXPECT_NE(2, old_default_behavior);
  GMOCK_FLAG(default_mock_behavior) = old_default_behavior;
}
References EXPECT_EQ, EXPECT_NE, GMOCK_FLAG, and TestInitGoogleMock().
TEST() [12/13]
TEST (WideInitGoogleMockTest , ParsesSingleFlag)
Definition at line 187 of file gmock_test.cc.
{
  const wchar_t* argv[] = {
    L"foo.exe",
    L"--gmock_verbose=info",
    NULL
  };
  const wchar_t* new_argv[] = {
    L"foo.exe",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, "info");
}
References TestInitGoogleMock().
TEST() [13/13]
TEST (WideInitGoogleMockTest , ParsesUnrecognizedFlag)
Definition at line 222 of file gmock_test.cc.
{
  const wchar_t* argv[] = {
    L"foo.exe",
    L"--non_gmock_flag=blah",
    NULL
  };
  const wchar_t* new_argv[] = {
    L"foo.exe",
    L"--non_gmock_flag=blah",
    NULL
  };
  TestInitGoogleMock(argv, new_argv, GMOCK_FLAG(verbose));
}
References GMOCK_FLAG, and TestInitGoogleMock().
TestInitGoogleMock()
template<typename Char , int M, int N> void TestInitGoogleMock (const Char *(&) argv[M], const Char *(&) new_argv[N], const ::std::string & expected_gmock_verbose)
Definition at line 51 of file gmock_test.cc.
{
  const ::std::string old_verbose = GMOCK_FLAG(verbose);
  int argc = M - 1;
  InitGoogleMock(&argc, const_cast<Char**>(argv));
  ASSERT_EQ(N - 1, argc) << "The new argv has wrong number of elements.";
  for (int i = 0; i < N; i++) {
    EXPECT_STREQ(new_argv[i], argv[i]);
  }
  EXPECT_EQ(expected_gmock_verbose, GMOCK_FLAG(verbose).c_str());
  GMOCK_FLAG(verbose) = old_verbose;  // Restores the gmock_verbose flag.
}
References ASSERT_EQ, EXPECT_EQ, EXPECT_STREQ, and GMOCK_FLAG.