wiNpoS: rapidjson/thirdparty/gtest/googlemock/test/gmock_output_test_.cc File Reference
gmock_output_test_.cc File Reference
#include "gmock/gmock.h"
#include <stdio.h>
#include <string>
#include "gtest/gtest.h"
Classes
class MockFoo
class GMockOutputTest
Functions
TEST_F (GMockOutputTest, ExpectedCall)
TEST_F (GMockOutputTest, ExpectedCallToVoidFunction)
TEST_F (GMockOutputTest, ExplicitActionsRunOut)
TEST_F (GMockOutputTest, UnexpectedCall)
TEST_F (GMockOutputTest, UnexpectedCallToVoidFunction)
TEST_F (GMockOutputTest, ExcessiveCall)
TEST_F (GMockOutputTest, ExcessiveCallToVoidFunction)
TEST_F (GMockOutputTest, UninterestingCall)
TEST_F (GMockOutputTest, UninterestingCallToVoidFunction)
TEST_F (GMockOutputTest, RetiredExpectation)
TEST_F (GMockOutputTest, UnsatisfiedPrerequisite)
TEST_F (GMockOutputTest, UnsatisfiedPrerequisites)
TEST_F (GMockOutputTest, UnsatisfiedWith)
TEST_F (GMockOutputTest, UnsatisfiedExpectation)
TEST_F (GMockOutputTest, MismatchArguments)
TEST_F (GMockOutputTest, MismatchWith)
TEST_F (GMockOutputTest, MismatchArgumentsAndWith)
TEST_F (GMockOutputTest, UnexpectedCallWithDefaultAction)
TEST_F (GMockOutputTest, ExcessiveCallWithDefaultAction)
TEST_F (GMockOutputTest, UninterestingCallWithDefaultAction)
TEST_F (GMockOutputTest, ExplicitActionsRunOutWithDefaultAction)
TEST_F (GMockOutputTest, CatchesLeakedMocks)
MATCHER_P2 (IsPair, first, second, "")
TEST_F (GMockOutputTest, PrintsMatcher)
void TestCatchesLeakedMocksInAdHocTests ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 297 of file gmock_output_test_.cc.
{
  testing::InitGoogleMock(&argc, argv);
  // Ensures that the tests pass no matter what value of
  // --gmock_catch_leaked_mocks and --gmock_verbose the user specifies.
  testing::GMOCK_FLAG(catch_leaked_mocks) = true;
  testing::GMOCK_FLAG(verbose) = "warning";
  TestCatchesLeakedMocksInAdHocTests();
  return RUN_ALL_TESTS();
}
References testing::InitGoogleMock(), RUN_ALL_TESTS(), and TestCatchesLeakedMocksInAdHocTests().
MATCHER_P2()
MATCHER_P2 (IsPair , first , second , "")
Definition at line 278 of file gmock_output_test_.cc.
{
  return Value(arg.first, first) && Value(arg.second, second);
}
TEST_F() [1/23]
TEST_F (GMockOutputTest , CatchesLeakedMocks)
Definition at line 261 of file gmock_output_test_.cc.
{
  MockFoo* foo1 = new MockFoo;
  MockFoo* foo2 = new MockFoo;
  // Invokes ON_CALL on foo1.
  ON_CALL(*foo1, Bar(_, _, _)).WillByDefault(Return('a'));
  // Invokes EXPECT_CALL on foo2.
  EXPECT_CALL(*foo2, Bar2(_, _));
  EXPECT_CALL(*foo2, Bar2(1, _));
  EXPECT_CALL(*foo2, Bar3(_, _)).Times(AnyNumber());
  foo2->Bar2(2, 1);
  foo2->Bar2(1, 1);
  // Both foo1 and foo2 are deliberately leaked.
}
References EXPECT_CALL, and ON_CALL.
TEST_F() [2/23]
TEST_F (GMockOutputTest , ExcessiveCall)
Definition at line 115 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(0, _));
  foo_.Bar2(0, 0);  // Expected call
  foo_.Bar2(0, 1);  // Excessive call
}
References EXPECT_CALL.
TEST_F() [3/23]
TEST_F (GMockOutputTest , ExcessiveCallToVoidFunction)
Definition at line 122 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar3(0, _));
  foo_.Bar3(0, 0);  // Expected call
  foo_.Bar3(0, 1);  // Excessive call
}
References EXPECT_CALL.
TEST_F() [4/23]
TEST_F (GMockOutputTest , ExcessiveCallWithDefaultAction)
Definition at line 225 of file gmock_output_test_.cc.
{
  ON_CALL(foo_, Bar2(_, _))
      .WillByDefault(Return(true));   // Default action #1
  ON_CALL(foo_, Bar2(1, _))
      .WillByDefault(Return(false));  // Default action #2
  EXPECT_CALL(foo_, Bar2(2, 2));
  EXPECT_CALL(foo_, Bar2(1, 1));
  foo_.Bar2(2, 2);  // Expected call.
  foo_.Bar2(2, 2);  // Excessive call, takes default action #1.
  foo_.Bar2(1, 1);  // Expected call.
  foo_.Bar2(1, 1);  // Excessive call, takes default action #2.
}
References EXPECT_CALL, and ON_CALL.
TEST_F() [5/23]
TEST_F (GMockOutputTest , ExpectedCall)
Definition at line 75 of file gmock_output_test_.cc.
{
  testing::GMOCK_FLAG(verbose) = "info";
  EXPECT_CALL(foo_, Bar2(0, _));
  foo_.Bar2(0, 0);  // Expected call
  testing::GMOCK_FLAG(verbose) = "warning";
}
References EXPECT_CALL.
TEST_F() [6/23]
TEST_F (GMockOutputTest , ExpectedCallToVoidFunction)
Definition at line 84 of file gmock_output_test_.cc.
{
  testing::GMOCK_FLAG(verbose) = "info";
  EXPECT_CALL(foo_, Bar3(0, _));
  foo_.Bar3(0, 0);  // Expected call
  testing::GMOCK_FLAG(verbose) = "warning";
}
References EXPECT_CALL.
TEST_F() [7/23]
TEST_F (GMockOutputTest , ExplicitActionsRunOut)
Definition at line 93 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(_, _))
      .Times(2)
      .WillOnce(Return(false));
  foo_.Bar2(2, 2);
  foo_.Bar2(1, 1);  // Explicit actions in EXPECT_CALL run out.
}
References EXPECT_CALL.
TEST_F() [8/23]
TEST_F (GMockOutputTest , ExplicitActionsRunOutWithDefaultAction)
Definition at line 250 of file gmock_output_test_.cc.
{
  ON_CALL(foo_, Bar2(_, _))
      .WillByDefault(Return(true));   // Default action #1
  EXPECT_CALL(foo_, Bar2(_, _))
      .Times(2)
      .WillOnce(Return(false));
  foo_.Bar2(2, 2);
  foo_.Bar2(1, 1);  // Explicit actions in EXPECT_CALL run out.
}
References EXPECT_CALL, and ON_CALL.
TEST_F() [9/23]
TEST_F (GMockOutputTest , MismatchArguments)
Definition at line 189 of file gmock_output_test_.cc.
{
  const std::string s = "Hi";
  EXPECT_CALL(foo_, Bar(Ref(s), _, Ge(0)));
  foo_.Bar("Ho", 0, -0.1);  // Mismatch arguments
  foo_.Bar(s, 0, 0);
}
References EXPECT_CALL.
TEST_F() [10/23]
TEST_F (GMockOutputTest , MismatchArgumentsAndWith)
Definition at line 205 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(Ge(2), Ge(1)))
      .With(Ge());
  foo_.Bar2(1, 3);  // Mismatch arguments and mismatch With()
  foo_.Bar2(2, 1);
}
References EXPECT_CALL.
TEST_F() [11/23]
TEST_F (GMockOutputTest , MismatchWith)
Definition at line 197 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(Ge(2), Ge(1)))
      .With(Ge());
  foo_.Bar2(2, 3);  // Mismatch With()
  foo_.Bar2(2, 1);
}
References EXPECT_CALL.
TEST_F() [12/23]
TEST_F (GMockOutputTest , PrintsMatcher)
Definition at line 282 of file gmock_output_test_.cc.
{
  const testing::Matcher<int> m1 = Ge(48);
  EXPECT_THAT((std::pair<int, bool>(42, true)), IsPair(m1, true));
}
References EXPECT_THAT.
TEST_F() [13/23]
TEST_F (GMockOutputTest , RetiredExpectation)
Definition at line 137 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(_, _))
      .RetiresOnSaturation();
  EXPECT_CALL(foo_, Bar2(0, 0));
  foo_.Bar2(1, 1);
  foo_.Bar2(1, 1);  // Matches a retired expectation
  foo_.Bar2(0, 0);
}
References EXPECT_CALL.
TEST_F() [14/23]
TEST_F (GMockOutputTest , UnexpectedCall)
Definition at line 101 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(0, _));
  foo_.Bar2(1, 0);  // Unexpected call
  foo_.Bar2(0, 0);  // Expected call
}
References EXPECT_CALL.
TEST_F() [15/23]
TEST_F (GMockOutputTest , UnexpectedCallToVoidFunction)
Definition at line 108 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar3(0, _));
  foo_.Bar3(1, 0);  // Unexpected call
  foo_.Bar3(0, 0);  // Expected call
}
References EXPECT_CALL.
TEST_F() [16/23]
TEST_F (GMockOutputTest , UnexpectedCallWithDefaultAction)
Definition at line 213 of file gmock_output_test_.cc.
{
  ON_CALL(foo_, Bar2(_, _))
      .WillByDefault(Return(true));   // Default action #1
  ON_CALL(foo_, Bar2(1, _))
      .WillByDefault(Return(false));  // Default action #2
  EXPECT_CALL(foo_, Bar2(2, 2));
  foo_.Bar2(1, 0);  // Unexpected call, takes default action #2.
  foo_.Bar2(0, 0);  // Unexpected call, takes default action #1.
  foo_.Bar2(2, 2);  // Expected call.
}
References EXPECT_CALL, and ON_CALL.
TEST_F() [17/23]
TEST_F (GMockOutputTest , UninterestingCall)
Definition at line 129 of file gmock_output_test_.cc.
{
  foo_.Bar2(0, 1);  // Uninteresting call
}
TEST_F() [18/23]
TEST_F (GMockOutputTest , UninterestingCallToVoidFunction)
Definition at line 133 of file gmock_output_test_.cc.
{
  foo_.Bar3(0, 1);  // Uninteresting call
}
TEST_F() [19/23]
TEST_F (GMockOutputTest , UninterestingCallWithDefaultAction)
Definition at line 240 of file gmock_output_test_.cc.
{
  ON_CALL(foo_, Bar2(_, _))
      .WillByDefault(Return(true));   // Default action #1
  ON_CALL(foo_, Bar2(1, _))
      .WillByDefault(Return(false));  // Default action #2
  foo_.Bar2(2, 2);  // Uninteresting call, takes default action #1.
  foo_.Bar2(1, 1);  // Uninteresting call, takes default action #2.
}
References ON_CALL.
TEST_F() [20/23]
TEST_F (GMockOutputTest , UnsatisfiedExpectation)
Definition at line 181 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar(_, _, _));
  EXPECT_CALL(foo_, Bar2(0, _))
      .Times(2);
  foo_.Bar2(0, 1);
}
References EXPECT_CALL.
TEST_F() [21/23]
TEST_F (GMockOutputTest , UnsatisfiedPrerequisite)
Definition at line 147 of file gmock_output_test_.cc.
{
  {
    InSequence s;
    EXPECT_CALL(foo_, Bar(_, 0, _));
    EXPECT_CALL(foo_, Bar2(0, 0));
    EXPECT_CALL(foo_, Bar2(1, _));
  }
  foo_.Bar2(1, 0);  // Has one immediate unsatisfied pre-requisite
  foo_.Bar("Hi", 0, 0);
  foo_.Bar2(0, 0);
  foo_.Bar2(1, 0);
}
References EXPECT_CALL.
TEST_F() [22/23]
TEST_F (GMockOutputTest , UnsatisfiedPrerequisites)
Definition at line 161 of file gmock_output_test_.cc.
{
  Sequence s1, s2;
  EXPECT_CALL(foo_, Bar(_, 0, _))
      .InSequence(s1);
  EXPECT_CALL(foo_, Bar2(0, 0))
      .InSequence(s2);
  EXPECT_CALL(foo_, Bar2(1, _))
      .InSequence(s1, s2);
  foo_.Bar2(1, 0);  // Has two immediate unsatisfied pre-requisites
  foo_.Bar("Hi", 0, 0);
  foo_.Bar2(0, 0);
  foo_.Bar2(1, 0);
}
References EXPECT_CALL.
TEST_F() [23/23]
TEST_F (GMockOutputTest , UnsatisfiedWith)
Definition at line 177 of file gmock_output_test_.cc.
{
  EXPECT_CALL(foo_, Bar2(_, _)).With(Ge());
}
References EXPECT_CALL.
TestCatchesLeakedMocksInAdHocTests()
void TestCatchesLeakedMocksInAdHocTests ()
Definition at line 287 of file gmock_output_test_.cc.
{
  MockFoo* foo = new MockFoo;
  // Invokes EXPECT_CALL on foo.
  EXPECT_CALL(*foo, Bar2(_, _));
  foo->Bar2(2, 1);
  // foo is deliberately leaked.
}
References EXPECT_CALL.