wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_list_tests_unittest_.cc File Reference
gtest_list_tests_unittest_.cc File Reference
#include "gtest/gtest.h"
Classes
class FooTest
class MyType
class ValueParamTest
class VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName
class TypedTest< T >
class MyArray< T, kSize >
class TypeParamTest< T >
Typedefs
typedef testing::Types< VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName, int *, MyArray< bool, 42 > > MyTypes
Functions
TEST (Foo, Bar1)
TEST (Foo, Bar2)
TEST (Foo, DISABLED_Bar3)
TEST (Abc, Xyz)
TEST (Abc, Def)
TEST (FooBar, Baz)
TEST_F (FooTest, Test1)
TEST_F (FooTest, DISABLED_Test2)
TEST_F (FooTest, Test3)
TEST (FooDeathTest, Test1)
void PrintTo (const MyType &x, std::ostream *os)
TEST_P (ValueParamTest, TestA)
TEST_P (ValueParamTest, TestB)
INSTANTIATE_TEST_CASE_P (MyInstantiation, ValueParamTest, testing::Values(MyType("one line"), MyType("two\nlines"), MyType("a very\nloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line")))
TYPED_TEST_CASE (TypedTest, MyTypes)
TYPED_TEST (TypedTest, TestA)
TYPED_TEST (TypedTest, TestB)
TYPED_TEST_CASE_P (TypeParamTest)
TYPED_TEST_P (TypeParamTest, TestA)
TYPED_TEST_P (TypeParamTest, TestB)
REGISTER_TYPED_TEST_CASE_P (TypeParamTest, TestA, TestB)
INSTANTIATE_TYPED_TEST_CASE_P (My, TypeParamTest, MyTypes)
int main (int argc, char **argv)
Typedef Documentation
MyTypes
typedef testing::Types<VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName, int*, MyArray<bool, 42> > MyTypes
Definition at line 125 of file gtest_list_tests_unittest_.cc.
Function Documentation
INSTANTIATE_TEST_CASE_P()
INSTANTIATE_TEST_CASE_P (MyInstantiation , ValueParamTest , testing::Values(MyType("one line"), MyType("two\nlines"), MyType("a very\nloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line")))
INSTANTIATE_TYPED_TEST_CASE_P()
INSTANTIATE_TYPED_TEST_CASE_P (My , TypeParamTest , MyTypes)
main()
int main (int argc, char ** argv)
Definition at line 153 of file gtest_list_tests_unittest_.cc.
{
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
References testing::InitGoogleTest(), and RUN_ALL_TESTS().
PrintTo()
void PrintTo (const MyType & x, std::ostream * os)
Definition at line 90 of file gtest_list_tests_unittest_.cc.
{
  *os << x.value();
}
References MyType::value().
REGISTER_TYPED_TEST_CASE_P()
REGISTER_TYPED_TEST_CASE_P (TypeParamTest , TestA , TestB)
TEST() [1/7]
TEST (Abc , Def)
Definition at line 56 of file gtest_list_tests_unittest_.cc.
               {
}
TEST() [2/7]
TEST (Abc , Xyz)
Definition at line 53 of file gtest_list_tests_unittest_.cc.
               {
}
TEST() [3/7]
TEST (Foo , Bar1)
Definition at line 44 of file gtest_list_tests_unittest_.cc.
                {
}
TEST() [4/7]
TEST (Foo , Bar2)
Definition at line 47 of file gtest_list_tests_unittest_.cc.
                {
}
TEST() [5/7]
TEST (Foo , DISABLED_Bar3)
Definition at line 50 of file gtest_list_tests_unittest_.cc.
{
}
TEST() [6/7]
TEST (FooBar , Baz)
Definition at line 59 of file gtest_list_tests_unittest_.cc.
                  {
}
TEST() [7/7]
TEST (FooDeathTest , Test1)
Definition at line 74 of file gtest_list_tests_unittest_.cc.
{
}
TEST_F() [1/3]
TEST_F (FooTest , DISABLED_Test2)
Definition at line 68 of file gtest_list_tests_unittest_.cc.
{
}
TEST_F() [2/3]
TEST_F (FooTest , Test1)
Definition at line 65 of file gtest_list_tests_unittest_.cc.
                       {
}
TEST_F() [3/3]
TEST_F (FooTest , Test3)
Definition at line 71 of file gtest_list_tests_unittest_.cc.
                       {
}
TEST_P() [1/2]
TEST_P (ValueParamTest , TestA)
Definition at line 97 of file gtest_list_tests_unittest_.cc.
{
}
TEST_P() [2/2]
TEST_P (ValueParamTest , TestB)
Definition at line 100 of file gtest_list_tests_unittest_.cc.
{
}
TYPED_TEST() [1/2]
TYPED_TEST (TypedTest , TestA)
Definition at line 129 of file gtest_list_tests_unittest_.cc.
{
}
TYPED_TEST() [2/2]
TYPED_TEST (TypedTest , TestB)
Definition at line 132 of file gtest_list_tests_unittest_.cc.
{
}
TYPED_TEST_CASE()
TYPED_TEST_CASE (TypedTest , MyTypes)
TYPED_TEST_CASE_P()
TYPED_TEST_CASE_P (TypeParamTest)
TYPED_TEST_P() [1/2]
TYPED_TEST_P (TypeParamTest , TestA)
Definition at line 143 of file gtest_list_tests_unittest_.cc.
{
}
TYPED_TEST_P() [2/2]
TYPED_TEST_P (TypeParamTest , TestB)
Definition at line 146 of file gtest_list_tests_unittest_.cc.
{
}