wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_throw_on_failure_ex_test.cc File Reference
gtest_throw_on_failure_ex_test.cc File Reference
#include "gtest/gtest.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdexcept>
Functions
void Fail (const char *msg)
void TestFailureThrowsRuntimeError ()
int main (int argc, char **argv)
Function Documentation
Fail()
void Fail (const char * msg)
Definition at line 45 of file gtest_throw_on_failure_ex_test.cc.
{
  printf("FAILURE: %s\n", msg);
  fflush(stdout);
  exit(1);
}
main()
int main (int argc, char ** argv)
Definition at line 81 of file gtest_throw_on_failure_ex_test.cc.
{
  testing::InitGoogleTest(&argc, argv);
  // We want to ensure that people can use Google Test assertions in
  // other testing frameworks, as long as they initialize Google Test
  // properly and set the thrown-on-failure mode.  Therefore, we don't
  // use Google Test's constructs for defining and running tests
  // (e.g. TEST and RUN_ALL_TESTS) here.
  TestFailureThrowsRuntimeError();
  return 0;
}
References testing::InitGoogleTest(), and TestFailureThrowsRuntimeError().
TestFailureThrowsRuntimeError()
void TestFailureThrowsRuntimeError ()
Definition at line 53 of file gtest_throw_on_failure_ex_test.cc.
{
  testing::GTEST_FLAG(throw_on_failure) = true;
  // A successful assertion shouldn't throw.
  try {
    EXPECT_EQ(3, 3);
  } catch(...) {
    Fail("A successful assertion wrongfully threw.");
  }
  // A failed assertion should throw a subclass of std::runtime_error.
  try {
    EXPECT_EQ(2, 3) << "Expected failure";
  } catch(const std::runtime_error& e) {
    if (strstr(e.what(), "Expected failure") != NULL)
      return;
    printf("%s",
           "A failed assertion did throw an exception of the right type, "
           "but the message is incorrect.  Instead of containing \"Expected "
           "failure\", it is:\n");
    Fail(e.what());
  } catch(...) {
    Fail("A failed assertion threw the wrong type of exception.");
  }
  Fail("A failed assertion should've thrown but didn't.");
}
References EXPECT_EQ, and Fail().