wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_repeat_test.cc File Reference
gtest_repeat_test.cc File Reference
#include <stdlib.h>
#include <iostream>
#include "gtest/gtest.h"
#include "src/gtest-internal-inl.h"
Classes
class anonymous_namespace{gtest_repeat_test.cc}::MyEnvironment
class anonymous_namespace{gtest_repeat_test.cc}::MyParamTest
Namespaces
namespace testing
namespace anonymous_namespace{gtest_repeat_test.cc}
Macros
#define GTEST_CHECK_INT_EQ_(expected, actual)
Functions
testing::GTEST_DECLARE_string_ (death_test_style)
testing::GTEST_DECLARE_string_ (filter)
testing::GTEST_DECLARE_int32_ (repeat)
anonymous_namespace{gtest_repeat_test.cc}::TEST (FooTest, ShouldFail)
anonymous_namespace{gtest_repeat_test.cc}::TEST (FooTest, ShouldPass)
anonymous_namespace{gtest_repeat_test.cc}::TEST (BarDeathTest, ThreadSafeAndFast)
anonymous_namespace{gtest_repeat_test.cc}::TEST_P (MyParamTest, ShouldPass)
anonymous_namespace{gtest_repeat_test.cc}::INSTANTIATE_TEST_CASE_P (MyParamSequence, MyParamTest, testing::Range(0, kNumberOfParamTests))
void anonymous_namespace{gtest_repeat_test.cc}::ResetCounts ()
void anonymous_namespace{gtest_repeat_test.cc}::CheckCounts (int expected)
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatUnspecified ()
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeat (int repeat)
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithEmptyFilter (int repeat)
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithFilterForSuccessfulTests (int repeat)
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithFilterForFailedTests (int repeat)
int main (int argc, char **argv)
Variables
int anonymous_namespace{gtest_repeat_test.cc}::g_environment_set_up_count = 0
int anonymous_namespace{gtest_repeat_test.cc}::g_environment_tear_down_count = 0
int anonymous_namespace{gtest_repeat_test.cc}::g_should_fail_count = 0
int anonymous_namespace{gtest_repeat_test.cc}::g_should_pass_count = 0
int anonymous_namespace{gtest_repeat_test.cc}::g_death_test_count = 0
int anonymous_namespace{gtest_repeat_test.cc}::g_param_test_count = 0
const int anonymous_namespace{gtest_repeat_test.cc}::kNumberOfParamTests = 10
Macro Definition Documentation
GTEST_CHECK_INT_EQ_
#define GTEST_CHECK_INT_EQ_ (expected, actual)
Value:
  do {\
    const int expected_val = (expected);\
    const int actual_val = (actual);\
    if (::testing::internal::IsTrue(expected_val != actual_val)) {\
      ::std::cout << "Value of: " #actual "\n"\
                  << "  Actual: " << actual_val << "\n"\
                  << "Expected: " #expected "\n"\
                  << "Which is: " << expected_val << "\n";\
      ::testing::internal::posix::Abort();\
    }\
  } while (::testing::internal::AlwaysFalse())
Definition at line 55 of file gtest_repeat_test.cc.
     {\
    const int expected_val = (expected);\
    const int actual_val = (actual);\
    if (::testing::internal::IsTrue(expected_val != actual_val)) {\
      ::std::cout << "Value of: " #actual "\n"\
                  << "  Actual: " << actual_val << "\n"\
                  << "Expected: " #expected "\n"\
                  << "Which is: " << expected_val << "\n";\
      ::testing::internal::posix::Abort();\
    }\
  } while (::testing::internal::AlwaysFalse())
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 211 of file gtest_repeat_test.cc.
{
  testing::InitGoogleTest(&argc, argv);
  testing::AddGlobalTestEnvironment(new MyEnvironment);
  TestRepeatUnspecified();
  TestRepeat(0);
  TestRepeat(1);
  TestRepeat(5);
  TestRepeatWithEmptyFilter(2);
  TestRepeatWithEmptyFilter(3);
  TestRepeatWithFilterForSuccessfulTests(3);
  TestRepeatWithFilterForFailedTests(4);
  // It would be nice to verify that the tests indeed loop forever
  // when GTEST_FLAG(repeat) is negative, but this test will be quite
  // complicated to write.  Since this flag is for interactive
  // debugging only and doesn't affect the normal test result, such a
  // test would be an overkill.
  printf("PASS\n");
  return 0;
}
References testing::AddGlobalTestEnvironment(), testing::InitGoogleTest(), anonymous_namespace{gtest_repeat_test.cc}::TestRepeat(), anonymous_namespace{gtest_repeat_test.cc}::TestRepeatUnspecified(), anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithEmptyFilter(), anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithFilterForFailedTests(), and anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithFilterForSuccessfulTests().