wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_unittest.cc File Reference
gtest_unittest.cc File Reference
#include "gtest/gtest.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <map>
#include <vector>
#include <ostream>
#include "gtest/gtest-spi.h"
#include "src/gtest-internal-inl.h"
Classes
class testing::internal::TestEventListenersAccessor
class testing::internal::UnitTestRecordPropertyTestHelper
class TestingVector
class anonymous_namespace{gtest_unittest.cc}::SubClassOfTest
class anonymous_namespace{gtest_unittest.cc}::AnotherSubClassOfTest
class anonymous_namespace{gtest_unittest.cc}::FormatEpochTimeInMillisAsIso8601Test
class anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest
class anonymous_namespace{gtest_unittest.cc}::ScopedFakeTestPartResultReporterTest
class anonymous_namespace{gtest_unittest.cc}::TestResultTest
class anonymous_namespace{gtest_unittest.cc}::GTestFlagSaverTest
class anonymous_namespace{gtest_unittest.cc}::ShouldShardTest
class anonymous_namespace{gtest_unittest.cc}::UnitTestRecordPropertyTest
class anonymous_namespace{gtest_unittest.cc}::UnitTestRecordPropertyTestEnvironment
struct anonymous_namespace{gtest_unittest.cc}::IsEvenFunctor
struct anonymous_namespace{gtest_unittest.cc}::AssertIsEvenFunctor
struct anonymous_namespace{gtest_unittest.cc}::SumIsEven3Functor
struct anonymous_namespace{gtest_unittest.cc}::AssertSumIsEven5Functor
class anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >
struct anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues
class anonymous_namespace{gtest_unittest.cc}::DisabledTestsTest
class anonymous_namespace{gtest_unittest.cc}::SingleEvaluationTest
class anonymous_namespace{gtest_unittest.cc}::NoFatalFailureTest
class anonymous_namespace{gtest_unittest.cc}::Uncopyable
class anonymous_namespace{gtest_unittest.cc}::UnprintableChar
class anonymous_namespace{gtest_unittest.cc}::Foo
class anonymous_namespace{gtest_unittest.cc}::FRIEND_TEST_Test2
class anonymous_namespace{gtest_unittest.cc}::TestLifeCycleTest
struct ConvertibleToAssertionResult
class Base
class anonymous_namespace{gtest_unittest.cc}::MyTypeInUnnamedNameSpace
class namespace1::MyTypeInNameSpace1
class namespace2::MyTypeInNameSpace2
class testing::TestInfoTest
class testing::CodeLocationForTESTF
class testing::CodeLocationForTESTP
class testing::CodeLocationForTYPEDTEST< T >
class testing::CodeLocationForTYPEDTESTP< T >
class testing::SetUpTestCaseTest
struct testing::Flags
class testing::ParseFlagsTest
class testing::CurrentTestInfoTest
class my_namespace::testing::Test
class my_namespace::testing::Message
class my_namespace::testing::AssertionResult
class ProtectedFixtureMethodsTest
class StaticAssertTypeEqTestHelper< T >
class TestListener
class SequenceTestingListener
class ConversionHelperBase
class ConversionHelperDerived
class NonContainer
struct AHashTable
struct NotReallyAHashTable
class AdHocTestResultTest
Namespaces
namespace testing
namespace testing::internal
namespace anonymous_namespace{gtest_unittest.cc}
namespace namespace1
namespace namespace2
namespace my_namespace
namespace my_namespace::testing
Macros
#define GTEST_USE_UNPROTECTED_COMMA_ global_var++, global_var++
#define VERIFY_CODE_LOCATION
#define GTEST_TEST_PARSING_FLAGS_(argv1, argv2, expected, should_print_help)
Typedefs
typedef ScopedFakeTestPartResultReporterTest anonymous_namespace{gtest_unittest.cc}::ExpectFatalFailureTest
typedef ScopedFakeTestPartResultReporterTest anonymous_namespace{gtest_unittest.cc}::ExpectNonfatalFailureTest
typedef TestResultTest anonymous_namespace{gtest_unittest.cc}::TestResultDeathTest
typedef ShouldShardTest anonymous_namespace{gtest_unittest.cc}::ShouldShardDeathTest
typedef FloatingPointTest< float > anonymous_namespace{gtest_unittest.cc}::FloatTest
typedef FloatingPointTest< double > anonymous_namespace{gtest_unittest.cc}::DoubleTest
typedef int IntAlias
Enumerations
enum anonymous_namespace{gtest_unittest.cc}::NamedEnum { anonymous_namespace{gtest_unittest.cc}::kE1 = 0 , anonymous_namespace{gtest_unittest.cc}::kE2 = 1 }
enum { anonymous_namespace{gtest_unittest.cc}::kCaseA = -1 , anonymous_namespace{gtest_unittest.cc}::kCaseB = INT_MAX , anonymous_namespace{gtest_unittest.cc}::kCaseC = 42 }
Functions
TEST (CommandLineFlagsTest, CanBeAccessedInCodeOnceGTestHIsIncluded)
::std::ostream & operator<< (::std::ostream &os, const TestingVector &vector)
anonymous_namespace{gtest_unittest.cc}::TEST (GetRandomSeedFromFlagTest, HandlesZero)
anonymous_namespace{gtest_unittest.cc}::TEST (GetRandomSeedFromFlagTest, PreservesValidSeed)
anonymous_namespace{gtest_unittest.cc}::TEST (GetRandomSeedFromFlagTest, NormalizesInvalidSeed)
anonymous_namespace{gtest_unittest.cc}::TEST (GetNextRandomSeedTest, WorksForValidInput)
static void anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults ()
anonymous_namespace{gtest_unittest.cc}::TEST (GetTypeIdTest, ReturnsSameValueForSameType)
anonymous_namespace{gtest_unittest.cc}::TEST (GetTypeIdTest, ReturnsDifferentValuesForDifferentTypes)
anonymous_namespace{gtest_unittest.cc}::TEST (GetTestTypeIdTest, ReturnsTheSameValueInsideOrOutsideOfGoogleTest)
anonymous_namespace{gtest_unittest.cc}::TEST (CanonicalizeForStdLibVersioning, LeavesUnversionedNamesUnchanged)
anonymous_namespace{gtest_unittest.cc}::TEST (CanonicalizeForStdLibVersioning, ElidesDoubleUnderNames)
anonymous_namespace{gtest_unittest.cc}::TEST (FormatTimeInMillisAsSecondsTest, FormatsZero)
anonymous_namespace{gtest_unittest.cc}::TEST (FormatTimeInMillisAsSecondsTest, FormatsPositiveNumber)
anonymous_namespace{gtest_unittest.cc}::TEST (FormatTimeInMillisAsSecondsTest, FormatsNegativeNumber)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test, PrintsTwoDigitSegments)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test, MillisecondsDoNotAffectResult)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test, PrintsLeadingZeroes)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test, Prints24HourTime)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test, PrintsEpochStart)
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test, CanEncodeNul)
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test, CanEncodeAscii)
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test, CanEncode8To11Bits)
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test, CanEncode12To16Bits)
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test, CanEncode17To21Bits)
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test, CanEncodeInvalidCodePoint)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, CanEncodeNul)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, CanEncodeAscii)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, CanEncode8To11Bits)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, CanEncode12To16Bits)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, StopsOnNulCharacter)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, StopsWhenLengthLimitReached)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, CanEncode17To21Bits)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, CanEncodeInvalidCodePoint)
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test, ConcatenatesCodepointsCorrectly)
anonymous_namespace{gtest_unittest.cc}::TEST (RandomDeathTest, GeneratesCrashesOnInvalidRange)
anonymous_namespace{gtest_unittest.cc}::TEST (RandomTest, GeneratesNumbersWithinRange)
anonymous_namespace{gtest_unittest.cc}::TEST (RandomTest, RepeatsWhenReseeded)
static bool anonymous_namespace{gtest_unittest.cc}::IsPositive (int n)
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityTest, CountIf)
static void anonymous_namespace{gtest_unittest.cc}::Accumulate (int n)
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityTest, ForEach)
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityTest, GetElementOr)
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityDeathTest, ShuffleRange)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, HandlesEmptyRange)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, HandlesRangeOfSizeOne)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, ShufflesEntireVector)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, ShufflesStartOfVector)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, ShufflesEndOfVector)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, ShufflesMiddleOfVector)
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest, ShufflesRepeatably)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertHelperTest, AssertHelperIsSmall)
anonymous_namespace{gtest_unittest.cc}::TEST (StringTest, EndsWithCaseInsensitive)
anonymous_namespace{gtest_unittest.cc}::TEST (StringTest, CaseInsensitiveWideCStringEquals)
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest, StringValue)
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest, ReplaceStringValue)
static void anonymous_namespace{gtest_unittest.cc}::AddFatalFailure ()
static void anonymous_namespace{gtest_unittest.cc}::AddNonfatalFailure ()
anonymous_namespace{gtest_unittest.cc}::TEST_F (ScopedFakeTestPartResultReporterTest, InterceptsTestFailures)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ScopedFakeTestPartResultReporterTest, DeprecatedConstructor)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest, CatchesFatalFaliure)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest, AcceptsStdStringObject)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest, CatchesFatalFailureOnAllThreads)
int anonymous_namespace{gtest_unittest.cc}::NonVoidFunction ()
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest, CanBeUsedInNonVoidFunction)
void anonymous_namespace{gtest_unittest.cc}::DoesNotAbortHelper (bool *aborted)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest, DoesNotAbort)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest, AcceptsMacroThatExpandsToUnprotectedComma)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectNonfatalFailureTest, CatchesNonfatalFailure)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectNonfatalFailureTest, CatchesNonfatalFailureOnAllThreads)
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest, ConstructorWorks)
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest, SetValue)
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultTest, total_part_count)
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultTest, Passed)
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultTest, Failed)
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultDeathTest, GetTestPartResult)
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest, NoPropertiesFoundWhenNoneAreAdded)
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest, OnePropertyFoundWhenAdded)
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest, MultiplePropertiesFoundWhenAdded)
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest, OverridesValuesForDuplicateKeys)
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest, GetTestProperty)
anonymous_namespace{gtest_unittest.cc}::TEST_F (GTestFlagSaverTest, ModifyGTestFlags)
anonymous_namespace{gtest_unittest.cc}::TEST_F (GTestFlagSaverTest, VerifyGTestFlags)
static void anonymous_namespace{gtest_unittest.cc}::SetEnv (const char *name, const char *value)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest, ReturnsDefaultWhenVariableIsNotSet)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest, ReturnsDefaultWhenValueOverflows)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest, ReturnsDefaultWhenValueIsInvalid)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest, ParsesAndReturnsValidValue)
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest, ReturnsFalseForInvalidFlag)
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest, ReturnsDefaultWhenValueOverflows)
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest, ReturnsDefaultWhenValueIsInvalid)
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest, ParsesAndReturnsValidValue)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromEnvOrDieTest, ParsesAndReturnsValidValue)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromEnvOrDieDeathTest, AbortsOnFailure)
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromEnvOrDieDeathTest, AbortsOnInt32Overflow)
anonymous_namespace{gtest_unittest.cc}::TEST (ShouldRunTestOnShardTest, IsPartitionWhenThereIsOneShard)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardTest, ReturnsFalseWhenNeitherEnvVarIsSet)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardTest, ReturnsFalseWhenTotalShardIsOne)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardTest, WorksWhenShardEnvVarsAreValid)
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardDeathTest, AbortsWhenShardingEnvVarsAreInvalid)
anonymous_namespace{gtest_unittest.cc}::TEST (ShouldRunTestOnShardTest, IsPartitionWhenThereAreFiveShards)
anonymous_namespace{gtest_unittest.cc}::TEST (UnitTestTest, CanGetOriginalWorkingDir)
anonymous_namespace{gtest_unittest.cc}::TEST (UnitTestTest, ReturnsPlausibleTimestamp)
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKey (const TestResult &test_result, const char *key)
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest (const char *key)
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase (const char *key)
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyOutsideOfTestCase (const char *key)
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest, OnePropertyFoundWhenAdded)
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest, MultiplePropertiesFoundWhenAdded)
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest, OverridesValuesForDuplicateKeys)
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest, AddFailureInsideTestsWhenUsingTestCaseReservedKeys)
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest, AddRecordWithReservedKeysGeneratesCorrectPropertyList)
bool anonymous_namespace{gtest_unittest.cc}::IsEven (int n)
AssertionResult anonymous_namespace{gtest_unittest.cc}::AssertIsEven (const char *expr, int n)
AssertionResult anonymous_namespace{gtest_unittest.cc}::ResultIsEven (int n)
AssertionResult anonymous_namespace{gtest_unittest.cc}::ResultIsEvenNoExplanation (int n)
bool anonymous_namespace{gtest_unittest.cc}::SumIsEven2 (int n1, int n2)
AssertionResult anonymous_namespace{gtest_unittest.cc}::AssertSumIsEven4 (const char *e1, const char *e2, const char *e3, const char *e4, int n1, int n2, int n3, int n4)
anonymous_namespace{gtest_unittest.cc}::TEST (Pred1Test, WithoutFormat)
anonymous_namespace{gtest_unittest.cc}::TEST (Pred1Test, WithFormat)
anonymous_namespace{gtest_unittest.cc}::TEST (Pred1Test, SingleEvaluationOnFailure)
anonymous_namespace{gtest_unittest.cc}::TEST (PredTest, WithoutFormat)
anonymous_namespace{gtest_unittest.cc}::TEST (PredTest, WithFormat)
anonymous_namespace{gtest_unittest.cc}::TEST (PredTest, SingleEvaluationOnFailure)
bool anonymous_namespace{gtest_unittest.cc}::IsPositive (double x)
template<typename T >
bool anonymous_namespace{gtest_unittest.cc}::IsNegative (T x)
template<typename T1 , typename T2 >
bool anonymous_namespace{gtest_unittest.cc}::GreaterThan (T1 x1, T2 x2)
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateAssertionTest, AcceptsOverloadedFunction)
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateAssertionTest, AcceptsTemplateFunction)
AssertionResult anonymous_namespace{gtest_unittest.cc}::IsPositiveFormat (const char *, int n)
AssertionResult anonymous_namespace{gtest_unittest.cc}::IsPositiveFormat (const char *, double x)
template<typename T >
AssertionResult anonymous_namespace{gtest_unittest.cc}::IsNegativeFormat (const char *, T x)
template<typename T1 , typename T2 >
AssertionResult anonymous_namespace{gtest_unittest.cc}::EqualsFormat (const char *, const char *, const T1 &x1, const T2 &x2)
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateFormatAssertionTest, AcceptsOverloadedFunction)
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateFormatAssertionTest, AcceptsTemplateFunction)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, ASSERT_STREQ)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, ASSERT_STREQ_Null)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, ASSERT_STREQ_Null2)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, ASSERT_STRNE)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, ASSERT_STRCASEEQ)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, ASSERT_STRCASENE)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, STREQ_Wide)
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest, STRNE_Wide)
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest, ReturnsCorrectResultForCString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest, ReturnsCorrectResultForWideCString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest, GeneratesCorrectMessageForCString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest, ReturnsCorrectResultsForStdString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest, ReturnsCorrectResultForCString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest, ReturnsCorrectResultForWideCString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest, GeneratesCorrectMessageForWideCString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest, ReturnsCorrectResultsForStdString)
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest, GeneratesCorrectMessageForStdString)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, Size)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, Zeros)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, AlmostZeros)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, SmallDiff)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, LargeDiff)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, Infinity)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, NaN)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, Reflexive)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, Commutative)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, EXPECT_NEAR)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, ASSERT_NEAR)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, FloatLESucceeds)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest, FloatLEFails)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, Size)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, Zeros)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, AlmostZeros)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, SmallDiff)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, LargeDiff)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, Infinity)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, NaN)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, Reflexive)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, Commutative)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, EXPECT_NEAR)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, ASSERT_NEAR)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, DoubleLESucceeds)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest, DoubleLEFails)
anonymous_namespace{gtest_unittest.cc}::TEST (DisabledTest, DISABLED_TestShouldNotRun)
anonymous_namespace{gtest_unittest.cc}::TEST (DisabledTest, NotDISABLED_TestShouldRun)
anonymous_namespace{gtest_unittest.cc}::TEST (DISABLED_TestCase, TestShouldNotRun)
anonymous_namespace{gtest_unittest.cc}::TEST (DISABLED_TestCase, DISABLED_TestShouldNotRun)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DisabledTestsTest, DISABLED_TestShouldNotRun_1)
anonymous_namespace{gtest_unittest.cc}::TEST_F (DisabledTestsTest, DISABLED_TestShouldNotRun_2)
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest, FailedASSERT_STREQ)
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest, ASSERT_STR)
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest, FailedASSERT_NE)
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest, OtherCases)
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest, NoFailure)
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest, NonFatalIsNoFailure)
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest, AssertNoFatalFailureOnFatalFailure)
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest, ExpectNoFatalFailureOnFatalFailure)
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest, MessageIsStreamable)
std::string anonymous_namespace{gtest_unittest.cc}::EditsToString (const std::vector< EditType > &edits)
std::vector< size_t > anonymous_namespace{gtest_unittest.cc}::CharsToIndices (const std::string &str)
std::vector< std::string > anonymous_namespace{gtest_unittest.cc}::CharsToLines (const std::string &str)
anonymous_namespace{gtest_unittest.cc}::TEST (EditDistance, TestCases)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, EqFailure)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, EqFailureWithDiff)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, AppendUserMessage)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_TRUE)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, AssertTrueWithAssertionResult)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_FALSE)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, AssertFalseWithAssertionResult)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, ASSERT_EQ_Double)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_EQ)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, ASSERT_EQ_0)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_NE)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_LE)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_LT)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_GE)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ASSERT_GT)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, AssertPrecedence)
void anonymous_namespace{gtest_unittest.cc}::TestEq1 (int x)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, NonFixtureSubroutine)
::std::ostream & anonymous_namespace{gtest_unittest.cc}::operator<< (::std::ostream &os, const Uncopyable &value)
bool anonymous_namespace{gtest_unittest.cc}::IsPositiveUncopyable (const Uncopyable &x)
void anonymous_namespace{gtest_unittest.cc}::TestAssertNonPositive ()
void anonymous_namespace{gtest_unittest.cc}::TestAssertEqualsUncopyable ()
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, AssertWorksWithUncopyableObject)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, ExpectWorksWithUncopyableObject)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, NamedEnum)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest, AnonymousEnum)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionSyntaxTest, BasicAssertionsBehavesLikeSingleStatement)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionSyntaxTest, NoFatalFailureAssertionsBehavesLikeSingleStatement)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionSyntaxTest, WorksWithSwitch)
testing::TEST (SuccessfulAssertionTest, SUCCEED)
testing::TEST (SuccessfulAssertionTest, EXPECT)
testing::TEST (SuccessfulAssertionTest, EXPECT_STR)
testing::TEST (SuccessfulAssertionTest, ASSERT)
testing::TEST (SuccessfulAssertionTest, ASSERT_STR)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, EXPECT)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, ASSERT)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, ASSERT_STR)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, ASSERT_FLOATING)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, ASSERT_FALSE)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, FAIL)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, SUCCEED)
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest, ASSERT_TRUE)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_TRUE)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, ExpectTrueWithAssertionResult)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_FALSE)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, ExpectFalseWithAssertionResult)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_EQ)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_EQ_Double)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_EQ_0)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_NE)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_LE)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_LT)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_GE)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, EXPECT_GT)
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest, ExpectPrecedence)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest, Scalar)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest, Pointer)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest, NullPointer)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest, CString)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest, NullCString)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest, string)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest, stringWithEmbeddedNUL)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest, NULChar)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest, int)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest, NullCharPtr)
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest, BasicIoManip)
void anonymous_namespace{gtest_unittest.cc}::AddFailureHelper (bool *aborted)
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest, ADD_FAILURE)
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest, ADD_FAILURE_AT)
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest, FAIL)
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest, SUCCEED)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, Bool)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, Int)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, Time_T)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, Char)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, WideChar)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, StdString)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, CharPointer)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, WideCharPointer)
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest, OtherPointer)
anonymous_namespace{gtest_unittest.cc}::TEST (ComparisonAssertionTest, AcceptsUnprintableArgs)
anonymous_namespace{gtest_unittest.cc}::TEST (FRIEND_TEST_Test, TEST)
anonymous_namespace{gtest_unittest.cc}::TEST_F (FRIEND_TEST_Test2, TEST_F)
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestLifeCycleTest, Test1)
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestLifeCycleTest, Test2)
TEST (AssertionResultTest, CopyConstructorWorksWhenNotOptimied)
TEST (AssertionResultTest, ConstructionWorks)
TEST (AssertionResultTest, NegationWorks)
TEST (AssertionResultTest, StreamingWorks)
TEST (AssertionResultTest, CanStreamOstreamManipulators)
TEST (AssertionResultTest, ConstructibleFromImplicitlyConvertible)
std::ostream & operator<< (std::ostream &os, const Base &val)
std::ostream & operator<< (std::ostream &os, const Base *pointer)
TEST (MessageTest, CanStreamUserTypeInGlobalNameSpace)
std::ostream & anonymous_namespace{gtest_unittest.cc}::operator<< (std::ostream &os, const MyTypeInUnnamedNameSpace &val)
std::ostream & anonymous_namespace{gtest_unittest.cc}::operator<< (std::ostream &os, const MyTypeInUnnamedNameSpace *pointer)
TEST (MessageTest, CanStreamUserTypeInUnnamedNameSpace)
std::ostream & namespace1::operator<< (std::ostream &os, const MyTypeInNameSpace1 &val)
std::ostream & namespace1::operator<< (std::ostream &os, const MyTypeInNameSpace1 *pointer)
TEST (MessageTest, CanStreamUserTypeInUserNameSpace)
std::ostream & operator<< (std::ostream &os, const namespace2::MyTypeInNameSpace2 &val)
std::ostream & operator<< (std::ostream &os, const namespace2::MyTypeInNameSpace2 *pointer)
TEST (MessageTest, CanStreamUserTypeInUserNameSpaceWithStreamOperatorInGlobal)
TEST (MessageTest, NullPointers)
TEST (MessageTest, WideStrings)
testing::TEST_F (TestInfoTest, Names)
testing::TEST_F (TestInfoTest, result)
testing::TEST (CodeLocationForTEST, Verify)
testing::TEST_F (CodeLocationForTESTF, Verify)
testing::TEST_P (CodeLocationForTESTP, Verify)
testing::INSTANTIATE_TEST_CASE_P (, CodeLocationForTESTP, Values(0))
testing::TYPED_TEST_CASE (CodeLocationForTYPEDTEST, int)
testing::TYPED_TEST (CodeLocationForTYPEDTEST, Verify)
testing::TYPED_TEST_CASE_P (CodeLocationForTYPEDTESTP)
testing::TYPED_TEST_P (CodeLocationForTYPEDTESTP, Verify)
testing::REGISTER_TYPED_TEST_CASE_P (CodeLocationForTYPEDTESTP, Verify)
testing::INSTANTIATE_TYPED_TEST_CASE_P (My, CodeLocationForTYPEDTESTP, int)
testing::TEST_F (SetUpTestCaseTest, Test1)
testing::TEST_F (SetUpTestCaseTest, Test2)
testing::TEST_F (ParseFlagsTest, Empty)
testing::TEST_F (ParseFlagsTest, NoFlag)
testing::TEST_F (ParseFlagsTest, FilterBad)
testing::TEST_F (ParseFlagsTest, FilterEmpty)
testing::TEST_F (ParseFlagsTest, FilterNonEmpty)
testing::TEST_F (ParseFlagsTest, BreakOnFailureWithoutValue)
testing::TEST_F (ParseFlagsTest, BreakOnFailureFalse_0)
testing::TEST_F (ParseFlagsTest, BreakOnFailureFalse_f)
testing::TEST_F (ParseFlagsTest, BreakOnFailureFalse_F)
testing::TEST_F (ParseFlagsTest, BreakOnFailureTrue)
testing::TEST_F (ParseFlagsTest, CatchExceptions)
testing::TEST_F (ParseFlagsTest, DeathTestUseFork)
testing::TEST_F (ParseFlagsTest, DuplicatedFlags)
testing::TEST_F (ParseFlagsTest, UnrecognizedFlag)
testing::TEST_F (ParseFlagsTest, ListTestsFlag)
testing::TEST_F (ParseFlagsTest, ListTestsTrue)
testing::TEST_F (ParseFlagsTest, ListTestsFalse)
testing::TEST_F (ParseFlagsTest, ListTestsFalse_f)
testing::TEST_F (ParseFlagsTest, ListTestsFalse_F)
testing::TEST_F (ParseFlagsTest, OutputEmpty)
testing::TEST_F (ParseFlagsTest, OutputXml)
testing::TEST_F (ParseFlagsTest, OutputXmlFile)
testing::TEST_F (ParseFlagsTest, OutputXmlDirectory)
testing::TEST_F (ParseFlagsTest, PrintTimeFlag)
testing::TEST_F (ParseFlagsTest, PrintTimeTrue)
testing::TEST_F (ParseFlagsTest, PrintTimeFalse)
testing::TEST_F (ParseFlagsTest, PrintTimeFalse_f)
testing::TEST_F (ParseFlagsTest, PrintTimeFalse_F)
testing::TEST_F (ParseFlagsTest, RandomSeed)
testing::TEST_F (ParseFlagsTest, Repeat)
testing::TEST_F (ParseFlagsTest, AlsoRunDisabledTestsFlag)
testing::TEST_F (ParseFlagsTest, AlsoRunDisabledTestsTrue)
testing::TEST_F (ParseFlagsTest, AlsoRunDisabledTestsFalse)
testing::TEST_F (ParseFlagsTest, ShuffleWithoutValue)
testing::TEST_F (ParseFlagsTest, ShuffleFalse_0)
testing::TEST_F (ParseFlagsTest, ShuffleTrue)
testing::TEST_F (ParseFlagsTest, StackTraceDepth)
testing::TEST_F (ParseFlagsTest, StreamResultTo)
testing::TEST_F (ParseFlagsTest, ThrowOnFailureWithoutValue)
testing::TEST_F (ParseFlagsTest, ThrowOnFailureFalse_0)
testing::TEST_F (ParseFlagsTest, ThrowOnFailureTrue)
testing::TEST_F (CurrentTestInfoTest, WorksForFirstTestInATestCase)
testing::TEST_F (CurrentTestInfoTest, WorksForSecondTestInATestCase)
my_namespace::testing::TEST (NestedTestingNamespaceTest, Success)
my_namespace::testing::TEST (NestedTestingNamespaceTest, Failure)
TEST (StreamingAssertionsTest, Unconditional)
TEST (StreamingAssertionsTest, Truth)
TEST (StreamingAssertionsTest, Truth2)
TEST (StreamingAssertionsTest, IntegerEquals)
TEST (StreamingAssertionsTest, IntegerLessThan)
TEST (StreamingAssertionsTest, StringsEqual)
TEST (StreamingAssertionsTest, StringsNotEqual)
TEST (StreamingAssertionsTest, StringsEqualIgnoringCase)
TEST (StreamingAssertionsTest, StringNotEqualIgnoringCase)
TEST (StreamingAssertionsTest, FloatingPointEquals)
TEST (ColoredOutputTest, UsesColorsWhenGTestColorFlagIsYes)
TEST (ColoredOutputTest, UsesColorsWhenGTestColorFlagIsAliasOfYes)
TEST (ColoredOutputTest, UsesNoColorWhenGTestColorFlagIsNo)
TEST (ColoredOutputTest, UsesNoColorWhenGTestColorFlagIsInvalid)
TEST (ColoredOutputTest, UsesColorsWhenStdoutIsTty)
TEST (ColoredOutputTest, UsesColorsWhenTermSupportsColors)
TEST (StaticAssertTypeEqTest, WorksInClass)
TEST (StaticAssertTypeEqTest, CompilesForEqualTypes)
TEST (HasNonfatalFailureTest, ReturnsFalseWhenThereIsNoFailure)
static void FailFatally ()
TEST (HasNonfatalFailureTest, ReturnsFalseWhenThereIsOnlyFatalFailure)
TEST (HasNonfatalFailureTest, ReturnsTrueWhenThereIsNonfatalFailure)
TEST (HasNonfatalFailureTest, ReturnsTrueWhenThereAreFatalAndNonfatalFailures)
static bool HasNonfatalFailureHelper ()
TEST (HasNonfatalFailureTest, WorksOutsideOfTestBody)
TEST (HasNonfatalFailureTest, WorksOutsideOfTestBody2)
TEST (HasFailureTest, ReturnsFalseWhenThereIsNoFailure)
TEST (HasFailureTest, ReturnsTrueWhenThereIsFatalFailure)
TEST (HasFailureTest, ReturnsTrueWhenThereIsNonfatalFailure)
TEST (HasFailureTest, ReturnsTrueWhenThereAreFatalAndNonfatalFailures)
static bool HasFailureHelper ()
TEST (HasFailureTest, WorksOutsideOfTestBody)
TEST (HasFailureTest, WorksOutsideOfTestBody2)
TEST (TestEventListenersTest, ConstructionWorks)
TEST (TestEventListenersTest, DestructionWorks)
TEST (TestEventListenersTest, Append)
TEST (EventListenerTest, AppendKeepsOrder)
TEST (TestEventListenersTest, Release)
TEST (EventListenerTest, SuppressEventForwarding)
TEST (EventListenerDeathTest, EventsNotForwardedInDeathTestSubprecesses)
TEST (EventListenerTest, default_result_printer)
TEST (EventListenerTest, RemovingDefaultResultPrinterWorks)
TEST (EventListenerTest, default_xml_generator)
TEST (EventListenerTest, RemovingDefaultXmlGeneratorWorks)
GTEST_TEST (AlternativeNameTest, Works)
TEST (IsAProtocolMessageTest, ValueIsCompileTimeConstant)
TEST (IsAProtocolMessageTest, ValueIsTrueWhenTypeIsAProtocolMessage)
TEST (IsAProtocolMessageTest, ValueIsFalseWhenTypeIsNotAProtocolMessage)
TEST (CompileAssertTypesEqual, CompilesWhenTypesAreEqual)
TEST (RemoveReferenceTest, DoesNotAffectNonReferenceType)
TEST (RemoveReferenceTest, RemovesReference)
template<typename T1 , typename T2 >
void TestGTestRemoveReference ()
TEST (RemoveReferenceTest, MacroVersion)
TEST (RemoveConstTest, DoesNotAffectNonConstType)
TEST (RemoveConstTest, RemovesConst)
template<typename T1 , typename T2 >
void TestGTestRemoveConst ()
TEST (RemoveConstTest, MacroVersion)
template<typename T1 , typename T2 >
void TestGTestRemoveReferenceAndConst ()
TEST (RemoveReferenceToConstTest, Works)
TEST (AddReferenceTest, DoesNotAffectReferenceType)
TEST (AddReferenceTest, AddsReference)
template<typename T1 , typename T2 >
void TestGTestAddReference ()
TEST (AddReferenceTest, MacroVersion)
template<typename T1 , typename T2 >
void TestGTestReferenceToConst ()
TEST (GTestReferenceToConstTest, Works)
TEST (ImplicitlyConvertibleTest, ValueIsCompileTimeConstant)
TEST (ImplicitlyConvertibleTest, ValueIsTrueWhenConvertible)
TEST (ImplicitlyConvertibleTest, ValueIsFalseWhenNotConvertible)
TEST (IsContainerTestTest, WorksForNonContainer)
TEST (IsContainerTestTest, WorksForContainer)
TEST (IsHashTable, Basic)
TEST (ArrayEqTest, WorksForDegeneratedArrays)
TEST (ArrayEqTest, WorksForOneDimensionalArrays)
TEST (ArrayEqTest, WorksForTwoDimensionalArrays)
TEST (ArrayAwareFindTest, WorksForOneDimensionalArray)
TEST (ArrayAwareFindTest, WorksForTwoDimensionalArray)
TEST (CopyArrayTest, WorksForDegeneratedArrays)
TEST (CopyArrayTest, WorksForOneDimensionalArrays)
TEST (CopyArrayTest, WorksForTwoDimensionalArrays)
TEST (NativeArrayTest, ConstructorFromArrayWorks)
TEST (NativeArrayTest, CreatesAndDeletesCopyOfArrayWhenAskedTo)
TEST (NativeArrayTest, TypeMembersAreCorrect)
TEST (NativeArrayTest, MethodsWork)
TEST (NativeArrayTest, WorksForTwoDimensionalArray)
TEST (SkipPrefixTest, SkipsWhenPrefixMatches)
TEST (SkipPrefixTest, DoesNotSkipWhenPrefixDoesNotMatch)
TEST_F (AdHocTestResultTest, AdHocTestResultForTestCaseShowsFailure)
TEST_F (AdHocTestResultTest, AdHocTestResultTestForUnitTestDoesNotShowFailure)
Variables
static int anonymous_namespace{gtest_unittest.cc}::g_sum = 0
static const wchar_t *const anonymous_namespace{gtest_unittest.cc}::kNull = NULL
static int anonymous_namespace{gtest_unittest.cc}::global_var = 0
static Environment * anonymous_namespace{gtest_unittest.cc}::record_property_env
static bool dummy1 GTEST_ATTRIBUTE_UNUSED_ = StaticAssertTypeEq<bool, bool>()
Macro Definition Documentation
GTEST_TEST_PARSING_FLAGS_
#define GTEST_TEST_PARSING_FLAGS_ (argv1, argv2, expected, should_print_help)
Value:
  TestParsingFlags(sizeof(argv1)/sizeof(*argv1) - 1, argv1, \
                   sizeof(argv2)/sizeof(*argv2) - 1, argv2, \
                   expected, should_print_help)
Definition at line 5739 of file gtest_unittest.cc.
{
  const char* argv[] = {
    NULL
  };
  const char* argv2[] = {
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), false);
}
// Tests parsing a command line that has no flag.
TEST_F(ParseFlagsTest, NoFlag) {
  const char* argv[] = {
    "foo.exe",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), false);
}
// Tests parsing a bad --gtest_filter flag.
TEST_F(ParseFlagsTest, FilterBad) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    "--gtest_filter",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter(""), true);
}
// Tests parsing an empty --gtest_filter flag.
TEST_F(ParseFlagsTest, FilterEmpty) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter=",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter(""), false);
}
// Tests parsing a non-empty --gtest_filter flag.
TEST_F(ParseFlagsTest, FilterNonEmpty) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter=abc",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter("abc"), false);
}
// Tests parsing --gtest_break_on_failure.
TEST_F(ParseFlagsTest, BreakOnFailureWithoutValue) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure",
    NULL
};
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(true), false);
}
// Tests parsing --gtest_break_on_failure=0.
TEST_F(ParseFlagsTest, BreakOnFailureFalse_0) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=0",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(false), false);
}
// Tests parsing --gtest_break_on_failure=f.
TEST_F(ParseFlagsTest, BreakOnFailureFalse_f) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=f",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(false), false);
}
// Tests parsing --gtest_break_on_failure=F.
TEST_F(ParseFlagsTest, BreakOnFailureFalse_F) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=F",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(false), false);
}
// Tests parsing a --gtest_break_on_failure flag that has a "true"
// definition.
TEST_F(ParseFlagsTest, BreakOnFailureTrue) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=1",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(true), false);
}
// Tests parsing --gtest_catch_exceptions.
TEST_F(ParseFlagsTest, CatchExceptions) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_catch_exceptions",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::CatchExceptions(true), false);
}
// Tests parsing --gtest_death_test_use_fork.
TEST_F(ParseFlagsTest, DeathTestUseFork) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_death_test_use_fork",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::DeathTestUseFork(true), false);
}
// Tests having the same flag twice with different values.  The
// expected behavior is that the one coming last takes precedence.
TEST_F(ParseFlagsTest, DuplicatedFlags) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter=a",
    "--gtest_filter=b",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter("b"), false);
}
// Tests having an unrecognized flag on the command line.
TEST_F(ParseFlagsTest, UnrecognizedFlag) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure",
    "bar",  // Unrecognized by Google Test.
    "--gtest_filter=b",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    "bar",
    NULL
  };
  Flags flags;
  flags.break_on_failure = true;
  flags.filter = "b";
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, flags, false);
}
// Tests having a --gtest_list_tests flag
TEST_F(ParseFlagsTest, ListTestsFlag) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_list_tests",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(true), false);
}
// Tests having a --gtest_list_tests flag with a "true" value
TEST_F(ParseFlagsTest, ListTestsTrue) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_list_tests=1",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(true), false);
}
// Tests having a --gtest_list_tests flag with a "false" value
TEST_F(ParseFlagsTest, ListTestsFalse) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_list_tests=0",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(false), false);
}
// Tests parsing --gtest_list_tests=f.
TEST_F(ParseFlagsTest, ListTestsFalse_f) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_list_tests=f",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(false), false);
}
// Tests parsing --gtest_list_tests=F.
TEST_F(ParseFlagsTest, ListTestsFalse_F) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_list_tests=F",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(false), false);
}
// Tests parsing --gtest_output (invalid).
TEST_F(ParseFlagsTest, OutputEmpty) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_output",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    "--gtest_output",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), true);
}
// Tests parsing --gtest_output=xml
TEST_F(ParseFlagsTest, OutputXml) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_output=xml",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Output("xml"), false);
}
// Tests parsing --gtest_output=xml:file
TEST_F(ParseFlagsTest, OutputXmlFile) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_output=xml:file",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Output("xml:file"), false);
}
// Tests parsing --gtest_output=xml:directory/path/
TEST_F(ParseFlagsTest, OutputXmlDirectory) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_output=xml:directory/path/",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                            Flags::Output("xml:directory/path/"), false);
}
// Tests having a --gtest_print_time flag
TEST_F(ParseFlagsTest, PrintTimeFlag) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_print_time",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(true), false);
}
// Tests having a --gtest_print_time flag with a "true" value
TEST_F(ParseFlagsTest, PrintTimeTrue) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_print_time=1",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(true), false);
}
// Tests having a --gtest_print_time flag with a "false" value
TEST_F(ParseFlagsTest, PrintTimeFalse) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_print_time=0",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(false), false);
}
// Tests parsing --gtest_print_time=f.
TEST_F(ParseFlagsTest, PrintTimeFalse_f) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_print_time=f",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(false), false);
}
// Tests parsing --gtest_print_time=F.
TEST_F(ParseFlagsTest, PrintTimeFalse_F) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_print_time=F",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(false), false);
}
// Tests parsing --gtest_random_seed=number
TEST_F(ParseFlagsTest, RandomSeed) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_random_seed=1000",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::RandomSeed(1000), false);
}
// Tests parsing --gtest_repeat=number
TEST_F(ParseFlagsTest, Repeat) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_repeat=1000",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Repeat(1000), false);
}
// Tests having a --gtest_also_run_disabled_tests flag
TEST_F(ParseFlagsTest, AlsoRunDisabledTestsFlag) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_also_run_disabled_tests",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                              Flags::AlsoRunDisabledTests(true), false);
}
// Tests having a --gtest_also_run_disabled_tests flag with a "true" value
TEST_F(ParseFlagsTest, AlsoRunDisabledTestsTrue) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_also_run_disabled_tests=1",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                              Flags::AlsoRunDisabledTests(true), false);
}
// Tests having a --gtest_also_run_disabled_tests flag with a "false" value
TEST_F(ParseFlagsTest, AlsoRunDisabledTestsFalse) {
    const char* argv[] = {
      "foo.exe",
      "--gtest_also_run_disabled_tests=0",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                              Flags::AlsoRunDisabledTests(false), false);
}
// Tests parsing --gtest_shuffle.
TEST_F(ParseFlagsTest, ShuffleWithoutValue) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_shuffle",
    NULL
};
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Shuffle(true), false);
}
// Tests parsing --gtest_shuffle=0.
TEST_F(ParseFlagsTest, ShuffleFalse_0) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_shuffle=0",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Shuffle(false), false);
}
// Tests parsing a --gtest_shuffle flag that has a "true" definition.
TEST_F(ParseFlagsTest, ShuffleTrue) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_shuffle=1",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Shuffle(true), false);
}
// Tests parsing --gtest_stack_trace_depth=number.
TEST_F(ParseFlagsTest, StackTraceDepth) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_stack_trace_depth=5",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::StackTraceDepth(5), false);
}
TEST_F(ParseFlagsTest, StreamResultTo) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_stream_result_to=localhost:1234",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(
      argv, argv2, Flags::StreamResultTo("localhost:1234"), false);
}
// Tests parsing --gtest_throw_on_failure.
TEST_F(ParseFlagsTest, ThrowOnFailureWithoutValue) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_throw_on_failure",
    NULL
};
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(true), false);
}
// Tests parsing --gtest_throw_on_failure=0.
TEST_F(ParseFlagsTest, ThrowOnFailureFalse_0) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_throw_on_failure=0",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(false), false);
}
// Tests parsing a --gtest_throw_on_failure flag that has a "true"
// definition.
TEST_F(ParseFlagsTest, ThrowOnFailureTrue) {
  const char* argv[] = {
    "foo.exe",
    "--gtest_throw_on_failure=1",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(true), false);
}
# if GTEST_OS_WINDOWS
// Tests parsing wide strings.
TEST_F(ParseFlagsTest, WideStrings) {
  const wchar_t* argv[] = {
    L"foo.exe",
    L"--gtest_filter=Foo*",
    L"--gtest_list_tests=1",
    L"--gtest_break_on_failure",
    L"--non_gtest_flag",
    NULL
  };
  const wchar_t* argv2[] = {
    L"foo.exe",
    L"--non_gtest_flag",
    NULL
  };
  Flags expected_flags;
  expected_flags.break_on_failure = true;
  expected_flags.filter = "Foo*";
  expected_flags.list_tests = true;
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, expected_flags, false);
}
# endif  // GTEST_OS_WINDOWS
#if GTEST_USE_OWN_FLAGFILE_FLAG_
class FlagfileTest : public ParseFlagsTest {
 public:
  virtual void SetUp() {
    ParseFlagsTest::SetUp();
    testdata_path_.Set(internal::FilePath(
        testing::TempDir() + internal::GetCurrentExecutableName().string() +
        "_flagfile_test"));
    testing::internal::posix::RmDir(testdata_path_.c_str());
    EXPECT_TRUE(testdata_path_.CreateFolder());
  }
  virtual void TearDown() {
    testing::internal::posix::RmDir(testdata_path_.c_str());
    ParseFlagsTest::TearDown();
  }
  internal::FilePath CreateFlagfile(const char* contents) {
    internal::FilePath file_path(internal::FilePath::GenerateUniqueFileName(
        testdata_path_, internal::FilePath("unique"), "txt"));
    FILE* f = testing::internal::posix::FOpen(file_path.c_str(), "w");
    fprintf(f, "%s", contents);
    fclose(f);
    return file_path;
  }
 private:
  internal::FilePath testdata_path_;
};
// Tests an empty flagfile.
TEST_F(FlagfileTest, Empty) {
  internal::FilePath flagfile_path(CreateFlagfile(""));
  std::string flagfile_flag =
      std::string("--" GTEST_FLAG_PREFIX_ "flagfile=") + flagfile_path.c_str();
  const char* argv[] = {
    "foo.exe",
    flagfile_flag.c_str(),
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), false);
}
// Tests passing a non-empty --gtest_filter flag via --gtest_flagfile.
TEST_F(FlagfileTest, FilterNonEmpty) {
  internal::FilePath flagfile_path(CreateFlagfile(
      "--"  GTEST_FLAG_PREFIX_  "filter=abc"));
  std::string flagfile_flag =
      std::string("--" GTEST_FLAG_PREFIX_ "flagfile=") + flagfile_path.c_str();
  const char* argv[] = {
    "foo.exe",
    flagfile_flag.c_str(),
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter("abc"), false);
}
// Tests passing several flags via --gtest_flagfile.
TEST_F(FlagfileTest, SeveralFlags) {
  internal::FilePath flagfile_path(CreateFlagfile(
      "--"  GTEST_FLAG_PREFIX_  "filter=abc\n"
      "--"  GTEST_FLAG_PREFIX_  "break_on_failure\n"
      "--"  GTEST_FLAG_PREFIX_  "list_tests"));
  std::string flagfile_flag =
      std::string("--" GTEST_FLAG_PREFIX_ "flagfile=") + flagfile_path.c_str();
  const char* argv[] = {
    "foo.exe",
    flagfile_flag.c_str(),
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  Flags expected_flags;
  expected_flags.break_on_failure = true;
  expected_flags.filter = "abc";
  expected_flags.list_tests = true;
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, expected_flags, false);
}
#endif  // GTEST_USE_OWN_FLAGFILE_FLAG_
// Tests current_test_info() in UnitTest.
class CurrentTestInfoTest : public Test {
 protected:
  // Tests that current_test_info() returns NULL before the first test in
  // the test case is run.
  static void SetUpTestCase() {
    // There should be no tests running at this point.
    const TestInfo* test_info =
      UnitTest::GetInstance()->current_test_info();
    EXPECT_TRUE(test_info == NULL)
        << "There should be no tests running at this point.";
  }
  // Tests that current_test_info() returns NULL after the last test in
  // the test case has run.
  static void TearDownTestCase() {
    const TestInfo* test_info =
      UnitTest::GetInstance()->current_test_info();
    EXPECT_TRUE(test_info == NULL)
        << "There should be no tests running at this point.";
  }
};
// Tests that current_test_info() returns TestInfo for currently running
// test by checking the expected test name against the actual one.
TEST_F(CurrentTestInfoTest, WorksForFirstTestInATestCase) {
  const TestInfo* test_info =
    UnitTest::GetInstance()->current_test_info();
  ASSERT_TRUE(NULL != test_info)
      << "There is a test running so we should have a valid TestInfo.";
  EXPECT_STREQ("CurrentTestInfoTest", test_info->test_case_name())
      << "Expected the name of the currently running test case.";
  EXPECT_STREQ("WorksForFirstTestInATestCase", test_info->name())
      << "Expected the name of the currently running test.";
}
// Tests that current_test_info() returns TestInfo for currently running
// test by checking the expected test name against the actual one.  We
// use this test to see that the TestInfo object actually changed from
// the previous invocation.
TEST_F(CurrentTestInfoTest, WorksForSecondTestInATestCase) {
  const TestInfo* test_info =
    UnitTest::GetInstance()->current_test_info();
  ASSERT_TRUE(NULL != test_info)
      << "There is a test running so we should have a valid TestInfo.";
  EXPECT_STREQ("CurrentTestInfoTest", test_info->test_case_name())
      << "Expected the name of the currently running test case.";
  EXPECT_STREQ("WorksForSecondTestInATestCase", test_info->name())
      << "Expected the name of the currently running test.";
}
}  // namespace testing
// These two lines test that we can define tests in a namespace that
// has the name "testing" and is nested in another namespace.
namespace my_namespace {
namespace testing {
// Makes sure that TEST knows to use ::testing::Test instead of
// ::my_namespace::testing::Test.
class Test {};
// Makes sure that an assertion knows to use ::testing::Message instead of
// ::my_namespace::testing::Message.
class Message {};
// Makes sure that an assertion knows to use
// ::testing::AssertionResult instead of
// ::my_namespace::testing::AssertionResult.
class AssertionResult {};
// Tests that an assertion that should succeed works as expected.
TEST(NestedTestingNamespaceTest, Success) {
  EXPECT_EQ(1, 1) << "This shouldn't fail.";
}
// Tests that an assertion that should fail works as expected.
TEST(NestedTestingNamespaceTest, Failure) {
  EXPECT_FATAL_FAILURE(FAIL() << "This failure is expected.",
                       "This failure is expected.");
}
}  // namespace testing
}  // namespace my_namespace
// Tests that one can call superclass SetUp and TearDown methods--
// that is, that they are not private.
// No tests are based on this fixture; the test "passes" if it compiles
// successfully.
class ProtectedFixtureMethodsTest : public Test {
 protected:
  virtual void SetUp() {
    Test::SetUp();
  }
  virtual void TearDown() {
    Test::TearDown();
  }
};
// StreamingAssertionsTest tests the streaming versions of a representative
// sample of assertions.
TEST(StreamingAssertionsTest, Unconditional) {
  SUCCEED() << "expected success";
  EXPECT_NONFATAL_FAILURE(ADD_FAILURE() << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(FAIL() << "expected failure",
                       "expected failure");
}
#ifdef __BORLANDC__
// Silences warnings: "Condition is always true", "Unreachable code"
# pragma option push -w-ccc -w-rch
#endif
TEST(StreamingAssertionsTest, Truth) {
  EXPECT_TRUE(true) << "unexpected failure";
  ASSERT_TRUE(true) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(false) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(false) << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, Truth2) {
  EXPECT_FALSE(false) << "unexpected failure";
  ASSERT_FALSE(false) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(true) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_FALSE(true) << "expected failure",
                       "expected failure");
}
#ifdef __BORLANDC__
// Restores warnings after previous "#pragma option push" suppressed them
# pragma option pop
#endif
TEST(StreamingAssertionsTest, IntegerEquals) {
  EXPECT_EQ(1, 1) << "unexpected failure";
  ASSERT_EQ(1, 1) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(1, 2) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_EQ(1, 2) << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, IntegerLessThan) {
  EXPECT_LT(1, 2) << "unexpected failure";
  ASSERT_LT(1, 2) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(2, 1) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_LT(2, 1) << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, StringsEqual) {
  EXPECT_STREQ("foo", "foo") << "unexpected failure";
  ASSERT_STREQ("foo", "foo") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STREQ("foo", "bar") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STREQ("foo", "bar") << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, StringsNotEqual) {
  EXPECT_STRNE("foo", "bar") << "unexpected failure";
  ASSERT_STRNE("foo", "bar") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRNE("foo", "foo") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STRNE("foo", "foo") << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, StringsEqualIgnoringCase) {
  EXPECT_STRCASEEQ("foo", "FOO") << "unexpected failure";
  ASSERT_STRCASEEQ("foo", "FOO") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRCASEEQ("foo", "bar") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STRCASEEQ("foo", "bar") << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, StringNotEqualIgnoringCase) {
  EXPECT_STRCASENE("foo", "bar") << "unexpected failure";
  ASSERT_STRCASENE("foo", "bar") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRCASENE("foo", "FOO") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STRCASENE("bar", "BAR") << "expected failure",
                       "expected failure");
}
TEST(StreamingAssertionsTest, FloatingPointEquals) {
  EXPECT_FLOAT_EQ(1.0, 1.0) << "unexpected failure";
  ASSERT_FLOAT_EQ(1.0, 1.0) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(0.0, 1.0) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_FLOAT_EQ(0.0, 1.0) << "expected failure",
                       "expected failure");
}
#if GTEST_HAS_EXCEPTIONS
TEST(StreamingAssertionsTest, Throw) {
  EXPECT_THROW(ThrowAnInteger(), int) << "unexpected failure";
  ASSERT_THROW(ThrowAnInteger(), int) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_THROW(ThrowAnInteger(), bool) <<
                          "expected failure", "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_THROW(ThrowAnInteger(), bool) <<
                       "expected failure", "expected failure");
}
TEST(StreamingAssertionsTest, NoThrow) {
  EXPECT_NO_THROW(ThrowNothing()) << "unexpected failure";
  ASSERT_NO_THROW(ThrowNothing()) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_NO_THROW(ThrowAnInteger()) <<
                          "expected failure", "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_NO_THROW(ThrowAnInteger()) <<
                       "expected failure", "expected failure");
}
TEST(StreamingAssertionsTest, AnyThrow) {
  EXPECT_ANY_THROW(ThrowAnInteger()) << "unexpected failure";
  ASSERT_ANY_THROW(ThrowAnInteger()) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_ANY_THROW(ThrowNothing()) <<
                          "expected failure", "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_ANY_THROW(ThrowNothing()) <<
                       "expected failure", "expected failure");
}
#endif  // GTEST_HAS_EXCEPTIONS
// Tests that Google Test correctly decides whether to use colors in the output.
TEST(ColoredOutputTest, UsesColorsWhenGTestColorFlagIsYes) {
  GTEST_FLAG(color) = "yes";
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
}
TEST(ColoredOutputTest, UsesColorsWhenGTestColorFlagIsAliasOfYes) {
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  GTEST_FLAG(color) = "True";
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
  GTEST_FLAG(color) = "t";
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
  GTEST_FLAG(color) = "1";
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
}
TEST(ColoredOutputTest, UsesNoColorWhenGTestColorFlagIsNo) {
  GTEST_FLAG(color) = "no";
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_FALSE(ShouldUseColor(false));  // Stdout is not a TTY.
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_FALSE(ShouldUseColor(false));  // Stdout is not a TTY.
}
TEST(ColoredOutputTest, UsesNoColorWhenGTestColorFlagIsInvalid) {
  SetEnv("TERM", "xterm");  // TERM supports colors.
  GTEST_FLAG(color) = "F";
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  GTEST_FLAG(color) = "0";
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  GTEST_FLAG(color) = "unknown";
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
}
TEST(ColoredOutputTest, UsesColorsWhenStdoutIsTty) {
  GTEST_FLAG(color) = "auto";
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_FALSE(ShouldUseColor(false));  // Stdout is not a TTY.
  EXPECT_TRUE(ShouldUseColor(true));    // Stdout is a TTY.
}
TEST(ColoredOutputTest, UsesColorsWhenTermSupportsColors) {
  GTEST_FLAG(color) = "auto";
#if GTEST_OS_WINDOWS
  // On Windows, we ignore the TERM variable as it's usually not set.
  SetEnv("TERM", "dumb");
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "");
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm");
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
#else
  // On non-Windows platforms, we rely on TERM to determine if the
  // terminal supports colors.
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "emacs");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "vt100");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm-mono");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm-color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "screen");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "screen-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "tmux");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "tmux-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "rxvt-unicode");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "rxvt-unicode-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "linux");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "cygwin");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
#endif  // GTEST_OS_WINDOWS
}
// Verifies that StaticAssertTypeEq works in a namespace scope.
static bool dummy1 GTEST_ATTRIBUTE_UNUSED_ = StaticAssertTypeEq<bool, bool>();
static bool dummy2 GTEST_ATTRIBUTE_UNUSED_ =
    StaticAssertTypeEq<const int, const int>();
// Verifies that StaticAssertTypeEq works in a class.
template <typename T>
class StaticAssertTypeEqTestHelper {
 public:
  StaticAssertTypeEqTestHelper() { StaticAssertTypeEq<bool, T>(); }
};
TEST(StaticAssertTypeEqTest, WorksInClass) {
  StaticAssertTypeEqTestHelper<bool>();
}
// Verifies that StaticAssertTypeEq works inside a function.
typedef int IntAlias;
TEST(StaticAssertTypeEqTest, CompilesForEqualTypes) {
  StaticAssertTypeEq<int, IntAlias>();
  StaticAssertTypeEq<int*, IntAlias*>();
}
TEST(HasNonfatalFailureTest, ReturnsFalseWhenThereIsNoFailure) {
  EXPECT_FALSE(HasNonfatalFailure());
}
static void FailFatally() { FAIL(); }
TEST(HasNonfatalFailureTest, ReturnsFalseWhenThereIsOnlyFatalFailure) {
  FailFatally();
  const bool has_nonfatal_failure = HasNonfatalFailure();
  ClearCurrentTestPartResults();
  EXPECT_FALSE(has_nonfatal_failure);
}
TEST(HasNonfatalFailureTest, ReturnsTrueWhenThereIsNonfatalFailure) {
  ADD_FAILURE();
  const bool has_nonfatal_failure = HasNonfatalFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_nonfatal_failure);
}
TEST(HasNonfatalFailureTest, ReturnsTrueWhenThereAreFatalAndNonfatalFailures) {
  FailFatally();
  ADD_FAILURE();
  const bool has_nonfatal_failure = HasNonfatalFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_nonfatal_failure);
}
// A wrapper for calling HasNonfatalFailure outside of a test body.
static bool HasNonfatalFailureHelper() {
  return testing::Test::HasNonfatalFailure();
}
TEST(HasNonfatalFailureTest, WorksOutsideOfTestBody) {
  EXPECT_FALSE(HasNonfatalFailureHelper());
}
TEST(HasNonfatalFailureTest, WorksOutsideOfTestBody2) {
  ADD_FAILURE();
  const bool has_nonfatal_failure = HasNonfatalFailureHelper();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_nonfatal_failure);
}
TEST(HasFailureTest, ReturnsFalseWhenThereIsNoFailure) {
  EXPECT_FALSE(HasFailure());
}
TEST(HasFailureTest, ReturnsTrueWhenThereIsFatalFailure) {
  FailFatally();
  const bool has_failure = HasFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
TEST(HasFailureTest, ReturnsTrueWhenThereIsNonfatalFailure) {
  ADD_FAILURE();
  const bool has_failure = HasFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
TEST(HasFailureTest, ReturnsTrueWhenThereAreFatalAndNonfatalFailures) {
  FailFatally();
  ADD_FAILURE();
  const bool has_failure = HasFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
// A wrapper for calling HasFailure outside of a test body.
static bool HasFailureHelper() { return testing::Test::HasFailure(); }
TEST(HasFailureTest, WorksOutsideOfTestBody) {
  EXPECT_FALSE(HasFailureHelper());
}
TEST(HasFailureTest, WorksOutsideOfTestBody2) {
  ADD_FAILURE();
  const bool has_failure = HasFailureHelper();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
class TestListener : public EmptyTestEventListener {
 public:
  TestListener() : on_start_counter_(NULL), is_destroyed_(NULL) {}
  TestListener(int* on_start_counter, bool* is_destroyed)
      : on_start_counter_(on_start_counter),
        is_destroyed_(is_destroyed) {}
  virtual ~TestListener() {
    if (is_destroyed_)
      *is_destroyed_ = true;
  }
 protected:
  virtual void OnTestProgramStart(const UnitTest& /*unit_test*/) {
    if (on_start_counter_ != NULL)
      (*on_start_counter_)++;
  }
 private:
  int* on_start_counter_;
  bool* is_destroyed_;
};
// Tests the constructor.
TEST(TestEventListenersTest, ConstructionWorks) {
  TestEventListeners listeners;
  EXPECT_TRUE(TestEventListenersAccessor::GetRepeater(&listeners) != NULL);
  EXPECT_TRUE(listeners.default_result_printer() == NULL);
  EXPECT_TRUE(listeners.default_xml_generator() == NULL);
}
// Tests that the TestEventListeners destructor deletes all the listeners it
// owns.
TEST(TestEventListenersTest, DestructionWorks) {
  bool default_result_printer_is_destroyed = false;
  bool default_xml_printer_is_destroyed = false;
  bool extra_listener_is_destroyed = false;
  TestListener* default_result_printer = new TestListener(
      NULL, &default_result_printer_is_destroyed);
  TestListener* default_xml_printer = new TestListener(
      NULL, &default_xml_printer_is_destroyed);
  TestListener* extra_listener = new TestListener(
      NULL, &extra_listener_is_destroyed);
  {
    TestEventListeners listeners;
    TestEventListenersAccessor::SetDefaultResultPrinter(&listeners,
                                                        default_result_printer);
    TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners,
                                                       default_xml_printer);
    listeners.Append(extra_listener);
  }
  EXPECT_TRUE(default_result_printer_is_destroyed);
  EXPECT_TRUE(default_xml_printer_is_destroyed);
  EXPECT_TRUE(extra_listener_is_destroyed);
}
// Tests that a listener Append'ed to a TestEventListeners list starts
// receiving events.
TEST(TestEventListenersTest, Append) {
  int on_start_counter = 0;
  bool is_destroyed = false;
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    listeners.Append(listener);
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_EQ(1, on_start_counter);
  }
  EXPECT_TRUE(is_destroyed);
}
// Tests that listeners receive events in the order they were appended to
// the list, except for *End requests, which must be received in the reverse
// order.
class SequenceTestingListener : public EmptyTestEventListener {
 public:
  SequenceTestingListener(std::vector<std::string>* vector, const char* id)
      : vector_(vector), id_(id) {}
 protected:
  virtual void OnTestProgramStart(const UnitTest& /*unit_test*/) {
    vector_->push_back(GetEventDescription("OnTestProgramStart"));
  }
  virtual void OnTestProgramEnd(const UnitTest& /*unit_test*/) {
    vector_->push_back(GetEventDescription("OnTestProgramEnd"));
  }
  virtual void OnTestIterationStart(const UnitTest& /*unit_test*/,
                                    int /*iteration*/) {
    vector_->push_back(GetEventDescription("OnTestIterationStart"));
  }
  virtual void OnTestIterationEnd(const UnitTest& /*unit_test*/,
                                  int /*iteration*/) {
    vector_->push_back(GetEventDescription("OnTestIterationEnd"));
  }
 private:
  std::string GetEventDescription(const char* method) {
    Message message;
    message << id_ << "." << method;
    return message.GetString();
  }
  std::vector<std::string>* vector_;
  const char* const id_;
  GTEST_DISALLOW_COPY_AND_ASSIGN_(SequenceTestingListener);
};
TEST(EventListenerTest, AppendKeepsOrder) {
  std::vector<std::string> vec;
  TestEventListeners listeners;
  listeners.Append(new SequenceTestingListener(&vec, "1st"));
  listeners.Append(new SequenceTestingListener(&vec, "2nd"));
  listeners.Append(new SequenceTestingListener(&vec, "3rd"));
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("1st.OnTestProgramStart", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestProgramStart", vec[1].c_str());
  EXPECT_STREQ("3rd.OnTestProgramStart", vec[2].c_str());
  vec.clear();
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramEnd(
      *UnitTest::GetInstance());
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("3rd.OnTestProgramEnd", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestProgramEnd", vec[1].c_str());
  EXPECT_STREQ("1st.OnTestProgramEnd", vec[2].c_str());
  vec.clear();
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestIterationStart(
      *UnitTest::GetInstance(), 0);
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("1st.OnTestIterationStart", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestIterationStart", vec[1].c_str());
  EXPECT_STREQ("3rd.OnTestIterationStart", vec[2].c_str());
  vec.clear();
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestIterationEnd(
      *UnitTest::GetInstance(), 0);
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("3rd.OnTestIterationEnd", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestIterationEnd", vec[1].c_str());
  EXPECT_STREQ("1st.OnTestIterationEnd", vec[2].c_str());
}
// Tests that a listener removed from a TestEventListeners list stops receiving
// events and is not deleted when the list is destroyed.
TEST(TestEventListenersTest, Release) {
  int on_start_counter = 0;
  bool is_destroyed = false;
  // Although Append passes the ownership of this object to the list,
  // the following calls release it, and we need to delete it before the
  // test ends.
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    listeners.Append(listener);
    EXPECT_EQ(listener, listeners.Release(listener));
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_TRUE(listeners.Release(listener) == NULL);
  }
  EXPECT_EQ(0, on_start_counter);
  EXPECT_FALSE(is_destroyed);
  delete listener;
}
// Tests that no events are forwarded when event forwarding is disabled.
TEST(EventListenerTest, SuppressEventForwarding) {
  int on_start_counter = 0;
  TestListener* listener = new TestListener(&on_start_counter, NULL);
  TestEventListeners listeners;
  listeners.Append(listener);
  ASSERT_TRUE(TestEventListenersAccessor::EventForwardingEnabled(listeners));
  TestEventListenersAccessor::SuppressEventForwarding(&listeners);
  ASSERT_FALSE(TestEventListenersAccessor::EventForwardingEnabled(listeners));
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(0, on_start_counter);
}
// Tests that events generated by Google Test are not forwarded in
// death test subprocesses.
TEST(EventListenerDeathTest, EventsNotForwardedInDeathTestSubprecesses) {
  EXPECT_DEATH_IF_SUPPORTED({
      GTEST_CHECK_(TestEventListenersAccessor::EventForwardingEnabled(
          *GetUnitTestImpl()->listeners())) << "expected failure";},
      "expected failure");
}
// Tests that a listener installed via SetDefaultResultPrinter() starts
// receiving events and is returned via default_result_printer() and that
// the previous default_result_printer is removed from the list and deleted.
TEST(EventListenerTest, default_result_printer) {
  int on_start_counter = 0;
  bool is_destroyed = false;
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  TestEventListeners listeners;
  TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, listener);
  EXPECT_EQ(listener, listeners.default_result_printer());
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
  // Replacing default_result_printer with something else should remove it
  // from the list and destroy it.
  TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, NULL);
  EXPECT_TRUE(listeners.default_result_printer() == NULL);
  EXPECT_TRUE(is_destroyed);
  // After broadcasting an event the counter is still the same, indicating
  // the listener is not in the list anymore.
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
}
// Tests that the default_result_printer listener stops receiving events
// when removed via Release and that is not owned by the list anymore.
TEST(EventListenerTest, RemovingDefaultResultPrinterWorks) {
  int on_start_counter = 0;
  bool is_destroyed = false;
  // Although Append passes the ownership of this object to the list,
  // the following calls release it, and we need to delete it before the
  // test ends.
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, listener);
    EXPECT_EQ(listener, listeners.Release(listener));
    EXPECT_TRUE(listeners.default_result_printer() == NULL);
    EXPECT_FALSE(is_destroyed);
    // Broadcasting events now should not affect default_result_printer.
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_EQ(0, on_start_counter);
  }
  // Destroying the list should not affect the listener now, too.
  EXPECT_FALSE(is_destroyed);
  delete listener;
}
// Tests that a listener installed via SetDefaultXmlGenerator() starts
// receiving events and is returned via default_xml_generator() and that
// the previous default_xml_generator is removed from the list and deleted.
TEST(EventListenerTest, default_xml_generator) {
  int on_start_counter = 0;
  bool is_destroyed = false;
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  TestEventListeners listeners;
  TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners, listener);
  EXPECT_EQ(listener, listeners.default_xml_generator());
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
  // Replacing default_xml_generator with something else should remove it
  // from the list and destroy it.
  TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners, NULL);
  EXPECT_TRUE(listeners.default_xml_generator() == NULL);
  EXPECT_TRUE(is_destroyed);
  // After broadcasting an event the counter is still the same, indicating
  // the listener is not in the list anymore.
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
}
// Tests that the default_xml_generator listener stops receiving events
// when removed via Release and that is not owned by the list anymore.
TEST(EventListenerTest, RemovingDefaultXmlGeneratorWorks) {
  int on_start_counter = 0;
  bool is_destroyed = false;
  // Although Append passes the ownership of this object to the list,
  // the following calls release it, and we need to delete it before the
  // test ends.
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners, listener);
    EXPECT_EQ(listener, listeners.Release(listener));
    EXPECT_TRUE(listeners.default_xml_generator() == NULL);
    EXPECT_FALSE(is_destroyed);
    // Broadcasting events now should not affect default_xml_generator.
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_EQ(0, on_start_counter);
  }
  // Destroying the list should not affect the listener now, too.
  EXPECT_FALSE(is_destroyed);
  delete listener;
}
// Sanity tests to ensure that the alternative, verbose spellings of
// some of the macros work.  We don't test them thoroughly as that
// would be quite involved.  Since their implementations are
// straightforward, and they are rarely used, we'll just rely on the
// users to tell us when they are broken.
GTEST_TEST(AlternativeNameTest, Works) {  // GTEST_TEST is the same as TEST.
  GTEST_SUCCEED() << "OK";  // GTEST_SUCCEED is the same as SUCCEED.
  // GTEST_FAIL is the same as FAIL.
  EXPECT_FATAL_FAILURE(GTEST_FAIL() << "An expected failure",
                       "An expected failure");
  // GTEST_ASSERT_XY is the same as ASSERT_XY.
  GTEST_ASSERT_EQ(0, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_EQ(0, 1) << "An expected failure",
                       "An expected failure");
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_EQ(1, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_NE(0, 1);
  GTEST_ASSERT_NE(1, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_NE(0, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_LE(0, 0);
  GTEST_ASSERT_LE(0, 1);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_LE(1, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_LT(0, 1);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_LT(0, 0) << "An expected failure",
                       "An expected failure");
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_LT(1, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_GE(0, 0);
  GTEST_ASSERT_GE(1, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_GE(0, 1) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_GT(1, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_GT(0, 1) << "An expected failure",
                       "An expected failure");
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_GT(1, 1) << "An expected failure",
                       "An expected failure");
}
// Tests for internal utilities necessary for implementation of the universal
// printing.
// TODO(vladl@google.com): Find a better home for them.
class ConversionHelperBase {};
class ConversionHelperDerived : public ConversionHelperBase {};
// Tests that IsAProtocolMessage<T>::value is a compile-time constant.
TEST(IsAProtocolMessageTest, ValueIsCompileTimeConstant) {
  GTEST_COMPILE_ASSERT_(IsAProtocolMessage<ProtocolMessage>::value,
                        const_true);
  GTEST_COMPILE_ASSERT_(!IsAProtocolMessage<int>::value, const_false);
}
// Tests that IsAProtocolMessage<T>::value is true when T is
// proto2::Message or a sub-class of it.
TEST(IsAProtocolMessageTest, ValueIsTrueWhenTypeIsAProtocolMessage) {
  EXPECT_TRUE(IsAProtocolMessage< ::proto2::Message>::value);
  EXPECT_TRUE(IsAProtocolMessage<ProtocolMessage>::value);
}
// Tests that IsAProtocolMessage<T>::value is false when T is neither
// ProtocolMessage nor a sub-class of it.
TEST(IsAProtocolMessageTest, ValueIsFalseWhenTypeIsNotAProtocolMessage) {
  EXPECT_FALSE(IsAProtocolMessage<int>::value);
  EXPECT_FALSE(IsAProtocolMessage<const ConversionHelperBase>::value);
}
// Tests that CompileAssertTypesEqual compiles when the type arguments are
// equal.
TEST(CompileAssertTypesEqual, CompilesWhenTypesAreEqual) {
  CompileAssertTypesEqual<void, void>();
  CompileAssertTypesEqual<int*, int*>();
}
// Tests that RemoveReference does not affect non-reference types.
TEST(RemoveReferenceTest, DoesNotAffectNonReferenceType) {
  CompileAssertTypesEqual<int, RemoveReference<int>::type>();
  CompileAssertTypesEqual<const char, RemoveReference<const char>::type>();
}
// Tests that RemoveReference removes reference from reference types.
TEST(RemoveReferenceTest, RemovesReference) {
  CompileAssertTypesEqual<int, RemoveReference<int&>::type>();
  CompileAssertTypesEqual<const char, RemoveReference<const char&>::type>();
}
// Tests GTEST_REMOVE_REFERENCE_.
template <typename T1, typename T2>
void TestGTestRemoveReference() {
  CompileAssertTypesEqual<T1, GTEST_REMOVE_REFERENCE_(T2)>();
}
TEST(RemoveReferenceTest, MacroVersion) {
  TestGTestRemoveReference<int, int>();
  TestGTestRemoveReference<const char, const char&>();
}
// Tests that RemoveConst does not affect non-const types.
TEST(RemoveConstTest, DoesNotAffectNonConstType) {
  CompileAssertTypesEqual<int, RemoveConst<int>::type>();
  CompileAssertTypesEqual<char&, RemoveConst<char&>::type>();
}
// Tests that RemoveConst removes const from const types.
TEST(RemoveConstTest, RemovesConst) {
  CompileAssertTypesEqual<int, RemoveConst<const int>::type>();
  CompileAssertTypesEqual<char[2], RemoveConst<const char[2]>::type>();
  CompileAssertTypesEqual<char[2][3], RemoveConst<const char[2][3]>::type>();
}
// Tests GTEST_REMOVE_CONST_.
template <typename T1, typename T2>
void TestGTestRemoveConst() {
  CompileAssertTypesEqual<T1, GTEST_REMOVE_CONST_(T2)>();
}
TEST(RemoveConstTest, MacroVersion) {
  TestGTestRemoveConst<int, int>();
  TestGTestRemoveConst<double&, double&>();
  TestGTestRemoveConst<char, const char>();
}
// Tests GTEST_REMOVE_REFERENCE_AND_CONST_.
template <typename T1, typename T2>
void TestGTestRemoveReferenceAndConst() {
  CompileAssertTypesEqual<T1, GTEST_REMOVE_REFERENCE_AND_CONST_(T2)>();
}
TEST(RemoveReferenceToConstTest, Works) {
  TestGTestRemoveReferenceAndConst<int, int>();
  TestGTestRemoveReferenceAndConst<double, double&>();
  TestGTestRemoveReferenceAndConst<char, const char>();
  TestGTestRemoveReferenceAndConst<char, const char&>();
  TestGTestRemoveReferenceAndConst<const char*, const char*>();
}
// Tests that AddReference does not affect reference types.
TEST(AddReferenceTest, DoesNotAffectReferenceType) {
  CompileAssertTypesEqual<int&, AddReference<int&>::type>();
  CompileAssertTypesEqual<const char&, AddReference<const char&>::type>();
}
// Tests that AddReference adds reference to non-reference types.
TEST(AddReferenceTest, AddsReference) {
  CompileAssertTypesEqual<int&, AddReference<int>::type>();
  CompileAssertTypesEqual<const char&, AddReference<const char>::type>();
}
// Tests GTEST_ADD_REFERENCE_.
template <typename T1, typename T2>
void TestGTestAddReference() {
  CompileAssertTypesEqual<T1, GTEST_ADD_REFERENCE_(T2)>();
}
TEST(AddReferenceTest, MacroVersion) {
  TestGTestAddReference<int&, int>();
  TestGTestAddReference<const char&, const char&>();
}
// Tests GTEST_REFERENCE_TO_CONST_.
template <typename T1, typename T2>
void TestGTestReferenceToConst() {
  CompileAssertTypesEqual<T1, GTEST_REFERENCE_TO_CONST_(T2)>();
}
TEST(GTestReferenceToConstTest, Works) {
  TestGTestReferenceToConst<const char&, char>();
  TestGTestReferenceToConst<const int&, const int>();
  TestGTestReferenceToConst<const double&, double>();
  TestGTestReferenceToConst<const std::string&, const std::string&>();
}
// Tests that ImplicitlyConvertible<T1, T2>::value is a compile-time constant.
TEST(ImplicitlyConvertibleTest, ValueIsCompileTimeConstant) {
  GTEST_COMPILE_ASSERT_((ImplicitlyConvertible<int, int>::value), const_true);
  GTEST_COMPILE_ASSERT_((!ImplicitlyConvertible<void*, int*>::value),
                        const_false);
}
// Tests that ImplicitlyConvertible<T1, T2>::value is true when T1 can
// be implicitly converted to T2.
TEST(ImplicitlyConvertibleTest, ValueIsTrueWhenConvertible) {
  EXPECT_TRUE((ImplicitlyConvertible<int, double>::value));
  EXPECT_TRUE((ImplicitlyConvertible<double, int>::value));
  EXPECT_TRUE((ImplicitlyConvertible<int*, void*>::value));
  EXPECT_TRUE((ImplicitlyConvertible<int*, const int*>::value));
  EXPECT_TRUE((ImplicitlyConvertible<ConversionHelperDerived&,
                                     const ConversionHelperBase&>::value));
  EXPECT_TRUE((ImplicitlyConvertible<const ConversionHelperBase,
                                     ConversionHelperBase>::value));
}
// Tests that ImplicitlyConvertible<T1, T2>::value is false when T1
// cannot be implicitly converted to T2.
TEST(ImplicitlyConvertibleTest, ValueIsFalseWhenNotConvertible) {
  EXPECT_FALSE((ImplicitlyConvertible<double, int*>::value));
  EXPECT_FALSE((ImplicitlyConvertible<void*, int*>::value));
  EXPECT_FALSE((ImplicitlyConvertible<const int*, int*>::value));
  EXPECT_FALSE((ImplicitlyConvertible<ConversionHelperBase&,
                                      ConversionHelperDerived&>::value));
}
// Tests IsContainerTest.
class NonContainer {};
TEST(IsContainerTestTest, WorksForNonContainer) {
  EXPECT_EQ(sizeof(IsNotContainer), sizeof(IsContainerTest<int>(0)));
  EXPECT_EQ(sizeof(IsNotContainer), sizeof(IsContainerTest<char[5]>(0)));
  EXPECT_EQ(sizeof(IsNotContainer), sizeof(IsContainerTest<NonContainer>(0)));
}
TEST(IsContainerTestTest, WorksForContainer) {
  EXPECT_EQ(sizeof(IsContainer),
            sizeof(IsContainerTest<std::vector<bool> >(0)));
  EXPECT_EQ(sizeof(IsContainer),
            sizeof(IsContainerTest<std::map<int, double> >(0)));
}
#if GTEST_LANG_CXX11
struct ConstOnlyContainerWithPointerIterator {
  using const_iterator = int*;
  const_iterator begin() const;
  const_iterator end() const;
};
struct ConstOnlyContainerWithClassIterator {
  struct const_iterator {
    const int& operator*() const;
    const_iterator& operator++(/* pre-increment */);
  };
  const_iterator begin() const;
  const_iterator end() const;
};
TEST(IsContainerTestTest, ConstOnlyContainer) {
  EXPECT_EQ(sizeof(IsContainer),
            sizeof(IsContainerTest<ConstOnlyContainerWithPointerIterator>(0)));
  EXPECT_EQ(sizeof(IsContainer),
            sizeof(IsContainerTest<ConstOnlyContainerWithClassIterator>(0)));
}
#endif  // GTEST_LANG_CXX11
// Tests IsHashTable.
struct AHashTable {
  typedef void hasher;
};
struct NotReallyAHashTable {
  typedef void hasher;
  typedef void reverse_iterator;
};
TEST(IsHashTable, Basic) {
  EXPECT_TRUE(testing::internal::IsHashTable<AHashTable>::value);
  EXPECT_FALSE(testing::internal::IsHashTable<NotReallyAHashTable>::value);
#if GTEST_LANG_CXX11
  EXPECT_FALSE(testing::internal::IsHashTable<std::vector<int>>::value);
  EXPECT_TRUE(testing::internal::IsHashTable<std::unordered_set<int>>::value);
#endif  // GTEST_LANG_CXX11
#if GTEST_HAS_HASH_SET_
  EXPECT_TRUE(testing::internal::IsHashTable<__gnu_cxx::hash_set<int>>::value);
#endif  // GTEST_HAS_HASH_SET_
}
// Tests ArrayEq().
TEST(ArrayEqTest, WorksForDegeneratedArrays) {
  EXPECT_TRUE(ArrayEq(5, 5L));
  EXPECT_FALSE(ArrayEq('a', 0));
}
TEST(ArrayEqTest, WorksForOneDimensionalArrays) {
  // Note that a and b are distinct but compatible types.
  const int a[] = { 0, 1 };
  long b[] = { 0, 1 };
  EXPECT_TRUE(ArrayEq(a, b));
  EXPECT_TRUE(ArrayEq(a, 2, b));
  b[0] = 2;
  EXPECT_FALSE(ArrayEq(a, b));
  EXPECT_FALSE(ArrayEq(a, 1, b));
}
TEST(ArrayEqTest, WorksForTwoDimensionalArrays) {
  const char a[][3] = { "hi", "lo" };
  const char b[][3] = { "hi", "lo" };
  const char c[][3] = { "hi", "li" };
  EXPECT_TRUE(ArrayEq(a, b));
  EXPECT_TRUE(ArrayEq(a, 2, b));
  EXPECT_FALSE(ArrayEq(a, c));
  EXPECT_FALSE(ArrayEq(a, 2, c));
}
// Tests ArrayAwareFind().
TEST(ArrayAwareFindTest, WorksForOneDimensionalArray) {
  const char a[] = "hello";
  EXPECT_EQ(a + 4, ArrayAwareFind(a, a + 5, 'o'));
  EXPECT_EQ(a + 5, ArrayAwareFind(a, a + 5, 'x'));
}
TEST(ArrayAwareFindTest, WorksForTwoDimensionalArray) {
  int a[][2] = { { 0, 1 }, { 2, 3 }, { 4, 5 } };
  const int b[2] = { 2, 3 };
  EXPECT_EQ(a + 1, ArrayAwareFind(a, a + 3, b));
  const int c[2] = { 6, 7 };
  EXPECT_EQ(a + 3, ArrayAwareFind(a, a + 3, c));
}
// Tests CopyArray().
TEST(CopyArrayTest, WorksForDegeneratedArrays) {
  int n = 0;
  CopyArray('a', &n);
  EXPECT_EQ('a', n);
}
TEST(CopyArrayTest, WorksForOneDimensionalArrays) {
  const char a[3] = "hi";
  int b[3];
#ifndef __BORLANDC__  // C++Builder cannot compile some array size deductions.
  CopyArray(a, &b);
  EXPECT_TRUE(ArrayEq(a, b));
#endif
  int c[3];
  CopyArray(a, 3, c);
  EXPECT_TRUE(ArrayEq(a, c));
}
TEST(CopyArrayTest, WorksForTwoDimensionalArrays) {
  const int a[2][3] = { { 0, 1, 2 }, { 3, 4, 5 } };
  int b[2][3];
#ifndef __BORLANDC__  // C++Builder cannot compile some array size deductions.
  CopyArray(a, &b);
  EXPECT_TRUE(ArrayEq(a, b));
#endif
  int c[2][3];
  CopyArray(a, 2, c);
  EXPECT_TRUE(ArrayEq(a, c));
}
// Tests NativeArray.
TEST(NativeArrayTest, ConstructorFromArrayWorks) {
  const int a[3] = { 0, 1, 2 };
  NativeArray<int> na(a, 3, RelationToSourceReference());
  EXPECT_EQ(3U, na.size());
  EXPECT_EQ(a, na.begin());
}
TEST(NativeArrayTest, CreatesAndDeletesCopyOfArrayWhenAskedTo) {
  typedef int Array[2];
  Array* a = new Array[1];
  (*a)[0] = 0;
  (*a)[1] = 1;
  NativeArray<int> na(*a, 2, RelationToSourceCopy());
  EXPECT_NE(*a, na.begin());
  delete[] a;
  EXPECT_EQ(0, na.begin()[0]);
  EXPECT_EQ(1, na.begin()[1]);
  // We rely on the heap checker to verify that na deletes the copy of
  // array.
}
TEST(NativeArrayTest, TypeMembersAreCorrect) {
  StaticAssertTypeEq<char, NativeArray<char>::value_type>();
  StaticAssertTypeEq<int[2], NativeArray<int[2]>::value_type>();
  StaticAssertTypeEq<const char*, NativeArray<char>::const_iterator>();
  StaticAssertTypeEq<const bool(*)[2], NativeArray<bool[2]>::const_iterator>();
}
TEST(NativeArrayTest, MethodsWork) {
  const int a[3] = { 0, 1, 2 };
  NativeArray<int> na(a, 3, RelationToSourceCopy());
  ASSERT_EQ(3U, na.size());
  EXPECT_EQ(3, na.end() - na.begin());
  NativeArray<int>::const_iterator it = na.begin();
  EXPECT_EQ(0, *it);
  ++it;
  EXPECT_EQ(1, *it);
  it++;
  EXPECT_EQ(2, *it);
  ++it;
  EXPECT_EQ(na.end(), it);
  EXPECT_TRUE(na == na);
  NativeArray<int> na2(a, 3, RelationToSourceReference());
  EXPECT_TRUE(na == na2);
  const int b1[3] = { 0, 1, 1 };
  const int b2[4] = { 0, 1, 2, 3 };
  EXPECT_FALSE(na == NativeArray<int>(b1, 3, RelationToSourceReference()));
  EXPECT_FALSE(na == NativeArray<int>(b2, 4, RelationToSourceCopy()));
}
TEST(NativeArrayTest, WorksForTwoDimensionalArray) {
  const char a[2][3] = { "hi", "lo" };
  NativeArray<char[3]> na(a, 2, RelationToSourceReference());
  ASSERT_EQ(2U, na.size());
  EXPECT_EQ(a, na.begin());
}
// Tests SkipPrefix().
TEST(SkipPrefixTest, SkipsWhenPrefixMatches) {
  const char* const str = "hello";
  const char* p = str;
  EXPECT_TRUE(SkipPrefix("", &p));
  EXPECT_EQ(str, p);
  p = str;
  EXPECT_TRUE(SkipPrefix("hell", &p));
  EXPECT_EQ(str + 4, p);
}
TEST(SkipPrefixTest, DoesNotSkipWhenPrefixDoesNotMatch) {
  const char* const str = "world";
  const char* p = str;
  EXPECT_FALSE(SkipPrefix("W", &p));
  EXPECT_EQ(str, p);
  p = str;
  EXPECT_FALSE(SkipPrefix("world!", &p));
  EXPECT_EQ(str, p);
}
// Tests ad_hoc_test_result().
class AdHocTestResultTest : public testing::Test {
 protected:
  static void SetUpTestCase() {
    FAIL() << "A failure happened inside SetUpTestCase().";
  }
};
TEST_F(AdHocTestResultTest, AdHocTestResultForTestCaseShowsFailure) {
  const testing::TestResult& test_result = testing::UnitTest::GetInstance()
                                               ->current_test_case()
                                               ->ad_hoc_test_result();
  EXPECT_TRUE(test_result.Failed());
}
TEST_F(AdHocTestResultTest, AdHocTestResultTestForUnitTestDoesNotShowFailure) {
  const testing::TestResult& test_result =
      testing::UnitTest::GetInstance()->ad_hoc_test_result();
  EXPECT_FALSE(test_result.Failed());
}
GTEST_USE_UNPROTECTED_COMMA_
#define GTEST_USE_UNPROTECTED_COMMA_ global_var++, global_var++
Definition at line 1261 of file gtest_unittest.cc.
VERIFY_CODE_LOCATION
#define VERIFY_CODE_LOCATION
Value:
  const int expected_line = __LINE__ - 1; \
  const TestInfo* const test_info = GetUnitTestImpl()->current_test_info(); \
  ASSERT_TRUE(test_info); \
  EXPECT_STREQ(__FILE__, test_info->file()); \
  EXPECT_EQ(expected_line, test_info->line())
Definition at line 5370 of file gtest_unittest.cc.
Typedef Documentation
IntAlias
typedef int IntAlias
Definition at line 6918 of file gtest_unittest.cc.
Function Documentation
FailFatally()
static void FailFatally () static
Definition at line 6929 of file gtest_unittest.cc.
{ FAIL(); }
References FAIL.
GTEST_TEST()
GTEST_TEST (AlternativeNameTest , Works)
Definition at line 7331 of file gtest_unittest.cc.
                                       {  // GTEST_TEST is the same as TEST.
  GTEST_SUCCEED() << "OK";  // GTEST_SUCCEED is the same as SUCCEED.
  // GTEST_FAIL is the same as FAIL.
  EXPECT_FATAL_FAILURE(GTEST_FAIL() << "An expected failure",
                       "An expected failure");
  // GTEST_ASSERT_XY is the same as ASSERT_XY.
  GTEST_ASSERT_EQ(0, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_EQ(0, 1) << "An expected failure",
                       "An expected failure");
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_EQ(1, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_NE(0, 1);
  GTEST_ASSERT_NE(1, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_NE(0, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_LE(0, 0);
  GTEST_ASSERT_LE(0, 1);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_LE(1, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_LT(0, 1);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_LT(0, 0) << "An expected failure",
                       "An expected failure");
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_LT(1, 0) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_GE(0, 0);
  GTEST_ASSERT_GE(1, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_GE(0, 1) << "An expected failure",
                       "An expected failure");
  GTEST_ASSERT_GT(1, 0);
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_GT(0, 1) << "An expected failure",
                       "An expected failure");
  EXPECT_FATAL_FAILURE(GTEST_ASSERT_GT(1, 1) << "An expected failure",
                       "An expected failure");
}
References EXPECT_FATAL_FAILURE, GTEST_ASSERT_EQ, GTEST_ASSERT_GE, GTEST_ASSERT_GT, GTEST_ASSERT_LE, GTEST_ASSERT_LT, GTEST_ASSERT_NE, GTEST_FAIL, and GTEST_SUCCEED.
HasFailureHelper()
static bool HasFailureHelper () static
Definition at line 6996 of file gtest_unittest.cc.
{ return testing::Test::HasFailure(); }
References testing::Test::HasFailure().
HasNonfatalFailureHelper()
static bool HasNonfatalFailureHelper () static
Definition at line 6954 of file gtest_unittest.cc.
{
  return testing::Test::HasNonfatalFailure();
}
References testing::Test::HasNonfatalFailure().
operator<<() [1/5]
::std::ostream & operator<< (::std::ostream & os, const TestingVector & vector)
Definition at line 301 of file gtest_unittest.cc.
{
  os << "{ ";
  for (size_t i = 0; i < vector.size(); i++) {
    os << vector[i] << " ";
  }
  os << "}";
  return os;
}
operator<<() [2/5]
std::ostream & operator<< (std::ostream & os, const Base & val)
Definition at line 5195 of file gtest_unittest.cc.
{
  return os << val.x();
}
References Base::x().
operator<<() [3/5]
std::ostream & operator<< (std::ostream & os, const Base * pointer)
Definition at line 5199 of file gtest_unittest.cc.
{
  return os << "(" << pointer->x() << ")";
}
operator<<() [4/5]
std::ostream & operator<< (std::ostream & os, const namespace2::MyTypeInNameSpace2 & val)
Definition at line 5270 of file gtest_unittest.cc.
{
  return os << val.x();
}
References Base::x().
operator<<() [5/5]
std::ostream & operator<< (std::ostream & os, const namespace2::MyTypeInNameSpace2 * pointer)
Definition at line 5274 of file gtest_unittest.cc.
{
  return os << "(" << pointer->x() << ")";
}
TEST() [1/90]
TEST (AddReferenceTest , AddsReference)
Definition at line 7482 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<int&, AddReference<int>::type>();
  CompileAssertTypesEqual<const char&, AddReference<const char>::type>();
}
TEST() [2/90]
TEST (AddReferenceTest , DoesNotAffectReferenceType)
Definition at line 7476 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<int&, AddReference<int&>::type>();
  CompileAssertTypesEqual<const char&, AddReference<const char&>::type>();
}
TEST() [3/90]
TEST (AddReferenceTest , MacroVersion)
Definition at line 7494 of file gtest_unittest.cc.
{
  TestGTestAddReference<int&, int>();
  TestGTestAddReference<const char&, const char&>();
}
TEST() [4/90]
TEST (ArrayAwareFindTest , WorksForOneDimensionalArray)
Definition at line 7637 of file gtest_unittest.cc.
{
  const char a[] = "hello";
  EXPECT_EQ(a + 4, ArrayAwareFind(a, a + 5, 'o'));
  EXPECT_EQ(a + 5, ArrayAwareFind(a, a + 5, 'x'));
}
References EXPECT_EQ.
TEST() [5/90]
TEST (ArrayAwareFindTest , WorksForTwoDimensionalArray)
Definition at line 7643 of file gtest_unittest.cc.
{
  int a[][2] = { { 0, 1 }, { 2, 3 }, { 4, 5 } };
  const int b[2] = { 2, 3 };
  EXPECT_EQ(a + 1, ArrayAwareFind(a, a + 3, b));
  const int c[2] = { 6, 7 };
  EXPECT_EQ(a + 3, ArrayAwareFind(a, a + 3, c));
}
References EXPECT_EQ.
TEST() [6/90]
TEST (ArrayEqTest , WorksForDegeneratedArrays)
Definition at line 7606 of file gtest_unittest.cc.
{
  EXPECT_TRUE(ArrayEq(5, 5L));
  EXPECT_FALSE(ArrayEq('a', 0));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [7/90]
TEST (ArrayEqTest , WorksForOneDimensionalArrays)
Definition at line 7611 of file gtest_unittest.cc.
{
  // Note that a and b are distinct but compatible types.
  const int a[] = { 0, 1 };
  long b[] = { 0, 1 };
  EXPECT_TRUE(ArrayEq(a, b));
  EXPECT_TRUE(ArrayEq(a, 2, b));
  b[0] = 2;
  EXPECT_FALSE(ArrayEq(a, b));
  EXPECT_FALSE(ArrayEq(a, 1, b));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [8/90]
TEST (ArrayEqTest , WorksForTwoDimensionalArrays)
Definition at line 7623 of file gtest_unittest.cc.
{
  const char a[][3] = { "hi", "lo" };
  const char b[][3] = { "hi", "lo" };
  const char c[][3] = { "hi", "li" };
  EXPECT_TRUE(ArrayEq(a, b));
  EXPECT_TRUE(ArrayEq(a, 2, b));
  EXPECT_FALSE(ArrayEq(a, c));
  EXPECT_FALSE(ArrayEq(a, 2, c));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [9/90]
TEST (AssertionResultTest , CanStreamOstreamManipulators)
Definition at line 5155 of file gtest_unittest.cc.
{
  AssertionResult r = AssertionSuccess();
  r << "Data" << std::endl << std::flush << std::ends << "Will be visible";
  EXPECT_STREQ("Data\n\\0Will be visible", r.message());
}
References EXPECT_STREQ, and testing::AssertionResult::message().
TEST() [10/90]
TEST (AssertionResultTest , ConstructibleFromImplicitlyConvertible)
Definition at line 5181 of file gtest_unittest.cc.
{
  ConvertibleToAssertionResult obj;
  EXPECT_TRUE(obj);
}
References EXPECT_TRUE.
TEST() [11/90]
TEST (AssertionResultTest , ConstructionWorks)
Definition at line 5116 of file gtest_unittest.cc.
{
  AssertionResult r1 = AssertionSuccess();
  EXPECT_TRUE(r1);
  EXPECT_STREQ("", r1.message());
  AssertionResult r2 = AssertionSuccess() << "abc";
  EXPECT_TRUE(r2);
  EXPECT_STREQ("abc", r2.message());
  AssertionResult r3 = AssertionFailure();
  EXPECT_FALSE(r3);
  EXPECT_STREQ("", r3.message());
  AssertionResult r4 = AssertionFailure() << "def";
  EXPECT_FALSE(r4);
  EXPECT_STREQ("def", r4.message());
  AssertionResult r5 = AssertionFailure(Message() << "ghi");
  EXPECT_FALSE(r5);
  EXPECT_STREQ("ghi", r5.message());
}
References EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, and testing::AssertionResult::message().
TEST() [12/90]
TEST (AssertionResultTest , CopyConstructorWorksWhenNotOptimied)
Definition at line 5100 of file gtest_unittest.cc.
{
  // Checks that the copy constructor doesn't try to dereference NULL pointers
  // in the source object.
  AssertionResult r1 = AssertionSuccess();
  AssertionResult r2 = r1;
  // The following line is added to prevent the compiler from optimizing
  // away the constructor call.
  r1 << "abc";
  AssertionResult r3 = r1;
  EXPECT_EQ(static_cast<bool>(r3), static_cast<bool>(r1));
  EXPECT_STREQ("abc", r1.message());
}
References EXPECT_EQ, EXPECT_STREQ, and testing::AssertionResult::message().
TEST() [13/90]
TEST (AssertionResultTest , NegationWorks)
Definition at line 5139 of file gtest_unittest.cc.
{
  AssertionResult r1 = AssertionSuccess() << "abc";
  EXPECT_FALSE(!r1);
  EXPECT_STREQ("abc", (!r1).message());
  AssertionResult r2 = AssertionFailure() << "def";
  EXPECT_TRUE(!r2);
  EXPECT_STREQ("def", (!r2).message());
}
References EXPECT_FALSE, EXPECT_STREQ, and EXPECT_TRUE.
TEST() [14/90]
TEST (AssertionResultTest , StreamingWorks)
Definition at line 5149 of file gtest_unittest.cc.
{
  AssertionResult r = AssertionSuccess();
  r << "abc" << 'd' << 0 << true;
  EXPECT_STREQ("abcd0true", r.message());
}
References EXPECT_STREQ, and testing::AssertionResult::message().
TEST() [15/90]
TEST (ColoredOutputTest , UsesColorsWhenGTestColorFlagIsAliasOfYes)
Definition at line 6787 of file gtest_unittest.cc.
{
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  GTEST_FLAG(color) = "True";
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
  GTEST_FLAG(color) = "t";
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
  GTEST_FLAG(color) = "1";
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
}
References EXPECT_TRUE, GTEST_FLAG, and anonymous_namespace{gtest_unittest.cc}::SetEnv().
TEST() [16/90]
TEST (ColoredOutputTest , UsesColorsWhenGTestColorFlagIsYes)
Definition at line 6775 of file gtest_unittest.cc.
{
  GTEST_FLAG(color) = "yes";
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_TRUE(ShouldUseColor(false));  // Stdout is not a TTY.
}
References EXPECT_TRUE, GTEST_FLAG, and anonymous_namespace{gtest_unittest.cc}::SetEnv().
TEST() [17/90]
TEST (ColoredOutputTest , UsesColorsWhenStdoutIsTty)
Definition at line 6825 of file gtest_unittest.cc.
{
  GTEST_FLAG(color) = "auto";
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_FALSE(ShouldUseColor(false));  // Stdout is not a TTY.
  EXPECT_TRUE(ShouldUseColor(true));    // Stdout is a TTY.
}
References EXPECT_FALSE, EXPECT_TRUE, GTEST_FLAG, and anonymous_namespace{gtest_unittest.cc}::SetEnv().
TEST() [18/90]
TEST (ColoredOutputTest , UsesColorsWhenTermSupportsColors)
Definition at line 6833 of file gtest_unittest.cc.
{
  GTEST_FLAG(color) = "auto";
#if GTEST_OS_WINDOWS
  // On Windows, we ignore the TERM variable as it's usually not set.
  SetEnv("TERM", "dumb");
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "");
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm");
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
#else
  // On non-Windows platforms, we rely on TERM to determine if the
  // terminal supports colors.
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "emacs");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "vt100");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm-mono");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm-color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "xterm-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "screen");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "screen-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "tmux");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "tmux-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "rxvt-unicode");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "rxvt-unicode-256color");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "linux");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
  SetEnv("TERM", "cygwin");  // TERM supports colors.
  EXPECT_TRUE(ShouldUseColor(true));  // Stdout is a TTY.
#endif  // GTEST_OS_WINDOWS
}
References EXPECT_FALSE, EXPECT_TRUE, GTEST_FLAG, and anonymous_namespace{gtest_unittest.cc}::SetEnv().
TEST() [19/90]
TEST (ColoredOutputTest , UsesNoColorWhenGTestColorFlagIsInvalid)
Definition at line 6812 of file gtest_unittest.cc.
{
  SetEnv("TERM", "xterm");  // TERM supports colors.
  GTEST_FLAG(color) = "F";
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  GTEST_FLAG(color) = "0";
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  GTEST_FLAG(color) = "unknown";
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
}
References EXPECT_FALSE, GTEST_FLAG, and anonymous_namespace{gtest_unittest.cc}::SetEnv().
TEST() [20/90]
TEST (ColoredOutputTest , UsesNoColorWhenGTestColorFlagIsNo)
Definition at line 6800 of file gtest_unittest.cc.
{
  GTEST_FLAG(color) = "no";
  SetEnv("TERM", "xterm");  // TERM supports colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_FALSE(ShouldUseColor(false));  // Stdout is not a TTY.
  SetEnv("TERM", "dumb");  // TERM doesn't support colors.
  EXPECT_FALSE(ShouldUseColor(true));  // Stdout is a TTY.
  EXPECT_FALSE(ShouldUseColor(false));  // Stdout is not a TTY.
}
References EXPECT_FALSE, GTEST_FLAG, and anonymous_namespace{gtest_unittest.cc}::SetEnv().
TEST() [21/90]
TEST (CommandLineFlagsTest , CanBeAccessedInCodeOnceGTestHIsIncluded)
Definition at line 40 of file gtest_unittest.cc.
{
  bool dummy = testing::GTEST_FLAG(also_run_disabled_tests)
      || testing::GTEST_FLAG(break_on_failure)
      || testing::GTEST_FLAG(catch_exceptions)
      || testing::GTEST_FLAG(color) != "unknown"
      || testing::GTEST_FLAG(filter) != "unknown"
      || testing::GTEST_FLAG(list_tests)
      || testing::GTEST_FLAG(output) != "unknown"
      || testing::GTEST_FLAG(print_time)
      || testing::GTEST_FLAG(random_seed)
      || testing::GTEST_FLAG(repeat) > 0
      || testing::GTEST_FLAG(show_internal_stack_frames)
      || testing::GTEST_FLAG(shuffle)
      || testing::GTEST_FLAG(stack_trace_depth) > 0
      || testing::GTEST_FLAG(stream_result_to) != "unknown"
      || testing::GTEST_FLAG(throw_on_failure);
  EXPECT_TRUE(dummy || !dummy);  // Suppresses warning that dummy is unused.
}
References EXPECT_TRUE.
TEST() [22/90]
TEST (CompileAssertTypesEqual , CompilesWhenTypesAreEqual)
Definition at line 7404 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<void, void>();
  CompileAssertTypesEqual<int*, int*>();
}
TEST() [23/90]
TEST (CopyArrayTest , WorksForDegeneratedArrays)
Definition at line 7654 of file gtest_unittest.cc.
{
  int n = 0;
  CopyArray('a', &n);
  EXPECT_EQ('a', n);
}
References EXPECT_EQ.
TEST() [24/90]
TEST (CopyArrayTest , WorksForOneDimensionalArrays)
Definition at line 7660 of file gtest_unittest.cc.
{
  const char a[3] = "hi";
  int b[3];
#ifndef __BORLANDC__  // C++Builder cannot compile some array size deductions.
  CopyArray(a, &b);
  EXPECT_TRUE(ArrayEq(a, b));
#endif
  int c[3];
  CopyArray(a, 3, c);
  EXPECT_TRUE(ArrayEq(a, c));
}
References EXPECT_TRUE.
TEST() [25/90]
TEST (CopyArrayTest , WorksForTwoDimensionalArrays)
Definition at line 7673 of file gtest_unittest.cc.
{
  const int a[2][3] = { { 0, 1, 2 }, { 3, 4, 5 } };
  int b[2][3];
#ifndef __BORLANDC__  // C++Builder cannot compile some array size deductions.
  CopyArray(a, &b);
  EXPECT_TRUE(ArrayEq(a, b));
#endif
  int c[2][3];
  CopyArray(a, 2, c);
  EXPECT_TRUE(ArrayEq(a, c));
}
References EXPECT_TRUE.
TEST() [26/90]
TEST (EventListenerDeathTest , EventsNotForwardedInDeathTestSubprecesses)
Definition at line 7201 of file gtest_unittest.cc.
{
  EXPECT_DEATH_IF_SUPPORTED({
      GTEST_CHECK_(TestEventListenersAccessor::EventForwardingEnabled(
          *GetUnitTestImpl()->listeners())) << "expected failure";},
      "expected failure");
}
References testing::internal::TestEventListenersAccessor::EventForwardingEnabled(), EXPECT_DEATH_IF_SUPPORTED, and GTEST_CHECK_.
TEST() [27/90]
TEST (EventListenerTest , AppendKeepsOrder)
Definition at line 7123 of file gtest_unittest.cc.
{
  std::vector<std::string> vec;
  TestEventListeners listeners;
  listeners.Append(new SequenceTestingListener(&vec, "1st"));
  listeners.Append(new SequenceTestingListener(&vec, "2nd"));
  listeners.Append(new SequenceTestingListener(&vec, "3rd"));
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("1st.OnTestProgramStart", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestProgramStart", vec[1].c_str());
  EXPECT_STREQ("3rd.OnTestProgramStart", vec[2].c_str());
  vec.clear();
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramEnd(
      *UnitTest::GetInstance());
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("3rd.OnTestProgramEnd", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestProgramEnd", vec[1].c_str());
  EXPECT_STREQ("1st.OnTestProgramEnd", vec[2].c_str());
  vec.clear();
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestIterationStart(
      *UnitTest::GetInstance(), 0);
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("1st.OnTestIterationStart", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestIterationStart", vec[1].c_str());
  EXPECT_STREQ("3rd.OnTestIterationStart", vec[2].c_str());
  vec.clear();
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestIterationEnd(
      *UnitTest::GetInstance(), 0);
  ASSERT_EQ(3U, vec.size());
  EXPECT_STREQ("3rd.OnTestIterationEnd", vec[0].c_str());
  EXPECT_STREQ("2nd.OnTestIterationEnd", vec[1].c_str());
  EXPECT_STREQ("1st.OnTestIterationEnd", vec[2].c_str());
}
References testing::TestEventListeners::Append(), ASSERT_EQ, EXPECT_STREQ, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestIterationEnd(), testing::TestEventListener::OnTestIterationStart(), testing::TestEventListener::OnTestProgramEnd(), and testing::TestEventListener::OnTestProgramStart().
TEST() [28/90]
TEST (EventListenerTest , default_result_printer)
Definition at line 7211 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  bool is_destroyed = false;
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  TestEventListeners listeners;
  TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, listener);
  EXPECT_EQ(listener, listeners.default_result_printer());
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
  // Replacing default_result_printer with something else should remove it
  // from the list and destroy it.
  TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, NULL);
  EXPECT_TRUE(listeners.default_result_printer() == NULL);
  EXPECT_TRUE(is_destroyed);
  // After broadcasting an event the counter is still the same, indicating
  // the listener is not in the list anymore.
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
}
References testing::TestEventListeners::default_result_printer(), EXPECT_EQ, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), and testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter().
TEST() [29/90]
TEST (EventListenerTest , default_xml_generator)
Definition at line 7270 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  bool is_destroyed = false;
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  TestEventListeners listeners;
  TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners, listener);
  EXPECT_EQ(listener, listeners.default_xml_generator());
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
  // Replacing default_xml_generator with something else should remove it
  // from the list and destroy it.
  TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners, NULL);
  EXPECT_TRUE(listeners.default_xml_generator() == NULL);
  EXPECT_TRUE(is_destroyed);
  // After broadcasting an event the counter is still the same, indicating
  // the listener is not in the list anymore.
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(1, on_start_counter);
}
References testing::TestEventListeners::default_xml_generator(), EXPECT_EQ, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), and testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator().
TEST() [30/90]
TEST (EventListenerTest , RemovingDefaultResultPrinterWorks)
Definition at line 7242 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  bool is_destroyed = false;
  // Although Append passes the ownership of this object to the list,
  // the following calls release it, and we need to delete it before the
  // test ends.
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, listener);
    EXPECT_EQ(listener, listeners.Release(listener));
    EXPECT_TRUE(listeners.default_result_printer() == NULL);
    EXPECT_FALSE(is_destroyed);
    // Broadcasting events now should not affect default_result_printer.
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_EQ(0, on_start_counter);
  }
  // Destroying the list should not affect the listener now, too.
  EXPECT_FALSE(is_destroyed);
  delete listener;
}
References testing::TestEventListeners::default_result_printer(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), testing::TestEventListeners::Release(), and testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter().
TEST() [31/90]
TEST (EventListenerTest , RemovingDefaultXmlGeneratorWorks)
Definition at line 7301 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  bool is_destroyed = false;
  // Although Append passes the ownership of this object to the list,
  // the following calls release it, and we need to delete it before the
  // test ends.
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners, listener);
    EXPECT_EQ(listener, listeners.Release(listener));
    EXPECT_TRUE(listeners.default_xml_generator() == NULL);
    EXPECT_FALSE(is_destroyed);
    // Broadcasting events now should not affect default_xml_generator.
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_EQ(0, on_start_counter);
  }
  // Destroying the list should not affect the listener now, too.
  EXPECT_FALSE(is_destroyed);
  delete listener;
}
References testing::TestEventListeners::default_xml_generator(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), testing::TestEventListeners::Release(), and testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator().
TEST() [32/90]
TEST (EventListenerTest , SuppressEventForwarding)
Definition at line 7185 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  TestListener* listener = new TestListener(&on_start_counter, NULL);
  TestEventListeners listeners;
  listeners.Append(listener);
  ASSERT_TRUE(TestEventListenersAccessor::EventForwardingEnabled(listeners));
  TestEventListenersAccessor::SuppressEventForwarding(&listeners);
  ASSERT_FALSE(TestEventListenersAccessor::EventForwardingEnabled(listeners));
  TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
      *UnitTest::GetInstance());
  EXPECT_EQ(0, on_start_counter);
}
References testing::TestEventListeners::Append(), ASSERT_FALSE, ASSERT_TRUE, testing::internal::TestEventListenersAccessor::EventForwardingEnabled(), EXPECT_EQ, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), and testing::internal::TestEventListenersAccessor::SuppressEventForwarding().
TEST() [33/90]
TEST (GTestReferenceToConstTest , Works)
Definition at line 7506 of file gtest_unittest.cc.
{
  TestGTestReferenceToConst<const char&, char>();
  TestGTestReferenceToConst<const int&, const int>();
  TestGTestReferenceToConst<const double&, double>();
  TestGTestReferenceToConst<const std::string&, const std::string&>();
}
TEST() [34/90]
TEST (HasFailureTest , ReturnsFalseWhenThereIsNoFailure)
Definition at line 6969 of file gtest_unittest.cc.
{
  EXPECT_FALSE(HasFailure());
}
References EXPECT_FALSE.
TEST() [35/90]
TEST (HasFailureTest , ReturnsTrueWhenThereAreFatalAndNonfatalFailures)
Definition at line 6987 of file gtest_unittest.cc.
{
  FailFatally();
  ADD_FAILURE();
  const bool has_failure = HasFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
References ADD_FAILURE, anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), EXPECT_TRUE, and FailFatally().
TEST() [36/90]
TEST (HasFailureTest , ReturnsTrueWhenThereIsFatalFailure)
Definition at line 6973 of file gtest_unittest.cc.
{
  FailFatally();
  const bool has_failure = HasFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
References anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), EXPECT_TRUE, and FailFatally().
TEST() [37/90]
TEST (HasFailureTest , ReturnsTrueWhenThereIsNonfatalFailure)
Definition at line 6980 of file gtest_unittest.cc.
{
  ADD_FAILURE();
  const bool has_failure = HasFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
References ADD_FAILURE, anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), and EXPECT_TRUE.
TEST() [38/90]
TEST (HasFailureTest , WorksOutsideOfTestBody)
Definition at line 6998 of file gtest_unittest.cc.
{
  EXPECT_FALSE(HasFailureHelper());
}
References EXPECT_FALSE, and HasFailureHelper().
TEST() [39/90]
TEST (HasFailureTest , WorksOutsideOfTestBody2)
Definition at line 7002 of file gtest_unittest.cc.
{
  ADD_FAILURE();
  const bool has_failure = HasFailureHelper();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_failure);
}
References ADD_FAILURE, anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), EXPECT_TRUE, and HasFailureHelper().
TEST() [40/90]
TEST (HasNonfatalFailureTest , ReturnsFalseWhenThereIsNoFailure)
Definition at line 6925 of file gtest_unittest.cc.
{
  EXPECT_FALSE(HasNonfatalFailure());
}
References EXPECT_FALSE.
TEST() [41/90]
TEST (HasNonfatalFailureTest , ReturnsFalseWhenThereIsOnlyFatalFailure)
Definition at line 6931 of file gtest_unittest.cc.
{
  FailFatally();
  const bool has_nonfatal_failure = HasNonfatalFailure();
  ClearCurrentTestPartResults();
  EXPECT_FALSE(has_nonfatal_failure);
}
References anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), EXPECT_FALSE, and FailFatally().
TEST() [42/90]
TEST (HasNonfatalFailureTest , ReturnsTrueWhenThereAreFatalAndNonfatalFailures)
Definition at line 6945 of file gtest_unittest.cc.
{
  FailFatally();
  ADD_FAILURE();
  const bool has_nonfatal_failure = HasNonfatalFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_nonfatal_failure);
}
References ADD_FAILURE, anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), EXPECT_TRUE, and FailFatally().
TEST() [43/90]
TEST (HasNonfatalFailureTest , ReturnsTrueWhenThereIsNonfatalFailure)
Definition at line 6938 of file gtest_unittest.cc.
{
  ADD_FAILURE();
  const bool has_nonfatal_failure = HasNonfatalFailure();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_nonfatal_failure);
}
References ADD_FAILURE, anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), and EXPECT_TRUE.
TEST() [44/90]
TEST (HasNonfatalFailureTest , WorksOutsideOfTestBody)
Definition at line 6958 of file gtest_unittest.cc.
{
  EXPECT_FALSE(HasNonfatalFailureHelper());
}
References EXPECT_FALSE, and HasNonfatalFailureHelper().
TEST() [45/90]
TEST (HasNonfatalFailureTest , WorksOutsideOfTestBody2)
Definition at line 6962 of file gtest_unittest.cc.
{
  ADD_FAILURE();
  const bool has_nonfatal_failure = HasNonfatalFailureHelper();
  ClearCurrentTestPartResults();
  EXPECT_TRUE(has_nonfatal_failure);
}
References ADD_FAILURE, anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults(), EXPECT_TRUE, and HasNonfatalFailureHelper().
TEST() [46/90]
TEST (ImplicitlyConvertibleTest , ValueIsCompileTimeConstant)
Definition at line 7514 of file gtest_unittest.cc.
{
  GTEST_COMPILE_ASSERT_((ImplicitlyConvertible<int, int>::value), const_true);
  GTEST_COMPILE_ASSERT_((!ImplicitlyConvertible<void*, int*>::value),
                        const_false);
}
References GTEST_COMPILE_ASSERT_.
TEST() [47/90]
TEST (ImplicitlyConvertibleTest , ValueIsFalseWhenNotConvertible)
Definition at line 7535 of file gtest_unittest.cc.
{
  EXPECT_FALSE((ImplicitlyConvertible<double, int*>::value));
  EXPECT_FALSE((ImplicitlyConvertible<void*, int*>::value));
  EXPECT_FALSE((ImplicitlyConvertible<const int*, int*>::value));
  EXPECT_FALSE((ImplicitlyConvertible<ConversionHelperBase&,
                                      ConversionHelperDerived&>::value));
}
References EXPECT_FALSE, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [48/90]
TEST (ImplicitlyConvertibleTest , ValueIsTrueWhenConvertible)
Definition at line 7522 of file gtest_unittest.cc.
{
  EXPECT_TRUE((ImplicitlyConvertible<int, double>::value));
  EXPECT_TRUE((ImplicitlyConvertible<double, int>::value));
  EXPECT_TRUE((ImplicitlyConvertible<int*, void*>::value));
  EXPECT_TRUE((ImplicitlyConvertible<int*, const int*>::value));
  EXPECT_TRUE((ImplicitlyConvertible<ConversionHelperDerived&,
                                     const ConversionHelperBase&>::value));
  EXPECT_TRUE((ImplicitlyConvertible<const ConversionHelperBase,
                                     ConversionHelperBase>::value));
}
References EXPECT_TRUE, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [49/90]
TEST (IsAProtocolMessageTest , ValueIsCompileTimeConstant)
Definition at line 7382 of file gtest_unittest.cc.
{
  GTEST_COMPILE_ASSERT_(IsAProtocolMessage<ProtocolMessage>::value,
                        const_true);
  GTEST_COMPILE_ASSERT_(!IsAProtocolMessage<int>::value, const_false);
}
References GTEST_COMPILE_ASSERT_.
TEST() [50/90]
TEST (IsAProtocolMessageTest , ValueIsFalseWhenTypeIsNotAProtocolMessage)
Definition at line 7397 of file gtest_unittest.cc.
{
  EXPECT_FALSE(IsAProtocolMessage<int>::value);
  EXPECT_FALSE(IsAProtocolMessage<const ConversionHelperBase>::value);
}
References EXPECT_FALSE.
TEST() [51/90]
TEST (IsAProtocolMessageTest , ValueIsTrueWhenTypeIsAProtocolMessage)
Definition at line 7390 of file gtest_unittest.cc.
{
  EXPECT_TRUE(IsAProtocolMessage< ::proto2::Message>::value);
  EXPECT_TRUE(IsAProtocolMessage<ProtocolMessage>::value);
}
References EXPECT_TRUE.
TEST() [52/90]
TEST (IsContainerTestTest , WorksForContainer)
Definition at line 7553 of file gtest_unittest.cc.
{
  EXPECT_EQ(sizeof(IsContainer),
            sizeof(IsContainerTest<std::vector<bool> >(0)));
  EXPECT_EQ(sizeof(IsContainer),
            sizeof(IsContainerTest<std::map<int, double> >(0)));
}
References EXPECT_EQ.
TEST() [53/90]
TEST (IsContainerTestTest , WorksForNonContainer)
Definition at line 7547 of file gtest_unittest.cc.
{
  EXPECT_EQ(sizeof(IsNotContainer), sizeof(IsContainerTest<int>(0)));
  EXPECT_EQ(sizeof(IsNotContainer), sizeof(IsContainerTest<char[5]>(0)));
  EXPECT_EQ(sizeof(IsNotContainer), sizeof(IsContainerTest<NonContainer>(0)));
}
References EXPECT_EQ.
TEST() [54/90]
TEST (IsHashTable , Basic)
Definition at line 7592 of file gtest_unittest.cc.
{
  EXPECT_TRUE(testing::internal::IsHashTable<AHashTable>::value);
  EXPECT_FALSE(testing::internal::IsHashTable<NotReallyAHashTable>::value);
#if GTEST_LANG_CXX11
  EXPECT_FALSE(testing::internal::IsHashTable<std::vector<int>>::value);
  EXPECT_TRUE(testing::internal::IsHashTable<std::unordered_set<int>>::value);
#endif  // GTEST_LANG_CXX11
#if GTEST_HAS_HASH_SET_
  EXPECT_TRUE(testing::internal::IsHashTable<__gnu_cxx::hash_set<int>>::value);
#endif  // GTEST_HAS_HASH_SET_
}
References EXPECT_FALSE, EXPECT_TRUE, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [55/90]
TEST (MessageTest , CanStreamUserTypeInGlobalNameSpace)
Definition at line 5204 of file gtest_unittest.cc.
{
  Message msg;
  Base a(1);
  msg << a << &a;  // Uses ::operator<<.
  EXPECT_STREQ("1(1)", msg.GetString().c_str());
}
References EXPECT_STREQ, and testing::Message::GetString().
TEST() [56/90]
TEST (MessageTest , CanStreamUserTypeInUnnamedNameSpace)
Definition at line 5229 of file gtest_unittest.cc.
{
  Message msg;
  MyTypeInUnnamedNameSpace a(1);
  msg << a << &a;  // Uses <unnamed_namespace>::operator<<.
  EXPECT_STREQ("1(1)", msg.GetString().c_str());
}
References EXPECT_STREQ, and testing::Message::GetString().
TEST() [57/90]
TEST (MessageTest , CanStreamUserTypeInUserNameSpace)
Definition at line 5254 of file gtest_unittest.cc.
{
  Message msg;
  namespace1::MyTypeInNameSpace1 a(1);
  msg << a << &a;  // Uses namespace1::operator<<.
  EXPECT_STREQ("1(1)", msg.GetString().c_str());
}
References EXPECT_STREQ, and testing::Message::GetString().
TEST() [58/90]
TEST (MessageTest , CanStreamUserTypeInUserNameSpaceWithStreamOperatorInGlobal)
Definition at line 5279 of file gtest_unittest.cc.
{
  Message msg;
  namespace2::MyTypeInNameSpace2 a(1);
  msg << a << &a;  // Uses ::operator<<.
  EXPECT_STREQ("1(1)", msg.GetString().c_str());
}
References EXPECT_STREQ, and testing::Message::GetString().
TEST() [59/90]
TEST (MessageTest , NullPointers)
Definition at line 5288 of file gtest_unittest.cc.
{
  Message msg;
  char* const p1 = NULL;
  unsigned char* const p2 = NULL;
  int* p3 = NULL;
  double* p4 = NULL;
  bool* p5 = NULL;
  Message* p6 = NULL;
  msg << p1 << p2 << p3 << p4 << p5 << p6;
  ASSERT_STREQ("(null)(null)(null)(null)(null)(null)",
               msg.GetString().c_str());
}
References ASSERT_STREQ, and testing::Message::GetString().
TEST() [60/90]
TEST (MessageTest , WideStrings)
Definition at line 5303 of file gtest_unittest.cc.
{
  // Streams a NULL of type const wchar_t*.
  const wchar_t* const_wstr = NULL;
  EXPECT_STREQ("(null)",
               (Message() << const_wstr).GetString().c_str());
  // Streams a NULL of type wchar_t*.
  wchar_t* wstr = NULL;
  EXPECT_STREQ("(null)",
               (Message() << wstr).GetString().c_str());
  // Streams a non-NULL of type const wchar_t*.
  const_wstr = L"abc\x8119";
  EXPECT_STREQ("abc\xe8\x84\x99",
               (Message() << const_wstr).GetString().c_str());
  // Streams a non-NULL of type wchar_t*.
  wstr = const_cast<wchar_t*>(const_wstr);
  EXPECT_STREQ("abc\xe8\x84\x99",
               (Message() << wstr).GetString().c_str());
}
References EXPECT_STREQ, and GetString().
TEST() [61/90]
TEST (NativeArrayTest , ConstructorFromArrayWorks)
Definition at line 7688 of file gtest_unittest.cc.
{
  const int a[3] = { 0, 1, 2 };
  NativeArray<int> na(a, 3, RelationToSourceReference());
  EXPECT_EQ(3U, na.size());
  EXPECT_EQ(a, na.begin());
}
References testing::internal::NativeArray< Element >::begin(), EXPECT_EQ, and testing::internal::NativeArray< Element >::size().
TEST() [62/90]
TEST (NativeArrayTest , CreatesAndDeletesCopyOfArrayWhenAskedTo)
Definition at line 7695 of file gtest_unittest.cc.
{
  typedef int Array[2];
  Array* a = new Array[1];
  (*a)[0] = 0;
  (*a)[1] = 1;
  NativeArray<int> na(*a, 2, RelationToSourceCopy());
  EXPECT_NE(*a, na.begin());
  delete[] a;
  EXPECT_EQ(0, na.begin()[0]);
  EXPECT_EQ(1, na.begin()[1]);
  // We rely on the heap checker to verify that na deletes the copy of
  // array.
}
References testing::internal::NativeArray< Element >::begin(), EXPECT_EQ, and EXPECT_NE.
TEST() [63/90]
TEST (NativeArrayTest , MethodsWork)
Definition at line 7718 of file gtest_unittest.cc.
{
  const int a[3] = { 0, 1, 2 };
  NativeArray<int> na(a, 3, RelationToSourceCopy());
  ASSERT_EQ(3U, na.size());
  EXPECT_EQ(3, na.end() - na.begin());
  NativeArray<int>::const_iterator it = na.begin();
  EXPECT_EQ(0, *it);
  ++it;
  EXPECT_EQ(1, *it);
  it++;
  EXPECT_EQ(2, *it);
  ++it;
  EXPECT_EQ(na.end(), it);
  EXPECT_TRUE(na == na);
  NativeArray<int> na2(a, 3, RelationToSourceReference());
  EXPECT_TRUE(na == na2);
  const int b1[3] = { 0, 1, 1 };
  const int b2[4] = { 0, 1, 2, 3 };
  EXPECT_FALSE(na == NativeArray<int>(b1, 3, RelationToSourceReference()));
  EXPECT_FALSE(na == NativeArray<int>(b2, 4, RelationToSourceCopy()));
}
References ASSERT_EQ, testing::internal::NativeArray< Element >::begin(), testing::internal::NativeArray< Element >::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, and testing::internal::NativeArray< Element >::size().
TEST() [64/90]
TEST (NativeArrayTest , TypeMembersAreCorrect)
Definition at line 7710 of file gtest_unittest.cc.
{
  StaticAssertTypeEq<char, NativeArray<char>::value_type>();
  StaticAssertTypeEq<int[2], NativeArray<int[2]>::value_type>();
  StaticAssertTypeEq<const char*, NativeArray<char>::const_iterator>();
  StaticAssertTypeEq<const bool(*)[2], NativeArray<bool[2]>::const_iterator>();
}
TEST() [65/90]
TEST (NativeArrayTest , WorksForTwoDimensionalArray)
Definition at line 7744 of file gtest_unittest.cc.
{
  const char a[2][3] = { "hi", "lo" };
  NativeArray<char[3]> na(a, 2, RelationToSourceReference());
  ASSERT_EQ(2U, na.size());
  EXPECT_EQ(a, na.begin());
}
References ASSERT_EQ, testing::internal::NativeArray< Element >::begin(), EXPECT_EQ, and testing::internal::NativeArray< Element >::size().
TEST() [66/90]
TEST (RemoveConstTest , DoesNotAffectNonConstType)
Definition at line 7435 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<int, RemoveConst<int>::type>();
  CompileAssertTypesEqual<char&, RemoveConst<char&>::type>();
}
TEST() [67/90]
TEST (RemoveConstTest , MacroVersion)
Definition at line 7454 of file gtest_unittest.cc.
{
  TestGTestRemoveConst<int, int>();
  TestGTestRemoveConst<double&, double&>();
  TestGTestRemoveConst<char, const char>();
}
TEST() [68/90]
TEST (RemoveConstTest , RemovesConst)
Definition at line 7441 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<int, RemoveConst<const int>::type>();
  CompileAssertTypesEqual<char[2], RemoveConst<const char[2]>::type>();
  CompileAssertTypesEqual<char[2][3], RemoveConst<const char[2][3]>::type>();
}
TEST() [69/90]
TEST (RemoveReferenceTest , DoesNotAffectNonReferenceType)
Definition at line 7410 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<int, RemoveReference<int>::type>();
  CompileAssertTypesEqual<const char, RemoveReference<const char>::type>();
}
TEST() [70/90]
TEST (RemoveReferenceTest , MacroVersion)
Definition at line 7428 of file gtest_unittest.cc.
{
  TestGTestRemoveReference<int, int>();
  TestGTestRemoveReference<const char, const char&>();
}
TEST() [71/90]
TEST (RemoveReferenceTest , RemovesReference)
Definition at line 7416 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<int, RemoveReference<int&>::type>();
  CompileAssertTypesEqual<const char, RemoveReference<const char&>::type>();
}
TEST() [72/90]
TEST (RemoveReferenceToConstTest , Works)
Definition at line 7467 of file gtest_unittest.cc.
{
  TestGTestRemoveReferenceAndConst<int, int>();
  TestGTestRemoveReferenceAndConst<double, double&>();
  TestGTestRemoveReferenceAndConst<char, const char>();
  TestGTestRemoveReferenceAndConst<char, const char&>();
  TestGTestRemoveReferenceAndConst<const char*, const char*>();
}
TEST() [73/90]
TEST (SkipPrefixTest , DoesNotSkipWhenPrefixDoesNotMatch)
Definition at line 7765 of file gtest_unittest.cc.
{
  const char* const str = "world";
  const char* p = str;
  EXPECT_FALSE(SkipPrefix("W", &p));
  EXPECT_EQ(str, p);
  p = str;
  EXPECT_FALSE(SkipPrefix("world!", &p));
  EXPECT_EQ(str, p);
}
References EXPECT_EQ, and EXPECT_FALSE.
TEST() [74/90]
TEST (SkipPrefixTest , SkipsWhenPrefixMatches)
Definition at line 7753 of file gtest_unittest.cc.
{
  const char* const str = "hello";
  const char* p = str;
  EXPECT_TRUE(SkipPrefix("", &p));
  EXPECT_EQ(str, p);
  p = str;
  EXPECT_TRUE(SkipPrefix("hell", &p));
  EXPECT_EQ(str + 4, p);
}
References EXPECT_EQ, and EXPECT_TRUE.
TEST() [75/90]
TEST (StaticAssertTypeEqTest , CompilesForEqualTypes)
Definition at line 6920 of file gtest_unittest.cc.
{
  StaticAssertTypeEq<int, IntAlias>();
  StaticAssertTypeEq<int*, IntAlias*>();
}
TEST() [76/90]
TEST (StaticAssertTypeEqTest , WorksInClass)
Definition at line 6912 of file gtest_unittest.cc.
{
  StaticAssertTypeEqTestHelper<bool>();
}
TEST() [77/90]
TEST (StreamingAssertionsTest , FloatingPointEquals)
Definition at line 6733 of file gtest_unittest.cc.
{
  EXPECT_FLOAT_EQ(1.0, 1.0) << "unexpected failure";
  ASSERT_FLOAT_EQ(1.0, 1.0) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(0.0, 1.0) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_FLOAT_EQ(0.0, 1.0) << "expected failure",
                       "expected failure");
}
References ASSERT_FLOAT_EQ, EXPECT_FATAL_FAILURE, EXPECT_FLOAT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [78/90]
TEST (StreamingAssertionsTest , IntegerEquals)
Definition at line 6679 of file gtest_unittest.cc.
{
  EXPECT_EQ(1, 1) << "unexpected failure";
  ASSERT_EQ(1, 1) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(1, 2) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_EQ(1, 2) << "expected failure",
                       "expected failure");
}
References ASSERT_EQ, EXPECT_EQ, EXPECT_FATAL_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [79/90]
TEST (StreamingAssertionsTest , IntegerLessThan)
Definition at line 6688 of file gtest_unittest.cc.
{
  EXPECT_LT(1, 2) << "unexpected failure";
  ASSERT_LT(1, 2) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(2, 1) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_LT(2, 1) << "expected failure",
                       "expected failure");
}
References ASSERT_LT, EXPECT_FATAL_FAILURE, EXPECT_LT, and EXPECT_NONFATAL_FAILURE.
TEST() [80/90]
TEST (StreamingAssertionsTest , StringNotEqualIgnoringCase)
Definition at line 6724 of file gtest_unittest.cc.
{
  EXPECT_STRCASENE("foo", "bar") << "unexpected failure";
  ASSERT_STRCASENE("foo", "bar") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRCASENE("foo", "FOO") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STRCASENE("bar", "BAR") << "expected failure",
                       "expected failure");
}
References ASSERT_STRCASENE, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_STRCASENE.
TEST() [81/90]
TEST (StreamingAssertionsTest , StringsEqual)
Definition at line 6697 of file gtest_unittest.cc.
{
  EXPECT_STREQ("foo", "foo") << "unexpected failure";
  ASSERT_STREQ("foo", "foo") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STREQ("foo", "bar") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STREQ("foo", "bar") << "expected failure",
                       "expected failure");
}
References ASSERT_STREQ, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_STREQ.
TEST() [82/90]
TEST (StreamingAssertionsTest , StringsEqualIgnoringCase)
Definition at line 6715 of file gtest_unittest.cc.
{
  EXPECT_STRCASEEQ("foo", "FOO") << "unexpected failure";
  ASSERT_STRCASEEQ("foo", "FOO") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRCASEEQ("foo", "bar") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STRCASEEQ("foo", "bar") << "expected failure",
                       "expected failure");
}
References ASSERT_STRCASEEQ, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_STRCASEEQ.
TEST() [83/90]
TEST (StreamingAssertionsTest , StringsNotEqual)
Definition at line 6706 of file gtest_unittest.cc.
{
  EXPECT_STRNE("foo", "bar") << "unexpected failure";
  ASSERT_STRNE("foo", "bar") << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRNE("foo", "foo") << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_STRNE("foo", "foo") << "expected failure",
                       "expected failure");
}
References ASSERT_STRNE, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_STRNE.
TEST() [84/90]
TEST (StreamingAssertionsTest , Truth)
Definition at line 6656 of file gtest_unittest.cc.
{
  EXPECT_TRUE(true) << "unexpected failure";
  ASSERT_TRUE(true) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(false) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(false) << "expected failure",
                       "expected failure");
}
References ASSERT_TRUE, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_TRUE.
TEST() [85/90]
TEST (StreamingAssertionsTest , Truth2)
Definition at line 6665 of file gtest_unittest.cc.
{
  EXPECT_FALSE(false) << "unexpected failure";
  ASSERT_FALSE(false) << "unexpected failure";
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(true) << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(ASSERT_FALSE(true) << "expected failure",
                       "expected failure");
}
References ASSERT_FALSE, EXPECT_FALSE, EXPECT_FATAL_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [86/90]
TEST (StreamingAssertionsTest , Unconditional)
Definition at line 6643 of file gtest_unittest.cc.
{
  SUCCEED() << "expected success";
  EXPECT_NONFATAL_FAILURE(ADD_FAILURE() << "expected failure",
                          "expected failure");
  EXPECT_FATAL_FAILURE(FAIL() << "expected failure",
                       "expected failure");
}
References ADD_FAILURE, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, FAIL, and SUCCEED.
TEST() [87/90]
TEST (TestEventListenersTest , Append)
Definition at line 7069 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  bool is_destroyed = false;
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    listeners.Append(listener);
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_EQ(1, on_start_counter);
  }
  EXPECT_TRUE(is_destroyed);
}
References testing::TestEventListeners::Append(), EXPECT_EQ, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), and testing::TestEventListener::OnTestProgramStart().
TEST() [88/90]
TEST (TestEventListenersTest , ConstructionWorks)
Definition at line 7033 of file gtest_unittest.cc.
{
  TestEventListeners listeners;
  EXPECT_TRUE(TestEventListenersAccessor::GetRepeater(&listeners) != NULL);
  EXPECT_TRUE(listeners.default_result_printer() == NULL);
  EXPECT_TRUE(listeners.default_xml_generator() == NULL);
}
References testing::TestEventListeners::default_result_printer(), testing::TestEventListeners::default_xml_generator(), EXPECT_TRUE, and testing::internal::TestEventListenersAccessor::GetRepeater().
TEST() [89/90]
TEST (TestEventListenersTest , DestructionWorks)
Definition at line 7043 of file gtest_unittest.cc.
{
  bool default_result_printer_is_destroyed = false;
  bool default_xml_printer_is_destroyed = false;
  bool extra_listener_is_destroyed = false;
  TestListener* default_result_printer = new TestListener(
      NULL, &default_result_printer_is_destroyed);
  TestListener* default_xml_printer = new TestListener(
      NULL, &default_xml_printer_is_destroyed);
  TestListener* extra_listener = new TestListener(
      NULL, &extra_listener_is_destroyed);
  {
    TestEventListeners listeners;
    TestEventListenersAccessor::SetDefaultResultPrinter(&listeners,
                                                        default_result_printer);
    TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners,
                                                       default_xml_printer);
    listeners.Append(extra_listener);
  }
  EXPECT_TRUE(default_result_printer_is_destroyed);
  EXPECT_TRUE(default_xml_printer_is_destroyed);
  EXPECT_TRUE(extra_listener_is_destroyed);
}
References testing::TestEventListeners::Append(), EXPECT_TRUE, testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter(), and testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator().
TEST() [90/90]
TEST (TestEventListenersTest , Release)
Definition at line 7164 of file gtest_unittest.cc.
{
  int on_start_counter = 0;
  bool is_destroyed = false;
  // Although Append passes the ownership of this object to the list,
  // the following calls release it, and we need to delete it before the
  // test ends.
  TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
  {
    TestEventListeners listeners;
    listeners.Append(listener);
    EXPECT_EQ(listener, listeners.Release(listener));
    TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
        *UnitTest::GetInstance());
    EXPECT_TRUE(listeners.Release(listener) == NULL);
  }
  EXPECT_EQ(0, on_start_counter);
  EXPECT_FALSE(is_destroyed);
  delete listener;
}
References testing::TestEventListeners::Append(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), and testing::TestEventListeners::Release().
TEST_F() [1/2]
TEST_F (AdHocTestResultTest , AdHocTestResultForTestCaseShowsFailure)
Definition at line 7786 of file gtest_unittest.cc.
{
  const testing::TestResult& test_result = testing::UnitTest::GetInstance()
                                               ->current_test_case()
                                               ->ad_hoc_test_result();
  EXPECT_TRUE(test_result.Failed());
}
References testing::TestCase::ad_hoc_test_result(), testing::UnitTest::current_test_case(), EXPECT_TRUE, testing::TestResult::Failed(), and testing::UnitTest::GetInstance().
TEST_F() [2/2]
TEST_F (AdHocTestResultTest , AdHocTestResultTestForUnitTestDoesNotShowFailure)
Definition at line 7793 of file gtest_unittest.cc.
{
  const testing::TestResult& test_result =
      testing::UnitTest::GetInstance()->ad_hoc_test_result();
  EXPECT_FALSE(test_result.Failed());
}
References testing::UnitTest::ad_hoc_test_result(), EXPECT_FALSE, testing::TestResult::Failed(), and testing::UnitTest::GetInstance().
TestGTestAddReference()
template<typename T1 , typename T2 > void TestGTestAddReference ()
Definition at line 7490 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<T1, GTEST_ADD_REFERENCE_(T2)>();
}
TestGTestReferenceToConst()
template<typename T1 , typename T2 > void TestGTestReferenceToConst ()
Definition at line 7502 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<T1, GTEST_REFERENCE_TO_CONST_(T2)>();
}
TestGTestRemoveConst()
template<typename T1 , typename T2 > void TestGTestRemoveConst ()
Definition at line 7450 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<T1, GTEST_REMOVE_CONST_(T2)>();
}
TestGTestRemoveReference()
template<typename T1 , typename T2 > void TestGTestRemoveReference ()
Definition at line 7424 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<T1, GTEST_REMOVE_REFERENCE_(T2)>();
}
TestGTestRemoveReferenceAndConst()
template<typename T1 , typename T2 > void TestGTestRemoveReferenceAndConst ()
Definition at line 7463 of file gtest_unittest.cc.
{
  CompileAssertTypesEqual<T1, GTEST_REMOVE_REFERENCE_AND_CONST_(T2)>();
}
Variable Documentation
GTEST_ATTRIBUTE_UNUSED_
bool dummy2 GTEST_ATTRIBUTE_UNUSED_ = StaticAssertTypeEq<bool, bool>() static
Definition at line 6900 of file gtest_unittest.cc.