wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_environment_test.cc File Reference
gtest_environment_test.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include "gtest/gtest.h"
#include "src/gtest-internal-inl.h"
Classes
class anonymous_namespace{gtest_environment_test.cc}::MyEnvironment
Namespaces
namespace testing
namespace anonymous_namespace{gtest_environment_test.cc}
Enumerations
enum anonymous_namespace{gtest_environment_test.cc}::FailureType { anonymous_namespace{gtest_environment_test.cc}::NO_FAILURE , anonymous_namespace{gtest_environment_test.cc}::NON_FATAL_FAILURE , anonymous_namespace{gtest_environment_test.cc}::FATAL_FAILURE }
Functions
testing::GTEST_DECLARE_string_ (filter)
anonymous_namespace{gtest_environment_test.cc}::TEST (FooTest, Bar)
void anonymous_namespace{gtest_environment_test.cc}::Check (bool condition, const char *msg)
int anonymous_namespace{gtest_environment_test.cc}::RunAllTests (MyEnvironment *env, FailureType failure)
int main (int argc, char **argv)
Variables
bool anonymous_namespace{gtest_environment_test.cc}::test_was_run
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 134 of file gtest_environment_test.cc.
{
  testing::InitGoogleTest(&argc, argv);
  // Registers a global test environment, and verifies that the
  // registration function returns its argument.
  MyEnvironment* const env = new MyEnvironment;
  Check(testing::AddGlobalTestEnvironment(env) == env,
        "AddGlobalTestEnvironment() should return its argument.");
  // Verifies that RUN_ALL_TESTS() runs the tests when the global
  // set-up is successful.
  Check(RunAllTests(env, NO_FAILURE) != 0,
        "RUN_ALL_TESTS() should return non-zero, as the global tear-down "
        "should generate a failure.");
  Check(test_was_run,
        "The tests should run, as the global set-up should generate no "
        "failure");
  Check(env->tear_down_was_run(),
        "The global tear-down should run, as the global set-up was run.");
  // Verifies that RUN_ALL_TESTS() runs the tests when the global
  // set-up generates no fatal failure.
  Check(RunAllTests(env, NON_FATAL_FAILURE) != 0,
        "RUN_ALL_TESTS() should return non-zero, as both the global set-up "
        "and the global tear-down should generate a non-fatal failure.");
  Check(test_was_run,
        "The tests should run, as the global set-up should generate no "
        "fatal failure.");
  Check(env->tear_down_was_run(),
        "The global tear-down should run, as the global set-up was run.");
  // Verifies that RUN_ALL_TESTS() runs no test when the global set-up
  // generates a fatal failure.
  Check(RunAllTests(env, FATAL_FAILURE) != 0,
        "RUN_ALL_TESTS() should return non-zero, as the global set-up "
        "should generate a fatal failure.");
  Check(!test_was_run,
        "The tests should not run, as the global set-up should generate "
        "a fatal failure.");
  Check(env->tear_down_was_run(),
        "The global tear-down should run, as the global set-up was run.");
  // Verifies that RUN_ALL_TESTS() doesn't do global set-up or
  // tear-down when there is no test to run.
  testing::GTEST_FLAG(filter) = "-*";
  Check(RunAllTests(env, NO_FAILURE) == 0,
        "RUN_ALL_TESTS() should return zero, as there is no test to run.");
  Check(!env->set_up_was_run(),
        "The global set-up should not run, as there is no test to run.");
  Check(!env->tear_down_was_run(),
        "The global tear-down should not run, "
        "as the global set-up was not run.");
  printf("PASS\n");
  return 0;
}
References testing::AddGlobalTestEnvironment(), anonymous_namespace{gtest_environment_test.cc}::Check(), anonymous_namespace{gtest_environment_test.cc}::FATAL_FAILURE, testing::InitGoogleTest(), anonymous_namespace{gtest_environment_test.cc}::NO_FAILURE, anonymous_namespace{gtest_environment_test.cc}::NON_FATAL_FAILURE, RunAllTests(), and anonymous_namespace{gtest_environment_test.cc}::test_was_run.