wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_assert_by_exception_test.cc File Reference
gtest_assert_by_exception_test.cc File Reference
#include "gtest/gtest.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdexcept>
Classes
class ThrowListener
Functions
void Fail (const char *msg)
static void AssertFalse ()
TEST (Test, Test)
TEST (Test, Test2)
int main (int argc, char **argv)
Variables
int kTestForContinuingTest = 0
Function Documentation
AssertFalse()
static void AssertFalse () static
Definition at line 59 of file gtest_assert_by_exception_test.cc.
{
  ASSERT_EQ(2, 3) << "Expected failure";
}
References ASSERT_EQ.
Fail()
void Fail (const char * msg)
Definition at line 53 of file gtest_assert_by_exception_test.cc.
{
  printf("FAILURE: %s\n", msg);
  fflush(stdout);
  exit(1);
}
main()
int main (int argc, char ** argv)
Definition at line 105 of file gtest_assert_by_exception_test.cc.
{
  testing::InitGoogleTest(&argc, argv);
  testing::UnitTest::GetInstance()->listeners().Append(new ThrowListener);
  int result = RUN_ALL_TESTS();
  if (result == 0) {
    printf("RUN_ALL_TESTS returned %d\n", result);
    Fail("Expected failure instead.");
  }
  if (kTestForContinuingTest == 0) {
    Fail("Should have continued with other tests, but did not.");
  }
  return 0;
}
References testing::TestEventListeners::Append(), Fail(), testing::UnitTest::GetInstance(), testing::InitGoogleTest(), kTestForContinuingTest, testing::UnitTest::listeners(), and RUN_ALL_TESTS().
TEST() [1/2]
TEST (Test , Test)
Definition at line 65 of file gtest_assert_by_exception_test.cc.
                 {
  // A successful assertion shouldn't throw.
  try {
    EXPECT_EQ(3, 3);
  } catch(...) {
    Fail("A successful assertion wrongfully threw.");
  }
  // A successful assertion shouldn't throw.
  try {
    EXPECT_EQ(3, 4);
  } catch(...) {
    Fail("A failed non-fatal assertion wrongfully threw.");
  }
  // A failed assertion should throw.
  try {
    AssertFalse();
  } catch(const testing::AssertionException& e) {
    if (strstr(e.what(), "Expected failure") != NULL)
      throw;
    printf("%s",
           "A failed assertion did throw an exception of the right type, "
           "but the message is incorrect.  Instead of containing \"Expected "
           "failure\", it is:\n");
    Fail(e.what());
  } catch(...) {
    Fail("A failed assertion threw the wrong type of exception.");
  }
  Fail("A failed assertion should've thrown but didn't.");
}
References AssertFalse(), EXPECT_EQ, and Fail().
TEST() [2/2]
TEST (Test , Test2)
Definition at line 100 of file gtest_assert_by_exception_test.cc.
                  {
  // FIXME(sokolov): how to force Test2 to be after Test?
  kTestForContinuingTest = 1;
}
References kTestForContinuingTest.
Variable Documentation
kTestForContinuingTest
int kTestForContinuingTest = 0
Definition at line 98 of file gtest_assert_by_exception_test.cc.