wiNpoS: rapidjson/thirdparty/gtest/googletest/test/gtest_xml_output_unittest_.cc File Reference
gtest_xml_output_unittest_.cc File Reference
#include "gtest/gtest.h"
Classes
class SuccessfulTest
class FailedTest
class DisabledTest
class PropertyRecordingTest
class ValueParamTest
Functions
TEST_F (SuccessfulTest, Succeeds)
TEST_F (FailedTest, Fails)
TEST_F (DisabledTest, DISABLED_test_not_run)
TEST (MixedResultTest, Succeeds)
TEST (MixedResultTest, Fails)
TEST (MixedResultTest, DISABLED_test)
TEST (XmlQuotingTest, OutputsCData)
TEST (InvalidCharactersTest, InvalidCharactersInMessage)
TEST_F (PropertyRecordingTest, OneProperty)
TEST_F (PropertyRecordingTest, IntValuedProperty)
TEST_F (PropertyRecordingTest, ThreeProperties)
TEST_F (PropertyRecordingTest, TwoValuesForOneKeyUsesLastValue)
TEST (NoFixtureTest, RecordProperty)
void ExternalUtilityThatCallsRecordProperty (const std::string &key, int value)
void ExternalUtilityThatCallsRecordProperty (const std::string &key, const std::string &value)
TEST (NoFixtureTest, ExternalUtilityThatCallsRecordIntValuedProperty)
TEST (NoFixtureTest, ExternalUtilityThatCallsRecordStringValuedProperty)
TEST_P (ValueParamTest, HasValueParamAttribute)
TEST_P (ValueParamTest, AnotherTestThatHasValueParamAttribute)
INSTANTIATE_TEST_CASE_P (Single, ValueParamTest, Values(33, 42))
int main (int argc, char **argv)
Function Documentation
ExternalUtilityThatCallsRecordProperty() [1/2]
void ExternalUtilityThatCallsRecordProperty (const std::string & key, const std::string & value)
Definition at line 128 of file gtest_xml_output_unittest_.cc.
{
  testing::Test::RecordProperty(key, value);
}
References testing::Test::RecordProperty().
ExternalUtilityThatCallsRecordProperty() [2/2]
void ExternalUtilityThatCallsRecordProperty (const std::string & key, int value)
Definition at line 124 of file gtest_xml_output_unittest_.cc.
{
  testing::Test::RecordProperty(key, value);
}
References testing::Test::RecordProperty().
INSTANTIATE_TEST_CASE_P()
INSTANTIATE_TEST_CASE_P (Single , ValueParamTest , Values(33, 42))
main()
int main (int argc, char ** argv)
Definition at line 170 of file gtest_xml_output_unittest_.cc.
{
  InitGoogleTest(&argc, argv);
  if (argc > 1 && strcmp(argv[1], "--shut_down_xml") == 0) {
    TestEventListeners& listeners = UnitTest::GetInstance()->listeners();
    delete listeners.Release(listeners.default_xml_generator());
  }
  testing::Test::RecordProperty("ad_hoc_property", "42");
  return RUN_ALL_TESTS();
}
References testing::Test::RecordProperty(), and RUN_ALL_TESTS().
TEST() [1/8]
TEST (InvalidCharactersTest , InvalidCharactersInMessage)
Definition at line 91 of file gtest_xml_output_unittest_.cc.
{
  FAIL() << "Invalid characters in brackets [\x1\x2]";
}
References FAIL.
TEST() [2/8]
TEST (MixedResultTest , DISABLED_test)
Definition at line 80 of file gtest_xml_output_unittest_.cc.
{
  FAIL() << "Unexpected failure: Disabled test should not be run";
}
References FAIL.
TEST() [3/8]
TEST (MixedResultTest , Fails)
Definition at line 75 of file gtest_xml_output_unittest_.cc.
{
  EXPECT_EQ(1, 2);
  ASSERT_EQ(2, 3);
}
References ASSERT_EQ, and EXPECT_EQ.
TEST() [4/8]
TEST (MixedResultTest , Succeeds)
Definition at line 70 of file gtest_xml_output_unittest_.cc.
{
  EXPECT_EQ(1, 1);
  ASSERT_EQ(1, 1);
}
References ASSERT_EQ, and EXPECT_EQ.
TEST() [5/8]
TEST (NoFixtureTest , ExternalUtilityThatCallsRecordIntValuedProperty)
Definition at line 133 of file gtest_xml_output_unittest_.cc.
{
  ExternalUtilityThatCallsRecordProperty("key_for_utility_int", 1);
}
References ExternalUtilityThatCallsRecordProperty().
TEST() [6/8]
TEST (NoFixtureTest , ExternalUtilityThatCallsRecordStringValuedProperty)
Definition at line 137 of file gtest_xml_output_unittest_.cc.
{
  ExternalUtilityThatCallsRecordProperty("key_for_utility_string", "1");
}
References ExternalUtilityThatCallsRecordProperty().
TEST() [7/8]
TEST (NoFixtureTest , RecordProperty)
Definition at line 120 of file gtest_xml_output_unittest_.cc.
{
  RecordProperty("key", "1");
}
TEST() [8/8]
TEST (XmlQuotingTest , OutputsCData)
Definition at line 84 of file gtest_xml_output_unittest_.cc.
{
  FAIL() << "XML output: "
            "<?xml encoding=\"utf-8\"><top><![CDATA[cdata text]]></top>";
}
References FAIL.
TEST_F() [1/7]
TEST_F (DisabledTest , DISABLED_test_not_run)
Definition at line 66 of file gtest_xml_output_unittest_.cc.
{
  FAIL() << "Unexpected failure: Disabled test should not be run";
}
References FAIL.
TEST_F() [2/7]
TEST_F (FailedTest , Fails)
Definition at line 59 of file gtest_xml_output_unittest_.cc.
{
  ASSERT_EQ(1, 2);
}
References ASSERT_EQ.
TEST_F() [3/7]
TEST_F (PropertyRecordingTest , IntValuedProperty)
Definition at line 105 of file gtest_xml_output_unittest_.cc.
{
  RecordProperty("key_int", 1);
}
TEST_F() [4/7]
TEST_F (PropertyRecordingTest , OneProperty)
Definition at line 101 of file gtest_xml_output_unittest_.cc.
{
  RecordProperty("key_1", "1");
}
TEST_F() [5/7]
TEST_F (PropertyRecordingTest , ThreeProperties)
Definition at line 109 of file gtest_xml_output_unittest_.cc.
{
  RecordProperty("key_1", "1");
  RecordProperty("key_2", "2");
  RecordProperty("key_3", "3");
}
TEST_F() [6/7]
TEST_F (PropertyRecordingTest , TwoValuesForOneKeyUsesLastValue)
Definition at line 115 of file gtest_xml_output_unittest_.cc.
{
  RecordProperty("key_1", "1");
  RecordProperty("key_1", "2");
}
TEST_F() [7/7]
TEST_F (SuccessfulTest , Succeeds)
Definition at line 51 of file gtest_xml_output_unittest_.cc.
{
  SUCCEED() << "This is a success.";
  ASSERT_EQ(1, 1);
}
References ASSERT_EQ, and SUCCEED.
TEST_P() [1/2]
TEST_P (ValueParamTest , AnotherTestThatHasValueParamAttribute)
Definition at line 145 of file gtest_xml_output_unittest_.cc.
{}
TEST_P() [2/2]
TEST_P (ValueParamTest , HasValueParamAttribute)
Definition at line 144 of file gtest_xml_output_unittest_.cc.
{}