wiNpoS: rapidjson/example/lookaheadparser/lookaheadparser.cpp File Reference
lookaheadparser.cpp File Reference
#include "rapidjson/reader.h"
#include "rapidjson/document.h"
#include <iostream>
Classes
class LookaheadParserHandler
class LookaheadParser
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 285 of file lookaheadparser.cpp.
           {
    using namespace std;
    char json[] = " { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null,"
        "\"i\":123, \"pi\": 3.1416, \"a\":[-1, 2, 3, 4, \"array\", []], \"skipArrays\":[1, 2, [[[3]]]], "
        "\"skipObject\":{ \"i\":0, \"t\":true, \"n\":null, \"d\":123.45 }, "
        "\"skipNested\":[[[[{\"\":0}, {\"\":[-9.87]}]]], [], []], "
        "\"skipString\":\"zzz\", \"reachedEnd\":null, \"t\":true }";
    LookaheadParser r(json);
    RAPIDJSON_ASSERT(r.PeekType() == kObjectType);
    r.EnterObject();
    while (const char* key = r.NextObjectKey()) {
        if (0 == strcmp(key, "hello")) {
            RAPIDJSON_ASSERT(r.PeekType() == kStringType);
            cout << key << ":" << r.GetString() << endl;
        }
        else if (0 == strcmp(key, "t") || 0 == strcmp(key, "f")) {
            RAPIDJSON_ASSERT(r.PeekType() == kTrueType || r.PeekType() == kFalseType);
            cout << key << ":" << r.GetBool() << endl;
            continue;
        }
        else if (0 == strcmp(key, "n")) {
            RAPIDJSON_ASSERT(r.PeekType() == kNullType);
            r.GetNull();
            cout << key << endl;
            continue;
        }
        else if (0 == strcmp(key, "pi")) {
            RAPIDJSON_ASSERT(r.PeekType() == kNumberType);
            cout << key << ":" << r.GetDouble() << endl;
            continue;
        }
        else if (0 == strcmp(key, "a")) {
            RAPIDJSON_ASSERT(r.PeekType() == kArrayType);
            r.EnterArray();
            cout << key << ":[ ";
            while (r.NextArrayValue()) {
                if (r.PeekType() == kNumberType) {
                    cout << r.GetDouble() << " ";
                }
                else if (r.PeekType() == kStringType) {
                    cout << r.GetString() << " ";
                }
                else {
                    r.SkipArray();
                    break;
                }
            }
            cout << "]" << endl;
        }
        else {
            cout << key << ":skipped" << endl;
            r.SkipValue();
        }
    }
    return 0;
}
References LookaheadParser::EnterArray(), LookaheadParser::EnterObject(), LookaheadParser::GetBool(), LookaheadParser::GetDouble(), LookaheadParser::GetNull(), LookaheadParser::GetString(), rapidjson::kArrayType, rapidjson::kFalseType, rapidjson::kNullType, rapidjson::kNumberType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::kTrueType, LookaheadParser::NextArrayValue(), LookaheadParser::NextObjectKey(), LookaheadParser::PeekType(), RAPIDJSON_ASSERT, LookaheadParser::SkipArray(), and LookaheadParser::SkipValue().