wiNpoS: testing::gmock_matchers_test Namespace Reference
testing::gmock_matchers_test Namespace Reference
Namespaces
namespace anonymous_namespace{gmock-matchers_test.cc}
namespace convertible_from_any
Classes
class AClass
class AllArgsHelper
struct AStruct
class BacktrackingBPMTest
class Base
class BipartiteNonSquareTest
class BipartiteRandomTest
class BipartiteTest
class ConstPropagatingPtr
class ConvertibleToBool
class Derived
class DerivedClass
struct DerivedStruct
class DivisibleByImpl
class EvenMatcherImpl
class FloatingPointNearTest
class FloatingPointTest
struct Functor
class GreaterThanMatcher
struct IntReferenceWrapper
class IntValue
class IsGreaterThan
class IsHalfOfMatcher
class NewEvenMatcherImpl
struct NonImplicitlyConstructibleTypeWithOperatorEq
class NotCopyable
class OptionalMatchersHelper
class OtherDerived
struct PolymorphicFunctor
class PolymorphicIsEvenImpl
class ReferencesBarOrIsZeroImpl
struct ReferencingFunctor
class SampleAnyType
class SampleOptionalInt
class SampleVariantIntString
class Streamlike
struct Type
class Uncopyable
struct Undefined
class UnorderedElementsAreTest
class Unprintable
Typedefs
typedef ::testing::tuple< long, int > Tuple2
typedef FloatingPointTest< float > FloatTest
typedef FloatingPointNearTest< float > FloatNearTest
typedef FloatingPointTest< double > DoubleTest
typedef FloatingPointNearTest< double > DoubleNearTest
Functions
Matcher< int > GreaterThan (int n)
std::string OfType (const std::string &type_name)
template<typename T >
std::string Describe (const Matcher< T > &m)
template<typename T >
std::string DescribeNegation (const Matcher< T > &m)
template<typename MatcherType , typename Value >
std::string Explain (const MatcherType &m, const Value &x)
TEST (MonotonicMatcherTest, IsPrintable)
TEST (MatchResultListenerTest, StreamingWorks)
TEST (MatchResultListenerTest, CanAccessUnderlyingStream)
TEST (MatchResultListenerTest, IsInterestedWorks)
TEST (MatcherInterfaceTest, CanBeImplementedUsingPublishedAPI)
TEST (MatcherInterfaceTest, CanBeImplementedUsingNewAPI)
TEST (MatcherTest, CanBeDefaultConstructed)
TEST (MatcherTest, CanBeConstructedFromMatcherInterface)
TEST (MatcherTest, CanBeImplicitlyConstructedFromValue)
TEST (MatcherTest, CanBeImplicitlyConstructedFromNULL)
TEST (MatcherTest, CanBeConstructedFromUndefinedVariable)
TEST (MatcherTest, CanAcceptAbstractClass)
TEST (MatcherTest, IsCopyable)
TEST (MatcherTest, CanDescribeItself)
TEST (MatcherTest, MatchAndExplain)
TEST (StringMatcherTest, CanBeImplicitlyConstructedFromCStringLiteral)
TEST (StringMatcherTest, CanBeImplicitlyConstructedFromString)
TEST (MakeMatcherTest, ConstructsMatcherFromMatcherInterface)
PolymorphicMatcher< ReferencesBarOrIsZeroImpl > ReferencesBarOrIsZero ()
TEST (MakePolymorphicMatcherTest, ConstructsMatcherUsingOldAPI)
PolymorphicMatcher< PolymorphicIsEvenImpl > PolymorphicIsEven ()
TEST (MakePolymorphicMatcherTest, ConstructsMatcherUsingNewAPI)
TEST (MatcherCastTest, FromPolymorphicMatcher)
bool IsPositiveIntValue (const IntValue &foo)
TEST (MatcherCastTest, FromCompatibleType)
TEST (MatcherCastTest, FromConstReferenceToNonReference)
TEST (MatcherCastTest, FromReferenceToNonReference)
TEST (MatcherCastTest, FromNonReferenceToConstReference)
TEST (MatcherCastTest, FromNonReferenceToReference)
TEST (MatcherCastTest, FromSameType)
TEST (MatcherCastTest, FromAValue)
TEST (MatcherCastTest, FromAnImplicitlyConvertibleValue)
TEST (MatcherCastTest, NonImplicitlyConstructibleTypeWithOperatorEq)
bool operator== (const IntReferenceWrapper &a, const IntReferenceWrapper &b)
TEST (MatcherCastTest, ValueIsNotCopied)
TEST (SafeMatcherCastTest, FromPolymorphicMatcher)
TEST (SafeMatcherCastTest, FromLosslesslyConvertibleArithmeticType)
TEST (SafeMatcherCastTest, FromBaseClass)
TEST (SafeMatcherCastTest, FromConstReferenceToReference)
TEST (SafeMatcherCastTest, FromNonReferenceToConstReference)
TEST (SafeMatcherCastTest, FromNonReferenceToReference)
TEST (SafeMatcherCastTest, FromSameType)
TEST (SafeMatcherCastTest, ValueIsNotCopied)
TEST (ExpectThat, TakesLiterals)
TEST (ExpectThat, TakesFunctions)
TEST (ATest, MatchesAnyValue)
TEST (ATest, WorksForDerivedClass)
TEST (ATest, CanDescribeSelf)
TEST (AnTest, MatchesAnyValue)
TEST (AnTest, CanDescribeSelf)
TEST (UnderscoreTest, MatchesAnyValue)
TEST (UnderscoreTest, CanDescribeSelf)
TEST (EqTest, MatchesEqualValue)
TEST (EqTest, CanDescribeSelf)
TEST (EqTest, IsPolymorphic)
TEST (TypedEqTest, ChecksEqualityForGivenType)
TEST (TypedEqTest, CanDescribeSelf)
TEST (TypedEqTest, HasSpecifiedType)
TEST (GeTest, ImplementsGreaterThanOrEqual)
TEST (GeTest, CanDescribeSelf)
TEST (GtTest, ImplementsGreaterThan)
TEST (GtTest, CanDescribeSelf)
TEST (LeTest, ImplementsLessThanOrEqual)
TEST (LeTest, CanDescribeSelf)
TEST (LtTest, ImplementsLessThan)
TEST (LtTest, CanDescribeSelf)
TEST (NeTest, ImplementsNotEqual)
TEST (NeTest, CanDescribeSelf)
TEST (IsNullTest, MatchesNullPointer)
TEST (IsNullTest, LinkedPtr)
TEST (IsNullTest, ReferenceToConstLinkedPtr)
TEST (IsNullTest, CanDescribeSelf)
TEST (NotNullTest, MatchesNonNullPointer)
TEST (NotNullTest, LinkedPtr)
TEST (NotNullTest, ReferenceToConstLinkedPtr)
TEST (NotNullTest, CanDescribeSelf)
TEST (RefTest, MatchesSameVariable)
TEST (RefTest, CanDescribeSelf)
TEST (RefTest, CanBeUsedAsMatcherForConstReference)
TEST (RefTest, IsCovariant)
TEST (RefTest, ExplainsResult)
TEST (StrEqTest, MatchesEqualString)
TEST (StrEqTest, CanDescribeSelf)
TEST (StrNeTest, MatchesUnequalString)
TEST (StrNeTest, CanDescribeSelf)
TEST (StrCaseEqTest, MatchesEqualStringIgnoringCase)
TEST (StrCaseEqTest, MatchesEqualStringWith0IgnoringCase)
TEST (StrCaseEqTest, CanDescribeSelf)
TEST (StrCaseNeTest, MatchesUnequalStringIgnoringCase)
TEST (StrCaseNeTest, CanDescribeSelf)
TEST (HasSubstrTest, WorksForStringClasses)
TEST (HasSubstrTest, WorksForCStrings)
TEST (HasSubstrTest, CanDescribeSelf)
TEST (KeyTest, CanDescribeSelf)
TEST (KeyTest, ExplainsResult)
TEST (KeyTest, MatchesCorrectly)
TEST (KeyTest, SafelyCastsInnerMatcher)
TEST (KeyTest, InsideContainsUsingMap)
TEST (KeyTest, InsideContainsUsingMultimap)
TEST (PairTest, Typing)
TEST (PairTest, CanDescribeSelf)
TEST (PairTest, CanExplainMatchResultTo)
TEST (PairTest, MatchesCorrectly)
TEST (PairTest, SafelyCastsInnerMatchers)
TEST (PairTest, InsideContainsUsingMap)
TEST (StartsWithTest, MatchesStringWithGivenPrefix)
TEST (StartsWithTest, CanDescribeSelf)
TEST (EndsWithTest, MatchesStringWithGivenSuffix)
TEST (EndsWithTest, CanDescribeSelf)
TEST (MatchesRegexTest, MatchesStringMatchingGivenRegex)
TEST (MatchesRegexTest, CanDescribeSelf)
TEST (ContainsRegexTest, MatchesStringContainingGivenRegex)
TEST (ContainsRegexTest, CanDescribeSelf)
TEST (Eq2Test, MatchesEqualArguments)
TEST (Eq2Test, CanDescribeSelf)
TEST (Ge2Test, MatchesGreaterThanOrEqualArguments)
TEST (Ge2Test, CanDescribeSelf)
TEST (Gt2Test, MatchesGreaterThanArguments)
TEST (Gt2Test, CanDescribeSelf)
TEST (Le2Test, MatchesLessThanOrEqualArguments)
TEST (Le2Test, CanDescribeSelf)
TEST (Lt2Test, MatchesLessThanArguments)
TEST (Lt2Test, CanDescribeSelf)
TEST (Ne2Test, MatchesUnequalArguments)
TEST (Ne2Test, CanDescribeSelf)
TEST (FloatEq2Test, MatchesEqualArguments)
TEST (FloatEq2Test, CanDescribeSelf)
TEST (NanSensitiveFloatEqTest, MatchesEqualArgumentsWithNaN)
TEST (NanSensitiveFloatEqTest, CanDescribeSelfWithNaNs)
TEST (DoubleEq2Test, MatchesEqualArguments)
TEST (DoubleEq2Test, CanDescribeSelf)
TEST (NanSensitiveDoubleEqTest, MatchesEqualArgumentsWithNaN)
TEST (NanSensitiveDoubleEqTest, CanDescribeSelfWithNaNs)
TEST (FloatNear2Test, MatchesEqualArguments)
TEST (FloatNear2Test, CanDescribeSelf)
TEST (NanSensitiveFloatNearTest, MatchesNearbyArgumentsWithNaN)
TEST (NanSensitiveFloatNearTest, CanDescribeSelfWithNaNs)
TEST (DoubleNear2Test, MatchesEqualArguments)
TEST (DoubleNear2Test, CanDescribeSelf)
TEST (NanSensitiveDoubleNearTest, MatchesNearbyArgumentsWithNaN)
TEST (NanSensitiveDoubleNearTest, CanDescribeSelfWithNaNs)
TEST (NotTest, NegatesMatcher)
TEST (NotTest, CanDescribeSelf)
TEST (NotTest, NotMatcherSafelyCastsMonomorphicMatchers)
void AllOfMatches (int num, const Matcher< int > &m)
TEST (AllOfTest, MatchesWhenAllMatch)
TEST (AllOfTest, CanDescribeSelf)
TEST (AllOfTest, CanDescribeNegation)
TEST (AllOfTest, AllOfMatcherSafelyCastsMonomorphicMatchers)
TEST (AllOfTest, ExplainsResult)
void AnyOfMatches (int num, const Matcher< int > &m)
TEST (AnyOfTest, MatchesWhenAnyMatches)
TEST (AnyOfTest, CanDescribeSelf)
TEST (AnyOfTest, CanDescribeNegation)
TEST (AnyOfTest, AnyOfMatcherSafelyCastsMonomorphicMatchers)
TEST (AnyOfTest, ExplainsResult)
int IsPositive (double x)
bool ReferencesFooAndIsZero (const int &n)
TEST (TrulyTest, MatchesWhatSatisfiesThePredicate)
TEST (TrulyTest, CanBeUsedWithFunctor)
ConvertibleToBool IsNotZero (int number)
TEST (TrulyTest, PredicateCanReturnAClassConvertibleToBool)
TEST (TrulyTest, CanDescribeSelf)
TEST (TrulyTest, WorksForByRefArguments)
TEST (MatchesTest, IsSatisfiedByWhatMatchesTheMatcher)
TEST (MatchesTest, WorksOnByRefArguments)
TEST (MatchesTest, WorksWithMatcherOnNonRefType)
TEST (ValueTest, WorksWithPolymorphicMatcher)
TEST (ValueTest, WorksWithMonomorphicMatcher)
TEST (ExplainMatchResultTest, WorksWithPolymorphicMatcher)
TEST (ExplainMatchResultTest, WorksWithMonomorphicMatcher)
MATCHER_P (Really, inner_matcher, "")
TEST (ExplainMatchResultTest, WorksInsideMATCHER)
TEST (DescribeMatcherTest, WorksWithValue)
TEST (DescribeMatcherTest, WorksWithMonomorphicMatcher)
TEST (DescribeMatcherTest, WorksWithPolymorphicMatcher)
TEST (AllArgsTest, WorksForTuple)
TEST (AllArgsTest, WorksForNonTuple)
TEST (AllArgsTest, WorksInWithClause)
TEST (AllArgsTest, WorksWithoutMatchers)
TEST (MatcherAssertionTest, WorksWhenMatcherIsSatisfied)
TEST (MatcherAssertionTest, WorksWhenMatcherIsNotSatisfied)
TEST (MatcherAssertionTest, WorksForByRefArguments)
TEST (MatcherAssertionTest, WorksForMonomorphicMatcher)
TEST_F (FloatTest, FloatEqApproximatelyMatchesFloats)
TEST_F (FloatTest, NanSensitiveFloatEqApproximatelyMatchesFloats)
TEST_F (FloatTest, FloatEqCannotMatchNaN)
TEST_F (FloatTest, NanSensitiveFloatEqCanMatchNaN)
TEST_F (FloatTest, FloatEqCanDescribeSelf)
TEST_F (FloatTest, NanSensitiveFloatEqCanDescribeSelf)
TEST_F (FloatNearTest, FloatNearMatches)
TEST_F (FloatNearTest, NanSensitiveFloatNearApproximatelyMatchesFloats)
TEST_F (FloatNearTest, FloatNearCanDescribeSelf)
TEST_F (FloatNearTest, NanSensitiveFloatNearCanDescribeSelf)
TEST_F (FloatNearTest, FloatNearCannotMatchNaN)
TEST_F (FloatNearTest, NanSensitiveFloatNearCanMatchNaN)
TEST_F (DoubleTest, DoubleEqApproximatelyMatchesDoubles)
TEST_F (DoubleTest, NanSensitiveDoubleEqApproximatelyMatchesDoubles)
TEST_F (DoubleTest, DoubleEqCannotMatchNaN)
TEST_F (DoubleTest, NanSensitiveDoubleEqCanMatchNaN)
TEST_F (DoubleTest, DoubleEqCanDescribeSelf)
TEST_F (DoubleTest, NanSensitiveDoubleEqCanDescribeSelf)
TEST_F (DoubleNearTest, DoubleNearMatches)
TEST_F (DoubleNearTest, NanSensitiveDoubleNearApproximatelyMatchesDoubles)
TEST_F (DoubleNearTest, DoubleNearCanDescribeSelf)
TEST_F (DoubleNearTest, ExplainsResultWhenMatchFails)
TEST_F (DoubleNearTest, NanSensitiveDoubleNearCanDescribeSelf)
TEST_F (DoubleNearTest, DoubleNearCannotMatchNaN)
TEST_F (DoubleNearTest, NanSensitiveDoubleNearCanMatchNaN)
TEST (PointeeTest, RawPointer)
TEST (PointeeTest, RawPointerToConst)
TEST (PointeeTest, ReferenceToConstRawPointer)
TEST (PointeeTest, ReferenceToNonConstRawPointer)
MATCHER_P (FieldIIs, inner_matcher, "")
TEST (PointeeTest, WorksWithConstPropagatingPointers)
TEST (PointeeTest, NeverMatchesNull)
TEST (PointeeTest, MatchesAgainstAValue)
TEST (PointeeTest, CanDescribeSelf)
TEST (PointeeTest, CanExplainMatchResult)
TEST (PointeeTest, AlwaysExplainsPointee)
bool ValueIsPositive (const Uncopyable &x)
MATCHER_P (UncopyableIs, inner_matcher, "")
TEST (FieldTest, WorksForNonConstField)
TEST (FieldTest, WorksForConstField)
TEST (FieldTest, WorksForUncopyableField)
TEST (FieldTest, WorksForPointerField)
TEST (FieldTest, WorksForByRefArgument)
TEST (FieldTest, WorksForArgumentOfSubType)
TEST (FieldTest, WorksForCompatibleMatcherType)
TEST (FieldTest, CanDescribeSelf)
TEST (FieldTest, CanDescribeSelfWithFieldName)
TEST (FieldTest, CanExplainMatchResult)
TEST (FieldTest, CanExplainMatchResultWithFieldName)
TEST (FieldForPointerTest, WorksForPointerToConst)
TEST (FieldForPointerTest, WorksForPointerToNonConst)
TEST (FieldForPointerTest, WorksForReferenceToConstPointer)
TEST (FieldForPointerTest, DoesNotMatchNull)
TEST (FieldForPointerTest, WorksForArgumentOfSubType)
TEST (FieldForPointerTest, CanDescribeSelf)
TEST (FieldForPointerTest, CanDescribeSelfWithFieldName)
TEST (FieldForPointerTest, CanExplainMatchResult)
TEST (FieldForPointerTest, CanExplainMatchResultWithFieldName)
TEST (PropertyTest, WorksForNonReferenceProperty)
TEST (PropertyTest, WorksForReferenceToConstProperty)
TEST (PropertyTest, WorksForReferenceToNonConstProperty)
TEST (PropertyTest, WorksForByValueArgument)
TEST (PropertyTest, WorksForArgumentOfSubType)
TEST (PropertyTest, WorksForCompatibleMatcherType)
TEST (PropertyTest, CanDescribeSelf)
TEST (PropertyTest, CanDescribeSelfWithPropertyName)
TEST (PropertyTest, CanExplainMatchResult)
TEST (PropertyTest, CanExplainMatchResultWithPropertyName)
TEST (PropertyForPointerTest, WorksForPointerToConst)
TEST (PropertyForPointerTest, WorksForPointerToNonConst)
TEST (PropertyForPointerTest, WorksForReferenceToConstPointer)
TEST (PropertyForPointerTest, WorksForReferenceToNonConstProperty)
TEST (PropertyForPointerTest, WorksForArgumentOfSubType)
TEST (PropertyForPointerTest, CanDescribeSelf)
TEST (PropertyForPointerTest, CanDescribeSelfWithPropertyDescription)
TEST (PropertyForPointerTest, CanExplainMatchResult)
TEST (PropertyForPointerTest, CanExplainMatchResultWithPropertyName)
std::string IntToStringFunction (int input)
TEST (ResultOfTest, WorksForFunctionPointers)
TEST (ResultOfTest, CanDescribeItself)
int IntFunction (int input)
TEST (ResultOfTest, CanExplainMatchResult)
TEST (ResultOfTest, WorksForNonReferenceResults)
double & DoubleFunction (double &input)
Uncopyable & RefUncopyableFunction (Uncopyable &obj)
TEST (ResultOfTest, WorksForReferenceToNonConstResults)
const std::string & StringFunction (const std::string &input)
TEST (ResultOfTest, WorksForReferenceToConstResults)
TEST (ResultOfTest, WorksForCompatibleMatcherTypes)
TEST (ResultOfDeathTest, DiesOnNullFunctionPointers)
TEST (ResultOfTest, WorksForFunctionReferences)
TEST (ResultOfTest, WorksForFunctors)
TEST (ResultOfTest, WorksForPolymorphicFunctors)
const int * ReferencingFunction (const int &n)
TEST (ResultOfTest, WorksForReferencingCallables)
PolymorphicMatcher< DivisibleByImpl > DivisibleBy (int n)
TEST (ExplainMatchResultTest, AllOf_False_False)
TEST (ExplainMatchResultTest, AllOf_False_True)
TEST (ExplainMatchResultTest, AllOf_True_False)
TEST (ExplainMatchResultTest, AllOf_True_True)
TEST (ExplainMatchResultTest, AllOf_True_True_2)
TEST (ExplainmatcherResultTest, MonomorphicMatcher)
TEST (ByRefTest, AllowsNotCopyableConstValueInMatchers)
TEST (ByRefTest, AllowsNotCopyableValueInMatchers)
TEST (IsEmptyTest, ImplementsIsEmpty)
TEST (IsEmptyTest, WorksWithString)
TEST (IsEmptyTest, CanDescribeSelf)
TEST (IsEmptyTest, ExplainsResult)
TEST (IsTrueTest, IsTrueIsFalse)
TEST (SizeIsTest, ImplementsSizeIs)
TEST (SizeIsTest, WorksWithMap)
TEST (SizeIsTest, WorksWithReferences)
TEST (SizeIsTest, CanDescribeSelf)
TEST (SizeIsTest, ExplainsResult)
TEST (ContainerEqExtraTest, MultipleValuesMissing)
TEST (ContainerEqExtraTest, MultipleValuesAdded)
TEST (ContainerEqExtraTest, MultipleValuesAddedAndRemoved)
TEST (ContainerEqExtraTest, MultiSetOfIntDuplicateDifference)
TEST (ContainerEqExtraTest, WorksForMaps)
TEST (ContainerEqExtraTest, WorksForNativeArray)
TEST (ContainerEqExtraTest, WorksForTwoDimensionalNativeArray)
TEST (ContainerEqExtraTest, WorksForNativeArrayAsTuple)
TEST (ContainerEqExtraTest, CopiesNativeArrayParameter)
TEST (WhenSortedByTest, WorksForEmptyContainer)
TEST (WhenSortedByTest, WorksForNonEmptyContainer)
TEST (WhenSortedByTest, WorksForNonVectorContainer)
TEST (WhenSortedByTest, WorksForNativeArray)
TEST (WhenSortedByTest, CanDescribeSelf)
TEST (WhenSortedByTest, ExplainsMatchResult)
TEST (WhenSortedTest, WorksForEmptyContainer)
TEST (WhenSortedTest, WorksForNonEmptyContainer)
TEST (WhenSortedTest, WorksForMapTypes)
TEST (WhenSortedTest, WorksForMultiMapTypes)
TEST (WhenSortedTest, WorksForPolymorphicMatcher)
TEST (WhenSortedTest, WorksForVectorConstRefMatcher)
TEST (StreamlikeTest, Iteration)
TEST (BeginEndDistanceIsTest, WorksWithNonStdList)
TEST (BeginEndDistanceIsTest, CanDescribeSelf)
TEST (BeginEndDistanceIsTest, ExplainsResult)
TEST (WhenSortedTest, WorksForStreamlike)
TEST (WhenSortedTest, WorksForVectorConstRefMatcherOnStreamlike)
TEST (IsSupersetOfTest, WorksForNativeArray)
TEST (IsSupersetOfTest, WorksWithDuplicates)
TEST (IsSupersetOfTest, WorksForEmpty)
TEST (IsSupersetOfTest, WorksForStreamlike)
TEST (IsSupersetOfTest, TakesStlContainer)
TEST (IsSupersetOfTest, Describe)
TEST (IsSupersetOfTest, DescribeNegation)
TEST (IsSupersetOfTest, MatchAndExplain)
TEST (IsSubsetOfTest, WorksForNativeArray)
TEST (IsSubsetOfTest, WorksWithDuplicates)
TEST (IsSubsetOfTest, WorksForEmpty)
TEST (IsSubsetOfTest, WorksForStreamlike)
TEST (IsSubsetOfTest, TakesStlContainer)
TEST (IsSubsetOfTest, Describe)
TEST (IsSubsetOfTest, DescribeNegation)
TEST (IsSubsetOfTest, MatchAndExplain)
TEST (ElemensAreStreamTest, WorksForStreamlike)
TEST (ElemensAreArrayStreamTest, WorksForStreamlike)
TEST (ElementsAreTest, WorksWithUncopyable)
TEST (ElementsAreTest, TakesStlContainer)
TEST (UnorderedElementsAreArrayTest, SucceedsWhenExpected)
TEST (UnorderedElementsAreArrayTest, VectorBool)
TEST (UnorderedElementsAreArrayTest, WorksForStreamlike)
TEST (UnorderedElementsAreArrayTest, TakesStlContainer)
TEST_F (UnorderedElementsAreTest, WorksWithUncopyable)
TEST_F (UnorderedElementsAreTest, SucceedsWhenExpected)
TEST_F (UnorderedElementsAreTest, FailsWhenAnElementMatchesNoMatcher)
TEST_F (UnorderedElementsAreTest, WorksForStreamlike)
TEST_F (UnorderedElementsAreTest, Performance)
TEST_F (UnorderedElementsAreTest, PerformanceHalfStrict)
TEST_F (UnorderedElementsAreTest, FailMessageCountWrong)
TEST_F (UnorderedElementsAreTest, FailMessageCountWrongZero)
TEST_F (UnorderedElementsAreTest, FailMessageUnmatchedMatchers)
TEST_F (UnorderedElementsAreTest, FailMessageUnmatchedElements)
TEST_F (UnorderedElementsAreTest, FailMessageUnmatchedMatcherAndElement)
static std::string EMString (int element, int matcher)
TEST_F (UnorderedElementsAreTest, FailMessageImperfectMatchOnly)
TEST_F (UnorderedElementsAreTest, Describe)
TEST_F (UnorderedElementsAreTest, DescribeNegation)
template<typename Graph >
ElementMatcherPairs FindBacktrackingMaxBPM (const Graph &g)
TEST_P (BipartiteTest, Exhaustive)
INSTANTIATE_TEST_CASE_P (AllGraphs, BipartiteTest, ::testing::Range(0, 5))
TEST_F (BipartiteNonSquareTest, SimpleBacktracking)
TEST_P (BipartiteNonSquareTest, Exhaustive)
INSTANTIATE_TEST_CASE_P (AllGraphs, BipartiteNonSquareTest, testing::Values(std::make_pair(1, 2), std::make_pair(2, 1), std::make_pair(3, 2), std::make_pair(2, 3), std::make_pair(4, 1), std::make_pair(1, 4), std::make_pair(4, 3), std::make_pair(3, 4)))
TEST_P (BipartiteRandomTest, LargerNets)
INSTANTIATE_TEST_CASE_P (Samples, BipartiteRandomTest, testing::Values(std::make_pair(5, 10000), std::make_pair(6, 5000), std::make_pair(7, 2000), std::make_pair(8, 500), std::make_pair(9, 100)))
TEST (IsReadableTypeNameTest, ReturnsTrueForShortNames)
TEST (IsReadableTypeNameTest, ReturnsTrueForLongNonTemplateNonFunctionNames)
TEST (IsReadableTypeNameTest, ReturnsFalseForLongTemplateNames)
TEST (IsReadableTypeNameTest, ReturnsFalseForLongFunctionTypeNames)
TEST (FormatMatcherDescriptionTest, WorksForEmptyDescription)
TEST (PolymorphicMatcherTest, CanAccessMutableImpl)
TEST (PolymorphicMatcherTest, CanAccessImpl)
TEST (MatcherTupleTest, ExplainsMatchFailure)
TEST (EachTest, ExplainsMatchResultCorrectly)
TEST (EachTest, DescribesItselfCorrectly)
TEST (EachTest, MatchesVectorWhenAllElementsMatch)
TEST (EachTest, MatchesMapWhenAllElementsMatch)
TEST (EachTest, AcceptsMatcher)
TEST (EachTest, WorksForNativeArrayAsTuple)
PolymorphicMatcher< IsHalfOfMatcher > IsHalfOf ()
TEST (PointwiseTest, DescribesSelf)
TEST (PointwiseTest, MakesCopyOfRhs)
TEST (PointwiseTest, WorksForLhsNativeArray)
TEST (PointwiseTest, WorksForRhsNativeArray)
TEST (PointwiseTest, WorksForVectorOfBool)
TEST (PointwiseTest, RejectsWrongSize)
TEST (PointwiseTest, RejectsWrongContent)
TEST (PointwiseTest, AcceptsCorrectContent)
TEST (PointwiseTest, AllowsMonomorphicInnerMatcher)
TEST (UnorderedPointwiseTest, DescribesSelf)
TEST (UnorderedPointwiseTest, MakesCopyOfRhs)
TEST (UnorderedPointwiseTest, WorksForLhsNativeArray)
TEST (UnorderedPointwiseTest, WorksForRhsNativeArray)
TEST (UnorderedPointwiseTest, RejectsWrongSize)
TEST (UnorderedPointwiseTest, RejectsWrongContent)
TEST (UnorderedPointwiseTest, AcceptsCorrectContentInSameOrder)
TEST (UnorderedPointwiseTest, AcceptsCorrectContentInDifferentOrder)
TEST (UnorderedPointwiseTest, AllowsMonomorphicInnerMatcher)
TEST (OptionalTest, DescribesSelf)
TEST (OptionalTest, ExplainsSelf)
TEST (OptionalTest, MatchesNonEmptyOptional)
TEST (OptionalTest, DoesNotMatchNullopt)
TEST (VariantTest, DescribesSelf)
TEST (VariantTest, ExplainsSelf)
TEST (VariantTest, FullMatch)
TEST (VariantTest, TypeDoesNotMatch)
TEST (VariantTest, InnerDoesNotMatch)
TEST (AnyWithTest, FullMatch)
TEST (AnyWithTest, TestBadCastType)
TEST (AnyWithTest, TestCompare)
TEST (AnyWithTest, DescribesSelf)
TEST (AnyWithTest, ExplainsSelf)
Variables
const int g_bar = 1
const int foo = 0
Typedef Documentation
DoubleNearTest
typedef FloatingPointNearTest<double> testing::gmock_matchers_test::DoubleNearTest
Definition at line 3589 of file gmock-matchers_test.cc.
DoubleTest
typedef FloatingPointTest<double> testing::gmock_matchers_test::DoubleTest
Definition at line 3533 of file gmock-matchers_test.cc.
FloatNearTest
typedef FloatingPointNearTest<float> testing::gmock_matchers_test::FloatNearTest
Definition at line 3474 of file gmock-matchers_test.cc.
FloatTest
typedef FloatingPointTest<float> testing::gmock_matchers_test::FloatTest
Definition at line 3418 of file gmock-matchers_test.cc.
Tuple2
typedef ::testing::tuple<long, int> testing::gmock_matchers_test::Tuple2
Definition at line 2225 of file gmock-matchers_test.cc.
Function Documentation
AllOfMatches()
void testing::gmock_matchers_test::AllOfMatches (int num, const Matcher< int > & m)
Definition at line 2485 of file gmock-matchers_test.cc.
{
  SCOPED_TRACE(Describe(m));
  EXPECT_TRUE(m.Matches(0));
  for (int i = 1; i <= num; ++i) {
    EXPECT_FALSE(m.Matches(i));
  }
  EXPECT_TRUE(m.Matches(num + 1));
}
References Describe(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and SCOPED_TRACE.
AnyOfMatches()
void testing::gmock_matchers_test::AnyOfMatches (int num, const Matcher< int > & m)
Definition at line 2683 of file gmock-matchers_test.cc.
{
  SCOPED_TRACE(Describe(m));
  EXPECT_FALSE(m.Matches(0));
  for (int i = 1; i <= num; ++i) {
    EXPECT_TRUE(m.Matches(i));
  }
  EXPECT_FALSE(m.Matches(num + 1));
}
References Describe(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and SCOPED_TRACE.
Describe()
template<typename T > std::string testing::gmock_matchers_test::Describe (const Matcher< T > & m)
Definition at line 201 of file gmock-matchers_test.cc.
{
  return DescribeMatcher<T>(m);
}
DescribeNegation()
template<typename T > std::string testing::gmock_matchers_test::DescribeNegation (const Matcher< T > & m)
Definition at line 207 of file gmock-matchers_test.cc.
{
  return DescribeMatcher<T>(m, true);
}
DivisibleBy()
PolymorphicMatcher< DivisibleByImpl > testing::gmock_matchers_test::DivisibleBy (int n)
Definition at line 4639 of file gmock-matchers_test.cc.
{
  return MakePolymorphicMatcher(DivisibleByImpl(n));
}
References testing::MakePolymorphicMatcher().
DoubleFunction()
double & testing::gmock_matchers_test::DoubleFunction (double & input)
Definition at line 4493 of file gmock-matchers_test.cc.
{ return input; }  // NOLINT
EMString()
static std::string testing::gmock_matchers_test::EMString (int element, int matcher) static
Definition at line 5873 of file gmock-matchers_test.cc.
{
  stringstream ss;
  ss << "(element #" << element << ", matcher #" << matcher << ")";
  return ss.str();
}
Explain()
template<typename MatcherType , typename Value > std::string testing::gmock_matchers_test::Explain (const MatcherType & m, const Value & x)
Definition at line 213 of file gmock-matchers_test.cc.
{
  StringMatchResultListener listener;
  ExplainMatchResult(m, x, &listener);
  return listener.str();
}
References testing::ExplainMatchResult(), and testing::StringMatchResultListener::str().
FindBacktrackingMaxBPM()
template<typename Graph > ElementMatcherPairs testing::gmock_matchers_test::FindBacktrackingMaxBPM (const Graph & g)
Definition at line 6024 of file gmock-matchers_test.cc.
{
  return BacktrackingMaxBPMState<Graph>(&g).Compute();
}
GreaterThan()
Matcher< int > testing::gmock_matchers_test::GreaterThan (int n)
Definition at line 187 of file gmock-matchers_test.cc.
{
  return MakeMatcher(new GreaterThanMatcher(n));
}
References testing::MakeMatcher().
INSTANTIATE_TEST_CASE_P() [1/3]
testing::gmock_matchers_test::INSTANTIATE_TEST_CASE_P (AllGraphs , BipartiteNonSquareTest , testing::Values(std::make_pair(1, 2), std::make_pair(2, 1), std::make_pair(3, 2), std::make_pair(2, 3), std::make_pair(4, 1), std::make_pair(1, 4), std::make_pair(4, 3), std::make_pair(3, 4)))
INSTANTIATE_TEST_CASE_P() [2/3]
testing::gmock_matchers_test::INSTANTIATE_TEST_CASE_P (AllGraphs , BipartiteTest , ::testing::Range(0, 5))
INSTANTIATE_TEST_CASE_P() [3/3]
testing::gmock_matchers_test::INSTANTIATE_TEST_CASE_P (Samples , BipartiteRandomTest , testing::Values(std::make_pair(5, 10000), std::make_pair(6, 5000), std::make_pair(7, 2000), std::make_pair(8, 500), std::make_pair(9, 100)))
IntFunction()
int testing::gmock_matchers_test::IntFunction (int input)
Definition at line 4470 of file gmock-matchers_test.cc.
{ return input == 42 ? 80 : 90; }
IntToStringFunction()
std::string testing::gmock_matchers_test::IntToStringFunction (int input)
Definition at line 4448 of file gmock-matchers_test.cc.
{
  return input == 1 ? "foo" : "bar";
}
IsHalfOf()
PolymorphicMatcher< IsHalfOfMatcher > testing::gmock_matchers_test::IsHalfOf ()
Definition at line 6344 of file gmock-matchers_test.cc.
{
  return MakePolymorphicMatcher(IsHalfOfMatcher());
}
References testing::MakePolymorphicMatcher().
IsNotZero()
ConvertibleToBool testing::gmock_matchers_test::IsNotZero (int number)
Definition at line 2951 of file gmock-matchers_test.cc.
{
  return ConvertibleToBool(number);
}
IsPositive()
int testing::gmock_matchers_test::IsPositive (double x)
Definition at line 2901 of file gmock-matchers_test.cc.
{
  return x > 0 ? 1 : 0;
}
IsPositiveIntValue()
bool testing::gmock_matchers_test::IsPositiveIntValue (const IntValue & foo)
Definition at line 632 of file gmock-matchers_test.cc.
{
  return foo.value() > 0;
}
MATCHER_P() [1/3]
testing::gmock_matchers_test::MATCHER_P (FieldIIs , inner_matcher , "")
Definition at line 3703 of file gmock-matchers_test.cc.
{
  return ExplainMatchResult(inner_matcher, arg.i, result_listener);
}
References testing::ExplainMatchResult().
MATCHER_P() [2/3]
testing::gmock_matchers_test::MATCHER_P (Really , inner_matcher , "")
Definition at line 3044 of file gmock-matchers_test.cc.
{
  return ExplainMatchResult(inner_matcher, arg, result_listener);
}
References testing::ExplainMatchResult().
MATCHER_P() [3/3]
testing::gmock_matchers_test::MATCHER_P (UncopyableIs , inner_matcher , "")
Definition at line 3890 of file gmock-matchers_test.cc.
{
  return ExplainMatchResult(inner_matcher, arg.value(), result_listener);
}
References testing::ExplainMatchResult().
OfType()
std::string testing::gmock_matchers_test::OfType (const std::string & type_name)
Definition at line 191 of file gmock-matchers_test.cc.
{
#if GTEST_HAS_RTTI
  return " (of type " + type_name + ")";
#else
  return "";
#endif
}
operator==()
bool testing::gmock_matchers_test::operator== (const IntReferenceWrapper & a, const IntReferenceWrapper & b)
Definition at line 799 of file gmock-matchers_test.cc.
{
  return a.value == b.value;
}
References testing::gmock_matchers_test::IntReferenceWrapper::value.
PolymorphicIsEven()
PolymorphicMatcher< PolymorphicIsEvenImpl > testing::gmock_matchers_test::PolymorphicIsEven ()
Definition at line 584 of file gmock-matchers_test.cc.
{
  return MakePolymorphicMatcher(PolymorphicIsEvenImpl());
}
References testing::MakePolymorphicMatcher().
ReferencesBarOrIsZero()
PolymorphicMatcher< ReferencesBarOrIsZeroImpl > testing::gmock_matchers_test::ReferencesBarOrIsZero ()
Definition at line 541 of file gmock-matchers_test.cc.
{
  return MakePolymorphicMatcher(ReferencesBarOrIsZeroImpl());
}
References testing::MakePolymorphicMatcher().
ReferencesFooAndIsZero()
bool testing::gmock_matchers_test::ReferencesFooAndIsZero (const int & n)
Definition at line 2922 of file gmock-matchers_test.cc.
{
  return (&n == &foo) && (n == 0);
}
ReferencingFunction()
const int * testing::gmock_matchers_test::ReferencingFunction (const int & n)
Definition at line 4593 of file gmock-matchers_test.cc.
{ return &n; }
RefUncopyableFunction()
Uncopyable & testing::gmock_matchers_test::RefUncopyableFunction (Uncopyable & obj)
Definition at line 4495 of file gmock-matchers_test.cc.
                                                   {  // NOLINT
  return obj;
}
StringFunction()
const std::string & testing::gmock_matchers_test::StringFunction (const std::string & input)
Definition at line 4519 of file gmock-matchers_test.cc.
{ return input; }
TEST() [1/350]
testing::gmock_matchers_test::TEST (AllArgsTest , WorksForNonTuple)
Definition at line 3073 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(42, AllArgs(Gt(0)));
  EXPECT_THAT('a', Not(AllArgs(Eq('b'))));
}
References testing::AllArgs(), testing::Eq(), EXPECT_THAT, testing::Gt(), and testing::Not().
TEST() [2/350]
testing::gmock_matchers_test::TEST (AllArgsTest , WorksForTuple)
Definition at line 3068 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(make_tuple(1, 2L), AllArgs(Lt()));
  EXPECT_THAT(make_tuple(2L, 1), Not(AllArgs(Lt())));
}
References testing::AllArgs(), EXPECT_THAT, testing::Lt(), and testing::Not().
TEST() [3/350]
testing::gmock_matchers_test::TEST (AllArgsTest , WorksInWithClause)
Definition at line 3088 of file gmock-matchers_test.cc.
{
  AllArgsHelper helper;
  ON_CALL(helper, Helper(_, _))
      .With(AllArgs(Lt()))
      .WillByDefault(Return(1));
  EXPECT_CALL(helper, Helper(_, _));
  EXPECT_CALL(helper, Helper(_, _))
      .With(AllArgs(Gt()))
      .WillOnce(Return(2));
  EXPECT_EQ(1, helper.Helper('\1', 2));
  EXPECT_EQ(2, helper.Helper('a', 1));
}
References testing::_, testing::AllArgs(), EXPECT_CALL, EXPECT_EQ, testing::Gt(), testing::Lt(), ON_CALL, and testing::Return().
TEST() [4/350]
testing::gmock_matchers_test::TEST (AllArgsTest , WorksWithoutMatchers)
Definition at line 3119 of file gmock-matchers_test.cc.
{
  OptionalMatchersHelper helper;
  ON_CALL(helper, NoArgs).WillByDefault(Return(10));
  ON_CALL(helper, OneArg).WillByDefault(Return(20));
  ON_CALL(helper, TwoArgs).WillByDefault(Return(30));
  EXPECT_EQ(10, helper.NoArgs());
  EXPECT_EQ(20, helper.OneArg(1));
  EXPECT_EQ(30, helper.TwoArgs('\1', 2));
  EXPECT_CALL(helper, NoArgs).Times(1);
  EXPECT_CALL(helper, OneArg).WillOnce(Return(100));
  EXPECT_CALL(helper, OneArg(17)).WillOnce(Return(200));
  EXPECT_CALL(helper, TwoArgs).Times(0);
  EXPECT_EQ(10, helper.NoArgs());
  EXPECT_EQ(100, helper.OneArg(1));
  EXPECT_EQ(200, helper.OneArg(17));
}
References EXPECT_CALL, EXPECT_EQ, ON_CALL, and testing::Return().
TEST() [5/350]
testing::gmock_matchers_test::TEST (AllOfTest , AllOfMatcherSafelyCastsMonomorphicMatchers)
Definition at line 2625 of file gmock-matchers_test.cc.
{
  // greater_than_5 and less_than_10 are monomorphic matchers.
  Matcher<int> greater_than_5 = Gt(5);
  Matcher<int> less_than_10 = Lt(10);
  Matcher<const int&> m = AllOf(greater_than_5, less_than_10);
  Matcher<int&> m2 = AllOf(greater_than_5, less_than_10);
  Matcher<int&> m3 = AllOf(greater_than_5, m2);
  // Tests that BothOf works when composing itself.
  Matcher<const int&> m4 = AllOf(greater_than_5, less_than_10, less_than_10);
  Matcher<int&> m5 = AllOf(greater_than_5, less_than_10, less_than_10);
}
References testing::AllOf(), testing::Gt(), and testing::Lt().
TEST() [6/350]
testing::gmock_matchers_test::TEST (AllOfTest , CanDescribeNegation)
Definition at line 2593 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = AllOf(Le(2), Ge(1));
  EXPECT_EQ("(isn't <= 2) or "
            "(isn't >= 1)",
            DescribeNegation(m));
  m = AllOf(Gt(0), Ne(1), Ne(2));
  EXPECT_EQ("(isn't > 0) or "
            "((is equal to 1) or "
            "(is equal to 2))",
            DescribeNegation(m));
  m = AllOf(Gt(0), Ne(1), Ne(2), Ne(3));
  EXPECT_EQ("((isn't > 0) or "
            "(is equal to 1)) or "
            "((is equal to 2) or "
            "(is equal to 3))",
            DescribeNegation(m));
  m = AllOf(Ge(0), Lt(10), Ne(3), Ne(5), Ne(7));
  EXPECT_EQ("((isn't >= 0) or "
            "(isn't < 10)) or "
            "((is equal to 3) or "
            "((is equal to 5) or "
            "(is equal to 7)))",
            DescribeNegation(m));
}
References testing::AllOf(), DescribeNegation(), EXPECT_EQ, testing::Ge(), testing::Gt(), testing::Le(), testing::Lt(), and testing::Ne().
TEST() [7/350]
testing::gmock_matchers_test::TEST (AllOfTest , CanDescribeSelf)
Definition at line 2563 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = AllOf(Le(2), Ge(1));
  EXPECT_EQ("(is <= 2) and (is >= 1)", Describe(m));
  m = AllOf(Gt(0), Ne(1), Ne(2));
  EXPECT_EQ("(is > 0) and "
            "((isn't equal to 1) and "
            "(isn't equal to 2))",
            Describe(m));
  m = AllOf(Gt(0), Ne(1), Ne(2), Ne(3));
  EXPECT_EQ("((is > 0) and "
            "(isn't equal to 1)) and "
            "((isn't equal to 2) and "
            "(isn't equal to 3))",
            Describe(m));
  m = AllOf(Ge(0), Lt(10), Ne(3), Ne(5), Ne(7));
  EXPECT_EQ("((is >= 0) and "
            "(is < 10)) and "
            "((isn't equal to 3) and "
            "((isn't equal to 5) and "
            "(isn't equal to 7)))",
            Describe(m));
}
References testing::AllOf(), Describe(), EXPECT_EQ, testing::Ge(), testing::Gt(), testing::Le(), testing::Lt(), and testing::Ne().
TEST() [8/350]
testing::gmock_matchers_test::TEST (AllOfTest , ExplainsResult)
Definition at line 2639 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  // Successful match.  Both matchers need to explain.  The second
  // matcher doesn't give an explanation, so only the first matcher's
  // explanation is printed.
  m = AllOf(GreaterThan(10), Lt(30));
  EXPECT_EQ("which is 15 more than 10", Explain(m, 25));
  // Successful match.  Both matchers need to explain.
  m = AllOf(GreaterThan(10), GreaterThan(20));
  EXPECT_EQ("which is 20 more than 10, and which is 10 more than 20",
            Explain(m, 30));
  // Successful match.  All matchers need to explain.  The second
  // matcher doesn't given an explanation.
  m = AllOf(GreaterThan(10), Lt(30), GreaterThan(20));
  EXPECT_EQ("which is 15 more than 10, and which is 5 more than 20",
            Explain(m, 25));
  // Successful match.  All matchers need to explain.
  m = AllOf(GreaterThan(10), GreaterThan(20), GreaterThan(30));
  EXPECT_EQ("which is 30 more than 10, and which is 20 more than 20, "
            "and which is 10 more than 30",
            Explain(m, 40));
  // Failed match.  The first matcher, which failed, needs to
  // explain.
  m = AllOf(GreaterThan(10), GreaterThan(20));
  EXPECT_EQ("which is 5 less than 10", Explain(m, 5));
  // Failed match.  The second matcher, which failed, needs to
  // explain.  Since it doesn't given an explanation, nothing is
  // printed.
  m = AllOf(GreaterThan(10), Lt(30));
  EXPECT_EQ("", Explain(m, 40));
  // Failed match.  The second matcher, which failed, needs to
  // explain.
  m = AllOf(GreaterThan(10), GreaterThan(20));
  EXPECT_EQ("which is 5 less than 20", Explain(m, 15));
}
References testing::AllOf(), EXPECT_EQ, Explain(), GreaterThan(), and testing::Lt().
TEST() [9/350]
testing::gmock_matchers_test::TEST (AllOfTest , MatchesWhenAllMatch)
Definition at line 2496 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = AllOf(Le(2), Ge(1));
  EXPECT_TRUE(m.Matches(1));
  EXPECT_TRUE(m.Matches(2));
  EXPECT_FALSE(m.Matches(0));
  EXPECT_FALSE(m.Matches(3));
  m = AllOf(Gt(0), Ne(1), Ne(2));
  EXPECT_TRUE(m.Matches(3));
  EXPECT_FALSE(m.Matches(2));
  EXPECT_FALSE(m.Matches(1));
  EXPECT_FALSE(m.Matches(0));
  m = AllOf(Gt(0), Ne(1), Ne(2), Ne(3));
  EXPECT_TRUE(m.Matches(4));
  EXPECT_FALSE(m.Matches(3));
  EXPECT_FALSE(m.Matches(2));
  EXPECT_FALSE(m.Matches(1));
  EXPECT_FALSE(m.Matches(0));
  m = AllOf(Ge(0), Lt(10), Ne(3), Ne(5), Ne(7));
  EXPECT_TRUE(m.Matches(0));
  EXPECT_TRUE(m.Matches(1));
  EXPECT_FALSE(m.Matches(3));
  // The following tests for varying number of sub-matchers. Due to the way
  // the sub-matchers are handled it is enough to test every sub-matcher once
  // with sub-matchers using the same matcher type. Varying matcher types are
  // checked for above.
  AllOfMatches(2, AllOf(Ne(1), Ne(2)));
  AllOfMatches(3, AllOf(Ne(1), Ne(2), Ne(3)));
  AllOfMatches(4, AllOf(Ne(1), Ne(2), Ne(3), Ne(4)));
  AllOfMatches(5, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5)));
  AllOfMatches(6, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6)));
  AllOfMatches(7, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7)));
  AllOfMatches(8, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7),
                        Ne(8)));
  AllOfMatches(9, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7),
                        Ne(8), Ne(9)));
  AllOfMatches(10, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7), Ne(8),
                         Ne(9), Ne(10)));
}
References testing::AllOf(), AllOfMatches(), EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::Gt(), testing::Le(), testing::Lt(), testing::internal::MatcherBase< T >::Matches(), and testing::Ne().
TEST() [10/350]
testing::gmock_matchers_test::TEST (AnTest , CanDescribeSelf)
Definition at line 984 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is anything", Describe(An<int>()));
}
References Describe(), and EXPECT_EQ.
TEST() [11/350]
testing::gmock_matchers_test::TEST (AnTest , MatchesAnyValue)
Definition at line 969 of file gmock-matchers_test.cc.
{
  // Tests a matcher for a value type.
  Matcher<int> m1 = An<int>();
  EXPECT_TRUE(m1.Matches(9143));
  EXPECT_TRUE(m1.Matches(-1532));
  // Tests a matcher for a reference type.
  int a = 2;
  int b = -6;
  Matcher<int&> m2 = An<int&>();
  EXPECT_TRUE(m2.Matches(a));
  EXPECT_TRUE(m2.Matches(b));
}
References EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [12/350]
testing::gmock_matchers_test::TEST (AnyOfTest , AnyOfMatcherSafelyCastsMonomorphicMatchers)
Definition at line 2837 of file gmock-matchers_test.cc.
{
  // greater_than_5 and less_than_10 are monomorphic matchers.
  Matcher<int> greater_than_5 = Gt(5);
  Matcher<int> less_than_10 = Lt(10);
  Matcher<const int&> m = AnyOf(greater_than_5, less_than_10);
  Matcher<int&> m2 = AnyOf(greater_than_5, less_than_10);
  Matcher<int&> m3 = AnyOf(greater_than_5, m2);
  // Tests that EitherOf works when composing itself.
  Matcher<const int&> m4 = AnyOf(greater_than_5, less_than_10, less_than_10);
  Matcher<int&> m5 = AnyOf(greater_than_5, less_than_10, less_than_10);
}
References testing::AnyOf(), testing::Gt(), and testing::Lt().
TEST() [13/350]
testing::gmock_matchers_test::TEST (AnyOfTest , CanDescribeNegation)
Definition at line 2809 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = AnyOf(Le(1), Ge(3));
  EXPECT_EQ("(isn't <= 1) and (isn't >= 3)",
            DescribeNegation(m));
  m = AnyOf(Lt(0), Eq(1), Eq(2));
  EXPECT_EQ("(isn't < 0) and "
            "((isn't equal to 1) and (isn't equal to 2))",
            DescribeNegation(m));
  m = AnyOf(Lt(0), Eq(1), Eq(2), Eq(3));
  EXPECT_EQ("((isn't < 0) and "
            "(isn't equal to 1)) and "
            "((isn't equal to 2) and "
            "(isn't equal to 3))",
            DescribeNegation(m));
  m = AnyOf(Le(0), Gt(10), 3, 5, 7);
  EXPECT_EQ("((isn't <= 0) and "
            "(isn't > 10)) and "
            "((isn't equal to 3) and "
            "((isn't equal to 5) and "
            "(isn't equal to 7)))",
            DescribeNegation(m));
}
References testing::AnyOf(), DescribeNegation(), testing::Eq(), EXPECT_EQ, testing::Ge(), testing::Gt(), testing::Le(), and testing::Lt().
TEST() [14/350]
testing::gmock_matchers_test::TEST (AnyOfTest , CanDescribeSelf)
Definition at line 2781 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = AnyOf(Le(1), Ge(3));
  EXPECT_EQ("(is <= 1) or (is >= 3)",
            Describe(m));
  m = AnyOf(Lt(0), Eq(1), Eq(2));
  EXPECT_EQ("(is < 0) or "
            "((is equal to 1) or (is equal to 2))",
            Describe(m));
  m = AnyOf(Lt(0), Eq(1), Eq(2), Eq(3));
  EXPECT_EQ("((is < 0) or "
            "(is equal to 1)) or "
            "((is equal to 2) or "
            "(is equal to 3))",
            Describe(m));
  m = AnyOf(Le(0), Gt(10), 3, 5, 7);
  EXPECT_EQ("((is <= 0) or "
            "(is > 10)) or "
            "((is equal to 3) or "
            "((is equal to 5) or "
            "(is equal to 7)))",
            Describe(m));
}
References testing::AnyOf(), Describe(), testing::Eq(), EXPECT_EQ, testing::Ge(), testing::Gt(), testing::Le(), and testing::Lt().
TEST() [15/350]
testing::gmock_matchers_test::TEST (AnyOfTest , ExplainsResult)
Definition at line 2851 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  // Failed match.  Both matchers need to explain.  The second
  // matcher doesn't give an explanation, so only the first matcher's
  // explanation is printed.
  m = AnyOf(GreaterThan(10), Lt(0));
  EXPECT_EQ("which is 5 less than 10", Explain(m, 5));
  // Failed match.  Both matchers need to explain.
  m = AnyOf(GreaterThan(10), GreaterThan(20));
  EXPECT_EQ("which is 5 less than 10, and which is 15 less than 20",
            Explain(m, 5));
  // Failed match.  All matchers need to explain.  The second
  // matcher doesn't given an explanation.
  m = AnyOf(GreaterThan(10), Gt(20), GreaterThan(30));
  EXPECT_EQ("which is 5 less than 10, and which is 25 less than 30",
            Explain(m, 5));
  // Failed match.  All matchers need to explain.
  m = AnyOf(GreaterThan(10), GreaterThan(20), GreaterThan(30));
  EXPECT_EQ("which is 5 less than 10, and which is 15 less than 20, "
            "and which is 25 less than 30",
            Explain(m, 5));
  // Successful match.  The first matcher, which succeeded, needs to
  // explain.
  m = AnyOf(GreaterThan(10), GreaterThan(20));
  EXPECT_EQ("which is 5 more than 10", Explain(m, 15));
  // Successful match.  The second matcher, which succeeded, needs to
  // explain.  Since it doesn't given an explanation, nothing is
  // printed.
  m = AnyOf(GreaterThan(10), Lt(30));
  EXPECT_EQ("", Explain(m, 0));
  // Successful match.  The second matcher, which succeeded, needs to
  // explain.
  m = AnyOf(GreaterThan(30), GreaterThan(20));
  EXPECT_EQ("which is 5 more than 20", Explain(m, 25));
}
References testing::AnyOf(), EXPECT_EQ, Explain(), GreaterThan(), testing::Gt(), and testing::Lt().
TEST() [16/350]
testing::gmock_matchers_test::TEST (AnyOfTest , MatchesWhenAnyMatches)
Definition at line 2694 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = AnyOf(Le(1), Ge(3));
  EXPECT_TRUE(m.Matches(1));
  EXPECT_TRUE(m.Matches(4));
  EXPECT_FALSE(m.Matches(2));
  m = AnyOf(Lt(0), Eq(1), Eq(2));
  EXPECT_TRUE(m.Matches(-1));
  EXPECT_TRUE(m.Matches(1));
  EXPECT_TRUE(m.Matches(2));
  EXPECT_FALSE(m.Matches(0));
  m = AnyOf(Lt(0), Eq(1), Eq(2), Eq(3));
  EXPECT_TRUE(m.Matches(-1));
  EXPECT_TRUE(m.Matches(1));
  EXPECT_TRUE(m.Matches(2));
  EXPECT_TRUE(m.Matches(3));
  EXPECT_FALSE(m.Matches(0));
  m = AnyOf(Le(0), Gt(10), 3, 5, 7);
  EXPECT_TRUE(m.Matches(0));
  EXPECT_TRUE(m.Matches(11));
  EXPECT_TRUE(m.Matches(3));
  EXPECT_FALSE(m.Matches(2));
  // The following tests for varying number of sub-matchers. Due to the way
  // the sub-matchers are handled it is enough to test every sub-matcher once
  // with sub-matchers using the same matcher type. Varying matcher types are
  // checked for above.
  AnyOfMatches(2, AnyOf(1, 2));
  AnyOfMatches(3, AnyOf(1, 2, 3));
  AnyOfMatches(4, AnyOf(1, 2, 3, 4));
  AnyOfMatches(5, AnyOf(1, 2, 3, 4, 5));
  AnyOfMatches(6, AnyOf(1, 2, 3, 4, 5, 6));
  AnyOfMatches(7, AnyOf(1, 2, 3, 4, 5, 6, 7));
  AnyOfMatches(8, AnyOf(1, 2, 3, 4, 5, 6, 7, 8));
  AnyOfMatches(9, AnyOf(1, 2, 3, 4, 5, 6, 7, 8, 9));
  AnyOfMatches(10, AnyOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));
}
References testing::AnyOf(), AnyOfMatches(), testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::Gt(), testing::Le(), testing::Lt(), and testing::internal::MatcherBase< T >::Matches().
TEST() [17/350]
testing::gmock_matchers_test::TEST (AnyWithTest , DescribesSelf)
Definition at line 6734 of file gmock-matchers_test.cc.
{
  const Matcher<const SampleAnyType&> m = AnyWith<int>(Eq(1));
  EXPECT_THAT(Describe(m), ContainsRegex("is an 'any' type with value of type "
                                         "'.*' and the value is equal to 1"));
}
References testing::ContainsRegex(), Describe(), testing::Eq(), and EXPECT_THAT.
TEST() [18/350]
testing::gmock_matchers_test::TEST (AnyWithTest , ExplainsSelf)
Definition at line 6740 of file gmock-matchers_test.cc.
{
  const Matcher<const SampleAnyType&> m = AnyWith<int>(Eq(1));
  EXPECT_THAT(Explain(m, SampleAnyType(1)), ContainsRegex("whose value 1"));
  EXPECT_THAT(Explain(m, SampleAnyType("A")),
              HasSubstr("whose value is not of type '"));
  EXPECT_THAT(Explain(m, SampleAnyType(2)), "whose value 2 doesn't match");
}
References testing::ContainsRegex(), testing::Eq(), EXPECT_THAT, Explain(), and testing::HasSubstr().
TEST() [19/350]
testing::gmock_matchers_test::TEST (AnyWithTest , FullMatch)
Definition at line 6702 of file gmock-matchers_test.cc.
{
  Matcher<SampleAnyType> m = AnyWith<int>(Eq(1));
  EXPECT_TRUE(m.Matches(SampleAnyType(1)));
}
References testing::Eq(), EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [20/350]
testing::gmock_matchers_test::TEST (AnyWithTest , TestBadCastType)
Definition at line 6707 of file gmock-matchers_test.cc.
{
  Matcher<SampleAnyType> m = AnyWith<std::string>(Eq("fail"));
  EXPECT_FALSE(m.Matches(SampleAnyType(1)));
}
References testing::Eq(), EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST() [21/350]
testing::gmock_matchers_test::TEST (AnyWithTest , TestCompare)
Definition at line 6730 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(SampleAnyType(1), AnyWith<int>(Gt(0)));
}
References EXPECT_THAT, and testing::Gt().
TEST() [22/350]
testing::gmock_matchers_test::TEST (ATest , CanDescribeSelf)
Definition at line 964 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is anything", Describe(A<bool>()));
}
References Describe(), and EXPECT_EQ.
TEST() [23/350]
testing::gmock_matchers_test::TEST (ATest , MatchesAnyValue)
Definition at line 940 of file gmock-matchers_test.cc.
{
  // Tests a matcher for a value type.
  Matcher<double> m1 = A<double>();
  EXPECT_TRUE(m1.Matches(91.43));
  EXPECT_TRUE(m1.Matches(-15.32));
  // Tests a matcher for a reference type.
  int a = 2;
  int b = -6;
  Matcher<int&> m2 = A<int&>();
  EXPECT_TRUE(m2.Matches(a));
  EXPECT_TRUE(m2.Matches(b));
}
References EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [24/350]
testing::gmock_matchers_test::TEST (ATest , WorksForDerivedClass)
Definition at line 954 of file gmock-matchers_test.cc.
{
  Base base;
  Derived derived;
  EXPECT_THAT(&base, A<Base*>());
  // This shouldn't compile: EXPECT_THAT(&base, A<Derived*>());
  EXPECT_THAT(&derived, A<Base*>());
  EXPECT_THAT(&derived, A<Derived*>());
}
References EXPECT_THAT.
TEST() [25/350]
testing::gmock_matchers_test::TEST (BeginEndDistanceIsTest , CanDescribeSelf)
Definition at line 5292 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m = BeginEndDistanceIs(2);
  EXPECT_EQ("distance between begin() and end() is equal to 2", Describe(m));
  EXPECT_EQ("distance between begin() and end() isn't equal to 2",
            DescribeNegation(m));
}
References testing::BeginEndDistanceIs(), Describe(), DescribeNegation(), and EXPECT_EQ.
TEST() [26/350]
testing::gmock_matchers_test::TEST (BeginEndDistanceIsTest , ExplainsResult)
Definition at line 5299 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m1 = BeginEndDistanceIs(2);
  Matcher<vector<int> > m2 = BeginEndDistanceIs(Lt(2));
  Matcher<vector<int> > m3 = BeginEndDistanceIs(AnyOf(0, 3));
  Matcher<vector<int> > m4 = BeginEndDistanceIs(GreaterThan(1));
  vector<int> container;
  EXPECT_EQ("whose distance between begin() and end() 0 doesn't match",
            Explain(m1, container));
  EXPECT_EQ("whose distance between begin() and end() 0 matches",
            Explain(m2, container));
  EXPECT_EQ("whose distance between begin() and end() 0 matches",
            Explain(m3, container));
  EXPECT_EQ(
      "whose distance between begin() and end() 0 doesn't match, which is 1 "
      "less than 1",
      Explain(m4, container));
  container.push_back(0);
  container.push_back(0);
  EXPECT_EQ("whose distance between begin() and end() 2 matches",
            Explain(m1, container));
  EXPECT_EQ("whose distance between begin() and end() 2 doesn't match",
            Explain(m2, container));
  EXPECT_EQ("whose distance between begin() and end() 2 doesn't match",
            Explain(m3, container));
  EXPECT_EQ(
      "whose distance between begin() and end() 2 matches, which is 1 more "
      "than 1",
      Explain(m4, container));
}
References testing::AnyOf(), testing::BeginEndDistanceIs(), EXPECT_EQ, Explain(), GreaterThan(), and testing::Lt().
TEST() [27/350]
testing::gmock_matchers_test::TEST (BeginEndDistanceIsTest , WorksWithNonStdList)
Definition at line 5286 of file gmock-matchers_test.cc.
{
  const int a[5] = {1, 2, 3, 4, 5};
  Streamlike<int> s(a, a + 5);
  EXPECT_THAT(s, BeginEndDistanceIs(5));
}
References testing::BeginEndDistanceIs(), and EXPECT_THAT.
TEST() [28/350]
testing::gmock_matchers_test::TEST (ByRefTest , AllowsNotCopyableConstValueInMatchers)
Definition at line 4704 of file gmock-matchers_test.cc.
{
  const NotCopyable const_value1(1);
  const Matcher<const NotCopyable&> m = Eq(ByRef(const_value1));
  const NotCopyable n1(1), n2(2);
  EXPECT_TRUE(m.Matches(n1));
  EXPECT_FALSE(m.Matches(n2));
}
References testing::ByRef(), testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [29/350]
testing::gmock_matchers_test::TEST (ByRefTest , AllowsNotCopyableValueInMatchers)
Definition at line 4713 of file gmock-matchers_test.cc.
{
  NotCopyable value2(2);
  const Matcher<NotCopyable&> m = Ge(ByRef(value2));
  NotCopyable n1(1), n2(2);
  EXPECT_FALSE(m.Matches(n1));
  EXPECT_TRUE(m.Matches(n2));
}
References testing::ByRef(), EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), and testing::internal::MatcherBase< T >::Matches().
TEST() [30/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , CopiesNativeArrayParameter)
Definition at line 5033 of file gmock-matchers_test.cc.
{
  std::string a1[][3] = {
    {"hi", "hello", "ciao"},
    {"bye", "see you", "ciao"}
  };
  std::string a2[][3] = {
    {"hi", "hello", "ciao"},
    {"bye", "see you", "ciao"}
  };
  const Matcher<const std::string(&)[2][3]> m = ContainerEq(a2);
  EXPECT_THAT(a1, m);
  a2[0][0] = "ha";
  EXPECT_THAT(a1, m);
}
References testing::ContainerEq(), and EXPECT_THAT.
TEST() [31/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , MultipleValuesAdded)
Definition at line 4939 of file gmock-matchers_test.cc.
{
  static const int vals[] = {1, 1, 2, 3, 5, 8};
  static const int test_vals[] = {1, 2, 92, 3, 5, 8, 46};
  list<size_t> my_set(vals, vals + 6);
  list<size_t> test_set(test_vals, test_vals + 7);
  const Matcher<const list<size_t>&> m = ContainerEq(my_set);
  EXPECT_FALSE(m.Matches(test_set));
  EXPECT_EQ("which has these unexpected elements: 92, 46",
            Explain(m, test_set));
}
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [32/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , MultipleValuesAddedAndRemoved)
Definition at line 4951 of file gmock-matchers_test.cc.
{
  static const int vals[] = {1, 1, 2, 3, 5, 8};
  static const int test_vals[] = {1, 2, 3, 92, 46};
  list<size_t> my_set(vals, vals + 6);
  list<size_t> test_set(test_vals, test_vals + 5);
  const Matcher<const list<size_t> > m = ContainerEq(my_set);
  EXPECT_FALSE(m.Matches(test_set));
  EXPECT_EQ("which has these unexpected elements: 92, 46,\n"
            "and doesn't have these expected elements: 5, 8",
            Explain(m, test_set));
}
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [33/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , MultipleValuesMissing)
Definition at line 4926 of file gmock-matchers_test.cc.
{
  static const int vals[] = {1, 1, 2, 3, 5, 8};
  static const int test_vals[] = {2, 1, 5};
  vector<int> my_set(vals, vals + 6);
  vector<int> test_set(test_vals, test_vals + 3);
  const Matcher<vector<int> > m = ContainerEq(my_set);
  EXPECT_FALSE(m.Matches(test_set));
  EXPECT_EQ("which doesn't have these expected elements: 3, 8",
            Explain(m, test_set));
}
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [34/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , MultiSetOfIntDuplicateDifference)
Definition at line 4965 of file gmock-matchers_test.cc.
{
  static const int vals[] = {1, 1, 2, 3, 5, 8};
  static const int test_vals[] = {1, 2, 3, 5, 8};
  vector<int> my_set(vals, vals + 6);
  vector<int> test_set(test_vals, test_vals + 5);
  const Matcher<vector<int> > m = ContainerEq(my_set);
  EXPECT_TRUE(m.Matches(my_set));
  EXPECT_FALSE(m.Matches(test_set));
  // There is nothing to report when both sets contain all the same values.
  EXPECT_EQ("", Explain(m, test_set));
}
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [35/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForMaps)
Definition at line 4979 of file gmock-matchers_test.cc.
{
  map<int, std::string> my_map;
  my_map[0] = "a";
  my_map[1] = "b";
  map<int, std::string> test_map;
  test_map[0] = "aa";
  test_map[1] = "b";
  const Matcher<const map<int, std::string>&> m = ContainerEq(my_map);
  EXPECT_TRUE(m.Matches(my_map));
  EXPECT_FALSE(m.Matches(test_map));
  EXPECT_EQ("which has these unexpected elements: (0, \"aa\"),\n"
            "and doesn't have these expected elements: (0, \"a\")",
            Explain(m, test_map));
}
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [36/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForNativeArray)
Definition at line 4997 of file gmock-matchers_test.cc.
{
  int a1[] = {1, 2, 3};
  int a2[] = {1, 2, 3};
  int b[] = {1, 2, 4};
  EXPECT_THAT(a1, ContainerEq(a2));
  EXPECT_THAT(a1, Not(ContainerEq(b)));
}
References testing::ContainerEq(), EXPECT_THAT, and testing::Not().
TEST() [37/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForNativeArrayAsTuple)
Definition at line 5020 of file gmock-matchers_test.cc.
{
  const int a1[] = {1, 2, 3};
  const int a2[] = {1, 2, 3};
  const int b[] = {1, 2, 3, 4};
  const int* const p1 = a1;
  EXPECT_THAT(make_tuple(p1, 3), ContainerEq(a2));
  EXPECT_THAT(make_tuple(p1, 3), Not(ContainerEq(b)));
  const int c[] = {1, 3, 2};
  EXPECT_THAT(make_tuple(p1, 3), Not(ContainerEq(c)));
}
References testing::ContainerEq(), EXPECT_THAT, and testing::Not().
TEST() [38/350]
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForTwoDimensionalNativeArray)
Definition at line 5006 of file gmock-matchers_test.cc.
{
  const char a1[][3] = {"hi", "lo"};
  const char a2[][3] = {"hi", "lo"};
  const char b[][3] = {"lo", "hi"};
  // Tests using ContainerEq() in the first dimension.
  EXPECT_THAT(a1, ContainerEq(a2));
  EXPECT_THAT(a1, Not(ContainerEq(b)));
  // Tests using ContainerEq() in the second dimension.
  EXPECT_THAT(a1, ElementsAre(ContainerEq(a2[0]), ContainerEq(a2[1])));
  EXPECT_THAT(a1, ElementsAre(Not(ContainerEq(b[0])), ContainerEq(a2[1])));
}
References testing::ContainerEq(), testing::ElementsAre(), EXPECT_THAT, and testing::Not().
TEST() [39/350]
testing::gmock_matchers_test::TEST (ContainsRegexTest , CanDescribeSelf)
Definition at line 1828 of file gmock-matchers_test.cc.
{
  Matcher<const std::string> m1 = ContainsRegex("Hi.*");
  EXPECT_EQ("contains regular expression \"Hi.*\"", Describe(m1));
  Matcher<const char*> m2 = ContainsRegex(new RE("a.*"));
  EXPECT_EQ("contains regular expression \"a.*\"", Describe(m2));
#if GTEST_HAS_ABSL
  Matcher<const absl::string_view> m3 = ContainsRegex(new RE("0.*"));
  EXPECT_EQ("contains regular expression \"0.*\"", Describe(m3));
#endif  // GTEST_HAS_ABSL
}
References testing::ContainsRegex(), Describe(), and EXPECT_EQ.
TEST() [40/350]
testing::gmock_matchers_test::TEST (ContainsRegexTest , MatchesStringContainingGivenRegex)
Definition at line 1804 of file gmock-matchers_test.cc.
{
  const Matcher<const char*> m1 = ContainsRegex(std::string("a.*z"));
  EXPECT_TRUE(m1.Matches("az"));
  EXPECT_TRUE(m1.Matches("0abcz1"));
  EXPECT_FALSE(m1.Matches(NULL));
  const Matcher<const std::string&> m2 = ContainsRegex(new RE("a.*z"));
  EXPECT_TRUE(m2.Matches("azbz"));
  EXPECT_TRUE(m2.Matches("az1"));
  EXPECT_FALSE(m2.Matches("1a"));
#if GTEST_HAS_ABSL
  const Matcher<const absl::string_view&> m3 = ContainsRegex(new RE("a.*z"));
  EXPECT_TRUE(m3.Matches(absl::string_view("azbz")));
  EXPECT_TRUE(m3.Matches(absl::string_view("az1")));
  EXPECT_FALSE(m3.Matches(absl::string_view("1a")));
  // Default-constructed absl::string_view should not match anything, in order
  // to distinguish it from an empty string.
  EXPECT_FALSE(m3.Matches(absl::string_view()));
  const Matcher<const absl::string_view&> m4 = ContainsRegex("");
  EXPECT_FALSE(m4.Matches(absl::string_view()));
#endif  // GTEST_HAS_ABSL
}
References testing::ContainsRegex(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [41/350]
testing::gmock_matchers_test::TEST (DescribeMatcherTest , WorksWithMonomorphicMatcher)
Definition at line 3057 of file gmock-matchers_test.cc.
{
  const Matcher<int> monomorphic = Le(0);
  EXPECT_EQ("is <= 0", DescribeMatcher<int>(monomorphic));
  EXPECT_EQ("isn't <= 0", DescribeMatcher<int>(monomorphic, true));
}
References EXPECT_EQ, and testing::Le().
TEST() [42/350]
testing::gmock_matchers_test::TEST (DescribeMatcherTest , WorksWithPolymorphicMatcher)
Definition at line 3063 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is even", DescribeMatcher<int>(PolymorphicIsEven()));
  EXPECT_EQ("is odd", DescribeMatcher<int>(PolymorphicIsEven(), true));
}
References EXPECT_EQ, and PolymorphicIsEven().
TEST() [43/350]
testing::gmock_matchers_test::TEST (DescribeMatcherTest , WorksWithValue)
Definition at line 3052 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is equal to 42", DescribeMatcher<int>(42));
  EXPECT_EQ("isn't equal to 42", DescribeMatcher<int>(42, true));
}
References EXPECT_EQ.
TEST() [44/350]
testing::gmock_matchers_test::TEST (DoubleEq2Test , CanDescribeSelf)
Definition at line 2362 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<double, double>&> m = DoubleEq();
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), testing::DoubleEq(), and EXPECT_EQ.
TEST() [45/350]
testing::gmock_matchers_test::TEST (DoubleEq2Test , MatchesEqualArguments)
Definition at line 2353 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<double, double> Tpl;
  Matcher<const Tpl&> m = DoubleEq();
  EXPECT_TRUE(m.Matches(Tpl(1.0, 1.0)));
  EXPECT_TRUE(m.Matches(Tpl(0.3, 0.1 + 0.1 + 0.1)));
  EXPECT_FALSE(m.Matches(Tpl(1.1, 1.0)));
}
References testing::DoubleEq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [46/350]
testing::gmock_matchers_test::TEST (DoubleNear2Test , CanDescribeSelf)
Definition at line 2434 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<double, double>&> m = DoubleNear(0.5);
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), testing::DoubleNear(), and EXPECT_EQ.
TEST() [47/350]
testing::gmock_matchers_test::TEST (DoubleNear2Test , MatchesEqualArguments)
Definition at line 2425 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<double, double> Tpl;
  Matcher<const Tpl&> m = DoubleNear(0.5);
  EXPECT_TRUE(m.Matches(Tpl(1.0, 1.0)));
  EXPECT_TRUE(m.Matches(Tpl(1.3, 1.0)));
  EXPECT_FALSE(m.Matches(Tpl(1.8, 1.0)));
}
References testing::DoubleNear(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [48/350]
testing::gmock_matchers_test::TEST (EachTest , AcceptsMatcher)
Definition at line 6307 of file gmock-matchers_test.cc.
{
  const int a[] = {1, 2, 3};
  EXPECT_THAT(a, Each(Gt(0)));
  EXPECT_THAT(a, Not(Each(Gt(1))));
}
References testing::Each(), EXPECT_THAT, testing::Gt(), and testing::Not().
TEST() [49/350]
testing::gmock_matchers_test::TEST (EachTest , DescribesItselfCorrectly)
Definition at line 6261 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m = Each(1);
  EXPECT_EQ("only contains elements that is equal to 1", Describe(m));
  Matcher<vector<int> > m2 = Not(m);
  EXPECT_EQ("contains some element that isn't equal to 1", Describe(m2));
}
References Describe(), testing::Each(), EXPECT_EQ, and testing::Not().
TEST() [50/350]
testing::gmock_matchers_test::TEST (EachTest , ExplainsMatchResultCorrectly)
Definition at line 6236 of file gmock-matchers_test.cc.
{
  set<int> a;  // empty
  Matcher<set<int> > m = Each(2);
  EXPECT_EQ("", Explain(m, a));
  Matcher<const int(&)[1]> n = Each(1);  // NOLINT
  const int b[1] = {1};
  EXPECT_EQ("", Explain(n, b));
  n = Each(3);
  EXPECT_EQ("whose element #0 doesn't match", Explain(n, b));
  a.insert(1);
  a.insert(2);
  a.insert(3);
  m = Each(GreaterThan(0));
  EXPECT_EQ("", Explain(m, a));
  m = Each(GreaterThan(10));
  EXPECT_EQ("whose element #0 doesn't match, which is 9 less than 10",
            Explain(m, a));
}
References testing::Each(), EXPECT_EQ, Explain(), and GreaterThan().
TEST() [51/350]
testing::gmock_matchers_test::TEST (EachTest , MatchesMapWhenAllElementsMatch)
Definition at line 6289 of file gmock-matchers_test.cc.
{
  map<const char*, int> my_map;
  const char* bar = "a string";
  my_map[bar] = 2;
  EXPECT_THAT(my_map, Each(make_pair(bar, 2)));
  map<std::string, int> another_map;
  EXPECT_THAT(another_map, Each(make_pair(std::string("fee"), 1)));
  another_map["fee"] = 1;
  EXPECT_THAT(another_map, Each(make_pair(std::string("fee"), 1)));
  another_map["fie"] = 2;
  another_map["foe"] = 3;
  another_map["fum"] = 4;
  EXPECT_THAT(another_map, Not(Each(make_pair(std::string("fee"), 1))));
  EXPECT_THAT(another_map, Not(Each(make_pair(std::string("fum"), 1))));
  EXPECT_THAT(another_map, Each(Pair(_, Gt(0))));
}
References testing::_, testing::Each(), EXPECT_THAT, testing::Gt(), testing::Not(), and testing::Pair().
TEST() [52/350]
testing::gmock_matchers_test::TEST (EachTest , MatchesVectorWhenAllElementsMatch)
Definition at line 6269 of file gmock-matchers_test.cc.
{
  vector<int> some_vector;
  EXPECT_THAT(some_vector, Each(1));
  some_vector.push_back(3);
  EXPECT_THAT(some_vector, Not(Each(1)));
  EXPECT_THAT(some_vector, Each(3));
  some_vector.push_back(1);
  some_vector.push_back(2);
  EXPECT_THAT(some_vector, Not(Each(3)));
  EXPECT_THAT(some_vector, Each(Lt(3.5)));
  vector<std::string> another_vector;
  another_vector.push_back("fee");
  EXPECT_THAT(another_vector, Each(std::string("fee")));
  another_vector.push_back("fie");
  another_vector.push_back("foe");
  another_vector.push_back("fum");
  EXPECT_THAT(another_vector, Not(Each(std::string("fee"))));
}
References testing::Each(), EXPECT_THAT, testing::Lt(), and testing::Not().
TEST() [53/350]
testing::gmock_matchers_test::TEST (EachTest , WorksForNativeArrayAsTuple)
Definition at line 6313 of file gmock-matchers_test.cc.
{
  const int a[] = {1, 2};
  const int* const pointer = a;
  EXPECT_THAT(make_tuple(pointer, 2), Each(Gt(0)));
  EXPECT_THAT(make_tuple(pointer, 2), Not(Each(Gt(1))));
}
References testing::Each(), EXPECT_THAT, testing::Gt(), and testing::Not().
TEST() [54/350]
testing::gmock_matchers_test::TEST (ElemensAreArrayStreamTest , WorksForStreamlike)
Definition at line 5600 of file gmock-matchers_test.cc.
{
  const int a[5] = {1, 2, 3, 4, 5};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  vector<int> expected;
  expected.push_back(1);
  expected.push_back(2);
  expected.push_back(3);
  expected.push_back(4);
  expected.push_back(5);
  EXPECT_THAT(s, ElementsAreArray(expected));
  expected[3] = 0;
  EXPECT_THAT(s, Not(ElementsAreArray(expected)));
}
References testing::ElementsAreArray(), EXPECT_THAT, GTEST_ARRAY_SIZE_, and testing::Not().
TEST() [55/350]
testing::gmock_matchers_test::TEST (ElemensAreStreamTest , WorksForStreamlike)
Definition at line 5593 of file gmock-matchers_test.cc.
{
  const int a[5] = {1, 2, 3, 4, 5};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(s, ElementsAre(1, 2, 3, 4, 5));
  EXPECT_THAT(s, Not(ElementsAre(2, 1, 4, 5, 3)));
}
References testing::ElementsAre(), EXPECT_THAT, GTEST_ARRAY_SIZE_, and testing::Not().
TEST() [56/350]
testing::gmock_matchers_test::TEST (ElementsAreTest , TakesStlContainer)
Definition at line 5623 of file gmock-matchers_test.cc.
{
  const int actual[] = {3, 1, 2};
  ::std::list<int> expected;
  expected.push_back(3);
  expected.push_back(1);
  expected.push_back(2);
  EXPECT_THAT(actual, ElementsAreArray(expected));
  expected.push_back(4);
  EXPECT_THAT(actual, Not(ElementsAreArray(expected)));
}
References testing::ElementsAreArray(), EXPECT_THAT, and testing::Not().
TEST() [57/350]
testing::gmock_matchers_test::TEST (ElementsAreTest , WorksWithUncopyable)
Definition at line 5616 of file gmock-matchers_test.cc.
{
  Uncopyable objs[2];
  objs[0].set_value(-3);
  objs[1].set_value(1);
  EXPECT_THAT(objs, ElementsAre(UncopyableIs(-3), Truly(ValueIsPositive)));
}
References testing::ElementsAre(), EXPECT_THAT, testing::gmock_matchers_test::Uncopyable::set_value(), testing::Truly(), and ValueIsPositive().
TEST() [58/350]
testing::gmock_matchers_test::TEST (EndsWithTest , CanDescribeSelf)
Definition at line 1758 of file gmock-matchers_test.cc.
{
  Matcher<const std::string> m = EndsWith("Hi");
  EXPECT_EQ("ends with \"Hi\"", Describe(m));
}
References Describe(), testing::EndsWith(), and EXPECT_EQ.
TEST() [59/350]
testing::gmock_matchers_test::TEST (EndsWithTest , MatchesStringWithGivenSuffix)
Definition at line 1726 of file gmock-matchers_test.cc.
{
  const Matcher<const char*> m1 = EndsWith("");
  EXPECT_TRUE(m1.Matches("Hi"));
  EXPECT_TRUE(m1.Matches(""));
  EXPECT_FALSE(m1.Matches(NULL));
  const Matcher<const std::string&> m2 = EndsWith(std::string("Hi"));
  EXPECT_TRUE(m2.Matches("Hi"));
  EXPECT_TRUE(m2.Matches("Wow Hi Hi"));
  EXPECT_TRUE(m2.Matches("Super Hi"));
  EXPECT_FALSE(m2.Matches("i"));
  EXPECT_FALSE(m2.Matches("Hi "));
#if GTEST_HAS_GLOBAL_STRING
  const Matcher<const ::string&> m3 = EndsWith(::string("Hi"));
  EXPECT_TRUE(m3.Matches("Hi"));
  EXPECT_TRUE(m3.Matches("Wow Hi Hi"));
  EXPECT_TRUE(m3.Matches("Super Hi"));
  EXPECT_FALSE(m3.Matches("i"));
  EXPECT_FALSE(m3.Matches("Hi "));
#endif  // GTEST_HAS_GLOBAL_STRING
#if GTEST_HAS_ABSL
  const Matcher<const absl::string_view&> m4 = EndsWith("");
  EXPECT_TRUE(m4.Matches("Hi"));
  EXPECT_TRUE(m4.Matches(""));
  // Default-constructed absl::string_view should not match anything, in order
  // to distinguish it from an empty string.
  EXPECT_FALSE(m4.Matches(absl::string_view()));
#endif  // GTEST_HAS_ABSL
}
References testing::EndsWith(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [60/350]
testing::gmock_matchers_test::TEST (Eq2Test , CanDescribeSelf)
Definition at line 2236 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Eq();
  EXPECT_EQ("are an equal pair", Describe(m));
}
References Describe(), testing::Eq(), and EXPECT_EQ.
TEST() [61/350]
testing::gmock_matchers_test::TEST (Eq2Test , MatchesEqualArguments)
Definition at line 2229 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Eq();
  EXPECT_TRUE(m.Matches(Tuple2(5L, 5)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 6)));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [62/350]
testing::gmock_matchers_test::TEST (EqTest , CanDescribeSelf)
Definition at line 1032 of file gmock-matchers_test.cc.
{
  Matcher<Unprintable> m = Eq(Unprintable());
  EXPECT_EQ("is equal to 1-byte object <61>", Describe(m));
}
References Describe(), testing::Eq(), and EXPECT_EQ.
TEST() [63/350]
testing::gmock_matchers_test::TEST (EqTest , IsPolymorphic)
Definition at line 1039 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(1);
  EXPECT_TRUE(m1.Matches(1));
  EXPECT_FALSE(m1.Matches(2));
  Matcher<char> m2 = Eq(1);
  EXPECT_TRUE(m2.Matches('\1'));
  EXPECT_FALSE(m2.Matches('a'));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [64/350]
testing::gmock_matchers_test::TEST (EqTest , MatchesEqualValue)
Definition at line 1011 of file gmock-matchers_test.cc.
{
  // 2 C-strings with same content but different addresses.
  const char a1[] = "hi";
  const char a2[] = "hi";
  Matcher<const char*> m1 = Eq(a1);
  EXPECT_TRUE(m1.Matches(a1));
  EXPECT_FALSE(m1.Matches(a2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [65/350]
testing::gmock_matchers_test::TEST (ExpectThat , TakesFunctions)
Definition at line 930 of file gmock-matchers_test.cc.
{
  struct Helper {
    static void Func() {}
  };
  void (*func)() = Helper::Func;
  EXPECT_THAT(func, Helper::Func);
  EXPECT_THAT(func, &Helper::Func);
}
References EXPECT_THAT.
TEST() [66/350]
testing::gmock_matchers_test::TEST (ExpectThat , TakesLiterals)
Definition at line 924 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(1, 1);
  EXPECT_THAT(1.0, 1.0);
  EXPECT_THAT(std::string(), "");
}
References EXPECT_THAT.
TEST() [67/350]
testing::gmock_matchers_test::TEST (ExplainmatcherResultTest , MonomorphicMatcher)
Definition at line 4676 of file gmock-matchers_test.cc.
{
  const Matcher<int> m = GreaterThan(5);
  EXPECT_EQ("which is 1 more than 5", Explain(m, 6));
}
References EXPECT_EQ, Explain(), and GreaterThan().
TEST() [68/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , AllOf_False_False)
Definition at line 4645 of file gmock-matchers_test.cc.
{
  const Matcher<int> m = AllOf(DivisibleBy(4), DivisibleBy(3));
  EXPECT_EQ("which is 1 modulo 4", Explain(m, 5));
}
References testing::AllOf(), DivisibleBy(), EXPECT_EQ, and Explain().
TEST() [69/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , AllOf_False_True)
Definition at line 4652 of file gmock-matchers_test.cc.
{
  const Matcher<int> m = AllOf(DivisibleBy(4), DivisibleBy(3));
  EXPECT_EQ("which is 2 modulo 4", Explain(m, 6));
}
References testing::AllOf(), DivisibleBy(), EXPECT_EQ, and Explain().
TEST() [70/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , AllOf_True_False)
Definition at line 4659 of file gmock-matchers_test.cc.
{
  const Matcher<int> m = AllOf(Ge(1), DivisibleBy(3));
  EXPECT_EQ("which is 2 modulo 3", Explain(m, 5));
}
References testing::AllOf(), DivisibleBy(), EXPECT_EQ, Explain(), and testing::Ge().
TEST() [71/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , AllOf_True_True)
Definition at line 4666 of file gmock-matchers_test.cc.
{
  const Matcher<int> m = AllOf(DivisibleBy(2), DivisibleBy(3));
  EXPECT_EQ("which is 0 modulo 2, and which is 0 modulo 3", Explain(m, 6));
}
References testing::AllOf(), DivisibleBy(), EXPECT_EQ, and Explain().
TEST() [72/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , AllOf_True_True_2)
Definition at line 4671 of file gmock-matchers_test.cc.
{
  const Matcher<int> m = AllOf(Ge(2), Le(3));
  EXPECT_EQ("", Explain(m, 2));
}
References testing::AllOf(), EXPECT_EQ, Explain(), testing::Ge(), and testing::Le().
TEST() [73/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , WorksInsideMATCHER)
Definition at line 3048 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(0, Really(Eq(0)));
}
References testing::Eq(), and EXPECT_THAT.
TEST() [74/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , WorksWithMonomorphicMatcher)
Definition at line 3032 of file gmock-matchers_test.cc.
{
  const Matcher<int> is_even = PolymorphicIsEven();
  StringMatchResultListener listener1;
  EXPECT_TRUE(ExplainMatchResult(is_even, 42, &listener1));
  EXPECT_EQ("% 2 == 0", listener1.str());
  const Matcher<const double&> is_zero = Eq(0);
  StringMatchResultListener listener2;
  EXPECT_FALSE(ExplainMatchResult(is_zero, 1.5, &listener2));
  EXPECT_EQ("", listener2.str());
}
References testing::Eq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::ExplainMatchResult(), PolymorphicIsEven(), and testing::StringMatchResultListener::str().
TEST() [75/350]
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , WorksWithPolymorphicMatcher)
Definition at line 3022 of file gmock-matchers_test.cc.
{
  StringMatchResultListener listener1;
  EXPECT_TRUE(ExplainMatchResult(PolymorphicIsEven(), 42, &listener1));
  EXPECT_EQ("% 2 == 0", listener1.str());
  StringMatchResultListener listener2;
  EXPECT_FALSE(ExplainMatchResult(Ge(42), 1.5, &listener2));
  EXPECT_EQ("", listener2.str());
}
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::ExplainMatchResult(), testing::Ge(), PolymorphicIsEven(), and testing::StringMatchResultListener::str().
TEST() [76/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , CanDescribeSelf)
Definition at line 4100 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct*> m = Field(&AStruct::x, Ge(0));
  EXPECT_EQ("is an object whose given field is >= 0", Describe(m));
  EXPECT_EQ("is an object whose given field isn't >= 0", DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Field(), testing::Ge(), and testing::gmock_matchers_test::AStruct::x.
TEST() [77/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , CanDescribeSelfWithFieldName)
Definition at line 4107 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct*> m = Field("field_name", &AStruct::x, Ge(0));
  EXPECT_EQ("is an object whose field `field_name` is >= 0", Describe(m));
  EXPECT_EQ("is an object whose field `field_name` isn't >= 0",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Field(), testing::Ge(), and testing::gmock_matchers_test::AStruct::x.
TEST() [78/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , CanExplainMatchResult)
Definition at line 4116 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct*> m = Field(&AStruct::x, Ge(0));
  AStruct a;
  a.x = 1;
  EXPECT_EQ("", Explain(m, static_cast<const AStruct*>(NULL)));
  EXPECT_EQ("which points to an object whose given field is 1" + OfType("int"),
            Explain(m, &a));
  m = Field(&AStruct::x, GreaterThan(0));
  EXPECT_EQ("which points to an object whose given field is 1" + OfType("int") +
            ", which is 1 more than 0", Explain(m, &a));
}
References EXPECT_EQ, Explain(), testing::Field(), testing::Ge(), GreaterThan(), OfType(), and testing::gmock_matchers_test::AStruct::x.
TEST() [79/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , CanExplainMatchResultWithFieldName)
Definition at line 4130 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct*> m = Field("field_name", &AStruct::x, Ge(0));
  AStruct a;
  a.x = 1;
  EXPECT_EQ("", Explain(m, static_cast<const AStruct*>(NULL)));
  EXPECT_EQ(
      "which points to an object whose field `field_name` is 1" + OfType("int"),
      Explain(m, &a));
  m = Field("field_name", &AStruct::x, GreaterThan(0));
  EXPECT_EQ("which points to an object whose field `field_name` is 1" +
                OfType("int") + ", which is 1 more than 0",
            Explain(m, &a));
}
References EXPECT_EQ, Explain(), testing::Field(), testing::Ge(), GreaterThan(), OfType(), and testing::gmock_matchers_test::AStruct::x.
TEST() [80/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , DoesNotMatchNull)
Definition at line 4081 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct*> m = Field(&AStruct::x, _);
  EXPECT_FALSE(m.Matches(NULL));
}
References testing::_, EXPECT_FALSE, testing::Field(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [81/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , WorksForArgumentOfSubType)
Definition at line 4088 of file gmock-matchers_test.cc.
{
  // Note that the matcher expects DerivedStruct but we say AStruct
  // inside Field().
  Matcher<DerivedStruct*> m = Field(&AStruct::x, Ge(0));
  DerivedStruct d;
  EXPECT_TRUE(m.Matches(&d));
  d.x = -1;
  EXPECT_FALSE(m.Matches(&d));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [82/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , WorksForPointerToConst)
Definition at line 4051 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct*> m = Field(&AStruct::x, Ge(0));
  AStruct a;
  EXPECT_TRUE(m.Matches(&a));
  a.x = -1;
  EXPECT_FALSE(m.Matches(&a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [83/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , WorksForPointerToNonConst)
Definition at line 4061 of file gmock-matchers_test.cc.
{
  Matcher<AStruct*> m = Field(&AStruct::x, Ge(0));
  AStruct a;
  EXPECT_TRUE(m.Matches(&a));
  a.x = -1;
  EXPECT_FALSE(m.Matches(&a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [84/350]
testing::gmock_matchers_test::TEST (FieldForPointerTest , WorksForReferenceToConstPointer)
Definition at line 4071 of file gmock-matchers_test.cc.
{
  Matcher<AStruct* const&> m = Field(&AStruct::x, Ge(0));
  AStruct a;
  EXPECT_TRUE(m.Matches(&a));
  a.x = -1;
  EXPECT_FALSE(m.Matches(&a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [85/350]
testing::gmock_matchers_test::TEST (FieldTest , CanDescribeSelf)
Definition at line 4008 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct&> m = Field(&AStruct::x, Ge(0));
  EXPECT_EQ("is an object whose given field is >= 0", Describe(m));
  EXPECT_EQ("is an object whose given field isn't >= 0", DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Field(), testing::Ge(), and testing::gmock_matchers_test::AStruct::x.
TEST() [86/350]
testing::gmock_matchers_test::TEST (FieldTest , CanDescribeSelfWithFieldName)
Definition at line 4015 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct&> m = Field("field_name", &AStruct::x, Ge(0));
  EXPECT_EQ("is an object whose field `field_name` is >= 0", Describe(m));
  EXPECT_EQ("is an object whose field `field_name` isn't >= 0",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Field(), testing::Ge(), and testing::gmock_matchers_test::AStruct::x.
TEST() [87/350]
testing::gmock_matchers_test::TEST (FieldTest , CanExplainMatchResult)
Definition at line 4024 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct&> m = Field(&AStruct::x, Ge(0));
  AStruct a;
  a.x = 1;
  EXPECT_EQ("whose given field is 1" + OfType("int"), Explain(m, a));
  m = Field(&AStruct::x, GreaterThan(0));
  EXPECT_EQ(
      "whose given field is 1" + OfType("int") + ", which is 1 more than 0",
      Explain(m, a));
}
References EXPECT_EQ, Explain(), testing::Field(), testing::Ge(), GreaterThan(), OfType(), and testing::gmock_matchers_test::AStruct::x.
TEST() [88/350]
testing::gmock_matchers_test::TEST (FieldTest , CanExplainMatchResultWithFieldName)
Definition at line 4037 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct&> m = Field("field_name", &AStruct::x, Ge(0));
  AStruct a;
  a.x = 1;
  EXPECT_EQ("whose field `field_name` is 1" + OfType("int"), Explain(m, a));
  m = Field("field_name", &AStruct::x, GreaterThan(0));
  EXPECT_EQ("whose field `field_name` is 1" + OfType("int") +
                ", which is 1 more than 0",
            Explain(m, a));
}
References EXPECT_EQ, Explain(), testing::Field(), testing::Ge(), GreaterThan(), OfType(), and testing::gmock_matchers_test::AStruct::x.
TEST() [89/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForArgumentOfSubType)
Definition at line 3983 of file gmock-matchers_test.cc.
{
  // Note that the matcher expects DerivedStruct but we say AStruct
  // inside Field().
  Matcher<const DerivedStruct&> m = Field(&AStruct::x, Ge(0));
  DerivedStruct d;
  EXPECT_TRUE(m.Matches(d));
  d.x = -1;
  EXPECT_FALSE(m.Matches(d));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [90/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForByRefArgument)
Definition at line 3972 of file gmock-matchers_test.cc.
{
  Matcher<const AStruct&> m = Field(&AStruct::x, Ge(0));
  AStruct a;
  EXPECT_TRUE(m.Matches(a));
  a.x = -1;
  EXPECT_FALSE(m.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [91/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForCompatibleMatcherType)
Definition at line 3996 of file gmock-matchers_test.cc.
{
  // The field is an int, but the inner matcher expects a signed char.
  Matcher<const AStruct&> m = Field(&AStruct::x,
                                    Matcher<signed char>(Ge(0)));
  AStruct a;
  EXPECT_TRUE(m.Matches(a));
  a.x = -1;
  EXPECT_FALSE(m.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [92/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForConstField)
Definition at line 3931 of file gmock-matchers_test.cc.
{
  AStruct a;
  Matcher<AStruct> m = Field(&AStruct::y, Ge(0.0));
  Matcher<AStruct> m_with_name = Field("y", &AStruct::y, Ge(0.0));
  EXPECT_TRUE(m.Matches(a));
  EXPECT_TRUE(m_with_name.Matches(a));
  m = Field(&AStruct::y, Le(0.0));
  m_with_name = Field("y", &AStruct::y, Le(0.0));
  EXPECT_FALSE(m.Matches(a));
  EXPECT_FALSE(m_with_name.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::Le(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::y.
TEST() [93/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForNonConstField)
Definition at line 3918 of file gmock-matchers_test.cc.
{
  Matcher<AStruct> m = Field(&AStruct::x, Ge(0));
  Matcher<AStruct> m_with_name = Field("x", &AStruct::x, Ge(0));
  AStruct a;
  EXPECT_TRUE(m.Matches(a));
  EXPECT_TRUE(m_with_name.Matches(a));
  a.x = -1;
  EXPECT_FALSE(m.Matches(a));
  EXPECT_FALSE(m_with_name.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::gmock_matchers_test::AStruct::x.
TEST() [94/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForPointerField)
Definition at line 3955 of file gmock-matchers_test.cc.
{
  // Matching against NULL.
  Matcher<AStruct> m = Field(&AStruct::p, static_cast<const char*>(NULL));
  AStruct a;
  EXPECT_TRUE(m.Matches(a));
  a.p = "hi";
  EXPECT_FALSE(m.Matches(a));
  // Matching a pointer that is not NULL.
  m = Field(&AStruct::p, StartsWith("hi"));
  a.p = "hill";
  EXPECT_TRUE(m.Matches(a));
  a.p = "hole";
  EXPECT_FALSE(m.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::AStruct::p, and testing::StartsWith().
TEST() [95/350]
testing::gmock_matchers_test::TEST (FieldTest , WorksForUncopyableField)
Definition at line 3945 of file gmock-matchers_test.cc.
{
  AStruct a;
  Matcher<AStruct> m = Field(&AStruct::z, Truly(ValueIsPositive));
  EXPECT_TRUE(m.Matches(a));
  m = Field(&AStruct::z, Not(Truly(ValueIsPositive)));
  EXPECT_FALSE(m.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Field(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::Truly(), ValueIsPositive(), and testing::gmock_matchers_test::AStruct::z.
TEST() [96/350]
testing::gmock_matchers_test::TEST (FloatEq2Test , CanDescribeSelf)
Definition at line 2327 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<float, float>&> m = FloatEq();
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::FloatEq().
TEST() [97/350]
testing::gmock_matchers_test::TEST (FloatEq2Test , MatchesEqualArguments)
Definition at line 2318 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<float, float> Tpl;
  Matcher<const Tpl&> m = FloatEq();
  EXPECT_TRUE(m.Matches(Tpl(1.0f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(0.3f, 0.1f + 0.1f + 0.1f)));
  EXPECT_FALSE(m.Matches(Tpl(1.1f, 1.0f)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::FloatEq(), and testing::internal::MatcherBase< T >::Matches().
TEST() [98/350]
testing::gmock_matchers_test::TEST (FloatNear2Test , CanDescribeSelf)
Definition at line 2397 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<float, float>&> m = FloatNear(0.5f);
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::FloatNear().
TEST() [99/350]
testing::gmock_matchers_test::TEST (FloatNear2Test , MatchesEqualArguments)
Definition at line 2388 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<float, float> Tpl;
  Matcher<const Tpl&> m = FloatNear(0.5f);
  EXPECT_TRUE(m.Matches(Tpl(1.0f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(1.3f, 1.0f)));
  EXPECT_FALSE(m.Matches(Tpl(1.8f, 1.0f)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::FloatNear(), and testing::internal::MatcherBase< T >::Matches().
TEST() [100/350]
testing::gmock_matchers_test::TEST (FormatMatcherDescriptionTest , WorksForEmptyDescription)
Definition at line 6176 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is even",
            FormatMatcherDescription(false, "IsEven", Strings()));
  EXPECT_EQ("not (is even)",
            FormatMatcherDescription(true, "IsEven", Strings()));
  const char* params[] = {"5"};
  EXPECT_EQ("equals 5",
            FormatMatcherDescription(false, "Equals",
                                     Strings(params, params + 1)));
  const char* params2[] = {"5", "8"};
  EXPECT_EQ("is in range (5, 8)",
            FormatMatcherDescription(false, "IsInRange",
                                     Strings(params2, params2 + 2)));
}
References EXPECT_EQ.
TEST() [101/350]
testing::gmock_matchers_test::TEST (Ge2Test , CanDescribeSelf)
Definition at line 2251 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Ge();
  EXPECT_EQ("are a pair where the first >= the second", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Ge().
TEST() [102/350]
testing::gmock_matchers_test::TEST (Ge2Test , MatchesGreaterThanOrEqualArguments)
Definition at line 2243 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Ge();
  EXPECT_TRUE(m.Matches(Tuple2(5L, 4)));
  EXPECT_TRUE(m.Matches(Tuple2(5L, 5)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 6)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), and testing::internal::MatcherBase< T >::Matches().
TEST() [103/350]
testing::gmock_matchers_test::TEST (GeTest , CanDescribeSelf)
Definition at line 1094 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Ge(5);
  EXPECT_EQ("is >= 5", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Ge().
TEST() [104/350]
testing::gmock_matchers_test::TEST (GeTest , ImplementsGreaterThanOrEqual)
Definition at line 1086 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Ge(0);
  EXPECT_TRUE(m1.Matches(1));
  EXPECT_TRUE(m1.Matches(0));
  EXPECT_FALSE(m1.Matches(-1));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), and testing::internal::MatcherBase< T >::Matches().
TEST() [105/350]
testing::gmock_matchers_test::TEST (Gt2Test , CanDescribeSelf)
Definition at line 2266 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Gt();
  EXPECT_EQ("are a pair where the first > the second", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Gt().
TEST() [106/350]
testing::gmock_matchers_test::TEST (Gt2Test , MatchesGreaterThanArguments)
Definition at line 2258 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Gt();
  EXPECT_TRUE(m.Matches(Tuple2(5L, 4)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 5)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 6)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Gt(), and testing::internal::MatcherBase< T >::Matches().
TEST() [107/350]
testing::gmock_matchers_test::TEST (GtTest , CanDescribeSelf)
Definition at line 1108 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Gt(5);
  EXPECT_EQ("is > 5", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Gt().
TEST() [108/350]
testing::gmock_matchers_test::TEST (GtTest , ImplementsGreaterThan)
Definition at line 1100 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = Gt(0);
  EXPECT_TRUE(m1.Matches(1.0));
  EXPECT_FALSE(m1.Matches(0.0));
  EXPECT_FALSE(m1.Matches(-1.0));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Gt(), and testing::internal::MatcherBase< T >::Matches().
TEST() [109/350]
testing::gmock_matchers_test::TEST (HasSubstrTest , CanDescribeSelf)
Definition at line 1498 of file gmock-matchers_test.cc.
{
  Matcher<std::string> m = HasSubstr("foo\n\"");
  EXPECT_EQ("has substring \"foo\\n\\\"\"", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::HasSubstr().
TEST() [110/350]
testing::gmock_matchers_test::TEST (HasSubstrTest , WorksForCStrings)
Definition at line 1466 of file gmock-matchers_test.cc.
{
  const Matcher<char*> m1 = HasSubstr("foo");
  EXPECT_TRUE(m1.Matches(const_cast<char*>("I love food.")));
  EXPECT_FALSE(m1.Matches(const_cast<char*>("tofo")));
  EXPECT_FALSE(m1.Matches(NULL));
  const Matcher<const char*> m2 = HasSubstr("foo");
  EXPECT_TRUE(m2.Matches("I love food."));
  EXPECT_FALSE(m2.Matches("tofo"));
  EXPECT_FALSE(m2.Matches(NULL));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::HasSubstr(), and testing::internal::MatcherBase< T >::Matches().
TEST() [111/350]
testing::gmock_matchers_test::TEST (HasSubstrTest , WorksForStringClasses)
Definition at line 1455 of file gmock-matchers_test.cc.
{
  const Matcher<std::string> m1 = HasSubstr("foo");
  EXPECT_TRUE(m1.Matches(std::string("I love food.")));
  EXPECT_FALSE(m1.Matches(std::string("tofo")));
  const Matcher<const std::string&> m2 = HasSubstr("foo");
  EXPECT_TRUE(m2.Matches(std::string("I love food.")));
  EXPECT_FALSE(m2.Matches(std::string("tofo")));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::HasSubstr(), and testing::internal::MatcherBase< T >::Matches().
TEST() [112/350]
testing::gmock_matchers_test::TEST (IsEmptyTest , CanDescribeSelf)
Definition at line 4740 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m = IsEmpty();
  EXPECT_EQ("is empty", Describe(m));
  EXPECT_EQ("isn't empty", DescribeNegation(m));
}
References Describe(), DescribeNegation(), and EXPECT_EQ.
TEST() [113/350]
testing::gmock_matchers_test::TEST (IsEmptyTest , ExplainsResult)
Definition at line 4746 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m = IsEmpty();
  vector<int> container;
  EXPECT_EQ("", Explain(m, container));
  container.push_back(0);
  EXPECT_EQ("whose size is 1", Explain(m, container));
}
References EXPECT_EQ, and Explain().
TEST() [114/350]
testing::gmock_matchers_test::TEST (IsEmptyTest , ImplementsIsEmpty)
Definition at line 4722 of file gmock-matchers_test.cc.
{
  vector<int> container;
  EXPECT_THAT(container, IsEmpty());
  container.push_back(0);
  EXPECT_THAT(container, Not(IsEmpty()));
  container.push_back(1);
  EXPECT_THAT(container, Not(IsEmpty()));
}
References EXPECT_THAT, and testing::Not().
TEST() [115/350]
testing::gmock_matchers_test::TEST (IsEmptyTest , WorksWithString)
Definition at line 4731 of file gmock-matchers_test.cc.
{
  std::string text;
  EXPECT_THAT(text, IsEmpty());
  text = "foo";
  EXPECT_THAT(text, Not(IsEmpty()));
  text = std::string("\0", 1);
  EXPECT_THAT(text, Not(IsEmpty()));
}
References EXPECT_THAT, and testing::Not().
TEST() [116/350]
testing::gmock_matchers_test::TEST (IsNullTest , CanDescribeSelf)
Definition at line 1212 of file gmock-matchers_test.cc.
{
  Matcher<int*> m = IsNull();
  EXPECT_EQ("is NULL", Describe(m));
  EXPECT_EQ("isn't NULL", DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::IsNull().
TEST() [117/350]
testing::gmock_matchers_test::TEST (IsNullTest , LinkedPtr)
Definition at line 1184 of file gmock-matchers_test.cc.
{
  const Matcher<linked_ptr<int> > m = IsNull();
  const linked_ptr<int> null_p;
  const linked_ptr<int> non_null_p(new int);
  EXPECT_TRUE(m.Matches(null_p));
  EXPECT_FALSE(m.Matches(non_null_p));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::IsNull(), and testing::internal::MatcherBase< T >::Matches().
TEST() [118/350]
testing::gmock_matchers_test::TEST (IsNullTest , MatchesNullPointer)
Definition at line 1156 of file gmock-matchers_test.cc.
{
  Matcher<int*> m1 = IsNull();
  int* p1 = NULL;
  int n = 0;
  EXPECT_TRUE(m1.Matches(p1));
  EXPECT_FALSE(m1.Matches(&n));
  Matcher<const char*> m2 = IsNull();
  const char* p2 = NULL;
  EXPECT_TRUE(m2.Matches(p2));
  EXPECT_FALSE(m2.Matches("hi"));
#if !GTEST_OS_SYMBIAN
  // Nokia's Symbian compiler generates:
  // gmock-matchers.h: ambiguous access to overloaded function
  // gmock-matchers.h: 'testing::Matcher<void *>::Matcher(void *)'
  // gmock-matchers.h: 'testing::Matcher<void *>::Matcher(const testing::
  //     MatcherInterface<void *> *)'
  // gmock-matchers.h:  (point of instantiation: 'testing::
  //     gmock_matchers_test::IsNullTest_MatchesNullPointer_Test::TestBody()')
  // gmock-matchers.h:   (instantiating: 'testing::PolymorphicMatc
  Matcher<void*> m3 = IsNull();
  void* p3 = NULL;
  EXPECT_TRUE(m3.Matches(p3));
  EXPECT_FALSE(m3.Matches(reinterpret_cast<void*>(0xbeef)));
#endif
}
References EXPECT_FALSE, EXPECT_TRUE, testing::IsNull(), and testing::internal::MatcherBase< T >::Matches().
TEST() [119/350]
testing::gmock_matchers_test::TEST (IsNullTest , ReferenceToConstLinkedPtr)
Definition at line 1193 of file gmock-matchers_test.cc.
{
  const Matcher<const linked_ptr<double>&> m = IsNull();
  const linked_ptr<double> null_p;
  const linked_ptr<double> non_null_p(new double);
  EXPECT_TRUE(m.Matches(null_p));
  EXPECT_FALSE(m.Matches(non_null_p));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::IsNull(), and testing::internal::MatcherBase< T >::Matches().
TEST() [120/350]
testing::gmock_matchers_test::TEST (IsReadableTypeNameTest , ReturnsFalseForLongFunctionTypeNames)
Definition at line 6170 of file gmock-matchers_test.cc.
{
  EXPECT_FALSE(IsReadableTypeName("void (&)(int, bool, char, float)"));
}
References EXPECT_FALSE.
TEST() [121/350]
testing::gmock_matchers_test::TEST (IsReadableTypeNameTest , ReturnsFalseForLongTemplateNames)
Definition at line 6164 of file gmock-matchers_test.cc.
{
  EXPECT_FALSE(
      IsReadableTypeName("basic_string<char, std::char_traits<char> >"));
  EXPECT_FALSE(IsReadableTypeName("std::vector<int, std::alloc_traits<int> >"));
}
References EXPECT_FALSE.
TEST() [122/350]
testing::gmock_matchers_test::TEST (IsReadableTypeNameTest , ReturnsTrueForLongNonTemplateNonFunctionNames)
Definition at line 6158 of file gmock-matchers_test.cc.
{
  EXPECT_TRUE(IsReadableTypeName("my_long_namespace::MyClassName"));
  EXPECT_TRUE(IsReadableTypeName("int [5][6][7][8][9][10][11]"));
  EXPECT_TRUE(IsReadableTypeName("my_namespace::MyOuterClass::MyInnerClass"));
}
References EXPECT_TRUE.
TEST() [123/350]
testing::gmock_matchers_test::TEST (IsReadableTypeNameTest , ReturnsTrueForShortNames)
Definition at line 6151 of file gmock-matchers_test.cc.
{
  EXPECT_TRUE(IsReadableTypeName("int"));
  EXPECT_TRUE(IsReadableTypeName("const unsigned char*"));
  EXPECT_TRUE(IsReadableTypeName("MyMap<int, void*>"));
  EXPECT_TRUE(IsReadableTypeName("void (*)(int, bool)"));
}
References EXPECT_TRUE.
TEST() [124/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , Describe)
Definition at line 5530 of file gmock-matchers_test.cc.
{
  typedef std::vector<int> IntVec;
  IntVec expected;
  expected.push_back(111);
  expected.push_back(222);
  expected.push_back(333);
  EXPECT_THAT(
      Describe<IntVec>(IsSubsetOf(expected)),
      Eq("an injection from elements to requirements exists such that:\n"
         " - an element is equal to 111\n"
         " - an element is equal to 222\n"
         " - an element is equal to 333"));
}
References testing::Eq(), EXPECT_THAT, and testing::IsSubsetOf().
TEST() [125/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , DescribeNegation)
Definition at line 5545 of file gmock-matchers_test.cc.
{
  typedef std::vector<int> IntVec;
  IntVec expected;
  expected.push_back(111);
  expected.push_back(222);
  expected.push_back(333);
  EXPECT_THAT(
      DescribeNegation<IntVec>(IsSubsetOf(expected)),
      Eq("no injection from elements to requirements exists such that:\n"
         " - an element is equal to 111\n"
         " - an element is equal to 222\n"
         " - an element is equal to 333"));
}
References testing::Eq(), EXPECT_THAT, and testing::IsSubsetOf().
TEST() [126/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , MatchAndExplain)
Definition at line 5559 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  v.push_back(2);
  v.push_back(3);
  std::vector<int> expected;
  expected.push_back(1);
  expected.push_back(2);
  StringMatchResultListener listener;
  ASSERT_FALSE(ExplainMatchResult(IsSubsetOf(expected), v, &listener))
      << listener.str();
  EXPECT_THAT(listener.str(),
              Eq("where the following elements don't match any matchers:\n"
                 "element #1: 3"));
  expected.push_back(3);
  listener.Clear();
  ASSERT_TRUE(ExplainMatchResult(IsSubsetOf(expected), v, &listener))
      << listener.str();
  EXPECT_THAT(listener.str(), Eq("where:\n"
                                 " - element #0 is matched by matcher #1,\n"
                                 " - element #1 is matched by matcher #2"));
}
References ASSERT_FALSE, ASSERT_TRUE, testing::StringMatchResultListener::Clear(), testing::Eq(), EXPECT_THAT, testing::ExplainMatchResult(), testing::IsSubsetOf(), and testing::StringMatchResultListener::str().
TEST() [127/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , TakesStlContainer)
Definition at line 5517 of file gmock-matchers_test.cc.
{
  const int actual[] = {3, 1, 2};
  ::std::list<int> expected;
  expected.push_back(1);
  expected.push_back(3);
  EXPECT_THAT(actual, Not(IsSubsetOf(expected)));
  expected.push_back(2);
  expected.push_back(4);
  EXPECT_THAT(actual, IsSubsetOf(expected));
}
References EXPECT_THAT, testing::IsSubsetOf(), and testing::Not().
TEST() [128/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , WorksForEmpty)
Definition at line 5487 of file gmock-matchers_test.cc.
{
  vector<int> numbers;
  vector<int> expected;
  EXPECT_THAT(numbers, IsSubsetOf(expected));
  expected.push_back(1);
  EXPECT_THAT(numbers, IsSubsetOf(expected));
  expected.clear();
  numbers.push_back(1);
  numbers.push_back(2);
  EXPECT_THAT(numbers, Not(IsSubsetOf(expected)));
  expected.push_back(1);
  EXPECT_THAT(numbers, Not(IsSubsetOf(expected)));
  expected.push_back(2);
  EXPECT_THAT(numbers, IsSubsetOf(expected));
  expected.push_back(3);
  EXPECT_THAT(numbers, IsSubsetOf(expected));
}
References EXPECT_THAT, testing::IsSubsetOf(), and testing::Not().
TEST() [129/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , WorksForNativeArray)
Definition at line 5468 of file gmock-matchers_test.cc.
{
  const int subset[] = {1, 4};
  const int superset[] = {1, 2, 4};
  const int disjoint[] = {1, 0, 3};
  EXPECT_THAT(subset, IsSubsetOf(subset));
  EXPECT_THAT(subset, IsSubsetOf(superset));
  EXPECT_THAT(superset, Not(IsSubsetOf(subset)));
  EXPECT_THAT(subset, Not(IsSubsetOf(disjoint)));
  EXPECT_THAT(disjoint, Not(IsSubsetOf(subset)));
}
References EXPECT_THAT, testing::IsSubsetOf(), and testing::Not().
TEST() [130/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , WorksForStreamlike)
Definition at line 5505 of file gmock-matchers_test.cc.
{
  const int a[5] = {1, 2};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  vector<int> expected;
  expected.push_back(1);
  EXPECT_THAT(s, Not(IsSubsetOf(expected)));
  expected.push_back(2);
  expected.push_back(5);
  EXPECT_THAT(s, IsSubsetOf(expected));
}
References EXPECT_THAT, GTEST_ARRAY_SIZE_, testing::IsSubsetOf(), and testing::Not().
TEST() [131/350]
testing::gmock_matchers_test::TEST (IsSubsetOfTest , WorksWithDuplicates)
Definition at line 5479 of file gmock-matchers_test.cc.
{
  const int not_enough[] = {1, 2};
  const int enough[] = {1, 1, 2};
  const int actual[] = {1, 1};
  EXPECT_THAT(actual, Not(IsSubsetOf(not_enough)));
  EXPECT_THAT(actual, IsSubsetOf(enough));
}
References EXPECT_THAT, testing::IsSubsetOf(), and testing::Not().
TEST() [132/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , Describe)
Definition at line 5409 of file gmock-matchers_test.cc.
{
  typedef std::vector<int> IntVec;
  IntVec expected;
  expected.push_back(111);
  expected.push_back(222);
  expected.push_back(333);
  EXPECT_THAT(
      Describe<IntVec>(IsSupersetOf(expected)),
      Eq("a surjection from elements to requirements exists such that:\n"
         " - an element is equal to 111\n"
         " - an element is equal to 222\n"
         " - an element is equal to 333"));
}
References testing::Eq(), EXPECT_THAT, and testing::IsSupersetOf().
TEST() [133/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , DescribeNegation)
Definition at line 5423 of file gmock-matchers_test.cc.
{
  typedef std::vector<int> IntVec;
  IntVec expected;
  expected.push_back(111);
  expected.push_back(222);
  expected.push_back(333);
  EXPECT_THAT(
      DescribeNegation<IntVec>(IsSupersetOf(expected)),
      Eq("no surjection from elements to requirements exists such that:\n"
         " - an element is equal to 111\n"
         " - an element is equal to 222\n"
         " - an element is equal to 333"));
}
References testing::Eq(), EXPECT_THAT, and testing::IsSupersetOf().
TEST() [134/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , MatchAndExplain)
Definition at line 5437 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  v.push_back(2);
  v.push_back(3);
  std::vector<int> expected;
  expected.push_back(1);
  expected.push_back(2);
  StringMatchResultListener listener;
  ASSERT_FALSE(ExplainMatchResult(IsSupersetOf(expected), v, &listener))
      << listener.str();
  EXPECT_THAT(listener.str(),
              Eq("where the following matchers don't match any elements:\n"
                 "matcher #0: is equal to 1"));
  v.push_back(1);
  listener.Clear();
  ASSERT_TRUE(ExplainMatchResult(IsSupersetOf(expected), v, &listener))
      << listener.str();
  EXPECT_THAT(listener.str(), Eq("where:\n"
                                 " - element #0 is matched by matcher #1,\n"
                                 " - element #2 is matched by matcher #0"));
}
References ASSERT_FALSE, ASSERT_TRUE, testing::StringMatchResultListener::Clear(), testing::Eq(), EXPECT_THAT, testing::ExplainMatchResult(), testing::IsSupersetOf(), and testing::StringMatchResultListener::str().
TEST() [135/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , TakesStlContainer)
Definition at line 5397 of file gmock-matchers_test.cc.
{
  const int actual[] = {3, 1, 2};
  ::std::list<int> expected;
  expected.push_back(1);
  expected.push_back(3);
  EXPECT_THAT(actual, IsSupersetOf(expected));
  expected.push_back(4);
  EXPECT_THAT(actual, Not(IsSupersetOf(expected)));
}
References EXPECT_THAT, testing::IsSupersetOf(), and testing::Not().
TEST() [136/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , WorksForEmpty)
Definition at line 5365 of file gmock-matchers_test.cc.
{
  vector<int> numbers;
  vector<int> expected;
  EXPECT_THAT(numbers, IsSupersetOf(expected));
  expected.push_back(1);
  EXPECT_THAT(numbers, Not(IsSupersetOf(expected)));
  expected.clear();
  numbers.push_back(1);
  numbers.push_back(2);
  EXPECT_THAT(numbers, IsSupersetOf(expected));
  expected.push_back(1);
  EXPECT_THAT(numbers, IsSupersetOf(expected));
  expected.push_back(2);
  EXPECT_THAT(numbers, IsSupersetOf(expected));
  expected.push_back(3);
  EXPECT_THAT(numbers, Not(IsSupersetOf(expected)));
}
References EXPECT_THAT, testing::IsSupersetOf(), and testing::Not().
TEST() [137/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , WorksForNativeArray)
Definition at line 5346 of file gmock-matchers_test.cc.
{
  const int subset[] = {1, 4};
  const int superset[] = {1, 2, 4};
  const int disjoint[] = {1, 0, 3};
  EXPECT_THAT(subset, IsSupersetOf(subset));
  EXPECT_THAT(subset, Not(IsSupersetOf(superset)));
  EXPECT_THAT(superset, IsSupersetOf(subset));
  EXPECT_THAT(subset, Not(IsSupersetOf(disjoint)));
  EXPECT_THAT(disjoint, Not(IsSupersetOf(subset)));
}
References EXPECT_THAT, testing::IsSupersetOf(), and testing::Not().
TEST() [138/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , WorksForStreamlike)
Definition at line 5383 of file gmock-matchers_test.cc.
{
  const int a[5] = {1, 2, 3, 4, 5};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  vector<int> expected;
  expected.push_back(1);
  expected.push_back(2);
  expected.push_back(5);
  EXPECT_THAT(s, IsSupersetOf(expected));
  expected.push_back(0);
  EXPECT_THAT(s, Not(IsSupersetOf(expected)));
}
References EXPECT_THAT, GTEST_ARRAY_SIZE_, testing::IsSupersetOf(), and testing::Not().
TEST() [139/350]
testing::gmock_matchers_test::TEST (IsSupersetOfTest , WorksWithDuplicates)
Definition at line 5357 of file gmock-matchers_test.cc.
{
  const int not_enough[] = {1, 2};
  const int enough[] = {1, 1, 2};
  const int expected[] = {1, 1};
  EXPECT_THAT(not_enough, Not(IsSupersetOf(expected)));
  EXPECT_THAT(enough, IsSupersetOf(expected));
}
References EXPECT_THAT, testing::IsSupersetOf(), and testing::Not().
TEST() [140/350]
testing::gmock_matchers_test::TEST (IsTrueTest , IsTrueIsFalse)
Definition at line 4754 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(true, IsTrue());
  EXPECT_THAT(false, IsFalse());
  EXPECT_THAT(true, Not(IsFalse()));
  EXPECT_THAT(false, Not(IsTrue()));
  EXPECT_THAT(0, Not(IsTrue()));
  EXPECT_THAT(0, IsFalse());
  EXPECT_THAT(NULL, Not(IsTrue()));
  EXPECT_THAT(NULL, IsFalse());
  EXPECT_THAT(-1, IsTrue());
  EXPECT_THAT(-1, Not(IsFalse()));
  EXPECT_THAT(1, IsTrue());
  EXPECT_THAT(1, Not(IsFalse()));
  EXPECT_THAT(2, IsTrue());
  EXPECT_THAT(2, Not(IsFalse()));
  int a = 42;
  EXPECT_THAT(a, IsTrue());
  EXPECT_THAT(a, Not(IsFalse()));
  EXPECT_THAT(&a, IsTrue());
  EXPECT_THAT(&a, Not(IsFalse()));
  EXPECT_THAT(false, Not(IsTrue()));
  EXPECT_THAT(true, Not(IsFalse()));
#if GTEST_LANG_CXX11
  EXPECT_THAT(std::true_type(), IsTrue());
  EXPECT_THAT(std::true_type(), Not(IsFalse()));
  EXPECT_THAT(std::false_type(), IsFalse());
  EXPECT_THAT(std::false_type(), Not(IsTrue()));
  EXPECT_THAT(nullptr, Not(IsTrue()));
  EXPECT_THAT(nullptr, IsFalse());
  std::unique_ptr<int> null_unique;
  std::unique_ptr<int> nonnull_unique(new int(0));
  EXPECT_THAT(null_unique, Not(IsTrue()));
  EXPECT_THAT(null_unique, IsFalse());
  EXPECT_THAT(nonnull_unique, IsTrue());
  EXPECT_THAT(nonnull_unique, Not(IsFalse()));
#endif  // GTEST_LANG_CXX11
}
References EXPECT_THAT, and testing::Not().
TEST() [141/350]
testing::gmock_matchers_test::TEST (KeyTest , CanDescribeSelf)
Definition at line 1503 of file gmock-matchers_test.cc.
{
  Matcher<const pair<std::string, int>&> m = Key("foo");
  EXPECT_EQ("has a key that is equal to \"foo\"", Describe(m));
  EXPECT_EQ("doesn't have a key that is equal to \"foo\"", DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::Key().
TEST() [142/350]
testing::gmock_matchers_test::TEST (KeyTest , ExplainsResult)
Definition at line 1509 of file gmock-matchers_test.cc.
{
  Matcher<pair<int, bool> > m = Key(GreaterThan(10));
  EXPECT_EQ("whose first field is a value which is 5 less than 10",
            Explain(m, make_pair(5, true)));
  EXPECT_EQ("whose first field is a value which is 5 more than 10",
            Explain(m, make_pair(15, true)));
}
References EXPECT_EQ, Explain(), GreaterThan(), and testing::Key().
TEST() [143/350]
testing::gmock_matchers_test::TEST (KeyTest , InsideContainsUsingMap)
Definition at line 1562 of file gmock-matchers_test.cc.
{
  map<int, char> container;
  container.insert(make_pair(1, 'a'));
  container.insert(make_pair(2, 'b'));
  container.insert(make_pair(4, 'c'));
  EXPECT_THAT(container, Contains(Key(1)));
  EXPECT_THAT(container, Not(Contains(Key(3))));
}
References testing::Contains(), EXPECT_THAT, testing::Key(), and testing::Not().
TEST() [144/350]
testing::gmock_matchers_test::TEST (KeyTest , InsideContainsUsingMultimap)
Definition at line 1571 of file gmock-matchers_test.cc.
{
  multimap<int, char> container;
  container.insert(make_pair(1, 'a'));
  container.insert(make_pair(2, 'b'));
  container.insert(make_pair(4, 'c'));
  EXPECT_THAT(container, Not(Contains(Key(25))));
  container.insert(make_pair(25, 'd'));
  EXPECT_THAT(container, Contains(Key(25)));
  container.insert(make_pair(25, 'e'));
  EXPECT_THAT(container, Contains(Key(25)));
  EXPECT_THAT(container, Contains(Key(1)));
  EXPECT_THAT(container, Not(Contains(Key(3))));
}
References testing::Contains(), EXPECT_THAT, testing::Key(), and testing::Not().
TEST() [145/350]
testing::gmock_matchers_test::TEST (KeyTest , MatchesCorrectly)
Definition at line 1517 of file gmock-matchers_test.cc.
{
  pair<int, std::string> p(25, "foo");
  EXPECT_THAT(p, Key(25));
  EXPECT_THAT(p, Not(Key(42)));
  EXPECT_THAT(p, Key(Ge(20)));
  EXPECT_THAT(p, Not(Key(Lt(25))));
}
References EXPECT_THAT, testing::Ge(), testing::Key(), testing::Lt(), and testing::Not().
TEST() [146/350]
testing::gmock_matchers_test::TEST (KeyTest , SafelyCastsInnerMatcher)
Definition at line 1554 of file gmock-matchers_test.cc.
{
  Matcher<int> is_positive = Gt(0);
  Matcher<int> is_negative = Lt(0);
  pair<char, bool> p('a', true);
  EXPECT_THAT(p, Key(is_positive));
  EXPECT_THAT(p, Not(Key(is_negative)));
}
References EXPECT_THAT, testing::Gt(), testing::Key(), testing::Lt(), and testing::Not().
TEST() [147/350]
testing::gmock_matchers_test::TEST (Le2Test , CanDescribeSelf)
Definition at line 2281 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Le();
  EXPECT_EQ("are a pair where the first <= the second", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Le().
TEST() [148/350]
testing::gmock_matchers_test::TEST (Le2Test , MatchesLessThanOrEqualArguments)
Definition at line 2273 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Le();
  EXPECT_TRUE(m.Matches(Tuple2(5L, 6)));
  EXPECT_TRUE(m.Matches(Tuple2(5L, 5)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 4)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Le(), and testing::internal::MatcherBase< T >::Matches().
TEST() [149/350]
testing::gmock_matchers_test::TEST (LeTest , CanDescribeSelf)
Definition at line 1122 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Le(5);
  EXPECT_EQ("is <= 5", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Le().
TEST() [150/350]
testing::gmock_matchers_test::TEST (LeTest , ImplementsLessThanOrEqual)
Definition at line 1114 of file gmock-matchers_test.cc.
{
  Matcher<char> m1 = Le('b');
  EXPECT_TRUE(m1.Matches('a'));
  EXPECT_TRUE(m1.Matches('b'));
  EXPECT_FALSE(m1.Matches('c'));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Le(), and testing::internal::MatcherBase< T >::Matches().
TEST() [151/350]
testing::gmock_matchers_test::TEST (Lt2Test , CanDescribeSelf)
Definition at line 2296 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Lt();
  EXPECT_EQ("are a pair where the first < the second", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Lt().
TEST() [152/350]
testing::gmock_matchers_test::TEST (Lt2Test , MatchesLessThanArguments)
Definition at line 2288 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Lt();
  EXPECT_TRUE(m.Matches(Tuple2(5L, 6)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 5)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 4)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Lt(), and testing::internal::MatcherBase< T >::Matches().
TEST() [153/350]
testing::gmock_matchers_test::TEST (LtTest , CanDescribeSelf)
Definition at line 1136 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Lt(5);
  EXPECT_EQ("is < 5", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Lt().
TEST() [154/350]
testing::gmock_matchers_test::TEST (LtTest , ImplementsLessThan)
Definition at line 1128 of file gmock-matchers_test.cc.
{
  Matcher<const std::string&> m1 = Lt("Hello");
  EXPECT_TRUE(m1.Matches("Abc"));
  EXPECT_FALSE(m1.Matches("Hello"));
  EXPECT_FALSE(m1.Matches("Hello, world!"));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Lt(), and testing::internal::MatcherBase< T >::Matches().
TEST() [155/350]
testing::gmock_matchers_test::TEST (MakeMatcherTest , ConstructsMatcherFromMatcherInterface)
Definition at line 515 of file gmock-matchers_test.cc.
{
  const MatcherInterface<int>* dummy_impl = NULL;
  Matcher<int> m = MakeMatcher(dummy_impl);
}
References testing::MakeMatcher().
TEST() [156/350]
testing::gmock_matchers_test::TEST (MakePolymorphicMatcherTest , ConstructsMatcherUsingNewAPI)
Definition at line 588 of file gmock-matchers_test.cc.
{
  // Using PolymorphicIsEven() as a Matcher<int>.
  const Matcher<int> m1 = PolymorphicIsEven();
  EXPECT_TRUE(m1.Matches(42));
  EXPECT_FALSE(m1.Matches(43));
  EXPECT_EQ("is even", Describe(m1));
  const Matcher<int> not_m1 = Not(m1);
  EXPECT_EQ("is odd", Describe(not_m1));
  EXPECT_EQ("% 2 == 0", Explain(m1, 42));
  // Using PolymorphicIsEven() as a Matcher<char>.
  const Matcher<char> m2 = PolymorphicIsEven();
  EXPECT_TRUE(m2.Matches('\x42'));
  EXPECT_FALSE(m2.Matches('\x43'));
  EXPECT_EQ("is even", Describe(m2));
  const Matcher<char> not_m2 = Not(m2);
  EXPECT_EQ("is odd", Describe(not_m2));
  EXPECT_EQ("% 2 == 0", Explain(m2, '\x42'));
}
References Describe(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), and PolymorphicIsEven().
TEST() [157/350]
testing::gmock_matchers_test::TEST (MakePolymorphicMatcherTest , ConstructsMatcherUsingOldAPI)
Definition at line 545 of file gmock-matchers_test.cc.
{
  // Using a polymorphic matcher to match a reference type.
  Matcher<const int&> m1 = ReferencesBarOrIsZero();
  EXPECT_TRUE(m1.Matches(0));
  // Verifies that the identity of a by-reference argument is preserved.
  EXPECT_TRUE(m1.Matches(g_bar));
  EXPECT_FALSE(m1.Matches(1));
  EXPECT_EQ("g_bar or zero", Describe(m1));
  // Using a polymorphic matcher to match a value type.
  Matcher<double> m2 = ReferencesBarOrIsZero();
  EXPECT_TRUE(m2.Matches(0.0));
  EXPECT_FALSE(m2.Matches(0.1));
  EXPECT_EQ("g_bar or zero", Describe(m2));
}
References Describe(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, g_bar, testing::internal::MatcherBase< T >::Matches(), and ReferencesBarOrIsZero().
TEST() [158/350]
testing::gmock_matchers_test::TEST (MatcherAssertionTest , WorksForByRefArguments)
Definition at line 3176 of file gmock-matchers_test.cc.
{
  // We use a static variable here as EXPECT_FATAL_FAILURE() cannot
  // reference auto variables.
  static int n;
  n = 0;
  EXPECT_THAT(n, AllOf(Le(7), Ref(n)));
  EXPECT_FATAL_FAILURE(ASSERT_THAT(n, ::testing::Not(::testing::Ref(n))),
                       "Value of: n\n"
                       "Expected: does not reference the variable @");
  // Tests the "Actual" part.
  EXPECT_FATAL_FAILURE(ASSERT_THAT(n, ::testing::Not(::testing::Ref(n))),
                       "Actual: 0" + OfType("int") + ", which is located @");
}
References testing::AllOf(), ASSERT_THAT, EXPECT_FATAL_FAILURE, EXPECT_THAT, testing::Le(), testing::Not(), OfType(), and testing::Ref().
TEST() [159/350]
testing::gmock_matchers_test::TEST (MatcherAssertionTest , WorksForMonomorphicMatcher)
Definition at line 3204 of file gmock-matchers_test.cc.
{
  Matcher<const char*> starts_with_he = StartsWith("he");
  ASSERT_THAT("hello", starts_with_he);
  Matcher<const std::string&> ends_with_ok = EndsWith("ok");
  ASSERT_THAT("book", ends_with_ok);
  const std::string bad = "bad";
  EXPECT_NONFATAL_FAILURE(EXPECT_THAT(bad, ends_with_ok),
                          "Value of: bad\n"
                          "Expected: ends with \"ok\"\n"
                          "  Actual: \"bad\"");
  Matcher<int> is_greater_than_5 = Gt(5);
  EXPECT_NONFATAL_FAILURE(EXPECT_THAT(5, is_greater_than_5),
                          "Value of: 5\n"
                          "Expected: is > 5\n"
                          "  Actual: 5" + OfType("int"));
}
References ASSERT_THAT, testing::EndsWith(), EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::Gt(), OfType(), and testing::StartsWith().
TEST() [160/350]
testing::gmock_matchers_test::TEST (MatcherAssertionTest , WorksWhenMatcherIsNotSatisfied)
Definition at line 3151 of file gmock-matchers_test.cc.
{
  // 'n' must be static as it is used in an EXPECT_FATAL_FAILURE(),
  // which cannot reference auto variables.
  static unsigned short n;  // NOLINT
  n = 5;
  // VC++ prior to version 8.0 SP1 has a bug where it will not see any
  // functions declared in the namespace scope from within nested classes.
  // EXPECT/ASSERT_(NON)FATAL_FAILURE macros use nested classes so that all
  // namespace-level functions invoked inside them need to be explicitly
  // resolved.
  EXPECT_FATAL_FAILURE(ASSERT_THAT(n, ::testing::Gt(10)),
                       "Value of: n\n"
                       "Expected: is > 10\n"
                       "  Actual: 5" + OfType("unsigned short"));
  n = 0;
  EXPECT_NONFATAL_FAILURE(
      EXPECT_THAT(n, ::testing::AllOf(::testing::Le(7), ::testing::Ge(5))),
      "Value of: n\n"
      "Expected: (is <= 7) and (is >= 5)\n"
      "  Actual: 0" + OfType("unsigned short"));
}
References testing::AllOf(), ASSERT_THAT, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::Ge(), testing::Gt(), testing::Le(), and OfType().
TEST() [161/350]
testing::gmock_matchers_test::TEST (MatcherAssertionTest , WorksWhenMatcherIsSatisfied)
Definition at line 3142 of file gmock-matchers_test.cc.
{
  ASSERT_THAT(5, Ge(2)) << "This should succeed.";
  ASSERT_THAT("Foo", EndsWith("oo"));
  EXPECT_THAT(2, AllOf(Le(7), Ge(0))) << "This should succeed too.";
  EXPECT_THAT("Hello", StartsWith("Hell"));
}
References testing::AllOf(), ASSERT_THAT, testing::EndsWith(), EXPECT_THAT, testing::Ge(), testing::Le(), and testing::StartsWith().
TEST() [162/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromAnImplicitlyConvertibleValue)
Definition at line 705 of file gmock-matchers_test.cc.
{
  const int kExpected = 'c';
  Matcher<int> m = MatcherCast<int>('c');
  EXPECT_TRUE(m.Matches(kExpected));
  EXPECT_FALSE(m.Matches(kExpected + 1));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [163/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromAValue)
Definition at line 697 of file gmock-matchers_test.cc.
{
  Matcher<int> m = MatcherCast<int>(42);
  EXPECT_TRUE(m.Matches(42));
  EXPECT_FALSE(m.Matches(239));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [164/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromCompatibleType)
Definition at line 638 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = Eq(2.0);
  Matcher<int> m2 = MatcherCast<int>(m1);
  EXPECT_TRUE(m2.Matches(2));
  EXPECT_FALSE(m2.Matches(3));
  Matcher<IntValue> m3 = Truly(IsPositiveIntValue);
  Matcher<int> m4 = MatcherCast<int>(m3);
  // In the following, the arguments 1 and 0 are statically converted
  // to IntValue objects, and then tested by the IsPositiveIntValue()
  // predicate.
  EXPECT_TRUE(m4.Matches(1));
  EXPECT_FALSE(m4.Matches(0));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, IsPositiveIntValue(), testing::internal::MatcherBase< T >::Matches(), and testing::Truly().
TEST() [165/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromConstReferenceToNonReference)
Definition at line 654 of file gmock-matchers_test.cc.
{
  Matcher<const int&> m1 = Eq(0);
  Matcher<int> m2 = MatcherCast<int>(m1);
  EXPECT_TRUE(m2.Matches(0));
  EXPECT_FALSE(m2.Matches(1));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [166/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromNonReferenceToConstReference)
Definition at line 670 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(0);
  Matcher<const int&> m2 = MatcherCast<const int&>(m1);
  EXPECT_TRUE(m2.Matches(0));
  EXPECT_FALSE(m2.Matches(1));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [167/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromNonReferenceToReference)
Definition at line 678 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(0);
  Matcher<int&> m2 = MatcherCast<int&>(m1);
  int n = 0;
  EXPECT_TRUE(m2.Matches(n));
  n = 1;
  EXPECT_FALSE(m2.Matches(n));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [168/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromPolymorphicMatcher)
Definition at line 613 of file gmock-matchers_test.cc.
{
  Matcher<int> m = MatcherCast<int>(Eq(5));
  EXPECT_TRUE(m.Matches(5));
  EXPECT_FALSE(m.Matches(6));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [169/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromReferenceToNonReference)
Definition at line 662 of file gmock-matchers_test.cc.
{
  Matcher<int&> m1 = Eq(0);
  Matcher<int> m2 = MatcherCast<int>(m1);
  EXPECT_TRUE(m2.Matches(0));
  EXPECT_FALSE(m2.Matches(1));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [170/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , FromSameType)
Definition at line 688 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(0);
  Matcher<int> m2 = MatcherCast<int>(m1);
  EXPECT_TRUE(m2.Matches(0));
  EXPECT_FALSE(m2.Matches(1));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [171/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , NonImplicitlyConstructibleTypeWithOperatorEq)
Definition at line 728 of file gmock-matchers_test.cc.
{
  Matcher<NonImplicitlyConstructibleTypeWithOperatorEq> m1 =
      MatcherCast<NonImplicitlyConstructibleTypeWithOperatorEq>(42);
  EXPECT_TRUE(m1.Matches(NonImplicitlyConstructibleTypeWithOperatorEq()));
  Matcher<NonImplicitlyConstructibleTypeWithOperatorEq> m2 =
      MatcherCast<NonImplicitlyConstructibleTypeWithOperatorEq>(239);
  EXPECT_FALSE(m2.Matches(NonImplicitlyConstructibleTypeWithOperatorEq()));
  // When updating the following lines please also change the comment to
  // namespace convertible_from_any.
  Matcher<int> m3 =
      MatcherCast<int>(NonImplicitlyConstructibleTypeWithOperatorEq());
  EXPECT_TRUE(m3.Matches(42));
  EXPECT_FALSE(m3.Matches(239));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [172/350]
testing::gmock_matchers_test::TEST (MatcherCastTest , ValueIsNotCopied)
Definition at line 803 of file gmock-matchers_test.cc.
{
  int n = 42;
  Matcher<IntReferenceWrapper> m = MatcherCast<IntReferenceWrapper>(n);
  // Verify that the matcher holds a reference to n, not to its temporary copy.
  EXPECT_TRUE(m.Matches(n));
}
References EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [173/350]
testing::gmock_matchers_test::TEST (MatcherInterfaceTest , CanBeImplementedUsingNewAPI)
Definition at line 300 of file gmock-matchers_test.cc.
{
  Matcher<int> m = MakeMatcher(new NewEvenMatcherImpl);
  EXPECT_TRUE(m.Matches(2));
  EXPECT_FALSE(m.Matches(3));
  EXPECT_EQ("value % 2 == 0", Explain(m, 2));
  EXPECT_EQ("value % 2 == 1", Explain(m, 3));
}
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), testing::MakeMatcher(), and testing::internal::MatcherBase< T >::Matches().
TEST() [174/350]
testing::gmock_matchers_test::TEST (MatcherInterfaceTest , CanBeImplementedUsingPublishedAPI)
Definition at line 275 of file gmock-matchers_test.cc.
{
  EvenMatcherImpl m;
}
TEST() [175/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanAcceptAbstractClass)
Definition at line 350 of file gmock-matchers_test.cc.
{ Matcher<const Undefined&> m = _; }
References testing::_.
TEST() [176/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanBeConstructedFromMatcherInterface)
Definition at line 314 of file gmock-matchers_test.cc.
{
  const MatcherInterface<int>* impl = new EvenMatcherImpl;
  Matcher<int> m(impl);
  EXPECT_TRUE(m.Matches(4));
  EXPECT_FALSE(m.Matches(5));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [177/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanBeConstructedFromUndefinedVariable)
Definition at line 343 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Undefined::kInt;
  EXPECT_TRUE(m1.Matches(1));
  EXPECT_FALSE(m1.Matches(2));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::gmock_matchers_test::Undefined::kInt, and testing::internal::MatcherBase< T >::Matches().
TEST() [178/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanBeDefaultConstructed)
Definition at line 309 of file gmock-matchers_test.cc.
{
  Matcher<double> m;
}
TEST() [179/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanBeImplicitlyConstructedFromNULL)
Definition at line 329 of file gmock-matchers_test.cc.
{
  Matcher<int*> m1 = NULL;
  EXPECT_TRUE(m1.Matches(NULL));
  int n = 0;
  EXPECT_FALSE(m1.Matches(&n));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [180/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanBeImplicitlyConstructedFromValue)
Definition at line 322 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = 5;
  EXPECT_TRUE(m1.Matches(5));
  EXPECT_FALSE(m1.Matches(6));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [181/350]
testing::gmock_matchers_test::TEST (MatcherTest , CanDescribeItself)
Definition at line 367 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is an even number",
            Describe(Matcher<int>(new EvenMatcherImpl)));
}
References Describe(), and EXPECT_EQ.
TEST() [182/350]
testing::gmock_matchers_test::TEST (MatcherTest , IsCopyable)
Definition at line 353 of file gmock-matchers_test.cc.
{
  // Tests the copy constructor.
  Matcher<bool> m1 = Eq(false);
  EXPECT_TRUE(m1.Matches(false));
  EXPECT_FALSE(m1.Matches(true));
  // Tests the assignment operator.
  m1 = Eq(true);
  EXPECT_TRUE(m1.Matches(true));
  EXPECT_FALSE(m1.Matches(false));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [183/350]
testing::gmock_matchers_test::TEST (MatcherTest , MatchAndExplain)
Definition at line 373 of file gmock-matchers_test.cc.
{
  Matcher<int> m = GreaterThan(0);
  StringMatchResultListener listener1;
  EXPECT_TRUE(m.MatchAndExplain(42, &listener1));
  EXPECT_EQ("which is 42 more than 0", listener1.str());
  StringMatchResultListener listener2;
  EXPECT_FALSE(m.MatchAndExplain(-9, &listener2));
  EXPECT_EQ("which is 9 less than 0", listener2.str());
}
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, GreaterThan(), testing::internal::MatcherBase< T >::MatchAndExplain(), and testing::StringMatchResultListener::str().
TEST() [184/350]
testing::gmock_matchers_test::TEST (MatcherTupleTest , ExplainsMatchFailure)
Definition at line 6210 of file gmock-matchers_test.cc.
{
  stringstream ss1;
  ExplainMatchFailureTupleTo(make_tuple(Matcher<char>(Eq('a')), GreaterThan(5)),
                             make_tuple('a', 10), &ss1);
  EXPECT_EQ("", ss1.str());  // Successful match.
  stringstream ss2;
  ExplainMatchFailureTupleTo(make_tuple(GreaterThan(5), Matcher<char>(Eq('a'))),
                             make_tuple(2, 'b'), &ss2);
  EXPECT_EQ("  Expected arg #0: is > 5\n"
            "           Actual: 2, which is 3 less than 5\n"
            "  Expected arg #1: is equal to 'a' (97, 0x61)\n"
            "           Actual: 'b' (98, 0x62)\n",
            ss2.str());  // Failed match where both arguments need explanation.
  stringstream ss3;
  ExplainMatchFailureTupleTo(make_tuple(GreaterThan(5), Matcher<char>(Eq('a'))),
                             make_tuple(2, 'a'), &ss3);
  EXPECT_EQ("  Expected arg #0: is > 5\n"
            "           Actual: 2, which is 3 less than 5\n",
            ss3.str());  // Failed match where only one argument needs
                         // explanation.
}
References testing::Eq(), EXPECT_EQ, and GreaterThan().
TEST() [185/350]
testing::gmock_matchers_test::TEST (MatchesRegexTest , CanDescribeSelf)
Definition at line 1789 of file gmock-matchers_test.cc.
{
  Matcher<const std::string> m1 = MatchesRegex(std::string("Hi.*"));
  EXPECT_EQ("matches regular expression \"Hi.*\"", Describe(m1));
  Matcher<const char*> m2 = MatchesRegex(new RE("a.*"));
  EXPECT_EQ("matches regular expression \"a.*\"", Describe(m2));
#if GTEST_HAS_ABSL
  Matcher<const absl::string_view> m3 = MatchesRegex(new RE("0.*"));
  EXPECT_EQ("matches regular expression \"0.*\"", Describe(m3));
#endif  // GTEST_HAS_ABSL
}
References Describe(), EXPECT_EQ, and testing::MatchesRegex().
TEST() [186/350]
testing::gmock_matchers_test::TEST (MatchesRegexTest , MatchesStringMatchingGivenRegex)
Definition at line 1765 of file gmock-matchers_test.cc.
{
  const Matcher<const char*> m1 = MatchesRegex("a.*z");
  EXPECT_TRUE(m1.Matches("az"));
  EXPECT_TRUE(m1.Matches("abcz"));
  EXPECT_FALSE(m1.Matches(NULL));
  const Matcher<const std::string&> m2 = MatchesRegex(new RE("a.*z"));
  EXPECT_TRUE(m2.Matches("azbz"));
  EXPECT_FALSE(m2.Matches("az1"));
  EXPECT_FALSE(m2.Matches("1az"));
#if GTEST_HAS_ABSL
  const Matcher<const absl::string_view&> m3 = MatchesRegex("a.*z");
  EXPECT_TRUE(m3.Matches(absl::string_view("az")));
  EXPECT_TRUE(m3.Matches(absl::string_view("abcz")));
  EXPECT_FALSE(m3.Matches(absl::string_view("1az")));
  // Default-constructed absl::string_view should not match anything, in order
  // to distinguish it from an empty string.
  EXPECT_FALSE(m3.Matches(absl::string_view()));
  const Matcher<const absl::string_view&> m4 = MatchesRegex("");
  EXPECT_FALSE(m4.Matches(absl::string_view()));
#endif  // GTEST_HAS_ABSL
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::MatchesRegex().
TEST() [187/350]
testing::gmock_matchers_test::TEST (MatchesTest , IsSatisfiedByWhatMatchesTheMatcher)
Definition at line 2982 of file gmock-matchers_test.cc.
{
  EXPECT_TRUE(Matches(Ge(0))(1));
  EXPECT_FALSE(Matches(Eq('a'))('b'));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), and testing::Matches().
TEST() [188/350]
testing::gmock_matchers_test::TEST (MatchesTest , WorksOnByRefArguments)
Definition at line 2989 of file gmock-matchers_test.cc.
{
  int m = 0, n = 0;
  EXPECT_TRUE(Matches(AllOf(Ref(n), Eq(0)))(n));
  EXPECT_FALSE(Matches(Ref(m))(n));
}
References testing::AllOf(), testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::Matches(), and testing::Ref().
TEST() [189/350]
testing::gmock_matchers_test::TEST (MatchesTest , WorksWithMatcherOnNonRefType)
Definition at line 2997 of file gmock-matchers_test.cc.
{
  Matcher<int> eq5 = Eq(5);
  EXPECT_TRUE(Matches(eq5)(5));
  EXPECT_FALSE(Matches(eq5)(2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::Matches().
TEST() [190/350]
testing::gmock_matchers_test::TEST (MatchResultListenerTest , CanAccessUnderlyingStream)
Definition at line 241 of file gmock-matchers_test.cc.
{
  EXPECT_TRUE(DummyMatchResultListener().stream() == NULL);
  EXPECT_TRUE(StreamMatchResultListener(NULL).stream() == NULL);
  EXPECT_EQ(&std::cout, StreamMatchResultListener(&std::cout).stream());
}
References EXPECT_EQ, and EXPECT_TRUE.
TEST() [191/350]
testing::gmock_matchers_test::TEST (MatchResultListenerTest , IsInterestedWorks)
Definition at line 248 of file gmock-matchers_test.cc.
{
  EXPECT_TRUE(StringMatchResultListener().IsInterested());
  EXPECT_TRUE(StreamMatchResultListener(&std::cout).IsInterested());
  EXPECT_FALSE(DummyMatchResultListener().IsInterested());
  EXPECT_FALSE(StreamMatchResultListener(NULL).IsInterested());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [192/350]
testing::gmock_matchers_test::TEST (MatchResultListenerTest , StreamingWorks)
Definition at line 225 of file gmock-matchers_test.cc.
{
  StringMatchResultListener listener;
  listener << "hi" << 5;
  EXPECT_EQ("hi5", listener.str());
  listener.Clear();
  EXPECT_EQ("", listener.str());
  listener << 42;
  EXPECT_EQ("42", listener.str());
  // Streaming shouldn't crash when the underlying ostream is NULL.
  DummyMatchResultListener dummy;
  dummy << "hi" << 5;
}
References testing::StringMatchResultListener::Clear(), EXPECT_EQ, and testing::StringMatchResultListener::str().
TEST() [193/350]
testing::gmock_matchers_test::TEST (MonotonicMatcherTest , IsPrintable)
Definition at line 219 of file gmock-matchers_test.cc.
{
  stringstream ss;
  ss << GreaterThan(5);
  EXPECT_EQ("is > 5", ss.str());
}
References EXPECT_EQ, and GreaterThan().
TEST() [194/350]
testing::gmock_matchers_test::TEST (NanSensitiveDoubleEqTest , CanDescribeSelfWithNaNs)
Definition at line 2381 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<double, double>&> m = NanSensitiveDoubleEq();
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::NanSensitiveDoubleEq().
TEST() [195/350]
testing::gmock_matchers_test::TEST (NanSensitiveDoubleEqTest , MatchesEqualArgumentsWithNaN)
Definition at line 2369 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<double, double> Tpl;
  Matcher<const Tpl&> m = NanSensitiveDoubleEq();
  EXPECT_TRUE(m.Matches(Tpl(1.0f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(std::numeric_limits<double>::quiet_NaN(),
                            std::numeric_limits<double>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(1.1f, 1.0f)));
  EXPECT_FALSE(m.Matches(Tpl(1.0f, std::numeric_limits<double>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(std::numeric_limits<double>::quiet_NaN(), 1.0f)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveDoubleEq().
TEST() [196/350]
testing::gmock_matchers_test::TEST (NanSensitiveDoubleNearTest , CanDescribeSelfWithNaNs)
Definition at line 2454 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<double, double>&> m =
      NanSensitiveDoubleNear(0.5f);
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::NanSensitiveDoubleNear().
TEST() [197/350]
testing::gmock_matchers_test::TEST (NanSensitiveDoubleNearTest , MatchesNearbyArgumentsWithNaN)
Definition at line 2441 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<double, double> Tpl;
  Matcher<const Tpl&> m = NanSensitiveDoubleNear(0.5f);
  EXPECT_TRUE(m.Matches(Tpl(1.0f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(1.1f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(std::numeric_limits<double>::quiet_NaN(),
                            std::numeric_limits<double>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(1.6f, 1.0f)));
  EXPECT_FALSE(m.Matches(Tpl(1.0f, std::numeric_limits<double>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(std::numeric_limits<double>::quiet_NaN(), 1.0f)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveDoubleNear().
TEST() [198/350]
testing::gmock_matchers_test::TEST (NanSensitiveFloatEqTest , CanDescribeSelfWithNaNs)
Definition at line 2346 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<float, float>&> m = NanSensitiveFloatEq();
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::NanSensitiveFloatEq().
TEST() [199/350]
testing::gmock_matchers_test::TEST (NanSensitiveFloatEqTest , MatchesEqualArgumentsWithNaN)
Definition at line 2334 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<float, float> Tpl;
  Matcher<const Tpl&> m = NanSensitiveFloatEq();
  EXPECT_TRUE(m.Matches(Tpl(1.0f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(std::numeric_limits<float>::quiet_NaN(),
                            std::numeric_limits<float>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(1.1f, 1.0f)));
  EXPECT_FALSE(m.Matches(Tpl(1.0f, std::numeric_limits<float>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(std::numeric_limits<float>::quiet_NaN(), 1.0f)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveFloatEq().
TEST() [200/350]
testing::gmock_matchers_test::TEST (NanSensitiveFloatNearTest , CanDescribeSelfWithNaNs)
Definition at line 2417 of file gmock-matchers_test.cc.
{
  Matcher<const ::testing::tuple<float, float>&> m =
      NanSensitiveFloatNear(0.5f);
  EXPECT_EQ("are an almost-equal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::NanSensitiveFloatNear().
TEST() [201/350]
testing::gmock_matchers_test::TEST (NanSensitiveFloatNearTest , MatchesNearbyArgumentsWithNaN)
Definition at line 2404 of file gmock-matchers_test.cc.
{
  typedef ::testing::tuple<float, float> Tpl;
  Matcher<const Tpl&> m = NanSensitiveFloatNear(0.5f);
  EXPECT_TRUE(m.Matches(Tpl(1.0f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(1.1f, 1.0f)));
  EXPECT_TRUE(m.Matches(Tpl(std::numeric_limits<float>::quiet_NaN(),
                            std::numeric_limits<float>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(1.6f, 1.0f)));
  EXPECT_FALSE(m.Matches(Tpl(1.0f, std::numeric_limits<float>::quiet_NaN())));
  EXPECT_FALSE(m.Matches(Tpl(std::numeric_limits<float>::quiet_NaN(), 1.0f)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveFloatNear().
TEST() [202/350]
testing::gmock_matchers_test::TEST (Ne2Test , CanDescribeSelf)
Definition at line 2311 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Ne();
  EXPECT_EQ("are an unequal pair", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Ne().
TEST() [203/350]
testing::gmock_matchers_test::TEST (Ne2Test , MatchesUnequalArguments)
Definition at line 2303 of file gmock-matchers_test.cc.
{
  Matcher<const Tuple2&> m = Ne();
  EXPECT_TRUE(m.Matches(Tuple2(5L, 6)));
  EXPECT_TRUE(m.Matches(Tuple2(5L, 4)));
  EXPECT_FALSE(m.Matches(Tuple2(5L, 5)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ne().
TEST() [204/350]
testing::gmock_matchers_test::TEST (NeTest , CanDescribeSelf)
Definition at line 1150 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Ne(5);
  EXPECT_EQ("isn't equal to 5", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Ne().
TEST() [205/350]
testing::gmock_matchers_test::TEST (NeTest , ImplementsNotEqual)
Definition at line 1142 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Ne(0);
  EXPECT_TRUE(m1.Matches(1));
  EXPECT_TRUE(m1.Matches(-1));
  EXPECT_FALSE(m1.Matches(0));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ne().
TEST() [206/350]
testing::gmock_matchers_test::TEST (NotNullTest , CanDescribeSelf)
Definition at line 1260 of file gmock-matchers_test.cc.
{
  Matcher<int*> m = NotNull();
  EXPECT_EQ("isn't NULL", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::NotNull().
TEST() [207/350]
testing::gmock_matchers_test::TEST (NotNullTest , LinkedPtr)
Definition at line 1232 of file gmock-matchers_test.cc.
{
  const Matcher<linked_ptr<int> > m = NotNull();
  const linked_ptr<int> null_p;
  const linked_ptr<int> non_null_p(new int);
  EXPECT_FALSE(m.Matches(null_p));
  EXPECT_TRUE(m.Matches(non_null_p));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NotNull().
TEST() [208/350]
testing::gmock_matchers_test::TEST (NotNullTest , MatchesNonNullPointer)
Definition at line 1219 of file gmock-matchers_test.cc.
{
  Matcher<int*> m1 = NotNull();
  int* p1 = NULL;
  int n = 0;
  EXPECT_FALSE(m1.Matches(p1));
  EXPECT_TRUE(m1.Matches(&n));
  Matcher<const char*> m2 = NotNull();
  const char* p2 = NULL;
  EXPECT_FALSE(m2.Matches(p2));
  EXPECT_TRUE(m2.Matches("hi"));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NotNull().
TEST() [209/350]
testing::gmock_matchers_test::TEST (NotNullTest , ReferenceToConstLinkedPtr)
Definition at line 1241 of file gmock-matchers_test.cc.
{
  const Matcher<const linked_ptr<double>&> m = NotNull();
  const linked_ptr<double> null_p;
  const linked_ptr<double> non_null_p(new double);
  EXPECT_FALSE(m.Matches(null_p));
  EXPECT_TRUE(m.Matches(non_null_p));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NotNull().
TEST() [210/350]
testing::gmock_matchers_test::TEST (NotTest , CanDescribeSelf)
Definition at line 2469 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Not(Eq(5));
  EXPECT_EQ("isn't equal to 5", Describe(m));
}
References Describe(), testing::Eq(), EXPECT_EQ, and testing::Not().
TEST() [211/350]
testing::gmock_matchers_test::TEST (NotTest , NegatesMatcher)
Definition at line 2461 of file gmock-matchers_test.cc.
{
  Matcher<int> m;
  m = Not(Eq(2));
  EXPECT_TRUE(m.Matches(3));
  EXPECT_FALSE(m.Matches(2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Not().
TEST() [212/350]
testing::gmock_matchers_test::TEST (NotTest , NotMatcherSafelyCastsMonomorphicMatchers)
Definition at line 2475 of file gmock-matchers_test.cc.
{
  // greater_than_5 is a monomorphic matcher.
  Matcher<int> greater_than_5 = Gt(5);
  Matcher<const int&> m = Not(greater_than_5);
  Matcher<int&> m2 = Not(greater_than_5);
  Matcher<int&> m3 = Not(m);
}
References testing::Gt(), and testing::Not().
TEST() [213/350]
testing::gmock_matchers_test::TEST (OptionalTest , DescribesSelf)
Definition at line 6590 of file gmock-matchers_test.cc.
{
  const Matcher<SampleOptionalInt> m = Optional(Eq(1));
  EXPECT_EQ("value is equal to 1", Describe(m));
}
References Describe(), testing::Eq(), EXPECT_EQ, and testing::Optional().
TEST() [214/350]
testing::gmock_matchers_test::TEST (OptionalTest , DoesNotMatchNullopt)
Definition at line 6611 of file gmock-matchers_test.cc.
{
  const Matcher<SampleOptionalInt> m = Optional(1);
  SampleOptionalInt empty;
  EXPECT_FALSE(m.Matches(empty));
}
References EXPECT_FALSE, testing::internal::MatcherBase< T >::Matches(), and testing::Optional().
TEST() [215/350]
testing::gmock_matchers_test::TEST (OptionalTest , ExplainsSelf)
Definition at line 6595 of file gmock-matchers_test.cc.
{
  const Matcher<SampleOptionalInt> m = Optional(Eq(1));
  EXPECT_EQ("whose value 1 matches", Explain(m, SampleOptionalInt(1)));
  EXPECT_EQ("whose value 2 doesn't match", Explain(m, SampleOptionalInt(2)));
}
References testing::Eq(), EXPECT_EQ, Explain(), and testing::Optional().
TEST() [216/350]
testing::gmock_matchers_test::TEST (OptionalTest , MatchesNonEmptyOptional)
Definition at line 6601 of file gmock-matchers_test.cc.
{
  const Matcher<SampleOptionalInt> m1 = Optional(1);
  const Matcher<SampleOptionalInt> m2 = Optional(Eq(2));
  const Matcher<SampleOptionalInt> m3 = Optional(Lt(3));
  SampleOptionalInt opt(1);
  EXPECT_TRUE(m1.Matches(opt));
  EXPECT_FALSE(m2.Matches(opt));
  EXPECT_TRUE(m3.Matches(opt));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::Lt(), testing::internal::MatcherBase< T >::Matches(), and testing::Optional().
TEST() [217/350]
testing::gmock_matchers_test::TEST (PairTest , CanDescribeSelf)
Definition at line 1597 of file gmock-matchers_test.cc.
{
  Matcher<const pair<std::string, int>&> m1 = Pair("foo", 42);
  EXPECT_EQ("has a first field that is equal to \"foo\""
            ", and has a second field that is equal to 42",
            Describe(m1));
  EXPECT_EQ("has a first field that isn't equal to \"foo\""
            ", or has a second field that isn't equal to 42",
            DescribeNegation(m1));
  // Double and triple negation (1 or 2 times not and description of negation).
  Matcher<const pair<int, int>&> m2 = Not(Pair(Not(13), 42));
  EXPECT_EQ("has a first field that isn't equal to 13"
            ", and has a second field that is equal to 42",
            DescribeNegation(m2));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Not(), and testing::Pair().
TEST() [218/350]
testing::gmock_matchers_test::TEST (PairTest , CanExplainMatchResultTo)
Definition at line 1612 of file gmock-matchers_test.cc.
{
  // If neither field matches, Pair() should explain about the first
  // field.
  const Matcher<pair<int, int> > m = Pair(GreaterThan(0), GreaterThan(0));
  EXPECT_EQ("whose first field does not match, which is 1 less than 0",
            Explain(m, make_pair(-1, -2)));
  // If the first field matches but the second doesn't, Pair() should
  // explain about the second field.
  EXPECT_EQ("whose second field does not match, which is 2 less than 0",
            Explain(m, make_pair(1, -2)));
  // If the first field doesn't match but the second does, Pair()
  // should explain about the first field.
  EXPECT_EQ("whose first field does not match, which is 1 less than 0",
            Explain(m, make_pair(-1, 2)));
  // If both fields match, Pair() should explain about them both.
  EXPECT_EQ("whose both fields match, where the first field is a value "
            "which is 1 more than 0, and the second field is a value "
            "which is 2 more than 0",
            Explain(m, make_pair(1, 2)));
  // If only the first match has an explanation, only this explanation should
  // be printed.
  const Matcher<pair<int, int> > explain_first = Pair(GreaterThan(0), 0);
  EXPECT_EQ("whose both fields match, where the first field is a value "
            "which is 1 more than 0",
            Explain(explain_first, make_pair(1, 0)));
  // If only the second match has an explanation, only this explanation should
  // be printed.
  const Matcher<pair<int, int> > explain_second = Pair(0, GreaterThan(0));
  EXPECT_EQ("whose both fields match, where the second field is a value "
            "which is 1 more than 0",
            Explain(explain_second, make_pair(0, 1)));
}
References EXPECT_EQ, Explain(), GreaterThan(), and testing::Pair().
TEST() [219/350]
testing::gmock_matchers_test::TEST (PairTest , InsideContainsUsingMap)
Definition at line 1680 of file gmock-matchers_test.cc.
{
  map<int, char> container;
  container.insert(make_pair(1, 'a'));
  container.insert(make_pair(2, 'b'));
  container.insert(make_pair(4, 'c'));
  EXPECT_THAT(container, Contains(Pair(1, 'a')));
  EXPECT_THAT(container, Contains(Pair(1, _)));
  EXPECT_THAT(container, Contains(Pair(_, 'a')));
  EXPECT_THAT(container, Not(Contains(Pair(3, _))));
}
References testing::_, testing::Contains(), EXPECT_THAT, testing::Not(), and testing::Pair().
TEST() [220/350]
testing::gmock_matchers_test::TEST (PairTest , MatchesCorrectly)
Definition at line 1650 of file gmock-matchers_test.cc.
{
  pair<int, std::string> p(25, "foo");
  // Both fields match.
  EXPECT_THAT(p, Pair(25, "foo"));
  EXPECT_THAT(p, Pair(Ge(20), HasSubstr("o")));
  // 'first' doesnt' match, but 'second' matches.
  EXPECT_THAT(p, Not(Pair(42, "foo")));
  EXPECT_THAT(p, Not(Pair(Lt(25), "foo")));
  // 'first' matches, but 'second' doesn't match.
  EXPECT_THAT(p, Not(Pair(25, "bar")));
  EXPECT_THAT(p, Not(Pair(25, Not("foo"))));
  // Neither field matches.
  EXPECT_THAT(p, Not(Pair(13, "bar")));
  EXPECT_THAT(p, Not(Pair(Lt(13), HasSubstr("a"))));
}
References EXPECT_THAT, testing::Ge(), testing::HasSubstr(), testing::Lt(), testing::Not(), and testing::Pair().
TEST() [221/350]
testing::gmock_matchers_test::TEST (PairTest , SafelyCastsInnerMatchers)
Definition at line 1670 of file gmock-matchers_test.cc.
{
  Matcher<int> is_positive = Gt(0);
  Matcher<int> is_negative = Lt(0);
  pair<char, bool> p('a', true);
  EXPECT_THAT(p, Pair(is_positive, _));
  EXPECT_THAT(p, Not(Pair(is_negative, _)));
  EXPECT_THAT(p, Pair(_, is_positive));
  EXPECT_THAT(p, Not(Pair(_, is_negative)));
}
References testing::_, EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), and testing::Pair().
TEST() [222/350]
testing::gmock_matchers_test::TEST (PairTest , Typing)
Definition at line 1587 of file gmock-matchers_test.cc.
                       {
  // Test verifies the following type conversions can be compiled.
  Matcher<const pair<const char*, int>&> m1 = Pair("foo", 42);
  Matcher<const pair<const char*, int> > m2 = Pair("foo", 42);
  Matcher<pair<const char*, int> > m3 = Pair("foo", 42);
  Matcher<pair<int, const std::string> > m4 = Pair(25, "42");
  Matcher<pair<const std::string, int> > m5 = Pair("25", 42);
}
References testing::Pair().
TEST() [223/350]
testing::gmock_matchers_test::TEST (PointeeTest , AlwaysExplainsPointee)
Definition at line 3867 of file gmock-matchers_test.cc.
{
  const Matcher<int*> m = Pointee(0);
  int n = 42;
  EXPECT_EQ("which points to 42" + OfType("int"), Explain(m, &n));
}
References EXPECT_EQ, Explain(), OfType(), and testing::Pointee().
TEST() [224/350]
testing::gmock_matchers_test::TEST (PointeeTest , CanDescribeSelf)
Definition at line 3849 of file gmock-matchers_test.cc.
{
  const Matcher<int*> m = Pointee(Gt(3));
  EXPECT_EQ("points to a value that is > 3", Describe(m));
  EXPECT_EQ("does not point to a value that is > 3",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Gt(), and testing::Pointee().
TEST() [225/350]
testing::gmock_matchers_test::TEST (PointeeTest , CanExplainMatchResult)
Definition at line 3856 of file gmock-matchers_test.cc.
{
  const Matcher<const std::string*> m = Pointee(StartsWith("Hi"));
  EXPECT_EQ("", Explain(m, static_cast<const std::string*>(NULL)));
  const Matcher<long*> m2 = Pointee(GreaterThan(1));  // NOLINT
  long n = 3;  // NOLINT
  EXPECT_EQ("which points to 3" + OfType("long") + ", which is 2 more than 1",
            Explain(m2, &n));
}
References EXPECT_EQ, Explain(), GreaterThan(), OfType(), testing::Pointee(), and testing::StartsWith().
TEST() [226/350]
testing::gmock_matchers_test::TEST (PointeeTest , MatchesAgainstAValue)
Definition at line 3839 of file gmock-matchers_test.cc.
{
  const Matcher<int*> m = Pointee(5);
  int n = 5;
  EXPECT_TRUE(m.Matches(&n));
  n = -1;
  EXPECT_FALSE(m.Matches(&n));
  EXPECT_FALSE(m.Matches(NULL));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [227/350]
testing::gmock_matchers_test::TEST (PointeeTest , NeverMatchesNull)
Definition at line 3833 of file gmock-matchers_test.cc.
{
  const Matcher<const char*> m = Pointee(_);
  EXPECT_FALSE(m.Matches(NULL));
}
References testing::_, EXPECT_FALSE, testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [228/350]
testing::gmock_matchers_test::TEST (PointeeTest , RawPointer)
Definition at line 3661 of file gmock-matchers_test.cc.
{
  const Matcher<int*> m = Pointee(Ge(0));
  int n = 1;
  EXPECT_TRUE(m.Matches(&n));
  n = -1;
  EXPECT_FALSE(m.Matches(&n));
  EXPECT_FALSE(m.Matches(NULL));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [229/350]
testing::gmock_matchers_test::TEST (PointeeTest , RawPointerToConst)
Definition at line 3671 of file gmock-matchers_test.cc.
{
  const Matcher<const double*> m = Pointee(Ge(0));
  double x = 1;
  EXPECT_TRUE(m.Matches(&x));
  x = -1;
  EXPECT_FALSE(m.Matches(&x));
  EXPECT_FALSE(m.Matches(NULL));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [230/350]
testing::gmock_matchers_test::TEST (PointeeTest , ReferenceToConstRawPointer)
Definition at line 3681 of file gmock-matchers_test.cc.
{
  const Matcher<int* const &> m = Pointee(Ge(0));
  int n = 1;
  EXPECT_TRUE(m.Matches(&n));
  n = -1;
  EXPECT_FALSE(m.Matches(&n));
  EXPECT_FALSE(m.Matches(NULL));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [231/350]
testing::gmock_matchers_test::TEST (PointeeTest , ReferenceToNonConstRawPointer)
Definition at line 3691 of file gmock-matchers_test.cc.
{
  const Matcher<double* &> m = Pointee(Ge(0));
  double x = 1.0;
  double* p = &x;
  EXPECT_TRUE(m.Matches(p));
  x = -1;
  EXPECT_FALSE(m.Matches(p));
  p = NULL;
  EXPECT_FALSE(m.Matches(p));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [232/350]
testing::gmock_matchers_test::TEST (PointeeTest , WorksWithConstPropagatingPointers)
Definition at line 3821 of file gmock-matchers_test.cc.
{
  const Matcher< ConstPropagatingPtr<int> > m = Pointee(Lt(5));
  int three = 3;
  const ConstPropagatingPtr<int> co(&three);
  ConstPropagatingPtr<int> o(&three);
  EXPECT_TRUE(m.Matches(o));
  EXPECT_TRUE(m.Matches(co));
  *o = 6;
  EXPECT_FALSE(m.Matches(o));
  EXPECT_FALSE(m.Matches(ConstPropagatingPtr<int>()));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Lt(), testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
TEST() [233/350]
testing::gmock_matchers_test::TEST (PointwiseTest , AcceptsCorrectContent)
Definition at line 6437 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {2, 4, 6};
  EXPECT_THAT(lhs, Pointwise(IsHalfOf(), rhs));
  EXPECT_EQ("", Explain(Pointwise(IsHalfOf(), rhs), lhs));
}
References EXPECT_EQ, EXPECT_THAT, Explain(), IsHalfOf(), and testing::Pointwise().
TEST() [234/350]
testing::gmock_matchers_test::TEST (PointwiseTest , AllowsMonomorphicInnerMatcher)
Definition at line 6444 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {2, 4, 6};
  const Matcher<tuple<const double&, const int&> > m1 = IsHalfOf();
  EXPECT_THAT(lhs, Pointwise(m1, rhs));
  EXPECT_EQ("", Explain(Pointwise(m1, rhs), lhs));
  // This type works as a tuple<const double&, const int&> can be
  // implicitly cast to tuple<double, int>.
  const Matcher<tuple<double, int> > m2 = IsHalfOf();
  EXPECT_THAT(lhs, Pointwise(m2, rhs));
  EXPECT_EQ("", Explain(Pointwise(m2, rhs), lhs));
}
References EXPECT_EQ, EXPECT_THAT, Explain(), IsHalfOf(), and testing::Pointwise().
TEST() [235/350]
testing::gmock_matchers_test::TEST (PointwiseTest , DescribesSelf)
Definition at line 6348 of file gmock-matchers_test.cc.
{
  vector<int> rhs;
  rhs.push_back(1);
  rhs.push_back(2);
  rhs.push_back(3);
  const Matcher<const vector<int>&> m = Pointwise(IsHalfOf(), rhs);
  EXPECT_EQ("contains 3 values, where each value and its corresponding value "
            "in { 1, 2, 3 } are a pair where the first is half of the second",
            Describe(m));
  EXPECT_EQ("doesn't contain exactly 3 values, or contains a value x at some "
            "index i where x and the i-th value of { 1, 2, 3 } are a pair "
            "where the first isn't half of the second",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, IsHalfOf(), and testing::Pointwise().
TEST() [236/350]
testing::gmock_matchers_test::TEST (PointwiseTest , MakesCopyOfRhs)
Definition at line 6363 of file gmock-matchers_test.cc.
{
  list<signed char> rhs;
  rhs.push_back(2);
  rhs.push_back(4);
  int lhs[] = {1, 2};
  const Matcher<const int (&)[2]> m = Pointwise(IsHalfOf(), rhs);
  EXPECT_THAT(lhs, m);
  // Changing rhs now shouldn't affect m, which made a copy of rhs.
  rhs.push_back(6);
  EXPECT_THAT(lhs, m);
}
References EXPECT_THAT, IsHalfOf(), and testing::Pointwise().
TEST() [237/350]
testing::gmock_matchers_test::TEST (PointwiseTest , RejectsWrongContent)
Definition at line 6428 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {2, 6, 4};
  EXPECT_THAT(lhs, Not(Pointwise(IsHalfOf(), rhs)));
  EXPECT_EQ("where the value pair (2, 6) at index #1 don't match, "
            "where the second/2 is 3",
            Explain(Pointwise(IsHalfOf(), rhs), lhs));
}
References EXPECT_EQ, EXPECT_THAT, Explain(), IsHalfOf(), testing::Not(), and testing::Pointwise().
TEST() [238/350]
testing::gmock_matchers_test::TEST (PointwiseTest , RejectsWrongSize)
Definition at line 6417 of file gmock-matchers_test.cc.
{
  const double lhs[2] = {1, 2};
  const int rhs[1] = {0};
  EXPECT_THAT(lhs, Not(Pointwise(Gt(), rhs)));
  EXPECT_EQ("which contains 2 values",
            Explain(Pointwise(Gt(), rhs), lhs));
  const int rhs2[3] = {0, 1, 2};
  EXPECT_THAT(lhs, Not(Pointwise(Gt(), rhs2)));
}
References EXPECT_EQ, EXPECT_THAT, Explain(), testing::Gt(), testing::Not(), and testing::Pointwise().
TEST() [239/350]
testing::gmock_matchers_test::TEST (PointwiseTest , WorksForLhsNativeArray)
Definition at line 6377 of file gmock-matchers_test.cc.
{
  const int lhs[] = {1, 2, 3};
  vector<int> rhs;
  rhs.push_back(2);
  rhs.push_back(4);
  rhs.push_back(6);
  EXPECT_THAT(lhs, Pointwise(Lt(), rhs));
  EXPECT_THAT(lhs, Not(Pointwise(Gt(), rhs)));
}
References EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), and testing::Pointwise().
TEST() [240/350]
testing::gmock_matchers_test::TEST (PointwiseTest , WorksForRhsNativeArray)
Definition at line 6387 of file gmock-matchers_test.cc.
{
  const int rhs[] = {1, 2, 3};
  vector<int> lhs;
  lhs.push_back(2);
  lhs.push_back(4);
  lhs.push_back(6);
  EXPECT_THAT(lhs, Pointwise(Gt(), rhs));
  EXPECT_THAT(lhs, Not(Pointwise(Lt(), rhs)));
}
References EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), and testing::Pointwise().
TEST() [241/350]
testing::gmock_matchers_test::TEST (PointwiseTest , WorksForVectorOfBool)
Definition at line 6398 of file gmock-matchers_test.cc.
{
  vector<bool> rhs(3, false);
  rhs[1] = true;
  vector<bool> lhs = rhs;
  EXPECT_THAT(lhs, Pointwise(Eq(), rhs));
  rhs[0] = true;
  EXPECT_THAT(lhs, Not(Pointwise(Eq(), rhs)));
}
References testing::Eq(), EXPECT_THAT, testing::Not(), and testing::Pointwise().
TEST() [242/350]
testing::gmock_matchers_test::TEST (PolymorphicMatcherTest , CanAccessImpl)
Definition at line 6204 of file gmock-matchers_test.cc.
{
  const PolymorphicMatcher<DivisibleByImpl> m(DivisibleByImpl(42));
  const DivisibleByImpl& impl = m.impl();
  EXPECT_EQ(42, impl.divider());
}
References testing::gmock_matchers_test::DivisibleByImpl::divider(), EXPECT_EQ, and testing::PolymorphicMatcher< Impl >::impl().
TEST() [243/350]
testing::gmock_matchers_test::TEST (PolymorphicMatcherTest , CanAccessMutableImpl)
Definition at line 6194 of file gmock-matchers_test.cc.
{
  PolymorphicMatcher<DivisibleByImpl> m(DivisibleByImpl(42));
  DivisibleByImpl& impl = m.mutable_impl();
  EXPECT_EQ(42, impl.divider());
  impl.set_divider(0);
  EXPECT_EQ(0, m.mutable_impl().divider());
}
References testing::gmock_matchers_test::DivisibleByImpl::divider(), EXPECT_EQ, testing::PolymorphicMatcher< Impl >::mutable_impl(), and testing::gmock_matchers_test::DivisibleByImpl::set_divider().
TEST() [244/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , CanDescribeSelf)
Definition at line 4395 of file gmock-matchers_test.cc.
{
  Matcher<const AClass*> m = Property(&AClass::n, Ge(0));
  EXPECT_EQ("is an object whose given property is >= 0", Describe(m));
  EXPECT_EQ("is an object whose given property isn't >= 0",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Ge(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [245/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , CanDescribeSelfWithPropertyDescription)
Definition at line 4403 of file gmock-matchers_test.cc.
{
  Matcher<const AClass*> m = Property("fancy_name", &AClass::n, Ge(0));
  EXPECT_EQ("is an object whose property `fancy_name` is >= 0", Describe(m));
  EXPECT_EQ("is an object whose property `fancy_name` isn't >= 0",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Ge(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [246/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , CanExplainMatchResult)
Definition at line 4412 of file gmock-matchers_test.cc.
{
  Matcher<const AClass*> m = Property(&AClass::n, Ge(0));
  AClass a;
  a.set_n(1);
  EXPECT_EQ("", Explain(m, static_cast<const AClass*>(NULL)));
  EXPECT_EQ(
      "which points to an object whose given property is 1" + OfType("int"),
      Explain(m, &a));
  m = Property(&AClass::n, GreaterThan(0));
  EXPECT_EQ("which points to an object whose given property is 1" +
            OfType("int") + ", which is 1 more than 0",
            Explain(m, &a));
}
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), testing::gmock_matchers_test::AClass::n(), OfType(), and testing::Property().
TEST() [247/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , CanExplainMatchResultWithPropertyName)
Definition at line 4428 of file gmock-matchers_test.cc.
{
  Matcher<const AClass*> m = Property("fancy_name", &AClass::n, Ge(0));
  AClass a;
  a.set_n(1);
  EXPECT_EQ("", Explain(m, static_cast<const AClass*>(NULL)));
  EXPECT_EQ("which points to an object whose property `fancy_name` is 1" +
                OfType("int"),
            Explain(m, &a));
  m = Property("fancy_name", &AClass::n, GreaterThan(0));
  EXPECT_EQ("which points to an object whose property `fancy_name` is 1" +
                OfType("int") + ", which is 1 more than 0",
            Explain(m, &a));
}
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), testing::gmock_matchers_test::AClass::n(), OfType(), and testing::Property().
TEST() [248/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , WorksForArgumentOfSubType)
Definition at line 4381 of file gmock-matchers_test.cc.
{
  // The matcher expects a DerivedClass, but inside the Property() we
  // say AClass.
  Matcher<const DerivedClass*> m = Property(&AClass::n, Ge(0));
  DerivedClass d;
  d.set_n(1);
  EXPECT_TRUE(m.Matches(&d));
  d.set_n(-1);
  EXPECT_FALSE(m.Matches(&d));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::AClass::n(), testing::Property(), and testing::gmock_matchers_test::AClass::set_n().
TEST() [249/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , WorksForPointerToConst)
Definition at line 4337 of file gmock-matchers_test.cc.
{
  Matcher<const AClass*> m = Property(&AClass::n, Ge(0));
  AClass a;
  a.set_n(1);
  EXPECT_TRUE(m.Matches(&a));
  a.set_n(-1);
  EXPECT_FALSE(m.Matches(&a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [250/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , WorksForPointerToNonConst)
Definition at line 4349 of file gmock-matchers_test.cc.
{
  Matcher<AClass*> m = Property(&AClass::s, StartsWith("hi"));
  AClass a;
  a.set_s("hill");
  EXPECT_TRUE(m.Matches(&a));
  a.set_s("hole");
  EXPECT_FALSE(m.Matches(&a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Property(), testing::gmock_matchers_test::AClass::s(), and testing::StartsWith().
TEST() [251/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , WorksForReferenceToConstPointer)
Definition at line 4362 of file gmock-matchers_test.cc.
{
  Matcher<AClass* const&> m = Property(&AClass::s, StartsWith("hi"));
  AClass a;
  a.set_s("hill");
  EXPECT_TRUE(m.Matches(&a));
  a.set_s("hole");
  EXPECT_FALSE(m.Matches(&a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Property(), testing::gmock_matchers_test::AClass::s(), and testing::StartsWith().
TEST() [252/350]
testing::gmock_matchers_test::TEST (PropertyForPointerTest , WorksForReferenceToNonConstProperty)
Definition at line 4374 of file gmock-matchers_test.cc.
{
  Matcher<const AClass*> m = Property(&AClass::x, _);
  EXPECT_FALSE(m.Matches(NULL));
}
References testing::_, EXPECT_FALSE, testing::internal::MatcherBase< T >::Matches(), testing::Property(), and testing::gmock_matchers_test::AClass::x().
TEST() [253/350]
testing::gmock_matchers_test::TEST (PropertyTest , CanDescribeSelf)
Definition at line 4293 of file gmock-matchers_test.cc.
{
  Matcher<const AClass&> m = Property(&AClass::n, Ge(0));
  EXPECT_EQ("is an object whose given property is >= 0", Describe(m));
  EXPECT_EQ("is an object whose given property isn't >= 0",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Ge(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [254/350]
testing::gmock_matchers_test::TEST (PropertyTest , CanDescribeSelfWithPropertyName)
Definition at line 4301 of file gmock-matchers_test.cc.
{
  Matcher<const AClass&> m = Property("fancy_name", &AClass::n, Ge(0));
  EXPECT_EQ("is an object whose property `fancy_name` is >= 0", Describe(m));
  EXPECT_EQ("is an object whose property `fancy_name` isn't >= 0",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, testing::Ge(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [255/350]
testing::gmock_matchers_test::TEST (PropertyTest , CanExplainMatchResult)
Definition at line 4310 of file gmock-matchers_test.cc.
{
  Matcher<const AClass&> m = Property(&AClass::n, Ge(0));
  AClass a;
  a.set_n(1);
  EXPECT_EQ("whose given property is 1" + OfType("int"), Explain(m, a));
  m = Property(&AClass::n, GreaterThan(0));
  EXPECT_EQ(
      "whose given property is 1" + OfType("int") + ", which is 1 more than 0",
      Explain(m, a));
}
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), testing::gmock_matchers_test::AClass::n(), OfType(), and testing::Property().
TEST() [256/350]
testing::gmock_matchers_test::TEST (PropertyTest , CanExplainMatchResultWithPropertyName)
Definition at line 4323 of file gmock-matchers_test.cc.
{
  Matcher<const AClass&> m = Property("fancy_name", &AClass::n, Ge(0));
  AClass a;
  a.set_n(1);
  EXPECT_EQ("whose property `fancy_name` is 1" + OfType("int"), Explain(m, a));
  m = Property("fancy_name", &AClass::n, GreaterThan(0));
  EXPECT_EQ("whose property `fancy_name` is 1" + OfType("int") +
                ", which is 1 more than 0",
            Explain(m, a));
}
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), testing::gmock_matchers_test::AClass::n(), OfType(), and testing::Property().
TEST() [257/350]
testing::gmock_matchers_test::TEST (PropertyTest , WorksForArgumentOfSubType)
Definition at line 4261 of file gmock-matchers_test.cc.
{
  // The matcher expects a DerivedClass, but inside the Property() we
  // say AClass.
  Matcher<const DerivedClass&> m = Property(&AClass::n, Ge(0));
  DerivedClass d;
  d.set_n(1);
  EXPECT_TRUE(m.Matches(d));
  d.set_n(-1);
  EXPECT_FALSE(m.Matches(d));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::AClass::n(), testing::Property(), and testing::gmock_matchers_test::AClass::set_n().
TEST() [258/350]
testing::gmock_matchers_test::TEST (PropertyTest , WorksForByValueArgument)
Definition at line 4248 of file gmock-matchers_test.cc.
{
  Matcher<AClass> m = Property(&AClass::s, StartsWith("hi"));
  AClass a;
  a.set_s("hill");
  EXPECT_TRUE(m.Matches(a));
  a.set_s("hole");
  EXPECT_FALSE(m.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Property(), testing::gmock_matchers_test::AClass::s(), and testing::StartsWith().
TEST() [259/350]
testing::gmock_matchers_test::TEST (PropertyTest , WorksForCompatibleMatcherType)
Definition at line 4276 of file gmock-matchers_test.cc.
{
  // n() returns an int but the inner matcher expects a signed char.
  Matcher<const AClass&> m = Property(&AClass::n,
                                      Matcher<signed char>(Ge(0)));
  Matcher<const AClass&> m_with_name =
      Property("n", &AClass::n, Matcher<signed char>(Ge(0)));
  AClass a;
  EXPECT_TRUE(m.Matches(a));
  EXPECT_TRUE(m_with_name.Matches(a));
  a.set_n(-1);
  EXPECT_FALSE(m.Matches(a));
  EXPECT_FALSE(m_with_name.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [260/350]
testing::gmock_matchers_test::TEST (PropertyTest , WorksForNonReferenceProperty)
Definition at line 4187 of file gmock-matchers_test.cc.
{
  Matcher<const AClass&> m = Property(&AClass::n, Ge(0));
  Matcher<const AClass&> m_with_name = Property("n", &AClass::n, Ge(0));
  AClass a;
  a.set_n(1);
  EXPECT_TRUE(m.Matches(a));
  EXPECT_TRUE(m_with_name.Matches(a));
  a.set_n(-1);
  EXPECT_FALSE(m.Matches(a));
  EXPECT_FALSE(m_with_name.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), testing::gmock_matchers_test::AClass::n(), and testing::Property().
TEST() [261/350]
testing::gmock_matchers_test::TEST (PropertyTest , WorksForReferenceToConstProperty)
Definition at line 4203 of file gmock-matchers_test.cc.
{
  Matcher<const AClass&> m = Property(&AClass::s, StartsWith("hi"));
  Matcher<const AClass&> m_with_name =
      Property("s", &AClass::s, StartsWith("hi"));
  AClass a;
  a.set_s("hill");
  EXPECT_TRUE(m.Matches(a));
  EXPECT_TRUE(m_with_name.Matches(a));
  a.set_s("hole");
  EXPECT_FALSE(m.Matches(a));
  EXPECT_FALSE(m_with_name.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Property(), testing::gmock_matchers_test::AClass::s(), and testing::StartsWith().
TEST() [262/350]
testing::gmock_matchers_test::TEST (PropertyTest , WorksForReferenceToNonConstProperty)
Definition at line 4235 of file gmock-matchers_test.cc.
{
  double x = 0.0;
  AClass a;
  Matcher<const AClass&> m = Property(&AClass::x, Ref(x));
  EXPECT_FALSE(m.Matches(a));
  m = Property(&AClass::x, Not(Ref(x)));
  EXPECT_TRUE(m.Matches(a));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::Property(), testing::Ref(), and testing::gmock_matchers_test::AClass::x().
TEST() [263/350]
testing::gmock_matchers_test::TEST (RefTest , CanBeUsedAsMatcherForConstReference)
Definition at line 1286 of file gmock-matchers_test.cc.
{
  int a = 0;
  int b = 0;
  Matcher<const int&> m = Ref(a);
  EXPECT_TRUE(m.Matches(a));
  EXPECT_FALSE(m.Matches(b));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ref().
TEST() [264/350]
testing::gmock_matchers_test::TEST (RefTest , CanDescribeSelf)
Definition at line 1276 of file gmock-matchers_test.cc.
{
  int n = 5;
  Matcher<int&> m = Ref(n);
  stringstream ss;
  ss << "references the variable @" << &n << " 5";
  EXPECT_EQ(ss.str(), Describe(m));
}
References Describe(), EXPECT_EQ, and testing::Ref().
TEST() [265/350]
testing::gmock_matchers_test::TEST (RefTest , ExplainsResult)
Definition at line 1312 of file gmock-matchers_test.cc.
{
  int n = 0;
  EXPECT_THAT(Explain(Matcher<const int&>(Ref(n)), n),
              StartsWith("which is located @"));
  int m = 0;
  EXPECT_THAT(Explain(Matcher<const int&>(Ref(n)), m),
              StartsWith("which is located @"));
}
References EXPECT_THAT, Explain(), testing::Ref(), and testing::StartsWith().
TEST() [266/350]
testing::gmock_matchers_test::TEST (RefTest , IsCovariant)
Definition at line 1298 of file gmock-matchers_test.cc.
{
  Base base, base2;
  Derived derived;
  Matcher<const Base&> m1 = Ref(base);
  EXPECT_TRUE(m1.Matches(base));
  EXPECT_FALSE(m1.Matches(base2));
  EXPECT_FALSE(m1.Matches(derived));
  m1 = Ref(derived);
  EXPECT_TRUE(m1.Matches(derived));
  EXPECT_FALSE(m1.Matches(base));
  EXPECT_FALSE(m1.Matches(base2));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ref().
TEST() [267/350]
testing::gmock_matchers_test::TEST (RefTest , MatchesSameVariable)
Definition at line 1267 of file gmock-matchers_test.cc.
{
  int a = 0;
  int b = 0;
  Matcher<int&> m = Ref(a);
  EXPECT_TRUE(m.Matches(a));
  EXPECT_FALSE(m.Matches(b));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ref().
TEST() [268/350]
testing::gmock_matchers_test::TEST (ResultOfDeathTest , DiesOnNullFunctionPointers)
Definition at line 4542 of file gmock-matchers_test.cc.
{
  EXPECT_DEATH_IF_SUPPORTED(
      ResultOf(static_cast<std::string (*)(int dummy)>(NULL),
               Eq(std::string("foo"))),
      "NULL function pointer is passed into ResultOf\\(\\)\\.");
}
References testing::Eq(), EXPECT_DEATH_IF_SUPPORTED, and testing::ResultOf().
TEST() [269/350]
testing::gmock_matchers_test::TEST (ResultOfTest , CanDescribeItself)
Definition at line 4460 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher = ResultOf(&IntToStringFunction, StrEq("foo"));
  EXPECT_EQ("is mapped by the given callable to a value that "
            "is equal to \"foo\"", Describe(matcher));
  EXPECT_EQ("is mapped by the given callable to a value that "
            "isn't equal to \"foo\"", DescribeNegation(matcher));
}
References Describe(), DescribeNegation(), EXPECT_EQ, IntToStringFunction(), testing::ResultOf(), and testing::StrEq().
TEST() [270/350]
testing::gmock_matchers_test::TEST (ResultOfTest , CanExplainMatchResult)
Definition at line 4472 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher = ResultOf(&IntFunction, Ge(85));
  EXPECT_EQ("which is mapped by the given callable to 90" + OfType("int"),
            Explain(matcher, 36));
  matcher = ResultOf(&IntFunction, GreaterThan(85));
  EXPECT_EQ("which is mapped by the given callable to 90" + OfType("int") +
            ", which is 5 more than 85", Explain(matcher, 36));
}
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), IntFunction(), OfType(), and testing::ResultOf().
TEST() [271/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForCompatibleMatcherTypes)
Definition at line 4532 of file gmock-matchers_test.cc.
{
  // IntFunction() returns int but the inner matcher expects a signed char.
  Matcher<int> matcher = ResultOf(IntFunction, Matcher<signed char>(Ge(85)));
  EXPECT_TRUE(matcher.Matches(36));
  EXPECT_FALSE(matcher.Matches(42));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), IntFunction(), testing::internal::MatcherBase< T >::Matches(), and testing::ResultOf().
TEST() [272/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForFunctionPointers)
Definition at line 4452 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher = ResultOf(&IntToStringFunction, Eq(std::string("foo")));
  EXPECT_TRUE(matcher.Matches(1));
  EXPECT_FALSE(matcher.Matches(2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, IntToStringFunction(), testing::internal::MatcherBase< T >::Matches(), and testing::ResultOf().
TEST() [273/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForFunctionReferences)
Definition at line 4551 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher = ResultOf(IntToStringFunction, StrEq("foo"));
  EXPECT_TRUE(matcher.Matches(1));
  EXPECT_FALSE(matcher.Matches(2));
}
References EXPECT_FALSE, EXPECT_TRUE, IntToStringFunction(), testing::internal::MatcherBase< T >::Matches(), testing::ResultOf(), and testing::StrEq().
TEST() [274/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForFunctors)
Definition at line 4565 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher = ResultOf(Functor(), Eq(std::string("foo")));
  EXPECT_TRUE(matcher.Matches(1));
  EXPECT_FALSE(matcher.Matches(2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::ResultOf().
TEST() [275/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForNonReferenceResults)
Definition at line 4484 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher = ResultOf(&IntFunction, Eq(80));
  EXPECT_TRUE(matcher.Matches(42));
  EXPECT_FALSE(matcher.Matches(36));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, IntFunction(), testing::internal::MatcherBase< T >::Matches(), and testing::ResultOf().
TEST() [276/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForPolymorphicFunctors)
Definition at line 4581 of file gmock-matchers_test.cc.
{
  Matcher<int> matcher_int = ResultOf(PolymorphicFunctor(), Ge(5));
  EXPECT_TRUE(matcher_int.Matches(10));
  EXPECT_FALSE(matcher_int.Matches(2));
  Matcher<const char*> matcher_string = ResultOf(PolymorphicFunctor(), Ge(5));
  EXPECT_TRUE(matcher_string.Matches("long string"));
  EXPECT_FALSE(matcher_string.Matches("shrt"));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Ge(), testing::internal::MatcherBase< T >::Matches(), and testing::ResultOf().
TEST() [277/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForReferenceToConstResults)
Definition at line 4521 of file gmock-matchers_test.cc.
{
  std::string s = "foo";
  std::string s2 = s;
  Matcher<const std::string&> matcher = ResultOf(&StringFunction, Ref(s));
  EXPECT_TRUE(matcher.Matches(s));
  EXPECT_FALSE(matcher.Matches(s2));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Ref(), testing::ResultOf(), and StringFunction().
TEST() [278/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForReferenceToNonConstResults)
Definition at line 4499 of file gmock-matchers_test.cc.
{
  double x = 3.14;
  double x2 = x;
  Matcher<double&> matcher = ResultOf(&DoubleFunction, Ref(x));
  EXPECT_TRUE(matcher.Matches(x));
  EXPECT_FALSE(matcher.Matches(x2));
  // Test that ResultOf works with uncopyable objects
  Uncopyable obj(0);
  Uncopyable obj2(0);
  Matcher<Uncopyable&> matcher2 =
      ResultOf(&RefUncopyableFunction, Ref(obj));
  EXPECT_TRUE(matcher2.Matches(obj));
  EXPECT_FALSE(matcher2.Matches(obj2));
}
References DoubleFunction(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Ref(), RefUncopyableFunction(), and testing::ResultOf().
TEST() [279/350]
testing::gmock_matchers_test::TEST (ResultOfTest , WorksForReferencingCallables)
Definition at line 4600 of file gmock-matchers_test.cc.
{
  const int n = 1;
  const int n2 = 1;
  Matcher<const int&> matcher2 = ResultOf(ReferencingFunction, Eq(&n));
  EXPECT_TRUE(matcher2.Matches(n));
  EXPECT_FALSE(matcher2.Matches(n2));
  Matcher<const int&> matcher3 = ResultOf(ReferencingFunctor(), Eq(&n));
  EXPECT_TRUE(matcher3.Matches(n));
  EXPECT_FALSE(matcher3.Matches(n2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), ReferencingFunction(), and testing::ResultOf().
TEST() [280/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromBaseClass)
Definition at line 849 of file gmock-matchers_test.cc.
{
  Derived d, d2;
  Matcher<Base*> m1 = Eq(&d);
  Matcher<Derived*> m2 = SafeMatcherCast<Derived*>(m1);
  EXPECT_TRUE(m2.Matches(&d));
  EXPECT_FALSE(m2.Matches(&d2));
  Matcher<Base&> m3 = Ref(d);
  Matcher<Derived&> m4 = SafeMatcherCast<Derived&>(m3);
  EXPECT_TRUE(m4.Matches(d));
  EXPECT_FALSE(m4.Matches(d2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ref().
TEST() [281/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromConstReferenceToReference)
Definition at line 863 of file gmock-matchers_test.cc.
{
  int n = 0;
  Matcher<const int&> m1 = Ref(n);
  Matcher<int&> m2 = SafeMatcherCast<int&>(m1);
  int n1 = 0;
  EXPECT_TRUE(m2.Matches(n));
  EXPECT_FALSE(m2.Matches(n1));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Ref().
TEST() [282/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromLosslesslyConvertibleArithmeticType)
Definition at line 836 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = DoubleEq(1.0);
  Matcher<float> m2 = SafeMatcherCast<float>(m1);
  EXPECT_TRUE(m2.Matches(1.0f));
  EXPECT_FALSE(m2.Matches(2.0f));
  Matcher<char> m3 = SafeMatcherCast<char>(TypedEq<int>('a'));
  EXPECT_TRUE(m3.Matches('a'));
  EXPECT_FALSE(m3.Matches('b'));
}
References testing::DoubleEq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [283/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromNonReferenceToConstReference)
Definition at line 873 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(0);
  Matcher<const int&> m2 = SafeMatcherCast<const int&>(m1);
  EXPECT_TRUE(m2.Matches(0));
  EXPECT_FALSE(m2.Matches(1));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [284/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromNonReferenceToReference)
Definition at line 881 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(0);
  Matcher<int&> m2 = SafeMatcherCast<int&>(m1);
  int n = 0;
  EXPECT_TRUE(m2.Matches(n));
  n = 1;
  EXPECT_FALSE(m2.Matches(n));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [285/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromPolymorphicMatcher)
Definition at line 827 of file gmock-matchers_test.cc.
{
  Matcher<char> m2 = SafeMatcherCast<char>(Eq(32));
  EXPECT_TRUE(m2.Matches(' '));
  EXPECT_FALSE(m2.Matches('\n'));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [286/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , FromSameType)
Definition at line 891 of file gmock-matchers_test.cc.
{
  Matcher<int> m1 = Eq(0);
  Matcher<int> m2 = SafeMatcherCast<int>(m1);
  EXPECT_TRUE(m2.Matches(0));
  EXPECT_FALSE(m2.Matches(1));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [287/350]
testing::gmock_matchers_test::TEST (SafeMatcherCastTest , ValueIsNotCopied)
Definition at line 917 of file gmock-matchers_test.cc.
{
  int n = 42;
  Matcher<IntReferenceWrapper> m = SafeMatcherCast<IntReferenceWrapper>(n);
  // Verify that the matcher holds a reference to n, not to its temporary copy.
  EXPECT_TRUE(m.Matches(n));
}
References EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [288/350]
testing::gmock_matchers_test::TEST (SizeIsTest , CanDescribeSelf)
Definition at line 4824 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m = SizeIs(2);
  EXPECT_EQ("size is equal to 2", Describe(m));
  EXPECT_EQ("size isn't equal to 2", DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::SizeIs().
TEST() [289/350]
testing::gmock_matchers_test::TEST (SizeIsTest , ExplainsResult)
Definition at line 4830 of file gmock-matchers_test.cc.
{
  Matcher<vector<int> > m1 = SizeIs(2);
  Matcher<vector<int> > m2 = SizeIs(Lt(2u));
  Matcher<vector<int> > m3 = SizeIs(AnyOf(0, 3));
  Matcher<vector<int> > m4 = SizeIs(GreaterThan(1));
  vector<int> container;
  EXPECT_EQ("whose size 0 doesn't match", Explain(m1, container));
  EXPECT_EQ("whose size 0 matches", Explain(m2, container));
  EXPECT_EQ("whose size 0 matches", Explain(m3, container));
  EXPECT_EQ("whose size 0 doesn't match, which is 1 less than 1",
            Explain(m4, container));
  container.push_back(0);
  container.push_back(0);
  EXPECT_EQ("whose size 2 matches", Explain(m1, container));
  EXPECT_EQ("whose size 2 doesn't match", Explain(m2, container));
  EXPECT_EQ("whose size 2 doesn't match", Explain(m3, container));
  EXPECT_EQ("whose size 2 matches, which is 1 more than 1",
            Explain(m4, container));
}
References testing::AnyOf(), EXPECT_EQ, Explain(), GreaterThan(), testing::Lt(), and testing::SizeIs().
TEST() [290/350]
testing::gmock_matchers_test::TEST (SizeIsTest , ImplementsSizeIs)
Definition at line 4792 of file gmock-matchers_test.cc.
{
  vector<int> container;
  EXPECT_THAT(container, SizeIs(0));
  EXPECT_THAT(container, Not(SizeIs(1)));
  container.push_back(0);
  EXPECT_THAT(container, Not(SizeIs(0)));
  EXPECT_THAT(container, SizeIs(1));
  container.push_back(0);
  EXPECT_THAT(container, Not(SizeIs(0)));
  EXPECT_THAT(container, SizeIs(2));
}
References EXPECT_THAT, testing::Not(), and testing::SizeIs().
TEST() [291/350]
testing::gmock_matchers_test::TEST (SizeIsTest , WorksWithMap)
Definition at line 4804 of file gmock-matchers_test.cc.
{
  map<std::string, int> container;
  EXPECT_THAT(container, SizeIs(0));
  EXPECT_THAT(container, Not(SizeIs(1)));
  container.insert(make_pair("foo", 1));
  EXPECT_THAT(container, Not(SizeIs(0)));
  EXPECT_THAT(container, SizeIs(1));
  container.insert(make_pair("bar", 2));
  EXPECT_THAT(container, Not(SizeIs(0)));
  EXPECT_THAT(container, SizeIs(2));
}
References EXPECT_THAT, testing::Not(), and testing::SizeIs().
TEST() [292/350]
testing::gmock_matchers_test::TEST (SizeIsTest , WorksWithReferences)
Definition at line 4816 of file gmock-matchers_test.cc.
{
  vector<int> container;
  Matcher<const vector<int>&> m = SizeIs(1);
  EXPECT_THAT(container, Not(m));
  container.push_back(0);
  EXPECT_THAT(container, m);
}
References EXPECT_THAT, testing::Not(), and testing::SizeIs().
TEST() [293/350]
testing::gmock_matchers_test::TEST (StartsWithTest , CanDescribeSelf)
Definition at line 1719 of file gmock-matchers_test.cc.
{
  Matcher<const std::string> m = StartsWith("Hi");
  EXPECT_EQ("starts with \"Hi\"", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::StartsWith().
TEST() [294/350]
testing::gmock_matchers_test::TEST (StartsWithTest , MatchesStringWithGivenPrefix)
Definition at line 1705 of file gmock-matchers_test.cc.
{
  const Matcher<const char*> m1 = StartsWith(std::string(""));
  EXPECT_TRUE(m1.Matches("Hi"));
  EXPECT_TRUE(m1.Matches(""));
  EXPECT_FALSE(m1.Matches(NULL));
  const Matcher<const std::string&> m2 = StartsWith("Hi");
  EXPECT_TRUE(m2.Matches("Hi"));
  EXPECT_TRUE(m2.Matches("Hi Hi!"));
  EXPECT_TRUE(m2.Matches("High"));
  EXPECT_FALSE(m2.Matches("H"));
  EXPECT_FALSE(m2.Matches(" Hi"));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::StartsWith().
TEST() [295/350]
testing::gmock_matchers_test::TEST (StrCaseEqTest , CanDescribeSelf)
Definition at line 1424 of file gmock-matchers_test.cc.
{
  Matcher<std::string> m = StrCaseEq("Hi");
  EXPECT_EQ("is equal to (ignoring case) \"Hi\"", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::StrCaseEq().
TEST() [296/350]
testing::gmock_matchers_test::TEST (StrCaseEqTest , MatchesEqualStringIgnoringCase)
Definition at line 1379 of file gmock-matchers_test.cc.
{
  Matcher<const char*> m = StrCaseEq(std::string("Hello"));
  EXPECT_TRUE(m.Matches("Hello"));
  EXPECT_TRUE(m.Matches("hello"));
  EXPECT_FALSE(m.Matches("Hi"));
  EXPECT_FALSE(m.Matches(NULL));
  Matcher<const std::string&> m2 = StrCaseEq("Hello");
  EXPECT_TRUE(m2.Matches("hello"));
  EXPECT_FALSE(m2.Matches("Hi"));
#if GTEST_HAS_ABSL
  Matcher<const absl::string_view&> m3 = StrCaseEq(std::string("Hello"));
  EXPECT_TRUE(m3.Matches(absl::string_view("Hello")));
  EXPECT_TRUE(m3.Matches(absl::string_view("hello")));
  EXPECT_FALSE(m3.Matches(absl::string_view("Hi")));
  EXPECT_FALSE(m3.Matches(absl::string_view()));
#endif  // GTEST_HAS_ABSL
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::StrCaseEq().
TEST() [297/350]
testing::gmock_matchers_test::TEST (StrCaseEqTest , MatchesEqualStringWith0IgnoringCase)
Definition at line 1399 of file gmock-matchers_test.cc.
{
  std::string str1("oabocdooeoo");
  std::string str2("OABOCDOOEOO");
  Matcher<const std::string&> m0 = StrCaseEq(str1);
  EXPECT_FALSE(m0.Matches(str2 + std::string(1, '\0')));
  str1[3] = str2[3] = '\0';
  Matcher<const std::string&> m1 = StrCaseEq(str1);
  EXPECT_TRUE(m1.Matches(str2));
  str1[0] = str1[6] = str1[7] = str1[10] = '\0';
  str2[0] = str2[6] = str2[7] = str2[10] = '\0';
  Matcher<const std::string&> m2 = StrCaseEq(str1);
  str1[9] = str2[9] = '\0';
  EXPECT_FALSE(m2.Matches(str2));
  Matcher<const std::string&> m3 = StrCaseEq(str1);
  EXPECT_TRUE(m3.Matches(str2));
  EXPECT_FALSE(m3.Matches(str2 + "x"));
  str2.append(1, '\0');
  EXPECT_FALSE(m3.Matches(str2));
  EXPECT_FALSE(m3.Matches(std::string(str2, 0, 9)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::StrCaseEq().
TEST() [298/350]
testing::gmock_matchers_test::TEST (StrCaseNeTest , CanDescribeSelf)
Definition at line 1449 of file gmock-matchers_test.cc.
{
  Matcher<const char*> m = StrCaseNe("Hi");
  EXPECT_EQ("isn't equal to (ignoring case) \"Hi\"", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::StrCaseNe().
TEST() [299/350]
testing::gmock_matchers_test::TEST (StrCaseNeTest , MatchesUnequalStringIgnoringCase)
Definition at line 1429 of file gmock-matchers_test.cc.
{
  Matcher<const char*> m = StrCaseNe("Hello");
  EXPECT_TRUE(m.Matches("Hi"));
  EXPECT_TRUE(m.Matches(NULL));
  EXPECT_FALSE(m.Matches("Hello"));
  EXPECT_FALSE(m.Matches("hello"));
  Matcher<std::string> m2 = StrCaseNe(std::string("Hello"));
  EXPECT_TRUE(m2.Matches(""));
  EXPECT_FALSE(m2.Matches("Hello"));
#if GTEST_HAS_ABSL
  Matcher<const absl::string_view> m3 = StrCaseNe("Hello");
  EXPECT_TRUE(m3.Matches(absl::string_view("Hi")));
  EXPECT_TRUE(m3.Matches(absl::string_view()));
  EXPECT_FALSE(m3.Matches(absl::string_view("Hello")));
  EXPECT_FALSE(m3.Matches(absl::string_view("hello")));
#endif  // GTEST_HAS_ABSL
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::StrCaseNe().
TEST() [300/350]
testing::gmock_matchers_test::TEST (StreamlikeTest , Iteration)
Definition at line 5261 of file gmock-matchers_test.cc.
{
  const int a[5] = {2, 1, 4, 5, 3};
  Streamlike<int> s(a, a + 5);
  Streamlike<int>::const_iterator it = s.begin();
  const int* ip = a;
  while (it != s.end()) {
    SCOPED_TRACE(ip - a);
    EXPECT_EQ(*ip++, *it++);
  }
}
References testing::gmock_matchers_test::Streamlike< T >::begin(), testing::gmock_matchers_test::Streamlike< T >::end(), EXPECT_EQ, and SCOPED_TRACE.
TEST() [301/350]
testing::gmock_matchers_test::TEST (StrEqTest , CanDescribeSelf)
Definition at line 1342 of file gmock-matchers_test.cc.
{
  Matcher<std::string> m = StrEq("Hi-\'\"?\\\a\b\f\n\r\t\v\xD3");
  EXPECT_EQ("is equal to \"Hi-\'\\\"?\\\\\\a\\b\\f\\n\\r\\t\\v\\xD3\"",
      Describe(m));
  std::string str("01204500800");
  str[3] = '\0';
  Matcher<std::string> m2 = StrEq(str);
  EXPECT_EQ("is equal to \"012\\04500800\"", Describe(m2));
  str[0] = str[6] = str[7] = str[9] = str[10] = '\0';
  Matcher<std::string> m3 = StrEq(str);
  EXPECT_EQ("is equal to \"\\012\\045\\0\\08\\0\\0\"", Describe(m3));
}
References Describe(), EXPECT_EQ, and testing::StrEq().
TEST() [302/350]
testing::gmock_matchers_test::TEST (StrEqTest , MatchesEqualString)
Definition at line 1324 of file gmock-matchers_test.cc.
{
  Matcher<const char*> m = StrEq(std::string("Hello"));
  EXPECT_TRUE(m.Matches("Hello"));
  EXPECT_FALSE(m.Matches("hello"));
  EXPECT_FALSE(m.Matches(NULL));
  Matcher<const std::string&> m2 = StrEq("Hello");
  EXPECT_TRUE(m2.Matches("Hello"));
  EXPECT_FALSE(m2.Matches("Hi"));
#if GTEST_HAS_ABSL
  Matcher<const absl::string_view&> m3 = StrEq("Hello");
  EXPECT_TRUE(m3.Matches(absl::string_view("Hello")));
  EXPECT_FALSE(m3.Matches(absl::string_view("hello")));
  EXPECT_FALSE(m3.Matches(absl::string_view()));
#endif  // GTEST_HAS_ABSL
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::StrEq().
TEST() [303/350]
testing::gmock_matchers_test::TEST (StringMatcherTest , CanBeImplicitlyConstructedFromCStringLiteral)
Definition at line 386 of file gmock-matchers_test.cc.
{
  Matcher<std::string> m1 = "hi";
  EXPECT_TRUE(m1.Matches("hi"));
  EXPECT_FALSE(m1.Matches("hello"));
  Matcher<const std::string&> m2 = "hi";
  EXPECT_TRUE(m2.Matches("hi"));
  EXPECT_FALSE(m2.Matches("hello"));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [304/350]
testing::gmock_matchers_test::TEST (StringMatcherTest , CanBeImplicitlyConstructedFromString)
Definition at line 398 of file gmock-matchers_test.cc.
{
  Matcher<std::string> m1 = std::string("hi");
  EXPECT_TRUE(m1.Matches("hi"));
  EXPECT_FALSE(m1.Matches("hello"));
  Matcher<const std::string&> m2 = std::string("hi");
  EXPECT_TRUE(m2.Matches("hi"));
  EXPECT_FALSE(m2.Matches("hello"));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [305/350]
testing::gmock_matchers_test::TEST (StrNeTest , CanDescribeSelf)
Definition at line 1374 of file gmock-matchers_test.cc.
{
  Matcher<const char*> m = StrNe("Hi");
  EXPECT_EQ("isn't equal to \"Hi\"", Describe(m));
}
References Describe(), EXPECT_EQ, and testing::StrNe().
TEST() [306/350]
testing::gmock_matchers_test::TEST (StrNeTest , MatchesUnequalString)
Definition at line 1356 of file gmock-matchers_test.cc.
{
  Matcher<const char*> m = StrNe("Hello");
  EXPECT_TRUE(m.Matches(""));
  EXPECT_TRUE(m.Matches(NULL));
  EXPECT_FALSE(m.Matches("Hello"));
  Matcher<std::string> m2 = StrNe(std::string("Hello"));
  EXPECT_TRUE(m2.Matches("hello"));
  EXPECT_FALSE(m2.Matches("Hello"));
#if GTEST_HAS_ABSL
  Matcher<const absl::string_view> m3 = StrNe("Hello");
  EXPECT_TRUE(m3.Matches(absl::string_view("")));
  EXPECT_TRUE(m3.Matches(absl::string_view()));
  EXPECT_FALSE(m3.Matches(absl::string_view("Hello")));
#endif  // GTEST_HAS_ABSL
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::StrNe().
TEST() [307/350]
testing::gmock_matchers_test::TEST (TrulyTest , CanBeUsedWithFunctor)
Definition at line 2935 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Truly(IsGreaterThan(5));
  EXPECT_TRUE(m.Matches(6));
  EXPECT_FALSE(m.Matches(4));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::Truly().
TEST() [308/350]
testing::gmock_matchers_test::TEST (TrulyTest , CanDescribeSelf)
Definition at line 2965 of file gmock-matchers_test.cc.
{
  Matcher<double> m = Truly(IsPositive);
  EXPECT_EQ("satisfies the given predicate",
            Describe(m));
}
References Describe(), EXPECT_EQ, IsPositive(), and testing::Truly().
TEST() [309/350]
testing::gmock_matchers_test::TEST (TrulyTest , MatchesWhatSatisfiesThePredicate)
Definition at line 2928 of file gmock-matchers_test.cc.
{
  Matcher<double> m = Truly(IsPositive);
  EXPECT_TRUE(m.Matches(2.0));
  EXPECT_FALSE(m.Matches(-1.5));
}
References EXPECT_FALSE, EXPECT_TRUE, IsPositive(), testing::internal::MatcherBase< T >::Matches(), and testing::Truly().
TEST() [310/350]
testing::gmock_matchers_test::TEST (TrulyTest , PredicateCanReturnAClassConvertibleToBool)
Definition at line 2958 of file gmock-matchers_test.cc.
{
  Matcher<int> m = Truly(IsNotZero);
  EXPECT_TRUE(m.Matches(1));
  EXPECT_FALSE(m.Matches(0));
}
References EXPECT_FALSE, EXPECT_TRUE, IsNotZero(), testing::internal::MatcherBase< T >::Matches(), and testing::Truly().
TEST() [311/350]
testing::gmock_matchers_test::TEST (TrulyTest , WorksForByRefArguments)
Definition at line 2973 of file gmock-matchers_test.cc.
{
  Matcher<const int&> m = Truly(ReferencesFooAndIsZero);
  EXPECT_TRUE(m.Matches(foo));
  int n = 0;
  EXPECT_FALSE(m.Matches(n));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), ReferencesFooAndIsZero(), and testing::Truly().
TEST() [312/350]
testing::gmock_matchers_test::TEST (TypedEqTest , CanDescribeSelf)
Definition at line 1061 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("is equal to 2", Describe(TypedEq<int>(2)));
}
References Describe(), and EXPECT_EQ.
TEST() [313/350]
testing::gmock_matchers_test::TEST (TypedEqTest , ChecksEqualityForGivenType)
Definition at line 1050 of file gmock-matchers_test.cc.
{
  Matcher<char> m1 = TypedEq<char>('a');
  EXPECT_TRUE(m1.Matches('a'));
  EXPECT_FALSE(m1.Matches('b'));
  Matcher<int> m2 = TypedEq<int>(6);
  EXPECT_TRUE(m2.Matches(6));
  EXPECT_FALSE(m2.Matches(7));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [314/350]
testing::gmock_matchers_test::TEST (TypedEqTest , HasSpecifiedType)
Definition at line 1079 of file gmock-matchers_test.cc.
{
  // Verfies that the type of TypedEq<T>(v) is Matcher<T>.
  Type<Matcher<int> >::IsTypeOf(TypedEq<int>(5));
  Type<Matcher<double> >::IsTypeOf(TypedEq<double>(5));
}
TEST() [315/350]
testing::gmock_matchers_test::TEST (UnderscoreTest , CanDescribeSelf)
Definition at line 1005 of file gmock-matchers_test.cc.
{
  Matcher<int> m = _;
  EXPECT_EQ("is anything", Describe(m));
}
References testing::_, Describe(), and EXPECT_EQ.
TEST() [316/350]
testing::gmock_matchers_test::TEST (UnderscoreTest , MatchesAnyValue)
Definition at line 990 of file gmock-matchers_test.cc.
{
  // Uses _ as a matcher for a value type.
  Matcher<int> m1 = _;
  EXPECT_TRUE(m1.Matches(123));
  EXPECT_TRUE(m1.Matches(-242));
  // Uses _ as a matcher for a reference type.
  bool a = false;
  const bool b = true;
  Matcher<const bool&> m2 = _;
  EXPECT_TRUE(m2.Matches(a));
  EXPECT_TRUE(m2.Matches(b));
}
References testing::_, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [317/350]
testing::gmock_matchers_test::TEST (UnorderedElementsAreArrayTest , SucceedsWhenExpected)
Definition at line 5638 of file gmock-matchers_test.cc.
{
  const int a[] = {0, 1, 2, 3, 4};
  std::vector<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  do {
    StringMatchResultListener listener;
    EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAreArray(a),
                                   s, &listener)) << listener.str();
  } while (std::next_permutation(s.begin(), s.end()));
}
References EXPECT_TRUE, testing::ExplainMatchResult(), GTEST_ARRAY_SIZE_, testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
TEST() [318/350]
testing::gmock_matchers_test::TEST (UnorderedElementsAreArrayTest , TakesStlContainer)
Definition at line 5677 of file gmock-matchers_test.cc.
{
  const int actual[] = {3, 1, 2};
  ::std::list<int> expected;
  expected.push_back(1);
  expected.push_back(2);
  expected.push_back(3);
  EXPECT_THAT(actual, UnorderedElementsAreArray(expected));
  expected.push_back(4);
  EXPECT_THAT(actual, Not(UnorderedElementsAreArray(expected)));
}
References EXPECT_THAT, testing::Not(), and testing::UnorderedElementsAreArray().
TEST() [319/350]
testing::gmock_matchers_test::TEST (UnorderedElementsAreArrayTest , VectorBool)
Definition at line 5648 of file gmock-matchers_test.cc.
{
  const bool a[] = {0, 1, 0, 1, 1};
  const bool b[] = {1, 0, 1, 1, 0};
  std::vector<bool> expected(a, a + GTEST_ARRAY_SIZE_(a));
  std::vector<bool> actual(b, b + GTEST_ARRAY_SIZE_(b));
  StringMatchResultListener listener;
  EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAreArray(expected),
                                 actual, &listener)) << listener.str();
}
References EXPECT_TRUE, testing::ExplainMatchResult(), GTEST_ARRAY_SIZE_, testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
TEST() [320/350]
testing::gmock_matchers_test::TEST (UnorderedElementsAreArrayTest , WorksForStreamlike)
Definition at line 5658 of file gmock-matchers_test.cc.
{
  // Streamlike 'container' provides only minimal iterator support.
  // Its iterators are tagged with input_iterator_tag, and it has no
  // size() or empty() methods.
  const int a[5] = {2, 1, 4, 5, 3};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  ::std::vector<int> expected;
  expected.push_back(1);
  expected.push_back(2);
  expected.push_back(3);
  expected.push_back(4);
  expected.push_back(5);
  EXPECT_THAT(s, UnorderedElementsAreArray(expected));
  expected.push_back(6);
  EXPECT_THAT(s, Not(UnorderedElementsAreArray(expected)));
}
References EXPECT_THAT, GTEST_ARRAY_SIZE_, testing::Not(), and testing::UnorderedElementsAreArray().
TEST() [321/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , AcceptsCorrectContentInDifferentOrder)
Definition at line 6554 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {6, 4, 2};
  EXPECT_THAT(lhs, UnorderedPointwise(IsHalfOf(), rhs));
}
References EXPECT_THAT, IsHalfOf(), and testing::UnorderedPointwise().
TEST() [322/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , AcceptsCorrectContentInSameOrder)
Definition at line 6548 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {2, 4, 6};
  EXPECT_THAT(lhs, UnorderedPointwise(IsHalfOf(), rhs));
}
References EXPECT_THAT, IsHalfOf(), and testing::UnorderedPointwise().
TEST() [323/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , AllowsMonomorphicInnerMatcher)
Definition at line 6560 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {4, 6, 2};
  const Matcher<tuple<const double&, const int&> > m1 = IsHalfOf();
  EXPECT_THAT(lhs, UnorderedPointwise(m1, rhs));
  // This type works as a tuple<const double&, const int&> can be
  // implicitly cast to tuple<double, int>.
  const Matcher<tuple<double, int> > m2 = IsHalfOf();
  EXPECT_THAT(lhs, UnorderedPointwise(m2, rhs));
}
References EXPECT_THAT, IsHalfOf(), and testing::UnorderedPointwise().
TEST() [324/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , DescribesSelf)
Definition at line 6458 of file gmock-matchers_test.cc.
{
  vector<int> rhs;
  rhs.push_back(1);
  rhs.push_back(2);
  rhs.push_back(3);
  const Matcher<const vector<int>&> m = UnorderedPointwise(IsHalfOf(), rhs);
  EXPECT_EQ(
      "has 3 elements and there exists some permutation of elements such "
      "that:\n"
      " - element #0 and 1 are a pair where the first is half of the second, "
      "and\n"
      " - element #1 and 2 are a pair where the first is half of the second, "
      "and\n"
      " - element #2 and 3 are a pair where the first is half of the second",
      Describe(m));
  EXPECT_EQ(
      "doesn't have 3 elements, or there exists no permutation of elements "
      "such that:\n"
      " - element #0 and 1 are a pair where the first is half of the second, "
      "and\n"
      " - element #1 and 2 are a pair where the first is half of the second, "
      "and\n"
      " - element #2 and 3 are a pair where the first is half of the second",
      DescribeNegation(m));
}
References Describe(), DescribeNegation(), EXPECT_EQ, IsHalfOf(), and testing::UnorderedPointwise().
TEST() [325/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , MakesCopyOfRhs)
Definition at line 6484 of file gmock-matchers_test.cc.
{
  list<signed char> rhs;
  rhs.push_back(2);
  rhs.push_back(4);
  int lhs[] = {2, 1};
  const Matcher<const int (&)[2]> m = UnorderedPointwise(IsHalfOf(), rhs);
  EXPECT_THAT(lhs, m);
  // Changing rhs now shouldn't affect m, which made a copy of rhs.
  rhs.push_back(6);
  EXPECT_THAT(lhs, m);
}
References EXPECT_THAT, IsHalfOf(), and testing::UnorderedPointwise().
TEST() [326/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , RejectsWrongContent)
Definition at line 6539 of file gmock-matchers_test.cc.
{
  const double lhs[3] = {1, 2, 3};
  const int rhs[3] = {2, 6, 6};
  EXPECT_THAT(lhs, Not(UnorderedPointwise(IsHalfOf(), rhs)));
  EXPECT_EQ("where the following elements don't match any matchers:\n"
            "element #1: 2",
            Explain(UnorderedPointwise(IsHalfOf(), rhs), lhs));
}
References EXPECT_EQ, EXPECT_THAT, Explain(), IsHalfOf(), testing::Not(), and testing::UnorderedPointwise().
TEST() [327/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , RejectsWrongSize)
Definition at line 6528 of file gmock-matchers_test.cc.
{
  const double lhs[2] = {1, 2};
  const int rhs[1] = {0};
  EXPECT_THAT(lhs, Not(UnorderedPointwise(Gt(), rhs)));
  EXPECT_EQ("which has 2 elements",
            Explain(UnorderedPointwise(Gt(), rhs), lhs));
  const int rhs2[3] = {0, 1, 2};
  EXPECT_THAT(lhs, Not(UnorderedPointwise(Gt(), rhs2)));
}
References EXPECT_EQ, EXPECT_THAT, Explain(), testing::Gt(), testing::Not(), and testing::UnorderedPointwise().
TEST() [328/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , WorksForLhsNativeArray)
Definition at line 6498 of file gmock-matchers_test.cc.
{
  const int lhs[] = {1, 2, 3};
  vector<int> rhs;
  rhs.push_back(4);
  rhs.push_back(6);
  rhs.push_back(2);
  EXPECT_THAT(lhs, UnorderedPointwise(Lt(), rhs));
  EXPECT_THAT(lhs, Not(UnorderedPointwise(Gt(), rhs)));
}
References EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), and testing::UnorderedPointwise().
TEST() [329/350]
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , WorksForRhsNativeArray)
Definition at line 6508 of file gmock-matchers_test.cc.
{
  const int rhs[] = {1, 2, 3};
  vector<int> lhs;
  lhs.push_back(4);
  lhs.push_back(2);
  lhs.push_back(6);
  EXPECT_THAT(lhs, UnorderedPointwise(Gt(), rhs));
  EXPECT_THAT(lhs, Not(UnorderedPointwise(Lt(), rhs)));
}
References EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), and testing::UnorderedPointwise().
TEST() [330/350]
testing::gmock_matchers_test::TEST (ValueTest , WorksWithMonomorphicMatcher)
Definition at line 3011 of file gmock-matchers_test.cc.
{
  const Matcher<int> is_zero = Eq(0);
  EXPECT_TRUE(Value(0, is_zero));
  EXPECT_FALSE(Value('a', is_zero));
  int n = 0;
  const Matcher<const int&> ref_n = Ref(n);
  EXPECT_TRUE(Value(n, ref_n));
  EXPECT_FALSE(Value(1, ref_n));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::Ref().
TEST() [331/350]
testing::gmock_matchers_test::TEST (ValueTest , WorksWithPolymorphicMatcher)
Definition at line 3006 of file gmock-matchers_test.cc.
{
  EXPECT_TRUE(Value("hi", StartsWith("h")));
  EXPECT_FALSE(Value(5, Gt(10)));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Gt(), and testing::StartsWith().
TEST() [332/350]
testing::gmock_matchers_test::TEST (VariantTest , DescribesSelf)
Definition at line 6641 of file gmock-matchers_test.cc.
{
  const Matcher<SampleVariantIntString> m = VariantWith<int>(Eq(1));
  EXPECT_THAT(Describe(m), ContainsRegex("is a variant<> with value of type "
                                         "'.*' and the value is equal to 1"));
}
References testing::ContainsRegex(), Describe(), testing::Eq(), and EXPECT_THAT.
TEST() [333/350]
testing::gmock_matchers_test::TEST (VariantTest , ExplainsSelf)
Definition at line 6647 of file gmock-matchers_test.cc.
{
  const Matcher<SampleVariantIntString> m = VariantWith<int>(Eq(1));
  EXPECT_THAT(Explain(m, SampleVariantIntString(1)),
              ContainsRegex("whose value 1"));
  EXPECT_THAT(Explain(m, SampleVariantIntString("A")),
              HasSubstr("whose value is not of type '"));
  EXPECT_THAT(Explain(m, SampleVariantIntString(2)),
              "whose value 2 doesn't match");
}
References testing::ContainsRegex(), testing::Eq(), EXPECT_THAT, Explain(), and testing::HasSubstr().
TEST() [334/350]
testing::gmock_matchers_test::TEST (VariantTest , FullMatch)
Definition at line 6657 of file gmock-matchers_test.cc.
{
  Matcher<SampleVariantIntString> m = VariantWith<int>(Eq(1));
  EXPECT_TRUE(m.Matches(SampleVariantIntString(1)));
  m = VariantWith<std::string>(Eq("1"));
  EXPECT_TRUE(m.Matches(SampleVariantIntString("1")));
}
References testing::Eq(), EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [335/350]
testing::gmock_matchers_test::TEST (VariantTest , InnerDoesNotMatch)
Definition at line 6673 of file gmock-matchers_test.cc.
{
  Matcher<SampleVariantIntString> m = VariantWith<int>(Eq(1));
  EXPECT_FALSE(m.Matches(SampleVariantIntString(2)));
  m = VariantWith<std::string>(Eq("1"));
  EXPECT_FALSE(m.Matches(SampleVariantIntString("2")));
}
References testing::Eq(), EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST() [336/350]
testing::gmock_matchers_test::TEST (VariantTest , TypeDoesNotMatch)
Definition at line 6665 of file gmock-matchers_test.cc.
{
  Matcher<SampleVariantIntString> m = VariantWith<int>(Eq(1));
  EXPECT_FALSE(m.Matches(SampleVariantIntString("1")));
  m = VariantWith<std::string>(Eq("1"));
  EXPECT_FALSE(m.Matches(SampleVariantIntString(1)));
}
References testing::Eq(), EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST() [337/350]
testing::gmock_matchers_test::TEST (WhenSortedByTest , CanDescribeSelf)
Definition at line 5089 of file gmock-matchers_test.cc.
{
  const Matcher<vector<int> > m = WhenSortedBy(less<int>(), ElementsAre(1, 2));
  EXPECT_EQ("(when sorted) has 2 elements where\n"
            "element #0 is equal to 1,\n"
            "element #1 is equal to 2",
            Describe(m));
  EXPECT_EQ("(when sorted) doesn't have 2 elements, or\n"
            "element #0 isn't equal to 1, or\n"
            "element #1 isn't equal to 2",
            DescribeNegation(m));
}
References Describe(), DescribeNegation(), testing::ElementsAre(), EXPECT_EQ, and testing::WhenSortedBy().
TEST() [338/350]
testing::gmock_matchers_test::TEST (WhenSortedByTest , ExplainsMatchResult)
Definition at line 5101 of file gmock-matchers_test.cc.
{
  const int a[] = {2, 1};
  EXPECT_EQ("which is { 1, 2 } when sorted, whose element #0 doesn't match",
            Explain(WhenSortedBy(less<int>(), ElementsAre(2, 3)), a));
  EXPECT_EQ("which is { 1, 2 } when sorted",
            Explain(WhenSortedBy(less<int>(), ElementsAre(1, 2)), a));
}
References testing::ElementsAre(), EXPECT_EQ, Explain(), and testing::WhenSortedBy().
TEST() [339/350]
testing::gmock_matchers_test::TEST (WhenSortedByTest , WorksForEmptyContainer)
Definition at line 5051 of file gmock-matchers_test.cc.
{
  const vector<int> numbers;
  EXPECT_THAT(numbers, WhenSortedBy(less<int>(), ElementsAre()));
  EXPECT_THAT(numbers, Not(WhenSortedBy(less<int>(), ElementsAre(1))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSortedBy().
TEST() [340/350]
testing::gmock_matchers_test::TEST (WhenSortedByTest , WorksForNativeArray)
Definition at line 5080 of file gmock-matchers_test.cc.
{
  const int numbers[] = {1, 3, 2, 4};
  const int sorted_numbers[] = {1, 2, 3, 4};
  EXPECT_THAT(numbers, WhenSortedBy(less<int>(), ElementsAre(1, 2, 3, 4)));
  EXPECT_THAT(numbers, WhenSortedBy(less<int>(),
                                    ElementsAreArray(sorted_numbers)));
  EXPECT_THAT(numbers, Not(WhenSortedBy(less<int>(), ElementsAre(1, 3, 2, 4))));
}
References testing::ElementsAre(), testing::ElementsAreArray(), EXPECT_THAT, testing::Not(), and testing::WhenSortedBy().
TEST() [341/350]
testing::gmock_matchers_test::TEST (WhenSortedByTest , WorksForNonEmptyContainer)
Definition at line 5057 of file gmock-matchers_test.cc.
{
  vector<unsigned> numbers;
  numbers.push_back(3);
  numbers.push_back(1);
  numbers.push_back(2);
  numbers.push_back(2);
  EXPECT_THAT(numbers, WhenSortedBy(greater<unsigned>(),
                                    ElementsAre(3, 2, 2, 1)));
  EXPECT_THAT(numbers, Not(WhenSortedBy(greater<unsigned>(),
                                        ElementsAre(1, 2, 2, 3))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSortedBy().
TEST() [342/350]
testing::gmock_matchers_test::TEST (WhenSortedByTest , WorksForNonVectorContainer)
Definition at line 5069 of file gmock-matchers_test.cc.
{
  list<std::string> words;
  words.push_back("say");
  words.push_back("hello");
  words.push_back("world");
  EXPECT_THAT(words, WhenSortedBy(less<std::string>(),
                                  ElementsAre("hello", "say", "world")));
  EXPECT_THAT(words, Not(WhenSortedBy(less<std::string>(),
                                      ElementsAre("say", "hello", "world"))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSortedBy().
TEST() [343/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForEmptyContainer)
Definition at line 5112 of file gmock-matchers_test.cc.
{
  const vector<int> numbers;
  EXPECT_THAT(numbers, WhenSorted(ElementsAre()));
  EXPECT_THAT(numbers, Not(WhenSorted(ElementsAre(1))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSorted().
TEST() [344/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForMapTypes)
Definition at line 5128 of file gmock-matchers_test.cc.
{
  map<std::string, int> word_counts;
  word_counts["and"] = 1;
  word_counts["the"] = 1;
  word_counts["buffalo"] = 2;
  EXPECT_THAT(word_counts,
              WhenSorted(ElementsAre(Pair("and", 1), Pair("buffalo", 2),
                                     Pair("the", 1))));
  EXPECT_THAT(word_counts,
              Not(WhenSorted(ElementsAre(Pair("and", 1), Pair("the", 1),
                                         Pair("buffalo", 2)))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), testing::Pair(), and testing::WhenSorted().
TEST() [345/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForMultiMapTypes)
Definition at line 5141 of file gmock-matchers_test.cc.
{
    multimap<int, int> ifib;
    ifib.insert(make_pair(8, 6));
    ifib.insert(make_pair(2, 3));
    ifib.insert(make_pair(1, 1));
    ifib.insert(make_pair(3, 4));
    ifib.insert(make_pair(1, 2));
    ifib.insert(make_pair(5, 5));
    EXPECT_THAT(ifib, WhenSorted(ElementsAre(Pair(1, 1),
                                             Pair(1, 2),
                                             Pair(2, 3),
                                             Pair(3, 4),
                                             Pair(5, 5),
                                             Pair(8, 6))));
    EXPECT_THAT(ifib, Not(WhenSorted(ElementsAre(Pair(8, 6),
                                                 Pair(2, 3),
                                                 Pair(1, 1),
                                                 Pair(3, 4),
                                                 Pair(1, 2),
                                                 Pair(5, 5)))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), testing::Pair(), and testing::WhenSorted().
TEST() [346/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForNonEmptyContainer)
Definition at line 5118 of file gmock-matchers_test.cc.
{
  list<std::string> words;
  words.push_back("3");
  words.push_back("1");
  words.push_back("2");
  words.push_back("2");
  EXPECT_THAT(words, WhenSorted(ElementsAre("1", "2", "2", "3")));
  EXPECT_THAT(words, Not(WhenSorted(ElementsAre("3", "1", "2", "2"))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSorted().
TEST() [347/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForPolymorphicMatcher)
Definition at line 5163 of file gmock-matchers_test.cc.
{
    std::deque<int> d;
    d.push_back(2);
    d.push_back(1);
    EXPECT_THAT(d, WhenSorted(ElementsAre(1, 2)));
    EXPECT_THAT(d, Not(WhenSorted(ElementsAre(2, 1))));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSorted().
TEST() [348/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForStreamlike)
Definition at line 5329 of file gmock-matchers_test.cc.
{
  // Streamlike 'container' provides only minimal iterator support.
  // Its iterators are tagged with input_iterator_tag.
  const int a[5] = {2, 1, 4, 5, 3};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(s, WhenSorted(ElementsAre(1, 2, 3, 4, 5)));
  EXPECT_THAT(s, Not(WhenSorted(ElementsAre(2, 1, 4, 5, 3))));
}
References testing::ElementsAre(), EXPECT_THAT, GTEST_ARRAY_SIZE_, testing::Not(), and testing::WhenSorted().
TEST() [349/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForVectorConstRefMatcher)
Definition at line 5171 of file gmock-matchers_test.cc.
{
    std::deque<int> d;
    d.push_back(2);
    d.push_back(1);
    Matcher<const std::vector<int>&> vector_match = ElementsAre(1, 2);
    EXPECT_THAT(d, WhenSorted(vector_match));
    Matcher<const std::vector<int>&> not_vector_match = ElementsAre(2, 1);
    EXPECT_THAT(d, Not(WhenSorted(not_vector_match)));
}
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSorted().
TEST() [350/350]
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForVectorConstRefMatcherOnStreamlike)
Definition at line 5338 of file gmock-matchers_test.cc.
{
  const int a[] = {2, 1, 4, 5, 3};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  Matcher<const std::vector<int>&> vector_match = ElementsAre(1, 2, 3, 4, 5);
  EXPECT_THAT(s, WhenSorted(vector_match));
  EXPECT_THAT(s, Not(WhenSorted(ElementsAre(2, 1, 4, 5, 3))));
}
References testing::ElementsAre(), EXPECT_THAT, GTEST_ARRAY_SIZE_, testing::Not(), and testing::WhenSorted().
TEST_F() [1/40]
testing::gmock_matchers_test::TEST_F (BipartiteNonSquareTest , SimpleBacktracking)
Definition at line 6068 of file gmock-matchers_test.cc.
{
  //   .......
  // 0:-----\ :
  // 1:---\ | :
  // 2:---\ | :
  // 3:-\ | | :
  //  :.......:
  //    0 1 2
  MatchMatrix g(4, 3);
  static const int kEdges[][2] = {{0, 2}, {1, 1}, {2, 1}, {3, 0}};
  for (size_t i = 0; i < GTEST_ARRAY_SIZE_(kEdges); ++i) {
    g.SetEdge(kEdges[i][0], kEdges[i][1], true);
  }
  EXPECT_THAT(FindBacktrackingMaxBPM(g),
              ElementsAre(Pair(3, 0),
                          Pair(AnyOf(1, 2), 1),
                          Pair(0, 2))) << g.DebugString();
}
References testing::AnyOf(), testing::internal::MatchMatrix::DebugString(), testing::ElementsAre(), EXPECT_THAT, FindBacktrackingMaxBPM(), GTEST_ARRAY_SIZE_, testing::Pair(), and testing::internal::MatchMatrix::SetEdge().
TEST_F() [2/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , DoubleNearCanDescribeSelf)
Definition at line 3599 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = DoubleNear(2.0, 0.5);
  EXPECT_EQ("is approximately 2 (absolute error <= 0.5)", Describe(m1));
  EXPECT_EQ(
      "isn't approximately 2 (absolute error > 0.5)", DescribeNegation(m1));
  Matcher<double> m2 = DoubleNear(0.5, 0.5);
  EXPECT_EQ("is approximately 0.5 (absolute error <= 0.5)", Describe(m2));
  EXPECT_EQ(
      "isn't approximately 0.5 (absolute error > 0.5)", DescribeNegation(m2));
  Matcher<double> m3 = DoubleNear(nan1_, 0.0);
  EXPECT_EQ("never matches", Describe(m3));
  EXPECT_EQ("is anything", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), testing::DoubleNear(), and EXPECT_EQ.
TEST_F() [3/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , DoubleNearCannotMatchNaN)
Definition at line 3645 of file gmock-matchers_test.cc.
{
  // DoubleNear never matches NaN.
  Matcher<double> m = DoubleNear(ParentType::nan1_, 0.1);
  EXPECT_FALSE(m.Matches(nan1_));
  EXPECT_FALSE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References testing::DoubleNear(), EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST_F() [4/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , DoubleNearMatches)
Definition at line 3591 of file gmock-matchers_test.cc.
{
  TestNearMatches(&DoubleNear);
}
References testing::DoubleNear().
TEST_F() [5/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , ExplainsResultWhenMatchFails)
Definition at line 3615 of file gmock-matchers_test.cc.
{
  EXPECT_EQ("", Explain(DoubleNear(2.0, 0.1), 2.05));
  EXPECT_EQ("which is 0.2 from 2", Explain(DoubleNear(2.0, 0.1), 2.2));
  EXPECT_EQ("which is -0.3 from 2", Explain(DoubleNear(2.0, 0.1), 1.7));
  const std::string explanation =
      Explain(DoubleNear(2.1, 1e-10), 2.1 + 1.2e-10);
  // Different C++ implementations may print floating-point numbers
  // slightly differently.
  EXPECT_TRUE(explanation == "which is 1.2e-10 from 2.1" ||  // GCC
              explanation == "which is 1.2e-010 from 2.1")   // MSVC
      << " where explanation is \"" << explanation << "\".";
}
References testing::DoubleNear(), EXPECT_EQ, EXPECT_TRUE, and Explain().
TEST_F() [6/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , NanSensitiveDoubleNearApproximatelyMatchesDoubles)
Definition at line 3595 of file gmock-matchers_test.cc.
{
  TestNearMatches(&NanSensitiveDoubleNear);
}
References testing::NanSensitiveDoubleNear().
TEST_F() [7/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , NanSensitiveDoubleNearCanDescribeSelf)
Definition at line 3629 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = NanSensitiveDoubleNear(2.0, 0.5);
  EXPECT_EQ("is approximately 2 (absolute error <= 0.5)", Describe(m1));
  EXPECT_EQ(
      "isn't approximately 2 (absolute error > 0.5)", DescribeNegation(m1));
  Matcher<double> m2 = NanSensitiveDoubleNear(0.5, 0.5);
  EXPECT_EQ("is approximately 0.5 (absolute error <= 0.5)", Describe(m2));
  EXPECT_EQ(
      "isn't approximately 0.5 (absolute error > 0.5)", DescribeNegation(m2));
  Matcher<double> m3 = NanSensitiveDoubleNear(nan1_, 0.1);
  EXPECT_EQ("is NaN", Describe(m3));
  EXPECT_EQ("isn't NaN", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::NanSensitiveDoubleNear().
TEST_F() [8/40]
testing::gmock_matchers_test::TEST_F (DoubleNearTest , NanSensitiveDoubleNearCanMatchNaN)
Definition at line 3653 of file gmock-matchers_test.cc.
{
  // NanSensitiveDoubleNear will match NaN.
  Matcher<double> m = NanSensitiveDoubleNear(nan1_, 0.1);
  EXPECT_TRUE(m.Matches(nan1_));
  EXPECT_TRUE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveDoubleNear().
TEST_F() [9/40]
testing::gmock_matchers_test::TEST_F (DoubleTest , DoubleEqApproximatelyMatchesDoubles)
Definition at line 3535 of file gmock-matchers_test.cc.
{
  TestMatches(&DoubleEq);
}
References testing::DoubleEq().
TEST_F() [10/40]
testing::gmock_matchers_test::TEST_F (DoubleTest , DoubleEqCanDescribeSelf)
Definition at line 3559 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = DoubleEq(2.0);
  EXPECT_EQ("is approximately 2", Describe(m1));
  EXPECT_EQ("isn't approximately 2", DescribeNegation(m1));
  Matcher<double> m2 = DoubleEq(0.5);
  EXPECT_EQ("is approximately 0.5", Describe(m2));
  EXPECT_EQ("isn't approximately 0.5", DescribeNegation(m2));
  Matcher<double> m3 = DoubleEq(nan1_);
  EXPECT_EQ("never matches", Describe(m3));
  EXPECT_EQ("is anything", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), testing::DoubleEq(), and EXPECT_EQ.
TEST_F() [11/40]
testing::gmock_matchers_test::TEST_F (DoubleTest , DoubleEqCannotMatchNaN)
Definition at line 3543 of file gmock-matchers_test.cc.
{
  // DoubleEq never matches NaN.
  Matcher<double> m = DoubleEq(nan1_);
  EXPECT_FALSE(m.Matches(nan1_));
  EXPECT_FALSE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References testing::DoubleEq(), EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST_F() [12/40]
testing::gmock_matchers_test::TEST_F (DoubleTest , NanSensitiveDoubleEqApproximatelyMatchesDoubles)
Definition at line 3539 of file gmock-matchers_test.cc.
{
  TestMatches(&NanSensitiveDoubleEq);
}
References testing::NanSensitiveDoubleEq().
TEST_F() [13/40]
testing::gmock_matchers_test::TEST_F (DoubleTest , NanSensitiveDoubleEqCanDescribeSelf)
Definition at line 3573 of file gmock-matchers_test.cc.
{
  Matcher<double> m1 = NanSensitiveDoubleEq(2.0);
  EXPECT_EQ("is approximately 2", Describe(m1));
  EXPECT_EQ("isn't approximately 2", DescribeNegation(m1));
  Matcher<double> m2 = NanSensitiveDoubleEq(0.5);
  EXPECT_EQ("is approximately 0.5", Describe(m2));
  EXPECT_EQ("isn't approximately 0.5", DescribeNegation(m2));
  Matcher<double> m3 = NanSensitiveDoubleEq(nan1_);
  EXPECT_EQ("is NaN", Describe(m3));
  EXPECT_EQ("isn't NaN", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::NanSensitiveDoubleEq().
TEST_F() [14/40]
testing::gmock_matchers_test::TEST_F (DoubleTest , NanSensitiveDoubleEqCanMatchNaN)
Definition at line 3551 of file gmock-matchers_test.cc.
{
  // NanSensitiveDoubleEq will match NaN.
  Matcher<double> m = NanSensitiveDoubleEq(nan1_);
  EXPECT_TRUE(m.Matches(nan1_));
  EXPECT_TRUE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveDoubleEq().
TEST_F() [15/40]
testing::gmock_matchers_test::TEST_F (FloatNearTest , FloatNearCanDescribeSelf)
Definition at line 3484 of file gmock-matchers_test.cc.
{
  Matcher<float> m1 = FloatNear(2.0f, 0.5f);
  EXPECT_EQ("is approximately 2 (absolute error <= 0.5)", Describe(m1));
  EXPECT_EQ(
      "isn't approximately 2 (absolute error > 0.5)", DescribeNegation(m1));
  Matcher<float> m2 = FloatNear(0.5f, 0.5f);
  EXPECT_EQ("is approximately 0.5 (absolute error <= 0.5)", Describe(m2));
  EXPECT_EQ(
      "isn't approximately 0.5 (absolute error > 0.5)", DescribeNegation(m2));
  Matcher<float> m3 = FloatNear(nan1_, 0.0);
  EXPECT_EQ("never matches", Describe(m3));
  EXPECT_EQ("is anything", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::FloatNear().
TEST_F() [16/40]
testing::gmock_matchers_test::TEST_F (FloatNearTest , FloatNearCannotMatchNaN)
Definition at line 3516 of file gmock-matchers_test.cc.
{
  // FloatNear never matches NaN.
  Matcher<float> m = FloatNear(ParentType::nan1_, 0.1f);
  EXPECT_FALSE(m.Matches(nan1_));
  EXPECT_FALSE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References EXPECT_FALSE, testing::FloatNear(), and testing::internal::MatcherBase< T >::Matches().
TEST_F() [17/40]
testing::gmock_matchers_test::TEST_F (FloatNearTest , FloatNearMatches)
Definition at line 3476 of file gmock-matchers_test.cc.
{
  TestNearMatches(&FloatNear);
}
References testing::FloatNear().
TEST_F() [18/40]
testing::gmock_matchers_test::TEST_F (FloatNearTest , NanSensitiveFloatNearApproximatelyMatchesFloats)
Definition at line 3480 of file gmock-matchers_test.cc.
{
  TestNearMatches(&NanSensitiveFloatNear);
}
References testing::NanSensitiveFloatNear().
TEST_F() [19/40]
testing::gmock_matchers_test::TEST_F (FloatNearTest , NanSensitiveFloatNearCanDescribeSelf)
Definition at line 3500 of file gmock-matchers_test.cc.
{
  Matcher<float> m1 = NanSensitiveFloatNear(2.0f, 0.5f);
  EXPECT_EQ("is approximately 2 (absolute error <= 0.5)", Describe(m1));
  EXPECT_EQ(
      "isn't approximately 2 (absolute error > 0.5)", DescribeNegation(m1));
  Matcher<float> m2 = NanSensitiveFloatNear(0.5f, 0.5f);
  EXPECT_EQ("is approximately 0.5 (absolute error <= 0.5)", Describe(m2));
  EXPECT_EQ(
      "isn't approximately 0.5 (absolute error > 0.5)", DescribeNegation(m2));
  Matcher<float> m3 = NanSensitiveFloatNear(nan1_, 0.1f);
  EXPECT_EQ("is NaN", Describe(m3));
  EXPECT_EQ("isn't NaN", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::NanSensitiveFloatNear().
TEST_F() [20/40]
testing::gmock_matchers_test::TEST_F (FloatNearTest , NanSensitiveFloatNearCanMatchNaN)
Definition at line 3524 of file gmock-matchers_test.cc.
{
  // NanSensitiveFloatNear will match NaN.
  Matcher<float> m = NanSensitiveFloatNear(nan1_, 0.1f);
  EXPECT_TRUE(m.Matches(nan1_));
  EXPECT_TRUE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveFloatNear().
TEST_F() [21/40]
testing::gmock_matchers_test::TEST_F (FloatTest , FloatEqApproximatelyMatchesFloats)
Definition at line 3420 of file gmock-matchers_test.cc.
{
  TestMatches(&FloatEq);
}
References testing::FloatEq().
TEST_F() [22/40]
testing::gmock_matchers_test::TEST_F (FloatTest , FloatEqCanDescribeSelf)
Definition at line 3444 of file gmock-matchers_test.cc.
{
  Matcher<float> m1 = FloatEq(2.0f);
  EXPECT_EQ("is approximately 2", Describe(m1));
  EXPECT_EQ("isn't approximately 2", DescribeNegation(m1));
  Matcher<float> m2 = FloatEq(0.5f);
  EXPECT_EQ("is approximately 0.5", Describe(m2));
  EXPECT_EQ("isn't approximately 0.5", DescribeNegation(m2));
  Matcher<float> m3 = FloatEq(nan1_);
  EXPECT_EQ("never matches", Describe(m3));
  EXPECT_EQ("is anything", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::FloatEq().
TEST_F() [23/40]
testing::gmock_matchers_test::TEST_F (FloatTest , FloatEqCannotMatchNaN)
Definition at line 3428 of file gmock-matchers_test.cc.
{
  // FloatEq never matches NaN.
  Matcher<float> m = FloatEq(nan1_);
  EXPECT_FALSE(m.Matches(nan1_));
  EXPECT_FALSE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References EXPECT_FALSE, testing::FloatEq(), and testing::internal::MatcherBase< T >::Matches().
TEST_F() [24/40]
testing::gmock_matchers_test::TEST_F (FloatTest , NanSensitiveFloatEqApproximatelyMatchesFloats)
Definition at line 3424 of file gmock-matchers_test.cc.
{
  TestMatches(&NanSensitiveFloatEq);
}
References testing::NanSensitiveFloatEq().
TEST_F() [25/40]
testing::gmock_matchers_test::TEST_F (FloatTest , NanSensitiveFloatEqCanDescribeSelf)
Definition at line 3458 of file gmock-matchers_test.cc.
{
  Matcher<float> m1 = NanSensitiveFloatEq(2.0f);
  EXPECT_EQ("is approximately 2", Describe(m1));
  EXPECT_EQ("isn't approximately 2", DescribeNegation(m1));
  Matcher<float> m2 = NanSensitiveFloatEq(0.5f);
  EXPECT_EQ("is approximately 0.5", Describe(m2));
  EXPECT_EQ("isn't approximately 0.5", DescribeNegation(m2));
  Matcher<float> m3 = NanSensitiveFloatEq(nan1_);
  EXPECT_EQ("is NaN", Describe(m3));
  EXPECT_EQ("isn't NaN", DescribeNegation(m3));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and testing::NanSensitiveFloatEq().
TEST_F() [26/40]
testing::gmock_matchers_test::TEST_F (FloatTest , NanSensitiveFloatEqCanMatchNaN)
Definition at line 3436 of file gmock-matchers_test.cc.
{
  // NanSensitiveFloatEq will match NaN.
  Matcher<float> m = NanSensitiveFloatEq(nan1_);
  EXPECT_TRUE(m.Matches(nan1_));
  EXPECT_TRUE(m.Matches(nan2_));
  EXPECT_FALSE(m.Matches(1.0));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and testing::NanSensitiveFloatEq().
TEST_F() [27/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , Describe)
Definition at line 5909 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(Describe<IntVec>(UnorderedElementsAre()),
              Eq("is empty"));
  EXPECT_THAT(
      Describe<IntVec>(UnorderedElementsAre(345)),
      Eq("has 1 element and that element is equal to 345"));
  EXPECT_THAT(
      Describe<IntVec>(UnorderedElementsAre(111, 222, 333)),
      Eq("has 3 elements and there exists some permutation "
         "of elements such that:\n"
         " - element #0 is equal to 111, and\n"
         " - element #1 is equal to 222, and\n"
         " - element #2 is equal to 333"));
}
References testing::Eq(), EXPECT_THAT, and testing::UnorderedElementsAre().
TEST_F() [28/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , DescribeNegation)
Definition at line 5924 of file gmock-matchers_test.cc.
{
  EXPECT_THAT(DescribeNegation<IntVec>(UnorderedElementsAre()),
              Eq("isn't empty"));
  EXPECT_THAT(
      DescribeNegation<IntVec>(UnorderedElementsAre(345)),
      Eq("doesn't have 1 element, or has 1 element that isn't equal to 345"));
  EXPECT_THAT(
      DescribeNegation<IntVec>(UnorderedElementsAre(123, 234, 345)),
      Eq("doesn't have 3 elements, or there exists no permutation "
         "of elements such that:\n"
         " - element #0 is equal to 123, and\n"
         " - element #1 is equal to 234, and\n"
         " - element #2 is equal to 345"));
}
References testing::Eq(), EXPECT_THAT, and testing::UnorderedElementsAre().
TEST_F() [29/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageCountWrong)
Definition at line 5811 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  v.push_back(4);
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAre(1, 2, 3),
                                  v, &listener)) << listener.str();
  EXPECT_THAT(listener.str(), Eq("which has 1 element"));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [30/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageCountWrongZero)
Definition at line 5820 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAre(1, 2, 3),
                                  v, &listener)) << listener.str();
  EXPECT_THAT(listener.str(), Eq(""));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [31/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageImperfectMatchOnly)
Definition at line 5879 of file gmock-matchers_test.cc.
{
  // A situation where all elements and matchers have a match
  // associated with them, but the max matching is not perfect.
  std::vector<std::string> v;
  v.push_back("a");
  v.push_back("b");
  v.push_back("c");
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(
      UnorderedElementsAre("a", "a", AnyOf("b", "c")), v, &listener))
      << listener.str();
  std::string prefix =
      "where no permutation of the elements can satisfy all matchers, "
      "and the closest match is 2 of 3 matchers with the "
      "pairings:\n";
  // We have to be a bit loose here, because there are 4 valid max matches.
  EXPECT_THAT(
      listener.str(),
      AnyOf(prefix + "{\n  " + EMString(0, 0) +
                     ",\n  " + EMString(1, 2) + "\n}",
            prefix + "{\n  " + EMString(0, 1) +
                     ",\n  " + EMString(1, 2) + "\n}",
            prefix + "{\n  " + EMString(0, 0) +
                     ",\n  " + EMString(2, 2) + "\n}",
            prefix + "{\n  " + EMString(0, 1) +
                     ",\n  " + EMString(2, 2) + "\n}"));
}
References testing::AnyOf(), EMString(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [32/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageUnmatchedElements)
Definition at line 5841 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  v.push_back(1);
  v.push_back(2);
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAre(1, 1),
                                  v, &listener)) << listener.str();
  EXPECT_THAT(
      listener.str(),
      Eq("where the following elements don't match any matchers:\n"
         "element #1: 2"));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [33/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageUnmatchedMatcherAndElement)
Definition at line 5854 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  v.push_back(2);
  v.push_back(3);
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAre(1, 2),
                                  v, &listener)) << listener.str();
  EXPECT_THAT(
      listener.str(),
      Eq("where"
         " the following matchers don't match any elements:\n"
         "matcher #0: is equal to 1\n"
         "and"
         " where"
         " the following elements don't match any matchers:\n"
         "element #1: 3"));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [34/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageUnmatchedMatchers)
Definition at line 5828 of file gmock-matchers_test.cc.
{
  std::vector<int> v;
  v.push_back(1);
  v.push_back(1);
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAre(1, 2),
                                  v, &listener)) << listener.str();
  EXPECT_THAT(
      listener.str(),
      Eq("where the following matchers don't match any elements:\n"
         "matcher #1: is equal to 2"));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [35/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailsWhenAnElementMatchesNoMatcher)
Definition at line 5749 of file gmock-matchers_test.cc.
{
  const int a[] = {1, 2, 3};
  std::vector<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  std::vector<Matcher<int> > mv;
  mv.push_back(1);
  mv.push_back(2);
  mv.push_back(2);
  // The element with value '3' matches nothing: fail fast.
  StringMatchResultListener listener;
  EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAreArray(mv),
                                  s, &listener)) << listener.str();
}
References EXPECT_FALSE, testing::ExplainMatchResult(), GTEST_ARRAY_SIZE_, testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
TEST_F() [36/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , Performance)
Definition at line 5779 of file gmock-matchers_test.cc.
{
  std::vector<int> s;
  std::vector<Matcher<int> > mv;
  for (int i = 0; i < 100; ++i) {
    s.push_back(i);
    mv.push_back(_);
  }
  mv[50] = Eq(0);
  StringMatchResultListener listener;
  EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAreArray(mv),
                                 s, &listener)) << listener.str();
}
References testing::_, testing::Eq(), EXPECT_TRUE, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
TEST_F() [37/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , PerformanceHalfStrict)
Definition at line 5795 of file gmock-matchers_test.cc.
{
  std::vector<int> s;
  std::vector<Matcher<int> > mv;
  for (int i = 0; i < 100; ++i) {
    s.push_back(i);
    if (i & 1) {
      mv.push_back(_);
    } else {
      mv.push_back(i);
    }
  }
  StringMatchResultListener listener;
  EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAreArray(mv),
                                 s, &listener)) << listener.str();
}
References testing::_, EXPECT_TRUE, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
TEST_F() [38/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , SucceedsWhenExpected)
Definition at line 5739 of file gmock-matchers_test.cc.
{
  const int a[] = {1, 2, 3};
  std::vector<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  do {
    StringMatchResultListener listener;
    EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAre(1, 2, 3),
                                   s, &listener)) << listener.str();
  } while (std::next_permutation(s.begin(), s.end()));
}
References EXPECT_TRUE, testing::ExplainMatchResult(), GTEST_ARRAY_SIZE_, testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
TEST_F() [39/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , WorksForStreamlike)
Definition at line 5762 of file gmock-matchers_test.cc.
{
  // Streamlike 'container' provides only minimal iterator support.
  // Its iterators are tagged with input_iterator_tag, and it has no
  // size() or empty() methods.
  const int a[5] = {2, 1, 4, 5, 3};
  Streamlike<int> s(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(s, UnorderedElementsAre(1, 2, 3, 4, 5));
  EXPECT_THAT(s, Not(UnorderedElementsAre(2, 2, 3, 4, 5)));
}
References EXPECT_THAT, GTEST_ARRAY_SIZE_, testing::Not(), and testing::UnorderedElementsAre().
TEST_F() [40/40]
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , WorksWithUncopyable)
Definition at line 5731 of file gmock-matchers_test.cc.
{
  Uncopyable objs[2];
  objs[0].set_value(-3);
  objs[1].set_value(1);
  EXPECT_THAT(objs,
              UnorderedElementsAre(Truly(ValueIsPositive), UncopyableIs(-3)));
}
References EXPECT_THAT, testing::gmock_matchers_test::Uncopyable::set_value(), testing::Truly(), testing::UnorderedElementsAre(), and ValueIsPositive().
TEST_P() [1/3]
testing::gmock_matchers_test::TEST_P (BipartiteNonSquareTest , Exhaustive)
Definition at line 6088 of file gmock-matchers_test.cc.
{
  size_t nlhs = GetParam().first;
  size_t nrhs = GetParam().second;
  MatchMatrix graph(nlhs, nrhs);
  do {
    EXPECT_EQ(FindBacktrackingMaxBPM(graph).size(),
              internal::FindMaxBipartiteMatching(graph).size())
        << "graph: " << graph.DebugString()
        << "\nbacktracking: "
        << PrintToString(FindBacktrackingMaxBPM(graph))
        << "\nmax flow: "
        << PrintToString(internal::FindMaxBipartiteMatching(graph));
  } while (graph.NextGraph());
}
References testing::internal::MatchMatrix::DebugString(), EXPECT_EQ, FindBacktrackingMaxBPM(), testing::internal::FindMaxBipartiteMatching(), testing::internal::MatchMatrix::NextGraph(), and testing::PrintToString().
TEST_P() [2/3]
testing::gmock_matchers_test::TEST_P (BipartiteRandomTest , LargerNets)
Definition at line 6119 of file gmock-matchers_test.cc.
{
  int nodes = GetParam().first;
  int iters = GetParam().second;
  MatchMatrix graph(nodes, nodes);
  testing::internal::Int32 seed = GTEST_FLAG(random_seed);
  if (seed == 0) {
    seed = static_cast<testing::internal::Int32>(time(NULL));
  }
  for (; iters > 0; --iters, ++seed) {
    srand(static_cast<int>(seed));
    graph.Randomize();
    EXPECT_EQ(FindBacktrackingMaxBPM(graph).size(),
              internal::FindMaxBipartiteMatching(graph).size())
        << " graph: " << graph.DebugString()
        << "\nTo reproduce the failure, rerun the test with the flag"
           " --" << GTEST_FLAG_PREFIX_ << "random_seed=" << seed;
  }
}
References testing::internal::MatchMatrix::DebugString(), EXPECT_EQ, FindBacktrackingMaxBPM(), testing::internal::FindMaxBipartiteMatching(), GTEST_FLAG, GTEST_FLAG_PREFIX_, and testing::internal::MatchMatrix::Randomize().
TEST_P() [3/3]
testing::gmock_matchers_test::TEST_P (BipartiteTest , Exhaustive)
Definition at line 6035 of file gmock-matchers_test.cc.
{
  int nodes = GetParam();
  MatchMatrix graph(nodes, nodes);
  do {
    ElementMatcherPairs matches =
        internal::FindMaxBipartiteMatching(graph);
    EXPECT_EQ(FindBacktrackingMaxBPM(graph).size(), matches.size())
        << "graph: " << graph.DebugString();
    // Check that all elements of matches are in the graph.
    // Check that elements of first and second are unique.
    std::vector<bool> seen_element(graph.LhsSize());
    std::vector<bool> seen_matcher(graph.RhsSize());
    SCOPED_TRACE(PrintToString(matches));
    for (size_t i = 0; i < matches.size(); ++i) {
      size_t ilhs = matches[i].first;
      size_t irhs = matches[i].second;
      EXPECT_TRUE(graph.HasEdge(ilhs, irhs));
      EXPECT_FALSE(seen_element[ilhs]);
      EXPECT_FALSE(seen_matcher[irhs]);
      seen_element[ilhs] = true;
      seen_matcher[irhs] = true;
    }
  } while (graph.NextGraph());
}
References testing::internal::MatchMatrix::DebugString(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, FindBacktrackingMaxBPM(), testing::internal::FindMaxBipartiteMatching(), testing::internal::MatchMatrix::HasEdge(), testing::internal::MatchMatrix::LhsSize(), testing::internal::MatchMatrix::NextGraph(), testing::PrintToString(), testing::internal::MatchMatrix::RhsSize(), and SCOPED_TRACE.
ValueIsPositive()
bool testing::gmock_matchers_test::ValueIsPositive (const Uncopyable & x)
Definition at line 3888 of file gmock-matchers_test.cc.
{ return x.value() > 0; }
References testing::gmock_matchers_test::Uncopyable::value().
Variable Documentation
foo
const int testing::gmock_matchers_test::foo = 0
Definition at line 2918 of file gmock-matchers_test.cc.
g_bar
const int testing::gmock_matchers_test::g_bar = 1
Definition at line 522 of file gmock-matchers_test.cc.