wiNpoS: fuse_gmock_files Namespace Reference
fuse_gmock_files Namespace Reference
Functions
GetGTestRootDir (gmock_root)
ValidateGMockRootDir (gmock_root)
ValidateOutputDir (output_dir)
FuseGMockH (gmock_root, output_dir)
FuseGMockAllCcToFile (gmock_root, output_file)
FuseGMockGTestAllCc (gmock_root, output_dir)
FuseGMock (gmock_root, output_dir)
main ()
Variables
str __author__ = 'wan@google.com (Zhanyong Wan)'
DEFAULT_GMOCK_ROOT_DIR = os.path.join(os.path.dirname(__file__), '..')
gtest = fuse_gtest_files
INCLUDE_GMOCK_FILE_REGEX = re.compile(r'^\s*#\s*include\s*"(gmock/.+)"')
str GMOCK_H_SEED = 'include/gmock/gmock.h'
str GMOCK_ALL_CC_SEED = 'src/gmock-all.cc'
str GTEST_H_OUTPUT = 'gtest/gtest.h'
str GMOCK_H_OUTPUT = 'gmock/gmock.h'
str GMOCK_GTEST_ALL_CC_OUTPUT = 'gmock-gtest-all.cc'
Detailed Description
fuse_gmock_files.py v0.1.0
Fuses Google Mock and Google Test source code into two .h files and a .cc file.
SYNOPSIS
       fuse_gmock_files.py [GMOCK_ROOT_DIR] OUTPUT_DIR
       Scans GMOCK_ROOT_DIR for Google Mock and Google Test source
       code, assuming Google Test is in the GMOCK_ROOT_DIR/../googletest
       directory, and generates three files:
       OUTPUT_DIR/gtest/gtest.h, OUTPUT_DIR/gmock/gmock.h, and
       OUTPUT_DIR/gmock-gtest-all.cc.  Then you can build your tests
       by adding OUTPUT_DIR to the include search path and linking
       with OUTPUT_DIR/gmock-gtest-all.cc.  These three files contain
       everything you need to use Google Mock.  Hence you can
       "install" Google Mock by copying them to wherever you want.
       GMOCK_ROOT_DIR can be omitted and defaults to the parent
       directory of the directory holding this script.
EXAMPLES
       ./fuse_gmock_files.py fused_gmock
       ./fuse_gmock_files.py path/to/unpacked/gmock fused_gmock
This tool is experimental.  In particular, it assumes that there is no
conditional inclusion of Google Mock or Google Test headers.  Please
report any problems to googlemock@googlegroups.com.  You can read
https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md for more
information.
Function Documentation
FuseGMock()
fuse_gmock_files.FuseGMock (gmock_root, output_dir)
Fuses gtest.h, gmock.h, and gmock-gtest-all.h.
Definition at line 215 of file fuse_gmock_files.py.
def FuseGMock(gmock_root, output_dir):
  """Fuses gtest.h, gmock.h, and gmock-gtest-all.h."""
  ValidateGMockRootDir(gmock_root)
  ValidateOutputDir(output_dir)
  gtest.FuseGTestH(GetGTestRootDir(gmock_root), output_dir)
  FuseGMockH(gmock_root, output_dir)
  FuseGMockGTestAllCc(gmock_root, output_dir)
References FuseGMockGTestAllCc(), FuseGMockH(), GetGTestRootDir(), ValidateGMockRootDir(), and ValidateOutputDir().
FuseGMockAllCcToFile()
fuse_gmock_files.FuseGMockAllCcToFile (gmock_root, output_file)
Scans folder gmock_root to fuse gmock-all.cc into output_file.
Definition at line 159 of file fuse_gmock_files.py.
def FuseGMockAllCcToFile(gmock_root, output_file):
  """Scans folder gmock_root to fuse gmock-all.cc into output_file."""
  processed_files = sets.Set()
  def ProcessFile(gmock_source_file):
    """Processes the given gmock source file."""
    # We don't process the same #included file twice.
    if gmock_source_file in processed_files:
      return
    processed_files.add(gmock_source_file)
    # Reads each line in the given gmock source file.
    for line in file(os.path.join(gmock_root, gmock_source_file), 'r'):
      m = INCLUDE_GMOCK_FILE_REGEX.match(line)
      if m:
        # It's '#include "gmock/foo.h"'.  We treat it as '#include
        # "gmock/gmock.h"', as all other gmock headers are being fused
        # into gmock.h and cannot be #included directly.
        # There is no need to #include "gmock/gmock.h" more than once.
        if not GMOCK_H_SEED in processed_files:
          processed_files.add(GMOCK_H_SEED)
          output_file.write('#include "%s"\n' % (GMOCK_H_OUTPUT,))
      else:
        m = gtest.INCLUDE_GTEST_FILE_REGEX.match(line)
        if m:
          # It's '#include "gtest/..."'.
          # There is no need to #include gtest.h as it has been
          # #included by gtest-all.cc.
          pass
        else:
          m = gtest.INCLUDE_SRC_FILE_REGEX.match(line)
          if m:
            # It's '#include "src/foo"' - let's process it recursively.
            ProcessFile(m.group(1))
          else:
            # Otherwise we copy the line unchanged to the output file.
            output_file.write(line)
  ProcessFile(GMOCK_ALL_CC_SEED)
FuseGMockGTestAllCc()
fuse_gmock_files.FuseGMockGTestAllCc (gmock_root, output_dir)
Scans folder gmock_root to generate gmock-gtest-all.cc in output_dir.
Definition at line 204 of file fuse_gmock_files.py.
def FuseGMockGTestAllCc(gmock_root, output_dir):
  """Scans folder gmock_root to generate gmock-gtest-all.cc in output_dir."""
  output_file = file(os.path.join(output_dir, GMOCK_GTEST_ALL_CC_OUTPUT), 'w')
  # First, fuse gtest-all.cc into gmock-gtest-all.cc.
  gtest.FuseGTestAllCcToFile(GetGTestRootDir(gmock_root), output_file)
  # Next, append fused gmock-all.cc to gmock-gtest-all.cc.
  FuseGMockAllCcToFile(gmock_root, output_file)
  output_file.close()
References FuseGMockAllCcToFile(), and GetGTestRootDir().
FuseGMockH()
fuse_gmock_files.FuseGMockH (gmock_root, output_dir)
Scans folder gmock_root to generate gmock/gmock.h in output_dir.
Definition at line 119 of file fuse_gmock_files.py.
def FuseGMockH(gmock_root, output_dir):
  """Scans folder gmock_root to generate gmock/gmock.h in output_dir."""
  output_file = file(os.path.join(output_dir, GMOCK_H_OUTPUT), 'w')
  processed_files = sets.Set()  # Holds all gmock headers we've processed.
  def ProcessFile(gmock_header_path):
    """Processes the given gmock header file."""
    # We don't process the same header twice.
    if gmock_header_path in processed_files:
      return
    processed_files.add(gmock_header_path)
    # Reads each line in the given gmock header.
    for line in file(os.path.join(gmock_root, gmock_header_path), 'r'):
      m = INCLUDE_GMOCK_FILE_REGEX.match(line)
      if m:
        # It's '#include "gmock/..."' - let's process it recursively.
        ProcessFile('include/' + m.group(1))
      else:
        m = gtest.INCLUDE_GTEST_FILE_REGEX.match(line)
        if m:
          # It's '#include "gtest/foo.h"'.  We translate it to
          # "gtest/gtest.h", regardless of what foo is, since all
          # gtest headers are fused into gtest/gtest.h.
          # There is no need to #include gtest.h twice.
          if not gtest.GTEST_H_SEED in processed_files:
            processed_files.add(gtest.GTEST_H_SEED)
            output_file.write('#include "%s"\n' % (gtest.GTEST_H_OUTPUT,))
        else:
          # Otherwise we copy the line unchanged to the output file.
          output_file.write(line)
  ProcessFile(GMOCK_H_SEED)
  output_file.close()
GetGTestRootDir()
fuse_gmock_files.GetGTestRootDir (gmock_root)
Returns the root directory of Google Test.
Definition at line 91 of file fuse_gmock_files.py.
def GetGTestRootDir(gmock_root):
  """Returns the root directory of Google Test."""
  return os.path.join(gmock_root, '../googletest')
main()
fuse_gmock_files.main ()
Definition at line 226 of file fuse_gmock_files.py.
def main():
  argc = len(sys.argv)
  if argc == 2:
    # fuse_gmock_files.py OUTPUT_DIR
    FuseGMock(DEFAULT_GMOCK_ROOT_DIR, sys.argv[1])
  elif argc == 3:
    # fuse_gmock_files.py GMOCK_ROOT_DIR OUTPUT_DIR
    FuseGMock(sys.argv[1], sys.argv[2])
  else:
    print __doc__
    sys.exit(1)
References FuseGMock(), and main().
ValidateGMockRootDir()
fuse_gmock_files.ValidateGMockRootDir (gmock_root)
Makes sure gmock_root points to a valid gmock root directory.
The function aborts the program on failure.
Definition at line 97 of file fuse_gmock_files.py.
def ValidateGMockRootDir(gmock_root):
  """Makes sure gmock_root points to a valid gmock root directory.
  The function aborts the program on failure.
  """
  gtest.ValidateGTestRootDir(GetGTestRootDir(gmock_root))
  gtest.VerifyFileExists(gmock_root, GMOCK_H_SEED)
  gtest.VerifyFileExists(gmock_root, GMOCK_ALL_CC_SEED)
References GetGTestRootDir().
ValidateOutputDir()
fuse_gmock_files.ValidateOutputDir (output_dir)
Makes sure output_dir points to a valid output directory.
The function aborts the program on failure.
Definition at line 108 of file fuse_gmock_files.py.
def ValidateOutputDir(output_dir):
  """Makes sure output_dir points to a valid output directory.
  The function aborts the program on failure.
  """
  gtest.VerifyOutputFile(output_dir, gtest.GTEST_H_OUTPUT)
  gtest.VerifyOutputFile(output_dir, GMOCK_H_OUTPUT)
  gtest.VerifyOutputFile(output_dir, GMOCK_GTEST_ALL_CC_OUTPUT)
Variable Documentation
__author__
str fuse_gmock_files.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 62 of file fuse_gmock_files.py.
DEFAULT_GMOCK_ROOT_DIR
fuse_gmock_files.DEFAULT_GMOCK_ROOT_DIR = os.path.join(os.path.dirname(__file__), '..')
Definition at line 71 of file fuse_gmock_files.py.
GMOCK_ALL_CC_SEED
str fuse_gmock_files.GMOCK_ALL_CC_SEED = 'src/gmock-all.cc'
Definition at line 83 of file fuse_gmock_files.py.
GMOCK_GTEST_ALL_CC_OUTPUT
str fuse_gmock_files.GMOCK_GTEST_ALL_CC_OUTPUT = 'gmock-gtest-all.cc'
Definition at line 88 of file fuse_gmock_files.py.
GMOCK_H_OUTPUT
str fuse_gmock_files.GMOCK_H_OUTPUT = 'gmock/gmock.h'
Definition at line 87 of file fuse_gmock_files.py.
GMOCK_H_SEED
str fuse_gmock_files.GMOCK_H_SEED = 'include/gmock/gmock.h'
Definition at line 82 of file fuse_gmock_files.py.
gtest
fuse_gmock_files.gtest = fuse_gtest_files
Definition at line 76 of file fuse_gmock_files.py.
GTEST_H_OUTPUT
str fuse_gmock_files.GTEST_H_OUTPUT = 'gtest/gtest.h'
Definition at line 86 of file fuse_gmock_files.py.
INCLUDE_GMOCK_FILE_REGEX
fuse_gmock_files.INCLUDE_GMOCK_FILE_REGEX = re.compile(r'^\s*#\s*include\s*"(gmock/.+)"')
Definition at line 79 of file fuse_gmock_files.py.