wiNpoS: testing::internal::anonymous_namespace{gtest-printers.cc} Namespace Reference
testing::internal::anonymous_namespace{gtest-printers.cc} Namespace Reference
Functions
bool ContainsUnprintableControlCodes (const char *str, size_t length)
bool IsUTF8TrailByte (unsigned char t)
bool IsValidUTF8 (const char *str, size_t length)
void ConditionalPrintAsText (const char *str, size_t length, ostream *os)
Function Documentation
ConditionalPrintAsText()
void testing::internal::anonymous_namespace{gtest-printers.cc}::ConditionalPrintAsText (const char * str, size_t length, ostream * os)
Definition at line 415 of file gtest-printers.cc.
{
  if (!ContainsUnprintableControlCodes(str, length) &&
      IsValidUTF8(str, length)) {
    *os << "\n    As Text: \"" << str << "\"";
  }
}
References ConditionalPrintAsText(), ContainsUnprintableControlCodes(), and IsValidUTF8().
ContainsUnprintableControlCodes()
bool testing::internal::anonymous_namespace{gtest-printers.cc}::ContainsUnprintableControlCodes (const char * str, size_t length)
Definition at line 359 of file gtest-printers.cc.
{
  const unsigned char *s = reinterpret_cast<const unsigned char *>(str);
  for (size_t i = 0; i < length; i++) {
    unsigned char ch = *s++;
    if (std::iscntrl(ch)) {
        switch (ch) {
        case '\t':
        case '\n':
        case '\r':
          break;
        default:
          return true;
        }
      }
  }
  return false;
}
References ContainsUnprintableControlCodes().
IsUTF8TrailByte()
bool testing::internal::anonymous_namespace{gtest-printers.cc}::IsUTF8TrailByte (unsigned char t)
Definition at line 378 of file gtest-printers.cc.
{ return 0x80 <= t && t<= 0xbf; }
References IsUTF8TrailByte().
IsValidUTF8()
bool testing::internal::anonymous_namespace{gtest-printers.cc}::IsValidUTF8 (const char * str, size_t length)
Definition at line 380 of file gtest-printers.cc.
{
  const unsigned char *s = reinterpret_cast<const unsigned char *>(str);
  for (size_t i = 0; i < length;) {
    unsigned char lead = s[i++];
    if (lead <= 0x7f) {
      continue;  // single-byte character (ASCII) 0..7F
    }
    if (lead < 0xc2) {
      return false;  // trail byte or non-shortest form
    } else if (lead <= 0xdf && (i + 1) <= length && IsUTF8TrailByte(s[i])) {
      ++i;  // 2-byte character
    } else if (0xe0 <= lead && lead <= 0xef && (i + 2) <= length &&
               IsUTF8TrailByte(s[i]) &&
               IsUTF8TrailByte(s[i + 1]) &&
               // check for non-shortest form and surrogate
               (lead != 0xe0 || s[i] >= 0xa0) &&
               (lead != 0xed || s[i] < 0xa0)) {
      i += 2;  // 3-byte character
    } else if (0xf0 <= lead && lead <= 0xf4 && (i + 3) <= length &&
               IsUTF8TrailByte(s[i]) &&
               IsUTF8TrailByte(s[i + 1]) &&
               IsUTF8TrailByte(s[i + 2]) &&
               // check for non-shortest form
               (lead != 0xf0 || s[i] >= 0x90) &&
               (lead != 0xf4 || s[i] < 0x90)) {
      i += 3;  // 4-byte character
    } else {
      return false;
    }
  }
  return true;
}
References IsUTF8TrailByte(), and IsValidUTF8().