wiNpoS: testing::gmock_matchers_test::convertible_from_any Namespace Reference
testing::gmock_matchers_test::convertible_from_any Namespace Reference
Classes
struct ConvertibleFromAny
Functions
bool operator== (const ConvertibleFromAny &a, const ConvertibleFromAny &b)
ostream & operator<< (ostream &os, const ConvertibleFromAny &a)
TEST (MatcherCastTest, ConversionConstructorIsUsed)
TEST (MatcherCastTest, FromConvertibleFromAny)
TEST (SafeMatcherCastTest, ConversionConstructorIsUsed)
TEST (SafeMatcherCastTest, FromConvertibleFromAny)
Function Documentation
operator<<()
ostream & testing::gmock_matchers_test::convertible_from_any::operator<< (ostream & os, const ConvertibleFromAny & a)
Definition at line 774 of file gmock-matchers_test.cc.
{
  return os << a.value;
}
operator==()
bool testing::gmock_matchers_test::convertible_from_any::operator== (const ConvertibleFromAny & a, const ConvertibleFromAny & b)
Definition at line 770 of file gmock-matchers_test.cc.
{
  return a.value == b.value;
}
References testing::gmock_matchers_test::convertible_from_any::ConvertibleFromAny::value.
TEST() [1/4]
testing::gmock_matchers_test::convertible_from_any::TEST (MatcherCastTest , ConversionConstructorIsUsed)
Definition at line 778 of file gmock-matchers_test.cc.
{
  Matcher<ConvertibleFromAny> m = MatcherCast<ConvertibleFromAny>(1);
  EXPECT_TRUE(m.Matches(ConvertibleFromAny(1)));
  EXPECT_FALSE(m.Matches(ConvertibleFromAny(2)));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [2/4]
testing::gmock_matchers_test::convertible_from_any::TEST (MatcherCastTest , FromConvertibleFromAny)
Definition at line 784 of file gmock-matchers_test.cc.
{
  Matcher<ConvertibleFromAny> m =
      MatcherCast<ConvertibleFromAny>(Eq(ConvertibleFromAny(1)));
  EXPECT_TRUE(m.Matches(ConvertibleFromAny(1)));
  EXPECT_FALSE(m.Matches(ConvertibleFromAny(2)));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [3/4]
testing::gmock_matchers_test::convertible_from_any::TEST (SafeMatcherCastTest , ConversionConstructorIsUsed)
Definition at line 901 of file gmock-matchers_test.cc.
{
  Matcher<ConvertibleFromAny> m = SafeMatcherCast<ConvertibleFromAny>(1);
  EXPECT_TRUE(m.Matches(ConvertibleFromAny(1)));
  EXPECT_FALSE(m.Matches(ConvertibleFromAny(2)));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [4/4]
testing::gmock_matchers_test::convertible_from_any::TEST (SafeMatcherCastTest , FromConvertibleFromAny)
Definition at line 907 of file gmock-matchers_test.cc.
{
  Matcher<ConvertibleFromAny> m =
      SafeMatcherCast<ConvertibleFromAny>(Eq(ConvertibleFromAny(1)));
  EXPECT_TRUE(m.Matches(ConvertibleFromAny(1)));
  EXPECT_FALSE(m.Matches(ConvertibleFromAny(2)));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().