wiNpoS: anonymous_namespace{gmock-actions_test.cc} Namespace Reference
anonymous_namespace{gmock-actions_test.cc} Namespace Reference
Classes
struct Base
struct Derived
class DestinationType
class Foo
class FromType
struct IntegerVectorWrapper
class IsNotZero
class MockClass
class MyActionImpl
class MyDefaultConstructible
class MyNonDefaultConstructible
class NullaryFunctor
class ReturnSecondArgumentAction
class ReturnZeroFromNullaryFunctionAction
class SetErrnoAndReturnTest
class SourceType
class ToType
class VoidNullaryFunctor
Typedefs
typedef int MyGlobalFunction(bool, int)
Functions
TEST (BuiltInDefaultValueTest, IsNullForPointerTypes)
TEST (BuiltInDefaultValueTest, ExistsForPointerTypes)
TEST (BuiltInDefaultValueTest, IsZeroForNumericTypes)
TEST (BuiltInDefaultValueTest, ExistsForNumericTypes)
TEST (BuiltInDefaultValueTest, IsFalseForBool)
TEST (BuiltInDefaultValueTest, BoolExists)
TEST (BuiltInDefaultValueTest, IsEmptyStringForString)
TEST (BuiltInDefaultValueTest, ExistsForString)
TEST (BuiltInDefaultValueTest, WorksForConstTypes)
TEST (BuiltInDefaultValueTest, DoesNotExistForNonDefaultConstructibleType)
TEST (BuiltInDefaultValueDeathTest, IsUndefinedForReferences)
TEST (BuiltInDefaultValueDeathTest, IsUndefinedForNonDefaultConstructibleType)
TEST (DefaultValueTest, IsInitiallyUnset)
TEST (DefaultValueTest, CanBeSetAndUnset)
TEST (DefaultValueDeathTest, GetReturnsBuiltInDefaultValueWhenUnset)
TEST (DefaultValueTest, GetWorksForVoid)
TEST (DefaultValueOfReferenceTest, IsInitiallyUnset)
TEST (DefaultValueOfReferenceTest, IsInitiallyNotExisting)
TEST (DefaultValueOfReferenceTest, CanBeSetAndUnset)
TEST (DefaultValueOfReferenceDeathTest, GetReturnsBuiltInDefaultValueWhenUnset)
TEST (ActionInterfaceTest, CanBeImplementedByDefiningPerform)
TEST (ActionInterfaceTest, MakeAction)
TEST (ActionTest, CanBeConstructedFromActionInterface)
TEST (ActionTest, DelegatesWorkToActionInterface)
TEST (ActionTest, IsCopyable)
TEST (ActionTest, CanBeConvertedToOtherActionType)
PolymorphicAction< ReturnSecondArgumentAction > ReturnSecondArgument ()
PolymorphicAction< ReturnZeroFromNullaryFunctionAction > ReturnZeroFromNullaryFunction ()
TEST (MakePolymorphicActionTest, ConstructsActionFromImpl)
TEST (MakePolymorphicActionTest, WorksWhenPerformHasOneTemplateParameter)
TEST (ReturnTest, WorksForVoid)
TEST (ReturnTest, ReturnsGivenValue)
TEST (ReturnTest, AcceptsStringLiteral)
TEST (ReturnTest, SupportsWrapperReturnType)
TEST (ReturnTest, IsCovariant)
TEST (ReturnTest, ConvertsArgumentWhenConverted)
TEST (ReturnTest, CanConvertArgumentUsingNonConstTypeCastOperator)
TEST (ReturnNullTest, WorksInPointerReturningFunction)
TEST (ReturnRefTest, WorksForReference)
TEST (ReturnRefTest, IsCovariant)
TEST (ReturnRefOfCopyTest, WorksForReference)
TEST (ReturnRefOfCopyTest, IsCovariant)
TEST (DoDefaultTest, ReturnsBuiltInDefaultValueByDefault)
TEST (DoDefaultDeathTest, DiesForUnknowType)
void VoidFunc (bool)
TEST (DoDefaultDeathTest, DiesIfUsedInCompositeAction)
TEST (DoDefaultTest, ReturnsUserSpecifiedPerTypeDefaultValueWhenThereIsOne)
TEST (DoDefaultTest, DoesWhatOnCallSpecifies)
TEST (DoDefaultTest, CannotBeUsedInOnCall)
TEST (SetArgPointeeTest, SetsTheNthPointee)
TEST (SetArgPointeeTest, AcceptsStringLiteral)
TEST (SetArgPointeeTest, AcceptsWideStringLiteral)
TEST (SetArgPointeeTest, AcceptsCharPointer)
TEST (SetArgPointeeTest, AcceptsWideCharPointer)
TEST (SetArgumentPointeeTest, SetsTheNthPointee)
int Nullary ()
void VoidNullary ()
TEST (InvokeWithoutArgsTest, Function)
TEST (InvokeWithoutArgsTest, Functor)
TEST (InvokeWithoutArgsTest, Method)
TEST (IgnoreResultTest, PolymorphicAction)
int ReturnOne ()
TEST (IgnoreResultTest, MonomorphicAction)
MyNonDefaultConstructible ReturnMyNonDefaultConstructible (double)
TEST (IgnoreResultTest, ActionReturningClass)
TEST (AssignTest, Int)
TEST (AssignTest, String)
TEST (AssignTest, CompatibleTypes)
TEST_F (SetErrnoAndReturnTest, Int)
TEST_F (SetErrnoAndReturnTest, Ptr)
TEST_F (SetErrnoAndReturnTest, CompatibleTypes)
TEST (ByRefTest, IsCopyable)
TEST (ByRefTest, ConstValue)
TEST (ByRefTest, NonConstValue)
TEST (ByRefTest, ExplicitType)
TEST (ByRefTest, PrintsCorrectly)
Variables
bool g_done = false
Typedef Documentation
MyGlobalFunction
typedef int anonymous_namespace{gmock-actions_test.cc}::MyGlobalFunction(bool, int)
Definition at line 386 of file gmock-actions_test.cc.
Function Documentation
Nullary()
int anonymous_namespace{gmock-actions_test.cc}::Nullary ()
Definition at line 1117 of file gmock-actions_test.cc.
{ return 1; }
ReturnMyNonDefaultConstructible()
MyNonDefaultConstructible anonymous_namespace{gmock-actions_test.cc}::ReturnMyNonDefaultConstructible (double)
Definition at line 1207 of file gmock-actions_test.cc.
{
  g_done = true;
  return MyNonDefaultConstructible(42);
}
References g_done.
ReturnOne()
int anonymous_namespace{gmock-actions_test.cc}::ReturnOne ()
Definition at line 1193 of file gmock-actions_test.cc.
                {
  g_done = true;
  return 1;
}
References g_done.
ReturnSecondArgument()
PolymorphicAction< ReturnSecondArgumentAction > anonymous_namespace{gmock-actions_test.cc}::ReturnSecondArgument ()
Definition at line 504 of file gmock-actions_test.cc.
{
  return MakePolymorphicAction(ReturnSecondArgumentAction());
}
ReturnZeroFromNullaryFunction()
PolymorphicAction< ReturnZeroFromNullaryFunctionAction > anonymous_namespace{gmock-actions_test.cc}::ReturnZeroFromNullaryFunction ()
Definition at line 509 of file gmock-actions_test.cc.
{
  return MakePolymorphicAction(ReturnZeroFromNullaryFunctionAction());
}
TEST() [1/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ActionInterfaceTest , CanBeImplementedByDefiningPerform)
Definition at line 395 of file gmock-actions_test.cc.
{
  MyActionImpl my_action_impl;
  (void)my_action_impl;
}
TEST() [2/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ActionInterfaceTest , MakeAction)
Definition at line 400 of file gmock-actions_test.cc.
{
  Action<MyGlobalFunction> action = MakeAction(new MyActionImpl);
  // When exercising the Perform() method of Action<F>, we must pass
  // it a tuple whose size and type are compatible with F's argument
  // types.  For example, if F is int(), then Perform() takes a
  // 0-tuple; if F is void(bool, int), then Perform() takes a
  // tuple<bool, int>, and so on.
  EXPECT_EQ(5, action.Perform(make_tuple(true, 5)));
}
References EXPECT_EQ.
TEST() [3/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ActionTest , CanBeConstructedFromActionInterface)
Definition at line 413 of file gmock-actions_test.cc.
{
  Action<MyGlobalFunction> action(new MyActionImpl);
}
TEST() [4/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ActionTest , CanBeConvertedToOtherActionType)
Definition at line 465 of file gmock-actions_test.cc.
{
  const Action<bool(int)> a1(new IsNotZero);  // NOLINT
  const Action<int(char)> a2 = Action<int(char)>(a1);  // NOLINT
  EXPECT_EQ(1, a2.Perform(make_tuple('a')));
  EXPECT_EQ(0, a2.Perform(make_tuple('\0')));
}
References EXPECT_EQ, and testing::Action< F >::Perform().
TEST() [5/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ActionTest , DelegatesWorkToActionInterface)
Definition at line 418 of file gmock-actions_test.cc.
{
  const Action<MyGlobalFunction> action(new MyActionImpl);
  EXPECT_EQ(5, action.Perform(make_tuple(true, 5)));
  EXPECT_EQ(0, action.Perform(make_tuple(false, 1)));
}
References EXPECT_EQ.
TEST() [6/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ActionTest , IsCopyable)
Definition at line 426 of file gmock-actions_test.cc.
{
  Action<MyGlobalFunction> a1(new MyActionImpl);
  Action<MyGlobalFunction> a2(a1);  // Tests the copy constructor.
  // a1 should continue to work after being copied from.
  EXPECT_EQ(5, a1.Perform(make_tuple(true, 5)));
  EXPECT_EQ(0, a1.Perform(make_tuple(false, 1)));
  // a2 should work like the action it was copied from.
  EXPECT_EQ(5, a2.Perform(make_tuple(true, 5)));
  EXPECT_EQ(0, a2.Perform(make_tuple(false, 1)));
  a2 = a1;  // Tests the assignment operator.
  // a1 should continue to work after being copied from.
  EXPECT_EQ(5, a1.Perform(make_tuple(true, 5)));
  EXPECT_EQ(0, a1.Perform(make_tuple(false, 1)));
  // a2 should work like the action it was copied from.
  EXPECT_EQ(5, a2.Perform(make_tuple(true, 5)));
  EXPECT_EQ(0, a2.Perform(make_tuple(false, 1)));
}
References EXPECT_EQ, and testing::Action< F >::Perform().
TEST() [7/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (AssignTest , CompatibleTypes)
Definition at line 1234 of file gmock-actions_test.cc.
{
  double x = 0;
  Action<void(int)> a = Assign(&x, 5);
  a.Perform(make_tuple(0));
  EXPECT_DOUBLE_EQ(5, x);
}
References EXPECT_DOUBLE_EQ.
TEST() [8/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (AssignTest , Int)
Definition at line 1220 of file gmock-actions_test.cc.
                      {
  int x = 0;
  Action<void(int)> a = Assign(&x, 5);
  a.Perform(make_tuple(0));
  EXPECT_EQ(5, x);
}
References EXPECT_EQ.
TEST() [9/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (AssignTest , String)
Definition at line 1227 of file gmock-actions_test.cc.
{
  ::std::string x;
  Action<void(void)> a = Assign(&x, "Hello, world");
  a.Perform(make_tuple());
  EXPECT_EQ("Hello, world", x);
}
References EXPECT_EQ.
TEST() [10/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueDeathTest , IsUndefinedForNonDefaultConstructibleType)
Definition at line 257 of file gmock-actions_test.cc.
{
  EXPECT_DEATH_IF_SUPPORTED({
    BuiltInDefaultValue<MyNonDefaultConstructible>::Get();
  }, "");
}
References EXPECT_DEATH_IF_SUPPORTED.
TEST() [11/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueDeathTest , IsUndefinedForReferences)
Definition at line 248 of file gmock-actions_test.cc.
{
  EXPECT_DEATH_IF_SUPPORTED({
    BuiltInDefaultValue<int&>::Get();
  }, "");
  EXPECT_DEATH_IF_SUPPORTED({
    BuiltInDefaultValue<const char&>::Get();
  }, "");
}
References EXPECT_DEATH_IF_SUPPORTED.
TEST() [12/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , BoolExists)
Definition at line 175 of file gmock-actions_test.cc.
{
  EXPECT_TRUE(BuiltInDefaultValue<bool>::Exists());
}
References EXPECT_TRUE.
TEST() [13/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , DoesNotExistForNonDefaultConstructibleType)
Definition at line 243 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(BuiltInDefaultValue<MyNonDefaultConstructible>::Exists());
}
References EXPECT_FALSE.
TEST() [14/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , ExistsForNumericTypes)
Definition at line 143 of file gmock-actions_test.cc.
{
  EXPECT_TRUE(BuiltInDefaultValue<unsigned char>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<signed char>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<char>::Exists());
#if GMOCK_HAS_SIGNED_WCHAR_T_
  EXPECT_TRUE(BuiltInDefaultValue<unsigned wchar_t>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<signed wchar_t>::Exists());
#endif
#if GMOCK_WCHAR_T_IS_NATIVE_
  EXPECT_TRUE(BuiltInDefaultValue<wchar_t>::Exists());
#endif
  EXPECT_TRUE(BuiltInDefaultValue<unsigned short>::Exists());  // NOLINT
  EXPECT_TRUE(BuiltInDefaultValue<signed short>::Exists());  // NOLINT
  EXPECT_TRUE(BuiltInDefaultValue<short>::Exists());  // NOLINT
  EXPECT_TRUE(BuiltInDefaultValue<unsigned int>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<signed int>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<int>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<unsigned long>::Exists());  // NOLINT
  EXPECT_TRUE(BuiltInDefaultValue<signed long>::Exists());  // NOLINT
  EXPECT_TRUE(BuiltInDefaultValue<long>::Exists());  // NOLINT
  EXPECT_TRUE(BuiltInDefaultValue<UInt64>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<Int64>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<float>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<double>::Exists());
}
References EXPECT_TRUE.
TEST() [15/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , ExistsForPointerTypes)
Definition at line 103 of file gmock-actions_test.cc.
{
  EXPECT_TRUE(BuiltInDefaultValue<int*>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<const char*>::Exists());
  EXPECT_TRUE(BuiltInDefaultValue<void*>::Exists());
}
References EXPECT_TRUE.
TEST() [16/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , ExistsForString)
Definition at line 191 of file gmock-actions_test.cc.
{
#if GTEST_HAS_GLOBAL_STRING
  EXPECT_TRUE(BuiltInDefaultValue< ::string>::Exists());
#endif  // GTEST_HAS_GLOBAL_STRING
  EXPECT_TRUE(BuiltInDefaultValue< ::std::string>::Exists());
}
References EXPECT_TRUE.
TEST() [17/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , IsEmptyStringForString)
Definition at line 181 of file gmock-actions_test.cc.
{
#if GTEST_HAS_GLOBAL_STRING
  EXPECT_EQ("", BuiltInDefaultValue< ::string>::Get());
#endif  // GTEST_HAS_GLOBAL_STRING
  EXPECT_EQ("", BuiltInDefaultValue< ::std::string>::Get());
}
References EXPECT_EQ.
TEST() [18/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , IsFalseForBool)
Definition at line 170 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(BuiltInDefaultValue<bool>::Get());
}
References EXPECT_FALSE.
TEST() [19/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , IsNullForPointerTypes)
Definition at line 96 of file gmock-actions_test.cc.
{
  EXPECT_TRUE(BuiltInDefaultValue<int*>::Get() == NULL);
  EXPECT_TRUE(BuiltInDefaultValue<const char*>::Get() == NULL);
  EXPECT_TRUE(BuiltInDefaultValue<void*>::Get() == NULL);
}
References EXPECT_TRUE.
TEST() [20/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , IsZeroForNumericTypes)
Definition at line 111 of file gmock-actions_test.cc.
{
  EXPECT_EQ(0U, BuiltInDefaultValue<unsigned char>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<signed char>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<char>::Get());
#if GMOCK_HAS_SIGNED_WCHAR_T_
  EXPECT_EQ(0U, BuiltInDefaultValue<unsigned wchar_t>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<signed wchar_t>::Get());
#endif
#if GMOCK_WCHAR_T_IS_NATIVE_
#if !defined(__WCHAR_UNSIGNED__)
  EXPECT_EQ(0, BuiltInDefaultValue<wchar_t>::Get());
#else
  EXPECT_EQ(0U, BuiltInDefaultValue<wchar_t>::Get());
#endif
#endif
  EXPECT_EQ(0U, BuiltInDefaultValue<unsigned short>::Get());  // NOLINT
  EXPECT_EQ(0, BuiltInDefaultValue<signed short>::Get());  // NOLINT
  EXPECT_EQ(0, BuiltInDefaultValue<short>::Get());  // NOLINT
  EXPECT_EQ(0U, BuiltInDefaultValue<unsigned int>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<signed int>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<int>::Get());
  EXPECT_EQ(0U, BuiltInDefaultValue<unsigned long>::Get());  // NOLINT
  EXPECT_EQ(0, BuiltInDefaultValue<signed long>::Get());  // NOLINT
  EXPECT_EQ(0, BuiltInDefaultValue<long>::Get());  // NOLINT
  EXPECT_EQ(0U, BuiltInDefaultValue<UInt64>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<Int64>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<float>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<double>::Get());
}
References EXPECT_EQ.
TEST() [21/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (BuiltInDefaultValueTest , WorksForConstTypes)
Definition at line 201 of file gmock-actions_test.cc.
{
  EXPECT_EQ("", BuiltInDefaultValue<const std::string>::Get());
  EXPECT_EQ(0, BuiltInDefaultValue<const int>::Get());
  EXPECT_TRUE(BuiltInDefaultValue<char* const>::Get() == NULL);
  EXPECT_FALSE(BuiltInDefaultValue<const bool>::Get());
}
References EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
TEST() [22/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ByRefTest , ConstValue)
Definition at line 1296 of file gmock-actions_test.cc.
{
  const int n = 0;
  // int& ref = ByRef(n);  // This shouldn't compile - we have a
                           // negative compilation test to catch it.
  const int& const_ref = ByRef(n);
  EXPECT_EQ(&n, &const_ref);
}
References EXPECT_EQ.
TEST() [23/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ByRefTest , ExplicitType)
Definition at line 1318 of file gmock-actions_test.cc.
{
  int n = 0;
  const int& r1 = ByRef<const int>(n);
  EXPECT_EQ(&n, &r1);
  // ByRef<char>(n);  // This shouldn't compile - we have a negative
                      // compilation test to catch it.
  Derived d;
  Derived& r2 = ByRef<Derived>(d);
  EXPECT_EQ(&d, &r2);
  const Derived& r3 = ByRef<const Derived>(d);
  EXPECT_EQ(&d, &r3);
  Base& r4 = ByRef<Base>(d);
  EXPECT_EQ(&d, &r4);
  const Base& r5 = ByRef<const Base>(d);
  EXPECT_EQ(&d, &r5);
  // The following shouldn't compile - we have a negative compilation
  // test for it.
  //
  // Base b;
  // ByRef<Derived>(b);
}
References EXPECT_EQ.
TEST() [24/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ByRefTest , IsCopyable)
Definition at line 1273 of file gmock-actions_test.cc.
{
  const std::string s1 = "Hi";
  const std::string s2 = "Hello";
  ::testing::internal::ReferenceWrapper<const std::string> ref_wrapper =
      ByRef(s1);
  const std::string& r1 = ref_wrapper;
  EXPECT_EQ(&s1, &r1);
  // Assigns a new value to ref_wrapper.
  ref_wrapper = ByRef(s2);
  const std::string& r2 = ref_wrapper;
  EXPECT_EQ(&s2, &r2);
  ::testing::internal::ReferenceWrapper<const std::string> ref_wrapper1 =
      ByRef(s1);
  // Copies ref_wrapper1 to ref_wrapper.
  ref_wrapper = ref_wrapper1;
  const std::string& r3 = ref_wrapper;
  EXPECT_EQ(&s1, &r3);
}
References EXPECT_EQ.
TEST() [25/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ByRefTest , NonConstValue)
Definition at line 1305 of file gmock-actions_test.cc.
{
  int n = 0;
  // ByRef(n) can be used as either an int&,
  int& ref = ByRef(n);
  EXPECT_EQ(&n, &ref);
  // or a const int&.
  const int& const_ref = ByRef(n);
  EXPECT_EQ(&n, &const_ref);
}
References EXPECT_EQ.
TEST() [26/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ByRefTest , PrintsCorrectly)
Definition at line 1347 of file gmock-actions_test.cc.
{
  int n = 42;
  ::std::stringstream expected, actual;
  testing::internal::UniversalPrinter<const int&>::Print(n, &expected);
  testing::internal::UniversalPrint(ByRef(n), &actual);
  EXPECT_EQ(expected.str(), actual.str());
}
References EXPECT_EQ, testing::internal::UniversalPrinter< T >::Print(), and testing::internal::UniversalPrint().
TEST() [27/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueDeathTest , GetReturnsBuiltInDefaultValueWhenUnset)
Definition at line 298 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(DefaultValue<int>::IsSet());
  EXPECT_TRUE(DefaultValue<int>::Exists());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible>::IsSet());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible>::Exists());
  EXPECT_EQ(0, DefaultValue<int>::Get());
  EXPECT_DEATH_IF_SUPPORTED({
    DefaultValue<MyNonDefaultConstructible>::Get();
  }, "");
}
References EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
TEST() [28/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueOfReferenceDeathTest , GetReturnsBuiltInDefaultValueWhenUnset)
Definition at line 371 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(DefaultValue<int&>::IsSet());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible&>::IsSet());
  EXPECT_DEATH_IF_SUPPORTED({
    DefaultValue<int&>::Get();
  }, "");
  EXPECT_DEATH_IF_SUPPORTED({
    DefaultValue<MyNonDefaultConstructible>::Get();
  }, "");
}
References EXPECT_DEATH_IF_SUPPORTED, and EXPECT_FALSE.
TEST() [29/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueOfReferenceTest , CanBeSetAndUnset)
Definition at line 346 of file gmock-actions_test.cc.
{
  int n = 1;
  DefaultValue<const int&>::Set(n);
  MyNonDefaultConstructible x(42);
  DefaultValue<MyNonDefaultConstructible&>::Set(x);
  EXPECT_TRUE(DefaultValue<const int&>::Exists());
  EXPECT_TRUE(DefaultValue<MyNonDefaultConstructible&>::Exists());
  EXPECT_EQ(&n, &(DefaultValue<const int&>::Get()));
  EXPECT_EQ(&x, &(DefaultValue<MyNonDefaultConstructible&>::Get()));
  DefaultValue<const int&>::Clear();
  DefaultValue<MyNonDefaultConstructible&>::Clear();
  EXPECT_FALSE(DefaultValue<const int&>::Exists());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible&>::Exists());
  EXPECT_FALSE(DefaultValue<const int&>::IsSet());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible&>::IsSet());
}
References EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
TEST() [30/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueOfReferenceTest , IsInitiallyNotExisting)
Definition at line 339 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(DefaultValue<int&>::Exists());
  EXPECT_FALSE(DefaultValue<MyDefaultConstructible&>::Exists());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible&>::Exists());
}
References EXPECT_FALSE.
TEST() [31/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueOfReferenceTest , IsInitiallyUnset)
Definition at line 332 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(DefaultValue<int&>::IsSet());
  EXPECT_FALSE(DefaultValue<MyDefaultConstructible&>::IsSet());
  EXPECT_FALSE(DefaultValue<MyNonDefaultConstructible&>::IsSet());
}
References EXPECT_FALSE.
TEST() [32/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueTest , CanBeSetAndUnset)
Definition at line 271 of file gmock-actions_test.cc.
{
  EXPECT_TRUE(DefaultValue<int>::Exists());
  EXPECT_FALSE(DefaultValue<const MyNonDefaultConstructible>::Exists());
  DefaultValue<int>::Set(1);
  DefaultValue<const MyNonDefaultConstructible>::Set(
      MyNonDefaultConstructible(42));
  EXPECT_EQ(1, DefaultValue<int>::Get());
  EXPECT_EQ(42, DefaultValue<const MyNonDefaultConstructible>::Get().value());
  EXPECT_TRUE(DefaultValue<int>::Exists());
  EXPECT_TRUE(DefaultValue<const MyNonDefaultConstructible>::Exists());
  DefaultValue<int>::Clear();
  DefaultValue<const MyNonDefaultConstructible>::Clear();
  EXPECT_FALSE(DefaultValue<int>::IsSet());
  EXPECT_FALSE(DefaultValue<const MyNonDefaultConstructible>::IsSet());
  EXPECT_TRUE(DefaultValue<int>::Exists());
  EXPECT_FALSE(DefaultValue<const MyNonDefaultConstructible>::Exists());
}
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, and anonymous_namespace{gmock-actions_test.cc}::MyDefaultConstructible::value().
TEST() [33/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueTest , GetWorksForVoid)
Definition at line 325 of file gmock-actions_test.cc.
{
  return DefaultValue<void>::Get();
}
TEST() [34/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DefaultValueTest , IsInitiallyUnset)
Definition at line 264 of file gmock-actions_test.cc.
{
  EXPECT_FALSE(DefaultValue<int>::IsSet());
  EXPECT_FALSE(DefaultValue<MyDefaultConstructible>::IsSet());
  EXPECT_FALSE(DefaultValue<const MyNonDefaultConstructible>::IsSet());
}
References EXPECT_FALSE.
TEST() [35/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DoDefaultDeathTest , DiesForUnknowType)
Definition at line 737 of file gmock-actions_test.cc.
{
  MockClass mock;
  EXPECT_CALL(mock, Foo())
      .WillRepeatedly(DoDefault());
#if GTEST_HAS_EXCEPTIONS
  EXPECT_ANY_THROW(mock.Foo());
#else
  EXPECT_DEATH_IF_SUPPORTED({
    mock.Foo();
  }, "");
#endif
}
References EXPECT_ANY_THROW, EXPECT_CALL, and EXPECT_DEATH_IF_SUPPORTED.
TEST() [36/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DoDefaultDeathTest , DiesIfUsedInCompositeAction)
Definition at line 755 of file gmock-actions_test.cc.
{
  MockClass mock;
  EXPECT_CALL(mock, IntFunc(_))
      .WillRepeatedly(DoAll(Invoke(VoidFunc),
                            DoDefault()));
  // Ideally we should verify the error message as well.  Sadly,
  // EXPECT_DEATH() can only capture stderr, while Google Mock's
  // errors are printed on stdout.  Therefore we have to settle for
  // not verifying the message.
  EXPECT_DEATH_IF_SUPPORTED({
    mock.IntFunc(true);
  }, "");
}
References EXPECT_CALL, EXPECT_DEATH_IF_SUPPORTED, and VoidFunc().
TEST() [37/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DoDefaultTest , CannotBeUsedInOnCall)
Definition at line 792 of file gmock-actions_test.cc.
{
  MockClass mock;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    ON_CALL(mock, IntFunc(_))
      .WillByDefault(DoDefault());
  }, "DoDefault() cannot be used in ON_CALL()");
}
References EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [38/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DoDefaultTest , DoesWhatOnCallSpecifies)
Definition at line 782 of file gmock-actions_test.cc.
{
  MockClass mock;
  ON_CALL(mock, IntFunc(_))
      .WillByDefault(Return(2));
  EXPECT_CALL(mock, IntFunc(_))
      .WillOnce(DoDefault());
  EXPECT_EQ(2, mock.IntFunc(false));
}
References EXPECT_CALL, EXPECT_EQ, and ON_CALL.
TEST() [39/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DoDefaultTest , ReturnsBuiltInDefaultValueByDefault)
Definition at line 728 of file gmock-actions_test.cc.
{
  MockClass mock;
  EXPECT_CALL(mock, IntFunc(_))
      .WillOnce(DoDefault());
  EXPECT_EQ(0, mock.IntFunc(true));
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [40/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (DoDefaultTest , ReturnsUserSpecifiedPerTypeDefaultValueWhenThereIsOne)
Definition at line 772 of file gmock-actions_test.cc.
{
  DefaultValue<int>::Set(1);
  MockClass mock;
  EXPECT_CALL(mock, IntFunc(_))
      .WillOnce(DoDefault());
  EXPECT_EQ(1, mock.IntFunc(false));
  DefaultValue<int>::Clear();
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [41/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (IgnoreResultTest , ActionReturningClass)
Definition at line 1212 of file gmock-actions_test.cc.
{
  g_done = false;
  Action<void(int)> a =
      IgnoreResult(Invoke(ReturnMyNonDefaultConstructible));  // NOLINT
  a.Perform(make_tuple(2));
  EXPECT_TRUE(g_done);
}
References EXPECT_TRUE, g_done, and ReturnMyNonDefaultConstructible().
TEST() [42/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (IgnoreResultTest , MonomorphicAction)
Definition at line 1198 of file gmock-actions_test.cc.
{
  g_done = false;
  Action<void()> a = IgnoreResult(Invoke(ReturnOne));
  a.Perform(make_tuple());
  EXPECT_TRUE(g_done);
}
References EXPECT_TRUE, g_done, and ReturnOne().
TEST() [43/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (IgnoreResultTest , PolymorphicAction)
Definition at line 1186 of file gmock-actions_test.cc.
{
  Action<void(int)> a = IgnoreResult(Return(5));  // NOLINT
  a.Perform(make_tuple(1));
}
TEST() [44/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (InvokeWithoutArgsTest , Function)
Definition at line 1143 of file gmock-actions_test.cc.
{
  // As an action that takes one argument.
  Action<int(int)> a = InvokeWithoutArgs(Nullary);  // NOLINT
  EXPECT_EQ(1, a.Perform(make_tuple(2)));
  // As an action that takes two arguments.
  Action<int(int, double)> a2 = InvokeWithoutArgs(Nullary);  // NOLINT
  EXPECT_EQ(1, a2.Perform(make_tuple(2, 3.5)));
  // As an action that returns void.
  Action<void(int)> a3 = InvokeWithoutArgs(VoidNullary);  // NOLINT
  g_done = false;
  a3.Perform(make_tuple(1));
  EXPECT_TRUE(g_done);
}
References EXPECT_EQ, EXPECT_TRUE, g_done, Nullary(), testing::Action< F >::Perform(), and VoidNullary().
TEST() [45/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (InvokeWithoutArgsTest , Functor)
Definition at line 1160 of file gmock-actions_test.cc.
{
  // As an action that takes no argument.
  Action<int()> a = InvokeWithoutArgs(NullaryFunctor());  // NOLINT
  EXPECT_EQ(2, a.Perform(make_tuple()));
  // As an action that takes three arguments.
  Action<int(int, double, char)> a2 =  // NOLINT
      InvokeWithoutArgs(NullaryFunctor());
  EXPECT_EQ(2, a2.Perform(make_tuple(3, 3.5, 'a')));
  // As an action that returns void.
  Action<void()> a3 = InvokeWithoutArgs(VoidNullaryFunctor());
  g_done = false;
  a3.Perform(make_tuple());
  EXPECT_TRUE(g_done);
}
References EXPECT_EQ, EXPECT_TRUE, g_done, and testing::Action< F >::Perform().
TEST() [46/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (InvokeWithoutArgsTest , Method)
Definition at line 1178 of file gmock-actions_test.cc.
{
  Foo foo;
  Action<int(bool, char)> a =  // NOLINT
      InvokeWithoutArgs(&foo, &Foo::Nullary);
  EXPECT_EQ(123, a.Perform(make_tuple(true, 'a')));
}
References EXPECT_EQ.
TEST() [47/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (MakePolymorphicActionTest , ConstructsActionFromImpl)
Definition at line 515 of file gmock-actions_test.cc.
{
  Action<int(bool, int, double)> a1 = ReturnSecondArgument();  // NOLINT
  EXPECT_EQ(5, a1.Perform(make_tuple(false, 5, 2.0)));
}
References EXPECT_EQ, testing::Action< F >::Perform(), and ReturnSecondArgument().
TEST() [48/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (MakePolymorphicActionTest , WorksWhenPerformHasOneTemplateParameter)
Definition at line 522 of file gmock-actions_test.cc.
{
  Action<int()> a1 = ReturnZeroFromNullaryFunction();
  EXPECT_EQ(0, a1.Perform(make_tuple()));
  Action<void*()> a2 = ReturnZeroFromNullaryFunction();
  EXPECT_TRUE(a2.Perform(make_tuple()) == NULL);
}
References EXPECT_EQ, EXPECT_TRUE, testing::Action< F >::Perform(), and ReturnZeroFromNullaryFunction().
TEST() [49/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnNullTest , WorksInPointerReturningFunction)
Definition at line 642 of file gmock-actions_test.cc.
{
  const Action<int*()> a1 = ReturnNull();
  EXPECT_TRUE(a1.Perform(make_tuple()) == NULL);
  const Action<const char*(bool)> a2 = ReturnNull();  // NOLINT
  EXPECT_TRUE(a2.Perform(make_tuple(true)) == NULL);
}
References EXPECT_TRUE.
TEST() [50/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnRefOfCopyTest , IsCovariant)
Definition at line 695 of file gmock-actions_test.cc.
{
  Base base;
  Derived derived;
  Action<Base&()> a = ReturnRefOfCopy(base);
  EXPECT_NE(&base, &a.Perform(make_tuple()));
  a = ReturnRefOfCopy(derived);
  EXPECT_NE(&derived, &a.Perform(make_tuple()));
}
References EXPECT_NE.
TEST() [51/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnRefOfCopyTest , WorksForReference)
Definition at line 682 of file gmock-actions_test.cc.
{
  int n = 42;
  const Action<const int&()> ret = ReturnRefOfCopy(n);
  EXPECT_NE(&n, &ret.Perform(make_tuple()));
  EXPECT_EQ(42, ret.Perform(make_tuple()));
  n = 43;
  EXPECT_NE(&n, &ret.Perform(make_tuple()));
  EXPECT_EQ(42, ret.Perform(make_tuple()));
}
References EXPECT_EQ, and EXPECT_NE.
TEST() [52/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnRefTest , IsCovariant)
Definition at line 671 of file gmock-actions_test.cc.
{
  Base base;
  Derived derived;
  Action<Base&()> a = ReturnRef(base);
  EXPECT_EQ(&base, &a.Perform(make_tuple()));
  a = ReturnRef(derived);
  EXPECT_EQ(&derived, &a.Perform(make_tuple()));
}
References EXPECT_EQ.
TEST() [53/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnRefTest , WorksForReference)
Definition at line 663 of file gmock-actions_test.cc.
{
  const int n = 0;
  const Action<const int&(bool)> ret = ReturnRef(n);  // NOLINT
  EXPECT_EQ(&n, &ret.Perform(make_tuple(true)));
}
References EXPECT_EQ.
TEST() [54/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , AcceptsStringLiteral)
Definition at line 547 of file gmock-actions_test.cc.
{
  Action<const char*()> a1 = Return("Hello");
  EXPECT_STREQ("Hello", a1.Perform(make_tuple()));
  Action<std::string()> a2 = Return("world");
  EXPECT_EQ("world", a2.Perform(make_tuple()));
}
References EXPECT_EQ, EXPECT_STREQ, and testing::Action< F >::Perform().
TEST() [55/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , CanConvertArgumentUsingNonConstTypeCastOperator)
Definition at line 636 of file gmock-actions_test.cc.
{
  SourceType s;
  Action<DestinationType()> action(Return(s));
}
TEST() [56/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , ConvertsArgumentWhenConverted)
Definition at line 616 of file gmock-actions_test.cc.
{
  bool converted = false;
  FromType x(&converted);
  Action<ToType()> action(Return(x));
  EXPECT_TRUE(converted) << "Return must convert its argument in its own "
                         << "conversion operator.";
  converted = false;
  action.Perform(tuple<>());
  EXPECT_FALSE(converted) << "Action must NOT convert its argument "
                          << "when performed.";
}
References anonymous_namespace{gmock-actions_test.cc}::FromType::converted(), EXPECT_FALSE, and EXPECT_TRUE.
TEST() [57/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , IsCovariant)
Definition at line 585 of file gmock-actions_test.cc.
{
  Base base;
  Derived derived;
  Action<Base*()> ret = Return(&base);
  EXPECT_EQ(&base, ret.Perform(make_tuple()));
  ret = Return(&derived);
  EXPECT_EQ(&derived, ret.Perform(make_tuple()));
}
References EXPECT_EQ.
TEST() [58/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , ReturnsGivenValue)
Definition at line 538 of file gmock-actions_test.cc.
{
  Action<int()> ret = Return(1);  // NOLINT
  EXPECT_EQ(1, ret.Perform(make_tuple()));
  ret = Return(-5);
  EXPECT_EQ(-5, ret.Perform(make_tuple()));
}
References EXPECT_EQ, and testing::Action< F >::Perform().
TEST() [59/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , SupportsWrapperReturnType)
Definition at line 563 of file gmock-actions_test.cc.
{
  // Initialize vector of integers.
  std::vector<int> v;
  for (int i = 0; i < 5; ++i) v.push_back(i);
  // Return() called with 'v' as argument. The Action will return the same data
  // as 'v' (copy) but it will be wrapped in an IntegerVectorWrapper.
  Action<IntegerVectorWrapper()> a = Return(v);
  const std::vector<int>& result = *(a.Perform(make_tuple()).v);
  EXPECT_THAT(result, ::testing::ElementsAre(0, 1, 2, 3, 4));
}
References testing::ElementsAre(), and EXPECT_THAT.
TEST() [60/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (ReturnTest , WorksForVoid)
Definition at line 532 of file gmock-actions_test.cc.
{
  const Action<void(int)> ret = Return();  // NOLINT
  return ret.Perform(make_tuple(1));
}
References testing::Action< F >::Perform().
TEST() [61/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (SetArgPointeeTest , AcceptsCharPointer)
Definition at line 859 of file gmock-actions_test.cc.
{
  typedef void MyFunction(bool, std::string*, const char**);
  const char* const hi = "hi";
  Action<MyFunction> a = SetArgPointee<1>(hi);
  std::string str;
  const char* ptr = NULL;
  a.Perform(make_tuple(true, &str, &ptr));
  EXPECT_EQ("hi", str);
  EXPECT_TRUE(ptr == NULL);
  char world_array[] = "world";
  char* const world = world_array;
  a = SetArgPointee<2>(world);
  str = "";
  a.Perform(make_tuple(true, &str, &ptr));
  EXPECT_EQ("", str);
  EXPECT_EQ(world, ptr);
}
References EXPECT_EQ, and EXPECT_TRUE.
TEST() [62/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (SetArgPointeeTest , AcceptsStringLiteral)
Definition at line 823 of file gmock-actions_test.cc.
{
  typedef void MyFunction(std::string*, const char**);
  Action<MyFunction> a = SetArgPointee<0>("hi");
  std::string str;
  const char* ptr = NULL;
  a.Perform(make_tuple(&str, &ptr));
  EXPECT_EQ("hi", str);
  EXPECT_TRUE(ptr == NULL);
  a = SetArgPointee<1>("world");
  str = "";
  a.Perform(make_tuple(&str, &ptr));
  EXPECT_EQ("", str);
  EXPECT_STREQ("world", ptr);
}
References EXPECT_EQ, EXPECT_STREQ, and EXPECT_TRUE.
TEST() [63/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (SetArgPointeeTest , AcceptsWideCharPointer)
Definition at line 878 of file gmock-actions_test.cc.
{
  typedef void MyFunction(bool, const wchar_t**);
  const wchar_t* const hi = L"hi";
  Action<MyFunction> a = SetArgPointee<1>(hi);
  const wchar_t* ptr = NULL;
  a.Perform(make_tuple(true, &ptr));
  EXPECT_EQ(hi, ptr);
# if GTEST_HAS_STD_WSTRING
  typedef void MyStringFunction(bool, std::wstring*);
  wchar_t world_array[] = L"world";
  wchar_t* const world = world_array;
  Action<MyStringFunction> a2 = SetArgPointee<1>(world);
  std::wstring str;
  a2.Perform(make_tuple(true, &str));
  EXPECT_EQ(world_array, str);
# endif
}
References EXPECT_EQ, and testing::Action< F >::Perform().
TEST() [64/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (SetArgPointeeTest , AcceptsWideStringLiteral)
Definition at line 839 of file gmock-actions_test.cc.
{
  typedef void MyFunction(const wchar_t**);
  Action<MyFunction> a = SetArgPointee<0>(L"world");
  const wchar_t* ptr = NULL;
  a.Perform(make_tuple(&ptr));
  EXPECT_STREQ(L"world", ptr);
# if GTEST_HAS_STD_WSTRING
  typedef void MyStringFunction(std::wstring*);
  Action<MyStringFunction> a2 = SetArgPointee<0>(L"world");
  std::wstring str = L"";
  a2.Perform(make_tuple(&str));
  EXPECT_EQ(L"world", str);
# endif
}
References EXPECT_EQ, EXPECT_STREQ, and testing::Action< F >::Perform().
TEST() [65/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (SetArgPointeeTest , SetsTheNthPointee)
Definition at line 802 of file gmock-actions_test.cc.
{
  typedef void MyFunction(bool, int*, char*);
  Action<MyFunction> a = SetArgPointee<1>(2);
  int n = 0;
  char ch = '\0';
  a.Perform(make_tuple(true, &n, &ch));
  EXPECT_EQ(2, n);
  EXPECT_EQ('\0', ch);
  a = SetArgPointee<2>('a');
  n = 0;
  ch = '\0';
  a.Perform(make_tuple(true, &n, &ch));
  EXPECT_EQ(0, n);
  EXPECT_EQ('a', ch);
}
References EXPECT_EQ.
TEST() [66/66]
anonymous_namespace{gmock-actions_test.cc}::TEST (SetArgumentPointeeTest , SetsTheNthPointee)
Definition at line 999 of file gmock-actions_test.cc.
{
  typedef void MyFunction(bool, int*, char*);
  Action<MyFunction> a = SetArgumentPointee<1>(2);
  int n = 0;
  char ch = '\0';
  a.Perform(make_tuple(true, &n, &ch));
  EXPECT_EQ(2, n);
  EXPECT_EQ('\0', ch);
  a = SetArgumentPointee<2>('a');
  n = 0;
  ch = '\0';
  a.Perform(make_tuple(true, &n, &ch));
  EXPECT_EQ(0, n);
  EXPECT_EQ('a', ch);
}
References EXPECT_EQ.
TEST_F() [1/3]
anonymous_namespace{gmock-actions_test.cc}::TEST_F (SetErrnoAndReturnTest , CompatibleTypes)
Definition at line 1262 of file gmock-actions_test.cc.
{
  Action<double()> a = SetErrnoAndReturn(EINVAL, 5);
  EXPECT_DOUBLE_EQ(5.0, a.Perform(make_tuple()));
  EXPECT_EQ(EINVAL, errno);
}
References EXPECT_DOUBLE_EQ, and EXPECT_EQ.
TEST_F() [2/3]
anonymous_namespace{gmock-actions_test.cc}::TEST_F (SetErrnoAndReturnTest , Int)
Definition at line 1249 of file gmock-actions_test.cc.
{
  Action<int(void)> a = SetErrnoAndReturn(ENOTTY, -5);
  EXPECT_EQ(-5, a.Perform(make_tuple()));
  EXPECT_EQ(ENOTTY, errno);
}
References EXPECT_EQ.
TEST_F() [3/3]
anonymous_namespace{gmock-actions_test.cc}::TEST_F (SetErrnoAndReturnTest , Ptr)
Definition at line 1255 of file gmock-actions_test.cc.
{
  int x;
  Action<int*(void)> a = SetErrnoAndReturn(ENOTTY, &x);
  EXPECT_EQ(&x, a.Perform(make_tuple()));
  EXPECT_EQ(ENOTTY, errno);
}
References EXPECT_EQ.
VoidFunc()
void anonymous_namespace{gmock-actions_test.cc}::VoidFunc (bool)
Definition at line 753 of file gmock-actions_test.cc.
{}
VoidNullary()
void anonymous_namespace{gmock-actions_test.cc}::VoidNullary ()
Definition at line 1125 of file gmock-actions_test.cc.
{ g_done = true; }
References g_done.
Variable Documentation
g_done
bool anonymous_namespace{gmock-actions_test.cc}::g_done = false
Definition at line 1124 of file gmock-actions_test.cc.