wiNpoS: testing::internal::anonymous_namespace{gtest-options_test.cc} Namespace Reference
testing::internal::anonymous_namespace{gtest-options_test.cc} Namespace Reference
Classes
class XmlOutputChangeDirTest
Functions
FilePath GetAbsolutePathOf (const FilePath &relative_path)
TEST (XmlOutputTest, GetOutputFormatDefault)
TEST (XmlOutputTest, GetOutputFormat)
TEST (XmlOutputTest, GetOutputFileDefault)
TEST (XmlOutputTest, GetOutputFileSingleFile)
TEST (XmlOutputTest, GetOutputFileFromDirectoryPath)
TEST (OutputFileHelpersTest, GetCurrentExecutableName)
TEST_F (XmlOutputChangeDirTest, PreserveOriginalWorkingDirWithDefault)
TEST_F (XmlOutputChangeDirTest, PreserveOriginalWorkingDirWithDefaultXML)
TEST_F (XmlOutputChangeDirTest, PreserveOriginalWorkingDirWithRelativeFile)
TEST_F (XmlOutputChangeDirTest, PreserveOriginalWorkingDirWithRelativePath)
TEST_F (XmlOutputChangeDirTest, PreserveOriginalWorkingDirWithAbsoluteFile)
TEST_F (XmlOutputChangeDirTest, PreserveOriginalWorkingDirWithAbsolutePath)
Function Documentation
GetAbsolutePathOf()
FilePath testing::internal::anonymous_namespace{gtest-options_test.cc}::GetAbsolutePathOf (const FilePath & relative_path)
Definition at line 55 of file gtest-options_test.cc.
{
  return FilePath::ConcatPaths(FilePath::GetCurrentDir(), relative_path);
}
References testing::internal::FilePath::ConcatPaths(), GetAbsolutePathOf(), and testing::internal::FilePath::GetCurrentDir().
TEST() [1/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST (OutputFileHelpersTest , GetCurrentExecutableName)
Definition at line 98 of file gtest-options_test.cc.
{
  const std::string exe_str = GetCurrentExecutableName().string();
#if GTEST_OS_WINDOWS
  const bool success =
      _strcmpi("gtest-options_test", exe_str.c_str()) == 0 ||
      _strcmpi("gtest-options-ex_test", exe_str.c_str()) == 0 ||
      _strcmpi("gtest_all_test", exe_str.c_str()) == 0 ||
      _strcmpi("gtest_dll_test", exe_str.c_str()) == 0;
#elif GTEST_OS_FUCHSIA
  const bool success = exe_str == "app";
#else
  // TODO(wan@google.com): remove the hard-coded "lt-" prefix when
  //   Chandler Carruth's libtool replacement is ready.
  const bool success =
      exe_str == "gtest-options_test" ||
      exe_str == "gtest_all_test" ||
      exe_str == "lt-gtest_all_test" ||
      exe_str == "gtest_dll_test";
#endif  // GTEST_OS_WINDOWS
  if (!success)
    FAIL() << "GetCurrentExecutableName() returns " << exe_str;
}
References FAIL, testing::internal::GetCurrentExecutableName(), and testing::internal::FilePath::string().
TEST() [2/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST (XmlOutputTest , GetOutputFileDefault)
Definition at line 71 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "";
  EXPECT_EQ(GetAbsolutePathOf(FilePath("test_detail.xml")).string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
}
References EXPECT_EQ, GetAbsolutePathOf(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and GTEST_FLAG.
TEST() [3/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST (XmlOutputTest , GetOutputFileFromDirectoryPath)
Definition at line 83 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "xml:path" GTEST_PATH_SEP_;
  const std::string expected_output_file =
      GetAbsolutePathOf(
          FilePath(std::string("path") + GTEST_PATH_SEP_ +
                   GetCurrentExecutableName().string() + ".xml")).string();
  const std::string& output_file =
      UnitTestOptions::GetAbsolutePathToOutputFile();
#if GTEST_OS_WINDOWS
  EXPECT_STRCASEEQ(expected_output_file.c_str(), output_file.c_str());
#else
  EXPECT_EQ(expected_output_file, output_file.c_str());
#endif
}
References EXPECT_EQ, EXPECT_STRCASEEQ, GetAbsolutePathOf(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::GetCurrentExecutableName(), GTEST_FLAG, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [4/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST (XmlOutputTest , GetOutputFileSingleFile)
Definition at line 77 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "xml:filename.abc";
  EXPECT_EQ(GetAbsolutePathOf(FilePath("filename.abc")).string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
}
References EXPECT_EQ, GetAbsolutePathOf(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and GTEST_FLAG.
TEST() [5/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST (XmlOutputTest , GetOutputFormat)
Definition at line 66 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "xml:filename";
  EXPECT_STREQ("xml", UnitTestOptions::GetOutputFormat().c_str());
}
References EXPECT_STREQ, testing::internal::UnitTestOptions::GetOutputFormat(), and GTEST_FLAG.
TEST() [6/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST (XmlOutputTest , GetOutputFormatDefault)
Definition at line 61 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "";
  EXPECT_STREQ("", UnitTestOptions::GetOutputFormat().c_str());
}
References EXPECT_STREQ, testing::internal::UnitTestOptions::GetOutputFormat(), and GTEST_FLAG.
TEST_F() [1/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST_F (XmlOutputChangeDirTest , PreserveOriginalWorkingDirWithAbsoluteFile)
Definition at line 177 of file gtest-options_test.cc.
{
#if GTEST_OS_WINDOWS
  GTEST_FLAG(output) = "xml:c:\\tmp\\filename.abc";
  EXPECT_EQ(FilePath("c:\\tmp\\filename.abc").string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
#else
  GTEST_FLAG(output) ="xml:/tmp/filename.abc";
  EXPECT_EQ(FilePath("/tmp/filename.abc").string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
#endif
}
References EXPECT_EQ, testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and GTEST_FLAG.
TEST_F() [2/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST_F (XmlOutputChangeDirTest , PreserveOriginalWorkingDirWithAbsolutePath)
Definition at line 189 of file gtest-options_test.cc.
{
#if GTEST_OS_WINDOWS
  const std::string path = "c:\\tmp\\";
#else
  const std::string path = "/tmp/";
#endif
  GTEST_FLAG(output) = "xml:" + path;
  const std::string expected_output_file =
      path + GetCurrentExecutableName().string() + ".xml";
  const std::string& output_file =
      UnitTestOptions::GetAbsolutePathToOutputFile();
#if GTEST_OS_WINDOWS
  EXPECT_STRCASEEQ(expected_output_file.c_str(), output_file.c_str());
#else
  EXPECT_EQ(expected_output_file, output_file.c_str());
#endif
}
References EXPECT_EQ, EXPECT_STRCASEEQ, testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::GetCurrentExecutableName(), GTEST_FLAG, and testing::internal::FilePath::string().
TEST_F() [3/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST_F (XmlOutputChangeDirTest , PreserveOriginalWorkingDirWithDefault)
Definition at line 140 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "";
  EXPECT_EQ(FilePath::ConcatPaths(original_working_dir_,
                                  FilePath("test_detail.xml")).string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and GTEST_FLAG.
TEST_F() [4/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST_F (XmlOutputChangeDirTest , PreserveOriginalWorkingDirWithDefaultXML)
Definition at line 147 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "xml";
  EXPECT_EQ(FilePath::ConcatPaths(original_working_dir_,
                                  FilePath("test_detail.xml")).string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and GTEST_FLAG.
TEST_F() [5/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST_F (XmlOutputChangeDirTest , PreserveOriginalWorkingDirWithRelativeFile)
Definition at line 154 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "xml:filename.abc";
  EXPECT_EQ(FilePath::ConcatPaths(original_working_dir_,
                                  FilePath("filename.abc")).string(),
            UnitTestOptions::GetAbsolutePathToOutputFile());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and GTEST_FLAG.
TEST_F() [6/6]
testing::internal::anonymous_namespace{gtest-options_test.cc}::TEST_F (XmlOutputChangeDirTest , PreserveOriginalWorkingDirWithRelativePath)
Definition at line 161 of file gtest-options_test.cc.
{
  GTEST_FLAG(output) = "xml:path" GTEST_PATH_SEP_;
  const std::string expected_output_file =
      FilePath::ConcatPaths(
          original_working_dir_,
          FilePath(std::string("path") + GTEST_PATH_SEP_ +
                   GetCurrentExecutableName().string() + ".xml")).string();
  const std::string& output_file =
      UnitTestOptions::GetAbsolutePathToOutputFile();
#if GTEST_OS_WINDOWS
  EXPECT_STRCASEEQ(expected_output_file.c_str(), output_file.c_str());
#else
  EXPECT_EQ(expected_output_file, output_file.c_str());
#endif
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, EXPECT_STRCASEEQ, testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::GetCurrentExecutableName(), GTEST_FLAG, GTEST_PATH_SEP_, and testing::internal::FilePath::string().