wiNpoS: gtest_test_utils Namespace Reference
gtest_test_utils Namespace Reference
Classes
class Subprocess
Functions
SetEnvVar (env_var, value)
_ParseAndStripGTestFlags (argv)
GetFlag (flag)
GetSourceDir ()
GetBuildDir ()
_RemoveTempDir ()
GetTempDir ()
GetTestExecutablePath (executable_name, build_dir=None)
GetExitStatus (exit_code)
Main ()
Variables
str __author__ = 'wan@google.com (Zhanyong Wan)'
str IS_LINUX = 'Linux'
str IS_WINDOWS = 'nt'
str IS_CYGWIN = 'posix' and 'CYGWIN' in os.uname()[0]
_test_module = unittest
bool _SUBPROCESS_MODULE_AVAILABLE = True
str GTEST_OUTPUT_VAR_NAME = 'GTEST_OUTPUT'
str PREMATURE_EXIT_FILE_ENV_VAR = 'TEST_PREMATURE_EXIT_FILE'
environ = os.environ.copy()
TestCase = _test_module.TestCase
dict _flag_map
bool _gtest_flags_are_parsed = False
_temp_dir = None
Detailed Description
Unit test utilities for Google C++ Testing and Mocking Framework.
Function Documentation
_ParseAndStripGTestFlags()
gtest_test_utils._ParseAndStripGTestFlags (argv) protected
Parses and strips Google Test flags from argv.  This is idempotent.
Definition at line 86 of file gtest_test_utils.py.
def _ParseAndStripGTestFlags(argv):
  """Parses and strips Google Test flags from argv.  This is idempotent."""
  # Suppresses the lint complaint about a global variable since we need it
  # here to maintain module-wide state.
  global _gtest_flags_are_parsed  # pylint: disable-msg=W0603
  if _gtest_flags_are_parsed:
    return
  _gtest_flags_are_parsed = True
  for flag in _flag_map:
    # The environment variable overrides the default value.
    if flag.upper() in os.environ:
      _flag_map[flag] = os.environ[flag.upper()]
    # The command line flag overrides the environment variable.
    i = 1  # Skips the program name.
    while i < len(argv):
      prefix = '--' + flag + '='
      if argv[i].startswith(prefix):
        _flag_map[flag] = argv[i][len(prefix):]
        del argv[i]
        break
      else:
        # We don't increment i in case we just found a --gtest_* flag
        # and removed it from argv.
        i += 1
_RemoveTempDir()
gtest_test_utils._RemoveTempDir () protected
Definition at line 140 of file gtest_test_utils.py.
def _RemoveTempDir():
  if _temp_dir:
    shutil.rmtree(_temp_dir, ignore_errors=True)
GetBuildDir()
gtest_test_utils.GetBuildDir ()
Returns the absolute path of the directory where the test binaries are.
Definition at line 132 of file gtest_test_utils.py.
def GetBuildDir():
  """Returns the absolute path of the directory where the test binaries are."""
  return os.path.abspath(GetFlag('build_dir'))
References GetFlag().
GetExitStatus()
gtest_test_utils.GetExitStatus (exit_code)
Returns the argument to exit(), or -1 if exit() wasn't called.
Args:
  exit_code: the result value of os.system(command).
Definition at line 185 of file gtest_test_utils.py.
def GetExitStatus(exit_code):
  """Returns the argument to exit(), or -1 if exit() wasn't called.
  Args:
    exit_code: the result value of os.system(command).
  """
  if os.name == 'nt':
    # On Windows, os.WEXITSTATUS() doesn't work and os.system() returns
    # the argument to exit() directly.
    return exit_code
  else:
    # On Unix, os.WEXITSTATUS() must be used to extract the exit status
    # from the result of os.system().
    if os.WIFEXITED(exit_code):
      return os.WEXITSTATUS(exit_code)
    else:
      return -1
GetFlag()
gtest_test_utils.GetFlag (flag)
Returns the value of the given flag.
Definition at line 115 of file gtest_test_utils.py.
def GetFlag(flag):
  """Returns the value of the given flag."""
  # In case GetFlag() is called before Main(), we always call
  # _ParseAndStripGTestFlags() here to make sure the --gtest_* flags
  # are parsed.
  _ParseAndStripGTestFlags(sys.argv)
  return _flag_map[flag]
References _ParseAndStripGTestFlags().
GetSourceDir()
gtest_test_utils.GetSourceDir ()
Returns the absolute path of the directory where the .py files are.
Definition at line 126 of file gtest_test_utils.py.
def GetSourceDir():
  """Returns the absolute path of the directory where the .py files are."""
  return os.path.abspath(GetFlag('source_dir'))
References GetFlag().
GetTempDir()
gtest_test_utils.GetTempDir ()
Definition at line 147 of file gtest_test_utils.py.
def GetTempDir():
  global _temp_dir
  if not _temp_dir:
    _temp_dir = tempfile.mkdtemp()
  return _temp_dir
GetTestExecutablePath()
gtest_test_utils.GetTestExecutablePath (executable_name, build_dir = None)
Returns the absolute path of the test binary given its name.
The function will print a message and abort the program if the resulting file
doesn't exist.
Args:
  executable_name: name of the test binary that the test script runs.
  build_dir:       directory where to look for executables, by default
                   the result of GetBuildDir().
Returns:
  The absolute path of the test binary.
Definition at line 154 of file gtest_test_utils.py.
def GetTestExecutablePath(executable_name, build_dir=None):
  """Returns the absolute path of the test binary given its name.
  The function will print a message and abort the program if the resulting file
  doesn't exist.
  Args:
    executable_name: name of the test binary that the test script runs.
    build_dir:       directory where to look for executables, by default
                     the result of GetBuildDir().
  Returns:
    The absolute path of the test binary.
  """
  path = os.path.abspath(os.path.join(build_dir or GetBuildDir(),
                                      executable_name))
  if (IS_WINDOWS or IS_CYGWIN) and not path.endswith('.exe'):
    path += '.exe'
  if not os.path.exists(path):
    message = (
        'Unable to find the test binary "%s". Please make sure to provide\n'
        'a path to the binary via the --build_dir flag or the BUILD_DIR\n'
        'environment variable.' % path)
    print >> sys.stderr, message
    sys.exit(1)
  return path
References GetBuildDir().
Main()
gtest_test_utils.Main ()
Runs the unit test.
Definition at line 304 of file gtest_test_utils.py.
def Main():
  """Runs the unit test."""
  # We must call _ParseAndStripGTestFlags() before calling
  # unittest.main().  Otherwise the latter will be confused by the
  # --gtest_* flags.
  _ParseAndStripGTestFlags(sys.argv)
  # The tested binaries should not be writing XML output files unless the
  # script explicitly instructs them to.
  # TODO(vladl@google.com): Move this into Subprocess when we implement
  # passing environment into it as a parameter.
  if GTEST_OUTPUT_VAR_NAME in os.environ:
    del os.environ[GTEST_OUTPUT_VAR_NAME]
  _test_module.main()
References _ParseAndStripGTestFlags().
SetEnvVar()
gtest_test_utils.SetEnvVar (env_var, value)
Sets/unsets an environment variable to a given value.
Definition at line 65 of file gtest_test_utils.py.
def SetEnvVar(env_var, value):
  """Sets/unsets an environment variable to a given value."""
  if value is not None:
    environ[env_var] = value
  elif env_var in environ:
    del environ[env_var]
# Here we expose a class from a particular module, depending on the
# environment. The comment suppresses the 'Invalid variable name' lint
# complaint.
Variable Documentation
__author__
str gtest_test_utils.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 34 of file gtest_test_utils.py.
_flag_map
dict gtest_test_utils._flag_map protected
Initial value:
=  {'source_dir': os.path.dirname(sys.argv[0]),
             'build_dir': os.path.dirname(sys.argv[0])}
Definition at line 81 of file gtest_test_utils.py.
_gtest_flags_are_parsed
bool gtest_test_utils._gtest_flags_are_parsed = False protected
Definition at line 83 of file gtest_test_utils.py.
_SUBPROCESS_MODULE_AVAILABLE
bool gtest_test_utils._SUBPROCESS_MODULE_AVAILABLE = True protected
Definition at line 51 of file gtest_test_utils.py.
_temp_dir
gtest_test_utils._temp_dir = None protected
Definition at line 138 of file gtest_test_utils.py.
_test_module
gtest_test_utils._test_module = unittest protected
Definition at line 47 of file gtest_test_utils.py.
environ
gtest_test_utils.environ = os.environ.copy()
Definition at line 62 of file gtest_test_utils.py.
GTEST_OUTPUT_VAR_NAME
str gtest_test_utils.GTEST_OUTPUT_VAR_NAME = 'GTEST_OUTPUT'
Definition at line 57 of file gtest_test_utils.py.
IS_CYGWIN
str gtest_test_utils.IS_CYGWIN = 'posix' and 'CYGWIN' in os.uname()[0]
Definition at line 41 of file gtest_test_utils.py.
IS_LINUX
str gtest_test_utils.IS_LINUX = 'Linux'
Definition at line 39 of file gtest_test_utils.py.
IS_WINDOWS
str gtest_test_utils.IS_WINDOWS = 'nt'
Definition at line 40 of file gtest_test_utils.py.
PREMATURE_EXIT_FILE_ENV_VAR
str gtest_test_utils.PREMATURE_EXIT_FILE_ENV_VAR = 'TEST_PREMATURE_EXIT_FILE'
Definition at line 60 of file gtest_test_utils.py.
TestCase
gtest_test_utils.TestCase = _test_module.TestCase
Definition at line 77 of file gtest_test_utils.py.