wiNpoS: testing::internal::anonymous_namespace{gtest-filepath_test.cc} Namespace Reference
testing::internal::anonymous_namespace{gtest-filepath_test.cc} Namespace Reference
Classes
class DirectoryCreationTest
Functions
TEST (GetCurrentDirTest, ReturnsCurrentDir)
TEST (IsEmptyTest, ReturnsTrueForEmptyPath)
TEST (IsEmptyTest, ReturnsFalseForNonEmptyPath)
TEST (RemoveDirectoryNameTest, WhenEmptyName)
TEST (RemoveDirectoryNameTest, ButNoDirectory)
TEST (RemoveDirectoryNameTest, RootFileShouldGiveFileName)
TEST (RemoveDirectoryNameTest, WhereThereIsNoFileName)
TEST (RemoveDirectoryNameTest, ShouldGiveFileName)
TEST (RemoveDirectoryNameTest, ShouldAlsoGiveFileName)
TEST (RemoveFileNameTest, EmptyName)
TEST (RemoveFileNameTest, ButNoFile)
TEST (RemoveFileNameTest, GivesDirName)
TEST (RemoveFileNameTest, GivesDirAndSubDirName)
TEST (RemoveFileNameTest, GivesRootDir)
TEST (MakeFileNameTest, GenerateWhenNumberIsZero)
TEST (MakeFileNameTest, GenerateFileNameNumberGtZero)
TEST (MakeFileNameTest, GenerateFileNameWithSlashNumberIsZero)
TEST (MakeFileNameTest, GenerateFileNameWithSlashNumberGtZero)
TEST (MakeFileNameTest, GenerateWhenNumberIsZeroAndDirIsEmpty)
TEST (MakeFileNameTest, GenerateWhenNumberIsNotZeroAndDirIsEmpty)
TEST (ConcatPathsTest, WorksWhenDirDoesNotEndWithPathSep)
TEST (ConcatPathsTest, WorksWhenPath1EndsWithPathSep)
TEST (ConcatPathsTest, Path1BeingEmpty)
TEST (ConcatPathsTest, Path2BeingEmpty)
TEST (ConcatPathsTest, BothPathBeingEmpty)
TEST (ConcatPathsTest, Path1ContainsPathSep)
TEST (ConcatPathsTest, Path2ContainsPathSep)
TEST (ConcatPathsTest, Path2EndsWithPathSep)
TEST (RemoveTrailingPathSeparatorTest, EmptyString)
TEST (RemoveTrailingPathSeparatorTest, FileNoSlashString)
TEST (RemoveTrailingPathSeparatorTest, ShouldRemoveTrailingSeparator)
TEST (RemoveTrailingPathSeparatorTest, ShouldRemoveLastSeparator)
TEST (RemoveTrailingPathSeparatorTest, ShouldReturnUnmodified)
TEST (DirectoryTest, RootDirectoryExists)
TEST (DirectoryTest, EmptyPathDirectoryDoesNotExist)
TEST (DirectoryTest, CurrentDirectoryExists)
TEST (NormalizeTest, MultipleConsecutiveSepaparatorsInMidstring)
TEST (NormalizeTest, MultipleConsecutiveSepaparatorsAtStringStart)
TEST (NormalizeTest, MultipleConsecutiveSepaparatorsAtStringEnd)
TEST (AssignmentOperatorTest, DefaultAssignedToNonDefault)
TEST (AssignmentOperatorTest, NonDefaultAssignedToDefault)
TEST (AssignmentOperatorTest, ConstAssignedToNonConst)
TEST_F (DirectoryCreationTest, CreateDirectoriesRecursively)
TEST_F (DirectoryCreationTest, CreateDirectoriesForAlreadyExistingPath)
TEST_F (DirectoryCreationTest, CreateDirectoriesAndUniqueFilename)
TEST_F (DirectoryCreationTest, CreateDirectoriesFail)
TEST (NoDirectoryCreationTest, CreateNoDirectoriesForDefaultXmlFile)
TEST (FilePathTest, DefaultConstructor)
TEST (FilePathTest, CharAndCopyConstructors)
TEST (FilePathTest, StringConstructor)
TEST (FilePathTest, Set)
TEST (FilePathTest, ToString)
TEST (FilePathTest, RemoveExtension)
TEST (FilePathTest, RemoveExtensionWhenThereIsNoExtension)
TEST (FilePathTest, IsDirectory)
TEST (FilePathTest, IsAbsolutePath)
TEST (FilePathTest, IsRootDirectory)
Function Documentation
TEST() [1/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (AssignmentOperatorTest , ConstAssignedToNonConst)
Definition at line 474 of file gtest-filepath_test.cc.
{
  const FilePath const_default_path("const_path");
  FilePath non_default_path("path");
  non_default_path = const_default_path;
  EXPECT_EQ("const_path", non_default_path.string());
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [2/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (AssignmentOperatorTest , DefaultAssignedToNonDefault)
Definition at line 458 of file gtest-filepath_test.cc.
{
  FilePath default_path;
  FilePath non_default_path("path");
  non_default_path = default_path;
  EXPECT_EQ("", non_default_path.string());
  EXPECT_EQ("", default_path.string());  // RHS var is unchanged.
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [3/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (AssignmentOperatorTest , NonDefaultAssignedToDefault)
Definition at line 466 of file gtest-filepath_test.cc.
{
  FilePath non_default_path("path");
  FilePath default_path;
  default_path = non_default_path;
  EXPECT_EQ("path", default_path.string());
  EXPECT_EQ("path", non_default_path.string());  // RHS var is unchanged.
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [4/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , BothPathBeingEmpty)
Definition at line 299 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath(""),
                                          FilePath(""));
  EXPECT_EQ("", actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [5/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , Path1BeingEmpty)
Definition at line 288 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath(""),
                                          FilePath("bar.xml"));
  EXPECT_EQ("bar.xml", actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [6/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , Path1ContainsPathSep)
Definition at line 305 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath("foo" GTEST_PATH_SEP_ "bar"),
                                          FilePath("foobar.xml"));
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar" GTEST_PATH_SEP_ "foobar.xml",
            actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [7/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , Path2BeingEmpty)
Definition at line 294 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath("foo"), FilePath(""));
  EXPECT_EQ("foo" GTEST_PATH_SEP_, actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [8/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , Path2ContainsPathSep)
Definition at line 312 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(
      FilePath("foo" GTEST_PATH_SEP_),
      FilePath("bar" GTEST_PATH_SEP_ "bar.xml"));
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar" GTEST_PATH_SEP_ "bar.xml",
            actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [9/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , Path2EndsWithPathSep)
Definition at line 320 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath("foo"),
                                          FilePath("bar" GTEST_PATH_SEP_));
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar" GTEST_PATH_SEP_, actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [10/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , WorksWhenDirDoesNotEndWithPathSep)
Definition at line 276 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath("foo"),
                                          FilePath("bar.xml"));
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar.xml", actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [11/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (ConcatPathsTest , WorksWhenPath1EndsWithPathSep)
Definition at line 282 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::ConcatPaths(FilePath("foo" GTEST_PATH_SEP_),
                                          FilePath("bar.xml"));
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar.xml", actual.string());
}
References testing::internal::FilePath::ConcatPaths(), EXPECT_EQ, GTEST_PATH_SEP_, and testing::internal::FilePath::string().
TEST() [12/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (DirectoryTest , CurrentDirectoryExists)
Definition at line 397 of file gtest-filepath_test.cc.
{
#if GTEST_OS_WINDOWS  // We are on Windows.
# ifndef _WIN32_CE  // Windows CE doesn't have a current directory.
  EXPECT_TRUE(FilePath(".").DirectoryExists());
  EXPECT_TRUE(FilePath(".\\").DirectoryExists());
# endif  // _WIN32_CE
#else
  EXPECT_TRUE(FilePath(".").DirectoryExists());
  EXPECT_TRUE(FilePath("./").DirectoryExists());
#endif  // GTEST_OS_WINDOWS
}
References EXPECT_TRUE.
TEST() [13/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (DirectoryTest , EmptyPathDirectoryDoesNotExist)
Definition at line 392 of file gtest-filepath_test.cc.
{
  EXPECT_FALSE(FilePath("").DirectoryExists());
}
References EXPECT_FALSE.
TEST() [14/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (DirectoryTest , RootDirectoryExists)
Definition at line 359 of file gtest-filepath_test.cc.
{
#if GTEST_OS_WINDOWS  // We are on Windows.
  char current_drive[_MAX_PATH];  // NOLINT
  current_drive[0] = static_cast<char>(_getdrive() + 'A' - 1);
  current_drive[1] = ':';
  current_drive[2] = '\\';
  current_drive[3] = '\0';
  EXPECT_TRUE(FilePath(current_drive).DirectoryExists());
#else
  EXPECT_TRUE(FilePath("/").DirectoryExists());
#endif  // GTEST_OS_WINDOWS
}
References EXPECT_TRUE.
TEST() [15/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , CharAndCopyConstructors)
Definition at line 572 of file gtest-filepath_test.cc.
{
  const FilePath fp("spicy");
  EXPECT_EQ("spicy", fp.string());
  const FilePath fp_copy(fp);
  EXPECT_EQ("spicy", fp_copy.string());
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [16/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , DefaultConstructor)
Definition at line 567 of file gtest-filepath_test.cc.
{
  FilePath fp;
  EXPECT_EQ("", fp.string());
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [17/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , IsAbsolutePath)
Definition at line 616 of file gtest-filepath_test.cc.
{
  EXPECT_FALSE(FilePath("is" GTEST_PATH_SEP_ "relative").IsAbsolutePath());
  EXPECT_FALSE(FilePath("").IsAbsolutePath());
#if GTEST_OS_WINDOWS
  EXPECT_TRUE(FilePath("c:\\" GTEST_PATH_SEP_ "is_not"
                       GTEST_PATH_SEP_ "relative").IsAbsolutePath());
  EXPECT_FALSE(FilePath("c:foo" GTEST_PATH_SEP_ "bar").IsAbsolutePath());
  EXPECT_TRUE(FilePath("c:/" GTEST_PATH_SEP_ "is_not"
                       GTEST_PATH_SEP_ "relative").IsAbsolutePath());
#else
  EXPECT_TRUE(FilePath(GTEST_PATH_SEP_ "is_not" GTEST_PATH_SEP_ "relative")
              .IsAbsolutePath());
#endif  // GTEST_OS_WINDOWS
}
References EXPECT_FALSE, EXPECT_TRUE, and GTEST_PATH_SEP_.
TEST() [18/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , IsDirectory)
Definition at line 608 of file gtest-filepath_test.cc.
{
  EXPECT_FALSE(FilePath("cola").IsDirectory());
  EXPECT_TRUE(FilePath("koala" GTEST_PATH_SEP_).IsDirectory());
#if GTEST_HAS_ALT_PATH_SEP_
  EXPECT_TRUE(FilePath("koala/").IsDirectory());
#endif
}
References EXPECT_FALSE, EXPECT_TRUE, and GTEST_PATH_SEP_.
TEST() [19/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , IsRootDirectory)
Definition at line 631 of file gtest-filepath_test.cc.
{
#if GTEST_OS_WINDOWS
  EXPECT_TRUE(FilePath("a:\\").IsRootDirectory());
  EXPECT_TRUE(FilePath("Z:/").IsRootDirectory());
  EXPECT_TRUE(FilePath("e://").IsRootDirectory());
  EXPECT_FALSE(FilePath("").IsRootDirectory());
  EXPECT_FALSE(FilePath("b:").IsRootDirectory());
  EXPECT_FALSE(FilePath("b:a").IsRootDirectory());
  EXPECT_FALSE(FilePath("8:/").IsRootDirectory());
  EXPECT_FALSE(FilePath("c|/").IsRootDirectory());
#else
  EXPECT_TRUE(FilePath("/").IsRootDirectory());
  EXPECT_TRUE(FilePath("//").IsRootDirectory());
  EXPECT_FALSE(FilePath("").IsRootDirectory());
  EXPECT_FALSE(FilePath("\\").IsRootDirectory());
  EXPECT_FALSE(FilePath("/x").IsRootDirectory());
#endif
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [20/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , RemoveExtension)
Definition at line 598 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("app", FilePath("app.cc").RemoveExtension("cc").string());
  EXPECT_EQ("app", FilePath("app.exe").RemoveExtension("exe").string());
  EXPECT_EQ("APP", FilePath("APP.EXE").RemoveExtension("exe").string());
}
References EXPECT_EQ.
TEST() [21/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , RemoveExtensionWhenThereIsNoExtension)
Definition at line 604 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("app", FilePath("app").RemoveExtension("exe").string());
}
References EXPECT_EQ.
TEST() [22/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , Set)
Definition at line 585 of file gtest-filepath_test.cc.
{
  const FilePath apple("apple");
  FilePath mac("mac");
  mac.Set(apple);  // Implement Set() since overloading operator= is forbidden.
  EXPECT_EQ("apple", mac.string());
  EXPECT_EQ("apple", apple.string());
}
References EXPECT_EQ, testing::internal::FilePath::Set(), and testing::internal::FilePath::string().
TEST() [23/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , StringConstructor)
Definition at line 580 of file gtest-filepath_test.cc.
{
  const FilePath fp(std::string("cider"));
  EXPECT_EQ("cider", fp.string());
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [24/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (FilePathTest , ToString)
Definition at line 593 of file gtest-filepath_test.cc.
{
  const FilePath file("drink");
  EXPECT_EQ("drink", file.string());
}
References EXPECT_EQ, and testing::internal::FilePath::string().
TEST() [25/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (GetCurrentDirTest , ReturnsCurrentDir)
Definition at line 76 of file gtest-filepath_test.cc.
{
  const FilePath original_dir = FilePath::GetCurrentDir();
  EXPECT_FALSE(original_dir.IsEmpty());
  posix::ChDir(GTEST_PATH_SEP_);
  const FilePath cwd = FilePath::GetCurrentDir();
  posix::ChDir(original_dir.c_str());
# if GTEST_OS_WINDOWS
  // Skips the ":".
  const char* const cwd_without_drive = strchr(cwd.c_str(), ':');
  ASSERT_TRUE(cwd_without_drive != NULL);
  EXPECT_STREQ(GTEST_PATH_SEP_, cwd_without_drive + 1);
# else
  EXPECT_EQ(GTEST_PATH_SEP_, cwd.string());
# endif
}
References ASSERT_TRUE, testing::internal::FilePath::c_str(), testing::internal::posix::ChDir(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, testing::internal::FilePath::GetCurrentDir(), GTEST_PATH_SEP_, testing::internal::FilePath::IsEmpty(), and testing::internal::FilePath::string().
TEST() [26/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (IsEmptyTest , ReturnsFalseForNonEmptyPath)
Definition at line 104 of file gtest-filepath_test.cc.
{
  EXPECT_FALSE(FilePath("a").IsEmpty());
  EXPECT_FALSE(FilePath(".").IsEmpty());
  EXPECT_FALSE(FilePath("a/b").IsEmpty());
  EXPECT_FALSE(FilePath("a\\b\\").IsEmpty());
}
References EXPECT_FALSE.
TEST() [27/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (IsEmptyTest , ReturnsTrueForEmptyPath)
Definition at line 100 of file gtest-filepath_test.cc.
{
  EXPECT_TRUE(FilePath("").IsEmpty());
}
References EXPECT_TRUE.
TEST() [28/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (MakeFileNameTest , GenerateFileNameNumberGtZero)
Definition at line 246 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::MakeFileName(FilePath("foo"), FilePath("bar"),
      12, "xml");
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar_12.xml", actual.string());
}
References EXPECT_EQ, GTEST_PATH_SEP_, testing::internal::FilePath::MakeFileName(), and testing::internal::FilePath::string().
TEST() [29/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (MakeFileNameTest , GenerateFileNameWithSlashNumberGtZero)
Definition at line 258 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::MakeFileName(FilePath("foo" GTEST_PATH_SEP_),
      FilePath("bar"), 12, "xml");
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar_12.xml", actual.string());
}
References EXPECT_EQ, GTEST_PATH_SEP_, testing::internal::FilePath::MakeFileName(), and testing::internal::FilePath::string().
TEST() [30/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (MakeFileNameTest , GenerateFileNameWithSlashNumberIsZero)
Definition at line 252 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::MakeFileName(FilePath("foo" GTEST_PATH_SEP_),
      FilePath("bar"), 0, "xml");
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar.xml", actual.string());
}
References EXPECT_EQ, GTEST_PATH_SEP_, testing::internal::FilePath::MakeFileName(), and testing::internal::FilePath::string().
TEST() [31/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (MakeFileNameTest , GenerateWhenNumberIsNotZeroAndDirIsEmpty)
Definition at line 270 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::MakeFileName(FilePath(""), FilePath("bar"),
      14, "xml");
  EXPECT_EQ("bar_14.xml", actual.string());
}
References EXPECT_EQ, testing::internal::FilePath::MakeFileName(), and testing::internal::FilePath::string().
TEST() [32/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (MakeFileNameTest , GenerateWhenNumberIsZero)
Definition at line 240 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::MakeFileName(FilePath("foo"), FilePath("bar"),
      0, "xml");
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar.xml", actual.string());
}
References EXPECT_EQ, GTEST_PATH_SEP_, testing::internal::FilePath::MakeFileName(), and testing::internal::FilePath::string().
TEST() [33/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (MakeFileNameTest , GenerateWhenNumberIsZeroAndDirIsEmpty)
Definition at line 264 of file gtest-filepath_test.cc.
{
  FilePath actual = FilePath::MakeFileName(FilePath(""), FilePath("bar"),
      0, "xml");
  EXPECT_EQ("bar.xml", actual.string());
}
References EXPECT_EQ, testing::internal::FilePath::MakeFileName(), and testing::internal::FilePath::string().
TEST() [34/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (NoDirectoryCreationTest , CreateNoDirectoriesForDefaultXmlFile)
Definition at line 562 of file gtest-filepath_test.cc.
{
  const FilePath test_detail_xml("test_detail.xml");
  EXPECT_FALSE(test_detail_xml.CreateDirectoriesRecursively());
}
References testing::internal::FilePath::CreateDirectoriesRecursively(), and EXPECT_FALSE.
TEST() [35/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (NormalizeTest , MultipleConsecutiveSepaparatorsAtStringEnd)
Definition at line 433 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("foo" GTEST_PATH_SEP_,
    FilePath("foo" GTEST_PATH_SEP_).string());
  EXPECT_EQ("foo" GTEST_PATH_SEP_,
    FilePath("foo" GTEST_PATH_SEP_ GTEST_PATH_SEP_).string());
  EXPECT_EQ("foo" GTEST_PATH_SEP_,
    FilePath("foo" GTEST_PATH_SEP_ GTEST_PATH_SEP_ GTEST_PATH_SEP_).string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [36/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (NormalizeTest , MultipleConsecutiveSepaparatorsAtStringStart)
Definition at line 423 of file gtest-filepath_test.cc.
{
  EXPECT_EQ(GTEST_PATH_SEP_ "bar",
    FilePath(GTEST_PATH_SEP_ "bar").string());
  EXPECT_EQ(GTEST_PATH_SEP_ "bar",
    FilePath(GTEST_PATH_SEP_ GTEST_PATH_SEP_ "bar").string());
  EXPECT_EQ(GTEST_PATH_SEP_ "bar",
    FilePath(GTEST_PATH_SEP_ GTEST_PATH_SEP_ GTEST_PATH_SEP_ "bar").string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [37/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (NormalizeTest , MultipleConsecutiveSepaparatorsInMidstring)
Definition at line 412 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar",
            FilePath("foo" GTEST_PATH_SEP_ "bar").string());
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar",
            FilePath("foo" GTEST_PATH_SEP_ GTEST_PATH_SEP_ "bar").string());
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar",
            FilePath("foo" GTEST_PATH_SEP_ GTEST_PATH_SEP_
                     GTEST_PATH_SEP_ "bar").string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [38/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveDirectoryNameTest , ButNoDirectory)
Definition at line 117 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("afile",
      FilePath("afile").RemoveDirectoryName().string());
}
References EXPECT_EQ.
TEST() [39/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveDirectoryNameTest , RootFileShouldGiveFileName)
Definition at line 123 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("afile",
      FilePath(GTEST_PATH_SEP_ "afile").RemoveDirectoryName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [40/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveDirectoryNameTest , ShouldAlsoGiveFileName)
Definition at line 141 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("afile",
      FilePath("adir" GTEST_PATH_SEP_ "subdir" GTEST_PATH_SEP_ "afile")
      .RemoveDirectoryName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [41/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveDirectoryNameTest , ShouldGiveFileName)
Definition at line 135 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("afile",
      FilePath("adir" GTEST_PATH_SEP_ "afile").RemoveDirectoryName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [42/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveDirectoryNameTest , WhenEmptyName)
Definition at line 112 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("", FilePath("").RemoveDirectoryName().string());
}
References EXPECT_EQ.
TEST() [43/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveDirectoryNameTest , WhereThereIsNoFileName)
Definition at line 129 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("",
      FilePath("adir" GTEST_PATH_SEP_).RemoveDirectoryName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [44/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveFileNameTest , ButNoFile)
Definition at line 186 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("adir" GTEST_PATH_SEP_,
      FilePath("adir" GTEST_PATH_SEP_).RemoveFileName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [45/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveFileNameTest , EmptyName)
Definition at line 176 of file gtest-filepath_test.cc.
{
#if GTEST_OS_WINDOWS_MOBILE
  // On Windows CE, we use the root as the current directory.
  EXPECT_EQ(GTEST_PATH_SEP_, FilePath("").RemoveFileName().string());
#else
  EXPECT_EQ("." GTEST_PATH_SEP_, FilePath("").RemoveFileName().string());
#endif
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [46/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveFileNameTest , GivesDirAndSubDirName)
Definition at line 198 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("adir" GTEST_PATH_SEP_ "subdir" GTEST_PATH_SEP_,
      FilePath("adir" GTEST_PATH_SEP_ "subdir" GTEST_PATH_SEP_ "afile")
      .RemoveFileName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [47/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveFileNameTest , GivesDirName)
Definition at line 192 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("adir" GTEST_PATH_SEP_,
            FilePath("adir" GTEST_PATH_SEP_ "afile").RemoveFileName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [48/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveFileNameTest , GivesRootDir)
Definition at line 205 of file gtest-filepath_test.cc.
{
  EXPECT_EQ(GTEST_PATH_SEP_,
      FilePath(GTEST_PATH_SEP_ "afile").RemoveFileName().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [49/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveTrailingPathSeparatorTest , EmptyString)
Definition at line 327 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("", FilePath("").RemoveTrailingPathSeparator().string());
}
References EXPECT_EQ.
TEST() [50/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveTrailingPathSeparatorTest , FileNoSlashString)
Definition at line 332 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("foo", FilePath("foo").RemoveTrailingPathSeparator().string());
}
References EXPECT_EQ.
TEST() [51/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveTrailingPathSeparatorTest , ShouldRemoveLastSeparator)
Definition at line 346 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar",
            FilePath("foo" GTEST_PATH_SEP_ "bar" GTEST_PATH_SEP_)
                .RemoveTrailingPathSeparator().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [52/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveTrailingPathSeparatorTest , ShouldRemoveTrailingSeparator)
Definition at line 337 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("foo",
      FilePath("foo" GTEST_PATH_SEP_).RemoveTrailingPathSeparator().string());
#if GTEST_HAS_ALT_PATH_SEP_
  EXPECT_EQ("foo", FilePath("foo/").RemoveTrailingPathSeparator().string());
#endif
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST() [53/53]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST (RemoveTrailingPathSeparatorTest , ShouldReturnUnmodified)
Definition at line 353 of file gtest-filepath_test.cc.
{
  EXPECT_EQ("foo" GTEST_PATH_SEP_ "bar",
            FilePath("foo" GTEST_PATH_SEP_ "bar")
                .RemoveTrailingPathSeparator().string());
}
References EXPECT_EQ, and GTEST_PATH_SEP_.
TEST_F() [1/4]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST_F (DirectoryCreationTest , CreateDirectoriesAndUniqueFilename)
Definition at line 535 of file gtest-filepath_test.cc.
{
  FilePath file_path(FilePath::GenerateUniqueFileName(testdata_path_,
      FilePath("unique"), "txt"));
  EXPECT_EQ(unique_file0_.string(), file_path.string());
  EXPECT_FALSE(file_path.FileOrDirectoryExists());  // file not there
  testdata_path_.CreateDirectoriesRecursively();
  EXPECT_FALSE(file_path.FileOrDirectoryExists());  // file still not there
  CreateTextFile(file_path.c_str());
  EXPECT_TRUE(file_path.FileOrDirectoryExists());
  FilePath file_path2(FilePath::GenerateUniqueFileName(testdata_path_,
      FilePath("unique"), "txt"));
  EXPECT_EQ(unique_file1_.string(), file_path2.string());
  EXPECT_FALSE(file_path2.FileOrDirectoryExists());  // file not there
  CreateTextFile(file_path2.c_str());
  EXPECT_TRUE(file_path2.FileOrDirectoryExists());
}
References testing::internal::FilePath::c_str(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::internal::FilePath::FileOrDirectoryExists(), testing::internal::FilePath::GenerateUniqueFileName(), and testing::internal::FilePath::string().
TEST_F() [2/4]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST_F (DirectoryCreationTest , CreateDirectoriesFail)
Definition at line 554 of file gtest-filepath_test.cc.
{
  // force a failure by putting a file where we will try to create a directory.
  CreateTextFile(testdata_file_.c_str());
  EXPECT_TRUE(testdata_file_.FileOrDirectoryExists());
  EXPECT_FALSE(testdata_file_.DirectoryExists());
  EXPECT_FALSE(testdata_file_.CreateDirectoriesRecursively());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [3/4]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST_F (DirectoryCreationTest , CreateDirectoriesForAlreadyExistingPath)
Definition at line 528 of file gtest-filepath_test.cc.
{
  EXPECT_FALSE(testdata_path_.DirectoryExists()) << testdata_path_.string();
  EXPECT_TRUE(testdata_path_.CreateDirectoriesRecursively());
  // Call 'create' again... should still succeed.
  EXPECT_TRUE(testdata_path_.CreateDirectoriesRecursively());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [4/4]
testing::internal::anonymous_namespace{gtest-filepath_test.cc}::TEST_F (DirectoryCreationTest , CreateDirectoriesRecursively)
Definition at line 522 of file gtest-filepath_test.cc.
{
  EXPECT_FALSE(testdata_path_.DirectoryExists()) << testdata_path_.string();
  EXPECT_TRUE(testdata_path_.CreateDirectoriesRecursively());
  EXPECT_TRUE(testdata_path_.DirectoryExists());
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::FilePath::string().