wiNpoS: anonymous_namespace{gtest_repeat_test.cc} Namespace Reference
anonymous_namespace{gtest_repeat_test.cc} Namespace Reference
Classes
class MyEnvironment
class MyParamTest
Functions
TEST (FooTest, ShouldFail)
TEST (FooTest, ShouldPass)
TEST (BarDeathTest, ThreadSafeAndFast)
TEST_P (MyParamTest, ShouldPass)
INSTANTIATE_TEST_CASE_P (MyParamSequence, MyParamTest, testing::Range(0, kNumberOfParamTests))
void ResetCounts ()
void CheckCounts (int expected)
void TestRepeatUnspecified ()
void TestRepeat (int repeat)
void TestRepeatWithEmptyFilter (int repeat)
void TestRepeatWithFilterForSuccessfulTests (int repeat)
void TestRepeatWithFilterForFailedTests (int repeat)
Variables
int g_environment_set_up_count = 0
int g_environment_tear_down_count = 0
int g_should_fail_count = 0
int g_should_pass_count = 0
int g_death_test_count = 0
int g_param_test_count = 0
const int kNumberOfParamTests = 10
Function Documentation
CheckCounts()
void anonymous_namespace{gtest_repeat_test.cc}::CheckCounts (int expected)
Definition at line 141 of file gtest_repeat_test.cc.
{
  GTEST_CHECK_INT_EQ_(expected, g_environment_set_up_count);
  GTEST_CHECK_INT_EQ_(expected, g_environment_tear_down_count);
  GTEST_CHECK_INT_EQ_(expected, g_should_fail_count);
  GTEST_CHECK_INT_EQ_(expected, g_should_pass_count);
  GTEST_CHECK_INT_EQ_(expected, g_death_test_count);
  GTEST_CHECK_INT_EQ_(expected * kNumberOfParamTests, g_param_test_count);
}
References g_death_test_count, g_environment_set_up_count, g_environment_tear_down_count, g_param_test_count, g_should_fail_count, g_should_pass_count, GTEST_CHECK_INT_EQ_, and kNumberOfParamTests.
INSTANTIATE_TEST_CASE_P()
anonymous_namespace{gtest_repeat_test.cc}::INSTANTIATE_TEST_CASE_P (MyParamSequence , MyParamTest , testing::Range(0, kNumberOfParamTests))
ResetCounts()
void anonymous_namespace{gtest_repeat_test.cc}::ResetCounts ()
Definition at line 131 of file gtest_repeat_test.cc.
                   {
  g_environment_set_up_count = 0;
  g_environment_tear_down_count = 0;
  g_should_fail_count = 0;
  g_should_pass_count = 0;
  g_death_test_count = 0;
  g_param_test_count = 0;
}
References g_death_test_count, g_environment_set_up_count, g_environment_tear_down_count, g_param_test_count, g_should_fail_count, and g_should_pass_count.
TEST() [1/3]
anonymous_namespace{gtest_repeat_test.cc}::TEST (BarDeathTest , ThreadSafeAndFast)
Definition at line 104 of file gtest_repeat_test.cc.
{
  g_death_test_count++;
  GTEST_FLAG(death_test_style) = "threadsafe";
  EXPECT_DEATH_IF_SUPPORTED(::testing::internal::posix::Abort(), "");
  GTEST_FLAG(death_test_style) = "fast";
  EXPECT_DEATH_IF_SUPPORTED(::testing::internal::posix::Abort(), "");
}
References testing::internal::posix::Abort(), EXPECT_DEATH_IF_SUPPORTED, g_death_test_count, and GTEST_FLAG.
TEST() [2/3]
anonymous_namespace{gtest_repeat_test.cc}::TEST (FooTest , ShouldFail)
Definition at line 86 of file gtest_repeat_test.cc.
{
  g_should_fail_count++;
  EXPECT_EQ(0, 1) << "Expected failure.";
}
References EXPECT_EQ, and g_should_fail_count.
TEST() [3/3]
anonymous_namespace{gtest_repeat_test.cc}::TEST (FooTest , ShouldPass)
Definition at line 95 of file gtest_repeat_test.cc.
{
  g_should_pass_count++;
}
References g_should_pass_count.
TEST_P()
anonymous_namespace{gtest_repeat_test.cc}::TEST_P (MyParamTest , ShouldPass)
Definition at line 120 of file gtest_repeat_test.cc.
{
  // TODO(vladl@google.com): Make parameter value checking robust
  //                         WRT order of tests.
  GTEST_CHECK_INT_EQ_(g_param_test_count % kNumberOfParamTests, GetParam());
  g_param_test_count++;
}
References g_param_test_count, GTEST_CHECK_INT_EQ_, and kNumberOfParamTests.
TestRepeat()
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeat (int repeat)
Definition at line 158 of file gtest_repeat_test.cc.
{
  GTEST_FLAG(repeat) = repeat;
  ResetCounts();
  GTEST_CHECK_INT_EQ_(repeat > 0 ? 1 : 0, RUN_ALL_TESTS());
  CheckCounts(repeat);
}
References CheckCounts(), GTEST_CHECK_INT_EQ_, GTEST_FLAG, ResetCounts(), and RUN_ALL_TESTS().
TestRepeatUnspecified()
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatUnspecified ()
Definition at line 151 of file gtest_repeat_test.cc.
{
  ResetCounts();
  GTEST_CHECK_INT_EQ_(1, RUN_ALL_TESTS());
  CheckCounts(1);
}
References CheckCounts(), GTEST_CHECK_INT_EQ_, ResetCounts(), and RUN_ALL_TESTS().
TestRepeatWithEmptyFilter()
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithEmptyFilter (int repeat)
Definition at line 168 of file gtest_repeat_test.cc.
{
  GTEST_FLAG(repeat) = repeat;
  GTEST_FLAG(filter) = "None";
  ResetCounts();
  GTEST_CHECK_INT_EQ_(0, RUN_ALL_TESTS());
  CheckCounts(0);
}
References CheckCounts(), GTEST_CHECK_INT_EQ_, GTEST_FLAG, ResetCounts(), and RUN_ALL_TESTS().
TestRepeatWithFilterForFailedTests()
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithFilterForFailedTests (int repeat)
Definition at line 195 of file gtest_repeat_test.cc.
{
  GTEST_FLAG(repeat) = repeat;
  GTEST_FLAG(filter) = "*ShouldFail";
  ResetCounts();
  GTEST_CHECK_INT_EQ_(1, RUN_ALL_TESTS());
  GTEST_CHECK_INT_EQ_(repeat, g_environment_set_up_count);
  GTEST_CHECK_INT_EQ_(repeat, g_environment_tear_down_count);
  GTEST_CHECK_INT_EQ_(repeat, g_should_fail_count);
  GTEST_CHECK_INT_EQ_(0, g_should_pass_count);
  GTEST_CHECK_INT_EQ_(0, g_death_test_count);
  GTEST_CHECK_INT_EQ_(0, g_param_test_count);
}
References g_death_test_count, g_environment_set_up_count, g_environment_tear_down_count, g_param_test_count, g_should_fail_count, g_should_pass_count, GTEST_CHECK_INT_EQ_, GTEST_FLAG, ResetCounts(), and RUN_ALL_TESTS().
TestRepeatWithFilterForSuccessfulTests()
void anonymous_namespace{gtest_repeat_test.cc}::TestRepeatWithFilterForSuccessfulTests (int repeat)
Definition at line 179 of file gtest_repeat_test.cc.
{
  GTEST_FLAG(repeat) = repeat;
  GTEST_FLAG(filter) = "*-*ShouldFail";
  ResetCounts();
  GTEST_CHECK_INT_EQ_(0, RUN_ALL_TESTS());
  GTEST_CHECK_INT_EQ_(repeat, g_environment_set_up_count);
  GTEST_CHECK_INT_EQ_(repeat, g_environment_tear_down_count);
  GTEST_CHECK_INT_EQ_(0, g_should_fail_count);
  GTEST_CHECK_INT_EQ_(repeat, g_should_pass_count);
  GTEST_CHECK_INT_EQ_(repeat, g_death_test_count);
  GTEST_CHECK_INT_EQ_(repeat * kNumberOfParamTests, g_param_test_count);
}
References g_death_test_count, g_environment_set_up_count, g_environment_tear_down_count, g_param_test_count, g_should_fail_count, g_should_pass_count, GTEST_CHECK_INT_EQ_, GTEST_FLAG, kNumberOfParamTests, ResetCounts(), and RUN_ALL_TESTS().
Variable Documentation
g_death_test_count
int anonymous_namespace{gtest_repeat_test.cc}::g_death_test_count = 0
Definition at line 102 of file gtest_repeat_test.cc.
g_environment_set_up_count
int anonymous_namespace{gtest_repeat_test.cc}::g_environment_set_up_count = 0
Definition at line 72 of file gtest_repeat_test.cc.
g_environment_tear_down_count
int anonymous_namespace{gtest_repeat_test.cc}::g_environment_tear_down_count = 0
Definition at line 73 of file gtest_repeat_test.cc.
g_param_test_count
int anonymous_namespace{gtest_repeat_test.cc}::g_param_test_count = 0
Definition at line 114 of file gtest_repeat_test.cc.
g_should_fail_count
int anonymous_namespace{gtest_repeat_test.cc}::g_should_fail_count = 0
Definition at line 84 of file gtest_repeat_test.cc.
g_should_pass_count
int anonymous_namespace{gtest_repeat_test.cc}::g_should_pass_count = 0
Definition at line 93 of file gtest_repeat_test.cc.
kNumberOfParamTests
const int anonymous_namespace{gtest_repeat_test.cc}::kNumberOfParamTests = 10
Definition at line 116 of file gtest_repeat_test.cc.