wiNpoS: anonymous_namespace{gtest_environment_test.cc} Namespace Reference
anonymous_namespace{gtest_environment_test.cc} Namespace Reference
Classes
class MyEnvironment
Enumerations
enum FailureType { NO_FAILURE , NON_FATAL_FAILURE , FATAL_FAILURE }
Functions
TEST (FooTest, Bar)
void Check (bool condition, const char *msg)
int RunAllTests (MyEnvironment *env, FailureType failure)
Variables
bool test_was_run
Enumeration Type Documentation
FailureType
enum anonymous_namespace{gtest_environment_test.cc}::FailureType
Enumerator
NO_FAILURE
NON_FATAL_FAILURE
FATAL_FAILURE
Definition at line 45 of file gtest_environment_test.cc.
                 {
  NO_FAILURE, NON_FATAL_FAILURE, FATAL_FAILURE
};
Function Documentation
Check()
void anonymous_namespace{gtest_environment_test.cc}::Check (bool condition, const char * msg)
Definition at line 113 of file gtest_environment_test.cc.
{
  if (!condition) {
    printf("FAILED: %s\n", msg);
    testing::internal::posix::Abort();
  }
}
References testing::internal::posix::Abort().
RunAllTests()
int anonymous_namespace{gtest_environment_test.cc}::RunAllTests (MyEnvironment * env, FailureType failure)
Definition at line 124 of file gtest_environment_test.cc.
{
  env->Reset();
  env->set_failure_in_set_up(failure);
  test_was_run = false;
  testing::internal::GetUnitTestImpl()->ClearAdHocTestResult();
  return RUN_ALL_TESTS();
}
References testing::internal::UnitTestImpl::ClearAdHocTestResult(), testing::internal::GetUnitTestImpl(), anonymous_namespace{gtest_environment_test.cc}::MyEnvironment::Reset(), RUN_ALL_TESTS(), anonymous_namespace{gtest_environment_test.cc}::MyEnvironment::set_failure_in_set_up(), and test_was_run.
TEST()
anonymous_namespace{gtest_environment_test.cc}::TEST (FooTest , Bar)
Definition at line 108 of file gtest_environment_test.cc.
                   {
  test_was_run = true;
}
References test_was_run.
Variable Documentation
test_was_run
bool anonymous_namespace{gtest_environment_test.cc}::test_was_run
Definition at line 104 of file gtest_environment_test.cc.