wiNpoS: testing Namespace Reference
testing Namespace Reference
Namespaces
namespace anonymous_namespace{gmock-cardinalities.cc}
namespace anonymous_namespace{gmock-spec-builders.cc}
namespace anonymous_namespace{gmock_stress_test.cc}
namespace anonymous_namespace{gtest-printers.cc}
namespace anonymous_namespace{gtest.cc}
namespace gmock_generated_actions_test
namespace gmock_generated_function_mockers_test
namespace gmock_matchers_test
namespace gmock_more_actions_test
namespace gmock_nice_strict_test
namespace gtest_printers_test
namespace internal
namespace internal2
Classes
class Action
class ActionInterface
class AssertionResult
class Cardinality
class CardinalityInterface
class CodeLocationForTESTF
class CodeLocationForTESTP
class CodeLocationForTYPEDTEST
class CodeLocationForTYPEDTESTP
class CurrentTestInfoTest
class DefaultValue
class DefaultValue< T & >
class DefaultValue< void >
class EmptyTestEventListener
class Environment
class Expectation
class ExpectationSet
struct Flags
class InSequence
class Matcher
class Matcher< const std::string & >
class Matcher< std::string >
class MatcherDescriberInterface
class MatcherInterface
class MatchResultListener
class Message
class Mock
class MockFunction
class MockFunction< R(A0)>
class MockFunction< R(A0, A1)>
class MockFunction< R(A0, A1, A2)>
class MockFunction< R(A0, A1, A2, A3)>
class MockFunction< R(A0, A1, A2, A3, A4)>
class MockFunction< R(A0, A1, A2, A3, A4, A5)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6, A7)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6, A7, A8)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9)>
class NaggyMock
class NiceMock
class ParseFlagsTest
class PolymorphicAction
class PolymorphicMatcher
struct PrintToStringParamName
class SafeMatcherCastImpl
class ScopedFakeTestPartResultReporter
class ScopedTrace
class Sequence
class SetUpTestCaseTest
class StrictMock
class StringMatchResultListener
class Test
class TestCase
class TestEventListener
class TestEventListeners
class TestInfo
class TestInfoTest
struct TestParamInfo
class TestPartResult
class TestPartResultArray
class TestPartResultReporterInterface
class TestProperty
class TestResult
class TestWithParam
class UnitTest
class WithParamInterface
Typedefs
typedef internal::IgnoredValue Unused
typedef internal::TimeInMillis TimeInMillis
Functions
template<typename F >
Action< F > MakeAction (ActionInterface< F > *impl)
template<typename Impl >
PolymorphicAction< Impl > MakePolymorphicAction (const Impl &impl)
template<typename R >
internal::ReturnAction< R > Return (R value)
PolymorphicAction< internal::ReturnNullAction > ReturnNull ()
PolymorphicAction< internal::ReturnVoidAction > Return ()
template<typename R >
internal::ReturnRefAction< R > ReturnRef (R &x)
template<typename R >
internal::ReturnRefOfCopyAction< R > ReturnRefOfCopy (const R &x)
template<typename R >
internal::ByMoveWrapper< R > ByMove (R x)
internal::DoDefaultAction DoDefault ()
template<size_t N, typename T >
PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > SetArgPointee (const T &x)
template<size_t N>
PolymorphicAction< internal::SetArgumentPointeeAction< N, const char *, false > > SetArgPointee (const char *p)
template<size_t N>
PolymorphicAction< internal::SetArgumentPointeeAction< N, const wchar_t *, false > > SetArgPointee (const wchar_t *p)
template<size_t N, typename T >
PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > SetArgumentPointee (const T &x)
template<typename T1 , typename T2 >
PolymorphicAction< internal::AssignAction< T1, T2 > > Assign (T1 *ptr, T2 val)
template<typename T >
PolymorphicAction< internal::SetErrnoAndReturnAction< T > > SetErrnoAndReturn (int errval, T result)
template<typename FunctionImpl >
PolymorphicAction< internal::InvokeWithoutArgsAction< FunctionImpl > > InvokeWithoutArgs (FunctionImpl function_impl)
template<class Class , typename MethodPtr >
PolymorphicAction< internal::InvokeMethodWithoutArgsAction< Class, MethodPtr > > InvokeWithoutArgs (Class *obj_ptr, MethodPtr method_ptr)
template<typename A >
internal::IgnoreResultAction< A > IgnoreResult (const A &an_action)
template<typename T >
internal::ReferenceWrapper< T > ByRef (T &l_value)
GTEST_API_ Cardinality AtLeast (int n)
GTEST_API_ Cardinality AtMost (int n)
GTEST_API_ Cardinality AnyNumber ()
GTEST_API_ Cardinality Between (int min, int max)
GTEST_API_ Cardinality Exactly (int n)
Cardinality MakeCardinality (const CardinalityInterface *c)
template<int k1, typename InnerAction >
internal::WithArgsAction< InnerAction, k1 > WithArgs (const InnerAction &action)
template<int k1, int k2, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > WithArgs (const InnerAction &action)
template<typename Action1 , typename Action2 >
internal::DoBothAction< Action1, Action2 > DoAll (Action1 a1, Action2 a2)
template<typename Action1 , typename Action2 , typename Action3 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, Action3 > > DoAll (Action1 a1, Action2 a2, Action3 a3)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, Action4 > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, Action5 > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, Action6 > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, Action7 > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, Action8 > > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, Action9 > > > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 , typename Action10 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, internal::DoBothAction< Action9, Action10 > > > > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9, Action10 a10)
template<int k>
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction,)
template<int k>
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction,)< k > InvokeArgument()
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction,)< k >
template<int k, typename p0_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P)< k
p0_type InvokeArgument (p0_type p0)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P)< k
template<int k, typename p0_type , typename p1_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P2)
template<int k, typename p0_type , typename p1_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P2)< k
p1_type InvokeArgument (p0_type p0, p1_type p1)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P2)< k
template<int k, typename p0_type , typename p1_type , typename p2_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P3)
template<int k, typename p0_type , typename p1_type , typename p2_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P3)< k
p2_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P3)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P4)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P4)< k
p3_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P4)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P5)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P5)< k
p4_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P5)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P6)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P6)< k
p5_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P6)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P7)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P7)< k
p6_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P7)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P8)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P8)< k
p7_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P8)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P9)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P9)< k
p8_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P9)< k
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type >
class GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P10)
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type >
GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P10)< k
p9_type InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8, p9_type p9)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (InvokeArgumentAction, P10)< k
template<typename T >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction,)
template<typename T >
GTEST_CONCAT_TOKEN_ (ReturnNewAction,)< T > ReturnNew()
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction,)< T >
template<typename T , typename p0_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P)< T
p0_type ReturnNew (p0_type p0)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P)< T
template<typename T , typename p0_type , typename p1_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P2)
template<typename T , typename p0_type , typename p1_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P2)< T
p1_type ReturnNew (p0_type p0, p1_type p1)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P2)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P3)
template<typename T , typename p0_type , typename p1_type , typename p2_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P3)< T
p2_type ReturnNew (p0_type p0, p1_type p1, p2_type p2)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P3)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P4)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P4)< T
p3_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P4)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P5)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P5)< T
p4_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P5)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P6)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P6)< T
p5_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P6)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P7)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P7)< T
p6_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P7)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P8)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P8)< T
p7_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P8)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P9)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P9)< T
p8_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P9)< T
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type >
class GTEST_CONCAT_TOKEN_ (ReturnNewAction, P10)
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type >
GTEST_CONCAT_TOKEN_ (ReturnNewAction, P10)< T
p9_type ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8, p9_type p9)
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type >
::testing::internal::Function< F >::Result GTEST_CONCAT_TOKEN_ (ReturnNewAction, P10)< T
template<typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher > Args (const InnerMatcher &matcher)
template<int k1, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1 > Args (const InnerMatcher &matcher)
template<int k1, int k2, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > Args (const InnerMatcher &matcher)
internal::ElementsAreMatcher< ::testing::tuple<> > ElementsAre ()
template<typename T1 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type > > ElementsAre (const T1 &e1)
template<typename T1 , typename T2 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > ElementsAre (const T1 &e1, const T2 &e2)
template<typename T1 , typename T2 , typename T3 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9, const T10 &e10)
internal::UnorderedElementsAreMatcher< ::testing::tuple<> > UnorderedElementsAre ()
template<typename T1 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type > > UnorderedElementsAre (const T1 &e1)
template<typename T1 , typename T2 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2)
template<typename T1 , typename T2 , typename T3 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9, const T10 &e10)
template<typename M1 , typename M2 >
internal::AllOfResult2< M1, M2 >::type AllOf (M1 m1, M2 m2)
template<typename M1 , typename M2 , typename M3 >
internal::AllOfResult3< M1, M2, M3 >::type AllOf (M1 m1, M2 m2, M3 m3)
template<typename M1 , typename M2 , typename M3 , typename M4 >
internal::AllOfResult4< M1, M2, M3, M4 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 >
internal::AllOfResult5< M1, M2, M3, M4, M5 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 >
internal::AllOfResult6< M1, M2, M3, M4, M5, M6 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 >
internal::AllOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 >
internal::AllOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 >
internal::AllOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 >
internal::AllOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10)
template<typename M1 , typename M2 >
internal::AnyOfResult2< M1, M2 >::type AnyOf (M1 m1, M2 m2)
template<typename M1 , typename M2 , typename M3 >
internal::AnyOfResult3< M1, M2, M3 >::type AnyOf (M1 m1, M2 m2, M3 m3)
template<typename M1 , typename M2 , typename M3 , typename M4 >
internal::AnyOfResult4< M1, M2, M3, M4 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 >
internal::AnyOfResult5< M1, M2, M3, M4, M5 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 >
internal::AnyOfResult6< M1, M2, M3, M4, M5, M6 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 >
internal::AnyOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 >
internal::AnyOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 >
internal::AnyOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 >
internal::AnyOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Matcher< T > &matcher)
template<typename T >
Matcher< T > MakeMatcher (const MatcherInterface< T > *impl)
template<class Impl >
PolymorphicMatcher< Impl > MakePolymorphicMatcher (const Impl &impl)
template<typename T , typename M >
Matcher< T > MatcherCast (const M &matcher)
template<typename T , typename M >
Matcher< T > SafeMatcherCast (const M &polymorphic_matcher)
template<typename T >
Matcher< T > A ()
template<typename Iter >
internal::ElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > ElementsAreArray (Iter first, Iter last)
template<typename T >
internal::ElementsAreArrayMatcher< T > ElementsAreArray (const T *pointer, size_t count)
template<typename T , size_t N>
internal::ElementsAreArrayMatcher< T > ElementsAreArray (const T(&array)[N])
template<typename Container >
internal::ElementsAreArrayMatcher< typename Container::value_type > ElementsAreArray (const Container &container)
template<typename Iter >
internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > UnorderedElementsAreArray (Iter first, Iter last)
template<typename T >
internal::UnorderedElementsAreArrayMatcher< T > UnorderedElementsAreArray (const T *pointer, size_t count)
template<typename T , size_t N>
internal::UnorderedElementsAreArrayMatcher< T > UnorderedElementsAreArray (const T(&array)[N])
template<typename Container >
internal::UnorderedElementsAreArrayMatcher< typename Container::value_type > UnorderedElementsAreArray (const Container &container)
template<typename T >
Matcher< T > An ()
template<typename T >
internal::EqMatcher< T > Eq (T x)
template<typename Lhs , typename Rhs >
Matcher< Lhs > TypedEq (const Rhs &rhs)
template<typename Rhs >
internal::GeMatcher< Rhs > Ge (Rhs x)
template<typename Rhs >
internal::GtMatcher< Rhs > Gt (Rhs x)
template<typename Rhs >
internal::LeMatcher< Rhs > Le (Rhs x)
template<typename Rhs >
internal::LtMatcher< Rhs > Lt (Rhs x)
template<typename Rhs >
internal::NeMatcher< Rhs > Ne (Rhs x)
PolymorphicMatcher< internal::IsNullMatcher > IsNull ()
PolymorphicMatcher< internal::NotNullMatcher > NotNull ()
template<typename T >
internal::RefMatcher< T & > Ref (T &x)
internal::FloatingEqMatcher< double > DoubleEq (double rhs)
internal::FloatingEqMatcher< double > NanSensitiveDoubleEq (double rhs)
internal::FloatingEqMatcher< double > DoubleNear (double rhs, double max_abs_error)
internal::FloatingEqMatcher< double > NanSensitiveDoubleNear (double rhs, double max_abs_error)
internal::FloatingEqMatcher< float > FloatEq (float rhs)
internal::FloatingEqMatcher< float > NanSensitiveFloatEq (float rhs)
internal::FloatingEqMatcher< float > FloatNear (float rhs, float max_abs_error)
internal::FloatingEqMatcher< float > NanSensitiveFloatNear (float rhs, float max_abs_error)
template<typename InnerMatcher >
internal::PointeeMatcher< InnerMatcher > Pointee (const InnerMatcher &inner_matcher)
template<typename Class , typename FieldType , typename FieldMatcher >
PolymorphicMatcher< internal::FieldMatcher< Class, FieldType > > Field (FieldType Class::*field, const FieldMatcher &matcher)
template<typename Class , typename FieldType , typename FieldMatcher >
PolymorphicMatcher< internal::FieldMatcher< Class, FieldType > > Field (const std::string &field_name, FieldType Class::*field, const FieldMatcher &matcher)
template<typename Class , typename PropertyType , typename PropertyMatcher >
PolymorphicMatcher< internal::PropertyMatcher< Class, PropertyType, PropertyType(Class::*)() const > > Property (PropertyType(Class::*property)() const, const PropertyMatcher &matcher)
template<typename Class , typename PropertyType , typename PropertyMatcher >
PolymorphicMatcher< internal::PropertyMatcher< Class, PropertyType, PropertyType(Class::*)() const > > Property (const std::string &property_name, PropertyType(Class::*property)() const, const PropertyMatcher &matcher)
template<typename Callable , typename ResultOfMatcher >
internal::ResultOfMatcher< Callable > ResultOf (Callable callable, const ResultOfMatcher &matcher)
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > StrEq (const std::string &str)
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > StrNe (const std::string &str)
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > StrCaseEq (const std::string &str)
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > StrCaseNe (const std::string &str)
PolymorphicMatcher< internal::HasSubstrMatcher< std::string > > HasSubstr (const std::string &substring)
PolymorphicMatcher< internal::StartsWithMatcher< std::string > > StartsWith (const std::string &prefix)
PolymorphicMatcher< internal::EndsWithMatcher< std::string > > EndsWith (const std::string &suffix)
PolymorphicMatcher< internal::MatchesRegexMatcher > MatchesRegex (const internal::RE *regex)
PolymorphicMatcher< internal::MatchesRegexMatcher > MatchesRegex (const std::string &regex)
PolymorphicMatcher< internal::MatchesRegexMatcher > ContainsRegex (const internal::RE *regex)
PolymorphicMatcher< internal::MatchesRegexMatcher > ContainsRegex (const std::string &regex)
internal::Eq2Matcher Eq ()
internal::Ge2Matcher Ge ()
internal::Gt2Matcher Gt ()
internal::Le2Matcher Le ()
internal::Lt2Matcher Lt ()
internal::Ne2Matcher Ne ()
internal::FloatingEq2Matcher< float > FloatEq ()
internal::FloatingEq2Matcher< double > DoubleEq ()
internal::FloatingEq2Matcher< float > NanSensitiveFloatEq ()
internal::FloatingEq2Matcher< double > NanSensitiveDoubleEq ()
internal::FloatingEq2Matcher< float > FloatNear (float max_abs_error)
internal::FloatingEq2Matcher< double > DoubleNear (double max_abs_error)
internal::FloatingEq2Matcher< float > NanSensitiveFloatNear (float max_abs_error)
internal::FloatingEq2Matcher< double > NanSensitiveDoubleNear (double max_abs_error)
template<typename InnerMatcher >
internal::NotMatcher< InnerMatcher > Not (InnerMatcher m)
template<typename Predicate >
PolymorphicMatcher< internal::TrulyMatcher< Predicate > > Truly (Predicate pred)
template<typename SizeMatcher >
internal::SizeIsMatcher< SizeMatcher > SizeIs (const SizeMatcher &size_matcher)
template<typename DistanceMatcher >
internal::BeginEndDistanceIsMatcher< DistanceMatcher > BeginEndDistanceIs (const DistanceMatcher &distance_matcher)
template<typename Container >
PolymorphicMatcher< internal::ContainerEqMatcher< GTEST_REMOVE_CONST_(Container)> > ContainerEq (const Container &rhs)
template<typename Comparator , typename ContainerMatcher >
internal::WhenSortedByMatcher< Comparator, ContainerMatcher > WhenSortedBy (const Comparator &comparator, const ContainerMatcher &container_matcher)
template<typename ContainerMatcher >
internal::WhenSortedByMatcher< internal::LessComparator, ContainerMatcher > WhenSorted (const ContainerMatcher &container_matcher)
template<typename TupleMatcher , typename Container >
internal::PointwiseMatcher< TupleMatcher, GTEST_REMOVE_CONST_(Container)> Pointwise (const TupleMatcher &tuple_matcher, const Container &rhs)
template<typename Tuple2Matcher , typename RhsContainer >
internal::UnorderedElementsAreArrayMatcher< typename internal::BoundSecondMatcher< Tuple2Matcher, typename internal::StlContainerView< GTEST_REMOVE_CONST_(RhsContainer)>::type::value_type > > UnorderedPointwise (const Tuple2Matcher &tuple2_matcher, const RhsContainer &rhs_container)
template<typename M >
internal::ContainsMatcher< M > Contains (M matcher)
template<typename Iter >
internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > IsSupersetOf (Iter first, Iter last)
template<typename T >
internal::UnorderedElementsAreArrayMatcher< T > IsSupersetOf (const T *pointer, size_t count)
template<typename T , size_t N>
internal::UnorderedElementsAreArrayMatcher< T > IsSupersetOf (const T(&array)[N])
template<typename Container >
internal::UnorderedElementsAreArrayMatcher< typename Container::value_type > IsSupersetOf (const Container &container)
template<typename Iter >
internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > IsSubsetOf (Iter first, Iter last)
template<typename T >
internal::UnorderedElementsAreArrayMatcher< T > IsSubsetOf (const T *pointer, size_t count)
template<typename T , size_t N>
internal::UnorderedElementsAreArrayMatcher< T > IsSubsetOf (const T(&array)[N])
template<typename Container >
internal::UnorderedElementsAreArrayMatcher< typename Container::value_type > IsSubsetOf (const Container &container)
template<typename M >
internal::EachMatcher< M > Each (M matcher)
template<typename M >
internal::KeyMatcher< M > Key (M inner_matcher)
template<typename FirstMatcher , typename SecondMatcher >
internal::PairMatcher< FirstMatcher, SecondMatcher > Pair (FirstMatcher first_matcher, SecondMatcher second_matcher)
template<typename M >
internal::MatcherAsPredicate< M > Matches (M matcher)
template<typename T , typename M >
bool Value (const T &value, M matcher)
template<typename T , typename M >
bool ExplainMatchResult (M matcher, const T &value, MatchResultListener *listener)
template<typename T , typename M >
std::string DescribeMatcher (const M &matcher, bool negation=false)
template<typename InnerMatcher >
InnerMatcher AllArgs (const InnerMatcher &matcher)
template<typename ValueMatcher >
internal::OptionalMatcher< ValueMatcher > Optional (const ValueMatcher &value_matcher)
template<typename T >
PolymorphicMatcher< internal::any_cast_matcher::AnyCastMatcher< T > > AnyWith (const Matcher< const T & > &matcher)
template<typename T >
PolymorphicMatcher< internal::variant_matcher::VariantMatcher< T > > VariantWith (const Matcher< const T & > &matcher)
template<typename FunctionImpl >
PolymorphicAction< internal::InvokeAction< FunctionImpl > > Invoke (FunctionImpl function_impl)
template<class Class , typename MethodPtr >
PolymorphicAction< internal::InvokeMethodAction< Class, MethodPtr > > Invoke (Class *obj_ptr, MethodPtr method_ptr)
template<typename InnerAction >
internal::WithArgsAction< InnerAction > WithoutArgs (const InnerAction &action)
template<int k, typename InnerAction >
internal::WithArgsAction< InnerAction, k > WithArg (const InnerAction &action)
ACTION_TEMPLATE (ReturnArg, HAS_1_TEMPLATE_PARAMS(int, k), AND_0_VALUE_PARAMS())
ACTION_TEMPLATE (SaveArg, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(pointer))
ACTION_TEMPLATE (SaveArgPointee, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(pointer))
ACTION_TEMPLATE (SetArgReferee, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(value))
ACTION_TEMPLATE (SetArrayArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_2_VALUE_PARAMS(first, last))
ACTION_TEMPLATE (DeleteArg, HAS_1_TEMPLATE_PARAMS(int, k), AND_0_VALUE_PARAMS())
ACTION_P (ReturnPointee, pointer)
MATCHER (IsEmpty, negation ? "isn't empty" :"is empty")
MATCHER (IsTrue, negation ? "is false" :"is true")
MATCHER (IsFalse, negation ? "is true" :"is false")
template<typename T >
const T & Const (const T &x)
GMOCK_DECLARE_bool_ (catch_leaked_mocks)
GMOCK_DECLARE_string_ (verbose)
GMOCK_DECLARE_int32_ (default_mock_behavior)
GTEST_API_ void InitGoogleMock (int *argc, char **argv)
GTEST_API_ void InitGoogleMock (int *argc, wchar_t **argv)
GMOCK_DEFINE_bool_ (catch_leaked_mocks, true, "true iff Google Mock should report leaked mock objects " "as failures.")
GMOCK_DEFINE_string_ (verbose, internal::kWarningVerbosity, "Controls how verbose Google Mock's output is." " Valid values:\n" " info - prints all messages.\n" " warning - prints warnings and errors.\n" " error - prints errors only.")
GMOCK_DEFINE_int32_ (default_mock_behavior, 1, "Controls the default behavior of mocks." " Valid values:\n" " 0 - by default, mocks act as NiceMocks.\n" " 1 - by default, mocks act as NaggyMocks.\n" " 2 - by default, mocks act as StrictMocks.")
GTEST_DECLARE_string_ (death_test_style)
std::ostream & operator<< (std::ostream &os, const Message &sb)
template<typename T , typename IncrementT >
internal::ParamGenerator< T > Range (T start, T end, IncrementT step)
template<typename T >
internal::ParamGenerator< T > Range (T start, T end)
template<typename ForwardIterator >
internal::ParamGenerator< typename ::testing::internal::IteratorTraits< ForwardIterator >::value_type > ValuesIn (ForwardIterator begin, ForwardIterator end)
template<typename T , size_t N>
internal::ParamGenerator< T > ValuesIn (const T(&array)[N])
template<class Container >
internal::ParamGenerator< typename Container::value_type > ValuesIn (const Container &container)
template<typename T1 >
internal::ValueArray1< T1 > Values (T1 v1)
template<typename T1 , typename T2 >
internal::ValueArray2< T1, T2 > Values (T1 v1, T2 v2)
template<typename T1 , typename T2 , typename T3 >
internal::ValueArray3< T1, T2, T3 > Values (T1 v1, T2 v2, T3 v3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
internal::ValueArray4< T1, T2, T3, T4 > Values (T1 v1, T2 v2, T3 v3, T4 v4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
internal::ValueArray5< T1, T2, T3, T4, T5 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
internal::ValueArray6< T1, T2, T3, T4, T5, T6 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
internal::ValueArray7< T1, T2, T3, T4, T5, T6, T7 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
internal::ValueArray8< T1, T2, T3, T4, T5, T6, T7, T8 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
internal::ValueArray9< T1, T2, T3, T4, T5, T6, T7, T8, T9 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
internal::ValueArray10< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 >
internal::ValueArray11< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 >
internal::ValueArray12< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 >
internal::ValueArray13< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 >
internal::ValueArray14< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 >
internal::ValueArray15< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 >
internal::ValueArray16< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 >
internal::ValueArray17< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 >
internal::ValueArray18< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 >
internal::ValueArray19< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 >
internal::ValueArray20< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 >
internal::ValueArray21< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 >
internal::ValueArray22< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 >
internal::ValueArray23< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 >
internal::ValueArray24< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 >
internal::ValueArray25< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 >
internal::ValueArray26< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 >
internal::ValueArray27< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 >
internal::ValueArray28< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 >
internal::ValueArray29< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 >
internal::ValueArray30< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 >
internal::ValueArray31< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 >
internal::ValueArray32< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 >
internal::ValueArray33< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 >
internal::ValueArray34< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 >
internal::ValueArray35< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 >
internal::ValueArray36< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 >
internal::ValueArray37< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 >
internal::ValueArray38< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 >
internal::ValueArray39< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 >
internal::ValueArray40< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 >
internal::ValueArray41< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 >
internal::ValueArray42< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 >
internal::ValueArray43< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 >
internal::ValueArray44< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 >
internal::ValueArray45< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 >
internal::ValueArray46< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 >
internal::ValueArray47< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 , typename T48 >
internal::ValueArray48< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47, T48 v48)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 , typename T48 , typename T49 >
internal::ValueArray49< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47, T48 v48, T49 v49)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 , typename T48 , typename T49 , typename T50 >
internal::ValueArray50< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49, T50 > Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47, T48 v48, T49 v49, T50 v50)
internal::ParamGenerator< bool > Bool ()
template<typename T >
::std::string PrintToString (const T &value)
std::ostream & operator<< (std::ostream &os, const TestPartResult &result)
GTEST_DECLARE_bool_ (also_run_disabled_tests)
GTEST_DECLARE_bool_ (break_on_failure)
GTEST_DECLARE_bool_ (catch_exceptions)
GTEST_DECLARE_string_ (color)
GTEST_DECLARE_string_ (filter)
GTEST_DECLARE_bool_ (list_tests)
GTEST_DECLARE_string_ (output)
GTEST_DECLARE_bool_ (print_time)
GTEST_DECLARE_bool_ (print_utf8)
GTEST_DECLARE_int32_ (random_seed)
GTEST_DECLARE_int32_ (repeat)
GTEST_DECLARE_bool_ (show_internal_stack_frames)
GTEST_DECLARE_bool_ (shuffle)
GTEST_DECLARE_int32_ (stack_trace_depth)
GTEST_DECLARE_bool_ (throw_on_failure)
GTEST_DECLARE_string_ (stream_result_to)
GTEST_API_ AssertionResult AssertionSuccess ()
GTEST_API_ AssertionResult AssertionFailure ()
GTEST_API_ AssertionResult AssertionFailure (const Message &msg)
Environment * AddGlobalTestEnvironment (Environment *env)
GTEST_API_ void InitGoogleTest (int *argc, char **argv)
GTEST_API_ void InitGoogleTest (int *argc, wchar_t **argv)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
GTEST_API_ AssertionResult FloatLE (const char *expr1, const char *expr2, float val1, float val2)
GTEST_API_ AssertionResult DoubleLE (const char *expr1, const char *expr2, double val1, double val2)
template<typename T1 , typename T2 >
bool StaticAssertTypeEq ()
GTEST_API_ std::string TempDir ()
template<typename Pred , typename T1 >
AssertionResult AssertPred1Helper (const char *pred_text, const char *e1, Pred pred, const T1 &v1)
template<typename Pred , typename T1 , typename T2 >
AssertionResult AssertPred2Helper (const char *pred_text, const char *e1, const char *e2, Pred pred, const T1 &v1, const T2 &v2)
template<typename Pred , typename T1 , typename T2 , typename T3 >
AssertionResult AssertPred3Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3)
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 >
AssertionResult AssertPred4Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, const char *e4, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
AssertionResult AssertPred5Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, const char *e4, const char *e5, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)
GTEST_DEFINE_string_ (death_test_style, internal::StringFromGTestEnv("death_test_style", kDefaultDeathTestStyle), "Indicates how to run a death test in a forked child process: " "\"threadsafe\" (child process re-executes the test binary " "from the beginning, running only the specific death test) or " "\"fast\" (child process runs the death test immediately " "after forking).")
GTEST_DEFINE_bool_ (death_test_use_fork, internal::BoolFromGTestEnv("death_test_use_fork", false), "Instructs to use fork()/_exit() instead of clone() in death tests. " "Ignored and always uses fork() on POSIX systems where clone() is not " "implemented. Useful when running under valgrind or similar tools if " "those do not support clone(). Valgrind 3.3.1 will just fail if " "it sees an unsupported combination of clone() flags. " "It is not recommended to use this flag w/o valgrind though it will " "work in 99% of the cases. Once valgrind is fixed, this flag will " "most likely be removed.")
GTEST_DECLARE_bool_ (death_test_use_fork)
static const char * GetDefaultFilter ()
GTEST_DEFINE_bool_ (also_run_disabled_tests, internal::BoolFromGTestEnv("also_run_disabled_tests", false), "Run disabled tests too, in addition to the tests normally being run.")
GTEST_DEFINE_bool_ (break_on_failure, internal::BoolFromGTestEnv("break_on_failure", false), "True iff a failed assertion should be a debugger break-point.")
GTEST_DEFINE_bool_ (catch_exceptions, internal::BoolFromGTestEnv("catch_exceptions", true), "True iff " GTEST_NAME_ " should catch exceptions and treat them as test failures.")
GTEST_DEFINE_string_ (color, internal::StringFromGTestEnv("color", "auto"), "Whether to use colors in the output. Valid values: yes, no, " "and auto. 'auto' means to use colors if the output is " "being sent to a terminal and the TERM environment variable " "is set to a terminal type that supports colors.")
GTEST_DEFINE_string_ (filter, internal::StringFromGTestEnv("filter", GetDefaultFilter()), "A colon-separated list of glob (not regex) patterns " "for filtering the tests to run, optionally followed by a " "'-' and a : separated list of negative patterns (tests to " "exclude). A test is run if it matches one of the positive " "patterns and does not match any of the negative patterns.")
GTEST_DEFINE_bool_ (list_tests, false, "List all tests without running them.")
GTEST_DEFINE_string_ (output, internal::StringFromGTestEnv("output", internal::OutputFlagAlsoCheckEnvVar().c_str()), "A format (defaults to \"xml\" but can be specified to be \"json\"), " "optionally followed by a colon and an output file name or directory. " "A directory is indicated by a trailing pathname separator. " "Examples: \"xml:filename.xml\", \"xml::directoryname/\". " "If a directory is specified, output files will be created " "within that directory, with file-names based on the test " "executable's name and, if necessary, made unique by adding " "digits.")
GTEST_DEFINE_bool_ (print_time, internal::BoolFromGTestEnv("print_time", true), "True iff " GTEST_NAME_ " should display elapsed time in text output.")
GTEST_DEFINE_bool_ (print_utf8, internal::BoolFromGTestEnv("print_utf8", true), "True iff " GTEST_NAME_ " prints UTF8 characters as text.")
GTEST_DEFINE_int32_ (random_seed, internal::Int32FromGTestEnv("random_seed", 0), "Random number seed to use when shuffling test orders. Must be in range " "[1, 99999], or 0 to use a seed based on the current time.")
GTEST_DEFINE_int32_ (repeat, internal::Int32FromGTestEnv("repeat", 1), "How many times to repeat each test. Specify a negative number " "for repeating forever. Useful for shaking out flaky tests.")
GTEST_DEFINE_bool_ (show_internal_stack_frames, false, "True iff " GTEST_NAME_ " should include internal stack frames when " "printing test failure stack traces.")
GTEST_DEFINE_bool_ (shuffle, internal::BoolFromGTestEnv("shuffle", false), "True iff " GTEST_NAME_ " should randomize tests' order on every run.")
GTEST_DEFINE_int32_ (stack_trace_depth, internal::Int32FromGTestEnv("stack_trace_depth", kMaxStackTraceDepth), "The maximum number of stack frames to print when an " "assertion fails. The valid range is 0 through 100, inclusive.")
GTEST_DEFINE_string_ (stream_result_to, internal::StringFromGTestEnv("stream_result_to", ""), "This flag specifies the host name and the port number on which to stream " "test results. Example: \"localhost:555\". The flag is effective only on " "Linux.")
GTEST_DEFINE_bool_ (throw_on_failure, internal::BoolFromGTestEnv("throw_on_failure", false), "When this flag is specified, a failed assertion will throw an exception " "if exceptions are enabled or exit the program with a non-zero code " "otherwise. For use with an external test framework.")
template<int kSize>
std::vector< std::string > ArrayAsVector (const char *const (&array)[kSize])
static std::vector< std::string > GetReservedAttributesForElement (const std::string &xml_element)
static std::string FormatWordList (const std::vector< std::string > &words)
static bool ValidateTestPropertyName (const std::string &property_name, const std::vector< std::string > &reserved_names)
static bool TestPartFatallyFailed (const TestPartResult &result)
static bool TestPartNonfatallyFailed (const TestPartResult &result)
static std::string FormatCountableNoun (int count, const char *singular_form, const char *plural_form)
static std::string FormatTestCount (int test_count)
static std::string FormatTestCaseCount (int test_case_count)
static const char * TestPartResultTypeToString (TestPartResult::Type type)
TEST (GTestEnvVarTest, Dummy)
void PrintFlag (const char *flag)
TEST (SuccessfulAssertionTest, SUCCEED)
TEST (SuccessfulAssertionTest, EXPECT)
TEST (SuccessfulAssertionTest, EXPECT_STR)
TEST (SuccessfulAssertionTest, ASSERT)
TEST (SuccessfulAssertionTest, ASSERT_STR)
TEST_F (TestInfoTest, Names)
TEST_F (TestInfoTest, result)
TEST (CodeLocationForTEST, Verify)
TEST_F (CodeLocationForTESTF, Verify)
TEST_P (CodeLocationForTESTP, Verify)
INSTANTIATE_TEST_CASE_P (, CodeLocationForTESTP, Values(0))
TYPED_TEST_CASE (CodeLocationForTYPEDTEST, int)
TYPED_TEST (CodeLocationForTYPEDTEST, Verify)
TYPED_TEST_CASE_P (CodeLocationForTYPEDTESTP)
TYPED_TEST_P (CodeLocationForTYPEDTESTP, Verify)
REGISTER_TYPED_TEST_CASE_P (CodeLocationForTYPEDTESTP, Verify)
INSTANTIATE_TYPED_TEST_CASE_P (My, CodeLocationForTYPEDTESTP, int)
TEST_F (SetUpTestCaseTest, Test1)
TEST_F (SetUpTestCaseTest, Test2)
TEST_F (ParseFlagsTest, Empty)
TEST_F (ParseFlagsTest, NoFlag)
TEST_F (ParseFlagsTest, FilterBad)
TEST_F (ParseFlagsTest, FilterEmpty)
TEST_F (ParseFlagsTest, FilterNonEmpty)
TEST_F (ParseFlagsTest, BreakOnFailureWithoutValue)
TEST_F (ParseFlagsTest, BreakOnFailureFalse_0)
TEST_F (ParseFlagsTest, BreakOnFailureFalse_f)
TEST_F (ParseFlagsTest, BreakOnFailureFalse_F)
TEST_F (ParseFlagsTest, BreakOnFailureTrue)
TEST_F (ParseFlagsTest, CatchExceptions)
TEST_F (ParseFlagsTest, DeathTestUseFork)
TEST_F (ParseFlagsTest, DuplicatedFlags)
TEST_F (ParseFlagsTest, UnrecognizedFlag)
TEST_F (ParseFlagsTest, ListTestsFlag)
TEST_F (ParseFlagsTest, ListTestsTrue)
TEST_F (ParseFlagsTest, ListTestsFalse)
TEST_F (ParseFlagsTest, ListTestsFalse_f)
TEST_F (ParseFlagsTest, ListTestsFalse_F)
TEST_F (ParseFlagsTest, OutputEmpty)
TEST_F (ParseFlagsTest, OutputXml)
TEST_F (ParseFlagsTest, OutputXmlFile)
TEST_F (ParseFlagsTest, OutputXmlDirectory)
TEST_F (ParseFlagsTest, PrintTimeFlag)
TEST_F (ParseFlagsTest, PrintTimeTrue)
TEST_F (ParseFlagsTest, PrintTimeFalse)
TEST_F (ParseFlagsTest, PrintTimeFalse_f)
TEST_F (ParseFlagsTest, PrintTimeFalse_F)
TEST_F (ParseFlagsTest, RandomSeed)
TEST_F (ParseFlagsTest, Repeat)
TEST_F (ParseFlagsTest, AlsoRunDisabledTestsFlag)
TEST_F (ParseFlagsTest, AlsoRunDisabledTestsTrue)
TEST_F (ParseFlagsTest, AlsoRunDisabledTestsFalse)
TEST_F (ParseFlagsTest, ShuffleWithoutValue)
TEST_F (ParseFlagsTest, ShuffleFalse_0)
TEST_F (ParseFlagsTest, ShuffleTrue)
TEST_F (ParseFlagsTest, StackTraceDepth)
TEST_F (ParseFlagsTest, StreamResultTo)
TEST_F (ParseFlagsTest, ThrowOnFailureWithoutValue)
TEST_F (ParseFlagsTest, ThrowOnFailureFalse_0)
TEST_F (ParseFlagsTest, ThrowOnFailureTrue)
TEST_F (CurrentTestInfoTest, WorksForFirstTestInATestCase)
TEST_F (CurrentTestInfoTest, WorksForSecondTestInATestCase)
Variables
p0_type
p1_type
p2_type
p3_type
p4_type
p5_type
p6_type
p7_type
p8_type
const internal::AnythingMatcher _ = {}
class GTEST_API_ testing::InSequence GTEST_ATTRIBUTE_UNUSED_
const int kMaxStackTraceDepth = 100
static const char kDefaultDeathTestStyle [] = GTEST_DEFAULT_DEATH_TEST_STYLE
static const char kDisableTestFilter [] = "DISABLED_*:*/DISABLED_*"
static const char kDeathTestCaseFilter [] = "*DeathTest:*DeathTest/*"
static const char kUniversalFilter [] = "*"
static const char kDefaultOutputFormat [] = "xml"
static const char kDefaultOutputFile [] = "test_detail"
static const char kTestShardIndex [] = "GTEST_SHARD_INDEX"
static const char kTestTotalShards [] = "GTEST_TOTAL_SHARDS"
static const char kTestShardStatusFile [] = "GTEST_SHARD_STATUS_FILE"
static const char *const kReservedTestSuitesAttributes []
static const char *const kReservedTestSuiteAttributes []
static const char *const kReservedTestCaseAttributes []
Typedef Documentation
TimeInMillis
typedef internal::TimeInMillis testing::TimeInMillis private
Definition at line 506 of file gtest.h.
Unused
typedef internal::IgnoredValue testing::Unused
Definition at line 1097 of file gmock-actions.h.
Function Documentation
A()
template<typename T > Matcher< T > testing::A () inline
Definition at line 4287 of file gmock-matchers.h.
                      {
  return Matcher<T>(new internal::AnyMatcherImpl<T>());
}
ACTION_P()
testing::ACTION_P (ReturnPointee , pointer)
Definition at line 222 of file gmock-more-actions.h.
{ return *pointer; }
ACTION_TEMPLATE() [1/6]
testing::ACTION_TEMPLATE (DeleteArg , HAS_1_TEMPLATE_PARAMS(int, k) , AND_0_VALUE_PARAMS())
Definition at line 215 of file gmock-more-actions.h.
{
  delete ::testing::get<k>(args);
}
ACTION_TEMPLATE() [2/6]
testing::ACTION_TEMPLATE (ReturnArg , HAS_1_TEMPLATE_PARAMS(int, k) , AND_0_VALUE_PARAMS())
Definition at line 161 of file gmock-more-actions.h.
{
  return ::testing::get<k>(args);
}
ACTION_TEMPLATE() [3/6]
testing::ACTION_TEMPLATE (SaveArg , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(pointer))
Definition at line 169 of file gmock-more-actions.h.
{
  *pointer = ::testing::get<k>(args);
}
ACTION_TEMPLATE() [4/6]
testing::ACTION_TEMPLATE (SaveArgPointee , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(pointer))
Definition at line 177 of file gmock-more-actions.h.
{
  *pointer = *::testing::get<k>(args);
}
ACTION_TEMPLATE() [5/6]
testing::ACTION_TEMPLATE (SetArgReferee , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(value))
Definition at line 185 of file gmock-more-actions.h.
{
  typedef typename ::testing::tuple_element<k, args_type>::type argk_type;
  // Ensures that argument #k is a reference.  If you get a compiler
  // error on the next line, you are using SetArgReferee<k>(value) in
  // a mock function whose k-th (0-based) argument is not a reference.
  GTEST_COMPILE_ASSERT_(internal::is_reference<argk_type>::value,
                        SetArgReferee_must_be_used_with_a_reference_argument);
  ::testing::get<k>(args) = value;
}
References GTEST_COMPILE_ASSERT_.
ACTION_TEMPLATE() [6/6]
testing::ACTION_TEMPLATE (SetArrayArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_2_VALUE_PARAMS(first, last))
Definition at line 202 of file gmock-more-actions.h.
{
  // Visual Studio deprecates ::std::copy, so we use our own copy in that case.
#ifdef _MSC_VER
  internal::CopyElements(first, last, ::testing::get<k>(args));
#else
  ::std::copy(first, last, ::testing::get<k>(args));
#endif
}
References testing::internal::CopyElements().
AddGlobalTestEnvironment()
Environment * testing::AddGlobalTestEnvironment (Environment * env) inline private
Definition at line 1391 of file gtest.h.
{
  return UnitTest::GetInstance()->AddEnvironment(env);
}
AllArgs()
template<typename InnerMatcher > InnerMatcher testing::AllArgs (const InnerMatcher & matcher) inline
Definition at line 5204 of file gmock-matchers.h.
{ return matcher; }
References AllArgs().
AllOf() [1/9]
template<typename M1 , typename M2 > internal::AllOfResult2< M1, M2 >::type testing::AllOf (M1 m1, M2 m2) inline
Definition at line 1005 of file gmock-generated-matchers.h.
                    {
  return typename internal::AllOfResult2<M1, M2>::type(
      m1,
      m2);
}
References AllOf().
AllOf() [2/9]
template<typename M1 , typename M2 , typename M3 > internal::AllOfResult3< M1, M2, M3 >::type testing::AllOf (M1 m1, M2 m2, M3 m3) inline
Definition at line 1013 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult3<M1, M2, M3>::type(
      m1,
      ::testing::AllOf(m2, m3));
}
References AllOf().
AllOf() [3/9]
template<typename M1 , typename M2 , typename M3 , typename M4 > internal::AllOfResult4< M1, M2, M3, M4 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4) inline
Definition at line 1021 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult4<M1, M2, M3, M4>::type(
      ::testing::AllOf(m1, m2),
      ::testing::AllOf(m3, m4));
}
References AllOf().
AllOf() [4/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 > internal::AllOfResult5< M1, M2, M3, M4, M5 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5) inline
Definition at line 1029 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult5<M1, M2, M3, M4, M5>::type(
      ::testing::AllOf(m1, m2),
      ::testing::AllOf(m3, m4, m5));
}
References AllOf().
AllOf() [5/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 > internal::AllOfResult6< M1, M2, M3, M4, M5, M6 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6) inline
Definition at line 1038 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult6<M1, M2, M3, M4, M5, M6>::type(
      ::testing::AllOf(m1, m2, m3),
      ::testing::AllOf(m4, m5, m6));
}
References AllOf().
AllOf() [6/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 > internal::AllOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7) inline
Definition at line 1047 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult7<M1, M2, M3, M4, M5, M6, M7>::type(
      ::testing::AllOf(m1, m2, m3),
      ::testing::AllOf(m4, m5, m6, m7));
}
References AllOf().
AllOf() [7/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 > internal::AllOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8) inline
Definition at line 1056 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult8<M1, M2, M3, M4, M5, M6, M7, M8>::type(
      ::testing::AllOf(m1, m2, m3, m4),
      ::testing::AllOf(m5, m6, m7, m8));
}
References AllOf().
AllOf() [8/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 > internal::AllOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9) inline
Definition at line 1065 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult9<M1, M2, M3, M4, M5, M6, M7, M8,
      M9>::type(
      ::testing::AllOf(m1, m2, m3, m4),
      ::testing::AllOf(m5, m6, m7, m8, m9));
}
References AllOf().
AllOf() [9/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 > internal::AllOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10) inline
Definition at line 1076 of file gmock-generated-matchers.h.
{
  return typename internal::AllOfResult10<M1, M2, M3, M4, M5, M6, M7, M8, M9,
      M10>::type(
      ::testing::AllOf(m1, m2, m3, m4, m5),
      ::testing::AllOf(m6, m7, m8, m9, m10));
}
References AllOf().
An()
template<typename T > Matcher< T > testing::An () inline
Definition at line 4293 of file gmock-matchers.h.
{ return A<T>(); }
AnyNumber()
GTEST_API_ Cardinality testing::AnyNumber ()
Definition at line 146 of file gmock-cardinalities.cc.
{ return AtLeast(0); }
References AtLeast().
AnyOf() [1/9]
template<typename M1 , typename M2 > internal::AnyOfResult2< M1, M2 >::type testing::AnyOf (M1 m1, M2 m2) inline
Definition at line 1088 of file gmock-generated-matchers.h.
                    {
  return typename internal::AnyOfResult2<M1, M2>::type(
      m1,
      m2);
}
References AnyOf().
AnyOf() [2/9]
template<typename M1 , typename M2 , typename M3 > internal::AnyOfResult3< M1, M2, M3 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3) inline
Definition at line 1096 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult3<M1, M2, M3>::type(
      m1,
      ::testing::AnyOf(m2, m3));
}
References AnyOf().
AnyOf() [3/9]
template<typename M1 , typename M2 , typename M3 , typename M4 > internal::AnyOfResult4< M1, M2, M3, M4 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4) inline
Definition at line 1104 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult4<M1, M2, M3, M4>::type(
      ::testing::AnyOf(m1, m2),
      ::testing::AnyOf(m3, m4));
}
References AnyOf().
AnyOf() [4/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 > internal::AnyOfResult5< M1, M2, M3, M4, M5 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5) inline
Definition at line 1112 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult5<M1, M2, M3, M4, M5>::type(
      ::testing::AnyOf(m1, m2),
      ::testing::AnyOf(m3, m4, m5));
}
References AnyOf().
AnyOf() [5/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 > internal::AnyOfResult6< M1, M2, M3, M4, M5, M6 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6) inline
Definition at line 1121 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult6<M1, M2, M3, M4, M5, M6>::type(
      ::testing::AnyOf(m1, m2, m3),
      ::testing::AnyOf(m4, m5, m6));
}
References AnyOf().
AnyOf() [6/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 > internal::AnyOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7) inline
Definition at line 1130 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult7<M1, M2, M3, M4, M5, M6, M7>::type(
      ::testing::AnyOf(m1, m2, m3),
      ::testing::AnyOf(m4, m5, m6, m7));
}
References AnyOf().
AnyOf() [7/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 > internal::AnyOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8) inline
Definition at line 1139 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult8<M1, M2, M3, M4, M5, M6, M7, M8>::type(
      ::testing::AnyOf(m1, m2, m3, m4),
      ::testing::AnyOf(m5, m6, m7, m8));
}
References AnyOf().
AnyOf() [8/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 > internal::AnyOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9) inline
Definition at line 1148 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult9<M1, M2, M3, M4, M5, M6, M7, M8,
      M9>::type(
      ::testing::AnyOf(m1, m2, m3, m4),
      ::testing::AnyOf(m5, m6, m7, m8, m9));
}
References AnyOf().
AnyOf() [9/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 > internal::AnyOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10) inline
Definition at line 1159 of file gmock-generated-matchers.h.
{
  return typename internal::AnyOfResult10<M1, M2, M3, M4, M5, M6, M7, M8, M9,
      M10>::type(
      ::testing::AnyOf(m1, m2, m3, m4, m5),
      ::testing::AnyOf(m6, m7, m8, m9, m10));
}
References AnyOf().
AnyWith()
template<typename T > PolymorphicMatcher< internal::any_cast_matcher::AnyCastMatcher< T > > testing::AnyWith (const Matcher< const T & > & matcher)
Definition at line 5222 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::any_cast_matcher::AnyCastMatcher<T>(matcher));
}
References MakePolymorphicMatcher().
Args() [1/11]
template<typename InnerMatcher > internal::ArgsMatcher< InnerMatcher > testing::Args (const InnerMatcher & matcher) inline
Definition at line 481 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher>(matcher);
}
References Args().
Args() [2/11]
template<int k1, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 487 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1>(matcher);
}
References Args().
Args() [3/11]
template<int k1, int k2, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 493 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2>(matcher);
}
References Args().
Args() [4/11]
template<int k1, int k2, int k3, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 499 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3>(matcher);
}
References Args().
Args() [5/11]
template<int k1, int k2, int k3, int k4, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 505 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4>(matcher);
}
References Args().
Args() [6/11]
template<int k1, int k2, int k3, int k4, int k5, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 511 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4, k5>(matcher);
}
References Args().
Args() [7/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 517 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4, k5, k6>(matcher);
}
References Args().
Args() [8/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 524 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4, k5, k6,
      k7>(matcher);
}
References Args().
Args() [9/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 532 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4, k5, k6, k7,
      k8>(matcher);
}
References Args().
Args() [10/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 540 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8,
      k9>(matcher);
}
References Args().
Args() [11/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > testing::Args (const InnerMatcher & matcher) inline
Definition at line 549 of file gmock-generated-matchers.h.
{
  return internal::ArgsMatcher<InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8,
      k9, k10>(matcher);
}
References Args().
ArrayAsVector()
template<int kSize> std::vector< std::string > testing::ArrayAsVector (const char *const (&) array[kSize])
Definition at line 2123 of file gtest.cc.
{
  return std::vector<std::string>(array, array + kSize);
}
AssertionFailure() [1/2]
AssertionResult testing::AssertionFailure ()
Definition at line 1029 of file gtest.cc.
{
  return AssertionResult(false);
}
AssertionFailure() [2/2]
AssertionResult testing::AssertionFailure (const Message & msg)
Definition at line 1035 of file gtest.cc.
{
  return AssertionFailure() << message;
}
References AssertionFailure().
AssertionSuccess()
AssertionResult testing::AssertionSuccess ()
Definition at line 1024 of file gtest.cc.
{
  return AssertionResult(true);
}
AssertPred1Helper()
template<typename Pred , typename T1 > AssertionResult testing::AssertPred1Helper (const char * pred_text, const char * e1, Pred pred, const T1 & v1)
Definition at line 84 of file gtest_pred_impl.h.
{
  if (pred(v1)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1;
}
References AssertionFailure(), and AssertionSuccess().
AssertPred2Helper()
template<typename Pred , typename T1 , typename T2 > AssertionResult testing::AssertPred2Helper (const char * pred_text, const char * e1, const char * e2, Pred pred, const T1 & v1, const T2 & v2)
Definition at line 126 of file gtest_pred_impl.h.
{
  if (pred(v1, v2)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2;
}
References AssertionFailure(), and AssertionSuccess().
AssertPred3Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 > AssertionResult testing::AssertPred3Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3)
Definition at line 175 of file gtest_pred_impl.h.
{
  if (pred(v1, v2, v3)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ", "
                            << e3 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2
                            << "\n" << e3 << " evaluates to " << v3;
}
References AssertionFailure(), and AssertionSuccess().
AssertPred4Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 > AssertionResult testing::AssertPred4Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, const char * e4, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4)
Definition at line 231 of file gtest_pred_impl.h.
{
  if (pred(v1, v2, v3, v4)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ", "
                            << e3 << ", "
                            << e4 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2
                            << "\n" << e3 << " evaluates to " << v3
                            << "\n" << e4 << " evaluates to " << v4;
}
References AssertionFailure(), and AssertionSuccess().
AssertPred5Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > AssertionResult testing::AssertPred5Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, const char * e4, const char * e5, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5)
Definition at line 294 of file gtest_pred_impl.h.
{
  if (pred(v1, v2, v3, v4, v5)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ", "
                            << e3 << ", "
                            << e4 << ", "
                            << e5 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2
                            << "\n" << e3 << " evaluates to " << v3
                            << "\n" << e4 << " evaluates to " << v4
                            << "\n" << e5 << " evaluates to " << v5;
}
References AssertionFailure(), and AssertionSuccess().
Assign()
template<typename T1 , typename T2 > PolymorphicAction< internal::AssignAction< T1, T2 > > testing::Assign (T1 * ptr, T2 val)
Definition at line 1204 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::AssignAction<T1, T2>(ptr, val));
}
References Assign(), and MakePolymorphicAction().
AtLeast()
GTEST_API_ Cardinality testing::AtLeast (int n)
Definition at line 140 of file gmock-cardinalities.cc.
{ return Between(n, INT_MAX); }
References AtLeast(), and Between().
AtMost()
GTEST_API_ Cardinality testing::AtMost (int n)
Definition at line 143 of file gmock-cardinalities.cc.
{ return Between(0, n); }
References AtMost(), and Between().
BeginEndDistanceIs()
template<typename DistanceMatcher > internal::BeginEndDistanceIsMatcher< DistanceMatcher > testing::BeginEndDistanceIs (const DistanceMatcher & distance_matcher) inline
Definition at line 4800 of file gmock-matchers.h.
{
  return internal::BeginEndDistanceIsMatcher<DistanceMatcher>(distance_matcher);
}
Between()
GTEST_API_ Cardinality testing::Between (int min, int max)
Definition at line 149 of file gmock-cardinalities.cc.
{
  return Cardinality(new BetweenCardinalityImpl(min, max));
}
References Between().
Bool()
internal::ParamGenerator< bool > testing::Bool () inline
Definition at line 1216 of file gtest-param-test.h.
{
  return Values(false, true);
}
References Values().
ByMove()
template<typename R > internal::ByMoveWrapper< R > testing::ByMove (R x)
Definition at line 1151 of file gmock-actions.h.
{
  return internal::ByMoveWrapper<R>(internal::move(x));
}
References ByMove(), and testing::internal::move().
ByRef()
template<typename T > internal::ReferenceWrapper< T > testing::ByRef (T & l_value) inline
Definition at line 1256 of file gmock-actions.h.
                                                     {  // NOLINT
  return internal::ReferenceWrapper<T>(l_value);
}
References ByRef().
Const()
template<typename T > const T & testing::Const (const T & x) inline
Definition at line 1838 of file gmock-spec-builders.h.
{ return x; }
References Const().
ContainerEq()
template<typename Container > PolymorphicMatcher< internal::ContainerEqMatcher< GTEST_REMOVE_CONST_(Container)> > testing::ContainerEq (const Container & rhs) inline
Definition at line 4811 of file gmock-matchers.h.
{
  // This following line is for working around a bug in MSVC 8.0,
  // which causes Container to be a const type sometimes.
  typedef GTEST_REMOVE_CONST_(Container) RawContainer;
  return MakePolymorphicMatcher(
      internal::ContainerEqMatcher<RawContainer>(rhs));
}
References ContainerEq(), GTEST_REMOVE_CONST_, and MakePolymorphicMatcher().
Contains()
template<typename M > internal::ContainsMatcher< M > testing::Contains (M matcher) inline
Definition at line 4943 of file gmock-matchers.h.
{
  return internal::ContainsMatcher<M>(matcher);
}
References Contains().
ContainsRegex() [1/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::ContainsRegex (const internal::RE * regex) inline
Definition at line 4625 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(internal::MatchesRegexMatcher(regex, false));
}
References ContainsRegex(), and MakePolymorphicMatcher().
ContainsRegex() [2/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::ContainsRegex (const std::string & regex) inline
Definition at line 4629 of file gmock-matchers.h.
{
  return ContainsRegex(new internal::RE(regex));
}
References ContainsRegex().
DescribeMatcher()
template<typename T , typename M > std::string testing::DescribeMatcher (const M & matcher, bool negation = false)
Definition at line 5153 of file gmock-matchers.h.
{
  ::std::stringstream ss;
  Matcher<T> monomorphic_matcher = SafeMatcherCast<T>(matcher);
  if (negation) {
    monomorphic_matcher.DescribeNegationTo(&ss);
  } else {
    monomorphic_matcher.DescribeTo(&ss);
  }
  return ss.str();
}
References testing::internal::MatcherBase< T >::DescribeNegationTo(), and testing::internal::MatcherBase< T >::DescribeTo().
DoAll() [1/9]
template<typename Action1 , typename Action2 > internal::DoBothAction< Action1, Action2 > testing::DoAll (Action1 a1, Action2 a2) inline
Definition at line 776 of file gmock-generated-actions.h.
{
  return internal::DoBothAction<Action1, Action2>(a1, a2);
}
References DoAll().
DoAll() [2/9]
template<typename Action1 , typename Action2 , typename Action3 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, Action3 > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3) inline
Definition at line 783 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3));
}
References DoAll().
DoAll() [3/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, Action4 > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4) inline
Definition at line 791 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3, a4));
}
References DoAll().
DoAll() [4/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, Action5 > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5) inline
Definition at line 800 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3, a4, a5));
}
References DoAll().
DoAll() [5/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, Action6 > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6) inline
Definition at line 809 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3, a4, a5, a6));
}
References DoAll().
DoAll() [6/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, Action7 > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7) inline
Definition at line 819 of file gmock-generated-actions.h.
                {
  return DoAll(a1, DoAll(a2, a3, a4, a5, a6, a7));
}
References DoAll().
DoAll() [7/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, Action8 > > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8) inline
Definition at line 831 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3, a4, a5, a6, a7, a8));
}
References DoAll().
DoAll() [8/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, Action9 > > > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9) inline
Definition at line 844 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3, a4, a5, a6, a7, a8, a9));
}
References DoAll().
DoAll() [9/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 , typename Action10 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, internal::DoBothAction< Action9, Action10 > > > > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9, Action10 a10) inline
Definition at line 857 of file gmock-generated-actions.h.
{
  return DoAll(a1, DoAll(a2, a3, a4, a5, a6, a7, a8, a9, a10));
}
References DoAll().
DoDefault()
internal::DoDefaultAction testing::DoDefault () inline
Definition at line 1156 of file gmock-actions.h.
{
  return internal::DoDefaultAction();
}
DoubleEq() [1/2]
internal::FloatingEq2Matcher< double > testing::DoubleEq () inline
Definition at line 4721 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<double>();
}
DoubleEq() [2/2]
internal::FloatingEqMatcher< double > testing::DoubleEq (double rhs) inline
Definition at line 4380 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<double>(rhs, false);
}
DoubleLE()
AssertionResult testing::DoubleLE (const char * expr1, const char * expr2, double val1, double val2) private
Definition at line 1443 of file gtest.cc.
{
  return internal::FloatingPointLE<double>(expr1, expr2, val1, val2);
}
References DoubleLE().
DoubleNear() [1/2]
internal::FloatingEq2Matcher< double > testing::DoubleNear (double max_abs_error) inline
Definition at line 4745 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<double>(max_abs_error);
}
References DoubleNear().
DoubleNear() [2/2]
internal::FloatingEqMatcher< double > testing::DoubleNear (double rhs, double max_abs_error) inline
Definition at line 4393 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<double>(rhs, false, max_abs_error);
}
References DoubleNear().
Each()
template<typename M > internal::EachMatcher< M > testing::Each (M matcher) inline
Definition at line 5097 of file gmock-matchers.h.
{
  return internal::EachMatcher<M>(matcher);
}
ElementsAre() [1/11]
internal::ElementsAreMatcher< ::testing::tuple<> > testing::ElementsAre () inline
Definition at line 570 of file gmock-generated-matchers.h.
              {
  typedef ::testing::tuple<> Args;
  return internal::ElementsAreMatcher<Args>(Args());
}
References Args().
ElementsAre() [2/11]
template<typename T1 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type > > testing::ElementsAre (const T1 & e1) inline
Definition at line 579 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1));
}
References Args().
ElementsAre() [3/11]
template<typename T1 , typename T2 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2) inline
Definition at line 590 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2));
}
References Args().
ElementsAre() [4/11]
template<typename T1 , typename T2 , typename T3 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3) inline
Definition at line 603 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3));
}
References Args().
ElementsAre() [5/11]
template<typename T1 , typename T2 , typename T3 , typename T4 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4) inline
Definition at line 618 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4));
}
References Args().
ElementsAre() [6/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5) inline
Definition at line 635 of file gmock-generated-matchers.h.
                  {
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5));
}
References Args().
ElementsAre() [7/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6) inline
Definition at line 656 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5, e6));
}
References Args().
ElementsAre() [8/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7) inline
Definition at line 679 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5, e6, e7));
}
References Args().
ElementsAre() [9/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8) inline
Definition at line 704 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type,
      typename internal::DecayArray<T8>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5, e6, e7,
      e8));
}
References Args().
ElementsAre() [10/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9) inline
Definition at line 732 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type,
      typename internal::DecayArray<T8>::type,
      typename internal::DecayArray<T9>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5, e6, e7,
      e8, e9));
}
References Args().
ElementsAre() [11/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > internal::ElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9, const T10 & e10) inline
Definition at line 762 of file gmock-generated-matchers.h.
                    {
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type,
      typename internal::DecayArray<T8>::type,
      typename internal::DecayArray<T9>::type,
      typename internal::DecayArray<T10>::type> Args;
  return internal::ElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5, e6, e7,
      e8, e9, e10));
}
References Args().
ElementsAreArray() [1/4]
template<typename Container > internal::ElementsAreArrayMatcher< typename Container::value_type > testing::ElementsAreArray (const Container & container) inline
Definition at line 4214 of file gmock-matchers.h.
{
  return ElementsAreArray(container.begin(), container.end());
}
References ElementsAreArray().
ElementsAreArray() [2/4]
template<typename T > internal::ElementsAreArrayMatcher< T > testing::ElementsAreArray (const T * pointer, size_t count) inline
Definition at line 4201 of file gmock-matchers.h.
{
  return ElementsAreArray(pointer, pointer + count);
}
References ElementsAreArray().
ElementsAreArray() [3/4]
template<typename T , size_t N> internal::ElementsAreArrayMatcher< T > testing::ElementsAreArray (const T(&) array[N]) inline
Definition at line 4207 of file gmock-matchers.h.
{
  return ElementsAreArray(array, N);
}
References ElementsAreArray().
ElementsAreArray() [4/4]
template<typename Iter > internal::ElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > testing::ElementsAreArray (Iter first, Iter last) inline
Definition at line 4195 of file gmock-matchers.h.
{
  typedef typename ::std::iterator_traits<Iter>::value_type T;
  return internal::ElementsAreArrayMatcher<T>(first, last);
}
References ElementsAreArray(), and T.
EndsWith()
PolymorphicMatcher< internal::EndsWithMatcher< std::string > > testing::EndsWith (const std::string & suffix) inline
Definition at line 4607 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(internal::EndsWithMatcher<std::string>(suffix));
}
References EndsWith(), and MakePolymorphicMatcher().
Eq() [1/2]
internal::Eq2Matcher testing::Eq () inline
Definition at line 4691 of file gmock-matchers.h.
{ return internal::Eq2Matcher(); }
Eq() [2/2]
template<typename T > internal::EqMatcher< T > testing::Eq (T x) inline
Definition at line 4299 of file gmock-matchers.h.
{ return internal::EqMatcher<T>(x); }
Exactly()
GTEST_API_ Cardinality testing::Exactly (int n)
Definition at line 154 of file gmock-cardinalities.cc.
{ return Between(n, n); }
References Between(), and Exactly().
ExplainMatchResult()
template<typename T , typename M > bool testing::ExplainMatchResult (M matcher, const T & value, MatchResultListener * listener) inline
Definition at line 5137 of file gmock-matchers.h.
{
  return SafeMatcherCast<const T&>(matcher).MatchAndExplain(value, listener);
}
References ExplainMatchResult().
Field() [1/2]
template<typename Class , typename FieldType , typename FieldMatcher > PolymorphicMatcher< internal::FieldMatcher< Class, FieldType > > testing::Field (const std::string & field_name, FieldType Class::* field, const FieldMatcher & matcher) inline
Definition at line 4477 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(internal::FieldMatcher<Class, FieldType>(
      field_name, field, MatcherCast<const FieldType&>(matcher)));
}
References Field(), and MakePolymorphicMatcher().
Field() [2/2]
template<typename Class , typename FieldType , typename FieldMatcher > PolymorphicMatcher< internal::FieldMatcher< Class, FieldType > > testing::Field (FieldType Class::* field, const FieldMatcher & matcher) inline
Definition at line 4463 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::FieldMatcher<Class, FieldType>(
          field, MatcherCast<const FieldType&>(matcher)));
  // The call to MatcherCast() is required for supporting inner
  // matchers of compatible types.  For example, it allows
  //   Field(&Foo::bar, m)
  // to compile where bar is an int32 and m is a matcher for int64.
}
References Field(), and MakePolymorphicMatcher().
FloatEq() [1/2]
internal::FloatingEq2Matcher< float > testing::FloatEq () inline
Definition at line 4715 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<float>();
}
FloatEq() [2/2]
internal::FloatingEqMatcher< float > testing::FloatEq (float rhs) inline
Definition at line 4408 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<float>(rhs, false);
}
FloatLE()
AssertionResult testing::FloatLE (const char * expr1, const char * expr2, float val1, float val2) private
Definition at line 1436 of file gtest.cc.
{
  return internal::FloatingPointLE<float>(expr1, expr2, val1, val2);
}
References FloatLE().
FloatNear() [1/2]
internal::FloatingEq2Matcher< float > testing::FloatNear (float max_abs_error) inline
Definition at line 4739 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<float>(max_abs_error);
}
References FloatNear().
FloatNear() [2/2]
internal::FloatingEqMatcher< float > testing::FloatNear (float rhs, float max_abs_error) inline
Definition at line 4421 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<float>(rhs, false, max_abs_error);
}
References FloatNear().
FormatCountableNoun()
static std::string testing::FormatCountableNoun (int count, const char * singular_form, const char * plural_form) static
Definition at line 2821 of file gtest.cc.
{
  return internal::StreamableToString(count) + " " +
      (count == 1 ? singular_form : plural_form);
}
References testing::internal::StreamableToString().
FormatTestCaseCount()
static std::string testing::FormatTestCaseCount (int test_case_count) static
Definition at line 2834 of file gtest.cc.
{
  return FormatCountableNoun(test_case_count, "test case", "test cases");
}
References FormatCountableNoun().
FormatTestCount()
static std::string testing::FormatTestCount (int test_count) static
Definition at line 2829 of file gtest.cc.
{
  return FormatCountableNoun(test_count, "test", "tests");
}
References FormatCountableNoun().
FormatWordList()
static std::string testing::FormatWordList (const std::vector< std::string > & words) static
Definition at line 2142 of file gtest.cc.
{
  Message word_list;
  for (size_t i = 0; i < words.size(); ++i) {
    if (i > 0 && words.size() > 2) {
      word_list << ", ";
    }
    if (i == words.size() - 1) {
      word_list << "and ";
    }
    word_list << "'" << words[i] << "'";
  }
  return word_list.GetString();
}
References testing::Message::GetString().
Ge() [1/2]
internal::Ge2Matcher testing::Ge () inline
Definition at line 4695 of file gmock-matchers.h.
{ return internal::Ge2Matcher(); }
Ge() [2/2]
template<typename Rhs > internal::GeMatcher< Rhs > testing::Ge (Rhs x) inline
Definition at line 4331 of file gmock-matchers.h.
{
  return internal::GeMatcher<Rhs>(x);
}
GetDefaultFilter()
static const char * testing::GetDefaultFilter () static
Definition at line 189 of file gtest.cc.
{
  const char* const testbridge_test_only =
      internal::posix::GetEnv("TESTBRIDGE_TEST_ONLY");
  if (testbridge_test_only != NULL) {
    return testbridge_test_only;
  }
  return kUniversalFilter;
}
References testing::internal::posix::GetEnv(), and kUniversalFilter.
GetReservedAttributesForElement()
static std::vector< std::string > testing::GetReservedAttributesForElement (const std::string & xml_element) static
Definition at line 2127 of file gtest.cc.
{
  if (xml_element == "testsuites") {
    return ArrayAsVector(kReservedTestSuitesAttributes);
  } else if (xml_element == "testsuite") {
    return ArrayAsVector(kReservedTestSuiteAttributes);
  } else if (xml_element == "testcase") {
    return ArrayAsVector(kReservedTestCaseAttributes);
  } else {
    GTEST_CHECK_(false) << "Unrecognized xml_element provided: " << xml_element;
  }
  // This code is unreachable but some compilers may not realizes that.
  return std::vector<std::string>();
}
References ArrayAsVector(), GTEST_CHECK_, kReservedTestCaseAttributes, kReservedTestSuiteAttributes, and kReservedTestSuitesAttributes.
GMOCK_DECLARE_bool_()
testing::GMOCK_DECLARE_bool_ (catch_leaked_mocks)
GMOCK_DECLARE_int32_()
testing::GMOCK_DECLARE_int32_ (default_mock_behavior)
References InitGoogleMock().
GMOCK_DECLARE_string_()
testing::GMOCK_DECLARE_string_ (verbose)
GMOCK_DEFINE_bool_()
testing::GMOCK_DEFINE_bool_ (catch_leaked_mocks , true , "true iff Google Mock should report leaked mock objects " "as failures.")
GMOCK_DEFINE_int32_()
testing::GMOCK_DEFINE_int32_ (default_mock_behavior , 1 , "Controls the default behavior of mocks." " Valid values:\n" " 0 - by default, mocks act as NiceMocks.\n" " 1 - by default, mocks act as NaggyMocks.\n" " 2 - by default, mocks act as StrictMocks.")
GMOCK_DEFINE_string_()
testing::GMOCK_DEFINE_string_ (verbose , internal::kWarningVerbosity , "Controls how verbose Google Mock's output is." " Valid values:\n" " info - prints all messages.\n" " warning - prints warnings and errors.\n" " error - prints errors only.")
Gt() [1/2]
internal::Gt2Matcher testing::Gt () inline
Definition at line 4699 of file gmock-matchers.h.
{ return internal::Gt2Matcher(); }
Gt() [2/2]
template<typename Rhs > internal::GtMatcher< Rhs > testing::Gt (Rhs x) inline
Definition at line 4337 of file gmock-matchers.h.
{
  return internal::GtMatcher<Rhs>(x);
}
GTEST_CONCAT_TOKEN_() [1/64]
template<int k, typename p0_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [2/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P)
GTEST_CONCAT_TOKEN_() [3/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P10)
Definition at line 2473 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [4/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P10)
GTEST_CONCAT_TOKEN_() [5/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P10) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [6/64]
template<int k, typename p0_type , typename p1_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P2)
Definition at line 2401 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [7/64]
template<int k, typename p0_type , typename p1_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P2) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [8/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P2)
GTEST_CONCAT_TOKEN_() [9/64]
template<int k, typename p0_type , typename p1_type , typename p2_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P3)
Definition at line 2410 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [10/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P3)
GTEST_CONCAT_TOKEN_() [11/64]
template<int k, typename p0_type , typename p1_type , typename p2_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P3) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [12/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P4)
Definition at line 2419 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [13/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P4)
GTEST_CONCAT_TOKEN_() [14/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P4) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [15/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P5)
Definition at line 2428 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [16/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P5) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [17/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P5)
GTEST_CONCAT_TOKEN_() [18/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P6)
Definition at line 2437 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [19/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P6) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [20/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P6)
GTEST_CONCAT_TOKEN_() [21/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P7)
Definition at line 2446 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [22/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P7) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [23/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P7)
GTEST_CONCAT_TOKEN_() [24/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P8)
Definition at line 2455 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [25/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P8)
GTEST_CONCAT_TOKEN_() [26/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P8) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [27/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type > class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P9)
Definition at line 2464 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [28/64]
template<int k, typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type > testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P9) inline
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [29/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction , P9)
GTEST_CONCAT_TOKEN_() [30/64]
template<int k> class testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction)
Definition at line 685 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [31/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction)
Definition at line 2392 of file gmock-generated-actions.h.
{
  using internal::invoke_argument::InvokeArgumentAdl;
  return InvokeArgumentAdl<return_type>(
      internal::invoke_argument::AdlTag(),
      ::testing::get<k>(args));
}
ACTION_TEMPLATE(InvokeArgument,
                HAS_1_TEMPLATE_PARAMS(int, k),
                AND_1_VALUE_PARAMS(p0)) {
GTEST_CONCAT_TOKEN_() [32/64]
template<int k> testing::GTEST_CONCAT_TOKEN_ (InvokeArgumentAction) inline
Definition at line 2392 of file gmock-generated-actions.h.
{
References testing::internal::invoke_argument::InvokeArgumentAdl().
GTEST_CONCAT_TOKEN_() [33/64]
template<typename T , typename p0_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P) inline
References T.
GTEST_CONCAT_TOKEN_() [34/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P)
GTEST_CONCAT_TOKEN_() [35/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P10)
Definition at line 2550 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [36/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type , typename p9_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P10) inline
References T.
GTEST_CONCAT_TOKEN_() [37/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P10)
GTEST_CONCAT_TOKEN_() [38/64]
template<typename T , typename p0_type , typename p1_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P2)
Definition at line 2502 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [39/64]
template<typename T , typename p0_type , typename p1_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P2) inline
References T.
GTEST_CONCAT_TOKEN_() [40/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P2)
GTEST_CONCAT_TOKEN_() [41/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P3)
Definition at line 2508 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [42/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P3) inline
References T.
GTEST_CONCAT_TOKEN_() [43/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P3)
GTEST_CONCAT_TOKEN_() [44/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P4)
Definition at line 2514 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [45/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P4) inline
References T.
GTEST_CONCAT_TOKEN_() [46/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P4)
GTEST_CONCAT_TOKEN_() [47/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P5)
Definition at line 2520 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [48/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P5)
GTEST_CONCAT_TOKEN_() [49/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P5) inline
References T.
GTEST_CONCAT_TOKEN_() [50/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P6)
Definition at line 2526 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [51/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P6) inline
References T.
GTEST_CONCAT_TOKEN_() [52/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P6)
GTEST_CONCAT_TOKEN_() [53/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P7)
Definition at line 2532 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [54/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P7)
GTEST_CONCAT_TOKEN_() [55/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P7) inline
References T.
GTEST_CONCAT_TOKEN_() [56/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P8)
Definition at line 2538 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [57/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P8)
GTEST_CONCAT_TOKEN_() [58/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P8) inline
References T.
GTEST_CONCAT_TOKEN_() [59/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P9)
Definition at line 2544 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [60/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P9)
GTEST_CONCAT_TOKEN_() [61/64]
template<typename T , typename p0_type , typename p1_type , typename p2_type , typename p3_type , typename p4_type , typename p5_type , typename p6_type , typename p7_type , typename p8_type > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction , P9) inline
References T.
GTEST_CONCAT_TOKEN_() [62/64]
template<typename T > class testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction)
Definition at line 2482 of file gmock-generated-actions.h.
{
GTEST_CONCAT_TOKEN_() [63/64]
template<typename arg0_type , typename arg1_type , typename arg2_type , typename arg3_type , typename arg4_type , typename arg5_type , typename arg6_type , typename arg7_type , typename arg8_type , typename arg9_type > ::testing::internal::Function< F >::Result testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction)
Definition at line 2496 of file gmock-generated-actions.h.
{
  return new T();
}
ACTION_TEMPLATE(ReturnNew,
                HAS_1_TEMPLATE_PARAMS(typename, T),
                AND_1_VALUE_PARAMS(p0)) {
GTEST_CONCAT_TOKEN_() [64/64]
template<typename T > testing::GTEST_CONCAT_TOKEN_ (ReturnNewAction) inline
Definition at line 2496 of file gmock-generated-actions.h.
{
References T.
GTEST_DECLARE_bool_() [1/10]
testing::GTEST_DECLARE_bool_ (also_run_disabled_tests)
GTEST_DECLARE_bool_() [2/10]
testing::GTEST_DECLARE_bool_ (break_on_failure)
GTEST_DECLARE_bool_() [3/10]
testing::GTEST_DECLARE_bool_ (catch_exceptions)
GTEST_DECLARE_bool_() [4/10]
testing::GTEST_DECLARE_bool_ (death_test_use_fork)
GTEST_DECLARE_bool_() [5/10]
testing::GTEST_DECLARE_bool_ (list_tests)
GTEST_DECLARE_bool_() [6/10]
testing::GTEST_DECLARE_bool_ (print_time)
GTEST_DECLARE_bool_() [7/10]
testing::GTEST_DECLARE_bool_ (print_utf8)
GTEST_DECLARE_bool_() [8/10]
testing::GTEST_DECLARE_bool_ (show_internal_stack_frames)
GTEST_DECLARE_bool_() [9/10]
testing::GTEST_DECLARE_bool_ (shuffle)
GTEST_DECLARE_bool_() [10/10]
testing::GTEST_DECLARE_bool_ (throw_on_failure)
GTEST_DECLARE_int32_() [1/3]
testing::GTEST_DECLARE_int32_ (random_seed)
GTEST_DECLARE_int32_() [2/3]
testing::GTEST_DECLARE_int32_ (repeat)
GTEST_DECLARE_int32_() [3/3]
testing::GTEST_DECLARE_int32_ (stack_trace_depth)
GTEST_DECLARE_string_() [1/5]
testing::GTEST_DECLARE_string_ (color)
GTEST_DECLARE_string_() [2/5]
testing::GTEST_DECLARE_string_ (death_test_style)
GTEST_DECLARE_string_() [3/5]
testing::GTEST_DECLARE_string_ (filter)
GTEST_DECLARE_string_() [4/5]
testing::GTEST_DECLARE_string_ (output)
GTEST_DECLARE_string_() [5/5]
testing::GTEST_DECLARE_string_ (stream_result_to)
GTEST_DEFINE_bool_() [1/10]
testing::GTEST_DEFINE_bool_ (also_run_disabled_tests , internal::BoolFromGTestEnv("also_run_disabled_tests", false) , "Run disabled tests too, in addition to the tests normally being run.")
GTEST_DEFINE_bool_() [2/10]
testing::GTEST_DEFINE_bool_ (break_on_failure , internal::BoolFromGTestEnv("break_on_failure", false) , "True iff a failed assertion should be a debugger break-point.")
GTEST_DEFINE_bool_() [3/10]
testing::GTEST_DEFINE_bool_ (catch_exceptions , internal::BoolFromGTestEnv("catch_exceptions", true) , "True iff " GTEST_NAME_ " should catch exceptions and treat them as test failures.")
GTEST_DEFINE_bool_() [4/10]
testing::GTEST_DEFINE_bool_ (death_test_use_fork , internal::BoolFromGTestEnv("death_test_use_fork", false) , "Instructs to use fork()/_exit() instead of clone() in death tests. " "Ignored and always uses fork() on POSIX systems where clone() is not " "implemented. Useful when running under valgrind or similar tools if " "those do not support clone(). Valgrind 3.3.1 will just fail if " "it sees an unsupported combination of clone() flags. " "It is not recommended to use this flag w/o valgrind though it will " "work in 99% of the cases. Once valgrind is fixed, this flag will " "most likely be removed.")
GTEST_DEFINE_bool_() [5/10]
testing::GTEST_DEFINE_bool_ (list_tests , false , "List all tests without running them.")
GTEST_DEFINE_bool_() [6/10]
testing::GTEST_DEFINE_bool_ (print_time , internal::BoolFromGTestEnv("print_time", true) , "True iff " GTEST_NAME_ " should display elapsed time in text output.")
GTEST_DEFINE_bool_() [7/10]
testing::GTEST_DEFINE_bool_ (print_utf8 , internal::BoolFromGTestEnv("print_utf8", true) , "True iff " GTEST_NAME_ " prints UTF8 characters as text.")
GTEST_DEFINE_bool_() [8/10]
testing::GTEST_DEFINE_bool_ (show_internal_stack_frames , false , "True iff " GTEST_NAME_ " should include internal stack frames when " "printing test failure stack traces.")
GTEST_DEFINE_bool_() [9/10]
testing::GTEST_DEFINE_bool_ (shuffle , internal::BoolFromGTestEnv("shuffle", false) , "True iff " GTEST_NAME_ " should randomize tests' order on every run.")
GTEST_DEFINE_bool_() [10/10]
testing::GTEST_DEFINE_bool_ (throw_on_failure , internal::BoolFromGTestEnv("throw_on_failure", false) , "When this flag is specified, a failed assertion will throw an exception " "if exceptions are enabled or exit the program with a non-zero code " "otherwise. For use with an external test framework.")
GTEST_DEFINE_int32_() [1/3]
testing::GTEST_DEFINE_int32_ (random_seed , internal::Int32FromGTestEnv("random_seed", 0) , "Random number seed to use when shuffling test orders. Must be in range " " [1, 99999], or 0 to use a seed based on the current time.")
GTEST_DEFINE_int32_() [2/3]
testing::GTEST_DEFINE_int32_ (repeat , internal::Int32FromGTestEnv("repeat", 1) , "How many times to repeat each test. Specify a negative number " "for repeating forever. Useful for shaking out flaky tests.")
GTEST_DEFINE_int32_() [3/3]
testing::GTEST_DEFINE_int32_ (stack_trace_depth , internal::Int32FromGTestEnv("stack_trace_depth", kMaxStackTraceDepth) , "The maximum number of stack frames to print when an " "assertion fails. The valid range is 0 through 100, inclusive.")
GTEST_DEFINE_string_() [1/5]
testing::GTEST_DEFINE_string_ (color , internal::StringFromGTestEnv("color", "auto") , "Whether to use colors in the output. Valid values: yes, no , " "and auto. 'auto' means to use colors if the output is " "being sent to a terminal and the TERM environment variable " "is set to a terminal type that supports colors.")
GTEST_DEFINE_string_() [2/5]
testing::GTEST_DEFINE_string_ (death_test_style , internal::StringFromGTestEnv("death_test_style", kDefaultDeathTestStyle) , "Indicates how to run a death test in a forked child process: " "\"threadsafe\" (child process re-executes the test binary " "from the beginning, running only the specific death test) or " "\"fast\" (child process runs the death test immediately " "after forking).")
GTEST_DEFINE_string_() [3/5]
testing::GTEST_DEFINE_string_ (filter , internal::StringFromGTestEnv("filter", GetDefaultFilter()) , "A colon-separated list of glob (not regex) patterns " "for filtering the tests to run, optionally followed by a " "'-' and a :separated list of negative patterns(tests to " "exclude). A test is run if it matches one of the positive " "patterns and does not match any of the negative patterns.")
GTEST_DEFINE_string_() [4/5]
testing::GTEST_DEFINE_string_ (output , internal::StringFromGTestEnv("output", internal::OutputFlagAlsoCheckEnvVar().c_str()) , "A format defaults to \"xml\" but can be specified to be \"json\", " "optionally followed by a colon and an output file name or directory. " "A directory is indicated by a trailing pathname separator. " "Examples:\"xml:filename.xml\" , \"xml::directoryname/\". " "If a directory is specified, output files will be created " "within that directory, with file-names based on the test " "executable 's name and, if necessary, made unique by adding " "digits.")
GTEST_DEFINE_string_() [5/5]
testing::GTEST_DEFINE_string_ (stream_result_to , internal::StringFromGTestEnv("stream_result_to", "") , "This flag specifies the host name and the port number on which to stream " "test results. Example: \"localhost:555\". The flag is effective only on " "Linux.")
HasSubstr()
PolymorphicMatcher< internal::HasSubstrMatcher< std::string > > testing::HasSubstr (const std::string & substring) inline
Definition at line 4593 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::HasSubstrMatcher<std::string>(substring));
}
References HasSubstr(), and MakePolymorphicMatcher().
IgnoreResult()
template<typename A > internal::IgnoreResultAction< A > testing::IgnoreResult (const A & an_action) inline
Definition at line 1244 of file gmock-actions.h.
{
  return internal::IgnoreResultAction<A>(an_action);
}
References IgnoreResult().
InitGoogleMock() [1/2]
GTEST_API_ void testing::InitGoogleMock (int * argc, char ** argv)
Definition at line 195 of file gmock.cc.
{
  internal::InitGoogleMockImpl(argc, argv);
}
References InitGoogleMock(), and testing::internal::InitGoogleMockImpl().
InitGoogleMock() [2/2]
GTEST_API_ void testing::InitGoogleMock (int * argc, wchar_t ** argv)
Definition at line 201 of file gmock.cc.
{
  internal::InitGoogleMockImpl(argc, argv);
}
References InitGoogleMock(), and testing::internal::InitGoogleMockImpl().
InitGoogleTest() [1/2]
void testing::InitGoogleTest (int * argc, char ** argv) private
Definition at line 5787 of file gtest.cc.
{
#if defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
  GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_(argc, argv);
#else  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
  internal::InitGoogleTestImpl(argc, argv);
#endif  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
}
References testing::internal::InitGoogleTestImpl().
InitGoogleTest() [2/2]
void testing::InitGoogleTest (int * argc, wchar_t ** argv) private
Definition at line 5797 of file gtest.cc.
{
#if defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
  GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_(argc, argv);
#else  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
  internal::InitGoogleTestImpl(argc, argv);
#endif  // defined(GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_)
}
References testing::internal::InitGoogleTestImpl().
INSTANTIATE_TEST_CASE_P()
testing::INSTANTIATE_TEST_CASE_P (CodeLocationForTESTP , Values(0))
INSTANTIATE_TYPED_TEST_CASE_P()
testing::INSTANTIATE_TYPED_TEST_CASE_P (My , CodeLocationForTYPEDTESTP , int)
Invoke() [1/2]
template<class Class , typename MethodPtr > PolymorphicAction< internal::InvokeMethodAction< Class, MethodPtr > > testing::Invoke (Class * obj_ptr, MethodPtr method_ptr)
Definition at line 123 of file gmock-more-actions.h.
{
  return MakePolymorphicAction(
      internal::InvokeMethodAction<Class, MethodPtr>(obj_ptr, method_ptr));
}
References Invoke(), and MakePolymorphicAction().
Invoke() [2/2]
template<typename FunctionImpl > PolymorphicAction< internal::InvokeAction< FunctionImpl > > testing::Invoke (FunctionImpl function_impl)
Definition at line 114 of file gmock-more-actions.h.
{
  return MakePolymorphicAction(
      internal::InvokeAction<FunctionImpl>(function_impl));
}
References Invoke(), and MakePolymorphicAction().
InvokeArgument() [1/10]
p0_type testing::InvokeArgument (p0_type p0)
Definition at line 2401 of file gmock-generated-actions.h.
{
InvokeArgument() [2/10]
p1_type testing::InvokeArgument (p0_type p0, p1_type p1)
Definition at line 2410 of file gmock-generated-actions.h.
{
InvokeArgument() [3/10]
p2_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2)
Definition at line 2419 of file gmock-generated-actions.h.
{
InvokeArgument() [4/10]
p3_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3)
Definition at line 2428 of file gmock-generated-actions.h.
{
InvokeArgument() [5/10]
p4_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4)
Definition at line 2437 of file gmock-generated-actions.h.
{
InvokeArgument() [6/10]
p5_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5)
Definition at line 2446 of file gmock-generated-actions.h.
{
InvokeArgument() [7/10]
p6_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6)
Definition at line 2455 of file gmock-generated-actions.h.
{
InvokeArgument() [8/10]
p7_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7)
Definition at line 2464 of file gmock-generated-actions.h.
{
InvokeArgument() [9/10]
p8_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8)
Definition at line 2473 of file gmock-generated-actions.h.
{
InvokeArgument() [10/10]
p9_type testing::InvokeArgument (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8, p9_type p9)
Definition at line 2482 of file gmock-generated-actions.h.
{
InvokeWithoutArgs() [1/2]
template<class Class , typename MethodPtr > PolymorphicAction< internal::InvokeMethodWithoutArgsAction< Class, MethodPtr > > testing::InvokeWithoutArgs (Class * obj_ptr, MethodPtr method_ptr)
Definition at line 1234 of file gmock-actions.h.
{
  return MakePolymorphicAction(
      internal::InvokeMethodWithoutArgsAction<Class, MethodPtr>(
          obj_ptr, method_ptr));
}
References InvokeWithoutArgs(), and MakePolymorphicAction().
InvokeWithoutArgs() [2/2]
template<typename FunctionImpl > PolymorphicAction< internal::InvokeWithoutArgsAction< FunctionImpl > > testing::InvokeWithoutArgs (FunctionImpl function_impl)
Definition at line 1225 of file gmock-actions.h.
{
  return MakePolymorphicAction(
      internal::InvokeWithoutArgsAction<FunctionImpl>(function_impl));
}
References InvokeWithoutArgs(), and MakePolymorphicAction().
IsNotSubstring() [1/3]
AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack) private
Definition at line 1651 of file gtest.cc.
{
  return IsSubstringImpl(false, needle_expr, haystack_expr, needle, haystack);
}
References IsNotSubstring().
IsNotSubstring() [2/3]
AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack) private
Definition at line 1633 of file gtest.cc.
{
  return IsSubstringImpl(false, needle_expr, haystack_expr, needle, haystack);
}
References IsNotSubstring().
IsNotSubstring() [3/3]
AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack) private
Definition at line 1639 of file gtest.cc.
{
  return IsSubstringImpl(false, needle_expr, haystack_expr, needle, haystack);
}
References IsNotSubstring().
IsNull()
PolymorphicMatcher< internal::IsNullMatcher > testing::IsNull () inline
Definition at line 4360 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(internal::IsNullMatcher());
}
References MakePolymorphicMatcher().
IsSubsetOf() [1/4]
template<typename Container > internal::UnorderedElementsAreArrayMatcher< typename Container::value_type > testing::IsSubsetOf (const Container & container) inline
Definition at line 5057 of file gmock-matchers.h.
{
  return IsSubsetOf(container.begin(), container.end());
}
References IsSubsetOf().
IsSubsetOf() [2/4]
template<typename T > internal::UnorderedElementsAreArrayMatcher< T > testing::IsSubsetOf (const T * pointer, size_t count) inline
Definition at line 5043 of file gmock-matchers.h.
{
  return IsSubsetOf(pointer, pointer + count);
}
References IsSubsetOf().
IsSubsetOf() [3/4]
template<typename T , size_t N> internal::UnorderedElementsAreArrayMatcher< T > testing::IsSubsetOf (const T(&) array[N]) inline
Definition at line 5049 of file gmock-matchers.h.
{
  return IsSubsetOf(array, N);
}
References IsSubsetOf().
IsSubsetOf() [4/4]
template<typename Iter > internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > testing::IsSubsetOf (Iter first, Iter last) inline
Definition at line 5036 of file gmock-matchers.h.
{
  typedef typename ::std::iterator_traits<Iter>::value_type T;
  return internal::UnorderedElementsAreArrayMatcher<T>(
      internal::UnorderedMatcherRequire::Subset, first, last);
}
References IsSubsetOf(), testing::internal::UnorderedMatcherRequire::Subset, and T.
IsSubstring() [1/3]
AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack) private
Definition at line 1645 of file gtest.cc.
{
  return IsSubstringImpl(true, needle_expr, haystack_expr, needle, haystack);
}
References IsSubstring().
IsSubstring() [2/3]
AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack) private
Definition at line 1621 of file gtest.cc.
{
  return IsSubstringImpl(true, needle_expr, haystack_expr, needle, haystack);
}
References IsSubstring().
IsSubstring() [3/3]
AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack) private
Definition at line 1627 of file gtest.cc.
{
  return IsSubstringImpl(true, needle_expr, haystack_expr, needle, haystack);
}
References IsSubstring().
IsSupersetOf() [1/4]
template<typename Container > internal::UnorderedElementsAreArrayMatcher< typename Container::value_type > testing::IsSupersetOf (const Container & container) inline
Definition at line 4998 of file gmock-matchers.h.
{
  return IsSupersetOf(container.begin(), container.end());
}
References IsSupersetOf().
IsSupersetOf() [2/4]
template<typename T > internal::UnorderedElementsAreArrayMatcher< T > testing::IsSupersetOf (const T * pointer, size_t count) inline
Definition at line 4984 of file gmock-matchers.h.
{
  return IsSupersetOf(pointer, pointer + count);
}
References IsSupersetOf().
IsSupersetOf() [3/4]
template<typename T , size_t N> internal::UnorderedElementsAreArrayMatcher< T > testing::IsSupersetOf (const T(&) array[N]) inline
Definition at line 4990 of file gmock-matchers.h.
{
  return IsSupersetOf(array, N);
}
References IsSupersetOf().
IsSupersetOf() [4/4]
template<typename Iter > internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > testing::IsSupersetOf (Iter first, Iter last) inline
Definition at line 4977 of file gmock-matchers.h.
{
  typedef typename ::std::iterator_traits<Iter>::value_type T;
  return internal::UnorderedElementsAreArrayMatcher<T>(
      internal::UnorderedMatcherRequire::Superset, first, last);
}
References IsSupersetOf(), testing::internal::UnorderedMatcherRequire::Superset, and T.
Key()
template<typename M > internal::KeyMatcher< M > testing::Key (M inner_matcher) inline
Definition at line 5105 of file gmock-matchers.h.
{
  return internal::KeyMatcher<M>(inner_matcher);
}
References Key().
Le() [1/2]
internal::Le2Matcher testing::Le () inline
Definition at line 4703 of file gmock-matchers.h.
{ return internal::Le2Matcher(); }
Le() [2/2]
template<typename Rhs > internal::LeMatcher< Rhs > testing::Le (Rhs x) inline
Definition at line 4343 of file gmock-matchers.h.
{
  return internal::LeMatcher<Rhs>(x);
}
Lt() [1/2]
internal::Lt2Matcher testing::Lt () inline
Definition at line 4707 of file gmock-matchers.h.
{ return internal::Lt2Matcher(); }
Lt() [2/2]
template<typename Rhs > internal::LtMatcher< Rhs > testing::Lt (Rhs x) inline
Definition at line 4349 of file gmock-matchers.h.
{
  return internal::LtMatcher<Rhs>(x);
}
MakeAction()
template<typename F > Action< F > testing::MakeAction (ActionInterface< F > * impl)
Definition at line 489 of file gmock-actions.h.
{
  return Action<F>(impl);
}
MakeCardinality()
Cardinality testing::MakeCardinality (const CardinalityInterface * c) inline
Definition at line 141 of file gmock-cardinalities.h.
{
  return Cardinality(c);
}
References MakeCardinality().
MakeMatcher()
template<typename T > Matcher< T > testing::MakeMatcher (const MatcherInterface< T > * impl) inline
Definition at line 615 of file gmock-matchers.h.
{
  return Matcher<T>(impl);
}
References MakeMatcher().
MakePolymorphicAction()
template<typename Impl > PolymorphicAction< Impl > testing::MakePolymorphicAction (const Impl & impl) inline
Definition at line 501 of file gmock-actions.h.
{
  return PolymorphicAction<Impl>(impl);
}
References MakePolymorphicAction().
MakePolymorphicMatcher()
template<class Impl > PolymorphicMatcher< Impl > testing::MakePolymorphicMatcher (const Impl & impl) inline
Definition at line 627 of file gmock-matchers.h.
{
  return PolymorphicMatcher<Impl>(impl);
}
References MakePolymorphicMatcher().
MATCHER() [1/3]
testing::MATCHER (IsEmpty , negation ? "isn't empty" :"is empty")
Definition at line 60 of file gmock-more-matchers.h.
                                          : "is empty") {
  if (arg.empty()) {
    return true;
  }
  *result_listener << "whose size is " << arg.size();
  return false;
}
MATCHER() [2/3]
testing::MATCHER (IsFalse , negation ? "is true" :"is false")
Definition at line 80 of file gmock-more-matchers.h.
                                      : "is false") {
  return !static_cast<bool>(arg);
}
MATCHER() [3/3]
testing::MATCHER (IsTrue , negation ? "is false" :"is true")
Definition at line 72 of file gmock-more-matchers.h.
                                      : "is true") {
  return static_cast<bool>(arg);
}
MatcherCast()
template<typename T , typename M > Matcher< T > testing::MatcherCast (const M & matcher) inline
Definition at line 777 of file gmock-matchers.h.
{
  return internal::MatcherCastImpl<T, M>::Cast(matcher);
}
References testing::internal::MatcherCastImpl< T, M >::Cast(), and MatcherCast().
Matches()
template<typename M > internal::MatcherAsPredicate< M > testing::Matches (M matcher) inline
Definition at line 5124 of file gmock-matchers.h.
{
  return internal::MatcherAsPredicate<M>(matcher);
}
References Matches().
MatchesRegex() [1/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::MatchesRegex (const internal::RE * regex) inline
Definition at line 4614 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(internal::MatchesRegexMatcher(regex, true));
}
References MakePolymorphicMatcher(), and MatchesRegex().
MatchesRegex() [2/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::MatchesRegex (const std::string & regex) inline
Definition at line 4618 of file gmock-matchers.h.
{
  return MatchesRegex(new internal::RE(regex));
}
References MatchesRegex().
NanSensitiveDoubleEq() [1/2]
internal::FloatingEq2Matcher< double > testing::NanSensitiveDoubleEq () inline
Definition at line 4733 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<double>(true);
}
NanSensitiveDoubleEq() [2/2]
internal::FloatingEqMatcher< double > testing::NanSensitiveDoubleEq (double rhs) inline
Definition at line 4386 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<double>(rhs, true);
}
NanSensitiveDoubleNear() [1/2]
internal::FloatingEq2Matcher< double > testing::NanSensitiveDoubleNear (double max_abs_error) inline
Definition at line 4760 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<double>(max_abs_error, true);
}
References NanSensitiveDoubleNear().
NanSensitiveDoubleNear() [2/2]
internal::FloatingEqMatcher< double > testing::NanSensitiveDoubleNear (double rhs, double max_abs_error) inline
Definition at line 4401 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<double>(rhs, true, max_abs_error);
}
References NanSensitiveDoubleNear().
NanSensitiveFloatEq() [1/2]
internal::FloatingEq2Matcher< float > testing::NanSensitiveFloatEq () inline
Definition at line 4727 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<float>(true);
}
NanSensitiveFloatEq() [2/2]
internal::FloatingEqMatcher< float > testing::NanSensitiveFloatEq (float rhs) inline
Definition at line 4414 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<float>(rhs, true);
}
NanSensitiveFloatNear() [1/2]
internal::FloatingEq2Matcher< float > testing::NanSensitiveFloatNear (float max_abs_error) inline
Definition at line 4752 of file gmock-matchers.h.
{
  return internal::FloatingEq2Matcher<float>(max_abs_error, true);
}
References NanSensitiveFloatNear().
NanSensitiveFloatNear() [2/2]
internal::FloatingEqMatcher< float > testing::NanSensitiveFloatNear (float rhs, float max_abs_error) inline
Definition at line 4429 of file gmock-matchers.h.
{
  return internal::FloatingEqMatcher<float>(rhs, true, max_abs_error);
}
References NanSensitiveFloatNear().
Ne() [1/2]
internal::Ne2Matcher testing::Ne () inline
Definition at line 4711 of file gmock-matchers.h.
{ return internal::Ne2Matcher(); }
Ne() [2/2]
template<typename Rhs > internal::NeMatcher< Rhs > testing::Ne (Rhs x) inline
Definition at line 4355 of file gmock-matchers.h.
{
  return internal::NeMatcher<Rhs>(x);
}
Not()
template<typename InnerMatcher > internal::NotMatcher< InnerMatcher > testing::Not (InnerMatcher m) inline
Definition at line 4768 of file gmock-matchers.h.
{
  return internal::NotMatcher<InnerMatcher>(m);
}
References Not().
NotNull()
PolymorphicMatcher< internal::NotNullMatcher > testing::NotNull () inline
Definition at line 4367 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(internal::NotNullMatcher());
}
References MakePolymorphicMatcher().
operator<<() [1/3]
template<typename T > std::ostream & testing::operator<< (std::ostream & os, const Matcher< T > & matcher)
Definition at line 543 of file gmock-matchers.h.
{
  matcher.DescribeTo(&os);
  return os;
}
References testing::internal::MatcherBase< T >::DescribeTo().
operator<<() [2/3]
std::ostream & testing::operator<< (std::ostream & os, const Message & sb) inline
Definition at line 231 of file gtest-message.h.
{
  return os << sb.GetString();
}
References testing::Message::GetString().
operator<<() [3/3]
std::ostream & testing::operator<< (std::ostream & os, const TestPartResult & result)
Definition at line 50 of file gtest-test-part.cc.
{
  return os
      << result.file_name() << ":" << result.line_number() << ": "
      << (result.type() == TestPartResult::kSuccess ? "Success" :
          result.type() == TestPartResult::kFatalFailure ? "Fatal failure" :
          "Non-fatal failure") << ":\n"
      << result.message() << std::endl;
}
References testing::TestPartResult::file_name(), testing::TestPartResult::kFatalFailure, testing::TestPartResult::kSuccess, testing::TestPartResult::line_number(), testing::TestPartResult::message(), and testing::TestPartResult::type().
Optional()
template<typename ValueMatcher > internal::OptionalMatcher< ValueMatcher > testing::Optional (const ValueMatcher & value_matcher) inline
Definition at line 5215 of file gmock-matchers.h.
{
  return internal::OptionalMatcher<ValueMatcher>(value_matcher);
}
Pair()
template<typename FirstMatcher , typename SecondMatcher > internal::PairMatcher< FirstMatcher, SecondMatcher > testing::Pair (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 5116 of file gmock-matchers.h.
{
  return internal::PairMatcher<FirstMatcher, SecondMatcher>(
      first_matcher, second_matcher);
}
References Pair().
Pointee()
template<typename InnerMatcher > internal::PointeeMatcher< InnerMatcher > testing::Pointee (const InnerMatcher & inner_matcher) inline
Definition at line 4437 of file gmock-matchers.h.
{
  return internal::PointeeMatcher<InnerMatcher>(inner_matcher);
}
References Pointee().
Pointwise()
template<typename TupleMatcher , typename Container > internal::PointwiseMatcher< TupleMatcher, GTEST_REMOVE_CONST_(Container)> testing::Pointwise (const TupleMatcher & tuple_matcher, const Container & rhs) inline
Definition at line 4848 of file gmock-matchers.h.
{
  // This following line is for working around a bug in MSVC 8.0,
  // which causes Container to be a const type sometimes (e.g. when
  // rhs is a const int[])..
  typedef GTEST_REMOVE_CONST_(Container) RawContainer;
  return internal::PointwiseMatcher<TupleMatcher, RawContainer>(
      tuple_matcher, rhs);
}
References GTEST_REMOVE_CONST_, and Pointwise().
PrintFlag()
void testing::PrintFlag (const char * flag)
Definition at line 51 of file gtest_env_var_test_.cc.
{
  if (strcmp(flag, "break_on_failure") == 0) {
    cout << GTEST_FLAG(break_on_failure);
    return;
  }
  if (strcmp(flag, "catch_exceptions") == 0) {
    cout << GTEST_FLAG(catch_exceptions);
    return;
  }
  if (strcmp(flag, "color") == 0) {
    cout << GTEST_FLAG(color);
    return;
  }
  if (strcmp(flag, "death_test_style") == 0) {
    cout << GTEST_FLAG(death_test_style);
    return;
  }
  if (strcmp(flag, "death_test_use_fork") == 0) {
    cout << GTEST_FLAG(death_test_use_fork);
    return;
  }
  if (strcmp(flag, "filter") == 0) {
    cout << GTEST_FLAG(filter);
    return;
  }
  if (strcmp(flag, "output") == 0) {
    cout << GTEST_FLAG(output);
    return;
  }
  if (strcmp(flag, "print_time") == 0) {
    cout << GTEST_FLAG(print_time);
    return;
  }
  if (strcmp(flag, "repeat") == 0) {
    cout << GTEST_FLAG(repeat);
    return;
  }
  if (strcmp(flag, "stack_trace_depth") == 0) {
    cout << GTEST_FLAG(stack_trace_depth);
    return;
  }
  if (strcmp(flag, "throw_on_failure") == 0) {
    cout << GTEST_FLAG(throw_on_failure);
    return;
  }
  cout << "Invalid flag name " << flag
       << ".  Valid names are break_on_failure, color, filter, etc.\n";
  exit(1);
}
References GTEST_FLAG.
PrintToString()
template<typename T > ::std::string testing::PrintToString (const T & value)
Definition at line 1069 of file gtest-printers.h.
{
  ::std::stringstream ss;
  internal::UniversalTersePrinter<T>::Print(value, &ss);
  return ss.str();
}
References testing::internal::UniversalTersePrinter< T >::Print(), and PrintToString().
Property() [1/2]
template<typename Class , typename PropertyType , typename PropertyMatcher > PolymorphicMatcher< internal::PropertyMatcher< Class, PropertyType, PropertyType(Class::*)() const > > testing::Property (const std::string & property_name, PropertyType(Class::*)() const property, const PropertyMatcher & matcher) inline
Definition at line 4509 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::PropertyMatcher<Class, PropertyType,
                                PropertyType (Class::*)() const>(
          property_name, property,
          MatcherCast<GTEST_REFERENCE_TO_CONST_(PropertyType)>(matcher)));
}
References MakePolymorphicMatcher(), and Property().
Property() [2/2]
template<typename Class , typename PropertyType , typename PropertyMatcher > PolymorphicMatcher< internal::PropertyMatcher< Class, PropertyType, PropertyType(Class::*)() const > > testing::Property (PropertyType(Class::*)() const property, const PropertyMatcher & matcher) inline
Definition at line 4491 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::PropertyMatcher<Class, PropertyType,
                                PropertyType (Class::*)() const>(
          property,
          MatcherCast<GTEST_REFERENCE_TO_CONST_(PropertyType)>(matcher)));
  // The call to MatcherCast() is required for supporting inner
  // matchers of compatible types.  For example, it allows
  //   Property(&Foo::bar, m)
  // to compile where bar() returns an int32 and m is a matcher for int64.
}
References MakePolymorphicMatcher(), and Property().
Range() [1/2]
template<typename T > internal::ParamGenerator< T > testing::Range (T start, T end)
Definition at line 244 of file gtest-param-test.h.
{
  return Range(start, end, 1);
}
References Range().
Range() [2/2]
template<typename T , typename IncrementT > internal::ParamGenerator< T > testing::Range (T start, T end, IncrementT step)
Definition at line 238 of file gtest-param-test.h.
{
  return internal::ParamGenerator<T>(
      new internal::RangeGenerator<T, IncrementT>(start, end, step));
}
Ref()
template<typename T > internal::RefMatcher< T & > testing::Ref (T & x) inline
Definition at line 4374 of file gmock-matchers.h.
                                        {  // NOLINT
  return internal::RefMatcher<T&>(x);
}
References Ref().
REGISTER_TYPED_TEST_CASE_P()
testing::REGISTER_TYPED_TEST_CASE_P (CodeLocationForTYPEDTESTP , Verify)
ResultOf()
template<typename Callable , typename ResultOfMatcher > internal::ResultOfMatcher< Callable > testing::ResultOf (Callable callable, const ResultOfMatcher & matcher)
Definition at line 4549 of file gmock-matchers.h.
{
  return internal::ResultOfMatcher<Callable>(
          callable,
          MatcherCast<typename internal::CallableTraits<Callable>::ResultType>(
              matcher));
  // The call to MatcherCast() is required for supporting inner
  // matchers of compatible types.  For example, it allows
  //   ResultOf(Function, m)
  // to compile where Function() returns an int32 and m is a matcher for int64.
}
References MatcherCast(), and ResultOf().
Return() [1/2]
PolymorphicAction< internal::ReturnVoidAction > testing::Return () inline
Definition at line 1128 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::ReturnVoidAction());
}
References MakePolymorphicAction().
Return() [2/2]
template<typename R > internal::ReturnAction< R > testing::Return (R value)
Definition at line 1118 of file gmock-actions.h.
{
  return internal::ReturnAction<R>(internal::move(value));
}
References testing::internal::move().
ReturnNew() [1/10]
p0_type testing::ReturnNew (p0_type p0)
Definition at line 2502 of file gmock-generated-actions.h.
{
ReturnNew() [2/10]
p1_type testing::ReturnNew (p0_type p0, p1_type p1)
Definition at line 2508 of file gmock-generated-actions.h.
{
ReturnNew() [3/10]
p2_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2)
Definition at line 2514 of file gmock-generated-actions.h.
{
ReturnNew() [4/10]
p3_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3)
Definition at line 2520 of file gmock-generated-actions.h.
{
ReturnNew() [5/10]
p4_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4)
Definition at line 2526 of file gmock-generated-actions.h.
{
ReturnNew() [6/10]
p5_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5)
Definition at line 2532 of file gmock-generated-actions.h.
{
ReturnNew() [7/10]
p6_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6)
Definition at line 2538 of file gmock-generated-actions.h.
{
ReturnNew() [8/10]
p7_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7)
Definition at line 2544 of file gmock-generated-actions.h.
{
ReturnNew() [9/10]
p8_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8)
Definition at line 2550 of file gmock-generated-actions.h.
{
ReturnNew() [10/10]
p9_type testing::ReturnNew (p0_type p0, p1_type p1, p2_type p2, p3_type p3, p4_type p4, p5_type p5, p6_type p6, p7_type p7, p8_type p8, p9_type p9)
Definition at line 2556 of file gmock-generated-actions.h.
{
ReturnNull()
PolymorphicAction< internal::ReturnNullAction > testing::ReturnNull () inline
Definition at line 1123 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::ReturnNullAction());
}
References MakePolymorphicAction().
ReturnRef()
template<typename R > internal::ReturnRefAction< R > testing::ReturnRef (R & x) inline
Definition at line 1134 of file gmock-actions.h.
                                                  {  // NOLINT
  return internal::ReturnRefAction<R>(x);
}
References ReturnRef().
ReturnRefOfCopy()
template<typename R > internal::ReturnRefOfCopyAction< R > testing::ReturnRefOfCopy (const R & x) inline
Definition at line 1142 of file gmock-actions.h.
{
  return internal::ReturnRefOfCopyAction<R>(x);
}
References ReturnRefOfCopy().
SafeMatcherCast()
template<typename T , typename M > Matcher< T > testing::SafeMatcherCast (const M & polymorphic_matcher) inline
Definition at line 832 of file gmock-matchers.h.
{
  return SafeMatcherCastImpl<T>::Cast(polymorphic_matcher);
}
References testing::SafeMatcherCastImpl< T >::Cast().
SetArgPointee() [1/3]
template<size_t N> PolymorphicAction< internal::SetArgumentPointeeAction< N, const char *, false > > testing::SetArgPointee (const char * p)
Definition at line 1178 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::SetArgumentPointeeAction<
      N, const char*, false>(p));
}
References MakePolymorphicAction(), and SetArgPointee().
SetArgPointee() [2/3]
template<size_t N, typename T > PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > testing::SetArgPointee (const T & x)
Definition at line 1166 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::SetArgumentPointeeAction<
      N, T, internal::IsAProtocolMessage<T>::value>(x));
}
References MakePolymorphicAction(), SetArgPointee(), and T.
SetArgPointee() [3/3]
template<size_t N> PolymorphicAction< internal::SetArgumentPointeeAction< N, const wchar_t *, false > > testing::SetArgPointee (const wchar_t * p)
Definition at line 1186 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::SetArgumentPointeeAction<
      N, const wchar_t*, false>(p));
}
References MakePolymorphicAction(), and SetArgPointee().
SetArgumentPointee()
template<size_t N, typename T > PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > testing::SetArgumentPointee (const T & x)
Definition at line 1197 of file gmock-actions.h.
{
  return MakePolymorphicAction(internal::SetArgumentPointeeAction<
      N, T, internal::IsAProtocolMessage<T>::value>(x));
}
References MakePolymorphicAction(), SetArgumentPointee(), and T.
SetErrnoAndReturn()
template<typename T > PolymorphicAction< internal::SetErrnoAndReturnAction< T > > testing::SetErrnoAndReturn (int errval, T result)
Definition at line 1213 of file gmock-actions.h.
{
  return MakePolymorphicAction(
      internal::SetErrnoAndReturnAction<T>(errval, result));
}
References MakePolymorphicAction(), and SetErrnoAndReturn().
SizeIs()
template<typename SizeMatcher > internal::SizeIsMatcher< SizeMatcher > testing::SizeIs (const SizeMatcher & size_matcher) inline
Definition at line 4789 of file gmock-matchers.h.
{
  return internal::SizeIsMatcher<SizeMatcher>(size_matcher);
}
References SizeIs().
StartsWith()
PolymorphicMatcher< internal::StartsWithMatcher< std::string > > testing::StartsWith (const std::string & prefix) inline
Definition at line 4600 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::StartsWithMatcher<std::string>(prefix));
}
References MakePolymorphicMatcher(), and StartsWith().
StaticAssertTypeEq()
template<typename T1 , typename T2 > bool testing::StaticAssertTypeEq () private
Definition at line 2238 of file gtest.h.
{
  (void)internal::StaticAssertTypeEqHelper<T1, T2>();
  return true;
}
References StaticAssertTypeEq().
StrCaseEq()
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > testing::StrCaseEq (const std::string & str) inline
Definition at line 4578 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::StrEqualityMatcher<std::string>(str, true, false));
}
References MakePolymorphicMatcher(), and StrCaseEq().
StrCaseNe()
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > testing::StrCaseNe (const std::string & str) inline
Definition at line 4585 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::StrEqualityMatcher<std::string>(str, false, false));
}
References MakePolymorphicMatcher(), and StrCaseNe().
StrEq()
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > testing::StrEq (const std::string & str) inline
Definition at line 4564 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::StrEqualityMatcher<std::string>(str, true, true));
}
References MakePolymorphicMatcher(), and StrEq().
StrNe()
PolymorphicMatcher< internal::StrEqualityMatcher< std::string > > testing::StrNe (const std::string & str) inline
Definition at line 4571 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::StrEqualityMatcher<std::string>(str, false, true));
}
References MakePolymorphicMatcher(), and StrNe().
TempDir()
std::string testing::TempDir () private
Definition at line 5805 of file gtest.cc.
                    {
#if defined(GTEST_CUSTOM_TEMPDIR_FUNCTION_)
  return GTEST_CUSTOM_TEMPDIR_FUNCTION_();
#endif
#if GTEST_OS_WINDOWS_MOBILE
  return "\\temp\\";
#elif GTEST_OS_WINDOWS
  const char* temp_dir = internal::posix::GetEnv("TEMP");
  if (temp_dir == NULL || temp_dir[0] == '\0')
    return "\\temp\\";
  else if (temp_dir[strlen(temp_dir) - 1] == '\\')
    return temp_dir;
  else
    return std::string(temp_dir) + "\\";
#elif GTEST_OS_LINUX_ANDROID
  return "/sdcard/";
#else
  return "/tmp/";
#endif  // GTEST_OS_WINDOWS_MOBILE
}
References testing::internal::posix::GetEnv().
TEST() [1/7]
testing::TEST (CodeLocationForTEST , Verify)
Definition at line 5377 of file gtest_unittest.cc.
{
  VERIFY_CODE_LOCATION;
}
References VERIFY_CODE_LOCATION.
TEST() [2/7]
testing::TEST (GTestEnvVarTest , Dummy)
Definition at line 48 of file gtest_env_var_test_.cc.
{
}
TEST() [3/7]
testing::TEST (SuccessfulAssertionTest , ASSERT) private
Definition at line 4245 of file gtest_unittest.cc.
{
  ASSERT_TRUE(true);
  EXPECT_EQ(0, GetUnitTestImpl()->current_test_result()->total_part_count());
}
References ASSERT_TRUE, and EXPECT_EQ.
TEST() [4/7]
testing::TEST (SuccessfulAssertionTest , ASSERT_STR) private
Definition at line 4251 of file gtest_unittest.cc.
{
  ASSERT_STREQ("", "");
  EXPECT_EQ(0, GetUnitTestImpl()->current_test_result()->total_part_count());
}
References ASSERT_STREQ, and EXPECT_EQ.
TEST() [5/7]
testing::TEST (SuccessfulAssertionTest , EXPECT) private
Definition at line 4233 of file gtest_unittest.cc.
{
  EXPECT_TRUE(true);
  EXPECT_EQ(0, GetUnitTestImpl()->current_test_result()->total_part_count());
}
References EXPECT_EQ, and EXPECT_TRUE.
TEST() [6/7]
testing::TEST (SuccessfulAssertionTest , EXPECT_STR) private
Definition at line 4239 of file gtest_unittest.cc.
{
  EXPECT_STREQ("", "");
  EXPECT_EQ(0, GetUnitTestImpl()->current_test_result()->total_part_count());
}
References EXPECT_EQ, and EXPECT_STREQ.
TEST() [7/7]
testing::TEST (SuccessfulAssertionTest , SUCCEED) private
Definition at line 4226 of file gtest_unittest.cc.
{
  SUCCEED();
  SUCCEED() << "OK";
  EXPECT_EQ(2, GetUnitTestImpl()->current_test_result()->total_part_count());
}
References EXPECT_EQ, and SUCCEED.
TEST_F() [1/48]
testing::TEST_F (CodeLocationForTESTF , Verify)
Definition at line 5384 of file gtest_unittest.cc.
{
  VERIFY_CODE_LOCATION;
}
References VERIFY_CODE_LOCATION.
TEST_F() [2/48]
testing::TEST_F (CurrentTestInfoTest , WorksForFirstTestInATestCase)
Definition at line 6566 of file gtest_unittest.cc.
{
  const TestInfo* test_info =
    UnitTest::GetInstance()->current_test_info();
  ASSERT_TRUE(NULL != test_info)
      << "There is a test running so we should have a valid TestInfo.";
  EXPECT_STREQ("CurrentTestInfoTest", test_info->test_case_name())
      << "Expected the name of the currently running test case.";
  EXPECT_STREQ("WorksForFirstTestInATestCase", test_info->name())
      << "Expected the name of the currently running test.";
}
References ASSERT_TRUE, testing::UnitTest::current_test_info(), EXPECT_STREQ, testing::UnitTest::GetInstance(), testing::TestInfo::name(), and testing::TestInfo::test_case_name().
TEST_F() [3/48]
testing::TEST_F (CurrentTestInfoTest , WorksForSecondTestInATestCase)
Definition at line 6581 of file gtest_unittest.cc.
{
  const TestInfo* test_info =
    UnitTest::GetInstance()->current_test_info();
  ASSERT_TRUE(NULL != test_info)
      << "There is a test running so we should have a valid TestInfo.";
  EXPECT_STREQ("CurrentTestInfoTest", test_info->test_case_name())
      << "Expected the name of the currently running test case.";
  EXPECT_STREQ("WorksForSecondTestInATestCase", test_info->name())
      << "Expected the name of the currently running test.";
}
References ASSERT_TRUE, testing::UnitTest::current_test_info(), EXPECT_STREQ, testing::UnitTest::GetInstance(), testing::TestInfo::name(), and testing::TestInfo::test_case_name().
TEST_F() [4/48]
testing::TEST_F (ParseFlagsTest , AlsoRunDisabledTestsFalse)
Definition at line 6268 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_also_run_disabled_tests=0",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                              Flags::AlsoRunDisabledTests(false), false);
}
References testing::Flags::AlsoRunDisabledTests(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [5/48]
testing::TEST_F (ParseFlagsTest , AlsoRunDisabledTestsFlag)
Definition at line 6234 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_also_run_disabled_tests",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                              Flags::AlsoRunDisabledTests(true), false);
}
References testing::Flags::AlsoRunDisabledTests(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [6/48]
testing::TEST_F (ParseFlagsTest , AlsoRunDisabledTestsTrue)
Definition at line 6251 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_also_run_disabled_tests=1",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                              Flags::AlsoRunDisabledTests(true), false);
}
References testing::Flags::AlsoRunDisabledTests(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [7/48]
testing::TEST_F (ParseFlagsTest , BreakOnFailureFalse_0)
Definition at line 5839 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=0",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(false), false);
}
References testing::Flags::BreakOnFailure(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [8/48]
testing::TEST_F (ParseFlagsTest , BreakOnFailureFalse_f)
Definition at line 5855 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=f",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(false), false);
}
References testing::Flags::BreakOnFailure(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [9/48]
testing::TEST_F (ParseFlagsTest , BreakOnFailureFalse_F)
Definition at line 5871 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=F",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(false), false);
}
References testing::Flags::BreakOnFailure(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [10/48]
testing::TEST_F (ParseFlagsTest , BreakOnFailureTrue)
Definition at line 5888 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure=1",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(true), false);
}
References testing::Flags::BreakOnFailure(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [11/48]
testing::TEST_F (ParseFlagsTest , BreakOnFailureWithoutValue)
Definition at line 5823 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure",
    NULL
};
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::BreakOnFailure(true), false);
}
References testing::Flags::BreakOnFailure(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [12/48]
testing::TEST_F (ParseFlagsTest , CatchExceptions)
Definition at line 5904 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_catch_exceptions",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::CatchExceptions(true), false);
}
References testing::Flags::CatchExceptions(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [13/48]
testing::TEST_F (ParseFlagsTest , DeathTestUseFork)
Definition at line 5920 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_death_test_use_fork",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::DeathTestUseFork(true), false);
}
References testing::Flags::DeathTestUseFork(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [14/48]
testing::TEST_F (ParseFlagsTest , DuplicatedFlags)
Definition at line 5937 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter=a",
    "--gtest_filter=b",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter("b"), false);
}
References testing::Flags::Filter(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [15/48]
testing::TEST_F (ParseFlagsTest , Empty)
Definition at line 5746 of file gtest_unittest.cc.
{
  const char* argv[] = {
    NULL
  };
  const char* argv2[] = {
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), false);
}
References GTEST_TEST_PARSING_FLAGS_.
TEST_F() [16/48]
testing::TEST_F (ParseFlagsTest , FilterBad)
Definition at line 5774 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    "--gtest_filter",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter(""), true);
}
References testing::Flags::Filter(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [17/48]
testing::TEST_F (ParseFlagsTest , FilterEmpty)
Definition at line 5791 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter=",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter(""), false);
}
References testing::Flags::Filter(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [18/48]
testing::TEST_F (ParseFlagsTest , FilterNonEmpty)
Definition at line 5807 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_filter=abc",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Filter("abc"), false);
}
References testing::Flags::Filter(), and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [19/48]
testing::TEST_F (ParseFlagsTest , ListTestsFalse)
Definition at line 6008 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_list_tests=0",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ListTests().
TEST_F() [20/48]
testing::TEST_F (ParseFlagsTest , ListTestsFalse_f)
Definition at line 6024 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_list_tests=f",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ListTests().
TEST_F() [21/48]
testing::TEST_F (ParseFlagsTest , ListTestsFalse_F)
Definition at line 6040 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_list_tests=F",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ListTests().
TEST_F() [22/48]
testing::TEST_F (ParseFlagsTest , ListTestsFlag)
Definition at line 5976 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_list_tests",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ListTests().
TEST_F() [23/48]
testing::TEST_F (ParseFlagsTest , ListTestsTrue)
Definition at line 5992 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_list_tests=1",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ListTests(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ListTests().
TEST_F() [24/48]
testing::TEST_F (ParseFlagsTest , NoFlag)
Definition at line 5759 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), false);
}
References GTEST_TEST_PARSING_FLAGS_.
TEST_F() [25/48]
testing::TEST_F (ParseFlagsTest , OutputEmpty)
Definition at line 6056 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_output",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    "--gtest_output",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags(), true);
}
References GTEST_TEST_PARSING_FLAGS_.
TEST_F() [26/48]
testing::TEST_F (ParseFlagsTest , OutputXml)
Definition at line 6073 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_output=xml",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Output("xml"), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Output().
TEST_F() [27/48]
testing::TEST_F (ParseFlagsTest , OutputXmlDirectory)
Definition at line 6105 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_output=xml:directory/path/",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2,
                            Flags::Output("xml:directory/path/"), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Output().
TEST_F() [28/48]
testing::TEST_F (ParseFlagsTest , OutputXmlFile)
Definition at line 6089 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_output=xml:file",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Output("xml:file"), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Output().
TEST_F() [29/48]
testing::TEST_F (ParseFlagsTest , PrintTimeFalse)
Definition at line 6154 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_print_time=0",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::PrintTime().
TEST_F() [30/48]
testing::TEST_F (ParseFlagsTest , PrintTimeFalse_f)
Definition at line 6170 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_print_time=f",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::PrintTime().
TEST_F() [31/48]
testing::TEST_F (ParseFlagsTest , PrintTimeFalse_F)
Definition at line 6186 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_print_time=F",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::PrintTime().
TEST_F() [32/48]
testing::TEST_F (ParseFlagsTest , PrintTimeFlag)
Definition at line 6122 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_print_time",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::PrintTime().
TEST_F() [33/48]
testing::TEST_F (ParseFlagsTest , PrintTimeTrue)
Definition at line 6138 of file gtest_unittest.cc.
{
    const char* argv[] = {
      "foo.exe",
      "--gtest_print_time=1",
      NULL
    };
    const char* argv2[] = {
      "foo.exe",
      NULL
    };
    GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::PrintTime(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::PrintTime().
TEST_F() [34/48]
testing::TEST_F (ParseFlagsTest , RandomSeed)
Definition at line 6202 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_random_seed=1000",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::RandomSeed(1000), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::RandomSeed().
TEST_F() [35/48]
testing::TEST_F (ParseFlagsTest , Repeat)
Definition at line 6218 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_repeat=1000",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Repeat(1000), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Repeat().
TEST_F() [36/48]
testing::TEST_F (ParseFlagsTest , ShuffleFalse_0)
Definition at line 6301 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_shuffle=0",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Shuffle(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Shuffle().
TEST_F() [37/48]
testing::TEST_F (ParseFlagsTest , ShuffleTrue)
Definition at line 6317 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_shuffle=1",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Shuffle(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Shuffle().
TEST_F() [38/48]
testing::TEST_F (ParseFlagsTest , ShuffleWithoutValue)
Definition at line 6285 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_shuffle",
    NULL
};
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::Shuffle(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::Shuffle().
TEST_F() [39/48]
testing::TEST_F (ParseFlagsTest , StackTraceDepth)
Definition at line 6333 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_stack_trace_depth=5",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::StackTraceDepth(5), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::StackTraceDepth().
TEST_F() [40/48]
testing::TEST_F (ParseFlagsTest , StreamResultTo)
Definition at line 6348 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_stream_result_to=localhost:1234",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(
      argv, argv2, Flags::StreamResultTo("localhost:1234"), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::StreamResultTo().
TEST_F() [41/48]
testing::TEST_F (ParseFlagsTest , ThrowOnFailureFalse_0)
Definition at line 6381 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_throw_on_failure=0",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(false), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ThrowOnFailure().
TEST_F() [42/48]
testing::TEST_F (ParseFlagsTest , ThrowOnFailureTrue)
Definition at line 6398 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_throw_on_failure=1",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ThrowOnFailure().
TEST_F() [43/48]
testing::TEST_F (ParseFlagsTest , ThrowOnFailureWithoutValue)
Definition at line 6365 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_throw_on_failure",
    NULL
};
  const char* argv2[] = {
    "foo.exe",
    NULL
  };
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(true), false);
}
References GTEST_TEST_PARSING_FLAGS_, and testing::Flags::ThrowOnFailure().
TEST_F() [44/48]
testing::TEST_F (ParseFlagsTest , UnrecognizedFlag)
Definition at line 5954 of file gtest_unittest.cc.
{
  const char* argv[] = {
    "foo.exe",
    "--gtest_break_on_failure",
    "bar",  // Unrecognized by Google Test.
    "--gtest_filter=b",
    NULL
  };
  const char* argv2[] = {
    "foo.exe",
    "bar",
    NULL
  };
  Flags flags;
  flags.break_on_failure = true;
  flags.filter = "b";
  GTEST_TEST_PARSING_FLAGS_(argv, argv2, flags, false);
}
References testing::Flags::break_on_failure, testing::Flags::filter, and GTEST_TEST_PARSING_FLAGS_.
TEST_F() [45/48]
testing::TEST_F (SetUpTestCaseTest , Test1)
Definition at line 5477 of file gtest_unittest.cc.
{
  EXPECT_STRNE(NULL, shared_resource_);
}
References EXPECT_STRNE.
TEST_F() [46/48]
testing::TEST_F (SetUpTestCaseTest , Test2)
Definition at line 5482 of file gtest_unittest.cc.
{
  EXPECT_STREQ("123", shared_resource_);
}
References EXPECT_STREQ.
TEST_F() [47/48]
testing::TEST_F (TestInfoTest , Names)
Definition at line 5352 of file gtest_unittest.cc.
{
  const TestInfo* const test_info = GetTestInfo("Names");
  ASSERT_STREQ("TestInfoTest", test_info->test_case_name());
  ASSERT_STREQ("Names", test_info->name());
}
References ASSERT_STREQ, testing::TestInfo::name(), and testing::TestInfo::test_case_name().
TEST_F() [48/48]
testing::TEST_F (TestInfoTest , result)
Definition at line 5360 of file gtest_unittest.cc.
{
  const TestInfo* const test_info = GetTestInfo("result");
  // Initially, there is no TestPartResult for this test.
  ASSERT_EQ(0, GetTestResult(test_info)->total_part_count());
  // After the previous assertion, there is still none.
  ASSERT_EQ(0, GetTestResult(test_info)->total_part_count());
}
References ASSERT_EQ.
TEST_P()
testing::TEST_P (CodeLocationForTESTP , Verify)
Definition at line 5391 of file gtest_unittest.cc.
{
  VERIFY_CODE_LOCATION;
}
References VERIFY_CODE_LOCATION.
TestPartFatallyFailed()
static bool testing::TestPartFatallyFailed (const TestPartResult & result) static
Definition at line 2195 of file gtest.cc.
{
  return result.fatally_failed();
}
References testing::TestPartResult::fatally_failed().
TestPartNonfatallyFailed()
static bool testing::TestPartNonfatallyFailed (const TestPartResult & result) static
Definition at line 2205 of file gtest.cc.
{
  return result.nonfatally_failed();
}
References testing::TestPartResult::nonfatally_failed().
TestPartResultTypeToString()
static const char * testing::TestPartResultTypeToString (TestPartResult::Type type) static
Definition at line 2842 of file gtest.cc.
{
  switch (type) {
    case TestPartResult::kSuccess:
      return "Success";
    case TestPartResult::kNonFatalFailure:
    case TestPartResult::kFatalFailure:
#ifdef _MSC_VER
      return "error: ";
#else
      return "Failure\n";
#endif
    default:
      return "Unknown result type";
  }
}
References testing::TestPartResult::kFatalFailure, testing::TestPartResult::kNonFatalFailure, and testing::TestPartResult::kSuccess.
Truly()
template<typename Predicate > PolymorphicMatcher< internal::TrulyMatcher< Predicate > > testing::Truly (Predicate pred) inline
Definition at line 4777 of file gmock-matchers.h.
                      {
  return MakePolymorphicMatcher(internal::TrulyMatcher<Predicate>(pred));
}
References MakePolymorphicMatcher(), and Truly().
TYPED_TEST()
testing::TYPED_TEST (CodeLocationForTYPEDTEST , Verify)
Definition at line 5403 of file gtest_unittest.cc.
{
  VERIFY_CODE_LOCATION;
}
References VERIFY_CODE_LOCATION.
TYPED_TEST_CASE()
testing::TYPED_TEST_CASE (CodeLocationForTYPEDTEST , int)
TYPED_TEST_CASE_P()
testing::TYPED_TEST_CASE_P (CodeLocationForTYPEDTESTP)
TYPED_TEST_P()
testing::TYPED_TEST_P (CodeLocationForTYPEDTESTP , Verify)
Definition at line 5413 of file gtest_unittest.cc.
{
  VERIFY_CODE_LOCATION;
}
References VERIFY_CODE_LOCATION.
TypedEq()
template<typename Lhs , typename Rhs > Matcher< Lhs > testing::TypedEq (const Rhs & rhs) inline
Definition at line 4327 of file gmock-matchers.h.
{ return Eq(rhs); }
References Eq(), and TypedEq().
UnorderedElementsAre() [1/11]
internal::UnorderedElementsAreMatcher< ::testing::tuple<> > testing::UnorderedElementsAre () inline
Definition at line 788 of file gmock-generated-matchers.h.
                       {
  typedef ::testing::tuple<> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args());
}
References Args().
UnorderedElementsAre() [2/11]
template<typename T1 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type > > testing::UnorderedElementsAre (const T1 & e1) inline
Definition at line 797 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1));
}
References Args().
UnorderedElementsAre() [3/11]
template<typename T1 , typename T2 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2) inline
Definition at line 808 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2));
}
References Args().
UnorderedElementsAre() [4/11]
template<typename T1 , typename T2 , typename T3 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3) inline
Definition at line 821 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3));
}
References Args().
UnorderedElementsAre() [5/11]
template<typename T1 , typename T2 , typename T3 , typename T4 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4) inline
Definition at line 836 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4));
}
References Args().
UnorderedElementsAre() [6/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5) inline
Definition at line 853 of file gmock-generated-matchers.h.
                  {
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5));
}
References Args().
UnorderedElementsAre() [7/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6) inline
Definition at line 874 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5,
      e6));
}
References Args().
UnorderedElementsAre() [8/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7) inline
Definition at line 898 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5,
      e6, e7));
}
References Args().
UnorderedElementsAre() [9/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8) inline
Definition at line 924 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type,
      typename internal::DecayArray<T8>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5,
      e6, e7, e8));
}
References Args().
UnorderedElementsAre() [10/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9) inline
Definition at line 952 of file gmock-generated-matchers.h.
{
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type,
      typename internal::DecayArray<T8>::type,
      typename internal::DecayArray<T9>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5,
      e6, e7, e8, e9));
}
References Args().
UnorderedElementsAre() [11/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > internal::UnorderedElementsAreMatcher< ::testing::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9, const T10 & e10) inline
Definition at line 982 of file gmock-generated-matchers.h.
                    {
  typedef ::testing::tuple<
      typename internal::DecayArray<T1>::type,
      typename internal::DecayArray<T2>::type,
      typename internal::DecayArray<T3>::type,
      typename internal::DecayArray<T4>::type,
      typename internal::DecayArray<T5>::type,
      typename internal::DecayArray<T6>::type,
      typename internal::DecayArray<T7>::type,
      typename internal::DecayArray<T8>::type,
      typename internal::DecayArray<T9>::type,
      typename internal::DecayArray<T10>::type> Args;
  return internal::UnorderedElementsAreMatcher<Args>(Args(e1, e2, e3, e4, e5,
      e6, e7, e8, e9, e10));
}
References Args().
UnorderedElementsAreArray() [1/4]
template<typename Container > internal::UnorderedElementsAreArrayMatcher< typename Container::value_type > testing::UnorderedElementsAreArray (const Container & container) inline
Definition at line 4263 of file gmock-matchers.h.
{
  return UnorderedElementsAreArray(container.begin(), container.end());
}
References UnorderedElementsAreArray().
UnorderedElementsAreArray() [2/4]
template<typename T > internal::UnorderedElementsAreArrayMatcher< T > testing::UnorderedElementsAreArray (const T * pointer, size_t count) inline
Definition at line 4250 of file gmock-matchers.h.
{
  return UnorderedElementsAreArray(pointer, pointer + count);
}
References UnorderedElementsAreArray().
UnorderedElementsAreArray() [3/4]
template<typename T , size_t N> internal::UnorderedElementsAreArrayMatcher< T > testing::UnorderedElementsAreArray (const T(&) array[N]) inline
Definition at line 4256 of file gmock-matchers.h.
{
  return UnorderedElementsAreArray(array, N);
}
References UnorderedElementsAreArray().
UnorderedElementsAreArray() [4/4]
template<typename Iter > internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > testing::UnorderedElementsAreArray (Iter first, Iter last) inline
Definition at line 4242 of file gmock-matchers.h.
{
  typedef typename ::std::iterator_traits<Iter>::value_type T;
  return internal::UnorderedElementsAreArrayMatcher<T>(
      internal::UnorderedMatcherRequire::ExactMatch, first, last);
}
References testing::internal::UnorderedMatcherRequire::ExactMatch, and T.
UnorderedPointwise()
template<typename Tuple2Matcher , typename RhsContainer > internal::UnorderedElementsAreArrayMatcher< typename internal::BoundSecondMatcher< Tuple2Matcher, typename internal::StlContainerView< GTEST_REMOVE_CONST_(RhsContainer)>::type::value_type > > testing::UnorderedPointwise (const Tuple2Matcher & tuple2_matcher, const RhsContainer & rhs_container) inline
Definition at line 4884 of file gmock-matchers.h.
{
  // This following line is for working around a bug in MSVC 8.0,
  // which causes RhsContainer to be a const type sometimes (e.g. when
  // rhs_container is a const int[]).
  typedef GTEST_REMOVE_CONST_(RhsContainer) RawRhsContainer;
  // RhsView allows the same code to handle RhsContainer being a
  // STL-style container and it being a native C-style array.
  typedef typename internal::StlContainerView<RawRhsContainer> RhsView;
  typedef typename RhsView::type RhsStlContainer;
  typedef typename RhsStlContainer::value_type Second;
  const RhsStlContainer& rhs_stl_container =
      RhsView::ConstReference(rhs_container);
  // Create a matcher for each element in rhs_container.
  ::std::vector<internal::BoundSecondMatcher<Tuple2Matcher, Second> > matchers;
  for (typename RhsStlContainer::const_iterator it = rhs_stl_container.begin();
       it != rhs_stl_container.end(); ++it) {
    matchers.push_back(
        internal::MatcherBindSecond(tuple2_matcher, *it));
  }
  // Delegate the work to UnorderedElementsAreArray().
  return UnorderedElementsAreArray(matchers);
}
References GTEST_REMOVE_CONST_, testing::internal::MatcherBindSecond(), UnorderedElementsAreArray(), and UnorderedPointwise().
ValidateTestPropertyName()
static bool testing::ValidateTestPropertyName (const std::string & property_name, const std::vector< std::string > & reserved_names) static
Definition at line 2156 of file gtest.cc.
{
  if (std::find(reserved_names.begin(), reserved_names.end(), property_name) !=
          reserved_names.end()) {
    ADD_FAILURE() << "Reserved key used in RecordProperty(): " << property_name
                  << " (" << FormatWordList(reserved_names)
                  << " are reserved by " << GTEST_NAME_ << ")";
    return false;
  }
  return true;
}
References ADD_FAILURE, FormatWordList(), and GTEST_NAME_.
Value()
template<typename T , typename M > bool testing::Value (const T & value, M matcher) inline
Definition at line 5130 of file gmock-matchers.h.
{
  return testing::Matches(matcher)(value);
}
References Matches().
Values() [1/50]
template<typename T1 > internal::ValueArray1< T1 > testing::Values (T1 v1)
Definition at line 344 of file gtest-param-test.h.
{
  return internal::ValueArray1<T1>(v1);
}
Values() [2/50]
template<typename T1 , typename T2 > internal::ValueArray2< T1, T2 > testing::Values (T1 v1, T2 v2)
Definition at line 349 of file gtest-param-test.h.
{
  return internal::ValueArray2<T1, T2>(v1, v2);
}
Values() [3/50]
template<typename T1 , typename T2 , typename T3 > internal::ValueArray3< T1, T2, T3 > testing::Values (T1 v1, T2 v2, T3 v3)
Definition at line 354 of file gtest-param-test.h.
{
  return internal::ValueArray3<T1, T2, T3>(v1, v2, v3);
}
Values() [4/50]
template<typename T1 , typename T2 , typename T3 , typename T4 > internal::ValueArray4< T1, T2, T3, T4 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4)
Definition at line 359 of file gtest-param-test.h.
{
  return internal::ValueArray4<T1, T2, T3, T4>(v1, v2, v3, v4);
}
Values() [5/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > internal::ValueArray5< T1, T2, T3, T4, T5 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5)
Definition at line 364 of file gtest-param-test.h.
           {
  return internal::ValueArray5<T1, T2, T3, T4, T5>(v1, v2, v3, v4, v5);
}
Values() [6/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > internal::ValueArray6< T1, T2, T3, T4, T5, T6 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6)
Definition at line 371 of file gtest-param-test.h.
{
  return internal::ValueArray6<T1, T2, T3, T4, T5, T6>(v1, v2, v3, v4, v5, v6);
}
Values() [7/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > internal::ValueArray7< T1, T2, T3, T4, T5, T6, T7 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7)
Definition at line 378 of file gtest-param-test.h.
{
  return internal::ValueArray7<T1, T2, T3, T4, T5, T6, T7>(v1, v2, v3, v4, v5,
      v6, v7);
}
Values() [8/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > internal::ValueArray8< T1, T2, T3, T4, T5, T6, T7, T8 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8)
Definition at line 386 of file gtest-param-test.h.
{
  return internal::ValueArray8<T1, T2, T3, T4, T5, T6, T7, T8>(v1, v2, v3, v4,
      v5, v6, v7, v8);
}
Values() [9/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > internal::ValueArray9< T1, T2, T3, T4, T5, T6, T7, T8, T9 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9)
Definition at line 394 of file gtest-param-test.h.
{
  return internal::ValueArray9<T1, T2, T3, T4, T5, T6, T7, T8, T9>(v1, v2, v3,
      v4, v5, v6, v7, v8, v9);
}
Values() [10/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > internal::ValueArray10< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10)
Definition at line 402 of file gtest-param-test.h.
{
  return internal::ValueArray10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(v1,
      v2, v3, v4, v5, v6, v7, v8, v9, v10);
}
Values() [11/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 > internal::ValueArray11< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11)
Definition at line 412 of file gtest-param-test.h.
                      {
  return internal::ValueArray11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10,
      T11>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11);
}
Values() [12/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 > internal::ValueArray12< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12)
Definition at line 422 of file gtest-param-test.h.
{
  return internal::ValueArray12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12);
}
Values() [13/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 > internal::ValueArray13< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13)
Definition at line 432 of file gtest-param-test.h.
{
  return internal::ValueArray13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13);
}
Values() [14/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 > internal::ValueArray14< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14)
Definition at line 442 of file gtest-param-test.h.
{
  return internal::ValueArray14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13,
      v14);
}
Values() [15/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 > internal::ValueArray15< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15)
Definition at line 453 of file gtest-param-test.h.
{
  return internal::ValueArray15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12,
      v13, v14, v15);
}
Values() [16/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 > internal::ValueArray16< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16)
Definition at line 465 of file gtest-param-test.h.
             {
  return internal::ValueArray16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11,
      v12, v13, v14, v15, v16);
}
Values() [17/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 > internal::ValueArray17< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17)
Definition at line 478 of file gtest-param-test.h.
                      {
  return internal::ValueArray17<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10,
      v11, v12, v13, v14, v15, v16, v17);
}
Values() [18/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 > internal::ValueArray18< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18)
Definition at line 491 of file gtest-param-test.h.
{
  return internal::ValueArray18<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18>(v1, v2, v3, v4, v5, v6, v7, v8, v9,
      v10, v11, v12, v13, v14, v15, v16, v17, v18);
}
Values() [19/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 > internal::ValueArray19< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19)
Definition at line 504 of file gtest-param-test.h.
{
  return internal::ValueArray19<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19>(v1, v2, v3, v4, v5, v6, v7, v8,
      v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19);
}
Values() [20/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 > internal::ValueArray20< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20)
Definition at line 517 of file gtest-param-test.h.
{
  return internal::ValueArray20<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20>(v1, v2, v3, v4, v5, v6, v7,
      v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20);
}
Values() [21/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 > internal::ValueArray21< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21)
Definition at line 531 of file gtest-param-test.h.
{
  return internal::ValueArray21<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21>(v1, v2, v3, v4, v5, v6,
      v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21);
}
Values() [22/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 > internal::ValueArray22< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22)
Definition at line 545 of file gtest-param-test.h.
                      {
  return internal::ValueArray22<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22>(v1, v2, v3, v4,
      v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19,
      v20, v21, v22);
}
Values() [23/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 > internal::ValueArray23< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23)
Definition at line 561 of file gtest-param-test.h.
{
  return internal::ValueArray23<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23>(v1, v2, v3,
      v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19,
      v20, v21, v22, v23);
}
Values() [24/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 > internal::ValueArray24< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24)
Definition at line 577 of file gtest-param-test.h.
{
  return internal::ValueArray24<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24>(v1, v2,
      v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18,
      v19, v20, v21, v22, v23, v24);
}
Values() [25/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 > internal::ValueArray25< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25)
Definition at line 593 of file gtest-param-test.h.
{
  return internal::ValueArray25<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25>(v1,
      v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17,
      v18, v19, v20, v21, v22, v23, v24, v25);
}
Values() [26/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 > internal::ValueArray26< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26)
Definition at line 611 of file gtest-param-test.h.
             {
  return internal::ValueArray26<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15,
      v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26);
}
Values() [27/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 > internal::ValueArray27< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27)
Definition at line 629 of file gtest-param-test.h.
                      {
  return internal::ValueArray27<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14,
      v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27);
}
Values() [28/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 > internal::ValueArray28< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28)
Definition at line 647 of file gtest-param-test.h.
{
  return internal::ValueArray28<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13,
      v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27,
      v28);
}
Values() [29/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 > internal::ValueArray29< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29)
Definition at line 666 of file gtest-param-test.h.
{
  return internal::ValueArray29<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12,
      v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26,
      v27, v28, v29);
}
Values() [30/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 > internal::ValueArray30< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30)
Definition at line 685 of file gtest-param-test.h.
{
  return internal::ValueArray30<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11,
      v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25,
      v26, v27, v28, v29, v30);
}
Values() [31/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 > internal::ValueArray31< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31)
Definition at line 705 of file gtest-param-test.h.
{
  return internal::ValueArray31<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10,
      v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24,
      v25, v26, v27, v28, v29, v30, v31);
}
Values() [32/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 > internal::ValueArray32< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32)
Definition at line 725 of file gtest-param-test.h.
             {
  return internal::ValueArray32<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32>(v1, v2, v3, v4, v5, v6, v7, v8, v9,
      v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23,
      v24, v25, v26, v27, v28, v29, v30, v31, v32);
}
Values() [33/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 > internal::ValueArray33< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33)
Definition at line 746 of file gtest-param-test.h.
                      {
  return internal::ValueArray33<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33>(v1, v2, v3, v4, v5, v6, v7, v8,
      v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23,
      v24, v25, v26, v27, v28, v29, v30, v31, v32, v33);
}
Values() [34/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 > internal::ValueArray34< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34)
Definition at line 767 of file gtest-param-test.h.
{
  return internal::ValueArray34<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34>(v1, v2, v3, v4, v5, v6, v7,
      v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22,
      v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34);
}
Values() [35/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 > internal::ValueArray35< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35)
Definition at line 788 of file gtest-param-test.h.
{
  return internal::ValueArray35<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35>(v1, v2, v3, v4, v5, v6,
      v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21,
      v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35);
}
Values() [36/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 > internal::ValueArray36< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36)
Definition at line 810 of file gtest-param-test.h.
{
  return internal::ValueArray36<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36>(v1, v2, v3, v4,
      v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19,
      v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33,
      v34, v35, v36);
}
Values() [37/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 > internal::ValueArray37< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37)
Definition at line 833 of file gtest-param-test.h.
             {
  return internal::ValueArray37<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37>(v1, v2, v3,
      v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19,
      v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33,
      v34, v35, v36, v37);
}
Values() [38/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 > internal::ValueArray38< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38)
Definition at line 857 of file gtest-param-test.h.
                      {
  return internal::ValueArray38<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38>(v1, v2,
      v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18,
      v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32,
      v33, v34, v35, v36, v37, v38);
}
Values() [39/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 > internal::ValueArray39< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39)
Definition at line 881 of file gtest-param-test.h.
{
  return internal::ValueArray39<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39>(v1,
      v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17,
      v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31,
      v32, v33, v34, v35, v36, v37, v38, v39);
}
Values() [40/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 > internal::ValueArray40< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40)
Definition at line 905 of file gtest-param-test.h.
{
  return internal::ValueArray40<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15,
      v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29,
      v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40);
}
Values() [41/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 > internal::ValueArray41< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41)
Definition at line 931 of file gtest-param-test.h.
{
  return internal::ValueArray41<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14,
      v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28,
      v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41);
}
Values() [42/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 > internal::ValueArray42< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42)
Definition at line 956 of file gtest-param-test.h.
             {
  return internal::ValueArray42<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13,
      v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27,
      v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41,
      v42);
}
Values() [43/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 > internal::ValueArray43< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43)
Definition at line 983 of file gtest-param-test.h.
                      {
  return internal::ValueArray43<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12,
      v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26,
      v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40,
      v41, v42, v43);
}
Values() [44/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 > internal::ValueArray44< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44)
Definition at line 1010 of file gtest-param-test.h.
{
  return internal::ValueArray44<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11,
      v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25,
      v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39,
      v40, v41, v42, v43, v44);
}
Values() [45/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 > internal::ValueArray45< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45)
Definition at line 1037 of file gtest-param-test.h.
{
  return internal::ValueArray45<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44, T45>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10,
      v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24,
      v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38,
      v39, v40, v41, v42, v43, v44, v45);
}
Values() [46/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 > internal::ValueArray46< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46)
Definition at line 1065 of file gtest-param-test.h.
{
  return internal::ValueArray46<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44, T45, T46>(v1, v2, v3, v4, v5, v6, v7, v8, v9,
      v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23,
      v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37,
      v38, v39, v40, v41, v42, v43, v44, v45, v46);
}
Values() [47/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 > internal::ValueArray47< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47)
Definition at line 1093 of file gtest-param-test.h.
{
  return internal::ValueArray47<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44, T45, T46, T47>(v1, v2, v3, v4, v5, v6, v7, v8,
      v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23,
      v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37,
      v38, v39, v40, v41, v42, v43, v44, v45, v46, v47);
}
Values() [48/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 , typename T48 > internal::ValueArray48< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47, T48 v48)
Definition at line 1121 of file gtest-param-test.h.
             {
  return internal::ValueArray48<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44, T45, T46, T47, T48>(v1, v2, v3, v4, v5, v6, v7,
      v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22,
      v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36,
      v37, v38, v39, v40, v41, v42, v43, v44, v45, v46, v47, v48);
}
Values() [49/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 , typename T48 , typename T49 > internal::ValueArray49< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47, T48 v48, T49 v49)
Definition at line 1150 of file gtest-param-test.h.
{
  return internal::ValueArray49<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44, T45, T46, T47, T48, T49>(v1, v2, v3, v4, v5, v6,
      v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21,
      v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35,
      v36, v37, v38, v39, v40, v41, v42, v43, v44, v45, v46, v47, v48, v49);
}
Values() [50/50]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 , typename T13 , typename T14 , typename T15 , typename T16 , typename T17 , typename T18 , typename T19 , typename T20 , typename T21 , typename T22 , typename T23 , typename T24 , typename T25 , typename T26 , typename T27 , typename T28 , typename T29 , typename T30 , typename T31 , typename T32 , typename T33 , typename T34 , typename T35 , typename T36 , typename T37 , typename T38 , typename T39 , typename T40 , typename T41 , typename T42 , typename T43 , typename T44 , typename T45 , typename T46 , typename T47 , typename T48 , typename T49 , typename T50 > internal::ValueArray50< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49, T50 > testing::Values (T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, T9 v9, T10 v10, T11 v11, T12 v12, T13 v13, T14 v14, T15 v15, T16 v16, T17 v17, T18 v18, T19 v19, T20 v20, T21 v21, T22 v22, T23 v23, T24 v24, T25 v25, T26 v26, T27 v27, T28 v28, T29 v29, T30 v30, T31 v31, T32 v32, T33 v33, T34 v34, T35 v35, T36 v36, T37 v37, T38 v38, T39 v39, T40 v40, T41 v41, T42 v42, T43 v43, T44 v44, T45 v45, T46 v46, T47 v47, T48 v48, T49 v49, T50 v50)
Definition at line 1179 of file gtest-param-test.h.
{
  return internal::ValueArray50<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11,
      T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25,
      T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39,
      T40, T41, T42, T43, T44, T45, T46, T47, T48, T49, T50>(v1, v2, v3, v4,
      v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19,
      v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33,
      v34, v35, v36, v37, v38, v39, v40, v41, v42, v43, v44, v45, v46, v47,
      v48, v49, v50);
}
ValuesIn() [1/3]
template<class Container > internal::ParamGenerator< typename Container::value_type > testing::ValuesIn (const Container & container)
Definition at line 319 of file gtest-param-test.h.
{
  return ValuesIn(container.begin(), container.end());
}
References ValuesIn().
ValuesIn() [2/3]
template<typename T , size_t N> internal::ParamGenerator< T > testing::ValuesIn (const T(&) array[N])
Definition at line 314 of file gtest-param-test.h.
{
  return ValuesIn(array, array + N);
}
References ValuesIn().
ValuesIn() [3/3]
template<typename ForwardIterator > internal::ParamGenerator< typename ::testing::internal::IteratorTraits< ForwardIterator >::value_type > testing::ValuesIn (ForwardIterator begin, ForwardIterator end)
Definition at line 306 of file gtest-param-test.h.
{
  typedef typename ::testing::internal::IteratorTraits<ForwardIterator>
      ::value_type ParamType;
  return internal::ParamGenerator<ParamType>(
      new internal::ValuesInIteratorRangeGenerator<ParamType>(begin, end));
}
VariantWith()
template<typename T > PolymorphicMatcher< internal::variant_matcher::VariantMatcher< T > > testing::VariantWith (const Matcher< const T & > & matcher)
Definition at line 5233 of file gmock-matchers.h.
{
  return MakePolymorphicMatcher(
      internal::variant_matcher::VariantMatcher<T>(matcher));
}
References MakePolymorphicMatcher().
WhenSorted()
template<typename ContainerMatcher > internal::WhenSortedByMatcher< internal::LessComparator, ContainerMatcher > testing::WhenSorted (const ContainerMatcher & container_matcher) inline
Definition at line 4833 of file gmock-matchers.h.
{
  return
      internal::WhenSortedByMatcher<internal::LessComparator, ContainerMatcher>(
          internal::LessComparator(), container_matcher);
}
References WhenSorted().
WhenSortedBy()
template<typename Comparator , typename ContainerMatcher > internal::WhenSortedByMatcher< Comparator, ContainerMatcher > testing::WhenSortedBy (const Comparator & comparator, const ContainerMatcher & container_matcher) inline
Definition at line 4823 of file gmock-matchers.h.
{
  return internal::WhenSortedByMatcher<Comparator, ContainerMatcher>(
      comparator, container_matcher);
}
References WhenSortedBy().
WithArg()
template<int k, typename InnerAction > internal::WithArgsAction< InnerAction, k > testing::WithArg (const InnerAction & action) inline
Definition at line 146 of file gmock-more-actions.h.
{
  return internal::WithArgsAction<InnerAction, k>(action);
}
References WithArg().
WithArgs() [1/10]
template<int k1, typename InnerAction > internal::WithArgsAction< InnerAction, k1 > testing::WithArgs (const InnerAction & action) inline
Definition at line 705 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1>(action);
}
References WithArgs().
WithArgs() [2/10]
template<int k1, int k2, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2 > testing::WithArgs (const InnerAction & action) inline
Definition at line 711 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2>(action);
}
References WithArgs().
WithArgs() [3/10]
template<int k1, int k2, int k3, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3 > testing::WithArgs (const InnerAction & action) inline
Definition at line 717 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3>(action);
}
References WithArgs().
WithArgs() [4/10]
template<int k1, int k2, int k3, int k4, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4 > testing::WithArgs (const InnerAction & action) inline
Definition at line 723 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4>(action);
}
References WithArgs().
WithArgs() [5/10]
template<int k1, int k2, int k3, int k4, int k5, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5 > testing::WithArgs (const InnerAction & action) inline
Definition at line 729 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4, k5>(action);
}
References WithArgs().
WithArgs() [6/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6 > testing::WithArgs (const InnerAction & action) inline
Definition at line 735 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4, k5, k6>(action);
}
References WithArgs().
WithArgs() [7/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7 > testing::WithArgs (const InnerAction & action) inline
Definition at line 742 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4, k5, k6,
      k7>(action);
}
References WithArgs().
WithArgs() [8/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8 > testing::WithArgs (const InnerAction & action) inline
Definition at line 750 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4, k5, k6, k7,
      k8>(action);
}
References WithArgs().
WithArgs() [9/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9 > testing::WithArgs (const InnerAction & action) inline
Definition at line 758 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4, k5, k6, k7, k8,
      k9>(action);
}
References WithArgs().
WithArgs() [10/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > testing::WithArgs (const InnerAction & action) inline
Definition at line 767 of file gmock-generated-actions.h.
{
  return internal::WithArgsAction<InnerAction, k1, k2, k3, k4, k5, k6, k7, k8,
      k9, k10>(action);
}
References WithArgs().
WithoutArgs()
template<typename InnerAction > internal::WithArgsAction< InnerAction > testing::WithoutArgs (const InnerAction & action) inline
Definition at line 135 of file gmock-more-actions.h.
{
  return internal::WithArgsAction<InnerAction>(action);
}
References WithoutArgs().
Variable Documentation
_
const internal::AnythingMatcher testing::_ = {}
Definition at line 4284 of file gmock-matchers.h.
{};
GTEST_ATTRIBUTE_UNUSED_
class GTEST_API_ testing::ScopedTrace testing::GTEST_ATTRIBUTE_UNUSED_
kDeathTestCaseFilter
const char testing::kDeathTestCaseFilter[] = "*DeathTest:*DeathTest/*" static
Definition at line 158 of file gtest.cc.
kDefaultDeathTestStyle
const char testing::kDefaultDeathTestStyle[] = GTEST_DEFAULT_DEATH_TEST_STYLE static
Definition at line 87 of file gtest-death-test.cc.
kDefaultOutputFile
const char testing::kDefaultOutputFile[] = "test_detail" static
Definition at line 166 of file gtest.cc.
kDefaultOutputFormat
const char testing::kDefaultOutputFormat[] = "xml" static
Definition at line 164 of file gtest.cc.
kDisableTestFilter
const char testing::kDisableTestFilter[] = "DISABLED_*:*/DISABLED_*" static
Definition at line 153 of file gtest.cc.
kMaxStackTraceDepth
const int testing::kMaxStackTraceDepth = 100
Definition at line 159 of file gtest.h.
kReservedTestCaseAttributes
const char* const testing::kReservedTestCaseAttributes[] static
Initial value:
= {
  "classname",
  "name",
  "status",
  "time",
  "type_param",
  "value_param"
}
Definition at line 2113 of file gtest.cc.
{
  "classname",
  "name",
  "status",
  "time",
  "type_param",
  "value_param"
};
kReservedTestSuiteAttributes
const char* const testing::kReservedTestSuiteAttributes[] static
Initial value:
= {
  "disabled",
  "errors",
  "failures",
  "name",
  "tests",
  "time"
}
Definition at line 2103 of file gtest.cc.
{
  "disabled",
  "errors",
  "failures",
  "name",
  "tests",
  "time"
};
kReservedTestSuitesAttributes
const char* const testing::kReservedTestSuitesAttributes[] static
Initial value:
= {
  "disabled",
  "errors",
  "failures",
  "name",
  "random_seed",
  "tests",
  "time",
  "timestamp"
}
Definition at line 2090 of file gtest.cc.
{
  "disabled",
  "errors",
  "failures",
  "name",
  "random_seed",
  "tests",
  "time",
  "timestamp"
};
kTestShardIndex
const char testing::kTestShardIndex[] = "GTEST_SHARD_INDEX" static
Definition at line 169 of file gtest.cc.
kTestShardStatusFile
const char testing::kTestShardStatusFile[] = "GTEST_SHARD_STATUS_FILE" static
Definition at line 173 of file gtest.cc.
kTestTotalShards
const char testing::kTestTotalShards[] = "GTEST_TOTAL_SHARDS" static
Definition at line 171 of file gtest.cc.
kUniversalFilter
const char testing::kUniversalFilter[] = "*" static
Definition at line 161 of file gtest.cc.
p0_type
testing::internal::Function< F >::Result testing::p0_type
Definition at line 2410 of file gmock-generated-actions.h.
p1_type
testing::internal::Function< F >::Result testing::p1_type
Definition at line 2419 of file gmock-generated-actions.h.
p2_type
testing::internal::Function< F >::Result testing::p2_type
Definition at line 2428 of file gmock-generated-actions.h.
p3_type
testing::internal::Function< F >::Result testing::p3_type
Definition at line 2437 of file gmock-generated-actions.h.
p4_type
testing::internal::Function< F >::Result testing::p4_type
Definition at line 2446 of file gmock-generated-actions.h.
p5_type
testing::internal::Function< F >::Result testing::p5_type
Definition at line 2455 of file gmock-generated-actions.h.
p6_type
testing::internal::Function< F >::Result testing::p6_type
Definition at line 2464 of file gmock-generated-actions.h.
p7_type
testing::internal::Function< F >::Result testing::p7_type
Definition at line 2473 of file gmock-generated-actions.h.
p8_type
testing::internal::Function< F >::Result testing::p8_type
Definition at line 2482 of file gmock-generated-actions.h.