wiNpoS: anonymous_namespace{gmock-spec-builders_test.cc} Namespace Reference
anonymous_namespace{gmock-spec-builders_test.cc} Namespace Reference
Classes
class CC
class EvenNumberCardinality
class GMockLogTest
class LogTestHelper
class MockA
class MockB
class MockC
class MockCC
class MockConstOverload
class MockIncomplete
struct MockWithConstMethods
class NonDefaultConstructible
class PartialOrderTest
struct Printable
class PrintMeNot
class ReferenceHoldingMock
class Result
struct Unprintable
class VerboseFlagPreservingFixture
Functions
void PrintTo (const Incomplete &x, ::std::ostream *os)
TEST (MockMethodTest, CanInstantiateWithIncompleteArgType)
TEST (OnCallSyntaxTest, CompilesWithMethodNameExpandedFromMacro)
TEST (OnCallSyntaxTest, WorksWithMethodNameExpandedFromMacro)
TEST (ExpectCallSyntaxTest, CompilesWithMethodNameExpandedFromMacro)
TEST (ExpectCallSyntaxTest, WorksWithMethodNameExpandedFromMacro)
TEST (OnCallSyntaxTest, EvaluatesFirstArgumentOnce)
TEST (OnCallSyntaxTest, EvaluatesSecondArgumentOnce)
TEST (OnCallSyntaxTest, WithIsOptional)
TEST (OnCallSyntaxTest, WithCanAppearAtMostOnce)
TEST (OnCallSyntaxTest, WillByDefaultIsMandatory)
TEST (OnCallSyntaxTest, WillByDefaultCanAppearAtMostOnce)
TEST (ExpectCallSyntaxTest, EvaluatesFirstArgumentOnce)
TEST (ExpectCallSyntaxTest, EvaluatesSecondArgumentOnce)
TEST (ExpectCallSyntaxTest, WithIsOptional)
TEST (ExpectCallSyntaxTest, WithCanAppearAtMostOnce)
TEST (ExpectCallSyntaxTest, WithMustBeFirstClause)
TEST (ExpectCallSyntaxTest, TimesCanBeInferred)
TEST (ExpectCallSyntaxTest, TimesCanAppearAtMostOnce)
TEST (ExpectCallSyntaxTest, TimesMustBeBeforeInSequence)
TEST (ExpectCallSyntaxTest, InSequenceIsOptional)
TEST (ExpectCallSyntaxTest, InSequenceCanAppearMultipleTimes)
TEST (ExpectCallSyntaxTest, InSequenceMustBeBeforeAfter)
TEST (ExpectCallSyntaxTest, InSequenceMustBeBeforeWillOnce)
TEST (ExpectCallSyntaxTest, AfterMustBeBeforeWillOnce)
TEST (ExpectCallSyntaxTest, WillIsOptional)
TEST (ExpectCallSyntaxTest, WillCanAppearMultipleTimes)
TEST (ExpectCallSyntaxTest, WillMustBeBeforeWillRepeatedly)
TEST (ExpectCallSyntaxTest, WillRepeatedlyIsOptional)
TEST (ExpectCallSyntaxTest, WillRepeatedlyCannotAppearMultipleTimes)
TEST (ExpectCallSyntaxTest, WillRepeatedlyMustBeBeforeRetiresOnSaturation)
TEST (ExpectCallSyntaxTest, RetiresOnSaturationIsOptional)
TEST (ExpectCallSyntaxTest, RetiresOnSaturationCannotAppearMultipleTimes)
TEST (ExpectCallSyntaxTest, DefaultCardinalityIsOnce)
TEST (OnCallTest, TakesBuiltInDefaultActionWhenNoOnCall)
TEST (OnCallTest, TakesBuiltInDefaultActionWhenNoOnCallMatches)
TEST (OnCallTest, PicksLastMatchingOnCall)
TEST (ExpectCallTest, AllowsAnyCallWhenNoSpec)
TEST (ExpectCallTest, PicksLastMatchingExpectCall)
TEST (ExpectCallTest, CatchesTooFewCalls)
TEST (ExpectCallTest, InfersCardinalityWhenThereIsNoWillRepeatedly)
TEST (ExpectCallTest, InfersCardinality1WhenThereIsWillRepeatedly)
TEST (ExpectCallTest, NthMatchTakesNthAction)
TEST (ExpectCallTest, TakesRepeatedActionWhenWillListIsExhausted)
TEST (UninterestingCallTest, DoesDefaultAction)
TEST (UnexpectedCallTest, DoesDefaultAction)
TEST (UnexpectedCallTest, GeneratesFailureForVoidFunction)
TEST (UnexpectedCallTest, GeneartesFailureForNonVoidFunction)
TEST (UnexpectedCallTest, RetiredExpectation)
TEST (UnexpectedCallTest, UnmatchedArguments)
TEST (UnexpectedCallTest, UnsatisifiedPrerequisites)
TEST (UndefinedReturnValueTest, ReturnValueIsMandatoryWhenNotDefaultConstructible)
TEST (ExcessiveCallTest, DoesDefaultAction)
TEST (ExcessiveCallTest, GeneratesFailureForVoidFunction)
TEST (ExcessiveCallTest, GeneratesFailureForNonVoidFunction)
TEST (InSequenceTest, AllExpectationInScopeAreInSequence)
TEST (InSequenceTest, NestedInSequence)
TEST (InSequenceTest, ExpectationsOutOfScopeAreNotAffected)
TEST (SequenceTest, AnyOrderIsOkByDefault)
TEST (SequenceTest, CallsMustBeInStrictOrderWhenSaidSo1)
TEST (SequenceTest, CallsMustBeInStrictOrderWhenSaidSo2)
TEST_F (PartialOrderTest, CallsMustConformToSpecifiedDag1)
TEST_F (PartialOrderTest, CallsMustConformToSpecifiedDag2)
TEST_F (PartialOrderTest, CallsMustConformToSpecifiedDag3)
TEST_F (PartialOrderTest, CallsMustConformToSpecifiedDag4)
TEST (SequenceTest, Retirement)
TEST (ExpectationTest, ConstrutorsWork)
TEST (ExpectationTest, AssignmentWorks)
TEST (ExpectationSetTest, MemberTypesAreCorrect)
TEST (ExpectationSetTest, ConstructorsWork)
TEST (ExpectationSetTest, AssignmentWorks)
TEST (ExpectationSetTest, InsertionWorks)
TEST (ExpectationSetTest, SizeWorks)
TEST (ExpectationSetTest, IsEnumerable)
TEST (AfterTest, SucceedsWhenPartialOrderIsSatisfied)
TEST (AfterTest, SucceedsWhenTotalOrderIsSatisfied)
TEST (AfterTest, CallsMustBeInStrictOrderWhenSpecifiedSo1)
TEST (AfterTest, CallsMustBeInStrictOrderWhenSpecifiedSo2)
TEST (AfterTest, CallsMustSatisfyPartialOrderWhenSpecifiedSo)
TEST (AfterTest, CallsMustSatisfyPartialOrderWhenSpecifiedSo2)
TEST (AfterTest, CanBeUsedWithInSequence)
TEST (AfterTest, CanBeCalledManyTimes)
TEST (AfterTest, AcceptsUpToFiveArguments)
TEST (AfterTest, AcceptsDuplicatedInput)
TEST (AfterTest, ChangesToExpectationSetHaveNoEffectAfterwards)
TEST (DeletingMockEarlyTest, Success1)
TEST (DeletingMockEarlyTest, Success2)
ACTION_P (Delete, ptr)
TEST (DeletingMockEarlyTest, CanDeleteSelfInActionReturningVoid)
TEST (DeletingMockEarlyTest, CanDeleteSelfInActionReturningValue)
TEST (DeletingMockEarlyTest, Failure1)
TEST (DeletingMockEarlyTest, Failure2)
Cardinality EvenNumber ()
TEST (ExpectationBaseTest, AllPrerequisitesAreSatisfiedWorksForNonMonotonicCardinality)
void operator<< (::std::ostream &os, const Printable &)
void PrintTo (PrintMeNot, ::std::ostream *)
TEST_F (GMockLogTest, DoesNotPrintGoodCallInternallyIfVerbosityIsWarning)
TEST_F (GMockLogTest, DoesNotPrintGoodCallInternallyIfVerbosityIsError)
TEST_F (GMockLogTest, DoesNotPrintWarningInternallyIfVerbosityIsError)
TEST (AllowLeakTest, AllowsLeakingUnusedMockObject)
TEST (AllowLeakTest, CanBeCalledBeforeOnCall)
TEST (AllowLeakTest, CanBeCalledAfterOnCall)
TEST (AllowLeakTest, CanBeCalledBeforeExpectCall)
TEST (AllowLeakTest, CanBeCalledAfterExpectCall)
TEST (AllowLeakTest, WorksWhenBothOnCallAndExpectCallArePresent)
TEST (VerifyAndClearExpectationsTest, NoMethodHasExpectations)
TEST (VerifyAndClearExpectationsTest, SomeMethodsHaveExpectationsAndSucceed)
TEST (VerifyAndClearExpectationsTest, SomeMethodsHaveExpectationsAndFail)
TEST (VerifyAndClearExpectationsTest, AllMethodsHaveExpectations)
TEST (VerifyAndClearExpectationsTest, AMethodHasManyExpectations)
TEST (VerifyAndClearExpectationsTest, CanCallManyTimes)
TEST (VerifyAndClearTest, NoMethodHasDefaultActions)
TEST (VerifyAndClearTest, SomeMethodsHaveDefaultActions)
TEST (VerifyAndClearTest, AllMethodsHaveDefaultActions)
TEST (VerifyAndClearTest, AMethodHasManyDefaultActions)
TEST (VerifyAndClearTest, CanCallManyTimes)
TEST (VerifyAndClearTest, Success)
TEST (VerifyAndClearTest, Failure)
TEST (VerifyAndClearTest, Const)
TEST (VerifyAndClearTest, CanSetDefaultActionsAndExpectationsAfterwards)
TEST (VerifyAndClearTest, DoesNotAffectOtherMockObjects)
TEST (VerifyAndClearTest, DestroyingChainedMocksDoesNotDeadlockThroughExpectations)
TEST (VerifyAndClearTest, DestroyingChainedMocksDoesNotDeadlockThroughDefaultAction)
TEST (SynchronizationTest, CanCallMockMethodInAction)
TEST (ParameterlessExpectationsTest, CanSetExpectationsWithoutMatchers)
TEST (ParameterlessExpectationsTest, CanSetExpectationsForOverloadedMethods)
TEST (ParameterlessExpectationsTest, CanSetExpectationsForConstMethods)
TEST (ParameterlessExpectationsTest, CanSetExpectationsForConstOverloadedMethods)
Function Documentation
ACTION_P()
anonymous_namespace{gmock-spec-builders_test.cc}::ACTION_P (Delete , ptr)
Definition at line 1883 of file gmock-spec-builders_test.cc.
{ delete ptr; }
EvenNumber()
Cardinality anonymous_namespace{gmock-spec-builders_test.cc}::EvenNumber ()
Definition at line 1971 of file gmock-spec-builders_test.cc.
{
  return Cardinality(new EvenNumberCardinality);
}
operator<<()
void anonymous_namespace{gmock-spec-builders_test.cc}::operator<< (::std::ostream & os, const Printable &) inline
Definition at line 2001 of file gmock-spec-builders_test.cc.
{
  os << "Printable";
}
PrintTo() [1/2]
void anonymous_namespace{gmock-spec-builders_test.cc}::PrintTo (const Incomplete & x, ::std::ostream * os)
Definition at line 135 of file gmock-spec-builders_test.cc.
{
  *os << "incomplete";
}
PrintTo() [2/2]
void anonymous_namespace{gmock-spec-builders_test.cc}::PrintTo (PrintMeNot , ::std::ostream *)
Definition at line 2248 of file gmock-spec-builders_test.cc.
{
  ADD_FAILURE() << "Google Mock is printing a value that shouldn't be "
                << "printed even to an internal buffer.";
}
References ADD_FAILURE.
TEST() [1/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , AcceptsDuplicatedInput)
Definition at line 1779 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ON_CALL(a, ReturnResult(_))
      .WillByDefault(Return(Result()));
  // Define ordering:
  //   DoA(1) ==>
  //   DoA(2) ==> ReturnResult(3)
  Expectation e1 = EXPECT_CALL(a, DoA(1));
  Expectation e2 = EXPECT_CALL(a, DoA(2));
  ExpectationSet es;
  es += e1;
  es += e2;
  EXPECT_CALL(a, ReturnResult(3))
      .After(e1, e2, es, e1);
  a.DoA(1);
  // May only be after DoA(2).
  EXPECT_NONFATAL_FAILURE(a.ReturnResult(3), "Unexpected mock function call");
  a.DoA(2);
  a.ReturnResult(3);
}
References EXPECT_CALL, EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [2/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , AcceptsUpToFiveArguments)
Definition at line 1760 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Expectation e1 = EXPECT_CALL(a, DoA(1));
  Expectation e2 = EXPECT_CALL(a, DoA(2));
  Expectation e3 = EXPECT_CALL(a, DoA(3));
  ExpectationSet es1 = EXPECT_CALL(a, DoA(4));
  ExpectationSet es2 = EXPECT_CALL(a, DoA(5));
  EXPECT_CALL(a, DoA(6))
      .After(e1, e2, e3, es1, es2);
  a.DoA(5);
  a.DoA(2);
  a.DoA(4);
  a.DoA(1);
  a.DoA(3);
  a.DoA(6);
}
References EXPECT_CALL.
TEST() [3/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , CallsMustBeInStrictOrderWhenSpecifiedSo1)
Definition at line 1635 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockB b;
  // Define ordering:
  //   a.DoA(1) ==> b.DoB() ==> a.DoA(2)
  Expectation e1 = EXPECT_CALL(a, DoA(1));
  Expectation e2 = EXPECT_CALL(b, DoB())
      .After(e1);
  EXPECT_CALL(a, DoA(2))
      .After(e2);
  a.DoA(1);
  // May only be called after DoB().
  EXPECT_NONFATAL_FAILURE(a.DoA(2), "Unexpected mock function call");
  b.DoB();
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [4/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , CallsMustBeInStrictOrderWhenSpecifiedSo2)
Definition at line 1657 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockB b;
  // Define ordering:
  //   a.DoA(1) ==> b.DoB() * 2 ==> a.DoA(2)
  Expectation e1 = EXPECT_CALL(a, DoA(1));
  Expectation e2 = EXPECT_CALL(b, DoB())
      .Times(2)
      .After(e1);
  EXPECT_CALL(a, DoA(2))
      .After(e2);
  a.DoA(1);
  b.DoB();
  // May only be called after the second DoB().
  EXPECT_NONFATAL_FAILURE(a.DoA(2), "Unexpected mock function call");
  b.DoB();
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [5/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , CallsMustSatisfyPartialOrderWhenSpecifiedSo)
Definition at line 1681 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ON_CALL(a, ReturnResult(_))
      .WillByDefault(Return(Result()));
  // Define ordering:
  //   a.DoA(1) ==>
  //   a.DoA(2) ==> a.ReturnResult(3)
  Expectation e = EXPECT_CALL(a, DoA(1));
  const ExpectationSet es = EXPECT_CALL(a, DoA(2));
  EXPECT_CALL(a, ReturnResult(3))
      .After(e, es);
  // May only be called last.
  EXPECT_NONFATAL_FAILURE(a.ReturnResult(3), "Unexpected mock function call");
  a.DoA(2);
  a.DoA(1);
  a.ReturnResult(3);
}
References EXPECT_CALL, EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [6/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , CallsMustSatisfyPartialOrderWhenSpecifiedSo2)
Definition at line 1703 of file gmock-spec-builders_test.cc.
{
  MockA a;
  // Define ordering:
  //   a.DoA(1) ==>
  //   a.DoA(2) ==> a.DoA(3)
  Expectation e = EXPECT_CALL(a, DoA(1));
  const ExpectationSet es = EXPECT_CALL(a, DoA(2));
  EXPECT_CALL(a, DoA(3))
      .After(e, es);
  a.DoA(2);
  // May only be called last.
  EXPECT_NONFATAL_FAILURE(a.DoA(3), "Unexpected mock function call");
  a.DoA(1);
  a.DoA(3);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [7/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , CanBeCalledManyTimes)
Definition at line 1743 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Expectation e1 = EXPECT_CALL(a, DoA(1));
  Expectation e2 = EXPECT_CALL(a, DoA(2));
  Expectation e3 = EXPECT_CALL(a, DoA(3));
  EXPECT_CALL(a, DoA(4))
      .After(e1)
      .After(e2)
      .After(e3);
  a.DoA(3);
  a.DoA(1);
  a.DoA(2);
  a.DoA(4);
}
References EXPECT_CALL.
TEST() [8/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , CanBeUsedWithInSequence)
Definition at line 1724 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s;
  Expectation e = EXPECT_CALL(a, DoA(1));
  EXPECT_CALL(a, DoA(2)).InSequence(s);
  EXPECT_CALL(a, DoA(3))
      .InSequence(s)
      .After(e);
  a.DoA(1);
  // May only be after DoA(2).
  EXPECT_NONFATAL_FAILURE(a.DoA(3), "Unexpected mock function call");
  a.DoA(2);
  a.DoA(3);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [9/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , ChangesToExpectationSetHaveNoEffectAfterwards)
Definition at line 1806 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ExpectationSet es1 = EXPECT_CALL(a, DoA(1));
  Expectation e2 = EXPECT_CALL(a, DoA(2));
  EXPECT_CALL(a, DoA(3))
      .After(es1);
  es1 += e2;
  a.DoA(1);
  a.DoA(3);
  a.DoA(2);
}
References EXPECT_CALL.
TEST() [10/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , SucceedsWhenPartialOrderIsSatisfied)
Definition at line 1604 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ExpectationSet es;
  es += EXPECT_CALL(a, DoA(1));
  es += EXPECT_CALL(a, DoA(2));
  EXPECT_CALL(a, DoA(3))
      .After(es);
  a.DoA(1);
  a.DoA(2);
  a.DoA(3);
}
References EXPECT_CALL.
TEST() [11/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AfterTest , SucceedsWhenTotalOrderIsSatisfied)
Definition at line 1617 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockB b;
  // The following also verifies that const Expectation objects work
  // too.  Do not remove the const modifiers.
  const Expectation e1 = EXPECT_CALL(a, DoA(1));
  const Expectation e2 = EXPECT_CALL(b, DoB())
      .Times(2)
      .After(e1);
  EXPECT_CALL(a, DoA(2)).After(e2);
  a.DoA(1);
  b.DoB();
  b.DoB();
  a.DoA(2);
}
References EXPECT_CALL.
TEST() [12/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AllowLeakTest , AllowsLeakingUnusedMockObject)
Definition at line 2291 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  Mock::AllowLeak(a);
}
TEST() [13/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AllowLeakTest , CanBeCalledAfterExpectCall)
Definition at line 2316 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  EXPECT_CALL(*a, DoA(_)).Times(AnyNumber());
  Mock::AllowLeak(a);
}
References EXPECT_CALL.
TEST() [14/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AllowLeakTest , CanBeCalledAfterOnCall)
Definition at line 2303 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  ON_CALL(*a, DoA(_)).WillByDefault(Return());
  Mock::AllowLeak(a);
}
References ON_CALL.
TEST() [15/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AllowLeakTest , CanBeCalledBeforeExpectCall)
Definition at line 2309 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  Mock::AllowLeak(a);
  EXPECT_CALL(*a, DoA(_));
  a->DoA(0);
}
References EXPECT_CALL.
TEST() [16/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AllowLeakTest , CanBeCalledBeforeOnCall)
Definition at line 2296 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  Mock::AllowLeak(a);
  ON_CALL(*a, DoA(_)).WillByDefault(Return());
  a->DoA(0);
}
References ON_CALL.
TEST() [17/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (AllowLeakTest , WorksWhenBothOnCallAndExpectCallArePresent)
Definition at line 2322 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  ON_CALL(*a, DoA(_)).WillByDefault(Return());
  EXPECT_CALL(*a, DoA(_)).Times(AnyNumber());
  Mock::AllowLeak(a);
}
References EXPECT_CALL, and ON_CALL.
TEST() [18/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (DeletingMockEarlyTest , CanDeleteSelfInActionReturningValue)
Definition at line 1895 of file gmock-spec-builders_test.cc.
{
  MockA* const a = new MockA;
  EXPECT_CALL(*a, ReturnResult(_))
      .WillOnce(DoAll(Delete(a), Return(Result())));
  a->ReturnResult(42);  // This will cause a to be deleted.
}
References EXPECT_CALL.
TEST() [19/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (DeletingMockEarlyTest , CanDeleteSelfInActionReturningVoid)
Definition at line 1889 of file gmock-spec-builders_test.cc.
{
  MockA* const a = new MockA;
  EXPECT_CALL(*a, DoA(_)).WillOnce(Delete(a));
  a->DoA(42);  // This will cause a to be deleted.
}
References EXPECT_CALL.
TEST() [20/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (DeletingMockEarlyTest , Failure1)
Definition at line 1903 of file gmock-spec-builders_test.cc.
{
  MockB* const b1 = new MockB;
  MockA* const a = new MockA;
  MockB* const b2 = new MockB;
  {
    InSequence dummy;
    EXPECT_CALL(*b1, DoB(_))
        .WillOnce(Return(1));
    EXPECT_CALL(*a, Binary(_, _))
        .Times(AnyNumber());
    EXPECT_CALL(*b2, DoB(_))
        .Times(AnyNumber())
        .WillRepeatedly(Return(2));
  }
  delete a;  // a is trivially satisfied.
  EXPECT_NONFATAL_FAILURE({
    b2->DoB(2);
  }, "Unexpected mock function call");
  EXPECT_EQ(1, b1->DoB(1));
  delete b1;
  delete b2;
}
References EXPECT_CALL, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [21/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (DeletingMockEarlyTest , Failure2)
Definition at line 1929 of file gmock-spec-builders_test.cc.
{
  MockB* const b1 = new MockB;
  MockA* const a = new MockA;
  MockB* const b2 = new MockB;
  {
    InSequence dummy;
    EXPECT_CALL(*b1, DoB(_));
    EXPECT_CALL(*a, Binary(_, _))
        .Times(AnyNumber());
    EXPECT_CALL(*b2, DoB(_))
        .Times(AnyNumber());
  }
  EXPECT_NONFATAL_FAILURE(delete b1,
                          "Actual: never called");
  EXPECT_NONFATAL_FAILURE(a->Binary(0, 1),
                          "Unexpected mock function call");
  EXPECT_NONFATAL_FAILURE(b2->DoB(1),
                          "Unexpected mock function call");
  delete a;
  delete b2;
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [22/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (DeletingMockEarlyTest , Success1)
Definition at line 1823 of file gmock-spec-builders_test.cc.
{
  MockB* const b1 = new MockB;
  MockA* const a = new MockA;
  MockB* const b2 = new MockB;
  {
    InSequence dummy;
    EXPECT_CALL(*b1, DoB(_))
        .WillOnce(Return(1));
    EXPECT_CALL(*a, Binary(_, _))
        .Times(AnyNumber())
        .WillRepeatedly(Return(true));
    EXPECT_CALL(*b2, DoB(_))
        .Times(AnyNumber())
        .WillRepeatedly(Return(2));
  }
  EXPECT_EQ(1, b1->DoB(1));
  delete b1;
  // a's pre-requisite has died.
  EXPECT_TRUE(a->Binary(0, 1));
  delete b2;
  // a's successor has died.
  EXPECT_TRUE(a->Binary(1, 2));
  delete a;
}
References EXPECT_CALL, EXPECT_EQ, and EXPECT_TRUE.
TEST() [23/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (DeletingMockEarlyTest , Success2)
Definition at line 1851 of file gmock-spec-builders_test.cc.
{
  MockB* const b1 = new MockB;
  MockA* const a = new MockA;
  MockB* const b2 = new MockB;
  {
    InSequence dummy;
    EXPECT_CALL(*b1, DoB(_))
        .WillOnce(Return(1));
    EXPECT_CALL(*a, Binary(_, _))
        .Times(AnyNumber());
    EXPECT_CALL(*b2, DoB(_))
        .Times(AnyNumber())
        .WillRepeatedly(Return(2));
  }
  delete a;  // a is trivially satisfied.
  EXPECT_EQ(1, b1->DoB(1));
  EXPECT_EQ(2, b2->DoB(2));
  delete b1;
  delete b2;
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [24/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExcessiveCallTest , DoesDefaultAction)
Definition at line 1191 of file gmock-spec-builders_test.cc.
{
  // When there is an ON_CALL() statement, the action specified by it
  // should be taken.
  MockA a;
  ON_CALL(a, Binary(_, _))
      .WillByDefault(Return(true));
  EXPECT_CALL(a, Binary(0, 0));
  a.Binary(0, 0);
  bool result = false;
  EXPECT_NONFATAL_FAILURE(result = a.Binary(0, 0),
                          "Mock function called more times than expected");
  EXPECT_TRUE(result);
  // When there is no ON_CALL(), the default value for the return type
  // should be returned.
  MockB b;
  EXPECT_CALL(b, DoB(0))
      .Times(0);
  int n = -1;
  EXPECT_NONFATAL_FAILURE(n = b.DoB(0),
                          "Mock function called more times than expected");
  EXPECT_EQ(0, n);
}
References EXPECT_CALL, EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_TRUE, and ON_CALL.
TEST() [25/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExcessiveCallTest , GeneratesFailureForNonVoidFunction)
Definition at line 1231 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB(_));
  b.DoB(1);
  EXPECT_NONFATAL_FAILURE(
      b.DoB(2),
      "Mock function called more times than expected - "
      "returning default value.\n"
      "    Function call: DoB(2)\n"
      "          Returns: 0\n"
      "         Expected: to be called once\n"
      "           Actual: called twice - over-saturated and active");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [26/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExcessiveCallTest , GeneratesFailureForVoidFunction)
Definition at line 1217 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(_))
      .Times(0);
  EXPECT_NONFATAL_FAILURE(
      a.DoA(9),
      "Mock function called more times than expected - returning directly.\n"
      "    Function call: DoA(9)\n"
      "         Expected: to be never called\n"
      "           Actual: called once - over-saturated and active");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [27/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationBaseTest , AllPrerequisitesAreSatisfiedWorksForNonMonotonicCardinality)
Definition at line 1975 of file gmock-spec-builders_test.cc.
{
  MockA* a = new MockA;
  Sequence s;
  EXPECT_CALL(*a, DoA(1))
      .Times(EvenNumber())
      .InSequence(s);
  EXPECT_CALL(*a, DoA(2))
      .Times(AnyNumber())
      .InSequence(s);
  EXPECT_CALL(*a, DoA(3))
      .Times(AnyNumber());
  a->DoA(3);
  a->DoA(1);
  EXPECT_NONFATAL_FAILURE(a->DoA(2), "Unexpected mock function call");
  EXPECT_NONFATAL_FAILURE(delete a, "to be called even number of times");
}
References EvenNumber(), EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [28/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationSetTest , AssignmentWorks)
Definition at line 1546 of file gmock-spec-builders_test.cc.
{
  ExpectationSet es1;
  ExpectationSet es2 = Expectation();
  es1 = es2;
  EXPECT_EQ(1, es1.size());
  EXPECT_THAT(*(es1.begin()), Eq(Expectation()));
  EXPECT_THAT(es1, Eq(es2));
}
References testing::ExpectationSet::begin(), EXPECT_EQ, EXPECT_THAT, and testing::ExpectationSet::size().
TEST() [29/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationSetTest , ConstructorsWork)
Definition at line 1517 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Expectation e1;
  const Expectation e2;
  ExpectationSet es1;  // Default ctor.
  ExpectationSet es2 = EXPECT_CALL(a, DoA(1));  // Ctor from EXPECT_CALL.
  ExpectationSet es3 = e1;  // Ctor from Expectation.
  ExpectationSet es4(e1);   // Ctor from Expectation; alternative syntax.
  ExpectationSet es5 = e2;  // Ctor from const Expectation.
  ExpectationSet es6(e2);   // Ctor from const Expectation; alternative syntax.
  ExpectationSet es7 = es2;  // Copy ctor.
  EXPECT_EQ(0, es1.size());
  EXPECT_EQ(1, es2.size());
  EXPECT_EQ(1, es3.size());
  EXPECT_EQ(1, es4.size());
  EXPECT_EQ(1, es5.size());
  EXPECT_EQ(1, es6.size());
  EXPECT_EQ(1, es7.size());
  EXPECT_THAT(es3, Ne(es2));
  EXPECT_THAT(es4, Eq(es3));
  EXPECT_THAT(es5, Eq(es4));
  EXPECT_THAT(es6, Eq(es5));
  EXPECT_THAT(es7, Eq(es2));
  a.DoA(1);
}
References EXPECT_CALL, EXPECT_EQ, EXPECT_THAT, and testing::ExpectationSet::size().
TEST() [30/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationSetTest , InsertionWorks)
Definition at line 1556 of file gmock-spec-builders_test.cc.
{
  ExpectationSet es1;
  Expectation e1;
  es1 += e1;
  EXPECT_EQ(1, es1.size());
  EXPECT_THAT(*(es1.begin()), Eq(e1));
  MockA a;
  Expectation e2 = EXPECT_CALL(a, DoA(1));
  es1 += e2;
  EXPECT_EQ(2, es1.size());
  ExpectationSet::const_iterator it1 = es1.begin();
  ExpectationSet::const_iterator it2 = it1;
  ++it2;
  EXPECT_TRUE(*it1 == e1 || *it2 == e1);  // e1 must be in the set.
  EXPECT_TRUE(*it1 == e2 || *it2 == e2);  // e2 must be in the set too.
  a.DoA(1);
}
References testing::ExpectationSet::begin(), EXPECT_CALL, EXPECT_EQ, EXPECT_THAT, EXPECT_TRUE, and testing::ExpectationSet::size().
TEST() [31/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationSetTest , IsEnumerable)
Definition at line 1590 of file gmock-spec-builders_test.cc.
{
  ExpectationSet es;
  EXPECT_TRUE(es.begin() == es.end());
  es += Expectation();
  ExpectationSet::const_iterator it = es.begin();
  EXPECT_TRUE(it != es.end());
  EXPECT_THAT(*it, Eq(Expectation()));
  ++it;
  EXPECT_TRUE(it== es.end());
}
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), EXPECT_THAT, and EXPECT_TRUE.
TEST() [32/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationSetTest , MemberTypesAreCorrect)
Definition at line 1513 of file gmock-spec-builders_test.cc.
{
  ::testing::StaticAssertTypeEq<Expectation, ExpectationSet::value_type>();
}
TEST() [33/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationSetTest , SizeWorks)
Definition at line 1576 of file gmock-spec-builders_test.cc.
{
  ExpectationSet es;
  EXPECT_EQ(0, es.size());
  es += Expectation();
  EXPECT_EQ(1, es.size());
  MockA a;
  es += EXPECT_CALL(a, DoA(1));
  EXPECT_EQ(2, es.size());
  a.DoA(1);
}
References EXPECT_CALL, EXPECT_EQ, and testing::ExpectationSet::size().
TEST() [34/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationTest , AssignmentWorks)
Definition at line 1498 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Expectation e1;
  Expectation e2 = EXPECT_CALL(a, DoA(1));
  EXPECT_THAT(e1, Ne(e2));
  e1 = e2;
  EXPECT_THAT(e1, Eq(e2));
  a.DoA(1);
}
References EXPECT_CALL, and EXPECT_THAT.
TEST() [35/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectationTest , ConstrutorsWork)
Definition at line 1466 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Expectation e1;  // Default ctor.
  // Ctor from various forms of EXPECT_CALL.
  Expectation e2 = EXPECT_CALL(a, DoA(2));
  Expectation e3 = EXPECT_CALL(a, DoA(3)).With(_);
  {
    Sequence s;
    Expectation e4 = EXPECT_CALL(a, DoA(4)).Times(1);
    Expectation e5 = EXPECT_CALL(a, DoA(5)).InSequence(s);
  }
  Expectation e6 = EXPECT_CALL(a, DoA(6)).After(e2);
  Expectation e7 = EXPECT_CALL(a, DoA(7)).WillOnce(Return());
  Expectation e8 = EXPECT_CALL(a, DoA(8)).WillRepeatedly(Return());
  Expectation e9 = EXPECT_CALL(a, DoA(9)).RetiresOnSaturation();
  Expectation e10 = e2;  // Copy ctor.
  EXPECT_THAT(e1, Ne(e2));
  EXPECT_THAT(e2, Eq(e10));
  a.DoA(2);
  a.DoA(3);
  a.DoA(4);
  a.DoA(5);
  a.DoA(6);
  a.DoA(7);
  a.DoA(8);
  a.DoA(9);
}
References EXPECT_CALL, and EXPECT_THAT.
TEST() [36/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , AfterMustBeBeforeWillOnce)
Definition at line 450 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Expectation e = EXPECT_CALL(a, DoA(1));
  EXPECT_NONFATAL_FAILURE({
    EXPECT_CALL(a, DoA(2))
        .WillOnce(Return())
        .After(e);
  }, ".After() cannot appear after ");
  a.DoA(1);
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [37/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , CompilesWithMethodNameExpandedFromMacro)
Definition at line 219 of file gmock-spec-builders_test.cc.
{
  MockCC cc;
  EXPECT_CALL(cc, Method());
  cc.Method();
}
References EXPECT_CALL, and Method.
TEST() [38/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , DefaultCardinalityIsOnce)
Definition at line 555 of file gmock-spec-builders_test.cc.
{
  {
    MockA a;
    EXPECT_CALL(a, DoA(1));
    a.DoA(1);
  }
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    MockA a;
    EXPECT_CALL(a, DoA(1));
  }, "to be called once");
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    MockA a;
    EXPECT_CALL(a, DoA(1));
    a.DoA(1);
    a.DoA(1);
  }, "to be called once");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [39/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , EvaluatesFirstArgumentOnce)
Definition at line 296 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockA* pa = &a;
  EXPECT_CALL(*pa++, DoA(_));
  a.DoA(0);
  EXPECT_EQ(&a + 1, pa);
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [40/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , EvaluatesSecondArgumentOnce)
Definition at line 305 of file gmock-spec-builders_test.cc.
{
  MockA a;
  int n = 0;
  EXPECT_CALL(a, DoA(n++));
  a.DoA(0);
  EXPECT_EQ(1, n);
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [41/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , InSequenceCanAppearMultipleTimes)
Definition at line 411 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s1, s2;
  EXPECT_CALL(a, DoA(1))
      .InSequence(s1, s2)
      .InSequence(s1);
  a.DoA(1);
}
References EXPECT_CALL.
TEST() [42/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , InSequenceIsOptional)
Definition at line 399 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s;
  EXPECT_CALL(a, DoA(1));
  EXPECT_CALL(a, DoA(2))
      .InSequence(s);
  a.DoA(1);
  a.DoA(2);
}
References EXPECT_CALL.
TEST() [43/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , InSequenceMustBeBeforeAfter)
Definition at line 422 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s;
  Expectation e = EXPECT_CALL(a, DoA(1))
      .Times(AnyNumber());
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(2))
        .After(e)
        .InSequence(s);
  }, ".InSequence() cannot appear after ");
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [44/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , InSequenceMustBeBeforeWillOnce)
Definition at line 437 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .WillOnce(Return())
        .InSequence(s);
  }, ".InSequence() cannot appear after ");
  a.DoA(1);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [45/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , RetiresOnSaturationCannotAppearMultipleTimes)
Definition at line 543 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .RetiresOnSaturation()
        .RetiresOnSaturation();
  }, ".RetiresOnSaturation() cannot appear more than once");
  a.DoA(1);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [46/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , RetiresOnSaturationIsOptional)
Definition at line 532 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(1));
  EXPECT_CALL(a, DoA(1))
      .RetiresOnSaturation();
  a.DoA(1);
  a.DoA(1);
}
References EXPECT_CALL.
TEST() [47/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , TimesCanAppearAtMostOnce)
Definition at line 373 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .Times(1)
        .Times(2);
  }, ".Times() cannot appear more than once in an EXPECT_CALL()");
  a.DoA(1);
  a.DoA(1);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [48/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , TimesCanBeInferred)
Definition at line 358 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(1))
      .WillOnce(Return());
  EXPECT_CALL(a, DoA(2))
      .WillOnce(Return())
      .WillRepeatedly(Return());
  a.DoA(1);
  a.DoA(2);
  a.DoA(2);
}
References EXPECT_CALL.
TEST() [49/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , TimesMustBeBeforeInSequence)
Definition at line 386 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .InSequence(s)
        .Times(1);
  }, ".Times() cannot appear after ");
  a.DoA(1);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [50/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WillCanAppearMultipleTimes)
Definition at line 475 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(1))
      .Times(AnyNumber())
      .WillOnce(Return())
      .WillOnce(Return())
      .WillOnce(Return());
}
References EXPECT_CALL.
TEST() [51/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WillIsOptional)
Definition at line 464 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(1));
  EXPECT_CALL(a, DoA(2))
      .WillOnce(Return());
  a.DoA(1);
  a.DoA(2);
}
References EXPECT_CALL.
TEST() [52/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WillMustBeBeforeWillRepeatedly)
Definition at line 485 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .WillRepeatedly(Return())
        .WillOnce(Return());
  }, ".WillOnce() cannot appear after ");
  a.DoA(1);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [53/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WillRepeatedlyCannotAppearMultipleTimes)
Definition at line 511 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .WillRepeatedly(Return())
        .WillRepeatedly(Return());
  }, ".WillRepeatedly() cannot appear more than once in an "
     "EXPECT_CALL()");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [54/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WillRepeatedlyIsOptional)
Definition at line 497 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(1))
      .WillOnce(Return());
  EXPECT_CALL(a, DoA(2))
      .WillOnce(Return())
      .WillRepeatedly(Return());
  a.DoA(1);
  a.DoA(2);
  a.DoA(2);
}
References EXPECT_CALL.
TEST() [55/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WillRepeatedlyMustBeBeforeRetiresOnSaturation)
Definition at line 522 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .RetiresOnSaturation()
        .WillRepeatedly(Return());
  }, ".WillRepeatedly() cannot appear after ");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [56/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WithCanAppearAtMostOnce)
Definition at line 326 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(6))
        .With(_)
        .With(_);
  }, ".With() cannot appear more than once in an EXPECT_CALL()");
  a.DoA(6);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [57/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WithIsOptional)
Definition at line 316 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_CALL(a, DoA(5))
      .Times(0);
  EXPECT_CALL(a, DoA(6))
      .With(_)
      .Times(0);
}
References EXPECT_CALL.
TEST() [58/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WithMustBeFirstClause)
Definition at line 338 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(1))
        .Times(1)
        .With(_);
  }, ".With() must be the first clause in an EXPECT_CALL()");
  a.DoA(1);
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_CALL(a, DoA(2))
        .WillOnce(Return())
        .With(_);
  }, ".With() must be the first clause in an EXPECT_CALL()");
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [59/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallSyntaxTest , WorksWithMethodNameExpandedFromMacro)
Definition at line 226 of file gmock-spec-builders_test.cc.
{
  MockCC cc;
  EXPECT_CALL(cc, Method()).WillOnce(Return(42));
  EXPECT_EQ(42, cc.Method());
}
References EXPECT_CALL, EXPECT_EQ, and Method.
TEST() [60/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , AllowsAnyCallWhenNoSpec)
Definition at line 793 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB());
  // There is no expectation on DoB(int).
  b.DoB();
  // DoB(int) can be called any number of times.
  b.DoB(1);
  b.DoB(2);
}
References EXPECT_CALL.
TEST() [61/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , CatchesTooFewCalls)
Definition at line 817 of file gmock-spec-builders_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    MockB b;
    EXPECT_CALL(b, DoB(5))
        .Times(AtLeast(2));
    b.DoB(5);
  }, "Actual function call count doesn't match EXPECT_CALL(b, DoB(5))...\n"
     "         Expected: to be called at least twice\n"
     "           Actual: called once - unsatisfied and active");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [62/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , InfersCardinality1WhenThereIsWillRepeatedly)
Definition at line 863 of file gmock-spec-builders_test.cc.
{
  {
    MockB b;
    EXPECT_CALL(b, DoB())
        .WillOnce(Return(1))
        .WillRepeatedly(Return(2));
    EXPECT_EQ(1, b.DoB());
  }
  {  // NOLINT
    MockB b;
    EXPECT_CALL(b, DoB())
        .WillOnce(Return(1))
        .WillRepeatedly(Return(2));
    EXPECT_EQ(1, b.DoB());
    EXPECT_EQ(2, b.DoB());
    EXPECT_EQ(2, b.DoB());
  }
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    MockB b;
    EXPECT_CALL(b, DoB())
        .WillOnce(Return(1))
        .WillRepeatedly(Return(2));
  }, "to be called at least once");
}
References EXPECT_CALL, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [63/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , InfersCardinalityWhenThereIsNoWillRepeatedly)
Definition at line 831 of file gmock-spec-builders_test.cc.
{
  {
    MockB b;
    EXPECT_CALL(b, DoB())
        .WillOnce(Return(1))
        .WillOnce(Return(2));
    EXPECT_EQ(1, b.DoB());
    EXPECT_EQ(2, b.DoB());
  }
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    MockB b;
    EXPECT_CALL(b, DoB())
        .WillOnce(Return(1))
        .WillOnce(Return(2));
    EXPECT_EQ(1, b.DoB());
  }, "to be called twice");
  {  // NOLINT
    MockB b;
    EXPECT_CALL(b, DoB())
        .WillOnce(Return(1))
        .WillOnce(Return(2));
    EXPECT_EQ(1, b.DoB());
    EXPECT_EQ(2, b.DoB());
    EXPECT_NONFATAL_FAILURE(b.DoB(), "to be called twice");
  }
}
References EXPECT_CALL, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [64/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , NthMatchTakesNthAction)
Definition at line 894 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(1))
      .WillOnce(Return(2))
      .WillOnce(Return(3));
  EXPECT_EQ(1, b.DoB());
  EXPECT_EQ(2, b.DoB());
  EXPECT_EQ(3, b.DoB());
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [65/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , PicksLastMatchingExpectCall)
Definition at line 806 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB(_))
      .WillRepeatedly(Return(2));
  EXPECT_CALL(b, DoB(1))
      .WillRepeatedly(Return(1));
  EXPECT_EQ(1, b.DoB(1));
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [66/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ExpectCallTest , TakesRepeatedActionWhenWillListIsExhausted)
Definition at line 908 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(1))
      .WillRepeatedly(Return(2));
  EXPECT_EQ(1, b.DoB());
  EXPECT_EQ(2, b.DoB());
  EXPECT_EQ(2, b.DoB());
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [67/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (InSequenceTest , AllExpectationInScopeAreInSequence)
Definition at line 1247 of file gmock-spec-builders_test.cc.
{
  MockA a;
  {
    InSequence dummy;
    EXPECT_CALL(a, DoA(1));
    EXPECT_CALL(a, DoA(2));
  }
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    a.DoA(2);
  }, "Unexpected mock function call");
  a.DoA(1);
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [68/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (InSequenceTest , ExpectationsOutOfScopeAreNotAffected)
Definition at line 1287 of file gmock-spec-builders_test.cc.
{
  MockA a;
  {
    InSequence dummy;
    EXPECT_CALL(a, DoA(1));
    EXPECT_CALL(a, DoA(2));
  }
  EXPECT_CALL(a, DoA(3));
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    a.DoA(2);
  }, "Unexpected mock function call");
  a.DoA(3);
  a.DoA(1);
  a.DoA(2);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [69/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (InSequenceTest , NestedInSequence)
Definition at line 1264 of file gmock-spec-builders_test.cc.
{
  MockA a;
  {
    InSequence dummy;
    EXPECT_CALL(a, DoA(1));
    {
      InSequence dummy2;
      EXPECT_CALL(a, DoA(2));
      EXPECT_CALL(a, DoA(3));
    }
  }
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    a.DoA(1);
    a.DoA(3);
  }, "Unexpected mock function call");
  a.DoA(2);
  a.DoA(3);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [70/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (MockMethodTest , CanInstantiateWithIncompleteArgType)
Definition at line 123 of file gmock-spec-builders_test.cc.
{
  // Even though this mock class contains a mock method that takes
  // by-reference an argument whose type is incomplete, we can still
  // use the mock, as long as Google Mock knows how to print the
  // argument.
  MockIncomplete incomplete;
  EXPECT_CALL(incomplete, ByRefFunc(_))
      .Times(AnyNumber());
}
References EXPECT_CALL.
TEST() [71/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , CompilesWithMethodNameExpandedFromMacro)
Definition at line 205 of file gmock-spec-builders_test.cc.
{
  MockCC cc;
  ON_CALL(cc, Method());
}
References Method, and ON_CALL.
TEST() [72/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , EvaluatesFirstArgumentOnce)
Definition at line 236 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockA* pa = &a;
  ON_CALL(*pa++, DoA(_));
  EXPECT_EQ(&a + 1, pa);
}
References EXPECT_EQ, and ON_CALL.
TEST() [73/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , EvaluatesSecondArgumentOnce)
Definition at line 244 of file gmock-spec-builders_test.cc.
{
  MockA a;
  int n = 0;
  ON_CALL(a, DoA(n++));
  EXPECT_EQ(1, n);
}
References EXPECT_EQ, and ON_CALL.
TEST() [74/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , WillByDefaultCanAppearAtMostOnce)
Definition at line 284 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    ON_CALL(a, DoA(5))
        .WillByDefault(Return())
        .WillByDefault(Return());
  }, ".WillByDefault() must appear exactly once in an ON_CALL()");
}
References EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [75/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , WillByDefaultIsMandatory)
Definition at line 275 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_DEATH_IF_SUPPORTED({
    ON_CALL(a, DoA(5));
    a.DoA(5);
  }, "");
}
References EXPECT_DEATH_IF_SUPPORTED, and ON_CALL.
TEST() [76/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , WithCanAppearAtMostOnce)
Definition at line 264 of file gmock-spec-builders_test.cc.
{
  MockA a;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    ON_CALL(a, ReturnResult(_))
        .With(_)
        .With(_)
        .WillByDefault(Return(Result()));
  }, ".With() cannot appear more than once in an ON_CALL()");
}
References EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [77/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , WithIsOptional)
Definition at line 254 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ON_CALL(a, DoA(5))
      .WillByDefault(Return());
  ON_CALL(a, DoA(_))
      .With(_)
      .WillByDefault(Return());
}
References ON_CALL.
TEST() [78/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallSyntaxTest , WorksWithMethodNameExpandedFromMacro)
Definition at line 212 of file gmock-spec-builders_test.cc.
{
  MockCC cc;
  ON_CALL(cc, Method()).WillByDefault(Return(42));
  EXPECT_EQ(42, cc.Method());
}
References EXPECT_EQ, Method, and ON_CALL.
TEST() [79/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallTest , PicksLastMatchingOnCall)
Definition at line 777 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB(_))
      .WillByDefault(Return(3));
  ON_CALL(b, DoB(2))
      .WillByDefault(Return(2));
  ON_CALL(b, DoB(1))
      .WillByDefault(Return(1));
  EXPECT_CALL(b, DoB(_));
  EXPECT_EQ(2, b.DoB(2));
}
References EXPECT_CALL, EXPECT_EQ, and ON_CALL.
TEST() [80/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallTest , TakesBuiltInDefaultActionWhenNoOnCall)
Definition at line 758 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB());
  EXPECT_EQ(0, b.DoB());
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [81/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (OnCallTest , TakesBuiltInDefaultActionWhenNoOnCallMatches)
Definition at line 767 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB(1))
      .WillByDefault(Return(1));
  EXPECT_CALL(b, DoB(_));
  EXPECT_EQ(0, b.DoB(2));
}
References EXPECT_CALL, EXPECT_EQ, and ON_CALL.
TEST() [82/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ParameterlessExpectationsTest , CanSetExpectationsForConstMethods)
Definition at line 2721 of file gmock-spec-builders_test.cc.
{
  MockWithConstMethods mock;
  ON_CALL(mock, Foo).WillByDefault(Return(7));
  ON_CALL(mock, Bar).WillByDefault(Return(33));
  EXPECT_THAT(mock.Foo(17), 7);
  EXPECT_THAT(mock.Bar(27, "purple"), 33);
}
References EXPECT_THAT, and ON_CALL.
TEST() [83/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ParameterlessExpectationsTest , CanSetExpectationsForConstOverloadedMethods)
Definition at line 2736 of file gmock-spec-builders_test.cc.
{
  MockConstOverload mock;
  ON_CALL(mock, Overloaded(_)).WillByDefault(Return(7));
  ON_CALL(mock, Overloaded(5)).WillByDefault(Return(9));
  ON_CALL(Const(mock), Overloaded(5)).WillByDefault(Return(11));
  ON_CALL(Const(mock), Overloaded(7)).WillByDefault(Return(13));
  EXPECT_THAT(mock.Overloaded(1), 7);
  EXPECT_THAT(mock.Overloaded(5), 9);
  EXPECT_THAT(mock.Overloaded(7), 7);
  const MockConstOverload& const_mock = mock;
  EXPECT_THAT(const_mock.Overloaded(1), 0);
  EXPECT_THAT(const_mock.Overloaded(5), 11);
  EXPECT_THAT(const_mock.Overloaded(7), 13);
}
References EXPECT_THAT, and ON_CALL.
TEST() [84/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ParameterlessExpectationsTest , CanSetExpectationsForOverloadedMethods)
Definition at line 2705 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB()).WillByDefault(Return(9));
  ON_CALL(b, DoB(5)).WillByDefault(Return(11));
  EXPECT_THAT(b.DoB(), 9);
  EXPECT_THAT(b.DoB(1), 0);  // default value
  EXPECT_THAT(b.DoB(5), 11);
}
References EXPECT_THAT, and ON_CALL.
TEST() [85/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (ParameterlessExpectationsTest , CanSetExpectationsWithoutMatchers)
Definition at line 2685 of file gmock-spec-builders_test.cc.
{
  MockA a;
  int do_a_arg0 = 0;
  ON_CALL(a, DoA).WillByDefault(SaveArg<0>(&do_a_arg0));
  int do_a_47_arg0 = 0;
  ON_CALL(a, DoA(47)).WillByDefault(SaveArg<0>(&do_a_47_arg0));
  a.DoA(17);
  EXPECT_THAT(do_a_arg0, 17);
  EXPECT_THAT(do_a_47_arg0, 0);
  a.DoA(47);
  EXPECT_THAT(do_a_arg0, 17);
  EXPECT_THAT(do_a_47_arg0, 47);
  ON_CALL(a, Binary).WillByDefault(Return(true));
  ON_CALL(a, Binary(_, 14)).WillByDefault(Return(false));
  EXPECT_THAT(a.Binary(14, 17), true);
  EXPECT_THAT(a.Binary(17, 14), false);
}
References EXPECT_THAT, and ON_CALL.
TEST() [86/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (SequenceTest , AnyOrderIsOkByDefault)
Definition at line 1307 of file gmock-spec-builders_test.cc.
{
  {
    MockA a;
    MockB b;
    EXPECT_CALL(a, DoA(1));
    EXPECT_CALL(b, DoB())
        .Times(AnyNumber());
    a.DoA(1);
    b.DoB();
  }
  {  // NOLINT
    MockA a;
    MockB b;
    EXPECT_CALL(a, DoA(1));
    EXPECT_CALL(b, DoB())
        .Times(AnyNumber());
    b.DoB();
    a.DoA(1);
  }
}
References EXPECT_CALL.
TEST() [87/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (SequenceTest , CallsMustBeInStrictOrderWhenSaidSo1)
Definition at line 1335 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ON_CALL(a, ReturnResult(_))
      .WillByDefault(Return(Result()));
  Sequence s;
  EXPECT_CALL(a, ReturnResult(1))
      .InSequence(s);
  EXPECT_CALL(a, ReturnResult(2))
      .InSequence(s);
  EXPECT_CALL(a, ReturnResult(3))
      .InSequence(s);
  a.ReturnResult(1);
  // May only be called after a.ReturnResult(2).
  EXPECT_NONFATAL_FAILURE(a.ReturnResult(3), "Unexpected mock function call");
  a.ReturnResult(2);
  a.ReturnResult(3);
}
References EXPECT_CALL, EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [88/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (SequenceTest , CallsMustBeInStrictOrderWhenSaidSo2)
Definition at line 1359 of file gmock-spec-builders_test.cc.
{
  MockA a;
  ON_CALL(a, ReturnResult(_))
      .WillByDefault(Return(Result()));
  Sequence s;
  EXPECT_CALL(a, ReturnResult(1))
      .InSequence(s);
  EXPECT_CALL(a, ReturnResult(2))
      .InSequence(s);
  // May only be called after a.ReturnResult(1).
  EXPECT_NONFATAL_FAILURE(a.ReturnResult(2), "Unexpected mock function call");
  a.ReturnResult(1);
  a.ReturnResult(2);
}
References EXPECT_CALL, EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [89/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (SequenceTest , Retirement)
Definition at line 1447 of file gmock-spec-builders_test.cc.
{
  MockA a;
  Sequence s;
  EXPECT_CALL(a, DoA(1))
      .InSequence(s);
  EXPECT_CALL(a, DoA(_))
      .InSequence(s)
      .RetiresOnSaturation();
  EXPECT_CALL(a, DoA(1))
      .InSequence(s);
  a.DoA(1);
  a.DoA(2);
  a.DoA(1);
}
References EXPECT_CALL.
TEST() [90/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (SynchronizationTest , CanCallMockMethodInAction)
Definition at line 2666 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockC c;
  ON_CALL(a, DoA(_))
      .WillByDefault(IgnoreResult(InvokeWithoutArgs(&c,
                                                    &MockC::NonVoidMethod)));
  EXPECT_CALL(a, DoA(1));
  EXPECT_CALL(a, DoA(1))
      .WillOnce(Invoke(&a, &MockA::DoA))
      .RetiresOnSaturation();
  EXPECT_CALL(c, NonVoidMethod());
  a.DoA(1);
  // This will match the second EXPECT_CALL() and trigger another a.DoA(1),
  // which will in turn match the first EXPECT_CALL() and trigger a call to
  // c.NonVoidMethod() that was specified by the ON_CALL() since the first
  // EXPECT_CALL() did not specify an action.
}
References EXPECT_CALL, and ON_CALL.
TEST() [91/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UndefinedReturnValueTest , ReturnValueIsMandatoryWhenNotDefaultConstructible)
Definition at line 1176 of file gmock-spec-builders_test.cc.
{
  MockA a;
  // TODO(wan@google.com): We should really verify the output message,
  // but we cannot yet due to that EXPECT_DEATH only captures stderr
  // while Google Mock logs to stdout.
#if GTEST_HAS_EXCEPTIONS
  EXPECT_ANY_THROW(a.ReturnNonDefaultConstructible());
#else
  EXPECT_DEATH_IF_SUPPORTED(a.ReturnNonDefaultConstructible(), "");
#endif
}
References EXPECT_ANY_THROW, and EXPECT_DEATH_IF_SUPPORTED.
TEST() [92/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UnexpectedCallTest , DoesDefaultAction)
Definition at line 999 of file gmock-spec-builders_test.cc.
{
  // When there is an ON_CALL() statement, the action specified by it
  // should be taken.
  MockA a;
  ON_CALL(a, Binary(_, _))
      .WillByDefault(Return(true));
  EXPECT_CALL(a, Binary(0, 0));
  a.Binary(0, 0);
  bool result = false;
  EXPECT_NONFATAL_FAILURE(result = a.Binary(1, 2),
                          "Unexpected mock function call");
  EXPECT_TRUE(result);
  // When there is no ON_CALL(), the default value for the return type
  // should be returned.
  MockB b;
  EXPECT_CALL(b, DoB(0))
      .Times(0);
  int n = -1;
  EXPECT_NONFATAL_FAILURE(n = b.DoB(1),
                          "Unexpected mock function call");
  EXPECT_EQ(0, n);
}
References EXPECT_CALL, EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_TRUE, and ON_CALL.
TEST() [93/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UnexpectedCallTest , GeneartesFailureForNonVoidFunction)
Definition at line 1074 of file gmock-spec-builders_test.cc.
{
  MockB b1;
  EXPECT_CALL(b1, DoB(1));
  b1.DoB(1);
  EXPECT_NONFATAL_FAILURE(
      b1.DoB(2),
      "Unexpected mock function call - returning default value.\n"
      "    Function call: DoB(2)\n"
      "          Returns: 0\n"
      "Google Mock tried the following 1 expectation, but it didn't match:");
  EXPECT_NONFATAL_FAILURE(
      b1.DoB(2),
      "  Expected arg #0: is equal to 1\n"
      "           Actual: 2\n"
      "         Expected: to be called once\n"
      "           Actual: called once - saturated and active");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [94/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UnexpectedCallTest , GeneratesFailureForVoidFunction)
Definition at line 1025 of file gmock-spec-builders_test.cc.
{
  // First, tests the message when there is only one EXPECT_CALL().
  MockA a1;
  EXPECT_CALL(a1, DoA(1));
  a1.DoA(1);
  // Ideally we should match the failure message against a regex, but
  // EXPECT_NONFATAL_FAILURE doesn't support that, so we test for
  // multiple sub-strings instead.
  EXPECT_NONFATAL_FAILURE(
      a1.DoA(9),
      "Unexpected mock function call - returning directly.\n"
      "    Function call: DoA(9)\n"
      "Google Mock tried the following 1 expectation, but it didn't match:");
  EXPECT_NONFATAL_FAILURE(
      a1.DoA(9),
      "  Expected arg #0: is equal to 1\n"
      "           Actual: 9\n"
      "         Expected: to be called once\n"
      "           Actual: called once - saturated and active");
  // Next, tests the message when there are more than one EXPECT_CALL().
  MockA a2;
  EXPECT_CALL(a2, DoA(1));
  EXPECT_CALL(a2, DoA(3));
  a2.DoA(1);
  EXPECT_NONFATAL_FAILURE(
      a2.DoA(2),
      "Unexpected mock function call - returning directly.\n"
      "    Function call: DoA(2)\n"
      "Google Mock tried the following 2 expectations, but none matched:");
  EXPECT_NONFATAL_FAILURE(
      a2.DoA(2),
      "tried expectation #0: EXPECT_CALL(a2, DoA(1))...\n"
      "  Expected arg #0: is equal to 1\n"
      "           Actual: 2\n"
      "         Expected: to be called once\n"
      "           Actual: called once - saturated and active");
  EXPECT_NONFATAL_FAILURE(
      a2.DoA(2),
      "tried expectation #1: EXPECT_CALL(a2, DoA(3))...\n"
      "  Expected arg #0: is equal to 3\n"
      "           Actual: 2\n"
      "         Expected: to be called once\n"
      "           Actual: never called - unsatisfied and active");
  a2.DoA(3);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [95/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UnexpectedCallTest , RetiredExpectation)
Definition at line 1094 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB(1))
      .RetiresOnSaturation();
  b.DoB(1);
  EXPECT_NONFATAL_FAILURE(
      b.DoB(1),
      "         Expected: the expectation is active\n"
      "           Actual: it is retired");
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [96/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UnexpectedCallTest , UnmatchedArguments)
Definition at line 1108 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB(1));
  EXPECT_NONFATAL_FAILURE(
      b.DoB(2),
      "  Expected arg #0: is equal to 1\n"
      "           Actual: 2\n");
  b.DoB(1);
}
References EXPECT_CALL, and EXPECT_NONFATAL_FAILURE.
TEST() [97/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UnexpectedCallTest , UnsatisifiedPrerequisites)
Definition at line 1121 of file gmock-spec-builders_test.cc.
{
  Sequence s1, s2;
  MockB b;
  EXPECT_CALL(b, DoB(1))
      .InSequence(s1);
  EXPECT_CALL(b, DoB(2))
      .Times(AnyNumber())
      .InSequence(s1);
  EXPECT_CALL(b, DoB(3))
      .InSequence(s2);
  EXPECT_CALL(b, DoB(4))
      .InSequence(s1, s2);
  ::testing::TestPartResultArray failures;
  {
    ::testing::ScopedFakeTestPartResultReporter reporter(&failures);
    b.DoB(4);
    // Now 'failures' contains the Google Test failures generated by
    // the above statement.
  }
  // There should be one non-fatal failure.
  ASSERT_EQ(1, failures.size());
  const ::testing::TestPartResult& r = failures.GetTestPartResult(0);
  EXPECT_EQ(::testing::TestPartResult::kNonFatalFailure, r.type());
  // Verifies that the failure message contains the two unsatisfied
  // pre-requisites but not the satisfied one.
#if GTEST_USES_PCRE
  EXPECT_THAT(r.message(), ContainsRegex(
      // PCRE has trouble using (.|\n) to match any character, but
      // supports the (?s) prefix for using . to match any character.
      "(?s)the following immediate pre-requisites are not satisfied:\n"
      ".*: pre-requisite #0\n"
      ".*: pre-requisite #1"));
#elif GTEST_USES_POSIX_RE
  EXPECT_THAT(r.message(), ContainsRegex(
      // POSIX RE doesn't understand the (?s) prefix, but has no trouble
      // with (.|\n).
      "the following immediate pre-requisites are not satisfied:\n"
      "(.|\n)*: pre-requisite #0\n"
      "(.|\n)*: pre-requisite #1"));
#else
  // We can only use Google Test's own simple regex.
  EXPECT_THAT(r.message(), ContainsRegex(
      "the following immediate pre-requisites are not satisfied:"));
  EXPECT_THAT(r.message(), ContainsRegex(": pre-requisite #0"));
  EXPECT_THAT(r.message(), ContainsRegex(": pre-requisite #1"));
#endif  // GTEST_USES_PCRE
  b.DoB(1);
  b.DoB(3);
  b.DoB(4);
}
References ASSERT_EQ, EXPECT_CALL, EXPECT_EQ, EXPECT_THAT, testing::TestPartResultArray::GetTestPartResult(), testing::TestPartResult::kNonFatalFailure, and testing::TestPartResultArray::size().
TEST() [98/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (UninterestingCallTest , DoesDefaultAction)
Definition at line 984 of file gmock-spec-builders_test.cc.
{
  // When there is an ON_CALL() statement, the action specified by it
  // should be taken.
  MockA a;
  ON_CALL(a, Binary(_, _))
      .WillByDefault(Return(true));
  EXPECT_TRUE(a.Binary(1, 2));
  // When there is no ON_CALL(), the default value for the return type
  // should be returned.
  MockB b;
  EXPECT_EQ(0, b.DoB());
}
References EXPECT_EQ, EXPECT_TRUE, and ON_CALL.
TEST() [99/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearExpectationsTest , AllMethodsHaveExpectations)
Definition at line 2377 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(1));
  EXPECT_CALL(b, DoB(_))
      .WillOnce(Return(2));
  b.DoB();
  b.DoB(1);
  ASSERT_TRUE(Mock::VerifyAndClearExpectations(&b));
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_TRUE, EXPECT_CALL, and EXPECT_EQ.
TEST() [100/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearExpectationsTest , AMethodHasManyExpectations)
Definition at line 2395 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB(0))
      .WillOnce(Return(1));
  EXPECT_CALL(b, DoB(_))
      .WillOnce(Return(2));
  b.DoB(1);
  bool result = true;
  EXPECT_NONFATAL_FAILURE(result = Mock::VerifyAndClearExpectations(&b),
                          "Actual: never called");
  ASSERT_FALSE(result);
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_FALSE, EXPECT_CALL, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [101/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearExpectationsTest , CanCallManyTimes)
Definition at line 2415 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB());
  b.DoB();
  Mock::VerifyAndClearExpectations(&b);
  EXPECT_CALL(b, DoB(_))
      .WillOnce(Return(1));
  b.DoB(1);
  Mock::VerifyAndClearExpectations(&b);
  Mock::VerifyAndClearExpectations(&b);
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References EXPECT_CALL, and EXPECT_EQ.
TEST() [102/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearExpectationsTest , NoMethodHasExpectations)
Definition at line 2331 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ASSERT_TRUE(Mock::VerifyAndClearExpectations(&b));
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_TRUE, and EXPECT_EQ.
TEST() [103/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearExpectationsTest , SomeMethodsHaveExpectationsAndFail)
Definition at line 2360 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(1));
  bool result = true;
  EXPECT_NONFATAL_FAILURE(result = Mock::VerifyAndClearExpectations(&b),
                          "Actual: never called");
  ASSERT_FALSE(result);
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_FALSE, EXPECT_CALL, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [104/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearExpectationsTest , SomeMethodsHaveExpectationsAndSucceed)
Definition at line 2344 of file gmock-spec-builders_test.cc.
{
  MockB b;
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(1));
  b.DoB();
  ASSERT_TRUE(Mock::VerifyAndClearExpectations(&b));
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_TRUE, EXPECT_CALL, and EXPECT_EQ.
TEST() [105/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , AllMethodsHaveDefaultActions)
Definition at line 2457 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB())
      .WillByDefault(Return(1));
  ON_CALL(b, DoB(_))
      .WillByDefault(Return(2));
  Mock::VerifyAndClear(&b);
  // Verifies that the default action of int DoB() was removed.
  EXPECT_EQ(0, b.DoB());
  // Verifies that the default action of int DoB(int) was removed.
  EXPECT_EQ(0, b.DoB(0));
}
References EXPECT_EQ, and ON_CALL.
TEST() [106/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , AMethodHasManyDefaultActions)
Definition at line 2475 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB(0))
      .WillByDefault(Return(1));
  ON_CALL(b, DoB(_))
      .WillByDefault(Return(2));
  Mock::VerifyAndClear(&b);
  // Verifies that the default actions (there are two) of int DoB(int)
  // were removed.
  EXPECT_EQ(0, b.DoB(0));
  EXPECT_EQ(0, b.DoB(1));
}
References EXPECT_EQ, and ON_CALL.
TEST() [107/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , CanCallManyTimes)
Definition at line 2492 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB())
      .WillByDefault(Return(1));
  Mock::VerifyAndClear(&b);
  Mock::VerifyAndClear(&b);
  ON_CALL(b, DoB(_))
      .WillByDefault(Return(1));
  Mock::VerifyAndClear(&b);
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References EXPECT_EQ, and ON_CALL.
TEST() [108/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , CanSetDefaultActionsAndExpectationsAfterwards)
Definition at line 2568 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB())
      .WillByDefault(Return(1));
  EXPECT_CALL(b, DoB(_))
      .WillOnce(Return(2));
  b.DoB(1);
  Mock::VerifyAndClear(&b);
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(3));
  ON_CALL(b, DoB(_))
      .WillByDefault(Return(4));
  EXPECT_EQ(3, b.DoB());
  EXPECT_EQ(4, b.DoB(1));
}
References EXPECT_CALL, EXPECT_EQ, and ON_CALL.
TEST() [109/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , Const)
Definition at line 2547 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(Const(b), DoB())
      .WillByDefault(Return(1));
  EXPECT_CALL(Const(b), DoB())
      .WillOnce(DoDefault())
      .WillOnce(Return(2));
  b.DoB();
  b.DoB();
  ASSERT_TRUE(Mock::VerifyAndClear(&b));
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_TRUE, EXPECT_CALL, EXPECT_EQ, and ON_CALL.
TEST() [110/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , DestroyingChainedMocksDoesNotDeadlockThroughDefaultAction)
Definition at line 2641 of file gmock-spec-builders_test.cc.
{
  linked_ptr<MockA> a(new MockA);
  ReferenceHoldingMock test_mock;
  // ON_CALL stores a reference to a inside test_mock.
  ON_CALL(test_mock, AcceptReference(_))
      .WillByDefault(SetArgPointee<0>(a));
  // Throw away the reference to the mock that we have in a. After this, the
  // only reference to it is stored by test_mock.
  a.reset();
  // When test_mock goes out of scope, it destroys the last remaining reference
  // to the mock object originally pointed to by a. This will cause the MockA
  // destructor to be called from inside the ReferenceHoldingMock destructor.
  // The state of all mocks is protected by a single global lock, but there
  // should be no deadlock.
}
References ON_CALL.
TEST() [111/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , DestroyingChainedMocksDoesNotDeadlockThroughExpectations)
Definition at line 2621 of file gmock-spec-builders_test.cc.
{
  linked_ptr<MockA> a(new MockA);
  ReferenceHoldingMock test_mock;
  // EXPECT_CALL stores a reference to a inside test_mock.
  EXPECT_CALL(test_mock, AcceptReference(_))
      .WillRepeatedly(SetArgPointee<0>(a));
  // Throw away the reference to the mock that we have in a. After this, the
  // only reference to it is stored by test_mock.
  a.reset();
  // When test_mock goes out of scope, it destroys the last remaining reference
  // to the mock object originally pointed to by a. This will cause the MockA
  // destructor to be called from inside the ReferenceHoldingMock destructor.
  // The state of all mocks is protected by a single global lock, but there
  // should be no deadlock.
}
References EXPECT_CALL.
TEST() [112/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , DoesNotAffectOtherMockObjects)
Definition at line 2589 of file gmock-spec-builders_test.cc.
{
  MockA a;
  MockB b1;
  MockB b2;
  ON_CALL(a, Binary(_, _))
      .WillByDefault(Return(true));
  EXPECT_CALL(a, Binary(_, _))
      .WillOnce(DoDefault())
      .WillOnce(Return(false));
  ON_CALL(b1, DoB())
      .WillByDefault(Return(1));
  EXPECT_CALL(b1, DoB(_))
      .WillOnce(Return(2));
  ON_CALL(b2, DoB())
      .WillByDefault(Return(3));
  EXPECT_CALL(b2, DoB(_));
  b2.DoB(0);
  Mock::VerifyAndClear(&b2);
  // Verifies that the default actions and expectations of a and b1
  // are still in effect.
  EXPECT_TRUE(a.Binary(0, 0));
  EXPECT_FALSE(a.Binary(0, 0));
  EXPECT_EQ(1, b1.DoB());
  EXPECT_EQ(2, b1.DoB(0));
}
References EXPECT_CALL, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, and ON_CALL.
TEST() [113/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , Failure)
Definition at line 2526 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB(_))
      .WillByDefault(Return(1));
  EXPECT_CALL(b, DoB())
      .WillOnce(Return(2));
  b.DoB(1);
  bool result = true;
  EXPECT_NONFATAL_FAILURE(result = Mock::VerifyAndClear(&b),
                          "Actual: never called");
  ASSERT_FALSE(result);
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_FALSE, EXPECT_CALL, EXPECT_EQ, EXPECT_NONFATAL_FAILURE, and ON_CALL.
TEST() [114/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , NoMethodHasDefaultActions)
Definition at line 2435 of file gmock-spec-builders_test.cc.
{
  MockB b;
  // If this crashes or generates a failure, the test will catch it.
  Mock::VerifyAndClear(&b);
  EXPECT_EQ(0, b.DoB());
}
References EXPECT_EQ.
TEST() [115/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , SomeMethodsHaveDefaultActions)
Definition at line 2444 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB())
      .WillByDefault(Return(1));
  Mock::VerifyAndClear(&b);
  // Verifies that the default action of int DoB() was removed.
  EXPECT_EQ(0, b.DoB());
}
References EXPECT_EQ, and ON_CALL.
TEST() [116/116]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST (VerifyAndClearTest , Success)
Definition at line 2508 of file gmock-spec-builders_test.cc.
{
  MockB b;
  ON_CALL(b, DoB())
      .WillByDefault(Return(1));
  EXPECT_CALL(b, DoB(1))
      .WillOnce(Return(2));
  b.DoB();
  b.DoB(1);
  ASSERT_TRUE(Mock::VerifyAndClear(&b));
  // There should be no expectations on the methods now, so we can
  // freely call them.
  EXPECT_EQ(0, b.DoB());
  EXPECT_EQ(0, b.DoB(1));
}
References ASSERT_TRUE, EXPECT_CALL, EXPECT_EQ, and ON_CALL.
TEST_F() [1/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (GMockLogTest , DoesNotPrintGoodCallInternallyIfVerbosityIsError)
Definition at line 2275 of file gmock-spec-builders_test.cc.
{
  GMOCK_FLAG(verbose) = kErrorVerbosity;
  EXPECT_CALL(helper_, Foo(_))
      .WillOnce(Return(PrintMeNot()));
  helper_.Foo(PrintMeNot());  // This is an expected call.
}
References EXPECT_CALL, and GMOCK_FLAG.
TEST_F() [2/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (GMockLogTest , DoesNotPrintGoodCallInternallyIfVerbosityIsWarning)
Definition at line 2268 of file gmock-spec-builders_test.cc.
{
  GMOCK_FLAG(verbose) = kWarningVerbosity;
  EXPECT_CALL(helper_, Foo(_))
      .WillOnce(Return(PrintMeNot()));
  helper_.Foo(PrintMeNot());  // This is an expected call.
}
References EXPECT_CALL, and GMOCK_FLAG.
TEST_F() [3/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (GMockLogTest , DoesNotPrintWarningInternallyIfVerbosityIsError)
Definition at line 2282 of file gmock-spec-builders_test.cc.
{
  GMOCK_FLAG(verbose) = kErrorVerbosity;
  ON_CALL(helper_, Foo(_))
      .WillByDefault(Return(PrintMeNot()));
  helper_.Foo(PrintMeNot());  // This should generate a warning.
}
References GMOCK_FLAG, and ON_CALL.
TEST_F() [4/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (PartialOrderTest , CallsMustConformToSpecifiedDag1)
Definition at line 1406 of file gmock-spec-builders_test.cc.
{
  a_.ReturnResult(1);
  b_.DoB();
  // May only be called after the second DoB().
  EXPECT_NONFATAL_FAILURE(a_.ReturnResult(2), "Unexpected mock function call");
  b_.DoB();
  a_.ReturnResult(3);
}
References EXPECT_NONFATAL_FAILURE.
TEST_F() [5/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (PartialOrderTest , CallsMustConformToSpecifiedDag2)
Definition at line 1417 of file gmock-spec-builders_test.cc.
{
  // May only be called after ReturnResult(1).
  EXPECT_NONFATAL_FAILURE(a_.ReturnResult(2), "Unexpected mock function call");
  a_.ReturnResult(1);
  b_.DoB();
  b_.DoB();
  a_.ReturnResult(3);
}
References EXPECT_NONFATAL_FAILURE.
TEST_F() [6/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (PartialOrderTest , CallsMustConformToSpecifiedDag3)
Definition at line 1427 of file gmock-spec-builders_test.cc.
{
  // May only be called last.
  EXPECT_NONFATAL_FAILURE(a_.ReturnResult(3), "Unexpected mock function call");
  a_.ReturnResult(1);
  b_.DoB();
  b_.DoB();
  a_.ReturnResult(3);
}
References EXPECT_NONFATAL_FAILURE.
TEST_F() [7/7]
anonymous_namespace{gmock-spec-builders_test.cc}::TEST_F (PartialOrderTest , CallsMustConformToSpecifiedDag4)
Definition at line 1437 of file gmock-spec-builders_test.cc.
{
  a_.ReturnResult(1);
  b_.DoB();
  b_.DoB();
  a_.ReturnResult(3);
  // May only be called before ReturnResult(3).
  EXPECT_NONFATAL_FAILURE(a_.ReturnResult(2), "Unexpected mock function call");
}
References EXPECT_NONFATAL_FAILURE.