wiNpoS: anonymous_namespace{gmock_leak_test_.cc} Namespace Reference
anonymous_namespace{gmock_leak_test_.cc} Namespace Reference
Classes
class FooInterface
class MockFoo
Functions
TEST (LeakTest, LeakedMockWithExpectCallCausesFailureWhenLeakCheckingIsEnabled)
TEST (LeakTest, LeakedMockWithOnCallCausesFailureWhenLeakCheckingIsEnabled)
TEST (LeakTest, CatchesMultipleLeakedMockObjects)
Function Documentation
TEST() [1/3]
anonymous_namespace{gmock_leak_test_.cc}::TEST (LeakTest , CatchesMultipleLeakedMockObjects)
Definition at line 84 of file gmock_leak_test_.cc.
{
  MockFoo* foo1 = new MockFoo;
  MockFoo* foo2 = new MockFoo;
  ON_CALL(*foo1, DoThis()).WillByDefault(Return());
  EXPECT_CALL(*foo2, DoThis());
  foo2->DoThis();
  // In order to test the leak detector, we deliberately leak foo1 and
  // foo2.
  // Makes sure Google Mock's leak detector can change the exit code
  // to 1 even when the code is already exiting with 0.
  exit(0);
}
References anonymous_namespace{gmock_leak_test_.cc}::FooInterface::DoThis(), EXPECT_CALL, and ON_CALL.
TEST() [2/3]
anonymous_namespace{gmock_leak_test_.cc}::TEST (LeakTest , LeakedMockWithExpectCallCausesFailureWhenLeakCheckingIsEnabled)
Definition at line 59 of file gmock_leak_test_.cc.
{
  MockFoo* foo = new MockFoo;
  EXPECT_CALL(*foo, DoThis());
  foo->DoThis();
  // In order to test the leak detector, we deliberately leak foo.
  // Makes sure Google Mock's leak detector can change the exit code
  // to 1 even when the code is already exiting with 0.
  exit(0);
}
References anonymous_namespace{gmock_leak_test_.cc}::FooInterface::DoThis(), and EXPECT_CALL.
TEST() [3/3]
anonymous_namespace{gmock_leak_test_.cc}::TEST (LeakTest , LeakedMockWithOnCallCausesFailureWhenLeakCheckingIsEnabled)
Definition at line 72 of file gmock_leak_test_.cc.
{
  MockFoo* foo = new MockFoo;
  ON_CALL(*foo, DoThis()).WillByDefault(Return());
  // In order to test the leak detector, we deliberately leak foo.
  // Makes sure Google Mock's leak detector can change the exit code
  // to 1 even when the code is already exiting with 0.
  exit(0);
}
References anonymous_namespace{gmock_leak_test_.cc}::FooInterface::DoThis(), and ON_CALL.