wiNpoS: anonymous_namespace{gtest-test-part_test.cc} Namespace Reference
anonymous_namespace{gtest-test-part_test.cc} Namespace Reference
Classes
class TestPartResultArrayTest
class TestPartResultTest
Typedefs
typedef TestPartResultArrayTest TestPartResultArrayDeathTest
Functions
TEST_F (TestPartResultTest, ConstructorWorks)
TEST_F (TestPartResultTest, ResultAccessorsWork)
TEST_F (TestPartResultTest, type)
TEST_F (TestPartResultTest, file_name)
TEST_F (TestPartResultTest, line_number)
TEST_F (TestPartResultTest, message)
TEST_F (TestPartResultTest, Passed)
TEST_F (TestPartResultTest, Failed)
TEST_F (TestPartResultTest, FatallyFailed)
TEST_F (TestPartResultTest, NonfatallyFailed)
TEST_F (TestPartResultArrayTest, InitialSizeIsZero)
TEST_F (TestPartResultArrayTest, ContainsGivenResultAfterAppend)
TEST_F (TestPartResultArrayTest, ContainsGivenResultsAfterTwoAppends)
TEST_F (TestPartResultArrayDeathTest, DiesWhenIndexIsOutOfBound)
Typedef Documentation
TestPartResultArrayDeathTest
typedef TestPartResultArrayTest anonymous_namespace{gtest-test-part_test.cc}::TestPartResultArrayDeathTest
Definition at line 194 of file gtest-test-part_test.cc.
Function Documentation
TEST_F() [1/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultArrayDeathTest , DiesWhenIndexIsOutOfBound)
Definition at line 198 of file gtest-test-part_test.cc.
{
  TestPartResultArray results;
  results.Append(r1_);
  EXPECT_DEATH_IF_SUPPORTED(results.GetTestPartResult(-1), "");
  EXPECT_DEATH_IF_SUPPORTED(results.GetTestPartResult(1), "");
}
References testing::TestPartResultArray::Append(), EXPECT_DEATH_IF_SUPPORTED, and testing::TestPartResultArray::GetTestPartResult().
TEST_F() [2/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultArrayTest , ContainsGivenResultAfterAppend)
Definition at line 176 of file gtest-test-part_test.cc.
{
  TestPartResultArray results;
  results.Append(r1_);
  EXPECT_EQ(1, results.size());
  EXPECT_STREQ("Failure 1", results.GetTestPartResult(0).message());
}
References testing::TestPartResultArray::Append(), EXPECT_EQ, EXPECT_STREQ, testing::TestPartResultArray::GetTestPartResult(), testing::TestPartResult::message(), and testing::TestPartResultArray::size().
TEST_F() [3/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultArrayTest , ContainsGivenResultsAfterTwoAppends)
Definition at line 185 of file gtest-test-part_test.cc.
{
  TestPartResultArray results;
  results.Append(r1_);
  results.Append(r2_);
  EXPECT_EQ(2, results.size());
  EXPECT_STREQ("Failure 1", results.GetTestPartResult(0).message());
  EXPECT_STREQ("Failure 2", results.GetTestPartResult(1).message());
}
References testing::TestPartResultArray::Append(), EXPECT_EQ, EXPECT_STREQ, testing::TestPartResultArray::GetTestPartResult(), testing::TestPartResult::message(), and testing::TestPartResultArray::size().
TEST_F() [4/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultArrayTest , InitialSizeIsZero)
Definition at line 169 of file gtest-test-part_test.cc.
{
  TestPartResultArray results;
  EXPECT_EQ(0, results.size());
}
References EXPECT_EQ, and testing::TestPartResultArray::size().
TEST_F() [5/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , ConstructorWorks)
Definition at line 58 of file gtest-test-part_test.cc.
{
  Message message;
  message << "something is terribly wrong";
  message << static_cast<const char*>(testing::internal::kStackTraceMarker);
  message << "some unimportant stack trace";
  const TestPartResult result(TestPartResult::kNonFatalFailure,
                              "some_file.cc",
                              42,
                              message.GetString().c_str());
  EXPECT_EQ(TestPartResult::kNonFatalFailure, result.type());
  EXPECT_STREQ("some_file.cc", result.file_name());
  EXPECT_EQ(42, result.line_number());
  EXPECT_STREQ(message.GetString().c_str(), result.message());
  EXPECT_STREQ("something is terribly wrong", result.summary());
}
References EXPECT_EQ, EXPECT_STREQ, testing::TestPartResult::file_name(), testing::TestPartResult::kNonFatalFailure, testing::internal::kStackTraceMarker, testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestPartResult::summary(), and testing::TestPartResult::type().
TEST_F() [6/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , Failed)
Definition at line 137 of file gtest-test-part_test.cc.
{
  EXPECT_FALSE(r1_.failed());
  EXPECT_TRUE(r2_.failed());
  EXPECT_TRUE(r3_.failed());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [7/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , FatallyFailed)
Definition at line 144 of file gtest-test-part_test.cc.
{
  EXPECT_FALSE(r1_.fatally_failed());
  EXPECT_FALSE(r2_.fatally_failed());
  EXPECT_TRUE(r3_.fatally_failed());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [8/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , file_name)
Definition at line 113 of file gtest-test-part_test.cc.
{
  EXPECT_STREQ("foo/bar.cc", r1_.file_name());
  EXPECT_STREQ(NULL, r3_.file_name());
}
References EXPECT_STREQ.
TEST_F() [9/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , line_number)
Definition at line 119 of file gtest-test-part_test.cc.
{
  EXPECT_EQ(10, r1_.line_number());
  EXPECT_EQ(-1, r2_.line_number());
}
References EXPECT_EQ.
TEST_F() [10/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , message)
Definition at line 125 of file gtest-test-part_test.cc.
{
  EXPECT_STREQ("Success!", r1_.message());
}
References EXPECT_STREQ.
TEST_F() [11/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , NonfatallyFailed)
Definition at line 151 of file gtest-test-part_test.cc.
{
  EXPECT_FALSE(r1_.nonfatally_failed());
  EXPECT_TRUE(r2_.nonfatally_failed());
  EXPECT_FALSE(r3_.nonfatally_failed());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [12/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , Passed)
Definition at line 130 of file gtest-test-part_test.cc.
{
  EXPECT_TRUE(r1_.passed());
  EXPECT_FALSE(r2_.passed());
  EXPECT_FALSE(r3_.passed());
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [13/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , ResultAccessorsWork)
Definition at line 76 of file gtest-test-part_test.cc.
{
  const TestPartResult success(TestPartResult::kSuccess,
                               "file.cc",
                               42,
                               "message");
  EXPECT_TRUE(success.passed());
  EXPECT_FALSE(success.failed());
  EXPECT_FALSE(success.nonfatally_failed());
  EXPECT_FALSE(success.fatally_failed());
  const TestPartResult nonfatal_failure(TestPartResult::kNonFatalFailure,
                                        "file.cc",
                                        42,
                                        "message");
  EXPECT_FALSE(nonfatal_failure.passed());
  EXPECT_TRUE(nonfatal_failure.failed());
  EXPECT_TRUE(nonfatal_failure.nonfatally_failed());
  EXPECT_FALSE(nonfatal_failure.fatally_failed());
  const TestPartResult fatal_failure(TestPartResult::kFatalFailure,
                                     "file.cc",
                                     42,
                                     "message");
  EXPECT_FALSE(fatal_failure.passed());
  EXPECT_TRUE(fatal_failure.failed());
  EXPECT_FALSE(fatal_failure.nonfatally_failed());
  EXPECT_TRUE(fatal_failure.fatally_failed());
}
References EXPECT_FALSE, EXPECT_TRUE, testing::TestPartResult::failed(), testing::TestPartResult::fatally_failed(), testing::TestPartResult::kFatalFailure, testing::TestPartResult::kNonFatalFailure, testing::TestPartResult::kSuccess, testing::TestPartResult::nonfatally_failed(), and testing::TestPartResult::passed().
TEST_F() [14/14]
anonymous_namespace{gtest-test-part_test.cc}::TEST_F (TestPartResultTest , type)
Definition at line 106 of file gtest-test-part_test.cc.
{
  EXPECT_EQ(TestPartResult::kSuccess, r1_.type());
  EXPECT_EQ(TestPartResult::kNonFatalFailure, r2_.type());
  EXPECT_EQ(TestPartResult::kFatalFailure, r3_.type());
}
References EXPECT_EQ, testing::TestPartResult::kFatalFailure, testing::TestPartResult::kNonFatalFailure, and testing::TestPartResult::kSuccess.