wiNpoS: anonymous_namespace{gmock-cardinalities_test.cc} Namespace Reference
anonymous_namespace{gmock-cardinalities_test.cc} Namespace Reference
Classes
class EvenCardinality
class MockFoo
Functions
TEST (CardinalityTest, IsDefaultConstructable)
TEST (CardinalityTest, IsCopyable)
TEST (CardinalityTest, IsOverSaturatedByCallCountWorks)
TEST (CardinalityTest, CanDescribeActualCallCount)
TEST (AnyNumber, Works)
TEST (AnyNumberTest, HasCorrectBounds)
TEST (AtLeastTest, OnNegativeNumber)
TEST (AtLeastTest, OnZero)
TEST (AtLeastTest, OnPositiveNumber)
TEST (AtLeastTest, HasCorrectBounds)
TEST (AtMostTest, OnNegativeNumber)
TEST (AtMostTest, OnZero)
TEST (AtMostTest, OnPositiveNumber)
TEST (AtMostTest, HasCorrectBounds)
TEST (BetweenTest, OnNegativeStart)
TEST (BetweenTest, OnNegativeEnd)
TEST (BetweenTest, OnStartBiggerThanEnd)
TEST (BetweenTest, OnZeroStartAndZeroEnd)
TEST (BetweenTest, OnZeroStartAndNonZeroEnd)
TEST (BetweenTest, OnSameStartAndEnd)
TEST (BetweenTest, OnDifferentStartAndEnd)
TEST (BetweenTest, HasCorrectBounds)
TEST (ExactlyTest, OnNegativeNumber)
TEST (ExactlyTest, OnZero)
TEST (ExactlyTest, OnPositiveNumber)
TEST (ExactlyTest, HasCorrectBounds)
TEST (MakeCardinalityTest, ConstructsCardinalityFromInterface)
Function Documentation
TEST() [1/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AnyNumber , Works)
Definition at line 110 of file gmock-cardinalities_test.cc.
                       {
  const Cardinality c = AnyNumber();
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_FALSE(c.IsSaturatedByCallCount(0));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(1));
  EXPECT_FALSE(c.IsSaturatedByCallCount(1));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(9));
  EXPECT_FALSE(c.IsSaturatedByCallCount(9));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "called any number of times",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [2/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AnyNumberTest , HasCorrectBounds)
Definition at line 127 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AnyNumber();
  EXPECT_EQ(0, c.ConservativeLowerBound());
  EXPECT_EQ(INT_MAX, c.ConservativeUpperBound());
}
References testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), and EXPECT_EQ.
TEST() [3/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtLeastTest , HasCorrectBounds)
Definition at line 182 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtLeast(2);
  EXPECT_EQ(2, c.ConservativeLowerBound());
  EXPECT_EQ(INT_MAX, c.ConservativeUpperBound());
}
References testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), and EXPECT_EQ.
TEST() [4/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtLeastTest , OnNegativeNumber)
Definition at line 135 of file gmock-cardinalities_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    AtLeast(-1);
  }, "The invocation lower bound must be >= 0");
}
References EXPECT_NONFATAL_FAILURE.
TEST() [5/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtLeastTest , OnPositiveNumber)
Definition at line 155 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtLeast(2);
  EXPECT_FALSE(c.IsSatisfiedByCallCount(0));
  EXPECT_FALSE(c.IsSaturatedByCallCount(0));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(1));
  EXPECT_FALSE(c.IsSaturatedByCallCount(1));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(2));
  EXPECT_FALSE(c.IsSaturatedByCallCount(2));
  stringstream ss1;
  AtLeast(1).DescribeTo(&ss1);
  EXPECT_PRED_FORMAT2(IsSubstring, "at least once",
                      ss1.str());
  stringstream ss2;
  c.DescribeTo(&ss2);
  EXPECT_PRED_FORMAT2(IsSubstring, "at least twice",
                      ss2.str());
  stringstream ss3;
  AtLeast(3).DescribeTo(&ss3);
  EXPECT_PRED_FORMAT2(IsSubstring, "at least 3 times",
                      ss3.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [6/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtLeastTest , OnZero)
Definition at line 141 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtLeast(0);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_FALSE(c.IsSaturatedByCallCount(0));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(1));
  EXPECT_FALSE(c.IsSaturatedByCallCount(1));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "any number of times",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [7/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtMostTest , HasCorrectBounds)
Definition at line 237 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtMost(2);
  EXPECT_EQ(0, c.ConservativeLowerBound());
  EXPECT_EQ(2, c.ConservativeUpperBound());
}
References testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), and EXPECT_EQ.
TEST() [8/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtMostTest , OnNegativeNumber)
Definition at line 190 of file gmock-cardinalities_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    AtMost(-1);
  }, "The invocation upper bound must be >= 0");
}
References EXPECT_NONFATAL_FAILURE.
TEST() [9/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtMostTest , OnPositiveNumber)
Definition at line 210 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtMost(2);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_FALSE(c.IsSaturatedByCallCount(0));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(1));
  EXPECT_FALSE(c.IsSaturatedByCallCount(1));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(2));
  EXPECT_TRUE(c.IsSaturatedByCallCount(2));
  stringstream ss1;
  AtMost(1).DescribeTo(&ss1);
  EXPECT_PRED_FORMAT2(IsSubstring, "called at most once",
                      ss1.str());
  stringstream ss2;
  c.DescribeTo(&ss2);
  EXPECT_PRED_FORMAT2(IsSubstring, "called at most twice",
                      ss2.str());
  stringstream ss3;
  AtMost(3).DescribeTo(&ss3);
  EXPECT_PRED_FORMAT2(IsSubstring, "called at most 3 times",
                      ss3.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [10/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (AtMostTest , OnZero)
Definition at line 196 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtMost(0);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_TRUE(c.IsSaturatedByCallCount(0));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(1));
  EXPECT_TRUE(c.IsSaturatedByCallCount(1));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "never called",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [11/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , HasCorrectBounds)
Definition at line 336 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Between(3, 5);
  EXPECT_EQ(3, c.ConservativeLowerBound());
  EXPECT_EQ(5, c.ConservativeUpperBound());
}
References testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), and EXPECT_EQ.
TEST() [12/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnDifferentStartAndEnd)
Definition at line 315 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Between(3, 5);
  EXPECT_FALSE(c.IsSatisfiedByCallCount(2));
  EXPECT_FALSE(c.IsSaturatedByCallCount(2));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(3));
  EXPECT_FALSE(c.IsSaturatedByCallCount(3));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(5));
  EXPECT_TRUE(c.IsSaturatedByCallCount(5));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(6));
  EXPECT_TRUE(c.IsSaturatedByCallCount(6));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "called between 3 and 5 times",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [13/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnNegativeEnd)
Definition at line 251 of file gmock-cardinalities_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    Between(1, -2);
  }, "The invocation upper bound must be >= 0, but is actually -2");
}
References EXPECT_NONFATAL_FAILURE.
TEST() [14/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnNegativeStart)
Definition at line 245 of file gmock-cardinalities_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    Between(-1, 2);
  }, "The invocation lower bound must be >= 0, but is actually -1");
}
References EXPECT_NONFATAL_FAILURE.
TEST() [15/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnSameStartAndEnd)
Definition at line 297 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Between(3, 3);
  EXPECT_FALSE(c.IsSatisfiedByCallCount(2));
  EXPECT_FALSE(c.IsSaturatedByCallCount(2));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(3));
  EXPECT_TRUE(c.IsSaturatedByCallCount(3));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(4));
  EXPECT_TRUE(c.IsSaturatedByCallCount(4));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "called 3 times",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [16/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnStartBiggerThanEnd)
Definition at line 257 of file gmock-cardinalities_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    Between(2, 1);
  }, "The invocation upper bound (1) must be >= "
     "the invocation lower bound (2)");
}
References EXPECT_NONFATAL_FAILURE.
TEST() [17/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnZeroStartAndNonZeroEnd)
Definition at line 279 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Between(0, 2);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_FALSE(c.IsSaturatedByCallCount(0));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(2));
  EXPECT_TRUE(c.IsSaturatedByCallCount(2));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(4));
  EXPECT_TRUE(c.IsSaturatedByCallCount(4));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "called at most twice",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [18/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (BetweenTest , OnZeroStartAndZeroEnd)
Definition at line 264 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Between(0, 0);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_TRUE(c.IsSaturatedByCallCount(0));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(1));
  EXPECT_TRUE(c.IsSaturatedByCallCount(1));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "never called",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [19/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (CardinalityTest , CanDescribeActualCallCount)
Definition at line 91 of file gmock-cardinalities_test.cc.
{
  stringstream ss0;
  Cardinality::DescribeActualCallCountTo(0, &ss0);
  EXPECT_EQ("never called", ss0.str());
  stringstream ss1;
  Cardinality::DescribeActualCallCountTo(1, &ss1);
  EXPECT_EQ("called once", ss1.str());
  stringstream ss2;
  Cardinality::DescribeActualCallCountTo(2, &ss2);
  EXPECT_EQ("called twice", ss2.str());
  stringstream ss3;
  Cardinality::DescribeActualCallCountTo(3, &ss3);
  EXPECT_EQ("called 3 times", ss3.str());
}
References EXPECT_EQ.
TEST() [20/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (CardinalityTest , IsCopyable)
Definition at line 68 of file gmock-cardinalities_test.cc.
{
  // Tests the copy constructor.
  Cardinality c = Exactly(1);
  EXPECT_FALSE(c.IsSatisfiedByCallCount(0));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(1));
  EXPECT_TRUE(c.IsSaturatedByCallCount(1));
  // Tests the assignment operator.
  c = Exactly(2);
  EXPECT_FALSE(c.IsSatisfiedByCallCount(1));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(2));
  EXPECT_TRUE(c.IsSaturatedByCallCount(2));
}
References EXPECT_FALSE, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [21/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (CardinalityTest , IsDefaultConstructable)
Definition at line 63 of file gmock-cardinalities_test.cc.
{
  Cardinality c;
}
TEST() [22/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (CardinalityTest , IsOverSaturatedByCallCountWorks)
Definition at line 82 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = AtMost(5);
  EXPECT_FALSE(c.IsOverSaturatedByCallCount(4));
  EXPECT_FALSE(c.IsOverSaturatedByCallCount(5));
  EXPECT_TRUE(c.IsOverSaturatedByCallCount(6));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::Cardinality::IsOverSaturatedByCallCount().
TEST() [23/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (ExactlyTest , HasCorrectBounds)
Definition at line 388 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Exactly(3);
  EXPECT_EQ(3, c.ConservativeLowerBound());
  EXPECT_EQ(3, c.ConservativeUpperBound());
}
References testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), and EXPECT_EQ.
TEST() [24/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (ExactlyTest , OnNegativeNumber)
Definition at line 344 of file gmock-cardinalities_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    Exactly(-1);
  }, "The invocation lower bound must be >= 0");
}
References EXPECT_NONFATAL_FAILURE.
TEST() [25/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (ExactlyTest , OnPositiveNumber)
Definition at line 364 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Exactly(2);
  EXPECT_FALSE(c.IsSatisfiedByCallCount(0));
  EXPECT_FALSE(c.IsSaturatedByCallCount(0));
  EXPECT_TRUE(c.IsSatisfiedByCallCount(2));
  EXPECT_TRUE(c.IsSaturatedByCallCount(2));
  stringstream ss1;
  Exactly(1).DescribeTo(&ss1);
  EXPECT_PRED_FORMAT2(IsSubstring, "called once",
                      ss1.str());
  stringstream ss2;
  c.DescribeTo(&ss2);
  EXPECT_PRED_FORMAT2(IsSubstring, "called twice",
                      ss2.str());
  stringstream ss3;
  Exactly(3).DescribeTo(&ss3);
  EXPECT_PRED_FORMAT2(IsSubstring, "called 3 times",
                      ss3.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [26/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (ExactlyTest , OnZero)
Definition at line 350 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = Exactly(0);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(0));
  EXPECT_TRUE(c.IsSaturatedByCallCount(0));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(1));
  EXPECT_TRUE(c.IsSaturatedByCallCount(1));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_PRED_FORMAT2(IsSubstring, "never called",
                      ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_FALSE, EXPECT_PRED_FORMAT2, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().
TEST() [27/27]
anonymous_namespace{gmock-cardinalities_test.cc}::TEST (MakeCardinalityTest , ConstructsCardinalityFromInterface)
Definition at line 415 of file gmock-cardinalities_test.cc.
{
  const Cardinality c = MakeCardinality(new EvenCardinality);
  EXPECT_TRUE(c.IsSatisfiedByCallCount(2));
  EXPECT_FALSE(c.IsSatisfiedByCallCount(3));
  EXPECT_FALSE(c.IsSaturatedByCallCount(10000));
  stringstream ss;
  c.DescribeTo(&ss);
  EXPECT_EQ("called even number of times", ss.str());
}
References testing::Cardinality::DescribeTo(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::Cardinality::IsSatisfiedByCallCount(), and testing::Cardinality::IsSaturatedByCallCount().