wiNpoS: Utils Namespace Reference
Utils Namespace Reference
Some helper constructs.
Classes
struct MainWndRes
Typedefs
using MainWindResVector = std::vector< MainWndRes >
Enumerations
enum Units { Percent , Pixels }
Functions
template<typename... Args>
string dformat (std::string_view rt_fmt_str, Args &&... args)
template<typename... Args>
std::wstring dwformat (std::wstring_view rt_fmt_str, Args &&... args)
void WriteDebugLog (string msg)
void ShowLastError (const string fmtStr)
template<typename T , typename Tx >
bool is_one_of (T t, Tx &&p1)
template<typename T , typename T1 , typename... Tx>
bool is_one_of (T t, T1 &&p1, Tx &&... px)
template<typename T , typename Tx >
bool is_each_of (T t, Tx &&p1)
template<typename T , typename T1 , typename... Tx>
bool is_each_of (T t, T1 &&p1, Tx &&... px)
template<typename T = uint32_t, typename M = T, typename F = T>
bool check_bits (M bitmask, F val)
template<typename T = uint32_t, typename M = T, typename F = T>
bool check_one_bit (M bitmask, F val)
template<typename T = uint32_t, typename M = T, typename F = T>
M set_bits (M bitmask, F val=0)
template<typename T = uint32_t, typename M = T, typename F = T>
M clear_bits (M bitmask, F val=0)
template<typename StrT >
std::string toLowerCase (const StrT &str)
MainWndRes GetMainWnd (DWORD threadId=0, DWORD processId=0)
MainWindResVector GetMainWnds (DWORD threadId=0, DWORD processId=0)
RECT ScaleRect (const RECT &in, FLOAT f)
bool operator== (const POINT &x, const POINT &y)
bool operator== (const RECT &x, const RECT &y)
Variables
string ExeName = initExeName()
string BinDir = initBinDir()
string ProductVersion = initVersionInfo("ProductVersion")
string ProductName = initVersionInfo("ProductName")
Detailed Description
Some helper constructs.
Typedef Documentation
MainWindResVector
using Utils::MainWindResVector = typedef std::vector<MainWndRes> private
Definition at line 203 of file Utils.h.
Enumeration Type Documentation
Units
enum Utils::Units
Enumerator
Percent
Pixels
Definition at line 213 of file Utils.h.
{ Percent, Pixels };
Function Documentation
check_bits()
template<typename T = uint32_t, typename M = T, typename F = T> bool Utils::check_bits (M bitmask, F val) inline private
Definition at line 148 of file Utils.h.
    {
        return ((T)val & (T)bitmask) == bitmask;
    }
References check_bits().
check_one_bit()
template<typename T = uint32_t, typename M = T, typename F = T> bool Utils::check_one_bit (M bitmask, F val) inline private
Definition at line 153 of file Utils.h.
    {
        return (((T)val) & ((T)bitmask)) != 0;
    }
References check_one_bit().
clear_bits()
template<typename T = uint32_t, typename M = T, typename F = T> M Utils::clear_bits (M bitmask, F val = 0) inline private
Definition at line 163 of file Utils.h.
    {
        return (T)val &= ~(T)bitmask;
    }
References clear_bits().
dformat()
template<typename... Args> string Utils::dformat (std::string_view rt_fmt_str, Args &&... args) private
dynamic format
Definition at line 45 of file Utils.h.
    {
        return std::vformat(rt_fmt_str, std::make_format_args(args...));
    }
References dformat().
dwformat()
template<typename... Args> std::wstring Utils::dwformat (std::wstring_view rt_fmt_str, Args &&... args) private
Definition at line 50 of file Utils.h.
    {
        return std::vformat(rt_fmt_str, std::make_wformat_args(args...));
    }
References dwformat().
GetMainWnd()
Utils::MainWndRes Utils::GetMainWnd (DWORD threadId = 0, DWORD processId = 0) private
Definition at line 177 of file Utils.cpp.
{
    auto wnds = GetDesktopWnds();
    processId = processId ? processId : GetCurrentProcessId();
    for (HWND hWnd : wnds)
    {
        DWORD wndProcessId = NULL;
        auto wndThreadId = GetWindowThreadProcessId(hWnd, &wndProcessId);
        if (processId == wndProcessId && (threadId == 0 || wndThreadId == threadId))
        {
            HWND hMainWnd = GetAncestor(hWnd, GA_ROOTOWNER);
            MainWndRes res = { hMainWnd, wndThreadId };
            return res;
        }
    }
    MainWndRes res = { 0 };
    return res;
}
References anonymous_namespace{Utils.cpp}::GetDesktopWnds().
GetMainWnds()
Utils::MainWindResVector Utils::GetMainWnds (DWORD threadId = 0, DWORD processId = 0) private
Definition at line 210 of file Utils.cpp.
{
    DesktopNameVector desktopNames;
    EnumDesktopsA(nullptr, EnumDesktopProcA, (LPARAM)&desktopNames);
    MainWindResVector mainWnds;
    for (const string dn : desktopNames)
    {
        HDESK hDesk = OpenDesktopA(dn.c_str(), 0, FALSE, READ_CONTROL);
        WndVector hWnds;
        auto res = EnumDesktopWindows(hDesk, EnumWindowsProc, (LPARAM)&hWnds);
        CloseDesktop(hDesk);
        for (HWND hWnd : hWnds)
        {
            DWORD wndProcessId = NULL;
            auto wndThreadId = GetWindowThreadProcessId(hWnd, &wndProcessId);
            if (processId == wndProcessId && (threadId == 0 || wndThreadId == threadId))
            {
                HWND hMainWnd = GetAncestor(hWnd, GA_ROOTOWNER);
                mainWnds.push_back({ hMainWnd, wndThreadId });
            }
        }
    }
    return mainWnds;
}
References anonymous_namespace{Utils.cpp}::EnumDesktopProcA(), and anonymous_namespace{Utils.cpp}::EnumWindowsProc().
is_each_of() [1/2]
template<typename T , typename T1 , typename... Tx> bool Utils::is_each_of (T t, T1 && p1, Tx &&... px) private
Definition at line 143 of file Utils.h.
{
        return is_each_of(t, p1) && is_each_of(t, px...);
    }
References is_each_of().
is_each_of() [2/2]
template<typename T , typename Tx > bool Utils::is_each_of (T t, Tx && p1) private
Definition at line 137 of file Utils.h.
    {
        return t == p1;
    }
References is_each_of().
is_one_of() [1/2]
template<typename T , typename T1 , typename... Tx> bool Utils::is_one_of (T t, T1 && p1, Tx &&... px) private
Definition at line 132 of file Utils.h.
{
        return is_one_of(t, p1) || is_one_of(t, px...);
    }
References is_one_of().
is_one_of() [2/2]
template<typename T , typename Tx > bool Utils::is_one_of (T t, Tx && p1) private
Definition at line 126 of file Utils.h.
    {
        return t == p1;
    }
References is_one_of().
operator==() [1/2]
bool Utils::operator== (const POINT & x, const POINT & y) inline
Definition at line 216 of file Utils.h.
    {
        using std::make_tuple;
        return make_tuple(x.x, x.y) == make_tuple(y.x, y.y);
    }
operator==() [2/2]
bool Utils::operator== (const RECT & x, const RECT & y) inline
Definition at line 221 of file Utils.h.
    {
        using std::make_tuple;
        return make_tuple(x.left, x.top, x.right, x.bottom) == make_tuple(y.left, y.top, y.right, y.bottom);
    }
ScaleRect()
RECT Utils::ScaleRect (const RECT & in, FLOAT f)
Definition at line 236 of file Utils.cpp.
{
    RECT r = { 0 };
    r.right = static_cast<LONG>(((FLOAT)((in.right - in.left) + in.left)) * f);
    r.bottom = static_cast<LONG>(((FLOAT)((in.bottom - in.top) + in.top)) * f);
    r.left = static_cast<LONG>(((FLOAT)in.left) * f);
    r.top = static_cast<LONG>(((FLOAT)in.top) * f);
    return r;
}
set_bits()
template<typename T = uint32_t, typename M = T, typename F = T> M Utils::set_bits (M bitmask, F val = 0) inline private
Definition at line 158 of file Utils.h.
    {
        return ((T)val |= (T)bitmask);
    }
References set_bits().
ShowLastError()
void Utils::ShowLastError (const string fmtStr) inline private
Definition at line 107 of file Utils.h.
    {
        LPSTR errorText = NULL;
        FormatMessageA(
            FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_IGNORE_INSERTS,
            NULL,
            GetLastError(),
            MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
            (LPSTR)&errorText,
            0,
            NULL);
        const string errorStr = errorText;
        string msg = dformat(fmtStr, errorStr);
        MessageBoxA(NULL, msg.c_str(), "Error", MB_ICONERROR | MB_OK);
        LocalFree(errorText);
    }
References dformat().
toLowerCase()
template<typename StrT > std::string Utils::toLowerCase (const StrT & str) inline private
Definition at line 182 of file Utils.h.
{
        StrT result = str;
        std::transform(result.begin(), result.end(), result.begin(), ::tolower);
        return result;
    }
References toLowerCase().
WriteDebugLog()
void Utils::WriteDebugLog (string msg) inline private
Definition at line 88 of file Utils.h.
    {
        ::OutputDebugStringA(msg.c_str());
    }
Variable Documentation
BinDir
string Utils::BinDir = initBinDir() extern private
Definition at line 108 of file Utils.cpp.
ExeName
string Utils::ExeName = initExeName() extern private
Definition at line 107 of file Utils.cpp.
ProductName
string Utils::ProductName = initVersionInfo("ProductName") extern private
Definition at line 110 of file Utils.cpp.
ProductVersion
string Utils::ProductVersion = initVersionInfo("ProductVersion") extern private
Definition at line 109 of file Utils.cpp.