wiNpoS: gtest_env_var_test Namespace Reference
gtest_env_var_test Namespace Reference
Classes
class GTestEnvVarTest
Functions
AssertEq (expected, actual)
SetEnvVar (env_var, value)
GetFlag (flag)
TestFlag (flag, test_val, default_val)
Variables
str __author__ = 'wan@google.com (Zhanyong Wan)'
str IS_WINDOWS = 'nt'
str IS_LINUX = 'Linux'
COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_env_var_test_')
environ = os.environ.copy()
Detailed Description
Verifies that Google Test correctly parses environment variables.
Function Documentation
AssertEq()
gtest_env_var_test.AssertEq (expected, actual)
Definition at line 48 of file gtest_env_var_test.py.
def AssertEq(expected, actual):
  if expected != actual:
    print 'Expected: %s' % (expected,)
    print '  Actual: %s' % (actual,)
    raise AssertionError
GetFlag()
gtest_env_var_test.GetFlag (flag)
Runs gtest_env_var_test_ and returns its output.
Definition at line 64 of file gtest_env_var_test.py.
def GetFlag(flag):
  """Runs gtest_env_var_test_ and returns its output."""
  args = [COMMAND]
  if flag is not None:
    args += [flag]
  return gtest_test_utils.Subprocess(args, env=environ).output
SetEnvVar()
gtest_env_var_test.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Definition at line 55 of file gtest_env_var_test.py.
def SetEnvVar(env_var, value):
  """Sets the env variable to 'value'; unsets it when 'value' is None."""
  if value is not None:
    environ[env_var] = value
  elif env_var in environ:
    del environ[env_var]
TestFlag()
gtest_env_var_test.TestFlag (flag, test_val, default_val)
Verifies that the given flag is affected by the corresponding env var.
Definition at line 73 of file gtest_env_var_test.py.
def TestFlag(flag, test_val, default_val):
  """Verifies that the given flag is affected by the corresponding env var."""
  env_var = 'GTEST_' + flag.upper()
  SetEnvVar(env_var, test_val)
  AssertEq(test_val, GetFlag(flag))
  SetEnvVar(env_var, None)
  AssertEq(default_val, GetFlag(flag))
References AssertEq(), GetFlag(), and SetEnvVar().
Variable Documentation
__author__
str gtest_env_var_test.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 34 of file gtest_env_var_test.py.
COMMAND
gtest_env_var_test.COMMAND = gtest_test_utils.GetTestExecutablePath('gtest_env_var_test_')
Definition at line 43 of file gtest_env_var_test.py.
environ
gtest_env_var_test.environ = os.environ.copy()
Definition at line 45 of file gtest_env_var_test.py.
IS_LINUX
str gtest_env_var_test.IS_LINUX = 'Linux'
Definition at line 41 of file gtest_env_var_test.py.
IS_WINDOWS
str gtest_env_var_test.IS_WINDOWS = 'nt'
Definition at line 40 of file gtest_env_var_test.py.