wiNpoS: anonymous_namespace{gtest-linked_ptr_test.cc} Namespace Reference
anonymous_namespace{gtest-linked_ptr_test.cc} Namespace Reference
Classes
class A
class B
class LinkedPtrTest
Functions
TEST_F (LinkedPtrTest, GeneralTest)
Variables
int num
Message * history = NULL
Function Documentation
TEST_F()
anonymous_namespace{gtest-linked_ptr_test.cc}::TEST_F (LinkedPtrTest , GeneralTest)
Definition at line 77 of file gtest-linked_ptr_test.cc.
{
  {
    linked_ptr<A> a0, a1, a2;
    // Use explicit function call notation here to suppress self-assign warning.
    a0.operator=(a0);
    a1 = a2;
    ASSERT_EQ(a0.get(), static_cast<A*>(NULL));
    ASSERT_EQ(a1.get(), static_cast<A*>(NULL));
    ASSERT_EQ(a2.get(), static_cast<A*>(NULL));
    ASSERT_TRUE(a0 == NULL);
    ASSERT_TRUE(a1 == NULL);
    ASSERT_TRUE(a2 == NULL);
    {
      linked_ptr<A> a3(new A);
      a0 = a3;
      ASSERT_TRUE(a0 == a3);
      ASSERT_TRUE(a0 != NULL);
      ASSERT_TRUE(a0.get() == a3);
      ASSERT_TRUE(a0 == a3.get());
      linked_ptr<A> a4(a0);
      a1 = a4;
      linked_ptr<A> a5(new A);
      ASSERT_TRUE(a5.get() != a3);
      ASSERT_TRUE(a5 != a3.get());
      a2 = a5;
      linked_ptr<B> b0(new B);
      linked_ptr<A> a6(b0);
      ASSERT_TRUE(b0 == a6);
      ASSERT_TRUE(a6 == b0);
      ASSERT_TRUE(b0 != NULL);
      a5 = b0;
      a5 = b0;
      a3->Use();
      a4->Use();
      a5->Use();
      a6->Use();
      b0->Use();
      (*b0).Use();
      b0.get()->Use();
    }
    a0->Use();
    a1->Use();
    a2->Use();
    a1 = a2;
    a2.reset(new A);
    a0.reset();
    linked_ptr<A> a7;
  }
  ASSERT_STREQ(
    "A0 ctor\n"
    "A1 ctor\n"
    "A2 ctor\n"
    "B2 ctor\n"
    "A0 use\n"
    "A0 use\n"
    "B2 use\n"
    "B2 use\n"
    "B2 use\n"
    "B2 use\n"
    "B2 use\n"
    "B2 dtor\n"
    "A2 dtor\n"
    "A0 use\n"
    "A0 use\n"
    "A1 use\n"
    "A3 ctor\n"
    "A0 dtor\n"
    "A3 dtor\n"
    "A1 dtor\n",
    history->GetString().c_str());
}
References ASSERT_EQ, ASSERT_STREQ, ASSERT_TRUE, testing::internal::linked_ptr< T >::get(), testing::Message::GetString(), history, and testing::internal::linked_ptr< T >::reset().
Variable Documentation
history
Message* anonymous_namespace{gtest-linked_ptr_test.cc}::history = NULL
Definition at line 44 of file gtest-linked_ptr_test.cc.
num
int anonymous_namespace{gtest-linked_ptr_test.cc}::num
Definition at line 43 of file gtest-linked_ptr_test.cc.