wiNpoS: anonymous_namespace{gmock-generated-matchers_test.cc} Namespace Reference
anonymous_namespace{gmock-generated-matchers_test.cc} Namespace Reference
Namespaces
namespace adl_test
namespace matcher_test
Classes
class GreaterThanMatcher
class LessThanMatcher
class NativeArrayPassedAsPointerAndSize
class UncopyableFoo
Functions
template<typename T >
std::string Describe (const Matcher< T > &m)
template<typename T >
std::string DescribeNegation (const Matcher< T > &m)
template<typename MatcherType , typename Value >
std::string Explain (const MatcherType &m, const Value &x)
TEST (ArgsTest, AcceptsZeroTemplateArg)
TEST (ArgsTest, AcceptsOneTemplateArg)
TEST (ArgsTest, AcceptsTwoTemplateArgs)
TEST (ArgsTest, AcceptsRepeatedTemplateArgs)
TEST (ArgsTest, AcceptsDecreasingTemplateArgs)
MATCHER (SumIsZero, "")
TEST (ArgsTest, AcceptsMoreTemplateArgsThanArityOfOriginalTuple)
TEST (ArgsTest, CanBeNested)
TEST (ArgsTest, CanMatchTupleByValue)
TEST (ArgsTest, CanMatchTupleByReference)
MATCHER_P (PrintsAs, str, "")
TEST (ArgsTest, AcceptsTenTemplateArgs)
TEST (ArgsTest, DescirbesSelfCorrectly)
TEST (ArgsTest, DescirbesNestedArgsCorrectly)
TEST (ArgsTest, DescribesNegationCorrectly)
TEST (ArgsTest, ExplainsMatchResultWithoutInnerExplanation)
Matcher< tuple< char, int > > LessThan ()
TEST (ArgsTest, ExplainsMatchResultWithInnerExplanation)
Matcher< int > GreaterThan (int n)
TEST (ElementsAreTest, CanDescribeExpectingNoElement)
TEST (ElementsAreTest, CanDescribeExpectingOneElement)
TEST (ElementsAreTest, CanDescribeExpectingManyElements)
TEST (ElementsAreTest, CanDescribeNegationOfExpectingNoElement)
TEST (ElementsAreTest, CanDescribeNegationOfExpectingOneElment)
TEST (ElementsAreTest, CanDescribeNegationOfExpectingManyElements)
TEST (ElementsAreTest, DoesNotExplainTrivialMatch)
TEST (ElementsAreTest, ExplainsNonTrivialMatch)
TEST (ElementsAreTest, CanExplainMismatchWrongSize)
TEST (ElementsAreTest, CanExplainMismatchRightSize)
TEST (ElementsAreTest, MatchesOneElementVector)
TEST (ElementsAreTest, MatchesOneElementList)
TEST (ElementsAreTest, MatchesThreeElementVector)
TEST (ElementsAreTest, MatchesOneElementEqMatcher)
TEST (ElementsAreTest, MatchesOneElementAnyMatcher)
TEST (ElementsAreTest, MatchesOneElementValue)
TEST (ElementsAreTest, MatchesThreeElementsMixedMatchers)
TEST (ElementsAreTest, MatchesTenElementVector)
TEST (ElementsAreTest, DoesNotMatchWrongSize)
TEST (ElementsAreTest, DoesNotMatchWrongValue)
TEST (ElementsAreTest, DoesNotMatchWrongOrder)
TEST (ElementsAreTest, WorksForNestedContainer)
TEST (ElementsAreTest, WorksWithByRefElementMatchers)
TEST (ElementsAreTest, WorksWithContainerPointerUsingPointee)
TEST (ElementsAreTest, WorksWithNativeArrayPassedByReference)
TEST (ElementsAreTest, WorksWithNativeArrayPassedAsPointerAndSize)
TEST (ElementsAreTest, WorksWithTwoDimensionalNativeArray)
TEST (ElementsAreTest, AcceptsStringLiteral)
TEST (ElementsAreTest, AcceptsArrayWithUnknownSize)
TEST (ElementsAreTest, MakesCopyOfArguments)
TEST (ElementsAreArrayTest, CanBeCreatedWithValueArray)
TEST (ElementsAreArrayTest, CanBeCreatedWithArraySize)
TEST (ElementsAreArrayTest, CanBeCreatedWithoutArraySize)
TEST (ElementsAreArrayTest, CanBeCreatedWithMatcherArray)
TEST (ElementsAreArrayTest, CanBeCreatedWithVector)
TEST (ElementsAreArrayTest, CanBeCreatedWithMatcherVector)
TEST (ElementsAreArrayTest, CanBeCreatedWithIteratorRange)
TEST (ElementsAreArrayTest, WorksWithNativeArray)
TEST (ElementsAreArrayTest, SourceLifeSpan)
MATCHER (IsEven, "")
TEST (MatcherMacroTest, Works)
MATCHER (IsEven2, negation ? "is odd" :"is even")
MATCHER_P2 (EqSumOf, x, y, std::string(negation ? "doesn't equal" :"equals")+" the sum of "+PrintToString(x)+" and "+PrintToString(y))
TEST (MatcherMacroTest, DescriptionCanReferenceNegationAndParameters)
TEST (MatcherMacroTest, CanExplainMatchResult)
MATCHER (IsEmptyString, "")
MATCHER (IsEmptyStringByRef, "")
TEST (MatcherMacroTest, CanReferenceArgType)
TEST (MatcherMacroTest, WorksInNamespace)
MATCHER (IsPositiveOdd, "")
TEST (MatcherMacroTest, CanBeComposedUsingValue)
MATCHER_P (IsGreaterThan32And, n, "")
TEST (MatcherPMacroTest, Works)
MATCHER_P (_is_Greater_Than32and_, n, "")
TEST (MatcherPMacroTest, GeneratesCorrectDescription)
MATCHER_P (ReferencesUncopyable, variable, "")
TEST (MatcherPMacroTest, WorksWhenExplicitlyInstantiatedWithReference)
MATCHER_P3 (ParamTypesAreIntLongAndChar, foo, bar, baz, "")
TEST (MatcherPnMacroTest, CanReferenceParamTypes)
MATCHER_P2 (ReferencesAnyOf, variable1, variable2, "")
TEST (MatcherPnMacroTest, WorksWhenExplicitlyInstantiatedWithReferences)
TEST (MatcherPnMacroTest, GeneratesCorretDescriptionWhenExplicitlyInstantiatedWithReferences)
MATCHER_P2 (IsNotInClosedRange, low, hi, "")
TEST (MatcherPnMacroTest, Works)
MATCHER (EqualsSumOf, "")
MATCHER_P (EqualsSumOf, a, "")
MATCHER_P2 (EqualsSumOf, a, b, "")
MATCHER_P3 (EqualsSumOf, a, b, c, "")
MATCHER_P4 (EqualsSumOf, a, b, c, d, "")
MATCHER_P5 (EqualsSumOf, a, b, c, d, e, "")
MATCHER_P6 (EqualsSumOf, a, b, c, d, e, f, "")
MATCHER_P7 (EqualsSumOf, a, b, c, d, e, f, g, "")
MATCHER_P8 (EqualsSumOf, a, b, c, d, e, f, g, h, "")
MATCHER_P9 (EqualsSumOf, a, b, c, d, e, f, g, h, i, "")
MATCHER_P10 (EqualsSumOf, a, b, c, d, e, f, g, h, i, j, "")
TEST (MatcherPnMacroTest, CanBeOverloadedOnNumberOfParameters)
TEST (MatcherPnMacroTest, WorksForDifferentParameterTypes)
MATCHER_P2 (EqConcat, prefix, suffix, "")
TEST (MatcherPnMacroTest, SimpleTypePromotion)
TEST (MatcherPnMacroTest, TypesAreCorrect)
MATCHER_P3 (TwoOf, m1, m2, m3, "")
TEST (MatcherPnMacroTest, CanUseMatcherTypedParameterInValue)
TEST (ContainsTest, ListMatchesWhenElementIsInContainer)
TEST (ContainsTest, ListDoesNotMatchWhenElementIsNotInContainer)
TEST (ContainsTest, SetMatchesWhenElementIsInContainer)
TEST (ContainsTest, SetDoesNotMatchWhenElementIsNotInContainer)
TEST (ContainsTest, ExplainsMatchResultCorrectly)
TEST (ContainsTest, DescribesItselfCorrectly)
TEST (ContainsTest, MapMatchesWhenElementIsInContainer)
TEST (ContainsTest, MapDoesNotMatchWhenElementIsNotInContainer)
TEST (ContainsTest, ArrayMatchesWhenElementIsInContainer)
TEST (ContainsTest, ArrayDoesNotMatchWhenElementIsNotInContainer)
TEST (ContainsTest, AcceptsMatcher)
TEST (ContainsTest, WorksForNativeArrayAsTuple)
TEST (ContainsTest, WorksForTwoDimensionalNativeArray)
TEST (AllOfTest, HugeMatcher)
TEST (AnyOfTest, HugeMatcher)
Variables
const char kHi [] = "hi"
Function Documentation
Describe()
template<typename T > std::string anonymous_namespace{gmock-generated-matchers_test.cc}::Describe (const Matcher< T > & m)
Definition at line 96 of file gmock-generated-matchers_test.cc.
{
  stringstream ss;
  m.DescribeTo(&ss);
  return ss.str();
}
References testing::internal::MatcherBase< T >::DescribeTo().
DescribeNegation()
template<typename T > std::string anonymous_namespace{gmock-generated-matchers_test.cc}::DescribeNegation (const Matcher< T > & m)
Definition at line 104 of file gmock-generated-matchers_test.cc.
{
  stringstream ss;
  m.DescribeNegationTo(&ss);
  return ss.str();
}
References testing::internal::MatcherBase< T >::DescribeNegationTo().
Explain()
template<typename MatcherType , typename Value > std::string anonymous_namespace{gmock-generated-matchers_test.cc}::Explain (const MatcherType & m, const Value & x)
Definition at line 112 of file gmock-generated-matchers_test.cc.
{
  stringstream ss;
  m.ExplainMatchResultTo(x, &ss);
  return ss.str();
}
GreaterThan()
Matcher< int > anonymous_namespace{gmock-generated-matchers_test.cc}::GreaterThan (int n)
Definition at line 292 of file gmock-generated-matchers_test.cc.
{
  return MakeMatcher(new GreaterThanMatcher(n));
}
LessThan()
Matcher< tuple< char, int > > anonymous_namespace{gmock-generated-matchers_test.cc}::LessThan ()
Definition at line 252 of file gmock-generated-matchers_test.cc.
{
  return MakeMatcher(new LessThanMatcher);
}
MATCHER() [1/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (EqualsSumOf , "")
Definition at line 968 of file gmock-generated-matchers_test.cc.
{ return arg == 0; }
MATCHER() [2/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (IsEmptyString , "")
Definition at line 806 of file gmock-generated-matchers_test.cc.
{
  StaticAssertTypeEq< ::std::string, arg_type>();
  return arg == "";
}
MATCHER() [3/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (IsEmptyStringByRef , "")
Definition at line 811 of file gmock-generated-matchers_test.cc.
{
  StaticAssertTypeEq<const ::std::string&, arg_type>();
  return arg == "";
}
MATCHER() [4/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (IsEven , "")
Definition at line 736 of file gmock-generated-matchers_test.cc.
{ return (arg % 2) == 0; }
MATCHER() [5/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (IsEven2 , negation ? "is odd" :"is even")
Definition at line 750 of file gmock-generated-matchers_test.cc.
                                     : "is even") {
  if ((arg % 2) == 0) {
    // Verifies that we can stream to result_listener, a listener
    // supplied by the MATCHER macro implicitly.
    *result_listener << "OK";
    return true;
  } else {
    *result_listener << "% 2 == " << (arg % 2);
    return false;
  }
}
MATCHER() [6/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (IsPositiveOdd , "")
Definition at line 837 of file gmock-generated-matchers_test.cc.
{
  return Value(arg, matcher_test::IsOdd()) && arg > 0;
}
MATCHER() [7/7]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER (SumIsZero , "")
Definition at line 163 of file gmock-generated-matchers_test.cc.
                       {
  return get<0>(arg) + get<1>(arg) + get<2>(arg) == 0;
}
MATCHER_P() [1/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P (_is_Greater_Than32and_ , n , "")
Definition at line 863 of file gmock-generated-matchers_test.cc.
{ return arg > 32 && arg > n; }
MATCHER_P() [2/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P (EqualsSumOf , a , "")
Definition at line 969 of file gmock-generated-matchers_test.cc.
{ return arg == a; }
MATCHER_P() [3/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P (IsGreaterThan32And , n , "")
Definition at line 849 of file gmock-generated-matchers_test.cc.
{ return arg > 32 && arg > n; }
MATCHER_P() [4/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P (PrintsAs , str , "")
Definition at line 193 of file gmock-generated-matchers_test.cc.
{
  return testing::PrintToString(arg) == str;
}
References testing::PrintToString().
MATCHER_P() [5/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P (ReferencesUncopyable , variable , "")
Definition at line 887 of file gmock-generated-matchers_test.cc.
{ return &arg == &variable; }
MATCHER_P10()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P10 (EqualsSumOf , a , b , c , d , e , f , g , h , i , j , "")
Definition at line 986 of file gmock-generated-matchers_test.cc.
{
  return arg == a + b + c + d + e + f + g + h + i + j;
}
MATCHER_P2() [1/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P2 (EqConcat , prefix , suffix , "")
Definition at line 1045 of file gmock-generated-matchers_test.cc.
{
  // The following lines promote the two parameters to desired types.
  std::string prefix_str(prefix);
  char suffix_char = static_cast<char>(suffix);
  return arg == prefix_str + suffix_char;
}
MATCHER_P2() [2/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P2 (EqSumOf , x , y , std::string(negation ? "doesn't equal" :"equals")+" the sum of "+PrintToString(x)+" and "+PrintToString(y))
Definition at line 764 of file gmock-generated-matchers_test.cc.
                                                               : "equals") +
                              " the sum of " + PrintToString(x) + " and " +
                              PrintToString(y)) {
  if (arg == (x + y)) {
    *result_listener << "OK";
    return true;
  } else {
    // Verifies that we can stream to the underlying stream of
    // result_listener.
    if (result_listener->stream() != NULL) {
      *result_listener->stream() << "diff == " << (x + y - arg);
    }
    return false;
  }
}
MATCHER_P2() [3/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P2 (EqualsSumOf , a , b , "")
Definition at line 970 of file gmock-generated-matchers_test.cc.
{ return arg == a + b; }
MATCHER_P2() [4/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P2 (IsNotInClosedRange , low , hi , "")
Definition at line 952 of file gmock-generated-matchers_test.cc.
{ return arg < low || arg > hi; }
MATCHER_P2() [5/5]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P2 (ReferencesAnyOf , variable1 , variable2 , "")
Definition at line 922 of file gmock-generated-matchers_test.cc.
{
  return &arg == &variable1 || &arg == &variable2;
}
MATCHER_P3() [1/3]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P3 (EqualsSumOf , a , b , c , "")
Definition at line 971 of file gmock-generated-matchers_test.cc.
{ return arg == a + b + c; }
MATCHER_P3() [2/3]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P3 (ParamTypesAreIntLongAndChar , foo , bar , baz , "")
Definition at line 908 of file gmock-generated-matchers_test.cc.
{
  StaticAssertTypeEq<int, foo_type>();
  StaticAssertTypeEq<long, bar_type>();  // NOLINT
  StaticAssertTypeEq<char, baz_type>();
  return arg == 0;
}
MATCHER_P3() [3/3]
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P3 (TwoOf , m1 , m2 , m3 , "")
Definition at line 1108 of file gmock-generated-matchers_test.cc.
{
  const int count = static_cast<int>(Value(arg, m1))
      + static_cast<int>(Value(arg, m2)) + static_cast<int>(Value(arg, m3));
  return count == 2;
}
MATCHER_P4()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P4 (EqualsSumOf , a , b , c , d , "")
Definition at line 972 of file gmock-generated-matchers_test.cc.
{ return arg == a + b + c + d; }
MATCHER_P5()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P5 (EqualsSumOf , a , b , c , d , e , "")
Definition at line 973 of file gmock-generated-matchers_test.cc.
{ return arg == a + b + c + d + e; }
MATCHER_P6()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P6 (EqualsSumOf , a , b , c , d , e , f , "")
Definition at line 974 of file gmock-generated-matchers_test.cc.
{
  return arg == a + b + c + d + e + f;
}
MATCHER_P7()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P7 (EqualsSumOf , a , b , c , d , e , f , g , "")
Definition at line 977 of file gmock-generated-matchers_test.cc.
{
  return arg == a + b + c + d + e + f + g;
}
MATCHER_P8()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P8 (EqualsSumOf , a , b , c , d , e , f , g , h , "")
Definition at line 980 of file gmock-generated-matchers_test.cc.
{
  return arg == a + b + c + d + e + f + g + h;
}
MATCHER_P9()
anonymous_namespace{gmock-generated-matchers_test.cc}::MATCHER_P9 (EqualsSumOf , a , b , c , d , e , f , g , h , i , "")
Definition at line 983 of file gmock-generated-matchers_test.cc.
{
  return arg == a + b + c + d + e + f + g + h + i;
}
TEST() [1/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (AllOfTest , HugeMatcher)
Definition at line 1250 of file gmock-generated-matchers_test.cc.
{
  // Verify that using AllOf with many arguments doesn't cause
  // the compiler to exceed template instantiation depth limit.
  EXPECT_THAT(0, testing::AllOf(_, _, _, _, _, _, _, _, _,
                                testing::AllOf(_, _, _, _, _, _, _, _, _, _)));
}
References testing::AllOf(), and EXPECT_THAT.
TEST() [2/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (AnyOfTest , HugeMatcher)
Definition at line 1257 of file gmock-generated-matchers_test.cc.
{
  // Verify that using AnyOf with many arguments doesn't cause
  // the compiler to exceed template instantiation depth limit.
  EXPECT_THAT(0, testing::AnyOf(_, _, _, _, _, _, _, _, _,
                                testing::AnyOf(_, _, _, _, _, _, _, _, _, _)));
}
References testing::AnyOf(), and EXPECT_THAT.
TEST() [3/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsDecreasingTemplateArgs)
Definition at line 147 of file gmock-generated-matchers_test.cc.
{
  const tuple<short, int, long> t(4, 5, 6L);  // NOLINT
  EXPECT_THAT(t, (Args<2, 0>(Gt())));
  EXPECT_THAT(t, Not(Args<2, 1>(Lt())));
}
References EXPECT_THAT.
TEST() [4/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsMoreTemplateArgsThanArityOfOriginalTuple)
Definition at line 167 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(make_tuple(-1, 2), (Args<0, 0, 1>(SumIsZero())));
  EXPECT_THAT(make_tuple(1, 2), Not(Args<0, 0, 1>(SumIsZero())));
}
References EXPECT_THAT.
TEST() [5/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsOneTemplateArg)
Definition at line 126 of file gmock-generated-matchers_test.cc.
{
  const tuple<int, bool> t(5, true);
  EXPECT_THAT(t, Args<0>(Eq(make_tuple(5))));
  EXPECT_THAT(t, Args<1>(Eq(make_tuple(true))));
  EXPECT_THAT(t, Not(Args<1>(Eq(make_tuple(false)))));
}
References EXPECT_THAT.
TEST() [6/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsRepeatedTemplateArgs)
Definition at line 141 of file gmock-generated-matchers_test.cc.
{
  const tuple<short, int, long> t(4, 5, 6L);  // NOLINT
  EXPECT_THAT(t, (Args<0, 0>(Eq())));
  EXPECT_THAT(t, Not(Args<1, 1>(Ne())));
}
References EXPECT_THAT.
TEST() [7/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsTenTemplateArgs)
Definition at line 197 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(make_tuple(0, 1L, 2, 3L, 4, 5, 6, 7, 8, 9),
              (Args<9, 8, 7, 6, 5, 4, 3, 2, 1, 0>(
                  PrintsAs("(9, 8, 7, 6, 5, 4, 3, 2, 1, 0)"))));
  EXPECT_THAT(make_tuple(0, 1L, 2, 3L, 4, 5, 6, 7, 8, 9),
              Not(Args<9, 8, 7, 6, 5, 4, 3, 2, 1, 0>(
                      PrintsAs("(0, 8, 7, 6, 5, 4, 3, 2, 1, 0)"))));
}
References EXPECT_THAT.
TEST() [8/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsTwoTemplateArgs)
Definition at line 133 of file gmock-generated-matchers_test.cc.
{
  const tuple<short, int, long> t(4, 5, 6L);  // NOLINT
  EXPECT_THAT(t, (Args<0, 1>(Lt())));
  EXPECT_THAT(t, (Args<1, 2>(Lt())));
  EXPECT_THAT(t, Not(Args<0, 2>(Gt())));
}
References EXPECT_THAT.
TEST() [9/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , AcceptsZeroTemplateArg)
Definition at line 120 of file gmock-generated-matchers_test.cc.
{
  const tuple<int, bool> t(5, true);
  EXPECT_THAT(t, Args<>(Eq(tuple<>())));
  EXPECT_THAT(t, Not(Args<>(Ne(tuple<>()))));
}
References EXPECT_THAT.
TEST() [10/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , CanBeNested)
Definition at line 172 of file gmock-generated-matchers_test.cc.
{
  const tuple<short, int, long, int> t(4, 5, 6L, 6);  // NOLINT
  EXPECT_THAT(t, (Args<1, 2, 3>(Args<1, 2>(Eq()))));
  EXPECT_THAT(t, (Args<0, 1, 3>(Args<0, 2>(Lt()))));
}
References EXPECT_THAT.
TEST() [11/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , CanMatchTupleByReference)
Definition at line 185 of file gmock-generated-matchers_test.cc.
{
  typedef tuple<char, char, int> Tuple3;
  const Matcher<const Tuple3&> m = Args<0, 1>(Lt());
  EXPECT_TRUE(m.Matches(Tuple3('a', 'b', 2)));
  EXPECT_FALSE(m.Matches(Tuple3('b', 'b', 2)));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [12/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , CanMatchTupleByValue)
Definition at line 178 of file gmock-generated-matchers_test.cc.
{
  typedef tuple<char, int, int> Tuple3;
  const Matcher<Tuple3> m = Args<1, 2>(Lt());
  EXPECT_TRUE(m.Matches(Tuple3('a', 1, 2)));
  EXPECT_FALSE(m.Matches(Tuple3('b', 2, 2)));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [13/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , DescirbesNestedArgsCorrectly)
Definition at line 213 of file gmock-generated-matchers_test.cc.
{
  const Matcher<const tuple<int, bool, char, int>&> m =
      Args<0, 2, 3>(Args<2, 0>(Lt()));
  EXPECT_EQ("are a tuple whose fields (#0, #2, #3) are a tuple "
            "whose fields (#2, #0) are a pair where the first < the second",
            Describe(m));
}
References Describe(), and EXPECT_EQ.
TEST() [14/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , DescirbesSelfCorrectly)
Definition at line 206 of file gmock-generated-matchers_test.cc.
{
  const Matcher<tuple<int, bool, char> > m = Args<2, 0>(Lt());
  EXPECT_EQ("are a tuple whose fields (#2, #0) are a pair where "
            "the first < the second",
            Describe(m));
}
References Describe(), and EXPECT_EQ.
TEST() [15/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , DescribesNegationCorrectly)
Definition at line 221 of file gmock-generated-matchers_test.cc.
{
  const Matcher<tuple<int, char> > m = Args<1, 0>(Gt());
  EXPECT_EQ("are a tuple whose fields (#1, #0) aren't a pair "
            "where the first > the second",
            DescribeNegation(m));
}
References DescribeNegation(), and EXPECT_EQ.
TEST() [16/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , ExplainsMatchResultWithInnerExplanation)
Definition at line 256 of file gmock-generated-matchers_test.cc.
{
  const Matcher<tuple<char, int, int> > m = Args<0, 2>(LessThan());
  EXPECT_EQ("whose fields (#0, #2) are ('a' (97, 0x61), 42), "
            "where the first value is 55 more than the second",
            Explain(m, make_tuple('a', 42, 42)));
  EXPECT_EQ("whose fields (#0, #2) are ('\\0', 43)",
            Explain(m, make_tuple('\0', 42, 43)));
}
References EXPECT_EQ, Explain(), and LessThan().
TEST() [17/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ArgsTest , ExplainsMatchResultWithoutInnerExplanation)
Definition at line 228 of file gmock-generated-matchers_test.cc.
{
  const Matcher<tuple<bool, int, int> > m = Args<1, 2>(Eq());
  EXPECT_EQ("whose fields (#1, #2) are (42, 42)",
            Explain(m, make_tuple(false, 42, 42)));
  EXPECT_EQ("whose fields (#1, #2) are (42, 43)",
            Explain(m, make_tuple(false, 42, 43)));
}
References EXPECT_EQ, and Explain().
TEST() [18/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , AcceptsMatcher)
Definition at line 1229 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2, 3 };
  EXPECT_THAT(a, Contains(Gt(2)));
  EXPECT_THAT(a, Not(Contains(Gt(4))));
}
References EXPECT_THAT.
TEST() [19/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , ArrayDoesNotMatchWhenElementIsNotInContainer)
Definition at line 1224 of file gmock-generated-matchers_test.cc.
{
  int int_array[] = { 1, 2, 3, 4 };
  EXPECT_THAT(int_array, Not(Contains(5)));
}
References EXPECT_THAT.
TEST() [20/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , ArrayMatchesWhenElementIsInContainer)
Definition at line 1219 of file gmock-generated-matchers_test.cc.
{
  const char* string_array[] = { "fee", "fie", "foe", "fum" };
  EXPECT_THAT(string_array, Contains(Eq(std::string("fum"))));
}
References EXPECT_THAT.
TEST() [21/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , DescribesItselfCorrectly)
Definition at line 1188 of file gmock-generated-matchers_test.cc.
{
  Matcher<vector<int> > m = Contains(1);
  EXPECT_EQ("contains at least one element that is equal to 1", Describe(m));
  Matcher<vector<int> > m2 = Not(m);
  EXPECT_EQ("doesn't contain any element that is equal to 1", Describe(m2));
}
References Describe(), and EXPECT_EQ.
TEST() [22/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , ExplainsMatchResultCorrectly)
Definition at line 1173 of file gmock-generated-matchers_test.cc.
{
  const int a[2] = { 1, 2 };
  Matcher<const int (&)[2]> m = Contains(2);
  EXPECT_EQ("whose element #1 matches", Explain(m, a));
  m = Contains(3);
  EXPECT_EQ("", Explain(m, a));
  m = Contains(GreaterThan(0));
  EXPECT_EQ("whose element #0 matches, which is 1 more than 0", Explain(m, a));
  m = Contains(GreaterThan(10));
  EXPECT_EQ("", Explain(m, a));
}
References EXPECT_EQ, Explain(), and GreaterThan().
TEST() [23/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , ListDoesNotMatchWhenElementIsNotInContainer)
Definition at line 1138 of file gmock-generated-matchers_test.cc.
{
  list<int> some_list;
  some_list.push_back(3);
  some_list.push_back(1);
  EXPECT_THAT(some_list, Not(Contains(4)));
}
References EXPECT_THAT.
TEST() [24/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , ListMatchesWhenElementIsInContainer)
Definition at line 1121 of file gmock-generated-matchers_test.cc.
{
  list<int> some_list;
  some_list.push_back(3);
  some_list.push_back(1);
  some_list.push_back(2);
  EXPECT_THAT(some_list, Contains(1));
  EXPECT_THAT(some_list, Contains(Gt(2.5)));
  EXPECT_THAT(some_list, Contains(Eq(2.0f)));
  list<std::string> another_list;
  another_list.push_back("fee");
  another_list.push_back("fie");
  another_list.push_back("foe");
  another_list.push_back("fum");
  EXPECT_THAT(another_list, Contains(std::string("fee")));
}
References EXPECT_THAT.
TEST() [25/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , MapDoesNotMatchWhenElementIsNotInContainer)
Definition at line 1212 of file gmock-generated-matchers_test.cc.
{
  map<int, int> some_map;
  some_map[1] = 11;
  some_map[2] = 22;
  EXPECT_THAT(some_map, Not(Contains(pair<const int, int>(2, 23))));
}
References EXPECT_THAT.
TEST() [26/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , MapMatchesWhenElementIsInContainer)
Definition at line 1196 of file gmock-generated-matchers_test.cc.
{
  map<const char*, int> my_map;
  const char* bar = "a string";
  my_map[bar] = 2;
  EXPECT_THAT(my_map, Contains(pair<const char* const, int>(bar, 2)));
  map<std::string, int> another_map;
  another_map["fee"] = 1;
  another_map["fie"] = 2;
  another_map["foe"] = 3;
  another_map["fum"] = 4;
  EXPECT_THAT(another_map,
              Contains(pair<const std::string, int>(std::string("fee"), 1)));
  EXPECT_THAT(another_map, Contains(pair<const std::string, int>("fie", 2)));
}
References EXPECT_THAT.
TEST() [27/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , SetDoesNotMatchWhenElementIsNotInContainer)
Definition at line 1162 of file gmock-generated-matchers_test.cc.
{
  set<int> some_set;
  some_set.insert(3);
  some_set.insert(1);
  EXPECT_THAT(some_set, Not(Contains(4)));
  set<const char*> c_string_set;
  c_string_set.insert("hello");
  EXPECT_THAT(c_string_set, Not(Contains(std::string("hello").c_str())));
}
References EXPECT_THAT.
TEST() [28/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , SetMatchesWhenElementIsInContainer)
Definition at line 1145 of file gmock-generated-matchers_test.cc.
{
  set<int> some_set;
  some_set.insert(3);
  some_set.insert(1);
  some_set.insert(2);
  EXPECT_THAT(some_set, Contains(Eq(1.0)));
  EXPECT_THAT(some_set, Contains(Eq(3.0f)));
  EXPECT_THAT(some_set, Contains(2));
  set<const char*> another_set;
  another_set.insert("fee");
  another_set.insert("fie");
  another_set.insert("foe");
  another_set.insert("fum");
  EXPECT_THAT(another_set, Contains(Eq(std::string("fum"))));
}
References EXPECT_THAT.
TEST() [29/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , WorksForNativeArrayAsTuple)
Definition at line 1235 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2 };
  const int* const pointer = a;
  EXPECT_THAT(make_tuple(pointer, 2), Contains(1));
  EXPECT_THAT(make_tuple(pointer, 2), Not(Contains(Gt(3))));
}
References EXPECT_THAT.
TEST() [30/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ContainsTest , WorksForTwoDimensionalNativeArray)
Definition at line 1242 of file gmock-generated-matchers_test.cc.
{
  int a[][3] = { { 1, 2, 3 }, { 4, 5, 6 } };
  EXPECT_THAT(a, Contains(ElementsAre(4, 5, 6)));
  EXPECT_THAT(a, Contains(Contains(5)));
  EXPECT_THAT(a, Not(Contains(ElementsAre(3, 4, 5))));
  EXPECT_THAT(a, Contains(Not(Contains(5))));
}
References EXPECT_THAT.
TEST() [31/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithArraySize)
Definition at line 599 of file gmock-generated-matchers_test.cc.
{
  const char* a[] = { "one", "two", "three" };
  vector<std::string> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(test_vector, ElementsAreArray(a, GTEST_ARRAY_SIZE_(a)));
  const char** p = a;
  test_vector[0] = "1";
  EXPECT_THAT(test_vector, Not(ElementsAreArray(p, GTEST_ARRAY_SIZE_(a))));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [32/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithIteratorRange)
Definition at line 692 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2, 3 };
  const vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  const vector<int> expected(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(test_vector, ElementsAreArray(expected.begin(), expected.end()));
  // Pointers are iterators, too.
  EXPECT_THAT(test_vector, ElementsAreArray(a, a + GTEST_ARRAY_SIZE_(a)));
  // The empty range of NULL pointers should also be okay.
  int* const null_int = NULL;
  EXPECT_THAT(test_vector, Not(ElementsAreArray(null_int, null_int)));
  EXPECT_THAT((vector<int>()), ElementsAreArray(null_int, null_int));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [33/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithMatcherArray)
Definition at line 620 of file gmock-generated-matchers_test.cc.
{
  const Matcher<std::string> kMatcherArray[] = {StrEq("one"), StrEq("two"),
                                                StrEq("three")};
  vector<std::string> test_vector;
  test_vector.push_back("one");
  test_vector.push_back("two");
  test_vector.push_back("three");
  EXPECT_THAT(test_vector, ElementsAreArray(kMatcherArray));
  test_vector.push_back("three");
  EXPECT_THAT(test_vector, Not(ElementsAreArray(kMatcherArray)));
}
References EXPECT_THAT.
TEST() [34/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithMatcherVector)
Definition at line 681 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2, 3 };
  const Matcher<int> kMatchers[] = { Eq(1), Eq(2), Eq(3) };
  vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  const vector<Matcher<int> > expected(
      kMatchers, kMatchers + GTEST_ARRAY_SIZE_(kMatchers));
  EXPECT_THAT(test_vector, ElementsAreArray(expected));
  test_vector.push_back(4);
  EXPECT_THAT(test_vector, Not(ElementsAreArray(expected)));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [35/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithoutArraySize)
Definition at line 610 of file gmock-generated-matchers_test.cc.
{
  const char* a[] = { "one", "two", "three" };
  vector<std::string> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(test_vector, ElementsAreArray(a));
  test_vector[0] = "1";
  EXPECT_THAT(test_vector, Not(ElementsAreArray(a)));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [36/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithValueArray)
Definition at line 589 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2, 3 };
  vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(test_vector, ElementsAreArray(a));
  test_vector[2] = 0;
  EXPECT_THAT(test_vector, Not(ElementsAreArray(a)));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [37/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , CanBeCreatedWithVector)
Definition at line 634 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2, 3 };
  vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  const vector<int> expected(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(test_vector, ElementsAreArray(expected));
  test_vector.push_back(4);
  EXPECT_THAT(test_vector, Not(ElementsAreArray(expected)));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [38/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , SourceLifeSpan)
Definition at line 716 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 1, 2, 3 };
  vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  vector<int> expect(a, a + GTEST_ARRAY_SIZE_(a));
  ElementsAreArrayMatcher<int> matcher_maker =
      ElementsAreArray(expect.begin(), expect.end());
  EXPECT_THAT(test_vector, matcher_maker);
  // Changing in place the values that initialized matcher_maker should not
  // affect matcher_maker anymore. It should have made its own copy of them.
  typedef vector<int>::iterator Iter;
  for (Iter it = expect.begin(); it != expect.end(); ++it) { *it += 10; }
  EXPECT_THAT(test_vector, matcher_maker);
  test_vector.push_back(3);
  EXPECT_THAT(test_vector, Not(matcher_maker));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [39/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreArrayTest , WorksWithNativeArray)
Definition at line 707 of file gmock-generated-matchers_test.cc.
{
  ::std::string a[] = { "hi", "ho" };
  ::std::string b[] = { "hi", "ho" };
  EXPECT_THAT(a, ElementsAreArray(b));
  EXPECT_THAT(a, ElementsAreArray(b, 2));
  EXPECT_THAT(a, Not(ElementsAreArray(b, 1)));
}
References EXPECT_THAT.
TEST() [40/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , AcceptsArrayWithUnknownSize)
Definition at line 555 of file gmock-generated-matchers_test.cc.
{
  // The size of kHi is not known in this test, but ElementsAre() should
  // still accept it.
  std::string array1[] = {"hi"};
  EXPECT_THAT(array1, ElementsAre(kHi));
  std::string array2[] = {"ho"};
  EXPECT_THAT(array2, Not(ElementsAre(kHi)));
}
References EXPECT_THAT, and kHi.
TEST() [41/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , AcceptsStringLiteral)
Definition at line 539 of file gmock-generated-matchers_test.cc.
{
  std::string array[] = {"hi", "one", "two"};
  EXPECT_THAT(array, ElementsAre("hi", "one", "two"));
  EXPECT_THAT(array, Not(ElementsAre("hi", "one", "too")));
}
References EXPECT_THAT.
TEST() [42/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanDescribeExpectingManyElements)
Definition at line 308 of file gmock-generated-matchers_test.cc.
{
  Matcher<list<std::string> > m = ElementsAre(StrEq("one"), "two");
  EXPECT_EQ("has 2 elements where\n"
            "element #0 is equal to \"one\",\n"
            "element #1 is equal to \"two\"", Describe(m));
}
References Describe(), and EXPECT_EQ.
TEST() [43/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanDescribeExpectingNoElement)
Definition at line 298 of file gmock-generated-matchers_test.cc.
{
  Matcher<const vector<int>&> m = ElementsAre();
  EXPECT_EQ("is empty", Describe(m));
}
References Describe(), and EXPECT_EQ.
TEST() [44/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanDescribeExpectingOneElement)
Definition at line 303 of file gmock-generated-matchers_test.cc.
{
  Matcher<vector<int> > m = ElementsAre(Gt(5));
  EXPECT_EQ("has 1 element that is > 5", Describe(m));
}
References Describe(), and EXPECT_EQ.
TEST() [45/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanDescribeNegationOfExpectingManyElements)
Definition at line 326 of file gmock-generated-matchers_test.cc.
{
  Matcher<const list<std::string>&> m = ElementsAre("one", "two");
  EXPECT_EQ("doesn't have 2 elements, or\n"
            "element #0 isn't equal to \"one\", or\n"
            "element #1 isn't equal to \"two\"", DescribeNegation(m));
}
References DescribeNegation(), and EXPECT_EQ.
TEST() [46/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanDescribeNegationOfExpectingNoElement)
Definition at line 315 of file gmock-generated-matchers_test.cc.
{
  Matcher<vector<int> > m = ElementsAre();
  EXPECT_EQ("isn't empty", DescribeNegation(m));
}
References DescribeNegation(), and EXPECT_EQ.
TEST() [47/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanDescribeNegationOfExpectingOneElment)
Definition at line 320 of file gmock-generated-matchers_test.cc.
{
  Matcher<const list<int>& > m = ElementsAre(Gt(5));
  EXPECT_EQ("doesn't have 1 element, or\n"
            "element #0 isn't > 5", DescribeNegation(m));
}
References DescribeNegation(), and EXPECT_EQ.
TEST() [48/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanExplainMismatchRightSize)
Definition at line 364 of file gmock-generated-matchers_test.cc.
{
  Matcher<const vector<int>& > m = ElementsAre(1, GreaterThan(5));
  vector<int> v;
  v.push_back(2);
  v.push_back(1);
  EXPECT_EQ("whose element #0 doesn't match", Explain(m, v));
  v[0] = 1;
  EXPECT_EQ("whose element #1 doesn't match, which is 4 less than 5",
            Explain(m, v));
}
References EXPECT_EQ, Explain(), and GreaterThan().
TEST() [49/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , CanExplainMismatchWrongSize)
Definition at line 353 of file gmock-generated-matchers_test.cc.
{
  Matcher<const list<int>& > m = ElementsAre(1, 3);
  list<int> test_list;
  // No need to explain when the container is empty.
  EXPECT_EQ("", Explain(m, test_list));
  test_list.push_back(1);
  EXPECT_EQ("which has 1 element", Explain(m, test_list));
}
References EXPECT_EQ, and Explain().
TEST() [50/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , DoesNotExplainTrivialMatch)
Definition at line 333 of file gmock-generated-matchers_test.cc.
{
  Matcher<const list<int>& > m = ElementsAre(1, Ne(2));
  list<int> test_list;
  test_list.push_back(1);
  test_list.push_back(3);
  EXPECT_EQ("", Explain(m, test_list));  // No need to explain anything.
}
References EXPECT_EQ, and Explain().
TEST() [51/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , DoesNotMatchWrongOrder)
Definition at line 457 of file gmock-generated-matchers_test.cc.
{
  vector<std::string> test_vector;
  test_vector.push_back("one");
  test_vector.push_back("three");
  test_vector.push_back("two");
  Matcher<vector<std::string> > m =
      ElementsAre(StrEq("one"), StrEq("two"), StrEq("three"));
  EXPECT_FALSE(m.Matches(test_vector));
}
References EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST() [52/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , DoesNotMatchWrongSize)
Definition at line 440 of file gmock-generated-matchers_test.cc.
{
  vector<std::string> test_vector;
  test_vector.push_back("test string");
  test_vector.push_back("test string");
  Matcher<vector<std::string> > m = ElementsAre(StrEq("test string"));
  EXPECT_FALSE(m.Matches(test_vector));
}
References EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST() [53/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , DoesNotMatchWrongValue)
Definition at line 449 of file gmock-generated-matchers_test.cc.
{
  vector<std::string> test_vector;
  test_vector.push_back("other string");
  Matcher<vector<std::string> > m = ElementsAre(StrEq("test string"));
  EXPECT_FALSE(m.Matches(test_vector));
}
References EXPECT_FALSE, and testing::internal::MatcherBase< T >::Matches().
TEST() [54/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , ExplainsNonTrivialMatch)
Definition at line 342 of file gmock-generated-matchers_test.cc.
{
  Matcher<const vector<int>& > m =
      ElementsAre(GreaterThan(1), 0, GreaterThan(2));
  const int a[] = { 10, 0, 100 };
  vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_EQ("whose element #0 matches, which is 9 more than 1,\n"
            "and whose element #2 matches, which is 98 more than 2",
            Explain(m, test_vector));
}
References EXPECT_EQ, Explain(), GreaterThan(), and GTEST_ARRAY_SIZE_.
TEST() [55/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MakesCopyOfArguments)
Definition at line 570 of file gmock-generated-matchers_test.cc.
{
  int x = 1;
  int y = 2;
  // This should make a copy of x and y.
  ::testing::internal::ElementsAreMatcher<testing::tuple<int, int> >
          polymorphic_matcher = ElementsAre(x, y);
  // Changing x and y now shouldn't affect the meaning of the above matcher.
  x = y = 0;
  const int array1[] = { 1, 2 };
  EXPECT_THAT(array1, polymorphic_matcher);
  const int array2[] = { 0, 0 };
  EXPECT_THAT(array2, Not(polymorphic_matcher));
}
References EXPECT_THAT.
TEST() [56/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesOneElementAnyMatcher)
Definition at line 407 of file gmock-generated-matchers_test.cc.
{
  vector<int> test_vector;
  test_vector.push_back(4);
  EXPECT_THAT(test_vector, ElementsAre(_));
}
References EXPECT_THAT.
TEST() [57/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesOneElementEqMatcher)
Definition at line 400 of file gmock-generated-matchers_test.cc.
{
  vector<int> test_vector;
  test_vector.push_back(4);
  EXPECT_THAT(test_vector, ElementsAre(Eq(4)));
}
References EXPECT_THAT.
TEST() [58/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesOneElementList)
Definition at line 384 of file gmock-generated-matchers_test.cc.
{
  list<std::string> test_list;
  test_list.push_back("test string");
  EXPECT_THAT(test_list, ElementsAre("test string"));
}
References EXPECT_THAT.
TEST() [59/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesOneElementValue)
Definition at line 414 of file gmock-generated-matchers_test.cc.
{
  vector<int> test_vector;
  test_vector.push_back(4);
  EXPECT_THAT(test_vector, ElementsAre(4));
}
References EXPECT_THAT.
TEST() [60/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesOneElementVector)
Definition at line 377 of file gmock-generated-matchers_test.cc.
{
  vector<std::string> test_vector;
  test_vector.push_back("test string");
  EXPECT_THAT(test_vector, ElementsAre(StrEq("test string")));
}
References EXPECT_THAT.
TEST() [61/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesTenElementVector)
Definition at line 430 of file gmock-generated-matchers_test.cc.
{
  const int a[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
  vector<int> test_vector(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(test_vector,
              // The element list can contain values and/or matchers
              // of different types.
              ElementsAre(0, Ge(0), _, 3, 4, Ne(2), Eq(6), 7, 8, _));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [62/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesThreeElementsMixedMatchers)
Definition at line 421 of file gmock-generated-matchers_test.cc.
{
  vector<int> test_vector;
  test_vector.push_back(1);
  test_vector.push_back(2);
  test_vector.push_back(3);
  EXPECT_THAT(test_vector, ElementsAre(1, Eq(2), _));
}
References EXPECT_THAT.
TEST() [63/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , MatchesThreeElementVector)
Definition at line 391 of file gmock-generated-matchers_test.cc.
{
  vector<std::string> test_vector;
  test_vector.push_back("one");
  test_vector.push_back("two");
  test_vector.push_back("three");
  EXPECT_THAT(test_vector, ElementsAre("one", StrEq("two"), _));
}
References EXPECT_THAT.
TEST() [64/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , WorksForNestedContainer)
Definition at line 468 of file gmock-generated-matchers_test.cc.
{
  const char* strings[] = {
    "Hi",
    "world"
  };
  vector<list<char> > nested;
  for (size_t i = 0; i < GTEST_ARRAY_SIZE_(strings); i++) {
    nested.push_back(list<char>(strings[i], strings[i] + strlen(strings[i])));
  }
  EXPECT_THAT(nested, ElementsAre(ElementsAre('H', Ne('e')),
                                  ElementsAre('w', 'o', _, _, 'd')));
  EXPECT_THAT(nested, Not(ElementsAre(ElementsAre('H', 'e'),
                                      ElementsAre('w', 'o', _, _, 'd'))));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [65/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , WorksWithByRefElementMatchers)
Definition at line 485 of file gmock-generated-matchers_test.cc.
{
  int a[] = { 0, 1, 2 };
  vector<int> v(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(v, ElementsAre(Ref(v[0]), Ref(v[1]), Ref(v[2])));
  EXPECT_THAT(v, Not(ElementsAre(Ref(v[0]), Ref(v[1]), Ref(a[2]))));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [66/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , WorksWithContainerPointerUsingPointee)
Definition at line 493 of file gmock-generated-matchers_test.cc.
{
  int a[] = { 0, 1, 2 };
  vector<int> v(a, a + GTEST_ARRAY_SIZE_(a));
  EXPECT_THAT(&v, Pointee(ElementsAre(0, 1, _)));
  EXPECT_THAT(&v, Not(Pointee(ElementsAre(0, _, 3))));
}
References EXPECT_THAT, and GTEST_ARRAY_SIZE_.
TEST() [67/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , WorksWithNativeArrayPassedAsPointerAndSize)
Definition at line 518 of file gmock-generated-matchers_test.cc.
{
  int array[] = { 0, 1 };
  ::testing::tuple<int*, size_t> array_as_tuple(array, 2);
  EXPECT_THAT(array_as_tuple, ElementsAre(0, 1));
  EXPECT_THAT(array_as_tuple, Not(ElementsAre(0)));
  NativeArrayPassedAsPointerAndSize helper;
  EXPECT_CALL(helper, Helper(_, _))
      .With(ElementsAre(0, 1));
  helper.Helper(array, 2);
}
References EXPECT_CALL, and EXPECT_THAT.
TEST() [68/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , WorksWithNativeArrayPassedByReference)
Definition at line 501 of file gmock-generated-matchers_test.cc.
{
  int array[] = { 0, 1, 2 };
  EXPECT_THAT(array, ElementsAre(0, 1, _));
  EXPECT_THAT(array, Not(ElementsAre(1, _, _)));
  EXPECT_THAT(array, Not(ElementsAre(0, _)));
}
References EXPECT_THAT.
TEST() [69/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (ElementsAreTest , WorksWithTwoDimensionalNativeArray)
Definition at line 530 of file gmock-generated-matchers_test.cc.
{
  const char a2[][3] = { "hi", "lo" };
  EXPECT_THAT(a2, ElementsAre(ElementsAre('h', 'i', '\0'),
                              ElementsAre('l', 'o', '\0')));
  EXPECT_THAT(a2, ElementsAre(StrEq("hi"), StrEq("lo")));
  EXPECT_THAT(a2, ElementsAre(Not(ElementsAre('h', 'o', '\0')),
                              ElementsAre('l', 'o', '\0')));
}
References EXPECT_THAT.
TEST() [70/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherMacroTest , CanBeComposedUsingValue)
Definition at line 841 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(3, IsPositiveOdd());
  EXPECT_THAT(4, Not(IsPositiveOdd()));
  EXPECT_THAT(-1, Not(IsPositiveOdd()));
}
References EXPECT_THAT.
TEST() [71/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherMacroTest , CanExplainMatchResult)
Definition at line 793 of file gmock-generated-matchers_test.cc.
{
  const Matcher<int> m1 = IsEven2();
  EXPECT_EQ("OK", Explain(m1, 4));
  EXPECT_EQ("% 2 == 1", Explain(m1, 5));
  const Matcher<int> m2 = EqSumOf(1, 2);
  EXPECT_EQ("OK", Explain(m2, 3));
  EXPECT_EQ("diff == -1", Explain(m2, 4));
}
References EXPECT_EQ, and Explain().
TEST() [72/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherMacroTest , CanReferenceArgType)
Definition at line 816 of file gmock-generated-matchers_test.cc.
{
  const Matcher< ::std::string> m1 = IsEmptyString();
  EXPECT_TRUE(m1.Matches(""));
  const Matcher<const ::std::string&> m2 = IsEmptyStringByRef();
  EXPECT_TRUE(m2.Matches(""));
}
References EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [73/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherMacroTest , DescriptionCanReferenceNegationAndParameters)
Definition at line 782 of file gmock-generated-matchers_test.cc.
{
  const Matcher<int> m1 = IsEven2();
  EXPECT_EQ("is even", Describe(m1));
  EXPECT_EQ("is odd", DescribeNegation(m1));
  const Matcher<int> m2 = EqSumOf(5, 9);
  EXPECT_EQ("equals the sum of 5 and 9", Describe(m2));
  EXPECT_EQ("doesn't equal the sum of 5 and 9", DescribeNegation(m2));
}
References Describe(), DescribeNegation(), and EXPECT_EQ.
TEST() [74/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherMacroTest , Works)
Definition at line 738 of file gmock-generated-matchers_test.cc.
{
  const Matcher<int> m = IsEven();
  EXPECT_TRUE(m.Matches(6));
  EXPECT_FALSE(m.Matches(7));
  EXPECT_EQ("is even", Describe(m));
  EXPECT_EQ("not (is even)", DescribeNegation(m));
  EXPECT_EQ("", Explain(m, 6));
  EXPECT_EQ("", Explain(m, 7));
}
References Describe(), DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [75/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherMacroTest , WorksInNamespace)
Definition at line 830 of file gmock-generated-matchers_test.cc.
{
  Matcher<int> m = matcher_test::IsOdd();
  EXPECT_FALSE(m.Matches(4));
  EXPECT_TRUE(m.Matches(5));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [76/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPMacroTest , GeneratesCorrectDescription)
Definition at line 865 of file gmock-generated-matchers_test.cc.
{
  const Matcher<int> m = _is_Greater_Than32and_(5);
  EXPECT_EQ("is greater than 32 and 5", Describe(m));
  EXPECT_EQ("not (is greater than 32 and 5)", DescribeNegation(m));
  EXPECT_EQ("", Explain(m, 36));
  EXPECT_EQ("", Explain(m, 5));
}
References Describe(), DescribeNegation(), EXPECT_EQ, and Explain().
TEST() [77/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPMacroTest , Works)
Definition at line 851 of file gmock-generated-matchers_test.cc.
{
  const Matcher<int> m = IsGreaterThan32And(5);
  EXPECT_TRUE(m.Matches(36));
  EXPECT_FALSE(m.Matches(5));
  EXPECT_EQ("is greater than 32 and 5", Describe(m));
  EXPECT_EQ("not (is greater than 32 and 5)", DescribeNegation(m));
  EXPECT_EQ("", Explain(m, 36));
  EXPECT_EQ("", Explain(m, 5));
}
References Describe(), DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [78/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPMacroTest , WorksWhenExplicitlyInstantiatedWithReference)
Definition at line 889 of file gmock-generated-matchers_test.cc.
{
  UncopyableFoo foo1('1'), foo2('2');
  const Matcher<const UncopyableFoo&> m =
      ReferencesUncopyable<const UncopyableFoo&>(foo1);
  EXPECT_TRUE(m.Matches(foo1));
  EXPECT_FALSE(m.Matches(foo2));
  // We don't want the address of the parameter printed, as most
  // likely it will just annoy the user.  If the address is
  // interesting, the user should consider passing the parameter by
  // pointer instead.
  EXPECT_EQ("references uncopyable 1-byte object <31>", Describe(m));
}
References Describe(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [79/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , CanBeOverloadedOnNumberOfParameters)
Definition at line 990 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(0, EqualsSumOf());
  EXPECT_THAT(1, EqualsSumOf(1));
  EXPECT_THAT(12, EqualsSumOf(10, 2));
  EXPECT_THAT(123, EqualsSumOf(100, 20, 3));
  EXPECT_THAT(1234, EqualsSumOf(1000, 200, 30, 4));
  EXPECT_THAT(12345, EqualsSumOf(10000, 2000, 300, 40, 5));
  EXPECT_THAT("abcdef",
              EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f'));
  EXPECT_THAT("abcdefg",
              EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g'));
  EXPECT_THAT("abcdefgh",
              EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g',
                          "h"));
  EXPECT_THAT("abcdefghi",
              EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g',
                          "h", 'i'));
  EXPECT_THAT("abcdefghij",
              EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g',
                          "h", 'i', ::std::string("j")));
  EXPECT_THAT(1, Not(EqualsSumOf()));
  EXPECT_THAT(-1, Not(EqualsSumOf(1)));
  EXPECT_THAT(-12, Not(EqualsSumOf(10, 2)));
  EXPECT_THAT(-123, Not(EqualsSumOf(100, 20, 3)));
  EXPECT_THAT(-1234, Not(EqualsSumOf(1000, 200, 30, 4)));
  EXPECT_THAT(-12345, Not(EqualsSumOf(10000, 2000, 300, 40, 5)));
  EXPECT_THAT("abcdef ",
              Not(EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f')));
  EXPECT_THAT("abcdefg ",
              Not(EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f',
                              'g')));
  EXPECT_THAT("abcdefgh ",
              Not(EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g',
                              "h")));
  EXPECT_THAT("abcdefghi ",
              Not(EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g',
                              "h", 'i')));
  EXPECT_THAT("abcdefghij ",
              Not(EqualsSumOf(::std::string("a"), 'b', 'c', "d", "e", 'f', 'g',
                              "h", 'i', ::std::string("j"))));
}
References EXPECT_THAT.
TEST() [80/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , CanReferenceParamTypes)
Definition at line 915 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(0, ParamTypesAreIntLongAndChar(10, 20L, 'a'));
}
References EXPECT_THAT.
TEST() [81/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , CanUseMatcherTypedParameterInValue)
Definition at line 1114 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(42, TwoOf(Gt(0), Lt(50), Eq(10)));
  EXPECT_THAT(0, Not(TwoOf(Gt(-1), Lt(1), Eq(0))));
}
References EXPECT_THAT.
TEST() [82/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , GeneratesCorretDescriptionWhenExplicitlyInstantiatedWithReferences)
Definition at line 936 of file gmock-generated-matchers_test.cc.
{
  UncopyableFoo foo1('1'), foo2('2');
  const Matcher<const UncopyableFoo&> m =
      ReferencesAnyOf<const UncopyableFoo&, const UncopyableFoo&>(foo1, foo2);
  // We don't want the addresses of the parameters printed, as most
  // likely they will just annoy the user.  If the addresses are
  // interesting, the user should consider passing the parameters by
  // pointers instead.
  EXPECT_EQ("references any of (1-byte object <31>, 1-byte object <32>)",
            Describe(m));
}
References Describe(), and EXPECT_EQ.
TEST() [83/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , SimpleTypePromotion)
Definition at line 1052 of file gmock-generated-matchers_test.cc.
{
  Matcher<std::string> no_promo =
      EqConcat(std::string("foo"), 't');
  Matcher<const std::string&> promo =
      EqConcat("foo", static_cast<int>('t'));
  EXPECT_FALSE(no_promo.Matches("fool"));
  EXPECT_FALSE(promo.Matches("fool"));
  EXPECT_TRUE(no_promo.Matches("foot"));
  EXPECT_TRUE(promo.Matches("foot"));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
TEST() [84/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , TypesAreCorrect)
Definition at line 1065 of file gmock-generated-matchers_test.cc.
{
  // EqualsSumOf() must be assignable to a EqualsSumOfMatcher variable.
  EqualsSumOfMatcher a0 = EqualsSumOf();
  // EqualsSumOf(1) must be assignable to a EqualsSumOfMatcherP variable.
  EqualsSumOfMatcherP<int> a1 = EqualsSumOf(1);
  // EqualsSumOf(p1, ..., pk) must be assignable to a EqualsSumOfMatcherPk
  // variable, and so on.
  EqualsSumOfMatcherP2<int, char> a2 = EqualsSumOf(1, '2');
  EqualsSumOfMatcherP3<int, int, char> a3 = EqualsSumOf(1, 2, '3');
  EqualsSumOfMatcherP4<int, int, int, char> a4 = EqualsSumOf(1, 2, 3, '4');
  EqualsSumOfMatcherP5<int, int, int, int, char> a5 =
      EqualsSumOf(1, 2, 3, 4, '5');
  EqualsSumOfMatcherP6<int, int, int, int, int, char> a6 =
      EqualsSumOf(1, 2, 3, 4, 5, '6');
  EqualsSumOfMatcherP7<int, int, int, int, int, int, char> a7 =
      EqualsSumOf(1, 2, 3, 4, 5, 6, '7');
  EqualsSumOfMatcherP8<int, int, int, int, int, int, int, char> a8 =
      EqualsSumOf(1, 2, 3, 4, 5, 6, 7, '8');
  EqualsSumOfMatcherP9<int, int, int, int, int, int, int, int, char> a9 =
      EqualsSumOf(1, 2, 3, 4, 5, 6, 7, 8, '9');
  EqualsSumOfMatcherP10<int, int, int, int, int, int, int, int, int, char> a10 =
      EqualsSumOf(1, 2, 3, 4, 5, 6, 7, 8, 9, '0');
  // Avoid "unused variable" warnings.
  (void)a0;
  (void)a1;
  (void)a2;
  (void)a3;
  (void)a4;
  (void)a5;
  (void)a6;
  (void)a7;
  (void)a8;
  (void)a9;
  (void)a10;
}
TEST() [85/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , Works)
Definition at line 954 of file gmock-generated-matchers_test.cc.
{
  const Matcher<const long&> m = IsNotInClosedRange(10, 20);  // NOLINT
  EXPECT_TRUE(m.Matches(36L));
  EXPECT_FALSE(m.Matches(15L));
  EXPECT_EQ("is not in closed range (10, 20)", Describe(m));
  EXPECT_EQ("not (is not in closed range (10, 20))", DescribeNegation(m));
  EXPECT_EQ("", Explain(m, 36L));
  EXPECT_EQ("", Explain(m, 15L));
}
References Describe(), DescribeNegation(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), and testing::internal::MatcherBase< T >::Matches().
TEST() [86/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , WorksForDifferentParameterTypes)
Definition at line 1035 of file gmock-generated-matchers_test.cc.
{
  EXPECT_THAT(123, EqualsSumOf(100L, 20, static_cast<char>(3)));
  EXPECT_THAT("abcd", EqualsSumOf(::std::string("a"), "b", 'c', "d"));
  EXPECT_THAT(124, Not(EqualsSumOf(100L, 20, static_cast<char>(3))));
  EXPECT_THAT("abcde", Not(EqualsSumOf(::std::string("a"), "b", 'c', "d")));
}
References EXPECT_THAT.
TEST() [87/87]
anonymous_namespace{gmock-generated-matchers_test.cc}::TEST (MatcherPnMacroTest , WorksWhenExplicitlyInstantiatedWithReferences)
Definition at line 926 of file gmock-generated-matchers_test.cc.
{
  UncopyableFoo foo1('1'), foo2('2'), foo3('3');
  const Matcher<const UncopyableFoo&> m =
      ReferencesAnyOf<const UncopyableFoo&, const UncopyableFoo&>(foo1, foo2);
  EXPECT_TRUE(m.Matches(foo1));
  EXPECT_TRUE(m.Matches(foo2));
  EXPECT_FALSE(m.Matches(foo3));
}
References EXPECT_FALSE, EXPECT_TRUE, and testing::internal::MatcherBase< T >::Matches().
Variable Documentation
kHi
const char anonymous_namespace{gmock-generated-matchers_test.cc}::kHi = "hi"
Definition at line 566 of file gmock-generated-matchers_test.cc.