wiNpoS: anonymous_namespace{gtest-message_test.cc} Namespace Reference
anonymous_namespace{gtest-message_test.cc} Namespace Reference
Functions
TEST (MessageTest, DefaultConstructor)
TEST (MessageTest, CopyConstructor)
TEST (MessageTest, ConstructsFromCString)
TEST (MessageTest, StreamsFloat)
TEST (MessageTest, StreamsDouble)
TEST (MessageTest, StreamsPointer)
TEST (MessageTest, StreamsNullPointer)
TEST (MessageTest, StreamsCString)
TEST (MessageTest, StreamsNullCString)
TEST (MessageTest, StreamsString)
TEST (MessageTest, StreamsStringWithEmbeddedNUL)
TEST (MessageTest, StreamsNULChar)
TEST (MessageTest, StreamsInt)
TEST (MessageTest, StreamsBasicIoManip)
TEST (MessageTest, GetString)
TEST (MessageTest, StreamsToOStream)
TEST (MessageTest, DoesNotTakeUpMuchStackSpace)
Function Documentation
TEST() [1/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , ConstructsFromCString)
Definition at line 58 of file gtest-message_test.cc.
{
  Message msg("Hello");
  EXPECT_EQ("Hello", msg.GetString());
}
References EXPECT_EQ.
TEST() [2/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , CopyConstructor)
Definition at line 51 of file gtest-message_test.cc.
{
  const Message msg1("Hello");
  const Message msg2(msg1);
  EXPECT_EQ("Hello", msg2.GetString());
}
References EXPECT_EQ.
TEST() [3/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , DefaultConstructor)
Definition at line 45 of file gtest-message_test.cc.
{
  const Message msg;
  EXPECT_EQ("", msg.GetString());
}
References EXPECT_EQ.
TEST() [4/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , DoesNotTakeUpMuchStackSpace)
Definition at line 155 of file gtest-message_test.cc.
{
  EXPECT_LE(sizeof(Message), 16U);
}
References EXPECT_LE.
TEST() [5/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , GetString)
Definition at line 140 of file gtest-message_test.cc.
{
  Message msg;
  msg << 1 << " lamb";
  EXPECT_EQ("1 lamb", msg.GetString());
}
References EXPECT_EQ.
TEST() [6/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsBasicIoManip)
Definition at line 132 of file gtest-message_test.cc.
{
  EXPECT_EQ("Line 1.\nA NUL char \\0 in line 2.",
               (Message() << "Line 1." << std::endl
                         << "A NUL char " << std::ends << std::flush
                         << " in line 2.").GetString());
}
References EXPECT_EQ, and GetString().
TEST() [7/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsCString)
Definition at line 94 of file gtest-message_test.cc.
{
  EXPECT_EQ("Foo", (Message() << "Foo").GetString());
}
References EXPECT_EQ, and GetString().
TEST() [8/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsDouble)
Definition at line 72 of file gtest-message_test.cc.
{
  const std::string s = (Message() << 1260570880.4555497 << " "
                                  << 1260572265.1954534).GetString();
  // Both numbers should be printed with enough precision.
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "1260570880.45", s.c_str());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, " 1260572265.19", s.c_str());
}
References EXPECT_PRED_FORMAT2, GetString(), and testing::IsSubstring().
TEST() [9/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsFloat)
Definition at line 64 of file gtest-message_test.cc.
{
  const std::string s = (Message() << 1.23456F << " " << 2.34567F).GetString();
  // Both numbers should be printed with enough precision.
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "1.234560", s.c_str());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, " 2.345669", s.c_str());
}
References EXPECT_PRED_FORMAT2, GetString(), and testing::IsSubstring().
TEST() [10/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsInt)
Definition at line 126 of file gtest-message_test.cc.
{
  EXPECT_EQ("123", (Message() << 123).GetString());
}
References EXPECT_EQ, and GetString().
TEST() [11/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsNULChar)
Definition at line 121 of file gtest-message_test.cc.
{
  EXPECT_EQ("\\0", (Message() << '\0').GetString());
}
References EXPECT_EQ, and GetString().
TEST() [12/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsNullCString)
Definition at line 99 of file gtest-message_test.cc.
{
  char* p = NULL;
  EXPECT_EQ("(null)", (Message() << p).GetString());
}
References EXPECT_EQ, and GetString().
TEST() [13/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsNullPointer)
Definition at line 88 of file gtest-message_test.cc.
{
  int* p = NULL;
  EXPECT_EQ("(null)", (Message() << p).GetString());
}
References EXPECT_EQ, and GetString().
TEST() [14/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsPointer)
Definition at line 81 of file gtest-message_test.cc.
{
  int n = 0;
  int* p = &n;
  EXPECT_NE("(null)", (Message() << p).GetString());
}
References EXPECT_NE, and GetString().
TEST() [15/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsString)
Definition at line 105 of file gtest-message_test.cc.
{
  const ::std::string str("Hello");
  EXPECT_EQ("Hello", (Message() << str).GetString());
}
References EXPECT_EQ, and GetString().
TEST() [16/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsStringWithEmbeddedNUL)
Definition at line 111 of file gtest-message_test.cc.
{
  const char char_array_with_nul[] =
      "Here's a NUL\0 and some more string";
  const ::std::string string_with_nul(char_array_with_nul,
                                      sizeof(char_array_with_nul) - 1);
  EXPECT_EQ("Here's a NUL\\0 and some more string",
            (Message() << string_with_nul).GetString());
}
References EXPECT_EQ, and GetString().
TEST() [17/17]
anonymous_namespace{gtest-message_test.cc}::TEST (MessageTest , StreamsToOStream)
Definition at line 147 of file gtest-message_test.cc.
{
  Message msg("Hello");
  ::std::stringstream ss;
  ss << msg;
  EXPECT_EQ("Hello", testing::internal::StringStreamToString(&ss));
}
References EXPECT_EQ, and testing::internal::StringStreamToString().