wiNpoS: anonymous_namespace{gtest_unittest.cc} Namespace Reference
anonymous_namespace{gtest_unittest.cc} Namespace Reference
Classes
class AnotherSubClassOfTest
struct AssertIsEvenFunctor
struct AssertSumIsEven5Functor
class DisabledTestsTest
class FloatingPointTest
class Foo
class FormatEpochTimeInMillisAsIso8601Test
class FRIEND_TEST_Test2
class GTestFlagSaverTest
struct IsEvenFunctor
class MyTypeInUnnamedNameSpace
class NoFatalFailureTest
class ScopedFakeTestPartResultReporterTest
class ShouldShardTest
class SingleEvaluationTest
class SubClassOfTest
struct SumIsEven3Functor
class TestLifeCycleTest
class TestResultTest
class Uncopyable
class UnitTestRecordPropertyTest
class UnitTestRecordPropertyTestEnvironment
class UnprintableChar
class VectorShuffleTest
Typedefs
typedef ScopedFakeTestPartResultReporterTest ExpectFatalFailureTest
typedef ScopedFakeTestPartResultReporterTest ExpectNonfatalFailureTest
typedef TestResultTest TestResultDeathTest
typedef ShouldShardTest ShouldShardDeathTest
typedef FloatingPointTest< float > FloatTest
typedef FloatingPointTest< double > DoubleTest
Enumerations
enum NamedEnum { kE1 = 0 , kE2 = 1 }
enum { kCaseA = -1 , kCaseB = INT_MAX , kCaseC = 42 }
Functions
TEST (GetRandomSeedFromFlagTest, HandlesZero)
TEST (GetRandomSeedFromFlagTest, PreservesValidSeed)
TEST (GetRandomSeedFromFlagTest, NormalizesInvalidSeed)
TEST (GetNextRandomSeedTest, WorksForValidInput)
static void ClearCurrentTestPartResults ()
TEST (GetTypeIdTest, ReturnsSameValueForSameType)
TEST (GetTypeIdTest, ReturnsDifferentValuesForDifferentTypes)
TEST (GetTestTypeIdTest, ReturnsTheSameValueInsideOrOutsideOfGoogleTest)
TEST (CanonicalizeForStdLibVersioning, LeavesUnversionedNamesUnchanged)
TEST (CanonicalizeForStdLibVersioning, ElidesDoubleUnderNames)
TEST (FormatTimeInMillisAsSecondsTest, FormatsZero)
TEST (FormatTimeInMillisAsSecondsTest, FormatsPositiveNumber)
TEST (FormatTimeInMillisAsSecondsTest, FormatsNegativeNumber)
TEST_F (FormatEpochTimeInMillisAsIso8601Test, PrintsTwoDigitSegments)
TEST_F (FormatEpochTimeInMillisAsIso8601Test, MillisecondsDoNotAffectResult)
TEST_F (FormatEpochTimeInMillisAsIso8601Test, PrintsLeadingZeroes)
TEST_F (FormatEpochTimeInMillisAsIso8601Test, Prints24HourTime)
TEST_F (FormatEpochTimeInMillisAsIso8601Test, PrintsEpochStart)
TEST (CodePointToUtf8Test, CanEncodeNul)
TEST (CodePointToUtf8Test, CanEncodeAscii)
TEST (CodePointToUtf8Test, CanEncode8To11Bits)
TEST (CodePointToUtf8Test, CanEncode12To16Bits)
TEST (CodePointToUtf8Test, CanEncode17To21Bits)
TEST (CodePointToUtf8Test, CanEncodeInvalidCodePoint)
TEST (WideStringToUtf8Test, CanEncodeNul)
TEST (WideStringToUtf8Test, CanEncodeAscii)
TEST (WideStringToUtf8Test, CanEncode8To11Bits)
TEST (WideStringToUtf8Test, CanEncode12To16Bits)
TEST (WideStringToUtf8Test, StopsOnNulCharacter)
TEST (WideStringToUtf8Test, StopsWhenLengthLimitReached)
TEST (WideStringToUtf8Test, CanEncode17To21Bits)
TEST (WideStringToUtf8Test, CanEncodeInvalidCodePoint)
TEST (WideStringToUtf8Test, ConcatenatesCodepointsCorrectly)
TEST (RandomDeathTest, GeneratesCrashesOnInvalidRange)
TEST (RandomTest, GeneratesNumbersWithinRange)
TEST (RandomTest, RepeatsWhenReseeded)
static bool IsPositive (int n)
TEST (ContainerUtilityTest, CountIf)
static void Accumulate (int n)
TEST (ContainerUtilityTest, ForEach)
TEST (ContainerUtilityTest, GetElementOr)
TEST (ContainerUtilityDeathTest, ShuffleRange)
TEST_F (VectorShuffleTest, HandlesEmptyRange)
TEST_F (VectorShuffleTest, HandlesRangeOfSizeOne)
TEST_F (VectorShuffleTest, ShufflesEntireVector)
TEST_F (VectorShuffleTest, ShufflesStartOfVector)
TEST_F (VectorShuffleTest, ShufflesEndOfVector)
TEST_F (VectorShuffleTest, ShufflesMiddleOfVector)
TEST_F (VectorShuffleTest, ShufflesRepeatably)
TEST (AssertHelperTest, AssertHelperIsSmall)
TEST (StringTest, EndsWithCaseInsensitive)
TEST (StringTest, CaseInsensitiveWideCStringEquals)
TEST (TestPropertyTest, StringValue)
TEST (TestPropertyTest, ReplaceStringValue)
static void AddFatalFailure ()
static void AddNonfatalFailure ()
TEST_F (ScopedFakeTestPartResultReporterTest, InterceptsTestFailures)
TEST_F (ScopedFakeTestPartResultReporterTest, DeprecatedConstructor)
TEST_F (ExpectFatalFailureTest, CatchesFatalFaliure)
TEST_F (ExpectFatalFailureTest, AcceptsStdStringObject)
TEST_F (ExpectFatalFailureTest, CatchesFatalFailureOnAllThreads)
int NonVoidFunction ()
TEST_F (ExpectFatalFailureTest, CanBeUsedInNonVoidFunction)
void DoesNotAbortHelper (bool *aborted)
TEST_F (ExpectFatalFailureTest, DoesNotAbort)
TEST_F (ExpectFatalFailureTest, AcceptsMacroThatExpandsToUnprotectedComma)
TEST_F (ExpectNonfatalFailureTest, CatchesNonfatalFailure)
TEST_F (ExpectNonfatalFailureTest, CatchesNonfatalFailureOnAllThreads)
TEST (TestPropertyTest, ConstructorWorks)
TEST (TestPropertyTest, SetValue)
TEST_F (TestResultTest, total_part_count)
TEST_F (TestResultTest, Passed)
TEST_F (TestResultTest, Failed)
TEST_F (TestResultDeathTest, GetTestPartResult)
TEST (TestResultPropertyTest, NoPropertiesFoundWhenNoneAreAdded)
TEST (TestResultPropertyTest, OnePropertyFoundWhenAdded)
TEST (TestResultPropertyTest, MultiplePropertiesFoundWhenAdded)
TEST (TestResultPropertyTest, OverridesValuesForDuplicateKeys)
TEST (TestResultPropertyTest, GetTestProperty)
TEST_F (GTestFlagSaverTest, ModifyGTestFlags)
TEST_F (GTestFlagSaverTest, VerifyGTestFlags)
static void SetEnv (const char *name, const char *value)
TEST (Int32FromGTestEnvTest, ReturnsDefaultWhenVariableIsNotSet)
TEST (Int32FromGTestEnvTest, ReturnsDefaultWhenValueOverflows)
TEST (Int32FromGTestEnvTest, ReturnsDefaultWhenValueIsInvalid)
TEST (Int32FromGTestEnvTest, ParsesAndReturnsValidValue)
TEST (ParseInt32FlagTest, ReturnsFalseForInvalidFlag)
TEST (ParseInt32FlagTest, ReturnsDefaultWhenValueOverflows)
TEST (ParseInt32FlagTest, ReturnsDefaultWhenValueIsInvalid)
TEST (ParseInt32FlagTest, ParsesAndReturnsValidValue)
TEST (Int32FromEnvOrDieTest, ParsesAndReturnsValidValue)
TEST (Int32FromEnvOrDieDeathTest, AbortsOnFailure)
TEST (Int32FromEnvOrDieDeathTest, AbortsOnInt32Overflow)
TEST (ShouldRunTestOnShardTest, IsPartitionWhenThereIsOneShard)
TEST_F (ShouldShardTest, ReturnsFalseWhenNeitherEnvVarIsSet)
TEST_F (ShouldShardTest, ReturnsFalseWhenTotalShardIsOne)
TEST_F (ShouldShardTest, WorksWhenShardEnvVarsAreValid)
TEST_F (ShouldShardDeathTest, AbortsWhenShardingEnvVarsAreInvalid)
TEST (ShouldRunTestOnShardTest, IsPartitionWhenThereAreFiveShards)
TEST (UnitTestTest, CanGetOriginalWorkingDir)
TEST (UnitTestTest, ReturnsPlausibleTimestamp)
void ExpectNonFatalFailureRecordingPropertyWithReservedKey (const TestResult &test_result, const char *key)
void ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest (const char *key)
void ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase (const char *key)
void ExpectNonFatalFailureRecordingPropertyWithReservedKeyOutsideOfTestCase (const char *key)
TEST_F (UnitTestRecordPropertyTest, OnePropertyFoundWhenAdded)
TEST_F (UnitTestRecordPropertyTest, MultiplePropertiesFoundWhenAdded)
TEST_F (UnitTestRecordPropertyTest, OverridesValuesForDuplicateKeys)
TEST_F (UnitTestRecordPropertyTest, AddFailureInsideTestsWhenUsingTestCaseReservedKeys)
TEST_F (UnitTestRecordPropertyTest, AddRecordWithReservedKeysGeneratesCorrectPropertyList)
bool IsEven (int n)
AssertionResult AssertIsEven (const char *expr, int n)
AssertionResult ResultIsEven (int n)
AssertionResult ResultIsEvenNoExplanation (int n)
bool SumIsEven2 (int n1, int n2)
AssertionResult AssertSumIsEven4 (const char *e1, const char *e2, const char *e3, const char *e4, int n1, int n2, int n3, int n4)
TEST (Pred1Test, WithoutFormat)
TEST (Pred1Test, WithFormat)
TEST (Pred1Test, SingleEvaluationOnFailure)
TEST (PredTest, WithoutFormat)
TEST (PredTest, WithFormat)
TEST (PredTest, SingleEvaluationOnFailure)
bool IsPositive (double x)
template<typename T >
bool IsNegative (T x)
template<typename T1 , typename T2 >
bool GreaterThan (T1 x1, T2 x2)
TEST (PredicateAssertionTest, AcceptsOverloadedFunction)
TEST (PredicateAssertionTest, AcceptsTemplateFunction)
AssertionResult IsPositiveFormat (const char *, int n)
AssertionResult IsPositiveFormat (const char *, double x)
template<typename T >
AssertionResult IsNegativeFormat (const char *, T x)
template<typename T1 , typename T2 >
AssertionResult EqualsFormat (const char *, const char *, const T1 &x1, const T2 &x2)
TEST (PredicateFormatAssertionTest, AcceptsOverloadedFunction)
TEST (PredicateFormatAssertionTest, AcceptsTemplateFunction)
TEST (StringAssertionTest, ASSERT_STREQ)
TEST (StringAssertionTest, ASSERT_STREQ_Null)
TEST (StringAssertionTest, ASSERT_STREQ_Null2)
TEST (StringAssertionTest, ASSERT_STRNE)
TEST (StringAssertionTest, ASSERT_STRCASEEQ)
TEST (StringAssertionTest, ASSERT_STRCASENE)
TEST (StringAssertionTest, STREQ_Wide)
TEST (StringAssertionTest, STRNE_Wide)
TEST (IsSubstringTest, ReturnsCorrectResultForCString)
TEST (IsSubstringTest, ReturnsCorrectResultForWideCString)
TEST (IsSubstringTest, GeneratesCorrectMessageForCString)
TEST (IsSubstringTest, ReturnsCorrectResultsForStdString)
TEST (IsNotSubstringTest, ReturnsCorrectResultForCString)
TEST (IsNotSubstringTest, ReturnsCorrectResultForWideCString)
TEST (IsNotSubstringTest, GeneratesCorrectMessageForWideCString)
TEST (IsNotSubstringTest, ReturnsCorrectResultsForStdString)
TEST (IsNotSubstringTest, GeneratesCorrectMessageForStdString)
TEST_F (FloatTest, Size)
TEST_F (FloatTest, Zeros)
TEST_F (FloatTest, AlmostZeros)
TEST_F (FloatTest, SmallDiff)
TEST_F (FloatTest, LargeDiff)
TEST_F (FloatTest, Infinity)
TEST_F (FloatTest, NaN)
TEST_F (FloatTest, Reflexive)
TEST_F (FloatTest, Commutative)
TEST_F (FloatTest, EXPECT_NEAR)
TEST_F (FloatTest, ASSERT_NEAR)
TEST_F (FloatTest, FloatLESucceeds)
TEST_F (FloatTest, FloatLEFails)
TEST_F (DoubleTest, Size)
TEST_F (DoubleTest, Zeros)
TEST_F (DoubleTest, AlmostZeros)
TEST_F (DoubleTest, SmallDiff)
TEST_F (DoubleTest, LargeDiff)
TEST_F (DoubleTest, Infinity)
TEST_F (DoubleTest, NaN)
TEST_F (DoubleTest, Reflexive)
TEST_F (DoubleTest, Commutative)
TEST_F (DoubleTest, EXPECT_NEAR)
TEST_F (DoubleTest, ASSERT_NEAR)
TEST_F (DoubleTest, DoubleLESucceeds)
TEST_F (DoubleTest, DoubleLEFails)
TEST (DisabledTest, DISABLED_TestShouldNotRun)
TEST (DisabledTest, NotDISABLED_TestShouldRun)
TEST (DISABLED_TestCase, TestShouldNotRun)
TEST (DISABLED_TestCase, DISABLED_TestShouldNotRun)
TEST_F (DisabledTestsTest, DISABLED_TestShouldNotRun_1)
TEST_F (DisabledTestsTest, DISABLED_TestShouldNotRun_2)
TEST_F (SingleEvaluationTest, FailedASSERT_STREQ)
TEST_F (SingleEvaluationTest, ASSERT_STR)
TEST_F (SingleEvaluationTest, FailedASSERT_NE)
TEST_F (SingleEvaluationTest, OtherCases)
TEST_F (NoFatalFailureTest, NoFailure)
TEST_F (NoFatalFailureTest, NonFatalIsNoFailure)
TEST_F (NoFatalFailureTest, AssertNoFatalFailureOnFatalFailure)
TEST_F (NoFatalFailureTest, ExpectNoFatalFailureOnFatalFailure)
TEST_F (NoFatalFailureTest, MessageIsStreamable)
std::string EditsToString (const std::vector< EditType > &edits)
std::vector< size_t > CharsToIndices (const std::string &str)
std::vector< std::string > CharsToLines (const std::string &str)
TEST (EditDistance, TestCases)
TEST (AssertionTest, EqFailure)
TEST (AssertionTest, EqFailureWithDiff)
TEST (AssertionTest, AppendUserMessage)
TEST (AssertionTest, ASSERT_TRUE)
TEST (AssertionTest, AssertTrueWithAssertionResult)
TEST (AssertionTest, ASSERT_FALSE)
TEST (AssertionTest, AssertFalseWithAssertionResult)
TEST (ExpectTest, ASSERT_EQ_Double)
TEST (AssertionTest, ASSERT_EQ)
TEST (ExpectTest, ASSERT_EQ_0)
TEST (AssertionTest, ASSERT_NE)
TEST (AssertionTest, ASSERT_LE)
TEST (AssertionTest, ASSERT_LT)
TEST (AssertionTest, ASSERT_GE)
TEST (AssertionTest, ASSERT_GT)
TEST (AssertionTest, AssertPrecedence)
void TestEq1 (int x)
TEST (AssertionTest, NonFixtureSubroutine)
::std::ostream & operator<< (::std::ostream &os, const Uncopyable &value)
bool IsPositiveUncopyable (const Uncopyable &x)
void TestAssertNonPositive ()
void TestAssertEqualsUncopyable ()
TEST (AssertionTest, AssertWorksWithUncopyableObject)
TEST (AssertionTest, ExpectWorksWithUncopyableObject)
TEST (AssertionTest, NamedEnum)
TEST (AssertionTest, AnonymousEnum)
TEST (AssertionSyntaxTest, BasicAssertionsBehavesLikeSingleStatement)
TEST (AssertionSyntaxTest, NoFatalFailureAssertionsBehavesLikeSingleStatement)
TEST (AssertionSyntaxTest, WorksWithSwitch)
TEST (AssertionWithMessageTest, EXPECT)
TEST (AssertionWithMessageTest, ASSERT)
TEST (AssertionWithMessageTest, ASSERT_STR)
TEST (AssertionWithMessageTest, ASSERT_FLOATING)
TEST (AssertionWithMessageTest, ASSERT_FALSE)
TEST (AssertionWithMessageTest, FAIL)
TEST (AssertionWithMessageTest, SUCCEED)
TEST (AssertionWithMessageTest, ASSERT_TRUE)
TEST (ExpectTest, EXPECT_TRUE)
TEST (ExpectTest, ExpectTrueWithAssertionResult)
TEST (ExpectTest, EXPECT_FALSE)
TEST (ExpectTest, ExpectFalseWithAssertionResult)
TEST (ExpectTest, EXPECT_EQ)
TEST (ExpectTest, EXPECT_EQ_Double)
TEST (ExpectTest, EXPECT_EQ_0)
TEST (ExpectTest, EXPECT_NE)
TEST (ExpectTest, EXPECT_LE)
TEST (ExpectTest, EXPECT_LT)
TEST (ExpectTest, EXPECT_GE)
TEST (ExpectTest, EXPECT_GT)
TEST (ExpectTest, ExpectPrecedence)
TEST (StreamableToStringTest, Scalar)
TEST (StreamableToStringTest, Pointer)
TEST (StreamableToStringTest, NullPointer)
TEST (StreamableToStringTest, CString)
TEST (StreamableToStringTest, NullCString)
TEST (StreamableTest, string)
TEST (StreamableTest, stringWithEmbeddedNUL)
TEST (StreamableTest, NULChar)
TEST (StreamableTest, int)
TEST (StreamableTest, NullCharPtr)
TEST (StreamableTest, BasicIoManip)
void AddFailureHelper (bool *aborted)
TEST (MacroTest, ADD_FAILURE)
TEST (MacroTest, ADD_FAILURE_AT)
TEST (MacroTest, FAIL)
TEST (MacroTest, SUCCEED)
TEST (EqAssertionTest, Bool)
TEST (EqAssertionTest, Int)
TEST (EqAssertionTest, Time_T)
TEST (EqAssertionTest, Char)
TEST (EqAssertionTest, WideChar)
TEST (EqAssertionTest, StdString)
TEST (EqAssertionTest, CharPointer)
TEST (EqAssertionTest, WideCharPointer)
TEST (EqAssertionTest, OtherPointer)
TEST (ComparisonAssertionTest, AcceptsUnprintableArgs)
TEST (FRIEND_TEST_Test, TEST)
TEST_F (FRIEND_TEST_Test2, TEST_F)
TEST_F (TestLifeCycleTest, Test1)
TEST_F (TestLifeCycleTest, Test2)
std::ostream & operator<< (std::ostream &os, const MyTypeInUnnamedNameSpace &val)
std::ostream & operator<< (std::ostream &os, const MyTypeInUnnamedNameSpace *pointer)
Variables
static int g_sum = 0
static const wchar_t *const kNull = NULL
static int global_var = 0
static Environment * record_property_env
Typedef Documentation
DoubleTest
typedef FloatingPointTest<double> anonymous_namespace{gtest_unittest.cc}::DoubleTest private
Definition at line 2942 of file gtest_unittest.cc.
ExpectFatalFailureTest
typedef ScopedFakeTestPartResultReporterTest anonymous_namespace{gtest_unittest.cc}::ExpectFatalFailureTest private
Definition at line 1193 of file gtest_unittest.cc.
ExpectNonfatalFailureTest
typedef ScopedFakeTestPartResultReporterTest anonymous_namespace{gtest_unittest.cc}::ExpectNonfatalFailureTest private
Definition at line 1280 of file gtest_unittest.cc.
FloatTest
typedef FloatingPointTest<float> anonymous_namespace{gtest_unittest.cc}::FloatTest private
Definition at line 2769 of file gtest_unittest.cc.
ShouldShardDeathTest
typedef ShouldShardTest anonymous_namespace{gtest_unittest.cc}::ShouldShardDeathTest private
Definition at line 1889 of file gtest_unittest.cc.
TestResultDeathTest
typedef TestResultTest anonymous_namespace{gtest_unittest.cc}::TestResultDeathTest private
Definition at line 1452 of file gtest_unittest.cc.
Enumeration Type Documentation
anonymous enum
anonymous enum private
Enumerator
kCaseA
kCaseB
kCaseC
Definition at line 3931 of file gtest_unittest.cc.
     {
  kCaseA = -1,
# if GTEST_OS_LINUX
  // We want to test the case where the size of the anonymous enum is
  // larger than sizeof(int), to make sure our implementation of the
  // assertions doesn't truncate the enums.  However, MSVC
  // (incorrectly) doesn't allow an enum value to exceed the range of
  // an int, so this has to be conditionally compiled.
  //
  // On Linux, kCaseB and kCaseA have the same value when truncated to
  // int size.  We want to test whether this will confuse the
  // assertions.
  kCaseB = testing::internal::kMaxBiggestInt,
# else
  kCaseB = INT_MAX,
# endif  // GTEST_OS_LINUX
  kCaseC = 42
};
NamedEnum
enum anonymous_namespace{gtest_unittest.cc}::NamedEnum private
Enumerator
kE1
kE2
Definition at line 3912 of file gtest_unittest.cc.
               {
  kE1 = 0,
  kE2 = 1
};
Function Documentation
Accumulate()
static void anonymous_namespace{gtest_unittest.cc}::Accumulate (int n) static private
Definition at line 799 of file gtest_unittest.cc.
{ g_sum += n; }
References g_sum.
AddFailureHelper()
void anonymous_namespace{gtest_unittest.cc}::AddFailureHelper (bool * aborted) private
Definition at line 4666 of file gtest_unittest.cc.
{
  *aborted = true;
  ADD_FAILURE() << "Intentional failure.";
  *aborted = false;
}
References ADD_FAILURE.
AddFatalFailure()
static void anonymous_namespace{gtest_unittest.cc}::AddFatalFailure () static private
Definition at line 1107 of file gtest_unittest.cc.
{
  FAIL() << "Expected fatal failure.";
}
References FAIL.
AddNonfatalFailure()
static void anonymous_namespace{gtest_unittest.cc}::AddNonfatalFailure () static private
Definition at line 1111 of file gtest_unittest.cc.
{
  ADD_FAILURE() << "Expected non-fatal failure.";
}
References ADD_FAILURE.
AssertIsEven()
AssertionResult anonymous_namespace{gtest_unittest.cc}::AssertIsEven (const char * expr, int n) private
Definition at line 2145 of file gtest_unittest.cc.
{
  if (IsEven(n)) {
    return AssertionSuccess();
  }
  Message msg;
  msg << expr << " evaluates to " << n << ", which is not even.";
  return AssertionFailure(msg);
}
References IsEven().
AssertSumIsEven4()
AssertionResult anonymous_namespace{gtest_unittest.cc}::AssertSumIsEven4 (const char * e1, const char * e2, const char * e3, const char * e4, int n1, int n2, int n3, int n4) private
Definition at line 2197 of file gtest_unittest.cc.
{
  const int sum = n1 + n2 + n3 + n4;
  if (IsEven(sum)) {
    return AssertionSuccess();
  }
  Message msg;
  msg << e1 << " + " << e2 << " + " << e3 << " + " << e4
      << " (" << n1 << " + " << n2 << " + " << n3 << " + " << n4
      << ") evaluates to " << sum << ", which is not even.";
  return AssertionFailure(msg);
}
References IsEven().
CharsToIndices()
std::vector< size_t > anonymous_namespace{gtest_unittest.cc}::CharsToIndices (const std::string & str) private
Definition at line 3483 of file gtest_unittest.cc.
{
  std::vector<size_t> out;
  for (size_t i = 0; i < str.size(); ++i) {
    out.push_back(str[i]);
  }
  return out;
}
CharsToLines()
std::vector< std::string > anonymous_namespace{gtest_unittest.cc}::CharsToLines (const std::string & str) private
Definition at line 3491 of file gtest_unittest.cc.
{
  std::vector<std::string> out;
  for (size_t i = 0; i < str.size(); ++i) {
    out.push_back(str.substr(i, 1));
  }
  return out;
}
ClearCurrentTestPartResults()
static void anonymous_namespace{gtest_unittest.cc}::ClearCurrentTestPartResults () static private
Definition at line 353 of file gtest_unittest.cc.
{
  TestResultAccessor::ClearTestPartResults(
      GetUnitTestImpl()->current_test_result());
}
References testing::internal::TestResultAccessor::ClearTestPartResults().
DoesNotAbortHelper()
void anonymous_namespace{gtest_unittest.cc}::DoesNotAbortHelper (bool * aborted) private
Definition at line 1238 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(false), "");
  EXPECT_FATAL_FAILURE_ON_ALL_THREADS(FAIL(), "");
  *aborted = false;
}
References ASSERT_TRUE, EXPECT_FATAL_FAILURE, EXPECT_FATAL_FAILURE_ON_ALL_THREADS, and FAIL.
EditsToString()
std::string anonymous_namespace{gtest_unittest.cc}::EditsToString (const std::vector< EditType > & edits) private
Definition at line 3474 of file gtest_unittest.cc.
{
  std::string out;
  for (size_t i = 0; i < edits.size(); ++i) {
    static const char kEdits[] = " +-/";
    out.append(1, kEdits[edits[i]]);
  }
  return out;
}
EqualsFormat()
template<typename T1 , typename T2 > AssertionResult anonymous_namespace{gtest_unittest.cc}::EqualsFormat (const char * , const char * , const T1 & x1, const T2 & x2) private
Definition at line 2423 of file gtest_unittest.cc.
{
  return x1 == x2 ? AssertionSuccess() :
      AssertionFailure(Message() << "Failure");
}
ExpectNonFatalFailureRecordingPropertyWithReservedKey()
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKey (const TestResult & test_result, const char * key) private
Definition at line 1966 of file gtest_unittest.cc.
{
  EXPECT_NONFATAL_FAILURE(Test::RecordProperty(key, "1"), "Reserved key");
  ASSERT_EQ(0, test_result.test_property_count()) << "Property for key '" << key
                                                  << "' recorded unexpectedly.";
}
References ASSERT_EQ, EXPECT_NONFATAL_FAILURE, and testing::TestResult::test_property_count().
ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest()
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest (const char * key) private
Definition at line 1973 of file gtest_unittest.cc.
                     {
  const TestInfo* test_info = UnitTest::GetInstance()->current_test_info();
  ASSERT_TRUE(test_info != NULL);
  ExpectNonFatalFailureRecordingPropertyWithReservedKey(*test_info->result(),
                                                        key);
}
References ASSERT_TRUE, testing::UnitTest::current_test_info(), ExpectNonFatalFailureRecordingPropertyWithReservedKey(), testing::UnitTest::GetInstance(), and testing::TestInfo::result().
ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase()
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase (const char * key) private
Definition at line 1981 of file gtest_unittest.cc.
                     {
  const TestCase* test_case = UnitTest::GetInstance()->current_test_case();
  ASSERT_TRUE(test_case != NULL);
  ExpectNonFatalFailureRecordingPropertyWithReservedKey(
      test_case->ad_hoc_test_result(), key);
}
References testing::TestCase::ad_hoc_test_result(), ASSERT_TRUE, testing::UnitTest::current_test_case(), ExpectNonFatalFailureRecordingPropertyWithReservedKey(), and testing::UnitTest::GetInstance().
ExpectNonFatalFailureRecordingPropertyWithReservedKeyOutsideOfTestCase()
void anonymous_namespace{gtest_unittest.cc}::ExpectNonFatalFailureRecordingPropertyWithReservedKeyOutsideOfTestCase (const char * key) private
Definition at line 1989 of file gtest_unittest.cc.
                     {
  ExpectNonFatalFailureRecordingPropertyWithReservedKey(
      UnitTest::GetInstance()->ad_hoc_test_result(), key);
}
References ExpectNonFatalFailureRecordingPropertyWithReservedKey(), and testing::UnitTest::GetInstance().
GreaterThan()
template<typename T1 , typename T2 > bool anonymous_namespace{gtest_unittest.cc}::GreaterThan (T1 x1, T2 x2) private
Definition at line 2381 of file gtest_unittest.cc.
{
  return x1 > x2;
}
IsEven()
bool anonymous_namespace{gtest_unittest.cc}::IsEven (int n) private
Definition at line 2134 of file gtest_unittest.cc.
                   {
  return (n % 2) == 0;
}
IsNegative()
template<typename T > bool anonymous_namespace{gtest_unittest.cc}::IsNegative (T x) private
Definition at line 2376 of file gtest_unittest.cc.
                     {
  return x < 0;
}
IsNegativeFormat()
template<typename T > AssertionResult anonymous_namespace{gtest_unittest.cc}::IsNegativeFormat (const char * , T x) private
Definition at line 2417 of file gtest_unittest.cc.
{
  return x < 0 ? AssertionSuccess() :
      AssertionFailure(Message() << "Failure");
}
IsPositive() [1/2]
bool anonymous_namespace{gtest_unittest.cc}::IsPositive (double x) private
Definition at line 2371 of file gtest_unittest.cc.
{
  return x > 0;
}
IsPositive() [2/2]
static bool anonymous_namespace{gtest_unittest.cc}::IsPositive (int n) static private
Definition at line 780 of file gtest_unittest.cc.
{ return n > 0; }
IsPositiveFormat() [1/2]
AssertionResult anonymous_namespace{gtest_unittest.cc}::IsPositiveFormat (const char * , double x) private
Definition at line 2411 of file gtest_unittest.cc.
{
  return x > 0 ? AssertionSuccess() :
      AssertionFailure(Message() << "Failure");
}
IsPositiveFormat() [2/2]
AssertionResult anonymous_namespace{gtest_unittest.cc}::IsPositiveFormat (const char * , int n) private
Definition at line 2406 of file gtest_unittest.cc.
{
  return n > 0 ? AssertionSuccess() :
      AssertionFailure(Message() << "Failure");
}
IsPositiveUncopyable()
bool anonymous_namespace{gtest_unittest.cc}::IsPositiveUncopyable (const Uncopyable & x) private
Definition at line 3871 of file gtest_unittest.cc.
{
  return x.value() > 0;
}
References anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
NonVoidFunction()
int anonymous_namespace{gtest_unittest.cc}::NonVoidFunction () private
Definition at line 1225 of file gtest_unittest.cc.
                      {
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(false), "");
  EXPECT_FATAL_FAILURE_ON_ALL_THREADS(FAIL(), "");
  return 0;
}
References ASSERT_TRUE, EXPECT_FATAL_FAILURE, EXPECT_FATAL_FAILURE_ON_ALL_THREADS, and FAIL.
operator<<() [1/3]
::std::ostream & anonymous_namespace{gtest_unittest.cc}::operator<< (::std::ostream & os, const Uncopyable & value) private
Definition at line 3864 of file gtest_unittest.cc.
{
  return os << value.value();
}
operator<<() [2/3]
std::ostream & anonymous_namespace{gtest_unittest.cc}::operator<< (std::ostream & os, const MyTypeInUnnamedNameSpace & val) private
Definition at line 5219 of file gtest_unittest.cc.
{
  return os << val.x();
}
References Base::x().
operator<<() [3/3]
std::ostream & anonymous_namespace{gtest_unittest.cc}::operator<< (std::ostream & os, const MyTypeInUnnamedNameSpace * pointer) private
Definition at line 5223 of file gtest_unittest.cc.
{
  return os << "(" << pointer->x() << ")";
}
ResultIsEven()
AssertionResult anonymous_namespace{gtest_unittest.cc}::ResultIsEven (int n) private
Definition at line 2157 of file gtest_unittest.cc.
{
  if (IsEven(n))
    return AssertionSuccess() << n << " is even";
  else
    return AssertionFailure() << n << " is odd";
}
References IsEven().
ResultIsEvenNoExplanation()
AssertionResult anonymous_namespace{gtest_unittest.cc}::ResultIsEvenNoExplanation (int n) private
Definition at line 2167 of file gtest_unittest.cc.
{
  if (IsEven(n))
    return AssertionSuccess();
  else
    return AssertionFailure() << n << " is odd";
}
References IsEven().
SetEnv()
static void anonymous_namespace{gtest_unittest.cc}::SetEnv (const char * name, const char * value) static private
Definition at line 1648 of file gtest_unittest.cc.
{
#if GTEST_OS_WINDOWS_MOBILE
  // Environment variables are not supported on Windows CE.
  return;
#elif defined(__BORLANDC__) || defined(__SunOS_5_8) || defined(__SunOS_5_9)
  // C++Builder's putenv only stores a pointer to its parameter; we have to
  // ensure that the string remains valid as long as it might be needed.
  // We use an std::map to do so.
  static std::map<std::string, std::string*> added_env;
  // Because putenv stores a pointer to the string buffer, we can't delete the
  // previous string (if present) until after it's replaced.
  std::string *prev_env = NULL;
  if (added_env.find(name) != added_env.end()) {
    prev_env = added_env[name];
  }
  added_env[name] = new std::string(
      (Message() << name << "=" << value).GetString());
  // The standard signature of putenv accepts a 'char*' argument. Other
  // implementations, like C++Builder's, accept a 'const char*'.
  // We cast away the 'const' since that would work for both variants.
  putenv(const_cast<char*>(added_env[name]->c_str()));
  delete prev_env;
#elif GTEST_OS_WINDOWS  // If we are on Windows proper.
  _putenv((Message() << name << "=" << value).GetString().c_str());
#else
  if (*value == '\0') {
    unsetenv(name);
  } else {
    setenv(name, value, 1);
  }
#endif  // GTEST_OS_WINDOWS_MOBILE
}
References GetString(), and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
SumIsEven2()
bool anonymous_namespace{gtest_unittest.cc}::SumIsEven2 (int n1, int n2) private
Definition at line 2183 of file gtest_unittest.cc.
{
  return IsEven(n1 + n2);
}
References IsEven().
TEST() [1/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertHelperTest , AssertHelperIsSmall) private
Definition at line 1017 of file gtest_unittest.cc.
{
  // To avoid breaking clients that use lots of assertions in one
  // function, we cannot grow the size of AssertHelper.
  EXPECT_LE(sizeof(testing::internal::AssertHelper), sizeof(void*));
}
References EXPECT_LE.
TEST() [2/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionSyntaxTest , BasicAssertionsBehavesLikeSingleStatement) private
Definition at line 4095 of file gtest_unittest.cc.
{
  if (AlwaysFalse())
    ASSERT_TRUE(false) << "This should never be executed; "
                          "It's a compilation test only.";
  if (AlwaysTrue())
    EXPECT_FALSE(false);
  else
    ;  // NOLINT
  if (AlwaysFalse())
    ASSERT_LT(1, 3);
  if (AlwaysFalse())
    ;  // NOLINT
  else
    EXPECT_GT(3, 2) << "";
}
References ASSERT_LT, ASSERT_TRUE, EXPECT_FALSE, and EXPECT_GT.
TEST() [3/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionSyntaxTest , NoFatalFailureAssertionsBehavesLikeSingleStatement) private
Definition at line 4156 of file gtest_unittest.cc.
{
  if (AlwaysFalse())
    EXPECT_NO_FATAL_FAILURE(FAIL()) << "This should never be executed. "
                                    << "It's a compilation test only.";
  else
    ;  // NOLINT
  if (AlwaysFalse())
    ASSERT_NO_FATAL_FAILURE(FAIL()) << "";
  else
    ;  // NOLINT
  if (AlwaysTrue())
    EXPECT_NO_FATAL_FAILURE(SUCCEED());
  else
    ;  // NOLINT
  if (AlwaysFalse())
    ;  // NOLINT
  else
    ASSERT_NO_FATAL_FAILURE(SUCCEED());
}
References ASSERT_NO_FATAL_FAILURE, EXPECT_NO_FATAL_FAILURE, FAIL, and SUCCEED.
TEST() [4/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionSyntaxTest , WorksWithSwitch) private
Definition at line 4180 of file gtest_unittest.cc.
{
  switch (0) {
    case 1:
      break;
    default:
      ASSERT_TRUE(true);
  }
  switch (0)
    case 0:
      EXPECT_FALSE(false) << "EXPECT_FALSE failed in switch case";
  // Binary assertions are implemented using a different code path
  // than the Boolean assertions.  Hence we test them separately.
  switch (0) {
    case 1:
    default:
      ASSERT_EQ(1, 1) << "ASSERT_EQ failed in default switch handler";
  }
  switch (0)
    case 0:
      EXPECT_NE(1, 2);
}
References ASSERT_EQ, ASSERT_TRUE, EXPECT_FALSE, and EXPECT_NE.
TEST() [5/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , AnonymousEnum) private
Definition at line 3956 of file gtest_unittest.cc.
{
# if GTEST_OS_LINUX
  EXPECT_EQ(static_cast<int>(kCaseA), static_cast<int>(kCaseB));
# endif  // GTEST_OS_LINUX
  EXPECT_EQ(kCaseA, kCaseA);
  EXPECT_NE(kCaseA, kCaseB);
  EXPECT_LT(kCaseA, kCaseB);
  EXPECT_LE(kCaseA, kCaseB);
  EXPECT_GT(kCaseB, kCaseA);
  EXPECT_GE(kCaseA, kCaseA);
  EXPECT_NONFATAL_FAILURE(EXPECT_GE(kCaseA, kCaseB),
                          "(kCaseA) >= (kCaseB)");
  EXPECT_NONFATAL_FAILURE(EXPECT_GE(kCaseA, kCaseC),
                          "-1 vs 42");
  ASSERT_EQ(kCaseA, kCaseA);
  ASSERT_NE(kCaseA, kCaseB);
  ASSERT_LT(kCaseA, kCaseB);
  ASSERT_LE(kCaseA, kCaseB);
  ASSERT_GT(kCaseB, kCaseA);
  ASSERT_GE(kCaseA, kCaseA);
# ifndef __BORLANDC__
  // ICE's in C++Builder.
  EXPECT_FATAL_FAILURE(ASSERT_EQ(kCaseA, kCaseB),
                       "  kCaseB\n    Which is: ");
  EXPECT_FATAL_FAILURE(ASSERT_EQ(kCaseA, kCaseC),
                       "\n    Which is: 42");
# endif
  EXPECT_FATAL_FAILURE(ASSERT_EQ(kCaseA, kCaseC),
                       "\n    Which is: -1");
}
References ASSERT_EQ, ASSERT_GE, ASSERT_GT, ASSERT_LE, ASSERT_LT, ASSERT_NE, EXPECT_EQ, EXPECT_FATAL_FAILURE, EXPECT_GE, EXPECT_GT, EXPECT_LE, EXPECT_LT, EXPECT_NE, EXPECT_NONFATAL_FAILURE, kCaseA, kCaseB, and kCaseC.
TEST() [6/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , AppendUserMessage) private
Definition at line 3623 of file gtest_unittest.cc.
{
  const std::string foo("foo");
  Message msg;
  EXPECT_STREQ("foo",
               AppendUserMessage(foo, msg).c_str());
  msg << "bar";
  EXPECT_STREQ("foo\nbar",
               AppendUserMessage(foo, msg).c_str());
}
References EXPECT_STREQ.
TEST() [7/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_EQ) private
Definition at line 3708 of file gtest_unittest.cc.
{
  ASSERT_EQ(5, 2 + 3);
  EXPECT_FATAL_FAILURE(ASSERT_EQ(5, 2*3),
                       "Expected equality of these values:\n"
                       "  5\n"
                       "  2*3\n"
                       "    Which is: 6");
}
References ASSERT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [8/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_FALSE) private
Definition at line 3665 of file gtest_unittest.cc.
{
  ASSERT_FALSE(2 < 1);  // NOLINT
  EXPECT_FATAL_FAILURE(ASSERT_FALSE(2 > 1),
                       "Value of: 2 > 1\n"
                       "  Actual: true\n"
                       "Expected: false");
}
References ASSERT_FALSE, and EXPECT_FATAL_FAILURE.
TEST() [9/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_GE) private
Definition at line 3774 of file gtest_unittest.cc.
{
  ASSERT_GE(2, 1);
  ASSERT_GE(2, 2);
  EXPECT_FATAL_FAILURE(ASSERT_GE(2, 3),
                       "Expected: (2) >= (3), actual: 2 vs 3");
}
References ASSERT_GE, and EXPECT_FATAL_FAILURE.
TEST() [10/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_GT) private
Definition at line 3782 of file gtest_unittest.cc.
{
  ASSERT_GT(2, 1);
  EXPECT_FATAL_FAILURE(ASSERT_GT(2, 2),
                       "Expected: (2) > (2), actual: 2 vs 2");
}
References ASSERT_GT, and EXPECT_FATAL_FAILURE.
TEST() [11/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_LE) private
Definition at line 3759 of file gtest_unittest.cc.
{
  ASSERT_LE(2, 3);
  ASSERT_LE(2, 2);
  EXPECT_FATAL_FAILURE(ASSERT_LE(2, 0),
                       "Expected: (2) <= (0), actual: 2 vs 0");
}
References ASSERT_LE, and EXPECT_FATAL_FAILURE.
TEST() [12/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_LT) private
Definition at line 3767 of file gtest_unittest.cc.
{
  ASSERT_LT(2, 3);
  EXPECT_FATAL_FAILURE(ASSERT_LT(2, 2),
                       "Expected: (2) < (2), actual: 2 vs 2");
}
References ASSERT_LT, and EXPECT_FATAL_FAILURE.
TEST() [13/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_NE) private
Definition at line 3751 of file gtest_unittest.cc.
{
  ASSERT_NE(6, 7);
  EXPECT_FATAL_FAILURE(ASSERT_NE('a', 'a'),
                       "Expected: ('a') != ('a'), "
                       "actual: 'a' (97, 0x61) vs 'a' (97, 0x61)");
}
References ASSERT_NE, and EXPECT_FATAL_FAILURE.
TEST() [14/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ASSERT_TRUE) private
Definition at line 3641 of file gtest_unittest.cc.
{
  ASSERT_TRUE(2 > 1);  // NOLINT
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(2 < 1),
                       "2 < 1");
}
References ASSERT_TRUE, and EXPECT_FATAL_FAILURE.
TEST() [15/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , AssertFalseWithAssertionResult) private
Definition at line 3674 of file gtest_unittest.cc.
{
  ASSERT_FALSE(ResultIsEven(3));
#ifndef __BORLANDC__
  // ICE's in C++Builder.
  EXPECT_FATAL_FAILURE(ASSERT_FALSE(ResultIsEven(2)),
                       "Value of: ResultIsEven(2)\n"
                       "  Actual: true (2 is even)\n"
                       "Expected: false");
#endif
  ASSERT_FALSE(ResultIsEvenNoExplanation(3));
  EXPECT_FATAL_FAILURE(ASSERT_FALSE(ResultIsEvenNoExplanation(2)),
                       "Value of: ResultIsEvenNoExplanation(2)\n"
                       "  Actual: true\n"
                       "Expected: false");
}
References ASSERT_FALSE, EXPECT_FATAL_FAILURE, ResultIsEven(), and ResultIsEvenNoExplanation().
TEST() [16/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , AssertPrecedence) private
Definition at line 3832 of file gtest_unittest.cc.
{
  ASSERT_EQ(1 < 2, true);
  bool false_value = false;
  ASSERT_EQ(true && false_value, false);
}
References ASSERT_EQ.
TEST() [17/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , AssertTrueWithAssertionResult) private
Definition at line 3648 of file gtest_unittest.cc.
{
  ASSERT_TRUE(ResultIsEven(2));
#ifndef __BORLANDC__
  // ICE's in C++Builder.
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(ResultIsEven(3)),
                       "Value of: ResultIsEven(3)\n"
                       "  Actual: false (3 is odd)\n"
                       "Expected: true");
#endif
  ASSERT_TRUE(ResultIsEvenNoExplanation(2));
  EXPECT_FATAL_FAILURE(ASSERT_TRUE(ResultIsEvenNoExplanation(3)),
                       "Value of: ResultIsEvenNoExplanation(3)\n"
                       "  Actual: false (3 is odd)\n"
                       "Expected: true");
}
References ASSERT_TRUE, EXPECT_FATAL_FAILURE, ResultIsEven(), and ResultIsEvenNoExplanation().
TEST() [18/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , AssertWorksWithUncopyableObject) private
Definition at line 3888 of file gtest_unittest.cc.
{
  Uncopyable x(5);
  ASSERT_PRED1(IsPositiveUncopyable, x);
  ASSERT_EQ(x, x);
  EXPECT_FATAL_FAILURE(TestAssertNonPositive(),
    "IsPositiveUncopyable(y) evaluates to false, where\ny evaluates to -1");
  EXPECT_FATAL_FAILURE(TestAssertEqualsUncopyable(),
                       "Expected equality of these values:\n"
                       "  x\n    Which is: 5\n  y\n    Which is: -1");
}
References ASSERT_EQ, ASSERT_PRED1, EXPECT_FATAL_FAILURE, IsPositiveUncopyable(), TestAssertEqualsUncopyable(), and TestAssertNonPositive().
TEST() [19/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , EqFailure) private
Definition at line 3548 of file gtest_unittest.cc.
{
  const std::string foo_val("5"), bar_val("6");
  const std::string msg1(
      EqFailure("foo", "bar", foo_val, bar_val, false)
      .failure_message());
  EXPECT_STREQ(
      "Expected equality of these values:\n"
      "  foo\n"
      "    Which is: 5\n"
      "  bar\n"
      "    Which is: 6",
      msg1.c_str());
  const std::string msg2(
      EqFailure("foo", "6", foo_val, bar_val, false)
      .failure_message());
  EXPECT_STREQ(
      "Expected equality of these values:\n"
      "  foo\n"
      "    Which is: 5\n"
      "  6",
      msg2.c_str());
  const std::string msg3(
      EqFailure("5", "bar", foo_val, bar_val, false)
      .failure_message());
  EXPECT_STREQ(
      "Expected equality of these values:\n"
      "  5\n"
      "  bar\n"
      "    Which is: 6",
      msg3.c_str());
  const std::string msg4(
      EqFailure("5", "6", foo_val, bar_val, false).failure_message());
  EXPECT_STREQ(
      "Expected equality of these values:\n"
      "  5\n"
      "  6",
      msg4.c_str());
  const std::string msg5(
      EqFailure("foo", "bar",
                std::string("\"x\""), std::string("\"y\""),
                true).failure_message());
  EXPECT_STREQ(
      "Expected equality of these values:\n"
      "  foo\n"
      "    Which is: \"x\"\n"
      "  bar\n"
      "    Which is: \"y\"\n"
      "Ignoring case",
      msg5.c_str());
}
References EXPECT_STREQ.
TEST() [20/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , EqFailureWithDiff) private
Definition at line 3603 of file gtest_unittest.cc.
{
  const std::string left(
      "1\\n2XXX\\n3\\n5\\n6\\n7\\n8\\n9\\n10\\n11\\n12XXX\\n13\\n14\\n15");
  const std::string right(
      "1\\n2\\n3\\n4\\n5\\n6\\n7\\n8\\n9\\n11\\n12\\n13\\n14");
  const std::string msg1(
      EqFailure("left", "right", left, right, false).failure_message());
  EXPECT_STREQ(
      "Expected equality of these values:\n"
      "  left\n"
      "    Which is: "
      "1\\n2XXX\\n3\\n5\\n6\\n7\\n8\\n9\\n10\\n11\\n12XXX\\n13\\n14\\n15\n"
      "  right\n"
      "    Which is: 1\\n2\\n3\\n4\\n5\\n6\\n7\\n8\\n9\\n11\\n12\\n13\\n14\n"
      "With diff:\n@@ -1,5 +1,6 @@\n 1\n-2XXX\n+2\n 3\n+4\n 5\n 6\n"
      "@@ -7,8 +8,6 @@\n 8\n 9\n-10\n 11\n-12XXX\n+12\n 13\n 14\n-15\n",
      msg1.c_str());
}
References EXPECT_STREQ.
TEST() [21/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , ExpectWorksWithUncopyableObject) private
Definition at line 3900 of file gtest_unittest.cc.
{
  Uncopyable x(5);
  EXPECT_PRED1(IsPositiveUncopyable, x);
  Uncopyable y(-1);
  EXPECT_NONFATAL_FAILURE(EXPECT_PRED1(IsPositiveUncopyable, y),
    "IsPositiveUncopyable(y) evaluates to false, where\ny evaluates to -1");
  EXPECT_EQ(x, x);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(x, y),
                          "Expected equality of these values:\n"
                          "  x\n    Which is: 5\n  y\n    Which is: -1");
}
References EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, and IsPositiveUncopyable().
TEST() [22/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , NamedEnum) private
Definition at line 3917 of file gtest_unittest.cc.
{
  EXPECT_EQ(kE1, kE1);
  EXPECT_LT(kE1, kE2);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(kE1, kE2), "Which is: 0");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(kE1, kE2), "Which is: 1");
}
References EXPECT_EQ, EXPECT_LT, EXPECT_NONFATAL_FAILURE, kE1, and kE2.
TEST() [23/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionTest , NonFixtureSubroutine) private
Definition at line 3844 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(TestEq1(2),
                       "  x\n    Which is: 2");
}
References EXPECT_FATAL_FAILURE, and TestEq1().
TEST() [24/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , ASSERT) private
Definition at line 4286 of file gtest_unittest.cc.
{
  ASSERT_EQ(1, 1) << "This should succeed.";
  ASSERT_NE(1, 2) << "This should succeed.";
  ASSERT_LE(1, 2) << "This should succeed.";
  ASSERT_LT(1, 2) << "This should succeed.";
  ASSERT_GE(1, 0) << "This should succeed.";
  EXPECT_FATAL_FAILURE(ASSERT_GT(1, 2) << "Expected failure.",
                       "Expected failure.");
}
References ASSERT_EQ, ASSERT_GE, ASSERT_GT, ASSERT_LE, ASSERT_LT, ASSERT_NE, and EXPECT_FATAL_FAILURE.
TEST() [25/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , ASSERT_FALSE) private
Definition at line 4314 of file gtest_unittest.cc.
{
  ASSERT_FALSE(false) << "This shouldn't fail.";
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_FALSE(true) << "Expected failure: " << 2 << " > " << 1
                       << " evaluates to " << true;
  }, "Expected failure");
}
References ASSERT_FALSE, and EXPECT_FATAL_FAILURE.
TEST() [26/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , ASSERT_FLOATING) private
Definition at line 4304 of file gtest_unittest.cc.
{
  ASSERT_FLOAT_EQ(1, 1) << "This should succeed.";
  ASSERT_DOUBLE_EQ(1, 1) << "This should succeed.";
  EXPECT_FATAL_FAILURE(ASSERT_NEAR(1,1.2, 0.1) << "Expect failure.",  // NOLINT
                       "Expect failure.");
  // To work around a bug in gcc 2.95.0, there is intentionally no
  // space after the first comma in the previous statement.
}
References ASSERT_DOUBLE_EQ, ASSERT_FLOAT_EQ, ASSERT_NEAR, and EXPECT_FATAL_FAILURE.
TEST() [27/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , ASSERT_STR) private
Definition at line 4296 of file gtest_unittest.cc.
{
  ASSERT_STREQ("1", "1") << "This should succeed.";
  ASSERT_STRNE("1", "2") << "This should succeed.";
  ASSERT_STRCASEEQ("a", "A") << "This should succeed.";
  EXPECT_FATAL_FAILURE(ASSERT_STRCASENE("a", "A") << "Expected failure.",
                       "Expected failure.");
}
References ASSERT_STRCASEEQ, ASSERT_STRCASENE, ASSERT_STREQ, ASSERT_STRNE, and EXPECT_FATAL_FAILURE.
TEST() [28/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , ASSERT_TRUE) private
Definition at line 4334 of file gtest_unittest.cc.
{
  ASSERT_TRUE(true) << "This should succeed.";
  ASSERT_TRUE(true) << true;
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_TRUE(false) << static_cast<const char *>(NULL)
                       << static_cast<char *>(NULL);
  }, "(null)(null)");
}
References ASSERT_TRUE, and EXPECT_FATAL_FAILURE.
TEST() [29/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , EXPECT) private
Definition at line 4262 of file gtest_unittest.cc.
{
  EXPECT_EQ(1, 1) << "This should succeed.";
  EXPECT_NONFATAL_FAILURE(EXPECT_NE(1, 1) << "Expected failure #1.",
                          "Expected failure #1");
  EXPECT_LE(1, 2) << "This should succeed.";
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(1, 0) << "Expected failure #2.",
                          "Expected failure #2.");
  EXPECT_GE(1, 0) << "This should succeed.";
  EXPECT_NONFATAL_FAILURE(EXPECT_GT(1, 2) << "Expected failure #3.",
                          "Expected failure #3.");
  EXPECT_STREQ("1", "1") << "This should succeed.";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRNE("1", "1") << "Expected failure #4.",
                          "Expected failure #4.");
  EXPECT_STRCASEEQ("a", "A") << "This should succeed.";
  EXPECT_NONFATAL_FAILURE(EXPECT_STRCASENE("a", "A") << "Expected failure #5.",
                          "Expected failure #5.");
  EXPECT_FLOAT_EQ(1, 1) << "This should succeed.";
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(1, 1.2) << "Expected failure #6.",
                          "Expected failure #6.");
  EXPECT_NEAR(1, 1.1, 0.2) << "This should succeed.";
}
References EXPECT_DOUBLE_EQ, EXPECT_EQ, EXPECT_FLOAT_EQ, EXPECT_GE, EXPECT_GT, EXPECT_LE, EXPECT_LT, EXPECT_NE, EXPECT_NEAR, EXPECT_NONFATAL_FAILURE, EXPECT_STRCASEEQ, EXPECT_STRCASENE, EXPECT_STREQ, and EXPECT_STRNE.
TEST() [30/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , FAIL) private
Definition at line 4323 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(FAIL() << 0,
                       "0");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [31/164]
anonymous_namespace{gtest_unittest.cc}::TEST (AssertionWithMessageTest , SUCCEED) private
Definition at line 4329 of file gtest_unittest.cc.
{
  SUCCEED() << "Success == " << 1;
}
References SUCCEED.
TEST() [32/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CanonicalizeForStdLibVersioning , ElidesDoubleUnderNames) private
Definition at line 396 of file gtest_unittest.cc.
{
  EXPECT_EQ("std::bind", CanonicalizeForStdLibVersioning("std::__1::bind"));
  EXPECT_EQ("std::_", CanonicalizeForStdLibVersioning("std::__1::_"));
  EXPECT_EQ("std::bind", CanonicalizeForStdLibVersioning("std::__g::bind"));
  EXPECT_EQ("std::_", CanonicalizeForStdLibVersioning("std::__g::_"));
  EXPECT_EQ("std::bind",
            CanonicalizeForStdLibVersioning("std::__google::bind"));
  EXPECT_EQ("std::_", CanonicalizeForStdLibVersioning("std::__google::_"));
}
References EXPECT_EQ.
TEST() [33/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CanonicalizeForStdLibVersioning , LeavesUnversionedNamesUnchanged) private
Definition at line 387 of file gtest_unittest.cc.
{
  EXPECT_EQ("std::bind", CanonicalizeForStdLibVersioning("std::bind"));
  EXPECT_EQ("std::_", CanonicalizeForStdLibVersioning("std::_"));
  EXPECT_EQ("std::__foo", CanonicalizeForStdLibVersioning("std::__foo"));
  EXPECT_EQ("gtl::__1::x", CanonicalizeForStdLibVersioning("gtl::__1::x"));
  EXPECT_EQ("__1::x", CanonicalizeForStdLibVersioning("__1::x"));
  EXPECT_EQ("::__1::x", CanonicalizeForStdLibVersioning("::__1::x"));
}
References EXPECT_EQ.
TEST() [34/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test , CanEncode12To16Bits) private
Definition at line 580 of file gtest_unittest.cc.
{
  // 0000 1000 1101 0011 => 1110-0000 10-100011 10-010011
  EXPECT_EQ("\xE0\xA3\x93",
            CodePointToUtf8(static_cast<wchar_t>(0x8D3)));
  // 1100 0111 0100 1101 => 1110-1100 10-011101 10-001101
  EXPECT_EQ("\xEC\x9D\x8D",
            CodePointToUtf8(static_cast<wchar_t>(0xC74D)));
}
References EXPECT_EQ.
TEST() [35/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test , CanEncode17To21Bits) private
Definition at line 597 of file gtest_unittest.cc.
{
  // 0 0001 0000 1000 1101 0011 => 11110-000 10-010000 10-100011 10-010011
  EXPECT_EQ("\xF0\x90\xA3\x93", CodePointToUtf8(L'\x108D3'));
  // 0 0001 0000 0100 0000 0000 => 11110-000 10-010000 10-010000 10-000000
  EXPECT_EQ("\xF0\x90\x90\x80", CodePointToUtf8(L'\x10400'));
  // 1 0000 1000 0110 0011 0100 => 11110-100 10-001000 10-011000 10-110100
  EXPECT_EQ("\xF4\x88\x98\xB4", CodePointToUtf8(L'\x108634'));
}
References EXPECT_EQ.
TEST() [36/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test , CanEncode8To11Bits) private
Definition at line 566 of file gtest_unittest.cc.
{
  // 000 1101 0011 => 110-00011 10-010011
  EXPECT_EQ("\xC3\x93", CodePointToUtf8(L'\xD3'));
  // 101 0111 0110 => 110-10101 10-110110
  // Some compilers (e.g., GCC on MinGW) cannot handle non-ASCII codepoints
  // in wide strings and wide chars. In order to accommodate them, we have to
  // introduce such character constants as integers.
  EXPECT_EQ("\xD5\xB6",
            CodePointToUtf8(static_cast<wchar_t>(0x576)));
}
References EXPECT_EQ.
TEST() [37/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test , CanEncodeAscii) private
Definition at line 557 of file gtest_unittest.cc.
{
  EXPECT_EQ("a", CodePointToUtf8(L'a'));
  EXPECT_EQ("Z", CodePointToUtf8(L'Z'));
  EXPECT_EQ("&", CodePointToUtf8(L'&'));
  EXPECT_EQ("\x7F", CodePointToUtf8(L'\x7F'));
}
References EXPECT_EQ.
TEST() [38/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test , CanEncodeInvalidCodePoint) private
Definition at line 609 of file gtest_unittest.cc.
{
  EXPECT_EQ("(Invalid Unicode 0x1234ABCD)", CodePointToUtf8(L'\x1234ABCD'));
}
References EXPECT_EQ.
TEST() [39/164]
anonymous_namespace{gtest_unittest.cc}::TEST (CodePointToUtf8Test , CanEncodeNul) private
Definition at line 552 of file gtest_unittest.cc.
{
  EXPECT_EQ("", CodePointToUtf8(L'\0'));
}
References EXPECT_EQ.
TEST() [40/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ComparisonAssertionTest , AcceptsUnprintableArgs) private
Definition at line 4989 of file gtest_unittest.cc.
{
  const UnprintableChar x('x'), y('y');
  ASSERT_EQ(x, x);
  EXPECT_NE(x, y);
  ASSERT_LT(x, y);
  EXPECT_LE(x, y);
  ASSERT_GT(y, x);
  EXPECT_GE(x, x);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(x, y), "1-byte object <78>");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(x, y), "1-byte object <79>");
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(y, y), "1-byte object <79>");
  EXPECT_NONFATAL_FAILURE(EXPECT_GT(x, y), "1-byte object <78>");
  EXPECT_NONFATAL_FAILURE(EXPECT_GT(x, y), "1-byte object <79>");
  // Code tested by EXPECT_FATAL_FAILURE cannot reference local
  // variables, so we have to write UnprintableChar('x') instead of x.
#ifndef __BORLANDC__
  // ICE's in C++Builder.
  EXPECT_FATAL_FAILURE(ASSERT_NE(UnprintableChar('x'), UnprintableChar('x')),
                       "1-byte object <78>");
  EXPECT_FATAL_FAILURE(ASSERT_LE(UnprintableChar('y'), UnprintableChar('x')),
                       "1-byte object <78>");
#endif
  EXPECT_FATAL_FAILURE(ASSERT_LE(UnprintableChar('y'), UnprintableChar('x')),
                       "1-byte object <79>");
  EXPECT_FATAL_FAILURE(ASSERT_GE(UnprintableChar('x'), UnprintableChar('y')),
                       "1-byte object <78>");
  EXPECT_FATAL_FAILURE(ASSERT_GE(UnprintableChar('x'), UnprintableChar('y')),
                       "1-byte object <79>");
}
References ASSERT_EQ, ASSERT_GE, ASSERT_GT, ASSERT_LE, ASSERT_LT, ASSERT_NE, EXPECT_EQ, EXPECT_FATAL_FAILURE, EXPECT_GE, EXPECT_GT, EXPECT_LE, EXPECT_LT, EXPECT_NE, and EXPECT_NONFATAL_FAILURE.
TEST() [41/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityDeathTest , ShuffleRange) private
Definition at line 832 of file gtest_unittest.cc.
{
  std::vector<int> a;
  a.push_back(0);
  a.push_back(1);
  a.push_back(2);
  testing::internal::Random random(1);
  EXPECT_DEATH_IF_SUPPORTED(
      ShuffleRange(&random, -1, 1, &a),
      "Invalid shuffle range start -1: must be in range \\[0, 3\\]");
  EXPECT_DEATH_IF_SUPPORTED(
      ShuffleRange(&random, 4, 4, &a),
      "Invalid shuffle range start 4: must be in range \\[0, 3\\]");
  EXPECT_DEATH_IF_SUPPORTED(
      ShuffleRange(&random, 3, 2, &a),
      "Invalid shuffle range finish 2: must be in range \\[3, 3\\]");
  EXPECT_DEATH_IF_SUPPORTED(
      ShuffleRange(&random, 3, 4, &a),
      "Invalid shuffle range finish 4: must be in range \\[3, 3\\]");
}
References EXPECT_DEATH_IF_SUPPORTED.
TEST() [42/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityTest , CountIf) private
Definition at line 782 of file gtest_unittest.cc.
{
  std::vector<int> v;
  EXPECT_EQ(0, CountIf(v, IsPositive));  // Works for an empty container.
  v.push_back(-1);
  v.push_back(0);
  EXPECT_EQ(0, CountIf(v, IsPositive));  // Works when no value satisfies.
  v.push_back(2);
  v.push_back(-10);
  v.push_back(10);
  EXPECT_EQ(2, CountIf(v, IsPositive));
}
References EXPECT_EQ, and IsPositive().
TEST() [43/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityTest , ForEach) private
Definition at line 801 of file gtest_unittest.cc.
{
  std::vector<int> v;
  g_sum = 0;
  ForEach(v, Accumulate);
  EXPECT_EQ(0, g_sum);  // Works for an empty container;
  g_sum = 0;
  v.push_back(1);
  ForEach(v, Accumulate);
  EXPECT_EQ(1, g_sum);  // Works for a container with one element.
  g_sum = 0;
  v.push_back(20);
  v.push_back(300);
  ForEach(v, Accumulate);
  EXPECT_EQ(321, g_sum);
}
References Accumulate(), EXPECT_EQ, and g_sum.
TEST() [44/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ContainerUtilityTest , GetElementOr) private
Definition at line 820 of file gtest_unittest.cc.
{
  std::vector<char> a;
  EXPECT_EQ('x', GetElementOr(a, 0, 'x'));
  a.push_back('a');
  a.push_back('b');
  EXPECT_EQ('a', GetElementOr(a, 0, 'x'));
  EXPECT_EQ('b', GetElementOr(a, 1, 'x'));
  EXPECT_EQ('x', GetElementOr(a, -2, 'x'));
  EXPECT_EQ('x', GetElementOr(a, 2, 'x'));
}
References EXPECT_EQ.
TEST() [45/164]
anonymous_namespace{gtest_unittest.cc}::TEST (DISABLED_TestCase , DISABLED_TestShouldNotRun) private
Definition at line 3137 of file gtest_unittest.cc.
{
  FAIL() << "Unexpected failure: Test in disabled test case should not be run.";
}
References FAIL.
TEST() [46/164]
anonymous_namespace{gtest_unittest.cc}::TEST (DISABLED_TestCase , TestShouldNotRun) private
Definition at line 3131 of file gtest_unittest.cc.
{
  FAIL() << "Unexpected failure: Test in disabled test case should not be run.";
}
References FAIL.
TEST() [47/164]
anonymous_namespace{gtest_unittest.cc}::TEST (DisabledTest , DISABLED_TestShouldNotRun) private
Definition at line 3119 of file gtest_unittest.cc.
{
  FAIL() << "Unexpected failure: Disabled test should not be run.";
}
References FAIL.
TEST() [48/164]
anonymous_namespace{gtest_unittest.cc}::TEST (DisabledTest , NotDISABLED_TestShouldRun) private
Definition at line 3125 of file gtest_unittest.cc.
{
  EXPECT_EQ(1, 1);
}
References EXPECT_EQ.
TEST() [49/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EditDistance , TestCases) private
Definition at line 3499 of file gtest_unittest.cc.
{
  struct Case {
    int line;
    const char* left;
    const char* right;
    const char* expected_edits;
    const char* expected_diff;
  };
  static const Case kCases[] = {
      // No change.
      {__LINE__, "A", "A", " ", ""},
      {__LINE__, "ABCDE", "ABCDE", "     ", ""},
      // Simple adds.
      {__LINE__, "X", "XA", " +", "@@ +1,2 @@\n X\n+A\n"},
      {__LINE__, "X", "XABCD", " ++++", "@@ +1,5 @@\n X\n+A\n+B\n+C\n+D\n"},
      // Simple removes.
      {__LINE__, "XA", "X", " -", "@@ -1,2 @@\n X\n-A\n"},
      {__LINE__, "XABCD", "X", " ----", "@@ -1,5 @@\n X\n-A\n-B\n-C\n-D\n"},
      // Simple replaces.
      {__LINE__, "A", "a", "/", "@@ -1,1 +1,1 @@\n-A\n+a\n"},
      {__LINE__, "ABCD", "abcd", "////",
       "@@ -1,4 +1,4 @@\n-A\n-B\n-C\n-D\n+a\n+b\n+c\n+d\n"},
      // Path finding.
      {__LINE__, "ABCDEFGH", "ABXEGH1", "  -/ -  +",
       "@@ -1,8 +1,7 @@\n A\n B\n-C\n-D\n+X\n E\n-F\n G\n H\n+1\n"},
      {__LINE__, "AAAABCCCC", "ABABCDCDC", "- /   + / ",
       "@@ -1,9 +1,9 @@\n-A\n A\n-A\n+B\n A\n B\n C\n+D\n C\n-C\n+D\n C\n"},
      {__LINE__, "ABCDE", "BCDCD", "-   +/",
       "@@ -1,5 +1,5 @@\n-A\n B\n C\n D\n-E\n+C\n+D\n"},
      {__LINE__, "ABCDEFGHIJKL", "BCDCDEFGJKLJK", "- ++     --   ++",
       "@@ -1,4 +1,5 @@\n-A\n B\n+C\n+D\n C\n D\n"
       "@@ -6,7 +7,7 @@\n F\n G\n-H\n-I\n J\n K\n L\n+J\n+K\n"},
      {}};
  for (const Case* c = kCases; c->left; ++c) {
    EXPECT_TRUE(c->expected_edits ==
                EditsToString(CalculateOptimalEdits(CharsToIndices(c->left),
                                                    CharsToIndices(c->right))))
        << "Left <" << c->left << "> Right <" << c->right << "> Edits <"
        << EditsToString(CalculateOptimalEdits(
               CharsToIndices(c->left), CharsToIndices(c->right))) << ">";
    EXPECT_TRUE(c->expected_diff == CreateUnifiedDiff(CharsToLines(c->left),
                                                      CharsToLines(c->right)))
        << "Left <" << c->left << "> Right <" << c->right << "> Diff <"
        << CreateUnifiedDiff(CharsToLines(c->left), CharsToLines(c->right))
        << ">";
  }
}
References CharsToIndices(), CharsToLines(), EditsToString(), and EXPECT_TRUE.
TEST() [50/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , Bool) private
Definition at line 4717 of file gtest_unittest.cc.
{
  EXPECT_EQ(true,  true);
  EXPECT_FATAL_FAILURE({
      bool false_value = false;
      ASSERT_EQ(false_value, true);
    }, "  false_value\n    Which is: false\n  true");
}
References ASSERT_EQ, EXPECT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [51/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , Char) private
Definition at line 4742 of file gtest_unittest.cc.
{
  ASSERT_EQ('z', 'z');
  const char ch = 'b';
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ('\0', ch),
                          "  ch\n    Which is: 'b'");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ('a', ch),
                          "  ch\n    Which is: 'b'");
}
References ASSERT_EQ, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [52/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , CharPointer) private
Definition at line 4904 of file gtest_unittest.cc.
{
  char* const p0 = NULL;
  // Only way to get the Nokia compiler to compile the cast
  // is to have a separate void* variable first. Putting
  // the two casts on the same line doesn't work, neither does
  // a direct C-style to char*.
  void* pv1 = (void*)0x1234;  // NOLINT
  void* pv2 = (void*)0xABC0;  // NOLINT
  char* const p1 = reinterpret_cast<char*>(pv1);
  char* const p2 = reinterpret_cast<char*>(pv2);
  ASSERT_EQ(p1, p1);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(p0, p2),
                          "  p2\n    Which is:");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(p1, p2),
                          "  p2\n    Which is:");
  EXPECT_FATAL_FAILURE(ASSERT_EQ(reinterpret_cast<char*>(0x1234),
                                 reinterpret_cast<char*>(0xABC0)),
                       "ABC0");
}
References ASSERT_EQ, EXPECT_EQ, EXPECT_FATAL_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [53/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , Int) private
Definition at line 4726 of file gtest_unittest.cc.
{
  ASSERT_EQ(32, 32);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(32, 33),
                          "  32\n  33");
}
References ASSERT_EQ, EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [54/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , OtherPointer) private
Definition at line 4951 of file gtest_unittest.cc.
{
  ASSERT_EQ(static_cast<const int*>(NULL),
            static_cast<const int*>(NULL));
  EXPECT_FATAL_FAILURE(ASSERT_EQ(static_cast<const int*>(NULL),
                                 reinterpret_cast<const int*>(0x1234)),
                       "0x1234");
}
References ASSERT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [55/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , StdString) private
Definition at line 4772 of file gtest_unittest.cc.
{
  // Compares a const char* to an std::string that has identical
  // content.
  ASSERT_EQ("Test", ::std::string("Test"));
  // Compares two identical std::strings.
  static const ::std::string str1("A * in the middle");
  static const ::std::string str2(str1);
  EXPECT_EQ(str1, str2);
  // Compares a const char* to an std::string that has different
  // content
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ("Test", ::std::string("test")),
                          "\"test\"");
  // Compares an std::string to a char* that has different content.
  char* const p1 = const_cast<char*>("foo");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(::std::string("bar"), p1),
                          "p1");
  // Compares two std::strings that have different contents, one of
  // which having a NUL character in the middle.  This should fail.
  static ::std::string str3(str1);
  str3.at(2) = '\0';
  EXPECT_FATAL_FAILURE(ASSERT_EQ(str1, str3),
                       "  str3\n    Which is: \"A \\0 in the middle\"");
}
References ASSERT_EQ, EXPECT_EQ, EXPECT_FATAL_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [56/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , Time_T) private
Definition at line 4733 of file gtest_unittest.cc.
{
  EXPECT_EQ(static_cast<time_t>(0),
            static_cast<time_t>(0));
  EXPECT_FATAL_FAILURE(ASSERT_EQ(static_cast<time_t>(0),
                                 static_cast<time_t>(1234)),
                       "1234");
}
References ASSERT_EQ, EXPECT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [57/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , WideChar) private
Definition at line 4752 of file gtest_unittest.cc.
{
  EXPECT_EQ(L'b', L'b');
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(L'\0', L'x'),
                          "Expected equality of these values:\n"
                          "  L'\0'\n"
                          "    Which is: L'\0' (0, 0x0)\n"
                          "  L'x'\n"
                          "    Which is: L'x' (120, 0x78)");
  static wchar_t wchar;
  wchar = L'b';
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(L'a', wchar),
                          "wchar");
  wchar = 0x8119;
  EXPECT_FATAL_FAILURE(ASSERT_EQ(static_cast<wchar_t>(0x8120), wchar),
                       "  wchar\n    Which is: L'");
}
References ASSERT_EQ, EXPECT_EQ, EXPECT_FATAL_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST() [58/164]
anonymous_namespace{gtest_unittest.cc}::TEST (EqAssertionTest , WideCharPointer) private
Definition at line 4926 of file gtest_unittest.cc.
{
  wchar_t* const p0 = NULL;
  // Only way to get the Nokia compiler to compile the cast
  // is to have a separate void* variable first. Putting
  // the two casts on the same line doesn't work, neither does
  // a direct C-style to char*.
  void* pv1 = (void*)0x1234;  // NOLINT
  void* pv2 = (void*)0xABC0;  // NOLINT
  wchar_t* const p1 = reinterpret_cast<wchar_t*>(pv1);
  wchar_t* const p2 = reinterpret_cast<wchar_t*>(pv2);
  EXPECT_EQ(p0, p0);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(p0, p2),
                          "  p2\n    Which is:");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(p1, p2),
                          "  p2\n    Which is:");
  void* pv3 = (void*)0x1234;  // NOLINT
  void* pv4 = (void*)0xABC0;  // NOLINT
  const wchar_t* p3 = reinterpret_cast<const wchar_t*>(pv3);
  const wchar_t* p4 = reinterpret_cast<const wchar_t*>(pv4);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(p3, p4),
                          "p4");
}
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [59/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , ASSERT_EQ_0) private
Definition at line 3739 of file gtest_unittest.cc.
{
  int n = 0;
  // A success.
  ASSERT_EQ(0, n);
  // A failure.
  EXPECT_FATAL_FAILURE(ASSERT_EQ(0, 5.6),
                       "  0\n  5.6");
}
References ASSERT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [60/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , ASSERT_EQ_Double) private
Definition at line 3698 of file gtest_unittest.cc.
{
  // A success.
  ASSERT_EQ(5.6, 5.6);
  // A failure.
  EXPECT_FATAL_FAILURE(ASSERT_EQ(5.1, 5.2),
                       "5.1");
}
References ASSERT_EQ, and EXPECT_FATAL_FAILURE.
TEST() [61/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_EQ) private
Definition at line 4422 of file gtest_unittest.cc.
{
  EXPECT_EQ(5, 2 + 3);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(5, 2*3),
                          "Expected equality of these values:\n"
                          "  5\n"
                          "  2*3\n"
                          "    Which is: 6");
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(5, 2 - 3),
                          "2 - 3");
}
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [62/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_EQ_0) private
Definition at line 4467 of file gtest_unittest.cc.
{
  int n = 0;
  // A success.
  EXPECT_EQ(0, n);
  // A failure.
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(0, 5.6),
                          "  0\n  5.6");
}
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [63/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_EQ_Double) private
Definition at line 4436 of file gtest_unittest.cc.
{
  // A success.
  EXPECT_EQ(5.6, 5.6);
  // A failure.
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(5.1, 5.2),
                          "5.1");
}
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [64/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_FALSE) private
Definition at line 4387 of file gtest_unittest.cc.
{
  EXPECT_FALSE(2 < 1);  // NOLINT
  EXPECT_FALSE(false) << "Intentional success";
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(true) << "Intentional failure #1.",
                          "Intentional failure #1.");
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(true) << "Intentional failure #2.",
                          "Intentional failure #2.");
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(2 > 1),
                          "Value of: 2 > 1\n"
                          "  Actual: true\n"
                          "Expected: false");
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(2 < 3),
                          "2 < 3");
}
References EXPECT_FALSE, and EXPECT_NONFATAL_FAILURE.
TEST() [65/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_GE) private
Definition at line 4520 of file gtest_unittest.cc.
{
  EXPECT_GE(2, 1);
  EXPECT_GE(2, 2);
  EXPECT_NONFATAL_FAILURE(EXPECT_GE(2, 3),
                          "Expected: (2) >= (3), actual: 2 vs 3");
  EXPECT_NONFATAL_FAILURE(EXPECT_GE(0.9, 1.1),
                          "(0.9) >= (1.1)");
}
References EXPECT_GE, and EXPECT_NONFATAL_FAILURE.
TEST() [66/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_GT) private
Definition at line 4530 of file gtest_unittest.cc.
{
  EXPECT_GT(2, 1);
  EXPECT_NONFATAL_FAILURE(EXPECT_GT(2, 2),
                          "Expected: (2) > (2), actual: 2 vs 2");
  EXPECT_NONFATAL_FAILURE(EXPECT_GT(2, 3),
                          "(2) > (3)");
}
References EXPECT_GT, and EXPECT_NONFATAL_FAILURE.
TEST() [67/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_LE) private
Definition at line 4501 of file gtest_unittest.cc.
{
  EXPECT_LE(2, 3);
  EXPECT_LE(2, 2);
  EXPECT_NONFATAL_FAILURE(EXPECT_LE(2, 0),
                          "Expected: (2) <= (0), actual: 2 vs 0");
  EXPECT_NONFATAL_FAILURE(EXPECT_LE(1.1, 0.9),
                          "(1.1) <= (0.9)");
}
References EXPECT_LE, and EXPECT_NONFATAL_FAILURE.
TEST() [68/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_LT) private
Definition at line 4511 of file gtest_unittest.cc.
{
  EXPECT_LT(2, 3);
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(2, 2),
                          "Expected: (2) < (2), actual: 2 vs 2");
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(2, 1),
                          "(2) < (1)");
}
References EXPECT_LT, and EXPECT_NONFATAL_FAILURE.
TEST() [69/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_NE) private
Definition at line 4479 of file gtest_unittest.cc.
{
  EXPECT_NE(6, 7);
  EXPECT_NONFATAL_FAILURE(EXPECT_NE('a', 'a'),
                          "Expected: ('a') != ('a'), "
                          "actual: 'a' (97, 0x61) vs 'a' (97, 0x61)");
  EXPECT_NONFATAL_FAILURE(EXPECT_NE(2, 2),
                          "2");
  char* const p0 = NULL;
  EXPECT_NONFATAL_FAILURE(EXPECT_NE(p0, p0),
                          "p0");
  // Only way to get the Nokia compiler to compile the cast
  // is to have a separate void* variable first. Putting
  // the two casts on the same line doesn't work, neither does
  // a direct C-style to char*.
  void* pv1 = (void*)0x1234;  // NOLINT
  char* const p1 = reinterpret_cast<char*>(pv1);
  EXPECT_NONFATAL_FAILURE(EXPECT_NE(p1, p1),
                          "p1");
}
References EXPECT_NE, and EXPECT_NONFATAL_FAILURE.
TEST() [70/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , EXPECT_TRUE) private
Definition at line 4357 of file gtest_unittest.cc.
{
  EXPECT_TRUE(true) << "Intentional success";
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(false) << "Intentional failure #1.",
                          "Intentional failure #1.");
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(false) << "Intentional failure #2.",
                          "Intentional failure #2.");
  EXPECT_TRUE(2 > 1);  // NOLINT
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(2 < 1),
                          "Value of: 2 < 1\n"
                          "  Actual: false\n"
                          "Expected: true");
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(2 > 3),
                          "2 > 3");
}
References EXPECT_NONFATAL_FAILURE, and EXPECT_TRUE.
TEST() [71/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , ExpectFalseWithAssertionResult) private
Definition at line 4403 of file gtest_unittest.cc.
{
  EXPECT_FALSE(ResultIsEven(3));
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(ResultIsEven(2)),
                          "Value of: ResultIsEven(2)\n"
                          "  Actual: true (2 is even)\n"
                          "Expected: false");
  EXPECT_FALSE(ResultIsEvenNoExplanation(3));
  EXPECT_NONFATAL_FAILURE(EXPECT_FALSE(ResultIsEvenNoExplanation(2)),
                          "Value of: ResultIsEvenNoExplanation(2)\n"
                          "  Actual: true\n"
                          "Expected: false");
}
References EXPECT_FALSE, EXPECT_NONFATAL_FAILURE, ResultIsEven(), and ResultIsEvenNoExplanation().
TEST() [72/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , ExpectPrecedence) private
Definition at line 4572 of file gtest_unittest.cc.
{
  EXPECT_EQ(1 < 2, true);
  EXPECT_NONFATAL_FAILURE(EXPECT_EQ(true, true && false),
                          "  true && false\n    Which is: false");
}
References EXPECT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST() [73/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ExpectTest , ExpectTrueWithAssertionResult) private
Definition at line 4373 of file gtest_unittest.cc.
{
  EXPECT_TRUE(ResultIsEven(2));
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(ResultIsEven(3)),
                          "Value of: ResultIsEven(3)\n"
                          "  Actual: false (3 is odd)\n"
                          "Expected: true");
  EXPECT_TRUE(ResultIsEvenNoExplanation(2));
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(ResultIsEvenNoExplanation(3)),
                          "Value of: ResultIsEvenNoExplanation(3)\n"
                          "  Actual: false (3 is odd)\n"
                          "Expected: true");
}
References EXPECT_NONFATAL_FAILURE, EXPECT_TRUE, ResultIsEven(), and ResultIsEvenNoExplanation().
TEST() [74/164]
anonymous_namespace{gtest_unittest.cc}::TEST (FormatTimeInMillisAsSecondsTest , FormatsNegativeNumber) private
Definition at line 422 of file gtest_unittest.cc.
{
  EXPECT_EQ("-0.003", FormatTimeInMillisAsSeconds(-3));
  EXPECT_EQ("-0.01", FormatTimeInMillisAsSeconds(-10));
  EXPECT_EQ("-0.2", FormatTimeInMillisAsSeconds(-200));
  EXPECT_EQ("-1.2", FormatTimeInMillisAsSeconds(-1200));
  EXPECT_EQ("-3", FormatTimeInMillisAsSeconds(-3000));
}
References EXPECT_EQ.
TEST() [75/164]
anonymous_namespace{gtest_unittest.cc}::TEST (FormatTimeInMillisAsSecondsTest , FormatsPositiveNumber) private
Definition at line 414 of file gtest_unittest.cc.
{
  EXPECT_EQ("0.003", FormatTimeInMillisAsSeconds(3));
  EXPECT_EQ("0.01", FormatTimeInMillisAsSeconds(10));
  EXPECT_EQ("0.2", FormatTimeInMillisAsSeconds(200));
  EXPECT_EQ("1.2", FormatTimeInMillisAsSeconds(1200));
  EXPECT_EQ("3", FormatTimeInMillisAsSeconds(3000));
}
References EXPECT_EQ.
TEST() [76/164]
anonymous_namespace{gtest_unittest.cc}::TEST (FormatTimeInMillisAsSecondsTest , FormatsZero) private
Definition at line 410 of file gtest_unittest.cc.
{
  EXPECT_EQ("0", FormatTimeInMillisAsSeconds(0));
}
References EXPECT_EQ.
TEST() [77/164]
anonymous_namespace{gtest_unittest.cc}::TEST (FRIEND_TEST_Test , TEST) private
Definition at line 5040 of file gtest_unittest.cc.
{
  ASSERT_EQ(1, Foo().Bar());
}
References ASSERT_EQ, and anonymous_namespace{gtest_unittest.cc}::Foo::Bar().
TEST() [78/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetNextRandomSeedTest , WorksForValidInput) private
Definition at line 340 of file gtest_unittest.cc.
{
  EXPECT_EQ(2, GetNextRandomSeed(1));
  EXPECT_EQ(3, GetNextRandomSeed(2));
  EXPECT_EQ(static_cast<int>(kMaxRandomSeed),
            GetNextRandomSeed(kMaxRandomSeed - 1));
  EXPECT_EQ(1, GetNextRandomSeed(kMaxRandomSeed));
  // We deliberately don't test GetNextRandomSeed() with invalid
  // inputs, as that requires death tests, which are expensive.  This
  // is fine as GetNextRandomSeed() is internal and has a
  // straightforward definition.
}
References EXPECT_EQ.
TEST() [79/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetRandomSeedFromFlagTest , HandlesZero) private
Definition at line 316 of file gtest_unittest.cc.
{
  const int seed = GetRandomSeedFromFlag(0);
  EXPECT_LE(1, seed);
  EXPECT_LE(seed, static_cast<int>(kMaxRandomSeed));
}
References EXPECT_LE.
TEST() [80/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetRandomSeedFromFlagTest , NormalizesInvalidSeed) private
Definition at line 330 of file gtest_unittest.cc.
{
  const int seed1 = GetRandomSeedFromFlag(-1);
  EXPECT_LE(1, seed1);
  EXPECT_LE(seed1, static_cast<int>(kMaxRandomSeed));
  const int seed2 = GetRandomSeedFromFlag(kMaxRandomSeed + 1);
  EXPECT_LE(1, seed2);
  EXPECT_LE(seed2, static_cast<int>(kMaxRandomSeed));
}
References EXPECT_LE.
TEST() [81/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetRandomSeedFromFlagTest , PreservesValidSeed) private
Definition at line 322 of file gtest_unittest.cc.
{
  EXPECT_EQ(1, GetRandomSeedFromFlag(1));
  EXPECT_EQ(2, GetRandomSeedFromFlag(2));
  EXPECT_EQ(kMaxRandomSeed - 1, GetRandomSeedFromFlag(kMaxRandomSeed - 1));
  EXPECT_EQ(static_cast<int>(kMaxRandomSeed),
            GetRandomSeedFromFlag(kMaxRandomSeed));
}
References EXPECT_EQ.
TEST() [82/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetTestTypeIdTest , ReturnsTheSameValueInsideOrOutsideOfGoogleTest) private
Definition at line 379 of file gtest_unittest.cc.
{
  EXPECT_EQ(kTestTypeIdInGoogleTest, GetTestTypeId());
}
References EXPECT_EQ.
TEST() [83/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetTypeIdTest , ReturnsDifferentValuesForDifferentTypes) private
Definition at line 368 of file gtest_unittest.cc.
{
  EXPECT_NE(GetTypeId<int>(), GetTypeId<const int>());
  EXPECT_NE(GetTypeId<int>(), GetTypeId<char>());
  EXPECT_NE(GetTypeId<int>(), GetTestTypeId());
  EXPECT_NE(GetTypeId<SubClassOfTest>(), GetTestTypeId());
  EXPECT_NE(GetTypeId<AnotherSubClassOfTest>(), GetTestTypeId());
  EXPECT_NE(GetTypeId<AnotherSubClassOfTest>(), GetTypeId<SubClassOfTest>());
}
References EXPECT_NE.
TEST() [84/164]
anonymous_namespace{gtest_unittest.cc}::TEST (GetTypeIdTest , ReturnsSameValueForSameType) private
Definition at line 360 of file gtest_unittest.cc.
{
  EXPECT_EQ(GetTypeId<int>(), GetTypeId<int>());
  EXPECT_EQ(GetTypeId<Test>(), GetTypeId<Test>());
}
References EXPECT_EQ.
TEST() [85/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromEnvOrDieDeathTest , AbortsOnFailure) private
Definition at line 1805 of file gtest_unittest.cc.
{
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "VAR", "xxx");
  EXPECT_DEATH_IF_SUPPORTED(
      Int32FromEnvOrDie(GTEST_FLAG_PREFIX_UPPER_ "VAR", 123),
      ".*");
}
References EXPECT_DEATH_IF_SUPPORTED, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [86/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromEnvOrDieDeathTest , AbortsOnInt32Overflow) private
Definition at line 1814 of file gtest_unittest.cc.
{
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "VAR", "1234567891234567891234");
  EXPECT_DEATH_IF_SUPPORTED(
      Int32FromEnvOrDie(GTEST_FLAG_PREFIX_UPPER_ "VAR", 123),
      ".*");
}
References EXPECT_DEATH_IF_SUPPORTED, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [87/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromEnvOrDieTest , ParsesAndReturnsValidValue) private
Definition at line 1794 of file gtest_unittest.cc.
{
  EXPECT_EQ(333, Int32FromEnvOrDie(GTEST_FLAG_PREFIX_UPPER_ "UnsetVar", 333));
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "UnsetVar", "123");
  EXPECT_EQ(123, Int32FromEnvOrDie(GTEST_FLAG_PREFIX_UPPER_ "UnsetVar", 333));
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "UnsetVar", "-123");
  EXPECT_EQ(-123, Int32FromEnvOrDie(GTEST_FLAG_PREFIX_UPPER_ "UnsetVar", 333));
}
References EXPECT_EQ, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [88/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest , ParsesAndReturnsValidValue) private
Definition at line 1728 of file gtest_unittest.cc.
{
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "123");
  EXPECT_EQ(123, Int32FromGTestEnv("temp", 0));
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "-321");
  EXPECT_EQ(-321, Int32FromGTestEnv("temp", 0));
}
References EXPECT_EQ, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [89/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest , ReturnsDefaultWhenValueIsInvalid) private
Definition at line 1713 of file gtest_unittest.cc.
{
  printf("(expecting 2 warnings)\n");
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "A1");
  EXPECT_EQ(40, Int32FromGTestEnv("temp", 40));
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "12X");
  EXPECT_EQ(50, Int32FromGTestEnv("temp", 50));
}
References EXPECT_EQ, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [90/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest , ReturnsDefaultWhenValueOverflows) private
Definition at line 1701 of file gtest_unittest.cc.
{
  printf("(expecting 2 warnings)\n");
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "12345678987654321");
  EXPECT_EQ(20, Int32FromGTestEnv("temp", 20));
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "-12345678987654321");
  EXPECT_EQ(30, Int32FromGTestEnv("temp", 30));
}
References EXPECT_EQ, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [91/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Int32FromGTestEnvTest , ReturnsDefaultWhenVariableIsNotSet) private
Definition at line 1692 of file gtest_unittest.cc.
{
  SetEnv(GTEST_FLAG_PREFIX_UPPER_ "TEMP", "");
  EXPECT_EQ(10, Int32FromGTestEnv("temp", 10));
}
References EXPECT_EQ, GTEST_FLAG_PREFIX_UPPER_, and SetEnv().
TEST() [92/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest , GeneratesCorrectMessageForStdString) private
Definition at line 2667 of file gtest_unittest.cc.
{
  EXPECT_STREQ("Value of: needle_expr\n"
               "  Actual: \"needle\"\n"
               "Expected: not a substring of haystack_expr\n"
               "Which is: \"two needles\"",
               IsNotSubstring(
                   "needle_expr", "haystack_expr",
                   ::std::string("needle"), "two needles").failure_message());
}
References EXPECT_STREQ.
TEST() [93/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest , GeneratesCorrectMessageForWideCString) private
Definition at line 2648 of file gtest_unittest.cc.
{
  EXPECT_STREQ("Value of: needle_expr\n"
               "  Actual: L\"needle\"\n"
               "Expected: not a substring of haystack_expr\n"
               "Which is: L\"two needles\"",
               IsNotSubstring(
                   "needle_expr", "haystack_expr",
                   L"needle", L"two needles").failure_message());
}
References EXPECT_STREQ.
TEST() [94/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest , ReturnsCorrectResultForCString) private
Definition at line 2634 of file gtest_unittest.cc.
{
  EXPECT_TRUE(IsNotSubstring("", "", "needle", "haystack"));
  EXPECT_FALSE(IsNotSubstring("", "", "needle", "two needles"));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [95/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest , ReturnsCorrectResultForWideCString) private
Definition at line 2641 of file gtest_unittest.cc.
{
  EXPECT_TRUE(IsNotSubstring("", "", L"needle", L"haystack"));
  EXPECT_FALSE(IsNotSubstring("", "", L"needle", L"two needles"));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [96/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsNotSubstringTest , ReturnsCorrectResultsForStdString) private
Definition at line 2660 of file gtest_unittest.cc.
{
  EXPECT_FALSE(IsNotSubstring("", "", std::string("hello"), "ahellob"));
  EXPECT_TRUE(IsNotSubstring("", "", "hello", std::string("world")));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [97/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest , GeneratesCorrectMessageForCString) private
Definition at line 2592 of file gtest_unittest.cc.
{
  EXPECT_STREQ("Value of: needle_expr\n"
               "  Actual: \"needle\"\n"
               "Expected: a substring of haystack_expr\n"
               "Which is: \"haystack\"",
               IsSubstring("needle_expr", "haystack_expr",
                           "needle", "haystack").failure_message());
}
References EXPECT_STREQ.
TEST() [98/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest , ReturnsCorrectResultForCString) private
Definition at line 2570 of file gtest_unittest.cc.
{
  EXPECT_FALSE(IsSubstring("", "", NULL, "a"));
  EXPECT_FALSE(IsSubstring("", "", "b", NULL));
  EXPECT_FALSE(IsSubstring("", "", "needle", "haystack"));
  EXPECT_TRUE(IsSubstring("", "", static_cast<const char*>(NULL), NULL));
  EXPECT_TRUE(IsSubstring("", "", "needle", "two needles"));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [99/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest , ReturnsCorrectResultForWideCString) private
Definition at line 2581 of file gtest_unittest.cc.
{
  EXPECT_FALSE(IsSubstring("", "", kNull, L"a"));
  EXPECT_FALSE(IsSubstring("", "", L"b", kNull));
  EXPECT_FALSE(IsSubstring("", "", L"needle", L"haystack"));
  EXPECT_TRUE(IsSubstring("", "", static_cast<const wchar_t*>(NULL), NULL));
  EXPECT_TRUE(IsSubstring("", "", L"needle", L"two needles"));
}
References EXPECT_FALSE, EXPECT_TRUE, and kNull.
TEST() [100/164]
anonymous_namespace{gtest_unittest.cc}::TEST (IsSubstringTest , ReturnsCorrectResultsForStdString) private
Definition at line 2603 of file gtest_unittest.cc.
{
  EXPECT_TRUE(IsSubstring("", "", std::string("hello"), "ahellob"));
  EXPECT_FALSE(IsSubstring("", "", "hello", std::string("world")));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [101/164]
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest , ADD_FAILURE) private
Definition at line 4673 of file gtest_unittest.cc.
{
  bool aborted = true;
  EXPECT_NONFATAL_FAILURE(AddFailureHelper(&aborted),
                          "Intentional failure.");
  EXPECT_FALSE(aborted);
}
References AddFailureHelper(), EXPECT_FALSE, and EXPECT_NONFATAL_FAILURE.
TEST() [102/164]
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest , ADD_FAILURE_AT) private
Definition at line 4681 of file gtest_unittest.cc.
{
  // Verifies that ADD_FAILURE_AT does generate a nonfatal failure and
  // the failure message contains the user-streamed part.
  EXPECT_NONFATAL_FAILURE(ADD_FAILURE_AT("foo.cc", 42) << "Wrong!", "Wrong!");
  // Verifies that the user-streamed part is optional.
  EXPECT_NONFATAL_FAILURE(ADD_FAILURE_AT("foo.cc", 42), "Failed");
  // Unfortunately, we cannot verify that the failure message contains
  // the right file path and line number the same way, as
  // EXPECT_NONFATAL_FAILURE() doesn't get to see the file path and
  // line number.  Instead, we do that in gtest_output_test_.cc.
}
References ADD_FAILURE_AT, and EXPECT_NONFATAL_FAILURE.
TEST() [103/164]
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest , FAIL) private
Definition at line 4696 of file gtest_unittest.cc.
                      {
  EXPECT_FATAL_FAILURE(FAIL(),
                       "Failed");
  EXPECT_FATAL_FAILURE(FAIL() << "Intentional failure.",
                       "Intentional failure.");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [104/164]
anonymous_namespace{gtest_unittest.cc}::TEST (MacroTest , SUCCEED) private
Definition at line 4704 of file gtest_unittest.cc.
{
  SUCCEED();
  SUCCEED() << "Explicit success.";
}
References SUCCEED.
TEST() [105/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest , ParsesAndReturnsValidValue) private
Definition at line 1780 of file gtest_unittest.cc.
{
  Int32 value = 123;
  EXPECT_TRUE(ParseInt32Flag("--" GTEST_FLAG_PREFIX_ "abc=456", "abc", &value));
  EXPECT_EQ(456, value);
  EXPECT_TRUE(ParseInt32Flag("--" GTEST_FLAG_PREFIX_ "abc=-789",
                             "abc", &value));
  EXPECT_EQ(-789, value);
}
References EXPECT_EQ, EXPECT_TRUE, GTEST_FLAG_PREFIX_, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [106/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest , ReturnsDefaultWhenValueIsInvalid) private
Definition at line 1766 of file gtest_unittest.cc.
{
  printf("(expecting 2 warnings)\n");
  Int32 value = 123;
  EXPECT_FALSE(ParseInt32Flag("--abc=A1", "abc", &value));
  EXPECT_EQ(123, value);
  EXPECT_FALSE(ParseInt32Flag("--abc=12X", "abc", &value));
  EXPECT_EQ(123, value);
}
References EXPECT_EQ, EXPECT_FALSE, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [107/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest , ReturnsDefaultWhenValueOverflows) private
Definition at line 1752 of file gtest_unittest.cc.
{
  printf("(expecting 2 warnings)\n");
  Int32 value = 123;
  EXPECT_FALSE(ParseInt32Flag("--abc=12345678987654321", "abc", &value));
  EXPECT_EQ(123, value);
  EXPECT_FALSE(ParseInt32Flag("--abc=-12345678987654321", "abc", &value));
  EXPECT_EQ(123, value);
}
References EXPECT_EQ, EXPECT_FALSE, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [108/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ParseInt32FlagTest , ReturnsFalseForInvalidFlag) private
Definition at line 1741 of file gtest_unittest.cc.
{
  Int32 value = 123;
  EXPECT_FALSE(ParseInt32Flag("--a=100", "b", &value));
  EXPECT_EQ(123, value);
  EXPECT_FALSE(ParseInt32Flag("a=100", "a", &value));
  EXPECT_EQ(123, value);
}
References EXPECT_EQ, EXPECT_FALSE, and anonymous_namespace{gtest_unittest.cc}::Uncopyable::value().
TEST() [109/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Pred1Test , SingleEvaluationOnFailure) private
Definition at line 2267 of file gtest_unittest.cc.
{
  // A success case.
  static int n = 0;
  EXPECT_PRED1(IsEven, n++);
  EXPECT_EQ(1, n) << "The argument is not evaluated exactly once.";
  // A failure case.
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_PRED_FORMAT1(AssertIsEvenFunctor(), n++)
        << "This failure is expected.";
  }, "This failure is expected.");
  EXPECT_EQ(2, n) << "The argument is not evaluated exactly once.";
}
References ASSERT_PRED_FORMAT1, EXPECT_EQ, EXPECT_FATAL_FAILURE, EXPECT_PRED1, and IsEven().
TEST() [110/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Pred1Test , WithFormat) private
Definition at line 2250 of file gtest_unittest.cc.
{
  // Success cases.
  EXPECT_PRED_FORMAT1(AssertIsEven, 2);
  ASSERT_PRED_FORMAT1(AssertIsEvenFunctor(), 4)
    << "This failure is UNEXPECTED!";
  // Failure cases.
  const int n = 5;
  EXPECT_NONFATAL_FAILURE(EXPECT_PRED_FORMAT1(AssertIsEvenFunctor(), n),
                          "n evaluates to 5, which is not even.");
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_PRED_FORMAT1(AssertIsEven, 5) << "This failure is expected.";
  }, "This failure is expected.");
}
References ASSERT_PRED_FORMAT1, AssertIsEven(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_PRED_FORMAT1.
TEST() [111/164]
anonymous_namespace{gtest_unittest.cc}::TEST (Pred1Test , WithoutFormat) private
Definition at line 2236 of file gtest_unittest.cc.
{
  // Success cases.
  EXPECT_PRED1(IsEvenFunctor(), 2) << "This failure is UNEXPECTED!";
  ASSERT_PRED1(IsEven, 4);
  // Failure cases.
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED1(IsEven, 5) << "This failure is expected.";
  }, "This failure is expected.");
  EXPECT_FATAL_FAILURE(ASSERT_PRED1(IsEvenFunctor(), 5),
                       "evaluates to false");
}
References ASSERT_PRED1, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, and IsEven().
TEST() [112/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateAssertionTest , AcceptsOverloadedFunction) private
Definition at line 2387 of file gtest_unittest.cc.
{
  // C++Builder requires C-style casts rather than static_cast.
  EXPECT_PRED1((bool (*)(int))(IsPositive), 5);  // NOLINT
  ASSERT_PRED1((bool (*)(double))(IsPositive), 6.0);  // NOLINT
}
References ASSERT_PRED1, EXPECT_PRED1, and IsPositive().
TEST() [113/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateAssertionTest , AcceptsTemplateFunction) private
Definition at line 2395 of file gtest_unittest.cc.
{
  EXPECT_PRED1(IsNegative<int>, -5);
  // Makes sure that we can handle templates with more than one
  // parameter.
  ASSERT_PRED2((GreaterThan<int, int>), 5, 0);
}
References ASSERT_PRED2, and EXPECT_PRED1.
TEST() [114/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateFormatAssertionTest , AcceptsOverloadedFunction) private
Definition at line 2431 of file gtest_unittest.cc.
{
  EXPECT_PRED_FORMAT1(IsPositiveFormat, 5);
  ASSERT_PRED_FORMAT1(IsPositiveFormat, 6.0);
}
References ASSERT_PRED_FORMAT1, EXPECT_PRED_FORMAT1, and IsPositiveFormat().
TEST() [115/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredicateFormatAssertionTest , AcceptsTemplateFunction) private
Definition at line 2438 of file gtest_unittest.cc.
{
  EXPECT_PRED_FORMAT1(IsNegativeFormat, -5);
  ASSERT_PRED_FORMAT2(EqualsFormat, 3, 3);
}
References ASSERT_PRED_FORMAT2, EqualsFormat(), EXPECT_PRED_FORMAT1, and IsNegativeFormat().
TEST() [116/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredTest , SingleEvaluationOnFailure) private
Definition at line 2324 of file gtest_unittest.cc.
{
  // A success case.
  int n1 = 0;
  int n2 = 0;
  EXPECT_PRED2(SumIsEven2, n1++, n2++);
  EXPECT_EQ(1, n1) << "Argument 1 is not evaluated exactly once.";
  EXPECT_EQ(1, n2) << "Argument 2 is not evaluated exactly once.";
  // Another success case.
  n1 = n2 = 0;
  int n3 = 0;
  int n4 = 0;
  int n5 = 0;
  ASSERT_PRED_FORMAT5(AssertSumIsEven5Functor(),
                      n1++, n2++, n3++, n4++, n5++)
                        << "This failure is UNEXPECTED!";
  EXPECT_EQ(1, n1) << "Argument 1 is not evaluated exactly once.";
  EXPECT_EQ(1, n2) << "Argument 2 is not evaluated exactly once.";
  EXPECT_EQ(1, n3) << "Argument 3 is not evaluated exactly once.";
  EXPECT_EQ(1, n4) << "Argument 4 is not evaluated exactly once.";
  EXPECT_EQ(1, n5) << "Argument 5 is not evaluated exactly once.";
  // A failure case.
  n1 = n2 = n3 = 0;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED3(SumIsEven3Functor(), ++n1, n2++, n3++)
        << "This failure is expected.";
  }, "This failure is expected.");
  EXPECT_EQ(1, n1) << "Argument 1 is not evaluated exactly once.";
  EXPECT_EQ(1, n2) << "Argument 2 is not evaluated exactly once.";
  EXPECT_EQ(1, n3) << "Argument 3 is not evaluated exactly once.";
  // Another failure case.
  n1 = n2 = n3 = n4 = 0;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT4(AssertSumIsEven4, ++n1, n2++, n3++, n4++);
  }, "evaluates to 1, which is not even.");
  EXPECT_EQ(1, n1) << "Argument 1 is not evaluated exactly once.";
  EXPECT_EQ(1, n2) << "Argument 2 is not evaluated exactly once.";
  EXPECT_EQ(1, n3) << "Argument 3 is not evaluated exactly once.";
  EXPECT_EQ(1, n4) << "Argument 4 is not evaluated exactly once.";
}
References ASSERT_PRED_FORMAT5, AssertSumIsEven4(), EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, EXPECT_PRED3, EXPECT_PRED_FORMAT4, and SumIsEven2().
TEST() [117/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredTest , WithFormat) private
Definition at line 2302 of file gtest_unittest.cc.
{
  // Success cases.
  ASSERT_PRED_FORMAT4(AssertSumIsEven4, 4, 6, 8, 10) <<
    "This failure is UNEXPECTED!";
  EXPECT_PRED_FORMAT5(AssertSumIsEven5Functor(), 2, 4, 6, 8, 10);
  // Failure cases.
  const int n1 = 1;
  const int n2 = 2;
  const int n3 = 4;
  const int n4 = 6;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT4(AssertSumIsEven4, n1, n2, n3, n4);
  }, "evaluates to 13, which is not even.");
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_PRED_FORMAT5(AssertSumIsEven5Functor(), 1, 2, 4, 6, 8)
        << "This failure is expected.";
  }, "This failure is expected.");
}
References ASSERT_PRED_FORMAT4, ASSERT_PRED_FORMAT5, AssertSumIsEven4(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED_FORMAT4, and EXPECT_PRED_FORMAT5.
TEST() [118/164]
anonymous_namespace{gtest_unittest.cc}::TEST (PredTest , WithoutFormat) private
Definition at line 2285 of file gtest_unittest.cc.
{
  // Success cases.
  ASSERT_PRED2(SumIsEven2, 2, 4) << "This failure is UNEXPECTED!";
  EXPECT_PRED3(SumIsEven3Functor(), 4, 6, 8);
  // Failure cases.
  const int n1 = 1;
  const int n2 = 2;
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED2(SumIsEven2, n1, n2) << "This failure is expected.";
  }, "This failure is expected.");
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_PRED3(SumIsEven3Functor(), 1, 2, 4);
  }, "evaluates to false");
}
References ASSERT_PRED2, ASSERT_PRED3, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED2, EXPECT_PRED3, and SumIsEven2().
TEST() [119/164]
anonymous_namespace{gtest_unittest.cc}::TEST (RandomDeathTest , GeneratesCrashesOnInvalidRange) private
Definition at line 735 of file gtest_unittest.cc.
{
  testing::internal::Random random(42);
  EXPECT_DEATH_IF_SUPPORTED(
      random.Generate(0),
      "Cannot generate a number in the range \\[0, 0\\)");
  EXPECT_DEATH_IF_SUPPORTED(
      random.Generate(testing::internal::Random::kMaxRange + 1),
      "Generation of a number in \\[0, 2147483649\\) was requested, "
      "but this can only generate numbers in \\[0, 2147483648\\)");
}
References EXPECT_DEATH_IF_SUPPORTED, testing::internal::Random::Generate(), and testing::internal::Random::kMaxRange.
TEST() [120/164]
anonymous_namespace{gtest_unittest.cc}::TEST (RandomTest , GeneratesNumbersWithinRange) private
Definition at line 746 of file gtest_unittest.cc.
{
  const UInt32 kRange = 10000;
  testing::internal::Random random(12345);
  for (int i = 0; i < 10; i++) {
    EXPECT_LT(random.Generate(kRange), kRange) << " for iteration " << i;
  }
  testing::internal::Random random2(testing::internal::Random::kMaxRange);
  for (int i = 0; i < 10; i++) {
    EXPECT_LT(random2.Generate(kRange), kRange) << " for iteration " << i;
  }
}
References EXPECT_LT, testing::internal::Random::Generate(), and testing::internal::Random::kMaxRange.
TEST() [121/164]
anonymous_namespace{gtest_unittest.cc}::TEST (RandomTest , RepeatsWhenReseeded) private
Definition at line 759 of file gtest_unittest.cc.
{
  const int kSeed = 123;
  const int kArraySize = 10;
  const UInt32 kRange = 10000;
  UInt32 values[kArraySize];
  testing::internal::Random random(kSeed);
  for (int i = 0; i < kArraySize; i++) {
    values[i] = random.Generate(kRange);
  }
  random.Reseed(kSeed);
  for (int i = 0; i < kArraySize; i++) {
    EXPECT_EQ(values[i], random.Generate(kRange)) << " for iteration " << i;
  }
}
References EXPECT_EQ, testing::internal::Random::Generate(), and testing::internal::Random::Reseed().
TEST() [122/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ShouldRunTestOnShardTest , IsPartitionWhenThereAreFiveShards) private
Definition at line 1911 of file gtest_unittest.cc.
{
  // Choose an arbitrary number of tests and shards.
  const int num_tests = 17;
  const int num_shards = 5;
  // Check partitioning: each test should be on exactly 1 shard.
  for (int test_id = 0; test_id < num_tests; test_id++) {
    int prev_selected_shard_index = -1;
    for (int shard_index = 0; shard_index < num_shards; shard_index++) {
      if (ShouldRunTestOnShard(num_shards, shard_index, test_id)) {
        if (prev_selected_shard_index < 0) {
          prev_selected_shard_index = shard_index;
        } else {
          ADD_FAILURE() << "Shard " << prev_selected_shard_index << " and "
            << shard_index << " are both selected to run test " << test_id;
        }
      }
    }
  }
  // Check balance: This is not required by the sharding protocol, but is a
  // desirable property for performance.
  for (int shard_index = 0; shard_index < num_shards; shard_index++) {
    int num_tests_on_shard = 0;
    for (int test_id = 0; test_id < num_tests; test_id++) {
      num_tests_on_shard +=
        ShouldRunTestOnShard(num_shards, shard_index, test_id);
    }
    EXPECT_GE(num_tests_on_shard, num_tests / num_shards);
  }
}
References ADD_FAILURE, and EXPECT_GE.
TEST() [123/164]
anonymous_namespace{gtest_unittest.cc}::TEST (ShouldRunTestOnShardTest , IsPartitionWhenThereIsOneShard) private
Definition at line 1823 of file gtest_unittest.cc.
{
  EXPECT_TRUE(ShouldRunTestOnShard(1, 0, 0));
  EXPECT_TRUE(ShouldRunTestOnShard(1, 0, 1));
  EXPECT_TRUE(ShouldRunTestOnShard(1, 0, 2));
  EXPECT_TRUE(ShouldRunTestOnShard(1, 0, 3));
  EXPECT_TRUE(ShouldRunTestOnShard(1, 0, 4));
}
References EXPECT_TRUE.
TEST() [124/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest , BasicIoManip) private
Definition at line 4657 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE({  // NOLINT
    FAIL() << "Line 1." << std::endl
           << "A NUL char " << std::ends << std::flush << " in line 2.";
  }, "Line 1.\nA NUL char \\0 in line 2.");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [125/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest , int) private
Definition at line 4640 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(FAIL() << 900913,
                       "900913");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [126/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest , NULChar) private
Definition at line 4633 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE({  // NOLINT
    FAIL() << "A NUL" << '\0' << " and some more string";
  }, "A NUL\\0 and some more string");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [127/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest , NullCharPtr) private
Definition at line 4650 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(FAIL() << static_cast<const char*>(NULL),
                       "(null)");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [128/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest , string) private
Definition at line 4613 of file gtest_unittest.cc.
{
  static const std::string str(
      "This failure message is a std::string, and is expected.");
  EXPECT_FATAL_FAILURE(FAIL() << str,
                       str.c_str());
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [129/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableTest , stringWithEmbeddedNUL) private
Definition at line 4622 of file gtest_unittest.cc.
{
  static const char char_array_with_nul[] =
      "Here's a NUL\0 and some more string";
  static const std::string string_with_nul(char_array_with_nul,
                                           sizeof(char_array_with_nul)
                                           - 1);  // drops the trailing NUL
  EXPECT_FATAL_FAILURE(FAIL() << string_with_nul,
                       "Here's a NUL\\0 and some more string");
}
References EXPECT_FATAL_FAILURE, and FAIL.
TEST() [130/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest , CString) private
Definition at line 4600 of file gtest_unittest.cc.
{
  EXPECT_STREQ("Foo", StreamableToString("Foo").c_str());
}
References EXPECT_STREQ.
TEST() [131/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest , NullCString) private
Definition at line 4605 of file gtest_unittest.cc.
{
  char* p = NULL;
  EXPECT_STREQ("(null)", StreamableToString(p).c_str());
}
References EXPECT_STREQ.
TEST() [132/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest , NullPointer) private
Definition at line 4594 of file gtest_unittest.cc.
{
  int* p = NULL;
  EXPECT_STREQ("(null)", StreamableToString(p).c_str());
}
References EXPECT_STREQ.
TEST() [133/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest , Pointer) private
Definition at line 4587 of file gtest_unittest.cc.
{
  int n = 0;
  int* p = &n;
  EXPECT_STRNE("(null)", StreamableToString(p).c_str());
}
References EXPECT_STRNE.
TEST() [134/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StreamableToStringTest , Scalar) private
Definition at line 4582 of file gtest_unittest.cc.
{
  EXPECT_STREQ("5", StreamableToString(5).c_str());
}
References EXPECT_STREQ.
TEST() [135/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , ASSERT_STRCASEEQ) private
Definition at line 2486 of file gtest_unittest.cc.
{
  ASSERT_STRCASEEQ("hi", "Hi");
  ASSERT_STRCASEEQ(static_cast<const char *>(NULL), NULL);
  ASSERT_STRCASEEQ("", "");
  EXPECT_FATAL_FAILURE(ASSERT_STRCASEEQ("Hi", "hi2"),
                       "Ignoring case");
}
References ASSERT_STRCASEEQ, and EXPECT_FATAL_FAILURE.
TEST() [136/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , ASSERT_STRCASENE) private
Definition at line 2496 of file gtest_unittest.cc.
{
  ASSERT_STRCASENE("hi1", "Hi2");
  ASSERT_STRCASENE("Hi", NULL);
  ASSERT_STRCASENE(NULL, "Hi");
  ASSERT_STRCASENE("", NULL);
  ASSERT_STRCASENE(NULL, "");
  ASSERT_STRCASENE("", "Hi");
  ASSERT_STRCASENE("Hi", "");
  EXPECT_FATAL_FAILURE(ASSERT_STRCASENE("Hi", "hi"),
                       "(ignoring case)");
}
References ASSERT_STRCASENE, and EXPECT_FATAL_FAILURE.
TEST() [137/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , ASSERT_STREQ) private
Definition at line 2447 of file gtest_unittest.cc.
{
  const char * const p1 = "good";
  ASSERT_STREQ(p1, p1);
  // Let p2 have the same content as p1, but be at a different address.
  const char p2[] = "good";
  ASSERT_STREQ(p1, p2);
  EXPECT_FATAL_FAILURE(ASSERT_STREQ("bad", "good"),
                       "  \"bad\"\n  \"good\"");
}
References ASSERT_STREQ, and EXPECT_FATAL_FAILURE.
TEST() [138/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , ASSERT_STREQ_Null) private
Definition at line 2460 of file gtest_unittest.cc.
{
  ASSERT_STREQ(static_cast<const char *>(NULL), NULL);
  EXPECT_FATAL_FAILURE(ASSERT_STREQ(NULL, "non-null"),
                       "non-null");
}
References ASSERT_STREQ, and EXPECT_FATAL_FAILURE.
TEST() [139/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , ASSERT_STREQ_Null2) private
Definition at line 2467 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(ASSERT_STREQ("non-null", NULL),
                       "non-null");
}
References ASSERT_STREQ, and EXPECT_FATAL_FAILURE.
TEST() [140/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , ASSERT_STRNE) private
Definition at line 2473 of file gtest_unittest.cc.
{
  ASSERT_STRNE("hi", "Hi");
  ASSERT_STRNE("Hi", NULL);
  ASSERT_STRNE(NULL, "Hi");
  ASSERT_STRNE("", NULL);
  ASSERT_STRNE(NULL, "");
  ASSERT_STRNE("", "Hi");
  ASSERT_STRNE("Hi", "");
  EXPECT_FATAL_FAILURE(ASSERT_STRNE("Hi", "Hi"),
                       "\"Hi\" vs \"Hi\"");
}
References ASSERT_STRNE, and EXPECT_FATAL_FAILURE.
TEST() [141/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , STREQ_Wide) private
Definition at line 2509 of file gtest_unittest.cc.
{
  // NULL strings.
  ASSERT_STREQ(static_cast<const wchar_t *>(NULL), NULL);
  // Empty strings.
  ASSERT_STREQ(L"", L"");
  // Non-null vs NULL.
  EXPECT_NONFATAL_FAILURE(EXPECT_STREQ(L"non-null", NULL),
                          "non-null");
  // Equal strings.
  EXPECT_STREQ(L"Hi", L"Hi");
  // Unequal strings.
  EXPECT_NONFATAL_FAILURE(EXPECT_STREQ(L"abc", L"Abc"),
                          "Abc");
  // Strings containing wide characters.
  EXPECT_NONFATAL_FAILURE(EXPECT_STREQ(L"abc\x8119", L"abc\x8120"),
                          "abc");
  // The streaming variation.
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_STREQ(L"abc\x8119", L"abc\x8121") << "Expected failure";
  }, "Expected failure");
}
References ASSERT_STREQ, EXPECT_NONFATAL_FAILURE, and EXPECT_STREQ.
TEST() [142/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringAssertionTest , STRNE_Wide) private
Definition at line 2538 of file gtest_unittest.cc.
{
  // NULL strings.
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_STRNE(static_cast<const wchar_t *>(NULL), NULL);
  }, "");
  // Empty strings.
  EXPECT_NONFATAL_FAILURE(EXPECT_STRNE(L"", L""),
                          "L\"\"");
  // Non-null vs NULL.
  ASSERT_STRNE(L"non-null", NULL);
  // Equal strings.
  EXPECT_NONFATAL_FAILURE(EXPECT_STRNE(L"Hi", L"Hi"),
                          "L\"Hi\"");
  // Unequal strings.
  EXPECT_STRNE(L"abc", L"Abc");
  // Strings containing wide characters.
  EXPECT_NONFATAL_FAILURE(EXPECT_STRNE(L"abc\x8119", L"abc\x8119"),
                          "abc");
  // The streaming variation.
  ASSERT_STRNE(L"abc\x8119", L"abc\x8120") << "This shouldn't happen";
}
References ASSERT_STRNE, EXPECT_NONFATAL_FAILURE, and EXPECT_STRNE.
TEST() [143/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringTest , CaseInsensitiveWideCStringEquals) private
Definition at line 1041 of file gtest_unittest.cc.
{
  EXPECT_TRUE(String::CaseInsensitiveWideCStringEquals(NULL, NULL));
  EXPECT_FALSE(String::CaseInsensitiveWideCStringEquals(kNull, L""));
  EXPECT_FALSE(String::CaseInsensitiveWideCStringEquals(L"", kNull));
  EXPECT_FALSE(String::CaseInsensitiveWideCStringEquals(kNull, L"foobar"));
  EXPECT_FALSE(String::CaseInsensitiveWideCStringEquals(L"foobar", kNull));
  EXPECT_TRUE(String::CaseInsensitiveWideCStringEquals(L"foobar", L"foobar"));
  EXPECT_TRUE(String::CaseInsensitiveWideCStringEquals(L"foobar", L"FOOBAR"));
  EXPECT_TRUE(String::CaseInsensitiveWideCStringEquals(L"FOOBAR", L"foobar"));
}
References testing::internal::String::CaseInsensitiveWideCStringEquals(), EXPECT_FALSE, EXPECT_TRUE, and kNull.
TEST() [144/164]
anonymous_namespace{gtest_unittest.cc}::TEST (StringTest , EndsWithCaseInsensitive) private
Definition at line 1024 of file gtest_unittest.cc.
{
  EXPECT_TRUE(String::EndsWithCaseInsensitive("foobar", "BAR"));
  EXPECT_TRUE(String::EndsWithCaseInsensitive("foobaR", "bar"));
  EXPECT_TRUE(String::EndsWithCaseInsensitive("foobar", ""));
  EXPECT_TRUE(String::EndsWithCaseInsensitive("", ""));
  EXPECT_FALSE(String::EndsWithCaseInsensitive("Foobar", "foo"));
  EXPECT_FALSE(String::EndsWithCaseInsensitive("foobar", "Foo"));
  EXPECT_FALSE(String::EndsWithCaseInsensitive("", "foo"));
}
References testing::internal::String::EndsWithCaseInsensitive(), EXPECT_FALSE, and EXPECT_TRUE.
TEST() [145/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest , ConstructorWorks) private
Definition at line 1340 of file gtest_unittest.cc.
{
  const TestProperty property("key", "value");
  EXPECT_STREQ("key", property.key());
  EXPECT_STREQ("value", property.value());
}
References EXPECT_STREQ, testing::TestProperty::key(), and testing::TestProperty::value().
TEST() [146/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest , ReplaceStringValue) private
Definition at line 1097 of file gtest_unittest.cc.
{
  TestProperty property("key", "1");
  EXPECT_STREQ("1", property.value());
  property.SetValue("2");
  EXPECT_STREQ("2", property.value());
}
References EXPECT_STREQ, and testing::TestProperty::value().
TEST() [147/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest , SetValue) private
Definition at line 1346 of file gtest_unittest.cc.
{
  TestProperty property("key", "value_1");
  EXPECT_STREQ("key", property.key());
  property.SetValue("value_2");
  EXPECT_STREQ("key", property.key());
  EXPECT_STREQ("value_2", property.value());
}
References EXPECT_STREQ, testing::TestProperty::key(), and testing::TestProperty::value().
TEST() [148/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestPropertyTest , StringValue) private
Definition at line 1090 of file gtest_unittest.cc.
{
  TestProperty property("key", "1");
  EXPECT_STREQ("key", property.key());
  EXPECT_STREQ("1", property.value());
}
References EXPECT_STREQ, testing::TestProperty::key(), and testing::TestProperty::value().
TEST() [149/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest , GetTestProperty) private
Definition at line 1518 of file gtest_unittest.cc.
{
  TestResult test_result;
  TestProperty property_1("key_1", "1");
  TestProperty property_2("key_2", "2");
  TestProperty property_3("key_3", "3");
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_1);
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_2);
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_3);
  const TestProperty& fetched_property_1 = test_result.GetTestProperty(0);
  const TestProperty& fetched_property_2 = test_result.GetTestProperty(1);
  const TestProperty& fetched_property_3 = test_result.GetTestProperty(2);
  EXPECT_STREQ("key_1", fetched_property_1.key());
  EXPECT_STREQ("1", fetched_property_1.value());
  EXPECT_STREQ("key_2", fetched_property_2.key());
  EXPECT_STREQ("2", fetched_property_2.value());
  EXPECT_STREQ("key_3", fetched_property_3.key());
  EXPECT_STREQ("3", fetched_property_3.value());
  EXPECT_DEATH_IF_SUPPORTED(test_result.GetTestProperty(3), "");
  EXPECT_DEATH_IF_SUPPORTED(test_result.GetTestProperty(-1), "");
}
References EXPECT_DEATH_IF_SUPPORTED, EXPECT_STREQ, testing::TestResult::GetTestProperty(), testing::TestProperty::key(), testing::internal::TestResultAccessor::RecordProperty(), and testing::TestProperty::value().
TEST() [150/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest , MultiplePropertiesFoundWhenAdded) private
Definition at line 1479 of file gtest_unittest.cc.
{
  TestResult test_result;
  TestProperty property_1("key_1", "1");
  TestProperty property_2("key_2", "2");
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_1);
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_2);
  ASSERT_EQ(2, test_result.test_property_count());
  const TestProperty& actual_property_1 = test_result.GetTestProperty(0);
  EXPECT_STREQ("key_1", actual_property_1.key());
  EXPECT_STREQ("1", actual_property_1.value());
  const TestProperty& actual_property_2 = test_result.GetTestProperty(1);
  EXPECT_STREQ("key_2", actual_property_2.key());
  EXPECT_STREQ("2", actual_property_2.value());
}
References ASSERT_EQ, EXPECT_STREQ, testing::TestResult::GetTestProperty(), testing::TestProperty::key(), testing::internal::TestResultAccessor::RecordProperty(), testing::TestResult::test_property_count(), and testing::TestProperty::value().
TEST() [151/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest , NoPropertiesFoundWhenNoneAreAdded) private
Definition at line 1462 of file gtest_unittest.cc.
{
  TestResult test_result;
  ASSERT_EQ(0, test_result.test_property_count());
}
References ASSERT_EQ, and testing::TestResult::test_property_count().
TEST() [152/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest , OnePropertyFoundWhenAdded) private
Definition at line 1468 of file gtest_unittest.cc.
{
  TestResult test_result;
  TestProperty property("key_1", "1");
  TestResultAccessor::RecordProperty(&test_result, "testcase", property);
  ASSERT_EQ(1, test_result.test_property_count());
  const TestProperty& actual_property = test_result.GetTestProperty(0);
  EXPECT_STREQ("key_1", actual_property.key());
  EXPECT_STREQ("1", actual_property.value());
}
References ASSERT_EQ, EXPECT_STREQ, testing::TestResult::GetTestProperty(), testing::TestProperty::key(), testing::internal::TestResultAccessor::RecordProperty(), testing::TestResult::test_property_count(), and testing::TestProperty::value().
TEST() [153/164]
anonymous_namespace{gtest_unittest.cc}::TEST (TestResultPropertyTest , OverridesValuesForDuplicateKeys) private
Definition at line 1496 of file gtest_unittest.cc.
{
  TestResult test_result;
  TestProperty property_1_1("key_1", "1");
  TestProperty property_2_1("key_2", "2");
  TestProperty property_1_2("key_1", "12");
  TestProperty property_2_2("key_2", "22");
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_1_1);
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_2_1);
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_1_2);
  TestResultAccessor::RecordProperty(&test_result, "testcase", property_2_2);
  ASSERT_EQ(2, test_result.test_property_count());
  const TestProperty& actual_property_1 = test_result.GetTestProperty(0);
  EXPECT_STREQ("key_1", actual_property_1.key());
  EXPECT_STREQ("12", actual_property_1.value());
  const TestProperty& actual_property_2 = test_result.GetTestProperty(1);
  EXPECT_STREQ("key_2", actual_property_2.key());
  EXPECT_STREQ("22", actual_property_2.value());
}
References ASSERT_EQ, EXPECT_STREQ, testing::TestResult::GetTestProperty(), testing::TestProperty::key(), testing::internal::TestResultAccessor::RecordProperty(), testing::TestResult::test_property_count(), and testing::TestProperty::value().
TEST() [154/164]
anonymous_namespace{gtest_unittest.cc}::TEST (UnitTestTest , CanGetOriginalWorkingDir) private
Definition at line 1953 of file gtest_unittest.cc.
{
  ASSERT_TRUE(UnitTest::GetInstance()->original_working_dir() != NULL);
  EXPECT_STRNE(UnitTest::GetInstance()->original_working_dir(), "");
}
References ASSERT_TRUE, EXPECT_STRNE, and testing::UnitTest::GetInstance().
TEST() [155/164]
anonymous_namespace{gtest_unittest.cc}::TEST (UnitTestTest , ReturnsPlausibleTimestamp) private
Definition at line 1958 of file gtest_unittest.cc.
{
  EXPECT_LT(0, UnitTest::GetInstance()->start_timestamp());
  EXPECT_LE(UnitTest::GetInstance()->start_timestamp(), GetTimeInMillis());
}
References EXPECT_LE, EXPECT_LT, and testing::UnitTest::GetInstance().
TEST() [156/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , CanEncode12To16Bits) private
Definition at line 646 of file gtest_unittest.cc.
{
  // 0000 1000 1101 0011 => 1110-0000 10-100011 10-010011
  const wchar_t s1[] = { 0x8D3, '\0' };
  EXPECT_STREQ("\xE0\xA3\x93", WideStringToUtf8(s1, 1).c_str());
  EXPECT_STREQ("\xE0\xA3\x93", WideStringToUtf8(s1, -1).c_str());
  // 1100 0111 0100 1101 => 1110-1100 10-011101 10-001101
  const wchar_t s2[] = { 0xC74D, '\0' };
  EXPECT_STREQ("\xEC\x9D\x8D", WideStringToUtf8(s2, 1).c_str());
  EXPECT_STREQ("\xEC\x9D\x8D", WideStringToUtf8(s2, -1).c_str());
}
References EXPECT_STREQ.
TEST() [157/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , CanEncode17To21Bits) private
Definition at line 673 of file gtest_unittest.cc.
{
  // 0 0001 0000 1000 1101 0011 => 11110-000 10-010000 10-100011 10-010011
  EXPECT_STREQ("\xF0\x90\xA3\x93", WideStringToUtf8(L"\x108D3", 1).c_str());
  EXPECT_STREQ("\xF0\x90\xA3\x93", WideStringToUtf8(L"\x108D3", -1).c_str());
  // 1 0000 1000 0110 0011 0100 => 11110-100 10-001000 10-011000 10-110100
  EXPECT_STREQ("\xF4\x88\x98\xB4", WideStringToUtf8(L"\x108634", 1).c_str());
  EXPECT_STREQ("\xF4\x88\x98\xB4", WideStringToUtf8(L"\x108634", -1).c_str());
}
References EXPECT_STREQ.
TEST() [158/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , CanEncode8To11Bits) private
Definition at line 633 of file gtest_unittest.cc.
{
  // 000 1101 0011 => 110-00011 10-010011
  EXPECT_STREQ("\xC3\x93", WideStringToUtf8(L"\xD3", 1).c_str());
  EXPECT_STREQ("\xC3\x93", WideStringToUtf8(L"\xD3", -1).c_str());
  // 101 0111 0110 => 110-10101 10-110110
  const wchar_t s[] = { 0x576, '\0' };
  EXPECT_STREQ("\xD5\xB6", WideStringToUtf8(s, 1).c_str());
  EXPECT_STREQ("\xD5\xB6", WideStringToUtf8(s, -1).c_str());
}
References EXPECT_STREQ.
TEST() [159/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , CanEncodeAscii) private
Definition at line 624 of file gtest_unittest.cc.
{
  EXPECT_STREQ("a", WideStringToUtf8(L"a", 1).c_str());
  EXPECT_STREQ("ab", WideStringToUtf8(L"ab", 2).c_str());
  EXPECT_STREQ("a", WideStringToUtf8(L"a", -1).c_str());
  EXPECT_STREQ("ab", WideStringToUtf8(L"ab", -1).c_str());
}
References EXPECT_STREQ.
TEST() [160/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , CanEncodeInvalidCodePoint) private
Definition at line 684 of file gtest_unittest.cc.
{
  EXPECT_STREQ("(Invalid Unicode 0xABCDFF)",
               WideStringToUtf8(L"\xABCDFF", -1).c_str());
}
References EXPECT_STREQ.
TEST() [161/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , CanEncodeNul) private
Definition at line 618 of file gtest_unittest.cc.
{
  EXPECT_STREQ("", WideStringToUtf8(L"", 0).c_str());
  EXPECT_STREQ("", WideStringToUtf8(L"", -1).c_str());
}
References EXPECT_STREQ.
TEST() [162/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , ConcatenatesCodepointsCorrectly) private
Definition at line 713 of file gtest_unittest.cc.
{
  const wchar_t s[] = { 0x108634, 0xC74D, '\n', 0x576, 0x8D3, 0x108634, '\0'};
  EXPECT_STREQ(
      "\xF4\x88\x98\xB4"
          "\xEC\x9D\x8D"
          "\n"
          "\xD5\xB6"
          "\xE0\xA3\x93"
          "\xF4\x88\x98\xB4",
      WideStringToUtf8(s, -1).c_str());
}
References EXPECT_STREQ.
TEST() [163/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , StopsOnNulCharacter) private
Definition at line 659 of file gtest_unittest.cc.
{
  EXPECT_STREQ("ABC", WideStringToUtf8(L"ABC\0XYZ", 100).c_str());
}
References EXPECT_STREQ.
TEST() [164/164]
anonymous_namespace{gtest_unittest.cc}::TEST (WideStringToUtf8Test , StopsWhenLengthLimitReached) private
Definition at line 665 of file gtest_unittest.cc.
{
  EXPECT_STREQ("ABC", WideStringToUtf8(L"ABCDEF", 3).c_str());
}
References EXPECT_STREQ.
TEST_F() [1/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DisabledTestsTest , DISABLED_TestShouldNotRun_1) private
Definition at line 3156 of file gtest_unittest.cc.
{
  FAIL() << "Unexpected failure: Disabled test should not be run.";
}
References FAIL.
TEST_F() [2/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DisabledTestsTest , DISABLED_TestShouldNotRun_2) private
Definition at line 3160 of file gtest_unittest.cc.
{
  FAIL() << "Unexpected failure: Disabled test should not be run.";
}
References FAIL.
TEST_F() [3/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , AlmostZeros) private
Definition at line 2963 of file gtest_unittest.cc.
{
  // In C++Builder, names within local classes (such as used by
  // EXPECT_FATAL_FAILURE) cannot be resolved against static members of the
  // scoping class.  Use a static local alias as a workaround.
  // We use the assignment syntax since some compilers, like Sun Studio,
  // don't allow initializing references using construction syntax
  // (parentheses).
  static const DoubleTest::TestValues& v = this->values_;
  EXPECT_DOUBLE_EQ(0.0, v.close_to_positive_zero);
  EXPECT_DOUBLE_EQ(-0.0, v.close_to_negative_zero);
  EXPECT_DOUBLE_EQ(v.close_to_positive_zero, v.close_to_negative_zero);
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_DOUBLE_EQ(v.close_to_positive_zero,
                     v.further_from_negative_zero);
  }, "v.further_from_negative_zero");
}
References ASSERT_DOUBLE_EQ, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::close_to_negative_zero, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::close_to_positive_zero, EXPECT_DOUBLE_EQ, EXPECT_FATAL_FAILURE, and anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::further_from_negative_zero.
TEST_F() [4/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , ASSERT_NEAR) private
Definition at line 3067 of file gtest_unittest.cc.
{
  ASSERT_NEAR(-1.0, -1.1, 0.2);
  ASSERT_NEAR(2.0, 3.0, 1.0);
  EXPECT_FATAL_FAILURE(ASSERT_NEAR(1.0, 1.5, 0.25),  // NOLINT
                       "The difference between 1.0 and 1.5 is 0.5, "
                       "which exceeds 0.25");
  // To work around a bug in gcc 2.95.0, there is intentionally no
  // space after the first comma in the previous statement.
}
References ASSERT_NEAR, and EXPECT_FATAL_FAILURE.
TEST_F() [5/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , Commutative) private
Definition at line 3046 of file gtest_unittest.cc.
{
  // We already tested EXPECT_DOUBLE_EQ(1.0, values_.close_to_one).
  EXPECT_DOUBLE_EQ(values_.close_to_one, 1.0);
  // We already tested EXPECT_DOUBLE_EQ(1.0, values_.further_from_one).
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(values_.further_from_one, 1.0),
                          "1.0");
}
References EXPECT_DOUBLE_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [6/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , DoubleLEFails) private
Definition at line 3087 of file gtest_unittest.cc.
{
  // When val1 is greater than val2 by a large margin,
  EXPECT_NONFATAL_FAILURE(EXPECT_PRED_FORMAT2(DoubleLE, 2.0, 1.0),
                          "(2.0) <= (1.0)");
  // or by a small yet non-negligible margin,
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT2(DoubleLE, values_.further_from_one, 1.0);
  }, "(values_.further_from_one) <= (1.0)");
#if !GTEST_OS_SYMBIAN && !defined(__BORLANDC__)
  // Nokia's STLport crashes if we try to output infinity or NaN.
  // C++Builder gives bad results for ordered comparisons involving NaNs
  // due to compiler bugs.
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT2(DoubleLE, values_.nan1, values_.infinity);
  }, "(values_.nan1) <= (values_.infinity)");
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT2(DoubleLE, -values_.infinity, values_.nan1);
  }, " (-values_.infinity) <= (values_.nan1)");
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_PRED_FORMAT2(DoubleLE, values_.nan1, values_.nan1);
  }, "(values_.nan1) <= (values_.nan1)");
#endif  // !GTEST_OS_SYMBIAN && !defined(__BORLANDC__)
}
References ASSERT_PRED_FORMAT2, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_PRED_FORMAT2.
TEST_F() [7/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , DoubleLESucceeds) private
Definition at line 3078 of file gtest_unittest.cc.
{
  EXPECT_PRED_FORMAT2(DoubleLE, 1.0, 2.0);  // When val1 < val2,
  ASSERT_PRED_FORMAT2(DoubleLE, 1.0, 1.0);  // val1 == val2,
  // or when val1 is greater than, but almost equals to, val2.
  EXPECT_PRED_FORMAT2(DoubleLE, values_.close_to_positive_zero, 0.0);
}
References ASSERT_PRED_FORMAT2, and EXPECT_PRED_FORMAT2.
TEST_F() [8/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , EXPECT_NEAR) private
Definition at line 3056 of file gtest_unittest.cc.
{
  EXPECT_NEAR(-1.0, -1.1, 0.2);
  EXPECT_NEAR(2.0, 3.0, 1.0);
  EXPECT_NONFATAL_FAILURE(EXPECT_NEAR(1.0, 1.5, 0.25),  // NOLINT
                          "The difference between 1.0 and 1.5 is 0.5, "
                          "which exceeds 0.25");
  // To work around a bug in gcc 2.95.0, there is intentionally no
  // space after the first comma in the previous statement.
}
References EXPECT_NEAR, and EXPECT_NONFATAL_FAILURE.
TEST_F() [9/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , Infinity) private
Definition at line 2999 of file gtest_unittest.cc.
{
  EXPECT_DOUBLE_EQ(values_.infinity, values_.close_to_infinity);
  EXPECT_DOUBLE_EQ(-values_.infinity, -values_.close_to_infinity);
#if !GTEST_OS_SYMBIAN
  // Nokia's STLport crashes if we try to output infinity or NaN.
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(values_.infinity, -values_.infinity),
                          "-values_.infinity");
  // This is interesting as the representations of infinity_ and nan1_
  // are only 1 DLP apart.
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(values_.infinity, values_.nan1),
                          "values_.nan1");
#endif  // !GTEST_OS_SYMBIAN
}
References EXPECT_DOUBLE_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [10/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , LargeDiff) private
Definition at line 2990 of file gtest_unittest.cc.
{
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(2.0, 3.0),
                          "3.0");
}
References EXPECT_DOUBLE_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [11/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , NaN) private
Definition at line 3015 of file gtest_unittest.cc.
{
#if !GTEST_OS_SYMBIAN
  // In C++Builder, names within local classes (such as used by
  // EXPECT_FATAL_FAILURE) cannot be resolved against static members of the
  // scoping class.  Use a static local alias as a workaround.
  // We use the assignment syntax since some compilers, like Sun Studio,
  // don't allow initializing references using construction syntax
  // (parentheses).
  static const DoubleTest::TestValues& v = this->values_;
  // Nokia's STLport crashes if we try to output infinity or NaN.
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(v.nan1, v.nan1),
                          "v.nan1");
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(v.nan1, v.nan2), "v.nan2");
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(1.0, v.nan1), "v.nan1");
  EXPECT_FATAL_FAILURE(ASSERT_DOUBLE_EQ(v.nan1, v.infinity),
                       "v.infinity");
#endif  // !GTEST_OS_SYMBIAN
}
References ASSERT_DOUBLE_EQ, EXPECT_DOUBLE_EQ, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::infinity, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::nan1, and anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::nan2.
TEST_F() [12/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , Reflexive) private
Definition at line 3036 of file gtest_unittest.cc.
{
  EXPECT_DOUBLE_EQ(0.0, 0.0);
  EXPECT_DOUBLE_EQ(1.0, 1.0);
#if !GTEST_OS_SYMBIAN
  // Nokia's STLport crashes if we try to output infinity or NaN.
  ASSERT_DOUBLE_EQ(values_.infinity, values_.infinity);
#endif  // !GTEST_OS_SYMBIAN
}
References ASSERT_DOUBLE_EQ, and EXPECT_DOUBLE_EQ.
TEST_F() [13/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , Size) private
Definition at line 2945 of file gtest_unittest.cc.
{
  TestSize();
}
References anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestSize().
TEST_F() [14/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , SmallDiff) private
Definition at line 2983 of file gtest_unittest.cc.
{
  EXPECT_DOUBLE_EQ(1.0, values_.close_to_one);
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(1.0, values_.further_from_one),
                          "values_.further_from_one");
}
References EXPECT_DOUBLE_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [15/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (DoubleTest , Zeros) private
Definition at line 2950 of file gtest_unittest.cc.
{
  EXPECT_DOUBLE_EQ(0.0, -0.0);
  EXPECT_NONFATAL_FAILURE(EXPECT_DOUBLE_EQ(-0.0, 1.0),
                          "1.0");
  EXPECT_FATAL_FAILURE(ASSERT_DOUBLE_EQ(0.0, 1.0),
                       "1.0");
}
References ASSERT_DOUBLE_EQ, EXPECT_DOUBLE_EQ, EXPECT_FATAL_FAILURE, and EXPECT_NONFATAL_FAILURE.
TEST_F() [16/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest , AcceptsMacroThatExpandsToUnprotectedComma) private
Definition at line 1263 of file gtest_unittest.cc.
{
#ifndef __BORLANDC__
  // ICE's in C++Builder.
  EXPECT_FATAL_FAILURE({
    GTEST_USE_UNPROTECTED_COMMA_;
    AddFatalFailure();
  }, "");
#endif
  EXPECT_FATAL_FAILURE_ON_ALL_THREADS({
    GTEST_USE_UNPROTECTED_COMMA_;
    AddFatalFailure();
  }, "");
}
References AddFatalFailure(), EXPECT_FATAL_FAILURE, EXPECT_FATAL_FAILURE_ON_ALL_THREADS, and GTEST_USE_UNPROTECTED_COMMA_.
TEST_F() [17/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest , AcceptsStdStringObject) private
Definition at line 1205 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(AddFatalFailure(),
                       ::std::string("Expected fatal failure."));
}
References AddFatalFailure(), and EXPECT_FATAL_FAILURE.
TEST_F() [18/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest , CanBeUsedInNonVoidFunction) private
Definition at line 1231 of file gtest_unittest.cc.
{
  NonVoidFunction();
}
References NonVoidFunction().
TEST_F() [19/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest , CatchesFatalFailureOnAllThreads) private
Definition at line 1210 of file gtest_unittest.cc.
{
  // We have another test below to verify that the macro catches fatal
  // failures generated on another thread.
  EXPECT_FATAL_FAILURE_ON_ALL_THREADS(AddFatalFailure(),
                                      "Expected fatal failure.");
}
References AddFatalFailure(), and EXPECT_FATAL_FAILURE_ON_ALL_THREADS.
TEST_F() [20/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest , CatchesFatalFaliure) private
Definition at line 1195 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(AddFatalFailure(), "Expected fatal failure.");
}
References AddFatalFailure(), and EXPECT_FATAL_FAILURE.
TEST_F() [21/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectFatalFailureTest , DoesNotAbort) private
Definition at line 1250 of file gtest_unittest.cc.
{
  bool aborted = true;
  DoesNotAbortHelper(&aborted);
  EXPECT_FALSE(aborted);
}
References DoesNotAbortHelper(), and EXPECT_FALSE.
TEST_F() [22/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectNonfatalFailureTest , CatchesNonfatalFailure) private
Definition at line 1282 of file gtest_unittest.cc.
{
  EXPECT_NONFATAL_FAILURE(AddNonfatalFailure(),
                          "Expected non-fatal failure.");
}
References AddNonfatalFailure(), and EXPECT_NONFATAL_FAILURE.
TEST_F() [23/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ExpectNonfatalFailureTest , CatchesNonfatalFailureOnAllThreads) private
Definition at line 1299 of file gtest_unittest.cc.
{
  // We have another test below to verify that the macro catches
  // non-fatal failures generated on another thread.
  EXPECT_NONFATAL_FAILURE_ON_ALL_THREADS(AddNonfatalFailure(),
                                         "Expected non-fatal failure.");
}
References AddNonfatalFailure(), and EXPECT_NONFATAL_FAILURE_ON_ALL_THREADS.
TEST_F() [24/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , AlmostZeros) private
Definition at line 2790 of file gtest_unittest.cc.
{
  // In C++Builder, names within local classes (such as used by
  // EXPECT_FATAL_FAILURE) cannot be resolved against static members of the
  // scoping class.  Use a static local alias as a workaround.
  // We use the assignment syntax since some compilers, like Sun Studio,
  // don't allow initializing references using construction syntax
  // (parentheses).
  static const FloatTest::TestValues& v = this->values_;
  EXPECT_FLOAT_EQ(0.0, v.close_to_positive_zero);
  EXPECT_FLOAT_EQ(-0.0, v.close_to_negative_zero);
  EXPECT_FLOAT_EQ(v.close_to_positive_zero, v.close_to_negative_zero);
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_FLOAT_EQ(v.close_to_positive_zero,
                    v.further_from_negative_zero);
  }, "v.further_from_negative_zero");
}
References ASSERT_FLOAT_EQ, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::close_to_negative_zero, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::close_to_positive_zero, EXPECT_FATAL_FAILURE, EXPECT_FLOAT_EQ, and anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::further_from_negative_zero.
TEST_F() [25/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , ASSERT_NEAR) private
Definition at line 2895 of file gtest_unittest.cc.
{
  ASSERT_NEAR(-1.0f, -1.1f, 0.2f);
  ASSERT_NEAR(2.0f, 3.0f, 1.0f);
  EXPECT_FATAL_FAILURE(ASSERT_NEAR(1.0f,1.5f, 0.25f),  // NOLINT
                       "The difference between 1.0f and 1.5f is 0.5, "
                       "which exceeds 0.25f");
  // To work around a bug in gcc 2.95.0, there is intentionally no
  // space after the first comma in the previous line.
}
References ASSERT_NEAR, and EXPECT_FATAL_FAILURE.
TEST_F() [26/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , Commutative) private
Definition at line 2874 of file gtest_unittest.cc.
{
  // We already tested EXPECT_FLOAT_EQ(1.0, values_.close_to_one).
  EXPECT_FLOAT_EQ(values_.close_to_one, 1.0);
  // We already tested EXPECT_FLOAT_EQ(1.0, values_.further_from_one).
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(values_.further_from_one, 1.0),
                          "1.0");
}
References EXPECT_FLOAT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [27/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , EXPECT_NEAR) private
Definition at line 2884 of file gtest_unittest.cc.
{
  EXPECT_NEAR(-1.0f, -1.1f, 0.2f);
  EXPECT_NEAR(2.0f, 3.0f, 1.0f);
  EXPECT_NONFATAL_FAILURE(EXPECT_NEAR(1.0f,1.5f, 0.25f),  // NOLINT
                          "The difference between 1.0f and 1.5f is 0.5, "
                          "which exceeds 0.25f");
  // To work around a bug in gcc 2.95.0, there is intentionally no
  // space after the first comma in the previous line.
}
References EXPECT_NEAR, and EXPECT_NONFATAL_FAILURE.
TEST_F() [28/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , FloatLEFails) private
Definition at line 2915 of file gtest_unittest.cc.
{
  // When val1 is greater than val2 by a large margin,
  EXPECT_NONFATAL_FAILURE(EXPECT_PRED_FORMAT2(FloatLE, 2.0f, 1.0f),
                          "(2.0f) <= (1.0f)");
  // or by a small yet non-negligible margin,
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT2(FloatLE, values_.further_from_one, 1.0f);
  }, "(values_.further_from_one) <= (1.0f)");
#if !GTEST_OS_SYMBIAN && !defined(__BORLANDC__)
  // Nokia's STLport crashes if we try to output infinity or NaN.
  // C++Builder gives bad results for ordered comparisons involving NaNs
  // due to compiler bugs.
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT2(FloatLE, values_.nan1, values_.infinity);
  }, "(values_.nan1) <= (values_.infinity)");
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    EXPECT_PRED_FORMAT2(FloatLE, -values_.infinity, values_.nan1);
  }, "(-values_.infinity) <= (values_.nan1)");
  EXPECT_FATAL_FAILURE({  // NOLINT
    ASSERT_PRED_FORMAT2(FloatLE, values_.nan1, values_.nan1);
  }, "(values_.nan1) <= (values_.nan1)");
#endif  // !GTEST_OS_SYMBIAN && !defined(__BORLANDC__)
}
References ASSERT_PRED_FORMAT2, EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and EXPECT_PRED_FORMAT2.
TEST_F() [29/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , FloatLESucceeds) private
Definition at line 2906 of file gtest_unittest.cc.
{
  EXPECT_PRED_FORMAT2(FloatLE, 1.0f, 2.0f);  // When val1 < val2,
  ASSERT_PRED_FORMAT2(FloatLE, 1.0f, 1.0f);  // val1 == val2,
  // or when val1 is greater than, but almost equals to, val2.
  EXPECT_PRED_FORMAT2(FloatLE, values_.close_to_positive_zero, 0.0f);
}
References ASSERT_PRED_FORMAT2, and EXPECT_PRED_FORMAT2.
TEST_F() [30/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , Infinity) private
Definition at line 2826 of file gtest_unittest.cc.
{
  EXPECT_FLOAT_EQ(values_.infinity, values_.close_to_infinity);
  EXPECT_FLOAT_EQ(-values_.infinity, -values_.close_to_infinity);
#if !GTEST_OS_SYMBIAN
  // Nokia's STLport crashes if we try to output infinity or NaN.
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(values_.infinity, -values_.infinity),
                          "-values_.infinity");
  // This is interesting as the representations of infinity and nan1
  // are only 1 DLP apart.
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(values_.infinity, values_.nan1),
                          "values_.nan1");
#endif  // !GTEST_OS_SYMBIAN
}
References EXPECT_FLOAT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [31/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , LargeDiff) private
Definition at line 2817 of file gtest_unittest.cc.
{
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(2.5, 3.0),
                          "3.0");
}
References EXPECT_FLOAT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [32/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , NaN) private
Definition at line 2842 of file gtest_unittest.cc.
                       {
#if !GTEST_OS_SYMBIAN
// Nokia's STLport crashes if we try to output infinity or NaN.
  // In C++Builder, names within local classes (such as used by
  // EXPECT_FATAL_FAILURE) cannot be resolved against static members of the
  // scoping class.  Use a static local alias as a workaround.
  // We use the assignment syntax since some compilers, like Sun Studio,
  // don't allow initializing references using construction syntax
  // (parentheses).
  static const FloatTest::TestValues& v = this->values_;
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(v.nan1, v.nan1),
                          "v.nan1");
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(v.nan1, v.nan2),
                          "v.nan2");
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(1.0, v.nan1),
                          "v.nan1");
  EXPECT_FATAL_FAILURE(ASSERT_FLOAT_EQ(v.nan1, v.infinity),
                       "v.infinity");
#endif  // !GTEST_OS_SYMBIAN
}
References ASSERT_FLOAT_EQ, EXPECT_FATAL_FAILURE, EXPECT_FLOAT_EQ, EXPECT_NONFATAL_FAILURE, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::infinity, anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::nan1, and anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestValues::nan2.
TEST_F() [33/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , Reflexive) private
Definition at line 2867 of file gtest_unittest.cc.
{
  EXPECT_FLOAT_EQ(0.0, 0.0);
  EXPECT_FLOAT_EQ(1.0, 1.0);
  ASSERT_FLOAT_EQ(values_.infinity, values_.infinity);
}
References ASSERT_FLOAT_EQ, and EXPECT_FLOAT_EQ.
TEST_F() [34/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , Size) private
Definition at line 2772 of file gtest_unittest.cc.
{
  TestSize();
}
References anonymous_namespace{gtest_unittest.cc}::FloatingPointTest< RawType >::TestSize().
TEST_F() [35/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , SmallDiff) private
Definition at line 2810 of file gtest_unittest.cc.
{
  EXPECT_FLOAT_EQ(1.0, values_.close_to_one);
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(1.0, values_.further_from_one),
                          "values_.further_from_one");
}
References EXPECT_FLOAT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [36/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FloatTest , Zeros) private
Definition at line 2777 of file gtest_unittest.cc.
{
  EXPECT_FLOAT_EQ(0.0, -0.0);
  EXPECT_NONFATAL_FAILURE(EXPECT_FLOAT_EQ(-0.0, 1.0),
                          "1.0");
  EXPECT_FATAL_FAILURE(ASSERT_FLOAT_EQ(0.0, 1.5),
                       "1.5");
}
References ASSERT_FLOAT_EQ, EXPECT_FATAL_FAILURE, EXPECT_FLOAT_EQ, and EXPECT_NONFATAL_FAILURE.
TEST_F() [37/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test , MillisecondsDoNotAffectResult) private
Definition at line 497 of file gtest_unittest.cc.
{
  EXPECT_EQ(
      "2011-10-31T18:52:42",
      FormatEpochTimeInMillisAsIso8601(1320087162 * kMillisPerSec + 234));
}
References EXPECT_EQ.
TEST_F() [38/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test , Prints24HourTime) private
Definition at line 508 of file gtest_unittest.cc.
{
  EXPECT_EQ("2011-09-28T17:08:22",
            FormatEpochTimeInMillisAsIso8601(1317229702 * kMillisPerSec));
}
References EXPECT_EQ.
TEST_F() [39/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test , PrintsEpochStart) private
Definition at line 513 of file gtest_unittest.cc.
{
  EXPECT_EQ("1970-01-01T00:00:00", FormatEpochTimeInMillisAsIso8601(0));
}
References EXPECT_EQ.
TEST_F() [40/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test , PrintsLeadingZeroes) private
Definition at line 503 of file gtest_unittest.cc.
{
  EXPECT_EQ("2011-09-03T05:07:02",
            FormatEpochTimeInMillisAsIso8601(1315026422 * kMillisPerSec));
}
References EXPECT_EQ.
TEST_F() [41/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FormatEpochTimeInMillisAsIso8601Test , PrintsTwoDigitSegments) private
Definition at line 492 of file gtest_unittest.cc.
{
  EXPECT_EQ("2011-10-31T18:52:42",
            FormatEpochTimeInMillisAsIso8601(1320087162 * kMillisPerSec));
}
References EXPECT_EQ.
TEST_F() [42/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (FRIEND_TEST_Test2 , TEST_F) private
Definition at line 5052 of file gtest_unittest.cc.
{
  ASSERT_EQ(1, foo.Bar());
}
References ASSERT_EQ.
TEST_F() [43/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (GTestFlagSaverTest , ModifyGTestFlags) private
Definition at line 1635 of file gtest_unittest.cc.
{
  VerifyAndModifyFlags();
}
References anonymous_namespace{gtest_unittest.cc}::GTestFlagSaverTest::VerifyAndModifyFlags().
TEST_F() [44/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (GTestFlagSaverTest , VerifyGTestFlags) private
Definition at line 1641 of file gtest_unittest.cc.
{
  VerifyAndModifyFlags();
}
References anonymous_namespace{gtest_unittest.cc}::GTestFlagSaverTest::VerifyAndModifyFlags().
TEST_F() [45/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest , AssertNoFatalFailureOnFatalFailure) private
Definition at line 3417 of file gtest_unittest.cc.
{
  TestPartResultArray gtest_failures;
  {
    ScopedFakeTestPartResultReporter gtest_reporter(&gtest_failures);
    DoAssertNoFatalFailureOnFails();
  }
  ASSERT_EQ(2, gtest_failures.size());
  EXPECT_EQ(TestPartResult::kFatalFailure,
            gtest_failures.GetTestPartResult(0).type());
  EXPECT_EQ(TestPartResult::kFatalFailure,
            gtest_failures.GetTestPartResult(1).type());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "some fatal failure",
                      gtest_failures.GetTestPartResult(0).message());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "it does",
                      gtest_failures.GetTestPartResult(1).message());
}
References ASSERT_EQ, anonymous_namespace{gtest_unittest.cc}::NoFatalFailureTest::DoAssertNoFatalFailureOnFails(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::TestPartResultArray::GetTestPartResult(), testing::IsSubstring(), testing::TestPartResult::kFatalFailure, testing::TestPartResult::message(), testing::TestPartResultArray::size(), and testing::TestPartResult::type().
TEST_F() [46/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest , ExpectNoFatalFailureOnFatalFailure) private
Definition at line 3434 of file gtest_unittest.cc.
{
  TestPartResultArray gtest_failures;
  {
    ScopedFakeTestPartResultReporter gtest_reporter(&gtest_failures);
    DoExpectNoFatalFailureOnFails();
  }
  ASSERT_EQ(3, gtest_failures.size());
  EXPECT_EQ(TestPartResult::kFatalFailure,
            gtest_failures.GetTestPartResult(0).type());
  EXPECT_EQ(TestPartResult::kNonFatalFailure,
            gtest_failures.GetTestPartResult(1).type());
  EXPECT_EQ(TestPartResult::kNonFatalFailure,
            gtest_failures.GetTestPartResult(2).type());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "some fatal failure",
                      gtest_failures.GetTestPartResult(0).message());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "it does",
                      gtest_failures.GetTestPartResult(1).message());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "other failure",
                      gtest_failures.GetTestPartResult(2).message());
}
References ASSERT_EQ, anonymous_namespace{gtest_unittest.cc}::NoFatalFailureTest::DoExpectNoFatalFailureOnFails(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::TestPartResultArray::GetTestPartResult(), testing::IsSubstring(), testing::TestPartResult::kFatalFailure, testing::TestPartResult::kNonFatalFailure, testing::TestPartResult::message(), testing::TestPartResultArray::size(), and testing::TestPartResult::type().
TEST_F() [47/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest , MessageIsStreamable) private
Definition at line 3455 of file gtest_unittest.cc.
{
  TestPartResultArray gtest_failures;
  {
    ScopedFakeTestPartResultReporter gtest_reporter(&gtest_failures);
    EXPECT_NO_FATAL_FAILURE(FAIL() << "foo") << "my message";
  }
  ASSERT_EQ(2, gtest_failures.size());
  EXPECT_EQ(TestPartResult::kNonFatalFailure,
            gtest_failures.GetTestPartResult(0).type());
  EXPECT_EQ(TestPartResult::kNonFatalFailure,
            gtest_failures.GetTestPartResult(1).type());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "foo",
                      gtest_failures.GetTestPartResult(0).message());
  EXPECT_PRED_FORMAT2(testing::IsSubstring, "my message",
                      gtest_failures.GetTestPartResult(1).message());
}
References ASSERT_EQ, EXPECT_EQ, EXPECT_NO_FATAL_FAILURE, EXPECT_PRED_FORMAT2, FAIL, testing::TestPartResultArray::GetTestPartResult(), testing::IsSubstring(), testing::TestPartResult::kNonFatalFailure, testing::TestPartResult::message(), testing::TestPartResultArray::size(), and testing::TestPartResult::type().
TEST_F() [48/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest , NoFailure) private
Definition at line 3403 of file gtest_unittest.cc.
{
  EXPECT_NO_FATAL_FAILURE(Succeeds());
  ASSERT_NO_FATAL_FAILURE(Succeeds());
}
References ASSERT_NO_FATAL_FAILURE, EXPECT_NO_FATAL_FAILURE, and anonymous_namespace{gtest_unittest.cc}::NoFatalFailureTest::Succeeds().
TEST_F() [49/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (NoFatalFailureTest , NonFatalIsNoFailure) private
Definition at line 3408 of file gtest_unittest.cc.
{
  EXPECT_NONFATAL_FAILURE(
      EXPECT_NO_FATAL_FAILURE(FailsNonFatal()),
      "some non-fatal failure");
  EXPECT_NONFATAL_FAILURE(
      ASSERT_NO_FATAL_FAILURE(FailsNonFatal()),
      "some non-fatal failure");
}
References ASSERT_NO_FATAL_FAILURE, EXPECT_NO_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, and anonymous_namespace{gtest_unittest.cc}::NoFatalFailureTest::FailsNonFatal().
TEST_F() [50/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ScopedFakeTestPartResultReporterTest , DeprecatedConstructor) private
Definition at line 1147 of file gtest_unittest.cc.
{
  TestPartResultArray results;
  {
    // Tests, that the deprecated constructor still works.
    ScopedFakeTestPartResultReporter reporter(&results);
    AddFailure(NONFATAL_FAILURE);
  }
  EXPECT_EQ(1, results.size());
}
References anonymous_namespace{gtest_unittest.cc}::ScopedFakeTestPartResultReporterTest::AddFailure(), EXPECT_EQ, and testing::TestPartResultArray::size().
TEST_F() [51/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ScopedFakeTestPartResultReporterTest , InterceptsTestFailures) private
Definition at line 1132 of file gtest_unittest.cc.
{
  TestPartResultArray results;
  {
    ScopedFakeTestPartResultReporter reporter(
        ScopedFakeTestPartResultReporter::INTERCEPT_ONLY_CURRENT_THREAD,
        &results);
    AddFailure(NONFATAL_FAILURE);
    AddFailure(FATAL_FAILURE);
  }
  EXPECT_EQ(2, results.size());
  EXPECT_TRUE(results.GetTestPartResult(0).nonfatally_failed());
  EXPECT_TRUE(results.GetTestPartResult(1).fatally_failed());
}
References anonymous_namespace{gtest_unittest.cc}::ScopedFakeTestPartResultReporterTest::AddFailure(), EXPECT_EQ, EXPECT_TRUE, testing::TestPartResult::fatally_failed(), testing::TestPartResultArray::GetTestPartResult(), testing::ScopedFakeTestPartResultReporter::INTERCEPT_ONLY_CURRENT_THREAD, testing::TestPartResult::nonfatally_failed(), and testing::TestPartResultArray::size().
TEST_F() [52/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardDeathTest , AbortsWhenShardingEnvVarsAreInvalid) private
Definition at line 1891 of file gtest_unittest.cc.
{
  SetEnv(index_var_, "4");
  SetEnv(total_var_, "4");
  EXPECT_DEATH_IF_SUPPORTED(ShouldShard(total_var_, index_var_, false), ".*");
  SetEnv(index_var_, "4");
  SetEnv(total_var_, "-2");
  EXPECT_DEATH_IF_SUPPORTED(ShouldShard(total_var_, index_var_, false), ".*");
  SetEnv(index_var_, "5");
  SetEnv(total_var_, "");
  EXPECT_DEATH_IF_SUPPORTED(ShouldShard(total_var_, index_var_, false), ".*");
  SetEnv(index_var_, "");
  SetEnv(total_var_, "5");
  EXPECT_DEATH_IF_SUPPORTED(ShouldShard(total_var_, index_var_, false), ".*");
}
References EXPECT_DEATH_IF_SUPPORTED, and SetEnv().
TEST_F() [53/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardTest , ReturnsFalseWhenNeitherEnvVarIsSet) private
Definition at line 1849 of file gtest_unittest.cc.
{
  SetEnv(index_var_, "");
  SetEnv(total_var_, "");
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, false));
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, true));
}
References EXPECT_FALSE, and SetEnv().
TEST_F() [54/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardTest , ReturnsFalseWhenTotalShardIsOne) private
Definition at line 1858 of file gtest_unittest.cc.
{
  SetEnv(index_var_, "0");
  SetEnv(total_var_, "1");
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, false));
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, true));
}
References EXPECT_FALSE, and SetEnv().
TEST_F() [55/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (ShouldShardTest , WorksWhenShardEnvVarsAreValid) private
Definition at line 1869 of file gtest_unittest.cc.
{
  SetEnv(index_var_, "4");
  SetEnv(total_var_, "22");
  EXPECT_TRUE(ShouldShard(total_var_, index_var_, false));
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, true));
  SetEnv(index_var_, "8");
  SetEnv(total_var_, "9");
  EXPECT_TRUE(ShouldShard(total_var_, index_var_, false));
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, true));
  SetEnv(index_var_, "0");
  SetEnv(total_var_, "9");
  EXPECT_TRUE(ShouldShard(total_var_, index_var_, false));
  EXPECT_FALSE(ShouldShard(total_var_, index_var_, true));
}
References EXPECT_FALSE, EXPECT_TRUE, and SetEnv().
TEST_F() [56/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest , ASSERT_STR) private
Definition at line 3278 of file gtest_unittest.cc.
{
  // successful EXPECT_STRNE
  EXPECT_STRNE(p1_++, p2_++);
  EXPECT_EQ(s1_ + 1, p1_);
  EXPECT_EQ(s2_ + 1, p2_);
  // failed EXPECT_STRCASEEQ
  EXPECT_NONFATAL_FAILURE(EXPECT_STRCASEEQ(p1_++, p2_++),
                          "Ignoring case");
  EXPECT_EQ(s1_ + 2, p1_);
  EXPECT_EQ(s2_ + 2, p2_);
}
References EXPECT_EQ, EXPECT_NONFATAL_FAILURE, EXPECT_STRCASEEQ, and EXPECT_STRNE.
TEST_F() [57/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest , FailedASSERT_NE) private
Definition at line 3293 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(SingleEvaluationTest::CompareAndIncrementInts(),
                       "(a_++) != (b_++)");
  EXPECT_EQ(1, a_);
  EXPECT_EQ(1, b_);
}
References anonymous_namespace{gtest_unittest.cc}::SingleEvaluationTest::CompareAndIncrementInts(), EXPECT_EQ, and EXPECT_FATAL_FAILURE.
TEST_F() [58/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest , FailedASSERT_STREQ) private
Definition at line 3270 of file gtest_unittest.cc.
{
  EXPECT_FATAL_FAILURE(SingleEvaluationTest::CompareAndIncrementCharPtrs(),
                       "p2_++");
  EXPECT_EQ(s1_ + 1, p1_);
  EXPECT_EQ(s2_ + 1, p2_);
}
References anonymous_namespace{gtest_unittest.cc}::SingleEvaluationTest::CompareAndIncrementCharPtrs(), EXPECT_EQ, and EXPECT_FATAL_FAILURE.
TEST_F() [59/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (SingleEvaluationTest , OtherCases) private
Definition at line 3301 of file gtest_unittest.cc.
{
  // successful EXPECT_TRUE
  EXPECT_TRUE(0 == a_++);  // NOLINT
  EXPECT_EQ(1, a_);
  // failed EXPECT_TRUE
  EXPECT_NONFATAL_FAILURE(EXPECT_TRUE(-1 == a_++), "-1 == a_++");
  EXPECT_EQ(2, a_);
  // successful EXPECT_GT
  EXPECT_GT(a_++, b_++);
  EXPECT_EQ(3, a_);
  EXPECT_EQ(1, b_);
  // failed EXPECT_LT
  EXPECT_NONFATAL_FAILURE(EXPECT_LT(a_++, b_++), "(a_++) < (b_++)");
  EXPECT_EQ(4, a_);
  EXPECT_EQ(2, b_);
  // successful ASSERT_TRUE
  ASSERT_TRUE(0 < a_++);  // NOLINT
  EXPECT_EQ(5, a_);
  // successful ASSERT_GT
  ASSERT_GT(a_++, b_++);
  EXPECT_EQ(6, a_);
  EXPECT_EQ(3, b_);
}
References ASSERT_GT, ASSERT_TRUE, EXPECT_EQ, EXPECT_GT, EXPECT_LT, EXPECT_NONFATAL_FAILURE, and EXPECT_TRUE.
TEST_F() [60/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestLifeCycleTest , Test1) private
Definition at line 5082 of file gtest_unittest.cc.
{
  // There should be only one test object in this test case that's
  // currently alive.
  ASSERT_EQ(1, count());
}
References ASSERT_EQ, and anonymous_namespace{gtest_unittest.cc}::TestLifeCycleTest::count().
TEST_F() [61/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestLifeCycleTest , Test2) private
Definition at line 5089 of file gtest_unittest.cc.
{
  // After Test1 is done and Test2 is started, there should still be
  // only one live test object, as the object for Test1 should've been
  // deleted.
  ASSERT_EQ(1, count());
}
References ASSERT_EQ, and anonymous_namespace{gtest_unittest.cc}::TestLifeCycleTest::count().
TEST_F() [62/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultDeathTest , GetTestPartResult) private
Definition at line 1454 of file gtest_unittest.cc.
{
  CompareTestPartResult(*pr1, r2->GetTestPartResult(0));
  CompareTestPartResult(*pr2, r2->GetTestPartResult(1));
  EXPECT_DEATH_IF_SUPPORTED(r2->GetTestPartResult(2), "");
  EXPECT_DEATH_IF_SUPPORTED(r2->GetTestPartResult(-1), "");
}
References anonymous_namespace{gtest_unittest.cc}::TestResultTest::CompareTestPartResult(), and EXPECT_DEATH_IF_SUPPORTED.
TEST_F() [63/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultTest , Failed) private
Definition at line 1444 of file gtest_unittest.cc.
{
  ASSERT_FALSE(r0->Failed());
  ASSERT_FALSE(r1->Failed());
  ASSERT_TRUE(r2->Failed());
}
References ASSERT_FALSE, and ASSERT_TRUE.
TEST_F() [64/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultTest , Passed) private
Definition at line 1437 of file gtest_unittest.cc.
{
  ASSERT_TRUE(r0->Passed());
  ASSERT_TRUE(r1->Passed());
  ASSERT_FALSE(r2->Passed());
}
References ASSERT_FALSE, and ASSERT_TRUE.
TEST_F() [65/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (TestResultTest , total_part_count) private
Definition at line 1430 of file gtest_unittest.cc.
{
  ASSERT_EQ(0, r0->total_part_count());
  ASSERT_EQ(1, r1->total_part_count());
  ASSERT_EQ(2, r2->total_part_count());
}
References ASSERT_EQ.
TEST_F() [66/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest , AddFailureInsideTestsWhenUsingTestCaseReservedKeys) private
Definition at line 2075 of file gtest_unittest.cc.
{
  ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(
      "name");
  ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(
      "value_param");
  ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(
      "type_param");
  ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(
      "status");
  ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(
      "time");
  ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(
      "classname");
}
References ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest().
TEST_F() [67/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest , AddRecordWithReservedKeysGeneratesCorrectPropertyList) private
Definition at line 2091 of file gtest_unittest.cc.
{
  EXPECT_NONFATAL_FAILURE(
      Test::RecordProperty("name", "1"),
      "'classname', 'name', 'status', 'time', 'type_param', and 'value_param'"
      " are reserved");
}
References EXPECT_NONFATAL_FAILURE.
TEST_F() [68/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest , MultiplePropertiesFoundWhenAdded) private
Definition at line 2040 of file gtest_unittest.cc.
{
  UnitTestRecordProperty("key_1", "1");
  UnitTestRecordProperty("key_2", "2");
  ASSERT_EQ(2, unit_test_.ad_hoc_test_result().test_property_count());
  EXPECT_STREQ("key_1",
               unit_test_.ad_hoc_test_result().GetTestProperty(0).key());
  EXPECT_STREQ("1", unit_test_.ad_hoc_test_result().GetTestProperty(0).value());
  EXPECT_STREQ("key_2",
               unit_test_.ad_hoc_test_result().GetTestProperty(1).key());
  EXPECT_STREQ("2", unit_test_.ad_hoc_test_result().GetTestProperty(1).value());
}
References ASSERT_EQ, and EXPECT_STREQ.
TEST_F() [69/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest , OnePropertyFoundWhenAdded) private
Definition at line 2028 of file gtest_unittest.cc.
{
  UnitTestRecordProperty("key_1", "1");
  ASSERT_EQ(1, unit_test_.ad_hoc_test_result().test_property_count());
  EXPECT_STREQ("key_1",
               unit_test_.ad_hoc_test_result().GetTestProperty(0).key());
  EXPECT_STREQ("1",
               unit_test_.ad_hoc_test_result().GetTestProperty(0).value());
}
References ASSERT_EQ, and EXPECT_STREQ.
TEST_F() [70/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (UnitTestRecordPropertyTest , OverridesValuesForDuplicateKeys) private
Definition at line 2056 of file gtest_unittest.cc.
{
  UnitTestRecordProperty("key_1", "1");
  UnitTestRecordProperty("key_2", "2");
  UnitTestRecordProperty("key_1", "12");
  UnitTestRecordProperty("key_2", "22");
  ASSERT_EQ(2, unit_test_.ad_hoc_test_result().test_property_count());
  EXPECT_STREQ("key_1",
               unit_test_.ad_hoc_test_result().GetTestProperty(0).key());
  EXPECT_STREQ("12",
               unit_test_.ad_hoc_test_result().GetTestProperty(0).value());
  EXPECT_STREQ("key_2",
               unit_test_.ad_hoc_test_result().GetTestProperty(1).key());
  EXPECT_STREQ("22",
               unit_test_.ad_hoc_test_result().GetTestProperty(1).value());
}
References ASSERT_EQ, and EXPECT_STREQ.
TEST_F() [71/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , HandlesEmptyRange) private
Definition at line 914 of file gtest_unittest.cc.
{
  // Tests an empty range at the beginning...
  ShuffleRange(&random_, 0, 0, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
  // ...in the middle...
  ShuffleRange(&random_, kVectorSize/2, kVectorSize/2, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
  // ...at the end...
  ShuffleRange(&random_, kVectorSize - 1, kVectorSize - 1, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
  // ...and past the end.
  ShuffleRange(&random_, kVectorSize, kVectorSize, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
}
References ASSERT_PRED1, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt(), and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsUnshuffled().
TEST_F() [72/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , HandlesRangeOfSizeOne) private
Definition at line 936 of file gtest_unittest.cc.
{
  // Tests a size one range at the beginning...
  ShuffleRange(&random_, 0, 1, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
  // ...in the middle...
  ShuffleRange(&random_, kVectorSize/2, kVectorSize/2 + 1, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
  // ...and at the end.
  ShuffleRange(&random_, kVectorSize - 1, kVectorSize, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsUnshuffled, vector_);
}
References ASSERT_PRED1, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt(), and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsUnshuffled().
TEST_F() [73/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , ShufflesEndOfVector) private
Definition at line 977 of file gtest_unittest.cc.
{
  const int kRangeSize = kVectorSize / 2;
  ShuffleRange(&random_, kRangeSize, kVectorSize, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  EXPECT_PRED3(RangeIsUnshuffled, vector_, 0, kRangeSize);
  EXPECT_PRED3(RangeIsShuffled, vector_, kRangeSize, kVectorSize);
}
References ASSERT_PRED1, EXPECT_PRED3, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::RangeIsShuffled(), anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::RangeIsUnshuffled(), and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt().
TEST_F() [74/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , ShufflesEntireVector) private
Definition at line 956 of file gtest_unittest.cc.
{
  Shuffle(&random_, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  EXPECT_FALSE(VectorIsUnshuffled(vector_)) << vector_;
  // Tests the first and last elements in particular to ensure that
  // there are no off-by-one problems in our shuffle algorithm.
  EXPECT_NE(0, vector_[0]);
  EXPECT_NE(kVectorSize - 1, vector_[kVectorSize - 1]);
}
References ASSERT_PRED1, EXPECT_FALSE, EXPECT_NE, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt(), and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsUnshuffled().
TEST_F() [75/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , ShufflesMiddleOfVector) private
Definition at line 986 of file gtest_unittest.cc.
{
  int kRangeSize = kVectorSize/3;
  ShuffleRange(&random_, kRangeSize, 2*kRangeSize, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  EXPECT_PRED3(RangeIsUnshuffled, vector_, 0, kRangeSize);
  EXPECT_PRED3(RangeIsShuffled, vector_, kRangeSize, 2*kRangeSize);
  EXPECT_PRED3(RangeIsUnshuffled, vector_, 2*kRangeSize, kVectorSize);
}
References ASSERT_PRED1, EXPECT_PRED3, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::RangeIsShuffled(), anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::RangeIsUnshuffled(), and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt().
TEST_F() [76/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , ShufflesRepeatably) private
Definition at line 996 of file gtest_unittest.cc.
{
  TestingVector vector2;
  for (int i = 0; i < kVectorSize; i++) {
    vector2.push_back(i);
  }
  random_.Reseed(1234);
  Shuffle(&random_, &vector_);
  random_.Reseed(1234);
  Shuffle(&random_, &vector2);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector2);
  for (int i = 0; i < kVectorSize; i++) {
    EXPECT_EQ(vector_[i], vector2[i]) << " where i is " << i;
  }
}
References ASSERT_PRED1, EXPECT_EQ, and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt().
TEST_F() [77/77]
anonymous_namespace{gtest_unittest.cc}::TEST_F (VectorShuffleTest , ShufflesStartOfVector) private
Definition at line 967 of file gtest_unittest.cc.
{
  const int kRangeSize = kVectorSize/2;
  ShuffleRange(&random_, 0, kRangeSize, &vector_);
  ASSERT_PRED1(VectorIsNotCorrupt, vector_);
  EXPECT_PRED3(RangeIsShuffled, vector_, 0, kRangeSize);
  EXPECT_PRED3(RangeIsUnshuffled, vector_, kRangeSize, kVectorSize);
}
References ASSERT_PRED1, EXPECT_PRED3, anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::RangeIsShuffled(), anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::RangeIsUnshuffled(), and anonymous_namespace{gtest_unittest.cc}::VectorShuffleTest::VectorIsNotCorrupt().
TestAssertEqualsUncopyable()
void anonymous_namespace{gtest_unittest.cc}::TestAssertEqualsUncopyable () private
Definition at line 3881 of file gtest_unittest.cc.
{
  Uncopyable x(5);
  Uncopyable y(-1);
  ASSERT_EQ(x, y);
}
References ASSERT_EQ.
TestAssertNonPositive()
void anonymous_namespace{gtest_unittest.cc}::TestAssertNonPositive () private
Definition at line 3876 of file gtest_unittest.cc.
{
  Uncopyable y(-1);
  ASSERT_PRED1(IsPositiveUncopyable, y);
}
References ASSERT_PRED1, and IsPositiveUncopyable().
TestEq1()
void anonymous_namespace{gtest_unittest.cc}::TestEq1 (int x) private
Definition at line 3839 of file gtest_unittest.cc.
                    {
  ASSERT_EQ(1, x);
}
References ASSERT_EQ.
Variable Documentation
g_sum
int anonymous_namespace{gtest_unittest.cc}::g_sum = 0 static private
Definition at line 798 of file gtest_unittest.cc.
global_var
int anonymous_namespace{gtest_unittest.cc}::global_var = 0 static private
Definition at line 1260 of file gtest_unittest.cc.
kNull
const wchar_t* const anonymous_namespace{gtest_unittest.cc}::kNull = NULL static private
Definition at line 1038 of file gtest_unittest.cc.
record_property_env
Environment* anonymous_namespace{gtest_unittest.cc}::record_property_env static private
Initial value:
=
    AddGlobalTestEnvironment(new UnitTestRecordPropertyTestEnvironment)
Definition at line 2122 of file gtest_unittest.cc.