wiNpoS: testing::anonymous_namespace{gmock_stress_test.cc} Namespace Reference
testing::anonymous_namespace{gmock_stress_test.cc} Namespace Reference
Classes
class Base
class Derived1
class Derived2
struct Dummy
struct Helper1Param
class MockFoo
Functions
template<typename T >
void JoinAndDelete (ThreadWithParam< T > *t)
linked_ptr< Derived1 > pointer1 (new Derived1(1, 2))
linked_ptr< Derived2 > pointer2 (new Derived2(3, 4))
void TestConcurrentCopyAndReadLinkedPtr (Dummy)
const linked_ptr< Derived1 > p0 (new Derived1(1, 2))
void TestConcurrentWriteToEqualLinkedPtr (Dummy)
void TestConcurrentMockObjects (Dummy)
void Helper1 (Helper1Param param)
void TestConcurrentCallsOnSameObject (Dummy)
void Helper2 (MockFoo *foo)
void TestPartiallyOrderedExpectationsWithThreads (Dummy)
TEST (StressTest, CanUseGMockWithThreads)
Variables
const int kMaxTestThreads = 50
const int kRepeat = 50
Function Documentation
Helper1()
void testing::anonymous_namespace{gmock_stress_test.cc}::Helper1 (Helper1Param param)
Definition at line 180 of file gmock_stress_test.cc.
{
  for (int i = 0; i < kRepeat; i++) {
    const char ch = param.mock_foo->Baz("a", "b");
    if (ch == 'a') {
      // It was an expected call.
      (*param.count)++;
    } else {
      // It was an excessive call.
      EXPECT_EQ('\0', ch);
    }
    // An unexpected call.
    EXPECT_EQ('\0', param.mock_foo->Baz("x", "y")) << "Expected failure.";
    // An uninteresting call.
    EXPECT_EQ(1, param.mock_foo->Bar(5));
  }
}
References testing::anonymous_namespace{gmock_stress_test.cc}::Helper1Param::count, EXPECT_EQ, Helper1(), kRepeat, and testing::anonymous_namespace{gmock_stress_test.cc}::Helper1Param::mock_foo.
Helper2()
void testing::anonymous_namespace{gmock_stress_test.cc}::Helper2 (MockFoo * foo)
Definition at line 231 of file gmock_stress_test.cc.
{
  for (int i = 0; i < kRepeat; i++) {
    foo->Bar(2);
    foo->Bar(3);
  }
}
References Helper2(), and kRepeat.
JoinAndDelete()
template<typename T > void testing::anonymous_namespace{gmock_stress_test.cc}::JoinAndDelete (ThreadWithParam< T > * t)
Definition at line 60 of file gmock_stress_test.cc.
{
  t->Join();
  delete t;
}
References JoinAndDelete().
p0()
const linked_ptr< Derived1 > testing::anonymous_namespace{gmock_stress_test.cc}::p0 (new Derived11, 2)
References p0().
pointer1()
linked_ptr< Derived1 > testing::anonymous_namespace{gmock_stress_test.cc}::pointer1 (new Derived11, 2)
References pointer1().
pointer2()
linked_ptr< Derived2 > testing::anonymous_namespace{gmock_stress_test.cc}::pointer2 (new Derived23, 4)
References pointer2().
TEST()
testing::anonymous_namespace{gmock_stress_test.cc}::TEST (StressTest , CanUseGMockWithThreads)
Definition at line 278 of file gmock_stress_test.cc.
{
  void (*test_routines[])(Dummy dummy) = {
    &TestConcurrentCopyAndReadLinkedPtr,
    &TestConcurrentWriteToEqualLinkedPtr,
    &TestConcurrentMockObjects,
    &TestConcurrentCallsOnSameObject,
    &TestPartiallyOrderedExpectationsWithThreads,
  };
  const int kRoutines = sizeof(test_routines)/sizeof(test_routines[0]);
  const int kCopiesOfEachRoutine = kMaxTestThreads / kRoutines;
  const int kTestThreads = kCopiesOfEachRoutine * kRoutines;
  ThreadWithParam<Dummy>* threads[kTestThreads] = {};
  for (int i = 0; i < kTestThreads; i++) {
    // Creates a thread to run the test function.
    threads[i] =
        new ThreadWithParam<Dummy>(test_routines[i % kRoutines], Dummy(), NULL);
    GTEST_LOG_(INFO) << "Thread #" << i << " running . . .";
  }
  // At this point, we have many threads running.
  for (int i = 0; i < kTestThreads; i++) {
    JoinAndDelete(threads[i]);
  }
  // Ensures that the correct number of failures have been reported.
  const TestInfo* const info = UnitTest::GetInstance()->current_test_info();
  const TestResult& result = *info->result();
  const int kExpectedFailures = (3*kRepeat + 1)*kCopiesOfEachRoutine;
  GTEST_CHECK_(kExpectedFailures == result.total_part_count())
      << "Expected " << kExpectedFailures << " failures, but got "
      << result.total_part_count();
}
References testing::UnitTest::current_test_info(), testing::UnitTest::GetInstance(), GTEST_CHECK_, GTEST_LOG_, JoinAndDelete(), kMaxTestThreads, kRepeat, testing::TestInfo::result(), TestConcurrentCallsOnSameObject(), TestConcurrentCopyAndReadLinkedPtr(), TestConcurrentMockObjects(), TestConcurrentWriteToEqualLinkedPtr(), TestPartiallyOrderedExpectationsWithThreads(), and testing::TestResult::total_part_count().
TestConcurrentCallsOnSameObject()
void testing::anonymous_namespace{gmock_stress_test.cc}::TestConcurrentCallsOnSameObject (Dummy)
Definition at line 200 of file gmock_stress_test.cc.
{
  MockFoo foo;
  ON_CALL(foo, Bar(_))
      .WillByDefault(Return(1));
  EXPECT_CALL(foo, Baz(_, "b"))
      .Times(kRepeat)
      .WillRepeatedly(Return('a'));
  EXPECT_CALL(foo, Baz(_, "c"));  // Expected to be unsatisfied.
  // This chunk of code should generate kRepeat failures about
  // excessive calls, and 2*kRepeat failures about unexpected calls.
  int count1 = 0;
  const Helper1Param param = { &foo, &count1 };
  ThreadWithParam<Helper1Param>* const t =
      new ThreadWithParam<Helper1Param>(Helper1, param, NULL);
  int count2 = 0;
  const Helper1Param param2 = { &foo, &count2 };
  Helper1(param2);
  JoinAndDelete(t);
  EXPECT_EQ(kRepeat, count1 + count2);
  // foo's destructor should generate one failure about unsatisfied
  // expectation.
}
References testing::_, EXPECT_CALL, EXPECT_EQ, Helper1(), JoinAndDelete(), kRepeat, ON_CALL, testing::Return(), and TestConcurrentCallsOnSameObject().
TestConcurrentCopyAndReadLinkedPtr()
void testing::anonymous_namespace{gmock_stress_test.cc}::TestConcurrentCopyAndReadLinkedPtr (Dummy)
Definition at line 100 of file gmock_stress_test.cc.
{
  // Reads pointer1 and pointer2 while they are being copied from in
  // another thread.
  EXPECT_EQ(1, pointer1->x());
  EXPECT_EQ(2, pointer1->y());
  EXPECT_EQ(3, pointer2->x());
  EXPECT_EQ(4, pointer2->z());
  // Copies from pointer1.
  linked_ptr<Derived1> p1(pointer1);
  EXPECT_EQ(1, p1->x());
  EXPECT_EQ(2, p1->y());
  // Assigns from pointer2 where the LHS was empty.
  linked_ptr<Base> p2;
  p2 = pointer1;
  EXPECT_EQ(1, p2->x());
  // Assigns from pointer2 where the LHS was not empty.
  p2 = pointer2;
  EXPECT_EQ(3, p2->x());
}
References EXPECT_EQ, pointer1(), pointer2(), and TestConcurrentCopyAndReadLinkedPtr().
TestConcurrentMockObjects()
void testing::anonymous_namespace{gmock_stress_test.cc}::TestConcurrentMockObjects (Dummy)
Definition at line 149 of file gmock_stress_test.cc.
{
  // Creates a mock and does some typical operations on it.
  MockFoo foo;
  ON_CALL(foo, Bar(_))
      .WillByDefault(Return(1));
  ON_CALL(foo, Baz(_, _))
      .WillByDefault(Return('b'));
  ON_CALL(foo, Baz(_, "you"))
      .WillByDefault(Return('a'));
  EXPECT_CALL(foo, Bar(0))
      .Times(AtMost(3));
  EXPECT_CALL(foo, Baz(_, _));
  EXPECT_CALL(foo, Baz("hi", "you"))
      .WillOnce(Return('z'))
      .WillRepeatedly(DoDefault());
  EXPECT_EQ(1, foo.Bar(0));
  EXPECT_EQ(1, foo.Bar(0));
  EXPECT_EQ('z', foo.Baz("hi", "you"));
  EXPECT_EQ('a', foo.Baz("hi", "you"));
  EXPECT_EQ('b', foo.Baz("hi", "me"));
}
References testing::_, testing::AtMost(), testing::DoDefault(), EXPECT_CALL, EXPECT_EQ, ON_CALL, testing::Return(), and TestConcurrentMockObjects().
TestConcurrentWriteToEqualLinkedPtr()
void testing::anonymous_namespace{gmock_stress_test.cc}::TestConcurrentWriteToEqualLinkedPtr (Dummy)
Definition at line 127 of file gmock_stress_test.cc.
{
  // p1 and p2 point to the same, shared thing.  One thread resets p1.
  // Another thread assigns to p2.  This will cause the same
  // underlying "ring" to be updated concurrently.
  linked_ptr<Derived1> p1(p0);
  linked_ptr<Derived1> p2(p0);
  EXPECT_EQ(1, p1->x());
  EXPECT_EQ(2, p1->y());
  EXPECT_EQ(1, p2->x());
  EXPECT_EQ(2, p2->y());
  p1.reset();
  p2 = p0;
  EXPECT_EQ(1, p2->x());
  EXPECT_EQ(2, p2->y());
}
References EXPECT_EQ, p0(), testing::internal::linked_ptr< T >::reset(), and TestConcurrentWriteToEqualLinkedPtr().
TestPartiallyOrderedExpectationsWithThreads()
void testing::anonymous_namespace{gmock_stress_test.cc}::TestPartiallyOrderedExpectationsWithThreads (Dummy)
Definition at line 239 of file gmock_stress_test.cc.
{
  MockFoo foo;
  Sequence s1, s2;
  {
    InSequence dummy;
    EXPECT_CALL(foo, Bar(0));
    EXPECT_CALL(foo, Bar(1))
        .InSequence(s1, s2);
  }
  EXPECT_CALL(foo, Bar(2))
      .Times(2*kRepeat)
      .InSequence(s1)
      .RetiresOnSaturation();
  EXPECT_CALL(foo, Bar(3))
      .Times(2*kRepeat)
      .InSequence(s2);
  {
    InSequence dummy;
    EXPECT_CALL(foo, Bar(2))
        .InSequence(s1, s2);
    EXPECT_CALL(foo, Bar(4));
  }
  foo.Bar(0);
  foo.Bar(1);
  ThreadWithParam<MockFoo*>* const t =
      new ThreadWithParam<MockFoo*>(Helper2, &foo, NULL);
  Helper2(&foo);
  JoinAndDelete(t);
  foo.Bar(2);
  foo.Bar(4);
}
References EXPECT_CALL, Helper2(), testing::InSequence::InSequence(), JoinAndDelete(), kRepeat, and TestPartiallyOrderedExpectationsWithThreads().
Variable Documentation
kMaxTestThreads
const int testing::anonymous_namespace{gmock_stress_test.cc}::kMaxTestThreads = 50
Definition at line 47 of file gmock_stress_test.cc.
kRepeat
const int testing::anonymous_namespace{gmock_stress_test.cc}::kRepeat = 50
Definition at line 50 of file gmock_stress_test.cc.