wiNpoS: gmock_test_utils Namespace Reference
gmock_test_utils Namespace Reference
Functions
GetSourceDir ()
GetTestExecutablePath (executable_name)
GetExitStatus (exit_code)
Main ()
Variables
str __author__ = 'wan@google.com (Zhanyong Wan)'
str SCRIPT_DIR = os.path.dirname(__file__) or '.'
gtest_tests_util_dir = os.path.join(SCRIPT_DIR, '../../googletest/test')
GTEST_TESTS_UTIL_DIR = gtest_tests_util_dir
Subprocess = gtest_test_utils.Subprocess
TestCase = gtest_test_utils.TestCase
environ = gtest_test_utils.environ
SetEnvVar = gtest_test_utils.SetEnvVar
PREMATURE_EXIT_FILE_ENV_VAR = gtest_test_utils.PREMATURE_EXIT_FILE_ENV_VAR
Detailed Description
Unit test utilities for Google C++ Mocking Framework.
Function Documentation
GetExitStatus()
gmock_test_utils.GetExitStatus (exit_code)
Returns the argument to exit(), or -1 if exit() wasn't called.
Args:
  exit_code: the result value of os.system(command).
Definition at line 74 of file gmock_test_utils.py.
def GetExitStatus(exit_code):
  """Returns the argument to exit(), or -1 if exit() wasn't called.
  Args:
    exit_code: the result value of os.system(command).
  """
  if os.name == 'nt':
    # On Windows, os.WEXITSTATUS() doesn't work and os.system() returns
    # the argument to exit() directly.
    return exit_code
  else:
    # On Unix, os.WEXITSTATUS() must be used to extract the exit status
    # from the result of os.system().
    if os.WIFEXITED(exit_code):
      return os.WEXITSTATUS(exit_code)
    else:
      return -1
# Suppresses the "Invalid const name" lint complaint
# pylint: disable-msg=C6409
# Exposes utilities from gtest_test_utils.
GetSourceDir()
gmock_test_utils.GetSourceDir ()
Returns the absolute path of the directory where the .py files are.
Definition at line 52 of file gmock_test_utils.py.
def GetSourceDir():
  """Returns the absolute path of the directory where the .py files are."""
  return gtest_test_utils.GetSourceDir()
References gtest_test_utils.GetSourceDir().
GetTestExecutablePath()
gmock_test_utils.GetTestExecutablePath (executable_name)
Returns the absolute path of the test binary given its name.
The function will print a message and abort the program if the resulting file
doesn't exist.
Args:
  executable_name: name of the test binary that the test script runs.
Returns:
  The absolute path of the test binary.
Definition at line 58 of file gmock_test_utils.py.
def GetTestExecutablePath(executable_name):
  """Returns the absolute path of the test binary given its name.
  The function will print a message and abort the program if the resulting file
  doesn't exist.
  Args:
    executable_name: name of the test binary that the test script runs.
  Returns:
    The absolute path of the test binary.
  """
  return gtest_test_utils.GetTestExecutablePath(executable_name)
References gtest_test_utils.GetTestExecutablePath().
Main()
gmock_test_utils.Main ()
Runs the unit test.
Definition at line 107 of file gmock_test_utils.py.
def Main():
  """Runs the unit test."""
  gtest_test_utils.Main()
References gtest_test_utils.Main().
Variable Documentation
__author__
str gmock_test_utils.__author__ = 'wan@google.com (Zhanyong Wan)' private
Definition at line 32 of file gmock_test_utils.py.
environ
gmock_test_utils.environ = gtest_test_utils.environ
Definition at line 100 of file gmock_test_utils.py.
gtest_tests_util_dir
gmock_test_utils.gtest_tests_util_dir = os.path.join(SCRIPT_DIR, '../../googletest/test')
Definition at line 41 of file gmock_test_utils.py.
GTEST_TESTS_UTIL_DIR
gmock_test_utils.GTEST_TESTS_UTIL_DIR = gtest_tests_util_dir
Definition at line 43 of file gmock_test_utils.py.
PREMATURE_EXIT_FILE_ENV_VAR
gmock_test_utils.PREMATURE_EXIT_FILE_ENV_VAR = gtest_test_utils.PREMATURE_EXIT_FILE_ENV_VAR
Definition at line 102 of file gmock_test_utils.py.
SCRIPT_DIR
str gmock_test_utils.SCRIPT_DIR = os.path.dirname(__file__) or '.'
Definition at line 38 of file gmock_test_utils.py.
SetEnvVar
gmock_test_utils.SetEnvVar = gtest_test_utils.SetEnvVar
Definition at line 101 of file gmock_test_utils.py.
Subprocess
gmock_test_utils.Subprocess = gtest_test_utils.Subprocess
Definition at line 98 of file gmock_test_utils.py.
TestCase
gmock_test_utils.TestCase = gtest_test_utils.TestCase
Definition at line 99 of file gmock_test_utils.py.