wiNpoS: testing::internal::anonymous_namespace{gmock-internal-utils_test.cc} Namespace Reference
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc} Namespace Reference
Classes
class Base
class Derived
class LogIsVisibleTest
Functions
TEST (JoinAsTupleTest, JoinsEmptyTuple)
TEST (JoinAsTupleTest, JoinsOneTuple)
TEST (JoinAsTupleTest, JoinsTwoTuple)
TEST (JoinAsTupleTest, JoinsTenTuple)
TEST (ConvertIdentifierNameToWordsTest, WorksWhenNameContainsNoWord)
TEST (ConvertIdentifierNameToWordsTest, WorksWhenNameContainsDigits)
TEST (ConvertIdentifierNameToWordsTest, WorksWhenNameContainsCamelCaseWords)
TEST (ConvertIdentifierNameToWordsTest, WorksWhenNameContains_SeparatedWords)
TEST (ConvertIdentifierNameToWordsTest, WorksWhenNameIsMixture)
TEST (PointeeOfTest, WorksForSmartPointers)
TEST (PointeeOfTest, WorksForRawPointers)
TEST (GetRawPointerTest, WorksForSmartPointers)
TEST (GetRawPointerTest, WorksForRawPointers)
TEST (KindOfTest, Bool)
TEST (KindOfTest, Integer)
TEST (KindOfTest, FloatingPoint)
TEST (KindOfTest, Other)
TEST (LosslessArithmeticConvertibleTest, BoolToBool)
TEST (LosslessArithmeticConvertibleTest, BoolToInteger)
TEST (LosslessArithmeticConvertibleTest, BoolToFloatingPoint)
TEST (LosslessArithmeticConvertibleTest, IntegerToBool)
TEST (LosslessArithmeticConvertibleTest, IntegerToInteger)
TEST (LosslessArithmeticConvertibleTest, IntegerToFloatingPoint)
TEST (LosslessArithmeticConvertibleTest, FloatingPointToBool)
TEST (LosslessArithmeticConvertibleTest, FloatingPointToInteger)
TEST (LosslessArithmeticConvertibleTest, FloatingPointToFloatingPoint)
TEST (TupleMatchesTest, WorksForSize0)
TEST (TupleMatchesTest, WorksForSize1)
TEST (TupleMatchesTest, WorksForSize2)
TEST (TupleMatchesTest, WorksForSize5)
TEST (AssertTest, SucceedsOnTrue)
TEST (AssertTest, FailsFatallyOnFalse)
TEST (ExpectTest, SucceedsOnTrue)
TEST (ExpectTest, FailsNonfatallyOnFalse)
TEST_F (LogIsVisibleTest, AlwaysReturnsTrueIfVerbosityIsInfo)
TEST_F (LogIsVisibleTest, AlwaysReturnsFalseIfVerbosityIsError)
TEST_F (LogIsVisibleTest, WorksWhenVerbosityIsWarning)
TEST (TypeTraitsTest, true_type)
TEST (TypeTraitsTest, false_type)
TEST (TypeTraitsTest, is_reference)
TEST (TypeTraitsTest, is_pointer)
TEST (TypeTraitsTest, type_equals)
TEST (TypeTraitsTest, remove_reference)
TEST (StlContainerViewTest, WorksForStlContainer)
TEST (StlContainerViewTest, WorksForStaticNativeArray)
TEST (StlContainerViewTest, WorksForDynamicNativeArray)
Function Documentation
TEST() [1/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (AssertTest , FailsFatallyOnFalse)
Definition at line 360 of file gmock-internal-utils_test.cc.
{
  EXPECT_DEATH_IF_SUPPORTED({
    Assert(false, __FILE__, __LINE__, "This should fail.");
  }, "");
  EXPECT_DEATH_IF_SUPPORTED({
    Assert(false, __FILE__, __LINE__);
  }, "");
}
References testing::internal::Assert(), and EXPECT_DEATH_IF_SUPPORTED.
TEST() [2/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (AssertTest , SucceedsOnTrue)
Definition at line 354 of file gmock-internal-utils_test.cc.
{
  Assert(true, __FILE__, __LINE__, "This should succeed.");
  Assert(true, __FILE__, __LINE__);  // This should succeed too.
}
References testing::internal::Assert().
TEST() [3/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ConvertIdentifierNameToWordsTest , WorksWhenNameContains_SeparatedWords)
Definition at line 113 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ("foo bar", ConvertIdentifierNameToWords("foo_bar"));
  EXPECT_EQ("foo", ConvertIdentifierNameToWords("_foo_"));
  EXPECT_EQ("foo bar", ConvertIdentifierNameToWords("_foo_bar_"));
  EXPECT_EQ("foo and bar", ConvertIdentifierNameToWords("_foo__and_bar"));
}
References testing::internal::ConvertIdentifierNameToWords(), and EXPECT_EQ.
TEST() [4/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ConvertIdentifierNameToWordsTest , WorksWhenNameContainsCamelCaseWords)
Definition at line 105 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ("a big word", ConvertIdentifierNameToWords("ABigWord"));
  EXPECT_EQ("foo bar", ConvertIdentifierNameToWords("FooBar"));
  EXPECT_EQ("foo", ConvertIdentifierNameToWords("Foo_"));
  EXPECT_EQ("foo bar", ConvertIdentifierNameToWords("_Foo_Bar_"));
  EXPECT_EQ("foo and bar", ConvertIdentifierNameToWords("_Foo__And_Bar"));
}
References testing::internal::ConvertIdentifierNameToWords(), and EXPECT_EQ.
TEST() [5/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ConvertIdentifierNameToWordsTest , WorksWhenNameContainsDigits)
Definition at line 98 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ("1", ConvertIdentifierNameToWords("_1"));
  EXPECT_EQ("2", ConvertIdentifierNameToWords("2_"));
  EXPECT_EQ("34", ConvertIdentifierNameToWords("_34_"));
  EXPECT_EQ("34 56", ConvertIdentifierNameToWords("_34_56"));
}
References testing::internal::ConvertIdentifierNameToWords(), and EXPECT_EQ.
TEST() [6/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ConvertIdentifierNameToWordsTest , WorksWhenNameContainsNoWord)
Definition at line 92 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ("", ConvertIdentifierNameToWords(""));
  EXPECT_EQ("", ConvertIdentifierNameToWords("_"));
  EXPECT_EQ("", ConvertIdentifierNameToWords("__"));
}
References testing::internal::ConvertIdentifierNameToWords(), and EXPECT_EQ.
TEST() [7/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ConvertIdentifierNameToWordsTest , WorksWhenNameIsMixture)
Definition at line 120 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ("foo bar 123", ConvertIdentifierNameToWords("Foo_bar123"));
  EXPECT_EQ("chapter 11 section 1",
            ConvertIdentifierNameToWords("_Chapter11Section_1_"));
}
References testing::internal::ConvertIdentifierNameToWords(), and EXPECT_EQ.
TEST() [8/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ExpectTest , FailsNonfatallyOnFalse)
Definition at line 377 of file gmock-internal-utils_test.cc.
{
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    Expect(false, __FILE__, __LINE__, "This should fail.");
  }, "This should fail");
  EXPECT_NONFATAL_FAILURE({  // NOLINT
    Expect(false, __FILE__, __LINE__);
  }, "Expectation failed");
}
References testing::internal::Expect(), and EXPECT_NONFATAL_FAILURE.
TEST() [9/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (ExpectTest , SucceedsOnTrue)
Definition at line 371 of file gmock-internal-utils_test.cc.
{
  Expect(true, __FILE__, __LINE__, "This should succeed.");
  Expect(true, __FILE__, __LINE__);  // This should succeed too.
}
References testing::internal::Expect().
TEST() [10/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (GetRawPointerTest , WorksForRawPointers)
Definition at line 161 of file gmock-internal-utils_test.cc.
{
  int* p = NULL;
  // Don't use EXPECT_EQ as no NULL-testing magic on Symbian.
  EXPECT_TRUE(NULL == GetRawPointer(p));
  int n = 1;
  EXPECT_EQ(&n, GetRawPointer(&n));
}
References EXPECT_EQ, EXPECT_TRUE, and testing::internal::GetRawPointer().
TEST() [11/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (GetRawPointerTest , WorksForSmartPointers)
Definition at line 144 of file gmock-internal-utils_test.cc.
{
#if GTEST_HAS_STD_UNIQUE_PTR_
  const char* const raw_p1 = new const char('a');  // NOLINT
  const std::unique_ptr<const char> p1(raw_p1);
  EXPECT_EQ(raw_p1, GetRawPointer(p1));
#endif  // GTEST_HAS_STD_UNIQUE_PTR_
#if GTEST_HAS_STD_SHARED_PTR_
  double* const raw_p2 = new double(2.5);  // NOLINT
  const std::shared_ptr<double> p2(raw_p2);
  EXPECT_EQ(raw_p2, GetRawPointer(p2));
#endif  // GTEST_HAS_STD_SHARED_PTR_
  const char* const raw_p4 = new const char('a');  // NOLINT
  const internal::linked_ptr<const char> p4(raw_p4);
  EXPECT_EQ(raw_p4, GetRawPointer(p4));
}
References EXPECT_EQ, and testing::internal::GetRawPointer().
TEST() [12/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (JoinAsTupleTest , JoinsEmptyTuple)
Definition at line 72 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ("", JoinAsTuple(Strings()));
}
References EXPECT_EQ, and testing::internal::JoinAsTuple().
TEST() [13/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (JoinAsTupleTest , JoinsOneTuple)
Definition at line 76 of file gmock-internal-utils_test.cc.
{
  const char* fields[] = {"1"};
  EXPECT_EQ("1", JoinAsTuple(Strings(fields, fields + 1)));
}
References EXPECT_EQ, and testing::internal::JoinAsTuple().
TEST() [14/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (JoinAsTupleTest , JoinsTenTuple)
Definition at line 86 of file gmock-internal-utils_test.cc.
{
  const char* fields[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};
  EXPECT_EQ("(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)",
            JoinAsTuple(Strings(fields, fields + 10)));
}
References EXPECT_EQ, and testing::internal::JoinAsTuple().
TEST() [15/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (JoinAsTupleTest , JoinsTwoTuple)
Definition at line 81 of file gmock-internal-utils_test.cc.
{
  const char* fields[] = {"1", "a"};
  EXPECT_EQ("(1, a)", JoinAsTuple(Strings(fields, fields + 2)));
}
References EXPECT_EQ, and testing::internal::JoinAsTuple().
TEST() [16/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (KindOfTest , Bool)
Definition at line 174 of file gmock-internal-utils_test.cc.
                       {
  EXPECT_EQ(kBool, GMOCK_KIND_OF_(bool));  // NOLINT
}
References EXPECT_EQ, GMOCK_KIND_OF_, and testing::internal::kBool.
TEST() [17/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (KindOfTest , FloatingPoint)
Definition at line 198 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ(kFloatingPoint, GMOCK_KIND_OF_(float));  // NOLINT
  EXPECT_EQ(kFloatingPoint, GMOCK_KIND_OF_(double));  // NOLINT
  EXPECT_EQ(kFloatingPoint, GMOCK_KIND_OF_(long double));  // NOLINT
}
References EXPECT_EQ, GMOCK_KIND_OF_, and testing::internal::kFloatingPoint.
TEST() [18/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (KindOfTest , Integer)
Definition at line 178 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(char));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(signed char));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(unsigned char));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(short));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(unsigned short));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(int));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(unsigned int));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(long));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(unsigned long));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(wchar_t));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(Int64));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(UInt64));  // NOLINT
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(size_t));  // NOLINT
#if GTEST_OS_LINUX || GTEST_OS_MAC || GTEST_OS_CYGWIN
  // ssize_t is not defined on Windows and possibly some other OSes.
  EXPECT_EQ(kInteger, GMOCK_KIND_OF_(ssize_t));  // NOLINT
#endif
}
References EXPECT_EQ, GMOCK_KIND_OF_, and testing::internal::kInteger.
TEST() [19/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (KindOfTest , Other)
Definition at line 204 of file gmock-internal-utils_test.cc.
{
  EXPECT_EQ(kOther, GMOCK_KIND_OF_(void*));  // NOLINT
  EXPECT_EQ(kOther, GMOCK_KIND_OF_(char**));  // NOLINT
  EXPECT_EQ(kOther, GMOCK_KIND_OF_(Base));  // NOLINT
}
References EXPECT_EQ, GMOCK_KIND_OF_, and testing::internal::kOther.
TEST() [20/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , BoolToBool)
Definition at line 212 of file gmock-internal-utils_test.cc.
{
  EXPECT_TRUE((LosslessArithmeticConvertible<bool, bool>::value));
}
References EXPECT_TRUE.
TEST() [21/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , BoolToFloatingPoint)
Definition at line 223 of file gmock-internal-utils_test.cc.
{
  EXPECT_TRUE((LosslessArithmeticConvertible<bool, float>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<bool, double>::value));
}
References EXPECT_TRUE.
TEST() [22/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , BoolToInteger)
Definition at line 216 of file gmock-internal-utils_test.cc.
{
  EXPECT_TRUE((LosslessArithmeticConvertible<bool, char>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<bool, int>::value));
  EXPECT_TRUE(
      (LosslessArithmeticConvertible<bool, unsigned long>::value));  // NOLINT
}
References EXPECT_TRUE.
TEST() [23/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , FloatingPointToBool)
Definition at line 275 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE((LosslessArithmeticConvertible<float, bool>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<double, bool>::value));
}
References EXPECT_FALSE.
TEST() [24/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , FloatingPointToFloatingPoint)
Definition at line 286 of file gmock-internal-utils_test.cc.
{
  // Smaller size => larger size is fine.
  EXPECT_TRUE((LosslessArithmeticConvertible<float, double>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<float, long double>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<double, long double>::value));
  // Same size: fine.
  EXPECT_TRUE((LosslessArithmeticConvertible<float, float>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<double, double>::value));
  // Larger size => smaller size is not fine.
  EXPECT_FALSE((LosslessArithmeticConvertible<double, float>::value));
  GTEST_INTENTIONAL_CONST_COND_PUSH_()
  if (sizeof(double) == sizeof(long double)) {  // NOLINT
  GTEST_INTENTIONAL_CONST_COND_POP_()
    // In some implementations (e.g. MSVC), double and long double
    // have the same size.
    EXPECT_TRUE((LosslessArithmeticConvertible<long double, double>::value));
  } else {
    EXPECT_FALSE((LosslessArithmeticConvertible<long double, double>::value));
  }
}
References EXPECT_FALSE, EXPECT_TRUE, GTEST_INTENTIONAL_CONST_COND_POP_, and GTEST_INTENTIONAL_CONST_COND_PUSH_.
TEST() [25/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , FloatingPointToInteger)
Definition at line 280 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE((LosslessArithmeticConvertible<float, long>::value));  // NOLINT
  EXPECT_FALSE((LosslessArithmeticConvertible<double, Int64>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<long double, int>::value));
}
References EXPECT_FALSE.
TEST() [26/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , IntegerToBool)
Definition at line 228 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE((LosslessArithmeticConvertible<unsigned char, bool>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<int, bool>::value));
}
References EXPECT_FALSE.
TEST() [27/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , IntegerToFloatingPoint)
Definition at line 266 of file gmock-internal-utils_test.cc.
{
  // Integers cannot be losslessly converted to floating-points, as
  // the format of the latter is implementation-defined.
  EXPECT_FALSE((LosslessArithmeticConvertible<char, float>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<int, double>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<
                short, long double>::value));  // NOLINT
}
References EXPECT_FALSE.
TEST() [28/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (LosslessArithmeticConvertibleTest , IntegerToInteger)
Definition at line 233 of file gmock-internal-utils_test.cc.
{
  // Unsigned => larger signed is fine.
  EXPECT_TRUE((LosslessArithmeticConvertible<unsigned char, int>::value));
  // Unsigned => larger unsigned is fine.
  EXPECT_TRUE(
      (LosslessArithmeticConvertible<unsigned short, UInt64>::value)); // NOLINT
  // Signed => unsigned is not fine.
  EXPECT_FALSE((LosslessArithmeticConvertible<short, UInt64>::value)); // NOLINT
  EXPECT_FALSE((LosslessArithmeticConvertible<
      signed char, unsigned int>::value));  // NOLINT
  // Same size and same signedness: fine too.
  EXPECT_TRUE((LosslessArithmeticConvertible<
               unsigned char, unsigned char>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<int, int>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<wchar_t, wchar_t>::value));
  EXPECT_TRUE((LosslessArithmeticConvertible<
               unsigned long, unsigned long>::value));  // NOLINT
  // Same size, different signedness: not fine.
  EXPECT_FALSE((LosslessArithmeticConvertible<
                unsigned char, signed char>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<int, unsigned int>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<UInt64, Int64>::value));
  // Larger size => smaller size is not fine.
  EXPECT_FALSE((LosslessArithmeticConvertible<long, char>::value));  // NOLINT
  EXPECT_FALSE((LosslessArithmeticConvertible<int, signed char>::value));
  EXPECT_FALSE((LosslessArithmeticConvertible<Int64, unsigned int>::value));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [29/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (PointeeOfTest , WorksForRawPointers)
Definition at line 138 of file gmock-internal-utils_test.cc.
{
  CompileAssertTypesEqual<int, PointeeOf<int*>::type>();
  CompileAssertTypesEqual<const char, PointeeOf<const char*>::type>();
  CompileAssertTypesEqual<void, PointeeOf<void*>::type>();
}
TEST() [30/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (PointeeOfTest , WorksForSmartPointers)
Definition at line 126 of file gmock-internal-utils_test.cc.
{
  CompileAssertTypesEqual<const char,
      PointeeOf<internal::linked_ptr<const char> >::type>();
#if GTEST_HAS_STD_UNIQUE_PTR_
  CompileAssertTypesEqual<int, PointeeOf<std::unique_ptr<int> >::type>();
#endif  // GTEST_HAS_STD_UNIQUE_PTR_
#if GTEST_HAS_STD_SHARED_PTR_
  CompileAssertTypesEqual<std::string,
                          PointeeOf<std::shared_ptr<std::string> >::type>();
#endif  // GTEST_HAS_STD_SHARED_PTR_
}
TEST() [31/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (StlContainerViewTest , WorksForDynamicNativeArray)
Definition at line 688 of file gmock-internal-utils_test.cc.
{
  StaticAssertTypeEq<NativeArray<int>,
      StlContainerView<tuple<const int*, size_t> >::type>();
  StaticAssertTypeEq<NativeArray<double>,
      StlContainerView<tuple<linked_ptr<double>, int> >::type>();
  StaticAssertTypeEq<const NativeArray<int>,
      StlContainerView<tuple<const int*, int> >::const_reference>();
  int a1[3] = { 0, 1, 2 };
  const int* const p1 = a1;
  NativeArray<int> a2 = StlContainerView<tuple<const int*, int> >::
      ConstReference(make_tuple(p1, 3));
  EXPECT_EQ(3U, a2.size());
  EXPECT_EQ(a1, a2.begin());
  const NativeArray<int> a3 = StlContainerView<tuple<int*, size_t> >::
      Copy(make_tuple(static_cast<int*>(a1), 3));
  ASSERT_EQ(3U, a3.size());
  EXPECT_EQ(0, a3.begin()[0]);
  EXPECT_EQ(1, a3.begin()[1]);
  EXPECT_EQ(2, a3.begin()[2]);
  // Makes sure a1 and a3 aren't aliases.
  a1[0] = 3;
  EXPECT_EQ(0, a3.begin()[0]);
}
References ASSERT_EQ, testing::internal::NativeArray< Element >::begin(), EXPECT_EQ, and testing::internal::NativeArray< Element >::size().
TEST() [32/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (StlContainerViewTest , WorksForStaticNativeArray)
Definition at line 661 of file gmock-internal-utils_test.cc.
{
  StaticAssertTypeEq<NativeArray<int>,
      StlContainerView<int[3]>::type>();
  StaticAssertTypeEq<NativeArray<double>,
      StlContainerView<const double[4]>::type>();
  StaticAssertTypeEq<NativeArray<char[3]>,
      StlContainerView<const char[2][3]>::type>();
  StaticAssertTypeEq<const NativeArray<int>,
      StlContainerView<int[2]>::const_reference>();
  int a1[3] = { 0, 1, 2 };
  NativeArray<int> a2 = StlContainerView<int[3]>::ConstReference(a1);
  EXPECT_EQ(3U, a2.size());
  EXPECT_EQ(a1, a2.begin());
  const NativeArray<int> a3 = StlContainerView<int[3]>::Copy(a1);
  ASSERT_EQ(3U, a3.size());
  EXPECT_EQ(0, a3.begin()[0]);
  EXPECT_EQ(1, a3.begin()[1]);
  EXPECT_EQ(2, a3.begin()[2]);
  // Makes sure a1 and a3 aren't aliases.
  a1[0] = 3;
  EXPECT_EQ(0, a3.begin()[0]);
}
References ASSERT_EQ, testing::internal::NativeArray< Element >::begin(), testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::StlContainerView< RawContainer >::Copy(), EXPECT_EQ, and testing::internal::NativeArray< Element >::size().
TEST() [33/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (StlContainerViewTest , WorksForStlContainer)
Definition at line 645 of file gmock-internal-utils_test.cc.
{
  StaticAssertTypeEq<std::vector<int>,
      StlContainerView<std::vector<int> >::type>();
  StaticAssertTypeEq<const std::vector<double>&,
      StlContainerView<std::vector<double> >::const_reference>();
  typedef std::vector<char> Chars;
  Chars v1;
  const Chars& v2(StlContainerView<Chars>::ConstReference(v1));
  EXPECT_EQ(&v1, &v2);
  v1.push_back('a');
  Chars v3 = StlContainerView<Chars>::Copy(v1);
  EXPECT_THAT(v3, Eq(v3));
}
References testing::internal::StlContainerView< RawContainer >::Copy(), testing::Eq(), EXPECT_EQ, and EXPECT_THAT.
TEST() [34/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TupleMatchesTest , WorksForSize0)
Definition at line 311 of file gmock-internal-utils_test.cc.
{
  tuple<> matchers;
  tuple<> values;
  EXPECT_TRUE(TupleMatches(matchers, values));
}
References EXPECT_TRUE, and testing::internal::TupleMatches().
TEST() [35/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TupleMatchesTest , WorksForSize1)
Definition at line 318 of file gmock-internal-utils_test.cc.
{
  tuple<Matcher<int> > matchers(Eq(1));
  tuple<int> values1(1),
      values2(2);
  EXPECT_TRUE(TupleMatches(matchers, values1));
  EXPECT_FALSE(TupleMatches(matchers, values2));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::TupleMatches().
TEST() [36/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TupleMatchesTest , WorksForSize2)
Definition at line 327 of file gmock-internal-utils_test.cc.
{
  tuple<Matcher<int>, Matcher<char> > matchers(Eq(1), Eq('a'));
  tuple<int, char> values1(1, 'a'),
      values2(1, 'b'),
      values3(2, 'a'),
      values4(2, 'b');
  EXPECT_TRUE(TupleMatches(matchers, values1));
  EXPECT_FALSE(TupleMatches(matchers, values2));
  EXPECT_FALSE(TupleMatches(matchers, values3));
  EXPECT_FALSE(TupleMatches(matchers, values4));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::TupleMatches().
TEST() [37/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TupleMatchesTest , WorksForSize5)
Definition at line 340 of file gmock-internal-utils_test.cc.
{
  tuple<Matcher<int>, Matcher<char>, Matcher<bool>, Matcher<long>,  // NOLINT
        Matcher<std::string> >
      matchers(Eq(1), Eq('a'), Eq(true), Eq(2L), Eq("hi"));
  tuple<int, char, bool, long, std::string>  // NOLINT
      values1(1, 'a', true, 2L, "hi"), values2(1, 'a', true, 2L, "hello"),
      values3(2, 'a', true, 2L, "hi");
  EXPECT_TRUE(TupleMatches(matchers, values1));
  EXPECT_FALSE(TupleMatches(matchers, values2));
  EXPECT_FALSE(TupleMatches(matchers, values3));
}
References testing::Eq(), EXPECT_FALSE, EXPECT_TRUE, and testing::internal::TupleMatches().
TEST() [38/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TypeTraitsTest , false_type)
Definition at line 533 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE(false_type::value);
}
References EXPECT_FALSE, and testing::internal::bool_constant< bool_value >::value.
TEST() [39/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TypeTraitsTest , is_pointer)
Definition at line 543 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE(is_pointer<int>::value);
  EXPECT_FALSE(is_pointer<char&>::value);
  EXPECT_TRUE(is_pointer<const int*>::value);
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [40/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TypeTraitsTest , is_reference)
Definition at line 537 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE(is_reference<int>::value);
  EXPECT_FALSE(is_reference<char*>::value);
  EXPECT_TRUE(is_reference<const int&>::value);
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [41/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TypeTraitsTest , remove_reference)
Definition at line 556 of file gmock-internal-utils_test.cc.
{
  EXPECT_TRUE((type_equals<char, remove_reference<char&>::type>::value));
  EXPECT_TRUE((type_equals<const int,
               remove_reference<const int&>::type>::value));
  EXPECT_TRUE((type_equals<int, remove_reference<int>::type>::value));
  EXPECT_TRUE((type_equals<double*, remove_reference<double*>::type>::value));
}
References EXPECT_TRUE.
TEST() [42/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TypeTraitsTest , true_type)
Definition at line 529 of file gmock-internal-utils_test.cc.
{
  EXPECT_TRUE(true_type::value);
}
References EXPECT_TRUE, and testing::internal::bool_constant< bool_value >::value.
TEST() [43/43]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST (TypeTraitsTest , type_equals)
Definition at line 549 of file gmock-internal-utils_test.cc.
{
  EXPECT_FALSE((type_equals<int, const int>::value));
  EXPECT_FALSE((type_equals<int, int&>::value));
  EXPECT_FALSE((type_equals<int, double>::value));
  EXPECT_TRUE((type_equals<char, char>::value));
}
References EXPECT_FALSE, and EXPECT_TRUE.
TEST_F() [1/3]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST_F (LogIsVisibleTest , AlwaysReturnsFalseIfVerbosityIsError)
Definition at line 406 of file gmock-internal-utils_test.cc.
{
  GMOCK_FLAG(verbose) = kErrorVerbosity;
  EXPECT_FALSE(LogIsVisible(kInfo));
  EXPECT_FALSE(LogIsVisible(kWarning));
}
References EXPECT_FALSE, GMOCK_FLAG, testing::internal::kErrorVerbosity, testing::internal::kInfo, testing::internal::kWarning, and testing::internal::LogIsVisible().
TEST_F() [2/3]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST_F (LogIsVisibleTest , AlwaysReturnsTrueIfVerbosityIsInfo)
Definition at line 400 of file gmock-internal-utils_test.cc.
{
  GMOCK_FLAG(verbose) = kInfoVerbosity;
  EXPECT_TRUE(LogIsVisible(kInfo));
  EXPECT_TRUE(LogIsVisible(kWarning));
}
References EXPECT_TRUE, GMOCK_FLAG, testing::internal::kInfo, testing::internal::kInfoVerbosity, testing::internal::kWarning, and testing::internal::LogIsVisible().
TEST_F() [3/3]
testing::internal::anonymous_namespace{gmock-internal-utils_test.cc}::TEST_F (LogIsVisibleTest , WorksWhenVerbosityIsWarning)
Definition at line 412 of file gmock-internal-utils_test.cc.
{
  GMOCK_FLAG(verbose) = kWarningVerbosity;
  EXPECT_FALSE(LogIsVisible(kInfo));
  EXPECT_TRUE(LogIsVisible(kWarning));
}
References EXPECT_FALSE, EXPECT_TRUE, GMOCK_FLAG, testing::internal::kInfo, testing::internal::kWarning, testing::internal::kWarningVerbosity, and testing::internal::LogIsVisible().