wiNpoS: rapidjson/test/unittest/prettywritertest.cpp File Reference
prettywritertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/reader.h"
#include "rapidjson/prettywriter.h"
#include "rapidjson/stringbuffer.h"
#include "rapidjson/filewritestream.h"
#include <sstream>
Classes
class OStreamWrapper
Macros
#define T(meth, val, expected)
Functions
TEST (PrettyWriter, Basic)
TEST (PrettyWriter, FormatOptions)
TEST (PrettyWriter, SetIndent)
TEST (PrettyWriter, String)
TEST (PrettyWriter, OStreamWrapper)
TEST (PrettyWriter, FileWriteStream)
TEST (PrettyWriter, RawValue)
TEST (PrettyWriter, InvalidEventSequence)
TEST (PrettyWriter, NaN)
TEST (PrettyWriter, Inf)
TEST (PrettyWriter, Issue_889)
TEST (PrettyWriter, Issue_1336)
Variables
static const char kJson [] = "{\"hello\":\"world\",\"t\":true,\"f\":false,\"n\":null,\"i\":123,\"pi\":3.1416,\"a\":[1,2,3,-1],\"u64\":1234567890123456789,\"i64\":-1234567890123456789}"
static const char kPrettyJson []
static const char kPrettyJson_FormatOptions_SLA []
Macro Definition Documentation
T
#define T (meth, val, expected)
Value:
    {                                                   \
        StringBuffer buffer;                            \
        PrettyWriter<StringBuffer> writer(buffer);      \
        writer.meth(val);                               \
                                                        \
        EXPECT_STREQ(expected, buffer.GetString());     \
        EXPECT_TRUE(writer.IsComplete());               \
    }
Function Documentation
TEST() [1/12]
TEST (PrettyWriter , Basic)
Definition at line 60 of file prettywritertest.cpp.
{
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    Reader reader;
    StringStream s(kJson);
    reader.Parse(s, writer);
    EXPECT_STREQ(kPrettyJson, buffer.GetString());
}
References EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), kJson, kPrettyJson, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST() [2/12]
TEST (PrettyWriter , FileWriteStream)
Definition at line 167 of file prettywritertest.cpp.
{
    char filename[L_tmpnam];
    FILE* fp = TempFile(filename);
    ASSERT_TRUE(fp!=NULL);
    char buffer[16];
    FileWriteStream os(fp, buffer, sizeof(buffer));
    PrettyWriter<FileWriteStream> writer(os);
    Reader reader;
    StringStream s(kJson);
    reader.Parse(s, writer);
    fclose(fp);
    fp = fopen(filename, "rb");
    fseek(fp, 0, SEEK_END);
    size_t size = static_cast<size_t>(ftell(fp));
    fseek(fp, 0, SEEK_SET);
    char* json = static_cast<char*>(malloc(size + 1));
    size_t readLength = fread(json, 1, size, fp);
    json[readLength] = '\0';
    fclose(fp);
    remove(filename);
    EXPECT_STREQ(kPrettyJson, json);
    free(json);
}
References ASSERT_TRUE, EXPECT_STREQ, kJson, kPrettyJson, rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse(), and TempFile().
TEST() [3/12]
TEST (PrettyWriter , FormatOptions)
Definition at line 69 of file prettywritertest.cpp.
{
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    writer.SetFormatOptions(kFormatSingleLineArray);
    Reader reader;
    StringStream s(kJson);
    reader.Parse(s, writer);
    EXPECT_STREQ(kPrettyJson_FormatOptions_SLA, buffer.GetString());
}
References EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::kFormatSingleLineArray, kJson, kPrettyJson_FormatOptions_SLA, rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetFormatOptions().
TEST() [4/12]
TEST (PrettyWriter , Inf)
Definition at line 281 of file prettywritertest.cpp.
{
    double inf = std::numeric_limits<double>::infinity();
    EXPECT_TRUE(internal::Double(inf).IsInf());
    StringBuffer buffer;
    {
        PrettyWriter<StringBuffer> writer(buffer);
        EXPECT_FALSE(writer.Double(inf));
    }
    {
        PrettyWriter<StringBuffer> writer(buffer);
        EXPECT_FALSE(writer.Double(-inf));
    }
    {
        PrettyWriter<StringBuffer, UTF8<>, UTF8<>, CrtAllocator, kWriteNanAndInfFlag> writer(buffer);
        EXPECT_TRUE(writer.Double(inf));
    }
    {
        PrettyWriter<StringBuffer, UTF8<>, UTF8<>, CrtAllocator, kWriteNanAndInfFlag> writer(buffer);
        EXPECT_TRUE(writer.Double(-inf));
    }
    EXPECT_STREQ("Infinity-Infinity", buffer.GetString());
}
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::kWriteNanAndInfFlag.
TEST() [5/12]
TEST (PrettyWriter , InvalidEventSequence)
Definition at line 211 of file prettywritertest.cpp.
{
    // {]
    {
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);
        writer.StartObject();
        EXPECT_THROW(writer.EndArray(), AssertException);
        EXPECT_FALSE(writer.IsComplete());
    }
    // [}
    {
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);
        writer.StartArray();
        EXPECT_THROW(writer.EndObject(), AssertException);
        EXPECT_FALSE(writer.IsComplete());
    }
    // { 1:
    {
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);
        writer.StartObject();
        EXPECT_THROW(writer.Int(1), AssertException);
        EXPECT_FALSE(writer.IsComplete());
    }
    // { 'a' }
    {
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);
        writer.StartObject();
        writer.Key("a");
        EXPECT_THROW(writer.EndObject(), AssertException);
        EXPECT_FALSE(writer.IsComplete());
    }
    // { 'a':'b','c' }
    {
        StringBuffer buffer;
        PrettyWriter<StringBuffer> writer(buffer);
        writer.StartObject();
        writer.Key("a");
        writer.String("b");
        writer.Key("c");
        EXPECT_THROW(writer.EndObject(), AssertException);
        EXPECT_FALSE(writer.IsComplete());
    }
}
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), EXPECT_FALSE, EXPECT_THROW, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
TEST() [6/12]
TEST (PrettyWriter , Issue_1336)
Definition at line 342 of file prettywritertest.cpp.
{
#define T(meth, val, expected)                          \
    {                                                   \
        StringBuffer buffer;                            \
        PrettyWriter<StringBuffer> writer(buffer);      \
        writer.meth(val);                               \
                                                        \
        EXPECT_STREQ(expected, buffer.GetString());     \
        EXPECT_TRUE(writer.IsComplete());               \
    }
    T(Bool, false, "false");
    T(Bool, true, "true");
    T(Int, 0, "0");
    T(Uint, 0, "0");
    T(Int64, 0, "0");
    T(Uint64, 0, "0");
    T(Double, 0, "0.0");
    T(String, "Hello", "\"Hello\"");
#undef T
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    writer.Null();
    EXPECT_STREQ("null", buffer.GetString());
    EXPECT_TRUE(writer.IsComplete());
}
References EXPECT_STREQ, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), and T.
TEST() [7/12]
TEST (PrettyWriter , Issue_889)
Definition at line 305 of file prettywritertest.cpp.
{
    char buf[100] = "Hello";
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    writer.StartArray();
    writer.String(buf);
    writer.EndArray();
    EXPECT_STREQ("[\n    \"Hello\"\n]", buffer.GetString());
    EXPECT_TRUE(writer.IsComplete()); \
}
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), EXPECT_STREQ, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
TEST() [8/12]
TEST (PrettyWriter , NaN)
Definition at line 262 of file prettywritertest.cpp.
{
    double nan = std::numeric_limits<double>::quiet_NaN();
    EXPECT_TRUE(internal::Double(nan).IsNan());
    StringBuffer buffer;
    {
        PrettyWriter<StringBuffer> writer(buffer);
        EXPECT_FALSE(writer.Double(nan));
    }
    {
        PrettyWriter<StringBuffer, UTF8<>, UTF8<>, CrtAllocator, kWriteNanAndInfFlag> writer(buffer);
        EXPECT_TRUE(writer.Double(nan));
        EXPECT_STREQ("NaN", buffer.GetString());
    }
    GenericStringBuffer<UTF16<> > buffer2;
    PrettyWriter<GenericStringBuffer<UTF16<> > > writer2(buffer2);
    EXPECT_FALSE(writer2.Double(nan));
}
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::kWriteNanAndInfFlag.
TEST() [9/12]
TEST (PrettyWriter , OStreamWrapper)
Definition at line 151 of file prettywritertest.cpp.
{
    StringStream s(kJson);
    std::stringstream ss;
    OStreamWrapper os(ss);
    PrettyWriter<OStreamWrapper> writer(os);
    Reader reader;
    reader.Parse(s, writer);
    std::string actual = ss.str();
    EXPECT_STREQ(kPrettyJson, actual.c_str());
}
References EXPECT_STREQ, kJson, kPrettyJson, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST() [10/12]
TEST (PrettyWriter , RawValue)
Definition at line 192 of file prettywritertest.cpp.
{
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    writer.StartObject();
    writer.Key("a");
    writer.Int(1);
    writer.Key("raw");
    const char json[] = "[\"Hello\\nWorld\", 123.456]";
    writer.RawValue(json, strlen(json), kArrayType);
    writer.EndObject();
    EXPECT_TRUE(writer.IsComplete());
    EXPECT_STREQ(
        "{\n"
        "    \"a\": 1,\n"
        "    \"raw\": [\"Hello\\nWorld\", 123.456]\n" // no indentation within raw value
        "}",
        buffer.GetString());
}
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), EXPECT_STREQ, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), rapidjson::kArrayType, rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject().
TEST() [11/12]
TEST (PrettyWriter , SetIndent)
Definition at line 79 of file prettywritertest.cpp.
{
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    writer.SetIndent('\t', 1);
    Reader reader;
    StringStream s(kJson);
    reader.Parse(s, writer);
    EXPECT_STREQ(
        "{\n"
        "\t\"hello\": \"world\",\n"
        "\t\"t\": true,\n"
        "\t\"f\": false,\n"
        "\t\"n\": null,\n"
        "\t\"i\": 123,\n"
        "\t\"pi\": 3.1416,\n"
        "\t\"a\": [\n"
        "\t\t1,\n"
        "\t\t2,\n"
        "\t\t3,\n"
        "\t\t-1\n"
        "\t],\n"
        "\t\"u64\": 1234567890123456789,\n"
        "\t\"i64\": -1234567890123456789\n"
        "}",
        buffer.GetString());
}
References EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), kJson, rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetIndent().
TEST() [12/12]
TEST (PrettyWriter , String)
Definition at line 106 of file prettywritertest.cpp.
{
    StringBuffer buffer;
    PrettyWriter<StringBuffer> writer(buffer);
    EXPECT_TRUE(writer.StartArray());
    EXPECT_TRUE(writer.String("Hello\n"));
    EXPECT_TRUE(writer.EndArray());
    EXPECT_STREQ("[\n    \"Hello\\n\"\n]", buffer.GetString());
}
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), EXPECT_STREQ, EXPECT_TRUE, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Variable Documentation
kJson
const char kJson[] = "{\"hello\":\"world\",\"t\":true,\"f\":false,\"n\":null,\"i\":123,\"pi\":3.1416,\"a\":[1,2,3,-1],\"u64\":1234567890123456789,\"i64\":-1234567890123456789}" static
Definition at line 28 of file prettywritertest.cpp.
kPrettyJson
const char kPrettyJson[] static
Initial value:
=
"{\n"
"    \"hello\": \"world\",\n"
"    \"t\": true,\n"
"    \"f\": false,\n"
"    \"n\": null,\n"
"    \"i\": 123,\n"
"    \"pi\": 3.1416,\n"
"    \"a\": [\n"
"        1,\n"
"        2,\n"
"        3,\n"
"        -1\n"
"    ],\n"
"    \"u64\": 1234567890123456789,\n"
"    \"i64\": -1234567890123456789\n"
"}"
Definition at line 29 of file prettywritertest.cpp.
kPrettyJson_FormatOptions_SLA
const char kPrettyJson_FormatOptions_SLA[] static
Initial value:
=
"{\n"
"    \"hello\": \"world\",\n"
"    \"t\": true,\n"
"    \"f\": false,\n"
"    \"n\": null,\n"
"    \"i\": 123,\n"
"    \"pi\": 3.1416,\n"
"    \"a\": [1, 2, 3, -1],\n"
"    \"u64\": 1234567890123456789,\n"
"    \"i64\": -1234567890123456789\n"
"}"
Definition at line 47 of file prettywritertest.cpp.