wiNpoS: rapidjson/test/perftest/rapidjsontest.cpp File Reference
rapidjsontest.cpp File Reference
#include "perftest.h"
#include "rapidjson/rapidjson.h"
#include "rapidjson/document.h"
#include "rapidjson/prettywriter.h"
#include "rapidjson/stringbuffer.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/istreamwrapper.h"
#include "rapidjson/encodedstream.h"
#include "rapidjson/memorystream.h"
#include <fstream>
#include <vector>
Classes
class RapidJson
struct ValueCounter
struct NullStream
Macros
#define SIMD_SUFFIX(name) name
#define TEST_TYPED(index, Name)
#define TEST_TYPED(index, Name)
Functions
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_ValidateEncoding)
TEST_F (RapidJson, ReaderParse_DummyHandler)
TEST_F (RapidJson, ReaderParse_DummyHandler_Booleans)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Booleans)
TEST_F (RapidJson, ReaderParse_DummyHandler_Floats)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Floats)
TEST_F (RapidJson, ReaderParse_DummyHandler_Guids)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Guids)
TEST_F (RapidJson, ReaderParse_DummyHandler_Integers)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Integers)
TEST_F (RapidJson, ReaderParse_DummyHandler_Mixed)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Mixed)
TEST_F (RapidJson, ReaderParse_DummyHandler_Nulls)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Nulls)
TEST_F (RapidJson, ReaderParse_DummyHandler_Paragraphs)
TEST_F (RapidJson, ReaderParseInsitu_DummyHandler_Paragraphs)
TEST_F (RapidJson, ReaderParse_DummyHandler_FullPrecision)
TEST_F (RapidJson, ReaderParseIterative_DummyHandler)
TEST_F (RapidJson, ReaderParseIterativeInsitu_DummyHandler)
TEST_F (RapidJson, ReaderParseIterativePull_DummyHandler)
TEST_F (RapidJson, ReaderParseIterativePullInsitu_DummyHandler)
TEST_F (RapidJson, ReaderParse_DummyHandler_ValidateEncoding)
TEST_F (RapidJson, DocumentParseInsitu_MemoryPoolAllocator)
TEST_F (RapidJson, DocumentParseIterativeInsitu_MemoryPoolAllocator)
TEST_F (RapidJson, DocumentParse_MemoryPoolAllocator)
TEST_F (RapidJson, DocumentParseLength_MemoryPoolAllocator)
TEST_F (RapidJson, DocumentParseStdString_MemoryPoolAllocator)
TEST_F (RapidJson, DocumentParseIterative_MemoryPoolAllocator)
TEST_F (RapidJson, DocumentParse_CrtAllocator)
TEST_F (RapidJson, DocumentParseEncodedInputStream_MemoryStream)
TEST_F (RapidJson, DocumentParseAutoUTFInputStream_MemoryStream)
template<typename T >
size_t Traverse (const T &value)
TEST_F (RapidJson, DocumentTraverse)
TEST_F (RapidJson, DocumentAccept)
TEST_F (RapidJson, DocumentFind)
TEST_F (RapidJson, Writer_NullStream)
TEST_F (RapidJson, Writer_StringBuffer)
TEST_F (RapidJson, Writer_StringBuffer_Booleans)
TEST_F (RapidJson, Writer_StringBuffer_Floats)
TEST_F (RapidJson, Writer_StringBuffer_Guids)
TEST_F (RapidJson, Writer_StringBuffer_Integers)
TEST_F (RapidJson, Writer_StringBuffer_Mixed)
TEST_F (RapidJson, Writer_StringBuffer_Nulls)
TEST_F (RapidJson, Writer_StringBuffer_Paragraphs)
TEST_F (RapidJson, PrettyWriter_StringBuffer)
TEST_F (RapidJson, internal_Pow10)
TEST_F (RapidJson, SkipWhitespace_Basic)
TEST_F (RapidJson, SkipWhitespace)
TEST_F (RapidJson, SkipWhitespace_strspn)
TEST_F (RapidJson, UTF8_Validate)
TEST_F (RapidJson, FileReadStream)
TEST_F (RapidJson, ReaderParse_DummyHandler_FileReadStream)
TEST_F (RapidJson, IStreamWrapper)
TEST_F (RapidJson, IStreamWrapper_Unbuffered)
TEST_F (RapidJson, IStreamWrapper_Setbuffered)
TEST_F (RapidJson, ReaderParse_DummyHandler_IStreamWrapper)
TEST_F (RapidJson, ReaderParse_DummyHandler_IStreamWrapper_Unbuffered)
TEST_F (RapidJson, ReaderParse_DummyHandler_IStreamWrapper_Setbuffered)
TEST_F (RapidJson, StringBuffer)
Macro Definition Documentation
SIMD_SUFFIX
#define SIMD_SUFFIX (name) name
Definition at line 38 of file rapidjsontest.cpp.
TEST_TYPED [1/2]
#define TEST_TYPED (index, Name)
Value:
TEST_F(RapidJson, SIMD_SUFFIX(ReaderParse_DummyHandler_##Name)) {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        StringStream s(types_[index]);\
        BaseReaderHandler<> h;\
        Reader reader;\
        EXPECT_TRUE(reader.Parse(s, h));\
    }\
}\
TEST_F(RapidJson, SIMD_SUFFIX(ReaderParseInsitu_DummyHandler_##Name)) {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        memcpy(temp_, types_[index], typesLength_[index] + 1);\
        InsituStringStream s(temp_);\
        BaseReaderHandler<> h;\
        Reader reader;\
        EXPECT_TRUE(reader.Parse<kParseInsituFlag>(s, h));\
    }\
}
Definition at line 104 of file rapidjsontest.cpp.
                                                                {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        StringStream s(types_[index]);\
        BaseReaderHandler<> h;\
        Reader reader;\
        EXPECT_TRUE(reader.Parse(s, h));\
    }\
}\
TEST_F(RapidJson, SIMD_SUFFIX(ReaderParseInsitu_DummyHandler_##Name)) {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        memcpy(temp_, types_[index], typesLength_[index] + 1);\
        InsituStringStream s(temp_);\
        BaseReaderHandler<> h;\
        Reader reader;\
        EXPECT_TRUE(reader.Parse<kParseInsituFlag>(s, h));\
    }\
}
TEST_TYPED [2/2]
#define TEST_TYPED (index, Name)
Value:
TEST_F(RapidJson, SIMD_SUFFIX(Writer_StringBuffer_##Name)) {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        StringBuffer s(0, 1024 * 1024);\
        Writer<StringBuffer> writer(s);\
        typesDoc_[index].Accept(writer);\
        const char* str = s.GetString();\
        (void)str;\
    }\
}
Definition at line 104 of file rapidjsontest.cpp.
                                                                {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        StringStream s(types_[index]);\
        BaseReaderHandler<> h;\
        Reader reader;\
        EXPECT_TRUE(reader.Parse(s, h));\
    }\
}\
TEST_F(RapidJson, SIMD_SUFFIX(ReaderParseInsitu_DummyHandler_##Name)) {\
    for (size_t i = 0; i < kTrialCount * 10; i++) {\
        memcpy(temp_, types_[index], typesLength_[index] + 1);\
        InsituStringStream s(temp_);\
        BaseReaderHandler<> h;\
        Reader reader;\
        EXPECT_TRUE(reader.Parse<kParseInsituFlag>(s, h));\
    }\
}
Function Documentation
TEST_F() [1/59]
TEST_F (RapidJson , DocumentAccept)
Definition at line 331 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        ValueCounter counter;
        doc_.Accept(counter);
        EXPECT_EQ(4339u, counter.count_);
    }
}
References ValueCounter::count_, and EXPECT_EQ.
TEST_F() [2/59]
TEST_F (RapidJson , DocumentFind)
Definition at line 339 of file rapidjsontest.cpp.
{
    typedef Document::ValueType ValueType;
    typedef ValueType::ConstMemberIterator ConstMemberIterator;
    const Document &doc = typesDoc_[7]; // alotofkeys.json
    if (doc.IsObject()) {
        std::vector<const ValueType*> keys;
        for (ConstMemberIterator it = doc.MemberBegin(); it != doc.MemberEnd(); ++it) {
            keys.push_back(&it->name);
        }
        for (size_t i = 0; i < kTrialCount; i++) {
            for (size_t j = 0; j < keys.size(); j++) {
                EXPECT_TRUE(doc.FindMember(*keys[j]) != doc.MemberEnd());
            }
        }
    }
}
References EXPECT_TRUE.
TEST_F() [3/59]
TEST_F (RapidJson , DocumentParse_CrtAllocator)
Definition at line 252 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        GenericDocument<UTF8<>, CrtAllocator> doc;
        doc.Parse(temp_);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST_F() [4/59]
TEST_F (RapidJson , DocumentParse_MemoryPoolAllocator)
Definition at line 217 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        Document doc;
        doc.Parse(json_);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST_F() [5/59]
TEST_F (RapidJson , DocumentParseAutoUTFInputStream_MemoryStream)
Definition at line 271 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        MemoryStream ms(json_, length_);
        AutoUTFInputStream<unsigned, MemoryStream> is(ms);
        Document doc;
        doc.ParseStream<0, AutoUTF<unsigned> >(is);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
TEST_F() [6/59]
TEST_F (RapidJson , DocumentParseEncodedInputStream_MemoryStream)
Definition at line 261 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        MemoryStream ms(json_, length_);
        EncodedInputStream<UTF8<>, MemoryStream> is(ms);
        Document doc;
        doc.ParseStream<0, UTF8<> >(is);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
TEST_F() [7/59]
TEST_F (RapidJson , DocumentParseInsitu_MemoryPoolAllocator)
Definition at line 199 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        Document doc;
        doc.ParseInsitu(temp_);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu().
TEST_F() [8/59]
TEST_F (RapidJson , DocumentParseIterative_MemoryPoolAllocator)
Definition at line 244 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        Document doc;
        doc.Parse<kParseIterativeFlag>(json_);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, rapidjson::kParseIterativeFlag, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST_F() [9/59]
TEST_F (RapidJson , DocumentParseIterativeInsitu_MemoryPoolAllocator)
Definition at line 208 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        Document doc;
        doc.ParseInsitu<kParseIterativeFlag>(temp_);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, rapidjson::kParseIterativeFlag, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu().
TEST_F() [10/59]
TEST_F (RapidJson , DocumentParseLength_MemoryPoolAllocator)
Definition at line 225 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        Document doc;
        doc.Parse(json_, length_);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST_F() [11/59]
TEST_F (RapidJson , DocumentParseStdString_MemoryPoolAllocator)
Definition at line 234 of file rapidjsontest.cpp.
{
    const std::string s(json_, length_);
    for (size_t i = 0; i < kTrialCount; i++) {
        Document doc;
        doc.Parse(s);
        ASSERT_TRUE(doc.IsObject());
    }
}
References ASSERT_TRUE, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse().
TEST_F() [12/59]
TEST_F (RapidJson , DocumentTraverse)
Definition at line 304 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        size_t count = Traverse(doc_);
        EXPECT_EQ(4339u, count);
        //if (i == 0)
        //  std::cout << count << std::endl;
    }
}
References EXPECT_EQ, and Traverse().
TEST_F() [13/59]
TEST_F (RapidJson , FileReadStream)
Definition at line 464 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        FILE *fp = fopen(filename_, "rb");
        char buffer[65536];
        FileReadStream s(fp, buffer, sizeof(buffer));
        while (s.Take() != '\0')
            ;
        fclose(fp);
    }
}
References rapidjson::FileReadStream::Take().
TEST_F() [14/59]
TEST_F (RapidJson , internal_Pow10)
Definition at line 421 of file rapidjsontest.cpp.
{
    double sum = 0;
    for (size_t i = 0; i < kTrialCount * kTrialCount; i++)
        sum += internal::Pow10(int(i & 255));
    EXPECT_GT(sum, 0.0);
}
References EXPECT_GT, and rapidjson::internal::Pow10().
TEST_F() [15/59]
TEST_F (RapidJson , IStreamWrapper)
Definition at line 487 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        std::ifstream is(filename_, std::ios::in | std::ios::binary);
        char buffer[65536];
        IStreamWrapper isw(is, buffer, sizeof(buffer));
        while (isw.Take() != '\0')
            ;
        is.close();
    }
}
References IStreamWrapper::Take().
TEST_F() [16/59]
TEST_F (RapidJson , IStreamWrapper_Setbuffered)
Definition at line 508 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        std::ifstream is;
        char buffer[65536];
        is.rdbuf()->pubsetbuf(buffer, sizeof(buffer));
        is.open(filename_, std::ios::in | std::ios::binary);
        IStreamWrapper isw(is);
        while (isw.Take() != '\0')
            ;
        is.close();
    }
}
References IStreamWrapper::Take().
TEST_F() [17/59]
TEST_F (RapidJson , IStreamWrapper_Unbuffered)
Definition at line 498 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        std::ifstream is(filename_, std::ios::in | std::ios::binary);
        IStreamWrapper isw(is);
        while (isw.Take() != '\0')
            ;
        is.close();
    }
}
References IStreamWrapper::Take().
TEST_F() [18/59]
TEST_F (RapidJson , PrettyWriter_StringBuffer)
Definition at line 408 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringBuffer s(0, 2048 * 1024);
        PrettyWriter<StringBuffer> writer(s);
        writer.SetIndent(' ', 1);
        doc_.Accept(writer);
        const char* str = s.GetString();
        (void)str;
        //if (i == 0)
        //  std::cout << strlen(str) << std::endl;
    }
}
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetIndent().
TEST_F() [19/59]
TEST_F (RapidJson , ReaderParse_DummyHandler)
Definition at line 95 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringStream s(json_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse(s, h));
    }
}
References EXPECT_TRUE, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [20/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Booleans)
Definition at line 123 of file rapidjsontest.cpp.
TEST_F() [21/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_FileReadStream)
Definition at line 475 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        FILE *fp = fopen(filename_, "rb");
        char buffer[65536];
        FileReadStream s(fp, buffer, sizeof(buffer));
        BaseReaderHandler<> h;
        Reader reader;
        reader.Parse(s, h);
        fclose(fp);
    }
}
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [22/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Floats)
Definition at line 124 of file rapidjsontest.cpp.
TEST_F() [23/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_FullPrecision)
Definition at line 133 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringStream s(json_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse<kParseFullPrecisionFlag>(s, h));
    }
}
References EXPECT_TRUE, rapidjson::kParseFullPrecisionFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [24/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Guids)
Definition at line 125 of file rapidjsontest.cpp.
TEST_F() [25/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Integers)
Definition at line 126 of file rapidjsontest.cpp.
TEST_F() [26/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_IStreamWrapper)
Definition at line 521 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        std::ifstream is(filename_, std::ios::in | std::ios::binary);
        char buffer[65536];
        IStreamWrapper isw(is, buffer, sizeof(buffer));
        BaseReaderHandler<> h;
        Reader reader;
        reader.Parse(isw, h);
        is.close();
    }
}
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [27/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_IStreamWrapper_Setbuffered)
Definition at line 544 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        std::ifstream is;
        char buffer[65536];
        is.rdbuf()->pubsetbuf(buffer, sizeof(buffer));
        is.open(filename_, std::ios::in | std::ios::binary);
        IStreamWrapper isw(is);
        BaseReaderHandler<> h;
        Reader reader;
        reader.Parse(isw, h);
        is.close();
    }
}
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [28/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_IStreamWrapper_Unbuffered)
Definition at line 533 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        std::ifstream is(filename_, std::ios::in | std::ios::binary);
        IStreamWrapper isw(is);
        BaseReaderHandler<> h;
        Reader reader;
        reader.Parse(isw, h);
        is.close();
    }
}
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [29/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Mixed)
Definition at line 127 of file rapidjsontest.cpp.
TEST_F() [30/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Nulls)
Definition at line 128 of file rapidjsontest.cpp.
TEST_F() [31/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_Paragraphs)
Definition at line 129 of file rapidjsontest.cpp.
TEST_F() [32/59]
TEST_F (RapidJson , ReaderParse_DummyHandler_ValidateEncoding)
Definition at line 190 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringStream s(json_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse<kParseValidateEncodingFlag>(s, h));
    }
}
References EXPECT_TRUE, rapidjson::kParseValidateEncodingFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [33/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler)
Definition at line 75 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        InsituStringStream s(temp_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse<kParseInsituFlag>(s, h));
    }
}
References EXPECT_TRUE, rapidjson::kParseInsituFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [34/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Booleans)
Definition at line 123 of file rapidjsontest.cpp.
TEST_F() [35/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Floats)
Definition at line 124 of file rapidjsontest.cpp.
TEST_F() [36/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Guids)
Definition at line 125 of file rapidjsontest.cpp.
TEST_F() [37/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Integers)
Definition at line 126 of file rapidjsontest.cpp.
TEST_F() [38/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Mixed)
Definition at line 127 of file rapidjsontest.cpp.
TEST_F() [39/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Nulls)
Definition at line 128 of file rapidjsontest.cpp.
TEST_F() [40/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_Paragraphs)
Definition at line 129 of file rapidjsontest.cpp.
TEST_F() [41/59]
TEST_F (RapidJson , ReaderParseInsitu_DummyHandler_ValidateEncoding)
Definition at line 85 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        InsituStringStream s(temp_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse<kParseInsituFlag | kParseValidateEncodingFlag>(s, h));
    }
}
References EXPECT_TRUE, rapidjson::kParseInsituFlag, rapidjson::kParseValidateEncodingFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [42/59]
TEST_F (RapidJson , ReaderParseIterative_DummyHandler)
Definition at line 142 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringStream s(json_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse<kParseIterativeFlag>(s, h));
    }
}
References EXPECT_TRUE, rapidjson::kParseIterativeFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [43/59]
TEST_F (RapidJson , ReaderParseIterativeInsitu_DummyHandler)
Definition at line 151 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        InsituStringStream s(temp_);
        BaseReaderHandler<> h;
        Reader reader;
        EXPECT_TRUE(reader.Parse<kParseIterativeFlag|kParseInsituFlag>(s, h));
    }
}
References EXPECT_TRUE, rapidjson::kParseInsituFlag, rapidjson::kParseIterativeFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
TEST_F() [44/59]
TEST_F (RapidJson , ReaderParseIterativePull_DummyHandler)
Definition at line 161 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringStream s(json_);
        BaseReaderHandler<> h;
        Reader reader;
        reader.IterativeParseInit();
        while (!reader.IterativeParseComplete()) {
            if (!reader.IterativeParseNext<kParseDefaultFlags>(s, h))
                break;
        }
        EXPECT_FALSE(reader.HasParseError());
    }
}
References EXPECT_FALSE, rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), and rapidjson::kParseDefaultFlags.
TEST_F() [45/59]
TEST_F (RapidJson , ReaderParseIterativePullInsitu_DummyHandler)
Definition at line 175 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        memcpy(temp_, json_, length_ + 1);
        InsituStringStream s(temp_);
        BaseReaderHandler<> h;
        Reader reader;
        reader.IterativeParseInit();
        while (!reader.IterativeParseComplete()) {
            if (!reader.IterativeParseNext<kParseDefaultFlags|kParseInsituFlag>(s, h))
                break;
        }
        EXPECT_FALSE(reader.HasParseError());
    }
}
References EXPECT_FALSE, rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), rapidjson::kParseDefaultFlags, and rapidjson::kParseInsituFlag.
TEST_F() [46/59]
TEST_F (RapidJson , SkipWhitespace)
Definition at line 437 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        rapidjson::StringStream s(whitespace_);
        rapidjson::SkipWhitespace(s);
        ASSERT_EQ('[', s.Peek());
    }
}
References ASSERT_EQ, and rapidjson::SkipWhitespace().
TEST_F() [47/59]
TEST_F (RapidJson , SkipWhitespace_Basic)
Definition at line 428 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        rapidjson::StringStream s(whitespace_);
        while (s.Peek() == ' ' || s.Peek() == '\n' || s.Peek() == '\r' || s.Peek() == '\t')
            s.Take();
        ASSERT_EQ('[', s.Peek());
    }
}
References ASSERT_EQ.
TEST_F() [48/59]
TEST_F (RapidJson , SkipWhitespace_strspn)
Definition at line 445 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        const char* s = whitespace_ + std::strspn(whitespace_, " \t\r\n");
        ASSERT_EQ('[', *s);
    }
}
References ASSERT_EQ.
TEST_F() [49/59]
TEST_F (RapidJson , StringBuffer)
Definition at line 558 of file rapidjsontest.cpp.
{
    StringBuffer sb;
    for (int i = 0; i < 32 * 1024 * 1024; i++)
        sb.Put(i & 0x7f);
}
References rapidjson::GenericStringBuffer< Encoding, Allocator >::Put().
TEST_F() [50/59]
TEST_F (RapidJson , UTF8_Validate)
Definition at line 452 of file rapidjsontest.cpp.
{
    NullStream os;
    for (size_t i = 0; i < kTrialCount; i++) {
        StringStream is(json_);
        bool result = true;
        while (is.Peek() != '\0')
            result &= UTF8<>::Validate(is, os);
        EXPECT_TRUE(result);
    }
}
References EXPECT_TRUE, and rapidjson::UTF8< CharType >::Validate().
TEST_F() [51/59]
TEST_F (RapidJson , Writer_NullStream)
Definition at line 365 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        NullStream s;
        Writer<NullStream> writer(s);
        doc_.Accept(writer);
        //if (i == 0)
        //  std::cout << s.length_ << std::endl;
    }
}
TEST_F() [52/59]
TEST_F (RapidJson , Writer_StringBuffer)
Definition at line 375 of file rapidjsontest.cpp.
{
    for (size_t i = 0; i < kTrialCount; i++) {
        StringBuffer s(0, 1024 * 1024);
        Writer<StringBuffer> writer(s);
        doc_.Accept(writer);
        const char* str = s.GetString();
        (void)str;
        //if (i == 0)
        //  std::cout << strlen(str) << std::endl;
    }
}
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString().
TEST_F() [53/59]
TEST_F (RapidJson , Writer_StringBuffer_Booleans)
Definition at line 398 of file rapidjsontest.cpp.
TEST_F() [54/59]
TEST_F (RapidJson , Writer_StringBuffer_Floats)
Definition at line 399 of file rapidjsontest.cpp.
TEST_F() [55/59]
TEST_F (RapidJson , Writer_StringBuffer_Guids)
Definition at line 400 of file rapidjsontest.cpp.
TEST_F() [56/59]
TEST_F (RapidJson , Writer_StringBuffer_Integers)
Definition at line 401 of file rapidjsontest.cpp.
TEST_F() [57/59]
TEST_F (RapidJson , Writer_StringBuffer_Mixed)
Definition at line 402 of file rapidjsontest.cpp.
TEST_F() [58/59]
TEST_F (RapidJson , Writer_StringBuffer_Nulls)
Definition at line 403 of file rapidjsontest.cpp.
TEST_F() [59/59]
TEST_F (RapidJson , Writer_StringBuffer_Paragraphs)
Definition at line 404 of file rapidjsontest.cpp.
Traverse()
template<typename T > size_t Traverse (const T & value)
Definition at line 282 of file rapidjsontest.cpp.
{
    size_t count = 1;
    switch(value.GetType()) {
        case kObjectType:
            for (typename T::ConstMemberIterator itr = value.MemberBegin(); itr != value.MemberEnd(); ++itr) {
                count++;    // name
                count += Traverse(itr->value);
            }
            break;
        case kArrayType:
            for (typename T::ConstValueIterator itr = value.Begin(); itr != value.End(); ++itr)
                count += Traverse(*itr);
            break;
        default:
            // Do nothing.
            break;
    }
    return count;
}
References rapidjson::kArrayType, rapidjson::kObjectType, Traverse(), and rapidjson::value.