wiNpoS: rapidjson/test/unittest/regextest.cpp File Reference
regextest.cpp File Reference
#include "unittest.h"
#include "rapidjson/internal/regex.h"
Macros
#define EURO "\xE2\x82\xAC"
#define TEST_INVALID(s)
Functions
TEST (Regex, Single)
TEST (Regex, Concatenation)
TEST (Regex, Alternation1)
TEST (Regex, Alternation2)
TEST (Regex, Parenthesis1)
TEST (Regex, Parenthesis2)
TEST (Regex, Parenthesis3)
TEST (Regex, ZeroOrOne1)
TEST (Regex, ZeroOrOne2)
TEST (Regex, ZeroOrOne3)
TEST (Regex, ZeroOrOne4)
TEST (Regex, ZeroOrOne5)
TEST (Regex, ZeroOrMore1)
TEST (Regex, ZeroOrMore2)
TEST (Regex, ZeroOrMore3)
TEST (Regex, ZeroOrMore4)
TEST (Regex, OneOrMore1)
TEST (Regex, OneOrMore2)
TEST (Regex, OneOrMore3)
TEST (Regex, OneOrMore4)
TEST (Regex, QuantifierExact1)
TEST (Regex, QuantifierExact2)
TEST (Regex, QuantifierExact3)
TEST (Regex, QuantifierMin1)
TEST (Regex, QuantifierMin2)
TEST (Regex, QuantifierMin3)
TEST (Regex, QuantifierMinMax1)
TEST (Regex, QuantifierMinMax2)
TEST (Regex, QuantifierMinMax3)
TEST (Regex, QuantifierMinMax4)
TEST (Regex, QuantifierMinMax5)
TEST (Regex, Unicode)
TEST (Regex, AnyCharacter)
TEST (Regex, CharacterRange1)
TEST (Regex, CharacterRange2)
TEST (Regex, CharacterRange3)
TEST (Regex, CharacterRange4)
TEST (Regex, CharacterRange5)
TEST (Regex, CharacterRange6)
TEST (Regex, CharacterRange7)
TEST (Regex, CharacterRange8)
TEST (Regex, Search)
TEST (Regex, Search_BeginAnchor)
TEST (Regex, Search_EndAnchor)
TEST (Regex, Search_BothAnchor)
TEST (Regex, Escape)
TEST (Regex, Invalid)
TEST (Regex, Issue538)
TEST (Regex, Issue583)
Macro Definition Documentation
EURO
#define EURO "\xE2\x82\xAC"
Definition at line 404 of file regextest.cpp.
TEST_INVALID
#define TEST_INVALID (s)
Value:
    {\
        Regex re(s);\
        EXPECT_FALSE(re.IsValid());\
    }
Function Documentation
TEST() [1/49]
TEST (Regex , Alternation1)
Definition at line 41 of file regextest.cpp.
{
    Regex re("abab|abbb");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abab"));
    EXPECT_TRUE(rs.Match("abbb"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("ababa"));
    EXPECT_FALSE(rs.Match("abb"));
    EXPECT_FALSE(rs.Match("abbbb"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [2/49]
TEST (Regex , Alternation2)
Definition at line 54 of file regextest.cpp.
{
    Regex re("a|b|c");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("c"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("aa"));
    EXPECT_FALSE(rs.Match("ab"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [3/49]
TEST (Regex , AnyCharacter)
Definition at line 416 of file regextest.cpp.
{
    Regex re(".");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match(EURO));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EURO, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [4/49]
TEST (Regex , CharacterRange1)
Definition at line 427 of file regextest.cpp.
{
    Regex re("[abc]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("c"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("`"));
    EXPECT_FALSE(rs.Match("d"));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [5/49]
TEST (Regex , CharacterRange2)
Definition at line 440 of file regextest.cpp.
{
    Regex re("[^abc]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("`"));
    EXPECT_TRUE(rs.Match("d"));
    EXPECT_FALSE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("c"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [6/49]
TEST (Regex , CharacterRange3)
Definition at line 453 of file regextest.cpp.
{
    Regex re("[a-c]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("c"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("`"));
    EXPECT_FALSE(rs.Match("d"));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [7/49]
TEST (Regex , CharacterRange4)
Definition at line 466 of file regextest.cpp.
{
    Regex re("[^a-c]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("`"));
    EXPECT_TRUE(rs.Match("d"));
    EXPECT_FALSE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("c"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [8/49]
TEST (Regex , CharacterRange5)
Definition at line 479 of file regextest.cpp.
{
    Regex re("[-]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("-"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("a"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [9/49]
TEST (Regex , CharacterRange6)
Definition at line 488 of file regextest.cpp.
{
    Regex re("[a-]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("-"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("`"));
    EXPECT_FALSE(rs.Match("b"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [10/49]
TEST (Regex , CharacterRange7)
Definition at line 499 of file regextest.cpp.
{
    Regex re("[-a]");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("-"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("`"));
    EXPECT_FALSE(rs.Match("b"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [11/49]
TEST (Regex , CharacterRange8)
Definition at line 510 of file regextest.cpp.
{
    Regex re("[a-zA-Z0-9]*");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("Milo"));
    EXPECT_TRUE(rs.Match("MT19937"));
    EXPECT_TRUE(rs.Match("43"));
    EXPECT_FALSE(rs.Match("a_b"));
    EXPECT_FALSE(rs.Match("!"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [12/49]
TEST (Regex , Concatenation)
Definition at line 29 of file regextest.cpp.
{
    Regex re("abc");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abc"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("abcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [13/49]
TEST (Regex , Escape)
Definition at line 579 of file regextest.cpp.
                    {
    const char* s = "\\^\\$\\|\\(\\)\\?\\*\\+\\.\\[\\]\\{\\}\\\\\\f\\n\\r\\t\\v[\\b][\\[][\\]]";
    Regex re(s);
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("^$|()?*+.[]{}\\\x0C\n\r\t\x0B\b[]"));
    EXPECT_FALSE(rs.Match(s)); // Not escaping
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [14/49]
TEST (Regex , Invalid)
Definition at line 588 of file regextest.cpp.
                     {
#define TEST_INVALID(s) \
    {\
        Regex re(s);\
        EXPECT_FALSE(re.IsValid());\
    }
    TEST_INVALID("");
    TEST_INVALID("a|");
    TEST_INVALID("()");
    TEST_INVALID("(");
    TEST_INVALID(")");
    TEST_INVALID("(a))");
    TEST_INVALID("(a|)");
    TEST_INVALID("(a||b)");
    TEST_INVALID("(|b)");
    TEST_INVALID("?");
    TEST_INVALID("*");
    TEST_INVALID("+");
    TEST_INVALID("{");
    TEST_INVALID("{}");
    TEST_INVALID("a{a}");
    TEST_INVALID("a{0}");
    TEST_INVALID("a{-1}");
    TEST_INVALID("a{}");
    // TEST_INVALID("a{0,}");   // Support now
    TEST_INVALID("a{,0}");
    TEST_INVALID("a{1,0}");
    TEST_INVALID("a{-1,0}");
    TEST_INVALID("a{-1,1}");
    TEST_INVALID("a{4294967296}"); // overflow of unsigned
    TEST_INVALID("a{1a}");
    TEST_INVALID("[");
    TEST_INVALID("[]");
    TEST_INVALID("[^]");
    TEST_INVALID("[\\a]");
    TEST_INVALID("\\a");
#undef TEST_INVALID
}
References TEST_INVALID.
TEST() [15/49]
TEST (Regex , Issue538)
Definition at line 629 of file regextest.cpp.
                      {
    Regex re("^[0-9]+(\\\\.[0-9]+){0,2}");
    EXPECT_TRUE(re.IsValid());
}
References EXPECT_TRUE, and rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid().
TEST() [16/49]
TEST (Regex , Issue583)
Definition at line 634 of file regextest.cpp.
                      {
    Regex re("[0-9]{99999}");
    ASSERT_TRUE(re.IsValid());
}
References ASSERT_TRUE, and rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid().
TEST() [17/49]
TEST (Regex , OneOrMore1)
Definition at line 207 of file regextest.cpp.
{
    Regex re("a+");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("aa"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("ab"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [18/49]
TEST (Regex , OneOrMore2)
Definition at line 218 of file regextest.cpp.
{
    Regex re("a+b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_TRUE(rs.Match("aab"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("b"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [19/49]
TEST (Regex , OneOrMore3)
Definition at line 228 of file regextest.cpp.
{
    Regex re("a+b+");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_TRUE(rs.Match("aab"));
    EXPECT_TRUE(rs.Match("abb"));
    EXPECT_TRUE(rs.Match("aabb"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("ba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [20/49]
TEST (Regex , OneOrMore4)
Definition at line 241 of file regextest.cpp.
{
    Regex re("a(ab)+b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("aabb"));
    EXPECT_TRUE(rs.Match("aababb"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("ab"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [21/49]
TEST (Regex , Parenthesis1)
Definition at line 66 of file regextest.cpp.
{
    Regex re("(ab)c");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abc"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("abcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [22/49]
TEST (Regex , Parenthesis2)
Definition at line 78 of file regextest.cpp.
{
    Regex re("a(bc)");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abc"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("abcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [23/49]
TEST (Regex , Parenthesis3)
Definition at line 90 of file regextest.cpp.
{
    Regex re("(a|b)(c|d)");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ac"));
    EXPECT_TRUE(rs.Match("ad"));
    EXPECT_TRUE(rs.Match("bc"));
    EXPECT_TRUE(rs.Match("bd"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("cd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [24/49]
TEST (Regex , QuantifierExact1)
Definition at line 251 of file regextest.cpp.
{
    Regex re("ab{3}c");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abbbc"));
    EXPECT_FALSE(rs.Match("ac"));
    EXPECT_FALSE(rs.Match("abc"));
    EXPECT_FALSE(rs.Match("abbc"));
    EXPECT_FALSE(rs.Match("abbbbc"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [25/49]
TEST (Regex , QuantifierExact2)
Definition at line 262 of file regextest.cpp.
{
    Regex re("a(bc){3}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abcbcbcd"));
    EXPECT_FALSE(rs.Match("ad"));
    EXPECT_FALSE(rs.Match("abcd"));
    EXPECT_FALSE(rs.Match("abcbcd"));
    EXPECT_FALSE(rs.Match("abcbcbcbcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [26/49]
TEST (Regex , QuantifierExact3)
Definition at line 273 of file regextest.cpp.
{
    Regex re("a(b|c){3}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abbbd"));
    EXPECT_TRUE(rs.Match("acccd"));
    EXPECT_TRUE(rs.Match("abcbd"));
    EXPECT_FALSE(rs.Match("ad"));
    EXPECT_FALSE(rs.Match("abbd"));
    EXPECT_FALSE(rs.Match("accccd"));
    EXPECT_FALSE(rs.Match("abbbbd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [27/49]
TEST (Regex , QuantifierMin1)
Definition at line 286 of file regextest.cpp.
{
    Regex re("ab{3,}c");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abbbc"));
    EXPECT_TRUE(rs.Match("abbbbc"));
    EXPECT_TRUE(rs.Match("abbbbbc"));
    EXPECT_FALSE(rs.Match("ac"));
    EXPECT_FALSE(rs.Match("abc"));
    EXPECT_FALSE(rs.Match("abbc"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [28/49]
TEST (Regex , QuantifierMin2)
Definition at line 298 of file regextest.cpp.
{
    Regex re("a(bc){3,}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abcbcbcd"));
    EXPECT_TRUE(rs.Match("abcbcbcbcd"));
    EXPECT_FALSE(rs.Match("ad"));
    EXPECT_FALSE(rs.Match("abcd"));
    EXPECT_FALSE(rs.Match("abcbcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [29/49]
TEST (Regex , QuantifierMin3)
Definition at line 309 of file regextest.cpp.
{
    Regex re("a(b|c){3,}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abbbd"));
    EXPECT_TRUE(rs.Match("acccd"));
    EXPECT_TRUE(rs.Match("abcbd"));
    EXPECT_TRUE(rs.Match("accccd"));
    EXPECT_TRUE(rs.Match("abbbbd"));
    EXPECT_FALSE(rs.Match("ad"));
    EXPECT_FALSE(rs.Match("abbd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [30/49]
TEST (Regex , QuantifierMinMax1)
Definition at line 322 of file regextest.cpp.
{
    Regex re("ab{3,5}c");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abbbc"));
    EXPECT_TRUE(rs.Match("abbbbc"));
    EXPECT_TRUE(rs.Match("abbbbbc"));
    EXPECT_FALSE(rs.Match("ac"));
    EXPECT_FALSE(rs.Match("abc"));
    EXPECT_FALSE(rs.Match("abbc"));
    EXPECT_FALSE(rs.Match("abbbbbbc"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [31/49]
TEST (Regex , QuantifierMinMax2)
Definition at line 335 of file regextest.cpp.
{
    Regex re("a(bc){3,5}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abcbcbcd"));
    EXPECT_TRUE(rs.Match("abcbcbcbcd"));
    EXPECT_TRUE(rs.Match("abcbcbcbcbcd"));
    EXPECT_FALSE(rs.Match("ad"));
    EXPECT_FALSE(rs.Match("abcd"));
    EXPECT_FALSE(rs.Match("abcbcd"));
    EXPECT_FALSE(rs.Match("abcbcbcbcbcbcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [32/49]
TEST (Regex , QuantifierMinMax3)
Definition at line 348 of file regextest.cpp.
{
    Regex re("a(b|c){3,5}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("abbbd"));
    EXPECT_TRUE(rs.Match("acccd"));
    EXPECT_TRUE(rs.Match("abcbd"));
    EXPECT_TRUE(rs.Match("accccd"));
    EXPECT_TRUE(rs.Match("abbbbd"));
    EXPECT_TRUE(rs.Match("acccccd"));
    EXPECT_TRUE(rs.Match("abbbbbd"));
    EXPECT_FALSE(rs.Match("ad"));
    EXPECT_FALSE(rs.Match("abbd"));
    EXPECT_FALSE(rs.Match("accccccd"));
    EXPECT_FALSE(rs.Match("abbbbbbd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [33/49]
TEST (Regex , QuantifierMinMax4)
Definition at line 366 of file regextest.cpp.
{
    Regex re("a(b|c){0,3}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ad"));
    EXPECT_TRUE(rs.Match("abd"));
    EXPECT_TRUE(rs.Match("acd"));
    EXPECT_TRUE(rs.Match("abbd"));
    EXPECT_TRUE(rs.Match("accd"));
    EXPECT_TRUE(rs.Match("abcd"));
    EXPECT_TRUE(rs.Match("abbbd"));
    EXPECT_TRUE(rs.Match("acccd"));
    EXPECT_FALSE(rs.Match("abbbbd"));
    EXPECT_FALSE(rs.Match("add"));
    EXPECT_FALSE(rs.Match("accccd"));
    EXPECT_FALSE(rs.Match("abcbcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [34/49]
TEST (Regex , QuantifierMinMax5)
Definition at line 385 of file regextest.cpp.
{
    Regex re("a(b|c){0,}d");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ad"));
    EXPECT_TRUE(rs.Match("abd"));
    EXPECT_TRUE(rs.Match("acd"));
    EXPECT_TRUE(rs.Match("abbd"));
    EXPECT_TRUE(rs.Match("accd"));
    EXPECT_TRUE(rs.Match("abcd"));
    EXPECT_TRUE(rs.Match("abbbd"));
    EXPECT_TRUE(rs.Match("acccd"));
    EXPECT_TRUE(rs.Match("abbbbd"));
    EXPECT_TRUE(rs.Match("accccd"));
    EXPECT_TRUE(rs.Match("abcbcd"));
    EXPECT_FALSE(rs.Match("add"));
    EXPECT_FALSE(rs.Match("aad"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [35/49]
TEST (Regex , Search)
Definition at line 521 of file regextest.cpp.
                    {
    Regex re("abc");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Search("abc"));
    EXPECT_TRUE(rs.Search("_abc"));
    EXPECT_TRUE(rs.Search("abc_"));
    EXPECT_TRUE(rs.Search("_abc_"));
    EXPECT_TRUE(rs.Search("__abc__"));
    EXPECT_TRUE(rs.Search("abcabc"));
    EXPECT_FALSE(rs.Search("a"));
    EXPECT_FALSE(rs.Search("ab"));
    EXPECT_FALSE(rs.Search("bc"));
    EXPECT_FALSE(rs.Search("cba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search().
TEST() [36/49]
TEST (Regex , Search_BeginAnchor)
Definition at line 537 of file regextest.cpp.
{
    Regex re("^abc");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Search("abc"));
    EXPECT_TRUE(rs.Search("abc_"));
    EXPECT_TRUE(rs.Search("abcabc"));
    EXPECT_FALSE(rs.Search("_abc"));
    EXPECT_FALSE(rs.Search("_abc_"));
    EXPECT_FALSE(rs.Search("a"));
    EXPECT_FALSE(rs.Search("ab"));
    EXPECT_FALSE(rs.Search("bc"));
    EXPECT_FALSE(rs.Search("cba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search().
TEST() [37/49]
TEST (Regex , Search_BothAnchor)
Definition at line 567 of file regextest.cpp.
{
    Regex re("^abc$");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Search("abc"));
    EXPECT_FALSE(rs.Search(""));
    EXPECT_FALSE(rs.Search("a"));
    EXPECT_FALSE(rs.Search("b"));
    EXPECT_FALSE(rs.Search("ab"));
    EXPECT_FALSE(rs.Search("abcd"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search().
TEST() [38/49]
TEST (Regex , Search_EndAnchor)
Definition at line 552 of file regextest.cpp.
{
    Regex re("abc$");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Search("abc"));
    EXPECT_TRUE(rs.Search("_abc"));
    EXPECT_TRUE(rs.Search("abcabc"));
    EXPECT_FALSE(rs.Search("abc_"));
    EXPECT_FALSE(rs.Search("_abc_"));
    EXPECT_FALSE(rs.Search("a"));
    EXPECT_FALSE(rs.Search("ab"));
    EXPECT_FALSE(rs.Search("bc"));
    EXPECT_FALSE(rs.Search("cba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search().
TEST() [39/49]
TEST (Regex , Single)
Definition at line 20 of file regextest.cpp.
                    {
    Regex re("a");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("b"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [40/49]
TEST (Regex , Unicode)
Definition at line 406 of file regextest.cpp.
                     {
    Regex re("a" EURO "+b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a" EURO "b"));
    EXPECT_TRUE(rs.Match("a" EURO EURO "b"));
    EXPECT_FALSE(rs.Match("a?b"));
    EXPECT_FALSE(rs.Match("a" EURO "\xAC" "b")); // unaware of UTF-8 will match
}
References ASSERT_TRUE, EURO, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [41/49]
TEST (Regex , ZeroOrMore1)
Definition at line 160 of file regextest.cpp.
{
    Regex re("a*");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match(""));
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("aa"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("ab"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [42/49]
TEST (Regex , ZeroOrMore2)
Definition at line 171 of file regextest.cpp.
{
    Regex re("a*b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_TRUE(rs.Match("aab"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("bb"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [43/49]
TEST (Regex , ZeroOrMore3)
Definition at line 182 of file regextest.cpp.
{
    Regex re("a*b*");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match(""));
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("aa"));
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("bb"));
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_TRUE(rs.Match("aabb"));
    EXPECT_FALSE(rs.Match("ba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [44/49]
TEST (Regex , ZeroOrMore4)
Definition at line 196 of file regextest.cpp.
{
    Regex re("a(ab)*b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_TRUE(rs.Match("aabb"));
    EXPECT_TRUE(rs.Match("aababb"));
    EXPECT_FALSE(rs.Match(""));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [45/49]
TEST (Regex , ZeroOrOne1)
Definition at line 103 of file regextest.cpp.
{
    Regex re("a?");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match(""));
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("aa"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [46/49]
TEST (Regex , ZeroOrOne2)
Definition at line 112 of file regextest.cpp.
{
    Regex re("a?b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("a"));
    EXPECT_FALSE(rs.Match("aa"));
    EXPECT_FALSE(rs.Match("bb"));
    EXPECT_FALSE(rs.Match("ba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [47/49]
TEST (Regex , ZeroOrOne3)
Definition at line 124 of file regextest.cpp.
{
    Regex re("ab?");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("b"));
    EXPECT_FALSE(rs.Match("aa"));
    EXPECT_FALSE(rs.Match("bb"));
    EXPECT_FALSE(rs.Match("ba"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [48/49]
TEST (Regex , ZeroOrOne4)
Definition at line 136 of file regextest.cpp.
{
    Regex re("a?b?");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match(""));
    EXPECT_TRUE(rs.Match("a"));
    EXPECT_TRUE(rs.Match("b"));
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_FALSE(rs.Match("aa"));
    EXPECT_FALSE(rs.Match("bb"));
    EXPECT_FALSE(rs.Match("ba"));
    EXPECT_FALSE(rs.Match("abc"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
TEST() [49/49]
TEST (Regex , ZeroOrOne5)
Definition at line 150 of file regextest.cpp.
{
    Regex re("a(ab)?b");
    ASSERT_TRUE(re.IsValid());
    RegexSearch rs(re);
    EXPECT_TRUE(rs.Match("ab"));
    EXPECT_TRUE(rs.Match("aabb"));
    EXPECT_FALSE(rs.Match("aab"));
    EXPECT_FALSE(rs.Match("abb"));
}
References ASSERT_TRUE, EXPECT_FALSE, EXPECT_TRUE, rapidjson::internal::GenericRegex< Encoding, Allocator >::IsValid(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().