wiNpoS: rapidjson/test/unittest/stringbuffertest.cpp File Reference
stringbuffertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/stringbuffer.h"
#include "rapidjson/writer.h"
Functions
TEST (StringBuffer, InitialSize)
TEST (StringBuffer, Put)
TEST (StringBuffer, PutN_Issue672)
TEST (StringBuffer, Clear)
TEST (StringBuffer, Push)
TEST (StringBuffer, Pop)
TEST (StringBuffer, GetLength_Issue744)
Function Documentation
TEST() [1/7]
TEST (StringBuffer , Clear)
Definition at line 51 of file stringbuffertest.cpp.
{
    StringBuffer buffer;
    buffer.Put('A');
    buffer.Put('B');
    buffer.Put('C');
    buffer.Clear();
    EXPECT_EQ(0u, buffer.GetSize());
    EXPECT_EQ(0u, buffer.GetLength());
    EXPECT_STREQ("", buffer.GetString());
}
References rapidjson::GenericStringBuffer< Encoding, Allocator >::Clear(), EXPECT_EQ, EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Put().
TEST() [2/7]
TEST (StringBuffer , GetLength_Issue744)
Definition at line 89 of file stringbuffertest.cpp.
{
    GenericStringBuffer<UTF16<wchar_t> > buffer;
    buffer.Put('A');
    buffer.Put('B');
    buffer.Put('C');
    EXPECT_EQ(3u * sizeof(wchar_t), buffer.GetSize());
    EXPECT_EQ(3u, buffer.GetLength());
}
References EXPECT_EQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Put().
TEST() [3/7]
TEST (StringBuffer , InitialSize)
Definition at line 26 of file stringbuffertest.cpp.
{
    StringBuffer buffer;
    EXPECT_EQ(0u, buffer.GetSize());
    EXPECT_EQ(0u, buffer.GetLength());
    EXPECT_STREQ("", buffer.GetString());
}
References EXPECT_EQ, EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString().
TEST() [4/7]
TEST (StringBuffer , Pop)
Definition at line 75 of file stringbuffertest.cpp.
{
    StringBuffer buffer;
    buffer.Put('A');
    buffer.Put('B');
    buffer.Put('C');
    buffer.Put('D');
    buffer.Put('E');
    buffer.Pop(3);
    EXPECT_EQ(2u, buffer.GetSize());
    EXPECT_EQ(2u, buffer.GetLength());
    EXPECT_STREQ("AB", buffer.GetString());
}
References EXPECT_EQ, EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::GenericStringBuffer< Encoding, Allocator >::Pop(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Put().
TEST() [5/7]
TEST (StringBuffer , Push)
Definition at line 63 of file stringbuffertest.cpp.
{
    StringBuffer buffer;
    buffer.Push(5);
    EXPECT_EQ(5u, buffer.GetSize());
    EXPECT_EQ(5u, buffer.GetLength());
    // Causes sudden expansion to make the stack's capacity equal to size
    buffer.Push(65536u);
    EXPECT_EQ(5u + 65536u, buffer.GetSize());
}
References EXPECT_EQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Push().
TEST() [6/7]
TEST (StringBuffer , Put)
Definition at line 33 of file stringbuffertest.cpp.
{
    StringBuffer buffer;
    buffer.Put('A');
    EXPECT_EQ(1u, buffer.GetSize());
    EXPECT_EQ(1u, buffer.GetLength());
    EXPECT_STREQ("A", buffer.GetString());
}
References EXPECT_EQ, EXPECT_STREQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Put().
TEST() [7/7]
TEST (StringBuffer , PutN_Issue672)
Definition at line 42 of file stringbuffertest.cpp.
{
    GenericStringBuffer<UTF8<>, MemoryPoolAllocator<> > buffer;
    EXPECT_EQ(0u, buffer.GetSize());
    EXPECT_EQ(0u, buffer.GetLength());
    rapidjson::PutN(buffer, ' ', 1);
    EXPECT_EQ(1u, buffer.GetSize());
    EXPECT_EQ(1u, buffer.GetLength());
}
References EXPECT_EQ, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), and rapidjson::PutN().