wiNpoS: MyHandler Struct Reference
MyHandler Struct Reference
Public Member Functions
MyHandler ()
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const char *str, SizeType length, bool)
bool String (const char *str, SizeType length, bool)
bool StartObject ()
bool Key (const char *str, SizeType length, bool)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const char *str, SizeType length, bool copy)
bool String (const char *str, SizeType length, bool copy)
bool StartObject ()
bool Key (const char *str, SizeType length, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
Public Attributes
const char * type
std::string data
Private Member Functions
MyHandler (const MyHandler &noCopyConstruction)
MyHandler & operator= (const MyHandler &noAssignment)
Detailed Description
Definition at line 15 of file simplepullreader.cpp.
Constructor & Destructor Documentation
MyHandler() [1/2]
MyHandler::MyHandler () inline
Definition at line 19 of file simplepullreader.cpp.
: type(), data() {}
MyHandler() [2/2]
MyHandler::MyHandler (const MyHandler & noCopyConstruction) private
Member Function Documentation
Bool() [1/2]
bool MyHandler::Bool (bool b) inline
Definition at line 22 of file simplepullreader.cpp.
{ type = "Bool:"; data = b? "true": "false"; return true; }
References data, and type.
Bool() [2/2]
bool MyHandler::Bool (bool b) inline
Definition at line 9 of file simplereader.cpp.
{ cout << "Bool(" << boolalpha << b << ")" << endl; return true; }
Double() [1/2]
bool MyHandler::Double (double d) inline
Definition at line 27 of file simplepullreader.cpp.
{ type = "Double:"; data = stringify(d); return true; }
References data, stringify(), and type.
Double() [2/2]
bool MyHandler::Double (double d) inline
Definition at line 14 of file simplereader.cpp.
{ cout << "Double(" << d << ")" << endl; return true; }
EndArray() [1/2]
bool MyHandler::EndArray (SizeType elementCount) inline
Definition at line 34 of file simplepullreader.cpp.
{ type = "EndArray:"; data = stringify(elementCount); return true; }
References data, stringify(), and type.
EndArray() [2/2]
bool MyHandler::EndArray (SizeType elementCount) inline
Definition at line 30 of file simplereader.cpp.
{ cout << "EndArray(" << elementCount << ")" << endl; return true; }
EndObject() [1/2]
bool MyHandler::EndObject (SizeType memberCount) inline
Definition at line 32 of file simplepullreader.cpp.
{ type = "EndObject:"; data = stringify(memberCount); return true; }
References data, stringify(), and type.
EndObject() [2/2]
bool MyHandler::EndObject (SizeType memberCount) inline
Definition at line 28 of file simplereader.cpp.
{ cout << "EndObject(" << memberCount << ")" << endl; return true; }
Int() [1/2]
bool MyHandler::Int (int i) inline
Definition at line 23 of file simplepullreader.cpp.
{ type = "Int:"; data = stringify(i); return true; }
References data, stringify(), and type.
Int() [2/2]
bool MyHandler::Int (int i) inline
Definition at line 10 of file simplereader.cpp.
{ cout << "Int(" << i << ")" << endl; return true; }
Int64() [1/2]
bool MyHandler::Int64 (int64_t i) inline
Definition at line 25 of file simplepullreader.cpp.
{ type = "Int64:"; data = stringify(i); return true; }
References data, stringify(), and type.
Int64() [2/2]
bool MyHandler::Int64 (int64_t i) inline
Definition at line 12 of file simplereader.cpp.
{ cout << "Int64(" << i << ")" << endl; return true; }
Key() [1/2]
bool MyHandler::Key (const char * str, SizeType length, bool copy) inline
Definition at line 24 of file simplereader.cpp.
{
        cout << "Key(" << str << ", " << length << ", " << boolalpha << copy << ")" << endl;
        return true;
    }
Key() [2/2]
bool MyHandler::Key (const char * str, SizeType length, bool) inline
Definition at line 31 of file simplepullreader.cpp.
{ type = "Key:"; data = std::string(str, length); return true; }
References data, and type.
Null() [1/2]
bool MyHandler::Null () inline
Definition at line 21 of file simplepullreader.cpp.
{ type = "Null"; data.clear(); return true; }
References data, and type.
Null() [2/2]
bool MyHandler::Null () inline
Definition at line 8 of file simplereader.cpp.
{ cout << "Null()" << endl; return true; }
operator=()
MyHandler & MyHandler::operator= (const MyHandler & noAssignment) private
RawNumber() [1/2]
bool MyHandler::RawNumber (const char * str, SizeType length, bool copy) inline
Definition at line 15 of file simplereader.cpp.
{
        cout << "Number(" << str << ", " << length << ", " << boolalpha << copy << ")" << endl;
        return true;
    }
RawNumber() [2/2]
bool MyHandler::RawNumber (const char * str, SizeType length, bool) inline
Definition at line 28 of file simplepullreader.cpp.
{ type = "Number:"; data = std::string(str, length); return true; }
References data, and type.
StartArray() [1/2]
bool MyHandler::StartArray () inline
Definition at line 33 of file simplepullreader.cpp.
{ type = "StartArray"; data.clear(); return true; }
References data, and type.
StartArray() [2/2]
bool MyHandler::StartArray () inline
Definition at line 29 of file simplereader.cpp.
{ cout << "StartArray()" << endl; return true; }
StartObject() [1/2]
bool MyHandler::StartObject () inline
Definition at line 30 of file simplepullreader.cpp.
{ type = "StartObject"; data.clear(); return true; }
References data, and type.
StartObject() [2/2]
bool MyHandler::StartObject () inline
Definition at line 23 of file simplereader.cpp.
{ cout << "StartObject()" << endl; return true; }
String() [1/2]
bool MyHandler::String (const char * str, SizeType length, bool copy) inline
Definition at line 19 of file simplereader.cpp.
{
        cout << "String(" << str << ", " << length << ", " << boolalpha << copy << ")" << endl;
        return true;
    }
String() [2/2]
bool MyHandler::String (const char * str, SizeType length, bool) inline
Definition at line 29 of file simplepullreader.cpp.
{ type = "String:"; data = std::string(str, length); return true; }
References data, and type.
Uint() [1/2]
bool MyHandler::Uint (unsigned u) inline
Definition at line 24 of file simplepullreader.cpp.
{ type = "Uint:"; data = stringify(u); return true; }
References data, stringify(), and type.
Uint() [2/2]
bool MyHandler::Uint (unsigned u) inline
Definition at line 11 of file simplereader.cpp.
{ cout << "Uint(" << u << ")" << endl; return true; }
Uint64() [1/2]
bool MyHandler::Uint64 (uint64_t u) inline
Definition at line 26 of file simplepullreader.cpp.
{ type = "Uint64:"; data = stringify(u); return true; }
References data, stringify(), and type.
Uint64() [2/2]
bool MyHandler::Uint64 (uint64_t u) inline
Definition at line 13 of file simplereader.cpp.
{ cout << "Uint64(" << u << ")" << endl; return true; }
Member Data Documentation
data
std::string MyHandler::data
Definition at line 17 of file simplepullreader.cpp.
type
const char* MyHandler::type
Definition at line 16 of file simplepullreader.cpp.
The documentation for this struct was generated from the following files:
rapidjson/example/simplepullreader/simplepullreader.cpp
rapidjson/example/simplereader/simplereader.cpp