wiNpoS: rapidjson/example/traverseaspointer.cpp File Reference
traverseaspointer.cpp File Reference
#include "rapidjson/document.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/pointer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>
Functions
void traverse (const Value &v, const Pointer &p)
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 28 of file traverseaspointer.cpp.
                       {
    char readBuffer[65536];
    FileReadStream is(stdin, readBuffer, sizeof(readBuffer));
    Document d;
    d.ParseStream(is);
    Pointer root;
    traverse(d, root);
    return 0;
}
References rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), and traverse().
traverse()
void traverse (const Value & v, const Pointer & p)
Definition at line 9 of file traverseaspointer.cpp.
{
    StringBuffer sb;
    p.Stringify(sb);
    std::cout << sb.GetString() << std::endl;
    switch (v.GetType()) {
    case kArrayType:
        for (SizeType i = 0; i != v.Size(); ++i)
            traverse(v[i], p.Append(i));
        break;
    case kObjectType:
        for (Value::ConstMemberIterator m = v.MemberBegin(); m != v.MemberEnd(); ++m)
            traverse(m->value, p.Append(m->name.GetString(), m->name.GetStringLength()));
        break;
    default:
        break;
    }
}
References rapidjson::GenericPointer< ValueType, Allocator >::Append(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::kArrayType, rapidjson::kObjectType, and traverse().