wiNpoS: wiNpoS-Hook/dllmain.cpp File Reference
dllmain.cpp File Reference
#include "pch.h"
#include "DebugNew.h"
#include <vector>
#include <Utils.h>
#include "HooksMgr.h"
#include <Shlwapi.h>
#include "TaskToolbar.h"
Functions
LRESULT CALLBACK ShellHookProc (int nCode, WPARAM wParam, LPARAM lParam)
the exported hook for the shell procedure
BOOL APIENTRY DllMain (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
Variables
HINSTANCE hInstance = NULL
thread_local HooksMgr _hooksMgr
thread_local HHOOK hhShellHookProc = NULL
Function Documentation
DllMain()
BOOL APIENTRY DllMain (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
Definition at line 19 of file dllmain.cpp.
{
    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
    switch ((int)ul_reason_for_call)
    {
        case DLL_PROCESS_ATTACH:
        {
            hInstance = hModule;
            MainWindResVector mainWnds = GetMainWnds(0, GetCurrentProcessId());
            for (MainWndRes mainWnd : mainWnds)
            {
                PostMessage(mainWnd.hMainWnd, MT_HOOK_MSG_CREATE_TASK_TOOLBAR, (WPARAM)0, (LPARAM)0);
            }
            hhShellHookProc =
                SetWindowsHookEx(WH_SHELL, ShellHookProc, NULL, GetCurrentThreadId());
            WRITE_DEBUG_LOG(format("Attach {} to {}", Utils::DllName, Utils::ExeName));
            break;
        }
        case DLL_THREAD_ATTACH:
            hhShellHookProc =
                SetWindowsHookEx(WH_SHELL, ShellHookProc, NULL, GetCurrentThreadId());
            break;
        case DLL_THREAD_DETACH:
            if (hhShellHookProc && UnhookWindowsHookEx(hhShellHookProc))
                hhShellHookProc = NULL;
            AssertTrue(hhShellHookProc == NULL, "Hook handle should be NULL");
            break;
        case DLL_PROCESS_DETACH:
        {
            if (hhShellHookProc && UnhookWindowsHookEx(hhShellHookProc))
                hhShellHookProc = NULL;
            AssertTrue(hhShellHookProc == NULL, "Hook handle should be NULL");
            WRITE_DEBUG_LOG(format("Detach {} from {}", Utils::DllName, Utils::ExeName));
            break;
        }
        default:
            break;
    }
    return TRUE;
}
References AssertTrue, Utils::ExeName, hhShellHookProc, hInstance, MT_HOOK_MSG_CREATE_TASK_TOOLBAR, ShellHookProc(), and WRITE_DEBUG_LOG.
ShellHookProc()
LRESULT CALLBACK ShellHookProc (int nCode, WPARAM wParam, LPARAM lParam)
the exported hook for the shell procedure
Parameters
nCode
wParam
lParam
Returns
Definition at line 38 of file HooksImpl.cpp.
{
    if (_hooksCfg->isDisabled())
        return CallNextHookEx(NULL, nCode, wParam, lParam);
    return HooksImpl::shellHookProc(nCode, wParam, lParam);
}
References _hooksCfg, HooksCfg::isDisabled(), and HooksImpl::shellHookProc().
Variable Documentation
_hooksMgr
thread_local HooksMgr _hooksMgr
Definition at line 14 of file dllmain.cpp.
hhShellHookProc
thread_local HHOOK hhShellHookProc = NULL
Definition at line 15 of file dllmain.cpp.
hInstance
HINSTANCE hInstance = NULL
Definition at line 12 of file dllmain.cpp.